### PR TITLE
Fix issue #12146: add index to 'channel_id'

### LINKED ISSUE #12146: Missing INDEX makes report generation extremly slow (FIX included)
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

## Issue
If the `lead_donotcontact` table has a lot of entries (e.g. 60.000), the report-generation for `emails` becomes extremly (unusable) slow, if the bounced or unsubscribed columns are selected.

We tracked down the issue to the following sub-query, which is added e.g. when the `bounced` column is selected for an email report (same applies for `unsubcribed`):
```
IFNULL((SELECT ROUND(SUM(IF(dnc.id IS NOT NULL AND dnc.channel_id=e.id AND dnc.reason=2 , 1, 0)), 1) FROM lead_donotcontact dnc), 0)
```
While checking if all the fields inside the condition having an index, we found out that an index for `channel_id` is missing.

## Solution
To test it, we manually added the index, which increased the query speed for the email report by ~90%:
```
ALTER TABLE lead_donotcontact ADD INDEX dnc_channel_id_serch (channel_id);
```

As permanent solution, please add `->addIndex(['channel_id'], 'dnc_channel_id_search')` in the following line:
https://github.com/mautic/mautic/blob/d7a7c3e90afe8ee82e3f66585f8641d8b231fa60/app/bundles/LeadBundle/Entity/DoNotContact.php#L73

## Step 1
Take a huge Mautic database, e.g.:
leads: 1.500.000
lead_donotcontact: 60.000
emails: 200
email_stats: 3.500.000

## Step 2
- Create an email-report
- Add the following columns: `Read count, Read ratio, Clicks, Clicks ratio, Unique clicks, Unique clicks ratio`
- Add the following columns to slow down the query drastically: `bounced, unsubscribed`
- Add filter: `Sent count` greather than `100` (dynamic yes)

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/121828531-missing-index-makes-report-generation-extremly-slow-fix-included?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Moongazer**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ✅ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #12146 

#### Description:

Fix issue #12146: add index to 'channel_id' resolves timeout or extremely long loading time for email reports using this column.

Patch can and should be merged to v4.4 and v5.0.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for the PR @Moongazer - please make a duplicate PR for the 4.4 branch then we can get it out into the next patch release! I'll add it to the list for Open Source Friday.

Please also add the test instructions as this will ensure that folks are able to test and get the PR merged quickly! I will paste the template into your description for ease of adding it.

**Comment by Moongazer** [comment]
@RCheesley All right, here it is: https://github.com/mautic/mautic/pull/12187
Hope I was doing it right by creating a new branch from 4.4 and making the file changes again (still learning about how this collective process works with Git).

**Comment by RCheesley** [comment]
Looks perfect - will link it up to this one in the description so it's clear it's a companion PR! Hopefully we can get it tested this week all being well.

**Comment by escopecz** [comment]
Closing this. See https://github.com/mautic/mautic/pull/12187#issuecomment-1504948090 for details

**Pull request closed without merging**
