### PR TITLE
Revert "Change pre-commit hook to not allow a commit if there are err…

### PR DESCRIPTION
**Pull request by kuzmany**
…ors in php-cs-fixer."

This reverts commit 763d43aaf49723e09592705eab5adda4966af6db.

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

@biozshock PR added CS fix check before commit https://github.com/mautic/mautic/pull/13185/
But this check block merge feature in PHP Storm.
Can we find another way like this?

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
Let's revert if it causes issues

**Comment by kuzmany** [comment]
I found a workaround https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000395159-Disable-pre-commit-hooks-on-merge-commits but it's painful.

**Comment by kuzmany** [comment]
@mollux  could you please consider merging it? Today, it took me some time that I could have spent on something beneficial.

**Review by mollux — APPROVED** [review]

**Comment by mollux** [comment]
@kuzmany @biozshock I reverted this for now, but it still makes sense to get alike functionality in the pre commit hook IMO

Can you come up with a solution that is possible to run locally?

**Pull request merged**
