### PR TITLE
Fix day graph range

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
We noticed emails graphs is not correct.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Create email and send it by campaign action
3.  Go to detail of email make date range and see sent count is in graph is not from today, but from yesterday.
4. After PR should work properly

### CODE REVIEW

**Review by RCheesley — APPROVED** [review]
Thanks for the PR @kuzmany - it shows correctly in the campaign view:

screenshot-8080-mautic-mautic-l6xszxaidm8 ws-eu70 gitpod io-2022 10 07-13_15_28

However when you go into the individual email, indeed it seems to be showing the wrong date and the chart suggests it was sent the day previously:

screenshot-8080-mautic-mautic-l6xszxaidm8 ws-eu70 gitpod io-2022 10 07-13_15_56
 
Strangely it seems to have a clicked entry too (testing with Gitpod and did not actually open any of the emails) but that might be something to do with the sample data?

It is there as well when I check with this PR applied - saying it was clicked yesterday rather than today, and there are not any stats on clicks which seems a little strange.

screenshot-8080-mautic-mautic-1azoqqrnjz6 ws-eu70 gitpod io-2022 10 07-13_27_14

So the PR does fix what it claims to but I am a little confused by the click stats.

**Comment by kuzmany** [comment]
@RCheesley these click stats are there before  send email, then it's fixtures issue

image

**Comment by RCheesley** [comment]
> @RCheesley these click stats are there before send email, then it's fixtures issue

OK but the date it still incorrect on the chart (showing the day before), whereas it's fixed with the other line. Should that not also be fixed as well? Or do you mean that is a separate bug that needs to be fixed elsewhere? If so I'll create a separate issue.

**Comment by beetofly** [comment]
@kuzmany thank you for the fix. I tested it as described and it works fine:
Without your CodeFixes:
11544_TestEmail_without fix_day
And with your CodeFixes:
11544_TestEmail_with_fix_day

**Comment by RCheesley** [comment]
Thanks for helping to test @beetofly - marking this as ready to commit with a code review.

**Comment by RCheesley** [comment]
@all-contributors please add @beetofly for UserTesting

**Review by beetofly — APPROVED** [review]

**Review by volha-pivavarchyk — APPROVED** [review]
Works well for me too

**Review by mabumusa1 — APPROVED** [review]
I did a code review, it looks good

**Comment by RCheesley** [comment]
@kuzmany please make the PR against 5.x also - this is an older one so I think we haven't got the companion PR yet. Thanks!

**Pull request merged**
