### PR TITLE
Fix unicode char in from name

### LINKED ISSUE #9433: Unicode Characters in From Address Is Invalid in SES API
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.1.2-rc
| PHP version | 
| Browser | 

### Steps to reproduce
1. Send an email 
2. In the from field add unicode characters.
3. Below example of wrong text showing
 
image

Issue and solution was proposed by @benfavre

### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | yes
| Automated tests included?              | yes
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #9433

#### Steps to test this PR:
1. Send an email 
2. In the from field add unicode characters.
3. Below an example of wrong text showing
4. Apply the PR then send the same email you should find "From" address working as expected
 
Before applying the PR
image

After applying the PR
image

Issue and solution was proposed by @benfavre

### CODE REVIEW

**Comment by mabumusa1** [comment]
@benfavre please test this PR, it uses your code

**Comment by r-martins** [comment]
I was able to confirm the change worked in Mautic 3.2.2.
Thanks for the fix @mabumusa1.
_TEST__Sua_Chave_PagSeguro_PRO_-_mart_ricardo_gmail_com_-_Gmail

**Review by r-martins — DISMISSED** [review]
I was able to confirm the change worked in Mautic 3.2.2.
Thanks for the fix @mabumusa1.
_TEST__Sua_Chave_PagSeguro_PRO_-_mart_ricardo_gmail_com_-_Gmail

**Comment by campiotto** [comment]
This solution did not work for me.
I'm using 3.2.2, after changing line 384, clearing the cache and trying to send a test email the problem persists.

**Comment by r-martins** [comment]
> This solution did not work for me.
> I'm using 3.2.2, after changing line 384, clearing the cache and trying to send a test email the problem persists.

@campiotto are you using Amazon SES with the API mode to send e-mails? (dumb question, but pre-requisite for this test)
Configuration___Mautic

**Comment by campiotto** [comment]
> > This solution did not work for me.
> > I'm using 3.2.2, after changing line 384, clearing the cache and trying to send a test email the problem persists.
> 
> @campiotto are you using Amazon SES with the API mode to send e-mails? (dumb question, but pre-requisite for this test)
> Configuration___Mautic

Hi @r-martins, yes I'm using it with the SES API.

**Comment by Dador** [comment]
Currently fix doesn't work if you use "Queue" instead of "Send immediately" ("How should email be handled?" in "Email settings").

It can be fixed by additionally changing https://github.com/mautic/mautic/blob/e804468c8d05454fb3f020006f3ff0ad8c46f71a/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonApiTransport.php#L341
to:
```PHP
$sesArray['FromEmailAddress'] =  (!empty($fromName)) ? mb_encode_mimeheader($fromName).' <'.$fromEmail.'>' : $fromEmail;
```

**Comment by campiotto** [comment]
> Currently fix doesn't work if you use "Queue" instead of "Send immediately" ("How should email be handled?" in "Email settings").
> 
> It can be fixed by additionally changing
> 
> https://github.com/mautic/mautic/blob/e804468c8d05454fb3f020006f3ff0ad8c46f71a/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonApiTransport.php#L341
> 
> 
> to:
> ```
> $sesArray['FromEmailAddress'] =  (!empty($fromName)) ? mb_encode_mimeheader($fromName).' <'.$fromEmail.'>' : $fromEmail;
> ```

Perfect, this worked for me. Thank you Dador.

**Comment by mabumusa1** [comment]
@campiotto @Dador The line of code you are sharing is the same change of the code provided by this PR, please review this PR so it gets approved and merged in the next release of Mautic.

You can review this PR by clicking on the review link to the top right of this page.

Thanks

**Comment by npracht** [comment]
@mabumusa1 can you rebase against 3.2 branch ? Then we can merge it :)

**Comment by Dador** [comment]
@mabumusa1 it seems like a same change, but actually it's a bit different. This PR adds mb_encode_mimeheader only to line 384, which covers the case when emails are send immediately.
https://github.com/mautic/mautic/blob/7399476ea7df4c1f747ee045ef71f59599ac120c/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonApiTransport.php#L384
But to cover the case when emails are send via queue, mb_encode_mimeheader also has to be added to the line 341
https://github.com/mautic/mautic/blob/7399476ea7df4c1f747ee045ef71f59599ac120c/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonApiTransport.php#L341

I actually tested it before writing and second change is required to fix unicode in emails that're send via queue.

**Comment by mabumusa1** [comment]
> @mabumusa1 it seems like a same change, but actually it's a bit different. This PR adds mb_encode_mimeheader only to line 384, which covers the case when emails are send immediately.
> https://github.com/mautic/mautic/blob/7399476ea7df4c1f747ee045ef71f59599ac120c/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonApiTransport.php#L384
> 
> 
> But to cover the case when emails are send via queue, mb_encode_mimeheader also has to be added to the line 341
> https://github.com/mautic/mautic/blob/7399476ea7df4c1f747ee045ef71f59599ac120c/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonApiTransport.php#L341
> 
> I actually tested it before writing and second change is required to fix unicode in emails that're send via queue.

@Dador thanks for pointing this out, I fixed this issue. Thank you for your review

**Comment by mabumusa1** [comment]
@npracht I think this is ready to be merged

**Comment by mabumusa1** [comment]
@Dador please review the code so we can merge this PR. thanks

**Comment by dsp76** [comment]
@mabumusa1  I tried to patch 3.2.5 with it. However, the patch failed several with the mentioned version.
(I tried the .diff with git apply -v, maybe thats the wrong way to do it?)

**Comment by mabumusa1** [comment]
> @mabumusa1 I tried to patch 3.2.5 with it. However, the patch failed several with the mentioned version.
> (I tried the .diff with git apply -v, maybe thats the wrong way to do it?)

Try now, I rebased the code to reflect the latest changes in the features branch

**Review by Dador — APPROVED** [review]
Looks good to me.
Tested it. It does fixes the issue.

**Comment by Dador** [comment]
> @Dador please review the code so we can merge this PR. thanks

@mabumusa1, I did it, but not sure if it's helpful as I don't have write access to this repo.

**Pull request merged**
