### PR TITLE
Add tags to filters by default

### LINKED ISSUE #9904: V3 Feature regression: "Tags" filter missing on Dynamic Web Content [$65 awarded]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Mautic V2 allowed Tags to be used as a filter type for dynamic web content. This filter type is missing in Mautic V3.

| Q   | A
| --- | ---
| Mautic version | 3.2.5
| PHP version | 7.4
| Browser | N/A

### Steps to reproduce
1. Create new Dynamic Web Content (not campaign based)
2. On the filters tab, attempt to add a tags filter type

### Dropdown in 2.16
image

### Dropdown in 3.2.5
image

<bountysource-plugin>

---
The **[$65 bounty](https://app.bountysource.com/issues/97908768-v3-feature-regression-tags-filter-missing-on-dynamic-web-content?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** on this issue has been claimed at [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #9951: Forms are not able to submit
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Forms are not able to submit in preview or everywhere. 

image

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | features
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | Fixes #9904

#### Description:
This is fix for https://github.com/mautic/mautic/issues/9904
Tags are in filters by default

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create dynamics content  without Campaign based flag
3. Try use tags filter

### CODE REVIEW

**Review by RCheesley — CHANGES_REQUESTED** [review]
Confirm that the tags filter is missing, after applying the PR it was there but throws an error when I try to save:

screenshot-mautic4 ddev site-2021 05 23-16_21_11

**Comment by kuzmany** [comment]
@RCheesley thanks. Fixed

**Comment by stevedrobinson** [comment]
@kuzmany Thank you for working on it. It almost works, but displays a list of IDs instead of tags to select:
image

**Comment by stevedrobinson** [comment]
@kuzmany anything else I can do to help get this finished off?

**Comment by npracht** [comment]
@stevedrobinson if you want to check why it displays ID instead of tags ? Obvisouly it's related to last commit https://github.com/mautic/mautic/pull/10067/commits/eef04353e1398bfb456f4e496b7b07a81a6491c5 that wanted to fix issue reprorted by Ruth.

**Comment by stevedrobinson** [comment]
@npracht @kuzmany  I spent a couple of hours on this and got nowhere. 

Kuzmany's last commit seems right but some other bug somewhere is causing the dropdown to render the values instead of the labels, but only the first time you select a tag after adding a tags filter, and only before you select the first value. Once you select a value, it magically starts showing the labels, as it should. If you edit existing filters, it shows the labels correctly. The only way to reproduce the bug is immediately after adding a new tags filter.

Sorry, I'm afraid I don't understand enough about how Mautic renders its UI to figure this out.

**Comment by kuzmany** [comment]
@stevedrobinson can you record video how to reproduce it? I've tried a lot of combinations, and never happend that for me.

**Comment by stevedrobinson** [comment]
@kuzmany Here you go: http://www.youtube.com/watch?v=xUjajIy6ebo

Thank you.

**Comment by kuzmany** [comment]
@stevedrobinson please double check these lines https://github.com/mautic/mautic/pull/10067/files#diff-5681f5256ca46b41bc84b7c395153259e20e7b612b71f31260960d34049435f8R86
If you patch correctly.
Because on my side it works.

@RCheesley can you check the video and re-tests?

**Comment by stevedrobinson** [comment]
@kuzmany I verified the patch was in place, and even downloaded a fresh zip of 3.3.3 and reapplied the diff and I still get the behavior in the above video.

**Review by RCheesley — APPROVED** [review]
Worked great for me - tags are available and I was able to correctly select them.

This was using the latest Features branch (Mautic 4).

screenshot-mautic4 ddev site-2021 06 24-20_37_32

**Review by npracht — APPROVED** [review]
Just tested this fix and it works as expected. Tags are usable and I see values, not IDs :)
🚀

**Pull request merged**
