### PR TITLE
Features/aws: Continue #5263

### PR DESCRIPTION
**Pull request by chocopowwwa**
Continuing https://github.com/mautic/mautic/pull/5263, from my perspective, the problem only typehint and custom exception, since no body want to work on it, i guess give a shot on it. Yes the branch is stil conflicting,
Thank you.

### CODE REVIEW

**Comment by davidbnk** [comment]
@chocopowwwa Is this PR fully working? Is it ok to use in production? We are currently struggling with mautic send speed. We have about 400k contants and it takes more than 12 hours to send an email to all contacts. This is already with a local postfix installation to speed things up.

**Comment by davidbnk** [comment]
While testing this branch I was getting two errors:
```
[2018-06-19 19:57:07] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "getAttachments" of class "Swift_Message"." at /var/www/html/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php line 205 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"getAttachments\" of class \"Swift_Message\". at /var/www/html/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php:205)"} []
```

```
[2018-06-19 21:42:25] mautic.NOTICE: Swift_TransportException: The subject must be specified. (uncaught exception) at /var/www/html/app/bundles/EmailBundle/Swiftmailer/Transport/AbstractTokenArrayTransport.php line 283 while running console command `mautic:emails:send` [] []
```

Anyone got this branch working that could provide some tips?

**Comment by AlbanL74fr** [comment]
Hi, is this work still in progress? I experience very slow email delivery with SES by SMTP. I wonder if this could help me (and others).

**Comment by idealaunchtech** [comment]
I've taken the work from this PR and extracted it to a new mailer transport, leaving the original AWS smtp mailer as-is. New PR at #6977 .

**Comment by RCheesley** [comment]
Hi folks, I just wanted to say a big thank you for your work on this PR all the way back in 2018. We finally are getting it merged into Mautic 3.1!

Your work is very much appreciated! 🎉

**Pull request closed without merging**
