### PR TITLE
Send email to user, owner or any email address as a campaign event

### PR DESCRIPTION
**Pull request by escopecz**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/207
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/437, partly https://github.com/mautic/mautic/issues/2433, https://github.com/mautic/mautic/issues/124
| BC breaks? | N (some translation strings moved around)
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR will allow to send email to user, contact's owner or any To, Cc, Bcc email addresses as a campaign action.

The email tokens will get populated with the real values including contact field values. But the email hash is bogus so the links like unsubscribe won't work correctly. It's similar behaviour like when a user sends itself a test email.

#### Steps to test this PR:
1. Apply this PR
2. Clear the Mautic cache
3. Create a new campaign with your testing segment and "Send email" and "Send Email to User" actions. Test different configurations of the "Send Email to User" action.
4. Execute the `app/console mautic:campaigns:update` and `app/console mautic:campaigns:trigger` commands.
5. Check your inbox and see if you received the emails you'd expect based on the events config.
6. Make sure the form action "send results" still works since there were changes in it too.
7. Run the new tests: `phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml --filter CampaignSubscriberTest`

### CODE REVIEW

**Comment by mqueme** [comment]
The send email to user action didn't send anything.

**Comment by escopecz** [comment]
@mqueme could you debug further on your instance? It's sending emails for me and Werner.

**Comment by mqueme** [comment]
```
request.INFO: Matched route "mautic_email_tracker". {"route_parameters":{"_controller":"Mautic\\EmailBundle\\Controller\\PublicController::trackingImageAction","idHash":"599c262637ce0","_route":"mautic_email_tracker"},"request_uri":"http://www.mqueme.com/mautic/email/599c262637ce0.gif"} []
[2017-08-22 12:41:09] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
```

**Comment by mqueme** [comment]
this worked

**Comment by dongilbert** [comment]
The campaign details screen is missing a translation for `mautic.campaign.email.send.to.user`. Other than that, it worked as expected.

**Comment by dongilbert** [comment]
Added the missing translation string. +1

**Comment by dichvuhuuich** [comment]
@escopecz I don't see this PR link, could you provide again?

I think this feature is must have. Is there this feature added to Mautic?

**Comment by escopecz** [comment]
@dichvuhuuich I don't understand what PR link you mean. A URL to this page?

If you look into the right hand side column, it has milestone 2.10.0 assigned. It means this PR was released as part of Mautic 2.10.0.

**Comment by dichvuhuuich** [comment]
> @dichvuhuuich I don't understand what PR link you mean. A URL to this page?
> 
> If you look into the right hand side column, it has milestone 2.10.0 assigned. It means this PR was released as part of Mautic 2.10.0.
Thank you, I'm going to this from the issue
https://github.com/mautic/mautic/pull/4254. I only want use Email token field in action Send email to user of Campaign like this in picture.
image

Because this email token filed is variable. Is there any way to do this?

**Comment by escopecz** [comment]
It doesn't look like it is. But Mautic has a feature called Contact Onwers. You can see the switch on your screenshot called "Send email to contact's owner". If you'd use contact owners (which are Mautic users) and turn the switch to Yes then it should do what you need.

**Comment by dichvuhuuich** [comment]
> It doesn't look like it is. But Mautic has a feature called Contact Onwers. You can see the switch on your screenshot called "Send email to contact's owner". If you'd use contact owners (which are Mautic users) and turn the switch to Yes then it should do what you need.

I know this feature but this email is variable, so I have to add new email field in contact information. I want to a feature like this topic: https://forum.mautic.org/t/campaign-action-send-email-to-user/

**Comment by escopecz** [comment]
Ok. That feature is not built yet AFAIK.

**Comment by dichvuhuuich** [comment]
> Ok. That feature is not built yet AFAIK.

Is there anyway to use a part of code from this feature request https://github.com/mautic/mautic/pull/4254 to make email token can use? Thank you!

**Pull request merged**
