### PR TITLE
Notification message to include the reason

### LINKED ISSUE #14105: Notification | Import failed. Reason: %reason%
### Mautic Series

5.1.x series

### Mautic installed version

5.1.0

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.2.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

I am battling to use any bulk import functionality with 5.1.0. 

Related issues are: [https://github.com/mautic/mautic/issues/14106](https://github.com/mautic/mautic/issues/14106)

However, this error comes up after a failed import which does not look to be working correctly:

image

There is no description pulled into the %reason% placeholder. 

See relevant log output. 

### How can we reproduce this issue?

1. Upload .csv
2. Map fields
3. Select either import in browser or in background, both fail
4. Get error in logs, front end does not update:
image
5. Error notification appears:
image

### Relevant log output

```shell
ubuntu@xxxxxxxx:/var/www/mautic/mautic/var/logs$ tail -f mautic_prod-2024-09-11.php
[2024-09-11T06:17:19.259215+00:00] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORME                                                        xception: "An exception occurred while executing a query: SQLSTATE[22001]: String data, righ                                                        t truncated: 1406 Data too long for column 'companyname' at row 1" at /var/www/mautic/mautic                                                        /app/bundles/LeadBundle/Model/ImportModel.php line 340 {"exception":"[object] (Doctrine\\ORM                                                        \\ORMException(code: 0): An exception occurred while executing a query: SQLSTATE[22001]: Str                                                        ing data, right truncated: 1406 Data too long for column 'companyname' at row 1 at /var/www/                                                        mautic/mautic/app/bundles/LeadBundle/Model/ImportModel.php:340)"} {"hostname":"xxxxxxxx","pid":201380}
[2024-09-11T06:18:19.887450+00:00] mautic.WARNING: Command `mautic:import` exited with statu                                                        s code 1 [] {"hostname":"xxxxxxxx","pid":201560}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by shinde-rahul**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #14105 

## Description

Please see #14105 

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create multiple imports, out of which a minimum of two should be in In-Progress status
3.  Execute the `bin/console mautic:import` and see the notification area.

PS. Creating import with In-Progress status is a challenge via UI.

### CODE REVIEW

**Review by kuzmany — APPROVED** [review]
Good catch 👍

**Comment by matbcvo** [comment]
@shinde-rahul Please rebase your PR onto the 5.2 branch.

**Comment by shinde-rahul** [comment]
I have updated PR, changing the base to `5.2`. 

Thanks, @matbcvo, for the nudge.

**Review by matbcvo — APPROVED** [review]
The code changes look good to me. I have tested the PR.

image

**Pull request merged**
