### PR TITLE
Disabled send button from list If sending in background

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This is follow up for already merged PR https://github.com/mautic/mautic/pull/11351
We forgot disable send button from email list view. This PR added it there 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Setup Publish UP of segment email date lower like now
3. Go to emails page and see send button is disabled with tooltip message for that email 

image

### CODE REVIEW

**Review by mabumusa1 — DISMISSED** [review]
I reviewed this PR, and it looks good.

**Comment by escopecz** [comment]
@kuzmany the `app/bundles/EmailBundle/Views/Email/list.html.php` file has been removed with the Twig refactoring. Could you please update on top of the latest 5.x branch and copy the changes into `app/bundles/EmailBundle/Views/Email/list.html.twig`?

**Comment by kuzmany** [comment]
@escopecz resolved. Ready to test

**Review by volha-pivavarchyk — APPROVED** [review]
Works as described

**Pull request merged**
