### PR TITLE
Fixture landing pages emails

### LINKED ISSUE #11471: Landings pages and emails created via the fixtures are broken
### Mautic Version

4.3.x series

### PHP version

7.4.29

### What browsers are you seeing the problem on?

Not relevant

### What happened?

In the Doctrine fixtures, 2 emails and 1 landingspage is created. Unfortunately, their data still relies on the old builder. Possibly very old builder, as even disabling GrapesJS does not fix this.

When editing these pages or emails, clicking "build" brings up the old builder UI but it is entirely broken. The console is full of errors.

I suggest updating the csv files to create this content using the new structure.

### How can we reproduce this issue?

Step 1: Install Mautic
Step 2: Run `bin/console doctrine:fixtures:load`
Step 3: Attempt to launch the builder for any of the created emails or page

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/121828560-landings-pages-and-emails-created-via-the-fixtures-are-broken?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by shinde-rahul**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #11471  

#### Description:

In the Doctrine fixtures, 2 emails and 1 landing page are created. Unfortunately, their data still relies on the old builder. Possibly a very old builder, as even disabling GrapesJS still needs to fix this.

When editing these pages or emails, clicking "build" brings up the old builder UI but is entirely broken. The console is full of errors.

I suggest updating the CSV files to create this content using the new structure.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Run bin/console `doctrine:fixtures:load`
3. Attempt to launch the builder for any of the created emails or page

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/12478"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
@shinde-rahul could you please improve the description so everyone knows what is this fixing? Is this improving the fixtures for the legacy builder or GrapesJS?

**Comment by shinde-rahul** [comment]
@escopecz, done!

**Comment by escopecz** [comment]
Thanks! It seems that it broke some tests. Take a look, please

**Comment by shinde-rahul** [comment]
@escopecz, how to re-run the checks? It seems the error is not related to the changes.

**Comment by escopecz** [comment]
Closing and opening does the trick

**Comment by RCheesley** [comment]
@shinde-rahul this one needs a rebase to 4.4 and will need a companion PR for the 5.x branch please. Thank you!

**Comment by RCheesley** [comment]
@shinde-rahul I'm going to close this down as it's very outdated now. Please feel free to re-create it on the 5.x branch if you want to take it forward (or rebase here and we can re-open).

**Pull request closed without merging**
