### PR TITLE
Removed code no longer needed when saving SAML XML files

### PR DESCRIPTION
**Pull request by alanhartless**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This removes the code from https://github.com/mautic/mautic/pull/7305 that became obsolete with M3's changes to the SAML code. https://github.com/mautic/mautic/pull/8265

[//]: # ( As applicable: )
#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Upload an XML file (even if fake) through the Identity Provider Metadata file under User/Authentication tab of the configuration and save the Configuration.

### CODE REVIEW

**Comment by dennisameling** [comment]
Seems to be fixing the same that was fixed in https://github.com/mautic/mautic/pull/7305, but with less code than https://github.com/mautic/mautic/pull/7305. 

This PR also updates LightSAML so we could consider reverting #7305 and merging this PR instead.

**Comment by npracht** [comment]
Hi @alanhartless do you think we should try to merge that in M2 following the Dennis suggestion?
>Seems to be fixing the same that was fixed in #7305, but with less code than #7305.
>
>This PR also updates LightSAML so we could consider reverting #7305 and merging this PR instead.
>
>@alanhartless would you mind rebasing this PR from the staging branch? There's a conflict with composer.lock. Thanks!

**Comment by alanhartless** [comment]
@npracht @dennisameling I rebased and reverted the controller changes.

**Comment by npracht** [comment]
@alanhartless should we target M2 or M3 with this ?

**Comment by RCheesley** [comment]
@alanhartless some conflicts to be resolved here so removing from the milestone for 3.0.1

**Comment by RCheesley** [comment]
@alanhartless if you can address the conflicts that would be awesome - can you also maybe check to see if this addresses the bug reported in #7836 at the same time? Many thanks!

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
As this is a bit more complex and has outstanding conflicts / hasn't been tested, I'm pushing this to 3.2.

**Comment by alanhartless** [comment]
Conflicts resolved

**Review by kuzmany — DISMISSED** [review]
Make sense 👍

**Pull request merged**
