### PR TITLE
Schedule campaign events at an hour relative to the contact's timezone

### PR DESCRIPTION
**Pull request by alanhartless**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | y
| Automated tests included? |y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR fixes a bug where campaign events were executed regardless of the campaign's published state.

It also adds a feature to schedule a campaign event to be executed based on a relative hour to the contact's timezone or the system configuration if none. (There was a bug where new installations did not add timezone as a custom field so this has been fixed as well.) The event can be scheduled at a specific hour, between hours, and/or specific days of the week. 

It is includes https://github.com/mautic/mautic/pull/6482 due to conflicts so please merge it first. 

[//]: # ( As applicable: )

#### Steps to reproduce the bug:
1. Create a new Campaign
2. Setup Action to Send Email "at a relative time period" 5 minutes later
3. Edit the campaign and set unpublish at date/time in the past
4. Look at the database `campaign_lead_event_log` table and find the scheduled log entry for the contact and note the id
5. Execute the command `mautic:campaigns:execute --scheduled-log-ids=ID`; replace the ID with the one noted in step 4
6. Note that the event executes even though the campaign is supposed to be unpublished

#### Steps to test this PR:
1. Repeat and the event will not execute rather a log entry will note that it failed due to the campaign being unpublished (to prevent never ending attempts)

#### Steps to test this PR:
1. Create a new campaign
2. Add an action and schedule it with a relative time
3. Notice that if minute or hour interval unit is chosen, the custom hour/DOW fields disappear. 
4. Choose 1 day and set a specific time
5. Create a contact and set the contact's timezone
6. Create a second contact and set a different timezone
7. Create a third contact and leave timezone empty
8. Add all three to the campaign and execute via the command
9. Check their timelines and the actions should be scheduled at the hour relative to their timezone. The 3rd will be scheduled based on the system default timezone.
10. Edit the campaign and remove the hour (leave it blank)
11. Add a fourth contact through the campaign, execute the command, then note that the action should be scheduled exactly 24 hours in the future
12. Wait a day, execute the command, and then make sure the actions execute and are not rescheduled

### CODE REVIEW

**Comment by mleffler** [comment]
Tested once and code reviewed, looks like there are conflicts @alanhartless

**Comment by npracht** [comment]
@alanhartless do you think you can finish the work soon or should we postpone it to 2.15.0?
Thanks ç

**Comment by alanhartless** [comment]
The feature is done and conflicts resolved.

**Comment by npracht** [comment]
Great !! That seems exciting :)

**Comment by escopecz** [comment]
@alanhartless I'm stuck on

> 3. Notice that if minute or hour interval unit is chosen, the @ hour is disabled

It doesn't disable the field, but hides all new options. 

### This is how it looks like for day:
screen shot 2018-10-14 at 21 01 51



### And this is how it looks for hour:
screen shot 2018-10-14 at 21 02 01

**Comment by alanhartless** [comment]
That's correct behavior with the addition of the new schedule options. Will update testing instructions.

--

Alan

**Comment by escopecz** [comment]
@alanhartless I don't see any timezone related changes in the scheduled tasks:
linhartescope contact1190 gmail com mautic
agivu mautic
jenik kubalik mautic


Although maybe the problem is in the step

> Choose 1 day and set a specific time

Do you mean the "at a specific date/time" tab or fill in the "Schedule at" field in the "at relative time period" tab?

**Comment by escopecz** [comment]
Ok, that was it. I misunderstood that step as it's similar to what the next tab called. If I fill in the "Scheduled at" field then the timezones are working.

**Comment by alanhartless** [comment]
Under the "at relative time period"

**Pull request merged**
