### PR TITLE
fix: [DPMMA-2252] point groups migration fix

### LINKED ISSUE #12993: Unable to pass DB migrations: Table 'point_groups' already exists
### Mautic Version

5.0.x series

### PHP version

8.1.26

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Unable to pass DB migrations

### How can we reproduce this issue?

Step 1: php bin/console doctrine:migration:migrate

### Relevant log output

```shell
root@ma:/var/www/html/mautic# php bin/console doctrine:migration:migrate

 WARNING! You are about to execute a migration in database "uhlmautic" that could result in schema changes and data loss. Are you sure you wish to continue? (yes/no) [yes]:
 > yes

[notice] Migrating up to Mautic\Migrations\Version20230627140512
[notice] Table contact_export_scheduler already exists
[notice] Migration Mautic\Migrations\Version20220429091934 skipped during Pre-Checks. Reason: "Schema includes this migration"
[notice] Migration Mautic\Migrations\Version20220722074516 skipped during Pre-Checks. Reason: "The deduplicate column has already been added to the notifications table."
[notice] Migration Mautic\Migrations\Version20221014061125 skipped during Pre-Checks. Reason: "Index webhook_id_date_added already exists"
[notice] Migration Mautic\Migrations\Version20221014081742 skipped during Pre-Checks. Reason: "Schema includes this migration"
[notice] Migration Mautic\Migrations\Version20221128145933 skipped during Pre-Checks. Reason: "Schema includes this migration"
[notice] Migration Mautic\Migrations\Version20230131133732 skipped during Pre-Checks. Reason: "The last_built_time column has already been added to the lead_lists table."
[notice] Column asset_downloads.utm_campaign already exists
[notice] Column asset_downloads.utm_content already exists
[notice] Column asset_downloads.utm_medium already exists
[notice] Column asset_downloads.utm_source already exists
[notice] Column asset_downloads.utm_term already exists
[notice] Migration Mautic\Migrations\Version20230321133733 skipped during Pre-Checks. Reason: "Schema includes this migration"
[notice] Table plugin_crm_pipedrive_owners was already removed
[notice] Migration Mautic\Migrations\Version20230519154448 skipped during Pre-Checks. Reason: "Schema includes this migration"
[notice] Migration is not required.
[notice] Migration Mautic\Migrations\Version20230606111852 skipped during Pre-Checks. Reason: "Schema includes this migration"
[notice] Table point_groups already exists
[notice] Table point_group_contact_score already exists
[notice] Column points.group_id already exists
[notice] Column point_triggers.group_id already exists
[notice] Column lead_points_change_log.group_id already exists
[error] Migration Mautic\Migrations\Version20230621074925 failed during Execution. Error: "An exception occurred while executing a query: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'point_groups' already exists"

In ExceptionConverter.php line 45:
                                                                                                                                               
  An exception occurred while executing a query: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'point_groups' already exists  
                                                                                                                                               

In Exception.php line 28:
                                                                                                
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'point_groups' already exists  
                                                                                                

In Connection.php line 71:
                                                                                                
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'point_groups' already exists  
                                                                                                

doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]

root@ma:/var/www/html/mautic#
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ Y ]
| New feature/enhancement? (use the a.x branch)      | [ N ]
| Deprecations?                          | [ N ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #12993 

#### Description:
This PR fixes the issue with point groups migration

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Run `ddev exec php bin/console doctrine:migrations:migrate`

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
Nice catch! I firstly removed the schema changes added by this migration:
```
jan@mautic-web:/var/www/html$ php bin/console doctrine:migrations:execute 'Mautic\Migrations\Version20230621074925' --down -vvv

 WARNING! You are about to execute a migration in database "db2" that could result in schema changes and data loss. Are you sure you wish to continue? (yes/no) [yes]:
 > 

[notice] Executing Mautic\Migrations\Version20230621074925 down
[info] ++ reverting Mautic\Migrations\Version20230621074925
[debug] ALTER TABLE `point_group_contact_score` DROP FOREIGN KEY `FK_9D85A703E7A1254A` 
[debug] ALTER TABLE `point_group_contact_score` DROP FOREIGN KEY `FK_9D85A703FE54D947` 
[debug] ALTER TABLE `points` DROP FOREIGN KEY `FK_27BA8E29FE54D947` 
[debug] ALTER TABLE `point_triggers` DROP FOREIGN KEY `FK_9CABD32FFE54D947` 
[debug] ALTER TABLE `lead_points_change_log` DROP FOREIGN KEY `FK_949C2CCCFE54D947` 
[debug] ALTER TABLE `points` DROP group_id 
[debug] ALTER TABLE `point_triggers` DROP group_id 
[debug] ALTER TABLE `lead_points_change_log` DROP group_id 
[debug] DROP TABLE point_group_contact_score 
[debug] DROP TABLE point_groups 
[info] Migration Mautic\Migrations\Version20230621074925 reverted (took 118.2ms, used 22M memory)
[notice] finished in 128.5ms, used 22M memory, 1 migrations executed, 10 sql queries
```
And then applied again:
```
jan@mautic-web:/var/www/html$ php bin/console doctrine:migrations:execute 'Mautic\Migrations\Version20230621074925' --up -vvv

 WARNING! You are about to execute a migration in database "db2" that could result in schema changes and data loss. Are you sure you wish to continue? (yes/no) [yes]:
 > 

[notice] Executing Mautic\Migrations\Version20230621074925 up
[info] ++ migrating Mautic\Migrations\Version20230621074925
[debug] CREATE TABLE `point_groups`
(
    `id`                  INT UNSIGNED AUTO_INCREMENT NOT NULL,
    `is_published`        TINYINT(1)                  NOT NULL,
    `date_added`          DATETIME     DEFAULT NULL,
    `created_by`          INT          DEFAULT NULL,
    `created_by_user`     VARCHAR(191) DEFAULT NULL,
    `date_modified`       DATETIME     DEFAULT NULL,
    `modified_by`         INT          DEFAULT NULL,
    `modified_by_user`    VARCHAR(191) DEFAULT NULL,
    `checked_out`         DATETIME     DEFAULT NULL,
    `checked_out_by`      INT          DEFAULT NULL,
    `checked_out_by_user` VARCHAR(191) DEFAULT NULL,
    `name`                VARCHAR(191)                NOT NULL,
    `description`         LONGTEXT     DEFAULT NULL,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4
  COLLATE `utf8mb4_unicode_ci`
  ENGINE = InnoDB
  ROW_FORMAT = DYNAMIC; 
[debug] CREATE TABLE `point_group_contact_score`
(
    `contact_id`          BIGINT UNSIGNED NOT NULL,
    `group_id`           INT UNSIGNED    NOT NULL,
    `score`               INT             NOT NULL,
    PRIMARY KEY (`contact_id`, `group_id`)
) DEFAULT CHARACTER SET utf8mb4
  COLLATE `utf8mb4_unicode_ci`
  ENGINE = InnoDB
  ROW_FORMAT = DYNAMIC; 
[debug] ALTER TABLE `points` ADD group_id INT UNSIGNED DEFAULT NULL 
[debug] ALTER TABLE `point_triggers` ADD group_id INT UNSIGNED DEFAULT NULL 
[debug] ALTER TABLE `lead_points_change_log` ADD group_id INT UNSIGNED DEFAULT NULL 
[debug] ALTER TABLE `point_group_contact_score` ADD CONSTRAINT `FK_9D85A703E7A1254A` FOREIGN KEY (`contact_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE 
[debug] ALTER TABLE `point_group_contact_score` ADD CONSTRAINT `FK_9D85A703FE54D947` FOREIGN KEY (`group_id`) REFERENCES `point_groups` (`id`) ON DELETE CASCADE 
[debug] ALTER TABLE `points` ADD CONSTRAINT `FK_27BA8E29FE54D947` FOREIGN KEY (`group_id`) REFERENCES `point_groups` (`id`) ON DELETE CASCADE 
[debug] ALTER TABLE `point_triggers` ADD CONSTRAINT `FK_9CABD32FFE54D947` FOREIGN KEY (`group_id`) REFERENCES `point_groups` (`id`) ON DELETE CASCADE 
[debug] ALTER TABLE `lead_points_change_log` ADD CONSTRAINT `FK_949C2CCCFE54D947` FOREIGN KEY (`group_id`) REFERENCES `point_groups` (`id`) ON DELETE CASCADE 
[info] Migration Mautic\Migrations\Version20230621074925 migrated (took 199.5ms, used 26M memory)
[notice] finished in 209.1ms, used 26M memory, 1 migrations executed, 10 sql queries
```
There were no errors, everything was smooth 👍  Thank you!

**Comment by minchaminder** [comment]
Is there any fix for the meantime ?

**Comment by saschafoerster** [comment]
First try: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_72243719E7A1254A
Second try:  [PDOException (42S01)]                                                                            
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'mau_point_groups' already exists  


```
user@server:/var/www/html/mautic# php bin/console doctrine:migrations:execute 'Mautic\Migrations\Version20230621074925' --down -vvv

 WARNING! You are about to execute a migration in database "mautic_base" that could result in schema changes and data loss. Are you sure you wish to continue? (yes/no) [yes]:
 > yes

[notice] Executing Mautic\Migrations\Version20230621074925 down
[info] ++ reverting Mautic\Migrations\Version20230621074925
[debug] ALTER TABLE `mau_point_group_contact_score` DROP FOREIGN KEY `FK_72243719E7A1254A` 
[error] Migration Mautic\Migrations\Version20230621074925 failed during Execution. Error: "An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_72243719E7A1254A`; check that it exists"

In ExceptionConverter.php line 117:
                                                                                                                                                                    
  [Doctrine\DBAL\Exception\DriverException (1091)]                                                                                                                  
  An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_72243719E7A1254A`; check that   
  it exists                                                                                                                                                         
                                                                                                                                                                    

Exception trace:
  at /var/www/html/mautic/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:117
 Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() at /var/www/html/mautic/vendor/doctrine/dbal/src/Connection.php:1938
 Doctrine\DBAL\Connection->handleDriverException() at /var/www/html/mautic/vendor/doctrine/dbal/src/Connection.php:1880
 Doctrine\DBAL\Connection->convertExceptionDuringQuery() at /var/www/html/mautic/vendor/doctrine/dbal/src/Connection.php:1105
 Doctrine\DBAL\Connection->executeQuery() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:273
 Doctrine\Migrations\Version\DbalExecutor->executeResult() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:150
 Doctrine\Migrations\Version\DbalExecutor->executeMigration() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:73
 Doctrine\Migrations\Version\DbalExecutor->execute() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:88
 Doctrine\Migrations\DbalMigrator->executePlan() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:54
 Doctrine\Migrations\DbalMigrator->executeMigrations() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:136
 Doctrine\Migrations\DbalMigrator->migrate() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/ExecuteCommand.php:157
 Doctrine\Migrations\Tools\Console\Command\ExecuteCommand->execute() at /var/www/html/mautic/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /var/www/html/mautic/vendor/symfony/console/Application.php:1058
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/mautic/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/mautic/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /var/www/html/mautic/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/mautic/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /var/www/html/mautic/bin/console:16

In Exception.php line 28:
                                                                                                                              
  [Doctrine\DBAL\Driver\PDO\Exception (1091)]                                                                                 
  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_72243719E7A1254A`; check that it exists  
                                                                                                                              

Exception trace:
  at /var/www/html/mautic/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28
 Doctrine\DBAL\Driver\PDO\Exception::new() at /var/www/html/mautic/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:76
 Doctrine\DBAL\Driver\PDO\Connection->query() at /var/www/html/mautic/vendor/doctrine/dbal/src/Connection.php:1100
 Doctrine\DBAL\Connection->executeQuery() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:273
 Doctrine\Migrations\Version\DbalExecutor->executeResult() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:150
 Doctrine\Migrations\Version\DbalExecutor->executeMigration() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:73
 Doctrine\Migrations\Version\DbalExecutor->execute() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:88
 Doctrine\Migrations\DbalMigrator->executePlan() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:54
 Doctrine\Migrations\DbalMigrator->executeMigrations() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:136
 Doctrine\Migrations\DbalMigrator->migrate() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/ExecuteCommand.php:157
 Doctrine\Migrations\Tools\Console\Command\ExecuteCommand->execute() at /var/www/html/mautic/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /var/www/html/mautic/vendor/symfony/console/Application.php:1058
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/mautic/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/mautic/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /var/www/html/mautic/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/mautic/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /var/www/html/mautic/bin/console:16

In Connection.php line 71:
                                                                                                                              
  [PDOException (42000)]                                                                                                      
  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_72243719E7A1254A`; check that it exists  
                                                                                                                              

Exception trace:
  at /var/www/html/mautic/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:71
 PDO->query() at /var/www/html/mautic/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:71
 Doctrine\DBAL\Driver\PDO\Connection->query() at /var/www/html/mautic/vendor/doctrine/dbal/src/Connection.php:1100
 Doctrine\DBAL\Connection->executeQuery() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:273
 Doctrine\Migrations\Version\DbalExecutor->executeResult() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:150
 Doctrine\Migrations\Version\DbalExecutor->executeMigration() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:73
 Doctrine\Migrations\Version\DbalExecutor->execute() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:88
 Doctrine\Migrations\DbalMigrator->executePlan() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:54
 Doctrine\Migrations\DbalMigrator->executeMigrations() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:136
 Doctrine\Migrations\DbalMigrator->migrate() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/ExecuteCommand.php:157
 Doctrine\Migrations\Tools\Console\Command\ExecuteCommand->execute() at /var/www/html/mautic/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /var/www/html/mautic/vendor/symfony/console/Application.php:1058
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/mautic/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/mautic/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /var/www/html/mautic/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/mautic/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /var/www/html/mautic/bin/console:16

doctrine:migrations:execute [--write-sql [WRITE-SQL]] [--dry-run] [--up] [--down] [--query-time] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] <versions>...
```


```
user@server:/var/www/html/mautic# php bin/console doctrine:migrations:execute 'Mautic\Migrations\Version20230621074925' --up -vvv

 WARNING! You are about to execute a migration in database "mautic_base" that could result in schema changes and data loss. Are you sure you wish to continue? (yes/no) [yes]:
 > yes

[notice] Executing Mautic\Migrations\Version20230621074925 up
[notice] Table mau_point_groups already exists
[notice] Table mau_point_group_contact_score already exists
[notice] Column mau_points.group_id already exists
[notice] Column mau_point_triggers.group_id already exists
[notice] Column mau_lead_points_change_log.group_id already exists
[info] ++ migrating Mautic\Migrations\Version20230621074925
[debug] CREATE TABLE `mau_point_groups`
(
    `id`                  INT UNSIGNED AUTO_INCREMENT NOT NULL,
    `is_published`        TINYINT(1)                  NOT NULL,
    `date_added`          DATETIME     DEFAULT NULL,
    `created_by`          INT          DEFAULT NULL,
    `created_by_user`     VARCHAR(191) DEFAULT NULL,
    `date_modified`       DATETIME     DEFAULT NULL,
    `modified_by`         INT          DEFAULT NULL,
    `modified_by_user`    VARCHAR(191) DEFAULT NULL,
    `checked_out`         DATETIME     DEFAULT NULL,
    `checked_out_by`      INT          DEFAULT NULL,
    `checked_out_by_user` VARCHAR(191) DEFAULT NULL,
    `name`                VARCHAR(191)                NOT NULL,
    `description`         LONGTEXT     DEFAULT NULL,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4
  COLLATE `utf8mb4_unicode_ci`
  ENGINE = InnoDB
  ROW_FORMAT = DYNAMIC; 
[error] Migration Mautic\Migrations\Version20230621074925 failed during Execution. Error: "An exception occurred while executing a query: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'mau_point_groups' already exists"

In ExceptionConverter.php line 45:
                                                                                                                                                   
  [Doctrine\DBAL\Exception\TableExistsException (1050)]                                                                                            
  An exception occurred while executing a query: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'mau_point_groups' already exists  
                                                                                                                                                   

Exception trace:
  at /var/www/html/mautic/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:45
 Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() at /var/www/html/mautic/vendor/doctrine/dbal/src/Connection.php:1938
 Doctrine\DBAL\Connection->handleDriverException() at /var/www/html/mautic/vendor/doctrine/dbal/src/Connection.php:1880
 Doctrine\DBAL\Connection->convertExceptionDuringQuery() at /var/www/html/mautic/vendor/doctrine/dbal/src/Connection.php:1105
 Doctrine\DBAL\Connection->executeQuery() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:273
 Doctrine\Migrations\Version\DbalExecutor->executeResult() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:150
 Doctrine\Migrations\Version\DbalExecutor->executeMigration() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:73
 Doctrine\Migrations\Version\DbalExecutor->execute() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:88
 Doctrine\Migrations\DbalMigrator->executePlan() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:54
 Doctrine\Migrations\DbalMigrator->executeMigrations() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:136
 Doctrine\Migrations\DbalMigrator->migrate() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/ExecuteCommand.php:157
 Doctrine\Migrations\Tools\Console\Command\ExecuteCommand->execute() at /var/www/html/mautic/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /var/www/html/mautic/vendor/symfony/console/Application.php:1058
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/mautic/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/mautic/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /var/www/html/mautic/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/mautic/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /var/www/html/mautic/bin/console:16

In Exception.php line 28:
                                                                                                    
  [Doctrine\DBAL\Driver\PDO\Exception (1050)]                                                       
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'mau_point_groups' already exists  
                                                                                                    

Exception trace:
  at /var/www/html/mautic/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28
 Doctrine\DBAL\Driver\PDO\Exception::new() at /var/www/html/mautic/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:76
 Doctrine\DBAL\Driver\PDO\Connection->query() at /var/www/html/mautic/vendor/doctrine/dbal/src/Connection.php:1100
 Doctrine\DBAL\Connection->executeQuery() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:273
 Doctrine\Migrations\Version\DbalExecutor->executeResult() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:150
 Doctrine\Migrations\Version\DbalExecutor->executeMigration() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:73
 Doctrine\Migrations\Version\DbalExecutor->execute() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:88
 Doctrine\Migrations\DbalMigrator->executePlan() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:54
 Doctrine\Migrations\DbalMigrator->executeMigrations() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:136
 Doctrine\Migrations\DbalMigrator->migrate() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/ExecuteCommand.php:157
 Doctrine\Migrations\Tools\Console\Command\ExecuteCommand->execute() at /var/www/html/mautic/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /var/www/html/mautic/vendor/symfony/console/Application.php:1058
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/mautic/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/mautic/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /var/www/html/mautic/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/mautic/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /var/www/html/mautic/bin/console:16

In Connection.php line 71:
                                                                                                    
  [PDOException (42S01)]                                                                            
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'mau_point_groups' already exists  
                                                                                                    

Exception trace:
  at /var/www/html/mautic/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:71
 PDO->query() at /var/www/html/mautic/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:71
 Doctrine\DBAL\Driver\PDO\Connection->query() at /var/www/html/mautic/vendor/doctrine/dbal/src/Connection.php:1100
 Doctrine\DBAL\Connection->executeQuery() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:273
 Doctrine\Migrations\Version\DbalExecutor->executeResult() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:150
 Doctrine\Migrations\Version\DbalExecutor->executeMigration() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Version/DbalExecutor.php:73
 Doctrine\Migrations\Version\DbalExecutor->execute() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:88
 Doctrine\Migrations\DbalMigrator->executePlan() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:54
 Doctrine\Migrations\DbalMigrator->executeMigrations() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/DbalMigrator.php:136
 Doctrine\Migrations\DbalMigrator->migrate() at /var/www/html/mautic/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/ExecuteCommand.php:157
 Doctrine\Migrations\Tools\Console\Command\ExecuteCommand->execute() at /var/www/html/mautic/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /var/www/html/mautic/vendor/symfony/console/Application.php:1058
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/mautic/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/mautic/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at /var/www/html/mautic/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/mautic/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /var/www/html/mautic/bin/console:16

doctrine:migrations:execute [--write-sql [WRITE-SQL]] [--dry-run] [--up] [--down] [--query-time] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] <versions>...

```

**Comment by saschafoerster** [comment]
`ALTER TABLE `mau_point_group_contact_score` ADD CONSTRAINT `FK_72243719E7A1254A` FOREIGN KEY (`contact_id`) REFERENCES `mau_leads` (`id`) ON DELETE CASCADE `

Result: 
`Query 1 ERROR at Line 1: : Can't create table `mautic_base`.`mau_point_group_contact_score` (errno: 150 "Foreign key constraint is incorrectly formed")`

**Comment by patrykgruszka** [comment]
@saschafoerster I've updated the down procedure, please try the `--down` and `--up` again and see if it helps. I think this may be specific to your database, as the previous error was just due to the false negative error during the pre-up checks. The database should be fine in most cases.

**Comment by Napsty** [comment]
LGTM, manually applied patch in `app/migrations/Version20230621074925.php` and update to 5.0.1 (from 5.0.0-alpha1) worked successfully. Thanks for the fix!

**Pull request merged**
