### PR TITLE
Focus: hide form If we use notice type of popups 

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✅ 
| New feature/enhancement? (use the a.x branch)      | 
| Deprecations?                          | 🚫 
| BC breaks? (use the c.x branch)        | 
| Automated tests included?              | ✅ 
| Related user documentation PR URL      | no need
| Related developer documentation PR URL | no need
| Issue(s) addressed                     | 

#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2. Generate a focus with data collect selected and add a form
3. Switch to notice type of focus
4. Complete and preview
5. You should see form even If you want notice type of focus
6. After patch should work

### CODE REVIEW

**Review by escopecz — CHANGES_REQUESTED** [review]
The code change looks good. But I'm missing tests.

**Comment by kuzmany** [comment]
@escopecz unit tests added

**Review by escopecz — DISMISSED** [review]
I would remove the `mixed` types from the test params, but that's very minor issue. Code looks great. Thanks @kuzmany

**Review by npracht — DISMISSED** [review]
Tested again and it works from a user perspective. Using it in production environment for 3 months now 👍🏽

**Comment by npracht** [comment]
@escopecz we addressed your feedback, better to do it now :)
We're good to go, thanks for testing.

**Review by dennisameling — APPROVED** [review]

**Pull request merged**
