### PR TITLE
Handle error in PageSubscriber on page hit

### PR DESCRIPTION
**Pull request by nethunter**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| Automated tests included? | no
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description: 
When there's a missing hit record, the whole page hit daemon gets stuck. This at least marks this job as rejected, and logs the error.

Related to #5452

### CODE REVIEW

**Comment by kuzmany** [comment]
@nethunter Can you fix code style https://travis-ci.org/mautic/mautic/jobs/445070858#L710 ?
Also please add steps to test.

**Comment by npracht** [comment]
Hello @nethunter ! Could you address Kuzmany's comments ?

**Comment by Cl8vM1nd** [comment]
Fixed in #7030

**Comment by Woeler** [comment]
Since there seems to be no reaction, closing in favor of https://github.com/mautic/mautic/pull/7030

**Pull request closed without merging**
