### PR TITLE
Custom date field to trigger a campaign

### PR DESCRIPTION
**Pull request by nithinga**
| Q | A |
| --- | --- |
| Bug fix? | No |
| New feature? | Yes |
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/98 |
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/306 |
#### Description:

Feature to use custom date field to trigger a campaign.
#### Steps to test this PR:
1. Add a custom date field to Lead/Contacts.
2. Create a new campaign.
3. Open the campaign builder and create a contact segment/Contact Source
4. Link that contact segment to "condition" event using contact field value.
5. In "contact field value" form select our new custom date field, then select "Operator" as date.
6. Select "value" drop-down. ( values such is today, is tomorrow etc ). Save it.
7. Link this to any action such as send email.
8. Save the campaign.
9. Trigger the campaign.

**Note:** 
**Known issues**: Currently Mautic only executes campaign only once and doesn't support recurring campaigns. Waiting for someone to sort out the issues as referenced here,

 https://github.com/mautic/mautic/issues/1606

https://github.com/mautic/mautic/pull/2487

### CODE REVIEW

**Comment by nithinga** [comment]
@escopecz Documentation added.

**Comment by rodrideme** [comment]
congratulations @nithinga I can imagine the numbers the restaurants, bars, pubs would like to send to your customers a reminder 60, 30 days before your birthday about a reservation, fantastic

**Comment by virlatinus** [comment]
Feature works as documented. +1

**Comment by FerRubioMorales** [comment]
Thanks for your work. BUt i think this not cover my case.

I need to send an alert to someone that is based on form field/contact field values. Example:

Contact form:
Zone: New york | Paris

Send to sales manager on new york or Paris.

**Comment by conorseed** [comment]
This looks awesome @nithinga . Thanks to every who has contributed to this!!
Does it fully work? If so, how do I go about installing this into my Mautic installation?

**Comment by escopecz** [comment]
@conorseed It's in the Mautic's core since 2.5 (notice the milestone)

**Comment by conorseed** [comment]
Of course it has. Sorry, I'm still new to the Github world! 
Just did some more digging around and found out how to use this feature. 
Thanks heaps @escopecz!!

**Pull request merged**
