### PR TITLE
remove Raw block from GrapesJS sidebar for MJML emails

### PR DESCRIPTION
**Pull request by LordRembo**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Opened up [some discussion on the arguably broken state of the Raw block](https://forum.mautic.org/t/product-input-how-do-you-use-the-raw-block-in-the-email-editor/30748). My suggestion would be to remove this block entirely, since it's unusable.
It doesn't do what users think it does: renders a gallery of images instead of outputting editable html.
This seems to be intentional behavior, as [it behaves the same in GrapesJS' own demo](https://grapesjs.com/demo-mjml.html).  But since it makes no sense, we are better or removing it instead of leaving users confused.

**Note**: This PR just removes the block, it does not attempt to replace the suggested functionality. [That is a new feature in a separate PR, with its own caveats](https://github.com/mautic/mautic/pull/13386)

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Make a new MJML template based Email (eg. Paprika)
3. Notice the 'Raw' block is no longer present in the sidebar

### CODE REVIEW

**Comment by code5rick** [comment]
@LordRembo, after testing your PR on GitPod, I can confirm that it does remove the code block from the builder, more specifically on the email builder.

One thing I noticed is that the general font of Mautic seems off compared to the original. I believe you made changes to the stylesheet that affected the general layout.

image

Other than that, it seems OK!

**Comment by LordRembo** [comment]
@code5rick You need to test against the 5.x branch of the project, not the 5.0.3 release. There is nothing here that changes the body font.
It's probably something that was changed after that release.

**Comment by mollux** [comment]
@code5rick @LordRembo the font changes are related to https://github.com/mautic/mautic/pull/13317 which was merged into 5.x. 

As this PR targets the same branch, those font changes are here too

**Comment by RCheesley** [comment]
@LordRembo some conflicts to address here :)

**Comment by LordRembo** [comment]
Should be okay now

**Comment by LordRembo** [comment]
fixed the new merge conflicts

**Comment by LordRembo** [comment]
merged from latest in 5.x

**Review by andersonjeccel — APPROVED** [review]
Works as expected, no Raw block after

**Review by jos0405 — DISMISSED** [review]
Does what it claims: raw block is gone.

**Comment by LordRembo** [comment]
updated branch to be up-to-date with 5.x

**Comment by andersonjeccel** [comment]
@escopecz What do you think?

**Review by escopecz — APPROVED** [review]
Code seems OK. It's weird that there is no config option to set what blocks we want. I'm not familiar with this builder. But this works.

**Pull request merged**
