### PR TITLE
[UI] Remove Froala styles

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🟢
| BC breaks? (use the c.x branch)        | 🟢
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR removes all interface styles related to Froala.

---

### CODE REVIEW

**Comment by andersonjeccel** [comment]
@escopecz Going there and start deleting things is a therapy, but doing it in PHP and JS might break things that we want working

so I compiled changes in LESS/CSS and left the other parts for you :)

**Review by escopecz — APPROVED** [review]
Thanks! This will need some PHP and JS to be deleted too as you mentioned, but this is a good start 👍

**Review by matbcvo — APPROVED** [review]

**Comment by escopecz** [comment]
@andersonjeccel there are some conflicts

**Comment by andersonjeccel** [comment]
@escopecz solved

**Pull request merged**
