### PR TITLE
Merging 5.0 to 5.x to fix API Library tests

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [y]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

The API Library tests were fixed in https://github.com/mautic/mautic/pull/13410 but we still get notifications as the tests run from the 5.x branch. Let's merge the bug fix to the 5.x too to stop the notifications.

#### Steps to test this PR:

1. Let's just run the API Library tests on this PR.

### CODE REVIEW

**Comment by escopecz** [comment]
I started the API Library tests on this branch here: https://github.com/mautic/api-library/actions/runs/8047862353

**Review by patrykgruszka — CHANGES_REQUESTED** [review]
@escopecz there are 64 commits from the 5.0 branch and only 2 changed files, looks like there's something wrong with this PR.

**Comment by escopecz** [comment]
Yep, I'm not sure what I did wrong, though. What happens if you try to do this? And some API Library tests are still failing, so we'll have to figure that out too as this change won't fix the issue completely.

**Comment by patrykgruszka** [comment]
I'm having the same problem. It looks like the changes are already there, but without the commits. Maybe the commits got squashed during the merge? I thinks this is the PR https://github.com/mautic/mautic/pull/13354

**Review by patrykgruszka — APPROVED** [review]

**Comment by escopecz** [comment]
The CS issue should be fixed by merging 5.x

**Comment by escopecz** [comment]
Yep, the [API Library tests are passing](https://github.com/mautic/api-library/actions/runs/8204076006) with the latest changes. Thank you!

**Pull request merged**
