### PR TITLE
Support configuration of RabbitMQ idle timeout

### PR DESCRIPTION
**Pull request by maxlawton**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | features
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | https://github.com/mautic/mautic-documentation/pull/189

This is a re-submission of #6586, rebased on the **3.1** branch. The former PR was closed due to inactivity after M2 submission was ended.

#### Description:

Adds the following configuration options to the **QueueBundle**:

- *rabbitmq_idle_timeout*, default `0`.
- *rabbitmq_idle_timeout_exit_code*, default `0`. Doesn't appear to actually get returned by queue commands.

These options are read when loading the `old_sound_rabbit_mq` extension, in the setup for the *mautic* consumer.

##### N.B.

Ideally this would be accompanied by options for the `graceful_max_execution` settings, but there is no way to have an ineffectual default value for that as the extension does an `isset()` test before applying the setting to the service definition (in [OldSoundRabbitMqExtension::loadConsumers][rmqb-loadconsumers]). Therefore any value, like NULL or an empty array, will cause the _graceful max execution time_ to be set. Supporting ommission of null defaults would require changes to the _php-amqplib/rabbitmq-bundle_. As there are no checks against null or zero values, the following issues arise:

* When the `graceful_max_execution` is NULL or `['timeout' => NULL, ...]`, a non-valid DateTime is created [in the consumer][rmqb-consumer-maxexec].
* The use of an actual zero (`0`) for the `['graceful_max_execution']['timeout']` is explicitly [warned against][rmqb-consumer-nozero].

[rmqb-loadconsumers]: https://github.com/php-amqplib/RabbitMqBundle/blob/472aad360f9678234490bf0fad654981e3413d14/DependencyInjection/OldSoundRabbitMqExtension.php#L216-L225
[rmqb-consumer-maxexec]: https://github.com/php-amqplib/RabbitMqBundle/blob/472aad360f9678234490bf0fad654981e3413d14/RabbitMq/Consumer.php#L226-L232
[rmqb-consumer-nozero]: https://github.com/php-amqplib/RabbitMqBundle/blob/472aad360f9678234490bf0fad654981e3413d14/RabbitMq/Consumer.php#L74-L77

#### Steps to test this PR:

1. Set the options in `app/config/local.php`, e.g.:
    ```php
    <?php
    $parameters = array(
        // ...
        'rabbitmq_idle_timeout' => 10,
        'rabbitmq_idle_timeout_exit_code' => 408, // or whatever
        // ...
    );
    ```
3. Clear the app cache.
2. Run a queue command:
    `$ app/console mautic:queue:process -i page_hit`
3. The process should exit after the consumer has idled for the specified time. As tested with an empty queue, the total run time of the command is often ~6 seconds longer than the specified idle timeout (longer when the cache is rebuilt).

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
The code looks good 👍

**Comment by RCheesley** [comment]
@escopecz where can folk find documentation on configuring RabbitMQ? We had another issue about this, and if we're changing things we should update it.

**Comment by escopecz** [comment]
I think it should go to https://docs.mautic.org/en/queue. @maxlawton can you add those config options documented there?

**Comment by maxlawton** [comment]
@escopecz, @RCheesley The documentation for RabbitMQ at https://docs.mautic.org/en/queue refers to configuration that is no longer available as of https://github.com/mautic/mautic/commit/74b8c3e942636a953b081a285c5b696563806662

Is there somewhere else that I should add user documentation for the configurations defined in this PR?

**Comment by RCheesley** [comment]
@maxlawton I recommend removing the references to the GUI interface from the docs on that page, and replacing it with the config changes you need to make in the local configuration file to enable the queues.

**Review by hluchas — CHANGES_REQUESTED** [review]
Code looks good, but after test with
```
    // The number of seconds after which the queue consumer should timeout when idle
    'rabbitmq_idle_timeout' => 10,
    // The exit code to be returned when the consumer exits due to idle timeout
    'rabbitmq_idle_timeout_exit_code' => -1,
```
phpstorm run returns
```
"[docker-compose://[/Users/lukas.drahy/dev/mautic-dev-docker/mautic-community/docker-compose.yml, /Users/lukas.drahy/dev/mautic-dev-docker/mautic-community/docker-compose.override.yml]:php_xdebug/]:php" /var/www/html/bin/console mautic:queue:process --queue-name=email_hit --env=dev -v

Process finished with exit code 0
```

**Comment by maxlawton** [comment]
> Code looks good, but after test with
> 
> ```
>     // The number of seconds after which the queue consumer should timeout when idle
>     'rabbitmq_idle_timeout' => 10,
>     // The exit code to be returned when the consumer exits due to idle timeout
>     'rabbitmq_idle_timeout_exit_code' => -1,
> ```
> 
> phpstorm run returns
> 
> ```
> "[docker-compose://[/Users/lukas.drahy/dev/mautic-dev-docker/mautic-community/docker-compose.yml, /Users/lukas.drahy/dev/mautic-dev-docker/mautic-community/docker-compose.override.yml]:php_xdebug/]:php" /var/www/html/bin/console mautic:queue:process --queue-name=email_hit --env=dev -v
> 
> Process finished with exit code 0
> ```

@hluchas True, and noted in the description of this PR. That's because nothing is done with the result of `$consumer->consume($event->getMessages());` in the **RabbitMQSubscriber**. I'm working on a separate PR to persist that return value through the event so it can be read by the **ConsumeQueueCommand**. Doing that affects much more than allowing two parameters to be passed to the service, so I'd rather not add that complexity to this PR.

**Comment by RCheesley** [comment]
@maxlawton please could you pull in the latest updates from the Features branch? As this has two good tests and a code review it should be OK for us to get merged, I think. Unfortunately it's on a protected branch so I can't pull in the latest code changes.

**Review by kuzmany — APPROVED** [review]
I am good with it 👍

**Comment by RCheesley** [comment]
@maxlawton just needs you to merge in the latest features branch and we'll be able to get this into the next release (Mautic 4). Could you do that please?

**Comment by RCheesley** [comment]
@all-contributors please add @maxlawton for code

**Comment by RCheesley** [comment]
@all-contributors please add @maxlawton for docs

**Pull request merged**
