### PR TITLE
New expressions in Campaign lead field condition:  empty/not empty, regexp/not regexp

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | n
| New feature? | y
| Related user documentation PR URL | n
| Related developer documentation PR URL | n
| Issues addressed (#s or URLs) | n
| BC breaks? | n
| Deprecations? | n

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Update lead field condition:
- added empty/not empty operators
- added regexp/not regexp operators
(http://dev.mysql.com/doc/refman/5.7/en/regexp.html)

These changes improves work with campaigns.

#### Steps to test this PR:
1. Create campaign with Lead field condition
2. Test new operators

regexp

### CODE REVIEW

**Comment by medianicus** [comment]
Forgive my ignorance but my appdev / Linux experience is very limited. Is it possible to test this by just overwriting the changed files? If so, how do I get them?

Thanks

**Comment by FarhadF** [comment]
Yea you can make changes to the files manually too, then run `app/console cache:clear` and then refresh your browser.

If there are Database changes, there are usually Migration files, in t he commit, in that case (this is not the case for this PR) you need to run database migration too, `app/console doctrine:migrations:migrate` this will make changes to your database so be careful with that, and make sure you have a backup in place.

**Comment by mqueme** [comment]
This works for me as described.

**Comment by alanhartless** [comment]
Great feature - works for me. Added in regex support for segments too.

**Comment by gingerling** [comment]
Hi are empty/nor empty removed now? I used them in a campaign for my website newsletter signup with a honeypot, but when I updated to v2.14.1 they disappeared and my campaign broke.

**Pull request merged**
