### PR TITLE
Add html:// prefix for tokens to send raw html via api

### LINKED ISSUE #5933: API HTML based tokens
I have already tested sending emails with custom tokens, by giving values for them in a JSON object ("tokens" => ...). What I need to achieve is to include HTML in these custom tokens, a thing that did not work in my tests, as everything is parsed as text. Is there any way at all to achieve this?

For example, I have a list of products (lets say three products) and I create a detailed list in HTML with them and their thumbnails. I need to attach this code to the "{body}" token in the email template when I make the API request to Mautic.

Looking forward for your answer!

### PR DESCRIPTION
**Pull request by PurHur**
closes #5933

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Y 
| Automated tests included? | N
| Related user documentation PR URL |
| Related developer documentation PR URL |
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/5933
| BC breaks? | N
| Deprecations? |N 

#### Description:
This will allow the send email endpoint to send raw html via the tokens

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Send a html token like this:
```
$params = [
   'tokens' => [
        'strong_name' => 'html://<b>Strong Man!</b>'
    ],
];
$response = $emailApi->sendToContact($mailId, $contactId, $params);
```

### CODE REVIEW

**Comment by dennisameling** [comment]
@PurHur thanks for providing this PR! I see that the Scrutinizer test timed out (not your fault); I'll close and re-open the PR so that tests will run again 😊

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by PurHur** [comment]
**_Perfect_**

I will provide a new PR. I am not good enough for that 👽

**Comment by iparker** [comment]
Are there any news about this? I would be great to have the possibility to use html in tokens.

**Comment by RCheesley** [comment]
@iparker the PR was closed as it was old and needed to be updated. Feel free to make a new one against the Features branch.

**Pull request closed without merging**
