### PR TITLE
Remove multiselect field default value template

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR added in 4.1 support for multiple default values for multiselect contact field.
Looks like the PR generate textarea without make sense. This PR fixed it.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create new field for contact
3. See textarea on right side 
image
4. After PR should gone. 
5. Also check If multiselect default values works like before

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11069"></a>

### CODE REVIEW

**Comment by renatocron** [comment]
Tested locally (I managed to login on gitpod but it's too slow to save/edit)

The field is removed, the function (default value) is still working as before:
Adding new contact load the selected default fields:
image

**Review by mabumusa1 — APPROVED** [review]
I tested on Gitpod, works as expected

**Comment by RCheesley** [comment]
Thanks for testing folks! Just needs a code review and we should be good to go!

**Review by escopecz — APPROVED** [review]
The changes in this PR revert some changes made in https://github.com/mautic/mautic/pull/10415/files#diff-d7fd93dd01a8a62a7d76a1f3e01b075d06f4cd751fbbb09b2b033735f26f9f0dR173. I see no problem from the code point of view.

**Comment by escopecz** [comment]
Force-merging as this PR removes 2 lines and so it reduces the coverage.

**Pull request merged**
