### PR TITLE
Progressive profiling

### PR DESCRIPTION
**Pull request by escopecz**
Please answer the following questions:

| Q             | A
| ------------- | ---
| Bug fix?      | N
| New feature?  | Y
| BC breaks?    | N
| Deprecations? | N
| Fixed issues  | https://github.com/mautic/mautic/issues/414, https://github.com/mautic/mautic/issues/1242
| Documentation | https://github.com/mautic/documentation/pull/63

## Description
Progressive Profiling allows to display only certain fields in the form for current contact based on the past submissions. The conditions are:

- If the form field value already exists, don't display the field.
- Display the field only if the contact submitted this form for X times.

## Steps to test this PR
Run `app/console doctrine:migrations:migrate` command, clear the cache. Build a form with several fields. Each field has the new __Behavior__ tab where you can configure the conditions described above. Configure those conditions so you'd test as many combinations you can think of. Go to the form preview and check if the form displayed the correct fields. Submit the form and check the fields again. Repeat until you test the highest number of submissions you've configured.

The whole form field and action builder was redesigned, so make sure that everything like sorting, delete, new field/action, update of a field/action works.

Even the preview (and all means of displaying a Mautic form in production) was re-styled a bit. The fields are not always 50% wide, but instead, they are in a container with `min-width: 600px` and this box is centered. I hope it will be more convenient default styling.

### CODE REVIEW

**Comment by npracht** [comment]
Answers to https://github.com/mautic/mautic/issues/957 & https://github.com/mautic/mautic/issues/870.

**Comment by alanhartless** [comment]
In testing the new form builder layout (I like it!!), there seems to be a couple quirks. 

1. I can't edit a field unless I delete another first.
2. There's not behavior tab for Email. But I'm assuming this is on purpose? Are there other fields like this or just email?
3. Since the drag/reorder icon is a button, it makes me want to click it but then it does nothing. 
4. This may be an existing bug, but when I delete a field that is already assigned a contact field, the contact field is not added back to the list as being available for another field. I have to refresh to get the contact field available again. For example, add an Email field and check that the contact Email field is assigned. Delete the field and add a new Email field. Notice that Email is no longer available in the contact field list.
5. Viewing the form page/preview or form details page gives me this error `500 Internal Server Error - Notice: Undefined variable: html` for `/app/bundles/FormBundle/Model/FormModel.php (line #379)`

**Comment by alanhartless** [comment]
Should progressive form profiling be disabled for when kiosk mode is enabled?

**Comment by alanhartless** [comment]
Other than those, seems to work on the frontend. If I chose to hide a field that has a value, it didn't show. If I chose for it to show after x submissions. It didn't show till I submitted the form that many times. Good stuff!

**Comment by escopecz** [comment]
Alan, thanks for testing! I'll go through the reported bugs.

2. Yes, Email and Button doesn't have the Behavior tab on purpose. Although I'm still not sure if Email should have it or not. 
@dbhurley could you give us your input on point 3 and the kiosk mode?

**Comment by dbhurley** [comment]
3. Good point, maybe we don't make it a button but rather clicking and dragging anywhere in the panel will make it move.

Yes, kiosk mode should disabled progressive profiling.

**Comment by escopecz** [comment]
All reported issues are solved

**Comment by alanhartless** [comment]
Builder seems to be working well for me now. Good stuff! +1

**Comment by alanhartless** [comment]
@escopecz Sorry John, seems the merge of #1363 caused conflicts here.

**Comment by alanhartless** [comment]
@escopecz Would you please move that new auto fill option to the behavior tab?

**Comment by alanhartless** [comment]
Gotcha covered John - https://github.com/escopecz/mautic/pull/13

**Comment by dongilbert** [comment]
+1

**Pull request merged**
