### PR TITLE
vTiger: Company name support

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
One of previous Mautic version divided integrations fields for contact/company.
This PR added support for Company name and therefor add Company Mappings tab.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1.  Install vTiger plugin to Mautic
2. Contact mapping tab  is without Company field in Integration fields column

#### Steps to test this PR:
1. Apply PR
2. See Company mapping tab and Company field in Integrations tab

image

### CODE REVIEW

**Comment by justinroffmarsh** [comment]
In STEPS TO REPRODUCE, you do not actually need to add the Company field to Vtiger. Vtiger ships with that field in the Lead Module and it cannot be deleted or renamed.

**Comment by kuzmany** [comment]
@justinroffmarsh steps not talking about it

**Comment by kuzmany** [comment]
This PR should be marked ready to test

**Comment by alanhartless** [comment]
Ok so I can't even get vtiger to install to test this. But I don't see any red flags in the code and I can at least open the configuration. Since it's been confirmed by two vtiger users - we're good.

**Pull request merged**
