### PR TITLE
Fix broadcast query

### PR DESCRIPTION
**Pull request by mlahlouh**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [X ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
We noticed the broadcast command takes a lot of time to load the records from the database this PR makes the query faster and remove any redundant queries

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Fill the database with contacts in segments
3. Run broadcast command, and record the time.
4. apply the PR and record the time again.

### CODE REVIEW

**Comment by mabumusa1** [comment]
@RCheesley please add @mlahlouh to the CLA list, thank you

**Comment by escopecz** [comment]
@mabumusa1 can you please create a new PR with Mlahlouh in https://github.com/mautic/clabot-config/blob/main/.clabot? That'd help with the CLA check.

@mlahlouh I'm missing the performance gains you've got with this refactoring from subqueries to joins. We've done this refactoring back and forth many times. The rule we found is that subqueries are faster on small datasets up to 1M rows and subqueries are faster on larger datasets. Please provide all the information you have including the EXPLAIN queries before and after. We need good data to make this decision because next year there will be a PR reverting this change saying that joins are slow.

**Comment by mabumusa1** [comment]
@cla-bot check

**Comment by mlahlouh** [comment]
Hello @escopecz 

I'll list here the execution plan for both queries:

old one:
`EXPLAIN FORMAT=JSON SELECT count(*) AS count
FROM ma_leads l
WHERE (
		l.id IN (
			SELECT ll.lead_id
			FROM ma_lead_lists_leads ll
			WHERE (
					ll.leadlist_id IN (
						289
						,33
						)
					)
				AND (ll.manually_removed = 0)
			)
		)
	AND (
		l.id NOT IN (
			SELECT dnc.lead_id
			FROM ma_lead_donotcontact dnc
			WHERE dnc.channel = 'email'
			)
		)
	AND (
		l.id NOT IN (
			SELECT stat.lead_id
			FROM ma_email_stats stat
			WHERE (stat.lead_id IS NOT NULL)
				AND (stat.email_id = 36)
			)
		)
	AND (
		l.id NOT IN (
			SELECT mq.lead_id
			FROM ma_message_queue mq
			WHERE (mq.STATUS <> 'sent')
				AND (mq.channel = 'email')
				AND (mq.channel_id = 88)
			)
		)
	AND (
		l.id NOT IN (
			SELECT lc.lead_id
			FROM ma_lead_categories lc
			INNER JOIN ma_emails e ON e.category_id = lc.category_id
			WHERE (e.id = 36)
				AND (lc.manually_removed = 1)
			)
		)
	AND (
		(l.email IS NOT NULL)
		AND (l.email <> '')
		);
		`

The new one (JOIN):
`EXPLAIN FORMAT=JSON SELECT count(*) AS count
FROM ma_leads l
LEFT JOIN ma_email_stats stat ON (stat.lead_id = l.id)
	AND (stat.email_id = 36)
	AND (stat.lead_id IS NOT NULL)
LEFT JOIN ma_message_queue mq ON (mq.lead_id = l.id)
	AND (mq.STATUS = 'sent')
	AND (mq.channel = 'email')
	AND (mq.channel_id = 88)
INNER JOIN ma_lead_lists_leads ll ON (ll.lead_id = l.id)
	AND (
		ll.leadlist_id IN (
			289
			,33
			)
		)
	AND (ll.manually_removed = 0)
LEFT JOIN ma_lead_donotcontact dnc ON (dnc.lead_id = l.id)
	AND (dnc.channel = 'email')
LEFT JOIN ma_lead_categories lc ON (lc.lead_id = l.id)
	AND (lc.manually_removed = 1)
LEFT JOIN ma_emails e ON (e.id = 36)
	AND (e.category_id = lc.category_id)
WHERE (mq.id IS NULL)
	AND (
		(dnc.id IS NULL)
		AND (stat.id IS NULL)
		AND (lc.id IS NULL)
		)
	AND (
		(l.email IS NOT NULL)
		AND (l.email <> '')
		);`


New Query (Join):
Single stage and 
**query_cost** is 260,145
image


Old Query:
Multiple stages and 
**query_cost** is 307,768
image

**Comment by escopecz** [comment]
@mlahlouh Explain output looks great! What was the table size? We found that the used algorithm is different based on the table size. Was it 135k rows? Are you able to test with several millions?

**Comment by mabumusa1** [comment]
@mlahlouh I ran those two queries on an installation with 688K contacts, I got the following results.

@escopecz If you have a huge database to run the queries on, would be great to see the difference

```
 {
  "query_block": {
    "select_id": 1,
    "cost_info": {
      "query_cost": "6.61"
    },
    "duplicates_removal": {
      "using_temporary_table": true,
      "nested_loop": [
        {
          "table": {
            "table_name": "ll",
            "access_type": "range",
            "possible_keys": [
              "PRIMARY",
              "IDX_58E1930B9FC8874",
              "IDX_58E193055458D",
              "c5m_manually_removed"
            ],
            "key": "c5m_manually_removed",
            "used_key_parts": [
              "manually_removed",
              "leadlist_id"
            ],
            "key_length": "5",
            "rows_examined_per_scan": 2,
            "rows_produced_per_join": 2,
            "filtered": "100.00",
            "using_index": true,
            "cost_info": {
              "read_cost": "1.41",
              "eval_cost": "0.40",
              "prefix_cost": "1.81",
              "data_read_per_join": "48"
            },
            "used_columns": [
              "leadlist_id",
              "lead_id",
              "manually_removed"
            ],
            "attached_condition": "((`prefix`.`ll`.`manually_removed` = 0) and (not(<in_optimizer>(`prefix`.`ll`.`lead_id`,<exists>(<index_lookup>(<cache>(`prefix`.`l`.`id`) in c5m_lead_donotcontact on IDX_E467CC355458D checking NULL where (`prefix`.`dnc`.`channel` = 'email') having <is_not_null_test>(`prefix`.`dnc`.`lead_id`)))))) and (not(<in_optimizer>(`prefix`.`ll`.`lead_id`,<exists>(/* select#4 */ select 1 from `prefix`.`c5m_email_stats` `stat` where ((`prefix`.`stat`.`email_id` = 36) and (`prefix`.`stat`.`lead_id` is not null) and ((<cache>(`prefix`.`l`.`id`) = `prefix`.`stat`.`lead_id`) or isnull(`prefix`.`stat`.`lead_id`))) having <is_not_null_test>(`prefix`.`stat`.`lead_id`))))) and (not(<in_optimizer>(`prefix`.`ll`.`lead_id`,<exists>(<index_lookup>(<cache>(`prefix`.`l`.`id`) in c5m_message_queue on IDX_2251EB4C55458D where ((`prefix`.`mq`.`channel_id` = 88) and (`prefix`.`mq`.`status` <> 'sent') and (`prefix`.`mq`.`channel` = 'email') and (<cache>(`prefix`.`l`.`id`) = `prefix`.`mq`.`lead_id`))))))) and (not(<in_optimizer>(`prefix`.`ll`.`lead_id`,<exists>(/* select#6 */ select 1 from `prefix`.`c5m_lead_categories` `lc` join `prefix`.`c5m_emails` `e` where ((<cache>(`prefix`.`l`.`id`) = `prefix`.`lc`.`lead_id`) and multiple equal(36, NULL) and multiple equal(1, `prefix`.`lc`.`manually_removed`) and multiple equal(NULL, `prefix`.`lc`.`category_id`)))))) and (`prefix`.`ll`.`leadlist_id` in (289,33)))",
            "attached_subqueries": [
              {
                "dependent": true,
                "cacheable": false,
                "query_block": {
                  "select_id": 6,
                  "message": "no matching row in const table"
                }
              },
              {
                "dependent": true,
                "cacheable": false,
                "query_block": {
                  "select_id": 5,
                  "cost_info": {
                    "query_cost": "1.20"
                  },
                  "table": {
                    "table_name": "mq",
                    "access_type": "index_subquery",
                    "possible_keys": [
                      "IDX_2251EB4C55458D",
                      "c5m_message_status_search",
                      "c5m_message_channel_search"
                    ],
                    "key": "IDX_2251EB4C55458D",
                    "used_key_parts": [
                      "lead_id"
                    ],
                    "key_length": "8",
                    "ref": [
                      "func"
                    ],
                    "rows_examined_per_scan": 1,
                    "rows_produced_per_join": 1,
                    "filtered": "100.00",
                    "cost_info": {
                      "read_cost": "1.00",
                      "eval_cost": "0.20",
                      "prefix_cost": "1.20",
                      "data_read_per_join": "1K"
                    },
                    "used_columns": [
                      "lead_id",
                      "channel",
                      "channel_id",
                      "status"
                    ],
                    "attached_condition": "((`prefix`.`mq`.`channel_id` = 88) and (`prefix`.`mq`.`status` <> 'sent') and (`prefix`.`mq`.`channel` = 'email') and (<cache>(`prefix`.`l`.`id`) = `prefix`.`mq`.`lead_id`))"
                  }
                }
              },
              {
                "dependent": true,
                "cacheable": false,
                "query_block": {
                  "select_id": 4,
                  "cost_info": {
                    "query_cost": "1.20"
                  },
                  "table": {
                    "table_name": "stat",
                    "access_type": "ref",
                    "possible_keys": [
                      "IDX_D58EE30A832C1C9",
                      "IDX_D58EE3055458D",
                      "c5m_stat_email_search",
                      "c5m_stat_email_search2"
                    ],
                    "key": "IDX_D58EE30A832C1C9",
                    "used_key_parts": [
                      "email_id"
                    ],
                    "key_length": "5",
                    "ref": [
                      "const"
                    ],
                    "rows_examined_per_scan": 1,
                    "rows_produced_per_join": 0,
                    "filtered": "50.00",
                    "cost_info": {
                      "read_cost": "1.00",
                      "eval_cost": "0.10",
                      "prefix_cost": "1.20",
                      "data_read_per_join": "1K"
                    },
                    "used_columns": [
                      "email_id",
                      "lead_id"
                    ],
                    "attached_condition": "((`prefix`.`stat`.`lead_id` is not null) and ((<cache>(`prefix`.`l`.`id`) = `prefix`.`stat`.`lead_id`) or isnull(`prefix`.`stat`.`lead_id`)))"
                  }
                }
              },
              {
                "dependent": true,
                "cacheable": false,
                "query_block": {
                  "select_id": 3,
                  "cost_info": {
                    "query_cost": "2.44"
                  },
                  "table": {
                    "table_name": "dnc",
                    "access_type": "index_subquery",
                    "possible_keys": [
                      "IDX_E467CC355458D"
                    ],
                    "key": "IDX_E467CC355458D",
                    "used_key_parts": [
                      "lead_id"
                    ],
                    "key_length": "9",
                    "ref": [
                      "func"
                    ],
                    "rows_examined_per_scan": 2,
                    "rows_produced_per_join": 0,
                    "filtered": "10.00",
                    "cost_info": {
                      "read_cost": "2.04",
                      "eval_cost": "0.04",
                      "prefix_cost": "2.44",
                      "data_read_per_join": "164"
                    },
                    "used_columns": [
                      "lead_id",
                      "channel"
                    ],
                    "attached_condition": "(`prefix`.`dnc`.`channel` = 'email')"
                  }
                }
              }
            ]
          }
        },
        {
          "table": {
            "table_name": "l",
            "access_type": "eq_ref",
            "possible_keys": [
              "PRIMARY",
              "c5m_email_search"
            ],
            "key": "PRIMARY",
            "used_key_parts": [
              "id"
            ],
            "key_length": "8",
            "ref": [
              "prefix.ll.lead_id"
            ],
            "rows_examined_per_scan": 1,
            "rows_produced_per_join": 1,
            "filtered": "50.00",
            "cost_info": {
              "read_cost": "2.00",
              "eval_cost": "0.20",
              "prefix_cost": "6.61",
              "data_read_per_join": "23K"
            },
            "used_columns": [
              "id",
              "email"
            ],
            "attached_condition": "((`prefix`.`l`.`email` is not null) and (`prefix`.`l`.`email` <> ''))"
          }
        }
      ]
    }
  }
} 


========


{
  "query_block": {
    "select_id": 1,
    "cost_info": {
      "query_cost": "5.67"
    },
    "nested_loop": [
      {
        "table": {
          "table_name": "ll",
          "access_type": "range",
          "possible_keys": [
            "PRIMARY",
            "IDX_58E1930B9FC8874",
            "IDX_58E193055458D",
            "c5m_manually_removed"
          ],
          "key": "c5m_manually_removed",
          "used_key_parts": [
            "manually_removed",
            "leadlist_id"
          ],
          "key_length": "5",
          "rows_examined_per_scan": 2,
          "rows_produced_per_join": 2,
          "filtered": "100.00",
          "using_index": true,
          "cost_info": {
            "read_cost": "1.41",
            "eval_cost": "0.40",
            "prefix_cost": "1.81",
            "data_read_per_join": "48"
          },
          "used_columns": [
            "leadlist_id",
            "lead_id",
            "manually_removed"
          ],
          "attached_condition": "((`prefix`.`ll`.`manually_removed` = 0) and (`prefix`.`ll`.`leadlist_id` in (289,33)))"
        }
      },
      {
        "table": {
          "table_name": "l",
          "access_type": "eq_ref",
          "possible_keys": [
            "PRIMARY",
            "c5m_email_search"
          ],
          "key": "PRIMARY",
          "used_key_parts": [
            "id"
          ],
          "key_length": "8",
          "ref": [
            "prefix.ll.lead_id"
          ],
          "rows_examined_per_scan": 1,
          "rows_produced_per_join": 1,
          "filtered": "50.00",
          "cost_info": {
            "read_cost": "2.00",
            "eval_cost": "0.20",
            "prefix_cost": "4.21",
            "data_read_per_join": "23K"
          },
          "used_columns": [
            "id",
            "email"
          ],
          "attached_condition": "((`prefix`.`l`.`email` is not null) and (`prefix`.`l`.`email` <> ''))"
        }
      },
      {
        "table": {
          "table_name": "stat",
          "access_type": "ref",
          "possible_keys": [
            "IDX_D58EE30A832C1C9",
            "IDX_D58EE3055458D",
            "c5m_stat_email_search",
            "c5m_stat_email_search2"
          ],
          "key": "IDX_D58EE30A832C1C9",
          "used_key_parts": [
            "email_id"
          ],
          "key_length": "5",
          "ref": [
            "const"
          ],
          "rows_examined_per_scan": 1,
          "rows_produced_per_join": 0,
          "filtered": "10.00",
          "not_exists": true,
          "cost_info": {
            "read_cost": "1.00",
            "eval_cost": "0.02",
            "prefix_cost": "5.41",
            "data_read_per_join": "252"
          },
          "used_columns": [
            "id",
            "email_id",
            "lead_id"
          ],
          "attached_condition": "(<if>(found_match(stat), isnull(`prefix`.`stat`.`id`), true) and <if>(is_not_null_compl(stat), ((`prefix`.`stat`.`lead_id` = `prefix`.`ll`.`lead_id`) and (`prefix`.`ll`.`lead_id` is not null)), true))"
        }
      },
      {
        "table": {
          "table_name": "mq",
          "access_type": "ref",
          "possible_keys": [
            "IDX_2251EB4C55458D",
            "c5m_message_status_search",
            "c5m_message_channel_search"
          ],
          "key": "IDX_2251EB4C55458D",
          "used_key_parts": [
            "lead_id"
          ],
          "key_length": "8",
          "ref": [
            "prefix.ll.lead_id"
          ],
          "rows_examined_per_scan": 1,
          "rows_produced_per_join": 0,
          "filtered": "100.00",
          "not_exists": true,
          "cost_info": {
            "read_cost": "0.10",
            "eval_cost": "0.02",
            "prefix_cost": "5.53",
            "data_read_per_join": "160"
          },
          "used_columns": [
            "id",
            "lead_id",
            "channel",
            "channel_id",
            "status"
          ],
          "attached_condition": "(<if>(found_match(mq), isnull(`prefix`.`mq`.`id`), true) and <if>(is_not_null_compl(mq), ((`prefix`.`mq`.`channel_id` = 88) and (`prefix`.`mq`.`status` = 'sent') and (`prefix`.`mq`.`channel` = 'email')), true))"
        }
      },
      {
        "table": {
          "table_name": "dnc",
          "access_type": "ref",
          "possible_keys": [
            "IDX_E467CC355458D"
          ],
          "key": "IDX_E467CC355458D",
          "used_key_parts": [
            "lead_id"
          ],
          "key_length": "9",
          "ref": [
            "prefix.ll.lead_id"
          ],
          "rows_examined_per_scan": 1,
          "rows_produced_per_join": 0,
          "filtered": "10.00",
          "not_exists": true,
          "cost_info": {
            "read_cost": "0.10",
            "eval_cost": "0.00",
            "prefix_cost": "5.65",
            "data_read_per_join": "8"
          },
          "used_columns": [
            "id",
            "lead_id",
            "channel"
          ],
          "attached_condition": "(<if>(found_match(dnc), isnull(`prefix`.`dnc`.`id`), true) and <if>(is_not_null_compl(dnc), (`prefix`.`dnc`.`channel` = 'email'), true))"
        }
      },
      {
        "table": {
          "table_name": "lc",
          "access_type": "ref",
          "possible_keys": [
            "IDX_679E556455458D"
          ],
          "key": "IDX_679E556455458D",
          "used_key_parts": [
            "lead_id"
          ],
          "key_length": "8",
          "ref": [
            "prefix.ll.lead_id"
          ],
          "rows_examined_per_scan": 1,
          "rows_produced_per_join": 0,
          "filtered": "100.00",
          "not_exists": true,
          "cost_info": {
            "read_cost": "0.01",
            "eval_cost": "0.00",
            "prefix_cost": "5.67",
            "data_read_per_join": "0"
          },
          "used_columns": [
            "id",
            "category_id",
            "lead_id",
            "manually_removed"
          ],
          "attached_condition": "(<if>(found_match(lc), isnull(`prefix`.`lc`.`id`), true) and <if>(is_not_null_compl(lc), (`prefix`.`lc`.`manually_removed` = 1), true))"
        }
      },
      {
        "table": {
          "table_name": "e",
          "access_type": "const",
          "possible_keys": [
            "PRIMARY",
            "IDX_DECC375D12469DE2"
          ],
          "key": "PRIMARY",
          "used_key_parts": [
            "id"
          ],
          "key_length": "4",
          "ref": [
            "const"
          ],
          "rows_examined_per_scan": 1,
          "rows_produced_per_join": 0,
          "filtered": "100.00",
          "cost_info": {
            "read_cost": "0.01",
            "eval_cost": "0.00",
            "prefix_cost": "5.67",
            "data_read_per_join": "80"
          },
          "used_columns": [
            "id",
            "category_id"
          ],
          "attached_condition": "<if>(is_not_null_compl(e), (`prefix`.`e`.`category_id` = `prefix`.`lc`.`category_id`), true)"
        }
      }
    ]
  }
} 
```

**Comment by escopecz** [comment]
I tested it on a production instance that have:
- 9.7M rows in the leads table
- 40M rows in the lead_lists_leads table
- 0.4M rows in the lead_donotcontact table
- 46M rows in the email_stats table
- 2.5M rows in the message_queue table
- 0 rows in the lead_categories table

The old row was executed in 1.5 sec on the first load and 0.9 sec on consecutive.

The new one took 12 seconds on the first load and 1.5 sec on consecutive.

It also differed in the count value. The old query returned 58764 and the new returned 58766. I double-checked that 2 records weren't just created by executing the first one again.

Explain of the old one:
Screen Shot 2023-01-18 at 09 48 35

And the new one:
Screen Shot 2023-01-18 at 09 48 48

So from our stand point where we should optimize for the bigger datasets, I suggest to keep the query as is.

**Comment by mabumusa1** [comment]
@mlahlouh please check the comment above, it seems the new query did not do the trick

**Pull request closed without merging**
