### PR TITLE
Fix JS issue for code mode

### LINKED ISSUE #5021: Switching to code mode - cannot save changes unless code mode is disabled
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
When switching to code mode in the text slot, changes don't save unless you disable the code mode view 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

### PR DESCRIPTION
**Pull request by kuzmany**
closes #5021

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging for features or enhancements / 3.0 for bug fixes 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | https://github.com/mautic/mautic/issues/9138

#### Description:

PR https://github.com/mautic/mautic/pull/8949 merged to 3.1.0 brings a lot of JS issue while you're using code mode template, reported here https://github.com/mautic/mautic/issues/9138
This PR fixed it.

#### Steps to test this PR:
This PR require call `php bin/console mautic:assets:generate`
1. Load up [this PR](https://mautibox.com) 
2. Switch to code mode template and try edit the code
3. Open browser console (usually F12) and see If there are some errors in console.

### CODE REVIEW

**Comment by trianity** [comment]
@kuzmany  Thank you for the suggestion.
I changed the /app/bundles/CoreBundle/Assets/js/4.builder.js
and changed the /media/js/app.js (compressed form of the file - line 167) and clear the application cache with the command

[...]# php bin/console cache:clear --version
Mautic 3.1.0 - app/prod (kernel: app, env: prod, debug: false)
[...]# php bin/console cache:clear -v
// Clearing the cache for the prod environment with debug false
// Warming up cache...
// Removing old cache directory...
// Finished
[OK] Cache for the "prod" environment (debug=false) was successfully cleared.

And clear the browser cache and can confirm, that with all these actions **the suggested patch works**, and handled the issue.

**Comment by kuzmany** [comment]
@trianity I've added to description warning

This PR require call `php bin/console mautic:assets:generate`

You don't need  edit /media/js/app.js

**Comment by trianity** [comment]
@kuzmany Thank you. it was a missing data: to call `php bin/console mautic:assets:generate`
But the second change does not work.
The variable Mautic.CodeMode is not accessible from the Mautic.keepPreviewAlive = function(iframeId, slot) { .. }
but the function 
Mautic.isCodeMode = function() {
    return mQuery('a[data-theme=mautic_code_mode]').first().hasClass('hide');
};
is accesible.

**Comment by kuzmany** [comment]
@trianity I am not sure what is issue.
Can you please test it here: http://mautibox.com/9143

**Comment by trianity** [comment]
> @trianity I am not sure what is issue.
> Can you please test it here: http://mautibox.com/9143

@kuzmany  Thanks for the reply.
In the test system in: http://mautibox.com/9143 , there was not any issue if you use the condition:
            if (!Mautic.CodeMode) {
                Mautic.setCodeModeSlotContent(slot, value);
            }
but in my patched production system only works this variant of the condition:
            if (!Mautic.isCodeMode()) {
                Mautic.setCodeModeSlotContent(slot, value);
            }
It looks like somehow not equal the installed production Matuic v.3.1 and the mentioned test system above.

**Comment by kuzmany** [comment]
Then you have wrong patch.   Make this change https://github.com/mautic/mautic/pull/9143/files, run `php bin/console m:a:g` and then refresh browser, should work.

**Comment by trianity** [comment]
@kuzmany Yes, you are right.
I made a camelCase typo.

**Review by trianity — APPROVED** [review]
Tested in the production environment and the patch works.

**Review by RCheesley — APPROVED** [review]
Tested with 3.1 and I see the errors mentioned:

screenshot-nimbus-capture-2020 08 28-14_04_57

After applying the patch I am then able to save in code mode and regular themes.

The first error in the screenshot persists but I think that it is not causing a problem or related to this issue.

**Pull request merged**
