### PR TITLE
Fix time timezone on contact profile

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:
Time field on contact profile not display time in properly timezone. 

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Your local timezone should be different to UTC
3. Then create time field 
4. Add time to contact 
5. Check contact detail page and see time is in UTC 
6. After fix you should see correct time

### CODE REVIEW

**Comment by doppelD-LF** [comment]
Doesn't work on my end. After applying patch and creating time field in contact I get 1:00 am, regardless of the actual set time.

**Comment by RCheesley** [comment]
@doppelD-LF could you share with screenshots the steps you took? @kuzmany looks like a CS fix is needed here.

**Comment by kuzmany** [comment]
Found issue. Last commit should fixed it

**Review by jos0405 — APPROVED** [review]
This works as described.
My own timezone is shown in contact history if I change my timezone as admin.

**Review by Robmobius — COMMENTED** [review]
Not working for me, but 1st time testing a PR and using gitpod so I maybe am making a mistake

- Spun up mautic using gitpod with PR applied
- Created contact - showed UTC time stamp
- Adjusted global config to my time zone UTC + 2hrs
- Contact still showed UTC time stamp. 
- Sent an email - email sent time stamp was UTC
- Edited contact to Johannesburg time stamp (UTC +2)
- Contact still shows UTC
- Sent another email - still shows email sent time stamp as UTC. 

Am I testing incorrectly maybe?

**Comment by volha-pivavarchyk** [comment]
I added a new custom field and set it for 7 pm. My result is
1. on the current branch:
image
 
2. on 5.x:
image

Maybe my steps were wrong?

**Comment by RCheesley** [comment]
@all-contributors please add @doppelD-LF for usertesting

**Comment by RCheesley** [comment]
@all-contributors please add @Robmobius for userTesting

**Comment by RCheesley** [comment]
Thanks for testing @doppelD-LF @Robmobius @volha-pivavarchyk - @kuzmany could you please review the test instructions as folks seem to be struggling to test this successfully.

**Review by mabumusa1 — APPROVED** [review]
It works as expected, I created a custom field of type time and filled with UTC +2 (which was configured as the system default), then I changed my user's timezone to PST and it worked as expected. 

I think this one is good to go, thanks @kuzmany  

image

**Comment by escopecz** [comment]
@kuzmany as there are open PRs for LeadBundle's PHP to Twig refactoring then this will not be applied to the Twig templates. See https://github.com/mautic/mautic/pull/11820. Can you add this change to this twig file? https://github.com/mautic/mautic/pull/11820/files#diff-7f80fe47daf14bb8314cd219a8edcc9d4c43f5f7735b27595bc9b10b343dd132

**Comment by RCheesley** [comment]
@kuzmany a conflict to be resolved here, will need retesting after resolved I think.

**Comment by kuzmany** [comment]
Mautic5 stores time without converting to UTC. Then we display the value from the db directly. Do not need

**Pull request closed without merging**
