### PR TITLE
Text message type visible in categories page

### PR DESCRIPTION
**Pull request by aarohiprasad**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ Yes]
| New feature/enhancement? (use the a.x branch)      | [ NA]
| Deprecations?                          | [ NA]
| BC breaks? (use the c.x branch)        | [No ]
| Automated tests included?              | [ No] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Category type was not showing up for SMS on categories page. This PR fixes that. 
image

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Configure Twilio plugin to enable Text Messages.
3. Go to Text Messages and click on New button to create text message.
4. Select "New Template Text Message" type 
image

5. Select create category from category dropdown.
6. Create new category
7. Fill required fields for text message and save it.
8. Go to category list page you will see the populated type column for newly created category 
image

### CODE REVIEW

**Comment by escopecz** [comment]
@aarohiprasad please check the failing tests. Perhaps this change depends on some PR that we haven't pushed yet?

**Review by kuzmany — DISMISSED** [review]

**Review by mabumusa1 — DISMISSED** [review]
Changes are correct. Thanks @aarohiprasad .

Please fix the failing tests, so we can merge it

**Comment by RCheesley** [comment]
@aarohiprasad please can you address the failing tests so we can test and consider this for merging. Thanks!

**Review by fedys — APPROVED** [review]
Thanks @aarohiprasad!

**Review by escopecz — APPROVED** [review]
Makes sense 👍

**Pull request merged**
