### PR TITLE
Fix for Emails sent Report duplicates with campaign columns

### PR DESCRIPTION
**Pull request by patrykgruszka**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? |N
| Related user documentation PR URL | N
| Related developer documentation PR URL | N
| Issues addressed (#s or URLs) | 
| BC breaks? | N
| Deprecations? | N

[//]: # ( Required: )
#### Description:
Reports based on Emails Sent data source will contain duplicated rows when any campaign field is selected and that campaign has an action event (e.g Email read) based on emails sent.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create new template email
2. Create segment
3. Create campaign based on that segment with action **Send mail** and decision **Opens email**
image
4. Add contact to this campaign and trigger **all** campaign elements (open email)
5. Create report based on Emails Sent data source with campaign field as column
image
6. Generated report will contain double rows for this contact
image

#### Steps to test this PR:
1. Load up [this PR](https://m3.mautibox.com)
2. Repeat steps to reproduce

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@patrykgruszka could you take a look and resolve the conflict (in addition to signing the contributors agreement!) :)

**Comment by mabumusa1** [comment]
@patrykgruszka we would love to get this PR into the next release of Mautic, do you mind take a look into the pending issues and conflicts?

**Comment by mabumusa1** [comment]
@RCheesley I wrote an automated test for this file, I think this test will cover this issue 

https://github.com/mautic/mautic/pull/8746#issuecomment-684605285

**Comment by RCheesley** [comment]
@patrykgruszka we cannot merge this PR until you sign the contributors agreement - bumping  this to 3.1.2 as a result. Please can you sign no late than **18th October** so that we can merge this in the next release?

**Comment by RCheesley** [comment]
@cla-bot check

**Review by kuzmany — DISMISSED** [review]
Works for me 👍

**Review by RCheesley — DISMISSED** [review]
Confirmed the bug - one person who opened the email had a duplicated entry:

screenshot-local mautic3-2020 11 20-20_39_08

After the fix, only appears once in the report as expected:

screenshot-local mautic3-2020 11 20-20_39_37

**Comment by RCheesley** [comment]
@mabumusa1 is there some way to bring the test into this PR so that we can get the coverage up?

**Comment by mabumusa1** [comment]
@RCheesley this PR https://github.com/mautic/mautic/pull/9311 should cover the changes in this file

**Comment by kuzmany** [comment]
I found bug in these PR, I will back with solution today

**Comment by kuzmany** [comment]
I found this PR caused error with any emails report without campaign ID or campaign Name column. Last commit fixed it

**Comment by kuzmany** [comment]
I marked it as blocked. This bring some issue to us, we have some improvements, but need more time to cherry pick

**Comment by dennisameling** [comment]
Hi @patrykgruszka! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since this PR has conflicts now, could you please do a `git merge upstream/features` locally to resolve the conflicts? Thanks in advance!

**Comment by RCheesley** [comment]
@patrykgruszka please can you bring in the latest changes from the Features branch and address the conflict?

@kuzmany did you figure out the issues that you mentioned were arising from this?

**Comment by kuzmany** [comment]
@RCheesley Yes, we have used this PR, but need additional fix. I have to check it and try cherry pick. I let you know

**Comment by RCheesley** [comment]
OK perfect!

**Comment by kuzmany** [comment]
I've made PR https://github.com/mautic/mautic/pull/10102 what should fixed this issue. Please test

**Pull request closed without merging**
