### PR TITLE
Switch to skip empty decrypted keys instead of returning empty array and dropping other keys

### LINKED ISSUE #10573: Integration apiKeyDecrypt implementation clears all data if a yes/no question answered to false
### Mautic Version

4.0.0

### PHP version

all

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Clearbit API key is cleared on every use. Impossible to use the integration

### How can we reproduce this issue?

1. Set up clearbit integration by providing a token (even a wrong one)
2. Set "Automatically update on save?" to "No"
3. Save plugin settings
4. Reopen settings - the api key is gone

The api key is also cleared in the database.

----

I've debugged the flow and the reason is quite simple. "No" answers are saved as false.

AbstractIntegration::decryptApiKeys looks like this:

```php
public function decryptApiKeys(array $keys, $mainDecryptOnly = false)
    {
        $decrypted = [];

        foreach ($keys as $name => $key) {
            $key = $this->encryptionHelper->decrypt($key, $mainDecryptOnly);
            if (false === $key) {
                return [];
            }
            $decrypted[$name] = $key;
        }

        return $decrypted;
    }

```
    
The api key is properly decrypted, but then the auto_update value is also properly decrypted as false, and matches the if statement `if (false === $key)` - an empty array is returned and as a result `getDecryptedApiKeys` clears the keys in the database.

This is an obvious bug, probably influencing also other plugins.

My suggestion would be to decrypt all keys, and only return an empty array if all were false. Happy to provide the code if this is the right solution. 

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mkurzeja**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          |  yes
| New feature/enhancement? (use the a.x branch)      |  no
| Deprecations?                          |  no
| BC breaks? (use the c.x branch)        |  no
| Automated tests included?              |  no change
| Related user documentation PR URL      |  -
| Related developer documentation PR URL |  -
| Issue(s) addressed                     | Fixes #10573

#### Description:

Changes slightly the behavior of AbstarctIntegration::decryptApiKeys in order to not drop all settings when one setting is set to false. 

Note: This might also apply to previous versions - 3.x etc.

#### Steps to test this PR:

See #10573

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10574"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

Thanks for making the PR @mkurzeja !

**Comment by mkurzeja** [comment]
Not sure why the coverage is marked as decreased on files I did not touch at all.

**Comment by RCheesley** [comment]
@mkurzeja we have a problem at the moment with the 4.0 branch relating to codecov. It's not something you've done! We're trying to get to the bottom of it (it's blocked the 4.0.2 release 😭 ).

**Comment by RCheesley** [comment]
Could you please rebase this against the 4.x branch? Thanks!

**Review by npracht — APPROVED** [review]
We tested it and it solves an issue with Pipedrive integration

**Comment by mkurzeja** [comment]
@RCheesley rebased

**Review by kuzmany — APPROVED** [review]

**Pull request merged**
