### PR TITLE
Integrations field fix

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.0
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | /
| Related developer documentation PR URL | /
| Issue(s) addressed                     | /

#### Description:

When integrations want so get changed fields by `ChangeObjectDAO::getChangedFields()` to push their values to the integration, they get only required fields when the fields were created with `FullObjectBuilder` (not `PartialObjectBuilder`). Other fields were considered unchanged. My change will let the builder define what the default state the fields should be created with.

[//]: # ( As applicable: )
##### Bug in form push:
1. Configure an integration built on top of the IntegrationsBundle (I know, this is hard to find) Make sure that you have all required and also First Name fields mapped for the Lead object.
2. Create a standalone form with fields: Email, Last Name, First Name, company. Map them to Mautic contact fields.
3. Add the Push to the integration form action
4. Submit the form with all fields filled in.
5. Check the integration#### Description:
When integrations want so get changed fields by `ChangeObjectDAO::getChangedFields()` to push their values to the integration, they get only required fields when the fields were created with `FullObjectBuilder` (not `PartialObjectBuilder`). Other fields were considered unchanged. My change will let the builder define what the default state the fields should be created with.

[//]: # ( As applicable: )
##### Bug in form push:
1. Configure the integration built on top of the IntegratioonsBundle. Make sure that you have all required and also First Name fields mapped for the Lead object.
2. Create a standalone form with fields: Email, Last Name, First Name, company. Map them to Mautic contact fields.
3. Add the Push to the integration form action
4. Submit the form with all fields filled in.
5. Check the integration that the lead was created, but the First Name is empty.

##### Bug in update object sync:
1. Create a new Mautic contact with Email, First Name and Last Name.
2. Run sync.
3. Check the integration. The contact does not exist which is correct. It's missing one required field: Company.
4. Now, add a company to the Mautic contact, save.
5. Run sync.
6. Check the integration. The contact exists now. However, it does not have First Name.

##### Bug in form push:
2. Submit the form again with some other email address
3. Check the integration that the lead was created and the First Name is filled with your value. that the lead was created, but the First Name is empty.

##### Bug in update object sync:
1. Create a new Mautic contact with Email, First Name and Last Name.
2. Run sync.
3. Check the integration. The contact does not exist which is correct. It's missing one required field: Company.
4. Now, add a company to the Mautic contact, save.
5. Run sync.
6. Check the integration. The contact exists now. However, it does not have First Name.

##### Bug in form push:
2. Submit the form again with some other email address
3. Check the integration that the lead was created and the First Name is filled with your value.

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@escopecz @kuzmany @mabumusa1 are there any integrations that you can suggest we use to test this PR?

**Comment by mabumusa1** [comment]
@RCheesley unfortunately I do not

**Comment by escopecz** [comment]
There was https://github.com/mautic-inc/plugin-vtiger but as we don't have any customers on Vtiger anymore it might be dated. @kuzmany do you have something?

**Review by dennisameling — COMMENTED** [review]
@escopecz I tried reproducing this bug with Mautic's built-in vTiger integration, but the leads are created correctly. The first name is in there before and after applying this PR:

image

I checked Acquia's [`mc-cs-plugin-vtiger`](https://github.com/mautic-inc/plugin-vtiger) like you mentioned, but it doesn't have any reference to [getChangedFields()](https://github.com/acquia/mc-cs-plugin-vtiger/search?q=getChangedFields%28%29). Since nobody came up with a plugin that uses this functionality, I think we have two options in order not to waste more time:

1. Close this PR
2. Approve & merge this PR based on only a code review (code looks good IMO and includes automated tests)

Any thoughts on this?

**Comment by escopecz** [comment]
I agree with your 2 choices. I would rather go with the option 2 as we build all our new CRM plugins on top of this bundle and I hope that the community will start too. In that case I'd love to have it in a good shape.

The Vtiger bundle is no longer maintained as no customer of ours is using it for over a year.

**Review by dennisameling — APPROVED** [review]
Code LGTM and includes automated tests 👍🏼

**Review by kuzmany — APPROVED** [review]
I was able to reproduce it on our custom integration and works for me 👍

**Pull request merged**
