### PR TITLE
fix contact merging issue when mutliple unique identifiers are being used

### LINKED ISSUE #8948: Contact import is not merging based on more than one unique identifier fields
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Trying to upload contacts via CSV, but it is not merging data based on more than one unique identifier fields. It just merge them into one.

| Q   | A
| --- | ---
| Mautic version | 2.16.0
| PHP version | 7.1 
| Browser | any

### Steps to reproduce
1. Make more then one custom fields for contacts and choose "unique identifier" for them;
2. Upload CSV file to Contacts;
3. No merged contacts according to the defined unique identifiers, it merged them into one contact.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by cahaynes**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.1
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Issue(s) addressed                     | Fixes #8948

#### Description:

When multiple unique identifiers are used to determine the uniqueness of a contact, Mautic uses an OR condition whereas an AND condition would be desirable.  The OR condition can cause unintended merging of contacts since the uniqueness of a contact could be determined by only one of the unique fields.  Whereas, if a user wants to identify a contact by multiple unique fields then the combination of all unique fields should be used to determine uniqueness, that is, with the AND condition.

This PR is derived from PR #8997 

#### Steps to Reproduce Issue

1. Add a new custom field with the label **unique_field_1** and set _Is Unique Identifier_ to _Yes_
2. Add a new custom field with the label **unique_field_2** and set _Is Unique Identifier_ to _Yes_
3. Edit the **Email** field and set _Is Unique Identifier_ to _No_
4. Edit the **Company Email** field and set _Is Unique Identifier_ to _No_
5. Create a simple CSV file that has at least the following columns and rows:

email|unique_field_1|unique_field_2
------------ | ------------- | -------------
1@example.com|1|1
2@example.com|1|2
3@example.com|1|3
4@example.com|1|4

6. Import the CSV into Contacts
7. Once imported, Mautic will indicate that only 1 new contact was created and 3 of them were merged.

#### Steps to Test PR
1. Use the same Mautic field configuration and CSV used in the Steps to Reproduce Issue, i.e., steps 1-5.
2. Remove the Contact added in the Steps to Reproduce Issue (optional)
3. Go to **Settings>Configuration** and under the _Miscellaneous Settings_ change the "Set condition for joining unique fields" from OR to AND
4. Click _Save & Close_ .
5. Import the CSV into Contacts
6. Once imported, Mautic will indicate that 4 new contacts were created.
    If Step 2 was skipped, then it should indicate 1 contact was merged and 3 new contacts were created.

### CODE REVIEW

**Comment by cahaynes** [comment]
@RCheesley I just cherry-picked the changes from @WaldemarOrobanche, will this still be an issue with CLA?  I am sure I could fix the commit to be solely from me if needed.

**Comment by cahaynes** [comment]
@RCheesley I just went ahead made sure that I was the only contributor for the commit.

**Comment by RCheesley** [comment]
Hi @cahaynes thanks for getting this sorted, I'm sorry we ran out of time to test this for the 3.1.1 release so I am bumping it back to 3.1.2.

This means that we need to get it tested  by **18th October** to include it in the release - should be feasible!

**Comment by cahaynes** [comment]
Sounds good.  Thanks @RCheesley!

**Comment by kuzmany** [comment]
Thank you for nice addition. 
This is backwards compatibility change and need add new option/parameter to enable this behaviour.

**Comment by cahaynes** [comment]
@kuzmany thank you for your feedback.  Were you thinking about a parameter being added to this config: https://github.com/cahaynes/mautic/blob/issue_8948/app/bundles/LeadBundle/Config/config.php#L1301

**Comment by cahaynes** [comment]
@RCheesley I made the suggested change from @kuzmany by exposing a new Choice component in the Miscellaneous Settings within Configuration.  Also, noticed the function **getLeadIdsByUniqueFields** uses a similar query and I updated that query to use the same parameter as the function **getLeadsByUniqueFields** uses.  Doing a quick grep for the **getLeadIdsByUniqueFields** function, I didn't see that it was being used but figured consistency would be good in case it's used in the future.  Lastly, I updated the Steps to Test PR to reflect the new changes.

**Comment by cahaynes** [comment]
Looks like I misunderstood the error.  If anyone can give me any suggestions of what I need to do, that would be greatly appreciated.

**Comment by dennisameling** [comment]
@cahaynes thanks so much for your work on this - we're almost there! Tip: You can also run the failing tests locally by running `composer test -- app/bundles/LeadBundle/Tests/Model/LeadModelTest.php` in your terminal.

The tests were failing because of the following:

```PHP
$mockLeadModel = $this->getMockBuilder(LeadModel::class)
            ->disableOriginalConstructor()
            ->setMethods(['getRepository'])
            ->getMock();
```

Because of the `disableOriginalConstructor()`, all properties that are normally set in `LeadModel`'s constructor (also `CoreParametersHelper`) aren't available. That's why you're getting `Error: Call to a member function get() on null`. `$this->coreParametersHelper` is not set.

The solution is to do `setProperty()` which allows you to set the `coreParametersHelper` property manually so that it will be available in the `mockLeadModel`. I just committed that in https://github.com/mautic/mautic/pull/9216/commits/3ee2d9c5c301bcec36ed42eae4849a48afc25127. 

Let's see if CI will pass now 😊 

Side note, I saw that your PR changed the file permissions on one file from `755` to `644`. Could you please chmod it back to 755? Thanks 🚀 

image

**Comment by cahaynes** [comment]
@dennisameling thank you so much for the explanation and your fix.  I'll admit I did try running the tests locally but I was hitting some unrelated errors but I think I was invoking it incorrectly.  Also, I updated the file permission as you mentioned.

Thanks again!

**Comment by RCheesley** [comment]
@cahaynes thanks for your work on this and for getting the tests to pass!

We just need to get this tested so that we can merge in 3.2 - would be great to try and get this done in the forthcoming sprints!

**Comment by kuzmany** [comment]
This not cover all places where we are using the unique fields processing duplications.
Then I make same as feature with cover all situation works with contacts merge 
Then I close this and I will support new PR until merge to official repo https://github.com/mautic/mautic/pull/9452
Test would be appreciate

**Pull request closed without merging**
