### PR TITLE
UI warnings when unpublish associated segment

### PR DESCRIPTION
**Pull request by dadarya0**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | https://github.com/mautic/mautic-documentation/pull/207
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

Currently if a segment filter is using another segment as a source, and that source is unpublished, the segment will disappear from the segment membership filter.

This is expected behavior as unpublished segments are not available to segment filters, however this can cause issue when the filter ends up empty, leading to all contacts being added to the segment, which can be resource intensive.

**Solution :** 
Now we will warn the user that the segment is used as a filter within another segment and block them from unpublishing

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. Create a segment - S1
2. Create another segment - S2
3. In S2 segment, add segment membership filter and use segment S1 as value
4. Save & Close
5. Now Unpublish segment S1
6. S1 should not be unplublish and should show a warning message.

#### Other areas of Mautic that may be affected by the change:
1.
2.

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Review by RCheesley — DISMISSED** [review]
Thanks for this PR @dadarya0 - indeed a useful feature to stop people making costly mistakes!

Could you please make a PR to the documentation to add information about this feature (just a short addition to the segments page would be great) and explain how people can find the relevant segments they need to modify? I feel like that might be helpful for the less experienced marketer in case they don't understand what the error means.

**Comment by RCheesley** [comment]
Documentation PR is here: https://github.com/mautic/mautic-documentation/pull/207

**Comment by dadarya0** [comment]
> Documentation PR is here: [mautic/mautic-documentation#207](https://github.com/mautic/mautic-documentation/pull/207)

@RCheesley I have seen that you raised a Documentation PR for warning on delete segment but My PR is showing warning when user unpublished a segment so should I edit [PR](https://github.com/mautic/mautic-documentation/pull/207) for same or raise a new PR for unpulished ?

**Comment by RCheesley** [comment]
@dadarya0 when I tested the PR, I tested it by trying to delete the segment, so I'm guessing that it already works for both unpublish and delete. Will re-test to confirm!

**Comment by RCheesley** [comment]
@dadarya0 confirmed that this PR provides the warning both on delete and unpublish. I will update the docs PR accordingly!

**Comment by dadarya0** [comment]
> @dadarya0 confirmed that this PR provides the warning both on delete and unpublish. I will update the docs PR accordingly!

@RCheesley Actually for delete it was already implemented and for Unpublished I have implemented in this PR.

You have to review PR again, due to resolve conflict review has been dismissed.

**Comment by RCheesley** [comment]
@dadarya0 ahhh OK sorry that was not clear to me from the description, thanks for clarifying!

**Review by RCheesley — DISMISSED** [review]

**Comment by RCheesley** [comment]
Just requires a code review/test from one of the team then we will be good to go!

**Comment by escopecz** [comment]
@RCheesley @dadarya0 is our team member. We run it in production, so we as well approve :)

**Review by kuzmany — CHANGES_REQUESTED** [review]
media/css/app.css and media/js/app.js should not be part of PR, these files are generate on  release

**Review by kuzmany — DISMISSED** [review]
I tested it and works as charm. Great and useful PR 

image


@dadarya0 just remove that media files

**Comment by dadarya0** [comment]
> media/css/app.css and media/js/app.js should not be part of PR, these files are generate on release

@kuzmany Media file are removed from this PR. Thank you

**Comment by RCheesley** [comment]
Thanks for making the changes folks - @kuzmany assume this is good with you since the files have been removed as requested!

**Pull request merged**
