### PR TITLE
Fix form field campaign condition with special character in value

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 4.0
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
Form field condition made wrong condition If value contain special character like `&`

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Crete campaign form with email field
3. Create select field with one value `test & test`
4. Then create campaign with source of this form
5. Then create condition form field value with you select field condition equal `test & test`
6. Submit form
7. Trigger campaign actions
7. See your contact was not passed by condition
8. After PR should go to true

### CODE REVIEW

**Comment by jos0405** [comment]
I tested this, works:
image
image
image

**Review by jos0405 — COMMENTED** [review]
Tested, works.

**Review by jos0405 — DISMISSED** [review]

**Review by npracht — COMMENTED** [review]
👍🏽 this is working for me too. But we need a code review.
@mohit-rocks are you okay to give a look at the code ?

Thanks !

**Review by escopecz — DISMISSED** [review]
I added a functional test. It works as described 👍

**Review by escopecz — APPROVED** [review]
👍

**Pull request merged**
