### PR TITLE
[type-declarations] Add known void return type to /plugins

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Rebased and ready to go :+1:

**Comment by TomasVotruba** [comment]
Good to go :+1:

**Review by kuzmany — APPROVED** [review]
Seems good to me 👍

**Review by escopecz — APPROVED** [review]
Phpstan would tell us if some return type would be off. Good to go 👍 Thank you Tomas!

**Pull request merged**
