### PR TITLE
[UI] Fields

### LINKED ISSUE #13156: Align forms to the design system
### Description
Forms within the application do not currently align with the established design system, causing inconsistency and a disjointed user experience; the goal is to bring forms in line with the design system's guidelines.

### Impact
Aligning forms with the design system will create a cohesive and visually appealing interface, improving user familiarity, usability, and overall design consistency throughout the application.

### Tasks

- [x] Text input
- [ ] Number input
- [x] Selection field
- [ ] User made forms

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #13156 

## Description

This PR is based [on another PR](https://github.com/mautic/mautic/pull/13735), where I introduce tokens to replace most of the UI variables, aiming to improve consistency in all components. **We need it to be merged before this one becomes available for code review.**

This PR changes fields style and adds support for dark theme.

---

When border-radius is set to 0 on the brand center ([tokens approach](https://github.com/mautic/mautic/pull/13735)), fields receive a bottom border. When border-radius be >0, the border disappears to create an alternate style. Useful for branding.

https://github.com/mautic/mautic/assets/116097999/500f48cc-13ff-4b2a-97a5-6c341fd1984f

---

All libraries aligned to look exactly the same.

https://github.com/mautic/mautic/assets/116097999/4b91bebd-ec2d-4e12-9003-447422f84e3a

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Contacts > New > See the fields
3. Top navbar > Account > See the fields
4. Interact with them

### CODE REVIEW

**Review by kuzmany — COMMENTED** [review]
I found some inconsistent things, but in general looks good.

image

image

it is dropdown or not?
image

**Review by shinde-rahul — COMMENTED** [review]
Similar observations as @kuzmany .
-  For report fields, the `ms-search` is adding extra `5px` that is might be the reason.

**Comment by andersonjeccel** [comment]
Thanks for testing, I’ll address it soon

@shinde-rahul Did you notice any different place where things weren’t right?

I’m afraid to leave something behind

**Review by LordRembo — CHANGES_REQUESTED** [review]
Again same remark as I had on a few other PR's, I think a bunch of variable changes and restructuring (probably in relation to enabling dark-mode possibilities) would be better off split into their own PR, after getting some of the system rework PR's merged.
I think this PR is the 4th I've seen with the same changes to builder.css (and some other elements).

**Comment by andersonjeccel** [comment]
### How to test dark mode?
1. Open dev tools on your browser (F12)
2. Open the Console tab
3. On the field, paste `document.documentElement.setAttribute('color-theme', 'dark');` and hit Enter
4. The components changed by the specific PR you're seeing will become dark

**Review by LordRembo — APPROVED** [review]
Okay, so a lot of small styling changes to allow for use of CSS variables and restyling of the various form elements (including search). I don't really have a design opinion but looks clean & it's something we can build on for customisation later so it all makes sense I think.

**Review by kuzmany — APPROVED** [review]
Looks good 👍
Only the rough outline focuses, but others can decide about it.

image

**Comment by andersonjeccel** [comment]
@kuzmany The outline is intentional actually
You can also see them already (5.x branch) that dropdowns show it when you use your keyboard arrows to navigate 

Thanks for testing! 😉

**Pull request merged**
