### PR TITLE
[dead-code] Symplify useless variable assign, remove redundant null param

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
~~The `@param null $param` was hiding a lot of missing param types. I had to rebuild baselines to show these.
Those should be fixed, but that's work for another PR.~~

It will be better to handle in separate PR, as currently CI is failing for the baseline a lot. Let's keep it simple :)

Ready for review :+1:

**Comment by TomasVotruba** [comment]
The maria db test seems false positive due to coverage website to fail.

**Comment by escopecz** [comment]
@TomasVotruba would you mind resolving the conflicts?

**Comment by TomasVotruba** [comment]
Sure, give me 5 mins

**Review by escopecz — DISMISSED** [review]
This is a no-brainer PR. All the changes are correct in my eyes and must be correct otherwise PHPSTAN would scream. Thank you! 👍

**Comment by escopecz** [comment]
But it seems that Rector found another line to remove after the rebase :)

**Comment by TomasVotruba** [comment]
Indeed :) should be good now

**Review by escopecz — APPROVED** [review]

**Comment by TomasVotruba** [comment]
This one is ready for me. Let me know if there is something needed from me to finish it :+1:

**Comment by TomasVotruba** [comment]
:+1:

**Pull request merged**
