### PR TITLE
Fix form set config SDK

### LINKED ISSUE #9951: Forms are not able to submit
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Forms are not able to submit in preview or everywhere. 

image

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Fix for https://github.com/mautic/mautic/issues/9951
This https://github.com/mautic/mautic/commit/8b4cd18285b69ecd5f0caefed9d9522ba219ba48 add to generate url param to url to refresh resource on new version of Mautic.
This param produce  issue for Mautic forms 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Try create and submit form
3. Should works like before

### CODE REVIEW

**Comment by RCheesley** [comment]
@kuzmany do we need to regenerate assets or rebuild the form cache to test? Or should it work out of the box?

**Comment by kuzmany** [comment]
Yes, on prod enviroment.
Not in dev enviroment

**Review by RCheesley — APPROVED** [review]
Reproduced the bug on testing forms, with the PR applied it had resolved the error and the forms are now submitted as expected!

Thanks for jumping on this @kuzmany !

**Comment by RCheesley** [comment]
Just re-running the tests as the failure was due to a temporary server error according to the logs.

**Review by mohit-rocks — APPROVED** [review]
Code changes look good. I tried the patch on local for testing and it seems working fine.
I tried to embed the form in simple HTML and the issue seems to be reproducible. Patch fixes the issue.
Attaching both the screenshots.

Before applying the patch:
MautiCon_2020

After applying the patch:
MautiCon_2020

**Comment by RCheesley** [comment]
Awesome, thank you for testing @mohit-rocks - LGTM! 🚀

**Comment by RCheesley** [comment]
@all-contributors please add @mohit-rocks for userTesting

**Comment by RCheesley** [comment]
@all-contributors please add @mohit-rocks for review

**Pull request merged**
