### PR TITLE
Fix filemanager absolute url

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.2
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:

Noticed interested bug in file manager. This PR fixed it.

#### Steps to test this PR:

See video how to reprouce it: http://youtu.be/POHK5LQ5PBg?hd=1

1. Load up [this PR](https://mautibox.com).
2. Go to emails, try create email.
3. Edit text slot and try insert image - upload new image by file manager

image

4. Click on new uploaded image 
5. After insert to editor, check source of it
6. Without patch URL of image look like `/staging/efconnect?cmd=file&amp;target=fls1_bXRjLlBORw`. We expected absolute URL in format `https://mautibox.com/staging/media/images/mautic_logo_db64.png`

### CODE REVIEW

**Review by adiux — CHANGES_REQUESTED** [review]
I could not verify that the image uses the correct format.

**Steps**

1. Generate Assets
image

2. Load FileManager
image

3. Upload and select logo
image

4. Logo url is still in the old format (http://mtc-adiwegs.ddev.site/efconnect?cmd=file&target=fls1_bWF1dGljLWxvZ28tdGVzdC5wbmc):
image

**Review by RCheesley — COMMENTED** [review]
Also unable to reproduce this:

screenshot-nimbus-capture-2020 10 10-19_43_43

**Comment by kuzmany** [comment]
@RCheesley @adiwegs I was able to reproduce on mautibox  (open filemanager, drag&drop image and check source of editor)

image

**Comment by adiux** [comment]
@kuzmany I'm able to reproduce it when I drag and drop the image without opening the file manager. However, if I open the file manager, and upload the image first, then select it (as shown in my print screen above) the path seems to be the same as before. Image one came from the file manager. Image two was a direct drag and drop: 
image

**Comment by escopecz** [comment]
@kuzmany I also cannot reproduce I followed your latest steps:

> open filemanager, drag&drop image and check source of editor

But when I view the source code in the Froala editor I can see the image with absolute URL:
```html
<img src="https://mautic-community.local/media/images/755440d5c5f1e3335c235c3d77172b21.png" class="fr-fic fr-dib" data-ignore_wdt="1" width="736" height="1281">
```

**Comment by kuzmany** [comment]
This is how you could reproduce http://youtu.be/POHK5LQ5PBg?hd=1
I've made update, because it some cases still doesn't work.

This is hard fix,  because I was not able to fix it on elfinder bundle side.

**Review by escopecz — DISMISSED** [review]
I was able to reproduce:
```html
<img src="/efconnect?cmd=file&amp;target=fls1_U2NyZWVuIFNob3QgMjAyMC0xMi0wOSBhdCAwOC41Mi40NS5wbmc" class="fr-fic fr-dib" width="878" height="458">
```
With this PR I get the full image URL:
```html
<img src="https://mautic-community.local/media/images/Screen Shot 2020-12-07 at 14.08.26.png" class="fr-fic fr-dib" width="1074" height="272">
```

**Pull request merged**
