### PR TITLE
[UX] Change right sidebar icon on the navbar

### LINKED ISSUE #13327: [UX] Confusion over settings icon used for left sidebar menu
### Description
There is confusion over the settings icon used for the left sidebar menu. Users may not understand its purpose or may mistake it for a different function. This issue can be resolved by changing the icon to be more intuitive.

### Impact
Addressing this issue would improve the user interface and make the platform more user-friendly. It would reduce confusion and enhance navigation, leading to a more efficient and satisfying user experience. This would be particularly beneficial for new users who are still familiarizing themselves with the platform.

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #13327 

### Description:

The use of a settings icon for a button responsible for showing or hiding the right sidebar does not intuitively convey its function. This can lead to confusion and misinterpretation among users, hindering their ability to effectively navigate and utilize the platform.

This issue is largely due to the outdated icon package currently being used by Mautic. Font Awesome do not have a sidebar icon or something closer to it. As the platform has evolved over the years, the icon package has not kept pace, resulting in a lack of accurate representation for certain actions. This highlights the need for a more comprehensive and up-to-date icon package that can accurately represent the platform’s features and functionalities.

Unfortunately, this is not an isolated issue but rather one of many stemming from the current icon package. It underscores the urgent need to transition to a more complete icon package that can better serve the platform’s needs.

In another pull request, I have already requested the integration of a new icon package. The changes proposed in this PR are dependent on the successful merging of that request. By updating the icon package, we can significantly improve the user interface and overall user experience, making the platform more intuitive and user-friendly.

### Impact

Addressing this issue would improve the user interface and make the platform more user-friendly. It would reduce confusion and enhance navigation, leading to a more efficient and satisfying user experience. This would be particularly beneficial for new users who are still familiarizing themselves with the platform.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Look on the navbar for the new icon

image

### CODE REVIEW

**Review by LordRembo — APPROVED** [review]
Seems like a good replacement

**Review by Mike-Dropsolid — CHANGES_REQUESTED** [review]
The cog icon does imply configuration/settings behind it. But there's more in that sidebar that isn't 'configuration'.

While it makes sense, I'm not 100% the icon you propose is the best fit. Are there other options?

**Comment by andersonjeccel** [comment]
> The cog icon does imply configuration/settings behind it. But there's more in that sidebar that isn't 'configuration'.
> 
> While it makes sense, I'm not 100% the icon you propose is the best fit. Are there other options?

A toggle icon wouldn't be good because it wouldn't change when you click.

image

A menu icon wouldn't be good because it could confuse people since when you toggle a panel and the other one is hidden. 
It would sound like 1 button for 2 menus when you already have the option to collapse the first one. 

image


image

So it could be better to use a menu icon only for the left sidebar toggle between complete and icon-only.

**Comment by Mike-Dropsolid** [comment]
> > The cog icon does imply configuration/settings behind it. But there's more in that sidebar that isn't 'configuration'.
> > While it makes sense, I'm not 100% the icon you propose is the best fit. Are there other options?
> 
> A toggle icon wouldn't be good because it wouldn't change when you click.
> 
> image
> 
> A menu icon wouldn't be good because it could confuse people since when you toggle a panel and the other one is hidden. It would sound like 1 button for 2 menus when you already have the option to collapse the first one.
> 
> image
> 
> image
> 
> So it could be better to use a menu icon only for the left sidebar toggle between complete and icon-only.

Not convinced about any better solution. I'd go with your first suggestion.

**Review by Mike-Dropsolid — APPROVED** [review]
Looks good

**Comment by code5rick** [comment]
The icon suggested for the configuration bar to open is not ideal. While it indicates that the sidebar will open on the left side, it will actually open on the right side. For further context, I will provide a screenshot of how the Font Awesome sidebar icon appears.
image

By changing the configuration wheel icon to the sidebar icon, users might initially struggle to find where to access the settings. It's common for users to associate the wheel icon with accessing configurations. Keeping the wheel icon, but updating it to the latest version, maintains familiarity while accurately representing the sidebar's function as a hub for all Mautic configurations. This approach ensures users retain a visual cue for accessing settings, reducing confusion and the need to search for them elsewhere.

@Mike-Dropsolid

**Comment by Mike-Dropsolid** [comment]
> The icon suggested for the configuration bar to open is not ideal. While it indicates that the sidebar will open on the left side, it will actually open on the right side. For further context, I will provide a screenshot of how the Font Awesome sidebar icon appears. image
> 
> By changing the configuration wheel icon to the sidebar icon, users might initially struggle to find where to access the settings. It's common for users to associate the wheel icon with accessing configurations. Keeping the wheel icon, but updating it to the latest version, maintains familiarity while accurately representing the sidebar's function as a hub for all Mautic configurations. This approach ensures users retain a visual cue for accessing settings, reducing confusion and the need to search for them elsewhere.
> 
> @Mike-Dropsolid

Good point about the side the sidebar is being opened.

"It's common for users to associate the wheel icon with accessing configurations." For sure. But that's the point, right? It's not just configuration that is located in the sidebar. Or is it close enough?

@andersonjeccel There's no perfect solution to replace the current icon with. Maybe we should just go with what Ricardo is proposing? At least we won't confuse current users.

**Comment by LordRembo** [comment]
There was a concern raised in[ PR #13375](https://github.com/mautic/mautic/pull/13375#pullrequestreview-1897640082), by John, which is that the documentation might have to change as well.
@andersonjeccel could you check if there are mentions of the 'cog' icon name in the user documentation & labels in Mautic itself, and replace those?
Maybe a more neutral description, instead of using an icon name, would work better? Especially if another redesign might change icons again further down the road.

**Comment by andersonjeccel** [comment]
@Mike-Dropsolid 

That button acts as a sidebar toggle. When the left sidebar is visible, the toggle will display the right sidebar

However, when the right sidebar is open, clicking on it will make the left sidebar visible

If we are concerned that the toggle should represent the right sidebar, it would be necessary to update Mautic’s right sidebar behavior so that it appears above the page content and does not cause the left sidebar to hide
As we dive deeper, complex UX problems start to appear, but perhaps a more secure way would be to focus on small possible changes and leave a discussion about it in the future...

Also, I’m not sure if Mautic’s cash flow can handle $499/year for this suggestion... I checked financial data on Open collective and through conversations with Ruth. There’s also a license compatibility issue since newer versions of FontAwesome have become paid

Ricardo might need to think deeper, search, verify licence compatibility, check references, check user experience researches, weigh the pros and cons of each idea and outline a logical explanation for each, associate with the platform behaviour, check if a change causes a need to change behaviours or workflow, consider the effort of extra changes and plan how to implement on a code perspective

We could replace manually using a SVG, but it would break the consistency of the platform and make the code scattered over time as certain parts would use icons from the pack while others would use SVG

I'll leave the choice for you

**Comment by Mike-Dropsolid** [comment]
> @Mike-Dropsolid
> 
> That button acts as a sidebar toggle. When the left sidebar is visible, the toggle will display the right sidebar
> 
> However, when the right sidebar is open, clicking on it will make the left sidebar visible
> 
> If we are concerned that the toggle should represent the right sidebar, it would be necessary to update Mautic’s right sidebar behavior so that it appears above the page content and does not cause the left sidebar to hide As we dive deeper, complex UX problems start to appear, but perhaps a more secure way would be to focus on small possible changes and leave a discussion about it in the future...
> 
> Also, I’m not sure if Mautic’s cash flow can handle $499/year for this suggestion... I checked financial data on Open collective and through conversations with Ruth. There’s also a license compatibility issue since newer versions of FontAwesome have become paid
> 
> Ricardo might need to think deeper, search, verify licence compatibility, check references, check user experience researches, weigh the pros and cons of each idea and outline a logical explanation for each, associate with the platform behaviour, check if a change causes a need to change behaviours or workflow, consider the effort of extra changes and plan how to implement on a code perspective
> 
> We could replace manually using a SVG, but it would break the consistency of the platform and make the code scattered over time as certain parts would use icons from the pack while others would use SVG
> 
> I'll leave the choice for you

@andersonjeccel I meant this: "Keeping the wheel icon, but updating it to the latest version, maintains familiarity"

**Comment by andersonjeccel** [comment]
@Mike-Dropsolid Hm, got it. But we fall into the problem about having more than settings there. Should I proceed with the change even considering this?

**Comment by code5rick** [comment]
@andersonjeccel  I suggest you reread my comment. I never stated that we should proceed with FontAwesome Pro. The screenshot of FontAwesome was simply provided as an example. However, since you may not have understood that clearly, I will provide another screenshot to clarify, featuring the Remix icons that you selected:

image

If you still wish to keep that icon, please remember that the sidebar opens from the **right**, the icon should at least **reflect that**.

I never suggested changing any type of action, only the **icon**. You seem to have quite an attitude lately regarding any suggestions made. Next time, instead of creating drama on GitHub, let's discuss further details on Slack 👌

**Comment by andersonjeccel** [comment]
@code5rick Thanks for clarifying about FontAwesome!

I'm still confused about the suggestion, should I flip the icon or change to cog?

**Comment by andersonjeccel** [comment]
> There was a concern raised in[ PR #13375](https://github.com/mautic/mautic/pull/13375#pullrequestreview-1897640082), by John, which is that the documentation might have to change as well. @andersonjeccel could you check if there are mentions of the 'cog' icon name in the user documentation & labels in Mautic itself, and replace those? Maybe a more neutral description, instead of using an icon name, would work better? Especially if another redesign might change icons again further down the road.

Yeah, there is a few mentions about cog icon being the action to open "admin menu"

https://docs.mautic.org/en/5.x/search.html?q=cog&check_keywords=yes&area=default

At the moment, we have 2 cog icons being used

image

Perhaps changing to a sidebar icon could make the difference between both bigger (and clearer)

But a cog still maybe represents "admin menu" better than a sidebar icon

All items for reference:
image


@Mike-Dropsolid @LordRembo 
I'm not sure, what would you consider a priority?:

1. representing an admin menu
2. representing a sidebar with more options

Since Mautic is used by marketeers, it is possible that the main functionalities remain on the left sidebar and the right sidebar is less frequently used, to manage technical config...

We could find a mid-term by using one of these ideas:
image
image


Left sidebar for reference:
image

It would make sense to move Categories from right to left sidebar, maybe group them (an idea)

**Comment by code5rick** [comment]
> @code5rick Thanks for clarifying about FontAwesome!
> 
> I'm still confused about the suggestion, should I flip the icon or change to cog?

@andersonjeccel the suggestion that I made is, since the sidebar is labeled "Configurations," and cogwheels are commonly used icons to represent changing settings, as well as inner workings, we should keep the current icon from the previous versions. Since you are updating the Mautic icons and utilizing the Remix icons, the cog icon is labeled as "settings-5".

image

Since Mautic is a community-driven platform, we should collaborate as a team to improve the platform, setting aside ego, personal ambitions, and even portfolio interests. Please understand, this was simply a modest suggestion, and nothing new.

**Comment by Mike-Dropsolid** [comment]
Let's work together indeed and find common ground.

Personally I like the "list-settings" as alterative.

308150528-be2299ba-7933-457e-8af9-89be0d4978a9

@code5rick @LordRembo what do you guys think?

I would propose to choose between that one and keeping the cog.

**Comment by code5rick** [comment]
> Let's work together indeed and find common ground.
> 
> Personally I like the "list-settings" as alterative.
>
> @code5rick @LordRembo what do you guys think?
> 
> I would propose to choose between that one and keeping the cog.

I would keep the cog since it is more straightforward and easier to view, especially since the icon would be small. For context, here is a proposed icon referenced above:

image

However, I really liked @andersonjeccel 's idea about using the tools icons, however, I would use them to differentiate the "Configuration" nav-item. When I was writing documents explaining Mautic for internal use, I came across this problem and realized there are two types of cogs being used. **Just my suggestion**.

**Comment by LordRembo** [comment]
There's some good discussion here, as well as workable ideas to follow up on. Mike & I discussed with Anderson, to make a new PR compiling some info learned in here, to make a new proposal.
We also understand that some UX changes, like the subject of icons, is too tricky to decide (and merge) based on 2 reviews (as other PR's do), so we'll try to open that up more in the upcoming PR(s) and get more viewpoints.

**Pull request merged**
