### PR TITLE
bugfix: Handle SES bounces without a DSN

### PR DESCRIPTION
**Pull request by nextgens**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? |  Y
| New feature? |  N
| Automated tests included? | N
| Related user documentation PR URL |
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #4632
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
When receiving a bounce notification from SES, the current code assumes that it includes a DSN... which may not be present (as documented on https://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html).

Without this patch the following occurs:
[2019-09-16 13:51:01] mautic.NOTICE: PHP Notice - Undefined index:
diagnosticCode - in file
/var/www/mautic/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php
- at line 147 ...

This fixes it.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1.  Configure mautic to use SES for delivery
2. Send an email to an address that bounces and where the receiving MTA doesn't send a DSN back
3. Get the exception above ^

### CODE REVIEW

**Comment by nextgens** [comment]
I don't have an exhaustive list of MTAs that do not send DSNs ... but domains using Mimecast are a notable offender.

**Comment by AndrassGray** [comment]
Just trying to understand : You are talking about SNS, or does this concern a monitored inbox catching bounces ? Or both ?

**Comment by nextgens** [comment]
SNS callbacks... but it may also affect the monitored inbox (I haven't tested that)

**Comment by npracht** [comment]
@nextgens does https://github.com/mautic/mautic/pull/7893 is the same ? If yes any advice about which PR to keep (look at code quality please).

**Comment by nextgens** [comment]
@npracht it's addressing two different issues, not sure why you've marked it duplicate

**Comment by npracht** [comment]
Hi @nextgens ! I was suspecting it was addressing the same (it comes from the same piece of code obviously). I remove the duplicate tag.
However, can you test #7893 ?

**Comment by nextgens** [comment]
@npracht I've now tested #7893 and it doesn't work for me; not sure why.

**Comment by nextgens** [comment]
To test this PR, try sending an email to a non-existent user on a mimecast-enabled domain.

clearlythisdoesntexist@eurostar.com for instance

**Comment by nextgens** [comment]
@npracht @dennisameling this has been tested in #7893 (as it was wrongfully flagged duplicate)

see https://github.com/mautic/mautic/pull/7893#issuecomment-540063207 and comments below

**Comment by dennisameling** [comment]
Could you please resolve the merge conflict (AmazonTransport.php) now that we've merged #7893? Thanks! 😊

**Comment by nextgens** [comment]
@dennisameling this was tested in the other PR... see https://github.com/mautic/mautic/pull/7893#issuecomment-540063207

**Comment by dennisameling** [comment]
@nextgens I just put "Pending Test Confirmation" there because Travis tests were still running, just so I wouldn't forget about this PR. Sorry if that was confusing :blush: 

PHPCS is failing now, would you mind running `bin/php-cs-fixer fix -v --diff` locally? That should fix it automatically for you, after which you can push the change and Travis will pass then. :)

**Pull request merged**
