### PR TITLE
Allow ids remove strict mode (part 2)

### LINKED ISSUE #10398: MJML visual editor adds ID tags which are now deemed as invalid
### Mautic Version

4.0.0

### PHP version

7.4.19

### What browsers are you seeing the problem on?

Chrome

### What happened?

image

now that's not a valid MJML.

### How can we reproduce this issue?

Step 1: like described above.

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by adiux**
PR in the main repo for the presets PR https://github.com/mautic/grapesjs-preset-mautic/pull/23

### CODE REVIEW

**Comment by jos0405** [comment]
I checked out this PR. It does allow to save the templates with "id=" in them, and doesn't fail by non critical mjml errors. It does what it supposed to be. Many many thanks @adiux 

(If you test: need to purge previous js files from browser cache.)

**Comment by RCheesley** [comment]
Good to go given that this has already been tested in the preset repo. Thanks for testing @jos0405

**Comment by RCheesley** [comment]
@all-contributors please add @adiux for code

**Comment by RCheesley** [comment]
@all-contributors please add @jos0405 for usertesting

**Review by RCheesley — DISMISSED** [review]

**Comment by RCheesley** [comment]
@adiux this PR was made against the wrong branch unfortunately, updating the branch causes a bit of a problem because the base is out of date. We may need to make a new PR on the 4.0 branch (bug fixes)?

**Comment by RCheesley** [comment]
Closing this PR in favour of https://github.com/mautic/mautic/pull/10482

**Pull request closed without merging**
