### PR TITLE
Filter lead by stage

### PR DESCRIPTION
**Pull request by aviboy2006**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? |  Filter lead by stage
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description: Added stage filter for lead list ( contact list) 

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1.  Search any lead by stage name  'stage:"STAGENAME"
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by escopecz** [comment]
Please fix the code styles: https://travis-ci.org/mautic/mautic/jobs/252772738#L1149

And add the search command example to https://github.com/mautic/mautic/blob/staging/app/bundles/LeadBundle/Translations/en_US/messages.ini#L234

**Comment by aviboy2006** [comment]
Updated PR with search command help and indentation

**Comment by escopecz** [comment]
Thanks! It is still failing the CS check: https://travis-ci.org/mautic/mautic/jobs/252789177#L1097

**Comment by aviboy2006** [comment]
I tried with indentation check. not able to find exact issue. could you please help me this.

**Comment by escopecz** [comment]
Run `bin/php-cs-fixer fix -v` in Mautic root dir. It will go through all Mautic files and fix the CS for you. It will take a while. A better way is to use the pre-commit hook which will do it automatically for the files changed in your commits. All you have to do is to `git clone` this repository and run `composer install`. It should then trigger the pre-commit hook automatically for you.

**Comment by aviboy2006** [comment]
I tried what you suggested for fix automatically. But its doesnt help me. Please suggest me on this.

**Comment by aviboy2006** [comment]
guide on this  how to resolved this issue. I tried all options but failed :(

**Comment by escopecz** [comment]
Haha, it seems you made it worse :) I'll try to fix it. Let's see how it goes.

**Comment by aviboy2006** [comment]
Please do it. and guid me also how to do.

**Comment by escopecz** [comment]
Alright, code style fixed. All I did was to run the command I mentioned above and committed the changes it produced.

**Comment by aviboy2006** [comment]
Thanks @escopecz . I did same things but its failing for me. I tried random things and didnt work. What is next stage ?

**Comment by escopecz** [comment]
2 developers have to test it successfully before it will be merged.

**Comment by aviboy2006** [comment]
Please add me comman developer group chat if mautic have.

**Comment by escopecz** [comment]
https://www.mautic.org/slack/, the #dev channel

**Comment by dongilbert** [comment]
Do not merge yet

**Comment by escopecz** [comment]
😆  Not merging until Travis nods it's OK to

**Pull request merged**
