### PR TITLE
Fix campaign membership syncing when an issue such as api limits occur

### PR DESCRIPTION
**Pull request by alanhartless**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Required: )
#### Description:

This addresses two issues:
1. If for some reason the contact was deleted but a reference to the SF still in the integration_entity table, it was not possible to pull that contact back in through a campaign membership based segment. 
2. If an API limit was hit during fetching unknown contacts from SF during the middle of a campaign member segment sync, it would halt the campaign membership sync because the current date/time was cached as the last time a successful sync occurred so the next sync would only add contacts added to the campaign since then.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1.1 Setup Salesforce and create a segment for campaign membership. Run the `mautic:segment:update` command to build the segment. 
1.2 Go to the leads table in the database and manually delete the contacts just pulled from SF (leaving the entries in the integration_entities table intact
1.3 Run the segment command again and notice that the contacts are not recreated with the segment sync
2.1 Edit https://github.com/mautic/mautic/blob/staging/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php#L8886 and add `throw new ApiErrorException('test');` right after `try {`
2.2 Go to the cache_items table  and delete the entry like `Salesforce:Salesforce.CampaignSync.7010M000000naKGQAY` where `7010...` matches the campaign ID
2.3 Add another contact or lead to the SF campaign (in salesforce) that doesn't exist in Mautic already then repeat 2.3. Notice that even though an exception was thrown when fetching contacts from the SF campaign, a new datetime is cached in cache_items.

#### Steps to test this PR:
1. Repeat and contacts will be re-added to Mautic
2. Repeat and no date/time will be cached to cache_items allowing the next job to retry the campaign sync

### CODE REVIEW

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by npracht** [comment]
Hello @alanhartless could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback, i would very love to merge it in 3.0.1 if still relevant. Thanks !

**Comment by RCheesley** [comment]
@alanhartless conflicts to be addressed so will be removed form the 3.0.1 milestone

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
As this is a T3 with outstanding conflicts and no tests, I'm pushing it back to the 3.2 milestone. That should give us some time to address the conflicts and make sure that we can test it fully.

**Comment by anton-vlasenko** [comment]
I've added a functional test to this PR, but it still has to be code reviewed and tested.

**Comment by RCheesley** [comment]
Looks like we have a [failing test](https://github.com/mautic/mautic/pull/7514/checks?check_run_id=2591164066#step:9:70) to address @alanhartless @anton-vlasenko @fedys  - could someone take a look?

**Comment by dadarya0** [comment]
> Looks like we have a [failing test](https://github.com/mautic/mautic/pull/7514/checks?check_run_id=2591164066#step:9:70) to address @alanhartless @anton-vlasenko @fedys - could someone take a look?
@RCheesley failing test cases are fixed now.

**Review by luguenth — APPROVED** [review]
Tested step 1&2. Both cases are working now.

**Review by dennisameling — APPROVED** [review]

**Pull request merged**
