### PR TITLE
Fix : Prevent duplicate rows in email stats reports with campaign columns

### PR DESCRIPTION
**Pull request by tejasync**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✅ 
| New feature/enhancement? (use the a.x branch)      | ❌ 
| Deprecations?                          | ❌ 
| BC breaks? (use the c.x branch)        | ❌ 
| Automated tests included?              | ✅  
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

https://github.com/mautic/mautic/pull/10102 still shows duplicate rows in email stats reports with campaign columns. This PR fixes this.

#### Steps to reproduce:
1. Create new template email
2. Create segment
3. Create campaign based on that segment with action Send mail and decision Opens email
4. Add contact to this campaign and trigger all campaign elements (open email)
5. Create report based on Emails Sent data source with campaign field as column
6. Generated report will contain double rows for this contact
OR 
Refer PR https://github.com/mautic/mautic/pull/10102 for steps.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. After the PR, steps to reproduce should work fine

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11117"></a>

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
The code change makes sense 👍 Thanks Tejas!

**Comment by volha-pivavarchyk** [comment]
Works well.

Just one question. The report only contains data about the first campaign for this contact now. Is it expected behavior?

E.g., I create two distinct campaigns each with one single contact to whom the emails are sent. The report contains data about the first campaign 
image

The result before this PR:
image

**Comment by escopecz** [comment]
@volha-pivavarchyk great catch! 

@ts-navghane maybe we need more columns in the group by clause?

**Comment by RCheesley** [comment]
@ts-navghane can you review the feedback and update the PR as required? Thanks!

**Comment by tejasync** [comment]
@volha-pivavarchyk Thank you for reporting that. Will look into this. 
cc: @escopecz @RCheesley

**Comment by tejasync** [comment]
As @volha-pivavarchyk mentioned in the comment: https://github.com/mautic/mautic/pull/11117#issuecomment-1120221888.
I observed that, we do not require this change. We can simply add group by Campaign ID, Contact ID in the report UI to achieve the functionality. Closing this PR.

**Pull request closed without merging**
