### PR TITLE
[type-declarations] Add known void return type to Stage, User and Webhook bundles

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Good to go :+1:

**Comment by TomasVotruba** [comment]
Rebased and good to go :+1:

**Comment by TomasVotruba** [comment]
Good to go :+1:

**Review by escopecz — APPROVED** [review]
I scanned through the code. Looks good! Phpstan will confirm the return types in more detail. 👍

**Comment by TomasVotruba** [comment]
Awesome, thank you :+1:

**Pull request merged**
