### PR TITLE
Send email and sms webhook events added

### PR DESCRIPTION
**Pull request by escopecz**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | /
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

This PR adds 2 new events to the global webhooks:

Screenshot 2019-05-15 at 10 59 22

### Email Send Event

It will not fire a webhook for internal test emails. But it will fire it for:

- **Send email directly to a contact from the contact detail page**

Example payload:
```
{
    "mautic.email_on_send": [
        {
            "email": null,
            "contact": {
                "id": "12",
                "title": null,
                "firstname": "John",
                "lastname": "Doe",
                "email": "johndoe@gmail.com",
                [...]
            },
            "tokens": {
                "{unsubscribe_text}": "<a href=\"http://mautic-cloud.test/index_dev.php/email/unsubscribe/5cdaa50e155f9732391159\">Unsubscribe</a> to no longer receive emails from us.",
                [...]
            },
            "contentHash": "8bb9181fa1c76671352b79565e244240",
            "idHash": "5cdaa50e155f9732391159",
            "content": "<!DOCTYPE html><html>[...]</html>",
            "name": "mautic.email_on_send",
            "subject": "Test email",
            "source": [],
            "headers": {
                "List-Unsubscribe": "<http://mautic-cloud.test/index_dev.php/email/unsubscribe/5cdaa50e155f9732391159>"
            },
            "timestamp": "2019-05-14T11:22:54+00:00"
        }
    ]
}
```

- **Send email from a form action**
- **Send email from a campaign action**
- **Send segment email**

Example payload:
```
{
    "mautic.email_on_send": [
        {
            "email": {
                "isPublished": true,
                "dateAdded": "2019-05-15T10:03:20+00:00",
                "dateModified": null,
                "createdBy": 1,
                "createdByUser": "John Doe",
                "modifiedBy": null,
                "modifiedByUser": null,
                "id": 8,
                "name": "Test Email Internal Name",
                "subject": "Test Email",
                "language": "en",
                "category": null,
                "fromAddress": null,
                "fromName": null,
                "replyToAddress": null,
                "bccAddress": null,
                "utmTags": {
                    "utmSource": null,
                    [...]
                },
                "customHtml": "<!DOCTYPE html><html>[...]</html>",
                "plainText": null,
                "template": "blank",
                "emailType": "list",
                "publishUp": null,
                "publishDown": null,
                "readCount": 0,
                "sentCount": 0,
                "revision": 1,
                "assetAttachments": [],
                "variantStartDate": null,
                "variantSentCount": 0,
                "variantReadCount": 0,
                "variantParent": null,
                "variantChildren": [],
                "translationParent": null,
                "translationChildren": [],
                "unsubscribeForm": null,
                "dynamicContent": [
                    {
                        "tokenName": "Dynamic Content 1",
                        "content": "Default Dynamic Content",
                        "filters": [
                            {
                                "content": null,
                                "filters": []
                            }
                        ]
                    }
                ],
                "lists": [
                    {
                        "createdByUser": "Clare Schowalter",
                        "modifiedByUser": "Clare Schowalter",
                        "id": 1,
                        "name": "linhartescope",
                        "alias": "sdf",
                        "description": null,
                        "filters": [
                            {
                                "glue": "and",
                                "field": "email",
                                "object": "lead",
                                "type": "email",
                                "filter": "john",
                                "display": null,
                                "operator": "startsWith"
                            }
                        ],
                        "isGlobal": true,
                        "isPreferenceCenter": false
                    }
                ],
                "headers": []
            },
            "contact": {
                "id": "15",
                "date_added": "2019-04-15 12:11:46",
                "email": "linhartescope+contact3@gmail.com",
                [...]
            },
            "tokens": {
                "{dynamiccontent=\"Dynamic Content 1\"}": "Default Dynamic Content",
               [...]
            },
            "contentHash": "1692051d9cd408e413cd88c1de475edd",
            "idHash": "5cdbe478cd6fd396409369",
            "content": "<!DOCTYPE html><html>[...]</html>",
            "subject": "Test Email",
            "source": ["email", 8],
            "headers": {
                "Precedence": "Bulk",
                "List-Unsubscribe": "<https://xxx/email/unsubscribe/5cdbe478cd6fd396409369>"
            },
            "timestamp": "2019-05-15T10:05:45+00:00"
        }
    ]
}
```

### Text Send Event

Same as for emails above, just sending text messages.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create a webhook that has the new events active. Use for example https://requestbin.com to track the payloads sent with this webhook.
3. Create a new segment email. Send test email. No webhook is created.
4. Send the segment email. A new webhook payload will appear for each contact in the segment.
5. Test also sending a campaign email, form action email and email from the contact detail page. All those should create webhook payloads.
6. Test also SMS send webhook by sending SMS.

### CODE REVIEW

**Comment by StoppingBuck** [comment]
@escopecz I just followed the instruction steps to send the PR and 
- I can confirm that creating a segment mail and pressing Send Example to send an example to someone **does NOT** trigger the webhook
- Going to a Contact detail page and pressing the 'Send Email' to send an email directly to a contact **DOES** trigger the webhook

However, I found one error:
- If you create a segment mail for a segment of one person and send it out as normal by pressing the 'Send' button and in a batch of 100 (or whatever), **TWO** identical callbacks from the webhook are sent at the same time (confirmed with RequestBin). The content of the callbacks are identical, and they are sent with only a few ms apart, but it still looks like an error.

I have not tested the webhook for campaign email, form action email or SMS.

**Review by StoppingBuck — CHANGES_REQUESTED** [review]
@escopecz I just followed the instruction steps to test the PR and 
- I can confirm that creating a segment mail and pressing Send Example to send an example to someone **does NOT** trigger the webhook
- Going to a Contact detail page and pressing the 'Send Email' to send an email directly to a contact **DOES** trigger the webhook

However, I found one error:
- If you create a segment mail for a segment of one person and send it out as normal by pressing the 'Send' button and in a batch of 100 (or whatever), **TWO** identical callbacks from the webhook are sent at the same time (confirmed with RequestBin). The content of the callbacks are identical, and they are sent with only a few ms apart, but it still looks like an error.

I have not tested the webhook for campaign email, form action email or SMS.

**Comment by MajesteitBart** [comment]
Mautibox isn't working on this one..

**Comment by MajesteitBart** [comment]
I can confirm that in some cases, two identical callbacks are sent. In one case, it was a send email as a form action.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by StoppingBuck** [comment]
I spinned up Mautibox to test this PR after @escopecz 's changes yesterday, and have experienced:
The email sent webhook works for
* Sending an email directly to a contact
* Sending a segment email (the old bug which sent two webhooks per person seems to have been fixed :tada: )

I have not tested anything else at the moment.

**Comment by dennisameling** [comment]
Closing and re-opening for Codecov

**Review by dennisameling — CHANGES_REQUESTED** [review]
While the PR does seem to do what it describes, all webhooks are fired twice as indicated by other reviewers. I tested on Mautibox by sending a segment email to 8 contacts and got exactly 16 webhook requests:

image

@escopecz any idea what this could be?

**Comment by kuzmany** [comment]
Confirm @dennisameling reported issue. Events fired two times, tested on https://webhook.site/

**Comment by RCheesley** [comment]
Bumping to 3.2 due to unresolved feedback from testers.

**Comment by StoppingBuck** [comment]
@RCheesley Our company really needs this functionality. Is there any way we can assist with ensuring that this gets into 3.2? I noticed you mentioned during the sprint that the branch is private - do we have any way around that now that @escopecz appears to be busy elsewhere? I might be able to work full-time on this, but I don't have a lot of experience with rebasing.

**Comment by RCheesley** [comment]
@StoppingBuck to get this merged we need @escopecz to take a look at the feedback from all testers who are reporting duplicated webhooks. That should be addressed, the PR re-tested, and then it can be considered for the 3.2 release.  The only way around the private branch issue when the author is unresponsive is to create a new PR but that is a last resort. In this case I am hopeful that we will get a response soon so that we can move forward with this PR.

**Comment by escopecz** [comment]
@dennisameling and others, the issue with 2 webhooks per email sent is fixed by https://github.com/mautic/mautic/pull/7716/commits/05bd59fa22494f861dc996e85f7a7ee7e83a89e0. More details in https://github.com/mautic/mautic/pull/8619/files#r474078976

**Comment by StoppingBuck** [comment]
Just tested with mautibox and Pipedream

- Sending a segment mail to 1 contact = 1 event in Pipedream.
- Sending a segment email to 24 people = 24 events in Pipedream. 
- Sending an email directly to a contact = 1 event in Pipedream.

Which all looks great :+1: 

However:
- Sending a test email from Configuration --> Email Settings **also** results in an event in Pipedream. This is not really a problem for me, but given @escopecz 's comment above - `It will not fire a webhook for internal test emails` - I'm wondering if that is a bug?

**Review by kuzmany — CHANGES_REQUESTED** [review]
Sending email works properly 👍 
Open email works properly 👍 
But If I open email by view email, I've seen two open email request (also openCount is increase two times :() https://mautibox.com/7716/email/view/5f3fbcdc7cbdc899843173

**Comment by escopecz** [comment]
@StoppingBuck good catch. Fixed.

@kuzmany I cannot replicate on my local and the Mautibox instance is down at the moment. Anyway, I'm not touching the email open event nor webhook in this PR so it's not introduced by this PR. Please create a new issue for it.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by StoppingBuck** [comment]
So, uh, what happened to this one? Is it ready for 3.2? @escopecz

**Comment by RCheesley** [comment]
@StoppingBuck thanks for flagging - looks like we have two good tests so just running the Github Actions and if all is good we should be able to merge

**Comment by StoppingBuck** [comment]
Damn, it looks like there's problems with PHP 7.4: 

```
PHP Fatal error:  Declaration of Mautic\CoreBundle\Tests\Unit\Helper\MaxMindDoNotSellDownloadHelperTest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /home/runner/work/mautic/mautic/app/bundles/CoreBundle/Tests/Unit/Helper/MaxMindDoNotSellDownloadHelperTest.php on line 34
```

**Comment by RCheesley** [comment]
No it is with PHPUnit 8 - we are fixing this imminently

**Comment by StoppingBuck** [comment]
> No it is with PHPUnit 8 - we are fixing this imminently

@RCheesley Just to be sure: Does that mean that this PR is ready to go into 3.3? Or do we need to wait until PHPUnit 8 works? It seems that #9244 has been merged, so maybe it should work now?

**Comment by RCheesley** [comment]
A test was failing in this PR due to us merging the PR that updated PHPUnit to 8. We fixed that so it is now good to go for 3.3 🚀

**Comment by escopecz** [comment]
@RCheesley This is ready to be reviewed / tested.

**Pull request merged**
