### PR TITLE
The E-Mail Preview Url is set to published when the email is published

### PR DESCRIPTION
**Pull request by volha-pivavarchyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
The E-Mail Preview Url is set to published when the email is published.

image
image

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Toggle the email publish status in the email list and email view.
3. E-Mail Preview Url status also changes. It had not changed before.

### CODE REVIEW

**Comment by escopecz** [comment]
@volha-pivavarchyk I think that the public preview should be independent from the email publish state. The public preview is there if the author wants to send a preview to stakeholders before the send. So in many cases when the email is unpublished. However, the public preview should be unpublished when the stakeholders approve the email so none would be able to access it afterwards.

@RCheesley @mollux @mabumusa1 what do you think?

**Comment by RCheesley** [comment]
I am inclined to agree with @escopecz on this - the status of the preview should be set independent of whether the email is published or not.

Some orgs might not ever want to have previews enabled, published or not.

**Comment by kuzmany** [comment]
Yes, agree. And it should be by default disabled because just increasing the ID number allows anybody to see emails, even emails with high privacy levels.

**Comment by escopecz** [comment]
@volha-pivavarchyk I'll close this PR for now to reduce the number of open PRs that people might test. The discussion can continue here and it can be reopened if you give us a good reason why this behavior should change.

**Pull request closed without merging**
