### PR TITLE
Custom field could not be deleted if used

### PR DESCRIPTION
**Pull request by hluchas**
| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y 
| Automated tests included? | Partially
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Used custom field in segment filter could be deleted.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create custom field.
2. Use it in any segment filter.
3. Delete field - note that you can delete one or more fields directly in the list. There are two different ways how to do that.

#### Steps to test this PR:
1. Same scenario as for reproduction.

#### List deprecations along with the new alternative:
None
#### List backwards compatibility breaks:
None

### CODE REVIEW

**Comment by npracht** [comment]
@hluchas this is awesome !!

Could that also check if it is used in campaign condition ? :)

**Comment by hluchas** [comment]
@npracht May be good idea for further work!

**Comment by hluchas** [comment]
@escopecz What do you think?

**Comment by escopecz** [comment]
Heh, I was kinda avoiding commenting on this as I raised the same question as Norman before this PR was born. But let's answer this question:

_How many times any Mautic admin got a call from a contact asking if they can subscribe her/him again?_

I don't think this happens very often. There will be more examples of abusing the resubscribe option to spam people who have unsubscribed themselves. 

Also in case of this rare phone call the Mautic admin can send an email to the contact with the preference page link to subscribe again. I think that's the proper way to do it anyway. Because how can you know that the person on the phone is really the contact who unsubscribed?

So I'm all in for making spammers life more difficult.

**Pull request merged**
