### PR TITLE
Feature/report filter data by tags

### PR DESCRIPTION
**Pull request by arulrajsm28**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | No
| New feature? | Yes
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/995
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This will help to filter contacts with tags.

#### Steps to test this PR:
1. Create new Report in Reports page
2. Select Contacts in "Data Source" drop down in Details tab
3. Click Add filter button to add new filter 
4. Select Tags in "Column" select box  and add required options 
5. Save the report

### CODE REVIEW

**Comment by mqueme** [comment]
👍

**Review by mqueme — APPROVED** [review]

**Comment by escopecz** [comment]
I found 2 issues:
1. A report with "email" and "tags" columns shows also contacts with neither of those
2. If I sort by tags column, I don't see all the contacts with all the tags I have in Mautic.

**Comment by alanhartless** [comment]
I think the first is probably anonymous contacts because I had that as well.  But I have a problem with the second as well. When I order by tags, no contact my other non-id columns are not filled in and everyone has the same tags. I'm going to assume it's related to the group by.

**Comment by arulrajsm28** [comment]
@alanhartless @escopecz 
Updates made regarding issues reported .. Can you please check..
issue 1 is anonymous contact listing. need to filter out ?

**Comment by escopecz** [comment]
If I try to use the dynamic tag filter, I get this error:
```
500 Internal Server Error - Unable to transform value for property path "[tag]": Expected an array.

/app/bundles/ReportBundle/Controller/ReportController.php:644 at Symfony\Component\Form\FormFactory -> create ( 'report_dynamicfilters', array('tag' => '[object HTMLSelectElement]'), array('action' => '/index_dev.php/s/reports/view/10', 'report' => object(Report), 'filterDefinitions' => object(stdClass)) )
Mautic\ReportBundle\Controller\ReportController -> viewAction ( '10', '1' )
```
screen shot 2017-04-07 at 09 43 50

**Comment by arulrajsm28** [comment]
@escopecz can you please test it now. I have updated with fix.

**Comment by escopecz** [comment]
Hi, thanks! Please fix the merge conflicts by merging the latest staging branch into your branch.

**Comment by alanhartless** [comment]
Getting these errors on save:

```
2017-06-28 17:43:03] mautic.NOTICE: PHP Notice - Undefined variable: filterExpr - in file /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php - at line 374 [] []
[2017-06-28 17:43:03] mautic.ERROR: PHP Error: Call to a member function add() on null - in file /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php - at line 374 [] []
[2017-06-28 17:43:03] mautic.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Error: Call to a member function add() on null - in file /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php - at line 374 [] []
[2017-06-28 17:43:34] mautic.NOTICE: PHP Notice - Undefined variable: filterExpr - in file /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php - at line 374 [] []
[2017-06-28 17:43:34] mautic.ERROR: PHP Error: Call to a member function add() on null - in file /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php - at line 374 [] []
[2017-06-28 17:43:34] mautic.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Error: Call to a member function add() on null - in file /var/www/html/app/bundles/ReportBundle/Builder/MauticReportBuilder.php - at line 374 [] []``

**Comment by arulrajsm28** [comment]
@alanhartless please check now. The PR is updated. And fixed the issue.

**Comment by dongilbert** [comment]
This still has some issues. When I follow the steps, I'm given a report that displays only the tag selected in the filter in the tags column (even if the contact has multiple tags) and all other columns are empty. 

Filter setup:
screen shot 2017-09-19 at 10 48 07 am

expected contacts in report: 
screen shot 2017-09-19 at 10 45 48 am

Report data: 
screen shot 2017-09-19 at 10 45 40 am

Anonymous contacts that match tag:
screen shot 2017-09-19 at 10 45 56 am

**Comment by wittwerch** [comment]
@dbhurley Why was this PR closed without a reason?

**Comment by dbhurley** [comment]
Did you read through the comments? I would assume that offers explanation. Let me know if I am missing something.

**Comment by wittwerch** [comment]
dongilbert commented on 19 September, mentioned some issues and added the label "pending feedback". So yes, I don't see the explanation why Mautic is rejecting that PR. What's the reason?

**Comment by dbhurley** [comment]
[Back in February](https://github.com/mautic/mautic/pull/3134#issuecomment-276618140) there were 2 issues reported with this PR:
1. A report with "email" and "tags" columns shows also contacts with neither of those
2. If I sort by tags column, I don't see all the contacts with all the tags I have in Mautic.

This was [not resolved until August 30](https://github.com/mautic/mautic/pull/3134#issuecomment-326046032), when the Pending Feedback label was removed and the PR was re-tested. 

On Sept 19 the PR was tested again and noted to have conflicts with the current staging. 
Also [on Sept 19](https://github.com/mautic/mautic/pull/3134#issuecomment-330564863) an additional tester checked the PR and found numerous bugs in the code (again relating to the same tags). 

At this time the PR was again placed in the state of `Pending Feedback` meaning the PR needed to be fixed before it could be merged. 

In October the PR was removed from the project milestone due to no response. 

In November the PR was closed due to lack of response. 

**The last code submission was August 30 which is over 3 months ago. At this point the code is considered out of date and the PR will be closed until future updates are made.**

**Comment by wittwerch** [comment]
> This was not resolved until August 30, when the Pending Feedback label was removed and the PR was re-tested.

That is true. But maybe it is also related to the responsiveness of the core team. It's pretty hard to resolve issues when we don't get feedback for two month. Arul contributed some fixes on the 3. Feburary and there was no feedback till the 7. April. He fixed the mentioned issues on the 27. April and then had to wait again two month for feedback. If it goes back and forth like that it is really demotivating to wait weeks for feedback.

Anyway I see your point, there was no activity from our side in the last three months.

**Comment by dbhurley** [comment]
Two final comments: 
1. It's _not_ an "us" and "them" situation. We're all in this together.
2. Hopefully you see that things are moving faster these days 😉

**Comment by FranSanchezOria** [comment]
Hey guys,

Been reading this thread. I would love this feature implemented and I believe this have been raised several times by other people. Any chance to have it re-activated?

**Comment by djmonzyk** [comment]
I second this, I feel reporting on tags is a great feature and it sounds like the code is close...

**Comment by nickwild-999** [comment]
Me too. I would love to be able to report on Tags

**Comment by drimlike** [comment]
+1
This feature would be a great addition. Please consider adding it soon :)

**Comment by patrykgruszka** [comment]
I have created a similar feature, take a look at #11346 if you are still interested.

**Pull request closed without merging**
