### PR TITLE
fixing empty tag segmentation

### LINKED ISSUE #11178: Filter tag -> empty failed to filter contact into segment
### Mautic Version

4.2.x series

### PHP version

7.4+

### What browsers are you seeing the problem on?

Chrome

### What happened?

I accidently removed a tag on thousands of contacts that was assigned to a segment filtered with that tag.  

I figured since those contact does not have any other tags on it then I could create a segment and set filter to tag -> empty then create a segment campaign to add the tag back on to those with empty tags. 

But the the contact with no tags are not being added into segment with filter set at tag -> empty

The cron job is working fine because other filtering being processed .. just not the tag "empty" 

### How can we reproduce this issue?

Step 1: Have contact or several contacts with no tags
Step 2: Create a segment and set filter with tag = empty 

Notice that contacts with no tag are not being added to the segment. 

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/109790883-filter-tag-empty-failed-to-filter-contact-into-segment?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by npracht**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✔️ 
| New feature/enhancement? (use the a.x branch)      | No
| Deprecations?                          | No
| BC breaks? (use the c.x branch)        | No
| Automated tests included?              | No
| Related user documentation PR URL      | Not relevant
| Related developer documentation PR URL | Not relevant
| Issue(s) addressed                     | Fixes #11178

#### Description:

Create a segment with empty/not empty tag, see no contact matches criteria

#### Steps to test this PR:

1. Create segment with empty/not empty tag,
2. See it works ✔️ 

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11179"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
@npracht not sure if you intended the title that is set?

**Review by jos0405 — APPROVED** [review]
Works as described. What a fast fix!

image

image

**Comment by npracht** [comment]
Sorry @RCheesley 🤤

**Review by RCheesley — APPROVED** [review]
Works as expected, initial segment with tags = empty was 55, then I added a tag to a contact and created a segment for tags = not empty and one is shown, with one less in the empty segment.

Contact Segments _ Mautic

Just needs code review then good to go :)

**Comment by kuzmany** [comment]
This is not ready to commit. As author I just made hotfix internally for tags, but looks like this issue is related to all foreign filters (email stats, page_hits etc). I will push more commits

**Comment by npracht** [comment]
closing in favor of https://github.com/mautic/mautic/pull/11253

**Pull request closed without merging**
