### PR TITLE
Revert sidebar to cog icon

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by andersonjeccel** [comment]
image

**Review by escopecz — APPROVED** [review]
Looks great even with the new icon set:
Screenshot 2024-03-06 at 14 36 04

**Comment by code5rick** [comment]
Why the outline version of the cog? The solid version would be the best solution to maintain harmony with the other versions.

**Comment by LordRembo** [comment]
@code5rick I dunno, there's a bunch of icons that are semi-transparent already at the moment (eg. the 'save' icon and the 'Themes' icon in the shared screenshot). It keeps things light.
Maybe when we get to Andersons design system proposals, we can look at making this more consistent overall?

**Comment by Mike-Dropsolid** [comment]
Perfect.

**Review by RCheesley — APPROVED** [review]
Fine with me - we can follow up afterwards if we want to change it from the cog so that all are in approval of the direction we should go.

**Pull request merged**
