### PR TITLE
release 5.1.0

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴🟢
| Deprecations?                          | 🔴🟢
| BC breaks? (use the c.x branch)        | 🔴🟢
| Automated tests included?              | 🔴🟢 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by mollux** [comment]
API library tests running in https://github.com/mautic/api-library/actions/runs/9483793719

**Review by RCheesley — APPROVED** [review]

**Comment by RCheesley** [comment]
Versions look good, OK to go once API tests are passing!

**Comment by mollux** [comment]
API tests are passing, see https://github.com/mautic/api-library/actions/runs/9480606634

**Comment by mollux** [comment]
All tests green and we are good to go

**Pull request merged**
