### PR TITLE
[UX] Copy code blocks on click

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

this pr introduces a new feature that allows users to easily copy the content of code blocks by simply clicking on them. 

this functionality is particularly useful when working with code snippets or examples that need to be quickly copied and pasted elsewhere

when the user clicks on the code block or the copy icon, the entire content of the block is automatically copied to the user's clipboard, ready to be pasted

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Go to Marketplace > Open any > Click on the code for CLI then paste somewhere

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
Works great 👍 

https://github.com/mautic/mautic/assets/1235442/4904e45f-51be-4c04-926a-bcef98b37672

**Comment by escopecz** [comment]
It may be a good idea to add it also to the tracking script code area:
Screenshot 2024-06-28 at 09 55 21
But it's not a blocker for this PR. It can be improved in another one.

**Review by escopecz — CHANGES_REQUESTED** [review]
I found one issue. The copy button will appear only on refresh. It doesn't appear when I browse to that page with just ajax calls.

**Review by escopecz — APPROVED** [review]
The issue with ajax is resolved. Thank you! 👍

**Review by abhisekmazumdar — APPROVED** [review]
Works as expected

**Pull request merged**
