### PR TITLE
Empty and Not Empty report date filters are not compatible with MySQL8

### LINKED ISSUE #10643: Erro ao Salvar Relatório
### Mautic Version

4.0.0

### PHP version

7.4.26

### What browsers are you seeing the problem on?

Chrome

### What happened?

Ao tentar salvar o relatório Emails Enviados. Está retornando erro por conta do filtro selecionado.

### How can we reproduce this issue?

Vídeo anexo.

https://youtu.be/4peDEr7Skn8

### Relevant log output

```shell
[2021-11-24 17:06:04] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'SELECT count(*) FROM (SELECT `e`.`name` AS e_name, `l`.`email` AS email, IF(es.date_read IS NOT NULL, TIMEDIFF(es.date_read, es.date_sent), '-') AS read_delay FROM email_stats es LEFT JOIN emails e ON e.id = es.email_id LEFT JOIN leads l ON l.id = es.lead_id WHERE (es.date_sent IS NULL OR (es.date_sent BETWEEN ? AND ?)) AND ((es.date_read IS NOT NULL) AND (es.date_read <> '')) GROUP BY es.id) c' with params ["2021-10-24 03:00:00", "2021-11-24 20:06:04"]:  SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: ''" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 128 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT count(*) FROM (SELECT `e`.`name` AS e_name, `l`.`email` AS email, IF(es.date_read IS NOT NULL, TIMEDIFF(es.date_read, es.date_sent), '-') AS read_delay FROM email_stats es LEFT JOIN emails e ON e.id = es.email_id LEFT JOIN leads l ON l.id = es.lead_id WHERE (es.date_sent IS NULL OR (es.date_sent BETWEEN ? AND ?)) AND ((es.date_read IS NOT NULL) AND (es.date_read <> '')) GROUP BY es.id) c' with params [\"2021-10-24 03:00:00\", \"2021-11-24 20:06:04\"]:\n\nSQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: '' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:128, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: HY000): SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: '' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: '' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:112)"} []
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### LINKED ISSUE #10686: Segment Filters using "date"-Field and operator "empty/not empty" break Segemts:update
### Mautic Version

4.1.1

### PHP version

7.4

### What browsers are you seeing the problem on?

_No response_

### What happened?

When creating a segment with a filter on a date field like "Date Last Active" or "Date Identified" and then using the "empty" or the "not empty" operator, the segment wont work. 

But what makes thing worse is that the mautic:segments:update command or cron will stop as soon as it tries to put contacts in this Segment, thus not updating any Segments after that.

Here you can see the SQL-error provided when using mautic:segments:update:
image

I tested this against Mautic 4.x and Mautic 3.3.4, both times resulting in the same error. 

### How can we reproduce this issue?

1. Create Segment
2. Use Filter on a date-field like "Date last active" or "Date identified" etc.
3. Save the Segment
4. Use Terminal to navigate to your Mautic-Instance htdocs-folder
5. Use the command "mautic:segments:update"
6. See the errors for yourself

### Relevant log output

```shell
[2021-12-15 12:16:09] mautic.ERROR: Segment QB: Query Exception: An exception occurred while executing 'SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM (SELECT DISTINCT l.id as leadIdPrimary, par7.lead_id AS par7_lead_id FROM leads l LEFT JOIN lead_lists_leads par7 ON par7.lead_id = l.id and (par7.leadlist_id = 52) WHERE ((l.date_identified IS NOT NULL) AND (l.date_identified <> '')) AND (par7.lead_id IS NULL)) sss':  SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: '' {"query":"SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM (SELECT DISTINCT l.id as leadIdPrimary, par7.lead_id AS par7_lead_id FROM leads l LEFT JOIN lead_lists_leads par7 ON par7.lead_id = l.id and (par7.leadlist_id = 52) WHERE ((l.date_identified IS NOT NULL) AND (l.date_identified <> '')) AND (par7.lead_id IS NULL)) sss","parameters":{"par6":null}} []
[2021-12-15 12:16:09] mautic.NOTICE: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM (SELECT DISTINCT l.id as leadIdPrimary, par7.lead_id AS par7_lead_id FROM leads l LEFT JOIN lead_lists_leads par7 ON par7.lead_id = l.id and (par7.leadlist_id = 52) WHERE ((l.date_identified IS NOT NULL) AND (l.date_identified <> '')) AND (par7.lead_id IS NULL)) sss':  SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: '' (uncaught exception) at /var/www/m4test.mautic2.leuchtfeuer.com/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 128 while running console command `mautic:segments:update` [] []
[2021-12-15 12:16:09] mautic.WARNING: Command `mautic:segments:update` exited with status code 1 [] []
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/108498989-segment-filters-using-date-field-and-operator-empty-not-empty-break-segemts-update?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by fedys**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

[//]: # ( Required: )
#### Description:
When a user uses an empty or not empty filter within a report after being upgraded to MySQL 8 the report will crash and not return results. This PR fixes no longer valid `date`/`datetime` comparison with an empty string in MySQL 8.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a new report with the following filters on the _Data_ tab:
    -  A field of _Data Type_ **Date** with a condition **empty**.
    -  A field of _Data Type_ **Date** with a condition **not empty**.
    -  A field of _Data Type_ **Date/Time** with a condition **empty**.
    -  A field of _Data Type_ **Date/Time** with a condition **not empty**.
    -  A field of _Data Type_ **Time** with a condition **empty**.
    -  A field of _Data Type_ **Time** with a condition **not empty**.
2. When you go to the report's view page, you get _500 Internal Server Error_ message and in the logs there is `General error: 1525 Incorrect DATE value` error.

#### Steps to test this PR:
1. Repeat the first step above.
2. When you go to the report's view page, there is no error.
3. Validate that empty/not empty filters work as expected for both date and non-date fields.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10194"></a>

### CODE REVIEW

**Review by kuzmany — DISMISSED** [review]
Works 👍 Nice
Unit tests included 👍 
Code looks good 👍 
Let's go

**Comment by RCheesley** [comment]
@fedys looks like we need some PHPSTAN love on this PR :)

**Review by escopecz — APPROVED** [review]
👍

**Comment by Absynth723** [comment]
This bug is referenced as fixing #10686 but I believe it does not actually fix it. #10686 got closed so I guess this is the correct bug to report to? 
The following happens (I tried today) on an updated install on 4.2.0RC where I just tried a segment filter with "is empty" (on the attribution date, but it doesn't work on any other datetime field I tried).
 
/usr/bin/php /var/www/html/bin/console mautic:segments:update

```
In AbstractMySQLDriver.php line 128:

  An exception occurred while executing 'SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM (SELECT DISTINCT l.id as le
  adIdPrimary, par8.lead_id AS par8_lead_id FROM leads l LEFT JOIN lead_lists_leads par8 ON par8.lead_id = l.id and (par8.leadlist_id = 6) WHERE ((((l.email IS
   NOT NULL) AND (l.email <> '')) AND (l.date_letzter_kontakt_gf <= ?)) OR (((l.email IS NOT NULL) AND (l.email <> '')) AND ((l.attribution_date IS NULL) OR (l
  .attribution_date = '')))) AND (par8.lead_id IS NULL)) sss' with params ["2021-08-02"]:

  SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: ''


In Exception.php line 18:

  SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: ''


In PDOStatement.php line 112:

  SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: ''
```

This is:
Mautic: 4.2.0 RC1
MySQL: mysql  Ver 8.0.28-0ubuntu0.20.04.3 for Linux on x86_64 ((Ubuntu))

I did the upgrade with the command line from latest stable by changing config to accept "rc", then mautic:update:find and mautic:update:apply (and --finish) - worked without error. Did a cache clear just for good measure.

**Comment by escopecz** [comment]
You are right. I re-opened https://github.com/mautic/mautic/issues/10686

**Pull request merged**
