### PR TITLE
Fix resubscribe action condition check

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/issues/11784 

#### Description:

This is a copy of #11785

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by mabumusa1** [comment]
@escopecz this is 4.x version of #11883

**Comment by RCheesley** [comment]
@mabumusa1 although this PR is the same as one already approved on 5.x, it does need to be actually tested on the 4.* code base.

Furthermore it needs to be made on the 4.4 branch to be in the next bug fix release, we won't be making any more releases from 4.x. Could you rebase please? Thanks!

**Comment by mabumusa1** [comment]
@RCheesley I agree with you, I did a test on the original PR https://github.com/mautic/mautic/pull/11785 which was based on 4.x and it worked as expected, I will keep this PR marked as `ready-to-test` until someone else give it a try

**Comment by mabumusa1** [comment]
@daniellord32, this PR is the same as #11883, may you please confirm that this PR works on v4 so we can merge both of them

**Review by escopecz — APPROVED** [review]
👍

**Pull request merged**
