### PR TITLE
SMS enhancements - support callback with received & read & failed notifications

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR allow any text messages transport add delivered, read or failed notification.
Extend sms_messages table with: deliveredCount, readCount, failedCount column
Extend sms_messages_stat table with is_delivered, is_read, is_failed  column
All this columns are optional and disabled by default. Every transport can enabled it.

This PR is follower of new 2.16 feature Add support for sms replies as a campaign decision https://github.com/mautic/mautic/pull/7449

For DEVS:

Every SMS transport can implements TransportSettingsInterface and implement method enabledSettings with  array of any constant

TransportSettingsInterface::STAT_DELIVERED
TransportSettingsInterface::STAT_READED
TransportSettingsInterface::STAT_FAILED

This add new stats to column and graphs in details

image

image

Usage:

Example Transport

https://gist.github.com/kuzmany/995313c52f82bbb245152404f0c0d53d#file-exampletransport-php-L14

Example of Transport Callback

https://gist.github.com/kuzmany/1635e2684b4728cabb26e0689b3dbf5c

Dispatch Reply or Delivery events

https://gist.github.com/kuzmany/01001d7e49db8e9ddc00bbaa0592e314

#### How to test it:
You have to register a webhook with the service provider. For Twilio, it's done under Messaging for the phone number. The callback is `https://your.mautic.net/sms/twilio/callback`

1. Configure a SMS gateway 
2. Create a campaign with a "send text message" action then a "sends a text message" decision and do something as a result
3. Reply to a SMS 
4. The action attached to the decision should have been executed

#### List backwards compatibility breaks:
1. Refactor app\bundles\SmsBundle\Helper\ReplyHelper.php to app\bundles\SmsBundle\Helper\CallbackHelper.php
2. Remove getMessage() from app\bundles\SmsBundle\Callback\CallbackInterface.php
3. Add getEvent() to app\bundles\SmsBundle\Callback\CallbackInterface.php - should return ReplyEvent() or DeliveryEvent() object

If 3th party addon use that, need change it

### CODE REVIEW

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
Bumping to 3.2 due to unresolved conflicts.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@moskoweb see this PR - rebase of #7795

**Review by mabumusa1 — DISMISSED** [review]
I reviewed the code, it looks logical and adds layers of a logic needed for SMS. @kuzmany please add the points you mentioned in the PR to the documentation.

@RCheesley we need to add the comments for plugin developers in case we want to get this PR merged

**Comment by kuzmany** [comment]
I've resolve conflicts and test it.
Looks good for me
We use custom SMS provider

image

**Comment by RCheesley** [comment]
I might be missing something but there are listed BC breaks in the description - would that not require this to be held until the next major release, as we do not issue BC-breaking changes in minor releases?

**Comment by kuzmany** [comment]
@RCheesley In that time when I wrote the code, it was quite new code and I was sure nobody use it. Twilio integration is updated in this PR. 
I understand it's BC, but with note in release, we can let users knows about that. @escopecz what is your opinion?

**Comment by escopecz** [comment]
I would rather wait for 4.0 personally.

**Comment by RCheesley** [comment]
Semantic Versioning is quite clear on this and as this is what we follow, these rules must apply: 

https://semver.org/#spec-item-7

> Minor version Y (x.Y.z | x > 0) MUST be incremented if **new, backwards compatible functionality** is introduced to the public API. It MUST be incremented if any public API functionality is marked as deprecated. It MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes. Patch version MUST be reset to 0 when minor version is incremented.

https://semver.org/#spec-item-8

> Major version X (X.y.z | X > 0) MUST be incremented if **any backwards incompatible changes** are introduced to the public API. It MAY also include minor and patch level changes. Patch and minor version MUST be reset to 0 when major version is incremented.

As this includes backwards incompatible changes, it will need to wait for a major release.

**Comment by dennisameling** [comment]
Hi @kuzmany! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since this PR has conflicts now, could you please do a `git merge upstream/features` locally to resolve the conflicts? Thanks in advance!

**Comment by kuzmany** [comment]
Close favor to https://github.com/mautic/mautic/pull/9952

**Pull request closed without merging**
