### PR TITLE
Update robots.txt to remove unused folder

### PR DESCRIPTION
**Pull request by PierreAmmeloot**
Folder "addons" are gone.

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2.

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@PierreAmmeloot I don't think this folder is used any more, is it? Either way please make PRs against the Features branch rather than the 3.3 branch, as there will not be any more releases in the 3.x series other than fixing security issues. Thanks!

**Comment by RCheesley** [comment]
Also @PierreAmmeloot the CLA bot is failing as you filled the form with the GitHub username pierre_ammeloot but here you are using PierreAmmeloot. Which one should we add? If the latter could you please just complete the form with the correct username? Thanks!

**Comment by PierreAmmeloot** [comment]
Yes

Pierre

**Comment by npracht** [comment]
Hi @PierreAmmeloot.
Yes? You might misunderstood our feedbacks.

Ruth was asking you to:
1. You signed CLA agreement with `pierre_ammeloot` nickname while here you are using `PierreAmmeloot`. You need to resign it with the proper GitHub nickname please.
2. You need to rebase your PR against `features` branch as far as we don't support 3.3 branch anymore (except for security matters) if you want to see your PR merged.

Thanks

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Hi there,

Thank you for your contribution!

As we have released Mautic 4 now, the 3.x version is out of active support and therefore will not receive any further bug fixes or features.

If this PR is still relevant to Mautic 4, please either 

- Rebase on the 4.0 branch (for bug fixes) or the 4.x branch (for features and enhancements), or 
- Close this PR and make a fresh one on the correct branch.

If it is no longer relevant to Mautic 4, please close the PR.

Thanks in advance!

**Pull request closed without merging**
