### PR TITLE
Assets table new columns

### PR DESCRIPTION
**Pull request by alfredoct96**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | features
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | N/A

#### Description:
Added three new columns to assets table:
* created at
* modified at
* created by

Changed default order to decreasing modified at

### Before
assetsbefore

### After
assetsafter

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create two or more assets
3. Check existence of the new columns
4. Check the default order

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/9688"></a>

### CODE REVIEW

**Comment by kuzmany** [comment]
I am not sure If sort by modified date is the best https://github.com/mautic/mautic/pull/9688/files#diff-acd26f1f65a1e03f486c0b63cc678aebb396dd0b76d25be7d1262a205230170cR336
This will dynamically change ordering  of entities in time, what will be confused for users. For example I am using order by ID DESC (new to last)

**Comment by dennisameling** [comment]
Hi @alfredoct96! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since we don't have access to your branch, could you please click "Update branch" at the bottom of this PR? If that doesn't work, you can also run `git merge upstream/features` locally. Thanks in advance!

image

**Comment by alfredoct96** [comment]
> Hi @alfredoct96! Thanks for your PR  we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since we don't have access to your branch, could you please click "Update branch" at the bottom of this PR? If that doesn't work, you can also run `git merge upstream/features` locally. Thanks in advance!
> 
> image

Done @dennisameling

**Comment by RCheesley** [comment]
@alfredoct96 please merge in the changes from 4.x - we have a critical Gitpod fix and we can't merge it as you're on a protected branch with this PR, so it's blocking us testing this PR. Thanks!

**Comment by alfredoct96** [comment]
> Sponsor

I did the rebase with 4.x

**Review by RCheesley — DISMISSED** [review]
Thanks for your patience @alfredoct96 - I think these extra fields are useful for the user, and personally I think having last modified as the default sort order does make sense from the user perspective, and it's a simple one-click process to change to something else (e.g. ID) if you prefer some other way of sorting.

**Review by kuzmany — CHANGES_REQUESTED** [review]
Works. 
But could we change same date formatting like for segments? With short one with tooltip?

**Comment by alfredoct96** [comment]
> Works. But could we change same date formatting like for segments? With short one with tooltip?

@kuzmany Done

**Review by kuzmany — APPROVED** [review]

**Pull request merged**
