### PR TITLE
Campaign preview

### PR DESCRIPTION
**Pull request by GaberNeighbor**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Steps to test this PR:
1. Campaigns > any campaign > Details
2. Scroll down to stats tabs
3. Observe "preview" tab - it should be automatically selected, and displaying the current campaign flowchart created in the builder
4. Details > Edit > Launch Campaign Builder
5. Modify campaign by adding/removing events
6. save/close campaign builder
7. Save edit view, close > Details
8. Observe "preview" tab - it should be updated with the latest changes from the campaign builder
9. Repeat steps 4-8 as necessary to confidently approve the feature

### CODE REVIEW

**Comment by escopecz** [comment]
I'm getting `The template "MauticCampaignBundle:Campaign:preview.html.php" does not exist.` on step 1.

**Comment by dongilbert** [comment]
Seeing the same error as @escopecz. @GaberNeighbor Can you commit the preview template?

**Comment by dongilbert** [comment]
@GaberNeighbor Any updates?

**Comment by virlatinus** [comment]
There is an issue with this PR: The preview shows all existing campaign sources, not just the sources for the current campaign:

This campaign should have only 2 segments:
image

This campaign should have only the form:
image

**Comment by virlatinus** [comment]
I added code to show the correct campaign sources

**Pull request merged**
