### PR TITLE
Update form.html.twig

### LINKED ISSUE #12560: A/B Test functionality not working
### Mautic Version

5.0.x series

### PHP version

8.0.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

I was creating a landing page and intended to test the A/B testing feature. However, when I clicked on the button to activate this functionality, I encountered an issue. I received the following error message: "Your request could not be processed, please try again."

I tested it on two different Mautic installations of version 5 and encountered the same problem in both.

### How can we reproduce this issue?

Step 1: Go to Components > Landing Page.
Step 2: On the list, click on the title of a landing page (if you already have one created) to open its details.
Step 3: Under the graph, you will see a large button labeled "Create an A/B test." Click on it.
Step 4: After clicking the button, nothing happens, and an error message appears.

------
image

### Relevant log output

```shell
[2023-07-14T11:52:50.839053+00:00] mautic.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Field "template" has already been rendered, save the result of previous render call to a variable and output that instead.")." at /var/www/mautic/app/bundles/PageBundle/Resources/views/Page/form.html.twig line 99 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Field \"template\" has already been rendered, save the result of previous render call to a variable and output that instead.\"). at /var/www/mautic/app/bundles/PageBundle/Resources/views/Page/form.html.twig:99)\n[previous exception] [object] (Symfony\\Component\\Form\\Exception\\BadMethodCallException(code: 0): Field \"template\" has already been rendered, save the result of previous render call to a variable and output that instead. at /var/www/mautic/vendor/symfony/form/FormRenderer.php:136)"} {"hostname":"0b1ca92b843d","pid":39628}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by porubma**
Element can be rendered only once. 
Fields in right panel are rendered first at line 72. Rendering second time (in 99 line) is giving error. This error is generated by file /vendor/symfony/form/FormRenderer.php at 136. line.

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #12560

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by porubma** [comment]
The A/B testing of landing page didn't work (mautic 5).

**Comment by escopecz** [comment]
I was able to reproduce this issue when making a A/B test from a landing page:
Screenshot 2024-01-15 at 09 53 28

However, it looks like the field is missing now. Can you edit the variant content in the builder? I can't. And the JS error is:
```js
Uncaught Error: No valid HTML template found
    at o.getOriginalContentHtml (content.service.js:110:13)
    at d.value (builder.service.js:147:34)
    at d.value (builder.service.js:100:26)
    at Object.s [as launchBuilder] (builder.js:34:11)
    at HTMLButtonElement.onclick (24:1988:9)
    at Object.trigger (jquery.js?v27ef72d9:8625:27)
    at HTMLButtonElement.<anonymous> (jquery.js?v27ef72d9:8697:17)
    at Function.each (jquery.js?v27ef72d9:383:19)
    at jQuery.fn.init.each (jquery.js?v27ef72d9:205:17)
    at jQuery.fn.init.trigger (jquery.js?v27ef72d9:8696:15)
```

It was very similar in the PHP template in M4: https://github.com/mautic/mautic/blob/4.4/app/bundles/PageBundle/Views/Page/form.html.php

**Comment by escopecz** [comment]
Is this an issue only with the legacy builder? It seem to be working file with GrapesJS

**Comment by porubma** [comment]
I had this problem with GrapesJS.

**Comment by code5rick** [comment]
@RCheesley tested, and the A/B functionality now works fine!
Indeed, this feature wasn't working in the last public version 5 👍

**Review by escopecz — APPROVED** [review]
I was able to replicate this with the steps in https://github.com/mautic/mautic/issues/12560 and this fixed the error. I was able to edit the variant page in the GrapesJS builder too 👍

**Comment by escopecz** [comment]
@porubma Can you please rebase this PR on 5.0 branch so it could be merged to 5.0.2? If it's in the 5.x branch then it would go to 5.1.0.

**Comment by escopecz** [comment]
Do you need help with the rebase? I usually do

1. `git fetch upstream` (if upstream is the mautic/mautic remote name)
2. `git checkout patch-1` (this PR branch)
3. `git rebase upstream/5.0`

I can see that you have a conflict in the composer.lock. You can simply use theirs or yours. Doesn't matter. Just finish the rebase and then run `composer update --lock` which will update the composer.lock file to the right state.

**Comment by escopecz** [comment]
Would you mind if I give this a go?

**Comment by porubma** [comment]
Please can you do it? I have no github experience as you can see :(

**Comment by escopecz** [comment]
It was somehow tricky. So many conflicts I had. So I simply made a backup of this branch, reset this branch to the 5.0 branch and then cherry-picked https://github.com/porubma/mautic/commit/fb6e603b1aadbf00255d8b72db5048681f1648f9 on top of it.

**Comment by porubma** [comment]
Thanks

**Pull request merged**
