### PR TITLE
Citrix oAuth2 refactoring

### PR DESCRIPTION
**Pull request by anton-vlasenko**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Automated tests included? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR adds unit tests to the code submitted in https://github.com/mautic/mautic/pull/7380.
Also it contains refactoring of the code from the previously mentioned PR.

But with 7380, the refresh token was not taken into account so the plugin had to be manually re-authenticated every hour. This PR fixes that by adding the necessary support from the legacy integration framework to refresh access tokens using a refresh token.

#### Steps to reproduce the bug:
1. Set up one of the Goto integrations, authorize then wait 1 hour
1. Create a campaign to add the contact to a Goto event (meeting, webinar, etc)
1. Notice that the drop down list is empty and the log shows "token expired" error
1. Steps to test this PR:
1. Load up this PR
1. Repeat and the access token will refresh using the refresh token

Code hack to simulate:
1. It helps to have xdebug setup or else you'll have to extract the unencrypted access token to confirm that it changed
1. Add a xdebug breakpoint at https://github.com/mautic/mautic/blob/07c2c5a5edb3576304684afa2f80eea97fc343e7/app/bundles/PluginBundle/Integration/AbstractIntegration.php#L1499.
1. Before that line add $this->keys['expires'] = 1;
1. Add a campaign action from the step 2 of the steps to reproduce bug above
1. Note the value in $this->keys['access_token'] through xdebug
1. Repeat step 4 and note that the access token is now different

### CODE REVIEW

**Comment by npracht** [comment]
@anton-vlasenko can you check Travis please ?

**Comment by anton-vlasenko** [comment]
@npracht I've fixed the issue with Travis. Thank you for pointing out.
This PR also includes commit from the mautic cloud:
https://github.com/mautic/mautic/pull/7754/commits/bceb29c03cc76dbb0c880f78bbe9d638510f21c8.
So with this commit we make our integrations depend on UnifiedIntegrationInterface insted of AbstractIntegration class. It also resolves issue discussed here:

**Comment by anton-vlasenko** [comment]
I've fixed the issue with Travis. Thank you for pointing out, @npracht.
Also this PR contains a [commit](https://github.com/mautic/mautic/pull/7754/commits/bceb29c03cc76dbb0c880f78bbe9d638510f21c8) that fixes issue discussed here: https://mautic.slack.com/archives/C02HV76BW/p1565775874088900

**Comment by ekkeguembel** [comment]
@anton-vlasenko How does this PR relate to #7531 (part of 2.15.3)? It seems to address the same things (at least partly)

**Comment by RCheesley** [comment]
Bumping to 3.1.1 due to lots of unresolved conflicts!

**Comment by anton-vlasenko** [comment]
The conflicts have been fixed.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by mabumusa1** [comment]
@mtshaw3  May you please sign the contributor agreement found https://www.mautic.org/contributor-agreement, I think this PR is ready for merge, we are pending your sign

**Comment by RCheesley** [comment]
Bumping the PR to 3.1.2 due to a lack of testing - @oltmanns-leuchtfeuer maybe some of your team might be able to help with testing on this one?

**Review by LeonOltmanns — DISMISSED** [review]
Tested the PR as requested and it worked. Waited an hour and still webinars were still loaded, thus the refresh token did it's work accordingly. :)

**Comment by dennisameling** [comment]
Bumping to 3.2 due to pending CLA from @mtshaw3

**Comment by anton-vlasenko** [comment]
Conflicts have been resolved. I suppose it can be merged now (if this is a Tier 2 PR).

**Comment by RCheesley** [comment]
Pending tests passing after the branch being updated this should be GTG

**Comment by RCheesley** [comment]
Sorry @anton-vlasenko this is going to reduce test coverage so we need to bring it up to maintaining or improving coverage before we can merge it.

**Comment by anton-vlasenko** [comment]
@RCheesley Sorry, I believe this PR was all green when I wrote that comment. Probably I didn't notice that the code coverage got worse.
I will fix it once I'm on the community rotation next time. Or maybe some other developer will be willing to add more tests in the meantime.

**Review by kuzmany — DISMISSED** [review]
We are using it on production long time. 
Looks like works properly.
If we add unit tests, we can merge it.

@fedys can you look on unit tests for PR for of your colleague?

**Review by kuzmany — DISMISSED** [review]
👍

**Comment by anton-vlasenko** [comment]
> We are using it on production long time.
> Looks like works properly.
> If we add unit tests, we can merge it.
> 
> @fedys can you look on unit tests for PR for of your colleague?

@RCheesley 
Considering this comment from Kuzmany do we still need to test this?
Could we remove the `pending-test-confirmation` label and merge it?

**Comment by RCheesley** [comment]
@anton-vlasenko should be good to go now that the test coverage has been increased - let's update the branch / rerun the tests and then merge if all is ✅

**Comment by anton-vlasenko** [comment]
@RCheesley There was 1 small issue in the unit test and I fixed it.
Could we possible merge this PR because all is green now?
Thank you.

**Comment by RCheesley** [comment]
Your wish is my command 🧙‍♀️ ✨

**Comment by anton-vlasenko** [comment]
@RCheesley 🤣  I thought it's the other way around :)

**Pull request merged**
