### PR TITLE
Switch Doctrine cache to Symfony cache

### LINKED ISSUE #8289: Remove doctrine/doctrine-cache-bundle dependency
> This release drops support for PHP < 7.1 and marks this bundle as deprecated. With Symfony shipping its own cache component, there is no need to configure caches using this bundle in Symfony anymore.

Read more details at https://github.com/doctrine/DoctrineCacheBundle/releases/tag/1.4.0

We use it only for API limiter that was added a year ago 

https://github.com/mautic/mautic/blame/61907dd315985842dccbd1a5a60614fd6cfbce02/app/config/config.php#L360

@Dcoutelle or @npracht will you have time to change that to use Symfony's cache bundle instead so we could remove that deprecated dependency? 

https://symfony.com/doc/current/cache.html#configuring-cache-with-frameworkbundle

### PR DESCRIPTION
**Pull request by Enc3phale**
closes #8289

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? |N
| Related user documentation PR URL | N
| Related developer documentation PR URL | N
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/8289
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

Use Symfony's cache bundle instead Doctrine's cache bundle

### CODE REVIEW

**Comment by hluchas** [comment]
I'm getting error (cache dir is empty)

```
~/dev/community-fork(m3-switch-doctrine-cache) $ bin/console cache:warmup -e dev -v

In ArrayNode.php line 303:
                                                                                   
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]    
  Unrecognized option "type" under "framework.cache.pools.api_rate_limiter_cache"  
                                                                                   

Exception trace:
  at /Users/lukas.drahy/dev/community-fork/vendor/symfony/config/Definition/ArrayNode.php:303
 Symfony\Component\Config\Definition\ArrayNode->normalizeValue() at /Users/lukas.drahy/dev/community-fork/vendor/symfony/config/Definition/BaseNode.php:296
 Symfony\Component\Config\Definition\BaseNode->normalize() at /Users/lukas.drahy/dev/community-fork/vendor/symfony/config/Definition/PrototypedArrayNode.php:271
 Symfony\Component\Config\Definition\PrototypedArrayNode->normalizeValue() at /Users/lukas.drahy/dev/community-fork/vendor/symfony/config/Definition/BaseNode.php:296
 Symfony\Component\Config\Definition\BaseNode->normalize() at /Users/lukas.drahy/dev/community-fork/vendor/symfony/config/Definition/ArrayNode.php:292
 Symfony\Component\Config\Definition\ArrayNode->normalizeValue() at /Users/lukas.drahy/dev/community-fork/vendor/symfony/config/Definition/BaseNode.php:296
 Symfony\Component\Config\Definition\BaseNode->normalize() at /Users/lukas.drahy/dev/community-fork/vendor/symfony/config/Definition/ArrayNode.php:292
 Symfony\Component\Config\Definition\ArrayNode->normalizeValue() at /Users/lukas.drahy/dev/community-fork/vendor/symfony/config/Definition/BaseNode.php:296
 Symfony\Component\Config\Definition\BaseNode->normalize() at /Users/lukas.drahy/dev/community-fork/vendor/symfony/config/Definition/Processor.php:33
 Symfony\Component\Config\Definition\Processor->process() at /Users/lukas.drahy/dev/community-fork/vendor/symfony/config/Definition/Processor.php:50
 Symfony\Component\Config\Definition\Processor->processConfiguration() at /Users/lukas.drahy/dev/community-fork/vendor/symfony/dependency-injection/Extension/Extension.php:97
 Symfony\Component\DependencyInjection\Extension\Extension->processConfiguration() at /Users/lukas.drahy/dev/community-fork/vendor/symfony/framework-bundle/DependencyInjection/FrameworkExtension.php:176
 Symfony\Bundle\FrameworkBundle\DependencyInjection\FrameworkExtension->load() at /Users/lukas.drahy/dev/community-fork/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:71
 Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process() at /Users/lukas.drahy/dev/community-fork/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:39
 Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process() at /Users/lukas.drahy/dev/community-fork/vendor/symfony/dependency-injection/Compiler/Compiler.php:140
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /Users/lukas.drahy/dev/community-fork/vendor/symfony/dependency-injection/ContainerBuilder.php:790
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /Users/lukas.drahy/dev/community-fork/vendor/symfony/http-kernel/Kernel.php:643
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /Users/lukas.drahy/dev/community-fork/app/AppKernel.php:518
 AppKernel->initializeContainer() at /Users/lukas.drahy/dev/community-fork/app/AppKernel.php:278
 AppKernel->boot() at /Users/lukas.drahy/dev/community-fork/vendor/symfony/framework-bundle/Console/Application.php:64
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/lukas.drahy/dev/community-fork/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /Users/lukas.drahy/dev/community-fork/bin/console:41

~/dev/community-fork(m3-switch-doctrine-cache) $ 
```

**Comment by Enc3phale** [comment]
You need to edit your local.php to correspond to config.php modifications.
```
'api_rate_limiter_cache'            => [
     'adapter' => 'cache.adapter.filesystem',
],
```

**Comment by hluchas** [comment]
> You need to edit your local.php to correspond to config.php modifications.
> 
> ```
> 'api_rate_limiter_cache'            => [
>      'adapter' => 'cache.adapter.filesystem',
> ],
> ```

I'm sorry but the problem persist

**Comment by Enc3phale** [comment]
After clear cache ? I have no problem on my instance.
Can you send me errors ?

**Comment by hluchas** [comment]
> After clear cache ? I have no problem on my instance.
> Can you send me errors ?

Yes. It is the same error when I use `bin/console cache:clear -e dev -v` or delete cache folder content manually. Error is described above with stack trace

**Comment by hluchas** [comment]
I'm sorry. I had 
```
'api_rate_limiter_cache'            => [
     'type' => 'cache.adapter.filesystem',
],
```
in my local.php

**Comment by hluchas** [comment]
There could be problem with this when upgrading app. I needed to change 
```
'api_rate_limiter_cache'            => [
     'type' => 'cache.adapter.filesystem',
],
```
in `local.php` to
```
'api_rate_limiter_cache'            => [
     'adapter' => 'cache.adapter.filesystem',
],
```
somehow. There only one way to do that for now. Edit `local.php` manually. If I'm correct, we need to leave note somewhere. @escopecz What do you think?

**Comment by escopecz** [comment]
Yep, a note about a BC break in the Gdoc

**Comment by hluchas** [comment]
> Yep, a note about a BC break in the Gdoc

Done on page 2

**Pull request merged**
