### PR TITLE
Fix "like" and "not like" on segment update

### PR DESCRIPTION
**Pull request by Dcoutelle**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #4227
| BC breaks? | N
| Deprecations? | N

[//]: # ( Required: )
#### Description:

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Make one segment, with visited URL like `your_value`
2. Make one segment, with visited URL not like `your_value`
3. run `mautic:segments:update`
4. check lead are not in proper segement

#### Steps to test this PR:
1. Apply this PR
2. run `mautic:segments:update`
3. check lead are in proper segment

### CODE REVIEW

**Comment by escopecz** [comment]
Thanks for this! The "Visited URL like ..." started to work correctly when I applied this PR, but "Visited URL not like" does not work - it does not add any contacts to it even though it should be all except the one which is in the "like" segment.

While looking at the code, you changed `!like` to `notLike`, but the select of operators has `!like` as the key. Maybe that's the problem?
screen shot 2017-06-13 at 10 19 57

**Comment by dongilbert** [comment]
It's a BC error to change the code to `notLike` instead of leaving it as `!like`. Going to push a fix to this PR for that and test. It should resolve the issue @escopecz

**Comment by dongilbert** [comment]
Even with the change back to `!like`, it doesn't seem to be working to add users based on `Visited URL not like X`. Leaving this as pending feedback for now @Dcoutelle

**Comment by Dcoutelle** [comment]
I made it work with ```notLike``` while running segment update command and I saw this value into a debugger.

I will take a look next days.

**Comment by Dcoutelle** [comment]
@escopecz @dongilbert 

I made new test with visited URL and referer URL and `not like` path is working here.

`!like` input is transformed in `notLike` at [line 661](https://github.com/Webmecanik/mautic/blob/475f19fb545c138abfe7b459708d759c7c2e3e12/app/bundles/LeadBundle/Entity/LeadListRepository.php#L661)
image

When you test, lead don't go in the segment ? 
How can I reproduce your problem ?

**Comment by escopecz** [comment]
I followed your steps. The segment with "not like" operator did not populate any contacts even though it should be all existing contacts except 1.

**Comment by MaxWebmecanik** [comment]
@escopecz How are you testing this?

image

Just trying this works for me...

**Comment by MaxWebmecanik** [comment]
By the way, this seems to be the where the mapping from `!like` to `notLike` takes place.
https://github.com/mautic/mautic/blob/master/app/bundles/FormBundle/Model/FormModel.php#L816-L820

**Comment by dongilbert** [comment]
#3346 Possibly related

**Comment by MaxWebmecanik** [comment]
I mean... do you guys need more information? We'll gladly help.

**Comment by escopecz** [comment]
I re-tested. Here is how it looks like:
screen shot 2017-06-20 at 11 17 24

You can see that there are 2 contacts who visited a page which has "test" in the URL. There is 51 contacts in total. So the number of contacts who did not visit a page which contains "test" in the URL should not be 2, but 49. This is how I expect it to work. Or is my expectation wrong?

From this test it seems that "not like" does not count contacts which did not visit any page. In other words, they don't have any record in the page_hits table. Maybe an outer join should be somewhere?

**Comment by dongilbert** [comment]
The problem is with the query. It seems to only pull in leads that have visited a URL at all, and then only if the the URL matches the filters (like or not like).

**Comment by dongilbert** [comment]
@escopecz @MaxWebmecanik @Dcoutelle I've pushed some changes to the repository. We talked it over, and believe that the common practice amongst marketing automation & segment building tools (and the real goal of someone adding a filter that says "contacts that did not visit a page like X") is that a segment with such a filter should contain every contact that did not hit that page, including contacts that did not hit _any_ page. My changes reflect that, as well as add tests to verify the functionality. Can you test?

**Comment by mqueme** [comment]
Works!

**Comment by Dcoutelle** [comment]
Working too.

**Pull request merged**
