### PR TITLE
Store company changes on new contact save via UI

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.0 for bug fixes 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | /
| Related developer documentation PR URL | /
| Issue(s) addressed                     | /

#### Description:

When a contact was saved from UI form then the company information was not stored as one of the changes. This is an issue for audit log and for the IntegrationsBundle which did not record the company change this way. And the audit log was incomplete.

Screen Shot 2020-10-02 at 14 50 44

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a new contact with a company associated to it.
2. Check the audit log table record. It does not have the company change in it.

#### Steps to test this PR:
1. Create a new contact with a company associated to it.
2. Check the audit log table record. It does have the company change in it.

#### Other areas of Mautic that may be affected by the change:
1. Just creating a new contact via UI form

### CODE REVIEW

**Review by kuzmany — DISMISSED** [review]
Works for me 👍 

But there is still miss a lot of logged actions during the modify companies/mark as primary etc. Understand,  it's not purpose of this PR, but we should look on it later

**Review by dadarya0 — DISMISSED** [review]
Working for me, TY

**Comment by npracht** [comment]
@escopecz can you please resolve confict and then merge the PR :)

**Comment by escopecz** [comment]
Rebased. Merging.

**Pull request merged**
