### PR TITLE
Initial batch of Codeception acceptance tests for Companies (Dup #8710)

### PR DESCRIPTION
**Pull request by RCheesley**
So I learned the lesson the hard way not to delete my fork when there are open PR's! I have rebased against the 3.x branch. Apologies for the hassle!

This is a duplicate (intentional) of #8710 

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | x
| Automated tests included? | x
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Required: )
#### Description:
We have almost no Codeception acceptance tests that could be run against new releases of Mautic. I've started writing some which we can hopefully use to improve our UAT process.

This PR covers what I believe to be the basic set of tests for Companies. It can probably be improved, optimised and more tests added to make sure we have full coverage of all the possible actions that can be taken against companies, but it's a starting point!

I plan to chip away at creating a basic set of tests for each bundle, and then we can expand on them going forward to add more complexity, refine, and optimise/test cross browser/platform etc with Browserstack. If anyone would like to help with this please ping me on Slack.

A couple of points to add if testing these:

* I had to force Codeception to use max resolution using the following in my acceptance.suite.yml on all environments:
```
actor: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: http://local.mauticautomatedtests
            browser: chrome
            window_size: 1920x1080
        - \Helper\Acceptance
```
* On my Mac I had to set an argument of w2c: false per [this StackOverflow post](https://stackoverflow.com/questions/56556709/codeception-undefined-index-element-error/59875669#59875669).

* Depending on the speed of your environment, you may need to tinker with the wait periods. I tried to keep them as low as possible so as not to delay the tests overly, but if you have a slower machine you might find that errors are thrown. If you are seeing errors relating to fields not being visible or editable, throw in an `$I->makeScreenshot('file-name');` directly before the offending line and check the output to see if the field is in the process of being rendered.

* We are using a super outdated version of Codeception so some newer actions (e.g. clearField) are not available. This meant some slightly longer winded tests having to manually clear fields.

I wrote up the steps I followed to [get set up for testing and writing tests with Codeception](https://www.ruthcheesley.co.uk/blog/development/learning-to-write-acceptance-tests-with-codeception) in case it is helpful for anyone who would like to contribute to this going forward.

#### Steps to test this PR:
No testing required on the PR itself, but it would be helpful if some folk could test the acceptance tests and make sure they are correct/working as expected.

### CODE REVIEW

**Comment by hluchas** [comment]
Installation steps for selenium under osx is not working for me now as described here https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#codeceptionselenium

Content of `/usr/local/Cellar/selenium-server-standalone/3.5.3/homebrew.mxcl.selenium-server-standalone.plist` which has a bit different path.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>homebrew.mxcl.selenium-server-standalone</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <false/>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/bin/java</string>
    <string>-jar</string>
    <string>/usr/local/Cellar/selenium-server-standalone/3.141.59_1/libexec/selenium-server-standalone-3.141.59.jar</string>
    <string>-port</string>
    <string>4444</string>
    <string>-Dwebdriver.chrome.driver=/usr/local/Cellar/selenium-server-standalone/drivers/chromedriver</string>
  </array>
```
I didn't find path to chrome driver in paths:

- /usr/local/Cellar/selenium-server-standalone
- /usr/local/Cellar/selenium-server-standalone/3.141.59_1/

EDIT:
`brew cask install chromedriver`

`composer require codeception/module-webdriver --dev`
Is missing in composer json

I'm acruattly only able to run `bin/codecept run acceptance` with 
```
  [ConnectionException] Can't connect to Webdriver at http://127.0.0.1:4444/wd/hub. Please make sure that Selenium Server or PhantomJS is running.  
```

It needs to update ěinstall doc mentioned above

Tried for second time. Hopefully I'll get back to this tomorrow

**Comment by RCheesley** [comment]
> https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#codeceptionselenium

Which part is failing? What are the errors? Might be able to help as I had some struggles too!

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Closing as we are no longer using Codeception.

**Pull request closed without merging**
