### PR TITLE
Fix access_token expired after 1 hour for Go To plugins

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
2.15.2 add new Adapt GoTo plugin for oauth2 authentication https://github.com/mautic/mautic/pull/7380
But according to the documentation https://goto-developer.logmeininc.com/how-use-refresh-tokens access_token expire every one hour.
This PR try identify If access_token is invalid and then try refresh it (docs above)

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Setup GOTO plugin (webinar for example)
2. Authorize, and try use it one hour later. If you are on dev enviroment, you should see error in logs

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com/7531)
2. Repeat all steps. You access token should refresh after one hour

### CODE REVIEW

**Comment by johbuch** [comment]
hi zdeno, I created a new app in gotowebinar, then set the plugin but when I want to push contact to webinar through a form, I can't because my webinar does not appear 
image
I should have a webinar displayed

**Comment by kuzmany** [comment]
It's new issue?
Or it happend after upgrade?
Could you share with me goto credentials?

**Comment by johbuch** [comment]
@kuzmany  we patched this PR on my instance, I could set and authorised the plugin, but then webinars don't display.
i wrote you on slack

**Comment by kuzmany** [comment]
@johbuch last commit fixed it.

**Pull request merged**
