### PR TITLE
Fix npm dependencies: deinstall grunt-remove, update grunt 

### LINKED ISSUE #12007: npm install leads to dependency problems: grunt-remove@0.1.0
### Mautic Version

5.0.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

On the newest code I run `npm install`

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: grunt-remove@0.1.0
npm ERR! Found: grunt@1.5.3
npm ERR! node_modules/grunt
npm ERR!   dev grunt@"^1.5.3" from the root project
npm ERR!   peer grunt@">=0.4.2" from grunt-autoprefixer@3.0.4
npm ERR!   node_modules/grunt-autoprefixer
npm ERR!     dev grunt-autoprefixer@"^3.0.4" from the root project
npm ERR!   1 more (load-grunt-tasks)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer grunt@"~0.4.1" from grunt-remove@0.1.0
npm ERR! node_modules/grunt-remove
npm ERR!   dev grunt-remove@"^0.1.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: grunt@0.4.5
npm ERR! node_modules/grunt
npm ERR!   peer grunt@"~0.4.1" from grunt-remove@0.1.0
npm ERR!   node_modules/grunt-remove
npm ERR!     dev grunt-remove@"^0.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### How can we reproduce this issue?

Step 1:  load the latest code from the 5.x branch
Step 2: In the root folder run `npm install`. It will fail to install the dependencies.

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by adiux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #12007

#### Description:
There are issues with the current javascript dependencies. This PR fixes those by removing the unused package `grunt-remove`. In addition, multiple devDependencies were updated to the latest version. These are only dev dependencies. So there is no impact for the user. 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. run `npm install` in the root folder => there should be no error and a message in the style like this: `added 1 package, removed 15 packages, changed 14 packages, and audited 219 packages in 3s`

### CODE REVIEW

**Comment by adiux** [comment]
While fixing this I noticed that the plugins .LESS files are not converted with the watch command. Or is this on purpose? https://github.com/mautic/mautic/issues/12034

**Comment by escopecz** [comment]
I don't think it's on purpose. I think that there was no plugin using LESS so far. Can you please fix the scaffolded files missmatch check?

**Review by escopecz — APPROVED** [review]
Thanks! I see no issues in the code 👍

**Comment by escopecz** [comment]
I tested it and it works correctly:
```
~/html (fix-grunt-remove-update-grunt) $ npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'grunt@1.6.1',
npm WARN EBADENGINE   required: { node: '>=16' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN deprecated time-grunt@2.0.0: Deprecated because Grunt is practically unmaintained. Move on to something better. This package will continue to work with Grunt v1, but it will not receive any updates.
npm WARN deprecated browserslist@0.4.0: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.

added 218 packages, and audited 219 packages in 8s

20 packages are looking for funding
  run `npm fund` for details

4 vulnerabilities (2 moderate, 2 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
~/html (fix-grunt-remove-update-grunt) $ grunt compile-less
Running "less:files" (less) task
>> 8 stylesheets created.

Running "watch" task
Waiting...
```
As this PR is not changing any production files and only files needed like once per year in development and it worked in my test (result above) then I'm merging this PR without waiting for a second review.

**Pull request merged**
