### PR TITLE
Fix segment filteration issue on custom object

### PR DESCRIPTION
**Pull request by dadarya0**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | Yes
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | Yes 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
There was an error if using custom object filter in segment.
`Fatal error: Uncaught Error: Undefined constant Mautic\LeadBundle\LeadEvents::LIST_FILTERS_MERGE in /var/www/html/docroot/plugins/CustomObjectsBundle/EventListener/SegmentFiltersMergeSubscriber.php:27`

it is fixed now

#### Steps to test this PR:

1. Create a segment
2. Add multiple filter on same type of custom object filed 
3. Wait for segment rebuild
4. Segment should be rebuild correctly.

### CODE REVIEW

**Comment by escopecz** [comment]
This is breaking the Custom Objects plugin once https://github.com/acquia/mc-cs-plugin-custom-objects/pull/331 was merged.

@dadarya0 could you please also create a duplicate PR on top of the 4.4 branch? Because the CO plugin is not yet ready for M5 then this PR won't fix it for all the M4 users.

**Review by escopecz — APPROVED** [review]
The code looks fine. It's adding an option for plugins to hook up to the segment rebuild like the Custom Objects plugin does.

This PR cannot be tested without the CO plugin which still works only on M4. We can test that segments are still building and we have many functional tests for that. So this is safe to merge 👍

**Review by mabumusa1 — APPROVED** [review]
I tested locally as i have this issue, this PR fixed the issue

**Comment by escopecz** [comment]
Note: The M4 is on security fixes diet only now so this cannot be backported to M4 officially.

**Pull request merged**
