### PR TITLE
Fix input format for onesignal.

### LINKED ISSUE #6709: OneSignal notifications with "Additional Data" are failing
What type of report is this: Bug report

## Description:

When sending push notification with OneSignal plugin, generated JSON body looks like this:

```
{
  "include_player_ids" : [ "*******" ],
  "contents" : {
    "en" : "Happy"
  },
  "headings" : {
    "en" : "Tesla"
  },
  "data" :  [{
    "label" : "Data",
    "value" : "Value"
  }] ,
  "subtitle" : {
    "en" : "Subtitle"
  },
  "ios_sound" : "default",
  "ios_badgeType" : null,
  "ios_badgeCount" : 0,
  "content_available" : false,
  "ios_attachments" : {
    "id_5bb604839338e" : null
  },
  "mutable_content" : false,
  "android_sound" : null,
  "small_icon" : null,
  "large_icon" : null,
  "big_picture" : null,
  "android_led_color" : "FF",
  "android_accent_color" : "FF",
  "android_group" : null,
  "android_visibility" : 0,
  "app_id" : "****"
}
```

Problem is with "data" field. According to one signal documentation (https://documentation.onesignal.com/reference#section-attachments) data field must be a map. Mautic generates array :

```
"data" :  [{
    "label" : "Data",
    "value" : "Value"
  }]
```

Should be :

```
"data" :  {
    "Data" : "Value"
  }

``` 

One signals gives following response to invalid request :

```
{
    "errors": [
        "Data must be a valid JSON object and cannot be a string, a number, true, or false. See bit.ly/2iBky3H for an example of a JSON object. You can use jsonlint.com as a JSON validator."
    ]
}
```

| Q   | A
| --- | ---
| Mautic version |2.14.1 |
| PHP version | 7.1.16|

### Steps to reproduce:
1. Create Mobile notification.
2. Under "Additional data" tab add any custom values.
3. Send push notification using one signal api

 
### Log errors: 

```
{
    "errors": [
        "Data must be a valid JSON object and cannot be a string, a number, true, or false. See bit.ly/2iBky3H for an example of a JSON object. You can use jsonlint.com as a JSON validator."
    ]
}
```

### PR DESCRIPTION
**Pull request by crasx**
closes #6709 - OneSignal notifications with "Additional Data" are failing.

@btbounteous and the Bounteous will be providing testing

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Automated tests included? | N
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #6709
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Requires OneSignal setup 
2. Create Mobile notification.
3. Under "Additional data" tab add any custom values.
4. Send push notification using one signal api and note the error

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. configure OneSignal
3. Repeat the above and there should not be an error

### CODE REVIEW

**Review by btbounteous — DISMISSED** [review]
I tested the code for one, multiple and no data values.

**Comment by crasx** [comment]
Coding standards fixed

**Comment by npracht** [comment]
@btbounteous and does it work ?

**Comment by btbounteous** [comment]
> @btbounteous and does it work ?

Yep, it works.

**Comment by npracht** [comment]
Hi there!
It has been decided to do not create any extra Mautic 2 version (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@btbounteous @crasx as this will reduce coverage we need tests before we can merge this PR - could you please take a look and add tests? 

Moving to 3.0.2 release as a result.

Thanks in advance!

**Comment by RCheesley** [comment]
Close & reopen for Scrutinizer

**Comment by RCheesley** [comment]
@crasx @btbounteous if you can write the tests we are aiming to get this released in [3.0.2](https://github.com/mautic/mautic/milestone/63).  We need the PR updated no later than Sunday, 19th July to make that happen - can you help with that?

**Comment by crasx** [comment]
@RCheesley unfortunately I do not have a Mautic environment set up or the bandwidth to get this done any time soon. Is this something someone on your end could finish up?

**Comment by RCheesley** [comment]
Bumping to the next release pending automated tests.

**Comment by RCheesley** [comment]
> @RCheesley unfortunately I do not have a Mautic environment set up or the bandwidth to get this done any time soon. Is this something someone on your end could finish up?

Not at this moment in time unfortunately, hopefully someone in the community will be able to pick it up going forward if you've enabled maintainers to edit the PR :)

**Comment by RCheesley** [comment]
Bumping to 3.1.1 due to the lack of tests, hoping that @crasx @btbounteous can find the time to add tests so we can merge next month!

**Comment by anton-vlasenko** [comment]
This PR has fixed the issue for me as well.

**Comment by RCheesley** [comment]
@crasx @btbounteous we have to bump this again due to the lack of automated tests.  If we are to consider this for the next release, this will need to be addressed by **18th October**

**Comment by npracht** [comment]
@crasx we just need you to add some unit tests then we can merge it (it has been tested). Could you please do that soon ? Then i merge it in 3.1.2 :)

**Pull request merged**
