### PR TITLE
Adding support for PHP 8.3

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

Adding support for PHP 8.3. 

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Everything should work on PHP 8.3 the same way as on 8.0, 8.1, 8.2. But ideally, our test suite should catch the issues.

### CODE REVIEW

**Review by RCheesley — CHANGES_REQUESTED** [review]
When clicking to open an email generated by the sample data (the Kaleidoscope ones), I am getting this error (doesn't occur with the Email Test one or if I create a new email and then open it):

```
[2024-07-15T16:46:15.576907+00:00] mautic.CRITICAL: Uncaught PHP Exception TypeError: "Cannot assign null to property Mautic\EmailBundle\Helper\PlainTextHelper::$html of type string" at /var/www/html/app/bundles/EmailBundle/Helper/PlainTextHelper.php line 232 {"exception":"[object] (TypeError(code: 0): Cannot assign null to property Mautic\\EmailBundle\\Helper\\PlainTextHelper::$html of type string at /var/www/html/app/bundles/EmailBundle/Helper/PlainTextHelper.php:232)
[stacktrace]
#0 /var/www/html/app/bundles/EmailBundle/Controller/EmailController.php(388): Mautic\\EmailBundle\\Helper\\PlainTextHelper->setHtml()
#1 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(163): Mautic\\EmailBundle\\Controller\\EmailController->viewAction()
#2 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()
#3 /var/www/html/vendor/symfony/framework-bundle/Controller/AbstractController.php(156): Symfony\\Component\\HttpKernel\\HttpKernel->handle()
#4 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(415): Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController->forward()
#5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(163): Mautic\\CoreBundle\\Controller\\CommonController->executeAction()
#6 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()
#7 /var/www/html/vendor/symfony/http-kernel/Kernel.php(202): Symfony\\Component\\HttpKernel\\HttpKernel->handle()
#8 /var/www/html/app/AppKernel.php(109): Symfony\\Component\\HttpKernel\\Kernel->handle()
#9 /var/www/html/app/middlewares/CORSMiddleware.php(76): AppKernel->handle()
#10 /var/www/html/app/middlewares/HSTSMiddleware.php(39): Mautic\\Middleware\\CORSMiddleware->handle()
#11 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(28): Mautic\\Middleware\\HSTSMiddleware->handle()
#12 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle()
#13 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle()
#14 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle()
#15 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle()
#16 /var/www/html/index.php(19): Stack\\StackedHttpKernel->handle()
#17 {main}
```

Just checking to see if that's also in 5.x.

**Review by RCheesley — APPROVED** [review]
Looks like that's a bug in the 5.x release so otherwise good to go! Raised it as #13966

**Comment by escopecz** [comment]
@fedys could you please make the review?

**Review by fedys — APPROVED** [review]
The code changes look good. Thanks @escopecz!

**Comment by matbcvo** [comment]
I've tested this PR, also looks good. I discovered few errors, but these errors are already documented and not related to this PR.

**Comment by RCheesley** [comment]
@all-contributors please add @matbcvo for review

**Comment by RCheesley** [comment]
@all-contributors please add @matbcvo for userTesting

**Pull request merged**
