### PR TITLE
Fix social monitoring command for twitter

### PR DESCRIPTION
**Pull request by SamWebmecanik**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | X
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #4100
| BC breaks? | 
| Deprecations? | 

[//]: # ( Required: )
#### Description:

When you launch this command : mautic:social:monitoring, it fail with an error : 

[Symfony\Component\Debug\Exception\ContextErrorException]
Catchable Fatal Error: Argument 2 passed to Mautic\PluginBundle\Helper\oAuthHelper::__construct() must be an instance of Symfony\Component\HttpFoundation\Request, null given, called in /home/contactsiwantasp/public_html/app/bundles/PluginBundle/Integration/AbstractIntegration.php on line 1119 and defined

⚠️ This fix is not a real solution I think, but it fixes. ⚠️ 

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Config the twitter plugin
2. Create a social monitoring
3. Launch `mautic:social:monitoring`
4. See the error, is the same in the description of this PR.

#### Steps to test this PR:
1. Apply this PR.
2. Config the twitter plugin
3. Create a social monitoring
4. Launch `mautic:social:monitoring`
5. See the lead create or update.

### CODE REVIEW

**Comment by mqueme** [comment]
Thank you @SamWebmecanik for spotting this, I have made a couple of changes to correctly fix this issue.

**Comment by SamWebmecanik** [comment]
@alanhartless like that?

**Comment by billybobilly** [comment]
manually made the updates to app/bundles/PluginBundle/Helper/oAuthHelper.php and plugins/MauticSocialBundle/Integration/SocialIntegration.php 

Ran the cron job

output looks like it's successfully processing everything that was collected over the past week or so since it stopped working:

...
Updating existing lead ID #429261 (breakfastcrmnls)
Updating existing lead ID #296740 (donnachaffins)
Updating existing lead ID #397103 (frostybluefarms)
Creating new lead
Creating new lead
Creating new lead
Creating new lead
Updating existing lead ID #288199 (recetaspormenos)
Updating existing lead ID #283203 (printablexpress)
Creating new lead
Creating new lead
Creating new lead
...

No errors so far.

**Comment by mqueme** [comment]
This works for me as well.

**Comment by neerajsinghsonu** [comment]
Twitter Social Monitoring CLI Fixed :) Yeah!! 💃 Thanks [#4252](https://github.com/mautic/mautic/pull/4252/files/bb35c4bf7f441c8830b08590236bcf23a19d3e21) to @SamWebmecanik 👍 

1 - Mautic v2.8.2
2 - Twitter CLI Symfony Error for Command (php console mautic:social:monitoring)

... Fixed Now. Check & Confirm :)

**Comment by sagarnangare** [comment]
I fixed it in Mautic 2.8.2. Wrote a simple blog post here [http://www.sagarnangare.net/mautic-cron-issue-fix-social-monitoring-command-twitter/](http://www.sagarnangare.net/mautic-cron-issue-fix-social-monitoring-command-twitter/)

**Pull request merged**
