### PR TITLE
Fix Transport Container Injection

### LINKED ISSUE #9948: Amazon SES bounce management (mailer/amazon_api/callback throws error 500)
Mautic Version: 4.0.0-aplha1
PHP: 7.4.10

I followed the tutorial and setup everything properly. 

Access Log file entry:
"POST /mailer/amazon_api/callback HTTP/1.1" 500 64931 "-" "Amazon Simple Notification Service Agent"

Error Log (in Mautic ) entry:

[2021-04-28 18:54:08] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "The "swiftmailer.transport.real" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead." at /opt/bitnami/mauticiibp/mautic/vendor/symfony/dependency-injection/Container.php line 275 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): The \"swiftmailer.transport.real\" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead. at /opt/bitnami/mauticiibp/mautic/vendor/symfony/dependency-injection/Container.php:275)"}

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features"
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #9948... 

#### Steps to test this PR:
To test this PR you need to do this:
1. Activate SendGrid or SES API, you can use Fake API keys since we are not going to send anything.
2. Depending on your selection you need to open on your browser the callback URL, in my case I selected SendGrid so you can open the link `https://domain.com/mailer/sendgrid_api/callback`
3. You will get a 500 error 

After loading this PR:
1. Go to the same callback URL
2. You should see the word `success`  instead of error 500

### CODE REVIEW

**Comment by RCheesley** [comment]
@mabumusa1 could you possibly give a bit more explicit detail for testers to reproduce the issue (eg what specifically they should be posting) as that will likely help you to get testers more quickly. Thanks!

**Comment by donbowman** [comment]
i applied the patch, and now i get a 200 OK on /mailer/amazon_api/callback

I can confirmed w/ SES i now get a bounce notif for a `bad` email addr.

**Review by RCheesley — DISMISSED** [review]
Confirm the bug without the PR being applied:

`[2021-08-24 15:52:22] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "The "swiftmailer.transport.real" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead." at /var/www/html/vendor/symfony/dependency-injection/Container.php line 275 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): The \"swiftmailer.transport.real\" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead. at /var/www/html/vendor/symfony/dependency-injection/Container.php:275)"} []
`

After applying the PR I was able to get a success response per the instructions in the PR.

**Comment by RCheesley** [comment]
This is RTC if we can have a code review - @mautic/core-team can anyone help please?

**Review by dennisameling — DISMISSED** [review]
As can be seen in the error message that @RCheesley shared, one of the options that Symfony recommends is:

> ... or stop using the container directly and use dependency injection instead.

Mautic has been slowly moving into that direction of [dependency injection](https://symfony.com/doc/current/service_container/injection_types.html), which has several benefits like type-hinting (allowing tools like PHPSTAN to also catch more potential bugs). It will allow us to catch these type of errors earlier, as this could've been signaled right after we did the Symfony 4 upgrade, [which made services private by default](https://symfonycasts.com/screencast/symfony-bundle/autowiring-public-private#public-versus-private-services).

Let's take this opportunity to at least switch `ProcessEmailQueueCommand` to direct dependency injection, which I just did in https://github.com/mautic/mautic/pull/10352/commits/5b1239e65091bb4b09be68cf6bc41aa907822924.

Callback is still working:

image

The affected command also boots correctly without any warnings/errors about the dependency injection:

```
$ php bin/console mautic:emails:send
Mautic is not set to queue email.
```

Apart from that this PR looks good to me 👍🏼

**Review by lukassykora — APPROVED** [review]
I can not see any problem. The code and test look OK.

**Pull request merged**
