### PR TITLE
Fix salesforce sync companies even are disabled

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR prevent  error of Salesforce

`mautic.NOTICE: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'SELECT i.integration_entity_id, i.integration_entity, i.id, i.internal_entity_id,l. FROM integration_entity i INNER JOIN companies l ON l.id = i.internal_entity_id WHERE (i.integration = ?) AND (i.integration_entity = ?) AND (i.internal_entity = ?) AND ((i.integration_entity_id IS NOT NULL) AND (((i.last_sync_date IS NOT NULL) AND (l.date_modified > i.last_sync_date)) OR ((i.last_sync_date IS NULL) AND (l.date_modified IS NOT NULL) AND (l.date_modified > l.date_added)))) AND (l.companyname IS NOT NULL) AND (l.date_modified BETWEEN ? and ?) LIMIT 100' with params ["Salesforce", "Account", "company", "2021-09-30 01:04:06", "2021-09-30 01:24:06"]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM integration_entity i INNER JOIN companies l ON l.id = i.internal_entity_id ' at line 1 (uncaught exception)`

#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2. Setup Salesforce but not setup Account/Activity
3. Check Salesforce If you have some contacts/companies to sync
4. Then you can run `php bin/console mautic:integration:fetchleads --time-interval="60 minutes" --integration=Salesforce`
5. You should see error 

`mautic.NOTICE: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'SELECT i.integration_entity_id, i.integration_entity, i.id, i.internal_entity_id,l. FROM integration_entity i INNER JOIN companies l ON l.id = i.internal_entity_id WHERE (i.integration = ?) AND (i.integration_entity = ?) AND (i.internal_entity = ?) AND ((i.integration_entity_id IS NOT NULL) AND (((i.last_sync_date IS NOT NULL) AND (l.date_modified > i.last_sync_date)) OR ((i.last_sync_date IS NULL) AND (l.date_modified IS NOT NULL) AND (l.date_modified > l.date_added)))) AND (l.companyname IS NOT NULL) AND (l.date_modified BETWEEN ? and ?) LIMIT 100' with params ["Salesforce", "Account", "company", "2021-09-30 01:04:06", "2021-09-30 01:24:06"]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM integration_entity i INNER JOIN companies l ON l.id = i.internal_entity_id ' at line 1 (uncaught exception)`

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
The code change makes sense. I did not test it though 👍

**Review by npracht — APPROVED** [review]
Tested it with Salesforce account and it fixes the issue ✅

**Comment by alfredoct96** [comment]
@kuzmany "push_companies" settings doesn't exist and will never enter in this condition, why did you do this change? Am i missing something?

**Comment by kuzmany** [comment]
@alfredoct96 I see Salesforce support for companies sync

image

**Comment by alfredoct96** [comment]
@kuzmany  Yes, but that two features are associated to the options `get_leads` and `push_leads` in `getSupportedFeatures` method of `SalesforceIntegration` class.
There is not exists 'push_companies' settings, so i think that will never enter in that condition

**Comment by kuzmany** [comment]
@alfredoct96 I see in the code during the sync lead/contact object try also sync company related to lead/contact

https://github.com/mautic/mautic/blob/4.x/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php#L762

**Comment by alfredoct96** [comment]
@kuzmany  But this happens only if a new lead is created with a company.
If a new company  is created without leads it will never be synced to Salesforce because `push_companies` option doesn't exist and condition will fails. 
in_array('push_companies', $supportedFeatures) is always false

**Comment by kuzmany** [comment]
@alfredoct96 but it is what the PR does.  Do not run push companies on fetch command If push_companies is not in supportedFeatures, but still you are able to use method pushCompanies in your code

That means Salesforce for fetch command  try run pushCompanies even if we do not want it. This PR fixed it

**Comment by alfredoct96** [comment]
@kuzmany  But when is pushCompanies called if `push_companies` is always false?
That part of code seems unreachable.
Where `push_companies` is setted to true?

**Comment by alfredoct96** [comment]
Where `push_companies` is setted to true?

**Comment by kuzmany** [comment]
@alfredoct96 ah you're right. I need check the reported issue

**Pull request merged**
