### PR TITLE
5145 check curl is installed

### PR DESCRIPTION
**Pull request by Aerendir**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | No
| Automated tests included? | No
| Related user documentation PR URL | No
| Related developer documentation PR URL | No
| Issues addressed (#s or URLs) | #5145 
| BC breaks? | No
| Deprecations? | No

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR adds a check to ensure the cURL extension is loaded on the server as it is required by Mautic to work.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Disable the cURL extension on your server
2. Install Mautic: the installer doesn't alert you the extension isn't loaded
3. Complete the installation
4. Login: a 500 error appears

> Uh oh! I think I broke it. If I do it again, please report me to the system administrator! 

```
[Fri Jun 28 18:00:01.517917 2019] [php7:warn] [pid 7822] [client 93.151.244.14:62594] PHP Warning:  Use of undefined constant CURLOPT_FOLLOWLOCATION - assumed 'CURLOPT_FOLLOWLOCATION' (this will throw an Error in a future version of PHP) in /var/www/mautic/public_html/app/bundles/PluginBundle/Integration/AbstractIntegration.php on line 1023, referer: https://mautic/s/plugins
[Fri Jun 28 18:00:01.517943 2019] [php7:warn] [pid 7822] [client 93.151.244.14:62594] PHP Warning:  Use of undefined constant CURLOPT_REFERER - assumed 'CURLOPT_REFERER' (this will throw an Error in a future version of PHP) in /var/www/mautic/public_html/app/bundles/PluginBundle/Integration/AbstractIntegration.php on line 1024, referer: https://mautic/s/plugins
[Fri Jun 28 18:00:01.517972 2019] [php7:warn] [pid 7822] [client 93.151.244.14:62594] PHP Warning:  Use of undefined constant CURLOPT_USERAGENT - assumed 'CURLOPT_USERAGENT' (this will throw an Error in a future version of PHP) in /var/www/mautic/public_html/app/bundles/PluginBundle/Integration/AbstractIntegration.php on line 1025, referer: https://mautic/s/plugins
[Fri Jun 28 18:01:06.442964 2019] [php7:warn] [pid 7689] [client 93.151.244.14:62605] PHP Warning:  Use of undefined constant CURLOPT_HTTP_VERSION - assumed 'CURLOPT_HTTP_VERSION' (this will throw an Error in a future version of PHP) in /var/www/mautic/public_html/app/bundles/PluginBundle/Integration/AbstractIntegration.php on line 1020, referer: https://mautic/s/plugins
[Fri Jun 28 18:01:06.443029 2019] [php7:warn] [pid 7689] [client 93.151.244.14:62605] PHP Warning:  Use of undefined constant CURL_HTTP_VERSION_1_1 - assumed 'CURL_HTTP_VERSION_1_1' (this will throw an Error in a future version of PHP) in /var/www/mautic/public_html/app/bundles/PluginBundle/Integration/AbstractIntegration.php on line 1020, referer: https://mautic/s/plugins
[Fri Jun 28 18:01:06.443062 2019] [php7:warn] [pid 7689] [client 93.151.244.14:62605] PHP Warning:  Use of undefined constant CURLOPT_HEADER - assumed 'CURLOPT_HEADER' (this will throw an Error in a future version of PHP) in /var/www/mautic/public_html/app/bundles/PluginBundle/Integration/AbstractIntegration.php on line 1021, referer: https://mautic/s/plugins
[Fri Jun 28 18:01:06.443095 2019] [php7:warn] [pid 7689] [client 93.151.244.14:62605] PHP Warning:  Use of undefined constant CURLOPT_RETURNTRANSFER - assumed 'CURLOPT_RETURNTRANSFER' (this will throw an Error in a future version of PHP) in /var/www/mautic/public_html/app/bundles/PluginBundle/Integration/AbstractIntegration.php on line 1022, referer: https://mautic/s/plugins
[Fri Jun 28 18:01:06.443122 2019] [php7:warn] [pid 7689] [client 93.151.244.14:62605] PHP Warning:  Use of undefined constant CURLOPT_FOLLOWLOCATION - assumed 'CURLOPT_FOLLOWLOCATION' (this will throw an Error in a future version of PHP) in /var/www/mautic/public_html/app/bundles/PluginBundle/Integration/AbstractIntegration.php on line 1023, referer: https://mautic/s/plugins
[Fri Jun 28 18:01:06.443149 2019] [php7:warn] [pid 7689] [client 93.151.244.14:62605] PHP Warning:  Use of undefined constant CURLOPT_REFERER - assumed 'CURLOPT_REFERER' (this will throw an Error in a future version of PHP) in /var/www/mautic/public_html/app/bundles/PluginBundle/Integration/AbstractIntegration.php on line 1024, referer: https://mautic/s/plugins
[Fri Jun 28 18:01:06.443177 2019] [php7:warn] [pid 7689] [client 93.151.244.14:62605] PHP Warning:  Use of undefined constant CURLOPT_USERAGENT - assumed 'CURLOPT_USERAGENT' (this will throw an Error in a future version of PHP) in /var/www/mautic/public_html/app/bundles/PluginBundle/Integration/AbstractIntegration.php on line 1025, referer: https://mautic/s/plugins
```

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)

Not so involved in the project to know how to use this

NOTE: This PR is based on `master` branch. Please, let me know if this is wrong and if I have to use a different branch.

### CODE REVIEW

**Comment by Aerendir** [comment]
@escopecz , if you guide me I can add also the tests, but I cannot find them: they are not in the bundle nor in the `tests` folder...

**Comment by Aerendir** [comment]
This PR was closed as it targeted `master` branch instead of the `staging` one.

Here there si the correct PR: https://github.com/mautic/mautic/pull/7657

**Comment by escopecz** [comment]
Thanks @Aerendir! The tests are not done for some old code where the objective was to release the first version rather the stability which tests help with. Also, I'm not quite sure how you plan to mock response of the native PHP function `function_exists`. You'd have to create a new helper class that would encapsulate that native function.

**Comment by Aerendir** [comment]
@escopecz , if other checks are tested, then I will test this PR, too. But if they are not, I will not test this PR...

I'm exploring the Mautic's world since 6 or 7 days, so I'm not so experienced in flows, practices, etc...

**Comment by escopecz** [comment]
It's not tested and that code is not testable anyway in my opinion. Thanks for your work! Definitely reach out if you have any questions.

**Pull request closed without merging**
