### PR TITLE
TPROD-318 - Converting PHP templates for the IntegrationsBundle to Twig

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://mautic.atlassian.net/browse/TPROD-318

#### Description:

Converts PHP templates for the IntegrationsBundle to Twig.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. As there is no publicly available plugin to test this with (yet) then I guess we'll have to trust myself and our CI checks that it will work 🤷  There is quite great chance that this code have a bug or 2 in it as other PRs that refactor templates. However, we'll have to take the risk to move forward and the companies that use this bundle will have to fix the potential bugs as they start converting their integrations to M5. 
3. Please code-review.

### CODE REVIEW

**Comment by RCheesley** [comment]
We can now use the Pipedrive plugin #justsaying : https://github.com/Webmecanik/mautic-pipedrive-bundle

**Comment by escopecz** [comment]
@RCheesley good news!

I tried `bin/console mautic:marketplace:install webmecanik/mautic-pipedrive-bundle` but it failed with `Package 'webmecanik/mautic-pipedrive-bundle' not found in allowlist.`

So I used `composer require webmecanik/mautic-pipedrive-bundle` but `bin/console cache:clear` failed with `Cannot autowire service "MauticPlugin\PipedriveBundle\Connection\Credentials": argument "$tokenUrl" of method "__construct()" is type-hinted "string", you should configure its value explicitly.` which is an autowiring issue. So the plugin will have to be modified a little to support M5.

**Comment by RCheesley** [comment]
OK - yeah it is not in the allowlist yet - we haven't had the application I think, but it's in progress!

@kuzmany @npracht FYI re autowiring!

**Comment by kuzmany** [comment]
It's not ready for M5 of course.  Probably we need just add some exclude to Config/services.php

**Review by mabumusa1 — DISMISSED** [review]
I did a code review, the changes look logical. many PHP file turned into twig, controllers had changes and config. I did not see an obvious bug

**Comment by escopecz** [comment]
I added more tests to cover the new Twig extensions so we at least have a proof those work. Merging this as this cannot be tested at the moment and yet it is blocking the Symfony upgrade.

**Pull request merged**
