### PR TITLE
Fix SQL issue when creating a backup during install

### LINKED ISSUE #8457: Function "Backup existing tables" in installation process throws error
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When trying to run the Mautic installer in a database that already contains a Mautic installation, the following error occurs:

`An error occurred while attempting to install the data: An exception occurred while executing 'CREATE INDEX bak_page_hit_url ON bak_page_hits (url)': SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'url' used in key specification without a key length`

image

I could reproduce this error after a Mautic user reported in on the forums: https://forum.mautic.org/t/server-500-error-after-2-16-0-update-attempt/12827/9

| Q   | A
| --- | ---
| Mautic version | 2.16.0
| PHP version | 7.2
| Browser | Chrome 80

### Steps to reproduce
(not sure if step 1 and 2 are 100% necessary to reproduce)
1. Create a Mautic installation 
2. Remove the `app/config/local.php` file
3. Open your Mautic URL, the installer will open. Try following the steps, and at step 1, set "Backup existing tables" to "Yes"
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/88813891-function-backup-existing-tables-in-installation-process-throws-error?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [Y]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #8457 

#### Description:

The backup step didn't include the options when creating the backed up index, which is necessary for e.g. specifying the length of a text or blob. This PR ensures all the options are passed along.

#### Steps to test this PR:

1. install a vanilla mautic a first time
2. remove the `config/local.php` file
3. install it again, and ensure the backup tables option is on
4. an error is thrown about the `bak_page_hits` index
5. apply the patch
2. remove the `config/local.php` file
3. install it again, and ensure the backup tables option is on
4. no error is thrown, and the index in the `bak_page_hits` table exists

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10747"></a>

### CODE REVIEW

**Review by escopecz — CHANGES_REQUESTED** [review]
The code change makes sense. Thanks!

We can merge only code that has PHPUNIT tests confirming it works as intended. I was thinking how to test this one as it would break other functional tests when the database tables would be backed up. The way how it could work:

1. Create a table with special prefix and an index that has some options.
2. Create new SchemaHelper object with $dbParams that would allow it to connect to the test database but used the special table prefix.
3. Execute the createDatabase() method that would make the backup of that new table
4. Assert that the index was correctly backed up.

Do you think it could work? Let me know if you'll need some help.

**Comment by mollux** [comment]
@escopecz I added a test that reproduces the issue. 
The test fails without the patch, and success when patched.

I had to take another approach than you suggested.
the `SchemaHelper:installSchema()` method is not ideal to test, as e.g. the `SchemaTool` is instantiated inside, and not via DI, which makes is difficult to mock. 

IMO this test it's also more in line with the issue, as it will check the broken functionality, and no other side effects.

**Comment by mollux** [comment]
@RCheesley 

just to understand this correctly: why was the base branch changed from `4.1` to `4.x`, and not `4.2`?
It's a bugfix, not a feature :)

Or are the `4.1` `4.2`, ... branches only meant for bugs introduced in that version? (but how would anybody possibly know without tracing back commits)

**Comment by RCheesley** [comment]
It is explained in the contributors guide here:

a = current major release b = current minor release c = future major release

a.x for any features and enhancements (e.g. 4.x)
a.b for any bug fixes (e.g. 4.0, 4.1, 4.2)
c.x for any features, enhancements or bug fixes with backward compatibility breaking changes (e.g. 5.x)

So bug fixes will generally go into the a.b branch (e.g. 4.2). However when the next release is a feature release, we do that from the 4.x branch, so we then need PRs that are going to be included in that release, to be based on that for merging into that branch.

The 4.2 branch is only created from the 4.x branch, once we make the 4.2.0 release. It (should not) exist until that point.

**Comment by mollux** [comment]
@RCheesley 

aha, my confusion comes from the template 
`Bug fix? (use the a.b branch)` 

But it makes sense with the branching logic used in Mautic to use 4.x now

I'll rebase this to 4.x

**Comment by RCheesley** [comment]
Yeah maybe we need to update the template to say 'but if the next release is a minor release, please make all PRs against 4.x'?

I didn't want to over complicate things but that might be some useful information!

**Comment by mollux** [comment]
@escopecz The PR still mentions a `change requested`, but I don't see it in de UI.
Can you point me in the direction of that needed change?

**Comment by RCheesley** [comment]
@mollux in order to merge, the person requesting changes has to re-approve the PR. The changes were requested [here](https://github.com/mautic/mautic/pull/10747#pullrequestreview-855702520), so we need to have John review. He's on vacation this week, so should be done early next week all being well.

**Review by escopecz — APPROVED** [review]
Looks good to me. Thanks! 👍

**Review by kuzmany — APPROVED** [review]
Looks good.
Unit tests included and make sense 

:)

**Pull request merged**
