### PR TITLE
Add Redis to DDEV

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Add Redis for DDEV - your local enviroment based on 

- https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/redis
- https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/redis-commander

#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2. For new installation run `ddev start` 
3. For already exist ddev installation run `ddev restart`
4. After build you should see Redis Commander on https://mautic.ddev.site:1359/
image

5. Your redis instance is available inside the containers at `ddev-mautic-redis:6379`

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10538"></a>

### CODE REVIEW

**Review by RCheesley — DISMISSED** [review]
Thanks for this PR @kuzmany - worked great for me with DDEV restart and I'm sure it will be super helpful for folks using Redis!

🚀

**Comment by kuzmany** [comment]
@dennisameling can you make review of this?

**Comment by RCheesley** [comment]
Could you please rebase this against the 4.x branch? Thanks!

**Comment by biozshock** [comment]
After applying the patch redis has started with ddev.

**Comment by kuzmany** [comment]
@biozshock thanks for review. Can you use for next PRs review tool in the tab? 

image

**Review by biozshock — APPROVED** [review]

**Comment by RCheesley** [comment]
@all-contributors please add @biozshock for Review

**Pull request merged**
