### PR TITLE
This fixes various issues with the API

### PR DESCRIPTION
**Pull request by alanhartless**

### CODE REVIEW

**Comment by escopecz** [comment]
I pulled this PR and tested it with api-library/apitester and got this error:

```
{
"error":"Unable to find controller "MauticApiBundle:OAuth1\Authorize" - class "Mautic\ApiBundle\Controller\OAuth1\AuthorizeController" does not exist."
}
```
Here is what I did:
1. Base URL: URL of my Mautic instance.
2. API endpoint: leads
3. Click Submit
4. At OAuth1.0a tab, I inserted consumer key and secret from the Mautic instance.
5. Click Authorize

Am I doing something wrong?

**Comment by alanhartless** [comment]
Are you still getting this error?

**Comment by alanhartless** [comment]
Found a case mismatch.  Try it with that last commit and see if you can get past the error.

**Comment by escopecz** [comment]
The problem is resolved.

**Pull request merged**
