### PR TITLE
Fix A new entity was found through the relationship 'Mautic\LeadBundle\Entity\Company#owner

### PR DESCRIPTION
**Pull request by fedys**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             |no
| Automated tests included?              | yes
| Related user documentation PR URL      | 
| Related developer documentation PR URL |
| Issue(s) addressed                     | 

#### Description:
This PR fixes a Doctrine error `A new entity was found through the relationship 'Mautic\LeadBundle\Entity\Company#owner' that was not configured to cascade persist operations for entity: Mautic\UserBundle\Entity\User`. This error occurs when there is an integration plugin that syncs company owner field. As a company is being detached on https://github.com/mautic/mautic/blob/d6ac13284cfc6c9310ce8e918de651226cbe20b6/app/bundles/IntegrationsBundle/Sync/SyncDataExchange/Internal/ObjectHelper/CompanyObjectHelper.php#L67 and there is a cascade detach mapping on https://github.com/mautic/mautic/blob/65a7b49404982d90c2dd4a84636c9c509c2dfd42/app/bundles/LeadBundle/Entity/Company.php#L118 we got the error `A new entity was found through the relationship ...` when syncing another Company entity.

### CODE REVIEW

**Review by kuzmany — DISMISSED** [review]
Yes, we noticed this issue
And this PR fixed it 👍 
Thank you.

Approve it

**Comment by kuzmany** [comment]
@fedys can you rebase it based on 3.3 and then check unit tests?

**Comment by fedys** [comment]
@kuzmany rebased on 3.3. Tests are passing.

**Comment by RCheesley** [comment]
This one will need a rebase / conflicts addressed please!

**Comment by fedys** [comment]
@RCheesley I rebased the PR and solved conflicts.

**Review by kuzmany — APPROVED** [review]
Looks good 👍

**Review by npracht — APPROVED** [review]
This is used in our production environment for about 7 months. We use it to fix the same issue related to a custom CRM integration plugin sync company owner.

Good catch 👍🏽

**Pull request merged**
