### PR TITLE
Ensure default frequency rules are taken into account correclty

### LINKED ISSUE #10275: Segment-Mails are forced into email queue, even if queueing is not set up
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Bug occurred while testing out Segment-Emailing. 

Once I am asked to send out the Segment-Mail, I have to accept that the Mail will be queued. I can only accept that or cancel sending entirely. Issue is, I have not set up my Mautic to use email-queue, instead I am using the "send immediatley" option, resulting in the forced queued Segment-Email never being send out and stuck in queue. 

Screenshot v4000rc 1

Even worse is, I cannot access email-queue per CLI and force them to send out this way. I am getting an error stating, that email-queue is not set up.

Screenshot at Jul 20 09-11-50

| Q   | A
| --- | ---
| Mautic version | v4.0.0rc
| PHP version | 7.4
| Browser | Chrome

### Steps to reproduce
1. Go to Configuration - Email Settings
2. Set Email-Send method to "Send immediately"
2. Create a test-segment
2. Push a test-contact into that segment
3. Create a Segment-Mail
4. Send the Segment-Mail to the test-segment 
5. See that you have to Queue the Mail 
6. Mail gets stuck in a not-setup Queue

### Log errors
No errors are logged. 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### LINKED ISSUE #10416: "Default Frequency Rule" seems to be activated by default
### Mautic Version

4.0.0

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Chrome

### What happened?

While testing email-queue today I encountered an issue where only the first email was sent out to a Segment, the next Emails that I wanted to send out to the segment got into the queue but were never sent out and also werent to be found in the Spool folder.

This seems to be related to the "Default Frequency Rule", which is set to the following on a fresh 4.0.0 install:

image

Removing the "0" from the "Do not send me more than", thus setting it to blank, doesnt solve the Issue, I had to manually raise the "Do not contact me more than" ammount, which resulted in me being able to send out emails again.

It seems to be an Issue that the Default Frequency Rule does apply even though it has a "0", kind of indicating that the rule wont apply unless changed.

### How can we reproduce this issue?

Step 1: Go to the Mautic Configuration -> Email Settings
Step 2: See if the Default Frequency Rule is set to 0 / days, which is currently the default for a fresh install
Step 3: Activate email-queueing
Step 4: Create a test segment with a test contact in it
Step 5: Create a segment mail and send it to the test-segment
Step 6: The email should be sent out correctly
Step 7: Create another test-email and sent it to the test-segment again
Step 8: The Email should be queued, but won´t be send out and is not found in the spool-folder as the default frequency rule blocks it

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### LINKED ISSUE #10637: Mautic 4 - Twilio, can't send more than 1 text message, it breaks after the first sms
### Mautic Version

4.0.0

### PHP version

7.4.24

### What browsers are you seeing the problem on?

Chrome

### What happened?

Activated the Twillio plugin.
Managed to send a test message using the Twilio registered number. 
When I send the second text message then it breaks. 

In the contact, event log is says:
Last execution error: Scheduled

I also tested on two different servers, one version 4.0.1, and one server 4.0.2.
Then I tried a third server, with Mautic 3.3.3 and it works prefect on Mautic 3.

### How can we reproduce this issue?

Step 1:  Activate Twilio sms plugin
Step 2: Create a campaign
Step 3: Create a action of sending text message and select a segment group that has phone numbers 
Step 4: Create text message with "New segment text message"
Step 5: Save and activate the campaign

It will send the first text message.

Repeat Step 2-5, this time it will not send a text message. 
Instead it will give an error in the log and in the contact that was supposed to receive the text message, it says in the event log:  "Last execution error: Scheduled".

You can send to multiple contacts, but only once to each of them.

### Relevant log output

```shell
mautic.NOTICE: PHP Notice - Trying to access array offset on value of type null - in file /var/www/html/m4/app/bundles/SmsBundle/Form/Type/SmsSendType.php - at line 84 {"builder":"[object] (Symfony\\Component\\Form\\FormBuilder: {})","options":{"block_name":null,"disabled":false,"label_format":null,"label_translation_parameters":[],"attr_translation_parameters":[],"translation_domain":null,"auto_initialize":true,"trim":true,"required":true,"property_path":null,"mapped":true,"by_reference":true,"inherit_data":false,"compound":true,"method":"POST","action":"","post_max_size_message":"The uploaded file was too large. Please try to upload a smaller file.","allow_file_upload":false,"help_translation_parameters":[],"error_mapping":[],"invalid_message":"This value is not valid.","invalid_message_parameters":[],"allow_extra_fields":false,"extra_fields_message":"This form should not contain extra fields.","csrf_protection":true,"csrf_field_name":"_token","csrf_message":"The CSRF token is invalid. Please try to resubmit the form.","csrf_token_manager":"[object] (Symfony\\Component\\Security\\Csrf\\CsrfTokenManager: {})","csrf_token_id":null,"block_prefix":null,"label":false,"row_attr":[],"attr":[],"data":null,"data_class":null,"empty_data":"[object] (Closure: {})","error_bubbling":true,"label_attr":[],"upload_max_size_message":"[object] (Closure: {})","help":null,"help_attr":[],"help_html":false,"validation_groups":null,"constraints":[],"update_select":"campaignevent_properties_sms"},"windowUrl":"/s/sms/new?contentOnly=1&updateSelect=campaignevent_properties_sms"} []
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #10275 Fixes #10416 Fixes #10637 

#### Description:

The `DefaultFrequencyRuleViolations` are checked if the `defaultFrequencyTime` is present, regardless of the value of `defaultFrequencyNumber` due to an error in the conditional (2 times the same variable is checked)

This results in the issue described in [ #10275](https://github.com/mautic/mautic/issues/10275#issuecomment-903272962) (you can only send 1 mail to a contact, all subsequent attempts are queued), and explains why the mitigation in #10416 doesn't work

> Removing the "0" from the "Do not send me more than", thus setting it to blank, doesnt solve the Issue, I had to manually raise the "Do not contact me more than" ammount, which resulted in me being able to send out emails again.

#### Steps to test this PR:

see the steps in [ #10275](https://github.com/mautic/mautic/issues/10275#issuecomment-903272962) and #10416

#### Extra remarks
The question / suggestion in [#10416](https://github.com/mautic/mautic/issues/10416#issuecomment-915981168) is still valid, as this functionality after this patch works as `0` is interpreted as FALSE.
But what is we want to queue everything for all users that have no custom frequency rule?

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10753"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
@mollux I think this might also relate to https://github.com/mautic/mautic/issues/10637 - can you test on the SMS channel and see if it does apply there too?

**Review by jos0405 — APPROVED** [review]
Checked and it works.
Previously queued emails if frequency rule is 0 (default) were Queued, now not anymore.
image

**Comment by mollux** [comment]
@RCheesley this would possible also fix #10637 indeed
I couldn't test this completely (I have no SMS provider configured), but I followed the codeflow, and it also hits the `DefaultFrequencyRuleViolations` the same way as mail.

I pinged the the 2 other people involved in that issue if they could confirm this fix works for them too.

**Comment by RCheesley** [comment]
Great, thanks for testing @jos0405 and for checking out if it will impact the SMS issue as well @mollux - we just need a code review now and then we'll be good to get this merged and released in 4.1.2.

@kuzmany @escopecz could you take a look at the code please? Thanks!

**Review by kuzmany — APPROVED** [review]
Code looks good 👍

**Comment by RCheesley** [comment]
@all-contributors please add @mollux for code

**Pull request merged**
