### PR TITLE
Feature GoToWebinar Add token to include the webinar link for the registrant to join

### PR DESCRIPTION
**Pull request by virlatinus**
| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/170
| Related developer documentation PR URL | N/A
| Issues addressed (#s or URLs) | N/A
| BC breaks? | N/A
| Deprecations? | N/A

#### Description:
This PR adds an extra feature to the Citrix GotoWebinar plugin: a token that can be included in a segment email and replaced with the URL to join a live webinar.

#### Steps to test this PR:
1. Follow the steps in the [Citrix Plugin documentation](https://mautic.org/docs/en/plugins/citrix.html) to enable the GotoWebinar plugin

2. Create a webinar in the [GotoWebinar website](https://www.gotomeeting.com/webinar)

3. Create a new contact and use the emaill address to register for the new webinar

4. Run the Citrix Sync command: `php app/console mautic:citrix:sync` so that the webinar information is retrieved to the database.

5. Create a segment with a "Webinar (registered)" filter. (Note that this is mandatory, and it will be validated when trying to save the email with the token in the body)
image

6. Add the contact to the segment manually or by running `php app/console mautic:segments:update`

7. Create a new segment email and assign the previously created segment.
image

8. Open the email builder and insert the GotoWebinar button token:
image

9. Send the email to the segment contacts.
image

10. The email in the new contact inbox should include a button to join the webinar with the appropiate URL for the contact.
image

11. The button can be styled by overriding the `citrix-start-button` CSS class. ie
```
.citrix-start-button {
  background: green !important;
}
```

### CODE REVIEW

**Comment by matishaladiwala** [comment]
Works for me - both button and link.

**Comment by escopecz** [comment]
I was about to create a segment with my webinar registrants, but my webinar was not in the select, so I chose "any webinar" option just to save the segment and try to refresh. But when I hit save I got this error:
```
mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\InvalidArgumentException: "The value of type "array" cannot be converted to a valid array key." at vendor/symfony/form/ChoiceList/ArrayKeyChoiceList.php line 75 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\InvalidArgumentException(code: 0): The value of type \"array\" cannot be converted to a valid array key. at /var/www/html/vendor/symfony/form/ChoiceList/ArrayKeyChoiceList.php:75)"} []
```

**Comment by virlatinus** [comment]
@escopecz are you in the current staging? I just tested and it let me create a segment with filter `registered to Any Webinar`

**Comment by YannickBiet** [comment]
Hi Werner, what about the emails sent as result of a form submit ? You can in deed choose and register to the webinar using the form actions and then wanted to send directly an email to the contact containg the Button or Webinar URL ?

Seems this scenario is not supported in your PR ? 
(see https://github.com/mautic/mautic/issues/3953)

**Comment by YannickBiet** [comment]
I have rewrite a full test with Form / Segments / and a new segment email linked to the segment.

The link sent is not a button and does not contain the link.

**Pull request merged**
