### PR TITLE
add language support to form error messages

### LINKED ISSUE #4658: Translate Please wait … message when submitting a form
| Feature request? | 

## Description:
When submitting a Mautic form, the text in the buttons says ´Please wait …´. We use Mautic for our Dutch clients and would like to see that the text in the button is translated is the language the Mautic instance is set up. So a Dutch message in Dutch language, a German in German language and so on...

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/48229346-translate-please-wait-message-when-submitting-a-form?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by enguerr**
Q | A
-- | --
Bug fix? | No
New feature? | Yes
Automated tests included? | No
Issues addressed (#s or URLs) |  resolves #4658
BC breaks? |  
Deprecations? |  

## Description:
Add Language support for form creation
To enable this path, please update the db schema. I've added some columns like title, noindex and lang on the form table.

## Steps to test this PR:
1. Load up this PR
2. Create a form
3. Select the desired language in the new select at the bottom right
4. All Error message , confirmations and loading message are in the selected language (not the owner user language)

## List deprecations along with the new alternative:
None

## List backwards compatibility breaks:
None

### CODE REVIEW

**Comment by RCheesley** [comment]
@enguerr thanks for submitting the PR! Can you please rebase against staging?

**Comment by enguerr** [comment]
@RCheesley Editing the pull request compare base is enough ?
(sry i'm not very confortable with pull requets rebasing...)

**Comment by npracht** [comment]
Hello @enguerr this is a very nice improvement.
Nevertheless, I'm wondering from a product perspective if it wouldn't be more efficient to display the message in the language of the visitor (based on browser language). I think this is feasible technically and instead of forcing a language, it would be more adapted.

**Review by npracht — CHANGES_REQUESTED** [review]
I just tested anyway, selecting french but everything is still in english (error or waiting message).

**Comment by RCheesley** [comment]
Given the findings from @npracht let's bump this to 3.2 so that we have more time to test in detail.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by dennisameling** [comment]
Hi @enguerr! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since this PR has conflicts now, could you please do a `git merge upstream/features` locally to resolve the conflicts? Thanks in advance!

**Comment by npracht** [comment]
I close it as far as it seems this is not supported anymore. Feel free to comment if someone want to re-open/carry it.

**Pull request closed without merging**
