### PR TITLE
Added Curaçao and Isle of Man

### PR DESCRIPTION
**Pull request by Dylan-86**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10498"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for making the PR @Dylan-86, please could you ensure that you provide a clear description so that people who would like to test this PR understand what to look for currently, and how to check the PR does what it says?

Many thanks!

@cla-bot check

**Comment by Dylan-86** [comment]
Simple test: right now Curaçao and Isle of Man are missing.

Create a new contact and select Curaçao as a country
Create a new contact and select Isle of Man as a country

**Review by escopecz — APPROVED** [review]
As I suck at geography I had to confirm:

> Curaçao is a Lesser Antilles island country in the southern Caribbean Sea and the Dutch Caribbean region, about 65 km (40 mi) north of the Venezuelan coast.

https://en.wikipedia.org/wiki/Cura%C3%A7ao

> The Isle of Man also known as Mann is an island and self-governing British Crown Dependency in the Irish Sea between Great Britain and Northern Ireland.

https://en.wikipedia.org/wiki/Isle_of_Man

I think those 2 options won't hurt to add.

**Review by jos0405 — APPROVED** [review]
Completing the coverage of Terra one country at the time.

**Pull request merged**
