### PR TITLE
[type-declarations] Add ctor based property types in - Lead bundles

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Good to go :+1:

**Comment by TomasVotruba** [comment]
Let's wait for other PRs to get merge first, as this will be a bigger rebase.

**Comment by TomasVotruba** [comment]
Ready to go :heavy_check_mark:

**Review by escopecz — APPROVED** [review]
I don't see any issues with these changes. 👍 

@TomasVotruba I started to think that since Mautic 5 supports only PHP 8+, we could switch directly to constructor property promotion instead of defining properties on the class level, right? Isn't this a change that is already outdated?

**Comment by TomasVotruba** [comment]
@escopecz PHP 8.0 is great target :+1:  

I plan to add property promotion PRs after those typed property PRs are merged. It's more safe to do it step by step :pray:

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Pull request merged**
