### PR TITLE
Anniversary segment filter

### PR DESCRIPTION
**Pull request by MaxWebmecanik**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | ✓
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

This PR adds the ability to segment contacts whose birthday is the current date through a segment filter.

image

#### Steps to test this PR:
1. Create a date custom field to hold the contact's birthday
2. Create a contact whose birthday is the current date but not the current year
3. Create a segment with a filter on that field with the _equals_ operator and _birthday_ as the value (or whatever the value of the translation key `mautic.lead.list.birthday` is in your locale)
4. Refresh the segments
5. The contact should now be in the segment

### CODE REVIEW

**Comment by escopecz** [comment]
Please fix the CS that failed the CI tests: https://travis-ci.org/mautic/mautic/jobs/249772331#L1149

**Comment by MaxWebmecanik** [comment]
@escopecz Here you go!

**Comment by escopecz** [comment]
I'm just testing https://github.com/mautic/mautic/pull/4566 and the campaign date filters are working with term "Anniversary" (`mautic.campaign.event.timed.choice.anniversary`) which does the same thing. It's in the code already, not a new feature. Would you mind changing "birthday" to "anniversary" to keep it consistent?

**Comment by MaxWebmecanik** [comment]
@escopecz I just changed it to anniversary!
I left the birthday case because we already use it today.
Is that ok? We'll still document for anniversary :)

**Comment by mqueme** [comment]
This didn;t work for me. I have a contacts with today's birthday but nothing gets added. I've used Anniversary, anniversary and birthday but nothing worked.

**Comment by npracht** [comment]
@mqueme you're instance is in English ?

**Comment by virlatinus** [comment]
Out of the box it didn't work for me.

It only worked when I changed line 769 in LeadListRepository.php to 
```
$details['filter']   = '%'.date('-m-d');
```
That way, when rebuilding the segment the query worked:
```
# app/console m:s:u -i 168 -e dev -vvv

SELECT count(l.id) as lead_count, max(l.id) as max_id 
    FROM leads l LEFT JOIN lead_lists_leads ll ON (ll.leadlist_id = 168) 
          AND (ll.lead_id = l.id) AND (ll.date_added <= '2017-08-22 14:39:17') 
    WHERE (l.birthday LIKE '%-08-22') AND (ll.lead_id IS NULL)
```

**Comment by escopecz** [comment]
I applied @virlatinus's suggestion. Ready to retest

**Comment by mqueme** [comment]
with these changes it works, but should it remove contacts who's birthdays don't apply anymore?

**Comment by escopecz** [comment]
It should and it does for me. I just confirmed with a test.

**Comment by luizeof** [comment]
This feature will automatically create a birthday date field for contact on new installation?

Today we have an birthday custom field on Mautic ... this will cause some conflict?


Thanks for this new feature!

**Comment by npracht** [comment]
Hello @luizeof it is more about a value that you have to apply to any date formatted field (native or custom).
It does not create a specific field.

**Comment by luizeof** [comment]
thanks for your response @npracht !

**Pull request merged**
