### PR TITLE
Retry payload to Momentum a few times before giving up if it returns a 500 error

### PR DESCRIPTION
**Pull request by alanhartless**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

**Contributed by the engineering team of Mautic, Inc.**

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

Because Momentum is a self hosted solution, there's a chance servers may have communication issues. This PR simply retries the send if Momentum returns a 500 error up to 3 times.

[//]: # ( As applicable: )
#### Steps to test this PR:
1. Run the new unit tests2.

### CODE REVIEW

**Comment by mleffler** [comment]
This has been code reviewed and has had one test pass.

**Comment by escopecz** [comment]
@alanhartless can you please fix the [CS issue](https://travis-ci.org/mautic/mautic/jobs/411390060#L707)?

**Comment by alanhartless** [comment]
@escopecz done

**Comment by escopecz** [comment]
I guess we are the only one who can test this. As it's running on our production servers for some time and it's covered with unit tests, I'm merging.

**Pull request merged**
