### PR TITLE
Fix 10455: Allows to reopen the code edit modal after grapesjs builder has been closed

### LINKED ISSUE #10455: MJML email builder - "Edit Code" function is broken
### Mautic Version

4.0.0

### PHP version

7.4.23

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

This is kind of related to #10398 & #10396.

I tried out the fix described in the issues linked above, removing the set ID when changing a picture by accessing the "Edit Code" function to manually remove the ID I encountered an Issue that I was not able to open the builder after closing and saving the email.

It seems that once you manually made any edit using the "edit code" option, save the email and re-open it, you cannot access the "edit code" option anymore.

### How can we reproduce this issue?

1. Create a new email
2. Choose a template 
3. Open the Builder 
4. Open the "Edit Code" option to manually edit the MJML
5. Make any minor change to the MJML
6. Save your edit by clicking on "edit"
7. Close the email builder
8. Save and Close you Mail
9. Re-open the mail
10. Go to the builder
11. Try to open the "edit Code"
12. It won't open

### Relevant log output

```shell
No Logs
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by adiux**
closes #10455

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | yes
| Deprecations?                          |  no
| BC breaks? (use the c.x branch)        | no
| Automated tests included?              | N/A
| Issue(s) addressed                     | Fixes #10455

#### Description:

This fixes an issue where the code editor modal did not open **again** when the grapesjs builder was closed.

#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2. See steps in the [issue](https://github.com/mautic/mautic/issues/10455)

This PR is the same as https://github.com/mautic/mautic/pull/10564 but based on 4.1 branch

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10707"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
@adiux I'm able to replicate and with your change I'm able to get to the "Edit Code" modal window for the second time. However, the "Save" button is not working. Do you think you could fix that issue as well?

**Review by bradycargle — DISMISSED** [review]
Tested and worked on my local environment. Attached a video showing my test

https://user-images.githubusercontent.com/79949869/149635052-89d3522b-6bc0-42ad-a6e5-e777d70120e7.mp4

**Review by jos0405 — DISMISSED** [review]
Looking good. Approved based on Brady’s video.

**Comment by adiux** [comment]
@escopecz I looked at the save button in the modal. It was working for me. Let me know if you still have the issue.

**Comment by escopecz** [comment]
Ok, the video was very helpful. I retested and now I can see what let me think that the Save button does not work. 

1. When you open the builder for the first time, edit the HTML code and click on the Save button - it will save and **close the modal window**.
2. Close the builder (do not reload the page). Open the builder again, edit the HTML and click on the Save button - it will save but the **modal window will stay open**.

Is that something that you think could be fixed in this PR? Or if you say it is not related to this fix then we can merge this PR and let somebody else to fix the UX issue.

**Comment by adiux** [comment]
@escopecz Thanks for that. I looked into it and found out that the problem is a bit bigger. The code in the modal is also not updated. Im working on a fix. But I think we should merge this first so we can look at it separately.

**Comment by escopecz** [comment]
@adiux do you think you'll be able to fix the commit history? There are commits in this PR that shouldn't be here.

**Comment by adiux** [comment]
@escopecz do I need to rebase it?

**Comment by adiux** [comment]
@escopecz Since the 4.1 release is done I opened a new PR for the 4.x branch: https://github.com/mautic/mautic/pull/10842

**Pull request closed without merging**
