### PR TITLE
Focus Custom CSS

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Y
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR added custom CSS to focus integration

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create modal window with custom style `.mf-modal { border: 10px solid #5D0E4E }`
3. You should see something like this

image

4. Test also with inline script on your page

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/8841"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
Close & open for Travis

**Comment by RCheesley** [comment]
@kuzmany a conflict to resolve here

**Comment by RCheesley** [comment]
@kuzmany failed Travis tests here - maybe a quick fix? I know a lot of folk are needing custom CSS for their focus items so might be a good one to try to get implemented. Otherwise we have to bump to 3.2 in November.

**Comment by RCheesley** [comment]
Looks like we need to increase test coverage a bit for this to not change or improve coverage @kuzmany ... sorry about that!

**Comment by kuzmany** [comment]
I don't see any logic to make unit tests.

**Comment by RCheesley** [comment]
@cla-bot check

**Review by npracht — DISMISSED** [review]
🚀 this works well. I can see the custom CSS displayed in the webpage where the focus is inserted.

**Review by luguenth — DISMISSED** [review]
Tested it and looks alright to me. Nice addition :)

**Comment by RCheesley** [comment]
PHPSTAN issue to fix here @kuzmany before we can merge.

cc @escopecz

**Pull request merged**
