### PR TITLE
Add translations for new blocks

### PR DESCRIPTION
**Pull request by volha-pivavarchyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [no ]
| New feature/enhancement? (use the a.x branch)      | [yes]
| Deprecations?                          | [no ]
| BC breaks? (use the c.x branch)        | [no]
| Automated tests included?              | [no] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR adds translations for new blocks in the grapesjs builder.
Related to the PR [#28](https://github.com/mautic/grapesjs-preset-mautic/pull/28)

#### Steps to test this PR:
This PR can be tested after merging the PR [#28](https://github.com/mautic/grapesjs-preset-mautic/pull/28)

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create new mjml email or select an existing one
3. Open the grapesjs builder
4. Block titles here

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11006"></a>

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
👍

**Comment by kuzmany** [comment]
Translations of core plugins should be done by transifex https://www.transifex.com/mautic/mautic/grapesjsbuilderbundle-javascript/

**Comment by jos0405** [comment]
@escopecz can you plz reply to @kuzmany 's comment above? Is this good to go, or should be changed?

**Comment by escopecz** [comment]
Yes, we should use Transifex for translations. However, the translations are already present in the current production release. This is a bug fix for those translations so I'd create a new ticket to move them to Transifex rather than blocking this bug fix.

**Comment by escopecz** [comment]
@volha-pivavarchyk please rebase on 4.4

**Comment by escopecz** [comment]
Ha, no need to rebase. Changing the target branch did not add any commits. So this is good to go.

**Review by jos0405 — APPROVED** [review]
Works as expected!

**Review by escopecz — APPROVED** [review]

**Pull request merged**
