### PR TITLE
Fix invalid form submit

### PR DESCRIPTION
**Pull request by LAN-Laurene**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? |  X
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description: 
Submitting a form without filling mandatory fields did not show error messages properly. This PR fixes that. 

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create Form with at least one mandatory field
2. Preview form
3. Submit form without filling any field
4. Notice the error message doesn't display but the url changes

#### Steps to test this PR:
1.  Apply PR
2.  Submit the form again without filling any field
3. Notice the error message should display properly and the url doesn't change.

### CODE REVIEW

**Comment by escopecz** [comment]
I'm not able to replicate the issue. If I create a form and then visit it in its public page (`http://mymautic.com/form/ID'), the require field validation is not triggered by a HTTP request as the description suggests, but by a JS validation. I tried to test also when the form is embedded via JS, but it behaves the same way. How do you "preview the form"?

**Comment by npracht** [comment]
@escopecz 
- https://yourmautic.com/s/forms/preview/ID
- or integrated in a mautic landing page

We reproduced on those 2 ways. @LAN-Laurene is gonna give you extra screenshots

**Comment by LAN-Laurene** [comment]
# Before patch

# After patch

**Comment by escopecz** [comment]
Nope, It shows the required message on the form preview page too as well as embedded into a landing page. Without this PR being applied. Strange. I'll test what happens if I apply this PR.

**Comment by escopecz** [comment]
It works the same when I apply this PR. So I guess we can approve it if it fixes the issue for somebody. I checked what the updated code does, it will use absolute URL instead of relative URL. I don't see any harm in doing that.

**Comment by npracht** [comment]
@escopecz we noticed that this PR generates a new bug - the form button stays on "waiting" even if it works.
@LAN-Laurene will add a commit to correct that when she'll have identified the issue.

**Comment by LAN-Laurene** [comment]
Hi @escopecz, 

I cancel the PR we noticed that it is because of a bad mautic configuration.

**Comment by malcolmgroves** [comment]
Hi @LAN-Laurene 

I've got the same issue (and a few other people [here](https://github.com/mautic/mautic/issues/3697). Can you share what was the bad configuration you found that resolved this?

**Comment by LAN-Laurene** [comment]
Hi @malcolmgroves,

For me, the error was on the `site URL` field in the configuration. You need to check that the value is exact.

capture

I hope this helps :)

**Comment by malcolmgroves** [comment]
Thanks @LAN-Laurene, unfortunately it is exact :-( Appreciate the response.

**Pull request closed without merging**
