### PR TITLE
Project Driven Sonar Scan

### PR DESCRIPTION
**Pull request by prateek-acq**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ No]
| New feature/enhancement? (use the a.x branch)      | [ Yes]
| Deprecations?                          | [ No]
| BC breaks? (use the c.x branch)        | [No ]
| Automated tests included?              | [ NA] 

#### Description:
This PR is for implementing project driven sonar scan for the branches and PRs.
Ensure creation of a SONAR_TOKEN environment variable in secrets.

(Additional description from @RCheesley)

What this PR adds:

1. Sonar properties file - defines some settings, paths etc for the Sonarcloud scan
2. Changes to tests.yml including:
    - Allowing tests to run on a branch called mauticSonar for any work that needs to be done on Sonar, in addition to the current branch restrictions
    - Make the code coverage report from Codecov readable by Sonar
    - Archive the code coverage report so that we can access it in a separate workflow (sonar.yml)
    - Save the PR number as an artifact so that we can access the PR and workflow run data in another workflow (sonar.yml)
3. Sonar.yml workflow in the .github/workflows - this must exist in the default branch for the workflows to function
    - Relies on the completion of the Mautic tests and validations workflow
    - When the tests pass successfully, it will:
        - Download an artifact from the test run which contains a reference to the PR number (PR_NUMBER.txt)
        - Reads this file and queries the GitHub API to get the PR data
        - Checks out the PR
        - Downloads the code coverage file from the test run (saved as an artifact)
        - Unzips the code coverage artifact and moves it inside the running container (clover.xml)
        - If the action is triggered on a PR, it will use the PR data to run the Sonarcloud scan
        - If the action is triggered on a push to a branch, it will just run as usual (no PR data needed as it is just checking the branch itself) 

#### Steps to test this PR:
This is CI/CD PR. Hence it does not need testing. It requires only review.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10825"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
Thank you for your help with getting this set up properly @prateek-acq - I've just added the SONAR_TOKEN secret so this should hopefully be good to go. 

Note to reviewers: We added the name of the branch in the list of branch names which the tests run, because that was needed when working locally. This can be removed once the PR is merged, I guess, or we could just keep that name/format in case we have to work on future stuff relating to Sonar.

**Comment by RCheesley** [comment]
This PR is currently failing because it's not able to see the SONAR_TOKEN secret. This is likely because GitHub doesn't pass secrets to external repos.

There were some changes made recently to work around this - see this article: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

> In order to solve this, we’ve added a new `pull_request_target` event, which behaves in an almost identical way to the `pull_request` event with the same set of filters and payload. However, instead of running against the workflow and code from the merge commit, the event runs against the workflow and code from the base of the pull request. This means the workflow is running from a trusted source and is given access to a read/write token as well as secrets enabling the maintainer to safely comment on or label a pull request.

I'm [checking with the Sonarcloud community](https://community.sonarsource.com/t/github-action-ci-build-fail-with-set-the-sonar-token-env-variable/38997/20?u=rcheesley) if this is the route we should explore.

**Comment by RCheesley** [comment]
The outcome of this is that the GitHub Action can't run on private forks, until they make some changes. It's a [highly requested feature](https://portal.productboard.com/sonarsource/1-sonarcloud/c/50-sonarcloud-analyzes-external-pull-request) so please go and vote there if you want this feature!

In the meantime we either have to wait, or we can look at using the automatic analysis which, while it works, may not give us the configuration options that we might need.

**Comment by RCheesley** [comment]
I've been working on this most of today and finally have some progress to report.

Firstly, we can't work on a PR to do this work, the GitHub Action for the scan will have to be in the default branch already - so I have been working in my fork.

Progress so far:

1. Updated the [tests.yml](https://github.com/RCheesley/mautic/pull/13/files#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957f) in accordance with the suggestions from [this thread](https://community.sonarsource.com/t/how-to-use-sonarcloud-with-a-forked-repository-on-github/7363/32?u=rcheesley).
2. Created a separate [sonar.yml](https://github.com/RCheesley/mautic/blob/4.x/.github/workflows/sonar.yml) - note that this file needs to already be present in the default branch as it makes use of `on: workflow_run` (e.g. it relies on the tests.yml to complete successfully) which allows us to run this on forks without access to secrets (which are accessed via the tests.yml workflow)

This results in the tests completing and then [triggering the sonar.yml workflow](https://github.com/RCheesley/mautic/runs/6427405020?check_suite_focus=true), which now works in that it runs the Sonar scan (nb I had to update the properties file to point at my own org / repo).

At this time, it seems to (from first look) be running [against the whole repo](https://sonarcloud.io/summary/new_code?id=RCheesley_mautic&pullRequest=13) so I will need to tweak that - it might be because I haven't had Sonarcloud set up yet for the repo though.

Furthermore, I had to remove the code coverage upload to just get this working in the basic form to start with - I'll need to re-add that as well so that we're posting the Codecov outcome to Sonarcloud - hopefully that should be possible to do now I'm neck deep on pulling in things from previously executed workflows!

I have to stop for now before my brain explodes 🤯  but I will come back to this next week and hopefully we can get it to a point where we can bring Sonarcloud support to forked PRs in mautic/mautic to help us improve our code quality iteratively over time!

**Comment by RCheesley** [comment]
Hi folks! 

Fairly major breakthrough in getting this working on PRs from forks, which SonarCloud does not support natively.

I now have a working example on my fork here: https://github.com/RCheesley/mautic/pull/13 with the SonarCloud report at https://sonarcloud.io/summary/new_code?id=RCheesley_mautic&pullRequest=13.  

This also uploads the code coverage report from Codecov and includes that in the analysis.

If we want to bring this into mautic/mautic **we can’t test it until the sonar.yml file is present in the default branch**, as it requires that for any of the checks to run. So we will have to either add that file in a separate PR to the one introducing the GitHub Action, or in the same PR with the proviso that it can’t be tested (because the file will not be already present in the default branch). I have taken the second approach, including it here. You can review and test on the PR on my fork.

We will of course need to communicate this out to developers what this check is (although the feedback is pretty concise and clear, from what I have seen) and make sure we have clear documentation on how to install the linter to give folks advice while they are coding (we can add it as a recommended extension) and what the different issues indicate/how we will treat them when reviewing PRs with outstanding issues (e.g. which we can safely ignore, which must be fixed before merging, for example).

**Comment by escopecz** [comment]
I discussed the future of this PR with @RCheesley and we decided to close this as it cannot be tested on a PR. It's still here as a reference once the issue with forks is resolved on the SonarQube side.

**Pull request closed without merging**
