### PR TITLE
Allow nullable values for value and label of Sortablelist

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
IF you save empty values in sortable list field type it return 500 error

image

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Try create select custom field
3. Let item empty of select value
image
4. Try save field
5. Without PR return error, after PR works as expected

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11068"></a>

### CODE REVIEW

**Review by jos0405 — APPROVED** [review]
Works as described.
Plz note, that it's possible to save empty label. I'm not sure if it's a good thing, but maybe okay.

image

**Comment by escopecz** [comment]
@kuzmany I'm wondering whether the proper fix isn't to validate the choices and disallow empty values. Is there a use case for empty values?

This will also need a test.

**Comment by kuzmany** [comment]
@escopecz my goal was prevent the 500 error at that moment. I know  there are more sophisticated solutions, but but this was sufficient for us.

**Comment by kuzmany** [comment]
@escopecz once If you agree with this solution, I will add unit tests

**Comment by escopecz** [comment]
I looked at it more closely and found that there is quite a lot of code which goal is to prevent calling this method with `null` values. And I believe it is better option to use strict types and ensure the method gets the types it expects then allowing null when not necessary. I created this alternative PR when I was looking through the code:

https://github.com/mautic/mautic/pull/11101

Please take a look.

**Comment by kuzmany** [comment]
Close favor to https://github.com/mautic/mautic/pull/11101

**Pull request closed without merging**
