### PR TITLE
AVG rounding in reports removed

### PR DESCRIPTION
**Pull request by annamunk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | no
| New feature/enhancement? (use the a.x branch)      | yes
| Deprecations?                          | no
| BC breaks? (use the c.x branch)        | no
| Automated tests included?              | yes
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

In the Emails Sent Report, we used to group our emails by ID and want to calculate AVG Read, AVG Bounced, AVG Unique clicks, AVG Unsubscribed statistics. By default, AVG is rounded to integer, so in our case, detailed values between 0 and 1 are lost. This PR removes AVG rounding.

#### Steps to test this PR:

1. Create Report with Data Source set to Emails Emails Sent.
2. In Data tab add Columns ID, Name and Group by ID. 
3. In Calculated columns add functions as follows:
Funtion: AVG, Column: Read, 
Funtion: AVG, Column: Bounced, 
Funtion: AVG, Column: Unique clicks, 
Funtion: AVG, Column: Unsubscribed statistics, 
4. Publish report and click Save & Close.
5. Check if results in AVG columns are float, not integer. 

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11273"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for making the PR @annamunk and welcome to the community!

It looks like you may need to add the email address you use to sign your Git commits to your GitHub profile, and then sign the [contributors agreement](https://www.mautic.org/contributor-agreement) :)

**Comment by annamunk** [comment]
@RCheesley thank you! 
I signed Mautic Contributors Agreement by sending email on 21.04.2022, but in document I included a company e-mail address and later made changes with the address alias. I've already linked both email addresses to my GitHub profile, so this shouldn't be a problem anymore. Is it possible to restart the cla-bot?

**Comment by RCheesley** [comment]
Yep will try again!

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by annamunk** [comment]
@RCheesley thank you!

**Review by escopecz — DISMISSED** [review]
I see no problem to merge this from the code perspective. Rounding the AVG results was added in https://github.com/mautic/mautic/commit/10425bdb3edb2ba66cdc15ddf95ffadb91a12505 and it doesn't seem like it was the main goal of the commit. I let others to chime in if the result is better UI than before.

**Comment by escopecz** [comment]
@annamunk please rebase on top of the 5.x branch as there will be no more feature releases in Mautic 4.

**Comment by annamunk** [comment]
@escopecz thank you! I rebased changes on top of the 5.x branch.

**Review by escopecz — APPROVED** [review]

**Review by RCheesley — COMMENTED** [review]
I have set up the report as instructed after sending some emails:

New Report _ Mautic

As soon as I save the report I am getting an error as below:



```
[2022-06-28 16:51:01] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'SELECT count(*) FROM (SELECT `e`.`id` AS e_id, `e`.`name` AS e_name, AVG() AS 'AVG ', AVG() AS 'AVG ', AVG() AS 'AVG ', AVG(IF(dnc.id IS NOT NULL AND dnc.reason=1, 1, 0)) AS 'AVG unsubscribed' FROM email_stats es LEFT JOIN emails e ON e.id = es.email_id LEFT JOIN lead_donotcontact dnc ON es.email_id = dnc.channel_id AND dnc.channel='email' AND es.lead_id = dnc.lead_id WHERE es.date_sent IS NULL OR (es.date_sent BETWEEN ? AND ?) GROUP BY e.id) c' with params ["2022-05-28 00:00:00", "2022-06-28 16:51:01"]:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AS 'AVG ', AVG() AS 'AVG ', AVG() AS 'AVG ', AVG(IF(dnc.id IS NOT NULL AND ...' at line 1" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 98 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'SELECT count(*) FROM (SELECT `e`.`id` AS e_id, `e`.`name` AS e_name, AVG() AS 'AVG ', AVG() AS 'AVG ', AVG() AS 'AVG ', AVG(IF(dnc.id IS NOT NULL AND dnc.reason=1, 1, 0)) AS 'AVG unsubscribed' FROM email_stats es LEFT JOIN emails e ON e.id = es.email_id LEFT JOIN lead_donotcontact dnc ON es.email_id = dnc.channel_id AND dnc.channel='email' AND es.lead_id = dnc.lead_id WHERE es.date_sent IS NULL OR (es.date_sent BETWEEN ? AND ?) GROUP BY e.id) c' with params [\"2022-05-28 00:00:00\", \"2022-06-28 16:51:01\"]:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AS 'AVG ', AVG() AS 'AVG ', AVG() AS 'AVG ', AVG(IF(dnc.id IS NOT NULL AND ...' at line 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:98, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AS 'AVG ', AVG() AS 'AVG ', AVG() AS 'AVG ', AVG(IF(dnc.id IS NOT NULL AND ...' at line 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AS 'AVG ', AVG() AS 'AVG ', AVG() AS 'AVG ', AVG(IF(dnc.id IS NOT NULL AND ...' at line 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)
[stacktrace]
#0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(182): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDO\\Exception))
#1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(159): Doctrine\\DBAL\\DBALException::wrapException(Object(Doctrine\\DBAL\\Driver\\PDO\\MySQL\\Driver), Object(Doctrine\\DBAL\\Driver\\PDO\\Exception), 'An exception oc...')
#2 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(2226): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDO\\MySQL\\Driver), Object(Doctrine\\DBAL\\Driver\\PDO\\Exception), 'SELECT count(*)...', Array)
#3 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1313): Doctrine\\DBAL\\Connection->handleExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDO\\Exception), 'SELECT count(*)...', Array, Array)
#4 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(212): Doctrine\\DBAL\\Connection->executeQuery('SELECT count(*)...', Array, Array)
#5 /var/www/html/app/bundles/ReportBundle/Model/ReportModel.php(750): Doctrine\\DBAL\\Query\\QueryBuilder->execute()
#6 /var/www/html/app/bundles/ReportBundle/Model/ReportModel.php(629): Mautic\\ReportBundle\\Model\\ReportModel->getTotalCount(Object(Doctrine\\DBAL\\Query\\QueryBuilder), Array)
#7 /var/www/html/app/bundles/ReportBundle/Controller/ReportController.php(652): Mautic\\ReportBundle\\Model\\ReportModel->getReportData(Object(Mautic\\ReportBundle\\Entity\\Report), Object(Symfony\\Component\\Form\\FormFactory), Array)
#8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(158): Mautic\\ReportBundle\\Controller\\ReportController->viewAction('16', 1)
#9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#10 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 /var/www/html/app/AppKernel.php(104): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#16 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#18 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#19 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#20 {main}
"} {"hostname":"mautic-web","pid":2515}
```

**Comment by kuzmany** [comment]
@RCheesley try add also these columns (read, bounced) to columns, probably builder does not add it to query If they are just in calculated columns

**Review by kuzmany — APPROVED** [review]
Make sense. Did try basic examples, it works

**Comment by escopecz** [comment]
@RCheesley if you agree, I mark this PR as ready-to-commit as it does not introduce the bug you have found. It existed before this change.

**Pull request merged**
