### PR TITLE
fix:[DPMMA-2746] fix assets reports

### PR DESCRIPTION
**Pull request by AlanWierzchonCA**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [YES ]
| New feature/enhancement? (use the a.x branch)      | [NO ]
| Deprecations?                          | [NO ]
| BC breaks? (use the c.x branch)        | [NO ]
| Automated tests included?              | [NO ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Fix Bug: https://github.com/mautic/mautic/issues/13695

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Add an asset
– Upload a local file (I tried with both .png and .jpg)
– Do not alter/edit anything else and click on “Save & Close”
– Copy the download URL
Generate a lead by opening the download URL of the newly created asset in a new incognito window (I used Brave browser)
Open the report “Downloads of all Assets”
– A 500 Internal Server Error should not be thrown.

### CODE REVIEW

**Review by RCheesley — APPROVED** [review]
Resolved the bug and the report is now accessible - thanks so much @AlanWierzchonCA 🚀

**Comment by juangadiel** [comment]
I can confirm this pull request fixes the bug #13695.

image

**Comment by escopecz** [comment]
@AlanWierzchonCA could you check the failing tests? I'll re-run the CI again to see if it's just a flaky test, but it failed the same way for 2 PHP versions

**Comment by escopecz** [comment]
Nice! So it was a flaky test after all!

**Review by escopecz — APPROVED** [review]
I'd solve it with `row.id is defined` as it is in row 27, but this works too 👍

**Comment by RCheesley** [comment]
@juangadiel in the future if you can go to [files changed -> leave a review](https://contribute.mautic.org/contributing-to-mautic/tester#leaving-your-review) (top right) it counts as a contribution, and our team also consider that as an approval. Thanks so much for reporting the test in the comment though! 🚀

**Comment by RCheesley** [comment]
@all-contributors please add @juangadiel for usertest

**Comment by RCheesley** [comment]
https://github.com/all-contributors please add @juangadiel for usertesting

**Comment by RCheesley** [comment]
@all-contributors please add @juangadiel for usertest

**Comment by RCheesley** [comment]
@all-contributors please add @juangadiel for usertesting

**Comment by juangadiel** [comment]
> @juangadiel in the future if you can go to [files changed -> leave a review](https://contribute.mautic.org/contributing-to-mautic/tester#leaving-your-review) (top right) it counts as a contribution, and our team also consider that as an approval. Thanks so much for reporting the test in the comment though! 🚀

Good to know, thanks!

**Pull request merged**
