### PR TITLE
Lead tags

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**
This adds tagging to leads.

1) Manually tag/untag through lead profile page
2) Tag through API lead endpoints by using tags=tag1,tag2,-tag3 (use - to remove the tag)
3) Tag through tracking pixel by appending tags=tag1,tag2,-tag3 (use - to remove the tag)
4) Tag through campaign action, form submit action, point trigger action
5) Search for leads by tag by using tag:TAG annotation
6) Tag on import

**Testing**
After applying the PR, clear cache and update doctrine schema to install new tables.

Test above feature list.

### CODE REVIEW

**Comment by drmmr763** [comment]
I ran into an issue testing this, I got this error:

```Internal Server Error - Notice: Undefined index: public_profile in /Users/chadwindnagle/Sites/gh-mautic/app/bundles/PluginBundle/Helper/IntegrationHelper.php line 176```

I was able to fix the error by going the plugins area and then hitting install plugins. I'm pretty certain this is unrelated to the tag feature, and possibly fixed elsewhere.
--

@ Test 

When I created a new tag from the profile I got this error:

```
Internal Server Error - Attempted to load class "InputHelper" from namespace "Mautic\LeadBundle\Model" in /Users/chadwindnagle/Sites/gh-mautic/app/bundles/LeadBundle/Model/LeadModel.php line 994. Do you need to "use" it from another namespace? 
```

**Comment by alanhartless** [comment]
Fixed the missing use statement.  The PHP notice is fixed with https://github.com/mautic/mautic/pull/794.

**Comment by escopecz** [comment]
1. Works
2. I was not able to create a lead via API. Here is how API tester log looks like
apitester-new-lead
3. I was not able to create/update a lead via tracking pixel either. I used this code for tracking pixel:
```
<img src="http://localhost/mautic-github/mtracking.gif?firstname=trackingpixel&tag=tag1,tag2,-tag3" />
```
and I was not able to find that lead by searching by name or tag1. I made firstname field publicly updatable before test.
4. I created a campaign with form source of leads and the change lead tags action. Then I went to the form detail and there was this error:
```
 500 Internal Server Error - The key, 'group' is missing.
```
```
/var/www/html/mautic-github/app/bundles/FormBundle/Event/FormBuilderEvent.php (line #196):
/var/www/html/mautic-github/app/bundles/FormBundle/Event/FormBuilderEvent.php (line #99): at Mautic\FormBundle\Event\FormBuilderEvent -> verifyComponent ( array('group', 'label', 'formType', 'callback'), array('callback', 'validator'), array('label' => 'mautic.lead.lead.events.changetags', 'description' => 'mautic.lead.lead.events.changetags_descr', 'formType' => 'modify_lead_tags', 'callback' => '\Mautic\LeadBundle\Helper\EventHelper::updateTags') )
/var/www/html/mautic-github/app/bundles/LeadBundle/EventListener/FormSubscriber.php (line #69): at Mautic\FormBundle\Event\FormBuilderEvent -> addSubmitAction ( 'lead.changetags', array('label' => 'mautic.lead.lead.events.changetags', 'description' => 'mautic.lead.lead.events.changetags_descr', 'formType' => 'modify_lead_tags', 'callback' => '\Mautic\LeadBundle\Helper\EventHelper::updateTags') )
at Mautic\LeadBundle\EventListener\FormSubscriber -> onFormBuilder ( object(FormBuilderEvent), 'mautic.form_on_build', object(TraceableEventDispatcher) )
```
5. Works
6. Works

**Comment by alanhartless** [comment]
@escopecz My bad.  The notation is "tags" not "tag." I updated the description.  Also fixed the missing group.  Thanks!

**Comment by escopecz** [comment]
Update of test:
1) Works
2) There is the problem that new lead cannot be created via API. Or is it problem on my local?
3) Works
4) Form works now. But there is this error on triggering the campaign:
```
php app/console mautic:campaign:trigger
Triggering events for campaign 25
Triggering first level events
1 total events(s) to be processed in batches of 100
 0/1 [>---------------------------]   0%PHP Catchable fatal error:  Argument 1 passed to Mautic\LeadBundle\Helper\EventHelper::updateTags() must be an instance of Mautic\LeadBundle\Helper\Lead, instance of Mautic\LeadBundle\Entity\Lead given in app/bundles/LeadBundle/Helper/EventHelper.php on line 21
```
5) Works
6) Works

**Comment by drmmr763** [comment]
+ Test
+ + Tested creating tags from lead view 
+ + tested creating lead and tags
+ + tested lead with form and tag action - works!
+ + lead created and tags via tracking pixel
+ + tag on import worked
+ + tag search works

+ vote +1

**Pull request merged**
