### PR TITLE
Change lead company link to View instead of Edit

### LINKED ISSUE #9123: Contacts Link to Company Not updated to View Layout
| Q   | A
| --- | ---
| Mautic version | 3.1.0+

### Steps to reproduce
1. Go to a contact who is assigned to a company.
2. Click on the link on the right side to the company page. It's currently set to the "edit" view instead of the new "view" layout.

mautic-companylink

### PR DESCRIPTION
**Pull request by colourfulowl**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging for features or enhancements / 3.0 for bug fixes 
| Bug fix?                               | yes?
| New feature?                           | yes?
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | NA
| Related developer documentation PR URL | NA 
| Issue(s) addressed                     | Fixes #9123   

#### Description:
This changes it so when you click on the company link on a lead it takes you to View of the company instead of the Edit view of the company.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2.

### CODE REVIEW

**Review by npracht — APPROVED** [review]
I confirm it works. Good UX enhancement.
Can you please sign the agreement ?

**Comment by colourfulowl** [comment]
> Can you please sign the agreement?

Signed :)

**Review by kuzmany — APPROVED** [review]
👍

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Awesome, thanks for making the PR @colourfulowl congrats on making your first contribution! 🎉

**Pull request merged**
