### PR TITLE
Allow append data to reports with plugin

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR allow extend reports table column by plugin. 
We have plugin extend email entity with extra1 and extra2 and this PR allow display this column in email report.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Code review is sufficient 
3. We can share also private plugin for testers (ask @npracht for access) 

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/7539"></a>

### CODE REVIEW

**Comment by npracht** [comment]
@kuzmany could you please update the PR to make it mergable ?

**Review by npracht — DISMISSED** [review]

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebased

**Comment by RCheesley** [comment]
@kuzmany @npracht could you share the plugin to permit testing please?

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@kuzmany appreciate this is a very old PR, do you want to rebase it for 5?

**Comment by kuzmany** [comment]
We do not use this for custom plugin anymore.

**Pull request closed without merging**
