### PR TITLE
Sugarcrm community-6 and sugarCRM 7 integration fullsync

### PR DESCRIPTION
**Pull request by mqueme**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Separated the code from #3702 so that we can merge this PR to work with Sugar CRM 6 community edition.
There are some pending checks. for updating contacts
#### Steps to test this PR:
1. install SugarCRM community edition. you can download from here [https://www.sugarcrm.com/download-ce](https://www.sugarcrm.com/download-ce)
2. Create Oauth keys in a SugarCRM 6.X instance [https://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_6.5/Application_Framework/Authentication/Oauth/](https://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_6.5/Application_Framework/Authentication/Oauth/) (Just step 1)
3. On the Mautic side, configure the SugarCRM plugin (Sugar URL, keys, login/password)
4. On the Mautic side, configure the plugin functionalities
5 On the Mautic side, configure the fields mapping for contacts/leads and companies
6. Run php app/console mautic:integration:fetchleads --integration=Sugarcrm
or php app/console mautic:integration:fetchleads --fetch-all --integration=Sugarcrm to synchronize all leads.

for sugarcrm 7 you will need admin login and password

### CODE REVIEW

**Comment by escopecz** [comment]
I'm still getting this error even though the required fields for company are filled in.

screen shot 2017-06-22 at 14 04 34


Also, the company mapping tab appeared after I mapped contact fields and hit apply and I got this error. It wasn't there after I authorised the plugin and the contact mapping tab appeared.

**Comment by escopecz** [comment]
The command did not push any Mautic contacts nor companies to Sugar:
```
$ php app/console mautic:integration:fetchleads --fetch-all --integration=Sugarcrm --env=dev
Command to fetch contacts from integration
Fetch contacts command is starting


0 contacts were updated and 0 contacts were created

Fetching companies
Fetch companies command is starting

0 companies were updated and 0 companies were created

Updating/creating leads from Mautic to Sugarcrm
Number of contacts pushed: 0 updated, 0 created, ? had errors and 0 were ignored (likely duplicates or didn't match field criteria)
```
Also there is 1 argument missing in the translation it seems (the question mark).

But it fetches all the companies and contacts from Sugar to Mautic. Should it even push from Mautic to Sugar?

**Comment by escopecz** [comment]
The company issue seems to be fixed, the Mautic contacts are being pushed to Sugar, but the contacts doesn't update no matter in what system I change the last name nor where the arrows are pointing.

**Comment by npracht** [comment]
Hi @mqueme & @clemrvt i've been testing, i have an issue with the sync. of the contact owner. When assigned to a contact in Mautic, it does not get to Sugar when the lead is pushed (and created).
Contact owner has the same email address in both app. Am i doing something wrong ?

N.

**Comment by giampyart** [comment]
HI @mqueme, testing this PR and companies and contacts are pulled from SuiteCRM but when I edit one mapped field it doen't update both CRM and Mautic (I tested both ways).

**Comment by mqueme** [comment]
@escopecz, @giampyart @npracht would you be able to test this again pls.

**Comment by giampyart** [comment]
@mqueme I made some tests and both doesn't update mapped fields in both directions.
To be sure could u share the steps to reproduce the pr or test?
I followed these:
- Create contact in SuiteCRM 
- run cron job and Contact is pulled fine into Mautic as Lead
- create a Lead in Mautic and using a campaign this lead is pushed correctly to Suite CRM using cron job campaign:trigger
- After steps above I tried to edit some mapped fields on both entity but SuiteCRM and Mautic don't sync.

**Comment by mqueme** [comment]
What is your data flow arrows pointing like? On create all mapped fields are used for either sides. On update it updates using data flow of how arrows are pointing in the configuration window.

**Pull request merged**
