### PR TITLE
Fix Code Mode block for non valid HTML

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Noticed If we use non valid HTML in Code Block, the builder broke it.

If you're using RSS Bundle for Mautic  https://github.com/ChrisRAoW/mautic-rss-to-email-bundle and use table layout

```
{feed url="https://www.webmecanik.com/feed/"}
  <table>
    <tr>
      {feeditems count="3"}
        <td>
          <h3>{feeditem:title}</h3>
          <p><small>{feeditem:date format="d-m-Y H:i"}</small></p>
          <p>{feeditem:description}</p>
          <p><img src="{feeditem:image}"></p>
        </td>
      {/feeditems}
    </tr>
  </table>
{/feed}
```

Mautic builder broke it to:

```
{feed url="https://www.webmecanik.com/feed/"}
{feeditems count="3"}
    {/feeditems}
  <table><tbody><tr><td>
        <h3>{feeditem:title}</h3>
        <p><small>{feeditem:date format="d-m-Y H:i"}</small></p>
        <p>{feeditem:description}</p>
        <p><img src="{feeditem:image}"></p>
  </td></tr></tbody></table>
{/feed}
```

This PR make html validation of code mode block, If is not valid encode html content, store to data attribute of code mode block and then on save paste that code on search/replace.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Install 
2. Create email and create code mode slot with this content

```
{feed url="https://www.webmecanik.com/feed/"}
  <table>
    <tr>
      {feeditems count="3"}
        <td>
          <h3>{feeditem:title}</h3>
          <p><small>{feeditem:date format="d-m-Y H:i"}</small></p>
          <p>{feeditem:description}</p>
          <p><img src="{feeditem:image}"></p>
        </td>
      {/feeditems}
    </tr>
  </table>
{/feed}
```
2. Unselect code mode slot and then select again. Should see broken code and broken email preview

```
{feed url="https://www.webmecanik.com/feed/"}
{feeditems count="3"}
    {/feeditems}
  <table><tbody><tr><td>
        <h3>{feeditem:title}</h3>
        <p><small>{feeditem:date format="d-m-Y H:i"}</small></p>
        <p>{feeditem:description}</p>
        <p><img src="{feeditem:image}"></p>
  </td></tr></tbody></table>
{/feed}
```

#### Steps to test this PR:
1. Load up [this PR](https://m3.mautibox.com)
2. Repeat all steps
3. You should see correct code and email preview

### CODE REVIEW

**Comment by pako69** [comment]
hi @kuzmany 
I'm facing the same bug. is there a solution?
Thanks

**Comment by npracht** [comment]
@pako69 did you try to apply this PR to fix the issue ?

**Comment by pako69** [comment]
> @pako69 did you try to apply this PR to fix the issue ?

Her Norman, It's Pascal Bouthis there ;-) This issue is still present...

Try this below in a Code Mode block:

```
{feed url="https://www.dimosoftware.fr/feed/feedname/"}
    {feeditems count="3"}
    <p><a target="_blank" href="{feeditem:link}"><img src="{feeditem:image}" width="160" height="107" alt="{feeditem:title}"></a></p>
    <p>{feeditem:category}</p>
    <p><a target="_blank" href="{feeditem:link}">{feeditem:title}</a></p>
    {/feeditems}
{/feed}    
```

> It Works

Try this:
```
{feed url="https://www.dimosoftware.fr/feed/feedname/"}
  <table>
    <tr>
      {feeditems count="3"}
        <td>
          <p><a target="_blank" href="{feeditem:link}"><img src="{feeditem:image}" width="160" height="107" alt="{feeditem:title}"></a></p>
          <p>{feeditem:category}</p>
          <p><a target="_blank" href="{feeditem:link}">{feeditem:title}</a></p>
        </td>
      {/feeditems}
    </tr>
  </table>
{/feed}
```

> It's totaly broken...

**Comment by janus-reith** [comment]
I tried to apply this PR, hoping it would fix my issue where my perfectly fine MJML-generated code is messed up as soon I save changes to the email - Sadly without success.

**Comment by kuzmany** [comment]
@janus-reith I don't think this PR could cover your template. This just cover code mode block content

**Comment by janus-reith** [comment]
@kuzmany you're right, also found the solution for the issue I had in a diferent file handling html input validation, will create a separate issue.

**Review by mabumusa1 — DISMISSED** [review]
Tried this PR with different codes that include invalid HTML include the example provided, it worked as expected

**Comment by npracht** [comment]
FYI we use it in production for 2 months

**Review by dennisameling — APPROVED** [review]
Code looks good. Since there's already 1 approval and it's running in prod at Webmecanik, approving 👍

**Pull request merged**
