### PR TITLE
[UX] Change Alias tooltips when creating Segments, Assets, Landing pages, Forms, from "Alphanumeric string" to "Letters and numbers"

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
The current tooltip for the Alias field in the creation of Segments, Assets, Landing pages, and Forms, which is “Alphanumeric string”, presents an opportunity for enhancement. It would be beneficial to use a more commonly understood term. The proposed solution in this pull request is to change the tooltip to “Letters and numbers”, which is a more straightforward description of the input requirements.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Segments
3. Create a new segment
4. Hover your mouse above the Alias field
5. Read the tooltip

image

### CODE REVIEW

**Comment by LordRembo** [comment]
'Alphanumeric' normally includes punctuation marks (eg. `,'().!?`) and special characters (eg. `*&$=`) as well, like used for making passwords. It's kinda weird that the original text then only mentions you can use hyphens, but are you sure only letters and numbers are allowed?

Reference: https://computer.howstuffworks.com/alphanumeric-characters.htm

**Comment by LordRembo** [comment]
Maybe @escopecz or @mollux can shed some light here?

**Review by escopecz — APPROVED** [review]
I think it is fine. I don't have a problem with alphanumeric, but letters and numbers may be more user friendly. I think that aliases only support letters, numbers and hyphens. We were recently also allowing underscores but I'm not sure if it was merged yet.

**Review by LordRembo — APPROVED** [review]
In that case, it's all good for me too.

**Pull request merged**
