### PR TITLE
Recover contact timeline

### PR DESCRIPTION
**Pull request by LAN-Laurene**
| Q             | A
| ------------- | ---
| Bug fix?      | 
| New feature?  |  X
| BC breaks?    | 
| Deprecations? | 
| Fixed issues  |  https://github.com/mautic/mautic/issues/1296

## Description

Hello,

Webmecanik has added a new route to the API. It allows us to recover the pages visited by a lead.

To call via the API, use: `leadHistory($leadId);` (endpoint : lead).

The pull request is complemented by that of the API librairy (https://github.com/mautic/api-library/pull/40) and that of the documentation (https://github.com/mautic/developer-documentation/pull/16)

### CODE REVIEW

**Comment by escopecz** [comment]
I'm getting error

```
Attempted to call an undefined method named getModel of class Mautic\\LeadBundle\\Controller\\Api\\LeadApiController on line 30.
```
Is your branch up to date with refactoring in current staging branch?

**Comment by npracht** [comment]
Hi @escopecz,

We've installed it on a 2.0.1 version and it's working without getting the issue.
Any advice to help us?

N.

**Comment by escopecz** [comment]
Ah, it might be an issue in the Mautic 2.0.0 codebase. I'll test it again with 2.0.1

**Comment by alanhartless** [comment]
Let's get /leads/ updated to /contacts/ in the URL.

Also, referencing #1296 Seems this one only pulls in page hit history though right? Not the lead's timeline. Maybe #2074 can be leveraged for this since it built in pagination. There are some databases floating out there with tens of thousands of page hits for single contacts so pagination/limiting results may be required for this to be effective.

**Comment by Dcoutelle** [comment]
@alanhartless @escopecz 

I propose to cancel this PR and make a new one from 2.1 version... this one is too old now, and can't be completed without conflicts.

Are you ok with this ?

**Comment by escopecz** [comment]
Sure

**Comment by npracht** [comment]
Hi, i think it should be close as far as it has been re-pulled on https://github.com/mautic/mautic/pull/2388

**Pull request closed without merging**
