### PR TITLE
Unable to find template GrapesJsBuilder/Setting/vars.html.twig

### PR DESCRIPTION
**Pull request by tomekkowalczyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ Y ]
| New feature/enhancement? (use the a.x branch)      | [ N ]
| Deprecations?                          | [ N ]
| BC breaks? (use the c.x branch)        | [ N ]
| Automated tests included?              | [ N ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Correct Bug: 
`mautic.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Unable to find template "GrapesJsBuilder/Setting/vars.html.twig" (looked into: /var/www/html/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views, /var/www/html/vendor/symfony/twig-bridge/Resources/views/Form).")."`

image

URL: https://mautic.ddev.site/index_dev.php/s/emails/new

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by escopecz** [comment]
@mabumusa1 it looks like this is reverting some refactoring you've done in past few days.

@tomekkowalczyk there is a conflict with your changes. Can you please test if you still have the issue with the latest 5.x branc?

**Comment by tomekkowalczyk** [comment]
@escopecz We have new bug (https://mautic.ddev.site/index_dev.php/s/emails/new):

image

**Comment by mabumusa1** [comment]
> @escopecz We have new bug (https://mautic.ddev.site/index_dev.php/s/emails/new):
> 
> image

@tomekkowalczyk @escopecz the fix is coming for this issue in this PR/

Thanks @tomekkowalczyk for reporting

**Comment by escopecz** [comment]
@mabumusa1 you probably forgot to link the PR. So can this be closed?

**Comment by mabumusa1** [comment]
Yes, the fix is in this PR #12136

**Comment by tomekkowalczyk** [comment]
@escopecz, @mabumusa1 

OK thanks

**Pull request closed without merging**
