### PR TITLE
DDEV fix  windows style line breaks for pre-commit and post-checkout git hooks

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:
If I am using commit and checkout on my DDEV in PHPStorm I geterror `bash\r: No such file or directory`
This PR fixed line breaks from Windows

1. Load up [this PR](https://mautibox.com)
2. Just try `ddev start` If works like before

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10551"></a>

### CODE REVIEW

**Review by dennisameling — DISMISSED** [review]
Code looks good but I think this needs a rebase to fix the Codecov issue.

**Comment by kuzmany** [comment]
@dennisameling don't have idea why CodeCov failed I rebase it

**Comment by RCheesley** [comment]
@kuzmany we are still having a problem with the 4.0 branch, hence why we have not yet released 4.0.2. It's reporting all PR's as lowering code coverage because a bunch of files are being included which aren't in the PR.

**Comment by kuzmany** [comment]
@RCheesley thanks for info 👍

**Comment by RCheesley** [comment]
Could you please rebase this against the 4.x branch? Thanks!

**Review by mmarton — DISMISSED** [review]
Tested it and it works for me (it worked before the change, but I guess not everyone use autocrlf=input setting)

**Comment by kuzmany** [comment]
@RCheesley rebased
There are two reviews. I hope it could be ready to commit

**Comment by RCheesley** [comment]
Codecov may throw a wobbly on this PR because it's not changing any tracked code. So it's safe to ignore in this instance.

**Comment by kuzmany** [comment]
@RCheesley can you approve it and merge?

**Comment by RCheesley** [comment]
@all-contributors please add @mmarton for userTesting

**Pull request merged**
