### PR TITLE
[UI] Update placeholders and plugins logos

### LINKED ISSUE #13147: Replace placeholder images
### Description
Replace outdated and generic placeholder images with more relevant and visually appealing images throughout the platform.

Based on user feedback:

> Imagery: replace the placeholder images by more modern ones

### Impact
Replacing old placeholder images will contribute to a more polished and engaging user interface, elevating the overall visual appeal and user experience, and potentially enhancing user engagement and satisfaction.

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #13147 

#### Description:

Based on feedback:

> Imagery: replace the placeholder images by more modern ones

The user is suggesting that the current placeholder images used in the platform appear outdated and should be replaced with more contemporary visuals. This feedback indicates that the imagery does not align with modern design trends or the user’s aesthetic expectations.

The user’s broader need is for a visually appealing platform that reflects current design standards and resonates with a modern audience. 

To address this feedback, this PR updates Mautic placeholder images with modern, high-quality images and logos that better represent current brands.

image

image

- [x] fix .img-responsive with to fill 100%

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Contacts > create new > See the new placeholder for contacts without profile pic
3. Open right sidebar > Plugins > Look at the new social and brands logos

### CODE REVIEW

**Review by shinde-rahul — APPROVED** [review]
LGTM! 

Thanks @andersonjeccel

**Comment by LordRembo** [comment]
I have the same remark as with PR #13629: if we're going to propose a UI overhaul / design system change anyway, is it worth pushing design updates for this design? @Mike-Dropsolid

**Comment by Mike-Dropsolid** [comment]
> I have the same remark as with PR #13629: if we're going to propose a UI overhaul / design system change anyway, is it worth pushing design updates for this design? @Mike-Dropsolid

This wouldn't have to be redone at least. Especially the logos update feels useful to me already. I don't mind.

**Comment by LordRembo** [comment]
Alrighty, 👍

**Review by kuzmany — DISMISSED** [review]

**Review by LordRembo — APPROVED** [review]
Good to go then!

**Comment by escopecz** [comment]
There is a failing test that must be fixed

**Comment by andersonjeccel** [comment]
I'll fix next Tuesday

**Comment by andersonjeccel** [comment]
The local file is .svg and Gravatar's .png

Actual code:

Gravatar
`$this->assertSame('https://www.gravatar.com/avatar/96f1b78c73c1ee806cf6a4168fe9bf77?s=250&d=http%3A%2F%2Flocalhost%2Fimages%2Favatar.png', $avatar, 'Gravatar image should be returned');`

Localhost
`$this->assertSame('http://localhost/images/avatar.svg', $avatar, 'Default image image should be returned');`

Even if the second is .png, it throws an error bc the existing file is .svg (less size, improves platform's performance)

**Comment by andersonjeccel** [comment]
@LordRembo help needed to fix the test 🙏🏻

**Comment by LordRembo** [comment]
@andersonjeccel You'll need to change the reference in the test. See file `app/bundles/LeadBundle/Tests/Helper/AvatarHelperTest.php`
Somewhere at the bottom, you'll see multiple references to `avatar.png`, you need to change the extension to `.svg` if that is the new format for the default avatar.
Maybe best to do another search for 'avatar.png' in the project, to check if there are any other incorrect references remaining.

**Comment by andersonjeccel** [comment]
@escopecz Seems fixed

**Comment by escopecz** [comment]
Nice! Is this ready for tests and review? If so, can it be moved out of draft?

**Comment by andersonjeccel** [comment]
@escopecz Now it's ready!

**Comment by escopecz** [comment]
the plugin logo changes look great. I'm not sure about the contact avatar. Is that a head with a steering wheel? If so, why?

**Comment by andersonjeccel** [comment]
It's an user icon 

image

How could I make it better?

**Comment by escopecz** [comment]
Now I get it. I looked at all the Remix user icons and when I saw this:
Screenshot 2024-05-02 at 08 59 20
https://remixicon.com/icon/user-3-line

I understood that the icon you selected is a head with shoulders. Not a steering wheel. But it's more abstract. I like the user, user-1 and user-2 better than user-6 as those I understand is a silhouette of a person. I couldn't get it from user-6 even though I tried.

**Comment by andersonjeccel** [comment]
Yeah, makes sense
I’ll change it soon!

**Comment by andersonjeccel** [comment]
@escopecz Say hi to Mrs Random

image

**Review by escopecz — APPROVED** [review]
Thank you! 👍

**Pull request merged**
