### PR TITLE
Fix minor typo.

### PR DESCRIPTION
**Pull request by giomasce**
Signed-off-by: Giovanni Mascellani <giovanni@mascellani.eu>

Nothing really strange. There was a typo and I fixed it.

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for making the PR @giomasce !

**Review by RaphaelWoude — APPROVED** [review]
Tested and works as expected.

**Review by mabumusa1 — APPROVED** [review]
Did a code review, it looks fine

**Comment by RCheesley** [comment]
Not stale!

**Comment by RCheesley** [comment]
@all-contributors please add @giomasce for code

**Comment by RCheesley** [comment]
@all-contributors please add @RaphaelWoude for userTesting

**Comment by RCheesley** [comment]
@all-contributors please add @mabumusa1 for review

**Pull request merged**
