### PR TITLE
[UI] Interactive filters for tables

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

Visual UI for quick filters.

image
image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Contacts > Create some > Open the filters and play with each
3. Repeat for other resources if you want

### CODE REVIEW

**Review by LordRembo — APPROVED** [review]
Just looking at it as an average user, I'm all for improved visibility in interactions. The code looks fine too.

**Comment by escopecz** [comment]
@andersonjeccel there are some conflicts

**Comment by andersonjeccel** [comment]
@escopecz The PR [UI] Remove search help from list toolbar (https://github.com/mautic/mautic/pull/13950) is a dependency of this one as we needed space to place the visual filters...

**Comment by andersonjeccel** [comment]
@escopecz The PR [UI] Remove search help from list toolbar (https://github.com/mautic/mautic/pull/13950) is a dependency of this one as we needed space to place the ui filters...

Would you feel OK to accept the search help icon removal in favor of the visual stuff?
Weighting search help vs. some interactive filters seems to leave the last one as winner

**Comment by MojisolaaaO** [comment]
@andersonjeccel  I can only see the filters for Ownership. Please how do I see the other filters as shown in the description?

Contacts | Mautic 2024-11-20 19-21-07

**Comment by andersonjeccel** [comment]
Hi @MojisolaaaO, each page has their own specific filters, try looking at the filters available for Forms, Landing pages and Assets to see more :)

**Comment by jos0405** [comment]
Hey,
Nice addition. Seems, that I cannot save segment catgories for filter. After clicking on save the modal doesn't disappear.

Error in console:
VM152 dashboard:9 
       GET https://8080-andersonjeccel-mautic-xo15120ezfi.ws-eu116.gitpod.io/_wdt/828a0f?_=1732182223714&mauticUserLastActive=194&mauticLastNotificationId= 404 (Not Found)
       
       
image

**Comment by andersonjeccel** [comment]
@jos0405 fixed, thank you for reviewing!

**Comment by escopecz** [comment]
These flag filters do not replace the search help completely. These are just boolean filters. How would users know they can type `ids:123,124` to search for the 2 entities with specific IDs? There are more just for contacts:
Screenshot 2024-11-21 at 14 05 05

I mean we should probably discuss this on https://github.com/mautic/mautic/pull/13950 which has conflicts BTW. But I'm OK with merging the removal of the search help buttons if it will get more approvals than disapprovals. Right now it has 2 disapprovals and 1 approval.

I also suggested how to do it in my last comment but didn't get any reply.

**Comment by andersonjeccel** [comment]
@escopecz There are many many more for contacts :)

Users can open the search help to know that they can use more filters while select fields are not available for a visual interaction

I created an entire modal for this

image

in the screenshot, I'm showing all search commands available for contacts based on existing stuff on the search subscribers (do you remember helping me to implement this?). Compare to those that appear in your screenshot

this can be accessed by clicking on the help dropup at the bottom right corner of your screen

image

if you feel that it's not visible enough, I can bring the help items again to the top navbar

**Comment by jos0405** [comment]
Works well, thank you
image

**Review by jos0405 — DISMISSED** [review]
Tested in different areas, looks good, works well.

**Comment by andersonjeccel** [comment]
Considered code review from this PR (#14275) that also includes this one as dependency

**Review by kuzmany — DISMISSED** [review]
Just basic tests did, works for me. Good job

Small UI  in segments

image

**Comment by andersonjeccel** [comment]
@kuzmany There's an inline style being applied to the field HTML that I have no idea where it's coming from :/

**Comment by kuzmany** [comment]
> @kuzmany There's an inline style being applied to the field HTML that I have no idea where it's coming from :/

No problem, it can be fixed anytime.

**Pull request merged**
