### PR TITLE
Allow tracking pixel to be freely placed in email

### PR DESCRIPTION
**Pull request by AndrassGray**
| Q  | A
| --- | ---
| Bug fix? | 
| Enhancement? |  X
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/323
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

#### Description:
We see more and more MUAs doing lazy image loading to enhance the user experience, both on mobile and on desktop. This could lead to the tracking pixel not firing because the recipient didn't scroll to the end of the message.

This PR proposes using a {tracking_pixel} token to be used anywhere in the message body, preferably above the fold, which will get replaced by the correct tracking pixel image. That way, it fires early to catch the email-open.

Caution : This pixel should be loaded as early as possible, but not before the preheader text.

### CODE REVIEW

**Comment by AndrassGray** [comment]
Just sayin' : The {tracking_pixel} token was always available, but only for the pixel URL. So if anybody wanted to use it, s/he could simply use  in the raw email. This would lead to the the tracking pixel firing twice for each open, though.

**Review by kuzmany — DISMISSED** [review]
👍 

Make sense. 
Thanks

**Review by kuzmany — APPROVED** [review]
Token works too.
Approved

**Comment by RCheesley** [comment]
@AndrassGray can you please add some clear testing instructions? I'd be happy to test but I don't know exactly what I'm looking for pre/post patch.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Given the lack of feedback and the existing conflicts, I'm going to close this PR down. If anyone would like to pick this up in the future please create a new PR and reference this one in your description.

**Pull request closed without merging**
