### PR TITLE
Theme panel headers

### PR DESCRIPTION
**Pull request by GaberNeighbor**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | x
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description: Styling the layout of theme-selection panels so the buttons don't get pushed beneath their container

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create/upload a theme with a long name
2. Go to the edit view of the email/page builder
3. Observe the panel buttons - buttons get pushed down

#### Steps to test this PR:
1. Create/upload a theme with a long name
2. Go to the edit view of the email/page builder
3. Observe the panel buttons - buttons remain in place

### CODE REVIEW

**Comment by GaberNeighbor** [comment]
Demonstration below:
[theme-panel-update.mov.zip](https://github.com/mautic/mautic/files/1682802/theme-panel-update.mov.zip)

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Label: UI

**Comment by escopecz** [comment]
It somehow did not work for me. All I had to do to see the problem was to make the view port a little smaller:
edit page with a form mautic

**Comment by npracht** [comment]
Hi @GaberNeighbor any chance you have a look quick before closing 2.14.0 ?

**Comment by mleffler** [comment]
@GaberNeighbor Hi - can you look at the conflicts please?

**Comment by mleffler** [comment]
I reached out to Gabe, and he will not have time to do this work in the near future.  So, I recommend we stop including it in releases unless somebody wants to take over and resolve the conflicts

**Comment by moskoweb** [comment]
Hello, it's more practical, just put the ```.ellipsis``` class in the ```<h3>``` tag of the theme panel component.

**Comment by moskoweb** [comment]
Another situation, is to create a pattern for the size of the themes thumbnails.

**Comment by dbhurley** [comment]
Closing this - if someone else wishes to fix it they can re-open.

**Comment by moskoweb** [comment]
A simpler and more practical way to fix the line break.

**Pull request closed without merging**
