### PR TITLE
Elfinder enabled sanitizier plugin

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.3
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
This plugin enabled sanitizier plugin to remove some characters from filename after upload.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Upload image with empty spaces in file name (`test test.png`)
3. After PR should be sanitize to `test-test.png`

### CODE REVIEW

**Review by npracht — DISMISSED** [review]
awesome 👍🏽 
Capture d’écran 2021-03-15 à 10 27 25

Capture d’écran 2021-03-15 à 10 27 05

**Comment by tejasync** [comment]
@kuzmany Could you please give more details about the steps to test w.r.t where to upload the images with file name having empty spaces and where the file is visible to verify the name sanitation?

**Comment by kuzmany** [comment]
@ts-navghane 

what is not clear?

2. Upload image with empty spaces in file name (`test test.png`)
3. After PR should be sanitize to `test-test.png`


PR replace `test test.png` to `test-test.png`

**Comment by RCheesley** [comment]
@kuzmany please can you rebase this onto Features if you want it to make its way into the 4.0 release? Currently it seems to be based on the 3.3 branch.

Thanks! 🚀

**Comment by kuzmany** [comment]
@RCheesley  3.3 branch  is not merged to features yet?

**Comment by RCheesley** [comment]
Thanks for changing the base - looks like there are some conflicts to address!

**Comment by RCheesley** [comment]
@kuzmany still some conflicts to address here - cannot merge until this is addressed

**Comment by kuzmany** [comment]
@RCheesley conflicts resolved

**Pull request merged**
