### PR TITLE
Tracked video bugfix

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/206
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/4431
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Fix for this issue https://github.com/mautic/mautic/issues/4431
Added new video attr data-mtc="1" make video trackable without gated video features. Also prevent don't convert other videos without this attr.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Add video tag to your Mautic tracking page
2.  Video is transform with mediaelements library

#### Steps to test this PR:
1. Add video tag to your Mautic tracking page
2. Add attr data-mtc="1"
3. See If video is transform with medialements library. 
That means mautic will track video hits for contacts

### CODE REVIEW

**Comment by luizeof** [comment]
@kuzmany hello friend ... can web filter contacts for watched some videos on segments?

**Comment by kuzmany** [comment]
@luizeof particaly https://github.com/mautic/mautic/pull/4441

**Comment by kuzmany** [comment]
@escopecz could you add this bugfix to 2.9.1. 
It's really annoying bug, cause transform all videos on website

**Comment by escopecz** [comment]
I'm not quite sure there will be 2.9.1 or there will be 2.10.0. But sure. It won't do any harm.

**Comment by alanhartless** [comment]
Closed in favor of #4480

**Comment by luizeof** [comment]
@kuzmany  @dongilbert data-mautic-video="true" from #4480 and data-mtc="1" are the same?

**Comment by kuzmany** [comment]
@luizeof just data-mautic-video="true"

**Comment by shulard** [comment]
Hello @kuzmany,

What's the behaviour when user haven't installed 2.9.1 yet ?

I've just published a new WP plugin release which includes your changes : https://github.com/mautic/mautic-wordpress/releases/tag/v2.2.0

**Pull request closed without merging**
