### PR TITLE
Show labels of select, multiselect and boolean custom lead fields

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
We noticed lead profile display values of select, multiselect or boolean fields. But custom fields have labels to values and these labels are more human friendly. This PR normalize these values and allow display in friendly format. 

Now

image

Expected

image

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create custom field select, multiselect and boolean (all with different labels / values)
2. Create contact and set these fields
3. Go to contact profile and see values there

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat all steps
3. See if works properly

### CODE REVIEW

**Comment by kuzmany** [comment]
@florentpetitjean can you check now?

**Comment by kuzmany** [comment]
@florentpetitjean rewrited. 
Please re-test all again.
Thanks

**Comment by kuzmany** [comment]
@florentpetitjean any details, error log...?

**Comment by florentpetitjean** [comment]
we got a 500 error with API tester, no more infos for now.

**Comment by florentpetitjean** [comment]
Here is the log ! 

[2019-12-10 15:53:43] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Mautic\LeadBundle\Helper\CustomFieldValueHelper::normalizeValue() must be of the type array, integer given, called in /Users/audrey/Sites/Automation_dev/app/bundles/LeadBundle/Helper/CustomFieldValueHelper.php on line 38" at /Users/audrey/Sites/Automation_dev/app/bundles/LeadBundle/Helper/CustomFieldValueHelper.php line 57 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Mautic\\LeadBundle\\Helper\\CustomFieldValueHelper::normalizeValue() must be of the type array, integer given, called in /Users/audrey/Sites/Automation_dev/app/bundles/LeadBundle/Helper/CustomFieldValueHelper.php on line 38 at /Users/audrey/Sites/Automation_dev/app/bundles/LeadBundle/Helper/CustomFieldValueHelper.php:57)"} []

**Comment by kuzmany** [comment]
@florentpetitjean What api call you test? Create or edit?  I am working on it

**Comment by florentpetitjean** [comment]
Just a Get contact send a 500 error

**Comment by kuzmany** [comment]
@florentpetitjean can you re-test now?

**Comment by Noa83** [comment]
API Tested, it works perfectly.

**Comment by kuzmany** [comment]
@npracht we need know first, If M3 will go to stable branch. 
Then we can check it then based on stable branch. 
Or If we should rebase it for M3 branch.

**Comment by dennisameling** [comment]
@kuzmany the tests are failing in Travis. Could you please rebase your branch from the `mautic/staging` branch to check if they still fail? Thanks! :)

**Comment by kuzmany** [comment]
@dennisameling I'll take look tomorrow

**Comment by kuzmany** [comment]
@dennisameling fixed

**Comment by dennisameling** [comment]
Merging as @Noa83 has confirmed that the API is working properly. Tests also passing now. 👍

**Pull request merged**
