### PR TITLE
Print recent activity logs in code of HTML

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:

Many times we need check what was changed in entities.  By default Mautic display recent activity timeline in email, campaigns, segments. But for more details we need go to audit logs and process it manually.
This PR added this output to HTML code as comment.

This should save everybody a tons of time.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Go to emails, create and edit it few times (title, subject, from...)
3. Open detail of email, show source and find: **recent activity logs**. You should find printed logs in comments
image

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10295"></a>

### CODE REVIEW

**Comment by npracht** [comment]
Hi @kuzmany I don't understand where I can find the place where i need to click to see the logs ?
Capture d’écran 2021-08-20 à 10 37 03

**Comment by kuzmany** [comment]
@npracht It's not related for end-users. It's  related for power users - you need view source of page and you need find it code - it's commented code.

**Review by npracht — DISMISSED** [review]
Okay now I see. I didn't understand it is in source code of the page.
Capture d’écran 2021-08-20 à 17 07 45

**Review by luguenth — APPROVED** [review]
Tested it and works like promised
image

**Comment by jos0405** [comment]
Tested, works like a charm.

`

<!-- recent activity logs
--
  | [
  | {
  | "userName": "Admin Mautic",
  | "userId": "1",
  | "bundle": "email",
  | "object": "email",
  | "objectId": "1",
  | "action": "update",
  | "details": {
  | "isPublished": [
  | "1",
  | ""
  | ],
  | "dateModified": [
  | "",
  | "2021-11-09T13:22:03+00:00"
  | ]
  | },
  | "dateAdded": false,
  | "ipAddress": "84.199.184.242"
  | },
  | {
  | "userName": "Admin Mautic",
  | "userId": "1",
  | "bundle": "email",

`

**Review by jos0405 — APPROVED** [review]

**Pull request merged**
