### PR TITLE
Fix inability to update Mautic lead fields if the value that is coming from the integration is empty.

### PR DESCRIPTION
**Pull request by anton-vlasenko**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Automated tests included? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

When a sales user updates a checkbox in the CRM (Salesforce) to go from checked --> unchecked, a text field in Mautic does not update from 1 to 0.

If the sales user checks an unchecked box, the Mautic field updates to a value of 1.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:

1. Create a checkbox field in Salesforce
2. Create a text field in Mautic
3. Set up the Salesforce plugin and map those two fields together, pushing from Salesforce to Mautic
4. Update the checkbox field in Salesforce to checked, then to unchecked.
5. A checked box passes a value of 1, but an unchecked box does not pass any value.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create a checkbox field in Salesforce
3. Create a text field in Mautic
4. Set up the Salesforce plugin and map those two fields together, pushing from Salesforce to Mautic
5. Update the checkbox field in Salesforce to checked, then to unchecked.
6. A checked box should pass a value of 1 to Mautic, an unchecked box should pass a value of 0.

### CODE REVIEW

**Comment by RCheesley** [comment]
Bumping to 3.2 due to unresolved conflicts.

**Comment by anton-vlasenko** [comment]
Conflicts have been resolved.

**Comment by RCheesley** [comment]
@cla-bot check

**Review by mabumusa1 — DISMISSED** [review]
The code looks logical and handles the reported issue, I think this code will solve the issue

**Comment by mabumusa1** [comment]
@RCheesley this is ready I think

**Comment by RCheesley** [comment]
As this [decreases coverage](https://github.com/mautic/mautic/pull/7753#issuecomment-678484744) it will need to be bumped to 3.1.2. @mautic/acquia-po another one to be addressed by **18th October**

**Comment by npracht** [comment]
@anton-vlasenko i don't understand the logic. Why a checkbox from CRM should be mapped to a text field in Mautic ? It should be mapped to a boolean field, shouldn't it ?

**Comment by anton-vlasenko** [comment]
@npracht We had a customer who mapped a checkbox Salesforce field to a custom Mautic text field.
Some customers need that.
PHP converts `false` boolean values to empty strings `''`.
This PR addresses that issue. Boolean values should not be converted to string values when we sync data back to Mautic.

**Review by kuzmany — DISMISSED** [review]
Looks good 👍

**Comment by RCheesley** [comment]
Changed to 3.3 base for merging in the 3.3.2 release - may need to be rebased but this is on a protected branch so fingers crossed it is all good!

**Comment by kuzmany** [comment]
@RCheesley  unit tests are included and looks like cover every situation. I removed need unit tests label

**Comment by RCheesley** [comment]
@kuzmany per the [code coverage report ](https://github.com/mautic/mautic/pull/7753#issuecomment-678484744)this will decrease coverage, hence why the check is failing. That should be addressed before we merge the PR.

**Pull request merged**
