### PR TITLE
Salesforce campaign segments

### PR DESCRIPTION
**Pull request by mqueme**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Related user documentation PR URL | pending
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR puts Salesforce campaign members into a segment. First it syncs campaign members into  mautic, and resulting campaign members are pulled as Mautic contacts, these mautic contacts are then inputted in a segment, needs https://github.com/mautic/mautic/pull/3674

#### Steps to test this PR:
1. Apply this PR
1.5 Salesforce plugin must be configured, and fields matched
2. Create a segment with an Integration Campaign filter
3. Select the campaign you want to use as your segment filter
4. Update you segment
5. Check that Contacts in Mautic are put into this segment, and they coincide with campaign members in Salesforce

### CODE REVIEW

**Comment by escopecz** [comment]
I got
```
Rebuilding contacts for segment 13
PHP Warning:  Missing argument 2 for MauticPlugin\MauticCrmBundle\Integration\SalesforceIntegration::getCampaignMembers(), called in plugins/MauticCrmBundle/EventListener/LeadListSubscriber.php on line 104 and defined in plugins/MauticCrmBundle/Integration/SalesforceIntegration.php on line 1243
PHP Notice:  Undefined variable: leadList in plugins/MauticCrmBundle/Integration/SalesforceIntegration.php on line 1284
PHP Warning:  array_keys() expects parameter 1 to be array, null given in plugins/MauticCrmBundle/Integration/SalesforceIntegration.php on line 1284
PHP Warning:  implode(): Invalid arguments passed in plugins/MauticCrmBundle/Integration/SalesforceIntegration.php on line 1284
PHP Notice:  Array to string conversion in plugins/MauticCrmBundle/Integration/SalesforceIntegration.php on line 1288
PHP Notice:  Undefined variable: leadList in plugins/MauticCrmBundle/Integration/SalesforceIntegration.php on line 1307
PHP Warning:  array_diff_key(): Argument #1 is not an array in plugins/MauticCrmBundle/Integration/SalesforceIntegration.php on line 1307
PHP Notice:  Array to string conversion in plugins/MauticCrmBundle/Integration/SalesforceIntegration.php on line 1325
PHP Notice:  Undefined variable: mixedFields in plugins/MauticCrmBundle/Integration/SalesforceIntegration.php on line 1328
PHP Warning:  array_filter() expects parameter 1 to be array, null given in plugins/MauticCrmBundle/Integration/SalesforceIntegration.php on line 1366
PHP Warning:  Invalid argument supplied for foreach() in plugins/MauticCrmBundle/Integration/SalesforceIntegration.php on line 1368
PHP Notice:  Undefined variable: persistEntities in plugins/MauticCrmBundle/Integration/SalesforceIntegration.php on line 1355
```
When executing the segments:update command

**Comment by escopecz** [comment]
I retested with latest changes. It freezes on rebuilding the segment I tested it with. It's running for 10 minutes now with no output, no error. Any advice?

**Comment by escopecz** [comment]
Ok, it finishes eventually, but it takes almost 20 minutes to add one contact to the segment
```
$ date "+%H:%M:%S" && app/console mautic:segments:update -i 13 && date "+%H:%M:%S"
14:54:02
Rebuilding contacts for segment 13
1 total contact(s) to be added in batches of 300
 1/1 [============================] 100%
0 total contact(s) to be removed in batches of 300
1 contact(s) affected
15:13:41
```
I don't think we can merge this when it takes so long.

**Comment by matishaladiwala** [comment]
The list of campaigns in SF does not show up in the filter picklist

**Comment by matishaladiwala** [comment]
Work well for me now. The segment was populated as soon as the cron was run! Approved

**Comment by escopecz** [comment]
I re-run again to make sure it takes that long even today:
```
21:23:05
Rebuilding contacts for segment 13
2 total contact(s) to be added in batches of 300
 2/2 [============================] 100%
0 total contact(s) to be removed in batches of 300
2 contact(s) affected
21:31:05
```

**Comment by escopecz** [comment]
As discussed in the private chat, the execution got a lot faster with this DB index:
```
ALTER TABLE `integration_entity` 
ADD INDEX `internal_integration_entity` (`internal_entity_id`, `integration_entity_id`, `internal_entity`, `integration_entity`)
```
```
$ date "+%H:%M:%S" && app/console mautic:segments:update -i 13 && date "+%H:%M:%S"
14:18:43
Rebuilding contacts for segment 13
0 total contact(s) to be added in batches of 300
0 total contact(s) to be removed in batches of 300
0 contact(s) affected
14:18:45
```

**Pull request merged**
