### PR TITLE
Grid Campaign and Flowchat Change

### PR DESCRIPTION
**Pull request by moskoweb**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/5863
| BC breaks? | 
| Deprecations? | https://github.com/mautic/mautic/pull/6072

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
New pull request reference: https://github.com/mautic/mautic/pull/6072

I made some improvements in CSS, adjusting so that it can be easily adapted, as well as putting the new action icons that were created in the latest versions.

Adjusting the preview to make it easier to display.

#### Steps to test this PR:
1. Clear cache from Mautic.
2. Regenerate assets by console.
3. Open Campaign Builder.

#### List deprecations along with the new alternative:
1. Grid format, now is image Base64.
2. Icons update from actions.

### CODE REVIEW

**Comment by moskoweb** [comment]
Preview: https://ibb.co/fe3Ujp

**Comment by kuzmany** [comment]
Nice.
Tested here https://mautibox.com/6584/s/campaigns/view/1

Labels in preview overflowed

image

**Comment by moskoweb** [comment]
New commit with correction.

**Review by kuzmany — DISMISSED** [review]
Tested on Mautibox
https://mautibox.com/6584/s/campaigns/view/1

Works as describes. I approve it. But UX changes should be approved by Mautic core team.

**Comment by moskoweb** [comment]
@kuzmany any suggestion of why you are giving this error in Travis?

**Comment by kuzmany** [comment]
1, remove space on begining $eventType https://travis-ci.org/mautic/mautic/jobs/436350194#L711
2, remove unnecessary space from here https://travis-ci.org/mautic/mautic/jobs/436350194#L716
`'mautic.campaign.'.$event['type']`

**Comment by moskoweb** [comment]
Seriously it was the spaces only?!

I thought it would be pretty rough only that be all. Gratitude.

**Comment by kuzmany** [comment]
@moskoweb check that links, travis always say errors very detailed

**Comment by Woeler** [comment]
Would like to hear what @alanhartless and @dbhurley have to say about this. Pretty big UX change. However I like it though.

**Comment by Woeler** [comment]
@moskoweb How does this work with existing campaigns? What happens to them if we include this in 2.15 and someone with like 10 campaigns updates to v2.15 from 2.14.2?

**Comment by moskoweb** [comment]
In the case of the campaigns already created, the positions of the node are maintained, and because of this, some campaigns may be messed up due to the new dimensions of each node.

**Comment by Woeler** [comment]
That would be a serious breaking change. We need a migration for this.

**Comment by heathdutton** [comment]
My UX designer's recommendations:
* The squares are not wide enough. The names of most of our events would not fit in a small square, So a rectangular shape would be better. Try to be closer to the existing event width to not be such a jarring change.
* The colored circle behind the icon has no purpose, remove it... it just adds clutter.
* The icons should be smaller, try to match the icons of the main navigation in size. Think about those who have campaigns that would need to be "re-arranged" to fit these all on screen. If the box heigh doesn't change drastically then they don't have to re-arrange their campaigns as much.
* The square arrow shapes (dropping the sine-like shape) is a nice idea visually, but in practice that will *not* work for complex campaigns without drastic re-arrangement, as this has a habit of burying the intended destinations.
* The arrows aren't really helping, I'd remove them all.
* This design is very "line heavy". Make the event boxes inverted (background color instead of outlines).

There are more... but this is initial impressions.

**Comment by dongilbert** [comment]
@moskoweb I wonder if it would be possible / better to recalculate the campaign layout on builder load?

**Comment by moskoweb** [comment]
> @moskoweb I wonder if it would be possible / better to recalculate the campaign layout on builder load?

I have given a study on the system used in the constructor because it has an auto-organization feature, and I think it would be great to implement it.

**Comment by MauriceW2** [comment]
I edited the 3 files manually, deleted the Mautic cache, Web browser cache and Coudflare cache.
But no difference. I don't see the change.

What I do see is that the file CampaignBundle/Assets/css/campaign.css is never loaded. How can that be?

**Comment by Woeler** [comment]
@MauriceW2 Because assets are compiled and minified for releases. These files are only touched in dev environments.

**Comment by moskoweb** [comment]
Will it be included in the next version?

**Comment by virgilwashere** [comment]
@moskoweb would it be possible to have boxes stretch wider based on content size...to a max of double current?

Also, have you looked at the effort of changing this PR to a Plugin?

**Comment by moskoweb** [comment]
> @moskoweb would it be possible to have boxes stretch wider based on content size...to a max of double current?
> 
> Also, have you looked at the effort of changing this PR to a Plugin?

I'm sorry, but I didn't understand your first question, if you refer to the connection limit, this is just a visual, so the limit is what Mautic as a whole would have.

About becoming a plugin, I came to think of developing, but I think it would be something to help everyone, just as the biggest Marketing Automation systems have grids and are more organized than a bunch of dropped connections on a white background.

**Comment by virgilwashere** [comment]
> @moskoweb would it be possible to have boxes stretch wider based on content size...to a max of double current?

image

The 2nd level red boxes are labelled: `Check for Honeypot field` and 🍯 `Honeypot`. 
 Obviously the full label doesn't fit in the 4 x 3 box.

`Check for valid email address` 😿 

The same for the 3rd layer of purple boxes.

A box that was 8x3 would be great!

image

**Comment by moskoweb** [comment]
> > @moskoweb would it be possible to have boxes stretch wider based on content size...to a max of double current?
> 
> image
> 
> The 2nd level red boxes are labelled: `Check for Honeypot field` and 🍯 `Honeypot`.
> Obviously the full label doesn't fit in the 4 x 3 box.
> 
> `Check for valid email address` 😿
> 
> The same for the 3rd layer of purple boxes.
> 
> A box that was 8x3 would be great!
> 
> image

Now I understand your point, but if you leave it that way, it gets very big, and you fall back on the problem you already have in the current system, getting complicated to understand quickly, if you hover over each name, will appear Full description of it.

In the current mode, this cut already made, did not change much in the width of the block, but in the way it displayed the information in a fast way.

**Comment by moskoweb** [comment]
@alanhartless and @dbhurley will it be approved for version 3?

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by npracht** [comment]
I think we should target 3.1.0 for that great UX enhancement ! @moskoweb

**Comment by moskoweb** [comment]
> I think we should target 3.1.0 for that great UX enhancement ! @moskoweb

I need to change to the base of 3.x, or in this case it has already changed to 3.1.0.

**Comment by npracht** [comment]
Hi ! You need to change the branch against you PRed. So you need to rebase from 3.x

**Review by RCheesley — CHANGES_REQUESTED** [review]
I am not able to see this in dev mode, I applied the PR, cleared cache and rebuilt the assets but I don't see any difference in the campaign builder. Just in case anyone else comes across that issue!

When I switch to production it works fine!

Thanks for this great PR @moskoweb and sorry we have taken _SO LONG_ to get around to properly reviewing and considering for including in a release. We really appreciate your patience!

I have the same concerns as [raised earlier in the discussions](https://github.com/mautic/mautic/pull/6584#issuecomment-543999812), it is a poor user experience to not be able to see the name of the item in the campaign and I would find this very frustrating as a user of Mautic. I'd rather we have a small icon to the left and the text to the right in a freely expanding fashion than what we have here. Excuse the drawing but hopefully this makes sense what I mean:

screenshot-local mautic3-2020 08 14-21_01_25

Also, if you are working with large campaigns with hundreds of these, it will become extremely cumbersome to have big chunky blocks - I do see the value for some users, but the builder is already pretty challenging when building out big campaigns and this would in my experience make it quite difficult for the marketer to move around very large campaigns.

So, I would want that to be addressed (always being able to see the full title, and using the minimum space) before we considered merging this PR.

Going forward, because I do think this is a really nice improvement to our UI, here are some thoughts from the user perspective that might be nice as an enhancement to what you've got here:

* Having some kind of setting whereby you can turn on/off the grid - maybe under settings > campaign settings and/or under the user account settings
* Giving the option to choose to have horizontal or vertical layout of the blocks - I think power users would prefer a minimal approach but I can see that some might also prefer the big, chunky blocks. So it might be nice to offer the choice if that were possible.

Thanks again for your work on this and for your patience!

**Comment by RCheesley** [comment]
Bumping this to 3.2 to give time for the changes to be made and thorough testing.

**Comment by moskoweb** [comment]
> I am not able to see this in dev mode, I applied the PR, cleared cache and rebuilt the assets but I don't see any difference in the campaign builder. Just in case anyone else comes across that issue!
> 
> When I switch to production it works fine!
> 
> Thanks for this great PR @moskoweb and sorry we have taken _SO LONG_ to get around to properly reviewing and considering for including in a release. We really appreciate your patience!
> 
> I have the same concerns as [raised earlier in the discussions](https://github.com/mautic/mautic/pull/6584#issuecomment-543999812), it is a poor user experience to not be able to see the name of the item in the campaign and I would find this very frustrating as a user of Mautic. I'd rather we have a small icon to the left and the text to the right in a freely expanding fashion than what we have here. Excuse the drawing but hopefully this makes sense what I mean:
> 
> screenshot-local mautic3-2020 08 14-21_01_25
> 
> Also, if you are working with large campaigns with hundreds of these, it will become extremely cumbersome to have big chunky blocks - I do see the value for some users, but the builder is already pretty challenging when building out big campaigns and this would in my experience make it quite difficult for the marketer to move around very large campaigns.
> 
> So, I would want that to be addressed (always being able to see the full title, and using the minimum space) before we considered merging this PR.
> 
> Going forward, because I do think this is a really nice improvement to our UI, here are some thoughts from the user perspective that might be nice as an enhancement to what you've got here:
> 
> * Having some kind of setting whereby you can turn on/off the grid - maybe under settings > campaign settings and/or under the user account settings
> * Giving the option to choose to have horizontal or vertical layout of the blocks - I think power users would prefer a minimal approach but I can see that some might also prefer the big, chunky blocks. So it might be nice to offer the choice if that were possible.
> 
> Thanks again for your work on this and for your patience!

Hello @RCheesley, your considerations are very nice, and the part of having the option for how you want is cool, but as for the look you want, basically you are saying you want it the way it is already, so this pull doesn't really make any sense for you, if the current model is good for your taste.

I do not think that the fact that it is square or rectangular is really something that affects the construction of campaigns, I have huge campaigns using this design and it does not hinder me, on the contrary, it helps me to identify more easily what is the action, condition or decision only by color and icon.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@moskoweb thanks for the feedback. I invite @mautic/product-team to review and provide their thoughts on this also so that we can get wider feedback and opinions.  Can you also take a look at the message regarding your git commit email so we can check the contributors agreement is signed?

**Comment by RCheesley** [comment]
@mautic/acquia-po you might also want to have some input into this PR.

**Comment by RCheesley** [comment]
@cla-bot check

**Review by dennisameling — COMMENTED** [review]
Very nice improvement to the UI! Thanks @moskoweb 🚀  I read through all the comments and agree that while this may be great for smaller campaigns with short action names, it could be cumbersome for more complex campaigns and/or actions with long names.

In order to get this merged ASAP, I indeed also would like to suggest to launch this behind a feature toggle (default off), and turn it on by default in Mautic 4. That way we can have people play/experiment with it and improve over time by processing their feedback. Think that for such a crucial element of the UI, this approach makes sense.

To make this a feature toggle, maybe this could be an approach:
- Replace `#CampaignCanvas` in the CSS with a custom class name, like `.campaign-canvas-grid`.
- Add a config parameter in Mautic called `activate_canvas_grid` or similar (boolean), default false
- In the HTML, get the config parameter with `$this->coreParametersHelper->get('activate_canvas_grid')`. Would be in `app/bundles/CampaignBundle/Views/Campaign/builder.html.php`, example:
```HTML
<div id="CampaignCanvas">
```
would become something like (I haven't tested this!)
```HTML
<div id="CampaignCanvas" <?php if (true === $this->coreParametersHelper->get('activate_canvas_grid')) echo 'class="campaign-canvas-grid"'; ?>>
```

Please let us know if you need help with this @moskoweb 😄 

image

**Comment by moskoweb** [comment]
> Very nice improvement to the UI! Thanks @moskoweb 🚀 I read through all the comments and agree that while this may be great for smaller campaigns with short action names, it could be cumbersome for more complex campaigns and/or actions with long names.
> 
> In order to get this merged ASAP, I indeed also would like to suggest to launch this behind a feature toggle (default off), and turn it on by default in Mautic 4. That way we can have people play/experiment with it and improve over time by processing their feedback. Think that for such a crucial element of the UI, this approach makes sense.
> 
> To make this a feature toggle, maybe this could be an approach:
> 
> * Replace `#CampaignCanvas` in the CSS with a custom class name, like `.campaign-canvas-grid`.
> * Add a config parameter in Mautic called `activate_canvas_grid` or similar (boolean), default false
> * In the HTML, get the config parameter with `$this->coreParametersHelper->get('activate_canvas_grid')`. Would be in `app/bundles/CampaignBundle/Views/Campaign/builder.html.php`, example:
> 
> ```
> <div id="CampaignCanvas">
> ```
> 
> would become something like (I haven't tested this!)
> 
> ```
> <div id="CampaignCanvas" <?php if (true === $this->coreParametersHelper->get('activate_canvas_grid')) echo 'class="campaign-canvas-grid"'; ?>>
> ```
> 
> Please let us know if you need help with this @moskoweb 😄
> 
> image

Glad you liked it and see, like me, being a big jump and improvement for Mautic. I think the idea of ​​whether or not to activate it is cool, I will be looking to develop this step, but when creating it, I aimed that most of the great and good Email Marketing systems have a simple and elegant visual editor, and that's why I wanted to bring this to the Mautic.

**Comment by RCheesley** [comment]
@moskoweb what are your thoughts on making the changes that are suggested to make this an optional feature that could be enabled? It would be great if we could aim to get this merged in the 3.3 release, which would mean we need to have this all wrapped up and tested no later than mid-February.

Do you think that's feasible? Would you like any help?

**Comment by RCheesley** [comment]
@moskoweb as we have not heard from you regarding the requested changes I am closing this PR. If you would like to pick it up again in the future just ping us and we can look to re-open.

**Pull request closed without merging**
