### PR TITLE
Index optimization

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**

1) This PR adds table indexes to improve Mautic responsiveness.  
2) Dynamically creates an index from the unique identifier fields which are used to search leads 
3) Optimized some of the queries used to generate dashboard stats

**Testing**
Apply the PR, clear Symfony's cache, run the `doctrine:schema:update` command which should setup the indexes.  Test browsing the site.  The big things to test are 

a) the dashboard stats look right
b) create a new lead field that is a unique identifier
c) run through the installer on a clean cache clear/rename config/local.php or a clean clone

Users with large data sets (email stats, dashboard stats, etc) should see a huge improvement.

### CODE REVIEW

**Comment by dbhurley** [comment]
wow, this works great! +1 all the way.

**Comment by escopecz** [comment]
Seems to work for prod, but in dev while on dashboard I get 
```
500 Internal Server Error - Parameter "slug" for route "mautic_page_public" must match "(?!(_(profiler|wdt)|css|images|js|favicon.ico|apps/bundles/|plugins/|addons/)).+" ("" given) to generate a corresponding URL. 
```
```
app/cache/dev/classes.php (line #1280):
app/cache/dev/appDevUrlGenerator.php (line #197): at Symfony\Component\Routing\Generator\UrlGenerator -> doGenerate ( array('slug'), array('_controller' => 'Mautic\PageBundle\Controller\PublicController::indexAction'), array('slug' => '(?!(_(profiler|wdt)|css|images|js|favicon.ico|apps/bundles/|plugins/|addons/)).+'), array(array('variable', '/', '(?!(_(profiler|wdt)|css|images|js|favicon.ico|apps/bundles/|plugins/|addons/)).+', 'slug')), array('slug' => ''), 'mautic_page_public', true, array(), array() )
app/cache/dev/classes.php (line #1643): at appDevUrlGenerator -> generate ( 'mautic_page_public', array('slug' => ''), true )
app/bundles/CoreBundle/Model/CommonModel.php (line #189): at Symfony\Component\Routing\Router -> generate ( 'mautic_page_public', array('slug' => ''), true )
app/bundles/PageBundle/Model/PageModel.php (line #291): at Mautic\CoreBundle\Model\CommonModel -> buildUrl ( 'mautic_page_public', array('slug' => ''), true, array() )
app/bundles/DashboardBundle/Controller/DefaultController.php (line #59): at Mautic\PageBundle\Model\PageModel -> generateUrl ( object(Page) )
at Mautic\DashboardBundle\Controller\DefaultController -> indexAction ( )
app/bootstrap.php.cache (line #3051): at call_user_func_array ( array(object(DefaultController), 'indexAction'), array() )
app/bootstrap.php.cache (line #3013): at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '1' )
app/bootstrap.php.cache (line #3162): at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '1', true )
app/bootstrap.php.cache (line #2403): at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel -> handle ( object(Request), '1', true )
app/AppKernel.php (line #110): at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), '1', true )
index_dev.php (line #56): at AppKernel -> handle ( object(Request) )
````

**Comment by drmmr763** [comment]
I get the same issue as @escopecz in dev mode. I suspect the issue exists in prod mode but its getting logged instead of breaking the page.

**Comment by alanhartless** [comment]
@escopecz @drmmr763 fixed.

**Comment by dbhurley** [comment]
Tested in dev mode, no error. +1

**Comment by drmmr763** [comment]
Worked for me!
+1

**Pull request merged**
