### PR TITLE
Salesforce contacts dnc sync fix

### PR DESCRIPTION
**Pull request by dadarya0**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | Y
| New feature/enhancement? (use the a.x branch)      | N
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | Y 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
We need to synchronize DNC record for new Lead/Contacts downloaded from SalesForce. Currently the plugin relied solely on DNC history, which is not synchronized unless we push something and nor it is synchronized if contact has been created opted-out.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Setting up SF plugin
3. Selecting “Use latest updated Do Not Contact record” under “Features” in Salesforce plugin
4. Pulling contacts from SF who are labeled as DNC out of the box into Mautic.
5. Verify downloaded is DNCed

One more testing is required in this PR :-

1. Create a new Lead in Salesforce and run the command php app/console mautic:integration:synccontacts -i Salesforce and note the contact exists in Mautic
2. Delete the contact in Mautic. Update a mapped field for the Lead in SF (i.e. last name) then delete them in SF.
3. Run the command php app/console mautic:integration:synccontacts -i Salesforce again
4. The contact should not be recreated in Mautic

### CODE REVIEW

**Review by rohitp19 — APPROVED** [review]
LGTM. Thanks!

**Review by rohitpavaskar — DISMISSED** [review]

**Comment by dadarya0** [comment]
@rohitp19 could you please review 2 commits (https://github.com/mautic/mautic/pull/13411/commits/e885fe16b0735b3b286cbf67c08815071fa400ea and https://github.com/mautic/mautic/pull/13411/commits/7c9645ca4cbe642024c47960e75db49aabe44876) As these are fixing an issue in which deleted contact was recreated again because of sync.

**Review by rohitpavaskar — DISMISSED** [review]

**Comment by dadarya0** [comment]
@rohitp19 please review https://github.com/mautic/mautic/pull/13411/commits/2932d8ec3ca9ec9493e2afd90a18739bd7c5b951 and https://github.com/mautic/mautic/pull/13411/commits/00ff5bfdcdbe7feb3a59bba2ba2e21ff7c31fd24 again

**Comment by escopecz** [comment]
@dadarya0 there is a conflict. Please look into it.

**Review by escopecz — APPROVED** [review]
I see no issue in the code. Since this cannot be tested due to https://github.com/mautic/mautic/issues/13467 let's get a second review to get this merged. 

cc @rohitp19

**Review by rohitp19 — APPROVED** [review]

**Review by rohitpavaskar — APPROVED** [review]

**Pull request merged**
