### PR TITLE
Ajaxify dashboard

### PR DESCRIPTION
**Pull request by hluchas**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Y
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR represents dashboard with all widgets loaded via AJAX

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Load and filter dashboard (use add widget/remove/edit/filter)

#### Steps to test this PR:
1. Same as reproduction steps

### CODE REVIEW

**Comment by mleffler** [comment]
This has been code reviewed and has had one test pass.

**Comment by alanhartless** [comment]
@hluchas we need to improve the UI on this before we can merge it.

**Comment by hluchas** [comment]
@alanhartless I forgot this PR, will take a look

**Comment by hluchas** [comment]
@alanhartless @escopecz I have fixes in this PR in cloud repo and I can move them to this PR or create next PR when this one will be merged.
https://github.com/mautic-inc/mautic-cloud/pull/470

**Comment by RCheesley** [comment]
@hluchas not sure if this is still relevant but it has some conflicts to be resolved if it is :)

**Comment by hluchas** [comment]
It is relevant. I'll fix this

**Comment by RCheesley** [comment]
Great, thanks @hluchas :)

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by hluchas** [comment]
new PR here https://github.com/mautic/mautic/pull/9386

**Pull request closed without merging**
