### PR TITLE
Fix Focus Stop engaging after a conversion for link

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/5956
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Fix Focus Stop engaging after a conversion for link

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create Focus with  Emphasize a link popup with enabled Stop engaging after a conversion? 
2.  Insert Focus and test.
3: After click on link, popup still show on page

#### Steps to test this PR:
1.  Repeat all steps.
2.  Focus stop show after click on link

### CODE REVIEW

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by escopecz** [comment]
It did not work for me I guess. Here is what I did:

1. Create a Focus item
2. Made sure "Stop engaging after a conversion?" is Yes
3. Content: `<a href="https://johnlinhart.com">john</a>`
4. Saved.
5. Tested the Focus item on a standalone HTML page in an incognito window.

When I click the link the page is opened in the popup modal window. That's probably not right, but that's not what this PR is about. When I refresh the HTML page the popup appears again. I clicked several more times, but no luck. The popup appears after every refresh.

**Comment by kuzmany** [comment]
@escopecz Did you choose Emphasize a link Focus Type during the create Focus?

**Comment by heathdutton** [comment]
The confusion is likely that you must create the content in "Basic" mode for this to work as designed. You can't create an html link and have it be treated the same way.

The code would never have worked right because there is no focus type called "click". So either way this is better. 👍 

screen shot 2018-09-04 at 3 38 45 pm

screen shot 2018-09-04 at 3 39 25 pm

**Pull request merged**
