### PR TITLE
Send report now

### PR DESCRIPTION
**Pull request by escopecz**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | https://github.com/mautic/mautic-documentation/pull/142
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | /
| BC breaks? | N
| Deprecations? | Y

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

~~⚠️ this PR depends on https://github.com/mautic/mautic/pull/8697/files#diff-bfa53625d4f7d4ad6aeef207808a2153R22 and that PR must be merged first.~~ DONE!

**Problem statement**
Some reports are getting slow to load. Some users just want to export the report. Therefore this feature will allow them to export the report on background (no waiting for page load required) and Mautic will send the report in CSV to the user.

This PR adds new unit to the report scheduler: **NOW**. It will send the report asap only once and then it turns off the scheduler.

The handling of too big CSV files has been changed as well. If the file is greater than 5MB (configurable file attachment limit) then the CSV file will be zipped. If the zip package is within the file attachment limit then it will be sent as the email attachment. If it's still too big it will move the zip file to more permanent location and the email will contain link to download it. The download link works only for logged in users.

If someone will try to download a compressed CSV report that had been deleted for whatever reason it will schedule the report to NOW again and send the user the email notification to his email address when the CSV report will be created.

The one-time report export and send can be configured 2 ways:

1. By scheduling the email:
Edit Report   Segment membership

2. By a button from the report list:
Reports   Mautic

The button is available only for non-scheduled reports as it would reset configuration for scheduled reports.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create a report.
3. Test both methods to send the report now.
4. Test that the scheduler is still working for other time units as before.
5. Try to mess with the new routes. Like schedule/download a report that does not exist or is scheduled already.
6. It would be nice if you could test sending big reports. Reports that have more than 5MB when exported to CSV. And even reports that have more than 5MB when zipped. Or use `report_export_max_filesize_in_bytes` config to set it to lower limit.

#### List deprecations along with the new alternative:
1. `MessageSchedule::getMessage()`
2. `MessageSchedule::fileCouldBeSend()`

### CODE REVIEW

**Comment by RCheesley** [comment]
Tagging for 2.16.1 as a bug fix is dependent on this PR, but as it's a feature then we might need to push this (and the bug fix) to 3.1. Open to discussions either way.

**Comment by RCheesley** [comment]
Actually reading up on semantic versioning and realised we can't do that so it will have to wait on the next feature release :(

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by npracht** [comment]
Hi @escopecz ! I am not sure it is a fantastic idea, but i want to share it anyway. You've done https://github.com/mautic/mautic/pull/7720 which needs to be applied after this PR. Maybe it would be clearer/safer to cherrypick the fix in the current PR ?

**Comment by escopecz** [comment]
It can be done. But I would argue it is simpler to review and test two big PRs than one mega PR. We have a lot of PRs that are dependent on each other. So we can either merge them all into one PR but no one will be able to review it and test it. I would rather start merging the PRs that we can and unblock the rest this way.

**Comment by escopecz** [comment]
Wait, looking closer to the changes, it seems that https://github.com/mautic/mautic/pull/7720 contains changes from this PR. @npracht you are right. Let me create a diff to be sure.

**Comment by escopecz** [comment]
The diff is showing all M3 changes as one is based on M2 and the other on M3. But I will cherry-pick the commits and be done with https://github.com/mautic/mautic/pull/7720. Thanks for pointing it out, Norman!

**Comment by npracht** [comment]
Thanks to you ❤️

**Comment by RCheesley** [comment]
Bumping to 3.2 due to unresolved conflicts and unmerged dependency.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by escopecz** [comment]
@RCheesley I already signed CLA. What else do I have to do?

**Comment by RCheesley** [comment]
> @RCheesley I already signed CLA. What else do I have to do?

You did but there is more than one person who made commits and they have not yet signed (@galvani)

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Review by RCheesley — DISMISSED** [review]
Tested per the instructions and was able to send an expected using 'now' and 'scheduled'.

screenshot-127 0 0 1_8025-2020 11 23-12_31_28

I was not able to test with a large data set / testing zipped files so another test would be advisable!

**Comment by escopecz** [comment]
@RCheesley thank you for testing! Is this doc not good enough? https://github.com/mautic/documentation/pull/302

**Comment by RCheesley** [comment]
> @RCheesley thank you for testing! Is this doc not good enough? [mautic/documentation#302](https://github.com/mautic/documentation/pull/302)

That repo is no longer in use, it will need to be pulled over to the live docs repo (https://github.com/mautic/mautic-documentation) - should be easy enough with the old PR :)

**Review by kuzmany — APPROVED** [review]
Works for me.
Tested locally even large reports attachment.
Code looks good, tests included. 

👍

**Pull request merged**
