### PR TITLE
Fixing missed template include syntax

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [y]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This is fixing this error [reported by the API tests](https://github.com/mautic/api-library/commit/ac029331b447a45b7edd3b4357c593efa83e7484/checks):
```
Response: {"errors":[{"message":"Template reference \u0022MauticFocusBundle:Builder:style.less.twig\u0022 not found, did you mean \u0022@MauticFocus\/Builder\/style.less.twig\u0022?","code":500,"type":null}]
```
I scanned for other forgotten include statements and found some more with the old syntax.

#### Steps to test this PR:

1. Check that the API Library tests are passing for this PR: https://github.com/mautic/api-library/actions/workflows/tests.yml

### CODE REVIEW

**Comment by escopecz** [comment]
I executed the API Library tests for this PR in https://github.com/mautic/api-library/actions/runs/4609143209

**Comment by escopecz** [comment]
That attempt allowed us to see the next error and failed with
```
Response: {"errors":[{"message":"An exception has been thrown during the rendering of a template (\u0022PHP Warning - require_once(\/var\/www\/html\/plugins\/MauticFocusBundle\/Twig\/Extension\/..\/..\/..\/Include\/lessc.inc.php): Failed to open stream: No such file or directory\u0022)
```

**Comment by escopecz** [comment]
Another error uncovered by the API Library tests:
```
Response: {"errors":[{"message":"There are no registered paths for namespace \u0022MauticFocusBundle\u0022.","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/plugins\/MauticFocusBundle\/Resources\/views\/Builder\/parent.less.twig","line":2,"args":[]},
```

**Comment by escopecz** [comment]
Api LIbrary tests are now green https://github.com/mautic/api-library/actions/runs/4609991464

**Review by RCheesley — APPROVED** [review]

**Review by mabumusa1 — APPROVED** [review]
Changes looks good

**Pull request merged**
