### PR TITLE
Add id of lead in mautic

### PR DESCRIPTION
**Pull request by SamWebmecanik**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | X
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Required: )
#### Description:
I will add the id field in the mapping of the CRM integration but with my code, it'll make that field available all throughout Mautic. If it's possible to not display it in the other parts of mautic, it would be great.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Open a CRM integration with a mapping
2. See the id lead field don't display in the list of mautic field

#### Steps to test this PR:
1. Apply this PR
2. Open a CRM integration with a mapping
3. See the id lead field display in the list of mautic field

### CODE REVIEW

**Comment by escopecz** [comment]
Please fix the code standards: https://travis-ci.org/mautic/mautic/jobs/247830231#L597

**Comment by MaxWebmecanik** [comment]
Ok so this time the tests pass on this PR but they timeout on staging for me....
That is without merging staging...
image

**Comment by MaxWebmecanik** [comment]
I also get a timeout if I merge staging...
image

**Comment by MaxWebmecanik** [comment]
So @escopecz I'm not sure what I should do... I would think this PR is not related to the tests breaking but I don't know how to test when it times out all the time...

**Comment by escopecz** [comment]
@MaxWebmecanik we fixed the issue on staging and I merged staging to this branch. The Travis tests should pass now.

**Comment by escopecz** [comment]
It seems it fails some unit tests. Please look into it.

**Comment by SamWebmecanik** [comment]
Closed in favor of #5310

**Pull request closed without merging**
