### PR TITLE
Amazon SES host: sa-east-1 not available

### PR DESCRIPTION
**Pull request by pbdco**
email-smtp.sa-east-1.amazonaws.com is not included in the dropdown list. If I add it mannualy it gives "This value is not valid."

image

https://github.com/mautic/mautic/issues/9414

### CODE REVIEW

**Comment by mabumusa1** [comment]
@pbdco thanks for the PR, may you please rebase this PR, I think there are the files that were committed in previous merges. I will review once you rebase

**Comment by mabumusa1** [comment]
@pbdco I was wondering if this setting will solve the issue you have

image

**Comment by RCheesley** [comment]
@pbdco this PR does not seem to fix the problem that you are reporting, do you need some help with making a pull request to add the new region?

There is some documentation to help you get started here: https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests

Please do join #t-product on Slack and ask for assistance if you need a hand! Get an invite at https://mautic.org/slack if you are not already on Slack :)

**Comment by npracht** [comment]
I'll close this PR @pbdco, it does not address the issue properly (see previous comments) and the PR itself is not done properly (it brings plenty of unrelated commits).

If you need any help to redo this PR properly, I invite you to join the #t-product channel on Slack and we'll help you :)

**Pull request closed without merging**
