### PR TITLE
Fix MJML email builder - "Edit Code" is broken

### LINKED ISSUE #10455: MJML email builder - "Edit Code" function is broken
### Mautic Version

4.0.0

### PHP version

7.4.23

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

This is kind of related to #10398 & #10396.

I tried out the fix described in the issues linked above, removing the set ID when changing a picture by accessing the "Edit Code" function to manually remove the ID I encountered an Issue that I was not able to open the builder after closing and saving the email.

It seems that once you manually made any edit using the "edit code" option, save the email and re-open it, you cannot access the "edit code" option anymore.

### How can we reproduce this issue?

1. Create a new email
2. Choose a template 
3. Open the Builder 
4. Open the "Edit Code" option to manually edit the MJML
5. Make any minor change to the MJML
6. Save your edit by clicking on "edit"
7. Close the email builder
8. Save and Close you Mail
9. Re-open the mail
10. Go to the builder
11. Try to open the "edit Code"
12. It won't open

### Relevant log output

```shell
No Logs
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by adiux**
closes #10455

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | yes
| Deprecations?                          |  no
| BC breaks? (use the c.x branch)        | no
| Automated tests included?              | N/A
| Issue(s) addressed                     | Fixes #10455

#### Description:

This fixes an issue where the code editor modal did not open **again** when the grapesjs builder was closed.

#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2. See steps in the [issue](https://github.com/mautic/mautic/issues/10455)

This PR is the same as https://github.com/mautic/mautic/pull/10564 but now based on 4.x branch

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10842"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
@adiux there seem to be commits unrelated to your changes. What did you use as a base branch?

**Comment by adiux** [comment]
@escopecz I just pulled the latest from 4.x. So in the files changed I only see the relevant changes I did.

**Comment by escopecz** [comment]
Yea, but we don't want to merge unnecessary commits either. It looks like those are commits coming from the 4.0 branch:

https://github.com/mautic/mautic/compare/4.x...4.0

It looks like the only commit needed here is https://github.com/mautic/mautic/pull/10842/commits/4da9ead2324cedaf0c10935b0d49cd8df6632451

Can you please do this:
- `git fetch upstream` (or whatever the mautic/mautic remote is called)
- `git checkout 4.x`
- `git reset --hard upstream/4.x`
- `git branch -b fix-10455-edit-code-is-broken-2`
- `git cherry-pick 4da9ead2324cedaf0c10935b0d49cd8df6632451`
- Now you can check the git history with `git log`. It should contain the last commit from https://github.com/mautic/mautic/commits/4.x and your commit on top of it. If it is OK, you can create new PR or use this branch and force push. To do that:
- `git checkout fix-10455-edit-code-is-broken`
- `git reset --hard fix-10455-edit-code-is-broken-2`
- `git push --force`

**Comment by adiux** [comment]
Thanks @escopecz 

I tried `git branch -b fix-10455-edit-code-is-broken-2`
error: unknown switch `b'

Did you mean git checkout?

**Comment by escopecz** [comment]
Yea, sorry. I was writing the commands just from the top of my head which is not very tidy place :). I hope you get the idea what I wanted to do from the brain dump.

**Comment by adiux** [comment]
@escopecz great job! I think it is clean now

**Comment by escopecz** [comment]
I'll mark this ready to commit as the code change was tested twice in the original PR https://github.com/mautic/mautic/pull/10564

**Review by kuzmany — APPROVED** [review]

**Pull request merged**
