### PR TITLE
Fix international phone number validation

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging for features or enhancements / 3.2 for bug fixes 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
International phone number validation doesn't exists after migrate to M3. This PR fixed it

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create form with phone field
3. Try create international phone number validation
4. Before PR you are not able to setup it.

image

### CODE REVIEW

**Comment by ismaescamillaa** [comment]
Loaded up the PR instance and tested the international validation, tested numbers in United States, Mexico and it worked.

I submitted a France number +3314326750, missing a zero and it validated it. all the rest of wrong phone numbers where marked as invalid.

Was this the test you intended?

**Comment by kuzmany** [comment]
@ismaescamillaa I meant that option Validate as international format was missing in previous 3.x 
Your number is in international format, validator doesn't care If number is correct

**Comment by ismaescamillaa** [comment]
Got it in that case I spawned an instance and validated the option is there. 

Not sure if you need me to add screenshots or any other proof of testing.

**Comment by kuzmany** [comment]
@ismaescamillaa You can approve it 

image

**Comment by npracht** [comment]
And don't forget to have a look at the code if it seems reliable for you :)

**Review by ismaescamillaa — APPROVED** [review]
Tested the functionality in sandbox and changes look good from my side.

**Review by hluchas — APPROVED** [review]
Looks good. Works well. 👍 
TY!

Would be better to replace `'tel'` with constant in the future .....

**Pull request merged**
