### PR TITLE
Monitored email feature

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**
This PR adds the feature to configure monitored email boxes for bounces, unsubscribes, and future bundle/plugin integrations

In the configuration, all email settings have been moved to the Email Settings tab.  Bounce handling and unsubscribe emails are optional.  There's the option to configure a global imap account and select each folder to monitor or custom imap connection settings per monitor. 

The PR also moves the email code from core bundle to email bundle  in order to show all the settings under the same tab leaving BC for MailHelper.

This also absorbed PR #775.

**Testing**
Apply the PR and nuke the cache.  Go to configuration and add a bounce and unsubscribe monitor.  Use a non-Gmail transport to send an email to a non existent lead email.  (Gmail rewrites return path so best to test with something else). The bounce should arrive to the specified inbox.  Make sure the mail is unread and run the console command `mautic:fetch:email`.  The message should be found and the lead marked as bounced.  If the folder is for unsubscribes, the lead will be unsubscribed.  

Once https://github.com/mautic/mautic/pull/777 is merged, we can add the email to the list-unsubscribe header.

### CODE REVIEW

**Comment by drmmr763** [comment]
Checked out PR, cleared cache, ran the entity update just in case. 

+ test I got this error:
```
500 Internal Server Error - Notice: Undefined index: address in /Users/chadwindnagle/Sites/gh-mautic/vendor/symfony/form/Symfony/Component/Form/FormView.php line 108
```

**Comment by escopecz** [comment]
I pulled the PR, nuked the cache and when I visit Mautic configuration, I get
```
 500 Internal Server Error - Attempted to call function "imap_list" from namespace "Mautic\EmailBundle\MonitoredEmail" in /var/www/html/mautic-github/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php line 313.
```

after php5-imap module installation
```
sudo apt-get install php5-imap
sudo php5enmod imap
sudo service apache2 restart
```
the configuration appeared fine. We'll probably have to check if the php5-imap module is installed and enabled in the server. As far as I found, this module is not part of LAMP or XAMP by default.

I changed my email settings from GMail to SMTP and while testing, I sent the test email to myself and it was delivered, but only with language strings (`mautic.core.config.form.mailer.transport.test_send.body`).

While testing IMAP I got this error:
```
Connection error: Certificate failure for mail.mydomain.com: Server name does not match certificate: /OU=Domain Control Validated/CN=*.mywebhosting.com
``` 
(I renamed domains, cuz they are personal) I configured **Use SSL** to No and port to 143. It shouldn't do anything with certificates, right?

**Comment by dbhurley** [comment]
Same error for me as @escopecz (imap_list).

**Comment by mbabker** [comment]
I checked a couple of shared hosts I have access to and both of them have the IMAP extension installed.  It might be a good idea to check some other common hosting platforms for this, and if it is indeed common enough, add a check to the installer.

For Homebrew PHP environments, you have to brew PHP with the IMAP extension enabled (it isn't a separate install like other extensions), so `brew install php5x --with-imap`.  Can't say much about other *AMP stacks these days.

**Comment by alanhartless** [comment]
The imap_list error is because the imap extension is not installed.  I originally hid the whole section if the extension wasn't installed but moved it around to show a message instead. As part of that move, the imap functions were accessed prematurely.  Should be fixed now.

@escopecz with the certificate error, I'm not able to reproduce the issue of not being able to disable SSL.  When I click No, SSL is not used. We have options though for when using SSL and the certificate issue.  We can either leave as is and require that certificates are valid are connect to the ssl/novalidate-cert imap endpoint. Of course that decreases level of security a notch but will be required for self signed certs so we may need it anyway. Or maybe we add it as an extra option, no/yes/no-validate? What do you think?

**Comment by dbhurley** [comment]
Minor thing: Can we update to this layout:
http://drop.dbh.li/image/0m0V3Y0i202x

`<div class="alert alert-info">...</div>`

**Comment by escopecz** [comment]
@alanhartless I agree. I'm not sure what's wrong with my email hosting, but it doesn't take any option.

**Comment by alanhartless** [comment]
@escopecz Can you try connecting now with some of the other encryption options? I added support for /tls, /ssl/no-validate, and /tls/no-validate.  You may need one of the no-validate options.

**Comment by escopecz** [comment]
Here is what happens with different options:
- port: 143, Encryption: None
```
Connection error: Certificate failure for mail.escopecz.cz: Server name does not match certificate: /OU=Domain Control Validated/CN=*.onebit.cz
```
- port: 993, Encryption: SSL
```
Connection error: Certificate failure for mail.escope.cz: Server name does not match certificate: /OU=Domain Control Validated/CN=*.onebit.cz
```
- port: 993, Encryption: SSL with no-validate
```
Connection error: Can't open mailbox {mail.escope.cz:993/imap/ssl/no-validate}: invalid remote specification
```
- port: 993, Encryption: SSL with no-validate
```
Connection error: Can't open mailbox {mail.escope.cz:993/imap/ssl/no-validate}: invalid remote specification
```
- port: 993, Encryption: TLS: The AJAX request never gets a response
- port: 993, Encryption: TLS with no-validate
```
Connection error: Can't open mailbox {mail.escope.cz:993/imap/tls/no-validate}: invalid remote specification
```
I had other problems with config form. Apply button doesn't save the info or it does it really slowly (Save button does it quite fast). It sometimes spins forever, sometimes finishes, but with value state before the change I wanted to save. The test button works only for the first time. When I change the Encryption and want to test again, it spins forever. The AJAX request fails with no error message and no error message is in the Mautic logs, but this is in the Apache log:
```
[Mon Aug 24 15:19:21.731953 2015] [:error] [pid 19600] [client 127.0.0.1:50111] PHP Fatal error:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Unknown: Can't open mailbox {mail.escope.cz:993/imap/ssl/no-validate}: invalid remote specification (errflg=2) in Unknown line 0' in Unknown:0\nStack trace:\n#0 [internal function]: Symfony\\Component\\Debug\\ErrorHandler->handle(8, 'Unknown: Can't ...', 'Unknown', 0, Array)\n#1 {main}\n  thrown in Unknown on line 0, referer: http://localhost/mautic-github/index_dev.php/s/config/edit
[Mon Aug 24 15:19:22.844883 2015] [core:notice] [pid 13149] AH00051: child pid 19600 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Mon Aug 24 15:21:24.012482 2015] [:error] [pid 19601] [client 127.0.0.1:50113] PHP Fatal error:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Unknown: [CLOSED] IMAP connection broken (server response) (errflg=2) in Unknown line 0' in Unknown:0\nStack trace:\n#0 [internal function]: Symfony\\Component\\Debug\\ErrorHandler->handle(8, 'Unknown: [CLOSE...', 'Unknown', 0, Array)\n#1 {main}\n  thrown in Unknown on line 0, referer: http://localhost/mautic-github/index_dev.php/s/config/edit
```
I had to restart the server during the testing because I Mautic didn't react even to the page refresh for quite some time.

**Comment by alanhartless** [comment]
@escopecz Do you have imap-ssl compiled into your PHP? It didn't come that way by default for me I had to install it. Wondering if that's what is causing you to not be able to connect?

**Comment by escopecz** [comment]
I tried to connect with my GMail account as well, but it does the same thing as I described above. So it's probably not a problem in the IMAP configuration.

How do I compile PHP with imap-ssl? I googled around, but couldn't find anything about it. But I think I have that installed and enabled. Here is what my phpinfo says 
phpinfo-imap

I think it is problem of my server config, but don't know what is it. I don't want to block this PR. Could someone else test it?

**Comment by alanhartless** [comment]
@escopecz I had the novalidate syntax wrong.  Can you give it another shot? I rigged my personal server with a self signed cert and could login using port 143 and tls with novalidate-cert.  I can log into Gmail and others using 993 SSL.  

It looks like you have imap compiled with SSL so that shouldn't be the issue.

**Comment by escopecz** [comment]
Port 143, None: `Connection error: Certificate failure for mail.escope.cz: Server name does not match certificate: /OU=Domain Control Validated/CN=*.onebit.cz`
Port 993, SSL: `Connection error: Certificate failure for mail.escope.cz: Server name does not match certificate: /OU=Domain Control Validated/CN=*.onebit.cz`
Port 993, TLS: `Connection error: Certificate failure for mail.escope.cz: Server name does not match certificate: /OU=Domain Control Validated/CN=*.onebit.cz`
Port 143, SSL with novalidate: `Connection error: TLS/SSL failure for mail.escope.cz: SSL negotiation failed`
Port 143, TLS with novalidate: `Connection error: IMAP Authentication cancelled`

The configuration's Apply request is still taking forever or fails. It happens only with this branch.

**Comment by alanhartless** [comment]
Is "SSL with novalidate" a typo? That should now be "SSL with novalidate-cert"

**Comment by escopecz** [comment]
Yes, I just simplified the option name

**Comment by alanhartless** [comment]
Are you able to connect into a Gmail account? (You will have to enable Gmail's "allow less secure applications" option to do so.  

I can't reproduce the config save thing at all.  It saves just fine for me.

**Comment by alanhartless** [comment]
`Port 143, SSL with novalidate: Connection error: TLS/SSL failure for mail.escope.cz: SSL negotiation failed`

I think that should be port 993

**Comment by escopecz** [comment]
I'll try GMail. Right now, I can't even open the config. Will try restarting server

**Comment by alanhartless** [comment]
Anything logged?

**Comment by escopecz** [comment]
Mautic logs are clear. Apache logs full of messages like
```
[Fri Aug 28 22:46:13.965354 2015] [:error] [pid 20269] [client 127.0.0.1:50406] PHP Fatal error:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Unknown: Certificate failure for mail.escope.cz: Server name does not match certificate: /OU=Domain Control Validated/CN=*.onebit.cz (errflg=2)' in Unknown:0\nStack trace:\n#0 [internal function]: Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Unknown: Certif...', 'Unknown', 0, Array)\n#1 {main}\n  thrown in Unknown on line 0, referer: http://localhost/mautic-github/index_dev.php/s/config/edit
zend_mm_heap corrupted
[Fri Aug 28 22:46:15.162229 2015] [core:notice] [pid 1319] AH00051: child pid 20269 exit signal Segmentation fault (11), possible coredump in /etc/apache2
zend_mm_heap corrupted
[Fri Aug 28 22:48:22.679591 2015] [:error] [pid 20326] [client 127.0.0.1:50417] PHP Fatal error:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Unknown: [CLOSED] IMAP connection broken (server response) (errflg=2)' in Unknown:0\nStack trace:\n#0 [internal function]: Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Unknown: [CLOSE...', 'Unknown', 0, Array)\n#1 {main}\n  thrown in Unknown on line 0, referer: http://localhost/mautic-github/index_dev.php/s/dashboard
[Fri Aug 28 22:48:26.295382 2015] [core:notice] [pid 1319] AH00051: child pid 20326 exit signal Segmentation fault (11), possible coredump in /etc/apache2
```

**Comment by alanhartless** [comment]
Symfony's dev mode is catching the PHP notice and throwing an exception with it.  Will probably need to silence the imap connection functions to prevent the notice.  Stand by.

**Comment by alanhartless** [comment]
Although the zend_mm_heap corrupted errors seem to suggest a PHP opcache issue as well.

**Comment by escopecz** [comment]
I turned off opcache in .htaccess with `php_flag opcache.enable Off` statement, but still the same result

**Comment by escopecz** [comment]
We found out with Alan that the imap connection didn't work for me because of charset encoding. Bounces still doesn't work for me though

**Comment by alanhartless** [comment]
I just went through the whole process and bounces are working.  I'm going to merge this so we can create beta packages and will continue testing through those.

Label assigned via a processed bounce

**Pull request merged**
