### PR TITLE
[UX] Quick help

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

this pr introduces a new quick help icon that, when clicked, displays a dropdown menu with useful information for mautic users. the dropdown will include shortcuts to common features:
- Keyboard shortcuts
- Search commands modal

image

this feature is designed to make it easier for users to discover and access important functionality within mautic. when providing a centralized location for these helpful items, users can quickly find the information they need without having to navigate through docs. 

It will allow us to add other things in the future, such as a “Provide feedback” link (if relevant), leave a slot for stakeholders to add a “contact support” or anything that helps the user with the platform or our stakeholders’ needs

Related PRs:
- #13939
- #13942 

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Contacts > Click on the icon on the navbar > Click on both

### CODE REVIEW

**Comment by LeonOltmanns** [comment]
@andersonjeccel I quite like the idea and like the implementation of the "Keyboard Shortcuts". On the other end the "Search Commands" only seem to work on pages, where a filter with a Search Help already exists.

Trying to access the "Search Commands" from the Dropdown on pages like Campaigns or the Dashboard results in nothing. And if that only works on pages where it is already implemented like here: 

image

I feel like its a more complicated to navigate to the dropdown and opening the "Search Help" over the dropdown instead of using the button directly next to the Filter option.

**Comment by andersonjeccel** [comment]
@oltmanns-leuchtfeuer In the past, some dialogs were built using JS and a bit of PHP that basically makes hard to work with any kind of specific customization related to these help features
I already moved the hardcoded JS keyboard shortcuts to a HTML/Twig template in #13895 that allows us to make them translatable and move things around the way we want

The main benefit is to create templates that are adequate to each scenario, so it would make sense to create a general Search commands window (that is not ready yet) to address everything everywhere.

I'll label this PR as blocked until we have the new search commands window, and I apologize for placing the ready to test label in the wrong moment

**Review by abhisekmazumdar — COMMENTED** [review]
High-level code review & local functional testing for this.

I see the new help icon over the navigation bar. Clicking the help button displays two options: 1. Keyboard shortcuts and 2. Search commands. The content of the help text over the help window changes according to the current page.


~~One issue: 
When in the Dashboard or any pages that don't have a filter input box, the Search commands link appears, but clicking it doesn't do anything. Perhaps we can hide it for those pages or add some default help text for those pages.~~

**Review by abhisekmazumdar — APPROVED** [review]
I see the bigger picture now after testing a few of the other related PRs.

**Review by escopecz — CHANGES_REQUESTED** [review]
The search commands option makes sense only in the list views that have a search box. If I go for example to the contact detail page, the search commands option is still there. When I click on it, nothing happens. It doesn't look like a good experience. It should either be there only when it can do something or open some apology message that it works only on the list views. A button that does nothing is bad.

**Comment by andersonjeccel** [comment]
@escopecz That's why we have an entire new solution here, with a much better experience than the current search help modals 😉
- #13939

**Comment by escopecz** [comment]
Can you elaborate? That PR depends on this PR. I don't like merging something that is half-baked.

**Comment by andersonjeccel** [comment]
@escopecz This PR adds the button that calls modals that already exist in each page (like Contacts, Forms etc)
The other PR changes the target of this button to a new modal, created specifically to improve the Help experience and available everywhere based on the feedback from oltmanns-leuchtfeuer (that already mentions 100% of your review)

All of them (5 PRs in total) are ready for production, all we need is to merge them
- #13908 (responsible for the main dropdown)
- #13939 (addresses the availability of the search help everywhere and improves the experience)
- #13895 (addresses a new experience for the shortcuts modal)
- #13940 (technical addition responsible for the components used to create these modals)
- #13942 (a new modal for the tokens users use as placeholders for Contacts and Companies fields)
- #13950 (completely remove the current search help)

**Comment by escopecz** [comment]
I still don't get it. I understand there are other related PRs, but what is the plan? Will the button display always something even if there is no search on the page? Or will it be hidden when there is no search? If so, why it's not being hidden in this PR?

**Comment by escopecz** [comment]
I'm re-reading your answers here and it seems you don't plan to hide the button. But what will it do when there is no search field?

**Comment by escopecz** [comment]
Sorry for additional comments, more questions are coming in to my head. Why is not this PR dependent on some other PR that adds the modal that the button would show up? This is not a feature we can merge in the current state as it adds a button that does nothing most of the time. Yet, other PRs depend on it. I'm not sure how to resolve it.

**Comment by andersonjeccel** [comment]
@escopecz The plan is to completely remove the search help as we have now using #13950 

Many search commands currently are wrong (check webhooks and companies)

in #13939 we’ll have a modal that shows all commands in an organized way, available in every page using the button I introduced here

Here the Search commands button opens the existing search help modal for resources on pages like contacts, but as you said, it’s problematic to have something that isn’t available everywhere 

So in the other PR, I address this issue making the same Search commands button open a different modal, available everywhere, organized and revised 

When there is no search field, the other PR will still open a Search help modal with all of them in accordions so users open the ones they want

The idea is also a bit about ensuring that Mautic features keep visible instead of disappearing every time based in conditions that the user don’t know 

We need to merge all of them to have a new experience, they’re ready, but separate so people can review each part

**Comment by escopecz** [comment]
Now I get the whole picture. Thanks for the explanation!

Now what is the order of merging here? This PR is ready, but depends on other PRs that are drafts with the "blocked" label. I don't see a clear path here.

**Comment by andersonjeccel** [comment]
@escopecz They're considered as blocked because they came after this PR here
I'm leaving blocked PRs as draft even when they're ready, so we avoid testing/reviewing before the dependencies get merged

So the order would be:

1. #13895
2. #13940 
3. #13908
4. #13939 and #13942 
5. #13950

**Comment by escopecz** [comment]
https://github.com/mautic/mautic/pull/13940 is blocked by https://github.com/mautic/mautic/pull/13630 which have negative comments. How do we move all this forward?

**Comment by andersonjeccel** [comment]
@escopecz That PR had a lot of changes since created, the comments are about changes that were reverted in the past (so I believe we can consider as solved, other enhancements added)

**Comment by andersonjeccel** [comment]
> [!WARNING]
> All Tier 1 PRs [need only 1 code review](https://contribute.mautic.org/governance/code-governance#:~:text=Full%20testing%20and%20approval%20by%20at%20least%20one%20community%20member%20(could%20be%20the%20person%20doing%20the%20code%20review%2C%20but%20should%20not%20be%20from%20the%20same%20company/organisation%20as%20the%20person%20submitting%20the%20PR).) and 1 user testing before able to merge. I'll update accordingly.

**Comment by RCheesley** [comment]
Just working through merging the PRs which are RTC from the dependency list in the comments above. Hold on to your hats 🤠

**Comment by RCheesley** [comment]
I'm assuming that the open requested changes is now addressed based on the comments above, so merging this PR.

**Pull request merged**
