### PR TITLE
Unicode fix

### PR DESCRIPTION
**Pull request by drmmr763**
Should fix issue where unicode characters coming from something like twitter breaks the database.

### CODE REVIEW

**Comment by dbhurley** [comment]
:+1: Works as expected.

**Comment by escopecz** [comment]
I tried to authorize Twitter integration (assuming it has to be done to test this), but while authorizing twitter app I got this error:
`You are not allowed to access this file. Check index_dev.php for more information.`
on this URL:
`http://mymautic/index_dev.php/s/addon/integrations/authcallback/Twitter?oauth_token=******&oauth_verifier=******`

**Comment by drmmr763** [comment]
@escopecz Would you mind testing without using the index_dev in the callback path?

I think the issue with testing that way is the index_dev.php code has a check for the referring IP address to be a localhost address, so since this comes from twitter that will fail, causing the error. Testing without the dev mode should work okay.

**Comment by escopecz** [comment]
Yup, authentication works when I don't use index_dev.php. Thanks.

I tested it with `FareehaSKhan` twitter account and the profile loaded without any error on lead detail. May it be because I configured database encoding before?

After applying this PR and refreshing Twitter account it works as well. I vote :+1:

**Pull request merged**
