### PR TITLE
Re-enable rendering of html in form field labels

### LINKED ISSUE #1790: Allow use html code in checkbox fields
## Description

One of the fields of my form is a checkbox "I accept the terms of the contract". But is not possible to insert a html code with link to the page of the contract.

in other fields is possible to use html code, but the checkbox field is not yet.
I want to use in the checkbox field a code like this:
`"I accept the <a href="http://exemple.com/contract" target="_blank">terms of the contract </a> "`

### PR DESCRIPTION
**Pull request by PatrickJenkner**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #1790 

## Description

The ability to use html in form field labels (e.g. for links) was broken in Mautic 5. This PR re-enables it.

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a form with multiple types of fields (Checkbox, Email, ...)
3. For each of those fields, use a label that contains html, for example `<a href="https://mautic.org"> Click here </a>`
4. See that the html is rendered
Bildschirmfoto 2024-07-30 um 14 53 35

6. Save the form
7. Verify that the html is also rendered in /s/forms/<id> and in the preview
image

### CODE REVIEW

**Comment by PatrickJenkner** [comment]
I noticed the failing unit tests, but from what I can tell that's not because of my changes (I downloaded a 5.x and those tests fail there as well; plus the unit tests ran through before I merged 5.x). So I'm gonna call it ready for review ¯\\\_(ツ)_/¯

**Review by escopecz — COMMENTED** [review]
Can we use the `|purify` filter instead of `|raw` to avoid XSS?

**Comment by PatrickJenkner** [comment]
> Can we use the `|purify` filter instead of `|raw` to avoid XSS?

Done, works just as well @escopecz

**Review by MadlenF — APPROVED** [review]
Works as expected from user-perspective! 👍

**Review by escopecz — APPROVED** [review]
The code changes make sense, thank you! 👍

**Pull request merged**
