### PR TITLE
Form field value conditions in the Campaigns

### PR DESCRIPTION
**Pull request by escopecz**
The new type of event was created for campaign - Conditions. Condition can be connected to any decision, action or another condition. This condition type can be used for more future events.

The form field value condition takes value defined in the campaign condition event and compares it with all lead's submissions of the defined form. Then it decides if the condition is true or false and triggers the next event accordingly.

This PR also fixes error for negative path of a campaigns if a decision is a first node after source.

Requested in https://github.com/mautic/mautic/issues/88, https://github.com/mautic/mautic/issues/527 and https://www.mautic.org/community/index.php/910-trigger-actions-based-on-form-fields

This also solves https://www.mautic.org/community/index.php/980-mautic-campaigns-trigger-dbalexception/0#p3905

### How to test
1. Apply the PR, clear Mautic cache, clear browser cache
2. Open a old or new campaign and create a campaign with the conditions.
3. Trigger the campaign and make sure it behaves as it should.
4. Old campaigns must still work.

Big thanks to Alan for help!

### CODE REVIEW

**Comment by alanhartless** [comment]
!()[http://alan.direct/drop/2015-09-18_12-56-56.png]

I see that the operator list is "borrowed" from the lead bundle which is fine except that empty, not empty, between, and not between are not native DBAL expr functions and are special cases handled by the lead's repository.  We would have to add handling of those in compareLastValue as well.

Also, between and not between would require two entries along with in and not in would require an array of values.  So maybe we should just remove those as options unless you want to add some means of handling the values of those in the form value condition's UI.

**Comment by alanhartless** [comment]
*I tested the following dripflow scenarios which did not seem to work:*

:x: Chaining condition to an action



Is there a use case for chaining a condition to an action? Since we don't support chaining actions with actions, maybe we should configure jsplumb so that a condition can only connect into a lead source, decision, or another condition (prevent it from connecting it into an action). Otherwise we would have to do queries after executing each action to see if there is something a condition chained to it and not sure what that would do for performance.  

:x: Scheduling/setting an interval for a condition connected into the source or the yes/green path of a decision





But my condition checks didn't get scheduled rather were just ignored.  Not sure how we want to handle that.  I was thinking it would be scheduled in one minute then pulled (with triggerScheduledEvents), condition checked, then associated actions were executed.

:x: Chaining a condition to the negative/red anchor of a decision



It was never caught by triggerNegativeEvents.  Not sure if this is the result of an existing bug/issue prior to this PR or not. If I put an action between the source and the decision, it worked.

*I also tested these scenarios which worked*

:heavy_check_mark:  Chaining a condition to the negative/red anchor of a decision with an action between the source and decision


:heavy_check_mark:  Chaining a condition to a condition


:heavy_check_mark:  Chaining a condition to a yes/green path of a decision without a wait


Those are the only ones I could think of to test.

**Comment by escopecz** [comment]
@alanhartless thanks for testing. Issues you found should be resolved.

**Comment by dbhurley** [comment]
image

Is it possible for the "Value" to be ajax-updated as well so that if the "Field" is a select then the value field is a dropdown of possible values instead of a free form entry?

**Comment by escopecz** [comment]
Yes, that's possible. Would you want to add also the lead field value condition into 1.2.1 or later?

**Comment by dbhurley** [comment]
If it can be done somewhat quickly then let's do it for 1.2.1

**Comment by escopecz** [comment]
Asynchronous update of value input to select box with values if the field has options is implemented as well as Lead Field Value Condition.

**Comment by alanhartless** [comment]
Lead field conditions and value boxes converting to selects/inputs work for me.

:+1:

**Comment by dbhurley** [comment]
+1 this works for me. Nicely done! :+1:

**Pull request merged**
