### PR TITLE
DPMMA-1157 Restrict password policy

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ N ]
| New feature/enhancement? (use the a.x branch)      | [ Y ]
| Deprecations?                          | [ N ]
| BC breaks? (use the c.x branch)        | [ N ]
| Automated tests included?              | [ Y ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:
This PR is a proposal to make more restrict password policy in Mautic.

Current password requirements: 
* Must contain at least 6 characters.

Password requirements after changes: 
* Password must be minimum eight characters,
* at least one uppercase letter, 
* at least one lowercase letter, 
* at least one number,
* at least one special character.

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Try to add a new user with password that doesn't meet the requirements (should be rejected)
3. Add new user with password that meet the requirements

### CODE REVIEW

**Comment by tomekkowalczyk** [comment]
@patrykgruszka the changes look ok.

**Review by tomekkowalczyk — APPROVED** [review]

**Review by PatrickJenkner — APPROVED** [review]
Works as described. Just a minor thing:
Screenshot 1 12812
Since there is only 1 single message listing all of the requirements, the user might not realize which rule their password is breaking.
However, there **is** a separate message for the length of the password, which means that this requirement is technically listed twice:
Screenshot 2 12812
Having separate messages for all the requirements would be nice, even though it's obviously not required.

**Comment by patrykgruszka** [comment]
@PatrickJenkner good point. I've split the restrictions to use different validation messages.

**Comment by escopecz** [comment]
This reminded me a PR that we have in our fork. I found out that it isn't pushed to the community yet. I can push it. It is based on https://github.com/bjeavons/zxcvbn-php rather than custom rules. We can then compare which one will be better.

**Comment by escopecz** [comment]
I pushed the password check PR from our fork for comparison: https://github.com/mautic/mautic/pull/12826

**Comment by escopecz** [comment]
I added a few reasons why https://github.com/mautic/mautic/pull/12826 is better than this implementation to the PR description. Would be everyone OK with closing this PR in favore of https://github.com/mautic/mautic/pull/12826?

**Comment by patrykgruszka** [comment]
Ok, let's work on #12826. Feel free to add the functional tests from this PR.

**Pull request closed without merging**
