### PR TITLE
Dispatch events from SendGridApiFacade

### PR DESCRIPTION
**Pull request by maxlawton**
| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | Maybe
| Deprecations? | N

#### Description:

This feature improves and extends the functionality submitted in PR #7224 by moving the event dispatching from the **SendGridApiMessage** service to the **SendGridApiFacade** and also providing event-based access to the SendGrid API mail send response.

The `SendGridMailEvents::GET_MAIL_MESSAGE` event is now dispatched immediately after the **Mail** instance is returned by **SendGridApiMessage**.

There is now another event, `SendGridMailEvents::MAIL_SEND_RESPONSE`, which is dispatched after the message has been sent and a **SendGrid\Response** has been received and validated. The event object passed to subscribers is an instance of **GetMailMessageEvent**, which allows access to the Response by way of its `getResponse()` method. This event class extends the previously defined **GetMailMessageResponse** and thereby allows access to the same _mail_ and _message_ objects.

##### PHPUnit

1.  Test that subscribers to both new events are called as expected:
    `$ bin/phpunit --configuration app/phpunit.xml.dist --filter '/SendGrid.*EventTest/'`

#### List backwards compatibility breaks:

1. An **EventDispatcher** must be passed via constructor injection to the **SendGridApiFacade** class. A constructor argument has been added as well as the relevant service configuration changes. Any use of the **SendGridApiFacade** class not covered by the scope of this codebase may be subject to breakage.
2. The aforementioned service constructor argument change and configuration edits will require the application kernel cache to be cleared and rebuilt. Probably a good idea to wipe the APC cache if applicable.

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by maxlawton** [comment]
@alanhartless, on #7224 (which I have closed in favor of this PR) you commented:
> At the very least, the hash ID, email ID and source information should be included. This can be passed through Sendgrids webhooks which then allows API manipulation via Mautic.

There are two obvious ways this could be achieved as default functionality for the _SendGridApiFacade_:

1. Define an _EventSubscriber_ service in the _EmailBundle_ which is enabled by default and adds the desired metadata in a handler on the `SendGridMailEvents::GET_MAIL_MESSAGE` event.
2. Propagate the desired metadata as part of the `SendGridApiMessage->getMessage(...)` process. This would entail either of the following:
    * Add more logic to the `SendGridMailMetadata::addMetadataToMail()` method.
    * Add another class to the `Mautic\EmailBundle\Swiftmailer\SendGrid\Mail` namespace (much like the original implementation of this PR's functionality back in #6695), which would then be injected into the _SendGridApiMessage_ class constructor, and would be called in the same manner as the other classes in that namespace.

With either approach, the event dispatched in this PR would allow plugin developers access to the values bound upon the `SendGrid\Mail` instance, should they find reason to remove or alter that information.

Let me know which you would prefer, and I'll add the functionality as desired. I think it would make sense to do so in a separate PR. The first approach would be dependent on this PR, but the second could be implemented for the _SendGridApiFacade_ in its current form in **staging**.

**Comment by maxlawton** [comment]
The default _customArgs_ functionality discussed above has been submitted in #9818. That feature is functionally independent from this.

**Comment by maxlawton** [comment]
Details for the failed checks have expired. I guess I'll have to merge *features* into this branch again and re-push to check tests. I am using this functionality in production, and do still consider it a desired feature. Please don't stale me, bot. 😄

**Comment by RCheesley** [comment]
Yes please do merge in the latest features branch :)

**Comment by andersonjeccel** [comment]
Hey there! 👋
I noticed this PR has been open for quite a while now (wow, time flies! 🕰️) without any recent activity. Given the age of this PR and the changes that have happened in the project since then, it's probably best to close this one out.

If you still think this change would be valuable, feel free to open a fresh PR with an updated implementation. Otherwise, no worries – thanks for your interest in contributing!

I'll be closing this PR to help keep our project tidy. Thanks for understanding! 😊

**Pull request closed without merging**
