### PR TITLE
Impossible to import contacts

### PR DESCRIPTION
**Pull request by anton-vlasenko**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
When we try to import a .csv with contacts we get an error. "Unable to read the imported csv file"

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Install Mautic using 3.x branch.
2. Create a csv file with the contacts.
3. Try to import it. You will get an error.

#### Steps to test this PR:
1. Install Mautic using 3.x branch.
2. Checkout this PR in git.
3. Create a csv file with the contacts.
4. Try to import it. You should get no errors. All the contacts have to be imported.

### CODE REVIEW

**Comment by LeonOltmanns** [comment]
Tested and got the following error when trying to Test the PR.

bug

Error Log:
`Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "PHP Notice - Undefined index: all_fields" at /var/app/current/code/pulls/8631/app/bundles/LeadBundle/Form/Type/LeadImportFieldType.php line 67`

**Comment by npracht** [comment]
@anton-vlasenko is it related to your PR or is it a bug with mautibox ?

**Comment by adiux** [comment]
not working for me, but with a different error (Browsers: Safari and Brave)
image

used csv sample data
https://drive.google.com/file/d/1eKeCADzh8j5TMmb7uYZaaurrWKrZHwLq/view?usp=sharing

image

**Comment by anton-vlasenko** [comment]
@oltmanns-leuchtfeuer @adiwegs 
What .csv file do you use for testing?
I've just tested with this .csv file and it works.
[contacts.csv.zip](https://github.com/mautic/mautic/files/4438806/contacts.csv.zip)

**Comment by adiux** [comment]
> @oltmanns-leuchtfeuer @adiwegs
> What .csv file do you use for testing?
> I've just tested with this .csv file and it works.
> [contacts.csv.zip](https://github.com/mautic/mautic/files/4438806/contacts.csv.zip)

https://drive.google.com/file/d/1eKeCADzh8j5TMmb7uYZaaurrWKrZHwLq/view?usp=sharing

**Comment by anton-vlasenko** [comment]
I can't reproduce this on my local environment with the test .csv file you provided. I'll test tomorrow on Mautibox.

**Comment by anton-vlasenko** [comment]
@npracht I think it's Mautibox related. I don't have the capacity to test it on Mautibox today. I'll do it tomorrow.

**Comment by anton-vlasenko** [comment]
I've asked around and It seems I can't do anything about Mautibox. It's a private service.
I don't have access to it.
And I can't select my PR from the list of PRs here https://mautibox.com/ nor there https://m3.mautibox.com/
So I suppose this has to be tested using some other method. There are no errors in my local environment.
I've updated the description.

**Comment by npracht** [comment]
@anton-vlasenko use http://m3.mautibox.com/ !

**Comment by anton-vlasenko** [comment]
This PR is blocked by https://github.com/mautic/mautic/pull/7308.
https://github.com/mautic/mautic/pull/7308/ has to be merged first.
If there will be error with the import, we should think about merging this PR then.
@adiwegs @oltmanns-leuchtfeuer @npracht Thank you for testing it. I apologize for taking your  time.

**Comment by npracht** [comment]
Okay ! #7308 was milestoned for later. @escopecz should we put both PR in 3.0.0 our both in 3.1.0 ?

**Comment by alanhartless** [comment]
@anton-vlasenko is this fixing something In Mautic 3 as is or something in John’s PR?

**Comment by escopecz** [comment]
@anton-vlasenko if this PR fixes a bug in https://github.com/mautic/mautic/pull/7308, do you think I could cherry-pick the 2 commits from this PR to https://github.com/mautic/mautic/pull/7308 and close this PR?

**Comment by npracht** [comment]
That would be more appropriate then :)

**Comment by anton-vlasenko** [comment]
> is this fixing something In Mautic 3 as is or something in John’s PR?

@alanhartless 
Probably bug appeared as a result of upgrading Mautic to Symfony 3.
I'm not saying that the bug is neccessarily in the https://github.com/mautic/mautic/pull/7308.
I'm only saying that when/if we decide to merge https://github.com/mautic/mautic/pull/7308, we will need to test contacts import.  If the import doesn't work we will have to merge this PR too.

> do you think I could cherry-pick the 2 commits from this PR to #7308 and close this PR?

@escopecz Yes, I think that's a good idea.
But I'd merge https://github.com/mautic/mautic/pull/7308 first, test contacts import and only then merge my PR if the contacts import doesn't work. But it's up to you. If you want to cherry-pick commits from this PR into https://github.com/mautic/mautic/pull/7308 you can do that of course. I suppose https://github.com/mautic/mautic/pull/7308 has to be rebased on top of the 3.x branch in the first place.

**Review by dongilbert — APPROVED** [review]
These are changes we've tested in our cloud environment for weeks and they are working as expected. It's not dependent upon any other PR

**Pull request merged**
