### PR TITLE
Refactor MauticFactory from PointModel and TriggerModel

### LINKED ISSUE #8229: Refactor MauticFactory from PointModel and TriggerModel

### PR DESCRIPTION
**Pull request by p365labs**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | N
| Automated tests included? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #8229 
| BC breaks? | N
| Deprecations? | N

Removed MauticFactory from PointModel and TriggerModel as Deprecated

### Steps to test:
1. Test that all point triggers and actions work.

### CODE REVIEW

**Review by escopecz — CHANGES_REQUESTED** [review]
Although I wish it would be this easy, it's not. The MauticFactory is being passed to several static methods (callbacks) with reflection. See for example https://github.com/mautic/mautic/blob/3.x/app/bundles/EmailBundle/Helper/PointEventHelper.php#L53. So in order to merge this PR you'll have to refactor all those callbacks to Symfony event architecture.

**Comment by p365labs** [comment]
@escopecz sorry but from the issue title I did not understand this. I removed deprecated MauticFactory from PointModel & TriggerModel. I see the other task u suggested another part always related to the hard task to remove MauticFactory. WDYT?

**Comment by escopecz** [comment]
I don't know what you are asking. Can you reformulate?

**Comment by p365labs** [comment]
@escopecz I removed MauticFactory dependency from PointModel and TriggerModel inside the PointBundle, as [here](https://github.com/mautic/mautic/issues/8229).
This PR is not about removing MauticFactory at all. The example you make is about **EmailBundle/Helper/PointEventHelper.php** which is not strictly related to this. 
Sorry but maybe, as Mautic is a really huge project,  I'm missing something here.

**Comment by escopecz** [comment]
You have to understand why the MauticFactory is there in the first place. It's not used in the models directly. It's sent to "callback" static functions. The example I used is related. Here is how the callback is configured: https://github.com/mautic/mautic/blob/916cb750f2e7896c735b231c98fd9a58c65cf0e5/app/bundles/EmailBundle/EventListener/PointSubscriber.php#L89

If we merge this PR before we refactor all those static callbacks to events then they will stop working. It's simple to confirm. Try this while checked in this branch:
1. Create a Point Trigger that will send an email if a contact gets 5 or more points
2. Edit a contact and give him 6 points.
3. The email was not sent. Check the logs for errors.

**Comment by p365labs** [comment]
@escopecz sorry... my fault I realize only right now *->triggerAction* is used in PointSubscriber....
my fault! :(

**Comment by escopecz** [comment]
Don't worry about it. It's not very transparent architecture. That's why we want to refactor to more transparent option :)

**Comment by p365labs** [comment]
@escopecz hava a look! I've tested right now the flow u suggested and is working fine.

**Comment by escopecz** [comment]
That's odd. Did your contact get the email? I get the error I'd expect:
```
500 Internal Server Error - Call to a member function getModel() on null at /app/bundles/LeadBundle/Helper/PointEventHelper.php:31 
```

**Comment by p365labs** [comment]
not checked on the LeadBundle side, u're right again my fault. please check it out right now

**Comment by escopecz** [comment]
I don't see how that could work. Have you tested it? `'leadModel'` would have to defined in this array:

https://github.com/mautic/mautic/pull/8538/files#diff-ccba3efcd0e7e7b58cbe8768fa6d316fR232-L250

The right solution is to move the methods from PointEventHelper classes to subscribers and listen for this event:

https://github.com/mautic/mautic/pull/8538/files#diff-ccba3efcd0e7e7b58cbe8768fa6d316fR280

The problem is not only with this one method, but there are several:

https://github.com/mautic/mautic/search?q=%22class+pointeventhelper%22&unscoped_q=%22class+pointeventhelper%22

The problem with the static methods is that you cannot use dependency injection there. That's why the whole MautiFactory was sent there.

**Review by dennisameling — CHANGES_REQUESTED** [review]
Tested on 3.x branch:

1. Create a Point Trigger that will send an email if a contact gets 5 or more points

image

2. Edit a contact and give him 6 points.
3. Email is sent correctly.

Then tested this PR with the same steps. Error:

```
[2020-04-25 19:38:14] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 3 passed to Mautic\EmailBundle\Helper\PointEventHelper::sendEmail() must be an instance of Mautic\EmailBundle\Model\EmailModel, null given" at /var/www/html/app/bundles/EmailBundle/Helper/PointEventHelper.php line 53 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 3 passed to Mautic\\EmailBundle\\Helper\\PointEventHelper::sendEmail() must be an instance of Mautic\\EmailBundle\\Model\\EmailModel, null given at /var/www/html/app/bundles/EmailBundle/Helper/PointEventHelper.php:53)
[stacktrace]
#0 [internal function]: Mautic\\EmailBundle\\Helper\\PointEventHelper::sendEmail(Array, Object(Mautic\\LeadBundle\\Entity\\Lead), NULL)
#1 /var/www/html/app/bundles/PointBundle/Model/TriggerModel.php(389): ReflectionMethod->invokeArgs(Object(Mautic\\PointBundle\\Model\\TriggerModel), Array)
#2 /var/www/html/app/bundles/PointBundle/Model/TriggerModel.php(345): Mautic\\PointBundle\\Model\\TriggerModel->invokeCallback(Array, Object(Mautic\\LeadBundle\\Entity\\Lead), Array)
#3 /var/www/html/app/bundles/PointBundle/Model/TriggerModel.php(415): Mautic\\PointBundle\\Model\\TriggerModel->triggerEvent(Array, Object(Mautic\\LeadBundle\\Entity\\Lead), true)
#4 /var/www/html/app/bundles/PointBundle/EventListener/LeadSubscriber.php(85): Mautic\\PointBundle\\Model\\TriggerModel->triggerEvents(Object(Mautic\\LeadBundle\\Entity\\Lead))
#5 /var/www/html/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(115): Mautic\\PointBundle\\EventListener\\LeadSubscriber->onLeadPointsChange(Object(Mautic\\LeadBundle\\Event\\PointsChangeEvent), 'mautic.lead_poi...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#6 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(214): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Mautic\\LeadBundle\\Event\\PointsChangeEvent), 'mautic.lead_poi...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#7 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'mautic.lead_poi...', Object(Mautic\\LeadBundle\\Event\\PointsChangeEvent))
#8 /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(143): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('mautic.lead_poi...', Object(Mautic\\LeadBundle\\Event\\PointsChangeEvent))
#9 /var/www/html/app/bundles/LeadBundle/Helper/LeadChangeEventDispatcher.php(84): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch('mautic.lead_poi...', Object(Mautic\\LeadBundle\\Event\\PointsChangeEvent))
#10 /var/www/html/app/bundles/LeadBundle/Helper/LeadChangeEventDispatcher.php(51): Mautic\\LeadBundle\\Helper\\LeadChangeEventDispatcher->dispatchPointChangeEvent(Object(Mautic\\LeadBundle\\Event\\LeadEvent))
#11 /var/www/html/app/bundles/LeadBundle/EventListener/LeadSubscriber.php(169): Mautic\\LeadBundle\\Helper\\LeadChangeEventDispatcher->dispatchEvents(Object(Mautic\\LeadBundle\\Event\\LeadEvent), Array)
#12 /var/www/html/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(115): Mautic\\LeadBundle\\EventListener\\LeadSubscriber->onLeadPostSave(Object(Mautic\\LeadBundle\\Event\\LeadEvent), 'mautic.lead_pos...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#13 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(214): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Mautic\\LeadBundle\\Event\\LeadEvent), 'mautic.lead_pos...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#14 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'mautic.lead_pos...', Object(Mautic\\LeadBundle\\Event\\LeadEvent))
#15 /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(143): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('mautic.lead_pos...', Object(Mautic\\LeadBundle\\Event\\LeadEvent))
#16 /var/www/html/app/bundles/LeadBundle/Model/LeadModel.php(467): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch('mautic.lead_pos...', Object(Mautic\\LeadBundle\\Event\\LeadEvent))
#17 /var/www/html/app/bundles/CoreBundle/Model/FormModel.php(112): Mautic\\LeadBundle\\Model\\LeadModel->dispatchEvent('post_save', Object(Mautic\\LeadBundle\\Entity\\Lead), false, Object(Mautic\\LeadBundle\\Event\\LeadEvent))
#18 /var/www/html/app/bundles/LeadBundle/Model/LeadModel.php(536): Mautic\\CoreBundle\\Model\\FormModel->saveEntity(Object(Mautic\\LeadBundle\\Entity\\Lead), true)
#19 /var/www/html/app/bundles/LeadBundle/Controller/LeadController.php(649): Mautic\\LeadBundle\\Model\\LeadModel->saveEntity(Object(Mautic\\LeadBundle\\Entity\\Lead), true)
#20 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(449): Mautic\\LeadBundle\\Controller\\LeadController->editAction('4', '')
#21 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('edit', '4', 0, '')
#22 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#23 /var/www/html/vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#24 /var/www/html/app/AppKernel.php(104): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#25 /var/www/html/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#26 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#27 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(64): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#28 /var/www/html/app/middlewares/VersionCheckMiddleware.php(67): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#29 /var/www/html/app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#30 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#31 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#32 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#33 {main}
"} 
```

@p365labs Would you mind checking your code? Thanks in advance 😊

**Comment by alanhartless** [comment]
At this point, we'll need to hold on this in 3.0.0. As John mentioned in https://github.com/mautic/mautic/pull/8538#issuecomment-599586169, removing dependency on MauticFactory can only be done once the execution of points and actions are refactored to be event subscribers (similar to form submit actions) rather than static methods. Then deprecate the static/MauticFactory to be removed in a future version of Mautic.

**Comment by kuzmany** [comment]
Part of refactoring do also PR this https://github.com/mautic/mautic/pull/7330

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by npracht** [comment]
@alanhartless i changed the branch to 4.0. Would you mind having a look at the PR to know if we merge it in 4.0 branch or if we close it ?

**Pull request closed without merging**
