### PR TITLE
Email form unsubscribe missing

### PR DESCRIPTION
**Pull request by escopecz**
How to replicate: Create an Email. Save. On email detail click on "Add A/B test" button.

### CODE REVIEW

**Comment by dbhurley** [comment]
:+1: Works as expected. +1

**Comment by dbhurley** [comment]
Can't merge. I think it just needs to be updated to the latest on 'staging'

**Comment by alanhartless** [comment]
Check that it's still a problem as I think I inadvertently fixed this with https://github.com/mautic/mautic/commit/791fc399ce47c5efb69f4469c9860749b24f2caf#diff-60072ef0fa130a4dd3a382f1cd777131R259. The root of the issue was that the unsubscribeForm was only defined if not a variant but really should be available to be changed for variants as well so fixed it in the EmailType.php form service.

**Comment by escopecz** [comment]
I tried to restore the database backup before migration, pull staging (since this is merged) and run the migration again and get this error:
```
...
     -> ALTER TABLE pages ALTER template DROP NOT NULL
Migration 20150521000000 failed during Post-Checks. Error An exception occurred while executing 'INSERT INTO emails (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, id, name, description, subject, from_address, from_name, reply_to_address, bcc_address, template, lang, content, plain_text, custom_html, email_type, publish_up, publish_down, read_count, sent_count, revision, variant_settings, variant_start_date, variant_sent_count, variant_read_count, category_id, variant_parent_id, unsubscribeform_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, "2015-06-04 07:34:34", 1, "John Linhart", "2015-06-03 09:22:19", 1, "John Linhart", null, null, "John Linhart", 5, "Email A1 - custom HTML", null, "Email A1 - custom HTML", null, null, null, null, "", "en", "a:0:{}", null, "<html>\n<head>\n\t<title><\/title>\n<\/head>\n<body>\n<p>Hello. this is version<\/p>\n<\/body>\n<\/html>", "list", null, null, 0, 3, 1, "a:2:{s:6:\"weight\";i:50;s:14:\"winnerCriteria\";s:14:\"email.openrate\";}", "2015-06-03 08:57:12", 3, 0, null, null, null]:

SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "content_mode" violates not-null constraint
DETAIL:  Failing row contains (5, null, null, null, t, 2015-06-04 07:34:34, 1, John Linhart, 2015-06-03 09:22:19, 1, John Linhart, null, null, John Linhart, Email A1 - custom HTML, , en, a:0:{}, null, <html>
<head>
	<title></title>
</head>
<body>
<p>Hello. this is ..., null, null, null, 0, 3, 1, a:2:{s:6:"weight";i:50;s:14:"winnerCriteria";s:14:"email.openrat..., 2015-06-03 08:57:12, 3, 0, Email A1 - custom HTML, null, null, null, null, null, list).
...
```

**Comment by dbhurley** [comment]
This looks to be fixed.

**Comment by escopecz** [comment]
Good. Closing this PR.

**Pull request closed without merging**
