### PR TITLE
Display list of contacts on click in Click stats table across all channel

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | Yes
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/1883
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR added clickable number of unique clicks across all channels (email, sms, notification, dynamicContent) Click stats table. Number of unique clicks will redirect to contact list with  related filter. Same like search commands: email_sent, email_read added few months ago.  This PR added new search commands  page_id, page_source, page_source_id
Also this PR fixed issue if somebody wrote same search command twice and more time. This lines fixed it https://github.com/mautic/mautic/pull/5849/files#diff-3fa38c644457bfa255aabbc8bd7e5291R1090

Preview in email details template: 

image

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1.  Try search with two same commands
image
2. If you use dev mode, error return. Or check logs for error something like 

> The given alias xx is not unique in FROM 

#### Steps to test this PR:
1. Apply PR and repeat steps
2. See no error 

#### Steps to test this feature request:

1. Apply PR and create email, notification, sms, dynamicContent with some click statistics
2. Go to all created entity to details
3. Scroll to click counts table and click on any number of unique clicks
4. Click should redirect to contacts page with search commands and related results
5. Check if all results works properly

### CODE REVIEW

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by AmitBFG** [comment]
Hi,

I have been waiting for this feature, where i can drill down to email clicks. How can i implement this in my existing mautic environment? 

I'm currently on v2.12.1

Thanks
Amit

**Comment by kuzmany** [comment]
@AmitBFG manually with change exactly lines https://github.com/mautic/mautic/pull/5849/files, by git apply or by https://github.com/mautic/mautic-tester

**Comment by LEAP-nishit** [comment]
@kuzmany if we do it manually with changes shown in commit, would any future upgrade process fail from a low to high risk perspective? Question mainly for a production enviroment.

**Comment by kuzmany** [comment]
Need update with every core update. It's risky, need tech skill guy in your team. 
Then not recommended do it.

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Label: Enhancement

**Comment by npracht** [comment]
@alanhartless & @escopecz this feature is awesome and wished by every mautic user for a looooong time.
Can we consider it as candidate for 2.14 ?

**Review by npracht — APPROVED** [review]
From a user perspective it works !

**Comment by LEAP-nishit** [comment]
👍 
Tested and works 
image

**Review by dongilbert — APPROVED** [review]

**Pull request merged**
