### PR TITLE
Fixes campaign emails that only recognized a lead's first and last name tokens

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**
Emails sent through a campaign would not populate lead fields other than first and last name. This PR fixes it.

**Testing**
Add an email to a campaign dropflow.  In that email add a token for the {leadfield=company} and {leadfield=firstname}.  Create/edit a lead to have both filled in.  Add the lead to the campaign then execute the mautic:campaign:trigger command. The email that arrives will have the first name but not the company populated.  Apply the PR, repeat and this time all the lead's fields should be available.

### CODE REVIEW

**Comment by escopecz** [comment]
I got SQL error on executing `mautic:campaign:trigger`
```
Triggering events for campaign 1
Triggering first level events


                                                                                                                  
  [Doctrine\DBAL\DBALException]                                                                                   
  An exception occurred while executing 'SELECT count(cl.lead_id) as lead_count FROM mau_campaign_leads cl WHERE  
   (cl.campaign_id = 1) AND (cl.manually_removed = ?) ORDER BY cl.lead_id ASC' with params [0]:                   
  SQLSTATE[42803]: Grouping error: 7 ERROR:  column "cl.lead_id" must appear in the GROUP BY clause or be used i  
  n an aggregate function                                                                                         
  LINE 1: ...n_id = 1) AND (cl.manually_removed = $1) ORDER BY cl.lead_id...                                      
                                                               ^   
  [PDOException]                                                                                                  
  SQLSTATE[42803]: Grouping error: 7 ERROR:  column "cl.lead_id" must appear in the GROUP BY clause or be used i  
  n an aggregate function                                                                                         
  LINE 1: ...n_id = 1) AND (cl.manually_removed = $1) ORDER BY cl.lead_id...    
```
Probably another problem with Postgres?

**Comment by escopecz** [comment]
The problem is here:
https://github.com/mautic/mautic/blob/staging/app/bundles/CampaignBundle/Entity/CampaignRepository.php#L554
When I remove the `->orderBy('cl.lead_id', 'ASC')` line, the command works. Is the ordering really necessary when we need just count?

**Comment by alanhartless** [comment]
@escopecz I started to add a group by but then reread and realized you're right; it's not even required for a count.  You should be able to test this PR now.

Thanks!

**Comment by escopecz** [comment]
I can confirm that after applying this PR, the campaign:trigger command works and that the sent email contains the company value. :+1:

**Pull request merged**
