### PR TITLE
Fix reply for email with suffix

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

If you use email with suffix for example `name+alias@gmail.com` then contact replies does not work properly  https://docs.mautic.org/en/channels/emails/contact-replies

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Setup contact replies monitoring https://docs.mautic.org/en/channels/emails/contact-replies
3. Create campaign with send email and reply decision
4. Send campaign email to contact with email address with suffix like `name+alias@gmail.com`
5. Then reply to the email
6. Then run `php bin/console mautic:email:fetch`
7. Check If reply was triggered properly

### CODE REVIEW

**Comment by escopecz** [comment]
@kuzmany how can this be `ready-to-test` and a draft PR with failing CI at the same time? 😄

**Comment by kuzmany** [comment]
@escopecz found another issue fixed in our report, but still need some tests. I removed label

**Review by escopecz — CHANGES_REQUESTED** [review]
Can you please start a new `app/bundles/CoreBundle/Helper/EmailAddressHelper.php` where we could add the `clean(string $email): string` and `getVariations(string $email): array` which will be then fairly simple to test with various email address examples?

**Comment by kuzmany** [comment]
@escopecz done. Added tests + fix PHP Stan

**Review by jos0405 — APPROVED** [review]
Just tested, works perfectly:
image

**Comment by daniellord32** [comment]
same as @jos0405  no issues all works well

**Review by escopecz — APPROVED** [review]
The code looks great. Thanks Zdeno! 👍

**Pull request merged**
