### PR TITLE
Pull request 7480 updates for pepipost SMTP

### PR DESCRIPTION
**Pull request by Hiteshpandey**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | Y
| Automated tests included? | N
| Related user documentation PR URL | https://github.com/mautic/mautic/pull/7480
| Related developer documentation PR URL | https://github.com/mautic/mautic/pull/7480
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/pull/7480
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description: 
Updated the PR https://github.com/mautic/mautic/pull/7480 raised by @moskoweb in order to get Pepipost webhooks working with the Pepipost SMTP Integration. Some minor changes are done so that bounced emails must be identified.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Set up webhooks according to the Mautic documentation
2. While using webhook updates with email get parameter set as "FROMADDRESS", Mautic won't be able to find the email address to be set as bounced.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com/)
2. Go through Mautic setup
3. Update the Pepipost SMTP credentials
4. Setup the webhook bounce handling as per [Mautic documentation](https://docs.mautic.org/en/channels/emails/bounce-management) and after logging into the Pepipost user panel, go [here](https://app.pepipost.com/app/settings/webhooks).
5. Find the Global API Section and set webhook as http://{site-domain}/mailer/pepipost/callback
6. You can now test by running campaigns.

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by Hiteshpandey** [comment]
> 
> 
> Hi there!
> It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.
> 
> **We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**
> ## How to do?
> 
>     1. Check if your feature or enhancement is still missing and relevant in Mautic 3
> 
>     2. **If Yes**: rebase your PR against the 3.x branch
> 
>     3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already
> 
> 
> **Please report results by commenting on your PR to make us administration easier.**
> 
> You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

Yes, will push the changes to a new pr and close this.

**Comment by npracht** [comment]
Hi @Hiteshpandey ! Maybe you can include code from https://github.com/mautic/mautic/pull/7480 at the same time ? Then i can close both PRs and we keep only one. That's also easier to test :)

**Comment by Hiteshpandey** [comment]
> 
> 
> Hi @Hiteshpandey ! Maybe you can include code from #7480 at the same time ? Then i can close both PRs and we keep only one. That's also easier to test :)

yup, this will work.

**Pull request closed without merging**
