### PR TITLE
[UI] New flexbox utilities

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#196 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR is based [on another PR](https://github.com/mautic/mautic/pull/13735), where I introduce tokens to replace most of the UI variables, aiming to improve consistency in all components. **We need it to be merged before this one becomes available for test.**

It creates new classes for most-used flexbox properties.
Also extends existing classes for things like padding.

---
### 📋 Steps to test this PR:

1. No testing

### CODE REVIEW

**Comment by LordRembo** [comment]
These changes make a lot of sense, I think. As you mentioned in another discussion, we need some flexbox options in there to be able to add new elements when proposing design changes/additions in future (eg. cards).
Is it useful to also have some documentation about the new classes and structures you are adding, eg. how to use them?

**Comment by andersonjeccel** [comment]
@LordRembo Nice idea, I'll add to my tasks list

**Review by LordRembo — CHANGES_REQUESTED** [review]
Alright, then if docs exist & the dependency is merged, I think this one is okay for further approval.

**Comment by andersonjeccel** [comment]
@escopecz This one is ready and has docs
We need it to proceed with the campaign builder redesign (it's probably the next one to be merged)

**Comment by LordRembo** [comment]
@andersonjeccel Could you link to the docs, in the issue description?

**Review by escopecz — APPROVED** [review]
I don't see any issue in the code, but I'd also like to read more about how to use the new classes.

**Review by LordRembo — APPROVED** [review]
Looks good, I'll just add a comment to the docs but it's not blocking for this PR.

**Comment by andersonjeccel** [comment]
Thanks!

**Comment by andersonjeccel** [comment]
@escopecz Seems ready!

**Pull request merged**
