### PR TITLE
#TPROD-310 - Migrate ChannelBundle to twig templates

### PR DESCRIPTION
**Pull request by SalemCode8**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. In the left side of the screen, open the "Channels" menu, click on "messages".
3. Test every single functionality on this page. Creating/editing/cloning messages, using different channels, filtering, pagination, etc. - all functionality should work exactly like it did before.

### CODE REVIEW

**Comment by volha-pivavarchyk** [comment]
@SalemCode8 Could you please specify which pages should be tested. All pages from the `channels` menu or just the `messages` page.

**Comment by SalemCode8** [comment]
> @SalemCode8 Could you please specify which pages should be tested. All pages from the `channels` menu or just the `messages` page.

the messages part

**Comment by volha-pivavarchyk** [comment]
1. There is the same content on the both tabs and and no distance between the yellow block and the footer. It looked a bit different before.
image

image

2. When I try to sort by category, the error is displayed. But I think it doesn't relate to this PR.
image

Everything else works fine for me.

**Comment by volha-pivavarchyk** [comment]
Everything works as before.
There is one small difference between the message texts:
now:
image

before (on 5.x branch):
image
image

@SalemCode8  Is it fine?

**Comment by SalemCode8** [comment]
> Everything works as before. There is one small difference between the message texts: now: image
> 
> before (on 5.x branch): image image
> 
> @SalemCode8 Is it fine?

Issue Fixed

**Review by RCheesley — CHANGES_REQUESTED** [review]
We seem to have the same issue reported earlier with Marketing Messages so maybe it has not been fixed fully - see below:

screenshot-8080-salemcode8-mautic-ueaf2i2b47v ws-eu74 gitpod io-2022 11 18-11_26_52

It is the same on each tab for each message, but also on the Contacts tab which should not be showing this.

When I try to clone an existing marketing message I am getting errors:

screenshot-8080-salemcode8-mautic-ueaf2i2b47v ws-eu74 gitpod io-2022 11 18-11_30_17

Same error as @volha-pivavarchyk when sorting by category.

When I try to paginate by 5 items it is paginating by 3, and I can't move between the items as expected - it's showing 1/2/3 on the first page, and 3/4/5 on the second page. When I expand it to 10, only 5 items out of 6 are showing:

screenshot-8080-salemcode8-mautic-ueaf2i2b47v ws-eu74 gitpod io-2022 11 18-11_32_51

Screen recording: https://watch.screencastify.com/v/lHoJiZtIt78Hl7N2R5RC

**Comment by volha-pivavarchyk** [comment]
The messages are displayed well for me now.
image

**Comment by RCheesley** [comment]
@SalemCode8 looks like a test is failing with PHP8 - can you take a look please?

**Comment by SalemCode8** [comment]
> @SalemCode8 looks like a test is failing with PHP8 - can you take a look please?

the tests failing is part of the 5.x latest pushes it's not related to this PR

**Comment by SalemCode8** [comment]
> We seem to have the same issue reported earlier with Marketing Messages so maybe it has not been fixed fully - see below:
> 
> screenshot-8080-salemcode8-mautic-ueaf2i2b47v ws-eu74 gitpod io-2022 11 18-11_26_52
> 
> It is the same on each tab for each message, but also on the Contacts tab which should not be showing this.
> 
> When I try to clone an existing marketing message I am getting errors:
> 
> screenshot-8080-salemcode8-mautic-ueaf2i2b47v ws-eu74 gitpod io-2022 11 18-11_30_17
> 
> Same error as @volha-pivavarchyk when sorting by category.
> 
> When I try to paginate by 5 items it is paginating by 3, and I can't move between the items as expected - it's showing 1/2/3 on the first page, and 3/4/5 on the second page. When I expand it to 10, only 5 items out of 6 are showing:
> 
> screenshot-8080-salemcode8-mautic-ueaf2i2b47v ws-eu74 gitpod io-2022 11 18-11_32_51
> 
> Screen recording: https://watch.screencastify.com/v/lHoJiZtIt78Hl7N2R5RC

The Views now fixed,
the sorting and errors in the details view is presented on the 5.x branch so I don't think it related to this PR,
the pagination issue tried to reproduce but couldn't if there's any steps to reproduce I'll give it another look.

**Comment by RCheesley** [comment]
For the pagination, I cloned the marketing message 5 times so I had 6 items (note the errors when cloning, but I was able to save still). Then I set the pagination from 10 to 5, expecting there to be 5 items on page 1 and 1 item on page 2. The result was not that. I'll test it again, maybe it was a glitch!

**Comment by RCheesley** [comment]
The messages are fixed, but still getting:

- Clone marketing message - errors about fields missing (this is present in 5.x so raising a separate issue)
- Pagination is not working correctly, see: https://watch.screencastify.com/v/dQJDHGGhJ6H6fooakssC

**Comment by volha-pivavarchyk** [comment]
Now works as before for me. I can't catch the pagination bag.

**Comment by sdoering** [comment]
**Steps to replicate:** 

1. In the gitpod instance I created a message
2. I added an email (created a new one)
3. Then I cloned said message
4. I then disabled email in the cloned message 
5. I switched the "publish" button to "published"

**The following error occured:** 

image

6. I was able to save and close the message
7. The configuration of the message was saved and I could open/edit it again (see following screenshot):

image

**Comment by sdoering** [comment]
Timing a message (publish/unpublish date) and adding a (new) category works fine: 
image

**Comment by escopecz** [comment]
The pagination issue and cloning issue were not caused by this PR. It existed before. But I fixed it in this PR. Please re-review.

There is one failing test when I merged latest 5.x. I can't figure out why it is failing now. It should be failing on 5.x too. But it will be fixed once https://github.com/mautic/mautic/pull/11778/files#diff-2ef4ef6bc337bbb5cb4279fe0bc9a35857453e60a5d5e1eb47f2e64bf7861c10 will exist.

**Review by volha-pivavarchyk — DISMISSED** [review]
Works as before

**Comment by volha-pivavarchyk** [comment]
@escopecz I faced with a double message header. It doesn't relate to this PR. I don't think this is expected behavior. Should this be fixed in a separate PR?

image

**Comment by escopecz** [comment]
@volha-pivavarchyk are you able to replicate it willingly? I managed to reproduce it when I changed from the rows per page limit from 5 to 10 once but it didn't appear when I tried it 100 times after that. Why do you think it's not related to this PR? Are you able to replicate it on 5.x?

**Comment by volha-pivavarchyk** [comment]
@escopecz I was able to reproduce the error as follows. I selected pagination 5, switched to page 2, changed the pagination to 15 or more. There were 11 messages in the list. I reproduced the same on the 5.x branch. But I didn't find out the cause of this bug in the code yet.

**Comment by escopecz** [comment]
Ok then, if it's reproducible in 5.x then it's not blocking this PR. Thanks!

**Comment by RCheesley** [comment]
I was able to reproduce the duplicate heading also:

1. Create 11 marketing messages
2. Set the number displayed to 25
3. Now set the number displayed to 5
4. Go to page 3, should be 1 item displayed
5. Now set the number displayed to (for example) 20 - header is duplicated

Here is a screen recording: https://watch.screencastify.com/v/wknyqZJ4Pw0MgZz3VmZv

So this is something that is in the 5.x branch as well as the message about the form fields. So the PR itself is good to go from my side!

**Comment by escopecz** [comment]
I found 2 templates unfinished. @RCheesley @volha-pivavarchyk please retest this scenarios:

Use this query to insert a dummy row into your instance so you could see the template in action
```sql
INSERT INTO `message_queue` (`id`, `event_id`, `lead_id`, `channel`, `channel_id`, `priority`, `max_attempts`, `attempts`, `success`, `status`, `date_published`, `scheduled_date`, `last_attempt`, `date_sent`, `options`)
VALUES
	(1, NULL, 1, 'email', 1, 0, 0, 0, 1, 'Sent', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '2022-12-12 12:12:12', '2022-12-12 12:12:12', NULL);
```
Add a table prefix if your instance use any. The query assumes that you have a contact with ID 1. Use another ID if you don't have it.

Go to the contact detail page of the contact ID 1 and ensure that the Marketing Message event is displayed normally:
Screen Shot 2022-12-14 at 10 19 51

The second scenario is not ready yet as it needs a dependency from the LeadBundle Twig refactoring. But I have prepared the Twig template and it is ready to be used once we have the dependency ready. The test scenario would be to go to the campaign builder and open the Marketing Message action. It should work now using the old PHP template and it should work the same after we switch to the Twig template.

The goal is to get this merged as it as other helpful Twig functions that can be used by other bundles and deal with the final template later when the dependency is available.

**Review by RCheesley — COMMENTED** [review]
Something not quite right on the contact profile when viewing the send entry (I sent it with a campaign):
screenshot-8080-salemcode8-mautic-q987s6z4kpe ws-eu78 gitpod io-2022 12 14-10_36_37

Also the contacts who received the email on the email channel should be showing here, I believe:
screenshot-8080-salemcode8-mautic-q987s6z4kpe ws-eu78 gitpod io-2022 12 14-10_37_20

**Comment by volha-pivavarchyk** [comment]
The first scenario works well for me.
image

I got the same result as @RCheesley when testing the second scenario.
image

**Comment by escopecz** [comment]
I found a way how to render twig templates from php templates that were not refactored yet which was the problem with the timeline. I also needed to refactor one more template from the CampaignBundle. Ready for retesting.

**Review by mabumusa1 — CHANGES_REQUESTED** [review]
I tested using Gitpod, there are minor issues
1. Index page has issue 500 error
image

2. I do not know what are these numbers, but they should not show 
image

Other functionality I tested and worked
1. Create a new message
2. Edit a message
3. Publish/unpublish 
4. Add categories 
5. Entries of contacts

**Comment by escopecz** [comment]
@mabumusa1 good catch! I was focusing on the events in the past commits and the list view stopped working by merging some other PRs. It seem to be working all now.

**Review by mabumusa1 — DISMISSED** [review]
It works as expected now, thanks @escopecz

**Comment by mabumusa1** [comment]
@volha-pivavarchyk can you please re-test this PR? it would be ready for commit after your approval

**Comment by volha-pivavarchyk** [comment]
@mabumusa1 Yes, sure. I can test in a few hours.

**Comment by volha-pivavarchyk** [comment]
I have just found the following cases.
1. The pagination is not displayed properly
image
5.x
image
2. Actions `New/Edit -> Save` result in the ability to select email when it is disabled
image
3. Duplicate header. This PR is not a cause of this issue.



All the rest works well for me. The contact timeline now looks really good.
image

**Comment by escopecz** [comment]
@volha-pivavarchyk you have a good eye! I fixed the issues 1 and 2. I will ignore issue 3 as it's not caused by this PR. Ready to retest.

**Review by mabumusa1 — APPROVED** [review]
Just re-tested, this PR is good to go

**Pull request merged**
