### PR TITLE
DPMMA-2881 fix Grapesjs-Mjml self-closing mj-spacer tag issue 

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description
This pull request resolves an issue where self-closing tag `<mj-spacer />` were causing rendering problems in Grapesjs-Mjml.

Fix for other self-closing tags was introduced in https://github.com/mautic/mautic/pull/13431, this PR just adds `mj-spacer`, to list of void tags.

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
1: Go to Channels > Emails
2: Create new
3: Select "New template email"
4: Fill in a name for "Subject" and "Internal name"
5: Select the "Brienz" theme - because it uses MJML
6: Go to "Builder"
7: Click on the pencil icon that corresponds to "Edit code"
8: Delete all the code and paste this code:
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text font-size="20px">top text</mj-text>
        <mj-spacer/>
        <mj-text font-size="20px">bottom text</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
10: Click save
11: Check if it's rendered correctly: top and bottom text should have a spacer element between
image

### CODE REVIEW

**Review by tomekkowalczyk — APPROVED** [review]
Change looks good ;)

**Review by Aleks0129 — APPROVED** [review]
Does what it says 
image

**Comment by escopecz** [comment]
Please resolve the conflicts. It's good to go afterwards.

**Comment by patrykgruszka** [comment]
@escopecz, I've resolved the conflicts, it's ready to merge

**Pull request merged**
