### PR TITLE
Track merged contacts so that tracked contacts will continue to be associated for 3rd party form submits

### PR DESCRIPTION
**Pull request by alanhartless**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y/enhancement
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

If a 3rd party submits a form to Mautic, Mautic will create/merge the contact which may result in a new ID. But then browser will continue to track the contact as a visitor rather than the contact identified through the form submit. This PR keeps track of IDs merged into a contact so that if a contact ID is given that has been merged into another, the resulting contact is still found and the browser updated with the new contact ID. 

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Reproducing is tricky due to requiring an advanced form setup that requires using a script to post to a Mautic form with mtc_id=ID of a visitor in the payload so that Mautic merges the visitor with that identified by the form
2. Redirect to a thank you page tracked by Mautic and the hit will be under a new visitor

#### Steps to test this PR:
1. Run migrations to update schema
2. Repeat the above and this time the hit will be under the merged contact
3. Run the functional tests

### CODE REVIEW

**Comment by escopecz** [comment]
@alanhartless could you provide the script needed to test this PR? I'm not sure I understand how it should look like from the description.

**Comment by alanhartless** [comment]
@escopecz 

I don't have the script and it was unique to my mautic form. here's what I did:
Create a simple Mautic form with just an email that redirects to a non-Mautic website that's tracked with the tracking pixel.
Create a basic custom PHP form that's tracked by mautic (embed tracking code); use your blog post code to repost to the Mautic form. In that code, grab $_COOKIES['mtc_id'] and send it in the root of the payload to Mautic (not in the mauticform array).

**Comment by virlatinus** [comment]
Tested it and it works. Unit tests also passed.

**Comment by diegofcv** [comment]
After upgrading to 2.10.1, Mautic started issuing errors like bellow. I got to this PR searching for the problem and found the SQL command that created the table in app/migrations/Version20170906161951.php. 

I needed to manually run the command to create the table, what solved the problem. 

For this to work, in the command, I needed to remove the line 54, because it seams that there is a "SQL" word lost there. Maybe this line prevented the command to work during the upgrade process.

[2017-10-09 18:21:07] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'UPDATE prefix_contact_merge_records SET contact_id = 28912 WHERE contact_id = 0':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'c1mkt.prefix_contact_merge_records' doesn't exist" at /var/www/clients/client1/web18/web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'UPDATE prefix_contact_merge_records SET contact_id = 28912 WHERE contact_id = 0':\n\nSQLSTATE[42S02]: Base
table or view not found: 1146 Table 'c1mkt.prefix_contact_merge_records' doesn't exist at /var/www/clients/client1/web18/web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'c1mkt.prefix_contact_merge_records' doesn't exist at /var/www/clients/client1/web18/web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:59, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table
'c1mkt.prefix_contact_merge_records' doesn't exist at /var/www/clients/client1/web18/web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:57)"} []

**Comment by escopecz** [comment]
Your database schema is out of date. Try steps in https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful

**Comment by sergiybond** [comment]
Is there a particular way to make this work? I am currently using Gravity Forms and use a WP Mautic Form Integrator to sync Gravity Forms with Mautic Forms through Oauth 2 API connection. I have upgraded to 2.11, making sure database schema is updated and have resynced the plugin settings from scratch, but Mautic is still not recognizing page hits for visitors who have been identified through a Gravity Form submission. It can't be an issue with tracking settings as it seems to be working well if Mautic native forms are used and page hits are reflected in the system.
Does this mean that the plugin creators need to update the plugin to utilize this new feature?
Thank you in advance for any reply - greatly appreciated.

**Comment by andrekutianski** [comment]
This problem still occurs in v2.15. I built a jQuery form submission for Mautic based on the gist of @escopecz available on https://gist.github.com/escopecz/136f62b66d526bc32006f0d2358a8e15. 
The form submission works perfectly, but Mautic creates a new contact instead of identifying the current anonymous contact.

**Pull request merged**
