### PR TITLE
Allow the use of = signs in tokens

### PR DESCRIPTION
**Pull request by aarohiprasad**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✅
| New feature/enhancement? (use the a.x branch)      | ✅
| Deprecations?                          | ❌
| BC breaks? (use the c.x branch)        | ❌
| Automated tests included?              |  ❌
| Related user documentation PR URL      |  
| Related developer documentation PR URL |  
| Issue(s) addressed                     | 

#### Description:

This PR adds enhances the regular expression to take "=" characters in account in tokens.

#### Steps to test this PR:

1. Create some tokens which have an '=' sign in the token name
1. Make sure tokens everywhere are being replaced as expected

#### Other areas of Mautic that may be affected by the change:
1. All places where tokens are replaced for emails.

[//]: # ( As applicable: )

### CODE REVIEW

**Comment by RCheesley** [comment]
@aarohiprasad could you please check the edits I made to the description make sense for this enhancement? It was not clear from me whether the = sign needs to be in the name of the token (which I assumed to be the case) or the text that is being inserted in the place of the token.

It is very helpful for users if you can provide direct examples that they can copy/paste in your test instructions - eg create a field called xxxxxx and then insert the field into an email using the token {xxxxxxx} - that way newbies will be much more able to help with the testing.

**Comment by RCheesley** [comment]
@aarohiprasad could you verify if the test instructions I wrote are correct? Thanks!

**Comment by escopecz** [comment]
@aarohiprasad could you also pull the tests that are in the original PR from Acquia?

**Review by escopecz — APPROVED** [review]
The new regex make sense and the tests are showing that it works as expected. Thank you! 👍

**Review by dongilbert — APPROVED** [review]

**Pull request merged**
