### PR TITLE
New Slot | Youtube thumbnail

### PR DESCRIPTION
**Pull request by moskoweb**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | N
| Related user documentation PR URL | N
| Related developer documentation PR URL | N
| Issues addressed (#s or URLs) | N
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Creation of a new slot for the email builder, in case he takes the thumbnail of a video on YouTube, and implements in an image element, which can also select the color of the play icon and add a title to the image.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create new email
2. Add slo YouTube Thumbnail

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2.

### CODE REVIEW

**Review by Strubbel94 — CHANGES_REQUESTED** [review]
image

The play button is cut in half at the top of the thumbnail. I suppose the button should be in the center of the thumbnail.
However the rest of the feature is working as intended.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@cla-bot check

@moskoweb thanks for changing the base branch, looks like there are some conflicts to be addressed before this can be tested.

As this is a new feature I'm going to tentatively suggest 3.2 which means you'll need to address the conflicting files and get it tested by no later than Sunday, 15th November to be considered for inclusion in the release. 

If we don't hear back from you within 14 days that you intend to carry this forward, we'll close the PR down.  Please let us know!

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@moskoweb looks like there are some code fixes needed in this PR, could you take a look please?

**Comment by moskoweb** [comment]
> @moskoweb looks like there are some code fixes needed in this PR, could you take a look please?

Can confirm if it worked, I did not understand if it was wrong or not.

**Pull request closed without merging**
