### PR TITLE
Add 404 option in configuration

### PR DESCRIPTION
**Pull request by dadarya0**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
1. Add an option in Configuration --> System Settings --> General Settings (with the Root URL selection), enabling the user to select a landing page to use as the customized 404 page just as they would with the root URL
2. Use the same tooltip as for the Mautic's root URL field and just replace "Root URL" with "404"
3. If the 404 page is unpublished then use the default 404 page

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. N/A 

#### Steps to test this PR:
1. Go to Components -> Landing pages -> Add new landing page
2. Go to Configuration --> System Settings --> General Settings
3. There should be field **404 page** with published landing pages for selection
4. Select any landing page and save
5. Now selected landing page should be display instead of 404 error page
6. if 404 page not defined or selected landing page is unpublished then display default 404 error page.

#### Other areas of Mautic that may be affected by the change:
1. 
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by mabumusa1** [comment]
@dadarya0 I will review this PR, may you please rebase to features branch?

**Comment by dadarya0** [comment]
> features

@mabumusa1 it is already rebased and up to date with features branch.

**Comment by dadarya0** [comment]
> @dadarya0 I will review this PR, may you please rebase to features branch?

@mabumusa1 it is already rebased and up to date with features branch.

image

**Comment by RCheesley** [comment]
@dadarya0 have you done a recent fetch from upstream and rebased from there, rather that origin/features? I am guessing that your personal fork (origin) may be out of date with mautic/mautic as we see a message suggesting that the PR is out of date with the features branch.

**Comment by dadarya0** [comment]
> @dadarya0 have you done a recent fetch from upstream and rebased from there, rather that origin/features? I am guessing that your personal fork (origin) may be out of date with mautic/mautic as we see a message suggesting that the PR is out of date with the features branch.

Thank @RCheesley it was out of date

**Review by kuzmany — APPROVED** [review]
Works as expected. Nice PR 👍

**Review by mabumusa1 — APPROVED** [review]
I tried this PR, it works as expected. 

let's get it merged

**Comment by RCheesley** [comment]
@all-contributors please add @dadarya0 for code

**Comment by RCheesley** [comment]
@all-contributors please add @mabumusa1 for userTesting

**Pull request merged**
