### PR TITLE
Utm tags

### PR DESCRIPTION
**Pull request by mqueme**
Please answer the following questions:

| Q             | A
| ------------- | ---
| Bug fix?      | n
| New feature?  | y
| BC breaks?    | n
| Deprecations? | n
| Fixed issues  |  n

## Description
This PR 
-Adds a new form action to save UTM tags when submitting a form, utm tags are saved from referer URL
-Saves UTM tags from URL in landing pages
-Displays query string parameters and UTM tags in contacts history, if saved from a form it displays the form id from form submitted

## Steps to test this PR
Download PR:
1. create a new form with a save utm tags action, when the form is submitted it should save UTM tags to contact if the url parameters are passed on to the form.
2. create a new page, it should save UTM tags that would come in the url to view the landing page.

UTM tags that are being recorded:
utm_campaign
utm_content
utm_medium
utm_source
utm_term

3. When you view contact history you will see UTM tag history in the timeline.

### CODE REVIEW

**Comment by bobcolner** [comment]
super excited about this feature.

**Comment by escopecz** [comment]
was composer.lock removed intentionally?

**Comment by escopecz** [comment]
This PR must contain some more code than what's needed for UTM tags. 6,420 additions is quite a lot. Any idea what it could be and how to get only the UTM code here?

**Comment by mqueme** [comment]
Let me rebranch and see.

**Comment by dongilbert** [comment]
This is the list of file modifications made when I merge the PR locally for testing

```
 app/bundles/FormBundle/Controller/PublicController.php      |   3 +-
 app/bundles/LeadBundle/Assets/js/lead.js                    |  28 +-
 app/bundles/LeadBundle/Config/config.php                    |   5 +
 app/bundles/LeadBundle/Controller/AjaxController.php        |  48 +++
 app/bundles/LeadBundle/Entity/Lead.php                      |  51 ++-
 app/bundles/LeadBundle/Entity/UtmTag.php                    | 435 ++++++++++++++++++++++++++
 app/bundles/LeadBundle/Entity/UtmTagRepository.php          |  50 +++
 app/bundles/LeadBundle/Event/LeadTimelineEvent.php          |   1 +
 app/bundles/LeadBundle/Event/LeadUtmTagsEvent.php           |  51 +++
 app/bundles/LeadBundle/EventListener/FormSubscriber.php     |  11 +
 app/bundles/LeadBundle/EventListener/LeadSubscriber.php     |  44 ++-
 .../Form/DataTransformer/UtmTagEntityModelTransformer.php   | 164 ++++++++++
 app/bundles/LeadBundle/Form/Type/ActionAddUtmTagsType.php   |  53 ++++
 app/bundles/LeadBundle/Helper/EventHelper.php               |  77 +++++
 app/bundles/LeadBundle/Helper/FormEventHelper.php           |   3 +
 app/bundles/LeadBundle/LeadEvents.php                       |  10 +
 app/bundles/LeadBundle/Model/LeadModel.php                  |  25 ++
 app/bundles/LeadBundle/Translations/en_US/messages.ini      |   8 +
 .../_formaction_properties_row.html.php                     |  20 ++
 .../Views/SubscribedEvents/Timeline/utmadded.html.php       | 124 ++++++++
 app/bundles/PageBundle/Model/PageModel.php                  |  46 ++-
 .../Views/SubscribedEvents/Timeline/index.html.php          |  81 +----
 app/bundles/PointBundle/Model/PointModel.php                |   2 +-
 app/migrations/Version20160504000000.php                    | 104 ++++++
```

So I'm not sure what's going on with the history here.

**Comment by escopecz** [comment]
While testing this PR, I get this error when I submit a form:

```
Call to a member function debug() on null" at app/bundles/FormBundle/Model/SubmissionModel.php line 545 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Call to a member function debug() on null at app/bundles/FormBundle/Model/SubmissionModel.php:545)"} []
[2016-06-20 18:20:55] mautic.ERROR: Error: Call to a member function debug() on null - in file app/bundles/FormBundle/Model/SubmissionModel.php - at line 545
```

This is not an issue of your code, but probably the refactoring. All the occurrences of `$logger` should be replaced with `$this->logger`. For example here:

https://github.com/mautic/mautic/blob/staging/app/bundles/FormBundle/Model/SubmissionModel.php#L545

I meant to create another PR for it, but then we'd have to wait for it to be merged to be able to test this PR. So I think it'd be easiest if you'd add it to this PR. What do you think?

**Comment by mqueme** [comment]
Yes I'll commit a fix.

**Pull request merged**
