### PR TITLE
Extended categories permissions

### PR DESCRIPTION
**Pull request by guestisp**
With this PR I add the support to customize categories with extended permissions (view own, view other, etc.). You can set specific permissions on all modules (emails, landing pages, etc.).

Steps to test:
- From administration panel, create a role with restricted categories permission (i.e. "view own" but not "view other") on a module (i.e. the landing pages module). Set the same permissions on the module, so a user with this role can access only on his own works.
- Assign this role to an user.
- Login with this user and create a landing page category.
- Login with your admin account and create a landing page category, too.
- Admin can see both categories but user can see only his own category.

### CODE REVIEW

**Comment by guestisp** [comment]
Is there anything wrong with this PR? Should I modify something in order to fix issues with Scrutinizer?

**Comment by alanhartless** [comment]
There are some conflicts so it would help if you pulled latest staging, merged into your categories-extended-permissions branch, resolve conflicts, then push to your branch to update the PR.  

But scrutinizer often errors out due to issues on their end; nothing to worry about.

Thanks!
Alan

**Comment by alanhartless** [comment]
@guestisp Would you be willing to merge the latest code into your branch and resolve the conflicts so we can test this? Thanks!

**Comment by guestisp** [comment]
@alanhartless Sorry for the delay but I was quite busy!

Anyway I see that in v1.2.1 categories were merged into one common place (very good) but this breaks my fixes. I will work on another PR to reintroduce extended category permissions on all modules ASAP.

Probably we can close this PR?

**Comment by dbhurley** [comment]
Closing per request.

**Pull request closed without merging**
