### PR TITLE
Fix Pipedrive mapping tab

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR get back ***** placeholder for secret keys of integrations based on PluginBundle
Also fixed hide contact/company mapping after click on apply button.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Set up Pipedrive integration https://docs.mautic.org/en/plugins/pipedrive
3. After PR see placeholder are ****** for secret fields (token, password)
image
4. After success set up, click on apply
5. Before PR mapping tabs should hide after apply, after PR works properly

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/9820"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
@kuzmany there are conflicts. Please take a look.

**Comment by npracht** [comment]
@luizeof as a user of Pipedrive, can i ask you to test this PR ?
Thanks !

**Comment by RCheesley** [comment]
Bumping from the release due to a lack of testing and tests not fully passing.

**Comment by jos0405** [comment]
Hi, I looked at the PR, and it seems to have some unfinished points:

1. The synch fields are not translated:
2.

**Comment by jos0405** [comment]
I looked at this PR, and found it incredibely valuable for Pipedrive integrations.
It seems to work, but I found some unfinished things:

1. Synch fields are not translated
image

2. @kuzmany What is a Timeline link?

**Comment by kuzmany** [comment]
@jos0405 It was fixed by https://github.com/mautic/mautic/pull/10649 in M 4.2.1.  I update branch and now it's correct
These tree items are special item in all integrations mapping tab. 
Sync of that 3 items is fixed by another PR https://github.com/mautic/mautic/pull/10991

**Review by jos0405 — APPROVED** [review]
Works perfectly

**Comment by npracht** [comment]
Hi there, as far as this plugin is outdated due to recent API BC from Pipedrive + the fact that Mautic Community policy is to not carry anymore third party plugins and move them slowly to marketplace, i'll close this issue.
You can still take advantage and contribute to a new Pipedrive plugin offered by a community contributor: https://github.com/Webmecanik/mautic-pipedrive-bundle

[See more on Mautic Community blog post](https://www.mautic.org/blog/integrator/exciting-news-new-integration-plugin-pipedrive-crm)

**Pull request closed without merging**
