### PR TITLE
Adding support for URL shortener in email

### LINKED ISSUE #2357: Allow URL shortening for emails
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? | x |
| Enhancement? |  |
## Description:

When I enter a po.st API URL i.e. `http://po.st/api/shorten?apiKey=xxxxx&format=txt&longUrl=` into the URL Shortener field in the Mautic configuration and I send an email using the Email channel, the URLs aren't shortened. Po.st allows for the use of your own domains as a shortener through CNAME records, so it'd be a great way to get nice looking short URLs for email links.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.0.1-dev |
| PHP version | 7.0.1 |
### Steps to reproduce:
1. Enter API URL in the URL Shortener field
2. Send an email and check the received URLs
### Log errors:

No relevant log errors.

### PR DESCRIPTION
**Pull request by christian-krieg**
* This feature was available only for links in SMS. However, there is legitimate interest for users to make this feature available also for links in E-Mails, especially when using a self-hosted URL shortener

* This feature is implemented such that if a link shortener URL is present, and the newly added configuration option to enable link shortening in e-Mails is set to "Yes", all tracking links and redirect links in e-mails are shortened using that link shortener URL

* This PR relates to the following discussions:

  * https://forum.mautic.org/t/url-shortener-how-and-where-does-it-work/16544
  * https://github.com/mautic/mautic/issues/2357
  * https://forum.mautic.org/t/allow-url-shortening-for-emails/17658
  * https://github.com/mautic/mautic/issues/39
  * https://github.com/mautic/mautic/issues/66
  * https://forum.mautic.org/t/how-to-track-clicks-in-sms/21267/5
  * https://github.com/mautic/mautic/pull/10280

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | []
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | Fixes #2357 #66 #39 -->

#### Steps to test this PR:

1) In the Mautic Configuration, navigate to 'System Settings' -> 'Miscellaneous Settings'.
2) Add a valid 'URL Shortener' URL as specified in the tool tip, and enable URL shortening in e-mails (set to "Yes")
3) Create a 'Test' segment
4) Create a test contact
5) Add the test contact to the 'Test' segment
6) Create a new segment e-mail, and assign it to the 'Test' segment
7) In the e-mail body, add some links. These links are transformed into trackable redirect links, which we wish to **shorten**
8) Save and close the e-mail
9) "Send" the e-mail. This sends the e-mail to the contacts in the 'Test' segment, while generating and shortening tracking links
10) Open the e-mail in the test user's mailbox, and verify that the tracking links have been shortened
11) Disable short links for e-mail in the Mautic configuration, and repeat 4)-9)
12) Verify that links in sent E-Mails are not shortened

### CODE REVIEW

**Comment by npracht** [comment]
Hi @christian-krieg !
Thanks a lot for your contribution. Few questions:
* Does that still use bitly?
* Does that update bitly API version? (see https://github.com/mautic/mautic/issues/8471)

**Comment by christian-krieg** [comment]
Hi @npracht ,

Also a big "Thank you" for your contributions to Mautic!

> * Does that still use bitly?

This PR just adds short URL support for E-Mail (in addition to SMS), while maintaining backwards compatibility by providing a switch in the Mautic configuration to turn the feature on/off. It doesn't change the way how Mautic interacts with the URL shortening service.

Therefore, the choice of shortening service is up to the user. I think the only requirement is that it supports authentication via query parameters, and that it returns the shortened URL as a simple text string. I didn't test with bit.ly, but I tested with [YOURLS](https://yourls.org/). It works for shortlink URLs of the following form  (to be provided via the Mautic configuration):

```
https://my.shortu.rl/yourls-api.php?signature=XXXXXXXXXX&action=shorturl&format=txt&url=
```

> * Does that update bitly API version? (see [update bit.ly api to v4 #8471](https://github.com/mautic/mautic/issues/8471))

No.

**Comment by npracht** [comment]
Okay thank a lot for your explanation.
I'll ask you few changes:
1. Can you add a piece of documentation of how to setup shortener ? Probably here you could change the text to say it is extended to emails as well and it supports "no matter" the provider" ?
https://github.com/mautic/user-documentation/blob/736cec2d03ae4b52e9d5b3c3d44110c4ded0de6d/docs/configuration/settings.rst?plain=1#L85
2. Can you rebase your PR against 5.x branch ? 4.x series will not integrate any feature anymore.
3. Can you check CS fixer ?

**Comment by christian-krieg** [comment]
Hi @npracht ,

I tried to rebase, but it was too time-consuming and painful. So instead, I migrated the changes to 5.x and created a new PR #12128.

> Okay thank a lot for your explanation. I'll ask you few changes:
> 
>     1. Can you add a piece of documentation of how to setup shortener ? Probably here you could change the text to say it is extended to emails as well and it supports "no matter" the provider" ?
>        https://github.com/mautic/user-documentation/blob/736cec2d03ae4b52e9d5b3c3d44110c4ded0de6d/docs/configuration/settings.rst?plain=1#L85
>

Done. 

> 
>     2. Can you rebase your PR against 5.x branch ? 4.x series will not integrate any feature anymore.
>

I tried to 'git rebase', but ended up manually migrating the feature to 5.x (it was too painful and time-consuming). 

>
>     3. Can you check CS fixer ?

Done. However, CS Fixer introduced non-functional changes to the commit, distorting it a bit.

**Pull request closed without merging**
