### PR TITLE
Editor changes

### PR DESCRIPTION
**Pull request by virlatinus**
| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Related user documentation PR URL | N/A
| Related developer documentation PR URL | N/A
| Issues addressed (#s or URLs) | N/A
| BC breaks? | N/A
| Deprecations? | N/A

#### Description:
This PR adds the following new slots to the editor:
- image card
- image+ caption
- social share
- social follow

It also adds a new dropdown in the editor to insert pages, forms, assets and tokens and enables changing image alignment.

#### Steps to test this PR:
1. Apply this PR
2. Create or Edit a new Landing Page or Email and try the new slot types
3. In the HTML editor try adding a token or asset from the dropdown list

#### Tips for testers:
To compile less files using grunt from the Mautic root directory:
```
npm install
grunt less
```
To rebuild javascript assets:
```
php app/console mautic:assets:generate
```

### CODE REVIEW

**Comment by escopecz** [comment]
I noticed a few issues:

1. The images in the "image + caption" and "image card" slots are not possible to edit. You'll have to init the Froala editor like the "image" slot does.
2. We'll have to update CSS to enable two-word slot types. Maybe expand them to 2 lines of text?
mautic-builder-slot-overflow
3. The image positioning is fixed Froala editor in https://github.com/mautic/mautic/pull/3476. Yours doesn't work if the image is wrapped in the link tag. So maybe remove it?
4. The card in the "image card" slot is as wide as the caption content. Shouldn't it be 100%?
5. The social buttons are somehow destroyed in the page preview. This is how it looks like in the builder:
screen shot 2017-03-01 at 15 00 02
And this is the preview:
screen shot 2017-03-01 at 15 00 16

**Comment by virlatinus** [comment]
I fixed the issues @escopecz mentioned:
1. The images in the "image + caption" and "image card" slots are not possible to edit. You'll have to init the Froala editor like the "image" slot does. **This is fixed**
2. We'll have to update CSS to enable two-word slot types. Maybe expand them to 2 lines of text? **The styles are there. Just need to rebuild the css**
3. The image positioning is fixed in the Froala editor in #3476. Yours doesn't work if the image is wrapped in the link tag. So maybe remove it? **I left the image align option to be consistent with the other image slot types**
4. The card in the "image card" slot is as wide as the caption content. Shouldn't it be 100%? **This is fixed**
5. The social buttons are somehow destroyed in the page preview. **This is fixed**

**Comment by escopecz** [comment]
1. fixed
2. Could you mention to the steps to test that testers must run `grunt compile-less` command? Or maybe run it and commit the CSS files? The labels are better with the styling.
3. If you want to leave it there, you should fix it if the image is a link (can be added via the Froala inline editor), because then the alignment doesn't work.
4. It doesn't seem to be fixed:
mautic-caption-width
5. I removed the share slot, added it again, but I still get all the share buttons floated to left and some broken HTML as at the screenshot I posted before.

**Comment by virlatinus** [comment]
Thanks @escopecz . I already made the changes you suggested.

**Comment by escopecz** [comment]
I tested the code mode slot. I typed in this code:
```
<a href="https://johnlinhart.com">John's</a>
```
And it was working until I selected another slot and tried to edit the code mode slot again. It won't load the codemirror editor. This error appears in the JS console:
```
Uncaught Error: Syntax error, unrecognized expression: input[type="radio"][data-slot-param="undefined"][value="linhart.com">John's</a>"]
    at Function.Sizzle.error (2.jquery.js:1440)
    at Sizzle.tokenize (2.jquery.js:2058)
    at Function.Sizzle [as find] (2.jquery.js:810)
    at jQuery.fn.init.find (2.jquery.js:2672)
    at Attr.<anonymous> (4.builder.js:904)
    at Function.each (2.jquery.js:374)
    at HTMLDivElement.<anonymous> (4.builder.js:897)
    at HTMLDivElement.dispatch (2.jquery.js:4410)
    at HTMLDivElement.elemData.handle (2.jquery.js:4096)
```
And if I inspect the slot:
```
<div data-slot="codemode" data-param-undefined="linhart.com&quot;>John's</a>">
                                    <div id="codemodeHtmlContainer">
    <p>Place your content here</p>
<a href="https://johnlinhart.com">John's</a></div>

                                <div data-slot-focus="true"></div></div>
```

**Comment by virlatinus** [comment]
I fixed the error with the code mode slot, but I disabled it so we can add it in the next release.

**Pull request merged**
