### PR TITLE
Fix for issue #5103 - Company/Accounts being duplicated on CRM Sync o…

### PR DESCRIPTION
**Pull request by stancel**
…f edited Company/Account

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? |  Yes
| New feature? |  No
| Automated tests included? | No
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) |  #5103 
| BC breaks? |  No
| Deprecations? |  No

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description: 
Like the reporter of #5103 we were seeing duplicate Mautic Company records being created when a SuiteCRM Account (Company) was edited. After debugging through this it was discovered that inside IdentifyCompanyHelper::identifyLeadsCompany class and method there was an else if statement for looking up a company name (not domain) through the MX records of the companyemail field. If anything was in that field it correctly skipped the next else if statement where the existing Mautic company would have been looked up by the 'companyname' field. 

The proper ordering should be to first lookup my the name then companyname fields. I believe that the else if check put in to lookup the domain should be assigned to the $companyDomain variable instead of the $companyName variable and have made that adjustment in this pull request as well.  Making these adjustments corrected the issue when testing in my local environment. Please let me know if you have any questions or feedback.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Activate SugarCRM integration (6.x) and map any applicable fields for account (companyname and companyemail at a minimum)
2. Add a SugarCRM Account (company) record and trigger the `mautic:integration:fetchleads --integration=Sugarcrm --time-interval="1 minute"` command
3. View that account/company added in Mautic
4. Edit the same SugarCRM Account (company) just added and trigger the `mautic:integration:fetchleads --integration=Sugarcrm --time-interval="1 minute"` command again
5. Observe that a duplicate Mautic Company is created versus updating the existing one.

#### Steps to test this PR:
1. First test the bug using the steps above
2. Pull the included commit into your repo
3. Follow the same testing steps above
4. Observe that the existing Mautic Company is properly updated versus a duplicate record being created

#### List deprecations along with the new alternative:
1. N/A

#### List backwards compatibility breaks:
1. None that I am aware of

### CODE REVIEW

**Comment by npracht** [comment]
✅  Just tested and it saved my life, Sugar company fetch is working again!
We had to add a small fix that manages the fact that mautic company email is unique --> See @Noa83 PR https://github.com/mautic/mautic/pull/5637.

Consequently, it also corrected https://github.com/mautic/mautic/issues/5617

**Comment by stancel** [comment]
Please let me know if there is anything else that I can do on this issue/pull request to make sure it gets included in a future release. Thanks.

**Comment by KaKite** [comment]
Tested, working as expected. Companies are fetching WITH and WITHOUT email addresses, no duplicates and attaching contacts in Mautic - GREAT WORK!!!

**Comment by Maxell92** [comment]
Hello @stancel,

could you please resolve conflict here? Rebase branch to actual staging ideally.

Thank you!

**Comment by mleffler** [comment]
@stancel We know this was important to you - are you able to reply so we can get this released?  Thank you!

**Comment by stancel** [comment]
Yes, I will take a look. Thanks

**Comment by alanhartless** [comment]
@stancel I think you're commit history diverged or something as it's wanting to push a lot of commits that are already in staging that are not associated with this PR. I think you need to try rebasing to staging. `git rebase staging` to clean this up.

**Comment by stancel** [comment]
Hi @alanhartless. That is what I did. I fetched from upstream, rebased the staging branch, then checkout out the pull request branch and ran "git rebase staging". I then resolved that the conflict with that one file/method and pushed to my pull request branch. Maybe I was supposed to go git rebase my-pull-request-branch while on git staging? (That would not update the needed branch for the pull request though). Please advise. Thanks.

**Comment by alanhartless** [comment]
Check to see what remote staging is pointing to. `git checkout staging` to see what it says. Should see something like `Your branch is up to date with 'origin/staging'.` origin should be whatever name you gave the remote to mautic/mautic.

**Comment by alanhartless** [comment]
Or try `git rebase origin/staging` while this PR's branch is checked out. Again, assuming origin is pointing to mautic/mautic.

**Comment by stancel** [comment]
Thanks. I'll take a look shortly and get back to you.

**Comment by dbhurley** [comment]
@stancel I'm going to have to push this to 2.14 (which shouldn't be too long in coming) - we're closing up 2.13.1 and this hasn't gotten any updates.

**Comment by stancel** [comment]
@dbhurley - please find the rebased updates pushed and let me know if anything else is needed. Thanks.

**Comment by alanhartless** [comment]
@stancel I think something is still off here. It shouldn't be including commits already in master. What branch did you rebase to?

**Pull request merged**
