### PR TITLE
Add toggle to links in CKE5, to add external target

### PR DESCRIPTION
**Pull request by LordRembo**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

[As mentioned in this ticket](https://github.com/mautic/mautic/issues/13362), there is a regression of functionality to do with Links in the text editor. While CKE4 had too many options (many unused), and we can't simply readd ALL the options (CKE5 has an entirely different structure for adding/changing stuff) it seems logical to at least be able to set `target`.
This aims to fix that by simply setting a decorator. 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. For a new Mautic install (or when using Gitpod), [make sure GrapesJS is installed](https://github.com/mautic/mautic/issues/13510) (recent merges of 5.x seems to have broken this)
3. If you already have a Mautic installed to test this PR in, I'd advise to run `npm install` followed by `npm run build` in the root of the project. Might be that ckeditor needs this.
4. Edit an Page or Email
5. Add a Text block, with some text
6. Select a bit of text and use the buttons of the text editor (CKE) to make it a link
7. You should now have a toggle option to make the target external (this prints `target="_blank"` in the html)

cke-link-target

### CODE REVIEW

**Review by kuzmany — CHANGES_REQUESTED** [review]
Does not work for me. On clicking the URL icon in the editor, nothing happens.

CPT2403081248-819x483

**Comment by LordRembo** [comment]
@kuzmany I'm seeing a while bunch of JS issues, and even more so after merging the latest from 5.x, will do a bit of digging for what's going on. Are you getting any JS errors in the browser console?

**Comment by LordRembo** [comment]
@kuzmany I can't even get to editing an email [because of this Froala issue](https://github.com/mautic/mautic/issues/13510) in Gitpod, so hopefully someone can give an insight on fixing/bypassing that first.

**Comment by LordRembo** [comment]
There's more JS issues coming from merging the 5.x branch (eg. I'm seeing ckeditor errors), which seems to have broken the whole Builder implementation. So until #13510 is fixed (and possibly other JS errors) this one's kinda hard to test.
Still, would be useful if someone did run this and check what kind of errors they see.

**Comment by LordRembo** [comment]
Looks like everything works, with the latest merges. For my local install though, I reinstalled the project because of whatever changes were merged in 5.x, were causing `500` errors.
I've also amended the description, to tell people to re-run `npm install` and `npm run build` in the root of the Mautic, because that might be needed on a not-so-fresh installation, to rebuild ckeditor.
Also had to install GrapesJS in the Plugins, [because of this error](https://github.com/mautic/mautic/issues/13510).

**Review by patrykgruszka — APPROVED** [review]
The code changes are minimal and look great. I've tested this on Gitpod and it works fine.

If you plan to test this on Gitpod, you will need to enable GrapesJS first, due to some issues on the latest 5.x branch:
1. Go to Plugins configuration and enable the GrapesJS
2. Remove cache `rm -rf var/cache/*`
3. Build cache `ddev exec bin/console c:c`

**Review by kuzmany — APPROVED** [review]
Works 👍

**Pull request merged**
