### PR TITLE
Resolves #3734

### LINKED ISSUE #3734: 500 Error when Trying to Filter Campaigns using "is:mine"
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:

A 500 Internal Server Error is thrown when trying to Filter Campaigns using "is:mine"

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6.3

### Steps to reproduce:
1. Go to "s/campaigns"
2. In the search filter enter "is:mine"
3. "500 Internal Server Error" is seen in Ajax Response

or

1. Go to "s/campaigns?search=is:mine"
2. "500 Internal Server Error" is seen

### Log errors: 

```
mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 107 near 'createdBy) =': Error: Invalid PathExpression. Must be a SingleValuedAssociationField." at /vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 107 near 'createdBy) =': Error: Invalid PathExpression. Must be a SingleValuedAssociationField. at /vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT c, cat FROM MauticCampaignBundle:Campaign c INDEX BY c.id LEFT JOIN c.category cat WHERE IDENTITY(c.createdBy) = 1 ORDER BY c.name ASC at /vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []
[2017-03-22 14:38:45] mautic.NOTICE: PHP Notice: Undefined variable: filterCommand - in file app/bundles/CampaignBundle/Entity/CampaignRepository.php - at line 311 [] []
```

### PR DESCRIPTION
**Pull request by devadattas**
Resolves #3734

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | No
| Issues addressed (#s or URLs) | #3734

### CODE REVIEW

**Comment by escopecz** [comment]
Hi! Thanks for those bug fixes! If there is no issue for your fix, there is no need to create one. Just document the issue in the PR description. It'll save some time for you as well as testers for testers.

**Comment by devadattas** [comment]
Hi John,

Thanks for the tip. Will take care of this for next patches.

I was hoping, having issues and resolution keeps things a bit more
organized.

**Comment by alanhartless** [comment]
Looking at the fix - should this be addressed at https://github.com/mautic/mautic/blob/bf74abe71dea5640f4eafd11252a8aca0e4d3908/app/bundles/CoreBundle/Entity/CommonRepository.php#L1077-L1077 instead? I'm pretty sure that createdBy is not an association anywhere and thus removing the use of IDENTITY() would fix it for everywhere is:mine is used.

**Comment by alanhartless** [comment]
Closing in favor of https://github.com/mautic/mautic/pull/5450

**Pull request closed without merging**
