### PR TITLE
Add html custom field

### PR DESCRIPTION
**Pull request by dadarya0**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | N
| New feature/enhancement? (use the a.x branch)      | Y
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | Y 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR implements a new HTML custom type field.
It allows to store html data and use it in emails, dynamic content and view/edit it in Mautic just as any other custom field.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a new custom field with type HTML for Contacts.
3. Create a new contact, add something like `<h1>Prague</h1>` to the field you've just created. Save the contact.
4. View that contact in Mautic. Make sure you see the `<h1>Prague</h1>` text in the details tray.
5. Go to to the audit log for that contact.
6. Make sure you see the `<h1>Prague</h1>` text in the audit log.
7. Create contact via API, send value `<h1>Prague</h1>` in your html field
8. Open the contact in Mautic. Make sure you see the `<h1>Prague</h1>` text.
9. Create a segment email. Insert a token in that email that is using the html field you created on step 3. LIke {contactfield=your_html_field}
10. Send an email to yourself.
11. You should see unescaped html code in the email.

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
I see no issue with these code changes 👍

**Comment by kuzmany** [comment]
What about?
Shouldn't we create migration and remove it then?
image

**Comment by escopecz** [comment]
@kuzmany good point! I wasn't aware about this.

@dadarya0 what would you suggest to do? Revert https://github.com/mautic/mautic/pull/8706 in this PR and add a migration for fields that have the "allow migration" option to convert them from `textarea` to `html` in this PR or create a separate PR for that once this one is merged?

**Comment by dadarya0** [comment]
> @kuzmany good point! I wasn't aware about this.
> 
> @dadarya0 what would you suggest to do? Revert #8706 in this PR and add a migration for fields that have the "allow migration" option to convert them from `textarea` to `html` in this PR or create a separate PR for that once this one is merged?

I think we can have both for now and we can revert https://github.com/mautic/mautic/pull/8706 later as it is not a blocker for now.

**Review by escopecz — APPROVED** [review]
No issues in the code I can see. Thanks! 👍

**Comment by Galokh66** [comment]
Tested and verified unescaped html code in the email.
Screenshot 2024-02-27 at 1 39 10 AM
Screenshot 2024-02-27 at 1 47 09 AM
Screenshot 2024-02-27 at 12 40 56 PM
Screenshot 2024-02-27 at 12 41 56 PM

**Review by Galokh66 — APPROVED** [review]

**Comment by RCheesley** [comment]
> we can revert #8706 later as it is not a blocker for now.

Was this ever done? If not, this is going to be somewhat confusing for the user, no?

**Comment by escopecz** [comment]
I'm afraid we can do it in M6 only. For now there will be 2 ways how to create a HTML custom field.

**Pull request merged**
