### PR TITLE
Reports: Group by date

### PR DESCRIPTION
**Pull request by dongilbert**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Related user documentation PR URL | Pending
| Related developer documentation PR URL | Pending
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

This PR both adds a feature and fixes a bug.

##### Feature
Previously, when grouping by a datetime field, the results from the report were... unimpressive to say the least. Since the grouping would always take into account the value of the field down to the microsecond (in PHP 7.1+, to the second in previous versions), the data didn't offer much insight into the number of emails sent out per day. There was a widget that made that specific data available, but now you can build it into your report and access that metric outside of just email sends per day.

[//]: # ( As applicable: )
#### Steps to test this PR:
1. Create an email report with `Date Sent` as the column, `Date Sent` as the `Group by`, and add a calculated field of `COUNT` on `Contact email`. 
2. On the `Graphs` tab, add the `Emails sent (line graph)`
3. Save and Close
4. This should produce a report that gives you the total number of contacts reached per day
5. Verify that the report counts are correct by validating the values in the `COUNT Contact Email` column with the values in the `Emails sent` graph.

### CODE REVIEW

**Comment by escopecz** [comment]
I applied this PR, cleared the cache and then I wanted to open the "All emails" report I had already, but I got this error instead:
```
Internal Server Error - An exception occurred while executing 'SELECT COUNT(*) as count FROM emails e LEFT JOIN emails vp ON vp.id = e.variant_parent_id LEFT JOIN categories c ON c.id = e.category_id LEFT JOIN (SELECT COUNT(cut2.channel_id) AS trackable_count, SUM(cut2.hits) AS hits, SUM(cut2.unique_hits) AS unique_hits, cut2.channel_id FROM channel_url_trackables cut2 WHERE cut2.channel = 'email' GROUP BY cut2.channel_id) cut ON e.id = cut.channel_id LEFT JOIN lead_donotcontact dnc ON e.id = dnc.channel_id and dnc.channel='email' and dnc.reason=1 GROUP BY e.id, e.subject, cut.hits, cut.unique_hits, e.read_count, CONCAT(ROUND((e.read_count/e.sent_count)*100, 1),'%'), e.sent_count, CONCAT(ROUND((COUNT(DISTINCT dnc.id)/e.sent_count)*100, 1),'%'), COUNT(DISTINCT dnc.id), CONCAT(ROUND(cut.unique_hits/(e.sent_count)*100, 1),'%'), CONCAT(ROUND(cut.hits/(e.sent_count)*100, 1),'%')': SQLSTATE[HY000]: General error: 1111 Invalid use of group function

at /app/bundles/ReportBundle/Model/ReportModel.php:631
```

**Comment by escopecz** [comment]
It's not throwing the SQL error now, but I can see this:
screen shot 2017-06-23 at 18 44 19

**Comment by matishaladiwala** [comment]
works for me!

**Comment by matishaladiwala** [comment]
existing reports work now too. Approved.

**Comment by mqueme** [comment]
This didn't work for me, the count column doesn't show anything for me. Could it be that I am testing on my localhost so stats may not be 100% accurate?

**Pull request merged**
