### PR TITLE
add automatically plain text version to email if not set

### PR DESCRIPTION
**Pull request by lukassykora**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Yes
| Automated tests included? | Yes
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
If the plain text is empty, generate it automatically.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Go to /s/emails
3. Create a new email and leave the plain text empty
4. Send example
5. The mail should have the plain text alternative (you can see in mailhog)

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by npracht** [comment]
@lukassykora can you please check travis ?

**Review by dennisameling — APPROVED** [review]
Works as described, the plain text is generated correctly:

image

Code also looks good.

Thanks @lukassykora! 🚀

**Review by kuzmany — APPROVED** [review]
Works as describe.
This is cool PR. 
Maybe we should update tooltip with info about auto generate plain text version If left empty.

image

**Comment by RCheesley** [comment]
I would like us to add this useful information to the documentation - @mautic/education-team can follow up next week with a PR for that.

@kuzmany I think the tooltip would be helpful but not necessary - we could make a separate issue/PR for that I feel, it's a small tweak so it would be a nice first issue/L1 issue for someone.

**Pull request merged**
