### PR TITLE
remove debug lines

### LINKED ISSUE #9572: possible bug in resend code in retry times handling
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When an email send failes, it gets resent. Should be tried a few times.
https://github.com/mautic/mautic/blob/features/app/bundles/EmailBundle/EventListener/EmailSubscriber.php
The `onEmailResend` method contains an odd condition:
```
if (true || $retries > 3) {
                    //tried too many times so just fail
```

This looks like a debugging condition left in the code. 
Or is it deliberate?

| Q   | A
| --- | ---
| Mautic version |  3.2
| PHP version | -
| Browser | -

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by pety-dc**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #9572 

#### Description:
Issue is self-explanatory 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2.

### CODE REVIEW

**Review by kuzmany — DISMISSED** [review]
👍

**Comment by npracht** [comment]
@kuzmany any idea why tests are failing ?

**Comment by RCheesley** [comment]
@pety-dc please can you make PRs on the correct branch according to the docs [here](https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#choose-the-right-branch)?

At the moment that is Features, as the next release coming up is 4.0 - you can always find that info in the [Milestones](https://github.com/mautic/mautic/milestones).

I will change the base to features - please can you rebase the PR accordingly?

**Comment by pety-dc** [comment]
@RCheesley 
I'm sorry, before submitting the PR I read the docs and AFAIR it said that bug fixes should be done against that lowest maintained branch as those are regularly merged into the feautures branch by the maintener teams. It seems however can't find these lines now.

**Comment by nickveenhof** [comment]
I think this can be closed as it is no longer relevant imho? Thanks for contributing though!

**Pull request closed without merging**
