### PR TITLE
Prevent campaign failures for unpublished emails and failure to move stage

### LINKED ISSUE #8521: Campaign "change contact stage" event does not work due to use of a non-existing method
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
This bug has apparently been around for a very long time according to a code trace. But when trying to change the stage through a campaign action, an exception is thrown due to the use of a `$event->getName()` where `getName()` is not defined. 

| Q   | A
| --- | ---
| Mautic version | 2.16/3.0
| PHP version | 7.3
| Browser | chrome

### Steps to reproduce
1. Create a stage
2. Create a campaign with an action to "change contact stage"
3. Execute the campaign
4. Note the error
 
### Log errors
```
[2020-03-05 00:48:17] mautic.NOTICE: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Mautic\CampaignBundle\Event\CampaignExecutionEvent::getName() (uncaught exception) at app/bundles/StageBundle/EventListener/CampaignSubscriber.php line 90 while running console command `mautic:campaigns:trigger`
[stack trace]
#0 vendor/symfony/event-dispatcher/Debug/WrappedListener.php(115): Mautic\StageBundle\EventListener\CampaignSubscriber->onCampaignTriggerActionChangeStage(Object(Mautic\CampaignBundle\Event\CampaignExecutionEvent), 'mautic.stage.on...', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#1 vendor/symfony/event-dispatcher/EventDispatcher.php(214): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Mautic\CampaignBundle\Event\CampaignExecutionEvent), 'mautic.stage.on...', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#2 vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'mautic.stage.on...', Object(Mautic\CampaignBundle\Event\CampaignExecutionEvent))
#3 vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(143): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('mautic.stage.on...', Object(Mautic\CampaignBundle\Event\CampaignExecutionEvent))
#4 app/bundles/CampaignBundle/Executioner/Dispatcher/LegacyEventDispatcher.php(225): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('mautic.stage.on...', Object(Mautic\CampaignBundle\Event\CampaignExecutionEvent))
#5 app/bundles/CampaignBundle/Executioner/Dispatcher/LegacyEventDispatcher.php(119): Mautic\CampaignBundle\Executioner\Dispatcher\LegacyEventDispatcher->dispatchEventName('mautic.stage.on...', Array, Object(Mautic\CampaignBundle\Entity\LeadEventLog))
#6 app/bundles/CampaignBundle/Executioner/Dispatcher/ActionDispatcher.php(110): Mautic\CampaignBundle\Executioner\Dispatcher\LegacyEventDispatcher->dispatchCustomEvent(Object(Mautic\CampaignBundle\EventCollector\Accessor\Event\ActionAccessor), Object(Doctrine\Common\Collections\ArrayCollection), NULL, Object(Mautic\CampaignBundle\Event\PendingEvent))
#7 app/bundles/CampaignBundle/Executioner/Event/ActionExecutioner.php(67): Mautic\CampaignBundle\Executioner\Dispatcher\ActionDispatcher->dispatchEvent(Object(Mautic\CampaignBundle\EventCollector\Accessor\Event\ActionAccessor), Object(Mautic\CampaignBundle\Entity\Event), Object(Doctrine\Common\Collections\ArrayCollection))
#8 app/bundles/CampaignBundle/Executioner/EventExecutioner.php(201): Mautic\CampaignBundle\Executioner\Event\ActionExecutioner->execute(Object(Mautic\CampaignBundle\EventCollector\Accessor\Event\ActionAccessor), Object(Doctrine\Common\Collections\ArrayCollection))
#9 app/bundles/CampaignBundle/Executioner/EventExecutioner.php(172): Mautic\CampaignBundle\Executioner\EventExecutioner->executeLogs(Object(Mautic\CampaignBundle\Entity\Event), Object(Doctrine\Common\Collections\ArrayCollection), Object(Mautic\CampaignBundle\Executioner\Result\Counter))
#10 app/bundles/CampaignBundle/Executioner/EventExecutioner.php(245): Mautic\CampaignBundle\Executioner\EventExecutioner->executeForContacts(Object(Mautic\CampaignBundle\Entity\Event), Object(Doctrine\Common\Collections\ArrayCollection), Object(Mautic\CampaignBundle\Executioner\Result\Counter), false)
#11 app/bundles/CampaignBundle/Executioner/KickoffExecutioner.php(222): Mautic\CampaignBundle\Executioner\EventExecutioner->executeEventsForContacts(Object(Doctrine\Common\Collections\ArrayCollection), Object(Doctrine\Common\Collections\ArrayCollection), Object(Mautic\CampaignBundle\Executioner\Result\Counter))
#12 app/bundles/CampaignBundle/Executioner/KickoffExecutioner.php(122): Mautic\CampaignBundle\Executioner\KickoffExecutioner->executeOrScheduleEvent()
#13 app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php(372): Mautic\CampaignBundle\Executioner\KickoffExecutioner->execute(Object(Mautic\CampaignBundle\Entity\Campaign), Object(Mautic\CampaignBundle\Executioner\ContactFinder\Limiter\ContactLimiter), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php(328): Mautic\CampaignBundle\Command\TriggerCampaignCommand->executeKickoff()
#15 app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php(277): Mautic\CampaignBundle\Command\TriggerCampaignCommand->triggerCampaign(Object(Mautic\CampaignBundle\Entity\Campaign))
#16 vendor/symfony/console/Command/Command.php(255): Mautic\CampaignBundle\Command\TriggerCampaignCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 vendor/symfony/console/Application.php(1001): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 vendor/symfony/framework-bundle/Console/Application.php(86): Symfony\Component\Console\Application->doRunCommand(Object(Mautic\CampaignBundle\Command\TriggerCampaignCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 vendor/symfony/console/Application.php(255): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Mautic\CampaignBundle\Command\TriggerCampaignCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 vendor/symfony/framework-bundle/Console/Application.php(74): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 vendor/symfony/console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 bin/console(41): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main}  
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by alanhartless**
closes https://github.com/mautic/mautic/issues/8521
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/8521
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
If an email is unpublished or if a contact fails to move a stage, the event triggered a failure that would lead to notifications to users and campaigns being unpublished. This fixes that. 

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a campaign that sends an email that is delayed by a few minutes
2. Unpublish the email
3. Execute the campaign
4. Notice that the campaign will unpublish
5. Add a bunch of contacts to a stage
6. Create a campaign that moves a contact into that same stage
7. The campaign will unpublish

#### Steps to test this PR:
1. Repeat the above and this time the campaign will not unpublish but the errors will be recorded in the contact's timeline

### CODE REVIEW

**Comment by npracht** [comment]
@alanhartless, again Travis :)

**Comment by alanhartless** [comment]
Thanks @npracht! Not sure why my git hook is not working. Will see if I can get that resolved.

**Comment by RCheesley** [comment]
Trying to replicate this in order to test the fix, but I don't see the campaign being unpublished as expected.

I get a bunch of notifications that the campaign event was not able to be executed, but the campaign is still published.

screenshot-local mautictest-2019 10 16-13_21_26

I had the same for the second test with the stage (although without any notifications this time) - the actions complete but the campaign remains published.

screenshot-local mautictest-2019 10 16-13_25_45

Maybe this issue has been resolved already?

**Review by adiux — CHANGES_REQUESTED** [review]
I followed the steps on how to reproduce the bug. It worked as expected until the point that there was no notification triggered. Based on the previous behaviour this should be the case.

image

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by npracht** [comment]
according to https://github.com/mautic/mautic/issues/8521 it is relevant for M3.
Need rebase against M3 branch now :)

**Comment by npracht** [comment]
Closing in favor of #8659

**Pull request closed without merging**
