### PR TITLE
Bugfix 12063 - 500 Error when changing tag in a Contact and clicking save&close [4.x]

### LINKED ISSUE #12063: 500 Error when changing tag and save/close
### Mautic Version

4.4.x series

### PHP version

7.4.33

### What browsers are you seeing the problem on?

Chrome

### What happened?

I’m receiving a 500 error saving a contact via the GUI…

I’ve created a quick screen share to demonstrate the issue I’m facing:

[https://streamable.com/b3jzax](https://streamable.com/b3jzax)

### How can we reproduce this issue?

Step 1:  Add contact
Step 2:  Add tag to contact
Step 3: Save
Step 4: Swap tag fpr a different tag
Step 5: Save & Close

This results in a 500 response from the server.  After this the contact cannot be viewed.  The view contact page then returns a 500 error.

### Relevant log output

```shell
There is nothing in the log related to the issue described.
```

### Code of Conduct

- [x] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by LordRembo**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ yes]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #12063 

#### Description:

This fix if for 4.x ([5.x version is here](https://github.com/mautic/mautic/pull/12106))

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. You need a Contact that has 1 tag
3. Edit the Contact and change the tag
4. Hit Save&Close
5. You should now be able to reopen the Contact (that wasn't possible before, gave a JS error or server error)
6. If you open the Audit log, you should see the 'old' and 'new' tag listed in the latest entry

### CODE REVIEW

**Comment by MadlenF** [comment]
Works as described!

**Review by RCheesley — DISMISSED** [review]
Works as expected - thanks for the PR! 🚀

**Comment by RCheesley** [comment]
@LordRembo this will need to be rebased on the 4.4 branch for the next patch release.

**Comment by LordRembo** [comment]
hmmm, just tried to rebase on 4.4 and resolved conflicts locally, but it' still showing conflicts in here.

**Comment by mollux** [comment]
@LordRembo I can help here if you want (tomorrow or thursday)

**Comment by LordRembo** [comment]
@mollux yeah, maybe best on Thursday then, so we can get this thing over and done with, seeing as we're both at the office.

**Comment by LordRembo** [comment]
@RCheesley it should be okay now, rebased on 4.4

**Review by RCheesley — APPROVED** [review]
Tested after rebase, all good! Thanks @LordRembo and sorry for the faffing about with bases!

**Comment by LordRembo** [comment]
@RCheesley no worries!

**Pull request merged**
