### PR TITLE
Support for emoji in emails

### PR DESCRIPTION
**Pull request by tejasync**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | features
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | N.A.
| Related developer documentation PR URL | N.A.
| Issue(s) addressed                     | N.A.

#### Description:
The issue with email subject is that it is converted to a token and so fails with email_stats.tokens on send because that column is not utf8mb and thus does not support emojis natively.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Execute query `ALTER TABLE <prefix>email_stats CHANGE COLUMN tokens tokens LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '(DC2Type:array)';` to change the email_stats:token column's charset to utf8.
2. Create email with emoji in subject (Use this emoji: https://emojipedia.org/worm/)
2. It is observed that email is not received when sent (use campaign send email action to send emails)

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Revert the query above if it was executed using `ALTER TABLE <prefix>email_stats CHANGE COLUMN tokens tokens LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL COMMENT '(DC2Type:array)';` to change charset to utf8mb4.
3. Follow steps to reproduce, email should be sent and received.

### CODE REVIEW

**Review by kuzmany — DISMISSED** [review]
Yes, this encoding change to  `utf8mb4_unicode_ci` we already use.
I tested migrations. And looks good 👍

**Comment by tejasync** [comment]
@cla-bot check

**Comment by jazeabby** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

Folks it's a manual process to add people to the list and you're just too darn fast! Added now!

**Review by jos0405 — APPROVED** [review]
This works. Some of our installations came with utf8mb4_unicode_ci, so I guess this has changed sometime in the past.
But those without were definetly cured by this migration and can send emojies now in subject line AND in email body.
image

**Comment by RCheesley** [comment]
This PR needs to be rebased, it's on the 4.0 branch. @ts-navghane would you be able to take a look please? Or if it's quicker, just make a new PR on the correct branch.

**Comment by tejasync** [comment]
@RCheesley Will make a new PR and link it to this, that'll be much quicker.

**Comment by tejasync** [comment]
New PR in favour of this PR: https://github.com/mautic/mautic/pull/10844

**Pull request merged**
