### PR TITLE
Email sender name not changing

### LINKED ISSUE #9751: Email sender name not changing
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.3.1
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create an email
2.  Change the sender to your desired sender name
 
### Log errors
Hello Guys,
I am new to mautic and I am having errors on the Sender Name, before the update on 3.3.1
Sender name was changing to what I want but after the update it would always send the email on a default sender name
Please help me identify what is the problem here. Thanks.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by MarketSmart**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | features
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Issue(s) addressed                     | Fixes #9751 

#### Description:
Using an already set variable from instead of systemFrom to have the from built for us and avoid additional changes.

#### Steps to reproduce:
Create an email
Change the sender to your desired from name and leave from address empty
Send the email and it will arrive as system default instead of set from name

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create an email
3. Change the sender to your desired from name and leave from address empty
4. Send the email and it should arrive with from name but from email will be system default
5. Additionally when leaving both empty it will be system default

### CODE REVIEW

**Comment by RCheesley** [comment]
The codecov report is including an unrelated file (not sure why!) so that can be disregarded! 

Thanks for making the PR @MarketSmart - have you tested this with different mail transports or just locally?

**Comment by MarketSmart** [comment]
> The codecov report is including an unrelated file (not sure why!) so that can be disregarded!
> 
> Thanks for making the PR @MarketSmart - have you tested this with different mail transports or just locally?

I tested in house with custom Mailgun plugin, Kafka plugin, Amazon SES SMTP and Other SMTP server mailers.

**Comment by RCheesley** [comment]
Wow thanks - that's awesome! :)

**Comment by MarketSmart** [comment]
I feel confident enough that im deploying a fork of this to our production systems. I will let you know in a week or so if all is well. We have hundreds of deployments of mautic. Anything else i can do in the meantime to get this PR merged @RCheesley ?

**Comment by RCheesley** [comment]
We need someone from outside your company to review the code and test - here are the requirements: https://contribute.mautic.org/community-structure/governance/code-governance#requirements-for-merging-a-tier-1-pr

**Review by luguenth — APPROVED** [review]
Hey just checked this PR and used Gmail for it. Works like a charm, nice work :)

**Review by LeonOltmanns — APPROVED** [review]
Tested the PR. Fixed the issue. Good job! :)

**Comment by RCheesley** [comment]
@all-contributors please add @MarketSmart for code

**Comment by RCheesley** [comment]
@all-contributors please add @luguenth for userTesting

**Comment by RCheesley** [comment]
@all-contributors please add @oltmanns-leuchtfeuer for userTesting

**Review by blankdigital — COMMENTED** [review]
Finally, perfectly working, thank you!

**Comment by jabaco** [comment]
This issue is still present when using amazona ses api (From name is always email account is amazon ses...) impossible to change via default sender in configuration or per email basis....

**Pull request merged**
