### PR TITLE
Support for PHP 7.2

### PR DESCRIPTION
**Pull request by StudioMaX**
Reopened https://github.com/mautic/mautic/pull/6599, https://github.com/mautic/mautic/pull/6848

---

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | Already covered
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | #5769 (closed)
| Related PR | #5936
| BC breaks? | N
| Deprecations? | Y

#### Description:
Since there are no fixes for a long time in [original PR](https://github.com/mautic/mautic/pull/5936) to fix the compatibility with PHP 7.2 and because Travis still reports the existing errors, I decided to open a new Pull Request.

It's about time to prepare Mautic for PHP 7.2. This PR upgrades the maximum PHP contstants and fixes PHP warning about Mcrypt constants.

# WARNING
**If you have some plugin credentials stored by Mcrypt they cannot be decrypted by OpenSSL. Make sure you have both libraries installed and enabled. Then re-save all plugins so the credentials are encrypted by OpenSSL and then you can upgrade to PHP 7.2.**

#### Steps to reproduce the bug:
1. Upgrade your PHP to 7.2.
2. You'll see a message that this version is not supported.
3. Hack `MAUTIC_MAXIMUM_PHP` in VersionCheckMiddleware.php to `7.2.999` to overcome the message.
4. Clear the cache.
5. In dev mode you'll see warning everywhere.

#### Steps to test this PR:
1. Apply this PR
2. No warnings are visible. Everything looks normal and little faster :)

#### List deprecations along with the new alternative:
1. Mcrypt extension does not exist on PHP 7.2. Use OpenSSL instead.

### CODE REVIEW

**Comment by Woeler** [comment]
I still see only one commit. Can you please rebase this to the current staging branch?

**Comment by StudioMaX** [comment]
Actually it was already _rebased_ on staging (not _merged_). Tree before this commit: https://github.com/mautic/mautic/commits/37903fe1a9a696ccb2845ed15a6e71e2a735a644

**Comment by Woeler** [comment]
I will discuss thus PR during the core meeting tomorrow. I want this in.

**Comment by StudioMaX** [comment]
Guys, did you find any reason for failing tests? If so, commit to this PR please, it's open for maintainters. Because I run tests without errors.

**Comment by alanhartless** [comment]
Seems it has conflicts now. It looked ok last time till it was merged into staging then travis blew up. We can merge after the conflicts are resolved to see what happens. But if Travis blows up again, someone needs to figure out why.

**Comment by StudioMaX** [comment]
Rebased and fixed conflicts.
> But if Travis blows up again, someone needs to figure out why.

I'm pretty sure that Travis will break again on the tests. Could you test this branch on your local environment?

**Comment by rseffner** [comment]
On monday official PHP 7.0 support ends. Then at the end of the year the same with PHP 5.x. What about Mautic then? I think PHP 7.2 support needs to be one of the first points at development todo.

**Comment by escopecz** [comment]
This is what I get on my local with php 7.1:
```
~/dev/mautic (StudioMaX-php-72) $ bin/phpunit -d memory_limit=2048M --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist--fail-on-warning
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

.........FERROR 1364 (HY000) at line 40: Field 'is_preference_center' doesn't have a default value
FERROR 1364 (HY000) at line 40: Field 'is_preference_center' doesn't have a default value
FERROR 1364 (HY000) at line 40: Field 'is_preference_center' doesn't have a default value
FERROR 1364 (HY000) at line 40: Field 'is_preference_center' doesn't have a default value
FERROR 1364 (HY000) at line 40: Field 'is_preference_center' doesn't have a default value
FERROR 1364 (HY000) at line 40: Field 'is_preference_center' doesn't have a default value
..............................................   61 / 1203 (  5%)
...........................................FF.............F..  122 / 1203 ( 10%)
..........................................................PHP Notice - Use of undefined constant SORTARRIVAL - assumed 'SORTARRIVAL' - in file /Users/jan/dev/mautic/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php - at line 1223
PHP Notice:  Use of undefined constant SORTARRIVAL - assumed 'SORTARRIVAL' in /Users/jan/dev/mautic/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php on line 1223
PHP Stack trace:
PHP   1. {main}() /Users/jan/dev/mautic/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /Users/jan/dev/mautic/vendor/phpunit/phpunit/phpunit:52
PHP   3. PHPUnit_TextUI_Command->run() /Users/jan/dev/mautic/vendor/phpunit/phpunit/src/TextUI/Command.php:116
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /Users/jan/dev/mautic/vendor/phpunit/phpunit/src/TextUI/Command.php:186
PHP   5. PHPUnit_Framework_TestSuite->run() /Users/jan/dev/mautic/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:517
PHP   6. PHPUnit_Framework_TestSuite->run() /Users/jan/dev/mautic/vendor/phpunit/phpunit/src/Framework/TestSuite.php:733
PHP   7. PHPUnit_Framework_TestSuite->run() /Users/jan/dev/mautic/vendor/phpunit/phpunit/src/Framework/TestSuite.php:733
PHP   8. Mautic\ConfigBundle\Tests\Form\Helper\RestrictionHelperTest->run() /Users/jan/dev/mautic/vendor/phpunit/phpunit/src/Framework/TestSuite.php:733
PHP   9. PHPUnit_Framework_TestResult->run() /Users/jan/dev/mautic/vendor/phpunit/phpunit/src/Framework/TestCase.php:868
PHP  10. Mautic\ConfigBundle\Tests\Form\Helper\RestrictionHelperTest->runBare() /Users/jan/dev/mautic/vendor/phpunit/phpunit/src/Framework/TestResult.php:686
PHP  11. Mautic\ConfigBundle\Tests\Form\Helper\RestrictionHelperTest->setUp() /Users/jan/dev/mautic/vendor/phpunit/phpunit/src/Framework/TestCase.php:909
PHP  12. Mautic\ConfigBundle\Tests\Form\Helper\RestrictionHelperTest->setUp() /Users/jan/dev/mautic/vendor/symfony/form/Test/TypeTestCase.php:31
PHP  13. Mautic\ConfigBundle\Tests\Form\Helper\RestrictionHelperTest->getExtensions() /Users/jan/dev/mautic/vendor/symfony/form/Test/FormIntegrationTestCase.php:31
PHP  14. PHPUnit_Framework_MockObject_MockBuilder->getMock() /Users/jan/dev/mautic/app/bundles/ConfigBundle/Tests/Form/Helper/RestrictionHelperTest.php:254
PHP  15. PHPUnit_Framework_MockObject_Generator->getMock() /Users/jan/dev/mautic/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/MockBuilder.php:117
PHP  16. PHPUnit_Framework_MockObject_Generator->generate() /Users/jan/dev/mautic/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php:263
PHP  17. PHPUnit_Framework_MockObject_Generator->generateMock() /Users/jan/dev/mautic/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php:574
PHP  18. PHPUnit_Framework_MockObject_Generator->generateMockedMethodDefinitionFromExisting() /Users/jan/dev/mautic/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php:827
PHP  19. PHPUnit_Framework_MockObject_Generator->getMethodParameters() /Users/jan/dev/mautic/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php:1024
PHP  20. ReflectionParameter->getDefaultValue() /Users/jan/dev/mautic/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php:1223
FE.  183 / 1203 ( 15%)
.............................................................  244 / 1203 ( 20%)
.............................................................  305 / 1203 ( 25%)
.............................................................  366 / 1203 ( 30%)
..................................EE....................PHP Notice:  Use of undefined constant SORTARRIVAL - assumed 'SORTARRIVAL' in /Users/jan/dev/mautic/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php on line 1223
PHP Stack trace:
PHP   1. {main}() /Users/jan/dev/mautic/vendor/phpunit/phpunit/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /Users/jan/dev/mautic/vendor/phpunit/phpunit/phpunit:52
PHP   3. PHPUnit_TextUI_Command->run() /Users/jan/dev/mautic/vendor/phpunit/phpunit/src/TextUI/Command.php:116
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /Users/jan/dev/mautic/vendor/phpunit/phpunit/src/TextUI/Command.php:186
PHP   5. PHPUnit_Framework_TestSuite->run() /Users/jan/dev/mautic/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:517
PHP   6. PHPUnit_Framework_TestSuite->run() /Users/jan/dev/mautic/vendor/phpunit/phpunit/src/Framework/TestSuite.php:733
PHP   7. PHPUnit_Framework_TestSuite->run() /Users/jan/dev/mautic/vendor/phpunit/phpunit/src/Framework/TestSuite.php:733
PHP   8. Mautic\EmailBundle\Tests\EmailModelTest->run() /Users/jan/dev/mautic/vendor/phpunit/phpunit/src/Framework/TestSuite.php:733
PHP   9. PHPUnit_Framework_TestResult->run() /Users/jan/dev/mautic/vendor/phpunit/phpunit/src/Framework/TestCase.php:868
PHP  10. Mautic\EmailBundle\Tests\EmailModelTest->runBare() /Users/jan/dev/mautic/vendor/phpunit/phpunit/src/Framework/TestResult.php:686
PHP  11. Mautic\EmailBundle\Tests\EmailModelTest->setUp() /Users/jan/dev/mautic/vendor/phpunit/phpunit/src/Framework/TestCase.php:909
PHP  12. Mautic\EmailBundle\Tests\EmailModelTest->createMock() /Users/jan/dev/mautic/app/bundles/EmailBundle/Tests/Model/EmailModelTest.php:83
PHP  13. PHPUnit_Framework_MockObject_MockBuilder->getMock() /Users/jan/dev/mautic/vendor/phpunit/phpunit/src/Framework/TestCase.php:1466
PHP  14. PHPUnit_Framework_MockObject_Generator->getMock() /Users/jan/dev/mautic/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/MockBuilder.php:117
PHP  15. PHPUnit_Framework_MockObject_Generator->generate() /Users/jan/dev/mautic/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php:263
PHP  16. PHPUnit_Framework_MockObject_Generator->generateMock() /Users/jan/dev/mautic/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php:574
PHP  17. PHPUnit_Framework_MockObject_Generator->generateMockedMethodDefinitionFromExisting() /Users/jan/dev/mautic/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php:827
PHP  18. PHPUnit_Framework_MockObject_Generator->getMethodParameters() /Users/jan/dev/mautic/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php:1024
PHP  19. ReflectionParameter->getDefaultValue() /Users/jan/dev/mautic/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php:1223
.....  427 / 1203 ( 35%)
...................................E...E...E..EE.E...........  488 / 1203 ( 40%)
.............................................................  549 / 1203 ( 45%)
.............................................................  610 / 1203 ( 50%)
.............................................................  671 / 1203 ( 55%)
.............................................................  732 / 1203 ( 60%)
.............................................................  793 / 1203 ( 65%)
.............................................................  854 / 1203 ( 70%)
.............................................................  915 / 1203 ( 76%)
.............................................................  976 / 1203 ( 81%)
............................................................. 1037 / 1203 ( 86%)
............................................................. 1098 / 1203 ( 91%)
............................................................. 1159 / 1203 ( 96%)
..........................aa1
```
It simply stops like there was a `die` somewhere...

**Comment by escopecz** [comment]
@kuzmany Found it: https://github.com/mautic/mautic/pull/5401/files#diff-bb0c946057e350446545f596a09fcef6R91

Please remove that debug code.

**Comment by npracht** [comment]
> @kuzmany Found it: https://github.com/mautic/mautic/pull/5401/files#diff-bb0c946057e350446545f596a09fcef6R91
> 
> Please remove that debug code.

https://github.com/mautic/mautic/pull/6950

**Comment by StudioMaX** [comment]
Rebased on current staging which already includes https://github.com/mautic/mautic/pull/6950.

**Comment by StudioMaX** [comment]
PHP 7.3 will be released on December 13th. Although I do not plan to use it in my projects in the near future, I think it's time to start adding support for 7.3 in this PR, since it may take a long time to find problems with the current Travis failures.

**Comment by Woeler** [comment]
@StudioMaX We are currently on it with 3 people, at this very moment. So we'll see.

**Comment by StudioMaX** [comment]
Still the same error

**Comment by escopecz** [comment]
Interesting is that it fails every time the PHP notice appears. So I think that if we fix the PHP notice it will also fix the failures. It looks like Travis "remembers" the constant `MAUTIC_INSTALLER` through all the individual tests.

**Comment by Woeler** [comment]
We're on it right now. We're highly suspicious that something in the new travis config is causing the issues.

**Comment by Woeler** [comment]
I'm not sure why this was added `sudo: false` to travis yaml. Maybe that is doing some weird stuff.

**Comment by escopecz** [comment]
Also the `dist: precise` row was added because some random jobs failed if it wasn't there. Any reason to remove it?

**Comment by Woeler** [comment]
I removed sudo, we can check that afterwards

**Comment by StudioMaX** [comment]
Precise is deprecated for some time
https://docs.travis-ci.com/user/reference/overview/#deprecated-virtualization-environments
> Precise Container-based environment: was available between December, 2014 and September, 2017.

**Comment by StudioMaX** [comment]
@luizeof `mcrypt` extensions is not needed anymore. I didn't used the official Docker image, so I'm not sure that this will be enough. But since there were no architectural changes here, I don’t think that you will need to change something else.

**Comment by Woeler** [comment]
So, with `sudo: false` removed it is now already passing tests that failed earlier.

**Comment by StudioMaX** [comment]
@Woeler That's cool! Good to know.

About `dist: xenial`, just to know: https://blog.travis-ci.com/2018-11-08-xenial-release . MySQL won't be started by default, etc. As I understand it, Travis team are still testing this image and will make it default in mid-January 2019.

**Comment by Woeler** [comment]
Ladies and gentlemen, all systems green. Can I get a cookie?

**Comment by escopecz** [comment]
Thanks @Woeler! 

🍪

**Comment by mabdelfattah** [comment]
I think there is something wrong here, as in `upgade.php` Mautic still checking for PHP version < 7.2 in `define('MAUTIC_MAXIMUM_PHP', '7.1.999');`

**Comment by heathdutton** [comment]
Thanks @mabdelfattah that is fixed in #6991

**Pull request merged**
