### PR TITLE
Fix email fetch message

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Some messages was not parse properly for replies. Found solution here https://github.com/barbushin/php-imap/issues/71

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Check If replies works as before https://docs.mautic.org/en/channels/emails/contact-replies

### CODE REVIEW

**Comment by jos0405** [comment]
I've got a strange behaviour.
I set up a monitored mailbox:
image

Did the campaign with email send and listening for reply.

But when I try to fetch, I get this error:
image

**Comment by npracht** [comment]
You have to setup all other things (select folders):
Capture d’écran 2023-01-06 à 11 44 47

otherwise your config doesn't work i think.

**Comment by kuzmany** [comment]
At least one of inboxes. At the issue you need configure replies

**Review by jos0405 — APPROVED** [review]
Duh...
Just tested, reply detection works as it supposed to!

image

**Comment by MadlenF** [comment]
Tested successfully! 👍 
Bildschirmfoto 2023-03-17 um 14 52 23

**Pull request merged**
