### PR TITLE
fix segment/campaign detail view's contacts tab pagination problem

### LINKED ISSUE #12092: The pagination url is wrong on the contacts tab in a segment or campaign detail page.
### Mautic Version

5.0.x series

### PHP version

8.0.27

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When you click on a pagination link in a segment detail page’s contact tab, it's not show the next page result, but jumps to the /s/contacts.

### How can we reproduce this issue?

Step 1: Select a segment with 2 pages or more, enter the detail page and then click the contacts tab.
Step 2: Click the page 2 link
Step 3: 
image
image

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jiang2013**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          |  [ x ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #12092 

##### What happened?
When you click on a pagination link in a segment detail page’s contact tab, it's not show the next page result, but jumps to the /s/contacts.

##### How can we reproduce this issue?
Step 1: Select a segment with 2 pages or more, enter the detail page and then click the contacts tab.
Step 2: Click the page 2 link
Step 3: Notice it doesn't work

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Go to a segment with 2 pages or more, enter the detail page, then click the contacts tab
3. Click the page 2 link
4. It should now direct you to the second page.

### CODE REVIEW

**Comment by mabumusa1** [comment]
@jiang2013 welcome to the community, I am here to help you get your first PR merged. please start by signing the contributor agreement and then the community will test, approve, and merge

**Comment by RCheesley** [comment]
Welcome to the community @jiang2013 - thanks for reporting the bug and even more for making a PR to address it!

@cla-bot check

**Comment by RCheesley** [comment]
Small issue, you signed the CLA with the username 'jiang2013' but it looks like there are some commits from another user, '@jiang20160402'. Could you just pop in the form again but using this username, just so we have it on record? Then I'll call the bot again and it should pass!

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Hurrah, all done! 🥳 🚀

**Comment by RCheesley** [comment]
I've updated the test instruction to make it easier for folks to test / review!

**Review by RCheesley — APPROVED** [review]
Thanks for snagging the bug @jiang2013 - tested the fix and it works perfectly! 

🚀

**Review by volha-pivavarchyk — APPROVED** [review]
Works as described

**Review by JeanMarcAivie — APPROVED** [review]
Tested successfully.

**Pull request merged**
