### PR TITLE
Fixed a bad merge with fields in segments

### PR DESCRIPTION
**Pull request by alanhartless**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | n
| Related user documentation PR URL | na
| Related developer documentation PR URL | na
| Issues addressed (#s or URLs) | na
| BC breaks? | n
| Deprecations? | n

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

Found a bad merge with the multiselect when determining the operators for a segment's filter.

#### Steps to test this PR:
1. Create a new multiselect custom field
2. Create a new segment and use that multiselect as the filter
3. Save and view - no notices or warnings should generate
4. Add a preferred locale as a filter - and the operator list should not include greater than, et al.
[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Repeat the above - should get a warning about array_key_exists expecting an array as argument 2

### CODE REVIEW

**Comment by escopecz** [comment]
The PHP warning is fixed with this PR :+1:

**Comment by dongilbert** [comment]
The PHP warning is fixed, but the select isn't a multi-select. It only allows me to choose one option.

**Comment by dongilbert** [comment]
Correction on this - it's not ready. Not sure how to remove approval though.

**Comment by escopecz** [comment]
What's the matter?

**Comment by dongilbert** [comment]
Adding a custom multi select field, or using the local filter allowed you to add these filters to the segment and save it, but when you went to load the segment, it errored out. My latest push fixed it.

**Comment by escopecz** [comment]
Now I get `Internal Server Error - Warning: implode(): Invalid arguments passed at app/bundles/LeadBundle/Views/Lead/lead.html.php (line #222)` when viewing a contact detail. Can you replicate?

**Comment by dongilbert** [comment]
@escopecz I am getting that error. Checking.

**Comment by escopecz** [comment]
With latest changes when I try to save a new email with multiselect dynamic filter, I get:
`500 Internal Server Error - Notice: Undefined index: fields at /app/bundles/CoreBundle/Form/Type/DynamicContentFilterEntryFiltersType.php (line #176)`

**Comment by alanhartless** [comment]
Tested the recent changes and all seem to work ok. +1

**Comment by escopecz** [comment]
:+1:

**Pull request merged**
