### PR TITLE
[UX] Change “Clear cache” button icon from Trash to Refresh

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Currently, the ‘Clear cache’ button is represented by a Trash can icon. While it serves its purpose, the icon could potentially be misinterpreted due to its common association with deletion functions.

The pull request proposes a shift from the Trash can icon to a Refresh symbol. This symbol is widely recognized in digital interfaces and aligns more closely with the action of clearing or refreshing data, which is the actual function of the button.

This subtle yet impactful change is expected to streamline the user interface and make it more intuitive. It primarily benefits users who frequently interact with the ‘Clear cache’ button, as it reduces ambiguity and enhances the clarity of the button’s function.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Marketplace
3. See the new icon!

OBS.: Merging the new icon pack is necessary. We may have to perform a rebase after completing the icon pack merge before this PR takes effect.

### CODE REVIEW

**Review by LordRembo — APPROVED** [review]
Looking good to me! The circular 'refresh' icon makes more sense than a button from non-tech perspective, as you're essentially renewing/refreshing.

**Review by patrykgruszka — APPROVED** [review]
The code looks fine, and the change makes sense. It relies on another pull request that needs to be merged first.

**Review by kuzmany — APPROVED** [review]
Why not 👍

**Review by Annam187 — CHANGES_REQUESTED** [review]
Screenshot 2024-02-18 at 3 32 03 PM

We've just confirmed during our contribution day. Could you please verify if this matches the expected icon, as we're observing different icons?
Could you please double-check to ensure this has been addressed in this [comment](https://github.com/mautic/mautic/pull/13375#pullrequestreview-1882977540)

**Comment by andersonjeccel** [comment]
@Annam187 Still waiting for the PR to be merged, thanks!

**Comment by escopecz** [comment]
@andersonjeccel what is blocking this? I can't see any link to another PR.

**Comment by LordRembo** [comment]
@escopecz It was [the PR with the icon pack](https://github.com/mautic/mautic/pull/13318), but I see that one was merged today, so I'll remove the 'blocked' label.

**Review by kuzmany — APPROVED** [review]
After merge last 5.x and run composer install it start working.
See new icon. I am OK with the change.

Devs note: spin feature of icon (this button do not use it) stop working for new icons, we need handle it later somewhere https://github.com/mautic/mautic/blob/9782f9f0cb7c4229187609db6eeee727cbc367c4/app/bundles/CoreBundle/Assets/js/1.core.js#L410

**Comment by kuzmany** [comment]
Support btn-spin for remix icons https://github.com/mautic/mautic/pull/13450

**Review by escopecz — APPROVED** [review]
I can see the refresh icon:
Screenshot 2024-02-23 at 09 52 43
However, all over the docs we call the icon that opens the admin menu the cog icon. It's not a cog anymore. Shall we change it back or change the docs, forum posts and all other locations? I'm not sure how to call the new icon. Ideas?

**Comment by LordRembo** [comment]
@escopecz That change is related to the ongoing discussion in This PR I think: [#13365](https://github.com/mautic/mautic/pull/13365)
Maybe best if you raise your concerns in there?

**Comment by andersonjeccel** [comment]
@escopecz This icon is called "sidebar" on Remix

**Comment by escopecz** [comment]
@andersonjeccel good to know but not sure how it is helpful to the raised points.

**Pull request merged**
