### PR TITLE
Fix multiple sending of marketing message of translation email

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Campaign marketing emails are supposed to be send only once to users.
If a mail has a translation and that translation is sent instead of the original mail because of the user's preferred locale,
then this user can receive the email multiple times.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create a Mail in `fr`.
3. Create a translation of that mail in `en`.
4. Create a Contact with preferred local set to `en`.
5. Create a Segment including this contact.
6. Create a campaign based on that segment with the action `Send email`: 
    - Check `Marketing` for the email type.
    - Select the `fr` version of your email.
7. Clone that campaign so we can trigger the email send twice.
8. Run the following commands to trigger the email send : 

```
mautic:segment:update
mautic:campaigns:update
mautic:campaigns:trigger
```
9. Go see your contact History, you should see two campaigns logs : 
    - One that went ok.
    - The second with this error

Screenshot 2021-09-07 at 17 11 07
10. Before PR email is send double time

### CODE REVIEW

**Comment by jos0405** [comment]
Tested by creating english campaign with German translation. Once the PR was installed I was unable to send 2nd marketing email: works as expected! Great job!

image

**Comment by jos0405** [comment]
I tested this (see above), works great, can we merge it?

**Review by escopecz — CHANGES_REQUESTED** [review]
Please add tests

**Comment by kuzmany** [comment]
Close at the moment. We will push it again once ready to M5

**Pull request closed without merging**
