### PR TITLE
Select custom field

### PR DESCRIPTION
**Pull request by escopecz**
Please answer the following questions:

| Q             | A
| ------------- | ---
| Bug fix?      | Y
| New feature?  | N
| BC breaks?    | N
| Deprecations? | N
| Fixed issues  |  https://www.mautic.org/community/index.php/3369-adding-new-option-to-custom-select-field/0#p10213

## Description
Select custom field doesn't show created options.

## Steps to reproduce the bug (if applicable)
Open a custom field type of select. Create one with some options if you don't have any and save. The options are not visible.

## Steps to test this PR
Apply this PR and the options should appear after refresh. Make sure that creating new select field let you create options.

### CODE REVIEW

**Comment by alanhartless** [comment]
This PR works for me.

**Comment by mqueme** [comment]
+1

**Comment by npracht** [comment]
Hi @escopecz ,

We've tried the PR but it does not work.
We still don't see the fields (i mean, we see them for half a second).

faxkasckfh

**Comment by escopecz** [comment]
@npracht you'd have to use the index_dev.php to see it. The prod JS will be compiled for the release.

**Pull request merged**
