### PR TITLE
[UI] Replace page actions icons from FontAwesome to Remix

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR changes icons from FontAwesome to Remix, focusing on buttons.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open all main pages and details, page dropdown, list dropdown

image

image

image

### CODE REVIEW

**Comment by andersonjeccel** [comment]
@LordRembo Is this size of PR ok?

A lot of files changes, but few lines

**Review by shinde-rahul — COMMENTED** [review]
LGTM!!

Did we discussed replacing the library?

**Comment by andersonjeccel** [comment]
> LGTM!!
> 
> Did we discussed replacing the library?

Yeah https://github.com/mautic/mautic/pull/13318

The main reason is to make Mautic modern and improve the representation of all actions (we had a cube associated to emails, which doesn't make sense, for example, instead of an envelope)

**Review by shinde-rahul — APPROVED** [review]
Thanks @andersonjeccel!!

**Review by LordRembo — APPROVED** [review]
The code changes all make sense. Using `^="ri-` to capture a class prefix is the best way to go. There should not be any elements that combine another functional class with an icon class, because the icons live in their own tag, and if one pops up it's easily changed.

**Review by Esthertests — APPROVED** [review]
This LGTM great work

**Comment by escopecz** [comment]
@andersonjeccel please resolve the conflict

**Comment by andersonjeccel** [comment]
@escopecz Seems done!

**Pull request merged**
