### PR TITLE
User tokens refactor (reset password token fix)

### PR DESCRIPTION
**Pull request by Dreiser**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | N
| Related developer documentation PR URL | N
| Issues addressed (#s or URLs) | -
| BC breaks? | Might be
| Deprecations? | N

[//]: # ( Required: )
#### Description:
See issue (reset token is generated based on last login of user - not random)

#### Steps to test this PR:
**Normal:**
1. Request new password
2. Change password by link
3. Try link again
**Expired:**
1. Request new password
2. In database table user_tokens change expiration to past datetime
3. Try link (shouldn't work)

#### List backwards compatibility breaks:
There might be BC break because method \Mautic\UserBundle\Model\UserModel::getResetToken now returns UserToken instead of string. I believe it won't be an issue but FYI.

### CODE REVIEW

**Comment by Gregy** [comment]
Please fix failing tests.

**Comment by Gregy** [comment]
I applied the PR and tried to reset a password. I received an email without any secret token at all. Complete text of the email:
```
Hi petr,

You requested a password reset. Click the link below to reset your password.

https://mautic.gregy.cz/passwordresetconfirm
```

**Comment by Gregy** [comment]
The secret was correctly created and stored in the user_tokens table. It just wasn't sent alogn with the email.

**Comment by Dreiser** [comment]
Stupid mistake :)

**Comment by Gregy** [comment]
Tested again. Email now contains the token but I noticed another issue. The flash message after reset email is sent says:
```
A new password has been generated and will be emailed to you. If you do not receive it within a few minutes, check your spam box and/or contact the system administrator.
```
That is not what happens so I believe it should be updated.

**Comment by Gregy** [comment]
Also it seems there is no code for clearing out expired tokens? Or am I missing something? Maybe you could hook into CoreEvents::MAINTENANCE_CLEANUP_DATA to handle it?

**Comment by alanhartless** [comment]
Or delete them when the user has a successful login.

**Comment by mleffler** [comment]
We logged the expiration and password text issues separately, expiration internally, password text externally.

**Comment by Dreiser** [comment]
@alanhartless It's deleted on use if it's one time only token. If it has expiration and it was one time token but wasn't used, it won't be deleted. Token's that are not one time only are never deleted. ofc not valid.

@Gregy ok

**Pull request merged**
