### PR TITLE
Add redirect url hits

### PR DESCRIPTION
**Pull request by kuzmany**
Skip isAnonymous() check, because we  know about user from url params.

### CODE REVIEW

**Comment by alanhartless** [comment]
Thanks for submitting this! 

Can you please provide some details around the case use for this?

There's a couple other things to consider.  Allowing the clickthrough for non anonymous leads (i.e. Mautic users) will cause Mautic to start tracking your users activity as the lead.  If you're testing, that may or may not be desired. Also note that by doing this, your users' test hits will be counted against A/B test stats, etc.

Thanks!
Alan

**Comment by kuzmany** [comment]
Hi Allan,

the main issue for this PR was that link tracks didn't work. 
If I send newsletter  and user wasn't lead, Mautic doesn't add his hit to page_redirects table.
I am not sure what was idea behind the track links, but usually If somebody click on link I know who he is.
Maybe We can add email check in url params:

if (!$this->factory->getSecurity()->isAnonymous() && (empty($clickthrough) || !isset($clickthrough['email'])))

**Comment by alanhartless** [comment]
It's on purpose that Mautic doesn't add a hit for users who are not leads. But the only time a user who is not tracked as a lead would receive a newsletter is if you are sending an "example" mail.  Is that the case here?

**Comment by kuzmany** [comment]
Alla,

this is issue, maybe you can test it:

1, Import leads to the Mautic and add them to the list Newsletter
2, Afterthat send email to this list
3, Link tracks doesn't count in this case

I do research and I find that Mautic check isAnonymous and this user from email is in that time anonymous.

**Comment by kuzmany** [comment]
Allan,

sorry about the misunderstanding

Now I did test, and It works.
Mautic didn't count link tracks just If I logged in as Mautic. 
If I try another browser or private tab, It works great.

Thank you for your support.

**Pull request closed without merging**
