### PR TITLE
Fix form rendering/thrown exception for Focus items that use the editor/HTML content modes

### PR DESCRIPTION
**Pull request by alanhartless**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

1. When saving a Focus item with custom HTML, an exception is thrown due to trying to generate contact tokens. This was fixed by checking for a lead before attempting to obtain data about the lead.
2. The contact tokens were generated at the time the content was cached so it was not live. This was fixed by replacing tokens at the time the focus content is fetched.
3. Forms manually embedded for the editor/HTML modes would not be caught as a conversion. This was fixed by using a new {focus_form} token that will inject the content of form selected. That way the custom rendering for the form required to make the focus conversion work is generated. 
4. If the HTML/editor content has images, the first time the iframe loads may be the wrong size due to the browser not having fetched the image yet. This was fixed by resizing within the iframe's onload method. 
5. The bar was broken for basic content as the editor/HTML content always rendered.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a new focus item, choose HTML for content mode, and attempt to save. It'll kill the buttons.
2. This is not possible to reproduce due to the first bug.
3. The only way to embed a form into the focus item using editor/HTML mode was to copy in the form's generate.js or iframe code. Do so and add the focus item to a webpage and load. Submit the form. Note that it will not show up as a conversion. 
4. Add an large image to the custom content of a focus item. Save and embed the focus item into a web page. Use a guest or incognito browser to load the page for the first time. The content will not be fully visible. Refresh and it will be. 
5. Create a new focus item and select a emphasize link focus and a bar style. Then choose basic for content and notice that the bar will have no content.

#### Steps to test this PR:
1. Save and should work
2. Add a contact token, ensure you are tracked by that token in a Guest session, open a focus item and the content should have the contact name. 
3. When building the focus item, choose the editor (test) then HTML (test), choose the form then insert {focus_form} into the content. The form's content should load in the preview and in the production focus item.
4. The focus should show the entire content. 
5. Repeat and this time the basic content will show (button) or if you choose editor/HTML, the appropriate content will show.

### CODE REVIEW

**Comment by escopecz** [comment]
1. Works
2. Tokens are not being replaced with contact values. Maybe I don't understand what to do clearly.
3. Form token doesn't work either. Even if I use `{focus_form}` in front of the form token.
4. If I place an image to the editor, save, open the builder again, it's gone.

screen shot 2017-09-12 at 12 28 13

5. The bar will not show up on the page with the focus JS. Only the close button is there and I have to click it twice so the bar would appear.
screen shot 2017-09-12 at 12 39 15

**Comment by alanhartless** [comment]
@escopecz 

2. You have to be sure you are getting tracked as an identified contact. Try submitting a form with your email address before you view the focus item. 
3. {form=1} tokens do not work in Focus items. {focus_form} will insert whatever form you've selected underneath the content. Did you select "Collect Data" focus and then selected the form in the content section? 
4. Fixed
5. Fixed

**Comment by alanhartless** [comment]
Something is wrong with submitting the form now. Looking into that.

**Comment by escopecz** [comment]
Thanks Alan. About 2, I visited the page in an incognito window with the focus item, opened the anonymous contact in the Mautic administration and inserted an email address. It still show up the token. Even without it, it should not display the token if the email address isn't known, right? About 3, ok, I didn't know you meant to test the Colect Data option. Will retest after the form fix.

**Comment by escopecz** [comment]
I found that the button URL was always `#`. Fix is coming.

**Comment by escopecz** [comment]
1, 2, 5. works now.

3. The form appears, but the form submission is stuck on sending. I don't see any error in the JS console nor Mautic log though.

4. If I place an image to the editor, it sticks there now when I save the focus item and open the builder again. But the modal box with the image never shows up in the page where the modal with the image never shows up. Again, no error anywhere.

**Comment by escopecz** [comment]
4. works too. It was a problem with the configuration of my focus item. It stopped engaging after form submission. But the form submission is still hanging. Although the data are being persisted to the database.

**Comment by escopecz** [comment]
There is a workaround with form displaying a message. Then the form submission works fine 👍

**Pull request merged**
