### PR TITLE
Fix contact CSV import progress checks unreachable statement

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.3
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
There is unreachable statement in contacts import controller that is responsible for some kind of multi import prevention.

To reproduce this you can try to run two contact imports at the same time in your browser.

This PR should fix the issue.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2.

### CODE REVIEW

**Review by kuzmany — APPROVED** [review]
Good catch 👍

**Comment by RCheesley** [comment]
Could you give some indication of how to test this bug and then to check with the PR applied? I am trying a few things like uploading the same data, changing some data with the same email address on import, but not hitting an error yet! Will keep trying but some test instructions would make it a lot less frustrating!

**Comment by patrykgruszka** [comment]
@RCheesley there was part of code that should postpone new contact import when another is already in progress. That code could not be reached, because there was literally always true condition in the code. To reproduce this you can try to run two contact imports at the same time in your browser.

**Comment by RCheesley** [comment]
@patrykgruszka thank you - that was some crucial information missing from the test instructions!

**Pull request merged**
