### PR TITLE
Fix: Change function renderArray() to use single quotes for key and value strings

### PR DESCRIPTION
**Pull request by skolarianer**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #5641
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Changes function renderArray() to use single quotes for key and value strings instead of double quotes. This allows to use `$` in passwords which otherwise gets parsed as variable. If the password contains `{$` – without the closing bracket of the complex syntax for variables like `{$foo}` – this leads to parsing errors of `…/app/config/local.php`.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Use a password containing `{$` in Configuration > Email Settings > Monitored Inbox Settings > Default Mailbox > IMAP password.
2. 'Save & Close' should throw: `Parse error: syntax error, unexpected ')', expecting variable (T_VARIABLE) or '{' or '$' - in file /…/app/config/local.php`

#### Steps to test this PR:
1. Same as above but without error

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by skolarianer** [comment]
Oops! Accidentally added commit https://github.com/mautic/mautic/pull/5648/commits/8a5861940d28a65ca4c5fb4a2750104594b2ee60 to that PR. Any way to remove that commit from this PR?

**Comment by skolarianer** [comment]
> Files:
> media/js/mautic-form-src.js
> media/js/mautic-form.js
> shouldn be part of this pull request? I don't think so

These files are not related to this bug. Please see https://github.com/mautic/mautic/pull/5648#issuecomment-360935202

**Comment by escopecz** [comment]
Maybe try to rebase to current staging? That commit is merged already, so it shouldn't show up at all.

**Comment by Woeler** [comment]
@escopecz Do you think someone can rebase this? Otherwise I think it would be best to create a new pr and merge it there (author here seems to be not responding). This is a small fix. Should take no more than 2 min.

**Comment by kuzmany** [comment]
@Woeler go for it

**Comment by Woeler** [comment]
@kuzmany @escopecz See https://github.com/mautic/mautic/pull/6737

**Comment by escopecz** [comment]
Closing this in favor of https://github.com/mautic/mautic/pull/6737

**Comment by skolarianer** [comment]
> … author here seems to be not responding …

Sorry for being off for some days. Glad to see this bug has been fixed with https://github.com/mautic/mautic/pull/6737.

But to be honest … this PR is more than 8 months old and not much had happened. So my priorities have changed over time – and yes it’s quite hard to overcome laziness and respond immediately in this case.

**Comment by Woeler** [comment]
no worries, it is done now. Albeit late.

**Pull request closed without merging**
