### PR TITLE
[UI] Tooltips

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR is based [on another PR](https://github.com/mautic/mautic/pull/13735), where I introduce tokens to replace most of the UI variables, aiming to improve consistency in all components. **We need it to be merged before this one becomes available for code review.**

This PR increases the font size for small elements and increases the padding of tooltips.

| Before                                 | After
| -------------------------------------- | ---
|  image                                      | image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Account > Look at the descriptions below the titles, they're 8% bigger
3. Open Contacts > Create new > Hover over any field with a tooltip

### CODE REVIEW

**Review by LordRembo — APPROVED** [review]
Okay, yeah, makes sense to add bit more space and size, for readability at least. Sound like a good improvement.

**Review by shinde-rahul — APPROVED** [review]
More Readable.

Thanks @andersonjeccel for this.

**Comment by RCheesley** [comment]
Re-running the failed test in case of a flakey test.

**Comment by andersonjeccel** [comment]
@RCheesley All passed!

**Pull request merged**
