### PR TITLE
fixed mautic:unusedip:delete

### LINKED ISSUE #10387: mautic:unusedip:delete not working in Mautic 4.0.0
### Mautic Version

4.0.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Calling mautic:unusedip:delete command ends with error
```
./bin/console mautic:unusedip:delete

In UnusedIpDeleteCommand.php line 55:
                                                                                                                      
  Attempted to call an undefined method named "getEntityManager" of class "Doctrine\Bundle\DoctrineBundle\Registry".  
                                                                                                                      

mautic:unusedip:delete [-l|--limit [LIMIT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

The reason for this is doctrine/doctrine-bundle package.
Mautic 3.3.3 uses
```
            "name": "doctrine/doctrine-bundle",
            "version": "1.12.13",
```
This version had `getEntityManager` method
https://github.com/doctrine/DoctrineBundle/blob/1.2.x/Registry.php

Mautic 4.0.0 uses
```
            "name": "doctrine/doctrine-bundle",
            "version": "2.4.2",
```
This version does not have that method:
https://github.com/doctrine/DoctrineBundle/blob/2.4.x/Registry.php

### How can we reproduce this issue?

Step 1: Run Mautic 4.0.0
Step 2: Run command `./bin/console mautic:unusedip:delete`

### Relevant log output

```shell
./bin/console mautic:unusedip:delete

In UnusedIpDeleteCommand.php line 55:
                                                                                                                      
  Attempted to call an undefined method named "getEntityManager" of class "Doctrine\Bundle\DoctrineBundle\Registry".  
                                                                                                                      

mautic:unusedip:delete [-l|--limit [LIMIT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by luguenth**
I closed the old PR, because I had problems with the branches:
https://github.com/mautic/mautic/pull/10536

It's still the same functionality and the same code, only based on the right

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | Yes
| New feature/enhancement? (use the a.x branch)      | No
| Deprecations?                          | No
| BC breaks? (use the c.x branch)        | No
| Issue(s) addressed                     | Fixes #10387  

#### Description:
As mentioned in #10387 it was not possible to use `mautic:unusedip:delete` since Mautic 4.x. This PR fixes this Issue
#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2. Got to the CLI
3. execute the command `bin/console mautic:unusedip:delete`
4. There should be no exception thrown.
5. `n unused IP addresses have been deleted` should appear

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10589"></a>

### CODE REVIEW

**Comment by luguenth** [comment]
@cla-bot check

**Comment by atowne07** [comment]
Commented on the wrong PR. Thanks @luguenth for letting me know.

**Comment by luguenth** [comment]
I think you wrote inside the wrong PR ;)

**Review by kuzmany — APPROVED** [review]

**Review by escopecz — APPROVED** [review]
👍

**Pull request merged**
