### PR TITLE
[DPMMA-1652] MySQL column form in submission 5x

### PR DESCRIPTION
**Pull request by tomekkowalczyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [yes ]
| New feature/enhancement? (use the a.x branch)      | [x ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [x ]
| Automated tests included?              | [yes ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

The purpose of the PR is to fix the SQL error stating that there is an invalid syntax. When we create a form with a field containing an SQL keyword, eg 'all', we will not be able to go to the results of the forms /s/forms/results/{$formId}. The solution adds "`" to the sql query as column names. 

`mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'INSERT INTO mc_form_results_1956_erp_pl_kon (imieinazwisko, nip, email, phonenumber, firma, all, zgoda_na_newsletter, zgoda_email, consent_phone, formurl, socmsformid, socmsreferrer, userip, employeesfinemail, employeesfinid, jsonform, crmcampaign, inboxcrm, utmsource, utmmedium, utmcampaign, utmterm, utmcontent, submission_id, form_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params`

#### Steps to test this PR:

1. Create a form in socms and set the mysql keyword as the name of one of the fields, e.g.: "all"
2. Save the form
3. Complete and submit the form
4. Go to the form results page /s/forms/results/{$formId}

### CODE REVIEW

**Review by volha-pivavarchyk — COMMENTED** [review]
Works well. 
But I couldn't reproduce the bug on the 5.x branch.

**Comment by tomekkowalczyk** [comment]
@volha-pivavarchyk Can you tell me more about what field name you used, maybe some screenshots would help. Generally, you should not be able to access the results page of the form /s/forms/results/{$formId} if you used the field name as the SQL keyword

**Comment by volha-pivavarchyk** [comment]
@tomekkowalczyk I added a SQL keyword as a field label. Maybe it should be another property.

image

image

**Review by escopecz — APPROVED** [review]
The code changes make sense. Thanks! 👍 

@tomekkowalczyk please figure out what Volha needs to replicate this so we can get this merged.

**Review by kuzmany — APPROVED** [review]
We met the same issue and this fix works. Thank you 👍

**Comment by kuzmany** [comment]
This brings the issue for forms with the file type. Need sanitize it also in app/bundles/FormBundle/Helper/FormUploader.php
Probably better would be to sanitize aliases results before saving the entity to avoid stopping working for plugins. 
@tomekkowalczyk are you able to look on it yet?

```

Subject: [PATCH] Fix form upload file
---
Index: app/bundles/FormBundle/Helper/FormUploader.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/app/bundles/FormBundle/Helper/FormUploader.php b/app/bundles/FormBundle/Helper/FormUploader.php
--- a/app/bundles/FormBundle/Helper/FormUploader.php	(revision 67f2181b3ec93cefa7ad3a5d6a060efad747c0b1)
+++ b/app/bundles/FormBundle/Helper/FormUploader.php	(revision 2faf29f42732c9b2ddd8c973e614e0919f034321)
@@ -57,12 +57,12 @@
 
         try {
             foreach ($filesToUpload as $fileFieldCrate) {
-                $field           = $fileFieldCrate->getField();
-                $alias           = $field->getAlias();
-                $uploadDir       = $this->getUploadDir($field);
-                $fileName        = $this->fileUploader->upload($uploadDir, $fileFieldCrate->getUploadedFile());
-                $result[$alias]  = $fileName;
-                $uploadedFile    = $uploadDir.DIRECTORY_SEPARATOR.$fileName;
+                $field                   = $fileFieldCrate->getField();
+                $alias                   = $field->getAlias();
+                $uploadDir               = $this->getUploadDir($field);
+                $fileName                = $this->fileUploader->upload($uploadDir, $fileFieldCrate->getUploadedFile());
+                $result['`'.$alias.'`']  = $fileName;
+                $uploadedFile            = $uploadDir.DIRECTORY_SEPARATOR.$fileName;
                 $this->fixRotationJPG($uploadedFile);
                 $uploadedFiles[] = $uploadedFile;
 
```

**Comment by tomekkowalczyk** [comment]
@kuzmany ok look at it

**Comment by kuzmany** [comment]
@tomekkowalczyk probably sanitize it before save entity. We found another issue related to this PR

**Comment by tomekkowalczyk** [comment]
@kuzmany  oki, but You have an idea how we write protect Entity?
- block sql words
- add a prefix or suffix

**Comment by kuzmany** [comment]
@tomekkowalczyk probably somewhere here https://github.com/mautic/mautic/blob/5.x/app/bundles/FormBundle/Model/FormModel.php#L415

**Comment by tomekkowalczyk** [comment]
> @tomekkowalczyk I added a SQL keyword as a field label. Maybe it should be another property.
> 
> image
> 
> image

@volha-pivavarchyk the change is on line 5.x, maybe that's why you can't reproduce the error
image

**Comment by volha-pivavarchyk** [comment]
@tomekkowalczyk  Maybe it is a reason.

**Comment by kuzmany** [comment]
@tomekkowalczyk I am okay with your solution to add  "`" just add it before saveEntity  https://github.com/mautic/mautic/blob/5.x/app/bundles/FormBundle/Model/FormModel.php#L415

**Comment by tomekkowalczyk** [comment]
@kuzmany Ok, I understand, but would you like the alias to be saved in the database as, for example ` 'all'`?
Table form_result
image


I noticed that when creating using the backend, a field with the prefix "f_all" is added. I suggest making an alias with a prefix as when creating using the API because then you can create a problematic column name all or mysql, etc.

What do you think about it?

**Comment by kuzmany** [comment]
@tomekkowalczyk do you mean prefix for all fields? Or do we have list of restricted aliases?

**Comment by kuzmany** [comment]
This causes another issue for us. I recommend revert it

**Comment by tomekkowalczyk** [comment]
@kuzmany it's about adding aliases to all fields, which will cause SQL phrases to be secured, e.g. f_all. So the current commit will then be rolled back

**Comment by kuzmany** [comment]
@tomekkowalczyk I revert it and write real solution https://github.com/mautic/mautic/pull/12272

**Pull request merged**
