### PR TITLE
Relative dates: Fix: Relative dates in segments don't work

### LINKED ISSUE #9636: Relative dates in segments don't work
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
If you specify "10 days ago" in the filter for a field with the date type, the exact date will be saved instead of the relative date.

At the same time, the filter by date with the value "today" or" yesterday" works correctly.

| Q   | A
| --- | ---
| Mautic version | 3.2.5
| PHP version | 7.2

### Steps to reproduce
1. Create a segment with a filter by the relative date "2 days ago" or "3 months ago" , etc.
2. Save and then go to edit the segment. Instead of a relative date, there will be an exact date and even a time
3. At first, the segment will work, but as soon as more than a relative date passes in time, contacts with an outdated date will not be deleted from the segment.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by shinde-rahul**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                |  3.2
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #9636 

#### Description:

Added new relative dates for segment filter,
- `'first day of '`
- `'last day of '`

#### Change log
- Updated DateOptionFactory to pick relative formats like "first day of " and "last day of "

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create a segment with a filter by the relative date "2 days ago" or "3 months ago", etc.
3. Save and then go to edit the segment. Instead of a relative date, there will be an exact date and even a time
4. At first, the segment will work, but as soon as more than a relative date passes in time, contacts with an outdated date will not be deleted from the segment.

### CODE REVIEW

**Comment by RCheesley** [comment]
@shinde-rahul is this going to be a replacement for https://github.com/mautic/mautic/pull/9678?

**Comment by shinde-rahul** [comment]
> @shinde-rahul, is this going to be a replacement for #9678?

I have created this draft PR to re-test it and add the testing steps. And I re-fork the repo that lead the branch of #9678 to orphan. If some updates needs to push I can use this PR and close the old one, or vice-versa.

**Review by alexhammerschmied — APPROVED** [review]
I tested this function in the last few days with "today",  "x days ago", "in x days" and it works great. 
The only thing missing is the "now" function. This is sill hard coding the current date and time  into the database (but it was not the scope of this pr anyway).

I think we're good to go with that PR. Thank you @shinde-rahul :)

**Comment by shinde-rahul** [comment]
Closing this PR as #9678 is good to go with.

**Pull request closed without merging**
