### PR TITLE
[UX] Make "Add widget" the main action on the dashboard

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
The primary action button on a page should represent the most common action used by users.
This change makes the primary button on the page to add a widget, as well as refining the text of the save button and reducing the verbosity of the import action.

Discussed on: https://mautic.slack.com/archives/C024XBCQS3Z/p1712174455596019

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open the dashboard
3. See the new page action
4. Click to open the dropdown and see new labels for already existing features

image

### CODE REVIEW

**Comment by LordRembo** [comment]
@andersonjeccel I'm not sure why some terms are shortened to 'pre-defined', instead of 'predefined dashboard'? Was this brought up in another discussion perhaps?

**Comment by andersonjeccel** [comment]
@LordRembo I reviewed the past discussion, people were ok about having or not having dashboard at the end

While having "dashboard", it would be an excessively safe approach as mentioned by Mike

When we compare to other features, like "Export", we're talking about exporting the dashboard, but there is no mention to "dashboard" at the end and that's normal

So thinking about consistency, while following what's being used on other pages, I just refined to remove the last word

Ruth confirmed it would be nice in terms of sense in English

**Review by LordRembo — APPROVED** [review]
Alright, works for me!

**Review by kuzmany — APPROVED** [review]
Yes , Add widget is most used action button on the dashboard.  

👍

**Pull request merged**
