### PR TITLE
Feature clone segments

### PR DESCRIPTION
**Pull request by davevurby**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | y |
| Automated tests included? | /
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/5604 (closed already)
| BC breaks? | N
| Deprecations? | N

[//]: # ( Required: )
#### Description:
New feature of cloning segment has been created. Because edit action was almost the same as clone action, I made some more changes to prevent code duplication.

#### Steps to test this PR:
1. Try to edit segment - make sure it still works properly
2. Try to clone segment
3. Make sure that filters has been cloned as well
4. Make sure that contacts HASN'T been cloned
5. Make sure that cloned segment is not published
6. The alias will get cleared on clone and automatically created as unique alias on save.
7. Clone/Edit -> Apply will get you to the edit form
8. Clone/Edit -> Save will take you to the detail page
9. Test the Clone button on the segment list as well as on detail page

### CODE REVIEW

**Comment by javjim-mautic** [comment]
Works properly as advertised.

**Comment by escopecz** [comment]
I have 3 issues with this:
1. If I clone the segment with ID 590 it redirects me to route `/s/segments/clone/590`. It's not how it works everywhere else, but fine. What is not that good is that if I click Apply it doesn't redirect me to the route `/s/segments/edit/[new_id]`. So I can click Apply several times and it will be creating new clones.
2. If I try to save a cloned segment I get error that the alias already exists. Can we simply clear the alias during cloning so the user wouldn't have to deal with it?
3. Also please add the Clone button to the segment detail page as other clone-able entities has it.

**Comment by davevurby** [comment]
Adjustments working properly

**Review by Maxell92 — APPROVED** [review]
Tested and works properly.

**Comment by javjim-mautic** [comment]
Tested and works

**Review by jessie-580 — COMMENTED** [review]
>

**Pull request merged**
