### PR TITLE
Add tag creation behavior for leads in edit page

### PR DESCRIPTION
**Pull request by julienWebmecanik**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 

#### Description:
At the moment we cannot create tags that are a substring of an existing tag, due to the select search mechanism we have on this field.
With this PR we can now do that by pressing the "Escape" key while typing.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Go to a contact page
3. Create a tag (eg: TestTag)
4. Start typing another tag (eg: Test)
5. Press the Escape key
6. The tag should be created and added to the selected tags.

Remarks: We have tag creation fields in many places (campaign and form actions, segments ...) but I did't manage to create  code working for all so I only made it for leads. (Mainly because campaign and form actions are in modals that closes when pressing Escape)

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10969"></a>

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
Works nicely for me. Thank you! 👍 

I'm wondering whether this intuitive enough or if it needs a sentence in the documentation. What do you think?

**Review by volha-pivavarchyk — DISMISSED** [review]
Works as described

**Comment by escopecz** [comment]
@julienWebmecanik as this is labeled as a bug fix, can you please rebase on top of 4.2 branch? I changed the target branch to 4.2 and now it shows more commits than it should.

**Comment by RCheesley** [comment]
@npracht @julienWebmecanik could you rebase this next week so that we might get this into the 4.2.2 release at the end of the month? Thanks!

**Comment by kuzmany** [comment]
@RCheesley rebased

**Comment by RCheesley** [comment]
Thanks @kuzmany much appreciated! LGTM once the tests pass :rocket:

**Pull request merged**
