### PR TITLE
[UX] Marketer-friendly labels for dashboard widgets size instead of pixels

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Humanized labels help users to get what they want easier.

Discussed on:
https://mautic.slack.com/archives/C024XBCQS3Z/p1711539574454129?thread_ts=1711538952.627039&cid=C024XBCQS3Z

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Dashboard > Add new widget > Height > see new labels

Before:
image

After:
image

### CODE REVIEW

**Review by adiux — COMMENTED** [review]
While I like the idea of making this more user friendly Im not sure this is the right approach. The labels will give the user no indication of how small or big something is. E.g. is XS 10px or 100px? 

As an idea: can we do it in columns? Something like this:
- Full Width
- Half  Width
- 1/6 Width

**Comment by andersonjeccel** [comment]
@adiux Actually this PR is about height instead of width, but that's a nice idea to another change!

I brought your idea to the Slack channel so we can discuss before coding it
https://mautic.slack.com/archives/C024XBCQS3Z/p1711556107540979

**Review by RCheesley — APPROVED** [review]
I like this change, it makes it easier for people to understand but I wonder how many folks actually size the height, I can't ever remember using that. I almost exclusively focus on width.

But no objections to this from me.

**Comment by andersonjeccel** [comment]
@RCheesley Some people said to keep the pixels height 
Perhaps we can use both eg. "Extra small (365px)" for some time until people get used to it then remove the pixels completely next year 

(In fact that's why I did on the last commit)

**Review by LordRembo — APPROVED** [review]
I like the labels, including the px values between brackets

**Comment by RCheesley** [comment]
OK - not sure if we can do anything about the code coverage here, I'll leave that for the code reviewer to determine.

**Review by shinde-rahul — APPROVED** [review]
LGTM!!!

**Pull request merged**
