### PR TITLE
Fix API remove values on PUT request

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

PUT request should create new entity If not exists. But remove also all fields values.
This PR fixed it

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2.

### CODE REVIEW

**Comment by escopecz** [comment]
From the dev docs:

> PUT creates a contact if the given ID does not exist and clears all the contact information, adds the information from the request. PATCH fails if the contact with the given ID does not exist and updates the contact field values with the values form the request.

It behaves as it should. Consider using PATCH if you don't want the fields values that you do not send in the request to be removed.

**Comment by kuzmany** [comment]
@escopecz that's crazy, I've checked docs two times and didn't notice that. 
It's not first time what somebody complain it.

If I apply this patch then:

- on edit edit entity and does not remove values
- if not exists create new one

Does it sound like more better way like handle PUT request, isn't it?

**Comment by escopecz** [comment]
This is really how PUT should work. See for example https://restfulapi.net/rest-put-vs-post/

> Use PUT when you want to modify a singular resource which is already a part of resources collection. PUT replaces the resource in its entirety. Use PATCH if request updates part of the resource.

**Comment by kuzmany** [comment]
@escopecz then nothing to say 👍 
Thank for your expertise 
Close it

**Pull request closed without merging**
