### PR TITLE
The API defines Contacts not Contact causing the API to not receive the correct mapping

### PR DESCRIPTION
**Pull request by mallezie**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Rebases PR https://github.com/mautic/mautic/pull/9559 to 5.x branch. 

#### Steps to test this PR:

How to test:

> 1. Set up mautic
> 2. Set up a trial Dynamics 365 account
> 3. Set up the Dynamics CRM Plugin and select contacts to sync
> 
> Without the patch, no fields from the contacts will show up, no contacts can be synced
> With the patch, contacts fields will show and contacts will sync :)
> It's kind of logical because all call towards this function use the plural. I'm not sure where the singular "Contact" would come from but in testing I found that it becomes "Contacts" instead of "Contact", hence this patch.

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by RCheesley** [comment]
Hi @mallezie - as this is a bug, please can you make it against the 5.0 branch as well? Thanks!

**Comment by mallezie** [comment]
Updated PR to be agains 5.0

**Review by escopecz — APPROVED** [review]
I don't have an account to test with but if this fixes your issue then let's not block this from getting merged 👍

**Comment by escopecz** [comment]
This fix was made twice in the past:

https://github.com/mautic/mautic/pull/9559/files

I take it as 2 additional reviews. Let's get this merged.

**Pull request merged**
