### PR TITLE
[UX] Change how the ways to implement a form are called

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
When you create a form, you are presented with 2 options to make it live: Automatic and Manual Copy. The problem is that both are manual and both require copying. What differs from them is the way the form will be hosted. 

In the first type, a link is generated that calls the Mautic external server to generate the form and returns it to the user's browser when he or she is accessing the page. In the second case, you do not depend on an external platform server to generate this form dynamically because the complete HTML will be placed directly in the content management system. 

This PR proposes to rename these options to reflect their true nature, reducing confusion for users who are setting up forms. This change will improve user experience by providing clearer instructions, ultimately making the form setup process more efficient.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Forms
3. Create a form
4. Save the form
5. Look at the alert card

image

### CODE REVIEW

**Review by shinde-rahul — APPROVED** [review]
LGTM!!

@andersonjeccel

**Comment by shinde-rahul** [comment]
One question: are we implementing this for user pages, too?

**Review by PatrickJenkner — APPROVED** [review]
Change works and I think the new wording is better 👍  Thanks!

**Review by roboparker — APPROVED** [review]

**Comment by escopecz** [comment]
As I wrote several times, these PRs must be accompanied with documentation PRs so we use the same terminology as in the docs. See https://docs.mautic.org/en/5.x/components/forms.html#automatic-copy

**Comment by andersonjeccel** [comment]
@escopecz Docs OK

User docs: https://github.com/mautic/user-documentation/pull/258
Dev docs: https://github.com/mautic/developer-documentation-new/pull/183

**Comment by escopecz** [comment]
@andersonjeccel thanks!

@RCheesley when shall we merge what? Like this?
1. Merge this PR
2. Merge the docs PRs when releasing Mautic 5.1.0?

**Comment by RCheesley** [comment]
There should be a milestone in the docs GitHub repos for the release, which these docs PRs should be associated with. Before the mautic/mautic PR is merged there's a label of 'pending PR merge' to use.

Then the Edu team (or release lead) merge them when the release is made. 

cc @favour-chibueze @fakela as I think we need the milestones set up for the new releases.

**Comment by RCheesley** [comment]
@all-contributors please add @andersonjeccel for docs

**Comment by RCheesley** [comment]
Hi folks, I've set up the milestones for the end-user and dev docs, so you can go ahead and merge this PR and the docs PRs will be merged when we release. @mautic/education-team will take care of that.

**Comment by RCheesley** [comment]
This one should be good to merge if all tests are green :)

**Pull request merged**
