### PR TITLE
Store new arrays as JSON instead of serialized PHP array

### PR DESCRIPTION
**Pull request by escopecz**
| Q | A |
| --- | --- |
| Bug fix? | Y |
| New feature? | N |
| Related user documentation PR URL | / |
| Related developer documentation PR URL | / |
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/1890, https://github.com/mautic/mautic/issues/1756, https://github.com/mautic/mautic/issues/1329, https://github.com/mautic/mautic/issues/1029, https://www.mautic.org/community/index.php/413-error-500-on-leads-page-after-editing-lead/0 |
| BC breaks? | N |
| Deprecations? | serialized PHP arrays in current databases, applying unserialize on database output will cause an error |
#### Description

**This PR must also replace all the un/serialize() functions used across Mautic, therefore, this PR is not fully ready to be merged. It might have to wait for Mautic 3.0**

Serialized arrays often suffers issues:

> It turns out that if there's a ", ', :, or ; in any of the array values the serialization gets corrupted.

_([Source](https://davidwalsh.name/php-serialize-unserialize-issues))_

As @PatchRanger [pointed out](https://github.com/mautic/mautic/issues/1329#issuecomment-232697573), the json_decode/encode should fix this. So this PR simply checks if the serialized array is JSON. If so, it decodes it as JSON. If not, it encodes it as PHP serialized array.

All new/updated arrays will be JSON encoded.

Other advantages of JSON are:
- more easily readable by humans
- json_encode is faster then unserialize
- json also requires much less space than serialized array _([source](http://cw-internetdienste.de/2015/05/04/serialize-vs-json_encode/))_
- safe (no problem with unserialized object execution)
#### Steps to test this PR
1. Go to a campaign
2. Make some change in the canvas (add an action or something)
3. Save the campaign

You may peep into the database and check that the canvas_settings array is really encoded by JSON. All Mautic must still work.
#### Steps to reproduce the bug

I wasn't actually ever able to replicate it, but you may try to replicate an issue from the issues above.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/2040"></a>

### CODE REVIEW

**Comment by PatchRanger** [comment]
@escopecz Thank you, John, for nice PR. I was willing to test it - but discovered that it has conflicts with current `staging`. It looks like there was introduced some protection from broken serialized strings - while it continues to rely on serialize/unserialize. My vote is still for switching to json_encode/json_decode - by the reasons you perfectly explained above.

**Comment by escopecz** [comment]
Thanks for the support! I firstly discussed this idea with @alanhartless and the implementation seemed quite simple at first (as you can see in this PR), but it turned out that there are other places where the serialize/unserialize is used in special cases so those would have to be handled and if Mautic does this for special cases, then 3rd party plugins can do so as well. So to change this would be a BC break so cannot happen until another BC breaking release, Mautic 3.0.0.

**Comment by PatchRanger** [comment]
@escopecz I got it, thank you.
Looks like one more related issue: #2439 .

**Comment by alanhartless** [comment]
Closing this one for now considering the BC break.

**Comment by escopecz** [comment]
I'd like to get this a second chance for M5.

**Pull request closed without merging**
