### PR TITLE
[UX] Change “Render style from Template?” to “Use theme style?” when creating form

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
The current label “Render style from Template?” presents an opportunity for enhancement. It would be beneficial to make the label more precise and aligned with the rest of the platform’s terminology. The proposed solution in this pull request is to change the label to “Use theme style?”, which directly relates to the improvement desired.

The change primarily benefits users who interact with the form creation process, providing them with a clearer understanding of the options available. By implementing this change, we can expect a more intuitive user experience and a more consistent user interface across the platform. This could potentially lead to users being more comfortable with using the platform and exploring its features.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Go to Forms
3. Create a new form
4. Look at the new title on the right side 

image

### CODE REVIEW

**Review by LordRembo — CHANGES_REQUESTED** [review]
Maybe making it something like "Use current theme style?" would make the most sense, because there are many themes. Could confuse people into thinking they need to select a new theme somewhere.

**Comment by Mike-Dropsolid** [comment]
> Maybe making it something like "Use current theme style?" would make the most sense, because there are many themes. Could confuse people into thinking they need to select a new theme somewhere.

Don't they? Shouldn't they select a theme in the dropdown below when putting this on Yes?

**Comment by andersonjeccel** [comment]
> > Maybe making it something like "Use current theme style?" would make the most sense, because there are many themes. Could confuse people into thinking they need to select a new theme somewhere.
> 
> Don't they? Shouldn't they select a theme in the dropdown below when putting this on Yes?

Yes, I thought it would be intuitive... Maybe we should change the order of the fields to first select a theme and then decide whether or not to use its style?

**Review by LordRembo — APPROVED** [review]
Ah, right, I missed that you can choose a field. My bad, I withdraw my initial statement :D
The order is fine as it is then, I think.

**Review by Mike-Dropsolid — APPROVED** [review]
The order is fine. Great proposal.

**Comment by Mike-Dropsolid** [comment]
Maybe something to investigate in another PR: should the "Theme" field be visible when "Use theme style" is on "No"?

**Comment by andersonjeccel** [comment]
> Maybe something to investigate in another PR: should the "Theme" field be visible when "Use theme style" is on "No"?

I will create an issue for this!

**Pull request merged**
