### PR TITLE
Fix: Dynamic Content in emails (legacy builder)- default content is not saved properly

### LINKED ISSUE #11788: Dynamic Content in emails (legacy builder)- default content is not saved properly
### Mautic Version

4.4.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When using the legacy builder, the default version of the dynamic content is not saved properly.

Was already reported (but never solved)  in https://github.com/mautic/mautic/issues/10540

### How can we reproduce this issue?

Step 1: Disable GrapesJS plugin
Step 2: Create a new email with the legacy builder 
Step 3: Create a dynamic content
Step 4: Create the default version and a variation with filter
Step 5: Save the email
Step 6: See the default window is empty now (note: If you send the email now to test contacts, they will still get the correct version, it’s just in the editor where the default is not saved. Also seems okay in the database)

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by irfanhanfi**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [4.x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #11788 

#### Description:
This PR is to fix the issue mentioned here - https://github.com/mautic/mautic/issues/11788

### CODE REVIEW

**Comment by MadlenF** [comment]
Works as expected from user-perpective!

**Review by kuzmany — DISMISSED** [review]
Works for me 👍 
Just app.js should not be part of the PR. It's regenerated during the release process.

**Comment by beschulz** [comment]
I believe this fix is faulty for html content. We experienced a double escaping issue. Doing the following resolved this:

```
        if (dynConContent.data('froala.editor') && Mautic.getActiveBuilderName() === 'legacy') {
            dynConContent = dynConContent.froalaEditor('html.get');
        } else {
            dynConContent = dynConContent.text();
        }
```

(i.e. using .text() instead of .html().

The way I understand the procedure here is that during init (when the initial html is build from the template) dynConContent isn't yet a froalaEditor - but it does have the ".editor" class. Insepcting the DOM revealed that the content from the database was inserted into the DOM as text, not html. I have the suspicion that this is the actual problem for the double escape and that my proposed fix just plasters over the cracks.

**Comment by mabumusa1** [comment]
@irfanhanfi thank you for this PR, there is a [feedback](https://github.com/mautic/mautic/pull/11887#issuecomment-1422915380), I think it is worth considering

**Comment by irfan-synerzip** [comment]
> @irfanhanfi thank you for this PR, there is a [feedback](https://github.com/mautic/mautic/pull/11887#issuecomment-1422915380), I think it is worth considering

I have addressed that change.

**Comment by beschulz** [comment]
@irfan-synerzip thanks a lot. Although I wonder if this breaks the grapejs stuff. Maybe the whole block should be:

```js
if (Mautic.getActiveBuilderName() === 'legacy') {
    if (dynConContent.data('froala.editor')){
        dynConContent = dynConContent.froalaEditor('html.get');
    } else {
        dynConContent = dynConContent.text();
    }
} else {
    dynConContent = dynConContent.html();
}
```

**Comment by irfan-synerzip** [comment]
@beschulz I did not see the issue with the GrapesJS editor but your approach looks safer. I have made the changes as per the latest comment.

Thank you!

**Review by mabumusa1 — APPROVED** [review]
I tested this PR and rebased it to 4.4, it looks goo to be merged

**Comment by mabumusa1** [comment]
@allcontributors please add @irfanhanfi for code

**Pull request merged**
