### PR TITLE
use a more strict constraint for doctrine-bundle

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes mautic/recommended-project#15 

#### Description:

There was a [recent change](https://github.com/doctrine/DoctrineBundle/pull/1452) in doctrine/DoctrineBundle that is releases since doctrine/DoctrineBundle [2.6.0](https://github.com/doctrine/DoctrineBundle/releases/tag/2.6.0)

That release is used for composer based installs, as [the constraint](https://github.com/mautic/mautic/blob/05020707c20414980ac849fb073201f42a8a7254/app/composer.json#L63) allows to use this version.

Version >= 2.6.0 results in errors on the CLI and in web requests, as [the implementation](https://github.com/mautic/mautic/blob/05020707c20414980ac849fb073201f42a8a7254/app/bundles/CoreBundle/DependencyInjection/Compiler/DbalPass.php#L27) (based on [this comment](https://github.com/doctrine/DoctrineBundle/issues/114#issuecomment-638882114)) is not compatible anymore.

This results in following error:

```
Argument 1 passed to Doctrine\DBAL\Configuration::setResultCacheImpl() must implement interface Doctrine\Common\Cache\Cache, instance of Symfony\Component\Cache\Adapter\ArrayAdapter given, called in /var/www/html/mautic/var/cache/pro_/ContainerHhAx6pL/appAppKernelProdContainer.php on line 2319  
```    

##### Possible solutions

**stricter contraint**

ensure the package is currently locked to < 2.6.0 to prevent this issue

This is implemented in this PR

**make the code compatible**

I would wait for this, as other issues bumped up too since that release:

* https://github.com/doctrine/DoctrineBundle/issues/1501
* https://github.com/doctrine/DoctrineBundle/issues/1485

#### Steps to test this PR:

* run `composer create-project mautic/recommended-project:^4 test-mautic --no-interaction`
* 

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11053"></a>

### CODE REVIEW

**Comment by zaharovrd** [comment]
i Also have this bug

````
bin/console cache:clear

In Configuration.php line 63:
                                                                                                                                     
  Argument 1 passed to Doctrine\DBAL\Configuration::setResultCacheImpl() must implement interface Doctrine\Common\Cache\Cache, inst  
  ance of Symfony\Component\Cache\Adapter\ArrayAdapter given, called in /docroot/var/cache/prod/Container  
  D9Pwsnd/appAppKernelProdContainer.php on line 2317    `


```

**Review by kuzmany — DISMISSED** [review]
I faced this issue and this fixed it 👍 
Big up

**Comment by RCheesley** [comment]
@mollux this PR is still in draft despite having two good tests already 😅 ... does it still require work, or is it good to be considered for merging? If the latter, could you convert it from a draft please? Thanks!

**Comment by mollux** [comment]
@RCheesley indeed :)
done!, I also rebased on the latest 4.2

merging this doesn't automatically resolve the related issue in mautic/recommended-project

**Comment by RCheesley** [comment]
Awesome thanks for that @mollux - indeed we'll have to close that issue I think once we merge this PR.

**Review by adiux — DISMISSED** [review]
This change led to: `Downgrading doctrine/doctrine-bundle (2.6.2 => 2.5.7)
` which solved the issue! Thanks @mollux !

**Pull request merged**
