### PR TITLE
Lead Timeline: display only fields with a value

### PR DESCRIPTION
**Pull request by escopecz**
The problem is outlined in https://github.com/mautic/mautic/issues/773

It was actually caused by form values being moved to the top. So if one value in the middle of the form was empty, all values from below was moved one field up and didn't match the labels.

~~This PR adds an empty space HTML entity when a value is empty.~~ *(edited according to comments)*
This PR displays only fields which has a non-empty value

### CODE REVIEW

**Comment by drmmr763** [comment]
+ vote +1
+ test woohoo!

**Comment by alanhartless** [comment]
My casual feeling here is to not show the label at all . The timeline is a bit crowded and spread out as is so anything we can do to keep it tidy I think will be helpful.  But some might want to see that there is a blank entry and thus want the label.  So I'm open to either way. @dbhurley?

**Comment by dbhurley** [comment]
whoops, thought I commented on this already, perhaps it was a different PR. I agree with @alanhartless - it would save space and probably look better to remove the label rather than add a non-breaking space.

**Comment by escopecz** [comment]
Updated. Now the form event in the Lead Timeline displays only fields with non-empty value. That means it will skip these values:
```
"" (an empty string)
0 (0 as an integer)
0.0 (0 as a float)
"0" (0 as a string)
NULL
FALSE
array() (an empty array)
$var; (a variable declared, but without a value)
```
(http://php.net/manual/en/function.empty.php)

Is the skipped 0 value OK?

**Comment by dbhurley** [comment]
Will the "zero" factor effect fields where a 0 would be an acceptable answer?

**Comment by alanhartless** [comment]
It will; will `!= ''` suffice?

**Comment by dbhurley** [comment]
I think empty string, null, array(), should all be checked.

**Comment by escopecz** [comment]
Is that OK?

**Comment by dbhurley** [comment]
+1 works great!

**Pull request merged**
