### PR TITLE
[UI] Fix reports width

### LINKED ISSUE #9791: Report (Table) Graph Panel Not Filling Space
| Q   | A
| --- | ---
| Mautic version | V2 - V3.2.5
| PHP version | 
| Browser | Chrome & Firefox

### Steps to reproduce
1. Create a report with a table panel view in it. For instance, the standard Submission of published Forms. The Panels at the bottom (.panel css class) don't fill the bootstrap column in Chrome and Firefox but it works fine in MS Edge. I've had this issue since v2 across multiple databases.

mautic-panel-width
_Top left - Chrome, Bottom Left - Firefox, Right - MS Edge_

A simple enough fix is to add the "width:100%" to the .panel class in .app.css

Before I create a pull request, is anyone else having this issue, or is it just something funky going on on my end.

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #9791 

#### Description:

Fixes width.

| Before                                      | After
| -------------------------------------- | ---
| image           | image

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Reports > Submissions of published Forms > See

### CODE REVIEW

**Review by kuzmany — APPROVED** [review]
Better like before 👍

**Review by shinde-rahul — APPROVED** [review]
LGTM!!

Thanks @andersonjeccel!

**Comment by RCheesley** [comment]
This has no milestone associated with it so it's not been in any release notes. Might be worth adding the milestone and updating the release notes?

**Comment by andersonjeccel** [comment]
@RCheesley  I have no idea in which version this was merged

**Comment by escopecz** [comment]
I'm adding the 5.1.0 milestone as that version was released on Jun 13 and this PR merged on Apr 24. M5.0.4 was released on Apr 11 so it wasn't that one.

**Comment by RCheesley** [comment]
Thanks folks, I've added it to the release notes for that release just in case we need to track it down in the future! 🚀

**Pull request merged**
