### PR TITLE
Feature/add rte for grapesjs TPROD-215

### LINKED ISSUE #10004: Grapesjs needs SharedSpace plugin from CKEditor
## Bug Description
With the current implementation of CKEditor, Grapesjs is not working. It apears that Grapesjs needs a plugin called [SharedSpace](https://ckeditor.com/cke4/addon/sharedspace) to work.

Implemented in the Grapesjs CKE preset:
https://github.com/artf/grapesjs-plugin-ckeditor/blob/master/src/index.js

image

> There are other warnings that are not related to the builder that we should address too. 

Without ths we can not replace/remove froala (e.g. needed for dynamci content)

| Q   | A
| --- | ---
| Mautic version | 4
| Browser | all

### Steps to reproduce
1. Enable CKE: https://github.com/adiux/plugin-grapesjs-builder/tree/feature/dc-use-cke-remove-froala
2. Edit an email. Add/edit some text
3. Check the console

 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98541403-grapesjs-needs-sharedspace-plugin-from-ckeditor?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #10289: Implement a Rich Text Editor for grapesJS
The refactoring PR (https://github.com/mautic/mautic/pull/10114) removed the legacy Froala editor. Currently, only the default RTE editor from Grapesjs is available. 

Once the refactoring is done, and all other UI bugs are fixed, we can then add CKE (or any other RTE). 

Related issue:
https://github.com/mautic/mautic/issues/10004

### PR DESCRIPTION
**Pull request by adiux**
Adds the Rich Text Editor (RTE) CKEditor to the grapesjs plugin.

This brings the following features
- Format text inside a grapesjs textblock or button
- Add links inside a text block

image

fixes: https://github.com/mautic/mautic/issues/10289
fixes: https://github.com/mautic/mautic/issues/10004

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Edit an email in HTML mode: check that you can use the features described above
3. Edit an email in MJML mode: check that you can use the features described above
4. Edit a landingpage: check that you can use the features described above
5. Check that there are no errors in the console

### CODE REVIEW

**Review by RCheesley — DISMISSED** [review]
Tested with HTML and MJML email themes, also with landing pages.

Was able to successfully edit existing text blocks and add new blocks, using all the features. Also checked that links are correctly being picked up and converted to tracking links.

I do still get the error in the console relating the the newsletter preset which I believe was recently removed and not related to this PR, so we should address that at some point:

```
grapesjs-preset-newsletter.min.js:15 Uncaught TypeError: Cannot read property 'set' of null
    at r.<anonymous> (grapesjs-preset-newsletter.min.js:15)
    at m (backbone.js:369)
    at v (backbone.js:356)
    at d (backbone.js:155)
    at r.l.trigger (backbone.js:346)
    at EditorView.js:18
```

🚀  Thanks for all the hard work @adiux

**Comment by adiux** [comment]
This error is not related to our code. We should look at fixing it. For now, I can not see any implication on the functionality.  https://github.com/artf/grapesjs-preset-newsletter/issues/52

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
OK thanks for the clarification @adiux - indeed let's keep an eye on it!

Just needs a code review/test and we should be good to go.

**Comment by RCheesley** [comment]
Just testing this after the updates and it looks like we are back with the old preset again?

screenshot-mautic4 ddev site-2021 08 23-16_55_53

the DWC is not getting sent correctly :(

**Comment by RCheesley** [comment]
Codecov is incorrect, PR does not change coverage: https://app.codecov.io/gh/mautic/mautic/compare/10349

**Comment by RCheesley** [comment]
Tried with the latest changes on a fresh installation of Mautic, but now DWC is not being rendered at all in the emails :/ When I edit there is nothing at all where I placed the Dynamic HTML block, either.

Error in console:  

```
Uncaught TypeError: Mautic.getBuilderContainer is not a function
    at i.showDynamicContentPopup (dynamicContent.commands.js:104)
    at run (commands.js:8)
    at r.callRun (CommandAbstract.js:91)
    at Object.runCommand (index.js:388)
    at Object.run (index.js:315)
    at r.onActive (dynamicContent.domcomponents.js:95)
    at m (backbone.js:368)
    at v (backbone.js:356)
    at d (backbone.js:155)
    at r.l.trigger (backbone.js:346)
```

screenshot-mautic4 ddev site_8026-2021 08 24-16_19_08

Screencast: https://youtu.be/t3gl2sRI0SM

**Comment by adiux** [comment]
I just rebuild the code again (for some reason there were changes) and tested it. All worked as expected for me:

Once I did get the variant
image

And once the default
image

**Comment by RCheesley** [comment]
@adiux looks like there is a conflict to be addressed on this one.

**Comment by RCheesley** [comment]
Working now! :D

**Review by RCheesley — DISMISSED** [review]

**Comment by RCheesley** [comment]
All good after the latest merge - RTE working and DC also working! LGTM! 🚀

**Pull request merged**
