### PR TITLE
Fix doctrine fixtures double loading

### LINKED ISSUE #10028: Doctrine fixtures are double-loading reports and custom fields
## Bug Description
When using bin/console d:f:l to load in sample data we are getting duplicates in both reports and custom fields:

screenshot-mautic4 ddev site-2021 05 15-13_42_39

screenshot-mautic4 ddev site-2021 05 15-13_42_57

| Q   | A
| --- | ---
| Mautic version | 4.0.0-alpha1
| PHP version | 7.4
| Browser | Chrome

### Steps to reproduce
1. Load up sample data in a Mautic instance using bin/console d:f:l
2. Check reports and custom fields - you should see duplicates.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98541391-doctrine-fixtures-are-double-loading-reports-and-custom-fields?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by shinde-rahul**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #10028 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Run bin/console d:f:l

### CODE REVIEW

**Review by RCheesley — DISMISSED** [review]
Thanks for making the PR @shinde-rahul - this fixes the issue and there is no longer any duplication.

Are the files that you have removed in this PR no longer used? I wasn't sure if maybe the fake report data was being used to inject info into the reports.

**Comment by shinde-rahul** [comment]
@RCheesley, the removed files were having duplicate code. As the InstallBundle has all required fixtures so removed those.

**Review by RCheesley — APPROVED** [review]

**Comment by RCheesley** [comment]
Bumping from the release due to lack of testing/code review

**Comment by escopecz** [comment]
I couldn't cherry-pick this as the repo and the commits do not exist anywhere. So I made all the changes again in https://github.com/mautic/mautic/pull/11536

**Pull request closed without merging**
