### PR TITLE
Fix contacts roll campaign tab

### PR DESCRIPTION
**Pull request by tomekkowalczyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [yes ]
| New feature/enhancement? (use the a.x branch)      | [ no]
| Deprecations?                          | [no ]
| BC breaks? (use the c.x branch)        | [ no]
| Automated tests included?              | [no ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     |  https://github.com/mautic/mautic/issues/10718

#### Description:
js assets build files are missing the latest changes related to loading contacts assigned to a given campaign in the campaign tab
image

#### Steps to test this PR:

1. Create campaigns
2. Go to the campaign view in the contact tab

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10756"></a>

### CODE REVIEW

**Comment by anthienvu** [comment]
@tomekkowalczyk I have replaced 2 files app.css and app.js but the contacts in campaign tab were still loading. Do I do something wrong?

Update: Contacts are loaded only after pressing save & close the campaign. It still won't autoload for next time.

**Comment by tomekkowalczyk** [comment]
@anthienvu 
Try cleaning cache `php bin/console c:c`
or generate your assets builds `php bin/console mautic:assets:generate`

**Comment by kuzmany** [comment]
I do not see in this PR what files are modified? Probably it was already fixed in some merged PR?

**Comment by tomekkowalczyk** [comment]
@kuzmany it is ultimately about the files `app/assets/css/app.css` and `app/assets/js/app.js`, when making the production package, build js was not done. The problem will be solved when build js is generated with one of the next `php bin/console mautic: assets: generate`

**Comment by escopecz** [comment]
Since the prod assets are generated on production package build I see no need for this PR. I would go as far as adding the 2 into `.gitignore`. I'm closing this PR but shout if I'm missing the point here.

**Pull request closed without merging**
