### PR TITLE
Fix timezone segment rebuild

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
Apply this fix first https://github.com/mautic/mautic/pull/7752
1. Setup local timezone on server to UTC
2. Setup timezone in Mautic configuration or in local.php to Europe/Paris
3. Create two custom field `date `and `datetime `format
4. Then create segment filter with both fields and relative dates
- equal = 2 days
- greater/equal 2 days

image 

5. Run segment rebuild
6. Check sql query in  logs on your dev enviroment
7. If today is 30. 10. 2019, you should see

`SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM (SELECT DISTINCT orp.lead_id as leadIdPrimary, orp.lead_id as id, orp.leadlist_id FROM lead_lists_leads orp LEFT JOIN (SELECT l.id FROM leads l WHERE ((l.custom_date LIKE '2019-10-31%') AND (l.custom_date_time LIKE '2019-11-01%')) OR ((l.custom_date >= '2019-10-31') AND (l.custom_date_time >= '2019-11-01'))) members ON members.id=orp.lead_id WHERE (orp.leadlist_id = 9) AND (members.id IS NULL) AND (orp.manually_added = '0')) sss`

What is wrong. Compare for `date` should be  2019-11-01 and for `datetime` should be for equal  '2019-11-01%' and for gt/gte/lt/lte  should UTC date with time frame 

#### Steps to test this PR:
1. Apply this PR
2. Run segment:rebuild 
3. You should see now in debug on dev enviroment

`SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM (SELECT DISTINCT orp.lead_id as leadIdPrimary, orp.lead_id as id, orp.leadlist_id FROM lead_lists_leads orp LEFT JOIN (SELECT l.id FROM leads l WHERE ((l.custom_date LIKE '2019-11-01%') AND (l.custom_date_time LIKE '2019-11-01%')) OR ((l.custom_date >= '2019-11-01') AND (l.custom_date_time >= '2019-11-01 11:48:12'))) members ON members.id=orp.lead_id WHERE (orp.leadlist_id = 9) AND (members.id IS NULL) AND (orp.manually_added = '0')) sss`

- l.custom_date LIKE '2019-11-01%' - ✔️ 
- l.custom_date_time LIKE '2019-11-01%' - ✔️ 
- l.custom_date >= '2019-11-01' - ✔️ 
- l.custom_date_time >= '2019-11-01 11:48:12' ✔️ 

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/9784"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
@kuzmany is this still WIP? If so let's make it a draft PR?

**Review by escopecz — CHANGES_REQUESTED** [review]
These changes would deserve a good test, functional if possible. Also, description and steps to test are missing.

**Review by alexhammerschmied — DISMISSED** [review]
Works as expected. Just tested it over the last days.

**Comment by alexhammerschmied** [comment]
I just realised that the segment filter 
customfield date/time < today
triggers with date/time if time is available. This is awesome 😎 
Very handy and that solves a lot of issues. That means we can use the segment filters as a workaround for the campaign date/time decision with minutes/hours

**Comment by RCheesley** [comment]
Hi there,

Thank you for your contribution!

As we have released Mautic 4 now, the 3.x version is out of active support and therefore will not receive any further bug fixes or features.

If this PR is still relevant to Mautic 4, please either 

- Rebase on the 4.0 branch (for bug fixes) or the 4.x branch (for features and enhancements), or 
- Close this PR and make a fresh one on the correct branch.

If it is no longer relevant to Mautic 4, please close the PR.

Thanks in advance!

**Comment by alexhammerschmied** [comment]
Seems to work in Mautic 4 as well. Segment membership is changing according to date AND time.

**Comment by RCheesley** [comment]
@kuzmany I have updated the base to 4.0 but this needs test coverage - can you add the tests so we can consider for the 4.1.2 release?

**Comment by RCheesley** [comment]
Removing from the milestone as this is a draft PR.

**Comment by kuzmany** [comment]
@alexhammerschmied  @RCheesley  can you test now based on description. Now should works properly and it's ready to review

**Comment by RCheesley** [comment]
OK great, did you address the [comment from @escopecz](https://github.com/mautic/mautic/pull/9784#pullrequestreview-635759345) about writing a test for this?

**Comment by kuzmany** [comment]
@RCheesley I will write tests later

**Comment by alexhammerschmied** [comment]
I tested it today and everything works as expected 👍

**Comment by RCheesley** [comment]
Thanks @alexhammerschmied - just needs a test written and rebasing to 4.2 then!

**Comment by bradjones1** [comment]
Opened #11798 which is a rebase on 4.4 (since I believe this to be a bugfix) and I also found that the TZ handling here is incorrect. I'm not 100% sure about the current date-only handling, but I think that is probably incorrect as well from the perspective of taking a "local" time and comparing it to the UTC date in the database.

This kind of slop is acceptable when you've only got to be within a day of correct, but relative times like hours or minutes is much more sensitive to TZ comparison. I found that the existing code generated a local-formatted time to compare to the db, which would be off by 0-24 hours, depending on the TZ. So I have changed this to explicitly use UTC if it is a relative comparison. I didn't touch the behavior, otherwise, because that would be a BC break?

**Comment by kuzmany** [comment]
I am gonna close it. We've identify some issue with it and working on new solution for timezones

**Comment by kuzmany** [comment]
This is follow up for this issue https://github.com/mautic/mautic/pull/11835 and more logic improvement like this

**Pull request closed without merging**
