### PR TITLE
Pipedrive - fix with import empty values

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Noticed issue with Pipedrive during import Lead/Company from Pipedrive to Mautic.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Setup Pipedrive with webhook  https://www.mautic.org/docs/en/plugins/pipedrive.html
2. Create contact on Pipedrive
3. Check in Mautic
4. Then try set empty some fields in Pipedrive mapped to Mautic. 
5. Fields with empty value wasn't update 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat all steps
3. The fields are empty now If you  change reset it in Pipedrive

### CODE REVIEW

**Comment by johbuch** [comment]
@kuzmany just tested but it does not work for me.
I created a company in pipedrive. This company was then created in mautic.
Then I empty some field (text, list etc.) but the values are still in the company within mautic

**Comment by kuzmany** [comment]
@johbuch I tested againg. And works for me, see screencast http://somup.com/cqnOQbn3Va
Also I tested it with custom field. 
How did you test it?

**Comment by johbuch** [comment]
@kuzmany I just tested with the company address default field, it worked.
But for a custom field it does not work.
The custom field is updated, but not emptied when I delete the value in pipedrive.
You said, for a custom field it worked for you ?

**Comment by kuzmany** [comment]
@johbuch I will test again.

**Comment by kuzmany** [comment]
@johbuch Try now, It's fixed by last commit.

**Comment by johbuch** [comment]
@kuzmany thanks it works now
good job ;)

**Pull request merged**
