### PR TITLE
TPROD-319 - LeadBundle: migrate views from PHP Engine to Twig

### PR DESCRIPTION
**Pull request by JoshuaEstes**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. 

- Notes on the Contact details page is updated
- Global search template
- History on the Contact details page is updated

### CODE REVIEW

**Comment by escopecz** [comment]
@JoshuaEstes is this the PR that was split into several smaller PRs? Can it be closed?

**Comment by JoshuaEstes** [comment]
@escopecz I would like to use this PR to bring everything together and removed any of the other php templates.

**Comment by mabumusa1** [comment]
@JoshuaEstes let's increase the code coverage for this PR

**Comment by JoshuaEstes** [comment]
@mabumusa1 This should do it.

**Review by RCheesley — CHANGES_REQUESTED** [review]
Bugs found:

- [ ] When you have multiple notes of different types, filtering by type does not work properly as the filter bar is duplicated and the second one does nothing: https://watch.screencastify.com/v/kFg7C64LbZlbX52yHBux
- [ ] When you search, there are multiple warnings popping up - nothing in the console: https://watch.screencastify.com/v/r6x9jXO2MH3Uo9kzyCgV
- [ ] There is a missing language string on the hover for the search results: https://watch.screencastify.com/v/4Jg27wzwLddkwwyGEndx

**Comment by RCheesley** [comment]
Also, conflict to resolve now! 😅

**Comment by JoshuaEstes** [comment]
@RCheesley 

> When you have multiple notes of different types, filtering by type does not work properly as the filter bar is duplicated and the second one does nothing

Notes on 5.x had a few issues. I resolved what I found but looks like this caused this issue. It seems to be resolved with https://github.com/mautic/mautic/pull/11793/commits/ec208d0f49b5447b5f84cbc66f1937002595ecb2 there's also a strange bug with notes where if you select a note type (doesn't matter which and can be more than one) and change the limit per page, it ignores the filter.

> When you search, there are multiple warnings popping up - nothing in the console

I get this on every branch. Not sure the exact cause, but I'm thinking that JS code cancels the request to submit a new one and it will cause the error. I could also be completely wrong. It just seems to happen sometimes.

> There is a missing language string on the hover for the search results

Can't seem to find it and the video doesn't seem to be available. Picture with an arrow pointing the the element can be helpful for me as well.

**Review by mabumusa1 — COMMENTED** [review]
- [X] Contact Dashboard
- [X] Timeline  
- [X] Timeline filter
- [X] Timeline Export
- [X] Event Details 
- [X] Audit Log


The comments stated by @RCheesley are there, but I do not think they are related to this PR

**Comment by sdoering** [comment]
I did not stumble over any issues related to the PR

- [x] Contact Dashboard
- [x] Timeline
- [x] Timeline filter
- [x] Timeline Export
- [x] Event Details
- [x] Audit Log

**Comment by RCheesley** [comment]
> Can't seem to find it and the video doesn't seem to be available. Picture with an arrow pointing the the element can be helpful for me as well.

Ooops, seems it didn't share when copied - fixed now!

It looks like `mautic.lead.lead.pointscount` is a missing translation - visible when you hover over the points count in the global search.

Video-Details-Screencastify

**Comment by JoshuaEstes** [comment]
@RCheesley Resolved https://github.com/mautic/mautic/pull/11793/commits/24fef8e0d86f469a6fac7e88cf05ca775eecf092 Thanks for info

**Comment by jos0405** [comment]
> > Can't seem to find it and the video doesn't seem to be available. Picture with an arrow pointing the the element can be helpful for me as well.
> 
> Ooops, seems it didn't share when copied - fixed now!
> 
> It looks like `mautic.lead.lead.pointscount` is a missing translation - visible when you hover over the points count in the global search.
> 
> Video-Details-Screencastify

Is the missing points translation connected with this bug?
https://github.com/mautic/mautic/issues/11522

**Review by jos0405 — CHANGES_REQUESTED** [review]
Maybe it's not related, but still want to share:
I wanted to test the timeline.
1. Created contact
2. Send email to contact (mailhog.local)
3. Open email in Mailhog
4. reload contact, get 500 error:
[2023-02-19 07:46:41] mautic.CRITICAL: Uncaught PHP Exception TypeError: "Mautic\CoreBundle\Templating\Twig\Extension\DateExtension::formatRange(): Argument #1 ($range) must be of type DateInterval, DateTime given, called in /var/www/html/var/tmp/twig/33/33f7863a73793f58a381db2f71bce609d788eda5686670fb715aa1049bfdf1d3.php on line 78" at /var/www/html/app/bundles/CoreBundle/Templating/Twig/Extension/DateExtension.php line 106 {"exception":"[object] (TypeError(code: 0): Mautic\\CoreBundle\\Templating\\Twig\\Extension\\DateExtension::formatRange(): Argument #1 ($range) must be of type DateInterval, DateTime given, called in /var/www/html/var/tmp/twig/33/33f7863a73793f58a381db2f71bce609d788eda5686670fb715aa1049bfdf1d3.php on line 78 at /var/www/html/app/bundles/CoreBundle/Templating/Twig/Extension/DateExtension.php:106)"} {"hostname":"mautic-web","pid":4877}

**Comment by jos0405** [comment]
There is also another issue - this happens on 4.4.4 as well.
If you API in any html content to Notes, then it will be sanitised.

A call to
https://8080-joshuaestes-mautic-28qhdk2ph6z.ws-eu87.gitpod.io/api/notes/new
using basic auth, payload:
{"lead":1, "type":"email", "text":"this <strong>is a text</strong>"}

Will result in "This is a text" in notes.
Again: same issue with M4, but maybe it's a simple fix?

**Comment by mabumusa1** [comment]
@JoshuaEstes please look into the feedback from @jos0405

**Comment by JoshuaEstes** [comment]
@jos0405 @mabumusa1 

For the API, https://github.com/mautic/mautic/pull/11793/commits/5c5a84caf34c24c7d09035f9239204a711d95bff is the fix for it.

> `[2023-02-19 07:46:41] mautic.CRITICAL: Uncaught PHP Exception TypeError: "Mautic\CoreBundle\Templating\Twig\Extension\DateExtension::formatRange(): Argument https://github.com/mautic/mautic/issues/1 ($range) must be of type DateInterval, DateTime given, called in /var/www/html/var/tmp/twig/33/33f7863a73793f58a381db2f71bce609d788eda5686670fb715aa1049bfdf1d3.php on line 78" at /var/www/html/app/bundles/CoreBundle/Templating/Twig/Extension/DateExtension.php line 106 {"exception":"[object] (TypeError(code: 0): Mautic\CoreBundle\Templating\Twig\Extension\DateExtension::formatRange(): Argument https://github.com/mautic/mautic/issues/1 ($range) must be of type DateInterval, DateTime given, called in /var/www/html/var/tmp/twig/33/33f7863a73793f58a381db2f71bce609d788eda5686670fb715aa1049bfdf1d3.php on line 78 at /var/www/html/app/bundles/CoreBundle/Templating/Twig/Extension/DateExtension.php:106)"} {"hostname":"mautic-web","pid":4877}`

I wasn't able to reproduce this one. Not sure if there is something else that I need to do to reproduce or not? Maybe edge case?

**Comment by mabumusa1** [comment]
@JoshuaEstes I followed the same steps as @jos0405 and I was able to reproduce the issue 

image

**Comment by escopecz** [comment]
I saw this error in some Twig refactoring PR I worked on before. I can't find the change I made but the `formatRange` method is indeed somewhere called with DateTime instead of DateInterval. It does not make sense to call with with DateTime so I would just remove that broken "feature" from the template if there are no 2 dates to make the DateInterval from that would make sense. This was hidden before M5 as we did not use types in this method and were checking if it is type of DateInterval and it it wasn't then it did nothing.

**Comment by JoshuaEstes** [comment]
Found it, resolved in https://github.com/mautic/mautic/pull/11793/commits/e321cc0db3c555cb3ae1a3b3488d462819f42b05 I think this is the correct logic that should be there.

@escopecz @mabumusa1 @jos0405

**Review by escopecz — APPROVED** [review]
I did not notice any issues in the code 👍

**Comment by mabumusa1** [comment]
Code review is done, and several testers approved. this PR is good to go once the CI is green

**Review by mabumusa1 — APPROVED** [review]
I re-tested this PR for the 3rd time and it worked as expected

**Pull request merged**
