### PR TITLE
Fix logger service for integrations

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Notice integrations error are not stored to mautic logs  in https://github.com/mautic/mautic/blob/features/app/bundles/PluginBundle/Integration/AbstractIntegration.php#L2158
This PR resolve it. It replace logger service to mautic logger service

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Core review

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
I see no harm in this code change 👍 

I did not test the plugin though, so if anyone has a CRM plugin configured, please make a quick test.

**Comment by escopecz** [comment]
@kuzmany there is a conflict to resolve.

**Comment by kuzmany** [comment]
I don't see conflicts 
@npracht check it please

**Review by npracht — APPROVED** [review]
👍🏽

**Pull request merged**
