### PR TITLE
Add Endpoint field to S3 plugin

### PR DESCRIPTION
**Pull request by skippednote**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

The endpoint field will allow the plugin to be used with other S3-compliant block storage solutions like DigitalOcean Spaces.

#### Steps to test this PR:

1. Create an S3-compliant bucket on platforms like DigitalOcean Spaces
2. Generate the Spaces API token
3. On the mautic website, go to plugins and click on the S3 plugin
4. Add the relevant credentials including the endpoint found on the Spaces page
5. Under assets, you should be able to access the remote files on Spaces
image

### CODE REVIEW

**Comment by escopecz** [comment]
Hi, thanks for this enhancement! Since there won't be any feature release for Mautic 4, please rebase this to the 5.x branch. It will also need tests to cover this new code and CLA needs to be signed as cla-bot pointed out above.

**Comment by RCheesley** [comment]
@cla-bot check

Thanks for the PR @skippednote and welcome to the community!

**Comment by RCheesley** [comment]
@skippednote could you please either rebase to 5.x or make a new PR please? Thank you!

**Comment by skippednote** [comment]
@RCheesley I've updated the PR. It's created against 5.x now.

**Review by escopecz — DISMISSED** [review]
The code changes look fine. Can you please also write docs for this if it can be used by other services than Amazon S3? It's not obvious from the code nor from the UI.

**Comment by skippednote** [comment]
@escopecz Sure, could you please help me with the relevant file/repo to update?

**Comment by escopecz** [comment]
Good question. We have [docs for the S3 plugin](https://github.com/mautic/mautic-documentation/blob/main/pages/15.Plugins/02.amazon-s3/docs.en.md). So perhaps that's the best place to note it works with other providers as well.

**Comment by skippednote** [comment]
Thanks @escopecz, I have created a PR for that https://github.com/mautic/mautic-documentation/pull/344

**Comment by escopecz** [comment]
Amazing! Thanks!

**Comment by escopecz** [comment]
Please fix the CS issue reported by GH Actions

**Comment by skippednote** [comment]
@escopecz Pushed the fix. Thanks.

**Review by mabumusa1 — APPROVED** [review]
I got testing keys from @escopecz , this code works as expected. I think this PR is ready to go

**Pull request merged**
