### PR TITLE
Leadlist command exit codes

### LINKED ISSUE #11440: The command mautic:segments:update does not return correct exit codes on failure.
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

The command mautic:segments:update does not return correct exit codes on failure.

```php ./bin/console mautic:segments:update -i 242 || echo "error"``` does not return exit code more than zero

### How can we reproduce this issue?

Step 1: As above

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by galvani**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #11440  

#### Description:

The command `mautic:segments:update` does not return correct exit codes on failure. This PR fixes it.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Run the command

 ```bin/console mautic:segments:update -i 999 || echo "should fail"```

3. apply the patch and run again, it should work

### CODE REVIEW

**Comment by MadlenF** [comment]
Works as expected for me!

**Review by jos0405 — DISMISSED** [review]
Works as described.
Before:
Screenshot 2022-09-23 at 14 16 11

After:
image

**Comment by jos0405** [comment]
It's still marked as WIP. Could you plz take a look @galvani and remove WIP before it can be pushed?

**Review by escopecz — DISMISSED** [review]
The changes make sense. The returns are missing when no ID is provided so an error in one segment wouldn't block rebuilding the rest. But when the ID is known we can return a non-zero exit code. It will help debugging and alerts.

**Comment by escopecz** [comment]
Ah, however, this will need a rebase. The 4.x branch is dead. There won't be any feature M4 releases anymore. Please rebase on 5.x branch and if you need this to be released in the final Mautic 4 releases, please create a duplicate PR against 4.4 branch too.

**Comment by escopecz** [comment]
Rebased on 5.x. Will merge once the CI is green

**Comment by escopecz** [comment]
@jos0405 could you please retest? I had to refactor the code a little due to [a bug in Rector](https://github.com/rectorphp/rector/issues/7668) and added a functional test for it.

**Review by mabumusa1 — APPROVED** [review]
This PR is good to go based on the conversation

**Pull request merged**
