### PR TITLE
Fix broken JS in 3b.chosen.ajax.js that makes dropdown broken in campaign builder

### PR DESCRIPTION
**Pull request by npracht**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✅ 
| New feature/enhancement? (use the a.x branch)      | No
| Deprecations?                          | No
| BC breaks? (use the c.x branch)        | No
| Automated tests included?              | N/A
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | 

#### Description:
We have noticed that in certain case sin UI of campaign builder, you are able to break the dropdown in action modal.
Capture d’écran 2023-03-29 à 10 56 39
Capture d’écran 2023-03-29 à 10 56 23

#### Steps to test this PR:
1. Create a lot of email
2. Try search in bar to break the UI
3. See with PR you cannot reproduce.

### CODE REVIEW

**Comment by npracht** [comment]
@adiux maybe you're okay to give a look ? :)

**Comment by adiux** [comment]
@npracht we can take a look. However, there is a test failing.

**Comment by npracht** [comment]
Capture d’écran 2023-03-29 à 12 10 53

codecov not working. It is not related to the PR.

**Comment by kuzmany** [comment]
Looks like this was already fixed with https://github.com/mautic/mautic/pull/10307

**Comment by npracht** [comment]
@patrykgruszka you confirm ?

**Comment by patrykgruszka** [comment]
Yes, this should be fixed. Check if the problem still exists after generating assets: `php bin/console mautic:assets:generate`.

**Comment by RCheesley** [comment]
Closing as this is reported as already being fixed by #10307

**Pull request closed without merging**
