### PR TITLE
Feature webhook authenticity verification

### LINKED ISSUE #6734: Webhook authenticity verification
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No |
| Feature request? | Yes |
| Enhancement? |  Yes |

## Description:
Currently it is not possible for systems using mautic webhooks to verify if a webhook call comes from mautic, and if its payload hasn't been modified.

A common solution for this problem (used for example by [github](https://developer.github.com/webhooks/securing/), [shopify](https://help.shopify.com/en/api/getting-started/webhooks#verify-webhook) and [wooCommerce](http://woocommerce.github.io/woocommerce-rest-api-docs/#webhook-properties)) is to provide a digital signature in the headers of each webhook calls.

In order to do this, mautic has to:
- generate a secret which will be shared with the application receiving the webhooks
- calculate a signature, using this secret on each payload data
- send this signature on webhook calls headers'

This solution didn't introduce breaking changes because each application could implement signature verification or not.

### PR DESCRIPTION
**Pull request by Clement134**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | No |
| New feature? | Yes |
| Automated tests included? | No |
| Related user documentation PR URL |  No |
| Related developer documentation PR URL | https://github.com/mautic/developer-documentation/pull/114 |
| Issues addressed (#s or URLs) | Resolves #6734 | 
| BC breaks? | No |
| Deprecations? | No |

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Add solution to verify webhook authenticity.
A secret is provided or generated on webhook creation. On each webhook call a base64 encoded HMAC-SHA256 signature is computed (with this secret) on the payload data. This signature is added in the header `Webhook-Signature`.
So a third party application (sharing the webhook secret) can compute the signature on the webhook body and verify the signature on the header to be sure that the webhook come from mautic and has not been modified.

For existing webhooks, the migration file automatically generate secret, so mautic can also generate signature for these webhooks.

#### Steps to test this PR:
1. Create a new webhook with `SECRET`
2. Start an api that implement webhook authenticity verification (example in nodeJS below)
3. Trigger the webhook
4. Verify api logs

#### NodeJS implementation example
```javascript
'use strict';

const express = require('express');
const crypto = require('crypto');
const app = express();
const port = 3000;
const SECRET = 'SECRET';

// save raw body
app.use ((req, res, next) => {
    let data = '';
    req.setEncoding('utf8');

    req.on('data', chunk => data += chunk);
    req.on('end', () => {
        req.body = data;
        return next();
    });
});

app.post('/webhook', (req, res) => {
    const receivedSignature = req.headers['webhook-signature'];
    console.log('Received signature (in header):', receivedSignature);

    const computedSignature = crypto.createHmac('sha256', SECRET).update(req.body).digest('base64');
    console.log('Computed signature (from body):', computedSignature);

    if (receivedSignature === computedSignature) {
        console.log('Webhook authenticity verification OK');
    } else {
        console.log('Webhook not authentic!');
    }

    res.send();
});

app.listen(port, () => console.log(`App listening on port ${port}!`));
```

#### List deprecations along with the new alternative:
No deprecations

#### List backwards compatibility breaks:
No backwards compatibility breaks

### CODE REVIEW

**Comment by Woeler** [comment]
@escopecz You assigned yourself, will you test this? I think this would be a great feature for 2.15

**Comment by escopecz** [comment]
I plan to test it.

**Comment by escopecz** [comment]
FWY I created a duplicated PR against the 3.x branch: https://github.com/mautic/mautic/pull/8397

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
Closing as this was merged into Mautic 3.x

**Pull request closed without merging**
