### PR TITLE
Add permissions on campaigns

### PR DESCRIPTION
**Pull request by Enc3phale**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | N
| Automated tests included? | N
| Related user documentation PR URL | N
| Related developer documentation PR URL | N
| Issues addressed (#s or URLs) | N
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Include PR #6240 for campaign permissions and add migration file.

### CODE REVIEW

**Comment by heathdutton** [comment]
Please run the migration file through PHPCS fixer.

**Comment by alanhartless** [comment]
@Enc3phale It'd be best to also update the bitwise in the permissions table.

**Comment by Enc3phale** [comment]
Sorry @alanhartless, but what does bitwise mean?

**Comment by alanhartless** [comment]
Mautic uses bitwise integers to determine permission access. Each level is assigned a bitwise integer. Mautic compares the summed role's bitwise with the individual permission bitwise to determine if the role has that permission. Those values are stored in the permissions table http://php.net/manual/en/language.operators.bitwise.php

Something like this may work (_not tested_ :-) )
```

/** @var \Mautic\CoreBundle\Security\Permissions\CorePermissions $security */
$security            = $this->container->get('mautic.security');
$campaignPermissions = $security->getPermissionObject('campaign');

$bit = 0;
foreach ($newPermissions as $perm) {
    $bit += $campaignPermissions->getValue($name, $perm);
}

$this->connection->update(
    MAUTIC_TABLE_PREFIX.'permissions',
    [
        'bitwise' => $bit,
    ],
    [
        'role_id' => $role['id'],
        'bundle'  => 'campaign',
        'name'    => 'campaigns',
    ]
);
```

**Comment by Enc3phale** [comment]
@alanhartless , thanks! I didn't know bitwise permission access in Mautic.

**Comment by Woeler** [comment]
What this does now really goes a little above my head. @escopecz Myabe you can look at it shortly?

**Comment by escopecz** [comment]
I checked out to `master`, created a role like this:

screenshot 2018-12-05 at 13 44 13

And run the migrations:
```
$ app/console doctrine:migrations:migrate

                    Mautic Migrations


WARNING! You have 4 previously executed migrations in the database that are not registered migrations.
    >> 2017-08-10 12:08:08 (20170810120808)
    >> 2017-09-26 23:43:18 (20170926234318)
    >> 2018-02-06 22:51:01 (20180206225101)
    >> 2018-05-08 20:29:30 (20180508202930)
Are you sure you wish to continue? (y/n)
WARNING! You are about to execute a database migration that could result in schema changes and data lost. Are you sure you wish to continue? (y/n)
Migrating up to 20181204000000 from 20181011150000

  ++ migrating 20181204000000

PHP Notice:  Undefined index: viewown in /Users/jan/dev/mautic/app/bundles/CoreBundle/Security/Permissions/AbstractPermissions.php on line 90
PHP Stack trace:
PHP   1. {main}() /Users/jan/dev/mautic/app/console:0
PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /Users/jan/dev/mautic/app/console:41
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:117
PHP   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/framework-bundle/Console/Application.php:84
PHP   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:193
PHP   6. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->run() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:861
PHP   7. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/symfony/console/Command/Command.php:242
PHP   8. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsMigrateDoctrineCommand.php:54
PHP   9. Doctrine\DBAL\Migrations\Migration->migrate() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php:143
PHP  10. Doctrine\DBAL\Migrations\Version->execute() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php:176
PHP  11. Mautic\Migrations\Version20181204000000->up() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Version.php:270
PHP  12. Mautic\CampaignBundle\Security\Permissions\CampaignPermissions->getValue() /Users/jan/dev/mautic/app/migrations/Version20181204000000.php:81

Notice: Undefined index: viewown in /Users/jan/dev/mautic/app/bundles/CoreBundle/Security/Permissions/AbstractPermissions.php on line 90

Call Stack:
    0.0037     364120   1. {main}() /Users/jan/dev/mautic/app/console:0
    0.0647    2552952   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /Users/jan/dev/mautic/app/console:41
    0.0798    3167656   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:117
    6.9222   73568000   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/framework-bundle/Console/Application.php:84
    6.9224   73568000   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:193
    6.9238   73581984   6. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->run() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:861
    6.9242   73583192   7. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/symfony/console/Command/Command.php:242
    6.9979   75441968   8. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsMigrateDoctrineCommand.php:54
    9.1748   75596608   9. Doctrine\DBAL\Migrations\Migration->migrate() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php:143
    9.1928   75597136  10. Doctrine\DBAL\Migrations\Version->execute() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php:176
   10.8063   79651152  11. Mautic\Migrations\Version20181204000000->up() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Version.php:270
   10.8106   79816240  12. Mautic\CampaignBundle\Security\Permissions\CampaignPermissions->getValue() /Users/jan/dev/mautic/app/migrations/Version20181204000000.php:81

PHP Notice:  Undefined index: viewother in /Users/jan/dev/mautic/app/bundles/CoreBundle/Security/Permissions/AbstractPermissions.phpon line 90
PHP Stack trace:
PHP   1. {main}() /Users/jan/dev/mautic/app/console:0
PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /Users/jan/dev/mautic/app/console:41
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:117
PHP   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/framework-bundle/Console/Application.php:84
PHP   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:193
PHP   6. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->run() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:861
PHP   7. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/symfony/console/Command/Command.php:242
PHP   8. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsMigrateDoctrineCommand.php:54
PHP   9. Doctrine\DBAL\Migrations\Migration->migrate() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php:143
PHP  10. Doctrine\DBAL\Migrations\Version->execute() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php:176
PHP  11. Mautic\Migrations\Version20181204000000->up() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Version.php:270
PHP  12. Mautic\CampaignBundle\Security\Permissions\CampaignPermissions->getValue() /Users/jan/dev/mautic/app/migrations/Version20181204000000.php:81

Notice: Undefined index: viewother in /Users/jan/dev/mautic/app/bundles/CoreBundle/Security/Permissions/AbstractPermissions.php on line 90

Call Stack:
    0.0037     364120   1. {main}() /Users/jan/dev/mautic/app/console:0
    0.0647    2552952   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /Users/jan/dev/mautic/app/console:41
    0.0798    3167656   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:117
    6.9222   73568000   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/framework-bundle/Console/Application.php:84
    6.9224   73568000   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:193
    6.9238   73581984   6. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->run() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:861
    6.9242   73583192   7. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/symfony/console/Command/Command.php:242
    6.9979   75441968   8. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsMigrateDoctrineCommand.php:54
    9.1748   75596608   9. Doctrine\DBAL\Migrations\Migration->migrate() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php:143
    9.1928   75597136  10. Doctrine\DBAL\Migrations\Version->execute() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php:176
   10.8063   79651152  11. Mautic\Migrations\Version20181204000000->up() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Version.php:270
   10.8166   79816272  12. Mautic\CampaignBundle\Security\Permissions\CampaignPermissions->getValue() /Users/jan/dev/mautic/app/migrations/Version20181204000000.php:81

PHP Notice:  Undefined index: editown in /Users/jan/dev/mautic/app/bundles/CoreBundle/Security/Permissions/AbstractPermissions.php on line 90
PHP Stack trace:
PHP   1. {main}() /Users/jan/dev/mautic/app/console:0
PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /Users/jan/dev/mautic/app/console:41
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:117
PHP   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/framework-bundle/Console/Application.php:84
PHP   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:193
PHP   6. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->run() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:861
PHP   7. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/symfony/console/Command/Command.php:242
PHP   8. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsMigrateDoctrineCommand.php:54
PHP   9. Doctrine\DBAL\Migrations\Migration->migrate() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php:143
PHP  10. Doctrine\DBAL\Migrations\Version->execute() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php:176
PHP  11. Mautic\Migrations\Version20181204000000->up() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Version.php:270
PHP  12. Mautic\CampaignBundle\Security\Permissions\CampaignPermissions->getValue() /Users/jan/dev/mautic/app/migrations/Version20181204000000.php:81

Notice: Undefined index: editown in /Users/jan/dev/mautic/app/bundles/CoreBundle/Security/Permissions/AbstractPermissions.php on line 90

Call Stack:
    0.0037     364120   1. {main}() /Users/jan/dev/mautic/app/console:0
    0.0647    2552952   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /Users/jan/dev/mautic/app/console:41
    0.0798    3167656   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:117
    6.9222   73568000   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/framework-bundle/Console/Application.php:84
    6.9224   73568000   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:193
    6.9238   73581984   6. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->run() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:861
    6.9242   73583192   7. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/symfony/console/Command/Command.php:242
    6.9979   75441968   8. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsMigrateDoctrineCommand.php:54
    9.1748   75596608   9. Doctrine\DBAL\Migrations\Migration->migrate() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php:143
    9.1928   75597136  10. Doctrine\DBAL\Migrations\Version->execute() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php:176
   10.8063   79651152  11. Mautic\Migrations\Version20181204000000->up() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Version.php:270
   10.8270   79816272  12. Mautic\CampaignBundle\Security\Permissions\CampaignPermissions->getValue() /Users/jan/dev/mautic/app/migrations/Version20181204000000.php:81

PHP Notice:  Undefined index: editother in /Users/jan/dev/mautic/app/bundles/CoreBundle/Security/Permissions/AbstractPermissions.phpon line 90
PHP Stack trace:
PHP   1. {main}() /Users/jan/dev/mautic/app/console:0
PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /Users/jan/dev/mautic/app/console:41
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:117
PHP   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/framework-bundle/Console/Application.php:84
PHP   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:193
PHP   6. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->run() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:861
PHP   7. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/symfony/console/Command/Command.php:242
PHP   8. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsMigrateDoctrineCommand.php:54
PHP   9. Doctrine\DBAL\Migrations\Migration->migrate() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php:143
PHP  10. Doctrine\DBAL\Migrations\Version->execute() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php:176
PHP  11. Mautic\Migrations\Version20181204000000->up() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Version.php:270
PHP  12. Mautic\CampaignBundle\Security\Permissions\CampaignPermissions->getValue() /Users/jan/dev/mautic/app/migrations/Version20181204000000.php:81

Notice: Undefined index: editother in /Users/jan/dev/mautic/app/bundles/CoreBundle/Security/Permissions/AbstractPermissions.php on line 90

Call Stack:
    0.0037     364120   1. {main}() /Users/jan/dev/mautic/app/console:0
    0.0647    2552952   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /Users/jan/dev/mautic/app/console:41
    0.0798    3167656   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:117
    6.9222   73568000   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/framework-bundle/Console/Application.php:84
    6.9224   73568000   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:193
    6.9238   73581984   6. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->run() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:861
    6.9242   73583192   7. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/symfony/console/Command/Command.php:242
    6.9979   75441968   8. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsMigrateDoctrineCommand.php:54
    9.1748   75596608   9. Doctrine\DBAL\Migrations\Migration->migrate() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php:143
    9.1928   75597136  10. Doctrine\DBAL\Migrations\Version->execute() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php:176
   10.8063   79651152  11. Mautic\Migrations\Version20181204000000->up() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Version.php:270
   10.8496   79816272  12. Mautic\CampaignBundle\Security\Permissions\CampaignPermissions->getValue() /Users/jan/dev/mautic/app/migrations/Version20181204000000.php:81

PHP Notice:  Undefined index: publishown in /Users/jan/dev/mautic/app/bundles/CoreBundle/Security/Permissions/AbstractPermissions.php on line 90
PHP Stack trace:
PHP   1. {main}() /Users/jan/dev/mautic/app/console:0
PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /Users/jan/dev/mautic/app/console:41
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:117
PHP   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/framework-bundle/Console/Application.php:84
PHP   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:193
PHP   6. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->run() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:861
PHP   7. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/symfony/console/Command/Command.php:242
PHP   8. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsMigrateDoctrineCommand.php:54
PHP   9. Doctrine\DBAL\Migrations\Migration->migrate() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php:143
PHP  10. Doctrine\DBAL\Migrations\Version->execute() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php:176
PHP  11. Mautic\Migrations\Version20181204000000->up() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Version.php:270
PHP  12. Mautic\CampaignBundle\Security\Permissions\CampaignPermissions->getValue() /Users/jan/dev/mautic/app/migrations/Version20181204000000.php:81

Notice: Undefined index: publishown in /Users/jan/dev/mautic/app/bundles/CoreBundle/Security/Permissions/AbstractPermissions.php on line 90

Call Stack:
    0.0037     364120   1. {main}() /Users/jan/dev/mautic/app/console:0
    0.0647    2552952   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /Users/jan/dev/mautic/app/console:41
    0.0798    3167656   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:117
    6.9222   73568000   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/framework-bundle/Console/Application.php:84
    6.9224   73568000   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:193
    6.9238   73581984   6. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->run() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:861
    6.9242   73583192   7. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/symfony/console/Command/Command.php:242
    6.9979   75441968   8. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsMigrateDoctrineCommand.php:54
    9.1748   75596608   9. Doctrine\DBAL\Migrations\Migration->migrate() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php:143
    9.1928   75597136  10. Doctrine\DBAL\Migrations\Version->execute() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php:176
   10.8063   79651152  11. Mautic\Migrations\Version20181204000000->up() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Version.php:270
   10.8527   79816272  12. Mautic\CampaignBundle\Security\Permissions\CampaignPermissions->getValue() /Users/jan/dev/mautic/app/migrations/Version20181204000000.php:81

PHP Notice:  Undefined index: publishother in /Users/jan/dev/mautic/app/bundles/CoreBundle/Security/Permissions/AbstractPermissions.php on line 90
PHP Stack trace:
PHP   1. {main}() /Users/jan/dev/mautic/app/console:0
PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /Users/jan/dev/mautic/app/console:41
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:117
PHP   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/framework-bundle/Console/Application.php:84
PHP   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:193
PHP   6. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->run() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:861
PHP   7. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/symfony/console/Command/Command.php:242
PHP   8. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsMigrateDoctrineCommand.php:54
PHP   9. Doctrine\DBAL\Migrations\Migration->migrate() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php:143
PHP  10. Doctrine\DBAL\Migrations\Version->execute() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php:176
PHP  11. Mautic\Migrations\Version20181204000000->up() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Version.php:270
PHP  12. Mautic\CampaignBundle\Security\Permissions\CampaignPermissions->getValue() /Users/jan/dev/mautic/app/migrations/Version20181204000000.php:81

Notice: Undefined index: publishother in /Users/jan/dev/mautic/app/bundles/CoreBundle/Security/Permissions/AbstractPermissions.php on line 90

Call Stack:
    0.0037     364120   1. {main}() /Users/jan/dev/mautic/app/console:0
    0.0647    2552952   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /Users/jan/dev/mautic/app/console:41
    0.0798    3167656   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:117
    6.9222   73568000   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /Users/jan/dev/mautic/vendor/symfony/framework-bundle/Console/Application.php:84
    6.9224   73568000   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:193
    6.9238   73581984   6. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->run() /Users/jan/dev/mautic/vendor/symfony/console/Application.php:861
    6.9242   73583192   7. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/symfony/console/Command/Command.php:242
    6.9979   75441968   8. Doctrine\Bundle\MigrationsBundle\Command\MigrationsMigrateDoctrineCommand->execute() /Users/jan/dev/mautic/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsMigrateDoctrineCommand.php:54
    9.1748   75596608   9. Doctrine\DBAL\Migrations\Migration->migrate() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/MigrateCommand.php:143
    9.1928   75597136  10. Doctrine\DBAL\Migrations\Version->execute() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php:176
   10.8063   79651152  11. Mautic\Migrations\Version20181204000000->up() /Users/jan/dev/mautic/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Version.php:270
   10.8585   79816272  12. Mautic\CampaignBundle\Security\Permissions\CampaignPermissions->getValue() /Users/jan/dev/mautic/app/migrations/Version20181204000000.php:81

Migration 20181204000000 was executed but did not result in any SQL statements
```

**Comment by Woeler** [comment]
Alright. I am going to revert the parent PR, and then I can go ahead with the beta release. We can see if we can get this in before stable, but I really do not want to wait any longer, sorry guys.

**Comment by npracht** [comment]
Fair enough.

@Enc3phale can you close this PR, create a new one containing the one from @Noa83 (#6240) + your migration file corrected ?

Thanks !

**Comment by npracht** [comment]
@escopecz you need to apply #6240 which is only in staging not master ;)

**Comment by escopecz** [comment]
This PR doesn't contain #6240? What was used as the base if not current staging?

**Comment by Enc3phale** [comment]
@escopecz it's only the migration file for #6240 which is already merged in staging.

**Comment by escopecz** [comment]
Hmm, so I don't understand why I need to apply #6240 when I'm testing this PR or how to technically do it.

**Pull request merged**
