### PR TITLE
New actions for plugins API: viewSettings, reload, install

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | tba
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
New API endpoint plugins:
- $apiPlugins->reload() - (inspirated by  https://github.com/mautic/mautic/pull/6201.)
- $apiPlugins->getSettings($integrationName);
-  $apiPlugins->install($package)

#### Steps to test this PR:
Require this API PR https://github.com/mautic/api-library/pull/169
1.  Apply PR  and setup API

**getSettings**

```
$apiPlugins = $api->newApi('plugins', $auth, $apiUrl);
$response =  $apiPlugins->getSettings('Pipedrive');
die(print_r($response));
```

Response should be
`

Response

```json
Array
(
    [update_mautic] => Array
        (
            [Company] => 1
            [Email] => 1
            [LastName] => 0
            [City] => 1
            [FirstName] => 1
        )

    [leadFields] => Array
        (
            [Company] => company
            [Email] => email
            [LastName] => lastname
            [City] => city
            [FirstName] => firstname
        )

    [updateBlanks] => Array
        (
        )

    [objects] => Array
        (
            [0] => Leads
            [1] => Contacts
        )

)
```

**install**

```
$apiPlugins = $api->newApi('plugins', $auth, $apiUrl);
$response =  $apiPlugins->install('kuzmany/mautic-netsuite-bundle');
die(print_r($response));
```

Response should be

Some strings like If you're running `composer require kuzmany/mautic-netsuite-bundle` in console.

**reload**

```
$apiPlugins = $api->newApi('plugins', $auth, $apiUrl);
$response = $apiPlugins->reload();
die(print_r($response));
```

Response should be
`
Array ( [response] => 0 new plugins were installed and 0 updated. )

### CODE REVIEW

**Comment by kuzmany** [comment]
@dongilbert as author of composer plugin please can you review my solution for installation plugin from packageist by API

Usage

```
$apiPlugins = $api->newApi('plugins', $auth, $apiUrl);
$response =  $apiPlugins->install('kuzmany/mautic-netsuite-bundle');
```

Code use shell_exec. 
I can add check for shell_exec later. 
This solution works for me, or exist another solution install plugin from packageist by PHP code?

https://github.com/mautic/mautic/pull/6551/files#diff-83e1d6de27868da82b05d2e563a579abR63

Thanks for help.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebased

**Comment by RCheesley** [comment]
If we are to merge this, we need to have the developer documentation PR ready. It seems that the [PR was closed](https://github.com/mautic/developer-documentation/pull/89#event-1897536578) @kuzmany - will you re-open it or does a new PR need to be made for this?

I've assigned to @dennisameling and @dongilbert (based on the [comment above](https://github.com/mautic/mautic/pull/6551#issuecomment-420571117)) for review.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by escopecz** [comment]
@kuzmany I'd like to have all new API endpoints covered by functional tests. Check https://github.com/mautic/mautic/blob/staging/app/bundles/EmailBundle/Tests/Controller/Api/EmailApiControllerFunctionalTest.php it's not hard to do.

**Comment by kuzmany** [comment]
What about 
> apiPlugins->install

If you decide it's not reliable, I can remove it from PR (I do not use anymore) and can handle it by plugin code in future

**Comment by escopecz** [comment]
Any code that is not covered by tests is not reliable.

**Comment by npracht** [comment]
This is too old. i'll close it and if someone want to carry it again, then we'll re-open it with huge pleasure.

**Pull request closed without merging**
