### PR TITLE
Merge 3.2.2-rc into features branch

### PR DESCRIPTION
**Pull request by hluchas**
Merge 3.2.2-rc into features branch
resolved conflicts from https://github.com/mautic/mautic/pull/9517 (needs to be closed)

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
Looks good 👍

**Comment by dennisameling** [comment]
I think something broke with this PR because I'm just trying to do a fresh installation based on the `features` branch:

The dashboard seems to be broken:

image

Unfortunately don't have time to dive further into this now, but at least wanted to drop this here. CC @npracht 

Can confirm the dashboard is working correctly in the `3.2` branch

**Comment by RCheesley** [comment]
@escopecz @hluchas can you take a look please?

**Comment by hluchas** [comment]
@RCheesley @dennisameling Confirmed. I'll create PR to fix `features` branch

**Comment by hluchas** [comment]
PR with fix here https://github.com/mautic/mautic/pull/9568

**Pull request merged**
