### PR TITLE
Remove dwc session, add cache

### PR DESCRIPTION
**Pull request by aarohiprasad**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Automated tests included? | N
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description: 
Dynamic content cannot use session for tracking because of session cookie does not have samesite none.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Set up dynamic content - https://www.mautic.org/docs/en/dwc/index.html. You need a campaign that has Campaign form as a source, then Request dynamic content, some condition and Push dynamic content. In the page you need the form code, tracking code and the code below:
```
<div data-slot="dwc" data-param-slot-name="[yourSlotName]">
  <h1>Dynamic web content for myslot</h1>
</div>
```
2. When you use it, you see that set-cookie header is there without samesite=none. It is on the file /dwc/[slotName]. The set-cookie is there when you submit the form a reload page.

#### Steps to test this PR:
1. Load up this PR and rebase staging (there are some other sessions fixes)
2. Set up dynamic content - https://www.mautic.org/docs/en/dwc/index.html
3. Check that all cookies have samesite-none. And dynamic content works well.

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
Makes sense, I see no issue with the code. 👍  Thanks!

**Comment by Shubham-Shinde-Acquia** [comment]
Hi @aarohiprasad while creating a campaign with above mentioned steps we got below exception in logs. 

`[2024-03-04T10:05:42.687441+00:00] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1364 Field 'failed_count' doesn't have a default value" at /var/www/html/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 114 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 1364): An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1364 Field 'failed_count' doesn't have a default value at /var/www/html/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:114)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1364): SQLSTATE[HY000]: General error: 1364 Field 'failed_count' doesn't have a default value at /var/www/html/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'failed_count' doesn't have a default value at /var/www/html/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:130)"} {"hostname":"61adb77a202c","pid":19}`

**Review by kuzmany — APPROVED** [review]
Good 👍

**Comment by aarohiprasad** [comment]
@Shubham-Shinde-Acquia This exception is unrelated to the changes in the code. 
Since this is just a switch from session to cache, I don't know if there's much to test. Can we go with 2 reviews and a merge instead @escopecz ?

**Comment by escopecz** [comment]
@aarohiprasad @rohitp19 this exception seem to be related to https://github.com/mautic/mautic/pull/13402. We must fix it before we release Mautic 5.1.0 which was suppose to be this week. @rohitp19 could you please look into it?

**Review by escopecz — APPROVED** [review]
I gave this a test and it was successful:
Screenshot 2024-04-18 at 13 52 59
I did not get the error along the way.

I'll merge this as it works and the reported error by @Shubham-Shinde-Acquia isn't related to this PR. But please, Shubham, let us know how to reproduce it so we could get it fixed.

**Pull request merged**
