### PR TITLE
optimize dashboard queries by adding indexes

### PR DESCRIPTION
**Pull request by pety-dc**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | no, enhancement
| New feature? | no, enhancement
| Automated tests included? | -
| Related user documentation PR URL | -
| Related developer documentation PR URL | -
| Issues addressed (#s or URLs) | -
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
There are a few dashboard items that runs very slow on a big database. This unoptimized behaviour makes login take annoyingly long time.

1.) count failed emails

FireShot Capture 004 - Dashboard - Leadengine - automation maxima hu

Counting failed emails on this dashboard item is done by the following query:
```
SELECT COUNT(t.id) AS count FROM email_stats t WHERE (t.is_failed = '1') AND (t.date_sent BETWEEN '2019-09-10 00:00:00' AND '2019-10-10 15:13:05')
```

This query takes 60 seconds on our database (3.5m records in `email_stats`) to run (less for subsequent query exection)
Adding a composite index on the `is_failed` and `date_sent` fields reduces the execution time below 1s.

2.) Upcoming emails

FireShot Capture 005 - Dashboard - Leadengine - automation maxima hu

```
SELECT ll.event_id,
                   ll.campaign_id,
                   ll.trigger_date,
                   ll.lead_id,
                   e.name AS event_name,
                   e.description AS event_description,
                   c.name AS campaign_name,
                   c.description AS campaign_description,
                   ll.metadata,
                   CONCAT(CONCAT(l.firstname, ' '), l.lastname) AS lead_name 
FROM campaign_lead_event_log ll 
LEFT JOIN campaign_events e ON e.id = ll.event_id 
LEFT JOIN campaigns c ON c.id = e.campaign_id 
LEFT JOIN leads l ON l.id = ll.lead_id WHERE (ll.is_scheduled = 1) AND (e.type = 'email.send') 
ORDER BY ll.trigger_date ASC LIMIT 4
```

This query takes 60-75 seconds on our database (15m records in `campaign_lead_event_log`) to run.
Adding a composite index on the `event_id, `lead_id`, `is_scheduled` fields reduces the execution time around 1s.

(It would also help to move filters from `WHERE` to `LEFT JOIN` conditions where possible)

3.) orphaned page_hits

There has been some cleanup in the database recently and many anonymus contacts got deleted. 
in the `page_hits` table the cascading is set to set lead_id to NULL when the corresponding contact gets deleted from the `leads` table.

FireShot Capture 006 - Dashboard - LeadEngine - ballaingatlan leadengine hu

_(For unknown reasons, mautic seems to count these orphaned users to returning visitoirs. This may be another bug)_

```
SELECT COUNT(t.id) AS count FROM page_hits t WHERE (lead_id IS NULL) AND (t.date_hit BETWEEN '2019-09-02 00:00:00' AND '2019-10-02 14:23:57')
```

This query takes several minutes to run on a 12m record `page_hits` table. 
Adding a composite index on `lead_id`,  `date_hit` fields reduces query execution time to around 1s.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Have millions of records in the `email_stats` table and load the dashboard
2. Have millions of records in the `campaign_lead_event_log` table and load the dashboard
3. Have millions of pagehits with a few million anonym contacts, delete most of the anonym contacts, load the dashboard 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@pety-dc could you please sign the Mautic Contributors Agreement: https://www.mautic.org/contributor-agreement? It looks like there was some issue with your git configuration but we can mark it manually as signed if necessary.

It would be great to see if we can get this merged into 3.2 if possible, which would mean we'd need to get it tested and approved before **Sunday, 15th November**.

I've asked a couple of the core team to take a look and review the proposed changes in the meantime.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by dennisameling** [comment]
Hi @pety-dc! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since this PR has conflicts now, could you please do a `git merge upstream/features` locally to resolve the conflicts? Thanks in advance!

**Pull request closed without merging**
