### PR TITLE
Fixes mautic/issues/9187 - Migration to increase field length for remo…

### LINKED ISSUE #9187: url too long when adding a remote asset generate 500
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.1.1
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create a remote asset
2. Add a long URL (longer than the SQL limit) : `https://www.test.com/test/replays-webinars/mn-test-cybercite-acquisition-fidelisation/merci-replay-mn-test-cybercite-acquisition-fidelisation/video-workshops-conseil-recommandations-adaptees-workshops-conseil-recommandations-adaptees-test-cybercite-acquisition-fidelisation/merci-replay-mn-test-cybercite-acquisition-fidelisation/video-workshops-conseil-recommandations-adaptees-workshops-conseil-recommandations-adaptees` (this link does not exist, don't care of that)

See that the app thrown a 500.

## Suggestions/options to solve this
1. Change this field type to TEXT or LONGTEXT ? It would need migration script.
2. Just handle the limit in the UI by throwing a message saying "too long URL, please make it shorter".
3. Just handle the limit in the UI by interrupting the user from adding more char in the input.

### PR DESCRIPTION
**Pull request by saitanay**
closes https://github.com/mautic/mautic/issues/9187

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.2
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | not applicable
| Related developer documentation PR URL | not applicable
| Issue(s) addressed                     | Fixes #9187

#### Description:
Allows long URLs (more than 191 chars) for remote assers. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Add a remote asset with a really long url. If you don't have one such, you can try the below with 2500+ Characters- 
`https://www.mautic.org/sites/default/files/content-images/Mautic_Logo_RGB_LB_39.png?random=RdkfEXkKJoYZojXeEqhXFTxgfCWrdiyiq2sPmPMDatuHgGsEdJA5QlfoHWCWJnc4goI3X3iR2BU9IRelxLzoyHcKa3pDEkdVtyp966c6pXWDtepAJg8EvcAvbsiNonyLsKVEvKv0QWFrEo4hMyR8ST7XAG7tlC1gFtnuhz5oRCPQy0akLjQ0guZr8khdyjjLtXY3DMzsTdlsx3OpMBHL5rihTxyfPrXcbBL3HW1O4hO8oMoPoagtlZXiYTQvPCnZJHJIhyd6VZztp3Uol41kWvyjbCxqKPqBOCS9jnt1DsH99PzNdJVJhw8XJwKQZ0SbPHSt439GmKfFhmbdHU78KPMwbiPYOBf90anedRUEoij86uez14GDnZbrPwGRPc2ft8SuVyF7a7gInF0DZfAwUPmTdWBOAsgK5YzKA3yJWuBI6BxQzlm9vnQb1cBQCHMm6L5fiBzxTTCJLQMSA173xIf9XCqsltBPFTXmeXFYyBCOO7ROPBa18FNejIIOA71AQR8TNFJSRhhSWEZO4PXfopXvuKce50I2Xx73QttdRkDejwE2AcFdFXdFH4lnphExmP0zms9dAylOms2oPkLnt6goqWISsob05KzNZ8tfrVoZ26eXrCCdDj94iGjYcZnnAc5UGHaIva7QyIOAUSHTYk9AlhDs1bV7I6etz7iw9FKt3smNJRbuW70sgbPBOiP48nHZZTuFcm5mBCvgbkhdPVxVlIIVXL3Ma0XKN2Hon0sk9WbdcXyNoPbTXaacAbOroTB4fcIiksUSr1iPpo3De7KI6YVYd7mJfwY0BYA3g1tZTT4CdqP3cLrgwjb8vsBLD4WopDkte6SAM09mu4YwXIOF6bt1ctXefqPKoSh2bzdpLORQlthO0NQSf8Ma9UY42OWmQAzRGRsfDYi2tVrzasmci1lhdaqOoOOv7ldlZMmBjYbeNi0dlc8b4bFTuKF6fGNaGhzQ4znD45ByQ2TN2xrywMChO2fKJpZKvTs4tB0haGP7FkH24a23XPz0uv45ZzosSUURSnqST0jFd2BDYDC6fxD4HIJ3seFesDugKm3yX2qXm7H4q4YizzP6Ht0pPLVASrMgAgQtf4YDNAQ6WE5QEdjMNbYmy2m65FpoL9e8gweoYFO6UrpfI3SShKvsJQ7nFSyRRfOUXunCjh0USBJZpvkUQbYDp3PAytodLseECI3hERomadTGU8gWzpeFFwqoF95UYUtLjgLr0CHn38pGgT5qaXJPcmqjapg1nvZIUqU5rwojKDpw8pNMYqJ1VryACXS4f40dkfXCG9JAUlwCnXxkwv1nzuqt6O11N0pPkhWb70G6zOnmXL8YdfLbQHOZj0MlYTzJevrLWtWuGwhLEnwakcc2n8c4g9kpWCjC2dsLQ0jy7Ougz7K7vPLqCZcqDrnptDU6kGELluOr1sNarEfWsteBICq6v46F5YtIDLhjLvyith5yiwomWspzKeaHYpA1FlIRVjMzKcMpWh0DbzwYyDHaxBo84APhX3bUFH3O8KNUezksW5HsNwZ3y0n6AGucnM23XkCmKu2ldVXVpLiAa2fQzEyd1brbrljP0DulZz1KoQnrgabgc3FjFVRBxAcA8I7Ik0wifYqUZxgkBDvmSHel3x2wXT9M9dx4bXjxxFcyAiulsTEwsndQkO1hRmaT8GxgRqtw2rRYw1LpGGkIbcEYGeyR8pgXNLOtLyw76XPHsy5cxspoLUzB2PYGFFapiarYpi4ERbv1Yd36YQmlZJSNvRUggnQ3ZLYyfgytN0wkhBnE1cbRt29Fy08FKtQcRAWi0HZcFcGUYqRdVnB08b72TEh1AhsiGilPV7tbprCLIdbiE7wn5DWDPWbIrHgDE9hyUYX7AJzJtFogZYxqIcagLaCWyrg98CqUji0in5kwHvkBFaLoVLA4gcgysgOTHMEnOKogrjplDv4RHB7iRDrt9wEcsJTYjzzMVnOkIcoOk7z7VqRx8iywymTR1gHbnwlQp2uxIT9BKDvOHLuYqYnSEHGBuCOLyQ82BGZGYWKdt8cHhlZkD4OAtUR5k3uzTCUfaGRwrzCKWFdG1ErCxJn0yQ8soT915ZA5sGWOzLQsnjlapVSVWBaAHWqhJZCgvjiwezjfdJyN3MTSJEZtMaBJ9KkZjpCDURDmCtSW4l5LLvrErTYefJzAgvqoUFA1mJdoD6BaCUXUq7zsujCp3S1sFetbCdt589WM8adDxz6A1xkJJRABXQ8JvWTsUpqmKVOdyQh5YIKVvVaUkT4Rw00MU5afLMZAqjjM57tInovdMOBXMwhhQ2OOatqx2sg7MafnQd1uu0dNWVp6Tym7T9dCQJFVjLzqHiYmQAMNEaNyfitXJtoDVOzqVlM23sUCP8VjbDAzzUd5239hUrhkcF5V8uoeBFbcuyhDwXoY8Yljx6SSX5HFjzXqUpoxsIAghvAyHTxxGM2U4aTd0elO4LOhEQ2yCmC7z7BUvazlaErHcHyBdw9QO2GluHOb
`

### CODE REVIEW

**Comment by npracht** [comment]
Due to migration schema, i think we should push it into 3.3.0 (minor version, not patch).

**Comment by saitanay** [comment]
> Due to migration schema, i think we should push it into 3.3.0 (minor version, not patch).

Can you guide me on how I can do that. These doesn't seem to be a 3.3 branch.

**Comment by npracht** [comment]
You need to push against "features" branch. But i can do it my own later, no worries :)

**Comment by saitanay** [comment]
Closing this PR. 

Raised a PR against Features branch as suggested by @npracht above. 

New PR - https://github.com/mautic/mautic/pull/9542

**Pull request closed without merging**
