### PR TITLE
Add is schedule changed method to report

### PR DESCRIPTION
**Pull request by aarohiprasad**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ No]
| New feature/enhancement? (use the a.x branch)      | [Yes ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR adds a method to get the entire schedule of a report in array format. This also checks if the edited schedule is the same as the old schedule in the controller

#### Steps to test this PR:

There is nothing much to test here. The test case covers almost all of the code change

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/12660"></a>

### CODE REVIEW

**Comment by aarohiprasad** [comment]
I am surprisingly getting a phpstan error "Access to an undefined property " on a protected property which is inherited from a parent class. Can we bypass this error?

**Review by roboparker — APPROVED** [review]
Thank you @aarohiprasad

**Comment by RCheesley** [comment]
@aarohiprasad the same applies in this PR - you must provide testing instructions, or if it's not something that is testable and is fully covered by automated tests, please state that in the description and explain why it's not test-able.

Thanks!

**Comment by RCheesley** [comment]
@escopecz query on PHPSTAN here.

**Comment by escopecz** [comment]
@aarohiprasad knows how to fix these errors. She's from my team. Aarohi, please take a look at thise.

**Comment by escopecz** [comment]
Oops, wrong button.

**Review by dadarya0 — APPROVED** [review]
Thans @aarohiprasad

**Review by kuzmany — APPROVED** [review]
Seems like nothing will change; we will only add some pieces of code for internal use.

👍

**Review by rohitpavaskar — APPROVED** [review]

**Pull request merged**
