### PR TITLE
Bugfix for segments multiple filters

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) |  https://github.com/mautic/mautic/issues/4075 https://github.com/mautic/mautic/issues/4082
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create segment
2. Select tags filter
3. Select box doesn't convert to multiple select

#### Steps to test this PR:
1. Apply PR and use php app/console mautic:assets:generate
2. Repeat all steps  for reproduce
3: See if works

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by kuzmany** [comment]
Test here  https://github.com/mautic/mautic/issues/4082#issuecomment-302129729

**Comment by npracht** [comment]
Hi @kuzmany don't you think you could have a look there also ? I think it should be closely related.
capture d ecran 2017-05-24 a 14 08 40

Thanks a lot for your contributions.

**Comment by kuzmany** [comment]
@npracht Did you mean extend this PR https://github.com/mautic/mautic/pull/3944?

**Comment by npracht** [comment]
Tested it is great ! :+1:

**Comment by virlatinus** [comment]
It works as described. +1

**Pull request merged**
