### PR TITLE
[UI] Dashboard widgets

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [X]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR increases the widget padding on the dashboard, removes its borders and makes light gray the dashboard background color. These changes aim to modernize the interface.

Before:

https://github.com/user-attachments/assets/8aabcf90-5a74-4b70-a7ad-0cdd443bf008

After:

https://github.com/user-attachments/assets/d4487f07-5d3f-4a1c-8cda-e002dbffbc20

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open the dashboard
3. Check the widgets and interact

### CODE REVIEW

**Review by shinde-rahul — APPROVED** [review]
LGTM!!!

Thank you @andersonjeccel!!!

**Review by kuzmany — DISMISSED** [review]
Works for me like you describe.
For me contrast is weak. But If others UI  team  approved it, then let's go.

image

**Comment by LordRembo** [comment]
Measuring the contrast, the text vs background is well within the strictest WCAG guidelines. The blue links, as well as the dark grey tooltip bubble with grey text, are very low contrast. Would be best to make that blue darker and the text in the bubble lighter.

**Comment by andersonjeccel** [comment]
I'll leave this as draft for a while until the other fixes happen for the items on top 🙏

**Comment by andersonjeccel** [comment]
> [!WARNING]
> All Tier 1 PRs [need only 1 code review and 1 user testing](https://contribute.mautic.org/governance/code-governance#:~:text=Full%20testing%20and%20approval%20by%20at%20least%20one%20community%20member%20(could%20be%20the%20person%20doing%20the%20code%20review%2C%20but%20should%20not%20be%20from%20the%20same%20company/organisation%20as%20the%20person%20submitting%20the%20PR).) before able to merge. I'll update accordingly.

**Review by LordRembo — CHANGES_REQUESTED** [review]
Not sure if it was left as a review before, so I'm doing it now: there was the request to make contrast changes.

**Comment by andersonjeccel** [comment]
@LordRembo already fixed and updated design in the description ✅

**Pull request closed without merging**
