### PR TITLE
Integration/sparkpost

### PR DESCRIPTION
**Pull request by jfgrissom**
Please answer the following questions:

| Q             | A
| ------------- | ---
| Bug fix?      |  No
| New feature?  |  Yes
| BC breaks?    |  None
| Deprecations? |  None
| Fixed issues  |  None

## Description
This adds the option to select the Sparkpost API transport as an email delivery option. 

## Steps to test this PR
1. Create a Sparkpost account (https://www.sparkpost.com).
2. Once your account is setup and verified, get an API key from https://app.sparkpost.com/account/credentials
3. Once you have an API key, setup your email configuration for Mautic (the url for it should look something like this http://host.yourdomain.tld/s/config/edit)
4. Add your mail delivery information (Use sandbox@sparkpostbox.com if you don't have a sending domain setup with Sparkpost).
5. Select Sparkpost as the sending service.
6. Enter your API Key where it says "Get this from your e-mail delivery service and enter it here.".
7. Click "Send test email" and it should look something like this (an api key is not shown in this picture but it has to be there for this to work).
8. Add a test subscriber and see if he gets the email.

### CODE REVIEW

**Comment by dongilbert** [comment]
BC Breaks is if the PR is going to break Backwards Compatibility. I quickly reviewed the code and it doesn't appear as though it will, so we can actually release it with the very next version of Mautic that is released after this is ready.

**Comment by jfgrissom** [comment]
Tbanks for the infomation on BC. 

Very cool that this could be added to the next release.

I'm glad I could help out on this. I really like the product a lot. It feels good to have contributed to it.

Hopefully I will be able to do more in the future!

I'll be happy to help with any problems that come up related to this.

**Comment by dongilbert** [comment]
There are some merge conflicts that need to be resolved before we can merge this. 

To resolve them, just use git to merge the latest staging branch from Mautic into your `integration/sparkpost` branch and then push it to your fork. It will auto update here and we should be good to go.

**Comment by jfgrissom** [comment]
Hi Don,

Thanks for your patience on this. I've merged your origin/staging into my integration/sparkpost. All the conflicts were automatically resolved so I pushed it back to my origin/integration/sparkpost.

It looks like there are no conflicts. I think you should be set. If not please feel free to text me @ 858-353-6439 and I'll help out quickly.

**Comment by jfgrissom** [comment]
I see the build is failing... HEAD tags were put into the composer files. I'll fix that now and re-push.

**Comment by jfgrissom** [comment]
Hm... sorry for all the failed builds. It looks like there were some changes in the email bundle config. A lot of the array()'s were turned into []'s. I'm not sure where that happened, but it seemed to cause some build issues.

**Comment by jfgrissom** [comment]
Haha, with all the build failures it looks like travis is my personal debugger.

**Comment by alanhartless** [comment]
Why does this PR include 2550 files changed? 😨

**Comment by alanhartless** [comment]
Oh, it looks like all the files were changed to 0755 instead of 0644. That needs to be reverted before this can be merged.

**Comment by jfgrissom** [comment]
Hm... sorry for any confusion.

I did a composer update because I was getting some errors when rebuilding the composer.json.

:(

I'll change the permissions.

Thanks for your patience.

**Comment by jfgrissom** [comment]
Hm... I've fixed the syntax issues that came with the auto-merge (HEAD tags, and some stuff related to the arrays changing between master and staging).

Now when I go to do a composer install (the same way the CI will do it) I'm getting this:

[Symfony\Component\Config\Exception\FileLoaderLoadException]                                                                                                                                                                                                  
  Class \Mautic\PluginBundle\Entity\Addon does not exist in /Users/jasonfgrissom/Repos/mautic-integration-sparkpost-v1/app/config/config.php (which is loaded in resource "/Users/jasonfgrissom/Repos/mautic-integration-sparkpost-v1/app/config/config.php").  
                                                                                                                                                                                                                                                                

                                                          
  [ReflectionException]                                   
  Class \Mautic\PluginBundle\Entity\Addon does not exist  
                                                          

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

                                                                                                                                                                                      
  [RuntimeException]                                                                                                                                                                  
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                                                                           
  Warning: array_map(): An error occurred while invoking the map callback in /Users/jasonfgrissom/Repos/mautic-integration-sparkpost-v1/app/config/config.php on line 85              
  PHP Warning:  array_map(): An error occurred while invoking the map callback in /Users/jasonfgrissom/Repos/mautic-integration-sparkpost-v1/app/config/config.php on line 85         
                                                                                                                                                                                      
                                                                                                                                                                                      
    [Symfony\Component\Config\Exception\FileLoaderLoadException]                                                                                                                      
                                                                                                                                                                                      
    Class \Mautic\PluginBundle\Entity\Addon does not exist in /Users/jasonfgrissom/Repos/mautic-integration-sparkpost-v1/app/config/config.php (which is loaded in resource "/Users/  
  jasonfgrissom/Repos/mautic-integration-sparkpost-v1/app/config/config.php").                                                                                                        
                                                                                                                                                                                      
                                                                                                                                                                                      
                                                                                                                                                                                      
    [ReflectionException]                                                                                                                                                             
    Class \Mautic\PluginBundle\Entity\Addon does not exist

**Comment by alanhartless** [comment]
You may need to manually wipe out the cache files because the 2.0 removed files that the old cache may still be dependent on. Try manually deleting app/cache/prod (and app/cache/dev or app/cache/test if they exist).  Does that get you past it?

**Comment by jfgrissom** [comment]
Oh, I should have mentioned that I tried that. No it doesn't get me passed it.

**Comment by alanhartless** [comment]
Ah, I think I see the issue. Give me a second to fix it.

**Comment by alanhartless** [comment]
See if this change is triggering the error: 
https://github.com/mautic/mautic/commit/398e0ae1dcebf589a75c001562b35ebed33aa2c3

**Comment by jfgrissom** [comment]
That helped but now I have a different error. Looks like some other things happened to the emailbundle config on the merge. I'm looking at it now. 

```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                   
  The service "mautic.email.campaignbundle.subscriber" has a dependency on a non-existent service "mautic.email.model.email".  
                                                                                                                               

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

                                                                                                                                   
  [RuntimeException]                                                                                                               
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                        
                                                                                                                                   
    [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                     
    The service "mautic.email.campaignbundle.subscriber" has a dependency on a non-existent service "mautic.email.model.email".
```

**Comment by jfgrissom** [comment]
I'm not really understanding how this is running on my local machine without any errors... haha. It only runs into problems when I try to run composer.

**Comment by jfgrissom** [comment]
I found the problem with the config. Composer is building now with no issues. So, I'm watching this to see what happens next. :)

Thanks again for your assistance on this!

**Comment by jfgrissom** [comment]
Ok, so it looks like the unit tests are failing now. I'm looking at the cause now. I'm going to grab a bite to eat and come back to this. 

Thanks again for your patience here.

**Comment by jfgrissom** [comment]
So this is interesting, the unit tests passed in the CI pipeline but they failed on my own system.
I think it's because the IP addresses in the test don't match the same subnet I'm on here at home.

This looks good now, please feel free to text me if you see anything else that needs to be reconciled on this.

Thanks again for your patience!

```
1) Mautic\CoreBundle\Tests\Helper\IpLookupHelperTest::testLocalIpIsReturnedWhenNotInRequestScope
Trying to configure method "findOneByIpAddress" which cannot be configured because it does not exist, has not been specified, is final, or is static

2) Mautic\CoreBundle\Tests\Helper\IpLookupHelperTest::testClientIpIsReturnedFromProxy
Trying to configure method "findOneByIpAddress" which cannot be configured because it does not exist, has not been specified, is final, or is static

3) Mautic\CoreBundle\Tests\Helper\IpLookupHelperTest::testClientIpIsReturnedFromRequest
Trying to configure method "findOneByIpAddress" which cannot be configured because it does not exist, has not been specified, is final, or is static

4) Mautic\CoreBundle\Tests\Helper\IpLookupHelperTest::testLocalIpIsReturnedForInternalNetworkIp
Trying to configure method "findOneByIpAddress" which cannot be configured because it does not exist, has not been specified, is final, or is static
```

**Comment by alanhartless** [comment]
Thanks for attending to this. It's getting close! :-)

I can't replicate the failed tests above. `findOneByIpAddress` is a "magic" function that's a feature/leveraged by Doctrine so it's not actually defined anywhere. What version of PHPUnit are you using?

Looking at https://github.com/mautic/mautic/pull/1715/files, there still seems to be a number of files with the wrong file permission. Also, many files removed in 2.0 are now added back (e.g. `/addons/.htaccess`, `app/bundles/AssetBundle/Helper/CampaignEventHelper.php`, etc)

To fix the file permissions, try running this from a terminal (assuming you're not on windows):

```
sudo find /path/to/repo -type f -exec chmod 664 {} \;
```

Commit and push. Then compare https://github.com/mautic/mautic/pull/1715/files with your changes. Delete any files added back that you did not add and commit that. Then let's see what the file diffs look like. 

Thanks!

**Comment by jfgrissom** [comment]
Alan,

Thanks again for your patience.

I'll do a check between master and staging to see the delta for the files that were added. (I won't be able to get to it today... very sorry for that. I'll try to carve out some time tomorrow.)

In looking at all the added files, I must have merged master on mental-auto-pilot (I'm in the habit of doing that from my day job) not realizing that I should have only branched from staging.

Also, for files 664 or 644?

Thanks again,
Jay

**Comment by alanhartless** [comment]
They should be 644. I just verified and I think you're actually ok. The files listed as changed have the wrong permission in the repo so this PR actually fixes them.

But the the files removed from 2.0 and added back to this PR need to be fixed. 

Yea, our master is the latest release while we actively work in staging. It's a bit of a change from "git" standards.

**Comment by jfgrissom** [comment]
Just a heads up. I've not forgotten about this.

I'm looking at the best way to do this. Being a bit more cautious than I have been.
I've run out time this morning but I'll keep chewing on this.

I'll get you an update a soon as I can carve out more time.

**Comment by alanhartless** [comment]
Hi @jfgrissom. No worries!

It almost seems like you need to checkout a fresh staging branch, create a new branch from it, then copy over the changes you made. I've tried to filter through the code diffs and there seems to only be a handful of files affected. 

I completely understand the time issue (or lack thereof!); we're trying to get 2.0 wrapped up so the sooner the better if this is to make it into the 2.0 release. 

Thanks!
Alan

**Comment by alanhartless** [comment]
Hi @jfgrissom Just checking on the status of this? Hope you're well!

**Comment by zstephen** [comment]
Hey @jfgrissom how are you going?
If he's not available, does anyone else have the skills to get this great work over the line?
I wish I did, but no, I don't :(

**Comment by alanhartless** [comment]
Closing this in favor of #2223 due to the lack of feedback. Hope you're OK!!! We'll still give you credit in the changelog.

**Pull request closed without merging**
