### PR TITLE
bug fix : Add check for opcache_invalidate function

### PR DESCRIPTION
**Pull request by 10257**
Please answer the following questions:

| Q             | A
| ------------- | ---
| Bug fix?      | Y
| New feature?  | N
| BC breaks?    | -
| Deprecations? | -
| Fixed issues  | - 

## Description
I tried installing mautic on my shared hosting (OVH) but i got an error 500 during step 3 of the install process. When i tried to refresh i was redirected to the dashboard. 
Then when i tried to save settings i got the same error 500 and the same trace in error logs.

`[2016-06-08 16:38:52] mautic.ERROR: Fatal: Call to undefined function Mautic\CoreBundle\Helper\opcache_invalidate() - in file /mautic/app/bundles/CoreBundle/Helper/CacheHelper.php - at line 167 [] []`

I found this similar issue in drupal, and it could be because the function opcache_invalidate is disabled using disable_functions in php.ini
https://www.drupal.org/node/2408533

[edit]
After further investigating, i found that OVH shared hosting is using this settings :
`opcache.restrict_api /home/ovh/fpm5.6/opcache-status.php` 
Wich prevent the access to the opcode api outside of this particular script.
[/edit]

This pull request add a simple check to verify if opcache_invalidate is available to prevent the error 500.

## Steps to reproduce the bug (if applicable)
Tried on php5.6-fpm
- Disable opcache_invalidate with disable_functions directive or opcache.restrict_api in php.ini
- Restart apache/php-fpm
- Try to save settings in Mautic...
- it doesn't work.

## Steps to test this PR
- Disable opcache_invalidate with disable_functions directive or opcache.restric_api in php.ini
- Restart apache/php-fpm
- Try to save settings in Mautic...
- It works!

### CODE REVIEW

**Comment by dongilbert** [comment]
👍

**Comment by 10257** [comment]
Sorry if i was unclear, i'm not doing PR very often...
I edited my original comment for clarity and to add some new information.
Please tell me if something is missing or if you need other information ?

**Comment by dongilbert** [comment]
You're fine. I had actually commented with a +1 thumbs up to indicate that it was good. It looks like GitHub is having an issue with Emoji's displaying in messages properly. Sorry if the ?? was confusing. 

The PR is good to go, once we get a second confirmation test. Thanks for submitting it!

**Comment by escopecz** [comment]
The configuration gets saved for me :+1:

**Pull request merged**
