### PR TITLE
Add text for the rebuilding contacts time for segment. The text "Tota…

### PR DESCRIPTION
**Pull request by AlanWierzchonCA**
…l time:" was left for the sum of the rebuilding time for all segments

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [No ]
| New feature/enhancement? (use the a.x branch)      | [ Yes]
| Deprecations?                          | [ No]
| BC breaks? (use the c.x branch)        | [ No]
| Automated tests included?              | [ No] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Add text for the rebuilding contacts time for segment. The text "Total time:" was left for the sum of the rebuilding time for all segments.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Run: $ php bin/console mautic:segments:update

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11419"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
Please rebase this PR on 5.x branch. If you want to get this PR into Mautic 4 then create a duplicate PR against the 4.4 branch too.

**Comment by escopecz** [comment]
Well, this is an enhancement. There won't be any feature release for Mautic 4 so this must go to 5.x branch.

**Comment by AlanWierzchonCA** [comment]
Hi @escopecz,

I made rebase these changes to 5.x

Best, 
Alan

**Review by escopecz — APPROVED** [review]
Looks good. The code is straight forward. The output looks like this for me:
Screen Shot 2022-09-15 at 17 05 33

For other testers, the `--timing=1` must be added after the command in the steps to test.

_Note: It's a bit odd that the first segment took more time than the total time, but that formula was not touched by this PR, so I'm leaving it be_

**Review by kuzmany — APPROVED** [review]
I used to use `--timing` parameter. This make it more clear

**Pull request merged**
