### PR TITLE
Extend point action with tagging

### LINKED ISSUE #4736: Extend point action with tagging
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Yes
| Enhancement? | 

## Description:
I would like to extend the point action such that when an action happens, one or multiple tags will be added.
This would help to categorise the traffic and the origins of the points. Especially useful when a client is having multiple products and then is able to setup a tracking that after the 5th product page visit a user gets 20 points and the name of the product can be tagged.
point action extension

### PR DESCRIPTION
**Pull request by vkovic**
closes #4736
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| New feature? | YES
| Automated tests included? | NO
| Issues addressed (#s or URLs) | #4736

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Mautic users can now add tags to point actions. These tags are relational data from 'lead_tags' table. When point action triggers for any lead corresponding tags will be tagged.

#### Steps to test this PR:
Add tags to point action
Check lead tags after triggering above point action

### CODE REVIEW

**Review by Strubbel94 — CHANGES_REQUESTED** [review]
I tried to add a tag to a point action (first screenshot), however I got the following error message (second screenshot)

image

image

**Comment by npracht** [comment]
@vkovic in which case would you use it ? I'd better see that as points trigger.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@vkovic could you take a look at the conflict please? Many thanks!

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Given the inactivity and lack of resolving conflicts I'm going to close this PR down. If anybody would like to pick it up again in the future, please create a new PR and mention this one in the description to link up the two.

**Pull request closed without merging**
