### PR TITLE
add default bcc

### PR DESCRIPTION
**Pull request by regevbr**
| Q  | A
| --- | ---
| Bug fix? |  No
| New feature? |  Yes
| Automated tests included? | No
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/314
| Related developer documentation PR URL | N/A
| Issues addressed (#s or URLs) | N/A
| BC breaks? |  No
| Deprecations? |  No

#### Description:

Add the ability to set a default BCC, so any mail that was not set with one, will get the default one (if set).
1 use case is to save all outgoing emails in a different email account for debugging and history preservation - with this feature it is much easier to achieve without changing 100's of email configurations

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Set a default BCC address in the email configuration section
3. Send out a test email and make sure it was sent to the bcc address as well. ( you will need to configure the email settings to something that will actually send out emails)
4. Create an email template, and set a different bcc email to it
5. Get the email to be sent out (in a flow) and make sure that it was bcc'd to the email specif address and not the default one

### CODE REVIEW

**Comment by regevbr** [comment]
@escopecz @kuzmany can you please review and feedback?

full disclosure: I didn't write php for 7 years or so - actually had to google "php check if array is empty" :-)

**Comment by escopecz** [comment]
I don't see any issue with your code. Nice work! It just must be tested.

**Comment by regevbr** [comment]
@escopecz thanks!
Anything else needed on my part?

**Comment by escopecz** [comment]
Just patience. There is not so many testers.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@regevbr could you take a look at the conflict?

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Hi @regevbr another PR here - we would need you to sign the contributors agreement, and let us know if you're able to fix the outstanding conflicts.

Please let us know, if we don't hear from you within 14 days we'll close the PR.

**Comment by npracht** [comment]
This is too old. i'll close it and if someone want to carry it again, then we'll re-open it with huge pleasure.

**Pull request closed without merging**
