### PR TITLE
Fixes issues with batch processing large number of leads with lists and campaigns

### PR DESCRIPTION
**Pull request by alanhartless**
This PR is mainly a performance boost to be able to properly rebuild lead lists and campaigns without hitting PHP memory limits.

1) Lists are no longer built through the web UI at all (meaning leads are not automatically added or removed based on filters.  Large number of leads would result in not being able to save lead lists and correctly build the leads. Thus it is now handled through the existing `mautic:leadlist:update` command (some aliases were added as well such as `mautic:rebuild:lists`). The command itself has been updated to batch the process to prevent Doctrine from attempting to hydrate all leads at once leading to the memory max issue. The command will now accept the arguments `--batch-limit=1000` which will force 1000 leads to be processed per loop.  The greater the number, the more memory used at once.  Also `--max-leads=1000` was added to limit the number of leads processed per execution of the script. By default, it will process all leads pending being added or removed form the list(s). Finally a `--force` option was added as there is a catch to prevent multiple scripts from overlapping which would lead to possible data collisions  If for some reason you want to force script execution (for example, if you ctrl-c cancelled the command).

To test, simply create a new list with filters that match existing leads then run the command. They should be added.  Preferably test with a 200+ leads (thousands if possible) to get a good test.  Also note that testing in the dev environment will use more memory, and may even see a memory usage increase during the script, because of logging.  Prod environment should see very little memory use increase throughout the process.

Also test manually adding a lead to the list that does not already match the filters.  Run the command and this lead should NOT be auto removed from the list.

2) Campaigns are no longer rebuilt when saving the campaign through the UI which had the same issue as above. Thus the new command `mautic:rebuild:campaigns` has been added.  Like lead lists, it will batch through leads belonging to the lists assigned to a campaign and add leads that should belong or remove leads that should not.  This command has the same arguments as the lead list command above.

Testing is pretty much the same as lead lists above.  The difference is that if you rebuild a lead list that is assigned to a campaign, the leads will be added or removed to the campaign during the list rebuild. In that case, truncate the table campaign_leads table then run the command.  Alternatively, assign a new list (with leads) to the campaign and save.  Then run the `mautic:rebuild:campaigns` command. Also test to ensure that leads manually added or not auto removed and visa versa.

3) The `mautic:campaigns:trigger` command has been updated as well including some aliases such as `mautic:trigger:campaigns` were added. Like the two commands above, larger number of leads caused Doctrine to use up all the available memory leading to fatal errors.  Thus, the process has been batched as well to keep memory in check.  `--batch-limit` will limit the number of events to process per loop. `--max-events` will limit the number of events to process and execute per campaign per script execution. 

Testing this requires a campaign setup and sending leads through that campaign, preferably one that has actions that are set with intervals from a "green/decision" path and "red/non-action" paths to test scheduling and execution of non-action events. 

The following bugs were fixed while dealing with this:
1) Campaign actions that were delayed to a specific date/time were fired prematurely due to an incorrectly used operator
2) Loading a campaign details page with a large number of leads and stats took a long time. Queries were changed to improve this response time
3) Cloning a campaign with a large number of leads failed due to Doctrine attempting to clone each lead as well. Cloning the leads were prevented to allow the command above to take care of it.
4) Manually added leads to a campaign were not marked as manually added and thus removed when the campaign was rebuilt.
5) Removed some of doctrine cascades as it caused issues with being able to delete campaigns and lists with large number of leads assigned. This is already taken care of at the database level.
6) Fixed not being able to delete campaigns that had logs associated for executed events.  This will require a migrations script for the release (doctrine:schema:update should be safe to use for testing).

### CODE REVIEW

**Comment by drmmr763** [comment]
+Test Works as advertised.
+ Vote 1

**Comment by drmmr763** [comment]
Re-testing after PR updates:

1) Tested list update CLI command to update lists. Worked successfully. 

2) Created campaign to send email to 173 leads. 

3) Got a sql error sending. 

```[Doctrine\DBAL\DBALException]                                                
  An exception occurred while executing 'SELECT count(l.id) as count FROM lea  
  ds l LEFT JOIN lead_lists_leads ll ON l.id = ll.lead_id WHERE (l.id IN ())   
  AND ((ll.manually_removed IS NULL) OR (ll.manually_removed = ?))' with para  
  ms [0]:                                                                      
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
  n your SQL syntax; check the manual that corresponds to your MySQL server v  
  ersion for the right syntax to use near ')) AND ((ll.manually_removed IS NU  
  LL) OR (ll.manually_removed = 0))' at line 1                                 

  [PDOException]                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
  n your SQL syntax; check the manual that corresponds to your MySQL server v  
  ersion for the right syntax to use near ')) AND ((ll.manually_removed IS NU  
  LL) OR (ll.manually_removed = 0))' at line 1```

**Comment by drmmr763** [comment]
+ Test works!
+ vote +1

**Comment by dbhurley** [comment]
+1 all good

**Pull request merged**
