### PR TITLE
Change foreign filters to subselect instead of exists

### LINKED ISSUE #5732: Wrong behavior with "Count URL" filter in Segments
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Hello,

In Segments i understand it's possible to combine “Visited URL” filter with "Visited URL Count" filter to segment only contacts who visited X time a “Visited URL” (confirmed yesterday by @kuzmany on Slack)

In fact, it doesn’t work. When i test this segment:
Visited URL = “http://www.my-url-test.com”
AND
Visited URL Count greater or egal 6

Mautic returns all contacts with minimum 1 visit of the URL “http://www.my-url-test.com” and with minimum 6 URL visited (**any** URL). I’m expecting to obtain contacts with 6 visits only for URL “http://www.my-url-test.com”.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 5.6

### Steps to reproduce:
1. Create new segment
2. Add filter "Visited URL" and choose an URL
3. Add filter "Count Visited URL" and choose a condition
4. Inspect history of each contact added to the segment, you'll see the bug 
 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/55303134-wrong-behavior-with-count-url-filter-in-segments?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #7763: email_stats table bloat
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
This issue persisted in Mautic for quite a long time, but seems like recent update made it worse.

Given: quite big Mautic installation, servicing 500k+ contacts, 65+ segments, sending 1m+ emails weekly. email_stats and other mautic tables are using InnoDB engine on MariaDB 10.2

After a day or two disk size of email_stats table becomes much more than data it holds. In our case the table can grow to 90Gb on disk in 1-2 days.

Steps we did to mitigate the issue:

- clear tokens column (found this recommendation a long time ago)
- clear open_details column;
- clear last_opened coluimn;
- optimize the table

After those steps the table size would go back to normal 2-3Gb from 90Gb.

It happens so often we even wrote a script doing this every night.

I wonder if there is a better way to approach the problem?

| Q   | A
| --- | ---
| Mautic version | 2.14.1 
| PHP version | 7.2
| Browser | any 

### Steps to reproduce

Just install Mautic with 500k+customers
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/78228630-email_stats-table-bloat?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #7854: ForeignValueFilterQuery is extremely slow on email_stats
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
We have been experiencing performance issues regarding a segment filter that filters contacts based on date_read in email_stats table.
This is a ForeignValueFilterQuery issue.

Queries performed by mysql in conjuction with this segment looks like this:

```
SELECT DISTINCT l.*, l.id, HJoufRks.lead_id AS HJoufRks_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads HJoufRks ON HJoufRks.lead_id = l.id and (HJoufRks.leadlist_id = 6) 
WHERE (l.last_active > '2019-09-03') 
     AND (EXISTS(SELECT NULL FROM email_stats ypBNlsEH WHERE (ypBNlsEH.lead_id = l.id) AND (ypBNlsEH.date_read > '2019-09-03'))) 
    AND (HJoufRks.lead_id IS NULL) 
    AND (l.id <= 950537) 
    AND ((l.date_added <= '2019-09-04 08:27:35') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```

We have over 600k contacts and the email_stats table has ~4m rows, it consumes ~20GB disk space. (We have 3GB allocated to innoDB buffer pool)
Not only is this query slow on its own, but mysql uses a wrong index to perform those queries in the exists function. Such query takes around 200 seconds to run, and even if I force mysql to use the proper index, it takes 20 seconds. This is the lowest I could find. Other queries (which count the users that are in that segment) take over 600 seconds. 

We experienced serious problems related to this probléme. Unfortunaely If someone adds or removes a Custom Field, other queries get jammed due to `waiting for metadata lock` along with the alter table due to the slow query with exists.

I tried to replace the exists function with a subselect and the query magically ran 200x faster (well below 1s)

```
SELECT DISTINCT l.*, l.id, HJoufRks.lead_id AS HJoufRks_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads HJoufRks ON HJoufRks.lead_id = l.id and (HJoufRks.leadlist_id = 6) 
WHERE (l.last_active > '2019-09-03') 
  AND l.id IN (SELECT lead_id FROM email_stats ypBNlsEH WHERE (ypBNlsEH.date_read > '2019-09-03')) 
  AND (HJoufRks.lead_id IS NULL) 
  AND (l.id <= 950537) 
  AND ((l.date_added <= '2019-09-04 08:27:35') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```

Similar problems have already been mentioned in other issues:
https://github.com/mautic/mautic/issues/2449
https://github.com/mautic/mautic/issues/5404
https://github.com/mautic/mautic/pull/5405
All are related to the poor performane of mysql function `exists` on large databases

I traced back in the git history and found that these foreign table segment queries were changed to use `exists` in this PR: 
https://github.com/mautic/mautic/pull/5755

@galvani It was you who performed and commited these changes. Unfortunately it is not clear from the description of PR why the change was made - other than for better performance. 
What was your motivation to implement `exists` instead of joins? What were your numbers?
There might be some catch in using subselects instead of `exists`
And what do you suggest to solve this serious problem?

Thanks

| Q   | A
| --- | ---
| Mautic version |  2.15.1
| PHP version | 7.2
| Browser | 

### Steps to reproduce
1. Have 500k contacts
2. Have ~4m rows in email_stats
3. Create a segment that filters on contact last_active field "-30 DAY" and email read -30 DAY
4. suffer the performance issues
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by pety-dc**
closes #7854
closes #7763
fixes #5732 

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | yes
| New feature? | yes
| Automated tests included? | no
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
https://github.com/mautic/mautic/issues/7854
Possibly:
https://github.com/mautic/mautic/issues/7763
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

As the https://github.com/mautic/mautic/issues/7854 issue states the `Exists` mysql function works slowly in many occasions if one works with a large database (100k+ leads + daily emails, etc) during segment rebuilding

Changing `Exists` to a `subselect` improves query time by 200x in most of the queries - especially when the segment filter result is a relatively low number of leads (<20% of the total lead count)

So most work was put into changing `exists` to `subselects`
With IN() + Subquery structure mysql can make use of [Firstmatch strategy](https://stackoverflow.com/questions/22300291/what-does-firstmatch-mean-in-a-explain-statement)

Also there was a logical error in how empty and notempty filters are performed on foreign tables: 

> Using a join table is necessary for empty/not empty to work properly
An Exists or IN subquery would not provide the proper result if there is no record for the lead in the foreign table
If we join the foreign table by lead_id and check for the filtered field for Null/notnull, the result will contain both those leads that have no record in the foreign table and those that have but with the value of NULL
Most often if a lead has not or has not done something that is usually stored in a foreign table, there is no record for that data
As empty/not empty you want to check whether that record is present or not

One can try with creating a empty/notempty filter on tags

I also implemented a way for adding index hints on segments QueryBuilder `from` and `joins`

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by pety-dc** [comment]
It turns out that the cause of slowness  was not only due to the `EXISTS` function, but inapproriate indexing. 

There were two queries which I experiences extremely slow execution:

a)
```
SELECT DISTINCT l.*, l.id, HJoufRks.lead_id AS HJoufRks_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads HJoufRks ON HJoufRks.lead_id = l.id and (HJoufRks.leadlist_id = 6) 
WHERE (l.last_active > '2019-09-03') 
     AND (EXISTS(SELECT NULL FROM email_stats ypBNlsEH WHERE (ypBNlsEH.lead_id = l.id) AND (ypBNlsEH.date_read > '2019-09-03'))) 
    AND (HJoufRks.lead_id IS NULL) 
    AND (l.id <= 950537) 
    AND ((l.date_added <= '2019-09-04 08:27:35') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```

b)
```
SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId 
FROM (
SELECT DISTINCT orp.lead_id as leadIdPrimary, orp.lead_id as id, orp.leadlist_id 
FROM lead_lists_leads orp 
LEFT JOIN (
SELECT l.id FROM leads l 
WHERE (l.last_active > '2019-08-13') AND (l.id IN (SELECT CaKepHts.lead_id FROM email_stats CaKepHts WHERE CaKepHts.date_read > '2019-08-13'))
) members ON members.id=orp.lead_id 
WHERE (orp.leadlist_id = '6') AND (members.id IS NULL) AND (orp.manually_added = '0')) sss
```

Changing the query from `EXISTS` to `subselect` solves the slowness of query `a)`, but not the other one.

It turned out that the `email_date_read_lead` index on email_stats is not appropriate for this query. 
However if I add an index that contains the same columns in reverse order as `email_date_read_lead`, query `b)` also gets much faster

**Comment by RCheesley** [comment]
Anybody currently using this in production @npracht @escopecz @heathdutton etc?

**Comment by npracht** [comment]
Not on my side

**Comment by escopecz** [comment]
Not us

**Comment by heathdutton** [comment]
We aren't using this patch in production, but we did notice the above-mentioned issue and offloaded segmentation queries to read replicas to sidestep the issue. They sometimes run for 5~10 minutes per query, and we have a dozen or so running at any given moment to keep up. That's just because of how complicated our segments are, and y'know ~400mil leads. 🤷‍♂ 

This would be worth testing, I just don't have the bandwidth for it at the moment.

**Comment by pety-dc** [comment]
I do

**Comment by RCheesley** [comment]
@pety-dc we need two successful tests in order to merge, and they need to be different people from the person submitting the PR - so trying to find a way to get that achieved :) Do you know of any other folk using this PR in action?

**Comment by pety-dc** [comment]
@RCheesley 
Unfortunately I don't know of any other user who uses this PR in production. We are using it in several instances though.

**Comment by alanhartless** [comment]
We'll need to test this with contacts and records in the millions. We found that often subselects are slower  than exists when looking at a significant amount of data although might be a slower for smaller amounts of data. A lot of profiling went into these query builders to start with.

**Comment by pety-dc** [comment]
@alanhartless 
I can understad that.  I did not create this PR out of pure boredom, but because the existing solution resulted in unacceptable load times of the dashboard. (Clients ran into 504 gateway errors after login while waiting 5-10m)
Adding more RAM did not help. I don't think I should have as much RAM as the the database size. As Ideal as it would be, I can't afford that.

I have 300+k rows  in the `leads` table and ~7m rows in the `email_stats`

Are you suggesting that subselect may be faster in such "medium sized" datasets, but with millions of leads and tens of millions of rows in `email_stats` table exists is faster?

Well, maybe, but there must be a reason for that.  And there must be a reason for `EXISTS` being so slow with my segment. Probably the number of results in the subselect.




The segment filters leads that have shown activity in last X days by `last_active` in `leads` table and by opening an email.

The exact same query (same dates, etc) I described in https://github.com/mautic/mautic/issues/7854
runs now:

5s with exists (after a few subsequent run)
```
SELECT DISTINCT l.*, l.id, HJoufRks.lead_id AS HJoufRks_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads HJoufRks ON HJoufRks.lead_id = l.id and (HJoufRks.leadlist_id = 6) 
WHERE (l.last_active > '2019-09-03') 
     AND (EXISTS(SELECT NULL FROM email_stats ypBNlsEH WHERE (ypBNlsEH.lead_id = l.id) AND (ypBNlsEH.date_read > '2019-09-03'))) 
    AND (HJoufRks.lead_id IS NULL) 
    AND (l.id <= 950537) 
    AND ((l.date_added <= '2019-09-04 08:27:35') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```

1100s with subselect
```
SELECT DISTINCT l.*, l.id, HJoufRks.lead_id AS HJoufRks_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads HJoufRks ON HJoufRks.lead_id = l.id and (HJoufRks.leadlist_id = 6) 
WHERE (l.last_active > '2019-09-03') 
  AND l.id IN (SELECT lead_id FROM email_stats ypBNlsEH WHERE (ypBNlsEH.date_read > '2019-09-03')) 
  AND (HJoufRks.lead_id IS NULL) 
  AND (l.id <= 950537) 
  AND ((l.date_added <= '2019-09-04 08:27:35') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```
In this case the `SELECT lead_id FROM email_stats ypBNlsEH WHERE (ypBNlsEH.date_read > '2019-09-03')` subselect has 432k rows as result.


Let's increase the dates by months

1)
5s with exists
```
SELECT DISTINCT l.*, l.id, HJoufRks.lead_id AS HJoufRks_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads HJoufRks ON HJoufRks.lead_id = l.id and (HJoufRks.leadlist_id = 6) 
WHERE (l.last_active > '2019-10-03') 
     AND (EXISTS(SELECT NULL FROM email_stats ypBNlsEH WHERE (ypBNlsEH.lead_id = l.id) AND (ypBNlsEH.date_read > '2019-10-03'))) 
    AND (HJoufRks.lead_id IS NULL) 
    AND (l.id <= 950537) 
    AND ((l.date_added <= '2019-10-04 08:27:35') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```

950s with subselect
```
SELECT DISTINCT l.*, l.id, HJoufRks.lead_id AS HJoufRks_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads HJoufRks ON HJoufRks.lead_id = l.id and (HJoufRks.leadlist_id = 6) 
WHERE (l.last_active > '2019-10-03') 
  AND l.id IN (SELECT lead_id FROM email_stats ypBNlsEH WHERE (ypBNlsEH.date_read > '2019-10-03')) 
  AND (HJoufRks.lead_id IS NULL) 
  AND (l.id <= 950537) 
  AND ((l.date_added <= '2019-10-04 08:27:35') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```
In this case the `SELECT lead_id FROM email_stats ypBNlsEH WHERE (ypBNlsEH.date_read > '2019-10-03')` subselect has 355k rows as result.


2)
3.8s with exists
```
SELECT DISTINCT l.*, l.id, HJoufRks.lead_id AS HJoufRks_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads HJoufRks ON HJoufRks.lead_id = l.id and (HJoufRks.leadlist_id = 6) 
WHERE (l.last_active > '2019-11-03') 
     AND (EXISTS(SELECT NULL FROM email_stats ypBNlsEH WHERE (ypBNlsEH.lead_id = l.id) AND (ypBNlsEH.date_read > '2019-11-03'))) 
    AND (HJoufRks.lead_id IS NULL) 
    AND (l.id <= 950537) 
    AND ((l.date_added <= '2019-11-04 08:27:35') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```

950s with subselect
```
SELECT DISTINCT l.*, l.id, HJoufRks.lead_id AS HJoufRks_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads HJoufRks ON HJoufRks.lead_id = l.id and (HJoufRks.leadlist_id = 6) 
WHERE (l.last_active > '2019-11-03') 
  AND l.id IN (SELECT lead_id FROM email_stats ypBNlsEH WHERE (ypBNlsEH.date_read > '2019-11-03')) 
  AND (HJoufRks.lead_id IS NULL) 
  AND (l.id <= 950537) 
  AND ((l.date_added <= '2019-11-04 08:27:35') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```
In this case the `SELECT lead_id FROM email_stats ypBNlsEH WHERE (ypBNlsEH.date_read > '2019-11-03')` subselect has 280k rows as result.


3)
4.2s with exists
```
SELECT DISTINCT l.*, l.id, HJoufRks.lead_id AS HJoufRks_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads HJoufRks ON HJoufRks.lead_id = l.id and (HJoufRks.leadlist_id = 6) 
WHERE (l.last_active > '2019-12-03') 
     AND (EXISTS(SELECT NULL FROM email_stats ypBNlsEH WHERE (ypBNlsEH.lead_id = l.id) AND (ypBNlsEH.date_read > '2019-12-03'))) 
    AND (HJoufRks.lead_id IS NULL) 
    AND (l.id <= 950537) 
    AND ((l.date_added <= '2019-12-04 08:27:35') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```

1000s with subselect
```
SELECT DISTINCT l.*, l.id, HJoufRks.lead_id AS HJoufRks_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads HJoufRks ON HJoufRks.lead_id = l.id and (HJoufRks.leadlist_id = 6) 
WHERE (l.last_active > '2019-12-03') 
  AND l.id IN (SELECT lead_id FROM email_stats ypBNlsEH WHERE (ypBNlsEH.date_read > '2019-12-03')) 
  AND (HJoufRks.lead_id IS NULL) 
  AND (l.id <= 950537) 
  AND ((l.date_added <= '2019-12-04 08:27:35') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```
In this case the `SELECT lead_id FROM email_stats ypBNlsEH WHERE (ypBNlsEH.date_read > '2019-12-03')` subselect has 220k rows as result.


4)
5s with exists
```
SELECT DISTINCT l.*, l.id, HJoufRks.lead_id AS HJoufRks_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads HJoufRks ON HJoufRks.lead_id = l.id and (HJoufRks.leadlist_id = 6) 
WHERE (l.last_active > '2020-01-03') 
     AND (EXISTS(SELECT NULL FROM email_stats ypBNlsEH WHERE (ypBNlsEH.lead_id = l.id) AND (ypBNlsEH.date_read > '2020-01-03'))) 
    AND (HJoufRks.lead_id IS NULL) 
    AND (l.id <= 950537) 
    AND ((l.date_added <= '2020-01-04 08:27:35') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```

1000s with subselect
```
SELECT DISTINCT l.*, l.id, HJoufRks.lead_id AS HJoufRks_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads HJoufRks ON HJoufRks.lead_id = l.id and (HJoufRks.leadlist_id = 6) 
WHERE (l.last_active > '2020-01-03') 
  AND l.id IN (SELECT lead_id FROM email_stats ypBNlsEH WHERE (ypBNlsEH.date_read > '2020-01-03')) 
  AND (HJoufRks.lead_id IS NULL) 
  AND (l.id <= 950537) 
  AND ((l.date_added <= '2020-01-04 08:27:35') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```
In this case the `SELECT lead_id FROM email_stats ypBNlsEH WHERE (ypBNlsEH.date_read > '2020-01-03')` subselect has 150k rows as result.


5)
4.2s with exists
```
SELECT DISTINCT l.*, l.id, HJoufRks.lead_id AS HJoufRks_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads HJoufRks ON HJoufRks.lead_id = l.id and (HJoufRks.leadlist_id = 6) 
WHERE (l.last_active > '2020-02-03') 
     AND (EXISTS(SELECT NULL FROM email_stats ypBNlsEH WHERE (ypBNlsEH.lead_id = l.id) AND (ypBNlsEH.date_read > '2020-02-03'))) 
    AND (HJoufRks.lead_id IS NULL) 
    AND (l.id <= 950537) 
    AND ((l.date_added <= '2020-02-04 08:27:35') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```

1000s with subselect
```
SELECT DISTINCT l.*, l.id, HJoufRks.lead_id AS HJoufRks_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads HJoufRks ON HJoufRks.lead_id = l.id and (HJoufRks.leadlist_id = 6) 
WHERE (l.last_active > '2020-02-03') 
  AND l.id IN (SELECT lead_id FROM email_stats ypBNlsEH WHERE (ypBNlsEH.date_read > '2020-02-03')) 
  AND (HJoufRks.lead_id IS NULL) 
  AND (l.id <= 950537) 
  AND ((l.date_added <= '2020-02-04 08:27:35') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```
In this case the `SELECT lead_id FROM email_stats ypBNlsEH WHERE (ypBNlsEH.date_read > '2020-02-03')` subselect has 90k rows as result.


6)
5s with exists
```
SELECT DISTINCT l.*, l.id, HJoufRks.lead_id AS HJoufRks_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads HJoufRks ON HJoufRks.lead_id = l.id and (HJoufRks.leadlist_id = 6) 
WHERE (l.last_active > '2020-03-03') 
     AND (EXISTS(SELECT NULL FROM email_stats ypBNlsEH WHERE (ypBNlsEH.lead_id = l.id) AND (ypBNlsEH.date_read > '2020-03-03'))) 
    AND (HJoufRks.lead_id IS NULL) 
    AND (l.id <= 950537) 
    AND ((l.date_added <= '2020-03-04 08:27:35') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```

1.4s with subselect
```
SELECT DISTINCT l.*, l.id, HJoufRks.lead_id AS HJoufRks_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads HJoufRks ON HJoufRks.lead_id = l.id and (HJoufRks.leadlist_id = 6) 
WHERE (l.last_active > '2020-02-03') 
  AND l.id IN (SELECT lead_id FROM email_stats ypBNlsEH WHERE (ypBNlsEH.date_read > '2020-02-03')) 
  AND (HJoufRks.lead_id IS NULL) 
  AND (l.id <= 950537) 
  AND ((l.date_added <= '2020-02-04 08:27:35') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```
In this case the `SELECT lead_id FROM email_stats ypBNlsEH WHERE (ypBNlsEH.date_read > '2020-03-03')` subselect has 40k rows as result.


I tried to figure out what lead these high query time with subselects and found that my original query uses different indexes with exists and subselect:
explain_exists png
explain_subselect png

The subselect uses `IDX_F5F47C7CB9FC8874` index for `lead_lists_leads` table instead of `PRIMARY` probably for when the subselects yields high result count.

So I rerun all the subselect queries with forcing the same index usage
0) 273s
1) 6.6s
2) 9.8s
3) 8.4s
4) 11s
5) 10s
6) 10s


I checked what SQL my segment yields. Here it is:
With exists:
```
SELECT DISTINCT l.*, l.id, yKihqoDU.lead_id AS yKihqoDU_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads yKihqoDU ON yKihqoDU.lead_id = l.id and (yKihqoDU.leadlist_id = 6) 
WHERE (l.last_active > '2020-02-19') 
  AND (EXISTS(SELECT NULL FROM email_stats ypBNlsEH WHERE (ypBNlsEH.lead_id = l.id) AND (ypBNlsEH.date_read > '2020-02-19')))  
  AND (yKihqoDU.lead_id IS NULL) 
  AND (l.id <= 896409) 
  AND ((l.date_added <= '2020-03-20 11:32:25') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```
finishes in 2-3s

with subselect:
```SELECT DISTINCT l.*, l.id, yKihqoDU.lead_id AS yKihqoDU_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads yKihqoDU FORCE INDEX (PRIMARY) ON yKihqoDU.lead_id = l.id and (yKihqoDU.leadlist_id = 6) 
WHERE (l.last_active > '2020-02-19') 
  AND (l.id IN (SELECT LtzBcMpU.lead_id FROM email_stats LtzBcMpU WHERE LtzBcMpU.date_read > '2020-02-19')) 
  AND (yKihqoDU.lead_id IS NULL) 
  AND (l.id <= 896409) 
  AND ((l.date_added <= '2020-03-20 11:32:25') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```
Finishes in 1-2s


If I run the query with `EXPLAIN EXTENDED` now they use the same indexes.
So it is possible that the very poor performance what I previously experienced with exists was due to inproper index usage done by mysql optimizer and subselect seemed to lead mysql optimizer to a more proper index usage.


Besides in the op I talked about `FirstMatch strategy` which clearly didn't appear in current tests
https://mariadb.com/kb/en/exists-to-in-optimization/
While it did with my first tests

The original subselect query with proper index usage and hinting firstMatch strategy finishes in 5.8s
```
SELECT DISTINCT l.*, l.id, HJoufRks.lead_id AS HJoufRks_lead_id 
FROM leads l 
LEFT JOIN lead_lists_leads HJoufRks FORCE INDEX (PRIMARY) ON HJoufRks.lead_id = l.id and (HJoufRks.leadlist_id = 6) 
WHERE (l.last_active > '2019-10-03') 
  AND l.id IN (SELECT /*+ SEMIJOIN(FIRSTMATCH) */ lead_id FROM email_stats ypBNlsEH WHERE (ypBNlsEH.date_read > '2019-10-03')) 
  AND (HJoufRks.lead_id IS NULL) 
  AND (l.id <= 950537) 
  AND ((l.date_added <= '2019-10-04 08:27:35') OR (l.date_added IS NULL)) 
ORDER BY l.id
LIMIT 300
```


Now you could ask why all the hassle when exists does it all. 
Well I can say that I wouldn't have done it if the existing solutions didn't resulted in unacceptable query times.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by npracht** [comment]
Hello @pety-dc could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback, i would very love to merge it in 3.0.1 if still relevant. Thanks !

**Comment by kfrankie** [comment]
> Anybody currently using this in production @npracht @escopecz @heathdutton etc?

@RCheesley we are using this on production, it speeds up things for email_stats >16M rows  and lead_list_leads >32M rows

**Comment by npracht** [comment]
@pety-dc can you have a look at conflicts ?
Thanks !

**Comment by RCheesley** [comment]
Bumping this to 3.1.1 due to unresolved conflicts.

**Comment by RCheesley** [comment]
Hi folks, we are pushing this back to 3.1.2 to give time to address the conflicts and get the contributor's agreement signed.

@pety-dc this will need to be done by the **18th October** to be considered for inclusion.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by dennisameling** [comment]
Hi @pety-dc! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since this PR has conflicts now, could you please do a `git merge upstream/features` locally to resolve the conflicts? Thanks in advance!

**Pull request closed without merging**
