### PR TITLE
Change 'Uttaranchal' to 'Uttarakhand' in regions.json

### PR DESCRIPTION
**Pull request by akhilrawat001**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging for features or enhancements / 3.0 for bug fixes 
| Bug fix?                               | yes
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2.

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Thanks for the PR @akhilrawat001 - confirmed the correct spelling via the Wikipedia entry [here](https://en.wikipedia.org/wiki/Administrative_divisions_of_India).

How do you propose managing folk who might already have this selected? I think we maybe need a migration to take care of that and update them to the new spelling?

**Comment by akhilrawat001** [comment]
> Thanks for the PR @akhilrawat001 - confirmed the correct spelling via the Wikipedia entry [here](https://en.wikipedia.org/wiki/Administrative_divisions_of_India).
> 
> How do you propose managing folk who might already have this selected? I think we maybe need a migration to take care of that and update them to the new spelling?

yes you are right.

**Comment by RCheesley** [comment]
> yes you are right.

Would you be able to do that? If not we can get one of the Product Team to help. We have a release freeze on Sunday for 3.1.1 so if we can get the migration in and tested by then we should be good to get it merged!

**Comment by akhilrawat001** [comment]
> > yes you are right.
> 
> Would you be able to do that? If not we can get one of the Product Team to help. We have a release freeze on Sunday for 3.1.1 so if we can get the migration in and tested by then we should be good to get it merged!

I won't be able to. I am sorry 😞

**Comment by akhilrawat001** [comment]
> > yes you are right.
> 
> Would you be able to do that? If not we can get one of the Product Team to help. We have a release freeze on Sunday for 3.1.1 so if we can get the migration in and tested by then we should be good to get it merged!

I don't think I will be able to.

**Comment by RCheesley** [comment]
OK no worries, I've provisionally tagged this for the 3.1.2 release. That means that we have a bit more breathing space. The deadline for that release is the 18th October.

Would you like some guidance with writing the migration, or are you able to do that yourself? Thank you again for taking the time to make the PR!

**Comment by akhilrawat002** [comment]
> OK no worries, I've provisionally tagged this for the 3.1.2 release. That means that we have a bit more breathing space. The deadline for that release is the 18th October.
> 
> Would you like some guidance with writing the migration, or are you able to do that yourself? Thank you again for taking the time to make the PR!

I would like some guidance. Thank you.

**Comment by akhilrawat001** [comment]
> OK no worries, I've provisionally tagged this for the 3.1.2 release. That means that we have a bit more breathing space. The deadline for that release is the 18th October.
> 
> Would you like some guidance with writing the migration, or are you able to do that yourself? Thank you again for taking the time to make the PR!

I would like some guidance thankyou.

**Comment by dennisameling** [comment]
@akhilrawat001 I just created a PR against Mautic's contribution docs with information about migrations: https://github.com/mautic/mautic-community-handbook/pull/24 - you can read it here: https://github.com/mautic/mautic-community-handbook/blob/2ce6a7dcc0526319ad7f6623029ea00d3d8884ad/pages/13.contributing/02.developer/01.Code/02.Pull%20requests/docs.md#step-6-migrations-needed

You can take inspiration from a similar PR which updates Portugal's regions: https://github.com/mautic/mautic/pull/8134/files

Please let us know if you need further instructions/help!

**Comment by akhilrawat001** [comment]
> @akhilrawat001 I just created a PR against Mautic's contribution docs with information about migrations: [mautic/mautic-community-handbook#24](https://github.com/mautic/mautic-community-handbook/pull/24) - you can read it here: https://github.com/mautic/mautic-community-handbook/blob/2ce6a7dcc0526319ad7f6623029ea00d3d8884ad/pages/13.contributing/02.developer/01.Code/02.Pull%20requests/docs.md#step-6-migrations-needed
> 
> You can take inspiration from a similar PR which updates Portugal's regions: https://github.com/mautic/mautic/pull/8134/files
> 
> Please let us know if you need further instructions/help!

Thankyou. I will go through it.

**Comment by RCheesley** [comment]
@akhilrawat001 do you think that you can follow the steps outlined in the docs to create the migration or do you need someone to do that for you?

Would be good to get this merged!

**Comment by akhilrawat001** [comment]
> @akhilrawat001 do you think that you can follow the steps outlined in the docs to create the migration or do you need someone to do that for you?
> 
> Would be good to get this merged!

I am not well. I am down with a fever. I will not be able to do it within 2-3 days.

**Comment by npracht** [comment]
Hello @akhilrawat001 ! We hope you're doing better now :)
Any chance you have a look at the migration schema for this PR ? Then we can include your PR in next release :)

**Comment by akhilrawat001** [comment]
@RCheesley I  am having trouble running mautic locally. The command to generate a migration file is not working, how do I proceed from here.

**Comment by RCheesley** [comment]
Hi there!

I would recommend setting up locally with DDEV and GitHub CLI if you are able to. I walked through how to do that on the video here: https://youtu.be/qw3qITyWS0I

It would be helpful to know what steps you are getting stuck on with the migration, that will allow us to help with troubleshooting. 

I have just merged in the changes from the features branch so that the PR is up to date for testing.

**Comment by RCheesley** [comment]
Hi @akhilrawat001 I am looking into this, but I am stuck with the lack of any testing instructions in the PR description. Can you point me in the right direction to where this regions file is used? I had thought it would be under contacts > state but that dropdown has the correct value.  

I tried creating the migration file as is explained in the docs and was able to create it, but need to know which table/column would need to be updated!

**Comment by RCheesley** [comment]
Bumping from the release due to outstanding issue with migration being required.

**Comment by akhilrawat001** [comment]
> Hi @akhilrawat001 I am looking into this, but I am stuck with the lack of any testing instructions in the PR description. Can you point me in the right direction to where this regions file is used? I had thought it would be under contacts > state but that dropdown has the correct value.
> 
> I tried creating the migration file as is explained in the docs and was able to create it, but need to know which table/column would need to be updated!

This PR can help https://github.com/mautic/mautic/pull/8134/files 
- File: app/migrations/Version20200815153711.php

@RCheesley

**Review by escopecz — APPROVED** [review]
I rebased this against 5.x and added the migration

**Pull request merged**
