### PR TITLE
Added an option for excluding segments when creating/updating segment emails

### PR DESCRIPTION
**Pull request by fedys**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [❌]
| New feature/enhancement? (use the a.x branch)      | [✅]
| Deprecations?                          | [❌]
| BC breaks? (use the c.x branch)        | [❌]
| Automated tests included?              | [✅] 
| Related user documentation PR URL      |  
| Related developer documentation PR URL |  
| Issue(s) addressed                     |  

#### Description:

As a user of Mautic, I want to exclude certain email addresses for segment emails, so that I can save time by avoiding all the steps required to go through a Campaign to exclude certain emails. This will prevent the need for extra segments built to handle exclusion cases

#### Steps to test this PR:

1. Create at least two segments with a couple of contacts.
2. Create a new segment email and select one segment in _Contact segment_ field and another segment in _Exclude contact segment_ field.
3. Save and send the email.
4. The contacts belonging to the excluded segment should not receive any email.

### CODE REVIEW

**Review by rohitpavaskar — APPROVED** [review]

**Review by kuzmany — APPROVED** [review]
Works for me 👍

**Comment by Galokh66** [comment]
Tested and verified that exclude segment contacts do not receive email, also these contacts are not shown under email contacts

**Review by Galokh66 — APPROVED** [review]

**Comment by RCheesley** [comment]
@fedys looks like we missed a docs update here - any possibility of adding this to https://docs.mautic.org/en/5.x/channels/emails.html#segment-broadcast-emails?

cc @mautic/education-team - this one is require for the 5.1 release.

**Comment by fedys** [comment]
> @fedys looks like we missed a docs update here - any possibility of adding this to https://docs.mautic.org/en/5.x/channels/emails.html#segment-broadcast-emails?
> 
> cc @mautic/education-team - this one is require for the 5.1 release.

@RCheesley I'll create a PR.

**Comment by RCheesley** [comment]
Thanks so much @fedys - ping me if you need any assistance with Vale etc!

**Comment by fedys** [comment]
@RCheesley See https://github.com/mautic/user-documentation/pull/268.

**Pull request merged**
