### PR TITLE
Front end web notifications label

### PR DESCRIPTION
**Pull request by GaberNeighbor**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| New feature? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Steps to test this PR:
1. Create a new web notification, testing each field individually for correct validation
2. Edit an existing web notification, testing each field individually for correct validation

#### Additional note - this PR is contingent on a bug fix for web notifications. In the current platform, if the user enters a name for the notification but not a header or message, the save/close module breaks. In this branch, the user gets the MautiBot

### CODE REVIEW

**Comment by escopecz** [comment]
Fix the 1code standard issues](https://travis-ci.org/mautic/mautic/jobs/263556608#L1151) please.

**Comment by GaberNeighbor** [comment]
@escopecz issues fixed

**Comment by dongilbert** [comment]
@GaberNeighbor This looks good. What do you think about dynamically updating the preview via JS to reflect the heading, link, and body content?

**Comment by virlatinus** [comment]
Tested it and it works as described but the error is thrown when there is no header or message.

**Comment by alanhartless** [comment]
We to be careful with file permissions. Files should be 0644 and directories 0755. This PR seems to have changed a bunch of file permissions which will need to be fixed before we can merge. @dongilbert can you help with that?

**Comment by virlatinus** [comment]
@alanhartless @dongilbert I just fixed the file permissions

**Comment by dongilbert** [comment]
I'm working on a JS change that I discussed with @GaberNeighbor

**Pull request merged**
