### PR TITLE
Code mode slot - placeholder

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/6442
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Code Mode block without content, or with content without input (scripts, css) are not showen in builder, then cannot select it for editation. This PR added gray block with small icon in right corner for code mode block.

You can test with https://mautibox.com/6454

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create an email or LP
2. Choose a theme (not the code mode)
3. Drag and drop the code mode bloc
4. Insert a script inside
5. Save the email or LP
6. Go back on the builder and see that you won't be able to the code mode bloc anymore in the builder.
 

#### Steps to test this PR:
1.  Apply PR and `run php app/console m:a:g`. Mautibox is in developement mode, not require this step.
2.  Repeat all steps and see gray placeholder in CodeMode slot area

image

### CODE REVIEW

**Comment by johbuch** [comment]
tested with mautibox, it works !

**Comment by escopecz** [comment]
@kuzmany I was able to replicate the issue and it works well in the builder, but when I save the page/email and preview then I can see "CODEMODE" written in the content and in the HTML I can see also the buttons to delete and clone the slot. Those should not be in the result HTML.
screen shot 2018-09-24 at 21 29 17

**Comment by kuzmany** [comment]
@escopecz  I cannot reproduce your issue. 
I did again test and works for me. 
I think its not related to this PR. You set something wrong and builder crash and insert some another HTML.  This PR just added additional CSS to builder, on page/email preview this CSS are not used.

image

**Comment by YosuCadilla** [comment]
Tested, I don't see the "Gray placeholder" mentioned in the PR test steps, however I do see the desired final result ( in my case a submit button) within the builder's WYSIWYG render block (left side of the screen).

So I was able to save, come back and edit again, it always worked flawlessly (just no "gray placeholder").

**Pull request merged**
