### PR TITLE
TPROD-336 - FocusBundle - Convert PHP Templates to Twig Templates

### PR DESCRIPTION
**Pull request by JoshuaEstes**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. 

- `/s/focus` List
  - renders correctly (with and without focus items)
  - can be sorted and filtered
- `/s/focus/new` New
  - Form is rendered correctly
  - Builder works as expected
- `/s/focus/edit/{id}` Edit
  - Form is rendered correctly
  - Builder works as expected
- `/s/focus/view/{id}` Details
  - page is rendered correctly
- Focus Item JS can be placed onto a web page and is rendered correctly (can be done using Landing Pages within Mautic. Best to use HTML with little to no other elements)
- Create/Edit a Campaign > Open Builder > Add Decision for Visits Page > Add a new action for the yes branch > Select **Show Focus Item** > Make sure form renders

**NOTES**
- If you find errors, let me know how to setup the Focus Item the exact same. Try to toggle different settings on/off to see if a setting is on/off will make a difference

**KNOWN ISSUES** that exist on the 5.x branch
- GIVEN you are on `/s/focus` AND have existing Focus Items WHEN you click on the publish toggle to publish or unpublish THEN it will only work once. You will need to reload the page in order to get this to work again

### CODE REVIEW

**Review by daniellord32 — CHANGES_REQUESTED** [review]
/s/focus List

- [x] renders correctly (with and without focus items)
- [x] can be sorted and filtered

/s/focus/new 

- [x] Form is rendered correctly
- [ ] Builder works as expected (See issue no 1 in issues below).

/s/focus/edit/{id} Edit

- [x] Form is rendered correctly
- [x] Builder works as expected

/s/focus/view/{id} Details

- [x] page is rendered correctly
- [ ] Focus Item JS can be placed onto a web page and is rendered correctly (can be done using Landing Pages within Mautic. Best to use HTML with little to no other elements) See issue no 2

- [x] Create/Edit a Campaign > Open Builder > Add Decision for Visits Page > Add a new action for the yes branch > Select Show Focus Item > Make sure form renders

Found issues

1. When creating a focus item with the following settings I hit a 500 error. I did not choose a color and left them blank. Perhaps we could default to white for the background and black for the text.
[2023-02-17 09:14:26] mautic.CRITICAL: Uncaught PHP Exception TypeError: "MauticPlugin\MauticFocusBundle\Templating\Twig\Extension\FocusBundleExtension::MauticPlugin\MauticFocusBundle\Templating\Twig\Extension\{closure}(): Argument #1 ($hexColor) must be of type string, null given, called in /var/www/html/var/tmp/twig/fe/fe76b9c0c83720704036e8cbf5fe04240f9a2a7924d552a1163473eb7194484d.php on line 39" at /var/www/html/plugins/MauticFocusBundle/Templating/Twig/Extension/FocusBundleExtension.php line 31 {"exception":"[object] (TypeError(code: 0): MauticPlugin\\MauticFocusBundle\\Templating\\Twig\\Extension\\FocusBundleExtension::MauticPlugin\\MauticFocusBundle\\Templating\\Twig\\Extension\\{closure}(): Argument #1 ($hexColor) must be of type string, null given, called in /var/www/html/var/tmp/twig/fe/fe76b9c0c83720704036e8cbf5fe04240f9a2a7924d552a1163473eb7194484d.php on line 39 at /var/www/html/plugins/MauticFocusBundle/Templating/Twig/Extension/FocusBundleExtension.php:31)"} {"hostname":"mautic-web","pid":2431}

2. Not sure I tested this correctly getting the following in console
image

**Comment by JoshuaEstes** [comment]
@daniellord32 

> Builder works as expected (See issue no 1 in issues below).

Resolved https://github.com/mautic/mautic/pull/11931/commits/64a649d29f02c674b65ff079ab9e6bee9c4006ad

>  Focus Item JS can be placed onto a web page and is rendered correctly (can be done using Landing Pages within Mautic. Best to use HTML with little to no other elements) See issue no 2

It looks like browser/server issue where it's blocking the js code from loading. You can try to do a landing page within the mautic install, however I found it was best to use a little html as possible. When testing I noticed grapesjs errors that were somehow causing this to fail.

**Comment by sdoering** [comment]
Hi, 

while testing, I stumbled upon behavior I was not expecting. I used html code in the builder and it renders in this way: 

image


Everything else seemed to work.

**Comment by JoshuaEstes** [comment]
@sdoering 

> while testing, I stumbled upon behavior I was not expecting. I used html code in the builder and it renders in this way:

Resolved https://github.com/mautic/mautic/pull/11931/commits/5ac74f13ac7adad8ad7fce11369ce7c39a35e19c

**Review by RCheesley — APPROVED** [review]
Tested all the UI and everything works as expected including embedding on landing pages and using HTML!

🚀

**Review by escopecz — APPROVED** [review]
I don't see anything wrong with the code. Thanks! 👍

**Pull request merged**
