### PR TITLE
Fix send unpublished SMS

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✅ 
| New feature/enhancement? (use the a.x branch)      | no
| Deprecations?                          | no
| BC breaks? (use the c.x branch)        | no
| Automated tests included?              | ✅ 
| Related user documentation PR URL      | no need
| Related developer documentation PR URL | no need
| Issue(s) addressed                     | 

#### Description:
This is weird. Unpublished SMS were sent.

#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2. Create SMS 
3. Unpublish it
4. Create campaign with send SMS
5. Before PR SMS was sent, after PR return 
6. 
image

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10577"></a>

### CODE REVIEW

**Comment by kuzmany** [comment]
@RCheesley this is critical issue. We should consider add it to next release.

**Review by npracht — DISMISSED** [review]
This fixes the issue !!

Capture d’écran 2021-12-23 à 09 50 48

**Review by escopecz — DISMISSED** [review]
The code looks great, tests included 👍

**Review by escopecz — APPROVED** [review]
re-approving

**Pull request merged**
