### PR TITLE
retrigger gitpod image generation and update ddev to latest version

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

When troubleshooting a test failure, I noticed the gitpod `composer` version is still 1.10 (inside the ddev shell it's 2.5). The ddev version is also outdated.

The main cause is that gitpod caches the generated image, and it is only regenerated when the dockerfile changes.
Composer 2 support was added in gitpod on Feb 4, 2022, [see here](https://github.com/gitpod-io/workspace-images/pull/660), but the last change of the dockerfile was on Nov 9, 2021, [see here](https://github.com/mautic/mautic/pull/10500).

This PR ensures the latest `gitpod/workspace-full` is used (by regenerating the Mautic gitpod image), and ddev is up-to-date. Next to that, ddev is installed via the recommended way (see https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/), and the phpmyadmin is added separately, as it's not part anymore of the ddev core

**before:**
```
gitpod /workspace/mautic $ composer -V
Deprecation Notice: Required parameter $path follows optional parameter $schema in /usr/share/php/JsonSchema/Constraints/UndefinedConstraint.php:62
Deprecation Notice: Required parameter $path follows optional parameter $schema in /usr/share/php/JsonSchema/Constraints/UndefinedConstraint.php:108
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:130
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:130
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:130
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:130
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:130
Composer 1.10.1 2020-03-13 20:34:27

gitpod /workspace/mautic $ ddev version
 ITEM            VALUE                                   
 DDEV version    v1.18.2                                 
 architecture    amd64                                   
 db              drud/ddev-dbserver-mariadb-10.3:v1.18.2 
 dba             phpmyadmin:5                            
 ddev-ssh-agent  drud/ddev-ssh-agent:v1.18.0             
 docker          20.10.8                                 
 docker-compose  v2.2.2                                  
 mutagen         0.12.0                                  
 os              linux                                   
 router          drud/ddev-router:v1.18.2                
 web             drud/ddev-webserver:v1.18.2             

```

**after:**
```
gitpod /workspace/mautic (gitpod-image-update) $ composer -V
Composer version 2.5.5 2023-03-21 11:50:05

gitpod /workspace/mautic (gitpod-image-update) $ ddev version
 ITEM             VALUE                                   
 DDEV version     v1.21.6                                 
 architecture     amd64                                   
 db               drud/ddev-dbserver-mariadb-10.4:v1.21.5 
 dba              phpmyadmin:5                            
 ddev-ssh-agent   drud/ddev-ssh-agent:v1.21.5             
 docker           23.0.3                                  
 docker-compose   v2.15.1                                 
 docker-platform  mollux-mautic-thpbyh2qnfo               
 mutagen          0.16.0                                  
 os               linux                                   
 router           drud/ddev-router:v1.21.5                
 web              drud/ddev-webserver:v1.21.5                       
 
```

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. verify that you can login into Mautic (which means DDEV is working)
3. verify phpmyadmin (port 8036) is working
4. check the ddev version: `ddev version`
5. check the composer version: `composer -V`

### CODE REVIEW

**Review by RCheesley — CHANGES_REQUESTED** [review]
Mautic login works ✅ 

PHPMyAdmin is not starting correctly:
screenshot-mollux-mautic-3jpcvx6i7wb ws-eu102 gitpod io-2023 07 25-13_23_44

screenshot-8036-mollux-mautic-3jpcvx6i7wb ws-eu102 gitpod io-2023 07 25-13_24_00

DDEV on 1.22.0 ✅ 
gitpod /workspace/mautic (gitpod-image-update) $ ddev --version
ddev version v1.22.0

Composer on v2 ✅ 
gitpod /workspace/mautic (gitpod-image-update) $ composer -V
Composer version 2.5.5 2023-03-21 11:50:05

**Comment by mollux** [comment]
@RCheesley well, [they released 1.22 yesterday](https://github.com/ddev/ddev/releases), let's see what's going on

**Comment by mollux** [comment]
@RCheesley could you re-check? I tested it with the previous minor version, and it all works (the test failure is unrelated)

**Review by RCheesley — APPROVED** [review]
Works fine with the 1.21.6 release of DDEV - we can make a later PR to bump to the minor when the issue with Gitpod ports is addressed.

**Comment by RCheesley** [comment]
Had a chat with @rfay about this and we can fix the ports issue like this:

In the docker-compose.gitpod.yaml add:

```
services:
  phpmyadmin:
    ports:
    - "8036:80"
```

Have raised https://github.com/ddev/ddev-phpmyadmin/issues/3 for a possibly more elegant longer term solution.

**Comment by rfay** [comment]
`ddev get ddev/ddev-phpmyadmin` should work OK for you now on Gitpod.

**Comment by escopecz** [comment]
I'm a bit confused by the comments. Do we need an update to this PR or is it ready to merge?

**Comment by mollux** [comment]
@escopecz we can merge it already, to ensure the images are more up-to-date.
We can than in another PR update to the latest version

**Pull request merged**
