### PR TITLE
[PHP 8.0] Remove unused catch variable

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Rebased and good to go :+1:

**Comment by TomasVotruba** [comment]
Good to go :partying_face:

**Comment by TomasVotruba** [comment]
CI is passing, but just to be sure I rebased :+1:

**Review by escopecz — APPROVED** [review]
One less distraction 👍 Good to go, thanks!

**Pull request merged**
