### PR TITLE
revert logic so correct template is included

### LINKED ISSUE #12589: Unable to use forms in a focus item
### Mautic Version

5.0.x series

### PHP version

8

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When I try to use data capture for the focus item and select a form, there is an error.

### How can we reproduce this issue?

Step 1: Create a focus item and choose collect data in the builder
Step 2: Select a form, check the logs for an error and notice that no form is displayed.

### Relevant log output

```shell
[2023-07-26 15:16:32] mautic.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "text.html.twig" (looked into: /var/www/html/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views, /var/www/html/templates, /var/www/html/vendor/symfony/twig-bridge/Resources/views/Form)." at /var/www/html/app/bundles/FormBundle/Resources/views/Builder/form.html.twig line 78 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Unable to find template \"text.html.twig\" (looked into: /var/www/html/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views, /var/www/html/templates, /var/www/html/vendor/symfony/twig-bridge/Resources/views/Form). at /var/www/html/app/bundles/FormBundle/Resources/views/Builder/form.html.twig:78)"} {"hostname":"mautic-web","pid":2076}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #12589 

#### Description:

the logic in selecting the correct template is wrong:
when there is no theme defined, the theme template is used (which doens't exist).
This PR corrects the logic, so the correct template is used

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. see #12589

be aware that you won't be able to save the focus item, as there is another bug, that will be tackled in another PR

### CODE REVIEW

**Comment by mollux** [comment]
will first investigate the test failures, those are weird

**Review by escopecz — APPROVED** [review]
Makes sense 👍

**Comment by escopecz** [comment]
It seems this will need some tests update

**Comment by RCheesley** [comment]
I think maybe it's a bit broken still, when I try to run `bin/console d:f:l` I get:

`  Unable to find template "@themes/blank/Field/text.html.twig" (looked into: /var/www/html/themes).  `

**Comment by RCheesley** [comment]
Converted to draft until this can be completed.

**Comment by mollux** [comment]
closing in favour of #12702

**Comment by escopecz** [comment]
Shoot, I could have saved some troubles if we've gotten a second test on this back then. I'm merging short bugfix PRs directly after I confirm they fix the issue and there is no issue with the code. Otherwise this project won't move and more devs will fix the same bug 🤦

**Comment by mollux** [comment]
@escopecz np!

**Pull request closed without merging**
