### PR TITLE
Fix set import template to send custom email If use legacy builder

### LINKED ISSUE #10604: CKEditor load error on personal email after upgrading to 4.0.1 version
### Mautic Version

4.0.0

### PHP version

7.4.27.

### What browsers are you seeing the problem on?

Firefox, Chrome, Not relevant

### What happened?

When sending a personal email, CKEditor is not fully loaded, so no Template emails can be loaded into the editor.

### How can we reproduce this issue?

Step 1: Got to Contact and select a contact (go into detail page of the contact)
Step 2: Open Google Chrome or other browser (like FireFox) developer tools and navigate to the console window
Step 3: Click to Send Email button (on contact detail page)
Step 4: On the modal windows choose the "Import from an existing template" select field and select any template

In the developer tool console window you will get "Uncaught CKEditor is not initialized yet, use ckeditor() with a callback." error message - and the email template is not loaded.

I tested this issue in 4 different servers in 4 different Mautic production instance. The issue was appeared after upgrading from 3.x to 4.x version. 

### Relevant log output

```shell
No PHP log.

The issue is related with /app/bundles/CoreBundle/Assets/js/libraries/ckeditor/adapters/jquery.js?v16bd556d

Console log: Uncaught CKEditor is not initialized yet, use ckeditor() with a callback.
```
The screenshot of the issue: 

ScreenShot_20211107235334
### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... https://github.com/mautic/mautic/issues/10604

#### Description:

If GrapesJs builder is disabled. Then it's not possible import template in send email to contact form. This PR fixed it

#### Steps to test this PR:

T

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester)). Require `php bin/console mautic:assets:generate` on production
2. Disable GrapesJs 
3. Refresh browser
4. Go to contact detail page
5. Try send email with import template of existing email

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10897"></a>

### CODE REVIEW

**Comment by medsun88** [comment]
Hi @kuzmany

#10897 , This is Not Working. 

I changed in File on production :  app/bundles/LeadBundle/Assets/js/lead.js
run 
Clear Cache. 
and this did not work, same Problem, email not loading.

**Comment by kuzmany** [comment]
@medsun88 Require `php bin/console mautic:assets:generate` on production

**Comment by medsun88** [comment]
> @medsun88 Require `php bin/console mautic:assets:generate` on production

@kuzmany ,  Yes Worked after clearing browser cache,  Thanks

**Review by volha-pivavarchyk — APPROVED** [review]
Works as expected after running php bin/console mautic:assets:generate.
It's possible to import template now.

**Pull request merged**
