### PR TITLE
Fix 500 error for integrations

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

I was not able to open setting of GrapesJs in actual 5.x
This PR fixed it
Note: GrapesJs does not work at the moment

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open GrapesJs configuration.
3. See 500 error
4. After PR should work

### CODE REVIEW

**Comment by volha-pivavarchyk** [comment]
The plugin settings work well. But the builder doesn't open up to me.
I've tested both the local and gitpod. 

image

**Review by daniellord32 — CHANGES_REQUESTED** [review]
No longer displays a 500 error. One thing I noticed is that the tab is not active by default. Clicking this will show the settings but perhaps it should be active and not have the class fade

image

**Comment by kuzmany** [comment]
@volha-pivavarchyk know issue, but not this PR cover it
@daniellord32 know issue, but not this PR cover it

**Review by volha-pivavarchyk — DISMISSED** [review]
This PR fixes 500er

**Comment by volha-pivavarchyk** [comment]
@kuzmany I double-checked. I can open the Grapes JS builder on the 5.x branch and on the current branch without `services.php`.

**Comment by kuzmany** [comment]
Ok, I will check it

**Comment by kuzmany** [comment]
@escopecz subscribers does not load with autowire, I had to add it to config.php back

At the moment it return 

`RuntimeException: The "MauticPlugin\GrapesJsBuilderBundle\Entity\GrapesJsBuilderRepository" entity repository implements "Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepositoryInterface", but its service could not be found. Make sure the service exists and is tagged with "doctrine.repository_service".`


What should I add to services.php to run it?

**Comment by escopecz** [comment]
@kuzmany do you mean Repositories?

The repositories are in the same directory as entities. The entities must be excluded as those are not service classes. But repositories are. So the Entity directory is excluded and repositories then must be configured as services. Example: https://github.com/mautic/mautic/blob/5.x/app/bundles/ChannelBundle/Config/services.php#L23

**Comment by kuzmany** [comment]
@escopecz yes, I did it like that. But wonder If not work 

https://github.com/mautic/mautic/pull/11896/files#diff-662dee0c1319d0f3b46647b36ce0fde17a436eecd6d1c178cf4de852d4d1835bR22

**Comment by escopecz** [comment]
I removed subscribers from all config.php files and did not find any problem.

Please create also the Extension class similar to https://github.com/mautic/mautic/blob/5.x/app/bundles/ChannelBundle/DependencyInjection/MauticChannelExtension.php

**Comment by kuzmany** [comment]
@escopecz ridiculous . If I remove subscribers from config then subscribers not work, If I add it, then it return on new email

image


I cannot move. I did everything like you did in others parts of system

**Comment by kuzmany** [comment]
@escopecz thanks, after add GrapesJsBuilderExtension class it works without subscribers in config https://github.com/mautic/mautic/blob/b80d89ba32b8e9a518a14aed1a244c0c6d0a8ba9/plugins/GrapesJsBuilderBundle/DependencyInjection/GrapesJsBuilderExtension.php

**Review by escopecz — APPROVED** [review]
Thank for fixing this Zdeno!

**Comment by mabumusa1** [comment]
This PR has three approvals, it is good to go

**Pull request merged**
