### PR TITLE
Fix gated video showing play button above form (Issue #9431)

### LINKED ISSUE #9431: Gated video showing play button above form
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I created an mp4 gated video following the instructions [here](https://docs.mautic.org/en/gated-video).  Everything worked well except after the form shows up and pauses the video, the play button for the video is on top of the form so the user can just press play and not fill out the form.

| Q   | A
| --- | ---
| Mautic version | 3.1.2
| PHP version | 7.2.24
| Browser | Chrome 86

### Steps to reproduce
1. Follow [these instructions](https://docs.mautic.org/en/gated-video) to include a gated video either on landing page or on any site that has mautic enabled.
2. Play the video until the form shows up and you'll see the play button clickable above the form.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by gabepri**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.2
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #9431

#### Description:
Gated video was not working correctly because the z-index of the play button was lower than that of the form.  [This PR](https://github.com/mautic/mautic/pull/6750) addressed the issue but it didn't make the changes to the minified css file.  I'm updating the minified css file here.

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by escopecz** [comment]
@dongilbert do you remember how this minified CSS file is generated? I can see that also the original version exists: 

https://github.com/mautic/mautic/blob/staging/media/css/mediaelementplayer.css

**Comment by dennisameling** [comment]
@escopecz was this closed automatically because you removed the `3.2.1` branch or did you close it manually?

**Comment by escopecz** [comment]
Oops, I did not meant to close this. It was caused automatically by my confusion with branches. Apologies. 

@gabepri could you please open the PR again? I cannot re-open for some reason.

**Comment by dennisameling** [comment]
We can't reopen since the `3.2.1` branch has been deleted; we also can't change the target branch anymore 😅 @gabepri would you mind creating a new PR for this? Sorry for the inconvenience!

**Pull request closed without merging**
