### PR TITLE
Improved Searching by email - assumes email is lower. For large lead …

### PR DESCRIPTION
**Pull request by maltonite**
…databases, the migration is likely to take a long time to run to set all emails to lower(email)

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Implements  #5917 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description: Sets all emails to lower. When searching by email, doesn't use lower(email) anymore. Significant performance increase with large DB.

- With the full scan, the DB is having to read each record, run lower(email), then compare. Relatively intensive, especially with 100k + records.
- The index doesn't require any processing by the DB, so naturally faster.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1.  Have large lead DB (1million + rows)
2.  Search by email. Can take significant time to find.

#### Steps to test this PR:
1.  Create db with test data of 1 million leads
2.  Search via email in contacts. 
3. Log/monitor queries. Use a programme such as PHPMyAdmin under performance monitor. Before the fix,  should see the query taking seconds to run. After the fix, should be faster (and may not see in query monitor). Ideally, turn on long query logging with a run time of 1 second or longer to view.

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1.
2.

### CODE REVIEW

**Comment by npracht** [comment]
Label: Enhancement

**Comment by Maxell92** [comment]
Hello @maltonite,

Do you have any performance test how big impact this PR has?

I think more work is needed here if we want to merge - we need to find every place in Mautic that can insert / update a email and put `lower` function there. Otherwise we run a migration and search will not work for new leads with uppercased email.

**Comment by maltonite** [comment]
Hi @Maxell92 

At the moment I haven't written a test class to demonstrate performance. I have seen queries though go from multiple seconds to give or take instantly due to using the index over a full table scan.

I am more familiar with the Laravel framework, where it is possible to always manipulate a value on the model before inserting into the DB. Is this possible within Symphony? If so, having a catch-all on the model might be the best option for setting strlower(email). Shouldn't all DB hits for leads go through LeadRepository?

**Comment by Maxell92** [comment]
Hello @maltonite,

1) So maybe you can paste here an explain and write it to the steps for testing to check difference between full scan and using index.
2) There are several way how to do it. You can hook some code to `prepersist` and these kind of methods, but the simplest one is to do it in the setter of entity.

But we have different issue here. We have discussed this possibility earlier and the problem is that user often want to display email as it was entered. Uppercase sometimes improve readability.

@alanhartless can you take a look on this PR please? What is your opinion?

**Comment by maltonite** [comment]
Hi @Maxell92 

1.
- With the full scan, the DB is having to read each record, run lower(email), then compare. Relatively intensive, especially with 100k + records. 
- The index doesn't require any processing by the DB, so naturally faster. 

2. Further reading the mysql docs, maybe setting the default character collection to latin1 on the column (and updating existing via a migration). https://dev.mysql.com/doc/refman/5.6/en/case-sensitivity.html. This means just removeing the criteria for searching, but not for selecting/inserting.  The default for MySQL DBs is either latin1 or latin1_swedish_ci. There is a potential risk of data loss with changing collection though.

**Comment by Maxell92** [comment]
1) I know this difference, I just wanted you to put it in the description so if anyone is going to test PR, he knows how to do it / what to look for :)
2) Could be an option. Lets wait for other Mautic dev and their opinion here.

**Comment by maltonite** [comment]
@Maxell92 

1. Updated :)
2. Sounds like a plan.

**Comment by npracht** [comment]
Hi @maltonite could you please resolve conflicts issue to tag it as candidate for 2.15.1 ? Thanks !

**Comment by maltonite** [comment]
This I believe is a duplicate of #6603 , so no need to merge.

**Pull request closed without merging**
