### PR TITLE
decode special characters in report display and export and form export and contact export

### PR DESCRIPTION
**Pull request by SamWebmecanik**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | X
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Required: )
#### Description:
In report , contact and form export the special characters are not decoding because when a value is send in database, this value is encode and when this value is use in a page, it is decode but not in report and form export.

[//]: # ( As applicable: )
#### Steps to reproduce the bug in report:
1. Create a lead with a special character ( ex: &)
2. Use this lead in report
3. See the character encode in the report

#### Steps to test this PR:
1. Apply this PR
2. Create a lead with a special character ( ex: &)
3. Use this lead in report
4. See the character decode in the report

[//]: # ( As applicable: )
#### Steps to reproduce the bug in form export:
1. Change lead in form report with a special character ( ex: &)
2. Export the result of the form in CSV or Excel
3. See the character encode in the export

#### Steps to test this PR:
1. Apply this PR
2. Export again the result of the form in CSV or Excel
3. See the character decode in the export

[//]: # ( As applicable: )
#### Steps to reproduce the bug in contact export:
1. Change lead in form report with a special character ( ex: &)
2. Export this contact
3. See the character encode in the export

#### Steps to test this PR:
1. Apply this PR
2. Export this contact (create before with a special character)
3. See the character decode in the export

### CODE REVIEW

**Comment by escopecz** [comment]
Is there a reason why the report exports aren't decoded as well? I can see it fixed in the report table, but if I export it, the encoding issue is there again.

**Comment by SamWebmecanik** [comment]
The last commit fix the decode bug in report export

**Comment by escopecz** [comment]
It fixed the CSV export, but the issue still exists for Excel export.

**Comment by SamWebmecanik** [comment]
Hi @escopecz,
I try to reproduce the bug with this PR with form result excel export and with report excel export but I didn't succeed. If you know with what character do you use for test ?

**Comment by escopecz** [comment]
I followed the steps to reproduce, so `&`. The order of the report is opposite of the excel, so if you modify the first row, look at the last row in the Excel doc. It's a bug, but unrelated to this PR.

**Comment by SamWebmecanik** [comment]
Thank you @escopecz, I fix it !

**Comment by SamWebmecanik** [comment]
We find an other bug same this one when we export contact, I will fix it in this PR.

**Comment by SamWebmecanik** [comment]
It's OK for decoding contact export 😄

**Comment by dongilbert** [comment]
+1 Works as expected. Unit tests still pass. Thanks @SamWebmecanik!

**Pull request merged**
