### PR TITLE
Remove duplicate index

### PR DESCRIPTION
**Pull request by tejasync**
| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | N
| Related user documentation PR URL | N
| Related developer documentation PR URL | N
| Issues addressed (#s or URLs) | N
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This task is to remove duplicate index (email) in email_assets_xref.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. View indexes from email_assets_xref table

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Execute migration
3. View indexes from email_assets_xref table

### CODE REVIEW

**Comment by RCheesley** [comment]
@mautic/acquia-po we will need someone to rebase this one as it is on an Acquia fork rather than a personal fork. Maybe @lijupm you could take a look?

**Review by kuzmany — CHANGES_REQUESTED** [review]
I don't understand this PR, what cause this issue?
I've tested migration, it remove index from email_assets_xref, 

But as as I read the code, migration should cover also email_list_xref, shouldn't it?

**Comment by fedys** [comment]
@kuzmany you are right. The migration for `email_list_xref` is missing. I will cherry pick the missing migration. Thanks!

**Comment by kuzmany** [comment]
@fedys can you get me more context of issue If we have index on email column in email_assets_xref ?

**Comment by fedys** [comment]
@kuzmany The index consisting of single `email_id` column (the last row in the screenshot) is completely redundant as DB can utilize primary key.
Snímek obrazovky 2021-03-05 v 10 23 12

**Comment by kuzmany** [comment]
@fedys the we should remove index also for asset_id - that column is also primary

Shouldn't it? Just asking :)

**Comment by fedys** [comment]
@kuzmany It is not possible to remove the index for `asset_id`. DB is able to utilize only the first column in the compound index (primary key here) when searching/sorting by a single column.

In this scenario if you tried removing that index, DB wouldn't allow that as every foreign key needs an index.

**Comment by kuzmany** [comment]
@fedys thank you for make it clear for me. I appreciate it

**Review by kuzmany — APPROVED** [review]
Works for me 👍

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by npracht** [comment]
There is a schema migration. @RCheesley can we tag it to patch release anyway or do we need to wait next minor ?

**Comment by RCheesley** [comment]
As a bug fix we can go with the next patch release but let's just double check that the migration is sound before we merge.

**Review by mohit-rocks — APPROVED** [review]

**Pull request merged**
