### PR TITLE
Issue-6874: RabbitMQ Click Counts Not Working

### PR DESCRIPTION
**Pull request by rasikaphanse**
Issue Link - https://github.com/mautic/mautic/issues/6874

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@rasikaphanse this PR is against the 2.16 branch. We are no longer accepting any PR's for Mautic 2 as it it out of support.

I can change the base but you will need to rebase the PR. Shout if you need help with that!

**Comment by jordan8037310** [comment]
@RCheesley we wanted to submit a patch for https://github.com/mautic/mautic/issues/6874 since it was closed without anyone submitting an official patch for 2.x and we were encountering issues in `mautic-k8s` which are now solved. 

We will submit another patch to M3 once we have an M3 instance running, but for now this should help anyone else who encounters RabbitMQ problems

**Comment by RCheesley** [comment]
OK well this PR will be closed if it is for 2.x as it is not supported - thanks though, hopefully it will help folk if they are stuck and not willing to update to 3.

**Pull request closed without merging**
