### PR TITLE
Fix campaign loop for jump action for decision

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

If decision has no parent then Jump to action event can make loop in campaing. 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Make this campaign 

image

3. Run campaign
4. Wait one minute to execute false path of decision
5. Then run again and again and see every time is decision execute to false  and make campaign false

image

### CODE REVIEW

**Comment by kuzmany** [comment]
I am gonna switch it to WIP, this PR cover just one case of usage Jump to event. Probably there are more issue

**Comment by kuzmany** [comment]
It's ready to test

**Review by volha-pivavarchyk — DISMISSED** [review]
Works well

image

**Review by RCheesley — DISMISSED** [review]
Reproduced the issue on 5.x - repeated loop:

screenshot-8080-mautic-mautic-vqn4hnxn8ob ws-eu71 gitpod io-2022 10 14-15_01_32

With the PR applied it only loops once as expected:



Thanks for the PR @kuzmany 🚀 good to go with a code review.

**Review by escopecz — CHANGES_REQUESTED** [review]
I must admit I don't feel comfortable merging PRs that modify features like campaigns without tests. We are always testing only happy paths and it's almost impossible to retest all campaign scenarios so we must cover them with functional tests otherwise we always be in the state where we fix one use case and break another.

**Review by escopecz — APPROVED** [review]
I added the functional test for this bug

**Pull request merged**
