### PR TITLE
Merge 4.0 into 4.x branch

### PR DESCRIPTION
**Pull request by npracht**
Merge 4.0 into 4.x branch

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10619"></a>

### CODE REVIEW

**Review by RCheesley — APPROVED** [review]

**Review by dennisameling — CHANGES_REQUESTED** [review]
Had a _very_ quick look but this PR will have quite some unintended side effects:
- PHPSTAN baseline (which was introduced in a 4.x PR) will be removed by this PR
- Some contributors will be removed in .all-contributorsrc
- An old subtree split config will be added again (`.github/subtree-splitter-config.json`) which we don't want
- The Gitpod configuration will be **removed** which we also don't want
- Etc.

I don't know on the top of my head what a good fix for this will be, don't have time to check that now sorry

**Comment by npracht** [comment]
Okay so this is crap. How do we usually do to merge 4.0 in 4.x ? Do we need to cherrypick commit by commit ?

**Comment by RCheesley** [comment]
I think that @escopecz did it last time?

**Review by RCheesley — CHANGES_REQUESTED** [review]
Spotted some issues with the PR so setting this to request changes

**Pull request closed without merging**
