### PR TITLE
Add search by company fields for list view/API

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | https://github.com/mautic/developer-documentation/pull/145
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR bring search by fields for companies (UX/API), same like contacts do.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Go to companies,  create companies with some data - name, city etc
3. Try search from field: city:"Your City" etc
4. You should see suggestion for that fields in the search field too
5. Same search feature you can use in API

```
$companyApi       = $api->newApi('companies', $auth, $apiUrl);
$response = $companyApi->getList('companyaddress1:test');
die(print_r($response));
```

### CODE REVIEW

**Comment by nickveenhof** [comment]
Tested this and it works as a charm. What I did is to apply the patch to my branch. Unfortunately the composer doesn't mention the mautic core itself as a dependency causing composer patches to not work in this way. It also makes this hard to use this patch in production while keeping a tab on this PR to know when it needs to be updated or even removed from my patches. I would advice to look at Drupal to see how they handle this. 

Unrelated, the change is exactly what I needed. When executing the following url without the patch (http://mautic.localhost/api/companies?search=crmid:791945) I had no result, after applying the patch I have the correct results. 

I also tested the UI and there I found something unexpected. I expected the questionmark next to the search to also show the available custom fields. See screenshot

image

**Comment by nickveenhof** [comment]
To be fair, contacts has the same problem in the questionmark help popup. Maybe that needs to be a separate issue?

**Comment by kuzmany** [comment]
> To be fair, contacts has the same problem in the questionmark help popup. Maybe that needs to be a separate issue?

Yes, let's move to another task.

I did test search by param and works for me.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebased

**Comment by RCheesley** [comment]
Bumping to 3.2 as we don't have sufficient tests to merge.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@kuzmany some conflicts on this one - if we can get that resolved and tests passing, seeing as we have the +1 from @nickveenhof (are you using in production?) and assuming that it is in production at Webmecanik, we can mark it RTC.

**Comment by kuzmany** [comment]
Unit tests added

**Pull request merged**
