### PR TITLE
Fix: #13554 downloading Maxmind database

### PR DESCRIPTION
**Pull request by obamwonyi**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the 5.x branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes ##13554

#### Description:

The fix was implemented as shown below 
```php 
  if (empty($package))
  {
	  $this->logger->error('Failed to fetch remote IP data: Invalid or inactive MaxMind license key');
	  return false;
  }
  try {
      $data = $this->client->get($package, [
          RequestOptions::ALLOW_REDIRECTS => true,
      ]);
  } catch (\Exception $exception) {
      $this->logger->error('Failed to fetch remote IP data: '.$exception->getMessage());
  }
``` 
The if statement would help make sure that the $package was downloaded before proceeding to the try catch statement if the download is empty then the appropriate error would be passed to the logger

#### Steps to test this PR:
Step 1: Configure Maxmind per settings here: https://docs.mautic.org/en/5.x/configuration/maxmind_license.html with a brand new key
Step 2: Click the button to pull the database immediately (within 5 mins of making the key)
Step 3: Try to run the CLI command bin/console mautic:iplookup:download

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
This code change should fix the issue. I'd prefer to throw an exception so the reason for the failure would be directly visible, but that would require more refactoring to catch the exception in multiple places. This is good compromise 👍

**Comment by escopecz** [comment]
@obamwonyi please check the CS Fixer issue in Github Actions

**Comment by obamwonyi** [comment]
Ok

**Comment by obamwonyi** [comment]
I have fixed the php-cs-fixer issue, by simply running  ```bash ddev exec php-cs-fixer fix.```, the test should pass now.

**Review by RCheesley — APPROVED** [review]
This did resolve the issue - now in the command line I get:

```
rcheesley@Drop mautic % ddev exec bin/console mautic:iplookup:download
17:15:40 ERROR     [mautic] Failed to fetch remote IP data: Client error: `GET https://download.maxmind.com/app/geoip_download?license_key=redacted&edition_id=GeoLite2-City&suffix=tar.gz` resulted in a `401 Unauthorized` response:
Invalid license key
```

This is a lot better than just throwing a random error.

I also then see the following:

```
 ["hostname" => "mautic-web","pid" => 6362]
ErrorException: Warning: Undefined variable $data in /var/www/html/app/bundles/CoreBundle/IpLookup/AbstractLocalDataLookup.php:99
Stack trace:
#0 /var/www/html/app/bundles/CoreBundle/Command/UpdateIpDataStoreCommand.php(39): Mautic\CoreBundle\IpLookup\AbstractLocalDataLookup->downloadRemoteDataStore()
#1 /var/www/html/vendor/symfony/console/Command/Command.php(298): Mautic\CoreBundle\Command\UpdateIpDataStoreCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Mautic\CoreBundle\Command\UpdateIpDataStoreCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Mautic\CoreBundle\Command\UpdateIpDataStoreCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/bin/console(16): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 {main}
Automatically fetching the IP lookup data failed. Download https://download.maxmind.com/app/geoip_download?license_key=redacted&edition_id=GeoLite2-City&suffix=tar.gz, extract if necessary, and upload to /var/www/html/var/cache/dev/../ip_data/GeoLite2-City.mmdb.
```

Not sure if that last error message is of any relevance!

**Review by escopecz — APPROVED** [review]
The code makes sense considering the `getRemoteDateStoreDownloadUrl()` method returns null if the key is empty 👍

**Pull request merged**
