### PR TITLE
Fix form issues with file type field

### LINKED ISSUE #9946: Link to form uploaded file not working
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Email with form results doesn't contain correct link to file.
It looks example as:
file: /forms/results/file/9/file  

This bug is new. I hadn't this problem on 2.16.3

| Q   | A
| --- | ---
| Mautic version | 3.3.2
| PHP version | 7.4
| Browser | Edge

### Steps to reproduce
1. Create new file field in form and publish
2. Set up notification
3. Upload file by a form
4. Link in notification contains only middle part of link
 
### Log errors
No logs

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by kuzmany**
Fixes: #9946

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.3
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
I've noticed two issue in forms. This PR fixed it.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create form with **file**, **email** and **file** and **Send form results** action
3. Disable  Save result? option for **file** and enable Public accessible link to download
4. Now send form
5. Without fix, you receive email with relative path to file. After apply the fix receive URL to download file
6. Then try clone form, and submit cloned form . Without fix you should see error in logs :

> Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'INSERT INTO

7. After fix and cloned form, you are able to submit cloned form without issue

### CODE REVIEW

**Comment by npracht** [comment]
@kuzmany can you check travis please ?

**Comment by adiux** [comment]
I just tested and I can confirm there is no Error message in the log. I was able to clone the form.

However, I can not access the file via link
image

The email
Screenshot 2020-10-10 at 12 57 26

the file is saved here
image

Maybe this is a separate issue?

**Review by RCheesley — COMMENTED** [review]
I was able to see the bug about the file path before the PR is applied:

screenshot-127 0 0 1_8025-2020 10 10-19_53_30

And I also see the name being saved to the database when the setting says it should not be:

screenshot-127 0 0 1_8025-2020 10 10-19_53_30 (1)

I was *not* able to reproduce the error on cloning the form and submitting, before or after applying the PR.

After applying the PR I get the full file path as expected:

screenshot-127 0 0 1_8025-2020 10 10-19_53_30 (2)

However the name is still being saved to the database:
screenshot-local mautic3-2020 10 10-19_54_24

Here is the field setting to confirm:

screenshot-local mautic3-2020 10 10-19_55_10

So,

1. File path is fixed ✅ 
2. Error on cloning the form cannot be reproduced ❓ 
3. First name field is still being saved to the database when it should not be ❌ 

Yes, I have applied the PR correctly (using GH CLI). Yes, I have cleared the cache. I tested with the standalone form.

I was able to access the file via the link in the email no probs.

**Comment by npracht** [comment]
@kuzmany can you please review Ruth feedbacks ?

**Comment by RCheesley** [comment]
As this is still pending feedback and has been bounced from several releases, if it is not ready to be merged in the 3.3.1 release we will close the PR.

**Comment by kuzmany** [comment]
@RCheesley I made little changes and rebase to 3.3

THis issue is just with file type in form.
If you disable save results on file type field, then clone form, your submit without PR return error

Can you please re-test it?

**Review by escopecz — APPROVED** [review]
I was able to reproduce both issues and this PR fixes them both. 👍 

I'm wondering what is the file URL for though. It gives me 404 when I try to access it. It has format of `https://xxx/forms/results/file/5/file`. Anyone knows?

**Comment by kuzmany** [comment]
@escopecz I suppose to need enable Public accessible link to download


image

**Comment by RCheesley** [comment]
@kuzmany I have followed all the steps but I am also getting a 404 error when trying to access the full link to the file once the PR is applied.

The file URL provided is https://example.com/forms/results/file/103/attach_file - the same as @escopecz above. The asset location is in media/files/form/4/14/mautic-2.png (where 4 is the form ID) in case that is any help? I can confirm that I have set the file to be publicly accessible per the instructions and it was an image file which is in the accept list.

So as we are both having a problem with accessing the file URL let's bump this to 4.0-beta to give more time to look into what the issue might be.

Surprised this is not covered in a test - is it possible to check that the file is accessible and not returning an error code?

**Review by escopecz — CHANGES_REQUESTED** [review]
Retested, the file is not downloadable (404)

**Comment by kuzmany** [comment]
I just make tests and works as I describe.

**Comment by tejasync** [comment]
Tested and works fine. Code LGTM! Thank you @kuzmany

**Review by mohit-rocks — APPROVED** [review]
Looks good to me.
I've tested this one and attaching the screenshot for the file URL
MailHog

Besides, I also tested by doing clone of the form and I am able to submit the clonned form.

**Comment by RCheesley** [comment]
@all-contributors please add @adiux for userTesting

**Pull request merged**
