### PR TITLE
"Including" or "Excluding" operator on campaign conditions for field value only allows 1 value selection, it should allow multiple values.

### PR DESCRIPTION
**Pull request by shinde-rahul**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix?                                      |  yes 
| New feature/enhancement?     |  no
| Deprecations?                           |  no
| BC breaks?                                | no
| Automated tests included?              | yes 
| Related user documentation PR URL      | NA 
| Related developer documentation PR URL | NA
| Issue(s) addressed                     | NA

#### Description:
"Including" or "Excluding" operator on campaign conditions for field value only allows 1 value selection, it should allow multiple values.

Additional Info:
The Mautic saves the multi-values to db with `|` separator. e.g. if a multi-select field has the following key-value pair 
```
key1 => Value 1
key2 => Value 2
key3 => Value 3
key4 => Value 4
```
when saving contact choosing `Value 2` and `Value 4` as options; saves the `key2|key4` in the database for that field/column. So while comparing we need to compare 'OR'ing these values.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
1. Create a custom field with the following details,
1.1 Alias: choices
1.1 Object: Contact
1.1 Data Type: Select
1.1 Options: Add some options
1. Add a condition to a campaign for a Contact Field Value
1.1 Select the newly created fields
1.1 Choose either include/exclude operator
1.1 select the multiple values
1. Save the campaign
1. Trigger the campaign (optional)

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10490"></a>

### CODE REVIEW

**Comment by shinde-rahul** [comment]
This PR depends on https://github.com/mautic/mautic/pull/8649.

**Comment by patrykgruszka** [comment]
I think this PR duplicates #9658.

**Comment by escopecz** [comment]
There is similar fix: https://github.com/mautic/mautic/pull/9658

We have to decide which one is better...

**Comment by shinde-rahul** [comment]
> There is similar fix: #9658
> 
> We have to decide which one is better...

Thanks for this heads up.

**Review by patrykgruszka — COMMENTED** [review]
Code looks good and works correctly for standard case. Only issue I've found is usage of special characters in select options like `|` which may cause unexpected behaviour because the database query uses REGEX operator.

**Comment by escopecz** [comment]
@patrykgruszka does it mean you prefer this PR over https://github.com/mautic/mautic/pull/9658? If so, can we close that one?

**Comment by patrykgruszka** [comment]
@escopecz I prefer #9658, because it uses `IN` and `NOT IN` operator instead of `REGEX` in database query.

**Comment by escopecz** [comment]
Ok. I discussed with our team including @shinde-rahul and as a result I'm closing this PR in favor of https://github.com/mautic/mautic/pull/9658

**Pull request closed without merging**
