### PR TITLE
removed batch parameter from addLeadToCompany so that it doesn't deta…

### PR DESCRIPTION
**Pull request by mqueme**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #2664 #2666
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
When submitting a form with a company field, resulted in  an error. this PR should fix that

#### Steps to test this PR:
1. create a form with a company matched field
2. submit, company should be created, lead should be created, submission saved

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. create a form with a company matched field
2. submit, you will see a 500 error

### CODE REVIEW

**Comment by amagdy3** [comment]
I've applied this to 2 mautic installations. Forms are being submitted with data. 

P.S. Submission is still quite slow but I guess it doesn't have to do with this.

**Comment by escopecz** [comment]
:+1:

**Comment by amagdy3** [comment]
FYI, @mqueme  after applying the PR I received a 500 error while adding an "Add to company" campaign action - probably something needs to be updated there as well.

capturecompanyaction

**Comment by alanhartless** [comment]
@amagdy3 Check your logs for an error.

**Comment by mqueme** [comment]
This was fixed in another PR @amagdy3 #2704

**Pull request merged**
