### PR TITLE
Update plugin schema on plugin install

### PR DESCRIPTION
**Pull request by arulrajsm28**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/2938

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
When installing custom plugin which have entity does not create table as expected. This PR will resolve this issue. 

#### Steps to test this PR:
1. Try to install plugins with entity schema from plugins menu
2. Check the tables are created 

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Try to install plugins with entity schema from plugins menu
2. Check the tables are created or not

### CODE REVIEW

**Comment by escopecz** [comment]
Can you provide a plugin we could test it with?

**Comment by escopecz** [comment]
Since there is no time to develop a testing plugin to test his and the requested testing plugin was not provided, I'm pushing this out of 2.8.0

**Comment by kermorgant** [comment]
Hi,
I've made a plugin to reproduce the issue here https://github.com/kermorgant/MauticSchemaCreationTestBundle

Hope it can help

**Comment by bobabram** [comment]
Had the same issue, checked out stable, applied PR, no issues, problem resolved.

vote +1

**Comment by virlatinus** [comment]
I installed the provided plugin and applied the PR, but the table was not created.

**Comment by virlatinus** [comment]
I deleted the entry in the plugins table, and started from the beginning and now it worked! +1

**Pull request merged**
