### PR TITLE
Making the deduplicate command fast

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [n]
| New feature/enhancement? (use the a.x branch)      | [enhancement]
| Deprecations?                          | [y]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [y] 
| Issue(s) addressed                     | /

#### Description:

The deduplicate command used to iterate through all contacts and checking if a duplicate exists for it. This was very inefficient and can take weeks to run it on several million contacts.

This PR optimizes the command so that:
- it finds which fields are unique identifiers
- use those identifiers to search for contacts that have some duplicates
- follows the previous logic of deduplicating those duplicates
- splits the `ContactDeduper` to multiple methods so it can be used elsewhere, not only in a command
- adds new `--batch` and `--processes` params to support parallel execution.
- adds new `mautic:contacts:deduplicate:ids` command that is used internally to run the parallel processes for specific contact IDs.

Example usage:
```
bin/console mautic:contacts:deduplicate --batch=100 --processes=10
```
This will split the deduplication into multiple processes. Each process will process maximally 100 concrete duplicated contacts. And there will be maximally 10 concurrent processes running at the same time.

The command will show a progress bar of how many processes are finished and when all of them are finished then it will display outputs for all of them.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create multiple contacts with duplicated email address. The contact you can generate the better as this is mainly speed optimization. We still assume that there are few duplicates within many unique contacts.
3. Run `bin/console mautic:contacts:deduplicate`. Feel free to play with the command parameters.
4. Check that the command output makes sense
5. Check that the duplicates were merged together the way you expect.

Here is a handy SQL query that will create 12 duplicated contacts:
```sql
INSERT INTO `mautic_leads` (`email`, is_published, points, date_identified) VALUES
('asfd1@sdf.dd', 1, 0, NOW()),
('asfd1@sdf.dd', 1, 0, NOW()),
('asfd2@sdf.dd', 1, 0, NOW()),
('asfd2@sdf.dd', 1, 0, NOW()),
('asfd3@sdf.dd', 1, 0, NOW()),
('asfd3@sdf.dd', 1, 0, NOW()),
('asfd4@sdf.dd', 1, 0, NOW()),
('asfd4@sdf.dd', 1, 0, NOW()),
('asfd5@sdf.dd', 1, 0, NOW()),
('asfd5@sdf.dd', 1, 0, NOW()),
('asfd6@sdf.dd', 1, 0, NOW()),
('asfd6@sdf.dd', 1, 0, NOW()),
('asfd7@sdf.dd', 1, 0, NOW()),
('asfd7@sdf.dd', 1, 0, NOW()),
('asfd8@sdf.dd', 1, 0, NOW()),
('asfd8@sdf.dd', 1, 0, NOW()),
('asfd9@sdf.dd', 1, 0, NOW()),
('asfd9@sdf.dd', 1, 0, NOW()),
('asfd10@sdf.dd', 1, 0, NOW()),
('asfd10@sdf.dd', 1, 0, NOW()),
('asfd11@sdf.dd', 1, 0, NOW()),
('asfd11@sdf.dd', 1, 0, NOW()),
('asfd12@sdf.dd', 1, 0, NOW()),
('asfd12@sdf.dd', 1, 0, NOW());
```

#### Other areas of Mautic that may be affected by the change:
1. Just the deduplicate command
2. The dedup command was removed as I think it was created by accident in a merge or something. It's funny that the deduplicate command had a duplicate. The community has only the deduplicate command.

#### List deprecations along with the new alternative:
1. `ContactDeduper::deduplicate()` Use the other methods in this service to compose what you need. See DeduplicateCommand for an example.

[//]: # ( As applicable: )
#### List of areas covered by the unit and/or functional tests:
1. The command tests that it will remove all the duplicated commands.

### CODE REVIEW

**Review by kuzmany — DISMISSED** [review]
Looks pretty good. Nice usage of processes
I've made also basic tests, works for me. 👍

**Comment by sdoering** [comment]
I created around 1220 duplicate contacts in the leads table and ran the deduplicate command: 

```
gitpod /workspace/mautic $ ddev exec bin/console mautic:contacts:deduplicate
Deduplicating contacts based on unique identifiers: Email
12 contacts found to deduplicate

Finding duplicates and creating processes for deduplication. 1 processes will be queued.

Starting to execute the 1 processes for deduplication. 1 processes will be executed in parallel.
 1/1 [============================] 100% 15 secs/15 secs 20.0 MiB

All processes have finished. The output of each process is below.
'/var/www/html/bin/console' 'mautic:contacts:deduplicate:ids' '--contact-ids' '1,3,5,7,9,11,13,15,17,19,21,23' '-e' 'prod'
12 contacts passed to deduplicate
Duration: 15201 ms, Memory: 31457280 bytes


Duration: 15707 ms, Memory: 20971520 bytes
```

The result were 12 contacts in the lead table filled with NULL-values:
image

**Comment by escopecz** [comment]
@sdoering can you please explicitly state if the test you did was successful or not? I can't say. Is 12 contacts the expected result?

Also, if you'd use the processes option it should be faster. Something like:
```
bin/console mautic:contacts:deduplicate --batch=50 --processes=5
```
The amount of processes and contacts per batch should be related to the contacts you have and what the server can handle so there is no recommended number of processes and the default is 1.

**Comment by mabumusa1** [comment]
@escopecz please resolve the conflict, so I can test

**Comment by escopecz** [comment]
@mabumusa1 the conflict is resolved.

**Review by mabumusa1 — APPROVED** [review]
One of the best changes, I've seen to get better performance. I tested it locally with 100 duplicate contacts, it worked as expected.

thanks @escopecz , this PR is good to go

**Pull request merged**
