### PR TITLE
[UI] Interface themes

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

Here new interface themes.

image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Account 
3. Click Appearance
4. Play with the options

### CODE REVIEW

**Comment by shinde-rahul** [comment]
@andersonjeccel, is the dark theme only available on the account details page? When I toggle, the only page that gets the dark theme is the accounts page, not any other pages.

**Comment by andersonjeccel** [comment]
@shinde-rahul In this one, yeah

I’m working by component in each pull request, only using the tokens PR as a base to provide me the necessary variables 

So to see everything in the dark theme, we would have to wait for the others to be merged first (or merge all the pending branches in this one, but it might be difficult to review the code later)

**Review by LordRembo — CHANGES_REQUESTED** [review]
@andersonjeccel Okay, so first off, same remark as I had on some other PR's: this one is dependent on changes you are trying to do in the Tokens PR. So you need to mark that as a dependency, eg. in the description. Similarly as the others, I'd ask to put this PR on draft or somehow make clear to users that part of the code is to be reviewed in that main Tokens PR.

**Comment by LordRembo** [comment]
@andersonjeccel  As for the code, I would suggest that the dark theme is actually loaded via both PHP and JS. Assuming you want to keep this working by setting a property on the html-tag of the site (or any other wrapper).

- For PHP: using the toggle would store a setting in Mautic, which can be read in the template of the html and print the theme color setting right there. That guarantees that any page refresh still loads the right theme and it's gonna be 'instant' as happens during rendering instead of after the DOM is ready. You could ask @mallezie what a course of action or example would be.
- For JS: the toggle would simultaneously still change the property in the HTML when clicked, so the theme is switched. Just won't write anything to localStorage.

**Comment by LordRembo** [comment]
3rd remark: 
The JS code is having some problems that it does not always work when the button is loaded. You should build on top of `Mautic.userOnLoad` instead of make a new `DOMContentLoaded` + use some kind of 'live' check to keep a look on the DOM.
Here's a suggestion on how to rewrite the listener using `mQuery` (whatever version of jQuery or mini-jQuery is in use in Mautic). Untested but it should show the concept.

```
Mautic.userOnLoad = function (container) {
  <code that already exists>
  
  // I'm rewriting using mQuery instead of using documentSelector because I can use 'on', which keeps the element alive when the DOM changes, so it will work even if the code loads before the button is rendered
  mQuery('.dark-toggle').on('click', function() {
    let buttonToggle = mQuery(this);
    let themeCurrent = document.documentElement.getAttribute('color-theme');
    let themeNew = themeCurrent === 'dark' ? 'light' : 'dark';
    document.documentElement.setAttribute('color-theme', themeNew);    
  });  
}
```

**Comment by andersonjeccel** [comment]
@LordRembo  Your solution solved the first issue, but now I’m having a problem to keep these attributes when leaving the account page
It seems like there’s another js code rewriting the entire html tag
But we also have another js code rewriting the body when the GrapeJS builder is opened

What would you suggest to keep only JS (no PHP)?

**Comment by LordRembo** [comment]
@andersonjeccel I'm not seeing any issues in the current version of your PR, so can you share some things to help me debug?
- the code you tried out, that makes changes to the html tag 
- what changes happen to the html tag when leaving the account page?
- what changes do you see when GrapesJS is opened?

**Comment by LordRembo** [comment]
@andersonjeccel I just tried copy pasting my bit of code and commenting out your JS changes. Just hade 1 typo I had to fix (use `mQuery` instead of `$`) but otherwise, I'm not finding any problems with the html tag on other pages.

This is what the userOnload looks like then:
```
 Mautic.userOnLoad = function (container) {
    if (mQuery(container + ' form[name="user"]').length) {
        if (mQuery('#user_position').length) {
            Mautic.activateTypeahead('#user_position', {displayKey: 'position'});
        }
    } else {
        if (mQuery(container + ' #list-search').length) {
            Mautic.activateSearchAutocomplete('list-search', 'user.user');
        }
    }

    mQuery('.dark-toggle').on('click', function() {
        let buttonToggle = mQuery(this);
        let themeCurrent = document.documentElement.getAttribute('color-theme');
        let themeNew = themeCurrent === 'dark' ? 'light' : 'dark';
        document.documentElement.setAttribute('color-theme', themeNew);    
    }); 
};
```

**Comment by LordRembo** [comment]
@andersonjeccel If there is indeed some logic that completely replace the html tag, you can still integrated the logic to set & read the theme from localStorage using JS (in addition to using PHP).
You would just need to find out what JS file is doing this and WHEN this change is triggered so you can find a way to execute your changes AFTER it or in a callback. 
But as said, I'm not seeing that problem so I'm gonna need your input to help.

**Comment by andersonjeccel** [comment]
@LordRembo 

I tested specifically this code:

```
// Dark theme toggle
Mautic.userOnLoad = function (container) {
    let theme = localStorage.getItem('theme');
    if (theme) {
        document.documentElement.setAttribute('color-theme', theme);
    } else {
        document.documentElement.setAttribute('color-theme', 'light');
    }

    mQuery('.dark-toggle').on('click', function() {
        let themeCurrent = document.documentElement.getAttribute('color-theme');
        let themeNew = themeCurrent === 'dark' ? 'light' : 'dark';
        document.documentElement.setAttribute('color-theme', themeNew);
        localStorage.setItem('theme', themeNew);
    });
};
```

Steps:
1. Go to Account
2. Click the button to toggle

It appends the attribute

image

And things go dark

image

I reload the page. Everything keeps working just fine.

---

Then I click on Dashboard. The html tag still have the attribute.
I reload the Dashboard page. Now we don't have the dark attribute, it disappears.

It comes from this:

`<html class=" supports csstransforms3d touchevents responsejs " color-theme="dark">`

To this:

`<html class=" supports csstransforms3d touchevents responsejs ">`

---

Considered an alternative: apply the attribute in the body tag instead of html.
Then I tested if things are rewritten opening other pages and finally the builder.

Steps:

1. Go to Channels > Emails > New > Builder.

The body tag goes from:

`<body class="header-fixed">`

To:

`<body class="header-fixed" style="overflow-y: hidden;">`

So the same problem.

---

Tried the last code you suggested and added localStorage:

```
Mautic.userOnLoad = function (container) {
    if (mQuery(container + ' form[name="user"]').length) {
        if (mQuery('#user_position').length) {
            Mautic.activateTypeahead('#user_position', {displayKey: 'position'});
        }
    } else {
        if (mQuery(container + ' #list-search').length) {
            Mautic.activateSearchAutocomplete('list-search', 'user.user');
        }
    }

    let theme = localStorage.getItem('theme');
    if (theme) {
        document.documentElement.setAttribute('color-theme', theme);
    } else {
        document.documentElement.setAttribute('color-theme', 'light');
    }

    mQuery('.dark-toggle').on('click', function() {
        let themeCurrent = document.documentElement.getAttribute('color-theme');
        let themeNew = themeCurrent === 'dark' ? 'light' : 'dark';
        document.documentElement.setAttribute('color-theme', themeNew);
        localStorage.setItem('theme', themeNew);
    });
};
```

The dark mode still disappears when I reload another page, out of the user profile.

The debugger says it's coming from `node_modules/jquery/dist/jquery.js`
Line 8218

But it doesn't seem relevant...

**Comment by LordRembo** [comment]
The code looks good with the latest changes I think. There will hopefully be some feedback on that code when the PR is public. Also, since the toggle stuff is now more generic, it would be useful to document the use.

**Comment by andersonjeccel** [comment]
@abhisekmazumdar some tests here :)

**Review by MojisolaaaO — COMMENTED** [review]
@andersonjeccel Great work on the implementation! 
However, while testing, I encountered a couple of issues with the interface themes:

**Defects:**
1. **Text Overlap Issue:** The description text for the themes overlap with other UI elements. The text should wrap properly to ensure readability. 
**Suggested fix:** Adjust the CSS for the theme description to allow for proper text wrapping.
[Screenshot of the Bug](https://monosnap.com/file/QiUPV7xKNpEB7eEO9WSSrH3VO9ypkj)

2. **Cancel Button Not Working:** When the "Cancel" button is clicked, the selected theme is still applied rather than reverting to the previous state. 
**Suggested fix:** Ensure the cancel action reverts the theme selection to the original theme before changes were applied. 
[Video of the Bug](https://monosnap.com/file/OMEY1Qq3bJTCIUwGtANgLjCEqxgVfg)


**Environment Details**
**Environment**: Test
 **Browser:** Google Chrome 
 **Zoom Level:** 100%
 **Operating System:** MacOS 

Looking forward to your thoughts on these points! Let me know if you need further details or assistance in reproducing these issues.

**Comment by andersonjeccel** [comment]
@MojisolaaaO Great that you found a bug, I'm also using this branch to fix some of those and commited an improvement

re. 2, the buttons are a structural UX issue with Mautic because they don't allow us to hide where they're not used/associated to functionalities, so there will be no fix for now :P

**Review by imaabasiee — APPROVED** [review]
Interface Theme: I played around with the themes and noticed that when you select a theme and cancels it, it does not revert to the previous one. Here is a video: https://www.loom.com/share/d0b695fe6a3843cab7abe6e08ad6d3d8

**Review by imaabasiee — APPROVED** [review]
https://github.com/mautic/mautic/pull/13767 Interface Theme: I played around with the themes and noticed that when you select a theme and cancels it, it does not revert to the previous one. Here is a video:
https://www.loom.com/share/d0b695fe6a3843cab7abe6e08ad6d3d8

**Comment by andersonjeccel** [comment]
@imaabasiee @MojisolaaaO Found a workaround to attach the themes and accessibility settings to the Save button, now it'll work as you expected before

**Comment by MojisolaaaO** [comment]
@andersonjeccel Great! Would check it out

**Comment by MojisolaaaO** [comment]
@andersonjeccel 
The first issue about the text overlapping has been **fixed**.
However, the issue about the selected theme still being applied when the "Cancel" button is clicked **persists**.

**Comment by andersonjeccel** [comment]
@MojisolaaaO Hm, we have an issue here

This is the current behavior after my last commit:

1. You click on each option and it's applied to preview
2. If you save, they become permanent (they won't disappear by themselves)
3. If you cancel, it reverts back to what you were using before

But still there's 1 specific use case where you'll find a bug: when not clicking Save nor Cancel, just clicking something on the sidebar, for example

The preview would be "carried" to the other pages until you reload (because Mautic commonly loads a page without reloading it)

To cover this specific scenario:
1. we can remove the preview feature, so you'll have to save each time to see how a theme looks
2. we leave it this way

What do you think?
I'll also ask colleagues here

**Comment by MojisolaaaO** [comment]
@andersonjeccel Thank you for the clarification. I believe we should leave it this way as the user instantly seeing the preview before deciding whether to maintain it gives a better user experience.

**Comment by MojisolaaaO** [comment]
@andersonjeccel Thank you for the clarification. I believe we should leave it this way. Being able to see the preview of the selected theme before deciding whether to maintain it gives a better user experience.

**Review by shinde-rahul — APPROVED** [review]
Code changes look good to me. 
I have one question: will this enable me to add custom themes?

**Comment by escopecz** [comment]
I was clicking through the UI and notice these issues:
The value in the input is not readable on email and asset detail pages:
Screenshot 2024-10-09 at 09 39 14
Screenshot 2024-10-09 at 09 34 22

Where did the landing page builder button go? I can see that it's missing in the 5.x branch as well. So it's not a blocker for this PR. Anyone knows?
Screenshot 2024-10-09 at 09 33 30

**Comment by andersonjeccel** [comment]
@shinde-rahul I’ll need some guidance to make it possible

there’s a twig function that allows devs to extend some specific places by appending new content, maybe that’s an initial solution to make it selectable, + adding a custom CSS file to set the styles

the JS code itself is really flexible and will adapt automatically to whatever you add since you follow the same structure seen on the others (radio input with attributes)

**Review by imaabasiee — APPROVED** [review]
Interface Theme: I played around with the themes and noticed that when you select a theme and cancels it, it does not revert to the previous one. Here is a video: https://www.loom.com/share/d0b695fe6a3843cab7abe6e08ad6d3d8?sid=6ce6f2c7-d1ed-4b4a-94e6-ccef15edf17e

Mojisola opened the issue here https://github.com/mautic/mautic/issues/14171

**Comment by andersonjeccel** [comment]
@imaabasiee Weird thing is that the functionality is there and here it works

https://github.com/user-attachments/assets/a838b50c-1b16-4594-9eae-3569539de250

**Comment by andersonjeccel** [comment]
@escopecz Did you fix something?

the button is there for me 

image

**Pull request merged**
