### PR TITLE
Segment query optimizatioin 

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [enhancement]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [x] 
| Related user documentation PR URL      | /
| Related developer documentation PR URL | /
| Issue(s) addressed                     | /

#### Description:

This PR optimizes two DB queries used when adding contacts into a segment.

#### Steps to test this PR:

Create a segment with a filter Unsubscribed - Email.
Check if proper contacts are added into the segment.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10904"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
@npracht @kuzmany @RCheesley this is blocking further work on https://github.com/mautic/mautic/pull/10903 which is needed for open sourcing the Custom Objects plugin. So we have to merge this asap.

**Review by kuzmany — DISMISSED** [review]
I am okay with this. 
Do Not Contact manually segment fitlers tests works for me with all combination what I've tried 👍 
Unit tests included 👍

**Comment by RCheesley** [comment]
Changed base to 4.2

**Review by RCheesley — DISMISSED** [review]
@kuzmany @escopecz from what I can see in the PR description, this is an enhancement and not a bug, so it should go to the 4.x branch.  Looks like it was incorrectly labelled as a bug, which is why I had changed the branch to 4.2 a little while ago.

Once this is rebased, it's RTC as I have just done a second test and all the segments worked as expected, filters are behaving as they should.

**Comment by escopecz** [comment]
Rebased to latest 4.x

**Comment by escopecz** [comment]
@RCheesley @kuzmany I had to cherry-pick once more after https://github.com/mautic/mautic/pull/9852 was merged. It contains all the commits as before except 2 that were adding duplicate filters to the community and therefore shouldn't be here. Please re-approve so this can be merged and I could continue with https://github.com/mautic/mautic/pull/10903 which is blocked by this.

**Review by RCheesley — DISMISSED** [review]
Works great for me - tried with equals and does not equal, correct numbers were assigned.

**Comment by RCheesley** [comment]
Should be GTG as soon as GitHub Actions is back up and running 😅

**Comment by kuzmany** [comment]
@escopecz need some touch because CI failing

**Comment by escopecz** [comment]
@kuzmany @RCheesley I fixed the segment filter for manually unsubscribed contacts from SMS channel pointed out by a test. Please re-review.

**Review by kuzmany — APPROVED** [review]

**Comment by RCheesley** [comment]
I have been testing this and am finding some strange behaviour when cloning the segment and then saving with changes, likewise when editing the segment.

Here's a screencast: https://watch.screencastify.com/v/nMUBLc0VqQ4cVEvYUozc

Here's what I believe to be the related log entry:

```
[2022-03-17 13:25:10] mautic.CRITICAL: Uncaught PHP Exception ErrorException: "PHP Notice - unserialize(): Error at offset 5812305 of 5812308 bytes" at /var/www/html/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php line 126 {"exception":"[object] (ErrorException(code: 0): PHP Notice - unserialize(): Error at offset 5812305 of 5812308 bytes at /var/www/html/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php:126)
[stacktrace]
#0 [internal function]: Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler->handleError(8, 'PHP Notice - un...', '/var/www/html/v...', 126, Array)
#1 /var/www/html/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php(126): unserialize('a:9:{s:5:\"token...')
#2 /var/www/html/vendor/symfony/http-kernel/Profiler/Profiler.php(87): Symfony\\Component\\HttpKernel\\Profiler\\FileProfilerStorage->read('8f5368')
#3 /var/www/html/vendor/symfony/web-profiler-bundle/Controller/ProfilerController.php(153): Symfony\\Component\\HttpKernel\\Profiler\\Profiler->loadProfile('8f5368')
#4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(158): Symfony\\Bundle\\WebProfilerBundle\\Controller\\ProfilerController->toolbarAction(Object(Symfony\\Component\\HttpFoundation\\Request), '8f5368')
#5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#6 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#7 /var/www/html/app/AppKernel.php(115): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#8 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#9 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#10 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#15 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#16 {main}
"} 

```

**Comment by RCheesley** [comment]
Also happens with Email manual unsub = yes, and SMS unsub manual = yes (creating from scratch, not cloning

New Segment _ Mautic
)

**Comment by kuzmany** [comment]
@RCheesley I feel like it's related to segments refactoring, not to the PR :(

**Comment by RCheesley** [comment]
OK I'll raise as a separate issue, I did check it in 4.x and didn't get it. But I'll check again!

**Comment by escopecz** [comment]
@RCheesley it happened to you in https://github.com/mautic/mautic/pull/10890#issuecomment-1050759432 as well which is not merged yet. So it is an issue in 4.x already.

**Pull request merged**
