### PR TITLE
Email without name should have a to: email@email.com

### PR DESCRIPTION
**Pull request by chandon**
Please answer the following questions. 

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #2131 
| BC breaks? | N
| Deprecations? | N

**Note that all new features should have a related user and/or developer documentation PR in their respective repositories.** 

#### Description:
When a contact has an email but no firstname and no lastname, email is send to " " < the@email.com >.
When firstname and lastname are empty, the "To:" field should be email only, without " " and < >

#### Steps to test this PR:
1. Create a user without firstname and lastname
2. Send an email with mautic.
3. Check To: header. Now it's To: email@email.com and not To: " " < email@email.com >

### CODE REVIEW

**Comment by dbhurley** [comment]
+1

**Comment by alanhartless** [comment]
+1

**Comment by alanhartless** [comment]
@chandon First, thanks for this! 

Second, just as a FYI, I'll manually merge this to fix this, but be aware of file permissions. Files should be 0644. This PR changed the two files you edited to 0755.

**Comment by chandon** [comment]
@alanhartless  thanks for thé info, samedi problem with all my pending PR, i will try to fix them today

**Pull request merged**
