### PR TITLE
Email Dynamic Content

### PR DESCRIPTION
**Pull request by dongilbert**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Related user documentation PR URL | Pending
| Related developer documentation PR URL | Pending
| Issues addressed (#s or URLs) | #2185 (?)
| BC breaks? | N/A
| Deprecations? | N/A
| Dependencies | #2558 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

This PR adds support for dynamic content to emails. (It's also the first step in implementing it where it makes sense on our other outbound channels.) 

This relies on #2558 due to adding the ability to create filters using Company data.

#### Steps to test.
Apply the PR, clear cache, run the migrations, then follow these steps below:

On the Email form page, you'll see that there is a new "Dynamic Content" tab at the top, as well as a new book icon on the Froala editor toolbar. The book icon, when clicked, shows a dropdown of the dynamic content that you've set up for that email. To set up dynamic content, click over to the Dynamic Content tab at the top, and you'll see the interface below:

screen shot 2016-09-20 at 8 55 34 pm

In the upper left of the content area is a "+ New" button. Click this to create a new dynamic content item for this email. On the right half of that screenshot you'll see the dynamic content form which has a Name, Default Content, and another tab block below.

When you enter text into the Name field, it will auto update the corresponding tab's name on the left. Removing all text from the Name field will revert the tab name to "Dynamic Content X", where X is that tab's place in line.

Default Content is where you enter the default text to use in the email. This will be used if the contact you are sending the email to fails to match any of the variant filters that you've set up.

The tabbed area below the textarea is where variants are created. Again you can click "+ New" here and it will create a variant. Variants have a Content area, which will be used in the email if the contact you are sending the email to matches the variant filters.

Below the content is where you set the actual filters. Select an option from the dropdown and you can add any filters there. This works identical to segment filters. If you're testing, please test several filter types to ensure they function correctly.

You can add an unlimited number of dynamic content items, and each item can have an unlimited number of variants (although the UI becomes unwieldy if you add an unreasonable amount).

Once you've created your dynamic content, click back over to the Content tab at the top and then click into the text area to insert one of them. Place your cursor where you want to insert the dynamic content, then using the book icon on the far right of the Froala editor toolbar, click that button and select one of your dynamic content items from the dropdown. The corresponding token is now inserted into the text area.

I've found the easiest way to see all the functionality is to set up a few different dynamic content items on an email and send that email out as part of a test campaign. Use many filters with different content for each and set up some fake contacts with specific data that you want to filter on. Add those contacts to a segment and use that segment as the entry point to the campaign, with a campaign action that sends them your email full of dynamic content.

### CODE REVIEW

**Comment by mqueme** [comment]
I was able to send emails using dynamic content.

**Comment by alanhartless** [comment]
Tested with company fields and all still worked. +1

**Comment by chandon** [comment]
Is it possible to activate "Code View" button on the froala editor of the dynamic content ?

**Comment by chandon** [comment]
@alanhartless  great job, i tested it, this feature was really missing !

You can include "contact/company fields" in variant

Seems that including another "dynamic content" in a "dynamic content" causes the dynamic content to be destroyed with "[object object]" text (i think it's quite hard to develop the inclusion of another dynamic content, because of possible circular references)

**Comment by dongilbert** [comment]
It is not currently possible to embed one Email Dynamic Content into another. While technically possible, it would run into the issue that you described of circular references. In order to protect against that I think we could add a validation check on save to ensure no circular references are added, and if one is detected just error the form, stop it from saving, redirect the user to the edit page and give them a message about it so they can fix it.

**Comment by chandon** [comment]
Tested *Custom* contact fields in variant, it's not working. Got {contactfield=custom_field} instead of value

**Comment by chandon** [comment]
if the custom field is included in a variation AND in the main body, both are translated in body + in variation. But if not in main body, the field is not translated

**Pull request merged**
