### PR TITLE
Add manually unsubsribed to segment filters

### LINKED ISSUE #2782: Allow searching contacts based on Bounce/Do Not Contact (DNC)
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? |  Y

## Description:
Allow searching contacts based on Bounce/Unsubscribe/Do Not Contact settings.

In addition, I think it would be nice if each contact in the contact list showed if they were set DNC/Bounced so its easy to tell from a glance without having to go into each separate contact. Perhaps by just showing a red circle with line through it on each row for DNC, and a yellow circle with line through it for Bounced.

### PR DESCRIPTION
**Pull request by galvani**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | Y
| BC breaks? | N
| Deprecations? | N
| Issues | fixes https://github.com/mautic/mautic/issues/2782

[//]: # ( Required: )
#### Description:
It is requested to enable users to filter for *manually added DNC contacts* for **email** and **sms**.
Fields labeled:
 * Manually marked as do not contact - Email
 * Manually marked as do not contact - SMS

#### Steps to test this PR:
1. Create few segments containing current DNC reasons and their combination
2. Write down the numbers so you can verify
3. Checkout this PR and CC
4 . Verify that filters you have created in **1** are still valid.
5. Create segment containing new DNC fields and verify the content is valid.

### CODE REVIEW

**Comment by npracht** [comment]
@galvani can you check Tavis plase ?

**Comment by galvani** [comment]
@npracht it's fine now. thanks for noticing.

**Comment by drimlike** [comment]
@npracht @escopecz @galvani 
Hello and happy new year! :) 
Is there a way to unlock the situation here and get the feature released please? Thank you!

**Comment by npracht** [comment]
Hi @drimlike !
Yes, find a release leader that would like to carry 2.15.4 if he wants to manage only bugs or 2.16.0 if he agrees to include features.

**Comment by drimlike** [comment]
Hi @npracht , thanks for your reply :) 
Do you mean that Mautic has no release leader anymore? I thought there was a small group of people taking care of the project. Or is it because Mautic has been acquired by a private company? Sorry I might have missed some bits and piece in the story.

**Comment by npracht** [comment]
Mautic community has no release leader for a 2.x version. All the Acquia's team and some community contributors are working hard on Mautic 3.x (so i guess we have a release leader there knowing that @alanhartless has released [3.0.0-alpha](https://github.com/mautic/mautic/releases/tag/3.0.0-alpha)).

So release leader there is, but currently focused on 3.x series. It would be great to have another community release leader for a last 2.x version but I am scared we don't find volunteers. If you feel like calling for volunteers on Slack, or even financing one. Then it could work !

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@mautic/acquia-po assuming this is still relevant for 3.x (as this wasn't clarified yet) I'm assigning this to the 3.2 milestone, so someone will need to address the conflicts and we need it tested by **Sunday, 15th November**.

**Comment by escopecz** [comment]
@RCheesley I rebased the PR.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by npracht** [comment]
@escopecz can you cover it with more tests ?

**Comment by escopecz** [comment]
@npracht done

**Review by npracht — APPROVED** [review]
👍

**Comment by escopecz** [comment]
This is problematic. The manually unsubscribed from email channel was already implemented in https://github.com/mautic/mautic/pull/7475

On top of that this PR does not add any new segment filters as it was not ported correctly from our fork.

**Comment by npracht** [comment]
oh ? So it worked on mautibox because of already merged PR right ?

**Comment by escopecz** [comment]
@npracht yes, I think you were testing the segment filter added by @kuzmany back in M2.

**Comment by alanhartless** [comment]
This PR added the `dnc_unsubscribed_sms_manually` filters that https://github.com/mautic/mautic/pull/8649 has some dependencies on. I'll try to cherry pick copy/paste the relevant parts into #8649.

**Comment by alanhartless** [comment]
The manual unsubscribe for SMS has been ported to https://github.com/mautic/mautic/pull/9852

**Pull request closed without merging**
