### PR TITLE
Update of the country name of Swaziland to Eswatini

### PR DESCRIPTION
**Pull request by AlanWierzchonCA**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [yes]
| New feature/enhancement? (use the a.x branch)      | [ no]
| Deprecations?                          | [ no]
| BC breaks? (use the c.x branch)        | [no ]
| Automated tests included?              | [no ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10954"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for the PR @AlanWierzchonCA - I checked the background on [Wikipedia](https://en.wikipedia.org/wiki/Eswatini) and indeed this needed updating! 

If you can please sign the contributors agreement that would be super. 

We will also need a database migration, so that folks who are using the old name will have their instances updated to the new name. Are you able to do that or would you like some help? There's some docs [here](https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#step-6-migrations-needed) about migrations.

**Comment by npracht** [comment]
@AlanWierzchonCA you have the exact same migration example here: https://github.com/mautic/mautic/pull/10802/files#diff-cc20b6d7cf880e01c8ede96286f54eaad66143f6d2766b6ccd3ab071ffc2f438

**Comment by AlanWierzchonCA** [comment]
Hi @Rcheesley,
I sent a Mautic Contributor Agreement some time ago and added a database migration with the last commit.

@npracht , thanks for the example!


Regards,
Alan

**Comment by RCheesley** [comment]
@npracht I don't think this is a BC break if we have the migration in place to change existing entries to the updated entry? Just noticed it has that label applied.

**Comment by RCheesley** [comment]
@AlanWierzchonCA could you please take a look at the [codestyle issues](https://github.com/mautic/mautic/runs/6370640720?check_suite_focus=true#step:7:54) being flagged by the GitHub Action checks? You can use the dev tools we have to auto-fix issues like this, check out our docs for more info on that: https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#code-standards

Thanks!

**Comment by npracht** [comment]
@RCheesley i think this is a BC. If people is using by API value ABC and then value ABC is changed to ABCD with migration of current value, the usage by API is broken if the person continue to send ABC.
This is a BC right ?

**Comment by AlanWierzchonCA** [comment]
Hi @RCheesley, 

I corrected the code style in the last commit, should I add something else?

**Comment by AlanWierzchonCA** [comment]
Hi @RCheesley,

I have commited corrections, so can you try review again?

**Comment by AlanWierzchonCA** [comment]
@RCheesley , 

I corrected the code style in migrations after the last check.

**Comment by AlanWierzchonCA** [comment]
Hello @RCheesley, 
what next with this PR?

**Comment by RCheesley** [comment]
Hey there! 

It will need to be rebased to 5.x for the next release where we would add this and you will need to update the upgrade file to alert people to the change if it's considered to be a BC break.

**Comment by AlanWierzchonCA** [comment]
I created PR for 5.x these changes: https://github.com/mautic/mautic/pull/12061 and updated the upgrade file with BC info.

**Comment by RCheesley** [comment]
Closing in favour of #12061

**Pull request closed without merging**
