### PR TITLE
Change clean conditional values  with InputHelper::clean

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Follow up for https://github.com/mautic/mautic/pull/11093
We need use clean of values, because some characters made form validation invalid

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create form with selectbox and value `J'è & Or`
3. Then make conditional field with condition for value in `J'è & Or`
4. Before PR you are not able to save field form becasue it retun validation error
5. After PR should work properly

### CODE REVIEW

**Comment by volha-pivavarchyk** [comment]
Im getting a validation error when I try to save the field. From the description, I understand otherwise. Am I wrong?

1. Create a new field 
image

2. Choose as condition
image

3. Get a validation error
image

**Review by escopecz — APPROVED** [review]
Looks good. Thanks! 👍

**Comment by kuzmany** [comment]
@volha-pivavarchyk you're true, this does not work If you type properties list. If you let properties list from mapping contact field then works 

image

We need check it, it's lil bit tricky

**Comment by escopecz** [comment]
Oops, I evaluated Volha's comment as positive. Should have read more carefully. @kuzmany will you push a fix as a new PR or shall I revert this?

**Comment by kuzmany** [comment]
@escopecz I do not have fix yet. It's
- InputHelper::clean works on properties list taken from contact field
- InputHelper::string works on properties list written directly properties tab

But any of them work for both. Don't have idea at the moment.

**Comment by escopecz** [comment]
How about to sanitize the conditions the same way as the value?

**Pull request merged**
