### PR TITLE
[UI] Dropdown menus

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description
This PR is based [on another PR](https://github.com/mautic/mautic/pull/13735), where I introduce tokens to replace most of the UI variables, aiming to improve consistency in all components. **We need it to be merged before this one becomes available for code review.**

It changes dropdown styles and makes it compatible with dark theme.
Also fixes the too tiny size of clickable items on mobile.

Now when you hover over danger actions, have better visual feedback:

https://github.com/mautic/mautic/assets/116097999/79ec8ea1-6062-43fe-99d4-f67736a11c9c

Or navigating with your keyboard arrows

https://github.com/mautic/mautic/assets/116097999/439f7e9a-fef1-4b7b-be2a-e9d0e03ee341

| Before                                 | After
| -------------------------------------- | ---
|  image                                      | image

image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open the Dashboard
3. Click on the caret to open the dropdown

### CODE REVIEW

**Review by PatrickJenkner — APPROVED** [review]
Works and looks good on both desktop and mobile 👍

**Review by shinde-rahul — APPROVED** [review]

**Comment by escopecz** [comment]
Isn't this PR based on https://github.com/mautic/mautic/pull/13735?

**Comment by LordRembo** [comment]
@andersonjeccel as mentioned in other similar PR's, this is another one based on the Tokens branch. I think there's 5 or 6 now? Please put it in draft until we discussed what you're trying to achieve and set a better course of action.

**Comment by andersonjeccel** [comment]
@escopecz Is this one ready to commit? No changes since last users tests, those commits are from the tokens PR

**Pull request merged**
