### PR TITLE
Zoho integration improvements

### LINKED ISSUE #9281: Zoho + Mautic plugin not importing some custom fields
## Bug Description

I have a Zoho account and have installed the Zoho plugin in Mautic.
Contacts from Zoho are correctly created in Mautic ("PULL"). Everything is fine except that some fields are not imported.

1. I have some "true/false" checkboxes in Zoho. I have created the same custom field in Mautic, "boolean". I have mapped the field. These fields are not imported. It seems to me that Zoho assigns "true/false" values while Mautic looks for "0/1".
2. I have a field "current status" in Zoho, which can be "open, closed, abandoned, lost, suspended". I have created in Mautic a custom field "Select" with these values. I have mapped the field. This fields is completely ignored.
3. Likewise, I have a "product" field in Zoho. Recreated in Mautic and mapped. It gets ignored.

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.3
| Browser | Chrome, Firefox, Edge. 

### Steps to reproduce
1. You need to have a Zoho account and probably a paid version that lets you create custom fields. 
2. Configure the Zoho plugin in Mautic, map the fields
3. Try to create a contact that has a custom field (in the type of a "select" and "boolean"), 
4. You should see the contact created in Mautic, but missing the values for the custom fields.
 
### Log errors
No error logged.

### PR DESCRIPTION
**Pull request by kuzmany**
closes https://github.com/mautic/mautic/issues/9281

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | x
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/9281
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

We build a lot of improvements to  Zoho integration

Bug fixes:
- fix multi select field options on both side
- fix sync company info to Mautic from Leads and Contacts
- pretend sync If contacts already exits in integration 

Improvements: 
-  add new option - Sync blank values from/to integration

# Steps to reproduce: 

1 Create a Multiple Select Custom Field on Mautic
2 Create A Multiple Select Custom Field on Zoho (Settings > Customization > Modules and Fields > Contacts - Select 'Fields' tab and click 'Create & Edit Fields' then drag a multi-select field into the form area. Note also: "If the ZohoCRM field is a pick list, **be sure the list values of Mautic's field match those of the field in ZohoCRM**" [source](https://docs.mautic.org/en/plugins/zoho-crm#test-the-plugin)
3 Mapped those 2 field in the Zoho plugin
4 Create a contact in Mautic, choose 2 choices in the select field
5 Synchronize and see that the 2 choices are in only one in Zoho
6, Map Account Name, Company field in Mautic for both tab (see example of mapping bellow)
6, Create contact on Zoho and add company to this contact
7. Try sync to Mautic. No company there, just on sync run second time
8. Create lead with company name
9. Sync no company name synced
10. Try update values with empty value - for example match Mautic address1 with  Mailing Street on Zoho. 
11. Empty values are skipped. New options added to integration allow sync also empty values 
12. Try to find contact in Zoho Contacts with modified date older like 15 minutes
13. Create same contact in Mautic - email should be same
14. Then try sync Zoho
15. Newly created contact in Mautic is created in Zoho Leads, even thought already exist in Zoho Contacts. We expect contact in Mautic will find already exists contact in Zoho Contacts

Example of mapping
image

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat all steps, see multi select in right way also company sync in right way

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/7867"></a>

### CODE REVIEW

**Review by florentpetitjean — COMMENTED** [review]
works fine with leads and contacts but can't sync multiple fields in company

**Review by florentpetitjean — DISMISSED** [review]
Tested and Working now. 
Thanks for that fix.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
Bumping to 3.1.1 due to unresolved failing Travis build.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Bumping to 3.1.2 due to unresolved failing Travis build.

@kuzmany this will need to be resolved by **18th October**

**Comment by npracht** [comment]
@kuzmany can you please check at travis issue ?

**Review by Dylan-86 — DISMISSED** [review]

**Comment by atulcj** [comment]
Since the Zoho Integration is being improved. Maybe this could be a valid addition.

Mautic 3.1.1 lists only 4 Zoho datacenters, but Zoho has more datacenters - as listed here 
[https://www.zoho.com/know-your-datacenter.html](https://www.zoho.com/know-your-datacenter.html)

I think the India datacentre is fairly new. When I created a Zoho account in June 2019 and was wanting to integrate Zoho CRM with mautic I discovered this problem. 

Another Zoho account (created in 2015) of mine has a US datacenter and the integration works ok.

I do not know of other Mautic users from India wanting to integrate with Zoho CRM and hence could not verify my finding. Nor did I find this issue being discussed anywhere else in the Mautic universe (Facebook group, Github, Forums).

I would like to apologize in advance if this was not the right place to be reporting this. Creating a new issue on Github is something I require to learn more about.

**Comment by RCheesley** [comment]
@kuzmany can you easily add into this PR the additional data centres that @atulcj mentions above? Also seems that there are some issues to fix on Travis.

**Comment by RCheesley** [comment]
@kuzmany I am just testing this before applying the PR and I note that in the description you state: 

> add new option - Sync blank values from/to integration

However I already see this as an option in 3.2.4:

screenshot-mautic32 ddev site-2021 01 18-13_34_49

Maybe this was implemented in an earlier feature release?

**Comment by kuzmany** [comment]
@RCheesley 
Update blank values means  update blank value, even If you set direction to other side.
That means, If you have first name empty on Mautic side, and you want to sync first name just to integration,  this option sync to Mautic first name in case If first name is empty.

Sync blank values from/to integration
means reset value. For example If you sync empty value of first name from integration to Mautic, then first name is not set to empty. This option enable this way to update/reset value.

Does it sound more clear?

**Comment by RCheesley** [comment]
> Does it sound more clear?

Not really. We need to ensure that this is properly documented with clear explanations otherwise I could see folk getting quite confused.

Can you please ensure that a docs PR is made? I just updated the docs to take into account the new UI when setting up API keys for Zoho.

**Comment by RCheesley** [comment]
Added some info on how to create a custom field in Zoho in case anybody testing is not familiar.

Got stuck because the multi-select field created in Zoho does not appear to be available for pairing in Mautic so will come back to this once we troubleshoot that!

**Comment by RCheesley** [comment]
Bumping from the release due to a lack of testing.

**Comment by npracht** [comment]
@RCheesley could you please explain what do you expect to be added in the doc ? I could do it but for me the doc is complete.

**Comment by RCheesley** [comment]
Hi @kuzmany - another one which we need to decide if we're going to pull forward to 5.x or not. What are your thoughts?

**Comment by kuzmany** [comment]
We gonna this PR fork to M5 internally and later push it to community.

**Pull request closed without merging**
