### PR TITLE
Pipedrive integration plugin

### PR DESCRIPTION
**Pull request by thecodeine**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | --
| New feature? | Y
| Related user documentation PR URL | --
| Related developer documentation PR URL | --
| Issues addressed (#s or URLs) | #659, #3858, 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Full live sync between Mautic (subscribers) and Pipedrive (webkoohs). Documentation in progress...

#### Testing

Please note, when creating the webhook in Pipedrive, the username and password you create for the endpoint does NOT need to be a valid mautic user. Just needs to be the same as what you entered in the Mautic Pipedrive integration form.

```
Pipedrive URL: https://YOURSUB.pipedrive.com
Pipedrive Token: In Pipedrive, go to Settings > Api > Token is highlighed in Green
Webhook User/Password: The username/password you specified when creating the webhook in Pipedrive
```

### CODE REVIEW

**Comment by npracht** [comment]
Congrats! :1st_place_medal: 
Thanks to @thecodeine for working and @webmecanik for the financing!

**Comment by clementdes** [comment]
Hi guys ? any idea of when would this pipedrive/mautic sync plugin release ? 
BTW: You rock... !!! 👍

**Comment by dongilbert** [comment]
I'm trying to test this, but without documentation on setting up the integration, it's very difficult. What information do I here to enable it? The documentation in Pipedrive is not helping much.

screen shot 2017-06-16 at 10 22 02 am

**Comment by dongilbert** [comment]
@thecodeine @npracht Any help? I'm also going to reach out to thecodeine on Slack.

**Comment by npracht** [comment]
@dongilbert documentation will be PRed on monday !

**Comment by thecodeine** [comment]
Link to PR with documentation. https://github.com/mautic/documentation/pull/197

**Comment by npracht** [comment]
@dongilbert, it is monday :)

**Comment by virlatinus** [comment]
I tried to push a contact and got the following error:
```
[2017-06-28 08:37:50] mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method MauticPlugin\MauticCrmBundle\Integration\Pipedrive\Export\LeadExport::logIntegrationError() - in file /var/www/mautic-fork/plugins/MauticCrmBundle/Integration/Pipedrive/Export/LeadExport.php - at line 58  
```

**Comment by dongilbert** [comment]
Form & campaign actions work. Pushing contacts & companies from the command line works as expected. Great job on this guys!

**Comment by thecodeine** [comment]
Thanks a lot @dongilbert ;-)

**Comment by willemrt** [comment]
This is fantastic! Great work

However Im not getting some mapped fields push both ways. Only one way (Mautic to Pipedrive) 

But its not syncing the other way (Pipedrive to Mautic). This is for custom text fields that I have mapped. Im my case an Industry field for contacts.

Name changes do however update perfectly.

Im not sure if this is the best place to report the bug?

**Pull request merged**
