### PR TITLE
Email copy improvements

### LINKED ISSUE #857: Optimize email copies in email_stats table to use less disk space
Hello,
after just sending first newsletter to 30K subscribents my mautic database shows 1.35GB in size.
Table 'email_stats' shows 1.3GB
Should it be that way?
Mayby it's possible to do some optimalization or add option not to save each sent email separately.
Regards,
Bart

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**

Mautic stores a copy of each email sent in it's email_stats table but this has resulted in very large tables when emails contain graphics.  This PR addresses this by creating a table that stores a copy of the content and referenced by the email_stats table instead.  This should decrease the space required significantly and fixes #857.

**Testing**

Apply the PR and run `doctrine:migrations:migrate` to update the schema.

Send an email to a lead directly (lead profile -> send email). It'll help to embed the {webview_url} token somewhere to make it easy to click through to the web view.

After sending, check the email_copies table for the new entry.  Send a different email and/or edit the email content of the original sent and send a second email.  This should result in a new entry into the email_copies table.  

Delete the originally sent email from Mautic's email list then click through to the webview or directly browse to it by gleaning the tracking hash from the email_stats table and go to /email/view/TRACKING_HASH. The content should display.

Now send an email to a lead list. After sending, check the email_stats table for entries created and ensure list_id is populated appropriately.

### CODE REVIEW

**Comment by escopecz** [comment]
I sent an email template to a lead directly with the `{webview_url}` shortcode in it. It worked nicely in the email, but when I preview the email in the broswer, the variables are not replaced. `{leadfield=firstname}` also works in email, but not in the webview. I guess that's not good.

**Comment by alanhartless** [comment]
@escopecz  :-) guess it would help to replace the tokens and to test with emails that actually use tokens :tired_face: 

list_id should be there in the `email_stats` table

**Comment by escopecz** [comment]
The tokens and URL trackers seem to work now, however, if I send a list email and delete it, the webview throws 404. Is that OK?

**Comment by alanhartless** [comment]
Does the stat still exist after you delete it? Didn't think we had a cascade delete on that but will check.

**Comment by escopecz** [comment]
Yes, the stat rows get deleted with the email

**Comment by alanhartless** [comment]
Changed cascading for the email_id in the stat table to null instead of delete.  The stat and copy should be reserved now.

**Comment by escopecz** [comment]
Yes, everything works for me now :+1: 

Note for other testers, make sure your DB schema is up to date after applying this PR. (command `doctrine:schema:update --dump-sql`)

**Comment by dbhurley** [comment]
:+1: Followed all steps, had to ensure schema updated before it worked.

**Pull request merged**
