### PR TITLE
[UI] Accent colors

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This allows you to set your preferred color.

Also:
- Adds styles for popovers
- Adds popover about solarized themes
- Includes minor fixes for the account page
- Makes the JS function more reliable when no accent colors are previously set (they default)
- Removes support for secondary brand color
- Adds 25 predefined accents
- Creates Twig template for popover
- Creates Twig template for accents
- Several fixes to improve the platform compatibility with themes
- Nests remix icon pack classes into the main icon class to improve specificity and allow devs to customize icon size in buttons

image

image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Account
3. Open the Appearance tab
4. Play with the colors then check the entire platform

### CODE REVIEW

**Comment by RaffyRod** [comment]
I want to attempt testing this PR. @andersonjeccel can I go ahead?

**Review by shinde-rahul — APPROVED** [review]
Code Looks Good to me!!!

**Comment by RaffyRod** [comment]
I have tested and validated each of the new Twig templates for popovers and accents, 
verifying that both operate as expected within the defined UI flows. The color customization functions perform correctly,
 including the default behavior when no accent colors are initially set. 

Additionally, I reviewed the changes in styles for popovers and the solarized theme popover, ensuring the styles are applied consistently. The improvements to the account page and the adjustments to JavaScript logic have proven to increase reliability in various scenarios.








@andersonjeccel please if posible add me as a reviewer.

**Comment by andersonjeccel** [comment]
@RaffyRod A huge THANKS for testing! 😄 

Also checking here re. adding as reviewer

**Review by RaffyRod — APPROVED** [review]
Looks good to me.

**Pull request merged**
