### PR TITLE
Fix DNC save entity

### LINKED ISSUE #8463: Undefined class constant ON_CAMPAIGN_ACTION_ADD_DONOTCONTACT
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Error 'The site is currently offline due to encountering an error' after upgrading to 2.16.0

| Q   | A
| --- | ---
| Mautic version | 2.16.0
| PHP version | 7.2.24
| Browser | Multiple

### Steps to reproduce
php app/console cache:clear
php app/console mautic:update:find
php app/console mautic:update:apply
php app/console cache:clear 

### Log errors
Symfony\Component\Debug\Exception\FatalThrowableError: Undefined class constant 'ON_CAMPAIGN_ACTION_ADD_DONOTCONTACT' - in file /app/app/bundles/LeadBundle/EventListener/CampaignActionDNCSubscriber.php - at line 56

Seems to be related to https://github.com/mautic/mautic/pull/7567

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
While we use https://github.com/mautic/mautic/pull/7567 in production we noticed something wrong with add DNC to contact. I noticed some issues and suggest improvements. 

If contact has already bounced, bounced flag was removed but and unsubscribe flag not added. In fact, this contact begin contactable

- This PR fixed it persits = true
- This PR rework campaign DNC actions for persist = false

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create contact and add bounce flag to contact (If you are not dev,  maybe by sending email to not exists email)
2. Open contact profile and Contact preferences 

image

3. Just save it
4. See Bounced flag removed from contact profile
5. Same happen If on public preferences center and also if you're using campaign action (https://github.com/mautic/mautic/pull/7567 )

#### Steps to test PR:
1. Repeat all steps like for tests
2. After save preferences center (public, in Mautic) you should still see bounced flag in contact profile. After remove bounced flag, then you can add DNC flag by contact preferences center
3. You can also test campaign actions https://github.com/mautic/mautic/pull/7567
- Add Do Not Contact - should add unsubscribe flag - If contact already has bounced flag, no unsubscribe flag added
- Remove Do Not Contact - should remove just Do Not Contact flag from contact profile, not bounce flag

### CODE REVIEW

**Comment by npracht** [comment]
>If contact has Bounced flag and add DNC campaign action is triggered: should be bounced flag removed and add Unsubscribed flag? Or add along with bounce flag also unsubscribe flag to contact? Or does not change it and let just bounce flag?

We should not remove existing flag. So add unsub flag extra.

>If contact has bounce flag and remove DNC campaign action is triggered: should remove bounce flag? Or just remove unsubscribe flag?

Only unsubscribe because this is the name of the action. You manage unsubscription by channel.

**Review by npracht — DISMISSED** [review]
Bug does not appear anymore

**Comment by npracht** [comment]
@petebytes can you comment here about your tests ? Then @kuzmany can follow up :)

**Comment by petebytes** [comment]
Sure @npracht
After manually replacing the 3 files, clearing cache then restarting the app I see the following. 

```
Did you forget a "use" statement for e.g. "Mautic\PageBundle\EventListener\ConfigSubscriber", "Mautic\CampaignBundle\EventListener\ConfigSubscriber", "Mautic\SmsBundle\EventListener\ConfigSubscriber", "Mautic\ApiBundle\EventListener\ConfigSubscriber", "Mautic\WebhookBundle\EventListener\ConfigSubscriber", "Mautic\UserBundle\EventListener\ConfigSubscriber", "Mautic\CoreBundle\EventListener\ConfigSubscriber", "Mautic\AssetBundle\EventListener\ConfigSubscriber", "Mautic\EmailBundle\EventListener\ConfigSubscriber", "Mautic\ReportBundle\EventListener\ConfigSubscriber", "Mautic\LeadBundle\EventListener\ConfigSubscriber", "Mautic\QueueBundle\EventListener\ConfigSubscriber", "Mautic\ConfigBundle\EventListener\ConfigSubscriber" or "MauticPlugin\MauticSocialBundle\EventListener\ConfigSubscriber"? - in file /app/vendor/symfony/event-dispatcher/ContainerAwareEventDispatcher.php - at line 138
172.17.0.1 - - [21/Feb/2020:20:29:45 +0000] "GET /media/css/app.css HTTP/1.1" 200 21457 "https://mautic.launchmuse.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/82.0.4065.1 Safari/537.36
[21-Feb-2020 20:29:54 UTC] Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "ConfigSubscriber" from namespace "Mautic\FormBundle\EventListener".
Did you forget a "use" statement for e.g. "Mautic\PageBundle\EventListener\ConfigSubscriber", "Mautic\CampaignBundle\EventListener\ConfigSubscriber", "Mautic\SmsBundle\EventListener\ConfigSubscriber", "Mautic\ApiBundle\EventListener\ConfigSubscriber", "Mautic\WebhookBundle\EventListener\ConfigSubscriber", "Mautic\UserBundle\EventListener\ConfigSubscriber", "Mautic\CoreBundle\EventListener\ConfigSubscriber", "Mautic\AssetBundle\EventListener\ConfigSubscriber", "Mautic\EmailBundle\EventListener\ConfigSubscriber", "Mautic\ReportBundle\EventListener\ConfigSubscriber", "Mautic\LeadBundle\EventListener\ConfigSubscriber", "Mautic\QueueBundle\EventListener\ConfigSubscriber", "Mautic\ConfigBundle\EventListener\ConfigSubscriber" or "MauticPlugin\MauticSocialBundle\EventListener\ConfigSubscriber"? - in file /app/vendor/symfony/event-dispatcher/ContainerAwareEventDispatcher.php - at line 138
172.17.0.1 - - [21/Feb/2020:20:29:54 +0000] "GET / HTTP/1.1" 500 1124"https://mautic.launchmuse.com" "Mozilla/5.0+(compatible; UptimeRobot/2.0; http://www.uptimerobot.com/)
```
(For additional history see https://github.com/mautic/mautic/issues/8463)

**Comment by kuzmany** [comment]
@petebytes It's not related to that PR

**Comment by petebytes** [comment]
@kuzmany thanks for looking into the issue - I was unable to fix the server, built new one and migrated data and it is now working.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebased

**Comment by RCheesley** [comment]
@kuzmany as this decreases code coverage we require tests before we can merge this - moving this to the 3.0.2 milestone accordingly.

**Comment by RCheesley** [comment]
Close & open for Scrutinizer

**Comment by RCheesley** [comment]
Bumping to 3.1.1 as we don't have sufficient tests in 3.x to merge.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by StoppingBuck** [comment]
I think this might be related to #9076 - namely, you can add an unlimited number of the same flag to the same channel.

**Comment by RCheesley** [comment]
Given all the PR's that we have in 3.1.1 which relate to DNC being broken I think we need to re-test this once those fixes have been merged. Bumping to 3.1.2 as a result.

**Comment by npracht** [comment]
@kuzmany can you confirm if we still need this fix for 3.1.1 ?

**Comment by RCheesley** [comment]
@kuzmany if we can get the test coverage up on this one we would like to aim for the 4.1.2 release in January.

**Comment by kuzmany** [comment]
I think this https://github.com/mautic/mautic/pull/8565 already fixed  it

**Pull request closed without merging**
