### PR TITLE
Remove email config from installer

### PR DESCRIPTION
**Pull request by fedys**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [❌]
| New feature/enhancement? (use the a.x branch)      | [✅]
| Deprecations?                          | [❌]
| BC breaks? (use the c.x branch)        | [✅]
| Automated tests included?              | [✅] 
| Related user documentation PR URL      |  
| Related developer documentation PR URL |  
| Issue(s) addressed                     |  

#### Description:

This PR removes the email configuration step from both web and CLI installers which will ease implementing the [new mailing service](https://github.com/mautic/mautic/issues/12096) utilizing Symfony mailer.

#### Steps to test this PR:

1. Check if the web installer no longer contains the email step and is working as expected.
2. Check if the CLI installer no longer contains the email step / options and is working as expected. 

#### BC breaks:

1. The web installer no longer contains the email step.
2. The CLI installer no longer contains the email step and the email options.

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
Thanks Fedy! I see no issue in the code. This will make Mautic installation less stressful and it will help with the new email setup where each email transport will be a new plugin. So once the user installs Mautic they will go and install the email transport (service) they want to use and configure it in the administration 👍

**Review by mabumusa1 — DISMISSED** [review]
Tested the installation, changes looks good!

I think I have to rewrite many of the automation I have after this one.

Thanks @fedys

**Comment by mollux** [comment]
Changes look good and work as expected!

It's not possible anymore to install the site CLI with mail parameters (e.g. a `The "--mailer_from_name" option does not exist.` error is thrown), which is good.

The only change I'm concerned about is the change of parameter to check if the site is installed (from `mailer_from_name` to `site_url`).
This needs to be mentioned in the upgrade notes, as any workflow prepopulating parameters may need to be adapted.

**Review by mollux — COMMENTED** [review]
Changes look good and work as expected!

It's not possible anymore to install the site CLI with mail parameters (e.g. a `The "--mailer_from_name" option does not exist.` error is thrown), which is good.

The only change I'm concerned about is the change of parameter to check if the site is installed (from `mailer_from_name` to `site_url`).
This needs to be mentioned in the upgrade notes, as any workflow prepopulating parameters may need to be adapted.

**Comment by fedys** [comment]
> Changes look good and work as expected!
> 
> It's not possible anymore to install the site CLI with mail parameters (e.g. a `The "--mailer_from_name" option does not exist.` error is thrown), which is good.
> 
> The only change I'm concerned about is the change of parameter to check if the site is installed (from `mailer_from_name` to `site_url`). This needs to be mentioned in the upgrade notes, as any workflow prepopulating parameters may need to be adapted.

I needed to change the parameter from `mailer_from_name` to `site_url` as the `mailer_from_name` is no longer written during the installation process. It could be changed to `secret_key` if `site_url` is causing any issues.

**Comment by escopecz** [comment]
@mollux good point. @fedys please mention the BC changes in https://github.com/mautic/mautic/blob/5.x/UPGRADE-5.0.md

**Comment by fedys** [comment]
> @mollux good point. @fedys please mention the BC changes in https://github.com/mautic/mautic/blob/5.x/UPGRADE-5.0.md

Done via https://github.com/mautic/mautic/commit/83b0c690ff12e3ac04fa99d5bc207b3f14955e56

**Review by mollux — APPROVED** [review]
upgrade notes are clear!

**Review by escopecz — APPROVED** [review]
Thank you, Fedy! 👍

**Pull request merged**
