### PR TITLE
[UX] Change "Published" to "Available for use" for bundles

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR addresses the labeling of some resources during their creation. The term “Published” has been updated to “Available for use” to more accurately reflect the resource’s status. This change ensures that users have a clear and precise understanding of when they become usable within the system. The new label eliminates any ambiguity, thereby improving the overall user experience, especially for those who are setting up resources for the first time or managing complex configurations.

Based on https://community.mautic.org/assemblies/ux-ui-tiger-team/f/59/debates/4

Bundles addressed here:

- [x] Custom fields
- [x] Category
- [x] Dynamic content
- [x] Emails
- [x] Marketing messages
- [x] Text messages
- [x] Forms
- [x] Landing pages
- [x] Assets
- [x] Points (Groups)
- [x] Reports

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open each item on the list above
3. Create a new
4. Look at the label

image

### CODE REVIEW

**Review by Esthertests — APPROVED** [review]
LGTM
on prod 
image

on PR changes 
image

**Comment by RCheesley** [comment]
I have the same question on this to the Webhooks one (#13500) - it seems that we are moving towards having a different terminology for different parts of the application to mean the same thing, published state.

❓Is this a good move? What is the thinking behind this?

I can understand that it might make it easier for the user to understand what the switch is doing if it's bundle-specific, but maybe that just makes it more complicated if there is no consistency between the same behaviour?

You will also need to ensure that all the documentation is updated to reflect these changes before these PRs are merged, and I don't see any docs PRs (perhaps we may need to update the developer docs as well as the end-user docs, and the knowledgebase in some cases - I'm not sure) for any of these.

**Comment by andersonjeccel** [comment]
https://github.com/mautic/user-documentation/pull/251
https://github.com/mautic/developer-documentation-new/pull/182

**Comment by andersonjeccel** [comment]
@RCheesley 


> I have the same question on this to the Webhooks one (#13500) - it seems that we are moving towards having a different terminology for different parts of the application to mean the same thing, published state.
> 
> ❓Is this a good move? What is the thinking behind this?
> 
> I can understand that it might make it easier for the user to understand what the switch is doing if it's bundle-specific, but maybe that just makes it more complicated if there is no consistency between the same behaviour?
> 
> You will also need to ensure that all the documentation is updated to reflect these changes before these PRs are merged, and I don't see any docs PRs (perhaps we may need to update the developer docs as well as the end-user docs, and the knowledgebase in some cases - I'm not sure) for any of these.

The idea is to have the right terminology for each. Separate states for campaigns and resources – Draft/Active for campaigns, Draft/Available for resources. There is more info on other PRs explaining the different approaches considered (each PR has its explanation). A general overview:

Draft/Available:
- Custom fields
- Category
- Dynamic content
- Emails
- Marketing messages
- Forms
- Landing pages
- Assets
- Points (Groups)
- Reports

Draft/Active:
- Segments
- Campaigns
- Focus items
- Points (Actions, Triggers)
- Stages
- Users
- Webhooks

What do you think about these?
And what do you think about Unavailable/Available and Unactive/Active?

**Comment by RCheesley** [comment]
I feel this requires a wider discussion with the community before we can decide on taking such a renaming.

The reason I think this is:

1. This could be considered a significant change to the way users will understand and interact with the software and there has not been any discussion or consultation on this with users to understand if this is a problem that needs solving, and whether this is the right way to address it. It might be that people agree these are the right terms to use, and it's OK to have a different term for each bundle, but we have not done any research or consultation **with our own community** that backs up the suggested improvements from the Tiger Team.
2. Changing from one set of terms across the whole application to potentially different terminology for each bundle has the potential to create confusion for users
3. There will be substantial work required for the translation teams to ensure that the terms are all being correctly translated with the correct meaning and implication of the action - going from one set of terms to one set for each bundle, multiplied by the number of languages we support, this is no small change.
4. Every single documentation resource will have to be updated to reflect the proposed changes and this must be done before the PRs can be merged - including KB content and potentially the dev docs as well. That's a big overhead.
5. Rather than moving towards consistency (one of the goals of the UX project) we're effectively moving in the opposite direction with these proposed changes. While I understand the reason for the proposal, I feel we need to get input from the users of the software before we decide to make such a change.

 Please start a debate here: https://community.mautic.org/assemblies/ux-ui-tiger-team/f/59/

**Comment by Mike-Dropsolid** [comment]
> I feel this requires a wider discussion with the community before we can decide on taking such a renaming.
> 
> The reason I think this is:
> 
> 1. This could be considered a significant change to the way users will understand and interact with the software and there has not been any discussion or consultation on this with users to understand if this is a problem that needs solving, and whether this is the right way to address it. It might be that people agree these are the right terms to use, and it's OK to have a different term for each bundle, but we have not done any research or consultation **with our own community** that backs up the suggested improvements from the Tiger Team.
> 2. Changing from one set of terms across the whole application to potentially different terminology for each bundle has the potential to create confusion for users
> 3. There will be substantial work required for the translation teams to ensure that the terms are all being correctly translated with the correct meaning and implication of the action - going from one set of terms to one set for each bundle, multiplied by the number of languages we support, this is no small change.
> 4. Every single documentation resource will have to be updated to reflect the proposed changes and this must be done before the PRs can be merged - including KB content and potentially the dev docs as well. That's a big overhead.
> 5. Rather than moving towards consistency (one of the goals of the UX project) we're effectively moving in the opposite direction with these proposed changes. While I understand the reason for the proposal, I feel we need to get input from the users of the software before we decide to make such a change.
> 
> Please start a debate here: https://community.mautic.org/assemblies/ux-ui-tiger-team/f/59/ (and please, don't use ChatGPT to write the debate text 😄 )

Just an FYI: this comes from feedback from our clients. When asking questions about the UX, the terminology came up and the 'Publish' was given as one of the examples.

It's no specific issue but in a broader context of using terminology that makes more sense/explains its use better

**Comment by RCheesley** [comment]
That's great to hear @Mike-Dropsolid - I'd be much happier with this change being made if we have the voice of the community in agreement that it would be an improvement for Mautic - and a commitment to making sure that there's consistency with our docs and other resources before the change is introduced. 

Otherwise it just becomes a big confusion point for folks who might be new to Mautic and following tutorials/documentation with different information on the screen in front of them.

I wonder as well, if it might be better to have all of the changes to those button texts in one PR which introduces the new terminology for Mautic in one PR to reduce the overload of reviewing and testing once it's been agreed by the community which terms to use etc? If they are separated in individual commits for each bundle, then it shouldn't create too much of an issue when it comes to reviewing and merging.

**Comment by Mike-Dropsolid** [comment]
> That's great to hear @Mike-Dropsolid - I'd be much happier with this change being made if we have the voice of the community in agreement that it would be an improvement for Mautic - and a commitment to making sure that there's consistency with our docs and other resources before the change is introduced.
> 
> Otherwise it just becomes a big confusion point for folks who might be new to Mautic and following tutorials/documentation with different information on the screen in front of them.
> 
> I wonder as well, if it might be better to have all of the changes to those button texts in one PR which introduces the new terminology for Mautic in one PR to reduce the overload of reviewing and testing once it's been agreed by the community which terms to use etc? If they are separated in individual commits for each bundle, then it shouldn't create too much of an issue when it comes to reviewing and merging.

Yes of course. I too would like more feedback on this. 1 or 2 of our clients saying this is no reference for the entire base of users. But at least it came from somewhere ;)

And while I realize these changes individually do not always look like much, all of them combined will make Mautic a tool that is much easier to use for anyone.

One PR, good idea!

**Comment by alexhammerschmied** [comment]
@Mike-Dropsolid I can confirm this from our clients as well. 
Mautic in general is considered as "developer-porn" in regards of naming and logic. It is logical but lots of marketers have serious problems understanding the naming and logic. 
I think the approach  mentioned by @andersonjeccel  above is a very good start

> Draft/Available:
> 
> * Custom fields
> * Category
> * Dynamic content
> * Emails
> * Marketing messages
> * Forms
> * Landing pages
> * Assets
> * Points (Groups)
> * Reports
> 
> Draft/Active:
> 
> * Segments
> * Campaigns
> * Focus items
> * Points (Actions, Triggers)
> * Stages
> * Users
> * Webhooks

**Comment by andersonjeccel** [comment]
@Mike-Dropsolid @RCheesley Here we go:
https://community.mautic.org/assemblies/ux-ui-tiger-team/f/59/debates/4

**Review by shinde-rahul — APPROVED** [review]
LGTM!!!

**Comment by andersonjeccel** [comment]
@RCheesley @escopecz Ready to commit
Docs: https://github.com/mautic/user-documentation/pull/251

**Pull request merged**
