### PR TITLE
SugarCRM Fix owner update

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This feature for Sugar CRM plugin is not working : 

image

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a contact in Sugar and sync it to Mautic
2. Update the contact Owner in Sugar and Sync again
3. The contact owner should be update in ATMT, but don't

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat all steps. Owner should be updated on Mautic side

### CODE REVIEW

**Comment by RCheesley** [comment]
@enableit do you think your team might be able to test this fix for SugarCRM?

**Comment by npracht** [comment]
FYI we use it for 5 months now

**Comment by RCheesley** [comment]
@npracht according to current code governance we require two tests afaik - if the community are happy to forego that in the case where something has been in heavy production use then we can move it to RTC. I think that's a wider conversation needed - perhaps one to table for the sprint in April :)

**Comment by npracht** [comment]
I know !!! That was just an information :P

N.

**Comment by RCheesley** [comment]
Looks like something is failing on Scrutinizer - not sure what though!

**Comment by dennisameling** [comment]
Closing and re-opening this PR so that Scrutinizer/Travis will run again. Pretty sure it was just a temporary issue.

**Pull request merged**
