### PR TITLE
Salesforce contact link

### PR DESCRIPTION
**Pull request by mqueme**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR puts the contact timeline link in a SF field if matched through the plugin UI
[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. Apply PR, match the contact timeline link with a Salesforce url field in the plugin config modal window, (the Salesforce fields can be a custom url field)
screen shot 2017-04-10 at 18 20 41

2. push a contact either through a push to integration action or the  cron job, and you should see this link in the SF lead or contact

### CODE REVIEW

**Comment by matishaladiwala** [comment]
The link writes over correctly to SF but when clicked it throws an error.

**Comment by mqueme** [comment]
@matishaladiwala  The error on the link is not related to this PR.

**Comment by escopecz** [comment]
@matishaladiwala @mqueme I pushed the fix for the link issue.

**Comment by matishaladiwala** [comment]
works for me now!

**Pull request merged**
