### PR TITLE
Tracking helper without session

### PR DESCRIPTION
**Pull request by lukassykora**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Automated tests included? | N
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description: 
Right now every anonymous user being tracked is assigned a set of cookies. One of them is a session cookie. In addition this symfony session cookie doesn't have the samesite attribute set (on purpose) which causes it to generate an ugly warning on every site mautic tracks. This PR removes the online statuses that are not used anyway.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Session cookie is created by mtc.js on costumer site  when the Mautic tracking code is added.

#### Steps to test this PR:
1. Run migration app/console doctrine:migrations:migrate 20200211095409
2. Test that no session and warning is created on the customer site by mtc.js. There is still one session cookie created by "event" file.

### CODE REVIEW

**Comment by hluchas** [comment]
I'm not able to test it. Getting the same results for staging and this branch without cookie setting in headers.

**Comment by escopecz** [comment]
@dennisameling Consider this for 2.16.2, please. It will show warnings in dev tools for latest browsers.

**Comment by kuzmany** [comment]
Need rebase against 3.x

**Comment by lukassykora** [comment]
no diff to be merged, closing

**Comment by escopecz** [comment]
This change is in 3.x already. This PR was meant to fix it for M2. If the community decides they need it, it can be reopened.

**Pull request closed without merging**
