### PR TITLE
Allow array values in api filter paramaters

### PR DESCRIPTION
**Pull request by galvani**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | Y
| BC breaks? | N
| Deprecations? | N 

Description:

We do not allow for API calls to use multiple arguments for anything but ids. The goal of this PR is to allow them.
Steps to test and reproduce this PR:

    Make simillar API calls with multiple arguments for something else than ids

/api/contacts?where[0][col]=global_customer_id&where[0][expr]=in&where[0][val]="10","11"
/api/contacts?where[0][col]=global_customer_id&where[0][expr]=in&where[0][val]=10,11

    They don't work
    Load up the PR
    They should work correctly now

### CODE REVIEW

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by dennisameling** [comment]
@galvani This PR is still based on Mautic 2. Could you please rebase it against the `staging` branch for Mautic 3 and to trigger a code coverage report? Thanks!

**Comment by RCheesley** [comment]
Bumping to 3.2 as this PR requires updating for 3.x and rebasing. cc @escopecz @alanhartless

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by npracht** [comment]
@mautic/acquia-po is it still actual and relevant for M3 ?

**Comment by escopecz** [comment]
@npracht yes, it is.

**Review by escopecz — APPROVED** [review]
Works for me 👍

**Comment by RCheesley** [comment]
@escopecz any chance you could offer a query to use with sample data to test this?

**Comment by escopecz** [comment]
Here is CURL. Paste it to a command line but update the values in capital letters:
```bash
curl "https://URL/index_dev.php/api/contacts?where%5B0%5D%5Bcol%5D=firstname&where%5B0%5D%5Bexpr%5D=in&where%5B0%5D%5Bval%5D=John,Jane" \
     -u 'USERNAME:PASSWORD'
```
In order to get some contacts in the response you have to have some contacts with first name of John and/or Jane

**Review by kuzmany — APPROVED** [review]
Looks good. 
Works for me
Unit test included

Then approve it 👍

**Pull request merged**
