### PR TITLE
Segment email send to email address once

### PR DESCRIPTION
**Pull request by hugoprossaird**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          |  no
| New feature/enhancement? (use the a.x branch)      |  yes
| Deprecations?                          |  no
| BC breaks? (use the c.x branch)        | no
| Automated tests included?              |  yes 

#### Description:

If a user want to store contacts with same the email address (so create duplicates based on email address on purpose), but avoid send more times to that email address, even If contact's are in segments. For example If more employees use same email address, or family use one email address for parents and children.
This PR added new configuration parameter to enable avoid send segment email to more like one unique email address.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create segment
3. Create 3 contacts with same [email@domain.tld](mailto:email@domain.tld) and add them to segment
4. Go to configuration and enable new options - Send to duplicated just once
5. Send segment email
6. See just one email you receive

### CODE REVIEW

**Comment by hugoprossaird** [comment]
Hello @kuzmany ,

I did here the rebase of your PR https://github.com/mautic/mautic/pull/9781,

Hugo

**Review by kuzmany — CHANGES_REQUESTED** [review]
1. need CS fixes - run `composer fixcs`
2. Need fix unit tests based on CI checks
https://github.com/mautic/mautic/pull/13768/checks#step:10:96
It was months ago, but I feel like this line it need for some DB version

https://github.com/mautic/mautic/pull/9781#pullrequestreview-973722332

**Comment by hugoprossaird** [comment]
@kuzmany, I disabled the ONLY_FULL_GROUP_BY in the test.

**Review by kuzmany — APPROVED** [review]
👍

**Comment by andersonjeccel** [comment]
Segment Emails are defined as marketing emails by default (and sent only once)
If Mautic is using email as unique identifier, shouldn't it be already doing what you're proposing?

What am I missing here?

**Comment by kuzmany** [comment]
@andersonjeccel We have customers who use multiple contacts with the same email address, such as parents and children. Email is not always unique.

**Review by andersonjeccel — APPROVED** [review]
The feature makes sense 👌

**Comment by escopecz** [comment]
Apologies, but a test started to fail on the 5.x branch when this PR got merged. I have to revert it. Please, create a new PR with these changes and fix that broken test.

https://github.com/mautic/mautic/pull/13902

**Pull request merged**
