### PR TITLE
Resolving Hubspot Mapping Error

### PR DESCRIPTION
**Pull request by onairmarc**
This PR implements the fix discussed in this Mautic Community Forum Thread: https://forum.mautic.org/t/hubspot-mapping-error/25711

### CODE REVIEW

**Comment by onairmarc** [comment]
@RCheesley This is the PR that replaces the PR on 4.x. Please let me know if you need anything else from me.

**Review by RCheesley — APPROVED** [review]
This worked perfectly for me, I was able to set up the HubSpot plugin and switch between the different tabs, which I can't do with the current mautic/mautic 4.4.4 release.

I also set up the Salesforce integration to make sure that the pagination still worked there, and it does!

Thanks @onairmarc for making the PR! 

🚀

**Comment by RCheesley** [comment]
@onairmarc if you have the capacity can you create this on the 5.x branch as well (just an exact duplicate of this PR), so that it makes it into both the 4.4.5 and the 5.0 alpha release? Should be quick to test and merge hopefully as it's super easy to test! Thanks so much! 🚀

**Comment by onairmarc** [comment]
Sure thing! I'll have time this evening to do this.

**Comment by onairmarc** [comment]
@RCheesley PR #11761 submitted for Mautic 5.x

**Review by biozshock — APPROVED** [review]
Confirm this works. Did the same but for all affected places in #11760

**Comment by RCheesley** [comment]
The file causing a reduction in coverage is not related to this PR so going to go ahead and merge.

**Pull request merged**
