### PR TITLE
Added character counter and information text to sms new form

### PR DESCRIPTION
**Pull request by ArnaudSau**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ no]
| New feature/enhancement? (use the a.x branch)      | [ yes]
| Deprecations?                          | [ no]
| BC breaks? (use the c.x branch)        | [ no]
| Automated tests included?              | [ no] 
| Related user documentation PR URL      | https://github.com/mautic/mautic-documentation/pull/257
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Considering the fact that sms are limited to 160 characters.
I added a counter and an information notice  to the sms creation form to inform the users on how many characters they are currently using.

#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2. Create a new sms
3. Type something in the textaera 
4. See that counter increases
5. See that the information box is present under the textaera

image

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10514"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
Really nice feature @ArnaudSau - thanks for making the PR and welcome to the Mautic Community! 🎉 🚀 

Would you be up for adding some screenshots to the end-user documentation about this? I think maybe we could add a screenshot on this page: https://docs.mautic.org/en/channels/marketing-messages/sms.

Also as a side note, 

> on how many characters he is currently using.

Could you try in the future to use terms which are not gendered, such as 'they are', rather than 'he is' or 'she is'? Thanks!

@cla-bot check

**Comment by npracht** [comment]
I don't think we need a screenshot of the counter in doc. This is a bit useless in terms of feature documentation. But you are right, I added the mention of this character count so people can be aware of the "limit" by reading the documentation.
https://github.com/mautic/mautic-documentation/pull/257

**Review by escopecz — APPROVED** [review]
The code looks good 👍

**Review by npracht — APPROVED** [review]
Okay this works great 👍🏽 
Nice for the user, focusing on UI/UX is always good :)

**Comment by RCheesley** [comment]
@all-contributors please add @ArnaudSau for code

**Pull request merged**
