### PR TITLE
Fix send email to contact If send email to user action do not choose user

### PR DESCRIPTION
**Pull request by julienWebmecanik**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.3
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no

#### Description:
When creating a form with "send email to user" action without choose user, then email is send to contact

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. create a form
3. add send email to user action
4. Choose email but don't choose use
5. Submit form and check you as contact receive email
6. After PR you have to choose user in Send email to user action

### CODE REVIEW

**Comment by RCheesley** [comment]
@julienWebmecanik @npracht as we aren't going to be making any further releases in the 3.x series, will you be rebasing this for Features? I noticed that it was changed from Features to 3.3, not sure why! :)

**Comment by julienWebmecanik** [comment]
@RCheesley Yeah I'll do that this week

**Comment by RCheesley** [comment]
Awesome, thanks @julienWebmecanik !

**Comment by kuzmany** [comment]
@julienWebmecanik this require rebase

**Comment by julienWebmecanik** [comment]
@kuzmany @RCheesley This should be ok now ?

**Comment by kuzmany** [comment]
No:( You can see files what are not related to this PRs 
https://github.com/mautic/mautic/pull/10101/files
You can try rebase, sometimes it make crazy. If not work, create new PR

**Comment by julienWebmecanik** [comment]
I'll just create a new PR then.

**Comment by julienWebmecanik** [comment]
I close this PR, new PR is https://github.com/mautic/mautic/pull/10243.

**Pull request closed without merging**
