### PR TITLE
Hide tooltips on keydown and wait for a user to stop typing.

### LINKED ISSUE #9505: Tooltips dont go away
## Bug Description
Tooltips in campaign builder seem to appear and never go away in some instances. A refresh will clear them but they usually come back fairly quickly while editing. Happens because I like to use my keyboard more than my mouse I guess. Tooltips will persist throughout mautic unless you refresh the page. Dashboard, configuration page, etc you name it they stay.

| Q   | A
| --- | ---
| Mautic version | 3.2.1
| PHP version | 7.3.24
| Browser | Chrome 87.0.4280.88

### Steps to reproduce
1. Create/Open a campaign
2. Launch Builder
3. Click "Select" to create an action
4. Hover mouse over last one on the list
5. Without moving mouse, type "tag" and hit enter
6. Hit cancel on modal or create
7. See tooltips on the screen.

Screen Shot 2020-12-16 at 10 47 03 AM

Screen Shot 2020-12-16 at 10 51 40 AM

### Log errors

JS console error

Uncaught TypeError: Cannot read property 'off' of null
    at libraries.js?v3b271e09:1606
    at HTMLDivElement.complete (libraries.js?v3b271e09:1551)
    at HTMLDivElement.fn (libraries.js?v3b271e09:444)
    at HTMLDivElement.handle (libraries.js?v3b271e09:1031)
    at HTMLDivElement.dispatch (libraries.js?v3b271e09:465)
    at HTMLDivElement.elemData.handle (libraries.js?v3b271e09:451)
    at Object.trigger (libraries.js?v3b271e09:682)
    at HTMLDivElement.<anonymous> (libraries.js?v3b271e09:688)
    at Function.each (libraries.js?v3b271e09:153)
    at jQuery.fn.init.each (libraries.js?v3b271e09:144)
(anonymous) @ libraries.js?v3b271e09:1606
complete @ libraries.js?v3b271e09:1551
fn @ libraries.js?v3b271e09:444
handle @ libraries.js?v3b271e09:1031
dispatch @ libraries.js?v3b271e09:465
elemData.handle @ libraries.js?v3b271e09:451
trigger @ libraries.js?v3b271e09:682
(anonymous) @ libraries.js?v3b271e09:688
each @ libraries.js?v3b271e09:153
each @ libraries.js?v3b271e09:144
trigger @ libraries.js?v3b271e09:688
callback @ libraries.js?v3b271e09:1026
setTimeout (async)
$.fn.emulateTransitionEnd @ libraries.js?v3b271e09:1027
Tooltip.hide @ libraries.js?v3b271e09:1555
Tooltip.destroy @ libraries.js?v3b271e09:1606
(anonymous) @ libraries.js?v3b271e09:1617
each @ libraries.js?v3b271e09:153
each @ libraries.js?v3b271e09:144
Plugin @ libraries.js?v3b271e09:1612
(anonymous) @ app.js?v3b271e09:409
each @ libraries.js?v3b271e09:153
each @ libraries.js?v3b271e09:144
Mautic.campaignBuilderUpdateEventListTooltips @ app.js?v3b271e09:409
(anonymous) @ app.js?v3b271e09:407
dispatch @ libraries.js?v3b271e09:465
elemData.handle @ libraries.js?v3b271e09:451

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/95233265-tooltips-dont-go-away?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by biozshock**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ x ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Issue(s) addressed                     | Fixes #9505 

#### Description:

When a user starts typing the action name the javscript was simultaneously creating and removing tooltips and select items.
The PR contains 2 fixes:
1. Avoid removing tooltip twice
2. Wait for the select to complete items processing when the user types faster than the code (approx 50ms per letter)

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Regenerate production assets if you are in prod env. `bin/console mautic:assets:generate`
3. Go to the campaign and create couple of items. 
4. For the test is better to use Actions, as they have more items in it. So add a node, press "select" in "Actions" popup, then do not move the mouse and quickly type `ta` or `tag`.
5. There are no tooltips leftover.

Video of reproducer: 
https://user-images.githubusercontent.com/169384/183074954-eb7e3245-c2a2-4188-8b80-592f24b02860.mp4

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11383"></a>

### CODE REVIEW

**Review by RCheesley — APPROVED** [review]
Thanks for the PR @biozshock - hurrah for finally getting to the bottom of this very annoying bug!

Confirmed with mautic/mautic that the tooltip get stuck and the error reported is showing in the console:

screenshot-nimbusweb me-2022 08 08-14_29_18

No problems with the patch applied - the tooltips do not get stuck and all seems to be working as expected!

Thanks so much @biozshock 🥳

**Review by jos0405 — APPROVED** [review]
It does work as expected.
In my version, I got these numbers and weird designations for the campaign step names, but I think it's irrelevant.

image

**Comment by RCheesley** [comment]
> In my version, I got these numbers and weird designations for the campaign step names,

I think this happens if you do not give the step a name, until you save. On saving it calls it the default action.

**Comment by escopecz** [comment]
@jos0405 @RCheesley the hash is there when using the dev environment (index_dev.php) and is there for debugging. It uses the actual event names on production. I know it is confusing and can/should be changed. But it's not related to this PR.

**Review by escopecz — APPROVED** [review]
I see no problem in the code. Thanks you for this! It was bugging us all for way too long. 👍

**Comment by RCheesley** [comment]
Super useful to know that @escopecz - learn something new every day!

**Pull request merged**
