### PR TITLE
Fix ajax lookup and company repository

### LINKED ISSUE #8101: Create New company option disapear if you enter letters in the company field in contact edit page
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When you create a contact, if you enter some letter to search for a company in the company field and then you erase what you type. the select option "Create New" disapear from the field. 

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 
| Browser | Chrome

### Steps to reproduce
1. Create a new contact and stay on the edit page
image
2. Clic on the company field and see the "Create new" option
image
3. In the edit page enter some letters in the company field
image
4. Erase what you just enter without validating with enter
5. Clic again in the field > you see the "Create New" option but if you click it it just vanished and do nothing

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by kuzmany**
closes https://github.com/mautic/mautic/issues/8101
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/8101
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
While I worked on this bug https://github.com/mautic/mautic/issues/8101 I noticed few bugs. This PR fixed it

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a new contact and stay on the edit page
image
2. Clic on the company field and see the "Create new" option
image
3. In the edit page enter some letters in the company field
image
4. Erase what you just enter without validating with enter
5. Click again in the field > you see the "Create New" option but if you click it it just vanished and do nothing

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. If not use dev mode, then require regenerate assets `php app/console mautic:assets:generate` (mautibox use dev mode)
3. Try if search working properly

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Review by florentpetitjean — DISMISSED** [review]
Tested and works fine. 
Thanks !

**Review by florentpetitjean — DISMISSED** [review]
Last commit works fine for company and doesn't broke search in campaign !

Thanks

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebased

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@kuzmany could you rebase this PR against 3.1 so that we can trigger the code coverage report? I'd like to see if we can get this into 3.1.2 if possible.

**Comment by kuzmany** [comment]
@RCheesley rebased

**Review by RCheesley — DISMISSED** [review]
Thanks for the PR @kuzmany ! Tested in 3.2.5 and indeed I got the error and the following is in the console:

```
libraries.js?vf045fc24:1906 Uncaught TypeError: Cannot set property 'selected' of undefined
    at Chosen.result_select (libraries.js?vf045fc24:1906)
    at Chosen.search_results_mouseup (libraries.js?vf045fc24:1901)
    at HTMLUListElement.<anonymous> (libraries.js?vf045fc24:1886)
    at HTMLUListElement.dispatch (libraries.js?vf045fc24:465)
    at HTMLUListElement.elemData.handle (libraries.js?vf045fc24:451)
```

After the PR I was able to create the company and it worked great - no errors! :tada:

**Comment by RCheesley** [comment]
Rebasing to get an accurate code coverage report!

**Comment by RCheesley** [comment]
@mautic/core-team I need some guidance here, the Codecov report is including files not relating to this PR, despite the fact that it has been rebased. It was previously flagged as having insufficient coverage and I am not sure that anything has been done to address that yet. If someone could take a look it would be great.

**Comment by escopecz** [comment]
@kuzmany did I understand correctly that we can close this one as https://github.com/mautic/mautic/pull/11457#issuecomment-1242049375 fixes the same issue?

**Comment by kuzmany** [comment]
Close favor to https://github.com/mautic/mautic/pull/13869

**Pull request closed without merging**
