### PR TITLE
Fix entity lookup type

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.3
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
We noticed issue with lookup type If use two different lookup type from same model. This cause issue in segment email translations

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create segment email (must be segment)
3. Create second segment email as translation and set Is a translation of  email create in step 
4. After save see **Is a translation** of  is empty
image
5. With this PR works properly

### CODE REVIEW

**Review by RCheesley — DISMISSED** [review]
Tested before applying and was unable to have the translation stay selected.

After applying the PR I was able to save and it retained the translated setting, and testing a send can confirm that the translated version was correctly sent to contacts who had that set in their contact profile.

Thanks @kuzmany ! 🚀

**Comment by tejasync** [comment]
I have tested this PR and works as expected, ready-to-commit label can be added.
There was a test case missing, which I have added.
Requesting @RCheesley for a review.

**Comment by RCheesley** [comment]
Bumping this to the 4.0 beta release as it is based on the Features branch. Thanks for adding the test @ts-navghane !

**Comment by RCheesley** [comment]
Updating the branch to re-run tests then we should be GTG 🚀

**Comment by RCheesley** [comment]
Uh oh ... seems like we have a failing test @kuzmany @ts-navghane https://github.com/mautic/mautic/pull/9653/checks?check_run_id=2438422003#step:9:69

**Comment by kuzmany** [comment]
@RCheesley fixed

**Review by RCheesley — APPROVED** [review]

**Pull request merged**
