### PR TITLE
Add the upload_dir to the DDEV config

### LINKED ISSUE #12244: DDEV needs upload_dir set
### Mautic Version

5.0.x series

### PHP version

8

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When starting DDEV locally on a Mac, the following message is shown:

> You have mutagen enabled and your 'php' project type doesn't have an upload_dir set. 
> For faster startup and less disk usage,
> set upload_dir to where your user-generated files are stored. 

This relates to: https://ddev.readthedocs.io/en/latest/users/install/performance/#filesystem-performance

We should add the upload_dir to the DDEV config.

Adding this here as a good first issue for someone to pick up and make a PR from!

### How can we reproduce this issue?

Step 1: On a mac, clone the repo and cd into the directory
Step 2: (assuming you have Docker/Colima and DDEV set up) type ddev start and you will see the warning notice.

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/121828522-ddev-needs-upload_dir-set?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nox1134**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #12244 ... 

#### Description:
When starting DDEV locally on a Mac, the following message is shown:

> You have mutagen enabled and your 'php' project type doesn't have an upload_dir set.
> For faster startup and less disk usage, set upload_dir to where your user-generated files are stored.
Screenshot 2024-03-13 at 11 58 46 PM

This PR addresses the warning message by adding the necessary `upload_dir` directives to the `config.yaml` file. It specifies the locations of user-uploaded materials (`media/files` and `media/images`).
Screenshot 2024-03-14 at 12 03 55 AM

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Start DDEV locally on a Mac. Run `ddev start`
3. Verify that the warning message regarding the missing upload directory no longer appears.
4. Ensure that the specified upload directories (`media/files` and `media/images`) function as expected.

### CODE REVIEW

**Review by RCheesley — APPROVED** [review]
Welcome to the community!

Tested this locally on my Mac and it works great - thanks for the PR!

**Comment by RCheesley** [comment]
@all-contributors please add @nox1134 for code

**Comment by nox1134** [comment]
Hi @RCheesley, thank you! Happy to join the community!

**Review by escopecz — APPROVED** [review]
Let's try to use this 👍

**Pull request merged**
