### PR TITLE
Add no_unused_imports to CS fixer

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR just enable no_unused_imports flag for CS fixer and clean project https://github.com/mautic/mautic/pull/10317/files#diff-25609b42e9159a63238ccf04d7491d663ac6adc34375cd5caaf7ac47a389ba6fR23 
A

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Just browse Mautic if everything works like before

### CODE REVIEW

**Comment by RCheesley** [comment]
@kuzmany is the base up to date? Codecov seems to be a bit wonky.

**Comment by kuzmany** [comment]
@RCheesley should be good now

**Comment by kuzmany** [comment]
@dennisameling @escopecz do you see guys any troubles with the change?

**Review by escopecz — APPROVED** [review]
Love it 👍

**Review by dennisameling — APPROVED** [review]
Nice one!! Thanks @kuzmany 🎉

**Comment by RCheesley** [comment]
@kuzmany is this something we can include in a patch release (as it has been added to the 4.0.1 milestone) or should this be held as an enhancement for 4.1? I'm not completely clear from the description what impact it has on Mautic but it looks like it's an enhancement, and hence should be 4.1.

**Comment by kuzmany** [comment]
@RCheesley this PR impact just code style, but If we postpone it, means need resolve conflicts later again.
I vote merge it in the closest release. But community can decide

**Comment by RCheesley** [comment]
OK, let's get it into the next release then :) Thanks!

**Pull request merged**
