### PR TITLE
#TPROD-329 - migrate UserBundle to twig templates

### PR DESCRIPTION
**Pull request by SalemCode8**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. In the top right corner of the screen, open the "Settings" menu and click "Users".
3. Test every single functionality on this page. Creating/editing/cloning webhooks, filtering, pagination, etc. - all functionality should work exactly like it did before.
4.  In the top right corner of the screen, open the "Settings" menu and click "Roles".
5. Test every single functionality on this page. Creating/editing/cloning webhooks, filtering, pagination, etc. - all functionality should work exactly like it did before.

### CODE REVIEW

**Review by kuzmany — COMMENTED** [review]
Roles permission probably has unclosed html tag. It's broken

image

**Review by RCheesley — CHANGES_REQUESTED** [review]
Same issue as @kuzmany for me - we should be able to click on the left item and the right items change relevant to that bundle, but instead they are all being displayed.

Here is a screencast: https://watch.screencastify.com/v/vTUSlBsC7xFJYpwUr6r2

**Comment by SalemCode8** [comment]
> Same issue as @kuzmany for me - we should be able to click on the left item and the right items change relevant to that bundle, but instead they are all being displayed.
> 
> Here is a screencast: https://watch.screencastify.com/v/vTUSlBsC7xFJYpwUr6r2

Working on the issue

**Review by RCheesley — CHANGES_REQUESTED** [review]
The first thing to catch my eye is that these are not aligned:
screenshot-8080-salemcode8-mautic-xkl2f976lgs ws-eu71 gitpod io-2022 10 18-14_49_37

Functionality wise everything else seems to be working as expected.

**Comment by RCheesley** [comment]
Still an issue on mobile layouts:

screenshot-8080-salemcode8-mautic-kqsyq9jxwbd ws-eu71 gitpod io-2022 10 20-19_31_56 (1)

**Review by volha-pivavarchyk — COMMENTED** [review]
Works well to me as before

**Review by RCheesley — APPROVED** [review]
Good to go - great work @SalemCode8 🚀

**Pull request merged**
