### PR TITLE
Prevent embedding the same image multiple times in an email when image embedding is enabled

### LINKED ISSUE #8995: Same image embedded in email multiple times
## Bug Description
When email is configured to get the images embedded, if the same image is referenced multiple times in the message, it gets added multiple times, even when only one reference will be used.

In function convertEmbedImages in https://github.com/mautic/mautic/blob/staging/app/bundles/EmailBundle/Helper/MailHelper.php we can see that for every match we get this executed:
                    $this->embedImagesReplaces[$match] = $this->message->embed(\Swift_Image::fromPath($match));

When the match is repeated, the key will be overwritten in $this->embedImagesReplaces, but message->embed will still be executed and the same image will be embedded multiple times.

I think before embedding the image you should check if key already exists.

| Q   | A
| --- | ---
| Mautic version | 2.16.0
| PHP version | 7.3
| Browser | N/A

### Steps to reproduce
1. Configure email to embed images in base64.
2. Create an email that references the same image several times.
3. Send the email and review the source code.

### PR DESCRIPTION
**Pull request by ramandi**
To avoid embedding the same image multiple times, as described in https://github.com/mautic/mautic/issues/8995

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.0 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | Fixes #8995

This PR helps to avoid embedding the same image multiple times if it is referenced to more than once in the email.

When email is configured to get the images embedded, if the same image is referenced multiple times in the message, it gets added multiple times, even when only one reference will be used.

In function convertEmbedImages in https://github.com/mautic/mautic/blob/staging/app/bundles/EmailBundle/Helper/MailHelper.php we can see that for every match we get this executed:
$this->embedImagesReplaces[$match] = $this->message->embed(\Swift_Image::fromPath($match));

When the match is repeated, the key will be overwritten in $this->embedImagesReplaces, but message->embed will still be executed and the same image will be embedded multiple times.

I think before embedding the image you should check if key already exists.

## Steps to reproduce

1. Configure email to embed images in base64.
2. Create an email that references the same image several times.
3. Send the email and review the source code. You should see the image being embedded multiple times rather than embedded once and referenced to the same image.

## Steps to test the PR

1. Apply this PR
2. Configure email to embed images in base64.
3. Create an email that references the same image several times.
4. Send the email and review the source code. You should only see the image embedded once, not multiple times, and the image should still work in all the places it is referenced.

**Please ensure you also test that sending emails with multiple images and images being referenced in multiple places is still working with base64 disabled, to ensure that this PR does not have any untoward effects outside these conditions**

### CODE REVIEW

**Comment by ramandi** [comment]
Added a space to comply with coding standard.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@ramandi thanks for making this PR - I have expanded on the description based on what you had included on the issue, so that it's clear for people to know what they should do to test.

**Comment by RCheesley** [comment]
I'm currently blocked from testing this fully due to the bug that is reported in #9069 which is throwing an error with the tracking pixel - so I had to disable the tracking pixel being included in the email in order to test. We need to test that this doesn't impact the tracking pixel as well.

I saw the four embeds of the image per the description, when the PR is applied then it is only embedded once.

https://youtu.be/T7bwkzhnfNg

I would like someone to test this in a live environment if possible, to check that the images do actually load OK as in my localhost they don't generally load in Mailhog.

**Review by kuzmany — DISMISSED** [review]
As author of this part of code https://github.com/mautic/mautic/pull/8600 
this change looks good to me 👍

**Comment by RCheesley** [comment]
@ramandi this has a conflict, would you be able to take a look?

@kuzmany have you tested this thoroughly with and without base64 encoding, with and without tracking pixel embedded? 

I'm very conscious that we have some big issues with these combinations causing all kinds of problems so am a bit twitchy about merging things that related to embedding and encoding without rigorous testing.

**Comment by kuzmany** [comment]
@RCheesley this code is affected just If is base64 encoding disabled. 
I've resolved conflicts and merge with actual staging.

**Review by npracht — APPROVED** [review]
👍

**Pull request merged**
