### PR TITLE
Option to disable assets like PDF from Google and other search engines

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Automated tests included? |
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/252
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

This bugfix/feature has been sponsored by @Webmecanik

[//]: # ( Required: )
#### Description:
PR added new option to disable search bots to crawl assets using the X-Robots-Tag HTTP header (more https://developers.google.com/search/reference/robots_meta_tag#using-the-x-robots-tag-http-header)

image

#### Steps to test this PR:
1. Apply PR
2.  Create local assets (PDF)
3. You can use Fetch as Google for websites https://support.google.com/webmasters/answer/6066468?hl=en for validation header. You should see X-Robots-Tag in header like this:
image
4. Make sure that there will be no tag when the checkbox is turned off.

Another way how to test robots header is in inspection of your browser:

image

### CODE REVIEW

**Comment by kuzmany** [comment]
Label: WIP

**Comment by kuzmany** [comment]
Label: Feature

**Comment by npracht** [comment]
Label: Needs documentation

**Comment by kuzmany** [comment]
Label: WIP

**Comment by kuzmany** [comment]
Label: Ready for test

**Comment by kuzmany** [comment]
Label: Ready To Test

**Comment by kuzmany** [comment]
Label: Feature Request
Label: Ready to test

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by kuzmany** [comment]
Label: Feature Request

**Comment by npracht** [comment]
@justinfortes could we add that as candidate for 2.13.0 ?
Thanks !

**Comment by kuzmany** [comment]
I understand, but in search engine world doesn't exist something like  index my content. Search crawlers index all internet content , and you can just disable crawling or indexing (by robots.txt, by headers)

**Comment by jimspillane** [comment]
Perhaps borrowing from [WordPress Settings](https://codex.wordpress.org/Settings_Reading_Screen), _Discourage search engines from indexing this asset_ and _dissallowIndexing_ for the column.

**Comment by kuzmany** [comment]
@jimspillane I took the language from google search engine help center. But Ok, I replace with your lang, but will see what @alanhartless say :)

**Comment by jimspillane** [comment]
The one from Google works well too.

**Comment by Maxell92** [comment]
Hello @kuzmany,

could you add 1 more step to the "Steps to test this PR" section please?

* Make sure that there will be no tag when the checkbox is turned off.

Everything is working, just to be sure that second tester will look at it. I can edit your description if you want.

Another way how to test robots header is in inspection of your browser:

screen shot 2018-03-22 at 15 13 02

**Comment by javjim-mautic** [comment]
working properly thanks!

**Pull request merged**
