### PR TITLE
Fix relative dates gt

### PR DESCRIPTION
**Pull request by galvani**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | Y
| BC breaks? | Y
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Operators **gte** and **gt** behave the same for *relative* date parameters. 

### Summary of the issue:
Customer tried “Date Last Active, Less than, -3 days” and “Less than or equal, -3 days”, and got the same results.

When Rowland tested in his own account, he said there was a Contact who was last active 3 days ago and they were not added to the Segment using the filter `Date last active` `less than or equal to` `-3 day`
It should include that Contact.
So is the `less than or equal to` filter acting the same as `less than` in regards to DATES?  
Also, how does time of day factor in? 
When you click into that filter to write in `-3 day` the time option does appear

### Expected Results:
When using the `less than` filter with `-3 day` I would expect all Contacts who were last active 4+ days ago to fill the Segment

When using the `less than or equal to` filter with `-3 day` I would expect all Contacts who were last active 3+ days ago to fill the Segment.

### Actual Results:
The same number of Contacts fill both Segments, but more importantly, the `less than or equal to` filter appears to be the same as the `less than` filter, as Contacts who were last active 3 days ago do not filter into the `less than or equal to` Segment, even though they should.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create 4 leads with date *value*, one from 24hrs ago and every of them +24hrs (2019-01-01,2019-01-02...today)
2. Create segment with *value* and set **gt** 2 day ago
3. Create segment with *value* and set **gte** 2 day ago
4. Run them and checj; they have same number of leads, it should be 2

#### Steps to test this PR:
1. Load up this PR
2. Rerun segments and verify the amount differ. It should be 1 and 2.

#### List backwards compatibility breaks:

This changes the behaviour of segments.

### CODE REVIEW

**Comment by dennisameling** [comment]
@galvani 
The tests are failing with the following error:

```
There was 1 error:
1) Mautic\LeadBundle\Tests\Segment\Decorator\Date\RelativeDateFunctionalTest::testRelativeOperators
BadMethodCallException: nelmio/alice should be installed to use this method.
/home/travis/build/mautic/mautic/vendor/liip/functional-test-bundle/Test/WebTestCase.php:549
/home/travis/build/mautic/mautic/app/bundles/LeadBundle/Tests/Segment/Decorator/Date/RelativeDateFunctionalTest.php:132
```

Could it be that `composer.json` also needs to be updated in this PR?

Thanks in advance!

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by npracht** [comment]
Hello @alanhartless could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback, i would very love to merge it in 3.0.1 if still relevant. Thanks !

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by npracht** [comment]
@mautic/acquia-po can someone fix this asap ? Otherwise i'll have to postpone from next release again. Thanks.

**Comment by chazadams** [comment]
> @mautic/acquia-po can someone fix this asap ? Otherwise i'll have to postpone from next release again. Thanks.

Our team is going to be going through the 3.1.2 items on 10/16

**Comment by npracht** [comment]
Closing for lack of feedback.

**Pull request closed without merging**
