### PR TITLE
[UX] Place the tip modal (the one that asks the website to generate preview) more below for Focus Items

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This enhancement optimizes the positioning of the tip modal related to website preview generation. By shifting it further down, it avoids interference with any top-placed navigation bars, respecting the user’s layout choices. This improvement caters to diverse design preferences and ensures a seamless user experience by maintaining clear visibility of all interface elements.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Focus Items
3. Create new
4. Open the builder
5. Select Display a notice
6. Select Bar style
7. Tip will be below

Captura de tela 2024-02-28 125107

### CODE REVIEW

**Review by PatrickJenkner — APPROVED** [review]
Change works and makes sense 👍

**Review by LordRembo — APPROVED** [review]
Great!

**Review by Mike-Dropsolid — APPROVED** [review]

**Comment by escopecz** [comment]
@andersonjeccel could you please also provide screenshots before the change so reviewers could see what it is about?

**Comment by andersonjeccel** [comment]
@escopecz Before:

image

**Pull request merged**
