### PR TITLE
Fix autofill boolean fields

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/6096
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Reported issue https://github.com/mautic/mautic/issues/6096
Noticed wrong value sanitize for boolean fields.
Also fixed for mapping autofill boolean radio/checkbox group.
This PR fixed it

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create 2 boolean custom fields (like below)
image
2. Create a form and add 3 form field
2.1 Add email form field map to email custom field
2.2 Add a radio group form field map to the first boolean custom field previously created.
In the properties tab, click on YES
image
Go on the behavior tab and click on YES to auto fill data
image
2.3 do the same for the second radio group form field
image
3. Create a landing page and add the form inside (with token or automatic copy, it's up to you)
4. Save the LP and open a new session.
5. Fill the form.
6. After filling the form, refresh the page and see that the first boolean field is checked on YES or NO (depends on what you filled).
See that the second boolean field is not checked (even if when you set, you clicked on auto fill data YES)
image
8. Go back in the form edition, change the order of boolean field
First I got the the bool1 and bool2
Now I have bool2 and bool1
image
Go back on the landing page and refresh
See that now bool2 is checked (earlier it was bool1) and the other one is not checked.
image

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Check If checkbox group/radio groups works properly for boolean type and autofill

### CODE REVIEW

**Comment by npracht** [comment]
@johbuch please test and confirm it works or not.

**Comment by npracht** [comment]
Using in production environment.

**Comment by AlbanL74fr** [comment]
@kuzmany At "step 4 : Save the LP and open a new session."
I tried logout from Mautibox and reload the LP (I already submitted the form) but no form field would pre-fill again. Did I miss something?
Open new session part is not really clear, IMO

**Comment by kuzmany** [comment]
@AlbanL74fr 
You need send form from not-logged Mautic. 
Then you submission will be related to lead ID

**Comment by AlbanL74fr** [comment]
All right @kuzmany Then it worked perfectly! Thanks. Should I click "Add your review" and "Approve" ?

**Comment by kuzmany** [comment]
@AlbanL74fr yes, you should add approve to pr 
Thank you for your tests

**Comment by AlbanL74fr** [comment]
@kuzmany Already tested and approved

**Pull request merged**
