### PR TITLE
Fix regex in `PageSubscriber.php` [backport to 4.4 of #12385]

### PR DESCRIPTION
**Pull request by putzwasser**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

The regex in `onPageDisplay()` for the `onPageDisplay_bodyOpen` event for outputting the `bodyOpenScripts` is faulty and won't catch all possible scenarios.

See this regex tester with real world scenarios (and sources):
https://regex101.com/r/fXmrq6/1

See that this fix fixes this:
https://regex101.com/r/W7bwDL/3

**Additional Ressources**
- https://www.rexegg.com/regex-style.html#contrast
- https://www.rexegg.com/regex-style.html#lazy_warning
- https://www.rexegg.com/regex-quantifiers.html#negclass_solution

5.x PR: https://github.com/mautic/mautic/pull/12385

### CODE REVIEW

**Comment by putzwasser** [comment]
PR for 5.x branch #12385

**Comment by RCheesley** [comment]
Hi @putzwasser and welcome to the community!

Appreciate you taking the time to make the PR for 4.4.x and 5.x, thank you!

Would you mind adding a description for testers (who most likely are not developers) so that they can understand how to reproduce the issue that is caused by this bug, and then what to expect when the PR is applied to demonstrate that it is resolved? This will ensure that we can get the PR tested and reviewed in good time.

**Comment by putzwasser** [comment]
@RCheesley Thanks for the welcoming.

I can't, actually. I just saw that the regex must be incorrect and checked it with the regex tester.

I'd give instructions on how to create and reproduce the error, but I have no idea how and when Mautic will add content automatically.

Mautic is a bit confusing here... It has the `{{ outputScripts('bodyOpen') }}`, `{{ outputScripts('bodyClose') }}`, `{{ outputHeadDeclarations() }}` statements in the template, but also adds scripts/tags hard coded. Unfortunately, there's little to no documentation on that.
I already asked in the slack channel, but I got no answer.

OTOH I included regex examples and links, which discuss/explain the matter (more abstract). So any developer should comprehend the changes.

If someone would explain Mautic's different mechanics of amending a page layout to me, I'd be happy to include an example.

**Comment by RCheesley** [comment]
@mabumusa1 any chance you can assist with this PR and the 5.x version https://github.com/mautic/mautic/pull/12385? We need unit tests but also test instructions so that it can be properly reviewed and tested.

**Review by galvani — APPROVED** [review]
makes sense

**Comment by RCheesley** [comment]
Closing this as we're not merging any new changes for the 4.x releases now and there's a 5.x branch PR available. Thanks @putzwasser and sorry we didn't get to merge it in the 4 release series.

**Pull request closed without merging**
