### PR TITLE
Fix download asset from form  action

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

The PR bring regression https://github.com/mautic/mautic/pull/11043

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Add form with assets download action
3. Submit form and see asset not start download
4. After PR it should start download like before

### CODE REVIEW

**Review by volha-pivavarchyk — APPROVED** [review]
Thanks @kuzmany. This works well. The bug has been fixed

**Comment by volha-pivavarchyk** [comment]
I have tried to reproduce the bug on the branch 4.4 again. I haven't been able to do that. 

image

**Comment by escopecz** [comment]
@volha-pivavarchyk I'm a bit confused from the 2 comments. Are you saying there was no bug in the first place?

**Comment by kuzmany** [comment]
It does not work. Also that PR https://github.com/mautic/mautic/pull/11043 bring another regression, then we had to decided revert it from production. 

```
We offer ICS files in their emails to save the event to a certain calendar.


But they are not opening in a correct way. It’s showing as plain text. They’ve been doing this for a long time and it worked well but now it doesn’t anymore.
```

We need add allowed file types for stream opening by default (images, pdf....)

**Comment by volha-pivavarchyk** [comment]
@escopecz When I tested it the first time, everything went smoothly. When I tried to do it again I couldn't reproduce the bug on the branch 4.4. It is just information. 

If @kuzmany was getting the bug, that's the way it is. The current branch works well. I think it is good changes.

**Review by escopecz — APPROVED** [review]
Thanks Zdeno! 👍

**Pull request merged**
