### PR TITLE
Add condition on tags in campaign

### PR DESCRIPTION
**Pull request by chandon**
Please answer the following questions. 

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #2088, https://github.com/mautic/mautic/issues/1293, https://github.com/mautic/mautic/issues/1089
| BC breaks? | N
| Deprecations? | N

**Note that all new features should have a related user and/or developer documentation PR in their respective repositories.** 

#### Description:

Contact field condition in campaign can now filter on **Tag** presence. To do so, use the Equals or Not Equals operator for the condition. The condition test only presence for 1 tag (space separator has no logic, if you type "tag1 tag2" as value, it'll not look for presence of tag1 AND tag2 but for the presence of a single tag named "tag1 tag2")

#### Steps to test this PR:
1. Create a campaign
2. Add a Contact field condiction
3. Select the Tag field
4. Select the Equals or Not Equals operator
5. Type a tag label as value
6. Add contacts to the campaign with ou without the tag

### CODE REVIEW

**Comment by chandon** [comment]
Replace #2095 has it was not the good way to do it

**Comment by escopecz** [comment]
A documentation PR is now required for every new feature request to keep the new features well documented. Please, create one at https://github.com/mautic/documentation and add the link to the table above.

**Comment by MxyzptlkFishStix** [comment]
+1 For multiple tag option in the near future.

**Comment by dongilbert** [comment]
This has merge conflicts that need to be resolved, as well as documentation added before it can be merged. 

I tested the functionality though, and it works. Thanks for this :) +1

**Comment by alanhartless** [comment]
@chandon Did you mean to close this PR or did it happen by accident when the branch was deleted?

**Comment by Mazzim** [comment]
I would love to see this implemented. Waiting for 'has tags' condition in campaigns for long time. Shame it never got merged :(

**Comment by that0n3guy** [comment]
Me too, almost a year :) (see https://github.com/mautic/mautic/issues/1293)

**Comment by chandon** [comment]
@alanhartless i deleted the branch because to many conflict. I did another specific branch, but it mixes other changes that where not accepted (and also in conflict with my original branch...).

So feel free to start from https://github.com/mautic/mautic/pull/2106/commits/eb4815da9e87f2dc5e43c25963aaf9d60bac36ac and to solve conflicts with the actual version of mautic...

**Comment by amagdy3** [comment]
Was there any progress with this or was it replaced by another?

**Comment by escopecz** [comment]
Replaced by https://github.com/mautic/mautic/pull/2479

**Pull request closed without merging**
