### PR TITLE
DPMMA-2831 Unsubscribe from all in preferences center

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🟢 
| Related user documentation PR URL      | https://github.com/mautic/user-documentation/pull/332
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description
When the preference center is activated, there is no option for users to unsubscribe from all marketing messages. This PR allows users to set the "Do Not Contact" flag by clicking a link in the subscription center.
image

Additionally, a new token is available to use in emails: `{dnc_url}`, so you can create an email footer like this:
image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Activate Preferences center Mautic settings
3. Send email to user with `unsubscribe_url` and `dnc_url`:
 ```
 Manage your <a href="{unsubscribe_url}">email preferences</a> or <a href="{dnc_url}">unsubscribe from all marketing messages</a>⁠⁠⁠⁠⁠⁠⁠.
 ```
4. Open the email and click the email preferences link.
5. Click the "Unsubscribe from all marketing messages" link in the preferences center.
6. Check if the contact is unsubscribed.
7. Click the resubscribe link.
8. Check if the contact is resubscribed.
9. Click the direct unsubscribe link in the email.
10. Check if the contact is unsubscribed.

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for the PR @patrykgruszka!

**Review by tomekkowalczyk — APPROVED** [review]
Hi, I tested the changes and everything looks ok.

**Review by andersonjeccel — APPROVED** [review]
Works as expected

image

image

image

**Review by escopecz — APPROVED** [review]
I see no problem in the code. Thanks!

I think the new token should be mentioned somewhere in the documentation though. Perhaps here?

https://github.com/mautic/user-documentation/blob/5.x/docs/channels/emails.rst?plain=1#L279

**Comment by patrykgruszka** [comment]
@escopecz good idea, here are the docs: https://github.com/mautic/user-documentation/pull/332

**Comment by RCheesley** [comment]
Just re-running the failed job, it was a failure to upload to Codecov so it should be green once this is complete and then we can merge.

**Pull request merged**
