### PR TITLE
Merge 4.3.0-beta into 5.x

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

**I am working on symfony mailer and messenger, there are some failing tests that got solved inside 4.x branch, so I created this PR to merge these changes.**

I compared all the files one by one but I had the following issues: 

I need to regenerate these assets 
```
both modified:   app/assets/scaffold/files/package-lock.json
	both modified:   media/js/app.js
	both modified:   plugins/GrapesJsBuilderBundle/Assets/library/js/dist/builder.js
	both modified:   plugins/GrapesJsBuilderBundle/Assets/library/js/dist/builder.js.map
```

In the file `app/bundles/LeadBundle/Model/LeadModel.php` there is 
```use Tightenco\Collect\Support\Collection;```

This is causing the system to break because it has been referenced twice, so I removed it

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11183"></a>

### CODE REVIEW

**Review by escopecz — CHANGES_REQUESTED** [review]
@mabumusa1 thanks for taking care of this! Please re-request review again once the CI checks are green. Let me know if you need any help.

**Comment by mabumusa1** [comment]
> @mabumusa1 thanks for taking care of this! Please re-request review again once the CI checks are green. Let me know if you need any help.

Thanks, @escopecz I need your help with two checks `scaffolded files mismatch` and `PHPStan baseline`. they are failing for no obvious reason

**Comment by RCheesley** [comment]
@mabumusa1 the scaffold check is reporting that there is a mismatch between the following files, which should be identical:

> Files ./package-lock.json and app/assets/scaffold/files/package-lock.json differ

So I would compare the two and verify against the 4.x branch what the correct settings should be.

**Comment by escopecz** [comment]
@mabumusa1 I just find out that there are unresolved conflicts committed to this PR. I'm a bit worried that other conflicts could be problematic too. Do you have some background to that?
Screen Shot 2022-05-25 at 15 06 32

**Comment by escopecz** [comment]
Closing in favore of https://github.com/mautic/mautic/pull/11211

**Pull request closed without merging**
