### PR TITLE
Beginnings of Twig Support in Custom Themes

### PR DESCRIPTION
**Pull request by dongilbert**
**Ready to Merge**

I'm still writing up the documentation, but that will be added to the doc repo, not here with the code. 

For a preview of the documentation, see https://github.com/dongilbert/mautic/wiki/Converting-PHP-Templates-to-Twig

**Testing**

- Check out this PR, then clear your application cache.
- Create a new landing page with the Mauve Theme
- Use builder to ensure all areas are editable and save properly
- View landing page in frontend
- Create a new email with the Mauve Theme
- Use builder to ensure all areas are editable and save properly
- Preview email on frontend
- Test converting the coffee theme config.php to json by using the `app/console mautic:theme:json-config --theme=coffee` command from the command line.

### CODE REVIEW

**Comment by alanhartless** [comment]
I tested everything I could think of with this and all seemed OK. :+1:

**Comment by dongilbert** [comment]
The latest PR adds in support to convert PHP template configs over to JSON in order to facilitate the migration to Twig.

**Comment by escopecz** [comment]
I tested landing pages with Mautic theme, emails, forms, unsubscriptions. I didn't found any problem. Coffee theme works as well. If I didn't forget to test something, I say :+1:

**Comment by dongilbert** [comment]
One thing to test that you may have skipped since I didn't put test instructions here is the `app/console mautic:theme:json-config` command

**Comment by escopecz** [comment]
command `app/console mautic:theme:json-config --theme coffee` deleted _themes/coffee/config.php_ and created _themes/coffee/config.json with basically same content. It transferred PHP array to JSON object. I guess that's what it should do.

**Comment by alanhartless** [comment]
:+1:

**Pull request merged**
