### PR TITLE
Fix focus campaign action - add local cache to tracking helper

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

This PR prevent waiting for update session If campaign action is executed after page visits. 
Tracking helper in first step try check local cache, then check in session.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1.  Create campaign with Page visits decision and after Focus action

image

2. The action is not executed every time. It's little tricky test it, but If I run this campaign on production I have few Focus fired, even all action are executed. Just check focus stats and it's not same (focus stats are lower) like campaign action triggered stats. 

#### Steps to test this PR:
1.  Repeat same camapign
2.  Focus should fire every time

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/6723"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
FYI Session storage won't work on new browsers. We have replaced it with a cache storage instead on our fork of Mautic, but it uses https://github.com/mautic/mautic/pull/7522 so we cannot create the PRs till that Cache Bundle is merged.

**Comment by escopecz** [comment]
@kuzmany there is also a conflict.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by npracht** [comment]
Hello @kuzmany could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback, i would very love to merge it in 3.0.1 if still relevant. Thanks !

**Comment by kuzmany** [comment]
@npracht based on john comments, this PR need rework based on new Cache Bundle https://github.com/mautic/mautic/pull/8817

**Comment by kuzmany** [comment]
@alanhartless  @escopecz can you describe more what is wrong with session now?
The same logic use FB and GA pixel support https://github.com/mautic/mautic/pull/4573 - that means doesn't work at M3?

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@kuzmany given the comments above and the fact that this PR is going to need to be refactored to use the new cache bundle which won't be making its way in until 3.2 at the earliest, I'm going to put this PR against 3.2.1 for now.

**Comment by dennisameling** [comment]
Hi @kuzmany! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since this PR has conflicts now, could you please do a `git merge upstream/features` locally to resolve the conflicts? Thanks in advance!

**Comment by RCheesley** [comment]
Hi @kuzmany this is quite an old PR now and from the comments above it needs reworking to use the new caching bundle. Is it still relevant to keep this PR open or would you prefer to start a fresh one?

**Comment by kuzmany** [comment]
@RCheesley but I removed session dependency, then not need cache support. The only limitation is you cannot use relative timing, because it's triggered directly after page visits decision. But it works and still it's relevant

**Comment by RCheesley** [comment]
OK great, thanks for the update!

**Review by jos0405 — DISMISSED** [review]
Amazing PR, works as expected!

Hardcoded:
image

Campaign driven:
image

Result:
image

**Comment by escopecz** [comment]
@kuzmany could you please rebase to 4.x. It's targeting 4.2 but when I switch to 4.x then another 50 commits are added, so changed it back so you can see the right commits. Please update the target branch once you rebase.

**Comment by kuzmany** [comment]
rebased

**Comment by escopecz** [comment]
@kuzmany I'm looking closely at the code changes; you are replacing session storage with just in-memory storage. So it used to remember data across request and now it will remember it only during 1 request.

I'm wondering how can this work? The storage in the TrackingHelper is being updated by a cron job when campaign events are being triggered and then it's accessed in the PageBundle's PublicController. It cannot technically remember the data with the changes you made.

**Comment by ghost** [comment]
In this state, should the tag pending-test-confirmation be removed? Actually the test at this state is not possible, or am I misunderstanding last comment?

**Comment by RCheesley** [comment]
Given the lack of response since 2022, I'm going to close this PR. If you want to re-open it in the future, please ping us. It will need to be rebased.

**Pull request closed without merging**
