### PR TITLE
Fix timezone on timeline

### LINKED ISSUE #10892: contact record event timestamps weird
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

A contact record that came in through an API push from Calendly via Zapier shows a "Contact Created" date of "Today at 8:37 pm" yet has a Contact Identified date of "Yesterday, 8:37 pm"

image

### How can we reproduce this issue?

Not exactly sure how to go about recreating this issue. I will keep a watch on future contact creations via the API and see if this happens again.

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 4.0
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     |  Fixes #10892

#### Description:
We got on timeline this 

image

You can see  contact created event as today, but others events happen yesterday. 
This issue was with reset timezone to UTC in  toUtcString method of DateTimehelper.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. This is hard to reproduce, I saw it on one instance and fixed it.
3. Just code review in this case should be enough

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10375"></a>

### CODE REVIEW

**Review by alexhammerschmied — DISMISSED** [review]
Yes it works. I had exactly this problem at one of my machines. This solved it. 
Thanks a lot! :)

**Review by volha-pivavarchyk — DISMISSED** [review]
Works well. I know what the problem was. Looks good.

**Comment by RCheesley** [comment]
@kuzmany please rebase the branch so that this could be merged! Once we have a code review this will be good to go as we have two good tests!

**Comment by kuzmany** [comment]
@RCheesley rebased

**Comment by RCheesley** [comment]
Good to go then :)

**Pull request merged**
