### PR TITLE
Enable video attributes in Froala

### PR DESCRIPTION
**Pull request by escopecz**
Please answer the following questions. 

| Q | A |
| --- | --- |
| Bug fix? | Y |
| New feature? | N |
| Related user documentation PR URL | / |
| Related developer documentation PR URL | / |
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/pull/2032#issuecomment-238078698 |
| BC breaks? | N |
| Deprecations? | N |
#### Description:

Some video HTML attributes get stripped by Froala.
#### Steps to test this PR:
1. Apply this PR
2. Refresh production assets
3. Refresh browser 
4. Repeat the test.
5. The attributes should stay there
#### Steps to reproduce the bug:
1. Try to save this as DWC content:

```
<div class="videoWrapper">
    <iframe src="https://player.vimeo.com/video/XXXXXXXXX?byline=0&amp;portrait=0&amp;badge=0" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
</div>
```

Notice that `frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen` attributes are stripped.

### CODE REVIEW

**Comment by Mazzim** [comment]
Works for me, thank you!

**Comment by mqueme** [comment]
this worked in the Landing page for me but not in dynamic content

**Comment by escopecz** [comment]
@mqueme, was the whole code stripped or just the attributes for you? Because the editor at DWC maybe doesn't save the code edited via the code view, but that's another issue. If you

1. Switch the editor to the code view
2. Paste the code snippet from the PR description
3. Switch back to wysiwyg
4. Save

Does the code stay there?

**Comment by Mazzim** [comment]
On Staging brach in Dynamic Content when I paste the code snipped to test the PR and switch back to wysywig and then back into code I see this:

`<div class="videoWrapper"><span class="fr-gatedvideo fr-dvi fr-draggable" contenteditable="false" style=""><iframe src="https://player.vimeo.com/video/177374667?byline=0&amp;portrait=0&amp;badge=0" width="100%" height="100%"></iframe></span></div>`

It gets transformed into a Gated video code. This explains why my test video stopped showing up in my DWC tests recently...

**Comment by Mazzim** [comment]
I checked it with Landing Pages, same thing happens. The test code snippet gets transformed into a gated video content. Froala wraps the  `<iframe>` tag inside `<span class="fr-gatedvideo fr-dvi fr-draggable" contenteditable="false" style="">`
I think it shouldn't work like this, shouldn't it?

**Comment by dongilbert** [comment]
@mazzim - that is correct. It should not. Gated Video should only support `<video>` tags.

**Comment by dongilbert** [comment]
+1

**Pull request merged**
