### PR TITLE
Editor improvements

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**

The HTML parser we use strips out comments, cdata tags, and if conditional blocks breaking layouts for some custom landing pages.  This PR preserves those.

It also adds a file manager icon to the full page editor to allow upload of custom css and JS files.  

Finally it adds the version to the asset files to ensure the browser is always using the latest after an upgrade.

**Testing**
Create a new landing page with custom html.  Edit the source and add something like

```
<![CDATA[ hello ]]> 
<!-- my comment -->
<!--[if IE]>
I'm IE
<![endif]-->
```

After saving and viewing the source again, those should remain intact.

The filemanager icon is a folder between the image and table icons.  Click on it, the filemanager should open.  Upload a file and ensure it only allows images, css, and JS files.  Select a file and the filemanager window should close and a dialog appears with the URL.  Ideally it would be nice to auto copy but that requires flash and browser restriction work arounds so figured the dialog is the next best thing.  Didn't want to auto paste into the editor since the CSS/JS files are likely to be inserted in the source head tags and not the body.

### CODE REVIEW

**Comment by escopecz** [comment]
I can confirm the code is the same. It only adds the code to `<body/>` tag and changes new lines. That is OK I guess. I was able to upload JS, CSS and images via the new editor icon. :+1:

**Comment by dbhurley** [comment]
+1 works for me.

**Comment by ehillerbrand** [comment]
@alanhartless @escopecz   Is this the bug fix for the HTML EDitor Outlook problem:  https://www.mautic.org/community/index.php//1013-html-email-bug-for-outlook/0

**Comment by escopecz** [comment]
I don't have Outlook or any other Microsoft software so I can't tell.

**Pull request merged**
