### PR TITLE
Feature - Add custom_args for Sendgrid API

### LINKED ISSUE #10688: "Custom headers" not working when send mail through "SendGrid API"
Hello! 

### Mautic Version

4.1.0 - upgraed from docker 4.0

### PHP version

7.4.25

I have a bug report and a few questions about Mautic.

# Bug Report

I was trying to set X-FOOBAR header to configuring some options but this field is not being sent. 
image
This customer-header is supposed to be included when I sent e-mails via the contact "Send Mail"

And these headers set on the Advanced on Campaign
image
(Name/From/Reply To/Plain text version is working)

Header `list-unsubscribe` **is also absent** on the sent mails via SendGrid API.

When I configured to use either "Sendgrid - SMTP" or "Other SMTP Server" [SSL+Login] the custom headers and list-unsubscribe is working.

image

# Questions to the community/developers

1. Which is the driver is the recommended way to send mail via Mautic ?
I was reading other issues, and I think that each driver behavior a little different (rate-limits, etc).
Is there any reason Mautic implemented sendgrid/amazon via SDK/API instead of SMTP? Is it faster than using SMTP?
Should I setup postfix/MTA to queue the emails from Mautic?

2. Why Custom-Header from settings are only send on system emails?
In settings, it explains where custom-headers are sent: ```...This includes password reset emails, emails to Mautic users, form post results, directly composed email to contacts, etc. If custom headers are required for an Email (used in campaigns or broadcasts), set customer headers in the Advanced tab of the Email.```
 **Why was this designed like that? Shouldn't the headers at least be copied when new Email Campaigns are added (like the "Mailer is owner" setting is)?**
As a system-admin I don't want to let mautic's users to control which custom-header he add or remove in each email (or at least, to not remove the ones set by the system-admin)
If anyone know the reason "Mautic Email" was removed from settings custom-header, and if I can open an PR to include a new boolean setting (eg: 'always-keep-custom-header') to make those headers always be sent on the all emails.
Is this the 'right' way to tackle this problem? Do I need to really need to change core to implement this, or the plugin is the right approach?
If a new setting okay, can it just exists on the settings.php file and not added in the web?

3. If manage to fix the Mautic to include headers, can I just open an PR this repo?
I'm not full time PHP developer, so I'm not used to the culture and tools. 
I managed include extra headers (hardcoded) using this file:
https://github.com/mautic/mautic/blob/4.x/app/bundles/EmailBundle/Swiftmailer/SendGrid/Mail/SendGridMailMetadata.php#L23
Is this ./app/bundles/ something I could send PR to mautic or is another repository?

**Thank you for reading until here**

### How can we reproduce this issue?

Step 1: Use "SendGrid API" as MTA
Step 2: Configure Custom Header, either on the Settings or in the Email Campaign
Step 3: If using Settings Custom-Headers, send an e-mail via "Send Mail" contact
Step 3: If using Settings Email Campaign, send an e-mail via "Email Campaign" to an segment, configuring the Custom-Header in the "Advanced" area.

### Relevant log output

_No response_

### Code of Conduct

- [x] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/108499011-custom-headers-not-working-when-send-mail-through-sendgrid-api?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by renatocron**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix?           | Not really
| New feature/enhancement?       | Yes
| Deprecations?                          | No
| BC breaks? (use the c.x branch)        | No
| Automated tests included?              | TODO (waiting for tests results)
| Related user documentation PR URL      | I cloned to add, but "Configuration" is not documented anywhere (e-mail settings are only cited on 03.Setup, but I dint change anything there). The messages.ini contains some explanation of this field for the user.

#### Description:

This feature enables system-admins to set custom_args to be set on all emails sent by Sendgrid API transport.

This can be configured on the Email Settings page.

#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2. Make sure to use SendGrid API and not Sendgrid SMTP as a transport method in *Mautic Configuration* -> *Email* => on *Mail Send Settings* set "Service to send mail through" as SendGrid API image
2. Still in the configuration page, add some key/value in the field "Custom Arguments"
3. Start ngrok or tool to monitor Sendgrid Webhook request
4. Set up sendgrid webhook to your address (Login to https://app.sendgrid.net => on left menu, *Mail Settings* -> *Mail Settings* => *Event Webhook* => type your webserver hook URL, select some all events or at least the "processed" event and click save.
5. Create an contact with e-amil field, send an e-mail via contact page or email campaign
6. Watch ngrok/webserver for the callback, the request should include the setup Custom Arguments set on step 2 image

**This code is backward compatible** and do not change the current behavior if not configured, even if the `mailer_transport_custom_args` is missing from `app/config/local.php`, it only appears after configuration is saved.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10691"></a>

This feature somewhat make useless the "always-keep-custom-header" setting I commented on #10688  

If you are curious, use case is more described better in https://github.com/AppCivico/sendgrid-fanout#why

### CODE REVIEW

**Comment by renatocron** [comment]
@npracht I added the type hints, but I'm not sure if I should use 

```* @var array<int,string>``` 
or 
```* @var array<string,string>```

The workflow is awaiting approval for running again

**Comment by renatocron** [comment]
I tried one work-arround to use X-SMTPAPI header (using email type=other smtp) but then, the page /mailer/sendgrid_api/callback returns 404

**Comment by leooxx** [comment]
Hello,

Is it the solution for the "ip_pool_name" parameter in the api ?

"ip_pool_name" is a group of ip in sendgrid. Use to separate marketing email and transactionnal email sending.
It's really important in marketing ...

Thank you,
Léo

**Comment by renatocron** [comment]
@leooxx It's not, I don't see in the docs who to set the IPs via custom_args (this is only for the API version).
The mautic sendgrid client api may support that, but I could not find how to use it (the version is this https://codeload.github.com/sendgrid/php-http-client/legacy.zip/7880d5aecc53856802130ba83af1dfcf942e9767 ) the code is not really good at documentation 

however, you can set it via X-SMTPAPI header, 
https://docs.sendgrid.com/for-developers/sending-email/building-an-x-smtpapi-header#ip-pools

for the header to work, you can wait for 4.2.2 release next monday, or apply this patch to your mautic: https://github.com/mautic/mautic/pull/10831 


About my comment on /mailer/sendgrid_api/callback returning 404, that's because when sendgrid SMPT is choose, you need to use https://[YOUR MAUTIC DOMAIN]/mailer/sendgrid/callback as stated here https://github.com/mautic/mautic/issues/10978#issuecomment-1082038193

**Comment by escopecz** [comment]
It would be nice to show this only when the Sendgrid option is selected. Take a look at https://github.com/mautic/mautic/blob/4.x/app/bundles/EmailBundle/Form/Type/ConfigType.php#L375. It would be even better if the transport service wasn't hard-coded in the ConfigType class but instead each transport could implement a `CustomArgsInterface` and if so then the custom args field would show up when the transport is selected in the UI.

Regarding the tests, testing new form fields is the easiest with functional tests like https://github.com/mautic/mautic/blob/4.x/app/bundles/CoreBundle/Tests/Unit/Form/Type/ConfigTypeTest.php#L49

And to test that the transport sends the correct data you'll have to mock the HTTP client service. Let me know if you'll need some help.

**Comment by escopecz** [comment]
I'll close and open this PR hoping the CI will kick in.

**Comment by escopecz** [comment]
Oops, I cannot reopen it as the source repository was deleted. @renatocron can you apply the changes onto your repository and create new PR?

**Pull request closed without merging**
