### PR TITLE
Email Preheader

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [y]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [n]
| Automated tests included?              | [ y] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | 

#### Description:

This is cherry-picked from this community PR, so follow the description and steps to test there: https://github.com/mautic/mautic/pull/9659

I also tested that contact tokens work in the preheader:
Screenshot 2024-04-04 at 18 02 11

Test that the preheader is added when sending through various places:
- Direct to contact on the contact detail page
- Test email from the email detail page
- campaigns
- segments

This PR also fixes the "send email to contact" form accessible in the contact detail page. There are several options that change the behavior like:
- When filling in the From and From Name fields, the email will be send from those values, not those in the global configuration.
- When you select a template email that have other From and From Name values and do not fill them in the form, it should use those. So there are several layers of values that can be overwritten. Same for the subject and preheader.

### CODE REVIEW

**Review by RCheesley — CHANGES_REQUESTED** [review]
I like having a separate field for the preheader, it makes a lot of sense.

I think we need to update the themes as well though, otherwise it isn't actually being used correctly, I don't think? It would cause confusion to have something in the preview already in the email template, IMO.

screenshot-mautic ddev site-2024 05 29-15_38_19
screenshot-mautic ddev site-2024 05 29-15_37_37
screenshot-mautic ddev site_8026-2024 05 29-15_39_26

**Review by kuzmany — COMMENTED** [review]
I did basic tests and seems works to me.

**Review by kuzmany — DISMISSED** [review]

**Comment by escopecz** [comment]
Thank you both for testing. I actually found that this requires https://github.com/mautic/mautic/pull/13528 to be prepared and merged first so I jumped there but also didn't finish due to other priorities. I'll let you know when I finish with both.

**Comment by escopecz** [comment]
https://github.com/mautic/mautic/pull/13528 is ready for review if anyone wants to unblock this feature PR

**Comment by escopecz** [comment]
This PR is now blocked by https://github.com/mautic/mautic/pull/13983

**Comment by escopecz** [comment]
This PR is finally ready for tests.

@RCheesley the MJML tag can be adjusted in some other PR. If it's editable in the code only, perhaps we should remove it from the core templates?

**Review by fedys — APPROVED** [review]
Good job! Thanks @escopecz!

**Review by kuzmany — APPROVED** [review]
Seems good to me 👍

**Pull request merged**
