### PR TITLE
Fix Most hit email redirects dashboard widget

### LINKED ISSUE #8424: Widget "Most hit email redirect" not working
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Hello, I can't make the widget : "Most hit email redirect" works. I tried all 3 filters but I always got a blank widget (also not working without filters) : 
image
Is it a real bug or did I miss something in the configuration (try segments or campaign with real clicks in it)
Thanks

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 
| Browser | Chrome

### Steps to reproduce
1. Do to the Dashboard
2. Open the widget menu 
image
3. Add the "Most hit email redirect" widget
4. Set some filter with email that got clicked in it
image

5. See that the widget stay blank.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/8424
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR fix https://github.com/mautic/mautic/issues/8424

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Do to the Dashboard
2. Open the widget menu 
image
3. Add the "Most hit email redirect" widget
4. Set some filter with email that got clicked in it
image

5. See that the widget stay blank.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. See your widget works now properly

### CODE REVIEW

**Review by npracht — DISMISSED** [review]
works now

**Comment by npracht** [comment]
Seeing the code changed and knowing it is relevant in M2, i think we can merge it in 2.16.2 @dennisameling

**Review by dennisameling — COMMENTED** [review]
Can confirm this leads to an empty table:
image

... but even after applying this PR, the table is still empty:

image

... the redirect is tracked though:

image

@kuzmany any clue why it's not working? This is my setup:

image

Also, the file that you applied the fix for also has `$segmentId` and `$campaignId` in there, is there a reason you didn't change those and only `$companyId`?

Thanks in advance

**Comment by kuzmany** [comment]
@dennisameling campaign filter is setup correctly? Try remove it.
In this PR I just gettype of segmentId and campaignId- null type and companyId was string type. This is reason why changed condition to empty

**Comment by kuzmany** [comment]
Rebased for 3.x and test.

@dennisameling I've noticed date range for dashboard was not provide properly.
Date To was "dateTo 00:00:00", last commit fixed it to "dateTo 23:59:59"
Now should works properly

**Review by npracht — COMMENTED** [review]
👍

**Review by RCheesley — APPROVED** [review]
Confirmed empty widget before applying PR, and data shows after applying:

screenshot-local mauticacceptancetests-2020 06 23-17_53_02

**Pull request merged**
