### PR TITLE
Reuse existing editor keep history 2

### LINKED ISSUE #10895: grapesjs edit source uses previous email
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

create 2 channel emails as mjml.

open first. uilder. select edit code. mod. exit, save and close.
re-open 2nd. builder. edit code. it has the mjml of the first one. the save+cancel buttons are now broken.

4.2-rc1

### How can we reproduce this issue?

create 2 channel emails as mjml.

open first. uilder. select edit code. mod. exit, save and close.
re-open 2nd. builder. edit code. it has the mjml of the first one. the save+cancel buttons are now broken.

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/108497529-grapesjs-edit-source-uses-previous-email?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by adiux**
Replaces https://github.com/mautic/mautic/pull/10781 which had some unrelated commits.

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | yes
| Deprecations?                          |  no
| BC breaks? (use the c.x branch)        |  no
| Automated tests included?              |  no
| Related user documentation PR URL      |  N/A
| Related developer documentation PR URL | 
| Issue(s) addressed                     |  https://github.com/mautic/plugin-grapesjs-builder/pull/91, not a reported issue: code in the editor does not update, related to: https://github.com/mautic/mautic/pull/10707 Fixes #10895 

#### Description:

While working on https://github.com/mautic/mautic/pull/10707 we realized that we have another problem with the editor content not being refreshed when the editor is reopened. This PR fixes that. 

Along with that, it creates new possibilities:
- Make the Grapesjs editor available in the global `Mautic.builder` property
- Keep the editor "around" when closed. This has the advantage that e.g. the history (undo) is still available after closing and reopening it.
- Faster load times
- New configuration possibilities. See the README in the preset (maybe check the companion PR).

#### Steps to test this PR:

1. Open this PR on Gitpod or pull-down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a new email and open it in the builder
3. Open the code mode. Make sure the HTML is from the theme selected
4. Close the modal and the builder
5. Select another theme
6. Open the builder and the code editor
7. Make sure the HTML is from the newly selected theme (used to be the first one)
8. In addition make sure the correct panel is opened on the right-hand side: the blocks selector, not e.g. the Style Manager or a blank panel

This PR relies on the code in the preset:
https://github.com/mautic/grapesjs-preset-mautic/pull/25/

Once this code works the preset PR should be code reviewed and merged too.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10847"></a>

### CODE REVIEW

**Comment by kuzmany** [comment]
Based on origin PR https://github.com/mautic/mautic/pull/10781 I marked it as pending test confirmation. 
Note to myself: I will check it and then go to ready to commit

**Comment by adiux** [comment]
I just found a problem. When the builder is closed and the email is saved, the builder can not be reopened again. 
image

In fact, the old builder is loaded partly:
image

@kuzmany, maybe you have some insights on why this could be? My guess is that something from the saving functionality restores parts of the old builder. So I assume this is somewhere in this file:
app/bundles/CoreBundle/Assets/js/4.builder.js

**Comment by kuzmany** [comment]
@adiux I don't have idea. I think this is critical, then we cannot merge it to 4.2, right?

**Comment by adiux** [comment]
@kuzmany yes, we should wait. When is the closing date for 4.2?

**Comment by kuzmany** [comment]
Today

**Comment by RCheesley** [comment]
@adiux did you manage to get any further with this PR?

**Comment by adiux** [comment]
@RCheesley I'm working on it. But I could not figure it out until now. It always breaks the opening of the editor or the opening of the code editor. I try to commit some more time this weekend.

**Comment by RCheesley** [comment]
Hi @adiux did you manage to make any progress with this? It looks like it is blocking #10902 and #11324 so would be good to get it wrapped up! What can we help with to get it over the line?

**Comment by adiux** [comment]
this PR is partly replaced by: https://github.com/mautic/mautic/pull/11376

**Comment by RCheesley** [comment]
@adiux should we close this PR then, or will there still be some useful parts of it that should be considered?

**Comment by adiux** [comment]
closing this. I will open a new one for the reusing of the history.

**Comment by adiux** [comment]
closing this. I will open a new one for the reusing of the history.

**Comment by Ilona-Sot** [comment]
@adiux @RCheesley - this error is a big problem for us. Are you going to continue working on the bug fix? Has a new PR already been created?

**Comment by RCheesley** [comment]
> closing this. I will open a new one for the reusing of the history.

@adiux did you get around to creating the new PR for this?

**Comment by adiux** [comment]
@RCheesley not for the keeping of the history. That was a side benefit. I would not worry about that for now.

**Pull request closed without merging**
