### PR TITLE
Fix #1564: Missing owner_id

### LINKED ISSUE #1564: "Mail is owner" not working in campaigns
## Description

Email sent from Campaigns is not sending from the Lead Owner, but instead sending from the default sender.

## Steps to Reproduce

1.) Create a Smart List
2.) Create new Leads, assign the Lead a Lead Owner and assign the Lead to the Smart List
3.) Create a Template Email for use in a campaign
4.) Create a Campaign adding the Smart List as the lead source and the Template Email as the first scheduled action to take palce at a specific date and time
5.) Publish the Campaign

Emails sent from the above campaign are not sending from the lead owner.

### PR DESCRIPTION
**Pull request by PatchRanger**
| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | n
| Related user documentation PR URL | n
| Related developer documentation PR URL | n
| Issues addressed (#s or URLs) | #1564 
| BC breaks? | n
| Deprecations? | n

#### Description:
Fix #1564 . The bug was due to missing `owner_id` parameter.
I am not sure I've found the best way to fix the bug.
May be it's better to extend profile fields with `owner_id` (as there were other issues about missing `owner_id` through out of the admin UI (eg, #897 )).
Or we could change the signature of `EmailModel::sendEmail` passing in (as 2nd parameter) an array of `Lead` instead of an array of arrays. Personally I would prefer passing into the function an object rather than an array - because an array is too generous while an object is a kind of contract, which guarantees a set of parameters, some interface and gives auto-completion feature to IDE.

### CODE REVIEW

**Comment by npracht** [comment]
Hi, this is great. this feature is core for a H2H relation. But as you mention in the issue 897, if the feature is not available everywhere (especially in campaign builder), it's easy to use, the only ways to use the feature is:
* Via manual edit of the contact
* Via contact import (all at once with the same owner)

N.

**Comment by PatchRanger** [comment]
@npracht You're right, for now this feature can't rely on campaign workflow, because there is no way to set Owner via campaign. So it is more a workaround rather than real fix. I guess, we should get feedback from Mautic developer team.
@dongilbert What is the best way to address the issue? Should we extend profile with `owner_id`? Please keep in mind #897.

**Comment by escopecz** [comment]
The fix works for me :+1:

**Comment by alanhartless** [comment]
+1

**Pull request merged**
