### PR TITLE
Add readme files

### PR DESCRIPTION
**Pull request by RCheesley**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✅ 
| New feature/enhancement? (use the a.x branch)      | 
| Deprecations?                          | 
| BC breaks? (use the c.x branch)        | 
| Automated tests included?              |  
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

Now that the Git Split is working, we need to have a change to the files in the directory, I think, to push the 13 new simple template themes over to their respective repos. Attract and Creative already worked because I made changes to the files _and_ added the git split stuff at the same time.

This PR adds readmes in all the repos (which I forgot to do before), simple change but hopefully it'll then trigger the full push over to the repositories and we'll be cookin on gas, as the saying goes!

a-cartoon-character-is-holding-a-can-of-lysol-spray

---
### 📋 Steps to test this PR:

Please do code review, check for any typos or errors in file names or references. Thanks in advance!

### CODE REVIEW

**Review by matbcvo — APPROVED** [review]

**Review by matbcvo — CHANGES_REQUESTED** [review]
One theme is missing - `_survey`, please create `README.md` for this theme.

**Review by andersonjeccel — CHANGES_REQUESTED** [review]
Also checked here, same issue reported before: survey is missing

**Comment by RCheesley** [comment]
Thanks folks, looks like I missed it in all the force-add manual commands! Just pushed it now.

**Review by matbcvo — APPROVED** [review]
Looks good to me

**Review by andersonjeccel — APPROVED** [review]
yep

**Pull request merged**
