### PR TITLE
M3 : Report email stats enhacement

### LINKED ISSUE #7331: bug with report email and graphic
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
With the report data source "email", if you add the graphic (the only one), it causes a bug when you save. 
Then you report is saved but you can't see it because you get 

| Q   | A
| --- | ---
| Mautic version | 2.15
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create a report and "email" as data source
image
2. Add some column
3. Go on the graphic tab and add the only one graphic
image
4. Save and see that you get a 500 error
image

### Log errors
here is the log from the 500 error
```
[2019-03-15 14:19:40] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT SUM(DISTINCT e.sent_count) as sent_count, SUM(DISTINCT e.read_count) as read_count, count(CASE WHEN dnc.id  and dnc.reason = 1 THEN 1 ELSE null END) as unsubscribed, count(CASE WHEN dnc.id  and dnc.reason = 2 THEN 1 ELSE null END) as bounced FROM emails e LEFT JOIN emails vp ON vp.id = e.variant_parent_id LEFT JOIN categories c ON c.id = e.category_id INNER JOIN (SELECT SUM(IF(donot.reason = 1,1, 0)) as unsubscribed, SUM(IF(donot.reason = 2,1, 0)) as bounced, donot.channel_id as channel_id FROM lead_donotcontact donot WHERE (donot.date_added BETWEEN ? AND ?) AND (donot.channel='email') GROUP BY donot.channel_id) dnc ON e.id = dnc.channel_id INNER JOIN (SELECT COUNT(es.email_id) as sent_count, SUM(es.is_read) as read_count, es.email_id as email_id FROM email_stats es WHERE es.date_sent BETWEEN ? AND ? GROUP BY es.email_id) stats ON e.id = stats.email_id INNER JOIN (SELECT COUNT(ph.id) as hits, COUNT(DISTINCT ph.lead_id) as unique_hits, ph.email_id as email_id FROM page_hits ph WHERE (ph.date_hit BETWEEN ? AND ?) AND (ph.email_id IS NOT NULL) GROUP BY ph.email_id) hits ON e.id = hits.email_id' with params ["2018-06-18 22:00:00", "2019-03-15 13:19:40", "2018-06-18 22:00:00", "2019-03-15 13:19:40", "2018-06-18 22:00:00", "2019-03-15 13:19:40"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dnc.id' in 'field list'" at /home/XXXXX/XXXXXXXXX.com/2-15-4-atmt/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT SUM(DISTINCT e.sent_count) as sent_count, SUM(DISTINCT e.read_count) as read_count, count(CASE WHEN dnc.id  and dnc.reason = 1 THEN 1 ELSE null END) as unsubscribed, count(CASE WHEN dnc.id  and dnc.reason = 2 THEN 1 ELSE null END) as bounced FROM emails e LEFT JOIN emails vp ON vp.id = e.variant_parent_id LEFT JOIN categories c ON c.id = e.category_id INNER JOIN (SELECT SUM(IF(donot.reason = 1,1, 0)) as unsubscribed, SUM(IF(donot.reason = 2,1, 0)) as bounced, donot.channel_id as channel_id FROM lead_donotcontact donot WHERE (donot.date_added BETWEEN ? AND ?) AND (donot.channel='email') GROUP BY donot.channel_id) dnc ON e.id = dnc.channel_id INNER JOIN (SELECT COUNT(es.email_id) as sent_count, SUM(es.is_read) as read_count, es.email_id as email_id FROM email_stats es WHERE es.date_sent BETWEEN ? AND ? GROUP BY es.email_id) stats ON e.id = stats.email_id INNER JOIN (SELECT COUNT(ph.id) as hits, COUNT(DISTINCT ph.lead_id) as unique_hits, ph.email_id as email_id FROM page_hits ph WHERE (ph.date_hit BETWEEN ? AND ?) AND (ph.email_id IS NOT NULL) GROUP BY ph.email_id) hits ON e.id = hits.email_id' with params [\"2018-06-18 22:00:00\", \"2019-03-15 13:19:40\", \"2018-06-18 22:00:00\", \"2019-03-15 13:19:40\", \"2018-06-18 22:00:00\", \"2019-03-15 13:19:40\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'dnc.id' in 'field list' at /home/XXXXX/XXXXX.com/2-15-4-atmt/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dnc.id' in 'field list' at /home/XXXXX/XXXXX.com/2-15-4-atmt/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dnc.id' in 'field list' at /home/XXXXX/XXXXX.com/2-15-4-atmt/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []
```
[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/71437964-bug-with-report-email-and-graphic?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mohit-rocks**
closes https://github.com/mautic/mautic/issues/7331
This PR is rebase of https://github.com/mautic/mautic/pull/7214 for 3.x

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR change logic to generate email stats (Data Source: Email).

Before update the emails are listed with date_added limit and numbers (sent, read, unsubscribed) are loaded global for all period. This a lot of users make confused.

Now

- If Hide date range is enabled - the dater range filter don't apply https://github.com/mautic/mautic/pull/7214/files#diff-5295a31f5d6a0e3c5ab1b7d4bc36f45dR373 . Thats what we expect, If I don't see date range forms, then date range cannot be apply to query.

- Data Source: Email - with date range now loaded emails active from date range and related stats (unsubscribed, ratio, read etc). That means If choose range last month, then I will see just emails and stats to that related month.

With enabled **Hide date range SQL** use the global dat from **emails table** (sent_count, read_count ...)
With disabling **Hide date range** SQL query create **inner JOIN** to other huge tables (page_hits, email_stats..) with date range limit. This prevents to load the large table more times.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:

1. Load up this PR (m3.mautibox.com) or load to you local environment with stats
2. Just retest both cases
3. If Hide date range is enabled/disabled

#### List deprecations along with the new alternative:
1. 
2. 

#### List backward compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by RCheesley** [comment]
Bumping to 3.2 due to test coverage issues and lack of testing.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@mohit-rocks looks like you have some conflicts to address here!

**Comment by dennisameling** [comment]
Hi @mohit-rocks! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since this PR has conflicts now, could you please do a `git merge upstream/features` locally to resolve the conflicts? Thanks in advance!

**Comment by mabumusa1** [comment]
Reopening to include in M5

**Comment by patrykgruszka** [comment]
This PR looks similar to #10767. Do you know which of these will be continued?

**Comment by jos0405** [comment]
@mabumusa1 @mohit-rocks @kuzmany is this the same as https://github.com/mautic/mautic/pull/10767 ?
Can you plz resolve the conflicts in this one or the other one if we would keep that so we can test it and move ahead?

**Comment by kuzmany** [comment]
Close favor to https://github.com/mautic/mautic/pull/10767

**Pull request closed without merging**
