### PR TITLE
Fix Preferance Center Javascript issue

### LINKED ISSUE #9268: Javascript Errors on Preference Center
In the preference center, when clicking on the 'Contact me Though Email' checkbox results in a javascript error:

`Uncaught TypeError: Cannot set property 'disabled' of null`

When clicking on save, this leads to a 500 error.  Clicking save without checking the checkbox does not result in an error.

Mautic 3.1.1
PHP Version 7.2.24-0ubuntu0.18.04.6

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | Yes
| New feature/enhancement? (use the a.x branch)      | No
| Deprecations?                          | No
| BC breaks? (use the c.x branch)        | No
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #9268

#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2. Activate preference center.
3. There will be no error log in javascript console, when changing checkboxes

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for making the PR @mabumusa1 - the code coverage seems to suggest that this PR needs to be rebased, perhaps? It is showing files which don't relate to this PR.

**Comment by mabumusa1** [comment]
> Thanks for making the PR @mabumusa1 - the code coverage seems to suggest that this PR needs to be rebased, perhaps? It is showing files which don't relate to this PR.

Thanks, @RCheesley, this PR changes a `js` file only, which is not included in the coverage report. I think this PR is good to be tested

**Comment by RCheesley** [comment]
Hopefully test coverage should pass now, there was a problem with the 4.0 branch after the last release.

**Review by kuzmany — APPROVED** [review]
Good catch!
Works 👍

**Review by escopecz — APPROVED** [review]
👍

**Pull request merged**
