### PR TITLE
Adding an option to hide themes

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ❌ 
| New feature/enhancement? (use the a.x branch)      | ✅ 
| Deprecations?                          | ❌ 
| BC breaks? (use the c.x branch)        | ✅ 
| Automated tests included?              | ✅  
| Related user documentation PR URL      | https://github.com/mautic/user-documentation/pull/303
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | /

#### Description:

Give user option to hide/unhide 'default' themes in the themes list page
Screenshot 2024-05-06 at 12 15 31
Screenshot 2024-05-06 at 12 15 40
Screenshot 2024-05-06 at 12 15 55

 Do no show these hidden themes in the Email/Page theme list
Update existing themes using migration

#### Steps to test this PR:

MAUT-10202:
1. Go to themes, check if 'Hide' option is visible for the default themes only
2. On click of 'Hide' option in the dropdown, confirmation popup appears.
3. On confirmation, theme is moved to the bottom of the theme list and is disabled (shown in grey font) and theme is hidden from email/page theme list and also in the 
5. Hidden themes will have 'Unhide' menu option, on clicking confirmation popup opens, on confirming theme will unhide and will be visible in the previous order and also visible in the email/page theme list
6. We have added a migration to rename deleted.txt with hidden-themes.txt and remove custom theme names from the file which are present in the instance's `public_html/themes` directory.

MAUT-10140:
1. There is no option to delete default themes anymore (this is now changed to Hide/Unhide)
2. Custom themes can be deleted, these won't be added to deleted.txt (deleted.txt has been renamed to hidden-themes.txt)
3. Saving custom themes with already existing names will generate error for e.g. Template name `abc` already exists.
4. Since, saving a theme is prefixed with 'beefree-' by default, if we try to save a befree theme without the 'beefree-' keyword, will generate error for e.g. If we try to save them with name `fall-in-love-with-this-seasons-collection` will generate - beefree-fall-in-love-with-this-seasons-collection is the default theme and therefore cannot be overwritten.

### CODE REVIEW

**Comment by RCheesley** [comment]
A couple of questions:

1. You mention default themes, can users also apply this to their own custom themes?
2. Could we update to use the new icon pack (ri-eye-off-line was suggested in [this comment](https://github.com/mautic/mautic/pull/13539#pullrequestreview-2011950165))
3. Can we have some user/developer docs please 😺

**Comment by escopecz** [comment]
Good questions
1. It doesn't make sense for custom themes as those can be easily removed. The default ones cannot and that's why the show/hide feature is needed.
2. I updated it in https://github.com/mautic/mautic/pull/13723/commits/3a20c42daac96cca15418c047f786fe03ddf0882 and I also had to change the icon from preview otherwise the eye icon would be used for preview as well as for unhide options. This is how it looks like now:
Screenshot 2024-05-07 at 16 11 01
Screenshot 2024-05-07 at 16 10 55
3. There is nothing needed for developer docs. It's a new column in the database. Nothing developers can set in the theme itself. Here is the user doc change: https://github.com/mautic/user-documentation/pull/303

**Review by andersonjeccel — APPROVED** [review]
From the UX perspective, that's a nice addition!

**Review by shinde-rahul — APPROVED** [review]
LGTM!!

Thanks @escopecz for having this feature in core.

**Review by kuzmany — CHANGES_REQUESTED** [review]
On add/edit langing page I got error:

```
 500 Internal Server Error - Key "visibility" for array with keys "name, key, config, dir, themesLocalDir" does not exist. 
 
 /html/app/bundles/CoreBundle/Resources/views/Helper/theme_select.html.twig:37 at
```

Other parts seems work properly.

**Comment by escopecz** [comment]
@kuzmany I couldn't reproduce but I [fixed it](https://github.com/mautic/mautic/pull/13723/commits/8872a9b5a225a870560326042160bffd39399944) based on the error message you provided.

I also noticed that the CSS class was added to libraries.css and not to any less file. [So I fixed that too](https://github.com/mautic/mautic/pull/13723/commits/5f7ec517ac89b8ece1e33795a09d2906e3e0da73). It's not my code. I'm just pushing it to the community repo, so I'm not that familiar with it.

**Review by Esthertests — APPROVED** [review]
great changes 
image
image
image
Tested the email page and checked that an hidden template is not shown and once unhidden it is shown,
image

**Comment by Esthertests** [comment]
@escopecz can we add a notification panel shown when user unhides a theme

**Review by kuzmany — APPROVED** [review]
Works properly 👍

**Pull request merged**
