### PR TITLE
Changes from PR#10782 rebuilt

### LINKED ISSUE #11290: Dynamic Content block missing in MJML email in GrapesJS builder in Mautic 4.3.x
### Mautic Version

4.3.x series

### PHP version

7.4.9

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

After updating Mautic to 4.3.x, I no longer see the button to add a Dynamic Content block in the GrapesJS mail editor, similar to https://github.com/mautic/mautic/pull/10782#issuecomment-1020121748. In the previous version 4.2.x, the button was visible and I was able to add a block.

### How can we reproduce this issue?

1. Create new or edit an existing MJML e-mail in the Mautic 4.2.x GrapesJS e-mail builder.
2. Add Dynamic Content block.
3. Close builder and save e-mail.
4. Switch Mautic to version 4.3.x, clear application and browser cache.
5. Open the e-mail saved in step 3 and try to add new Dynamic Content block or edit an existing one.

### Relevant log output

```shell
//Browser Console
backbone.js:370 Component type 'dynamic-content' not found {attrs: {…}, options: {…}, level: 'warning'}attrs: {type: 'dynamic-content', tagName: 'mj-text', attributes: {…}, components: {…}}...
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/109790896-dynamic-content-block-missing-in-mjml-email-in-grapesjs-builder-in-mautic-4-3-x?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by annamunk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [Yes ]
| New feature/enhancement? (use the a.x branch)      | [No]
| Deprecations?                          | [No]
| BC breaks? (use the c.x branch)        | [No]
| Automated tests included?              | [No] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #11290

#### Description:

Looks like changes introduced by https://github.com/mautic/mautic/pull/10782 and https://github.com/mautic/grapesjs-preset-mautic/pull/26 were overwritten with next GrapesJsBuilderBundle scripts build. 

In the grapesjs-preset-mautic I added changes to dist files and removed copies, which are no longer udpated and used by other scripts - https://github.com/mautic/grapesjs-preset-mautic/pull/30. Instead, the originals in the relevant subdirectories are used, e.g.
dist/dynamicContent.domcomponents.js - removed 
dist/dynamicContent/dynamicContent.domcomponents.js - in use and updated by `npm run build`

#### Steps to test this PR:

1. With Mautic branch 4.3, 4.4 or 5.x open the file `plugins\GrapesJsBuilderBundle\Assets\library\js\dist\builder.js`
2. Try to find changes introduced by https://github.com/mautic/grapesjs-preset-mautic/pull/26 e.g. `DC: ${dynamicContents.length} components found` (after building and minifying it may look like `DC: ${t.length} components found`). If nothing is found, the scripts with Dynamic Content for the MJML email are missing.
3. Checkout this PR and try to locate the changes again. You should now be able to find the scripts from https://github.com/mautic/grapesjs-preset-mautic/pull/26/files in builder.js

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11319"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for the PR @annamunk - guessing this is something that we are going to have to add more documentation on for developers working with the builder (and folks reviewing the PRs) as something must have gone wrong somewhere along the line!

**Comment by escopecz** [comment]
@annamunk if you want to get this bug fix merged into 4.4.1 then please rebase on branch 4.4. Otherwise this bug fix will be available in Mautic 5.0.0

**Comment by RCheesley** [comment]
Hi @annamunk would you be able to rebase this PR (or make a new one if it is easier) on the 4.4 branch? That way we can get it into one of the upcoming bug fix releases. On the 5.x branch it will have to wait until September at the earliest.

**Review by RCheesley — DISMISSED** [review]
Worked great - the Dynamic Content block is added and I can use it, however I am getting a critical error when I try to send an email using dynamic content - I think that this is happening when it is trying to use the filter. This may not be related to this PR (will create a separate issue) but just flagging that as a result of this, I was not able to actually send the emails to test the dynamic content worked.

```
[2022-07-15 13:07:41] mautic.CRITICAL: Uncaught PHP Exception ErrorException: "PHP Notice - Trying to access array offset on value of type null" at /var/www/html/app/bundles/EmailBundle/EventListener/MatchFilterForLeadTrait.php line 57 {"exception":"[object] (ErrorException(code: 0): PHP Notice - Trying to access array offset on value of type null at /var/www/html/app/bundles/EmailBundle/EventListener/MatchFilterForLeadTrait.php:57)
[stacktrace]
#0 /var/www/html/app/bundles/EmailBundle/EventListener/MatchFilterForLeadTrait.php(57): Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler->handleError(8, 'PHP Notice - Tr...', '/var/www/html/a...', 57, Array)
#1 /var/www/html/app/bundles/EmailBundle/EventListener/TokenSubscriber.php(106): Mautic\\EmailBundle\\EventListener\\TokenSubscriber->matchFilterForLead(Array, Array)
#2 /var/www/html/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(126): Mautic\\EmailBundle\\EventListener\\TokenSubscriber->onTokenReplacement(Object(Mautic\\CoreBundle\\Event\\TokenReplacementEvent), 'mautic.email_to...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#3 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Mautic\\CoreBundle\\Event\\TokenReplacementEvent), 'mautic.email_to...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#4 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'mautic.email_to...', Object(Mautic\\CoreBundle\\Event\\TokenReplacementEvent))
#5 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners(Array, 'mautic.email_to...', Object(Mautic\\CoreBundle\\Event\\TokenReplacementEvent))
#6 /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(168): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch(Object(Mautic\\CoreBundle\\Event\\TokenReplacementEvent), 'mautic.email_to...')
#7 /var/www/html/app/bundles/EmailBundle/EventListener/TokenSubscriber.php(78): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch(Object(Mautic\\CoreBundle\\Event\\TokenReplacementEvent), Object(Mautic\\CoreBundle\\Event\\TokenReplacementEvent))
#8 /var/www/html/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(126): Mautic\\EmailBundle\\EventListener\\TokenSubscriber->decodeTokens(Object(Mautic\\EmailBundle\\Event\\EmailSendEvent), 'mautic.email_on...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#9 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Mautic\\EmailBundle\\Event\\EmailSendEvent), 'mautic.email_on...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#10 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'mautic.email_on...', Object(Mautic\\EmailBundle\\Event\\EmailSendEvent))
#11 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners(Array, 'mautic.email_on...', Object(Mautic\\EmailBundle\\Event\\EmailSendEvent))
#12 /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(168): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch(Object(Mautic\\EmailBundle\\Event\\EmailSendEvent), 'mautic.email_on...')
#13 /var/www/html/app/bundles/EmailBundle/Helper/MailHelper.php(1630): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch(Object(Mautic\\EmailBundle\\Event\\EmailSendEvent), Object(Mautic\\EmailBundle\\Event\\EmailSendEvent))
#14 /var/www/html/app/bundles/EmailBundle/Model/SendEmailToContact.php(419): Mautic\\EmailBundle\\Helper\\MailHelper->dispatchSendEvent()
#15 /var/www/html/app/bundles/EmailBundle/Model/SendEmailToContact.php(222): Mautic\\EmailBundle\\Model\\SendEmailToContact->sendStandardEmail()
#16 /var/www/html/app/bundles/EmailBundle/Model/EmailModel.php(1502): Mautic\\EmailBundle\\Model\\SendEmailToContact->send()
#17 /var/www/html/app/bundles/EmailBundle/Model/EmailModel.php(1133): Mautic\\EmailBundle\\Model\\EmailModel->sendEmail(Object(Mautic\\EmailBundle\\Entity\\Email), Array, Array)
#18 /var/www/html/app/bundles/EmailBundle/Controller/AjaxController.php(59): Mautic\\EmailBundle\\Model\\EmailModel->sendEmailToLists(Object(Mautic\\EmailBundle\\Entity\\Email), Object(Doctrine\\ORM\\PersistentCollection), 90)
#19 /var/www/html/app/bundles/CoreBundle/Controller/AjaxController.php(131): Mautic\\EmailBundle\\Controller\\AjaxController->sendBatchAction(Object(Symfony\\Component\\HttpFoundation\\Request), 'email')
#20 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(158): Mautic\\CoreBundle\\Controller\\AjaxController->executeAjaxAction('sendBatch', Object(Symfony\\Component\\HttpFoundation\\Request), 'email')
#21 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#22 /var/www/html/vendor/symfony/framework-bundle/Controller/ControllerTrait.php(96): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#23 /var/www/html/app/bundles/CoreBundle/Controller/AjaxController.php(109): Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller->forward('MauticEmailBund...', Array)
#24 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(158): Mautic\\CoreBundle\\Controller\\AjaxController->delegateAjaxAction()
#25 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#26 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#27 /var/www/html/app/AppKernel.php(104): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#28 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#29 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#30 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#31 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#32 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#33 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#34 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#35 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#36 {main}
"} {"hostname":"mautic-web","pid":3754}
```

**Comment by RCheesley** [comment]
The above bug is already reported (by me! 🤦 ) https://github.com/mautic/mautic/issues/11202

**Comment by annamunk** [comment]
@RCheesley thank you! I did the rebase on the 4.4 branch and I also encountered error https://github.com/mautic/mautic/issues/11202 while testing Dynamic Content.

**Review by escopecz — APPROVED** [review]
Thanks! 👍

**Pull request merged**
