### PR TITLE
Create FUNDING.yml

### PR DESCRIPTION
**Pull request by RCheesley**
Add a FUNDING.yml file so that we can show ways people can support Mautic across our Github org.

This is a Github admin PR so no testing required.

### CODE REVIEW

**Comment by mabumusa1** [comment]
@RCheesley how can I see the funding section after you added this config? I did not see the part where I can go the funding page on that branch?

**Comment by RCheesley** [comment]
@mabumusa1 info is here: https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

**Comment by RCheesley** [comment]
This is a GH Admin PR so it doesn't really need to be tested - it is a file that should be included as part of the recommended Community Health files. Maybe just double check that the syntax is correct against the link above?

**Comment by mabumusa1** [comment]
@RCheesley that is correct, we need to see the syntax. I used github actions in the past and it used `yaml` files like this one, so we just need to verify that it actually works

**Comment by RCheesley** [comment]
You can see the syntax in the file:

github: mautic
open_collective: mautic 

This comes from: https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository#about-funding-files

**Comment by mabumusa1** [comment]
@RCheesley looks good

**Comment by RCheesley** [comment]
Great!

screenshot-github com-2020 09 18-10_04_41

The setting is enabled it just needs the YAML file for the info.

**Review by mabumusa1 — APPROVED** [review]
Looks good according to Github standards

**Pull request merged**
