### PR TITLE
Fix problem selecting filter in construction of segments/reports/etc by Enter keydown hitting

### PR DESCRIPTION
**Pull request by Noa83**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | No
| Automated tests included? | No
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | No
| Deprecations? | No

[//]: # ( Required: )
#### Description: 
This bug is encountered in many cases in whiches selection by keydown is available to select filters (Segments, Reports, Points, etc...). 
To illustrate the segment's case example, some screenshots:
When you're searching a filter by typing the first letters of it and then try to select it by Enter hitting, the field does not appear correctly (blank instead of text). 

screenshotBug1

If you try to do it once again, the letters you've typed before Enter hitting are now available in the selection.

screenshotBug2

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a new segment
2. Try to add a filter by typing the first letter of the field you want to select and then hit Enter key to select it.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com) or Load up on your mautic (assets generate + cache clear needed)
2. Reproduce the steps above
3. You can now select filter by keydown hitting.

### CODE REVIEW

**Comment by npracht** [comment]
@RCheesley we just added a new commit to fix tag creation on form action and csv import.

## How to test
Before installing the PR, test the 2 issues:
1. Create a form with action "add tag", try to add a new tag and see issue.
2. Import a csv file of contacts. Add a tag (a new one) and see issue.

**Install PR and reproduce.** 🎉

**Comment by npracht** [comment]
While testing the whole 3.0.0-alpha app, I noticed this issue is still existing. I think we should consider adding this PR in 3.X branch.

**Comment by escopecz** [comment]
If there will be another M2.x release then we can merge it to staging and then merge staging to the 3.x branch. If we won't find a release leader for another M2.x release then we can merge this directly to the 3.x branch.

**Comment by npracht** [comment]
I believe with the planning given by Alan that we won't have another 2.x release before 3.0.0 is out !

**Comment by escopecz** [comment]
That may be true. Especially when no one wants to be a release leader for it :)

Another question is if releasing M3.0.0 will automatically sunset M2.x.x. I don't think so as we have to give time to Mautic users to prepare for the migration. But that depends on what the community agrees on and if there is someone willing to support M2 for several more months. The two of us won't figure that out in this thread.

**Comment by kuzmany** [comment]
There are not human resources for maintenance 2.x.x, then we should focus on 3.x.x. 
All current PRs we can step by step rework for 3.x.x if need it.
Or we can release 3.0.0 as public preview for agencies, but 3.1.0 as stable release with bugfixes.
Release leader is time-consuming job. Companies whose earn money from Mautic, could sponsor some activities. That's not possible do it just for fun

Sorry for off-topic, maybe we can move discuss it to forum or slack :)

**Comment by npracht** [comment]
Hi @Noa83  can you check if your PR is mergeable in https://github.com/mautic/mautic/tree/3.x and manage conflicts if needed?
Then we give a chance to the PR to be merged in 3.0.0. Thanks !

**Comment by RCheesley** [comment]
@npracht I noticed this has me assigned as a reviewer, do you still require me to test?

**Comment by npracht** [comment]
Nope ! Already ready to commit :)

**Pull request merged**
