### PR TITLE
multiple domains email batch

### LINKED ISSUE #8813: In case of multiple domains use - batch email sending doesnt use default domain set in config but the current user domain
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
In case of multiple domains set up in the mautic box. 
For example, one for internet (company.net) and one for internal lan access (company.local).
In configuration, set up the default domain to company.net.
SendExampleAction =>work as expected with company.net links. unsubscribe link work.
SendBathAction => doesnt work well, it uses the current domain of the user who launch the batch. company.local. unsubscribe links doesnt work. 

| Q   | A
| --- | ---
| Mautic version | 2.6.2
| PHP version | 7.2
| Browser | Chrome

### Steps to reproduce
1. Configure default domain company.net
2. Access mautic with company.local
3.Send batch email
4.Unsubscribe links use company.local and doesnt work. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by enguerr**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | No
| Automated tests included? | No
| Related user documentation PR URL | No
| Related developer documentation PR URL | No
| Issues addressed (#s or URLs) | fixes #8813 
| BC breaks? | 
| Deprecations? | 

Resolve the issue when sending email from one domain (domain.local) when the default domain is set (domain.com) and all the links point to domain.local.

### CODE REVIEW

**Comment by kuzmany** [comment]
I don't think this is change to core.
You can manage this by another way in plugin.
For example RouterSubscriber like here: https://github.com/mautic/mautic/pull/7193

@dennisameling

**Comment by enguerr** [comment]
This is not related to plugin or specific item but this issue is related to all the things you want to publish (form / landing page / tracking pixel / emails / dynamic content). I tried to find the convergent method between all these features ... and the buildUrl was the one who was called by all of this different bundle (except the UI routing).

Anyway,
i can listen on routes (many routes to listen...) to correct this behaviour as the sample in the link you provided but i think, this is a general issue.
I'm (maybe) not the only user who planned to serve mautic inside the entreprise network (split dns configuration to respect N-tiers archictecture). 

My opinion is : the buildUrl must'nt use the Request object to build the elements production urls but the production defined url (site_url)

My patch may not be very elegant ... but is there  another best way to force site_url globally with the buildUrl function ?
Maybe adding the condition (UI routing vs Url for public item) inside the router class ?
(many changes)

What do you think about ? Maybe i'm missing something ?

This patch is deployed on all the mautic i've deployed and seems to be working as expected...

**Comment by RCheesley** [comment]
@enguerr as we've not had any tests on this I am going to bump it out to 3.2.

You might get more people testing if you could provide more explicit instructions in the PR description to enable people to reproduce the problem that this addresses, and how to test if it resolved the problem.

**Comment by mabumusa1** [comment]
@enguerr I am trying to reproduce the issue you mentioned, I am not sure I am doing correctly, may you please share a step by step guide to reproduce the issue. 

I read the code you added, seems like a valuable addition

**Comment by RCheesley** [comment]
@enguerr if you can please provide test instructions we have folk who are willing to test. If we do not hear from you in the next month we will close the PR as inactive.

**Comment by alanhartless** [comment]
I think https://github.com/mautic/mautic/pull/7193 was supposed to have fixed this as well unless M3 changed behavior and we have a regression. #7193 addressed a similar issue where the form action was cached with the request's domain instead of what was set in the site_url. So #7193 was done to force all URLs generated through the router to use the site_url. Before adding this new code, I think it needs to be debugged why #7193 is not working for this context.

**Comment by kuzmany** [comment]
I've tested this scenariou without this PR and for me works properly. I don't see any issue. As @alanhartless mention it was fixed times ago by subscriber https://github.com/mautic/mautic/pull/7193

If you need change behaviour you can use subscriber same like mentioned https://github.com/mautic/mautic/pull/7193 and change it 

Please let us feedback.

**Comment by npracht** [comment]
Closing for lack of feedbacks and obviously solved since offered PR 🚀

**Pull request closed without merging**
