### PR TITLE
Fix broken link in the readme

### PR DESCRIPTION
**Pull request by RCheesley**
Fix a typo

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | NA
| Related developer documentation PR URL | NA
| Issue(s) addressed                     | NA

#### Description:

Tiny link fix in the readme

### CODE REVIEW

**Review by npracht — COMMENTED** [review]
👍 works

**Comment by RCheesley** [comment]
@cla-bot check again please :)

**Comment by RCheesley** [comment]
Thanks @npracht just testing the CLA bot with an old PR I had sitting in my fork!

**Comment by RCheesley** [comment]
@cla-bot check again please :)

**Review by mabumusa1 — APPROVED** [review]
The link works

**Pull request merged**
