### PR TITLE
Fix marketing message sorting by category

### PR DESCRIPTION
**Pull request by volha-pivavarchyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Sorting marketing messages by category causes the following error.

image

This PR fixes the error. 
#### Steps to test this PR:
1. Create two or three marketing messages.
2. Try to sort by column
3. There is an error.
4. Swich on the other page, e.g. emails
5. Try to open the marketing messages page again
6. Not opening

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create two or three marketing messages.
3. Try to sort by column.
4. Sorting works well.

### CODE REVIEW

**Review by kuzmany — APPROVED** [review]
Works as expected

**Review by RCheesley — APPROVED** [review]
Thanks for the bug fix @volha-pivavarchyk - works great, no errors when sorting by category now! 🚀

**Comment by RCheesley** [comment]
@volha-pivavarchyk might be worth back-porting this over to 4.4 perhaps, to get the bug fix into the 4.x series? WDYT?

**Comment by volha-pivavarchyk** [comment]
@RCheesley I think it is a good idea. I have added a new PR

**Pull request merged**
