### PR TITLE
Fix incorrect cleanup calls in EventExecutioner

### PR DESCRIPTION
**Pull request by galvani**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | N
| BC breaks? | N 
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Failures fails to record due to a call to non-existent method.

### CODE REVIEW

**Comment by npracht** [comment]
@escopecz @kuzmany @Woeler a simple code review ?

**Comment by escopecz** [comment]
@npracht same here. Jan is my colleague. Someone from the community should review/test it. We already did.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by npracht** [comment]
Hello @alanhartless could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback, i would very love to merge it in 3.0.1 if still relevant. Thanks !

**Comment by RCheesley** [comment]
@galvani @escopecz @alanhartless am unable to rebase this due to permissions to trigger the code coverage report - please take a look and rebase against staging? Thanks!

**Comment by escopecz** [comment]
Rebased on current staging.

**Review by dennisameling — APPROVED** [review]
Can confirm the `clear()` method doesn't exist:

image

`clearCollection()` indeed does exist, so the code is OK 👍 Quite surprised PHPSTAN didn't catch this issue! Just checked by increasing the PHPSTAN level from 1 to 2 and then the error shows up:

image

@escopecz would be great if we could increase the PHPSTAN level at some point in the future 🚀

**Review by kuzmany — APPROVED** [review]

**Pull request merged**
