### PR TITLE
Lead details fix

### PR DESCRIPTION
**Pull request by mqueme**
Please answer the following questions:

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed issues  |  5

## Description
- Changed language search to filter
- cancel button on merge modal was giving an error
- removed extra contact on translation for segments for...
- removed extra search bar in merge modal
- changed panel search view in contact history to match search on notes tab

### CODE REVIEW

**Comment by dbhurley** [comment]
+1 - replacements look good to me.

**Comment by escopecz** [comment]
All is good, but I'm not sure about removing the search field from the manual merge modal. Now, when I want to search for johns in the merge modal, I can see only 2. But in the Contact Manager when I search for Johns, I can see 10 contacts. I think the search box was there for a reason. Although it wasn't clear how to use it. Here is how I think it should work:

https://github.com/mautic/documentation/pull/49/files#diff-d4a20f7d4a3c225d4cac437e09de9f1fR37

Also, here is the original PR adding the manual merge feature: https://github.com/mautic/mautic/pull/803. Maybe we could ask its author @zapur1 if the 2 search boxes are needed or not.

**Comment by zapur1** [comment]
Yeah the search box functionality is awkward to use. It was to mean that all the leads don't get loaded into a pre-populated dropdown. I also wasn't about to get the search box to behave in a ajax way where the select data is only loaded after a search has started. If you have added the ajax side of it then it should be much better

**Comment by dbhurley** [comment]
I see, we should have ajax searching within Chosen.

**Comment by escopecz** [comment]
:+1:

**Pull request merged**
