### PR TITLE
Campaign duplicate entry errors

### LINKED ISSUE #6613: Bug is back in 2.14.0  -- UniqueConstraintViolationException and subsequent campaign failure
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

| Q  | A
| ---| ---
| Bug report? | x |
| Feature request? || 
| Enhancement? | |

## Description:

I'm facing the issue described in #3749

Steps to reproduce and Mautic behaviour are exactly as described. The difference in logs is that my logs show that the Entity Manager is closed. See below.

This bug goes away when I downgrade to 2.13.1. (would not like to keep using 2.13.1 due to stability issues but have to while this bug exists)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.0

### Steps to reproduce:
See #3749 
 
### Log errors: 
```
[2018-09-12 22:37:03] mautic.ERROR: CAMPAIGN: The EntityManager is closed. [] []

[2018-09-12 22:38:02] mautic.ERROR: CAMPAIGN: An exception occurred while executing ‘INSERT INTO campaign_lead_event_log (rotation, date_triggered, is_scheduled, trigger_date, system_triggered, metadata, channel, channel_id, non_action_path_taken, event_id, lead_id, campaign_id, ip_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)’ with params [1, “2018-09-12 22:38:02”, 0, null, 1, “a:0:{}“, “email”, 101, 0, 37, 37510, 9, 2999]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry ‘37-37510-1’ for key ‘campaign_rotation’ [] []

[2018-09-12 22:38:02] mautic.ERROR: CAMPAIGN: The EntityManager is closed. [] []

```
_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/63612114-bug-is-back-in-2-14-0-uniqueconstraintviolationexception-and-subsequent-campaign-failure?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by heathdutton**
closes https://github.com/mautic/mautic/issues/6613
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | N
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
When running `console mautic:campaign:trigger` there are a few situations that can result in an integrity constraint violation AKA "Duplicate entry" errors. These *appear* innocuous and are generally ignored by people, but in some cases they can cause serious problems with lead handling. Here are some examples:

1. **User Error:** You are running multiple concurrent instances of the cron task `console mautic:campaign:trigger` probably also using --force, but without using the multi-threading parameters correctly. These processes are hitting the same event, lead and rotation at the same time. This PR will detect this as two events matching each other within a 60s timeframe and prevent saving a new event, thus preventing the exception most of the time (though not always). Note: Use --thread-id and --max-threads to avoid this problem altogether.
2. **Jump To Events:** You have jump-to event that takes leads somewhere they've already been, by way of intervals (particularly if there are intervals on both sides). This will cause the lead to stop when jumping to the event they've already hit. This PR fixes this by increasing the rotation before the jump occurs instead of afterward. This PR may resolve #7129.
3. **Event Rearrangement:** You have a campaign with a delay in a chain of events, and you re-arrange the order of events while leads are in the campaign queued for an event. It's like playing with a bug, and you have shuffled your hands to keep the bug on them as it walks across. In this case, the bug is the lead and your hands are two events. Previously the lead would HALT at the first "duplicate" event, and not run further through that branch of the campaign. This is not expected behavior by users. We have some events with hundreds of thousands of leads queued to continue after a delay, and the campaign manager (cognizant of this) may intentionally rearrange events to have the lead go back to a previous event in order to handle campaign changes gracefully. This PR fixes this by detecting this situation and incrementing the rotation when it occurs on a per event-lead-rotation basis.

Finally, this PR detects these critical DB related errors and throws them before they have a chance to mess up subsequent batches of leads. A single integrity constraint violation in the midst of a large batch of leads in a complex campaign can cause duplicate events (such as push to integration) to be fired in the thousands, so throwing the exception so that a new cron/thread picks up the body of work is much safer for us.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
* Run multiple simultaneous threads of `console mautic:campaign:trigger --force`. OR
* Rearrange a campaign vertically while leads are in flight and there are delays between events. OR
* Create a delayed "Jump To" event that sends a lead to an event that they have already hit. OR

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Make a simple campaign with 2 actions chained together, and a delay on the second action of a few minutes.
3. Add a lead to the campaign, wait till the lead is scheduled for the second event. (crons run every 5 minutes)
4. Edit the campaign (while the lead is in the middle), and change the order of events (first is second, and vice versa).
5. Wait ~5 minutes.
6. Check the lead, it should have fired one of those events TWICE. This is the expected behavior.

### CODE REVIEW

**Review by westonwatson — DISMISSED** [review]

**Comment by heathdutton** [comment]
Starting this week we'll be running this in production. ☝️ 
We'll be back here to modify the PR if we encounter issues.

**Comment by heathdutton** [comment]
We've been running this in production for a while, just modified with some tweaks to prevent notices when using master/slave DB cluster. Otherwise, it's been working well.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
Re-opening after close for travis

**Comment by RCheesley** [comment]
@heathdutton can you take a look at Travis errors please?  Can you also rebase against staging to trigger the code coverage report? Thanks!

**Comment by RCheesley** [comment]
Moving to a later release due to outstanding issues

**Comment by dennisameling** [comment]
@heathdutton Thanks so much for providing this PR together with the detailed explanation! Your code makes a lot of sense, I'm just curious about one thing: do you think it'd make sense to create tests for at least the  "Jump to Events" case? I understand some of the examples you mentioned are quite hard to reproduce in automated tests. At the same time we're trying to increase code coverage to make the product even more stable, and I think the "Jump to Events" action would be a good candidate for this.

I'm happy to help write those tests (if you think they'd be valuable) but would need some pointers as I'm fairly new to writing automated tests. Could you please let us know if tests would be valuable in this case and if yes, provide a few pointers so we can help write them? Thanks!! 🚀 

PS happy to test this PR once it's rebased :)

**Comment by heathdutton** [comment]
Yes @dennisameling even with this PR there are other edge-cases where a jump-to event can cause recursion. This just removes the most obvious/frequent case. And yes, needs rebasing too. To answer your question, yes there absolutely should be tests to handle these scenarios.

Most especially... If a lead is being assigned to an event it has already hit. Since there is always a chance that this has been caused, we need to make sure that *when* it happens, it does not cause campaign processing to completely halt due to an exception on FK constraint.

**Comment by RCheesley** [comment]
Can we get those tests written/travis issue addressed before the end of the weekend do you think folks? @dennisameling @heathdutton

**Comment by RCheesley** [comment]
Bumping to 3.1 due to lack of test coverage.

**Comment by RCheesley** [comment]
Bumping again to 3.1.1 - if we can't get the tests written before the next release, we will have to decide what to do with this PR going forward. Let's try to get some tests written folks! 🚀

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Hi folks, bumping again to 3.1.2 ... 3rd time lucky maybe? ;)

Let's try to get those issues addressed by **18th October** to be included in the release!

**Review by npracht — DISMISSED** [review]
@heathdutton would you have the chance to look at unit tests this week ? Then we can merge it.

On my side we're using it in production environment for a while now.

**Comment by dhilst** [comment]
I tried this, I applied it at 3.2 branch by hand and I still have the same integrity errors :(. I left the patch here if anyone want to try/check

[0001-Apply-PR-7605-to-3.2.patch.zip](https://github.com/mautic/mautic/files/5629919/0001-Apply-PR-7605-to-3.2.patch.zip)

I my case I have this testing campaign: 
image

**Comment by npracht** [comment]
@heathdutton can you review the conflicts please ?

**Comment by dennisameling** [comment]
Hi @heathdutton! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since this PR has conflicts now, could you please do a `git merge upstream/features` locally to resolve the conflicts? Thanks in advance!

**Comment by npracht** [comment]
Hi @heathdutton, any chance to get your help here ?
Thanks a lot <3

**Comment by RCheesley** [comment]
@heathdutton are you able to resolve the conflicts with this PR? If not we will take it on in the Product Team to try to get this PR into the 4.0.2 release but your help would be appreciated!

**Comment by nickveenhof** [comment]
Even with this patch I get:

`[2021-11-26 08:08:56] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO campaign_lead_event_log (rotation, date_triggered, is_scheduled, trigger_date, system_triggered, metadata, channel, channel_id, non_action_path_taken, event_id, lead_id, campaign_id, ip_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [66031, "2021-11-26 08:08:56", 0, null, 0, "a:0:{}", null, null, 0, 14, "16962", 5, 6323]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '14-16962-66031' for key 'campaign_rotation'" at /var/www/mauticswis/dev/application/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 74 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO campaign_lead_event_log (rotation, date_triggered, is_scheduled, trigger_date, system_triggered, metadata, channel, channel_id, non_action_path_taken, event_id, lead_id, campaign_id, ip_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [66031, \"2021-11-26 08:08:56\", 0, null, 0, \"a:0:{}\", null, null, 0, 14, \"16962\", 5, 6323]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '14-16962-66031' for key 'campaign_rotation' at /var/www/mauticswis/dev/application/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:74, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '14-16962-66031' for key 'campaign_rotation' at /var/www/mauticswis/dev/application/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '14-16962-66031' for key 'campaign_rotation' at /var/www/mauticswis/dev/application/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)"} []`

Or the response in the  browser from a testing user:

`{"error":{"code":500,"text":"Internal Server Error","exception":"","trace":""},"route":"\/mtc\/event","flashes":"","notifications":{"content":"","lastId":null,"hasNewNotifications":false,"updateAvailable":false},"browserNotifications":[],"newContent":"..."}`

I'm doing further investigation

**Comment by escopecz** [comment]
I'm closing this as Heath is no longer active and Acquia has another approach on solving this with upsert method (INSERT ... ON DUPLICATE KEY UPDATE) that is coming soon.

**Pull request closed without merging**
