### PR TITLE
TPROD: Fix Property Access

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

According to the [documentation](https://symfony.com/doc/5.4/components/property_access.html#usage), we can not use `new` to create new property access, but we have to use a static method and this PR is doing this 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by escopecz** [comment]
@mabumusa1 I guess this is related to https://github.com/mautic/mautic/pull/12166#issuecomment-1498907535 ? Can you remove the change in the phpunit.xml?

**Comment by mabumusa1** [comment]
> @mabumusa1 I guess this is related to [#12166 (comment)](https://github.com/mautic/mautic/pull/12166#issuecomment-1498907535) ? Can you remove the change in the phpunit.xml?

@escopecz yes, it should be related to the comment, but this PR does not solve the issue yet as we have to wait until doctrine is upgraded for the issue in the comment to go away

**Comment by escopecz** [comment]
@mabumusa1 can you please describe in the PR description why this change is needed?

**Comment by mabumusa1** [comment]
> @mabumusa1 can you please describe in the PR description why this change is needed?

@escopecz Done

**Review by escopecz — APPROVED** [review]
This change is done according to the docs. Thanks!

**Pull request merged**
