### PR TITLE
Improve boolean import/API support

### PR DESCRIPTION
**Pull request by heathdutton**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Y
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | N
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
When creating leads by imports or APIs, boolean values that don't use "true" or "false" (etc) end up being stored as FALSE, instead of NULL (a more accurate value for a non-answer). This can cause a lot of confusion. This fixes that and also supports values like "T" and "F" which are obviously representative.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a boolean field.
2. Import a CSV with one lead value of "T".
3. Open the lead imported and you'll see "No" (false value) selected.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create a boolean field.
3. Import a CSV with one lead value of "T".
4. Open the lead imported and you'll see "Yes" (true value) selected.

### CODE REVIEW

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@heathdutton if you have a moment could you rebase this against staging so that we can get a code coverage report triggered? I've assigned this to the 3.2 release, hopefully we should be able to get it tested in time!

Many thanks!

**Review by npracht — DISMISSED** [review]
Working well

**Comment by kuzmany** [comment]
@heathdutton are you able to check CS fixer?

**Comment by npracht** [comment]
@heathdutton if you can have a look at CS, we might be able to merge it today :)

**Review by kuzmany — DISMISSED** [review]
We use it and works properly 👍

**Comment by RCheesley** [comment]
@kuzmany or @mabumusa1 would either of you be up for writing the tests for this?

**Review by mabumusa1 — DISMISSED** [review]
I wrote a unit test for the code, it works as expected

**Comment by mabumusa1** [comment]
> @kuzmany or @mabumusa1 would either of you be up for writing the tests for this?

I wrote a basic test for it, I think this should pump up the coverage

**Review by kuzmany — DISMISSED** [review]
We use it on production long time. 
Unit tests included 

👍

**Comment by kuzmany** [comment]
This need rebase against to 4.x. I feel like create new PR it's faster. I will check it tomorrow

**Comment by kuzmany** [comment]
Close favor to  https://github.com/mautic/mautic/pull/10866

**Pull request closed without merging**
