### PR TITLE
[UX] 13 new core email layout themes

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR adds 13 email themes focused on providing ready-to-use start templates.
It's a result from the [debate opened in the community portal](https://community.mautic.org/assemblies/product-team/f/39/debates/9), where I highlight how needed those themes are to improve the adoption of Mautic as a reliable tool when compared to others in the market.

The goal here is not to present a WOW design, but to have some simple layouts available to customize a bit and send. 
Because of this thought, they're built in gray tones, no colors, using placeholders, responsive, fully editable, dry code, featuring main tokens (like webview url and unsubscribe text).

I'm using the character _ to make all of them become first, leaving future designed themes to be shown after those (already existing themes are also included in this criteria).

Also implemented a folder called `@defaults` so all themes can inherit placeholders, and more people can use them to create future themes if wanted.

they also have an unsubscribe page that shows different icons based on the current action instead of just a blank screen.

image

image

image

Unsubscribed
image

Resubscribed
image

Preference center (unstyled, only added the icon)
image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Channels > Emails and play with the theme options

### CODE REVIEW

**Review by Aleks0129 — CHANGES_REQUESTED** [review]
Thumbnail too high select button pushed down.

Screenshot 2024-10-03 at 16 33 02

**Comment by andersonjeccel** [comment]
@Aleks0129 Hi there, the image wasn't uploaded properly, could you edit your comment to add it again?

image

**Comment by andersonjeccel** [comment]
@Aleks0129 Thanks for reviewing!

This issue is more about the UI than the themes (it seems like the name in two lines is the cause, but that's something to be tackled in a page redesign), it'd be great if you could reconsider approving :)

**Comment by Aleks0129** [comment]
@andersonjeccel should I test the templates?

**Comment by andersonjeccel** [comment]
@Aleks0129 Yep, this PR is only adding the new templates :)

**Comment by Aleks0129** [comment]
@andersonjeccel I was testing with gitpod, which doesn't allow me to send emails to litmus. I will make a local install then.

**Comment by andersonjeccel** [comment]
@Aleks0129 They can be tested opening in the builder and looking at how they look, that's enough 
they look exactly the same when sent

**Review by Aleks0129 — APPROVED** [review]
I tested all of the templates. Looks good.

screencapture-8080-andersonjeccel-mautic-wxozl4ev29n-ws-eu116-gitpod-io-s-emails-edit-1-2024-10-05-18_13_28

screencapture-8080-andersonjeccel-mautic-wxozl4ev29n-ws-eu116-gitpod-io-email-preview-1-2024-10-05-18_07_19

**Comment by Oluwatomie** [comment]
I want to attempt testing this PR. @andersonjeccel do I have a nodge to go ahead?

**Comment by andersonjeccel** [comment]
Hi @Oluwatomie 

ofc, proceed :)

**Comment by RaffyRod** [comment]
I want to attempt testing this PR. @andersonjeccel can I go ahead?

**Comment by RaffyRod** [comment]
I have thoroughly tested and validated each of the 13 email themes introduced in this PR. 
The templates function as expected, providing clean, responsive layouts that are fully customizable. 
The use of placeholder content and gray tones is highly effective for quick adaptations, aligning with the goal of simplicity over design complexity.

In particular, I verified that all main changes, such as the web view, responsive view, etc.






@andersonjeccel Looks like I can not approve or  add a review, but I can upload my testing evidence, if possible please add me as reviewer too, so I can approve.

**Comment by andersonjeccel** [comment]
Hi @RaffyRod, thanks for reviewing!

I'm checking about the review permission

**Comment by andersonjeccel** [comment]
@RaffyRod It looks like we need to follow these steps: https://contribute.mautic.org/contributing-to-mautic/tester#leaving-your-review

To leave a review, we basically have to go to the Changed files tab, then click on "Add your review"

Check if this works, or ping me if you still need help

**Review by RaffyRod — APPROVED** [review]
Looks good to me.

**Comment by escopecz** [comment]
I'm not sure whether we want to add more core themes. We are improving the marketplace so it would be very simple to click and install themes from any author with one click.

There is an issue that many users use either just one theme to keep their branding unique or they create their own. So having a bunch of different themes is very confusing and distracting. And they cannot simply delete them as they will re-appear during the next Mautic update.

@RCheesley what's your take on this?

**Comment by andersonjeccel** [comment]
People seem not to have a problem as we see other marketing automation and mailing tools in the market providing ready to use templates...

Mailchimp offers 137 templates, for example, but the few we have in Mautic barely work and users gave only negative feedback about them, I posted a few yesterday on the ux-ui channel in Slack :(

The offerings on the marketplace and core can be considered different proposals, given the level of freedom to create and related context... we're probably unable to control quality and set guidelines (like 2, 3, 4, 8 and 11 mentioned in the debate) for things in the marketplace

I would say that it's far from being confusing or distracting, as it's making marketer's everyday job easier, but providers are always free to remove things they don't want 😄

**Comment by RCheesley** [comment]
@escopecz I think that it's very important that we have a decent range of themes available for people to understand how to use Mautic and get started. I talked extensively about this with @andersonjeccel and I think he's documented that in his reasonings which were recently shared on Slack, and we have a lot of feedback from users via the UX form and through client feedback on the Trials about their frustrations of not having decent themes, not being able to understand how to use features in the editor etc.

I think we should build up a decent stock of themes which ship with core and which make the email creation process simple using best practices with MJML etc, because you want users to at least have the basics before they have to go installing other things.

When I talk about users here, I am thinking about the solopreneur and first-time-using-marketing-software users as much as the mid to large size businesses who already have their marketing stuff in place. The majority of our users fall into the former groups, who do not already have a tonne of themes or specific branding and are often experimenting with different layouts etc. This makes it easier for them to see the power and flexibility of the email builder and what it's capable of, giving them some nice, simple themes that they can use as a starting point for building up their own brand.

I don't think we need to get to the extreme end of the Mailchimps of this world - I agree that beyond maybe 10-20 decent themes with core, the marketplace (when out of beta) would be the tool of choice to install themes, plugins etc.

We do have the option now, as far as I know, to [hide the default themes](https://github.com/mautic/mautic/pull/13723) so I think that would take care of 'I don't want to see the core themes any more' dimension?

**Comment by escopecz** [comment]
Thanks for your PoV! True about the theme hiding feature. I'll hit the merge button once the e2e tests finally get green.

**Pull request merged**
