### PR TITLE
Use Message Queue to Handle Email Hit and Page Hit Tracking

### PR DESCRIPTION
**Pull request by mikegillis677**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | X
| New feature? | Yes
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/171
| Related developer documentation PR URL | X
| Issues addressed (#s or URLs) | X
| BC breaks? | X
| Deprecations? | X

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This is basically the same thing as https://github.com/mautic/mautic/pull/2278.  I picked it up from them and implemented the feedback given in that pull request.

One of the bottlenecks in scaling Mautic is email open tracking and page hit tracking.  This pull request adds a queue mechanism to allow these events to be processed asynchronously, which frees up CPU and RAM resources to process more email open tracking and page hit tracking events simultanously.

This code implements the event based queuing mechanism described in the feedback in pull request 2278.  It also implements both RabbitMQ and Beanstalkd protocols, and allows them to be configured through a new Queue Settings page on the Configuration screen.  Additional protocols can be implemented by hooking up Event Listeners.

Processing queued events is handled via a new console command: `app/console mautic:queue:process -i QUEUE_NAME`.  You can pass it a queue name as a parameter.  Currently, two queues are implemented: `page_hit` and `email_hit`.

[//]: # ( As applicable: )
#### Steps to test this PR:
1. Install a [Beanstalkd](https://kr.github.io/beanstalkd/download.html) or [RabbitMQ](http://www.rabbitmq.com/download.html) client.  You can use [cloudamqp](https://www.cloudamqp.com/) for a free cloud based RabbitMQ client for testing purposes if you wish.
2. Launch your Beanstalkd or RabbitMQ client
3. Load up Mautic, and configure your chosen queue client on the new Queue Settings section of the Configuration screen.
4. Hit a Mautic landing page in your browser
5. Run `app/console mautic:queue:process -i page_hit -m 1`
6. Hit the url that simulates an open email in your browser : `mautic_url/email/{id}.gif`
7. Run `app/console mautic:queue:process -i email_hit -m 1`

### CODE REVIEW

**Comment by escopecz** [comment]
Thank you for this! Here are notes from my testing:

First thing I tested after I pulled and composer install was BC. The page hit and email open events work as they did before without any configuration change. So that's good :)

Then I tested beanstalk. When I saved the configuration and did not have beanstalk deamon running, the whole Mautic crashed. Is there something we could do about that? Like catch the error:

```
Symfony\Component\Debug\Exception\ContextErrorException: PHP Warning - fsockopen(): unable to connect to localhost:11300 (Connection refused)
```

The exception goes through `/app/bundles/CoreBundle/EventListener/ExceptionListener.php:81` so maybe we could catch it there and display some user-friendly warning. Because if someone changes that, he won't be able to change that back unless running the beanstalkd or change it in the config file. But that's just a small issue. Users who will know what they are doing won't have any problem with this. Only the 90% of the rest :)

I wasn't able to record any email hits though. Page hits are working fine. The email open action was processed via beanstalk queue correctly. I could see the incoming email hits. But it did not show up in the email stats nor in the contact time line.

Another issue with email hits is that if a contact opens the email in web view, the page hit is recorded in the beanstalk instead of email hit. I don't think that that's a big issue. It is a page hit after all. But the email hit is not recorded as it is without the queue configured. It should.

Another issue someone can have is the size of the beanstalk jobs. It stores everything about the page hit as well as every contact custom field. The limit is 65k. With my quite basic Mautic setup the job size is 26k. I can imagine that the limit can be hit easily on some instances today.

Some speed improvement stats:
- The email gif loads in 400 ms with the queue. Around 450 ms the same time takes it without the queue.
- The page hit tracking event loads in 716 ms with the queue. 2.5 s without the queue. I guess it's because I have a webhook configured on contact update event. So it is a big improvement here.

Could you please address the issues I found?

**Comment by escopecz** [comment]
I wanted to push a fix for failing CS check, but it seems this PR has the write access disabled:
```
`/usr/bin/git push --set-upstream mikegillis677 mikegillis677-queue_bundle:queue_bundle` failed with following output:

ERROR: Permission to mikegillis677/mautic.git denied to escopecz.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Please run `bin/php-cs-fixer fix -v` yourself to fix the CS.

**Comment by mikegillis677** [comment]
@escopecz I'm not able to reproduce the crash due to beanstalkd not running.  I checked the code in pda/pheanstalk, and it looks like the warning ought to be suppressed via `@fsockopen($hostname, $port, $errno, $errstr, $timeout)`.

**Comment by escopecz** [comment]
No worries, that is just a nice to have. I can fix it if you cannot replicate on your machine. The biggest problem is that the email opens are not tracked the same way with the queue and without. Also the job size may be problem for some current Mautic installations.

**Comment by mikegillis677** [comment]
@escopecz I ran some tests on the email open tracking after getting a new test environment setup (apparently, Mautic email tracking pixels don't work properly with the PHP Build-in web-server, which is my normal development environment).  My new development environment is a CentOS 7 server running local MariaDB, local beanstalkd, PHP 5.6.30, and Apache 2.4.6.

When I loaded the tracking pixel in my email client, it didn't work due to a invalid SSL cert in my test environment.  When I loaded the tracking pixel in my web browser, though, and clicked through the SSL warning, the email hit showed up in the queue.  When I then processed the queue using `app/console mautic:queue:process -i email_hit -m 1`, the email open was correctly recorded in the email stats and in the contact profile.

I created a new campaign and sent it out again to try from scratch with the open in web view.  I opened the link in web view, and nothing got tracked.  This was because I opened it in my web browser that I was logged into Mautic in (since web view email hits are only tracked if `$this->get('mautic.security')->isAnonymous()` evaluates to true in the EmailBundle PublicController.  I opened it again in a Chrome incognito window, and the email open was correctly recorded in the email stats and in the contact profile.

At this point, I'm going to go ahead and try to reduce the payload size of the page_hit queue jobs, and I'll get back to you when I've got the code changes ready.

**Comment by mikegillis677** [comment]
@escopecz Okay, I've run the PHP CS fixer and updated the logic for the queuing of page hits to lighten the payload that goes into the queue.

**Comment by alanhartless** [comment]
I couldn't push directly to this branch/PR so I had to submit a pull request. There were a number of issues I fixed described in https://github.com/mikegillis677/mautic/pull/1 but I'll cross reference them here:

Serializing objects can potentially introduce a security vulnerability when unserializing which will execute a __wake magic method. Therefore, just to be on the safe side, I've changed it to store the Request as a flat array on queue then rebuild the Request object on consume. This also prevents errors when using something like a beanstalk admin UI from throwing errors when viewing the job as it won't' find Symfony's classes.
The Hit entity lost storing the Lead entity association
Redirects are handled by page hits as well but consuming assumed all hits were from Page entities (and the Redirect association was not stored)
The signature and behavior for the public method PageModel::hitPage was completely changed causing a BC break for plugins that may leverage the page hits table to track traffic (same way redirects do). Therefore I moved the private method from PageBundle's PublicController to the PageModel in order to keep BC support.
The current lead was not set when processing the page hit via the consumer. This resulted in anything listening to the hit page listener to not know what lead is associated, i.e. campaign page hit decision. Same with email opens.

**Comment by escopecz** [comment]
Hi, would you mind fixing the [code standards issues](https://travis-ci.org/mautic/mautic/jobs/249760055#L1157)? There is a pre-commit hook which should do it for you. Please run `composer install`. Notice it will create a bin directory in Mautic root. Then run `bin/php-cs-fixer fix -v` to fix the CS for all files and commit the changes when the command finishes.

**Comment by mikegillis677** [comment]
@escopecz Alright, I've run php-cs-fixer and committed the results.  Were there any other adjustments you needed me to make?

**Comment by escopecz** [comment]
It's failing some unit tests now. Could you look into the reason why?

**Comment by mikegillis677** [comment]
@escopecz I ran the tests locally and they all pass.  According to the Travis CI build information, the failing test is `Mautic\PageBundle\Tests\Model\PageModelTest::testGenerateUrl_WhenCalled_ReturnsValidUrl` in file `mautic/app/bundles/PageBundle/Tests/PageTestAbstract.php`, but that file does not seem to exist in the project.  Do you know where I should look to find this test?

**Comment by escopecz** [comment]
Maybe try to merge latest staging branch to your branch go get the latest code. PageTestAbstract was merged on June 1 (https://github.com/mautic/mautic/commits/4e1975ac30b9be013f2aaf05658b305773e35eb1/app/bundles/PageBundle/Tests/PageTestAbstract.php) I'm not sure why would Travis trigger tests which are not in the branch though.

**Comment by mikegillis677** [comment]
@escopecz I've updated my branch with staging and fixed the failing test case.  It appears that all checks are passing now.

**Comment by escopecz** [comment]
When I test with Beanstalk, it passes all my functional tests I could think of. But what I don't understand is 

1. why the tracking pixel takes between 0,8 - 1.5 seconds to load when the queue is configured.
2. why is the page hit visible in the Mautic UI even if I do NOT run any mautic:queue:process command. I can see the events are being queued to Beanstalk, but I can see them in real time in Mautic too. What is the reason for queueing then?

When testing BC with queue disabled and accessing a page tracked by Mautic JS tracking I get this 500 error on the mtracking.gif request:
```
Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Mautic\PageBundle\Model\PageModel::processPageHit() must be an instance of Symfony\Component\HttpFoundation\Request, null given, called in app/bundles/PageBundle/Model/PageModel.php on line 609
/app/bundles/PageBundle/Model/PageModel.php:623
/app/bundles/PageBundle/Model/PageModel.php:623 at
/app/bundles/PageBundle/Model/PageModel.php:609 at Mautic\PageBundle\Model\PageModel -> processPageHit ( object(Hit), null, object(Request), false )
/app/bundles/PageBundle/Controller/PublicController.php:366 at Mautic\PageBundle\Model\PageModel -> hitPage ( null, object(Request) )
Mautic\PageBundle\Controller\PublicController -> trackingImageAction ( )
/vendor/symfony/http-kernel/HttpKernel.php:144 at call_user_func_array ( array(object(PublicController), 'trackingImageAction'), array() )
/vendor/symfony/http-kernel/HttpKernel.php:64 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '1' )
/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php:69 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '1', true )
/vendor/symfony/http-kernel/Kernel.php:185 at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel -> handle ( object(Request), '1', true )
```

**Comment by mikegillis677** [comment]
Hmm... something doesn't sound quite right then.  I'll take a look.

**Comment by mikegillis677** [comment]
Okay, I think I found the issue with the Fatal error you were getting, and I'll provide a fix for that once I get some of this other stuff fixed as well.

I also tracked down why you're seeing page hits before the queue is processed.  It looks like the logic that was implemented to reduce the size of the packet passed into the queue caused a regression.  I'll need to try to figure out a way to recode it so that we do less processing work up front, but also don't pass very much information into the queue.

**Comment by mikegillis677** [comment]
I've got the code refactored to deal with the issues that were raised. Page hits now correctly only increment when the queue is processed when queue is enabled. I also squashed the bugs that were causing the fatal in the Mautic JS tracking.

I went through and measured load times on my local install of Mautic with the queue enabled and disabled
*tracking pixel*
* queue enabled - 266 ms
* queue disabled - 631 ms

*simple page*
* queue enabled - 1.12 sec
* queue disabled - 1.38

The goal of the page hit tracking was to take some of the write load off of the database during times of large numbers of page hits, which might be a concern after a large campaign is sent out and many people are viewing a link to a Mautic Page resource.  I'm actually torn about writing the hit to disk for before stuffing the hit id into the queue for this reason, given that the hit entity doesn't seem to be particularly large when it is disconnected from related entities such as leads and pages, so it shouldn't increase the total size of the packet in the queue by very much.

**Comment by dongilbert** [comment]
@mikegillis677 Everything is looking good on this - functionality is great - thanks for that!

However, there's conflicting files with the composer.json and composer.lock files between this and current staging. I tried to resolve them but was unable. It seems that you're missing the `leezy/pheanstalk-bundle` from the composer.json It's present in the composer.lock file, so I'm not sure what's going on there. I tested using `beanstalkd`, so I know the code works, I'm just unable to properly resolve the conflicts in those files.

**Comment by dongilbert** [comment]
Other than that conflict, this seems good to go

**Comment by mikegillis677** [comment]
Alright, I went ahead, updated the composer.json for the missing dependency (not sure how that happened... maybe a messy merge?), and resolved the conflict.

**Pull request merged**
