### PR TITLE
Separate assets from media

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
**why**

make the lifecycle of composer based installs easier by not mixing application content and user uploaded content in the same folders.
This PR created a distinction between `app/assets` (application)  and ` media` (user) files.

**what does this PR**
* move all the static assets from the `media` folder to the `app/assets` folder
    * the dasboards
    * the flags
    * the mejs files
* introduce the `AssetsHelper::getOverridableUrl()` method, to provide logic to override an Mautic asset in `app/assets` via a file in the `media` folder
    * use the method above in all relevant places where logo's, flags, ... are references
* a command `mautic:assets:cleanup` that cleans up files in the `media` folder that already exist in the `app/assets` folder, and are exactly the same based on the md5 hash.

**possible folluw-up tasks**
* use the term `asset` and `media` consistently in code

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. check for broken images / js / css files in the installer, when clicking around, or when hitting an error page
3. test the asset override functionality
    - add a contact and assign a country (e.g. Belgium)
    - check if the flag loads
    - override the flag by copying another flag from the `app/assets` folder to the `media` folder
      ```
      cp app/assets/images/flags/France.png media/images/flags/Belgium.png
      ```
    - refresh the contact info and verify the flag is overridden.
4. test the `mautic:assets:cleanup` command
    - copy an extra asset to the media folder with the 
      ```
      cp app/assets/images/mautic_logo_db64.png media/images/mautic_logo_db64.png
      ```
    - run the cleanup command, it should show 1 file
      ```
      ./bin/console mautic:assets:cleanup
      1 obsolete files found
       - /var/www/html/mautic/media/images/mautic_logo_db64.png
      ```
    - verify `media/images/mautic_logo_db64.png` is gone, but `media/images/flags/Belgium.png` still exists

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10682"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
@mollux thanks for working on this. Please can you ensure the email address you use to sign your Git commits is on your GitHub profile? It doesn't have to be the primary, just present on your profile and verified etc.

Once that's done it will be able to check if you've signed the contributors agreement.

I've set the tests running, but as you're a new contributor it will need someone to approve & run each time you push changes, because of GitHub's security processes. Just ping using @ mautic/core-team if you need someone to approve and run.

**Comment by mollux** [comment]
@RCheesley thanks for starting the pipelines, this will already give more info about the next issues to tackle.
I'll also update the description of this PR once it is more clear what still needs to be tackled.

I added my mail address to my Github profile and signed the CLA.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by mollux** [comment]
@mautic/core-team could someone approve and run the tests?

**Comment by mollux** [comment]
@RCheesley it looks like @ mautic/core-team doesn't exist (anymore), who do I ping in the future?

**Comment by RCheesley** [comment]
You use it without the space after the @

**Comment by mollux** [comment]
@RCheesley I did the comment before I pinged you, but it doesn't appear as link, so I assumed something was wrong :)

**Comment by RCheesley** [comment]
Ah maybe it's only possible for the team to use it! Just set the tests running for you!

**Comment by mollux** [comment]
@RCheesley could you start the testsuite please? thanks!

**Comment by mollux** [comment]
@escopecz this is the PR for the assets / media separation

**Comment by escopecz** [comment]
@mollux there are some conflicts. Do you think you could update it?

**Comment by mollux** [comment]
@escopecz it will be some work, but doable

**Review by escopecz — COMMENTED** [review]
1. The `Swaziland.png` should be renamed to `Eswatini.png`, right? Or is it removed on purpose? Oh, all flags were removed. They were duplicated on both locations? Weird.
2. I'd keep the dashboards in the media folder as those dashboards can be managed via UI (uploaded, deleted)
3. Double-checking I understand the deleted minified assets. Those are generated with prod assets, right?
4. Does it mean that with the overridable assets this is not a BC break?

**Comment by mollux** [comment]
@escopecz 

> 1. The `Swaziland.png` should be renamed to `Eswatini.png`, right? Or is it removed on purpose? Oh, all flags were removed. They were duplicated on both locations? Weird.

indeed, they existed double, the diff looks weird due to the rename

> 2\. I'd keep the dashboards in the media folder as those dashboards can be managed via UI (uploaded, deleted)

the default dashboards are not manageable via the UI, the moment you edit them, they are stored in a separate dir, see https://github.com/mautic/mautic/blob/d421abdc0e55ab10f2de8283bc8c45b3990061df/app/bundles/DashboardBundle/Config/config.php#L55-L56

> 3\. Double-checking I understand the deleted minified assets. Those are generated with prod assets, right?

correct, you can verify it with running `./bin/console m:a:g` 




> 4\. Does it mean that with the overridable assets this is not a BC break?

correct, except the expected user behaviour somehow changes, so it makes sense to add in a major release

**Review by escopecz — APPROVED** [review]
I followed the steps and all work as described. I've also tried to upload/select images in the GrapesJS builder and they are also available in the Focus Items CK editor image browser. The flags and other core assets are not there anymore which is much cleaner experience. Thank you Mattias! 👍

**Review by RCheesley — APPROVED** [review]
I found a ton of bugs testing this but the PR itself works great:

Check for broken JS/CSS ✅  Found a lot of other bugs but they are present in the 5.x branch!
Test asset override ✅ 
Test mautic:assets:cleanup command ✅ 

Thanks @mollux 🚀

**Pull request merged**
