### PR TITLE
Segment filter 'Asset Downloads' not showing all assets

### PR DESCRIPTION
**Pull request by escopecz**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | No
| Automated tests included? | Yes
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | /
| BC breaks? | No
| Deprecations? | No

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Go to assets and create more than 10 assets(for easiness, have an asset starting with `w/x/y/z` so that it will be the 11th one if sorted)
2. Click on Segments >> New and chose tab "Filters"
3. Select "Asset Downloads" from the combo box
4. Chose 'including' from the operator dropdown box
5. Observe that the first 10 of your assets are listed in the filter next to it. Also notice that the file we mentioned above which starts with `w/x/y/z` is missing from the list
6. Start typing the missing file's name
7. It should now trigger an ajax request and should find the files starting with the searched text

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11002"></a>

### CODE REVIEW

**Comment by jos0405** [comment]
The 11th asset is still not there:

image

image

**Comment by jos0405** [comment]
Sorry, all good, tested wrong. Approved.

image

**Review by jos0405 — APPROVED** [review]
I could confirm the error from before, and this PR fixes it.
Works as described.

image

**Comment by jos0405** [comment]
Before PR
image

**Review by kuzmany — APPROVED** [review]
Works for me 👍

**Pull request merged**
