### PR TITLE
make xhtml tag closure optional

### LINKED ISSUE #9545: Landing page doesn't autofill form with querystring parameters
## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.2.2
| PHP version | 7.2.34

### Steps to reproduce
1. Create form with fields email_address, first_name, last_name

image

2. Create landing page with form embedded

3. Create e-mail with link to landing page
`{pagelink=2}?email_address={contactfield=email}&first_name={contactfield=firstname}&last_name={contactfield=lastname}`

    3a. Attempts to use the URL Encode filter (i.e. `{contactfield=email|true}`) seems to break things as the pipe character is encoded by the page builder.

image

4. Send e-mail, click link.

5. Form does not autofill with query string parameters.

    5a. Assuming maybe URL Encoding with the e-mail address (due to the `@` character) may be an issue, removing that and just going with `?first_name=Shaun&last_name=McPeck` still fails to populate (and hide) the fields for which values were provided.
 
I know the page/email builder is being revamped for a future release, so I know there's not a lot of work being done on that existing code base, but a quick hack that might fix this would be great!  (Also, maybe I'm just missing something and/or doing something wrong so there's a better "do it the right way" fix. 🤣)

Any guidance would be a great help. Cheers!

An old thread that I found didn't seem to have anything helpful for me: https://forum.mautic.org/t/how-to-pass-url-parameters-to-a-form/15315/13

### PR DESCRIPTION
**Pull request by pety-dc**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.2
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | fixes https://github.com/mautic/mautic/issues/9545

#### Description:
Pre-population form fieldy by url parameters is and old feaure and has been broken for quite some time. 
It seems The pre-population takes places by preg-replacing input html tags in the form html. the preg-replace looks for inputs in xhtml format (with `/>` ending) But before that the ˙DomDocument in `extractScriptTag` strips the closures from the inputs. (Probably because the form html does not have doctype and the DomDocument defaults to html5)
This breaks the input replacement.

The fix allows for the enclosure to be optional

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create a form with fields
3. Load the form url with parameters
4. See how the fields are prepopulated by the incoming values.

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by npracht** [comment]
Hi @pety-dc !
It seems being a good fix. Can you tell me more in detail how i can test this please ?
Also, can you have a look at the conflict ?

Thanks !

**Comment by kuzmany** [comment]
I've resolved conflicts, but I don't have permission to push it to this PR
@pety-dc are you able to allow permission? 

image

**Comment by pety-dc** [comment]
@kuzmany I see no such option in the PR page. But I resolved the conflict.

**Review by escopecz — CHANGES_REQUESTED** [review]
Please add a test case in https://github.com/mautic/mautic/blob/features/app/bundles/FormBundle/Tests/Helper/FormFieldHelperTest.php for this. All new PRs must have tests to be merged.

**Comment by escopecz** [comment]
There is a duplicated PR that addresses this and one more bug: https://github.com/mautic/mautic/pull/9550 Maybe we should close this one even if it's older. @pety-dc what are your thoughs?

**Comment by pety-dc** [comment]
I tested my PR to see whether it works with v3.2.2 (it was mentioned in #9550 that it doesn't) 
and it works perfectly as expected.

@escopecz  I thought adding `ready-to-test` would make this PR appear in mautibox. Could you tell me how it works?

**Comment by escopecz** [comment]
cc @heathdutton

**Comment by RCheesley** [comment]
> @escopecz I thought adding `ready-to-test` would make this PR appear in mautibox. Could you tell me how it works?

You just search for the PR number or go direct to https://mautibox.com/9239. We are just doing some maintenance however to upgrade the PHP version since the PR to deprecate 7.2 was recently merged to features, so we may have to wait a bit.

This PR in going to need to be rebased due to the [branch change](https://github.com/mautic/mautic/pull/9239#event-4223755193) but I believe it is on a protected organisation branch so we will need @pety-dc to do the rebasing.

**Comment by dennisameling** [comment]
Hi @pety-dc! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since we don't have access to your branch, could you please click "Update branch" at the bottom of this PR? If that doesn't work, you can also run `git merge upstream/features` locally. Thanks in advance!

image

**Comment by RCheesley** [comment]
We need to add a test [as requested above](https://github.com/mautic/mautic/pull/9239#pullrequestreview-560857782). - @pety-dc can you action that please? I have updated the base to the 4.0 branch, aiming to get this into 4.0.1 at the end of this month if we can get that test written. It may also need rebasing, not sure!

If you have not got the capacity let us know and one of the team will look into it.

**Comment by Tamas-Toth-ebola** [comment]
> We need to add a test [as requested above](https://github.com/mautic/mautic/pull/9239#pullrequestreview-560857782). - @pety-dc can you action that please? I have updated the base to the 4.0 branch, aiming to get this into 4.0.1 at the end of this month if we can get that test written. It may also need rebasing, not sure!
> 
> If you have not got the capacity let us know and one of the team will look into it.

Dear @RCheesley !

We are really glad to hear the acceptance of the PR but sadly @pety-dc currently does not have enough time for the further requirements. If you could wait for him, maybe some more weeks later will be some more quiet period, but now I can not say more accurate. If anyone could help with the missing part that would be really nice.

**Comment by jos0405** [comment]
Seems to be working as expected
image

**Comment by tejasync** [comment]
Hi @pety-dc, I have review and tested this PR, works as expected. To make this PR ready-to-commit, I have added test case, [here](https://github.com/mautic/mautic/compare/4.x...ts-navghane:pre-populate-from-url2?expand=1). Could you please give me access to push?
Screenshot 2021-09-14 at 17 18 36

**Comment by RCheesley** [comment]
@Tamas-Toth-ebola @pety-dc if someone can please pull the test mentioned here which has already been written: https://github.com/mautic/mautic/pull/9239#issuecomment-919077004 then we can get this merged. 

Unfortunately it was made on a private branch which maintainers are prevented from updating, therefore we need someone with access to bring in the test and push to the branch.

**Comment by pety-dc** [comment]
hey @ts-navghane ,
I've merged your branch (https://github.com/ts-navghane/mautic/tree/pre-populate-from-url2) to ours (https://github.com/d-code-ltd/mautic/tree/pre-populate-from-url2)

It says it has conflicts though

**Comment by RCheesley** [comment]
@pety-dc that may be due to the fact that we have merged some other PRs today relating to forms (as the 4.0.1 release is focused on fixing bugs relating to forms).  Sorry!

**Comment by dadarya0** [comment]
@pety-dc could you please resolve conflict or give me push permission ?

https://github.com/mautic/mautic/pull/9550#issuecomment-922828573

**Comment by kuzmany** [comment]
@pety-dc can you look on it?

**Comment by RCheesley** [comment]
Sorry folks, due to the unresolved conflict we will have to remove this from the milestone, which is a shame as it was almost ready to be committed. If this is not in a mergeable state before the 4.1 release on 29th November we will close the PR.

**Comment by andersonjeccel** [comment]
Hey there! Thanks for your contribution to the project. 

Just wanted to let you know that the issue this PR was addressing has actually been fixed in another PR that's already been merged. So, I'm going to go ahead and close this one to avoid any confusion. Really appreciate your effort though! 

Feel free to check out our open issues if you'd like to tackle something else. Thanks again!

**Pull request closed without merging**
