### PR TITLE
Fix report date filter

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
The dates in report filters were convert to UTC format.  This make issue with filtering. 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create custom field: **Test date**
3.  Create contact and fill **Test date** to 26. 1. 2022
4. Make sure your timezone in Configuration is **Europe/Paris** for example
5. Create contacts report with filter  **Test date** equal 26. 1. 2022
6. Before patch your contact is not in report
7. After patch contact go to report properly

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10800"></a>

### CODE REVIEW

**Review by mmarton — COMMENTED** [review]
Tested an can confirm the issue but with datetime type. Date could be also effected if utc and your current date are different

**Comment by kuzmany** [comment]
@mmarton but datetime is store as UTC to db, then we need convert date time in filters to UTC and then compare between them.

**Review by RCheesley — DISMISSED** [review]
Confirmed the issue with the contact not showing up in the report before applying the PR.

After applying, contact is showing as expected!

Thanks for the PR @kuzmany 🎉  🚀

**Comment by RCheesley** [comment]
Would be good to just have a quick code review before merging if that's possible!

**Review by escopecz — APPROVED** [review]
Makes sense. The date field do not have time (obviously) and so the DateTIme object is created with 00:00:00. Once the timezone is changed then the date is switched. It does not make sense to calculate timezone on a date field 👍

**Pull request merged**
