### PR TITLE
Add created and modified data to contact profile

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Just add Created on  and Last modified to contact profile

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Check contact profile - core tab - new data  (Created on, Modified by, Last modified)

image

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11352"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
Looks like there is a failing test to fix @kuzmany :)

**Review by RCheesley — DISMISSED** [review]
Works great, nice addition! Thanks @kuzmany 🚀

**Review by escopecz — DISMISSED** [review]
Nice. Thanks Zdeno! Once you fix the failing test this is ready to go 👍

**Review by escopecz — APPROVED** [review]
Thanks Zdeno!

**Pull request merged**
