### PR TITLE
[UI] Move sidebar header HTML structure to navbar

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

It's a good practice in modern apps to make the header layer be on top of the sidebar layer. This PR makes the header full width on the screen, moving the logo to the header template instead of keeping in the sidebar template.

It also improves the experience on mobile or when you're using Mautic in half of your desktop screen.

### Should I match the old layout (with blue bg) indepedently of the HTML structure? Give your opinion

| Before                                 | After
| -------------------------------------- | ---
|    image                                    | image

Before (mobile)

https://github.com/user-attachments/assets/2f225bfa-7210-45e1-83cc-f30b294921bd

After (mobile)

https://github.com/user-attachments/assets/d46033a9-e5ee-49a2-9782-09312ac7f7e1

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open the Dashboard and check if you can use the sidebar properly.
3. Using your browser's developer tools, activate the mobile mode and check if the sidebar can be accessible and keeps working normally.

### CODE REVIEW

**Review by Esthertests — APPROVED** [review]
LGTM, the white bg is okay and we can keep the new white bg i was checking for accessibility and the color contrast is better.
image
image

**Comment by andersonjeccel** [comment]
@Esthertests Thanks for testing!

**Review by abhisekmazumdar — APPROVED** [review]
A helpful change. LGTM

**Comment by abhisekmazumdar** [comment]
image

**Review by jos0405 — APPROVED** [review]
Looks amazing. Works on mobile perfectly.

image

image

**Pull request merged**
