### PR TITLE
Add missing dist sections

### LINKED ISSUE #7953: Integrity constraint violation when restarting campaign (2.15.1) STALLS CAMPAIGN TRIGGERS!
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Well, I haven't tracked the bug to know when and why is it happening, so I don't know what's the real cause of the error and whether the error occurs every time or there is a special occasion which I don'T know yet.

But I ran into a `Integrity constraint violation` error when a campaign uses `restart`
```
[2019-10-15 08:02:12] mautic.ERROR: CAMPAIGN: An exception occurred while executing 'INSERT INTO campaign_lead_event_log (rotation, date_triggered, is_scheduled, trigger_date, system_triggered, metadata, channel, channel_id, non_action_path_taken, event_id, lead_id, c
ampaign_id, ip_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, "2019-10-15 08:02:12", 1, "2019-10-15 21:00:00", 1, "a:0:{}", null, null, 0, 942, 2529, 58, 24]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '942-2529-1' for
key 'campaign_rotation' [] []
```

FireShot Capture 001 - View - 4 napos inaktív kieső ÉLES - LeadEngine - naplo leadengine hu

The problem is not only that this happens, but this bug stalls the campaign event triggering 

There is a similar issue, but that's related to `jump` event:
https://github.com/mautic/mautic/issues/6613

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2.x
| Browser | 

### Steps to reproduce
The bug is related to campaign restart (rotation), but I don't know the exact way to reproduce it sincs it has occured only one so far.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/82029559-integrity-constraint-violation-when-restarting-campaign-2-15-1-stalls-campaign-triggers?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #7955: Composer Install requires git on server
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
`dist` section is missing in composer.lock file.

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.2.19
| Browser | CLI

### Steps to reproduce
1. Clone ZIP file of version 2.15.3 on GitHub
2. Run `composer install` on shell without having git installed
 
### Log errors
```
[RuntimeException]                                                                                                       
  Failed to clone https://github.com/mautic/intl.git, git was not found, check that it is installed and in your PATH env.  
                                                                                                                           
  sh: 1: git: not found 

[RuntimeException]                                                                                                                           
  Failed to clone https://github.com/mautic/BazingaOAuthServerBundle.git, git was not found, check that it is installed and in your PATH env.  
                                                                                                                                               
  sh: 1: git: not found   
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by flossels**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? |  X
| New feature? | -  
| Automated tests included? | -
| Related user documentation PR URL |  -
| Related developer documentation PR URL |  -
| Issues addressed (#s or URLs) | #7955
| BC breaks? |  -
| Deprecations? | - 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Resolves #7955

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
See: #7955

#### Steps to test this PR:
1. Download ZIP file
2. Try to setup mautic without having git installed

### CODE REVIEW

**Comment by RCheesley** [comment]
Does this need testing, or just code review? I wasn't clear, as it seems to be specifically related to dev install environments being built via composer?

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by npracht** [comment]
Hello @flossels could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback. Thanks !

**Comment by npracht** [comment]
@dennisameling i am sure you have an opinion on that ?

**Comment by flossels** [comment]
on it.

**Comment by npracht** [comment]
Thanks dude !

**Comment by flossels** [comment]
The problem still exists (although in a different kind): 

```
- Installing symfony/intl (v3.4.26): Cloning d2ac837039 

  Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos Head to https://github.com/settings/tokens/newscopes=repo&description=Composer+on+testphp72+2020-06-10+0947 to retrieve a token. It will be stored in "/home/wessels/.composer/auth.json" for future use by Composer.

  [RuntimeException]
  Failed to clone https://github.com/mautic/intl.git, git was not found, check that it is installed and in your PATH env.

  sh: 1: git: not found
```

So it is still not possible to run a "composer install" without git available on the CLI.
I will come up with a new PR for this.

**Comment by npracht** [comment]
You are a 👑

**Comment by dennisameling** [comment]
Closing and re-opening so Travis will run again

**Comment by RCheesley** [comment]
@flossels are you still working on this PR or in another? I was not clear from the comments above.

**Comment by RCheesley** [comment]
Close and reopen for Travis

**Comment by mabumusa1** [comment]
@RCheesley I do not think this PR is relevant if you want to download the zip file directly from the repo that means you want to work the on the staging or `dev` version of it which require `composer` to install packages, and composer by nature require git to clone other repos. 

I never seen projects where they have `composer.lock` as part of the repo

**Comment by RCheesley** [comment]
Bumping to 3.1.1 @flossels if you want this to be considered please take a look at the Travis errors. If we don't hear back we'll close this as it's quite an edge case as mentioned above.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by mabumusa1** [comment]
I was not able to reproduce the issue this PR solve, in order to successfully install Mautic on a server that does not include Git you must use the distributable version which can be found on https://github.com/mautic/mautic/releases/tag/3.1.0.

**Pull request closed without merging**
