### PR TITLE
[rector] Few configuration improvements

### PR DESCRIPTION
**Pull request by TomasVotruba**
Hi, I want to look into the project and help a bit with type coverage :) 

I took the courtesy of upgrading Rector to fresh 0.18, and optimizing config for better performance.
Some sets are very heavy, like UP_TO_* and they should be run just once, to avoid blocking CI or local.

Befor this PR, Rector crashed on my 16 GB RAM machine. Now it's passing well and allows more devs to contribute and make use of it :+1: 

Let me know what you think. 

I want to follow up with more Rector-related PRs to fine tune process and then help with type coverage.

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for the PR @TomasVotruba and welcome to the Mautic community! I've requested reviews from some of the dev team so hopefully we will be able to get this merged promptly!

**Comment by RCheesley** [comment]
@all-contributors please add @TomasVotruba for code

**Comment by TomasVotruba** [comment]
@RCheesley Thank you :wink: , I look forward for next steps :+1:

**Comment by RCheesley** [comment]
Should be able to get eyes on it during our Open Source Friday sprint tomorrow all being well! 🚀

**Review by kuzmany — DISMISSED** [review]
Seems good to me.
Composer install works like before and rector works like charm.
👍

**Comment by escopecz** [comment]
Hey @TomasVotruba! Long time no see :)

Thanks for this update, it looks great! I worry about

> Some sets are very heavy, like UP_TO_* and they should be run just once, to avoid blocking CI or local.

I found them useful when rebasing old PRs to new Symfony version as it did some refactoring for me. I don't see any speed gains when removing this either. When comparing for example with https://github.com/mautic/mautic/pull/12681 it run Rector in 2 minutes, this PR runs it in 3. Is it due to cache invalidation?

**Comment by TomasVotruba** [comment]
Hi Honza, it's hard to miss :)

It's rather best practice, the up to sets should be run just once as they're designed for upgrade. 

The sets that should be run to help with everyday coding are missing here, coming soon. They'll bite bit of permanence.

I'd skip the speed compare now as the memory is more important to be able to run Rector with success 👍

**Comment by escopecz** [comment]
Acquia is currently starting the "Unforking" initiative where we'll be pushing around 400 PRs written for Symfony 3 and 4 and updating them for this 5.x branch that runs on Symfony 5. There are also many old PRs in the open PR backlog that could use the Rector rules. So any help that Rector could give us is greatly appreciated. Also, developers will start updating their Mautic plugins for Mautic 5 and Rector could help there too with Symfony updates. And code reviewers can count on Rector pointing out that some code needs an update to new Symfony version. Many are hard to spot. Like switched params in the `dispatch` method or slightly different namespaces. I think that it has great value in CI. Do you think we can keep the `UP_TO_*` rules for little bit longer?

**Comment by TomasVotruba** [comment]
I see. If that's the case, we can keep it, including a link to some issue to this to have context near.

I'll just comment the set out if crashes my local run.

**Review by escopecz — APPROVED** [review]
Thank you Tomas! I'm OK with this.

@mabumusa1 please give this a review too as it modifies the Doctrine rules you've added recently. OK with you?

**Review by mabumusa1 — APPROVED** [review]
I think this PR is good to go, it removes the rules that we already applied and we do not expect anyone to use the old methods. 

I think it is  good to remove them now since they take sometime to run.

**Comment by mabumusa1** [comment]
Thanks @TomasVotruba and welcome to the community, we hope we can see you more often

**Comment by TomasVotruba** [comment]
Thanks for the merge and welcoming :hugs: 

The faster the feedback loop, the more you'll see me :+1:  I'll keep them coming

**Pull request merged**
