### PR TITLE
Segments form submission filter

### PR DESCRIPTION
**Pull request by alfredoct96**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | features
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              |  N/A
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     |  N/A

#### Description:

Added 5 types of segment filters:
* form submission
* first conversion
* last conversion
* first conversion date
* last conversion date

With "Form Submission" a user can filter by form submission, a segment is populated with all the leads who submitted that form.

With "Last conversion" and "First conversion" a segment is populated with all the leads who submitted that form first (or last) .

With "First conversion date" and "Last conversion date" you can populate the segment filtering with the date of the first submission ( or the last submission).

#### Steps to test this PR:
1. Ensure you have multiple segments with multiple filters already before you check out this PR so you could test that existing segments still work.
2. Once you check out this branch, run the `bin/console mautic:segments:update` command and check that the command worked as before and no contacts were added or removed. The contact count for each existing segment should be the same
3. Edit a segment and check the functionality of the new filters

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/9694"></a>

### CODE REVIEW

**Comment by dennisameling** [comment]
Hi @alfredoct96! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since we don't have access to your branch, could you please click "Update branch" at the bottom of this PR? If that doesn't work, you can also run `git merge upstream/features` locally. Thanks in advance!

image

**Comment by alfredoct96** [comment]
> Hi @alfredoct96! Thanks for your PR  we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since we don't have access to your branch, could you please click "Update branch" at the bottom of this PR? If that doesn't work, you can also run `git merge upstream/features` locally. Thanks in advance!
> 
> image

Done @dennisameling

**Review by kuzmany — CHANGES_REQUESTED** [review]
Nice!
I am gonna test it. 

media/js/app.js should not be part of the PR. It's generated during build package

**Comment by RCheesley** [comment]
@alfredoct96 can you take a look at the feedback regarding media/js/app.js needing to be removed?
Thanks!

**Comment by alfredoct96** [comment]
> @alfredoct96 can you take a look at the feedback regarding media/js/app.js needing to be removed? Thanks!

@RCheesley @kuzmany sure, i did the revert

**Comment by kuzmany** [comment]
@alfredoct96 we've merged to 4.x big  update - segment refactoring https://github.com/mautic/mautic/pull/8649. Then this PR need resolve conflicts

**Comment by alfredoct96** [comment]
> @alfredoct96 we've merged to 4.x big update - segment refactoring #8649. Then this PR need resolve conflicts

This refactor was so much big! i updated my changes, it wasn't easy

**Review by kuzmany — CHANGES_REQUESTED** [review]
We use it on our fork. Seems work pretty good.
But need rebase based on 5.x

**Comment by RCheesley** [comment]
@alfredoct96 could you rebase this to 5.x please?

**Pull request closed without merging**
