### PR TITLE
Create company from ip lookup switch

### PR DESCRIPTION
**Pull request by escopecz**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Enhancement
| Automated tests included? | Y
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | /
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

In PR https://github.com/mautic/mautic/pull/7083 I've added option to create and link a company from IP lookup info to Mautic. It may cause problems as if a contact has a company and nothing else then Mautic considers it as identified contact. That may not be the best option for all users. Therefore this PR adds a new option which will allow users to decide what behavior they want.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. This will be a bit hard to test as only some paid IP lookup services provide the company data and only some IP addresses have it. But if you can then test that IP lookup still works. The change is covered with tests.
3. Check that the new option is in the configuration and you can turn it on and off.

### CODE REVIEW

**Comment by kuzmany** [comment]
Could we add this to 2.15.2? 
For me it's bug fix partially.

**Comment by escopecz** [comment]
We may as well. Because we started to add company from IP lookups recently and did not realize it will have this negative effect which can be considered a BC break.

**Comment by kuzmany** [comment]
Have mautic use it in production already?

**Comment by escopecz** [comment]
Yes, every PR that is submitted by a Mautic Inc. engineer has been reviewed, tested and released to Mautic Cloud instances already.

**Comment by kuzmany** [comment]
@escopecz good to know that 👍

**Comment by kuzmany** [comment]
@escopecz can you look on Scrutinizer  test or commit again for refresh test?

**Comment by escopecz** [comment]
I'm not going to create new bogus commit just to make Scrutinizer workflow to finish. I asked @dbhurley to turn it off for this repository as it causes only confusion and we are not considering its findings anyway. Hopefully he will get to it eventually. Please ignore Scrutinizer.

**Pull request merged**
