### PR TITLE
Fix for pushing to integrations in campaign actions

### LINKED ISSUE #10517: Pushing contact to integration in campaign actions results in a PHP error
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Reported on the forums:

https://forum.mautic.org/t/contact-syncing-from-mautic-to-salesforce-is-not-working-in-mautic-4-latest-stable-release/21065

I was able to reproduce with HubSpot.

There were two contacts in the segment:

ruth.cheesley@MacBookPro-RuthCheesley mautic % ddev exec bin/console m:c:t
Triggering events for campaign 3
Triggering events for newly added contacts
2 total events(s) to be processed in batches of 100 contacts
 2/2 [============================] 100%PHP Warning:  http_build_query() expects parameter 1 to be array, string given in /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php on line 359

Warning: http_build_query() expects parameter 1 to be array, string given in /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php on line 359
PHP Warning:  http_build_query() expects parameter 1 to be array, string given in /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php on line 359

Warning: http_build_query() expects parameter 1 to be array, string given in /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php on line 359

### How can we reproduce this issue?

Step 1: Create a segment with at least one contact in it
Step 2: Set up an integration - HubSpot or Salesforce for example - and map fields First Name, Last Name, Email.
Step 3: Add a campaign action to push to integration
Step 4: Run the crons to build segment, build campaign, trigger campaign
Step 5: Notice error in the command line output

### Relevant log output

```shell
ruth.cheesley@MacBookPro-RuthCheesley mautic % ddev exec bin/console m:c:t
Triggering events for campaign 3
Triggering events for newly added contacts
2 total events(s) to be processed in batches of 100 contacts
 2/2 [============================] 100%PHP Warning:  http_build_query() expects parameter 1 to be array, string given in /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php on line 359

Warning: http_build_query() expects parameter 1 to be array, string given in /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php on line 359
PHP Warning:  http_build_query() expects parameter 1 to be array, string given in /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php on line 359

Warning: http_build_query() expects parameter 1 to be array, string given in /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php on line 359
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by TonyBogdanov**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✅
| New feature/enhancement? (use the a.x branch)      | ❌
| Deprecations?                          | ❌
| BC breaks? (use the c.x branch)        | ❌
| Automated tests included?              | ✅ 
| Related user documentation PR URL      | ❌
| Related developer documentation PR URL | ❌
| Issue(s) addressed                     | Fixes #10517 

### Description

Starting with Mautic 4.0 it is no longer possible to push lead activity to integrations communicating via JSON such as Hubspot (and most likely Salesforce as well).

To reproduce it, follow these steps:

1. Enable the Hubspot integration by switching the plugin on and setting an API key.
2. Enable the *Triggered action push contacts to integration* feature.
3. Create a segment containing some contacts.
4. Run `./bin/console mautic:segments:update` to add the contacts to the segment.
5. Create a campaign using the segment's contacts as source and add a *Push contact to integration* (Hubspot) action.
6. Run `./bin/console mautic:campaigns:rebuild` to rebuild the campaign.
7. Run `./bin/console mautic:campaigns:trigger` to trigger the campaign and *push* the contacts to Hubspot.

At this point you should see the following error in the terminal:

```
Triggering events for campaign 1
Triggering events for newly added contacts
1 total events(s) to be processed in batches of 100 contacts
 1/1 [============================] 100%PHP Warning:  http_build_query() expects parameter 1 to be array, string given in /var/www/localhost/public/vendor/guzzlehttp/guzzle/src/Client.php on line 359
```

This is **NOT** treated as a critical error, so the command will succeed, however, the contact(s) will **NOT** be pushed to Hubspot due to this bug.

After applying this PR, follow the same steps above to trigger push again. This time around you shouldn't see the PHP Warning in the terminal and the contact(s) should now be pushed to Hubspot.

### Developer Description

Some integrations such as Hubspot have an `'encode_parameters' => 'json'` setting, which triggers the parameters being sent in `POST` / `PUT` / `PATCH` requests to be `json_encode`-d: https://github.com/mautic/mautic/blob/5975231722cfde8bdad783b373c70ad20333db37/app/bundles/PluginBundle/Integration/AbstractIntegration.php#L760

That causes a problem when the result is passed to Guzzle's `request` method under key `\GuzzleHttp\RequestOptions::FORM_PARAMS`, because the payload is expected to be an array: https://github.com/mautic/mautic/blob/5975231722cfde8bdad783b373c70ad20333db37/app/bundles/PluginBundle/Integration/AbstractIntegration.php#L829 as per the documentation: https://docs.guzzlephp.org/en/stable/request-options.html#form-params

The above RP addresses this by passing the payload under `\GuzzleHttp\RequestOptions::BODY` instead, **if** the payload is a string, rather than an array.

Tested and working with HubSpot.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10674"></a>

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
The code change is straight forward. The method `makeRequest()` itself is terrible. I wrote some tests to ensure it does what we want. Although the ways the request can be configured is close to infinity 😱 

Thank you @TonyBogdanov! 👍

**Review by escopecz — APPROVED** [review]
Re-approving

**Review by RCheesley — APPROVED** [review]
This worked great for me, with the exception that in dev mode there is the same error (I believe) when you try to add the action to the campaign even with the PR applied, which prevented me from actually setting up the campaign to test. I had to drop out to prod mode to set it up and then back to dev mode to test.

I will raise that as a separate issue so we can merge this PR and deal with that other issue separately.

**Comment by RCheesley** [comment]
@all-contributors please add @TonyBogdanov for code

**Pull request merged**
