### PR TITLE
A user can edit an email or landing page created in Code Mode in the Builder, after she acknowledged the risk

### PR DESCRIPTION
**Pull request by volha-pivavarchyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

As a user I might want to change something in the code mode, but then keep editing my email or landingpage in the builder. 

This PR offer not to block that by default, but enable the user to accept the risk that the builder could change the HTML, and let continue in the builder.
#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a new email or use the existing one
3. Choose the Code Mode
4. Click the builder button
5. The warning message here

  image
7. Click "ok". The builder is opened
8. Click "cansel". The builder is not opened

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11339"></a>

### CODE REVIEW

**Review by RCheesley — APPROVED** [review]
I was a bit confused at first, as we used to use the builder button to open up the code mode editor - but I guess what this is doing is expecting you to be using the Advanced tab to work with code mode, rather than the builder.

If that is the case then it worked great:

https://watch.screencastify.com/v/fY4cylhTX2Z3yCvTMtVi

**Review by jos0405 — APPROVED** [review]
I am also a bit confused, but I understand why it happens. After codemode you have to go back to default blank template.
I wonder if the settings in default template will overwrite changes for people.

https://www.loom.com/share/80f1128f29b94c6e8bb7b85b34ae342f

Anyway, I think it's a good PR and people need it.

**Review by jos0405 — APPROVED** [review]

**Comment by adiux** [comment]
@jos0405  @RCheesley Maybe we can make the message more clear. 

current:
By opening the builder you are leaving Code Mode. The builder might change your HTML code in unexpected ways. Only proceed if you know what you are doing.

new:
By opening the builder, you are leaving Code Mode. The builder might change your HTML code in unexpected ways. Use the Advanced Tab to edit your HTML code.

Would that be more clear?

**Comment by RCheesley** [comment]
> By opening the builder, you are leaving Code Mode. The builder might change your HTML code in unexpected ways. **It is recommended to use the** Advanced Tab to edit your HTML code.

Maybe making it clearer that it's recommended to use the advanced tab, rather than using the builder (the part I added in bold above)? I think that's what we're trying to convey with the warning, is that correct?

**Pull request merged**
