### PR TITLE
Automated testing by Travis-CI integration

### PR DESCRIPTION
**Pull request by PatchRanger**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  |yes 
| BC breaks?    | no
| Deprecations? | no
| Fixed issues  |  no

## Description
Provides Travis-CI integration in order to achieve automated testing.
Please note marks "red X" and "green check" behind each commit of this PR - it means that each of the commits tested separately by Travis-CI and this is how the automated PR testing will look like for each PR of Mautic project after this PR will be merged.

### CODE REVIEW

**Comment by PatchRanger** [comment]
@alanhartless @escopecz Any update? I think this change is very easy to introduce - and has a very large impact as it will force and accelerate testing other PRs. Could you please take a look in order to merge this PR?

**Comment by escopecz** [comment]
Looks good to me. 

If I remember well, we had something like it before and it was failing even if there was no issue with a PR. Maybe it was the reason why it was turned off. Alan might know more about it.

**Comment by alanhartless** [comment]
I don't think we've ever had Travis setup. But we'll slot this for 2.0 where some refactoring will bring better support for automated testing.

**Comment by PatchRanger** [comment]
Ok, so I need to open another PR against 2.0-dev branch, right?

**Comment by PatchRanger** [comment]
@dongilbert Thank you.

**Pull request merged**
