### PR TITLE
Adds support for transliteration of aliases

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**
When creating new forms or new lead fields, the use of cyrillic languages would cause creating the tables or columns in the database to fail at worse, at best cause a random f_string column to be generated.  This PR adds transliteration support for the aliases to ensure they will not cause schema change issues.

**Testing**

Before the PR create a form and use a cyrillic label such as Цель проекта for the form label and create a new field with the same then save. Look at the results table for the form and it should have a name like `form_results_1_` and the column name for the field will be something like `f_56174e763d08f` because the cyrillic letters were all wiped out leaving an empty alias.  Looking at the forms table will also note an empty value for alias.

After the PR, the cyrillic letters should be converted into latin equivalents so that they are better supported across the board.

### CODE REVIEW

**Comment by escopecz** [comment]
I get 
```
500 Internal Server Error - Attempted to load class "InputHelper" from the global namespace. Did you forget a "use" statement for "Mautic\CoreBundle\Helper\InputHelper"?
app/bundles/FormBundle/Views/Builder/form.html.php (line #11):
```

**Comment by alanhartless** [comment]
@escopecz Try it now.

**Comment by escopecz** [comment]
Works now :+1:

**Comment by that0n3guy** [comment]
Have you guys seen this: https://github.com/that0n3guy/transliteration   I think it may work well for this type of thing.  I swiped much of the code from https://www.drupal.org/project/transliteration a while ago.

**Comment by dbhurley** [comment]
+1 works as expected.

**Pull request merged**
