### PR TITLE
Add SMS Properties event

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR added support for additional properties for create/edit SMS added with form.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by mabumusa1** [comment]
@kuzmany what is missing for this PR? I did a code review, it looks good

**Comment by kuzmany** [comment]
@mabumusa1 It's ready to test

**Comment by kuzmany** [comment]
@mabumusa1 I had to rewrite it last week little bit, I am gonna commit changes soon

**Comment by RCheesley** [comment]
@kuzmany I think we're still waiting for the changes here, so I will pull the PR into draft status until you are ready.

**Comment by kuzmany** [comment]
Close at the moment. We will push it again once ready to M5

**Pull request closed without merging**
