### PR TITLE
Fix: Email builders code editor allows to save after closing and reopening

### LINKED ISSUE #11239: Certain scenario causes grapesjs editor manual code edit to break
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

_No response_

### What happened?

Under a specific scenario, the "save" button inside of the grapesjs code editor stops working. (I'm actually running Mautic 4.3.1 but that isn't available in the dropdown on this issue screen.)

### How can we reproduce this issue?

1. Open the grapesjs builder for any mjml email
2. In the grapesjs editor, press the "Edit Code" button
3. Press the save button (which should work and close the modal)
4. Close out of the email
5. Open the grapesjs builder for any **OTHER** mjml email
6. In the grapesjs editor, press the "Edit Code" button
7. Press the save button (which should no longer work and not close the modal)

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/109790907-certain-scenario-causes-grapesjs-editor-manual-code-edit-to-break?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by adiux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ y]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #11239

#### Steps to test this PR:

Reproduce it by:
1. Open the Email Builder
2. Change something in the Code Editor and save it
3. Close the Email Builder
4. Reopen the Email Builder (without saving or anything)
5. Change something in the Code Editor and try to save it.
6. Nothing happens

After applying this PR:
1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open the Email Builder
3. Change something in the Code Editor and save it
4. Close the Email Builder
5. Reopen the Email Builder (without saving or anything)
6. Change something in the Code Editor and save it.
7. Code Editor is closed and change is applied

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11376"></a>

### CODE REVIEW

**Review by RCheesley — APPROVED** [review]
Reproduced the issue in mautic/mautic and the bug is gone when this PR is applied. I tested with both an HTML and MJML theme, and also with landing pages. Thanks @adiux for the PR! :rocket:

**Review by jos0405 — APPROVED** [review]
Yep, this fixes it. Thank you!

**Comment by TechBill** [comment]
It somewhat fixes it and better than it was before but the editor and save button still does stop working after several opening / save / closing requiring to x out editor box and a browser refresh to restore it.  The fix is half and half.  It no longer lock up after the first save but it still lock up after few saves or reopening editor box.

**Review by escopecz — APPROVED** [review]
Code looks good. `static` is not supported by IE but that's alright these days.

**Pull request merged**
