### PR TITLE
If a user tries to upload a file to import contacts and something goes wrong, the user gets a message

### PR DESCRIPTION
**Pull request by volha-pivavarchyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [no]
| New feature/enhancement? (use the a.x branch)      | [yes]
| Deprecations?                          | [no]
| BC breaks? (use the c.x branch)        | [no]
| Automated tests included?              | [no] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
1. Sometimes CSV file upload fails silently. This PR adds a flash message to inform. 
2. When the user tries to upload a large contact CSV file (file is larger than the `upload_max_filesize`), the upload will fail silently in the default dev env config. The introduction text specifies the max amount to upload. 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open the import contact page. The max amount to upload is here.
   image
3. Try uploading a larger file. The flash message is displayed.
  image

### CODE REVIEW

**Comment by jos0405** [comment]
@volha-pivavarchyk ,
Maybe I'm not testing right.
I see only this page if I try to upload a file too large:
image

Missing message:
image

**Comment by volha-pivavarchyk** [comment]
@jos0405 I have it working fine locally and in gitpod. Could you please test in local instance.Do you get the same result. 

image

**Comment by RCheesley** [comment]
Does anyone have a file that can be used for testing with mock data?

**Review by RCheesley — APPROVED** [review]
Thanks for the PR - can confirm the silent failure with the current 5.x branch. Now I see the flash message appear.

🤔 It might be nicer if we could inform the user that the file size was too large, but maybe this is a generic error rather than something specific to this error? If it isn't then I would prefer that we state that they should check the file size - I think that would be more useful to the user rather than a generic message. Is that possible @volha-pivavarchyk ?  Reference: https://wix-ux.com/when-life-gives-you-lemons-write-better-error-messages-46c5223e1a2f from the UI/UX tiger team chat.

**Comment by volha-pivavarchyk** [comment]
This message is displayed when any ajax request is returned with a status error. There are some other similar cases. E.g., the wrong format file is selected for the user's avatar. That's why I added a common message.

I would like notice. The clear message can be displayed for the case of a large file. But we can't get this message in the default instance.
image

We solved this problem by changing the php configuration value.

**Review by mabumusa1 — APPROVED** [review]
I did code review today  and tested this PR yesterday, I think this PR is good to go

**Review by jos0405 — APPROVED** [review]
Works now, thx!

**Pull request merged**
