### PR TITLE
Fix for #7558 - PATCH loses data on contact merge

### PR DESCRIPTION
**Pull request by pjeby**
| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | No
| Automated tests included? | No
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #7558
| BC breaks? | 
| Deprecations? | 

#### Steps to reproduce the bug:
1. Create a new anonymous contact via curl get to /mtc
2. With curl, PATCH the contact to include first name, last name, or other fields, as well as email
3. Create a second anonymous contact via curl get /mtc
4. With curl, PATCH the second contact with the same email used in step 2

Result: the contacts are merged, but the field values created in step 2 will be missing.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Same steps as above, but the field values should remain intact.

### CODE REVIEW

**Comment by dennisameling** [comment]
More detailed steps to test with Mautibox PR 8579 (a recent PR based on the latest commits for 2.16.1):

1. Create a new anonymous contact via curl get to /mtc, so `curl https://mautibox.com/8579/mtc` 
2. Ensure the API is active and Basic Auth is enabled in Configuration > API settings > Enable Basic Auth
3. With curl, PATCH the contact to include first name, last name, or other fields, as well as email, that is:
```
REPLACE {CONTACT_ID} with the contact ID that was just created (Contacts > Toggle anonymous)!
curl -X PATCH https://mautibox.com/8579/api/contacts/{CONTACT_ID}/edit -u admin:mautic --header "Content-Type: application/json" --data '{"firstname": "Dennis", "lastname": "Demo", "email": "dennis@test.org"}'
``` 
4. Create a second anonymous contact via curl get /mtc, so `curl https://mautibox.com/8579/mtc`
5. With curl, PATCH the second contact with the same email used in step 3

Result: the contacts are merged, but the field values created in step 3 will be missing.

Step 1 created https://mautibox.com/8579/s/contacts/view/58, patched in step 3 and firstname + lastname + email are updated. Step 4 created https://mautibox.com/8579/s/contacts/view/59, patched in step 4 and firstname + lastname + email are updated. The contacts are merged into ID 55 (which I created earlier) and data is complete. 

@pjeby are you sure this is still an issue in 2.16.0?

**Comment by dennisameling** [comment]
To do: after the 2.16.1-beta release, check if #7717 introduced a bug like @pjeby mentioned in https://github.com/mautic/mautic/pull/7717#issuecomment-601315360

**Comment by pjeby** [comment]
I just checked - it didn't.  But it also doesn't fix the bug that this one does.

**Comment by pjeby** [comment]
I haven't tested any version of mautic that *doesn't* have this patch, since it was necessary when I created it, and I hadn't seen anything re: the original bug report.  Regarding #7717, I have now confirmed that it does *not* introduce the bug I thought it would...  which is consistent with the hypothesis that the bug *this* PR fixes has already been fixed via some other change since last May.  I will investigate further.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by npracht** [comment]
Hello @pjeby could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback, i would very love to merge it in 3.0.1 if still relevant. Thanks !

**Comment by RCheesley** [comment]
I am not fully clear if this issue remains in 3.0 @pjeby ? Can you take a look (mautibox.com is now running Mautic 3.0) and let us know? Thanks!

**Comment by RCheesley** [comment]
Moving to a later release due to unresolved Travis issues

**Pull request closed without merging**
