### PR TITLE
Update builder.css with Mautic Color Scheme

### LINKED ISSUE #10368: Mautic-themed skin for the GrapesJS builder is missing
## Bug Description
With recent refactoring the mautic-themed skin was lost as the changes were made to the minified files which were subsequently updated.

We need to make a new PR to re-add the styling using the correct files.

### PR DESCRIPTION
**Pull request by alexhammerschmied**
Beautify builder.css for better usability and to see future changes in css with each PR.
Update builder.css with Mautic specific colors for the builder.

#### Description:
The builder.css file was a minified file which didn't make sense - the grapesjs-min.css file gets created with the mautic cache and css is served from there anyway.
For future changes this is easier to compare changes and don't change the whole file (because the minfied file consists of only one line - therefor it is difficult to find the changes in it)

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. create a new email/landingpage and open the builder
3. Play around with the builder functions
4. Everything should be visible and look more Mautic-like

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10431"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
@adiux I'm not sure how far you got down the rabbit hole of having sass files available for compilation but that might impact this PR?

**Comment by alexhammerschmied** [comment]
@RCheesley @adiux yes, i realised that the .min.css files are created from the builder.css rules. which is great. So that is probably only the quick fix for that. Later on it would be nice to provide scss files. With these we could also allow everybody to make their own theme :)

**Comment by alexhammerschmied** [comment]
What shall we do to make this happen? Can I do anything further?

**Comment by adiux** [comment]
@alexhammerschmied we can not change anything in the /dist folder. These files get automatically built with every change. You can use the grapesjs-custom.css thou. It would be amazing if you can convert it to a scss file. Parcel will convert it automatically to a CSS if you change the import in builder.js: 

`import './grapesjs-custom.css';` to `import './grapesjs-custom';`

**Review by adiux — CHANGES_REQUESTED** [review]
change it to the files outside of dist folder. preferably also convert it to a scss file

**Comment by andersonjeccel** [comment]
Hey there! 👋

I noticed this PR has been open for quite a while now (wow, time flies! 🕰️) without any recent activity. Given the age of this PR and the changes that have happened in the project since then, it's probably best to close this one out.

If you still think this change would be valuable, feel free to open a fresh PR with an updated implementation. Otherwise, no worries – thanks for your interest in contributing!

I'll be closing this PR to help keep our project tidy. Thanks for understanding! 😊

**Pull request closed without merging**
