### PR TITLE
Fix empty slots in builder

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/5749
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This is follow up to https://github.com/mautic/mautic/pull/6454 based on this issue https://github.com/mautic/mautic/issues/5749
If  you leave your slots empty, then you can't edit it again. 
This PR added placeholder If slot is empty, then you can edit it.

image

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create email and open builder
2. Add text slot  and remove default text
3. You can edit slot 

#### Steps to test this PR:
1. Repeat all steps
2. See If you can edit slot without content
You can test text, dynamic content and code mode slot.

### CODE REVIEW

**Comment by chriscalabro** [comment]
Works as described when working with text and dynamic content slot types. But when using a code mode slot, the edit icon remains even after I add content to the slot. As in, it's always visible, whether slot contains content or not.

**Comment by kuzmany** [comment]
@chriscalabro Hi, re-test please with last commit

**Comment by moskoweb** [comment]
I think it's best if you leave the icon out of the box, but in the line that is empty, so you can click and edit.

```css
div:empty[data-slot]:before, div.empty[data-slot]:before, .codemodeHtmlContainer:empty:before {
    content: "\f044";
    font: normal normal normal 14px/1 FontAwesome;
    position: absolute;
    left: -1.5em; // left line
    top: 2px;
    color: gray;
    font-size: 1em; // minimal size
}
```

**Comment by YosuCadilla** [comment]
Tested, I can see the placeholders and **I can edit** after saving

**Comment by spatialy** [comment]
Tested and working as expected ... the placeholders are editable when re-editing.

**Pull request merged**
