### PR TITLE
Adding missing tag to the GrapesJs fixture

### LINKED ISSUE #13510: The grapesjs builder is not loading 5.x branch [$100 bounty]
### Mautic Version

5.0.x series

### Way of installing

Other (please specify if relevant in the bug report)

### PHP version

8.2.4

### What happened?

The legacy builder loads by default on the 5.x branch instead of GrapesJS.

### How can we reproduce this issue?

Step 1: Open latest 5.x on gitpod: https://gitpod.io/new/#https://github.com/mautic/mautic/
Step 2: Go to email, select any type and open the builder. Result on screenshot:
image

### How to turn on the GrapesJS
Step 1: Open latest 5.x on gitpod: https://gitpod.io/new/#https://github.com/mautic/mautic/
Step 2: Enable GrapesJS in plugins
Step 3: Remove and rebuild the cache
```
rm -rf var/cache/*
ddev exec php bin/console c:c
```
Step 4: Go to email, select any type and open the builder the GrapesJS should be loaded

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [y]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/issues/13510

#### Description:

The GrapesJS builder wasn't enabled by default in M5 which it should have been. The problem is that the fixture that was suppose to do that wasn't executed on install. It was missing a tag as I [suggested 2 weeks ago](https://github.com/mautic/mautic/issues/13510#issuecomment-2039148508). I was hoping someone will take that knowledge and take the $100 bounty for 1 line change but it seems no one is able to do that for whatever reason 🤷 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. The GrapesJS plugin should be enabled right after installation.
3. The email and landing page builders are opening the GrapesJS builder

### CODE REVIEW

**Review by kuzmany — APPROVED** [review]
Seem OK 👍

**Review by patrykgruszka — APPROVED** [review]
Works great :+1:

**Review by RCheesley — APPROVED** [review]
Works great! Thanks!

**Comment by patrykgruszka** [comment]
Code looks fine

**Pull request merged**
