### PR TITLE
Contact email statistics in lead view

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ N ]
| New feature/enhancement? (use the a.x branch)      | [ N ]
| Deprecations?                          | [ N ]
| BC breaks? (use the c.x branch)        | [ N ]
| Automated tests included?              | [ Y ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR adds few email channel statistics info in contact view:
- Total sent
- Open rate (OR)
- Click-through rate (CTR)
- Click-to-open rate (CTOR)
obraz

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Add new contact and send few emails to generate statistics
3. Open contact view page, statistics should be available as a new tab

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11406"></a>

### CODE REVIEW

**Review by kuzmany — APPROVED** [review]
This PR bring statistics to contact detail page. 
It works as expected.
 
image
 
Probably it deserve more visible place ;)

**Review by RCheesley — APPROVED** [review]
Thanks for the PR @patrykgruszka - agree with @kuzmany that it might be good to surface this in a more public way, but as it stands I think it is a great feature!

screenshot-8080-patrykgruszka-mautic-5t4reh6tokw ws-eu62 gitpod io-2022 08 23-17_27_06

**Comment by patrykgruszka** [comment]
@kuzmany @RCheesley thanks for your review. I have been thinking about placing this data above or below the engagements chart. It's loaded asynchronously so it doesn't slow down the loading time of the main view, but there might be a bit of a jump when the data is fetched. That's why I decided to hide the stats in a collapsible panel. Nevertheless, I'll consult the placement with UX/UI designer. Let me know if you have any ideas.

**Review by jos0405 — APPROVED** [review]
Looks good, works as expected. (Altough queue emailing didn't work for me with Mailhog, but might be another issue.)

**Comment by jos0405** [comment]
@RCheesley can we set as ready to be merged, or @patrykgruszka will make more changes?

**Comment by RCheesley** [comment]
@jos0405 personally I think that it is OK to merge it under the statistics tab as not everyone will be interested in the stats, and then if we want to make it more visible in the future based on feedback we can do that with a new PR. If we do that, we must make sure that it does not have a performance impact, which will take a bit more testing and code review I feel. 

Is that approach OK with you @patrykgruszka or do you have suggestions we can review now for a different placement?

**Comment by patrykgruszka** [comment]
@RCheesley I'm fine with it. Let's rearrange it later

**Pull request merged**
