### PR TITLE
Fix extracting url from plain text

### PR DESCRIPTION
**Pull request by Enc3phale**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | N
| Related user documentation PR URL | N
| Related developer documentation PR URL | N
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/6452
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
URL are not good extracted from plain text.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Apply step from Issue https://github.com/mautic/mautic/issues/6452

#### Steps to test this PR:
1. Apply PR
2. Url is now good

### CODE REVIEW

**Comment by StudioMaX** [comment]
@Enc3phale Travis failing, everything else looks good

**Comment by alanhartless** [comment]
Seems this broke URLs with query parameters. It will only find the base URL now. I'm trying to figure out a fix.

**Comment by mleffler** [comment]
CC: @Woeler @npracht

**Comment by Woeler** [comment]
If Alan is working on a fix and we can have it before tomorrow (because I dont think beta release will go out today, it is 10pm here and we have one crucial pr that needs to get in) then I'll get it in.

**Comment by mleffler** [comment]
The only other alternative is backing it out - not sure if that will cause any BC (or FC in this case :)) issues.  Whatever we feel is safest.  We will stay tuned for Alan :).

**Pull request merged**
