### PR TITLE
Fix reports graph with segment filter

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:
If you use Contact Point Log report, choose segment filter and choose graphs from graph table. 
It return error 

`[2021-11-24 10:37:51] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT DATE_FORMAT(lp.date_added, '%Y-%m-%d') AS date, COUNT(*) AS count FROM lead_points_change_log lp LEFT JOIN leads l ON l.id = lp.lead_id WHERE (lp.date_added IS NULL OR (lp.date_added BETWEEN ? AND ?)) AND ((l.email IS NOT NULL) AND (l.email <> '') AND (s.leadlist_id = ?)) GROUP BY DATE_FORMAT(lp.date_added, '%Y-%m-%d') ORDER BY DATE_FORMAT(lp.date_added, '%Y-%m-%d') ASC LIMIT 8' with params ["2021-11-16 23:00:00", "2021-11-24 09:37:51", "114"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 's.leadlist_id' in 'where clause'" at `

1. Load up [this PR](https://mautibox.com)
2. Create  Contact Point Log report with filter on segment
3. Choose also graphs from graph tab
4. Try save. It return error 500

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10653"></a>

### CODE REVIEW

**Review by annamunk — APPROVED** [review]
Works great! Contact Point Log report can be opened without error.

**Comment by annamunk** [comment]
@RCheesley is there a chance this PR will be merged soon?

**Comment by RCheesley** [comment]
@annamunk it needs to be code reviewed, tested by another tester and rebased before it can be considered for merging, and a duplicate PR made for the 4.4 branch to merge it into a 4.4.x release.

**Comment by kuzmany** [comment]
Close favor to https://github.com/mautic/mautic/pull/12536

**Pull request closed without merging**
