### PR TITLE
Add point field to several places in the app

### PR DESCRIPTION
**Pull request by SamWebmecanik**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | x
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/3822 https://github.com/mautic/mautic/issues/3533 https://github.com/mautic/mautic/issues/967 and a little bit of https://github.com/mautic/mautic/issues/124
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
# Description:
**We globally added the ability to modify the point contact field everywhere in the application.**

## Contact point management
You can now edit the points of a contact while modifying its contact page. Answers to issue https://github.com/mautic/mautic/issues/967

## Campaign point decision & update action
You can now find the contact point field in 2 places in the campaign builder to answer to the need of the issue https://github.com/mautic/mautic/issues/124
* Action: update contact field
* Condition on contact field value

## Synchronize point in CRM plugins
You will now find the point contact field in the CRM field mapping tab. Answers to issue https://github.com/mautic/mautic/issues/3822.
Then you can take action in your CRM depending on the score. Salesmen will be now very happy :)

## Use point in emails as token
Answers to issue https://github.com/mautic/mautic/issues/3533.

## Points in forms
You can now find the contact point field in the form field mapping tab.

---------

⚠️ @alanhartless how could we make it so doctrine is aware of this change, so that we can fix this for all existing instances using the standard doctrine migrations / schema update processes ?

### CODE REVIEW

**Comment by npracht** [comment]
@SamWebmecanik, @thecodeine is gonna make a commit on your PR to add the migration file.

**Comment by mqueme** [comment]
This didn't work for me. Points doesn't appear anywhere.

**Comment by alanhartless** [comment]
@SamWebmecanik What is there to fix? $points is defined in the Lead entity so Doctrine should already handle it.

**Comment by MaxWebmecanik** [comment]
Thanks a lot to @dakkor71 for the migration file! 🎉

**Comment by npracht** [comment]
@mqueme & @alanhartless ready to test ! :)

**Comment by mqueme** [comment]
Points does appear now, after migration. I am not sure about being able to assign a form field to points, it makes the point trigger action somewhat useless. I do see the function of it appearing in campaign decisions  and segment filters, though. I will let @alanhartless weigh in on this.

**Review by alanhartless — APPROVED** [review]
Although I agree with @mqueme that it doesn't quite make sense to having this available in all places we currently have contact fields since we have existing means for adjusting points, I don't see any major issue with it and does add an increased flexibility with points.

**Comment by FelipevDesign** [comment]
Is it possible to reset the points of all contacts at once? Or at least the contacts that I select? I have many contacts and, having changed the strategy, I need to reset the points for most of them.

**Comment by RCheesley** [comment]
@filipelbc this PR was from 2017. Please post your question at https://forum.mautic.org rather than on an old, merged PR. Thanks!

**Pull request merged**
