### PR TITLE
TPROD-337 - MauticFullContactBundle - Convert PHP Templates to Twig Templates

### PR DESCRIPTION
**Pull request by JoshuaEstes**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. 

- On the Contact details page, select "Lookup using FullContact" and verify the template works
- On the Contact list page, select 2 or more contacts and select "Lookup using FullContact" and verify the template works
- Navigate to the Plugins under Settings, select "FullContact" and verify the bottom of the modal renders correctly. This is the section that includes the webhook information

### CODE REVIEW

**Review by LordRembo — COMMENTED** [review]
Tested out in a local installation of Mautic, the templates seem to render as they should.

**Review by mabumusa1 — CHANGES_REQUESTED** [review]
- [X] Show modal for the settings and configurations
- [X] Values in the modal are saved correctly
- [X] Modal for one contact in the contact dashboard works
- [X] Multiple contacts in the contacts dashboard works
- [ ] Values in the modal does not persist, I selected No in the screenshot but after I save it shows yes again
image

**Comment by JoshuaEstes** [comment]
@mabumusa1 "Values in the modal does not persist, I selected No in the screenshot but after I save it shows yes again" This is the same functionality that currently exists. I don't think it should persist that value, however I don't use FullContact so I'm not sure if this would create a better experience or not for the users.

**Comment by mabumusa1** [comment]
> @mabumusa1 "Values in the modal does not persist, I selected No in the screenshot but after I save it shows yes again" This is the same functionality that currently exists. I don't think it should persist that value, however I don't use FullContact so I'm not sure if this would create a better experience or not for the users.

@JoshuaEstes since this is the current behavior, let's get this PR merged

**Review by mabumusa1 — APPROVED** [review]
Works as expected

**Pull request merged**
