### PR TITLE
Anton vlasenko: imports not completing

### PR DESCRIPTION
**Pull request by escopecz**
This is copy of https://github.com/mautic/mautic/pull/9974 that I had to make because it had conflicts and failing tests and @anton-vlasenko deleted his Mautic repo so I had to apply it as a patch, resolve the conflicts and create new PR so we can work on it. Here is the original description:

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Automated tests included? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
It's not possible to import some csv files.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Make sure you are on MySQL 5.7. 
2. Try to import contacts from this file [import-not-completing.zip](https://github.com/mautic/mautic/files/6437629/import-not-completing.zip)  in your newly created instance.
3. Make sure that you mapped all the fields from the csv fields to CS fields: First Name, Last Name, Email, Company Name.
4. The import will stuck.

#### Steps to test this PR:
1. Repeat steps 1-3 from "Steps to reproduce the bug".
2. You should be able to import all the contacts.

#### Other areas of Mautic that may be affected by the change:
1. Only import functionality should be affected.

#### List deprecations along with the new alternative:
No

#### List backwards compatibility breaks:
No

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10744"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
@kuzmany can you please retest after the merge conflicts I resolved? Otherwise it's ready for merge.

**Comment by anton-vlasenko** [comment]
@escopecz Yes, I removed my fork of Mautic when I was cleaning up my GitHub repos.
I promise I'll give myself a few slaps in the face.

**Review by kuzmany — DISMISSED** [review]
All good 👍

**Comment by escopecz** [comment]
Don't be so hard on yourself @anton-vlasenko. We love you even without a fork 😉

**Comment by biozshock** [comment]
Was unable to reproduce. Import finished without any errors.
```
MySQL version 5.7.36
PHP 7.4.26
```

Probably fixed in #9461. `$company` is already the object at the point of the call to `addLeadToCompany`.

**Comment by kuzmany** [comment]
We should need look why after change base need rebase. Does it normal? I think the commit history is the same then does not make sense and still add more work for devs.

**Comment by kuzmany** [comment]
@biozshock  yes, but this PR still bring one improvement to return ORMException If entity is closed. Code review and small test If import works like before and we can go to Ready to commit

https://github.com/mautic/mautic/pull/10744/files#diff-7dd9cc1b2476d838fda48a9a22d1d991d760f5975c4b77e5eb09dc28106dd879R375

**Comment by biozshock** [comment]
@kuzmany Checked out the branch and tested with the import file. Import finished without errors.

**Comment by kuzmany** [comment]
@escopecz need rebase, then we can go to RTC

**Comment by kuzmany** [comment]
@escopecz please rebase it

**Comment by escopecz** [comment]
@kuzmany it's rebased

**Review by kuzmany — APPROVED** [review]

**Comment by kuzmany** [comment]
Based on reviews on old PR https://github.com/mautic/mautic/pull/9974 and review here  - ready to commit

**Pull request merged**
