### PR TITLE
Fix bug with state filter not setting selected value

### PR DESCRIPTION
**Pull request by drmmr763**
Fixes issue where the state filter was dropping the selected value.

### CODE REVIEW

**Comment by dbhurley** [comment]
This was moved (I get the move) but also changed to check the label vs. the value. Is that the intended/desired check?

**Comment by drmmr763** [comment]
Yeah for some reason I decided to check the label, I'm going to change it back to value and see if it works properly. If so I think value is the right thing to check here.

**Comment by drmmr763** [comment]
How to test:

Before patch:
Create list, filter by region / state. Save & close
Edit list, check the state field. It should have dropped your selected value, if you save the empty value will be saved.

After patch:
Editing the list should not drop the state value, and saving will not save an empty value.

**Comment by dbhurley** [comment]
I tested as the instructions stated.

**Test Results**
Result: Success

**Pull request merged**
