### PR TITLE
refactor(phpstan): Remove deprecations related to execute\(\) method

### PR DESCRIPTION
**Pull request by scyzoryck**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Hi! My first PR here. 
Fixes for phpstan errors:
```
Call to deprecated method execute() of class Doctrine\DBAL\Query\QueryBuilder:  
Use {@see executeQuery()} or {@see executeStatement()} instead.                 
```

#### Steps to test this PR:

1. Run phpstan 
2. Run automated tests.

### CODE REVIEW

**Comment by scyzoryck** [comment]
It looks like tests are now passing failing tests are now passing on my local. However I was unable to run all of them :(

**Comment by RCheesley** [comment]
Thanks for the PR @scyzoryck and welcome to the community!

I've set the automated test suite running, and will ping some of the developers to review your proposed changes!

**Comment by scyzoryck** [comment]
Thanks! I will rebase the branch & fix the last issues from tests later today :)

**Review by mabumusa1 — DISMISSED** [review]
I love this PR, it is good to go. 

It was on my pipeline but never had the time to do it.

Thanks @scyzoryck this is a very strong start, we hope we can get more contribution from you

**Comment by mabumusa1** [comment]
@scyzoryck Please fix `CS fixer` then we are good to go, I will ask others to review this PR

**Comment by scyzoryck** [comment]
Thanks for feedback. Rebased & code style fixed. I need to finish setting up environment with docker to have all tests working on my local. :) 
I know it is a lot of changes in different files, but I had no idea how to approach it in the most easy way for code review. If you have any suggestion for the future contributions, let me know! 

Best, scyzoryck.

**Review by escopecz — APPROVED** [review]
I went through the code changes and confirmed that the `executeQuery` method is used for select queries and `executeStatement` method for the insert, update and delete queries.

Since this PR touches every part of Mautic we must trust our test suite to scream if there is something wrong. And it's not screaming, so approving 👍

**Pull request merged**
