### PR TITLE
Fixed CompanyExportTest and LeadExportTest

### PR DESCRIPTION
**Pull request by fedys**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Required: )
#### Description:
Running `\MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\CompanyExportTest` and `\MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\LeadExportTest` isolated (filtered out) do not pass. The reason is that there is a missing CSRF token in the `POST` data.

I also added AppKernel::getProjectDir() method so the value of %kernel.project_dir% parameter returns a proper value.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Running `bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --filter '\\Pipedrive\\Export\\(CompanyExportTest|LeadExportTest)::'` outputs failed tests

#### Steps to test this PR:
1. Running `bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --filter '\\Pipedrive\\Export\\(CompanyExportTest|LeadExportTest)::'` does not output any failed tests

### CODE REVIEW

**Review by dennisameling — COMMENTED** [review]
Can confirm the problem exists:

```
denni@mautic3-web:/var/www/html$ bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --filter '\\Pipedrive\\Export\\(CompanyExportTest|LeadExportTest)::'
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

FPHP Notice:  Undefined offset: 0 in /var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/CompanyExportTest.php on line 91
PHP Notice:  Undefined index: POST/Api/Post/organizations in /var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/CompanyExportTest.php on line 93
FFFFPHP Notice:  Undefined index: DELETE/Api/Delete/organizations/66 in /var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/CompanyExportTest.php on line 248
FPHP Notice:  Undefined offset: 0 in /var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php on line 69
EPHP Notice:  Undefined index: POST/Api/Put/persons in /var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php on line 105
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php on line 107
FPHP Notice:  Undefined offset: 1 in /var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php on line 154
FPHP Notice:  Undefined index: POST/Api/Put/persons in /var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php on line 200
PHP Notice:  Undefined index: POST/Api/Put/persons in /var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php on line 202
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php on line 202
FPHP Notice:  Undefined index: DELETE/Api/Delete/persons/99 in /var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php on line 238
F                                                       11 / 11 (100%)

Time: 3.87 minutes, Memory: 118.00 MB

There was 1 error:

1) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\LeadExportTest::testAddPersonViaPointTrigger
Error: Call to a member function getIntegrationEntity() on null

/var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php:71

--

There were 10 failures:

1) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\CompanyExportTest::testCreateCompanyWhenFeatureIsDisabled
Company failed to be created
Failed asserting that null is not null.

/var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/CompanyExportTest.php:55

2) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\CompanyExportTest::testCreateCompany
Failed asserting that 1 is identical to 0.

/var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/CompanyExportTest.php:95

3) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\CompanyExportTest::testUpdateCompanyWhenFeatureIsDisabled
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'Company Name'
+'New Test Name'

/var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/CompanyExportTest.php:145

4) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\CompanyExportTest::testUpdateCompany
Failed asserting that 1 is identical to 0.

/var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/CompanyExportTest.php:185

5) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\CompanyExportTest::testDeleteCompanyWhenFeatureIsDisabled
Failed asserting that 0 is identical to 1.

/var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/CompanyExportTest.php:218

6) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\CompanyExportTest::testDeleteCompany
Failed asserting that 1 is identical to 0.

/var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/CompanyExportTest.php:250

7) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\LeadExportTest::testUpdatePerson
Failed asserting that 1 is identical to 0.

/var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php:107

8) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\LeadExportTest::testUpdatePersonWithCompanyWhenFeatureIsDisabled
Failed asserting that 'Test' matches expected null.

/var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php:157

9) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\LeadExportTest::testUpdatePersonWithOwner
Failed asserting that 1 is identical to 0.

/var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php:202

10) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\LeadExportTest::testDeletePerson
Failed asserting that 1 is identical to 0.

/var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php:240

ERRORS!
Tests: 11, Assertions: 15, Errors: 1, Failures: 10.

THE ERROR HANDLER HAS CHANGED!
```

After applying this PR, the amount of failures decreased a lot, but I'm still seeing 3 failures:

```
denni@mautic3-web:/var/www/html$ bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --filter '\\Pipedrive\\Export\\(CompanyExportTest|LeadExportTest)::'
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

....FPHP Notice:  Undefined index: DELETE/Api/Delete/organizations/66 in /var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/CompanyExportTest.php on line 240
F....PHP Notice:  Undefined index: DELETE/Api/Delete/persons/99 in /var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php on line 228
F                                                       11 / 11 (100%)

Time: 4.52 minutes, Memory: 314.00 MB

There were 3 failures:

1) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\CompanyExportTest::testDeleteCompanyWhenFeatureIsDisabled
Failed asserting that 0 is identical to 1.

/var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/CompanyExportTest.php:210

2) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\CompanyExportTest::testDeleteCompany
Failed asserting that 1 is identical to 0.

/var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/CompanyExportTest.php:242

3) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\LeadExportTest::testDeletePerson
Failed asserting that 1 is identical to 0.

/var/www/html/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php:230

FAILURES!
Tests: 11, Assertions: 59, Failures: 3.

THE ERROR HANDLER HAS CHANGED!
```

@fedys Do you have any idea what could be wrong here? I also wiped my local database just to be sure, but the same errors happened.

**Comment by fedys** [comment]
@dennisameling I found out that the problem was missing http/https configuration on the test client. It should pass now.

**Comment by dennisameling** [comment]
@fedys Thanks!! The `getProjectDir()` error in Travis is because https://github.com/mautic/mautic/pull/8941 was merged recently which adds the exact same code snippet 😊 would you mind removing this snippet from your code? Thanks again!

**Comment by fedys** [comment]
@dennisameling Just removed. But I removed the one from the staging branch. Do you want me to remove it from my branch instead?

**Comment by dennisameling** [comment]
@fedys the way you did it now is also OK 👍 thanks.

**Review by dennisameling — APPROVED** [review]
Works correctly after applying this PR:

```
dennis@mautic3-web:/var/www/html$ bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --filter '\\Pipedrive\\Export\\(CompanyExportTest|LeadExportTest)::'
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

...........                                                       11 / 11 (100%)

Time: 2.64 minutes, Memory: 316.00 MB

OK (11 tests, 66 assertions)
```

Thanks @fedys!

**Review by RCheesley — APPROVED** [review]
Confirmed the failing test before applying the PR:

```
MacBookAir-RuthCheesley:mautic ruth.cheesley$ bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --filter '\\Pipedrive\\Export\\(CompanyExportTest|LeadExportTest)::'
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

FPHP Notice:  Undefined offset: 0 in /Users/ruth.cheesley/Sites/local.mauticacceptancetests/mautic/plugins/MauticCrmBundle/Tests/Pipedrive/Export/CompanyExportTest.php on line 91
PHP Notice:  Undefined index: POST/Api/Post/organizations in /Users/ruth.cheesley/Sites/local.mauticacceptancetests/mautic/plugins/MauticCrmBundle/Tests/Pipedrive/Export/CompanyExportTest.php on line 93
FFF..PHP Notice:  Undefined offset: 0 in /Users/ruth.cheesley/Sites/local.mauticacceptancetests/mautic/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php on line 69
EPHP Notice:  Undefined index: POST/Api/Put/persons in /Users/ruth.cheesley/Sites/local.mauticacceptancetests/mautic/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php on line 105
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /Users/ruth.cheesley/Sites/local.mauticacceptancetests/mautic/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php on line 107
FPHP Notice:  Undefined offset: 1 in /Users/ruth.cheesley/Sites/local.mauticacceptancetests/mautic/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php on line 154
FPHP Notice:  Undefined index: POST/Api/Put/persons in /Users/ruth.cheesley/Sites/local.mauticacceptancetests/mautic/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php on line 200
PHP Notice:  Undefined index: POST/Api/Put/persons in /Users/ruth.cheesley/Sites/local.mauticacceptancetests/mautic/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php on line 202
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /Users/ruth.cheesley/Sites/local.mauticacceptancetests/mautic/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php on line 202
F.                                                       11 / 11 (100%)

Time: 2.92 minutes, Memory: 281.00 MB

There was 1 error:

1) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\LeadExportTest::testAddPersonViaPointTrigger
Error: Call to a member function getIntegrationEntity() on null

/Users/ruth.cheesley/Sites/local.mauticacceptancetests/mautic/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php:71

--

There were 7 failures:

1) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\CompanyExportTest::testCreateCompanyWhenFeatureIsDisabled
Company failed to be created
Failed asserting that null is not null.

/Users/ruth.cheesley/Sites/local.mauticacceptancetests/mautic/plugins/MauticCrmBundle/Tests/Pipedrive/Export/CompanyExportTest.php:55

2) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\CompanyExportTest::testCreateCompany
Failed asserting that 1 is identical to 0.

/Users/ruth.cheesley/Sites/local.mauticacceptancetests/mautic/plugins/MauticCrmBundle/Tests/Pipedrive/Export/CompanyExportTest.php:95

3) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\CompanyExportTest::testUpdateCompanyWhenFeatureIsDisabled
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'Company Name'
+'New Test Name'

/Users/ruth.cheesley/Sites/local.mauticacceptancetests/mautic/plugins/MauticCrmBundle/Tests/Pipedrive/Export/CompanyExportTest.php:145

4) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\CompanyExportTest::testUpdateCompany
Failed asserting that 1 is identical to 0.

/Users/ruth.cheesley/Sites/local.mauticacceptancetests/mautic/plugins/MauticCrmBundle/Tests/Pipedrive/Export/CompanyExportTest.php:185

5) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\LeadExportTest::testUpdatePerson
Failed asserting that 1 is identical to 0.

/Users/ruth.cheesley/Sites/local.mauticacceptancetests/mautic/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php:107

6) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\LeadExportTest::testUpdatePersonWithCompanyWhenFeatureIsDisabled
Failed asserting that 'Test' matches expected null.

/Users/ruth.cheesley/Sites/local.mauticacceptancetests/mautic/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php:157

7) MauticPlugin\MauticCrmBundle\Tests\Pipedrive\Export\LeadExportTest::testUpdatePersonWithOwner
Failed asserting that 1 is identical to 0.

/Users/ruth.cheesley/Sites/local.mauticacceptancetests/mautic/plugins/MauticCrmBundle/Tests/Pipedrive/Export/LeadExportTest.php:202

ERRORS!
Tests: 11, Assertions: 22, Errors: 1, Failures: 7.

THE ERROR HANDLER HAS CHANGED!
```
After applying the PR:

```
MacBookAir-RuthCheesley:mautic ruth.cheesley$ bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --filter '\\Pipedrive\\Export\\(CompanyExportTest|LeadExportTest)::'
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

...........                                                       11 / 11 (100%)

Time: 3.09 minutes, Memory: 369.00 MB

OK (11 tests, 66 assertions)

THE ERROR HANDLER HAS CHANGED!
```

**Pull request merged**
