### PR TITLE
Optimize segment load query

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ N ]
| New feature/enhancement? (use the a.x branch)      | [ N ]
| Deprecations?                          | [ N ]
| BC breaks? (use the c.x branch)        | [ N ]
| Automated tests included?              | [ N ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Using forced index search in `SegmentContactsLineChartQuery::getFirstDateAddedSegmentEventLog` can significantly improve segment view load time.

Tests on table `mc_lead_event_log` with ~69 mln records:
```
MariaDB [mautic]> SELECT el.date_added - INTERVAL 10 SECOND FROM mc_lead_event_log el WHERE (el.object = 'segment') AND (el.bundle = 'lead') AND (el.object_id = 1104) ORDER BY el.date_added ASC LIMIT 1;
+------------------------------------+
| el.date_added - INTERVAL 10 SECOND |
+------------------------------------+
| 2022-01-13 14:15:10                |
+------------------------------------+
1 row in set (1 min 2.502 sec)

MariaDB [mautic]> SELECT el.date_added - INTERVAL 10 SECOND FROM mc_lead_event_log el FORCE INDEX (mc_IDX_SEARCH) WHERE (el.object = 'segment') AND (el.bundle = 'lead') AND (el.object_id = 1104) ORDER BY el.date_added ASC LIMIT 1;
+------------------------------------+
| el.date_added - INTERVAL 10 SECOND |
+------------------------------------+
| 2022-01-13 14:15:10                |
+------------------------------------+
1 row in set (3.180 sec)
```

#### Steps to test this PR:

1. This test makes sense on huge mautic database
2. Open large segment view in Mautic panel before applying changes from this PR and note loading time
3. Apply changes from this PR
4. Open again same segment and compare loading times

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
Thanks for the benchmark! Looks good 👍

**Comment by RCheesley** [comment]
@jos0405 @mabumusa1 @mollux do you have some large test databases you could check this one on?

**Comment by jos0405** [comment]
Sorry, only 400k is the largest - would it make sense to test?

**Comment by MadlenF** [comment]
Hi there, I tested this PR with 40k contacts which was not enough to see any difference.

**Pull request merged**
