### PR TITLE
Import events

### PR DESCRIPTION
**Pull request by escopecz**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Enhancement
| Automated tests included? | /
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | /
| BC breaks? | N
| Deprecations? | `getObjectFromRequest`

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

⚠️ ~This PR depends on changes in https://github.com/mautic/mautic/pull/8828 and therefore it can be tested only after https://github.com/mautic/mautic/pull/8828 is merged.~

The import feature used for companies and contacts was partly ready for any other entity import. At least from the database schema point of view. But in the code the 2 were hard-coded. This PR moves code specific for contacts and companies to listeners. Any other bundle or plugin can then use the same events to subscribe for the import feature.

#### Steps to test this PR:
1. Make sure that the contact and company import works the same as before.

### CODE REVIEW

**Comment by escopecz** [comment]
Tests are failing because this PR depends on https://github.com/mautic/mautic/pull/6875 which must be merged first.

**Comment by dongilbert** [comment]
+1, except for the failing tests, which will be resolved when the other Pr is merged.

**Review by dongilbert — DISMISSED** [review]

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by anton-vlasenko** [comment]
After merging this PR we will have to test if there is a bug with the import described here: https://github.com/mautic/mautic/pull/8631.
If there is a bug we will have to merge https://github.com/mautic/mautic/pull/8631 too.
https://github.com/mautic/mautic/pull/8631 is blocked by this PR.

**Comment by dongilbert** [comment]
@alanhartless This can't really be merged until #6875 as that PR fixes the failing tests here (not sure why that's the case @escopecz)

@escopecz I've tried rebasing to 3.x but the changes are quite complex and I don't want to make the wrong merge choices. I think you're the best one to rebase this to 3.x

**Comment by RCheesley** [comment]
Bumping to 3.2 due to blocking PR not being ready to be merged.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Pretty sure that this is going to need a rebase @escopecz

**Review by kuzmany — CHANGES_REQUESTED** [review]
This error happen on after submit import file for contacts

> Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "mautic_contact_import_action" as such route does not exist.

```
/var/cache/dev/appDevDebugProjectContainerUrlGenerator.php:557 at
/vendor/symfony/routing/Router.php:240 at appDevDebugProjectContainerUrlGenerator -> generate ( 'mautic_contact_import_action', array('objectAction' => 'cancel', 'object' => 'contacts'), '1' )
/vendor/symfony/framework-bundle/Templating/Helper/RouterHelper.php:44 at Symfony\Component\Routing\Router -> generate ( 'mautic_contact_import_action', array('objectAction' => 'cancel', 'object' => 'contacts'), '1' )
/app/bundles/LeadBundle/Views/Import/progress.html.php:73 at Symfony\Bundle\FrameworkBundle\Templating\Helper\RouterHelper -> path ( 'mautic_contact_import_action', array('objectAction' => 'cancel', 'object' => 'contacts') )
/app/bundles/CoreBundle/Templating/Engine/PhpEngine.php:156 at require ( '/var/app/current/code/pulls/7308/app/bundles/LeadBundle/Views/Import/progress.html.php' )
/vendor/symfony/templating/PhpEngine.php:78 at Mautic\CoreBundle\Templating\Engine\PhpEngine -> evaluate ( null, array('app' => object(GlobalVariables), 'progress' => object(Progress), 'import' => object(Import), 'complete' => false, 'failedRows' => null, 'objectName' => 'mautic.lead.leads', 'indexRoute' => 'mautic_contact_index', 'indexRouteParams' => array(), 'currentRoute' => '/7308/s/contacts/import/new', 'mauticContent' => 'leadImport', 'mauticTemplate' => 'MauticLeadBundle:Import:progress.html.php', 'view' => object(PhpEngine)) )
/app/bundles/CoreBundle/Templating/Engine/PhpEngine.php:128 at Symfony\Component\Templating\PhpEngine -> render ( 'MauticLeadBundle:Import:progress.html.php', array('app' => object(GlobalVariables), 'progress' => object(Progress), 'import' => object(Import), 'complete' => false, 'failedRows' => null, 'objectName' => 'mautic.lead.leads', 'indexRoute' => 'mautic_contact_index', 'indexRouteParams' => array(), 'currentRoute' => '/7308/s/contacts/import/new', 'mauticContent' => 'leadImport', 'mauticTemplate' => 'MauticLeadBundle:Import:progress.html.php') )
/vendor/symfony/templating/DelegatingEngine.php:41 at Mautic\CoreBundle\Templating\Engine\PhpEngine -> render ( 'MauticLeadBundle:Import:progress.html.php', array('progress' => object(Progress), 'import' => object(Import), 'complete' => false, 'failedRows' => null, 'objectName' => 'mautic.lead.leads', 'indexRoute' => 'mautic_contact_index', 'indexRouteParams' => array(), 'currentRoute' => '/7308/s/contacts/import/new', 'mauticContent' => 'leadImport', 'mauticTemplate' => 'MauticLeadBundle:Import:progress.html.php') )
/vendor/symfony/framework-bundle/Controller/ControllerTrait.php:262 at Symfony\Component\Templating\DelegatingEngine -> render ( 'MauticLeadBundle:Import:progress.html.php', array('progress' => object(Progress), 'import' => object(Import), 'complete' => false, 'failedRows' => null, 'objectName' => 'mautic.lead.leads', 'indexRoute' => 'mautic_contact_index', 'indexRouteParams' => array(), 'currentRoute' => '/7308/s/contacts/import/new', 'mauticContent' => 'leadImport') )
/app/bundles/CoreBundle/Controller/CommonController.php:377 at Symfony\Bundle\FrameworkBundle\Controller\Controller -> renderView ( 'MauticLeadBundle:Import:progress.html.php', array('progress' => object(Progress), 'import' => object(Import), 'complete' => false, 'failedRows' => null, 'objectName' => 'mautic.lead.leads', 'indexRoute' => 'mautic_contact_index', 'indexRouteParams' => array(), 'currentRoute' => '/7308/s/contacts/import/new', 'mauticContent' => 'leadImport') )
/app/bundles/CoreBundle/Controller/CommonController.php:210 at Mautic\CoreBundle\Controller\CommonController -> ajaxAction ( array('viewParameters' => array('progress' => object(Progress), 'import' => object(Import), 'complete' => false, 'failedRows' => null, 'objectName' => 'mautic.lead.leads', 'indexRoute' => 'mautic_contact_index', 'indexRouteParams' => array(), 'currentRoute' => '/7308/s/contacts/import/new', 'mauticContent' => 'leadImport'), 'contentTemplate' => 'MauticLeadBundle:Import:progress.html.php', 'passthroughVars' => array('activeLink' => '#mautic_contact_index', 'mauticContent' => 'leadImport', 'route' => '/7308/s/contacts/import/new', 'step' => '3', 'progress' => object(Progress))) )
/app/bundles/LeadBundle/Controller/ImportController.php:502 at Mautic\CoreBundle\Controller\CommonController -> delegateView ( array('viewParameters' => array('progress' => object(Progress), 'import' => object(Import), 'complete' => false, 'failedRows' => null, 'objectName' => 'mautic.lead.leads', 'indexRoute' => 'mautic_contact_index', 'indexRouteParams' => array(), 'currentRoute' => '/7308/s/contacts/import/new', 'mauticContent' => 'leadImport'), 'contentTemplate' => 'MauticLeadBundle:Import:progress.html.php', 'passthroughVars' => array('activeLink' => '#mautic_contact_index', 'mauticContent' => 'leadImport', 'route' => '/7308/s/contacts/import/new', 'step' => '3', 'progress' => object(Progress))) )
/app/bundles/LeadBundle/Controller/ImportController.php:445 at Mautic\LeadBundle\Controller\ImportController -> newAction ( '0', true )
/app/bundles/CoreBundle/Controller/CommonController.php:456 at Mautic\LeadBundle\Controller\ImportController -> newAction ( '0', '' )
/vendor/symfony/http-kernel/HttpKernel.php:151 at Mautic\CoreBundle\Controller\CommonController -> executeAction ( 'new', '0', '0', '' )
/vendor/symfony/http-kernel/HttpKernel.php:68 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '1' )
/vendor/symfony/http-kernel/Kernel.php:200 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '1', true )
/app/AppKernel.php:104 at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), '1', true )
/app/middlewares/CORSMiddleware.php:91 at AppKernel -> handle ( object(Request), '1', true )
/app/middlewares/CatchExceptionMiddleware.php:43 at Mautic\Middleware\CORSMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/Dev/IpRestrictMiddleware.php:64 at Mautic\Middleware\CatchExceptionMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/VersionCheckMiddleware.php:67 at Mautic\Middleware\Dev\IpRestrictMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/TrustMiddleware.php:51 at Mautic\Middleware\VersionCheckMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23 at Mautic\Middleware\TrustMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/run/src/Stack/run.php:13 at Stack\StackedHttpKernel -> handle ( object(Request) )
/index_dev.php:25 at Stack\run ( object(StackedHttpKernel) )
/index.php:6 at require_once ( '/var/app/current/code/pulls/7308/index_dev.php' )
```

**Comment by escopecz** [comment]
Thanks for the test @kuzmany! This PR still had some pre-M3 issues. It all works according to my tests now.

**Review by kuzmany — DISMISSED** [review]
This is nice PR to allow use import feature to any plugin. 
Works for me, code looks good 👍

**Review by kuzmany — DISMISSED** [review]

**Comment by RCheesley** [comment]
@escopecz when I check out this PR and go to contacts > import and companies > import the following error is being thrown:

```
[2021-05-15 18:52:31] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Argument 1 passed to "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" must be an instance of "Symfony\Component\EventDispatcher\Event", "Mautic\LeadBundle\Event\ImportInitEvent" given." at /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php line 154 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to \"Symfony\\Component\\EventDispatcher\\EventDispatcherInterface::dispatch()\" must be an instance of \"Symfony\\Component\\EventDispatcher\\Event\", \"Mautic\\LeadBundle\\Event\\ImportInitEvent\" given. at /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:154)
[stacktrace]
#0 /var/www/html/app/bundles/LeadBundle/Controller/ImportController.php(780): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch(Object(Mautic\\LeadBundle\\Event\\ImportInitEvent), Object(Mautic\\LeadBundle\\Event\\ImportInitEvent))
#1 /var/www/html/app/bundles/LeadBundle/Controller/ImportController.php(174): Mautic\\LeadBundle\\Controller\\ImportController->dispatchImportOnInit()
#2 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(458): Mautic\\LeadBundle\\Controller\\ImportController->newAction(0, '')
#3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(158): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('new', 0, 0, '')
#4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#5 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#6 /var/www/html/app/AppKernel.php(104): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#7 /var/www/html/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#8 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#9 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(61): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#10 /var/www/html/app/middlewares/VersionCheckMiddleware.php(67): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 /var/www/html/app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#14 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#15 {main}
"} 
```

Looks like maybe the PR might need some work doing before we can consider it for merging.

**Comment by dadarya0** [comment]
> @escopecz when I check out this PR and go to contacts > import and companies > import the following error is being thrown:
> 
> ```
> [2021-05-15 18:52:31] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Argument 1 passed to "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" must be an instance of "Symfony\Component\EventDispatcher\Event", "Mautic\LeadBundle\Event\ImportInitEvent" given." at /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php line 154 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to \"Symfony\\Component\\EventDispatcher\\EventDispatcherInterface::dispatch()\" must be an instance of \"Symfony\\Component\\EventDispatcher\\Event\", \"Mautic\\LeadBundle\\Event\\ImportInitEvent\" given. at /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:154)
> [stacktrace]
> #0 /var/www/html/app/bundles/LeadBundle/Controller/ImportController.php(780): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch(Object(Mautic\\LeadBundle\\Event\\ImportInitEvent), Object(Mautic\\LeadBundle\\Event\\ImportInitEvent))
> #1 /var/www/html/app/bundles/LeadBundle/Controller/ImportController.php(174): Mautic\\LeadBundle\\Controller\\ImportController->dispatchImportOnInit()
> #2 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(458): Mautic\\LeadBundle\\Controller\\ImportController->newAction(0, '')
> #3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(158): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('new', 0, 0, '')
> #4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
> #5 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
> #6 /var/www/html/app/AppKernel.php(104): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
> #7 /var/www/html/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
> #8 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
> #9 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(61): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
> #10 /var/www/html/app/middlewares/VersionCheckMiddleware.php(67): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
> #11 /var/www/html/app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
> #12 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
> #13 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
> #14 /var/www/html/index_dev.php(25): Stack\
> un(Object(Stack\\StackedHttpKernel))
> #15 {main}
> "} 
> ```
> 
> Looks like maybe the PR might need some work doing before we can consider it for merging.

@RCheesley Now PR is working.

**Review by kuzmany — DISMISSED** [review]
Test both : contacts and companies import works properly 👍

**Comment by RCheesley** [comment]
Looks like we have a conflicting file to be resolved now

**Pull request merged**
