### PR TITLE
Devices and Push devices tab to contacts detail

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Just added another tabs to contacts detail.
Missing info about contact devices and also about push ids related to this PR https://github.com/mautic/mautic/pull/5286

#### Steps to test this PR:
1. Go to lead detail and see new tabs 

Devices
image

Push devices
image

### CODE REVIEW

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by dbhurley** [comment]
From a UI perspective I'm not a fan of adding 2 additional tabs to this view, and due to their similarities I think we can probably accomplish this with one instead. Overall I absolutely like this addition.

**Comment by kuzmany** [comment]
Label: WIP

**Comment by kuzmany** [comment]
Label: Pending feedback

**Comment by kuzmany** [comment]
@dbhurley 
just confirm please. Can I create one tab (Devices) and user tabs in tab like example on this picture?

image

**Comment by mleffler** [comment]
Hi - moving to 2.14, because this is a feature request, and 2.13.1 should be as small as possible, and reactive to issues.

**Comment by dbhurley** [comment]
@kuzmany - no we don't do tabs in tabs

**Comment by kuzmany** [comment]
@dbhurley If no, then what? Just two tables  or something else?

**Comment by dbhurley** [comment]
No, you're not thinking about it right, there is only the need for one tab (if any, as I still question the relevancy of this feature at all). In one tab simply have a column that denotes the data for a push device. These are all devices there is no need in my opinion to separate them out into different tabs, making the user click around to try and find the same type of data.

**Comment by kuzmany** [comment]
If It's not relevant, please close it. 
I don't wanna rework it until you or @alanhartless confirm final way to finish it.

**Comment by alanhartless** [comment]
To me, this feels like something that should simply be added to the contact's History (timeline) tab. If it's date based and just FYI type stuff, the History tab is where it should go. It decreases UI clutter and makes it consumable through the UI and API. @dbhurley thoughts on that?

**Comment by kuzmany** [comment]
@alanhartless I agree with you. Then I will focus on finish my other  PRs, and maybe in future I will look on it.  Now I would mark it as stale.

Just fast question: It's possible now easy extend contact's tab sections by plugin?

**Comment by kuzmany** [comment]
@alanhartless that looks good ;) Thanks

**Comment by dbhurley** [comment]
Thanks @alanhartless - History timeline was exactly what I was thinking as well.

**Comment by kuzmany** [comment]
Close it. If somebody want  It's possible  easy  add device info to timeline as event (see conversation)
Code is still available as closed PR, everybody can use it as plugin, or as patch to Mautic.
Thanks guys.

**Pull request closed without merging**
