### PR TITLE
Fix gated video on landing page preview

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for 4.0
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:

Gated video is not display on preview of landing page, because it require mtc.js tracking code. 
My idea is placeholder on preview page

image

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create landing page
3. Create gated video
4. Check preview
5. You see nothing
6. After PR you see placholder

image

### CODE REVIEW

**Review by RCheesley — APPROVED** [review]
Looks good to me and makes sense.

Before the PR nothing is showing on page preview: 

screenshot-mautic4 ddev site-2021 05 25-20_25_55

After applying the PR the image that shows in the builder is shown as a placeholder:

screenshot-mautic4 ddev site-2021 05 25-20_26_35

Video works great and gated video popup still works as expected.

Just need a code review and then we will be good to go!

**Review by npracht — APPROVED** [review]
Also works for me 👍🏽

**Review by shinde-rahul — APPROVED** [review]
It worked as mentioned in the description. And the code LGTM!

**Comment by RCheesley** [comment]
@all-contributors please add @shinde-rahul for userTesting

**Pull request merged**
