### PR TITLE
Fix: Integration Campaign Members List issue

### LINKED ISSUE #12024: Integration Campaign Members not showing names in select list
### Mautic Version

4.4.x series

### PHP version

8.0.27

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What happened?

When trying to configure Mautic with the Salesforce integration we have issues with the “Integration Campaign Members” filter in segments where it is not filling in with our Salesforce campaigns. In the dropdown, it repeats Value and Label to choose from with increasing numbers 0-1999, shown below.
Screenshot 2023-02-23 164851

### How can we reproduce this issue?

Step 1: Configure salesforce integration plugin
Step2: Go to segments 
Step 3: Create new segment
4: Choose filter.
5: Select filter "Integration Campaign Members"
6: See select with 0 > Label and Value as seen in screenshot

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/121828491-integration-campaign-members-not-showing-names-in-select-list?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by irfanhanfi**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [4.4 ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #12024 

#### Description:
Fixes the Integration Campaign Members DropDown list issue as described here - https://github.com/mautic/mautic/issues/12024

### CODE REVIEW

**Comment by mabumusa1** [comment]
@irfanhanfi I am not sure if this PR is merged with `5.x`, can you assist me with this?

We need to make sure that we apply the same PRs on 4.4 and 5.x

**Comment by irfan-synerzip** [comment]
@mabumusa1 I just tested this on `5.x` and we need the same changes there as well.

**Comment by escopecz** [comment]
Please fix the CS fix check

**Comment by escopecz** [comment]
We'll also need a duplicate PR for the 5.x branch in order to merge this into Mautic 4.

**Comment by irfanhanfi** [comment]
> We'll also need a duplicate PR for the 5.x branch in order to merge this into Mautic 4.

Here is the 5.x PR - https://github.com/mautic/mautic/pull/12141

**Review by escopecz — APPROVED** [review]
The code change makes sense for fixing the bug 👍

**Review by MadlenF — APPROVED** [review]
We have that one in production and it works as expected!

**Pull request merged**
