### PR TITLE
Add close PR workflow and readme files for mirror repos of plugins and themes

### PR DESCRIPTION
**Pull request by RCheesley**
This PR:

- Adds a GitHub Actions workflow which will be executed if a PR is raised against a mirror repo, closing the PR and directing people to the relevant folder on mautic/mautic to make their contribution
- Adds a README.md where missing, informing folks that it is a mirror repo and telling them where to contribute changes

No testing is required, just code review from the core team to check the GitHub Actions / readme files as this does not impact Mautic itself, only our mirrored repos.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11023"></a>

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
Looks good 👍

**Comment by escopecz** [comment]
@RCheesley can you please try to rebase this on top of 4.x and change the base branch for this PR? I tried to do that but got a lot of conflicts. So I tried cherry-picking the commits as it has never failed me so far but I got the same bunch of conflicts when cherry-picking the last commit. I don't understand what's wrong. The closest I got is https://github.com/mautic/mautic/compare/4.x...escopecz:11023-test2?expand=1. But can you try yourself before I throw out my local repo and start over? That's the only option I haven't tried.

**Comment by RCheesley** [comment]
Oof, I get a whole tonne of conflicts too, whether I rebase or merge 4.x. How weird, this PR is only changing the github workflow and readmes! I think it's easier just to make a new PR to be honest.

**Comment by RCheesley** [comment]
Closing in favour of #11154

**Pull request closed without merging**
