### PR TITLE
Segment public name property for preference center

### PR DESCRIPTION
**Pull request by patrykgruszka**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | N
| Automated tests included? | N
| Related user documentation PR URL | N
| Related developer documentation PR URL | N
| Issues addressed (#s or URLs) | N
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR added new segment property - public name which is visible in preference center. Includes migration that sets Public name with same value as Name. Public name value is not required and 

image

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Run `php app/console doctrine:migrations:migrate`
3. Create segment with different Name and Public name
4. Activate segment Available in Preference Center option 
5. Activate preferences center, send mail with unsubscribe link
6. Open contact preferences center (click unsubscribe link)
7. In preferences center should appear public segment name

### CODE REVIEW

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by patrykgruszka** [comment]
Hi @npracht, this PR is adapted to version 3 and ready to merge.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@patrykgruszka thanks for submitting the PR - what a useful feature!

In order for us to consider this for merging in 3.2 we will require you to sign the Contributors Agreement - please see the link above in the comments. This is a one-time thing that all contributors need to do, once it's signed we can accept all your PR's going forward.

We will then need to get it tested and should be able to get it merged with the next minor release at the end of November.

**Comment by RCheesley** [comment]
@cla-bot check

**Review by kuzmany — DISMISSED** [review]
Works good 👍 
Code looks good as well
Migration works

**Review by RCheesley — DISMISSED** [review]
@patrykgruszka looks like we need to rebase against staging for this one - can you take a look? We will also need a PR to the documentation page on segmentation explaining how to use this feature - https://github.com/mautic/mautic-documentation/blob/master/pages/09.contacts/03.manage-segments/docs.en.md here is the file to edit.

I was able to test this up to checking it appearing on the landing page, as I can't edit the settings on Mautibox (settings which are system-set are getting cleared so you cannot save the settings).

Based on other +1's I'm good with getting this merged providing Codecov passes after a rebase and the documentation PR is made.

**Review by RCheesley — DISMISSED** [review]
Great PR, really helpful for the preference centre!

Tested with the PR applied and confirm that the migration set the public name automatically to the segment's name, and that when I changed this it showed in the preference centre:

screenshot-local mautic3-2020 11 21-16_38_07

screenshot-local mautic3-2020 11 21-16_36_02

Nice feature!

**Review by RCheesley — APPROVED** [review]

**Pull request merged**
