### PR TITLE
"Reply To" Address Should Default to the "From Address" In Email Advanced Tab

### PR DESCRIPTION
**Pull request by tejasync**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | N.A. 
| Related developer documentation PR URL | N.A. 
| Issue(s) addressed                     | N.A. 

#### Description:
If a "from" email address field is specified in the advanced tab of the email but the "reply to" email address field is blank, the "reply to" will default be the global sender email address specified in Configuration -> Email settings.
If a "from" email address field is specified in advanced tab AND "reply to" is blank, "reply to" should default to the "from" email specified in the advanced tab and not the global default sender email address.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Check default email address in configuration -> email settings
3. Open an email and change the "from" email address in the advanced tab but leave the "reply to" field blank
4. Send test email OR send email using a campaign
5. Reply to the email sent and observe that the "reply to" is not the same as the sender email
6. "Reply to" email should be "from" email address

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10471"></a>

### CODE REVIEW

**Review by kuzmany — DISMISSED** [review]
Works as expected.
Unit test include

Approve 👍

**Comment by jos0405** [comment]
Tested, works as expected

**Comment by npracht** [comment]
@jos0405 when you proceed your tests, please clic the Files Changed tab and start a review (approved or not). It's easier to follow after 🚀

**Comment by npracht** [comment]
@ts-navghane can you rebase against 4.0 branch please ?

**Comment by tejasync** [comment]
> @ts-navghane can you rebase against 4.0 branch please ?

@npracht Is it 4.x or 4.0? I just rebased with 4.0 and I can see a whole lot of unintended changes in the PR.

**Comment by mohit-rocks** [comment]
@npracht @ts-navghane As this is a new feature, I think we should target `4.x `and rebase with `4.x.`
Rebasing it into 4.0 will create a huge diff here.

**Comment by tejasync** [comment]
> @npracht @ts-navghane As this is a new feature, I think we should target `4.x `and rebase with `4.x.`
> 
> Rebasing it into 4.0 will create a huge diff here. 

@mohit-rocks That's what I initially thought. Thank you for confirming it. If you know, what would be the right way to revert the last rebase with 4.0 so, I can rebase it with 4.x?

**Comment by RCheesley** [comment]
Looks like we have a PHPSTAN issue to fix here before we can merge @ts-navghane - we bumped up the level this week so that's probably why!  Could you take a look?

cc @escopecz

**Pull request merged**
