### PR TITLE
Use ajax to populate email counts to prevent timeouts for loading the page

### PR DESCRIPTION
**Pull request by alanhartless**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? |  y
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

If there are a lot of counts (pending, sent, read, etc) for an email and a lot of emails per page, the page may timeout waiting to load all the counts. This PR changes it to load the page then use ajax to update the counts one email at a time to prevent this time out.

[//]: # ( As applicable: )
#### Steps to test this PR:
1. View the emails page
2. Watch the counts update and they should be appropriate for the email

### CODE REVIEW

**Comment by matishaladiwala** [comment]
works for me!

**Comment by Gregy** [comment]
The error in production was caused by out-of-date production assets. The error in dev mode remains. It appears roughly every 3rd reload (race condition?)

**Comment by Gregy** [comment]
One more note. Would it be possible to reserve the width for the badges in the table before the badges are loaded? Right now the whole table jumps around as the items are loaded and change size.

**Comment by Gregy** [comment]
Good to go. Issues resolved.

**Pull request merged**
