### PR TITLE
Configured form results email to send separate email to lead if applicable

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**

When using the form results action and send a copy to lead, the lead's reply to was populated and thus if the lead replied, it would go back to themselves.  

This PR changes the behavior to send a separate email to the lead than the admins so that if an admin replies, it'll go to the lead versus if a lead replies, it'll go back to the system configured email and the lead won't see the other emails associated.

**Testing**
Create a form submit action to send results and copy the lead.  Submit the form as a lead.  Before the PR, the lead will get an email and in the To will be the lead and the admin also if the lead replies, it'll be going back to themselves.  After the PR it should be the behavior as above.

### CODE REVIEW

**Comment by escopecz** [comment]
I'm confused a bit. I crated 2 emails. One for lead, second for user (admin). Then I created a form with 2 actions. Send email to lead (the lead email will be sent) and Send email to user (the user email will be sent). Then I open the form on public URL in anonymous browser window and submit it.

I get 3 emails. 2 Asset test emails from previous testing and one user email (which I configured earlier). So the lead email is not send at all and 2 another emails are sent instead. That works before and after this PR. I checked what I configured many times. The lead email has ID 40 and that is stored in the database. The Asset test email which is being sent instead has ID 19. What could cause this? I switched off all campaigns, but still the same result. 

After the PR: When I want to reply to the user email, it goes to the user's email address. If I reply to one of the Asset test emails (which I assume should be the lead email) it goes to the lead email address. That should be opposite, right?

**Comment by alanhartless** [comment]
@escopecz This isn't for the send email actions (which use an email template) but the 'send form results' action.

**Comment by versadial** [comment]
Tested and worked for me.

**Comment by escopecz** [comment]
Ahh, sorry. I misread the description. Those problems I mentioned are not related to this PR. 

With the PR, the email delivered to **To** address has set *reply-to* as the lead email. The copy of the email which lead gets doesn't have the *reply-to* header set. If I want to reply to the lead email in GMail, it will pre-set also the lead email which is weird.

**Comment by drmmr763** [comment]
+ test email `reply to` was the lead's before checking the PR out
+ after checking out the PR, the `reply to` was the system configured email
+ vote +1!

**Pull request merged**
