### PR TITLE
Remove last_active_search index 

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

Remove index last_active_search from this PR https://github.com/mautic/mautic/pull/6279
This index already added by FieldModel https://github.com/kuzmany/mautic/blob/928661ba87ecc8970568dce899404cd9d09fe7ae/app/bundles/LeadBundle/Model/FieldModel.php#L494-L494

#### Steps to test this PR:
1. Code review is enought

### CODE REVIEW

**Comment by alanhartless** [comment]
@kuzmany is this a breaking issue in 2.15.1 beta? 2.15.1 beta is already out so unless this is a breaking issue in 2.15.1 beta, it'll have to wait till the next release. 

Also, please don't assign PRs to milestones. The release leaders will manage that.

**Comment by kuzmany** [comment]
Yes, it caused a lot of ugly issues with `php app/console d:s:u --force`  remove a lot of columns and indexes. Script fail because it's duplicate index statement and everything after this line is removed from db  schema.

Discussed here https://github.com/mautic/mautic/issues/7167

**Comment by alanhartless** [comment]
Thank you for clarifying. I'll merge it into the beta.

**Comment by alanhartless** [comment]
@kuzmany can you please rebase to the release-2.15.1 branch?

**Comment by kuzmany** [comment]
@alanhartless done

**Comment by alanhartless** [comment]
Can you rebase instead of merge? Staging has already been prepped for the next release. If we merge that into release-2.15.1, the version numbers will get all confused.

You may need to hard reset to the commit previous to your merge. 

`git reset --hard a534f89`

Then rebase

`git rebase origin/release-2.15.1`

Then force push to your branch

`git push --force`

**Comment by kuzmany** [comment]
It's ok now?

Instead of  not existed
`git rebase origin/release-2.15.1` 

I use 

`git rebase upstream/release-2.15.1`

**Comment by alanhartless** [comment]
@kuzmany doesn't seem it worked as it still includes the staging commit `staging dev bump`. Maybe it'll be easier to close this PR, create a new branch based on the release-2.15.1 branch, re-make the code change, then create a new PR.

**Comment by kuzmany** [comment]
close it favor to https://github.com/mautic/mautic/pull/7343/files
@alanhartless please take a look

**Pull request closed without merging**
