### PR TITLE
TPROD-332 - CitrixBundle - Migrate PHP Templates to Twig Templates

### PR DESCRIPTION
**Pull request by JoshuaEstes**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. 

**REQUIRES** an active Citrix account to test. You will need to connect to it. Enabling the plugins and trying to test will cause failures.

Once Citrix plugins are enabled:
- Test new form fields
- Campaign actions

### CODE REVIEW

**Review by mabumusa1 — COMMENTED** [review]
- [X] Enable the plugin
- [X] Add a form field - API error when I try to save the request because I use dev keys that are not actually have permission to create
image
- [X] Campaign Action - The dialog did not render because it require actual API calls

**Comment by ekkeguembel** [comment]
Just tested on Gitpod, with our production gotowebinar.

## Sync
**After starting to sync nicely, it fails** when coming to a webinar with a negative ID (-2022844082891). No idea why that  (the same webinar is pulled nicely in other Mautic instances. Maybe a local issue, not sure.
```
In CitrixApi.php line 58:             
  Call to a member function getStatusCode() on array  
mautic:citrix:sync [-p|--product [PRODUCT]] [-i|--id [ID]] [--bypass-locking] [-t|--timeout TIMEOUT] [-x|--lock_mode LOCK_MODE] [-f|--force] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
Failed to execute command bin/console mautic:citrix:sync: exit status 255
```

with log entry
```
2023-02-22 16:07:10] mautic.ERROR: Error: Call to a member function getStatusCode() on array (uncaught exception) at /var/www/html/plugins/MauticCitrixBundle/Api/CitrixApi.php line 58 while running console command `mautic:citrix:sync` [stack trace] #0 /var/www/html/plugins/MauticCitrixBundle/Api/GotowebinarApi.php(26): MauticPlugin\MauticCitrixBundle\Api\CitrixApi->_request('webinars/-20228...', Array, 'rest/organizers...') #1 /var/www/html/plugins/MauticCitrixBundle/Helper/CitrixHelper.php(470): MauticPlugin\MauticCitrixBundle\Api\GotowebinarApi->request('webinars/-20228...') #2 /var/www/html/plugins/MauticCitrixBundle/Model/CitrixModel.php(249): MauticPlugin\MauticCitrixBundle\Helper\CitrixHelper::getRegistrants('webinar', -2022844082891) #3 /var/www/html/plugins/MauticCitrixBundle/Command/SyncCommand.php(103): MauticPlugin\MauticCitrixBundle\Model\CitrixModel->syncEvent('webinar', -2022844082891, 'test-decision_#...', 'Test-Decision', 0, Object(Symfony\Component\Console\Output\ConsoleOutput)) #4 /var/www/html/vendor/symfony/console/Command/Command.php(255): MauticPlugin\MauticCitrixBundle\Command\SyncCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #5 /var/www/html/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #6 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(97): Symfony\Component\Console\Application->doRunCommand(Object(MauticPlugin\MauticCitrixBundle\Command\SyncCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #7 /var/www/html/vendor/symfony/console/Application.php(273): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(MauticPlugin\MauticCitrixBundle\Command\SyncCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #8 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(83): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #9 /var/www/html/vendor/symfony/console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #10 /var/www/html/bin/console(42): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #11 {main} [] {"hostname":"mautic-web","pid":4809}
[2023-02-22 16:07:10] mautic.WARNING: Command `mautic:citrix:sync` exited with status code 1 [] {"hostname":"mautic-web","pid":4809}
```
**To overcome this issue, I synced some webinars specifically (using the -i option).**

## Form
Form field works as expected.

## Form action
**After creating one (looks ok), it can't be saved.** 
Error message:
`No field matches the contact field 'email'. Please add one through the Fields tab.<br/>No field matches the contact field 'firstname'. Please add one through the Fields tab.<br/>No field matches the contact field 'lastname'. Please add one through the Fields tab.`
**Thus the actual form action could not be tested.**
(Note that the error message is very ugly, and has HTML tags in it. Not sure if this caused by the Citrix plugin , or by the form builder.)

## Segment Filter
**segment:update fails** 
Error message:
```
In AbstractMySQLDriver.php line 98:
                                                                                                                                      
  An exception occurred while executing 'SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM   
  (SELECT DISTINCT l.id as leadIdPrimary FROM leads l WHERE (EXISTS (SELECT null FROM plugin_citrix_events par00 WHERE (par00.produc  
  t = 'webinar') AND (par00.event_type = 'registered') AND (par00.event_name IN ()) AND (par00.lead_id = l.id))) AND (l.id NOT IN (S  
  ELECT par1.lead_id FROM lead_lists_leads par1 WHERE par1.leadlist_id = ?))) sss' with params [2]:                                   
                                                                                                                                      
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to  
   your MariaDB server version for the right syntax to use near ')) AND (par00.lead_id = l.id))) AND (l.id NOT IN (SELECT par1.lead_  
  id FROM le...' at line 1                                                                                                            
                                                                                                                                      

In Exception.php line 18:
                                                                                                                                      
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to  
   your MariaDB server version for the right syntax to use near ')) AND (par00.lead_id = l.id))) AND (l.id NOT IN (SELECT par1.lead_  
  id FROM le...' at line 1                                                                                                            
                                                                                                                                      

In PDOStatement.php line 117:
                                                                                                                                      
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to  
   your MariaDB server version for the right syntax to use near ')) AND (par00.lead_id = l.id))) AND (l.id NOT IN (SELECT par1.lead_  
  id FROM le...' at line 1 
```  

## Campaign condition
"Has registered to at least one webinar" worked all right.

## Campaign action
**"Webinars list" is empty (although e.g. in the form field the list is properly populated)**

**Comment by mabumusa1** [comment]
> ```
> 
> ```

Thanks @ekkeguembel for your tests, I think many of the issues you mentioned are not related to this PR, by looking at the logs I think these are issues and bugs related to the plugin itself. I suggest we start separate issues for them.

@JoshuaEstes please check the logs in Form Action, I think it is related to this PR

**Comment by mabumusa1** [comment]
@escopecz please do a code review on this PR

**Comment by JoshuaEstes** [comment]
@mabumusa1 @ekkeguembel 

I couldn't get the **FormAction** to display an error. All this is really great information and will help in the future. One of the issues is I'm not sure if this worked in the first place. @ekkeguembel Do you get the same issues when using the 5.x branch?

The issue `Call to a member function getStatusCode() on array` isn't related to the twig files, however when I debug/troubleshoot the error it gives me an `Access Denied` from the API. It seems that when there is an error, an array is returned, but it it's successful an object will be returned. I cannot confirm because I have never had real production keys to test with.

**Review by escopecz — APPROVED** [review]
I see no issues in the code 👍

**Comment by mabumusa1** [comment]
@RCheesley I am not sure if we can merge this PR or not, but there are no testers who have active accounts on Citrix, I think @ekkeguembel did excellent work testing the PR and many of the errors he showed are not related to twig conversion.

I suggest we merge it, unless you know someone who can re-test

**Comment by RCheesley** [comment]
@ekkeguembel if it isn't too much of a problem, please could you test here: http://gitpod.io/#https://github.com/mautic/mautic

This would allow us to check whether the issues you have are common in the 5.x branch as others have suggested.

If that is the case then OK to merge and we will raise those issues separately as bugs.

Thanks in advance!

**Comment by ekkeguembel** [comment]
@RCheesley @mabumusa1 : I re-tested against vanilla Mautic (in Gitpod), but there "your request could not be processed, please try again" in the UI when you try anything Goto-related.

**Comment by mabumusa1** [comment]
> @RCheesley @mabumusa1 : I re-tested against vanilla Mautic (in Gitpod), but there "your request could not be processed, please try again" in the UI when you try anything Goto-related.

If you close gitpod window, it will terminate the server running mautic and that would result in the error message you see

**Comment by MadlenF** [comment]
> @mabumusa1 If you close gitpod window, it will terminate the server running mautic and that would result in the error message you see 

> 

I tried to test in vanilla mautic as well, with the same results, gitpod was still up and running.

**Comment by mabumusa1** [comment]
> > @mabumusa1 If you close gitpod window, it will terminate the server running mautic and that would result in the error message you see
> 
> > 
> 
> I tried to test in vanilla mautic as well, with the same results, gitpod was still up and running.

I think it is related to this issue #11977

**Pull request merged**
