### PR TITLE
Remove symfony/debug

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
image

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
Yep, let's remove this dependency:

> CAUTION: this component is deprecated since Symfony 4.4.

https://github.com/symfony/debug

**Comment by escopecz** [comment]
@mabumusa1 please check the PHPSTAN errors. We might have to replace it with https://github.com/symfony/symfony/tree/6.3/src/Symfony/Component/ErrorHandler after all

**Comment by mabumusa1** [comment]
> @mabumusa1 please check the PHPSTAN errors. We might have to replace it with https://github.com/symfony/symfony/tree/6.3/src/Symfony/Component/ErrorHandler after all

@escopecz I replaced it to `ErrorHandler` it should be good to go now

**Review by escopecz — APPROVED** [review]
Looks good 👍

**Pull request merged**
