### PR TITLE
Fix inability to delete campaign actions with many logs.

### PR DESCRIPTION
**Pull request by anton-vlasenko**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) |
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

When a campaign action accumulates a lot of event_logs (~500 000) and you attempt to delete it from the campaign you can run into issues.

Mautic tries to load all of the logs into memory before deleting them which leads to memory and cpu exhaustion. We need to optimize this process.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create (or find) a campaign action with 500 000 logs or more.
2. Attempt to delete that action from the campaign in the campaign builder.
3. Apply changes in the campaign builder.
3. This action will never end, you will get 500 server error in your browser's developer console.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create (or find) a campaign action with 500 000 logs or more.
3. Attempt to delete that action from the campaign in the campaign builder,
4. Apply changes in the campaign builder.
5. It will take some time (2-3 minutes), but you will be able to delete that action.

### CODE REVIEW

**Comment by npracht** [comment]
Hello @anton-vlasenko could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback, i would very love to merge it in 3.0.1 if still relevant. Thanks !

**Comment by RCheesley** [comment]
Bumping to 3.2 due to unresolved conflicts.

**Comment by anton-vlasenko** [comment]
Conflicts have been resolved.

**Comment by RCheesley** [comment]
@cla-bot check

**Review by kuzmany — DISMISSED** [review]
I've tested on actions with a lot of logs and was deleted without issue 👍

**Review by mabumusa1 — DISMISSED** [review]
I have a large database, I tested this PR and delivered what it promised. I think this PR is good to go

**Comment by RCheesley** [comment]
This PR will [decrease test coverage](https://github.com/mautic/mautic/pull/7747#issuecomment-678471919) so bumping it to 3.1.2 so that there is more time to write tests so that we maintain or (ideally) improve coverage cc @mautic/acquia-po

**Comment by npracht** [comment]
Hi @anton-vlasenko and @mautic/acquia-po ! We need more tests here, otherwise we'll have to postpone the merge again. Could you please have a look at it quickly ?
Thanks !

**Comment by dennisameling** [comment]
Bumping to 3.2 due to decreased test coverage. CC @mautic/acquia-po

**Comment by anton-vlasenko** [comment]
@cla-bot check

**Comment by anton-vlasenko** [comment]
@cla-bot check

**Pull request merged**
