### PR TITLE
Add support for plugin to inject buttons into other bundle pages.

### PR DESCRIPTION
**Pull request by alanhartless**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | n
| New feature? | y
| Related user documentation PR URL | na
| Related developer documentation PR URL | todo
| Issues addressed (#s or URLs) | na
| BC breaks? | n
| Deprecations? | n

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR adds support for plugins and other bundles to inject buttons into the various standard button areas of Mautic without requiring cross hard coding.

It also moves the batch buttons to be an activated dropdown around the check all. 

#### Steps to test this PR:
1. Extract the attached zip and drop attached ButtonSubscriber.php and config.php into the LeadBundle to test
2. Clear cache
3. View /s/contacts and /s/contacts/view/ID pages. On the /s/contacts, note the second "Extra Button" action for each contact dropdown. Also note the star/extra button in the batch toolbar area (on every page with the attached example file).
4. Go to a /s/contacts/view/ID page and note the Extra Button in the page actions/button list.
5. Ensure that the page actions have the correct formatting for the primary/buttons and dropdown list along with the dropdowns in the lists. Toolbar area should still include some buttons on the contacts page. 
6. For /s/contacts (and other list views), checking at least one items should activate the batch dropdown list. Unchecking them all should disable it.

[example.zip](https://github.com/mautic/mautic/files/602323/example.zip)

### CODE REVIEW

**Comment by escopecz** [comment]
This PR does everything what is described. It's a great functionality! I noticed just one styling issue in the contact batch button row. The additional button is missing space:
mautic-batch-buttons

But other than that :arrow_right: :+1:

**Comment by alanhartless** [comment]
@escopecz Can you try again? I moved the batch actions to be an activated dropdown for the check all. Did some work to add a priority system for the buttons and to also allow views to set which buttons are "primary" for the page actions (be a button versus listed in the dropdown). After making the changes, I couldn't reproduce the screenshot even after adding some "confirm" templated buttons.

**Comment by escopecz** [comment]
It looks all good to me :+1: 

The batch buttons UI is awesome!

**Comment by mqueme** [comment]
This is unstranslated 'mautic.lead.batch.companies'
I am logged in as Admin and getting an access error
screen shot 2016-11-22 at 14 32 09

**Comment by escopecz** [comment]
@mqueme the star button is added there by the dummy listener class. It's not a part of the PR, but just to show and test how a new button can be added to different positions via a listener.

**Comment by alanhartless** [comment]
That's right - it's just an example not meant to be actually used. Just shows how the buttons get injected.

**Comment by mqueme** [comment]
ah :) ok well then it adds it ok

**Pull request merged**
