### PR TITLE
[UX] Add the same user account helper on the user settings page

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This update incorporates the user account helper into the user settings page, mirroring the functionality found in the user profile. The helper reminds users of the variable that auto-populates their name in signatures, ensuring consistency across the platform.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Users
3. Edit you
4. Look at the Signature field

image

### CODE REVIEW

**Review by dadarya0 — DISMISSED** [review]
looks good to me.

**Review by LordRembo — APPROVED** [review]
Makes sense.

**Review by roboparker — APPROVED** [review]

**Review by adiux — APPROVED** [review]
👍

**Review by Mike-Dropsolid — APPROVED** [review]
Looks good.

**Comment by escopecz** [comment]
@andersonjeccel there are conflicts. Please, resolve them so this PR can get merged.

**Comment by escopecz** [comment]
There is another conflict. Please, take a look. It could be avoided if you'd add new translation strings to different line for each PR.

**Comment by andersonjeccel** [comment]
@escopecz Is it ok now?
No more conflict messages appearing here

**Review by escopecz — CHANGES_REQUESTED** [review]
Almost. The `mautic.user.config.signature.helper` key is now duplicated on lines 98 and 110

**Review by escopecz — APPROVED** [review]
Thanks! 👍

**Pull request merged**
