### PR TITLE
Single landing page scripts

### PR DESCRIPTION
**Pull request by alfredoct96**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | features
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | N/A

#### Description:

Added two new fields for landing page:
* Script inside head
* Script inside footer

Anyone with this feature can add custom script to single landing page, and can decide whether to upload it if inside head tag or at the end of body.

singlelandingscripts

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create a landing page
3. Edit the two new inputs with a custom script (example `<script>console.log("Hello world");</script>`)
4. Go to the landing page and check if script is loaded

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/9695"></a>

### CODE REVIEW

**Comment by kuzmany** [comment]
I like this PR.
But this PR require add manually `{headScript}` and `{footerScript}` to every template. And what about already created pages? This feature will not work everywhere and everyone. 
Would be better add tokens automatically during the build page `{headScript}` before `</head>` and `{footerScript}` before `</body>`

You can use PAGE_ON_DISPLAY subscriber, example: 

https://github.com/mautic/mautic/blob/d6ac13284cfc6c9310ce8e918de651226cbe20b6/app/bundles/AssetBundle/EventListener/BuilderSubscriber.php#L98-L97

**Comment by alfredoct96** [comment]
> I like this PR.
> But this PR require add manually `{headScript}` and `{footerScript}` to every template. And what about already created pages? This feature will not work everywhere and everyone.
> Would be better add tokens automatically during the build page `{headScript}` before `</head>` and `{footerScript}` before `</body>`
> 
> You can use PAGE_ON_DISPLAY subscriber, example:
> 
> https://github.com/mautic/mautic/blob/d6ac13284cfc6c9310ce8e918de651226cbe20b6/app/bundles/AssetBundle/EventListener/BuilderSubscriber.php#L98-L97

Hi @kuzmany .

I knew this evolution wasn't retroactive  but i didn't find a method to correct it, now I fixed it.

It was so simple! Why I didn't think about it before! I hope it's correct, thanks for the input :)

**Review by kuzmany — DISMISSED** [review]
Works as expect.  Code looks ok.
Good job :)

**Comment by jos0405** [comment]
Hey! Can we use tokens in scripts too? For example countdown deadline date, that we store in the contact?

**Comment by alfredoct96** [comment]
> Hey! Can we use tokens in scripts too? For example countdown deadline date, that we store in the contact?

No @jos0405 , at the moment tokens are not implemented

**Comment by dennisameling** [comment]
Hi @alfredoct96! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since we don't have access to your branch, could you please click "Update branch" at the bottom of this PR? If that doesn't work, you can also run `git merge upstream/features` locally. Thanks in advance!

image

**Comment by alfredoct96** [comment]
> Hi @alfredoct96! Thanks for your PR  we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since we don't have access to your branch, could you please click "Update branch" at the bottom of this PR? If that doesn't work, you can also run `git merge upstream/features` locally. Thanks in advance!
> 
> image

Done @dennisameling

**Comment by dennisameling** [comment]
@alfredoct96 Could you please merge/rebase the latest changes from `4.x` into your branch? It's a protected branch so we're not able to update it for you unfortunately. Just ping me here when it's done and I'll merge it right away :)

**Comment by alfredoct96** [comment]
> @alfredoct96 Could you please merge/rebase the latest changes from `4.x` into your branch? It's a protected branch so we're not able to update it for you unfortunately. Just ping me here when it's done and I'll merge it right away :)

Sure, i did the rebase

**Comment by luguenth** [comment]
When I test it o the new GrapesJS Landingpage Builder, it's not working. Is it supposed to work with that too, or only with the legacy builder?

**Comment by alfredoct96** [comment]
> When I test it o the new GrapesJS Landingpage Builder, it's not working. Is it supposed to work with that too, or only with the legacy builder?

When i did PR GrapeJs was not present ,at the moment it works with legacy builder

**Comment by alfredoct96** [comment]
> When I test it o the new GrapesJS Landingpage Builder, it's not working. Is it supposed to work with that too, or only with the legacy builder?

Hi, i did a check on a landing page with grapejs, and it works, what is your problem?
Are you sure you added the script correctly?

**Review by kuzmany — APPROVED** [review]
Works

image

Probably we should add basic functional tests.
Added header/footer script to createTestPage and then check it in content of page.

https://github.com/mautic/mautic/blob/a0ca40058260f9274570e124b8491baf7af4039b/app/bundles/PageBundle/Tests/Controller/PageControllerTest.php#L138

**Review by mabumusa1 — APPROVED** [review]
I conducted a code review, I think this is a good feature to be added.

**Comment by PierreAmmeloot** [comment]
@RCheesley I would like to update the documentation for Mautic 4.2.0 (if not already done).
Can you tell me where I can submit a new version of the Mautic documentation?

**Comment by npracht** [comment]
@PierreAmmeloot you can clone this repo : https://github.com/mautic/mautic-documentation, create a branch and update the content you'd like to.
Here is the how to contribute file: https://github.com/mautic/mautic-documentation/blob/main/CONTRIBUTING.md

**Pull request merged**
