### PR TITLE
Fixing background color contrast for buttons in the builder

### PR DESCRIPTION
**Pull request by eloimarquessilva**
Removing the background color f0f0f0 from gjs-field-radio class to improve the color constrast between radio's background and radio's options and returning the class parameters to the default of the original editor.

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10728"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
@eloimarquessilva would you mind pasting screenshot of before and after the change? I would help greatly to get this merged.

**Comment by eloimarquessilva** [comment]
Hi @escopecz, thank you for your reply.

As you asked, the screenshots:

image

image

**Review by escopecz — APPROVED** [review]
I cannot see the change when I apply this PR on my local. It must be some build step I'm missing or some browser cache I'm unable to clear because if I make the same change in the dev tools I can see the expected result. So I'm giving 👍  and someone with GrapeJS experience should make second review and ideally tell me how to test this properly.

**Comment by adiux** [comment]
@escopecz you need to run `npm run build`.  I usually run it, and commit the build with the PR as well. So this is not necessary for testing. @dennisameling created an action that builds the code automatically, so it is not necessary to actually commit it. But it makes it easier for testing.

**Review by adiux — APPROVED** [review]

**Comment by escopecz** [comment]
@eloimarquessilva could you please finish the steps in https://github.com/mautic/mautic/pull/10728#issuecomment-1005132631 so we could merge this PR?

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
All good to go now @escopecz once the tests finish running 🎉 

Thanks for the PR @eloimarquessilva and for getting the contributors agreement signed! 🚀

**Comment by eloimarquessilva** [comment]
> All good to go now @escopecz once the tests finish running 🎉
> 
> Thanks for the PR @eloimarquessilva and for getting the contributors agreement signed! 🚀


you are welcome :-)

**Comment by RCheesley** [comment]
@all-contributors please add @eloimarquessilva for code

**Comment by adiux** [comment]
@RCheesley I rebuild the CSS and JS. So the latest changes should be accounted for now.
image

**Comment by putzwasser** [comment]
I just updated to 4.1.2. I still see the low contrast buttons from the first screenshot. Flushing the browser cache didn't help.

Is there additional "work" to be done after the upgrade? A step I missed?
Or is the merged fix faulty?

I'm using chrome on linux with dark mode enabled (if that helps)

**Comment by RCheesley** [comment]
How did you install/update Mautic? If you installed with Composer you will probably need to manually build the assets.  We have a PR open to address this but it has a bunch of conflicts which we're waiting on the author to address.

Also ensure you've cleared your Mautic cache?

**Comment by putzwasser** [comment]
> Also ensure you've cleared your Mautic cache?

I did

> How did you install/update Mautic?

I followed the "use the production package" section from the docs.

> you will probably need to manually build the assets

How?

**Pull request merged**
