### PR TITLE
Bugfix Segment filter "email read count equals 0"  and new source ID filter

### PR DESCRIPTION
**Pull request by kuzmany**
Fix email read count with 0

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/5041
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Bugfix for https://github.com/mautic/mautic/issues/5041 

#### Steps to test this PR:
1.  Create filter with email read count equals = 0
2.  Run `php app/console m:s:r`
3. Works if segment is not empty
4. Create filter with Page source and Page source ID (for example email and id of email )
5.  Run `php app/console m:s:r`
6. See if segments contains contacts with contacts hits pages from that email

### CODE REVIEW

**Comment by kuzmany** [comment]
Bugfix https://github.com/mautic/mautic/pull/5043

**Comment by escopecz** [comment]
But it will need docs at least for what values can be filled into source field. E.g. `email`, `focus`...

**Comment by rowlandhill** [comment]
Thanks so much!  @matishaladiwala could this possibly be included in the next sprint?

**Comment by kuzmany** [comment]
@escopecz maybe should added predefined list with dynamic DISTINCT source items values from page_hits table? What do you think?

**Comment by escopecz** [comment]
That would be great!

**Comment by sarahwernik** [comment]
@alanhartless - This looks like a duplicate of 5041. But, this one states it should be included in 2.11. Is that still accurate? cc @rowlandhill

**Comment by alanhartless** [comment]
@sarahwernik  #5041 is the reported issue. This is the actual code fix.

**Comment by sarahwernik** [comment]
@alanhartless - Got it, so will it be released with 2.11 next week?

**Comment by kuzmany** [comment]
Label: WIP

**Pull request merged**
