### PR TITLE
Empty mail name part2

### PR DESCRIPTION
**Pull request by chandon**
Please answer the following questions. 

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #2131 
| BC breaks? | N
| Deprecations? | 

**Note that all new features should have a related user and/or developer documentation PR in their respective repositories.** 

#### Description:

This fix some cases where the name specified in an email is empty according to issue #2131 , first PR was #2132 and was incomplete

### CODE REVIEW

**Comment by escopecz** [comment]
Is it possible to write steps to test this?

**Comment by alanhartless** [comment]
Closing this in favor of https://github.com/mautic/mautic/pull/2284 (sorry). Part one of this change accidentally broke our transports that support tokenized emails (batch delivering via an API). But #2284 fixes this along with fixing the change from part 1.

**Comment by alanhartless** [comment]
But now that I'm thinking about it - it may have completely reverted the pretty headers. I'll test to double check.

**Comment by alanhartless** [comment]
Nope it worked. Pretty headers intact and tokens worked.

**Pull request closed without merging**
