### PR TITLE
Assets are streamed by default

### PR DESCRIPTION
**Pull request by volha-pivavarchyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [no]
| New feature/enhancement? (use the a.x branch)      | [yes]
| Deprecations?                          | [no]
| BC breaks? (use the c.x branch)        | [no]
| Automated tests included?              | [no] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR suggests displaying the assests directly in the browser by default. Displaying the file directly in the browser makes for a better UX.
#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create asset or use existing one
3. Preview it

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11043"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
Does it make sense for all the assets? I can see it is good for images and PDFs. But an asset can be a CSV, MS doc or other blob/executable file that browsers cannot display.

**Comment by adiux** [comment]
@escopecz I think the browser will download those regardless of our parameter? So it will be the same behavior as it is now.

**Comment by escopecz** [comment]
Ok. Let's test this. Can you please add a functional test that will call those 2 endpoints and confirm the content is correct? I found [this example](https://stackoverflow.com/questions/15734677/how-to-retrieve-a-streamed-response-e-g-download-a-file-with-symfony-test-cli) of how to get content of a streamed file.

**Comment by volha-pivavarchyk** [comment]
@escopecz I have added the functional tests that call endpoints with with different parameter values. Should I add more?

**Review by escopecz — DISMISSED** [review]
The tests look great! Thank you!

**Review by jos0405 — DISMISSED** [review]
Works as expected.

**Comment by escopecz** [comment]
@volha-pivavarchyk can you please rebase on 4.4 branch so we could merge this PR?

**Comment by escopecz** [comment]
Oh, wait. This is a feature. So rebase on 5.x branch please.

**Comment by RCheesley** [comment]
Thanks for rebasing @volha-pivavarchyk - ready to go! 🚀

**Comment by RCheesley** [comment]
@all-contributors please add @volha-pivavarchyk for code

**Pull request merged**
