### PR TITLE
Update services.php

### PR DESCRIPTION
**Pull request by ErikThiart**
Here are the changes I made:

- Added whitespace between statements for readability.
- Extracted the `$bundle['directory']` and `$bundle['namespace']` values to separate variables to avoid repetitive use of `$bundle`.
- Added curly braces to `if` statements for clarity and consistency.
- Used double quotes to interpolate variables in string literals for clarity.
- Moved the `$bundleDirectory` variable definition to avoid redundant calls to `$bundle['directory']`.
- Changed the indentation of the chained methods to match the arguments for each method.
- Simplified the `is_dir` check to avoid a separate `if` statement.

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by mabumusa1** [comment]
Hello @ErikThiart ,

Welcome to the community, please sign the contributor agreement, so we can get it tested and merged

**Review by escopecz — COMMENTED** [review]
I don't understand this change. It only changes the code style and removes useful comments. There is no change in behavior. Or am I missing something? As code style is just a preference of every developer I don't see a reason to merge this. You could go into every single Mautic file and do similar changes. Then someone else will do the changes as they are used to and revert some of your. It doesn't make any sense.

If you want to set some new code style rule, I'd suggest to do it in a systematic and automated way via CS Fixer config file. However, every such change will cause conflicts with forked repositories and open pull request. So I don't think it's worth it either unless somehow justified.

There is major refactoring going on where the community tries to upgrade the Symfony library. Please help us with that instead.

**Comment by ErikThiart** [comment]
Fair enough, I understand your point. 

I "refactored" and tried to keep the functionality exactly the same.

Well, is there any specific issue you need help with at the moment that I can try fix / add ?

**Comment by escopecz** [comment]
Thanks for understanding! 

Today, the blocker for Symfony upgrade is https://github.com/mautic/mautic/pull/12134 and there are 2 decisions we have to make. If you'd like to chime in.

And the force we lack the most are reviewers and testers. Some PRs are close to ready but are missing a test or some some small update. I know those are boring tasks for a developer but those are most needed to get work 100% done.

There is a [list of PRs that need some attention](https://github.com/mautic/mautic/issues/12117).

**Comment by mabumusa1** [comment]
@ErikThiart If you have time, we have a couple of packages that we need to refactor since we are upgrading to Symfony5, we can start with lightsaml if you want., it would be a good starting point

**Pull request closed without merging**
