### PR TITLE
Focus additions - CSS tab, HTML mode, API support, UTM tag support

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | y
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/168
| Related developer documentation PR URL | https://github.com/mautic/api-library/pull/93
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/2894 
| BC breaks? | n
| Deprecations? | n

[//]: # ( Required: )
#### Description:

**Focus Items channel updates  (steps to tests)**

**Dependencies:**

https://github.com/mautic/mautic/pull/3891  (point 5 - utm tags)

**Require**

doctrine:schema:update 
mautic:assets:generate

1.  Content mode with Basic|Editor|HTML options
Basic - the most easy mode
Editor - is more customizable
HTML - for experts
Support these tokens contactfield, pagelink, assetlink

image
image

3. API support

See https://github.com/mautic/api-library/pull/93

4.  Bugfixes
Focus window will not close  https://github.com/mautic/mautic/issues/2691 (fix https://github.com/mautic/mautic/pull/3460/commits/4920b06c617450f4085e3e3b962d984ceb8ef8e6  and https://github.com/mautic/mautic/pull/3460/commits/993995aa82cf56fdd70a832caeb47e8fbb6b3ada)
Focus copied statistics https://github.com/mautic/mautic/issues/3434 (fix https://github.com/mautic/mautic/pull/3460/commits/4542e7aa5f2fb410c570536d08bb1f599b3b7586)

5. Added Google Analytics UTM tag support
Need this PR https://github.com/mautic/mautic/pull/3891 
This update add utm tags to html content and to link type of course.

image

### CODE REVIEW

**Comment by clementdes** [comment]
Hi there,
any updates on this ?
Thx a lot for all your work !
Clement

**Comment by kuzmany** [comment]
Now I'm  done.
@alanhartless @escopecz please re-test, maybe add 2.8 release (a  lot of people vote for this)

**Comment by escopecz** [comment]
We had to draw the line on new PRs added to 2.8.0 so we would be able to test those marked as 2.8.0 and release soon. I added this PR to 2.9.0 milestone. Thanks for understanding.

**Comment by kuzmany** [comment]
@alanhartless I understand your commit, but now we can't add custom html/scripts to focus content, because Froala has strictly html formatted rules (without code mode)
https://github.com/mautic/mautic/pull/3460/commits/8d242bc40902d1968a043cb17650b540b0d8036d

Better should be to add HTML mode with -  Off|Editor|HTML

**Comment by alanhartless** [comment]
@kuzmany the concern was that most marketers will not know how to use HTML. I'm fine if you change it to support an option for a non-editor - can you get that in today? We're trying to get these things merged.

**Comment by kuzmany** [comment]
@alanhartless I will try resolve it, today

**Comment by kuzmany** [comment]
@alanhartless I remove CSS content tab and create new content mode switcher with Basic|Editor|HTML

HTML field for expert could replace CSS experience also. Just one textarea for experts and coders is more than enough. Now it's more non-technical people firendly, I hope.

Please re-test with doctrine:schema:udpdate and mautic:assets:generate 

image

**Comment by mqueme** [comment]
@kuzmany I am testing this. One thing I notice is that for every feature, Basic - the most easy mode, Editor - is more customizable, HTML - for experts. I can have 3 different contents, which makes things a bit confusing. When I place it in a page the basic content is picked.
I think that when the user toggles from view to view (basic, editor, html) the content should move with it.

**Comment by mqueme** [comment]
UTM tags works.

**Comment by dongilbert** [comment]
@kuzmany Do you have thoughts on this? Can you switch it so that the content goes with the editor's when you switch between them? That way there is only one content.

**Comment by kuzmany** [comment]
> I think that when the user toggles from view to view (basic, editor, html) the content should move with it.

But how? That's not possible, content shouldn't be move, every content mode in focus have limits and content can't be share between them. Maybe I  just don't understand :)

**Comment by kuzmany** [comment]
@dongilbert  If I use html content mode aj can insert CSS style, maybe scripts (Google Analytics events for example) therefore not possible share to editor. Froala will stripped it.

**Comment by dongilbert** [comment]
I see - no worries then. I discussed with @alanhartless and @mqueme and we're going to go with it. Thanks!

**Pull request merged**
