### PR TITLE
[BUGFIX] API will recognize and process incoming form field alias

### PR DESCRIPTION
**Pull request by Woeler**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | X
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/3820
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
In previous versions of Mautic for some odd reason the API would 100% reject form field aliasses that were passed to the API endpoint. I have now changed this. It will now check if the given form already has a field with the alias you pass. If it does, a random one will be generated instead, if it does not, your alias will be used.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
N/A

#### Steps to test this PR:
1. Create a form using the API
2. Set the alias of fields in your API request
3. See the alias appear in the backend of Mautic

#### List deprecations along with the new alternative:
N/A

#### List backwards compatibility breaks:
N/A

### CODE REVIEW

**Comment by Woeler** [comment]
Anyone tested this? I'd really like to see this fix in 2.9.0.

**Comment by escopecz** [comment]
Don't you think that the alias should be sanitised so it wouldn't contain characters which could break something like `"`?

**Comment by Woeler** [comment]
Totally didn't think about that. I will make sure to filter out " characters.

**Comment by escopecz** [comment]
I didn't express my concerns clearly. It can be used in GET HTTP method as attributes, so it should be only ASCII characters with underscore. So I'd use `InputHelper::filename()` method to sanitise the input alias. What do you think?

**Comment by Woeler** [comment]
Ah, understood. I will have a look at the function you provided.

**Comment by Woeler** [comment]
Had a look at the function. Seems to be exactly what is needed. No need to reinvent the wheel. I used the function for generating the alias now.

**Comment by Woeler** [comment]
Seems like travis is a bit drunk today :)

**Comment by virlatinus** [comment]
Tested the PR and ran the tests. Everything works!

**Comment by Woeler** [comment]
Thanks guys :)

**Pull request merged**
