### PR TITLE
Notification header size

### PR DESCRIPTION
**Pull request by escopecz**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | N
| Related user documentation PR URL | /
| Related developer documentation PR URL | .
| Issues addressed (#s or URLs) | /
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

Increasing `notification.header` column from 191 to 512 characters.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a campaign an action that will fail most of the time. For example sending email to contacts with invalid email address.
2. See the error in the logs. It will state that notification header is too small for the value that we want to store.

#### Steps to test this PR:
1. Clone the campaign and test again.
2. There will be no error and the campaign will be automatically unpublished.

#### Other areas of Mautic that may be affected by the change:
1. We are creating notifications from various places, but this change should have positive effect on all of them

### CODE REVIEW

**Comment by npracht** [comment]
@escopecz can you have a look at tests issue please ?

**Review by kuzmany — DISMISSED** [review]
Looks good. 
Migration run smooth.
Approve it 👍

**Comment by escopecz** [comment]
@npracht The issues should be fixed now.

**Comment by RCheesley** [comment]
GTG once tests are passing after branch is updated.

**Comment by RCheesley** [comment]
@escopecz looks like it needs to be rebased but it's throwing up conflicts when I try.

**Comment by RCheesley** [comment]
Fixed by the branch merge LGTM!

**Pull request merged**
