### PR TITLE
rework the seek / fgets combo to be compatible with both PHP 7 and 8

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

_this is a needed bugfix for the PHP 8 support, so that's why it's marked as a new feature / enhancement instead of a bugfix._

When testing and working on the PHP 8 support (see https://github.com/mautic/mautic/pull/9969#issuecomment-1020322075), I noticed a test failure for the `ImportModelTest::testLimit` test.

The run with PHP 8 would result in the last row of the first batch to be reimported as first row of the second batch.
This results in an extra imported row, failing the test.

After a long banging my head against the wall session, I found out this is actually a [PHP bugfix / feature](https://bugs.php.net/bug.php?id=81551).

Bottom line is that the default behaviour of [`splfileobject.fgets`](https://www.php.net/manual/en/splfileobject.fgets.php)  (and `splfileobject.fgetscsv`) has changed in PHP 8, without any BC breaking documentation.

This PR reworks the logic to have a consistent outcome in both PHP 7 and 8.
This is done by not relying on `fgets()` moving the line forward (which it doesn't anymore in PHP8 ), but using `current()` and `next()`.

#### Steps to test this PR:

This PR isn't really testable manually, as it ensures the test outcome in PHPUnit is consistent between PHP 7 and PHP 8.

If you want to test this manually, you could try following steps

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. go to https://example.com/s/contacts/import/new
3. import a CSV file that has +- 3,5 times the number of rows than the configured batch site (this to reproduce the multiple scenrario's like first batch, second batch, last half batch,...)

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11060"></a>

### CODE REVIEW

**Review by kuzmany — APPROVED** [review]
I did test on PHP8 and works in UI and console too.

**Review by RCheesley — APPROVED** [review]
Tested this in GitPod with PHP 7.4 using this data:
[MOCK_DATA.csv](https://github.com/mautic/mautic/files/8457132/MOCK_DATA.csv)

All contacts were imported as expected in batches of 50:

Contacts _ Mautic

In the logs, I see the end of the batches and the start of the next:

[2022-04-09 14:29:51] mautic.DEBUG: IMPORT(1): Entity on line 52 has been created  
[2022-04-09 14:29:53] mautic.DEBUG: IMPORT(1): The import is starting on line 52  
[2022-04-09 14:29:54] mautic.DEBUG: IMPORT(1): Entity on line 53 has been created  
 
This is repeated at the end of each batch.

Re-tested with PHP 8 (to do this I had to stop the instance (ddev delete -O), delete it in Gitpod, re-start it, press ctrl+c in startup, edit .ddev/config.yml to change the PHP version from 7.4 to 8.0, and then run ddev start - in case anyone else needs to know how!) but unfortunately I get the following error:

> Invalid file type "application/csv". Use a file that matches one of the following mime types: "text/*", "application/octet-stream".

I think therefore that this PR is dependent on this fix: #11011.

Applying this fix, I was then able to import the contacts in the usual way, and I can confirm that the correct number of contacts were imported:

Contacts _ Mautic (1)

No errors in the log, all good!

Thanks for your work on this @mollux ! 🚀

**Comment by RCheesley** [comment]
@mollux I am wondering if this PR might have caused #11194 - this and https://github.com/mautic/mautic/pull/11011 / https://github.com/mautic/mautic/pull/10884 are the only PRs I can see which might have impacted the importing functionality in the 4.3 milestone but the other two seem to be more targeted towards import validation.

**Comment by escopecz** [comment]
@RCheesley The regression was most likely caused by https://github.com/mautic/mautic/pull/11011. Not by this one.

**Comment by RCheesley** [comment]
Thanks for looking into it!

**Pull request merged**
