### PR TITLE
FullCalendar localization

### PR DESCRIPTION
**Pull request by hissy**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | No
| New feature? | Yes
| Automated tests included? | No
| Related user documentation PR URL | N/A
| Related developer documentation PR URL | N/A
| Issues addressed (#s or URLs) | N/A
| BC breaks? | No
| Deprecations? | No

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

We're using FullCalendar library but the locale is set as English and it's hardcoded.
Let's respect the locale of the system.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Go to Configuration page then choose Language
3. Go to Calendar page

### CODE REVIEW

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Hi @hissy thanks for the PR. We'd like to consider this for inclusion in the 3.2 milestone. To make that happen we need you to address the conflict and sign the contributors agreement (see above messages) before **Sunday, 15th November**.

Are you able to pick this up and get it over the line? If you can let us know with a reply that would be most appreciated so that we know you're going to work on it. If we don't hear within 14 days, we will close the PR down.

**Comment by hissy** [comment]
@RCheesley Signed it, but I need to update this PR. I'll check it later.

**Comment by RCheesley** [comment]
@hissy many thanks for signing the agreement, I'll get that sorted out right away!

Thanks also for looking at updating the PR, with the regular release cadence we should hopefully be able to get it merged pretty promptly with adequate testing!

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by hissy** [comment]
Sorry for the late, I've created the new pull request #9432
Please feel free to close this PR.

**Comment by escopecz** [comment]
Closing in favor of https://github.com/mautic/mautic/pull/9432

**Pull request closed without merging**
