### PR TITLE
Tokens added to cc bcc fields

### PR DESCRIPTION
**Pull request by escopecz**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | https://github.com/mautic/mautic-documentation/pull/259
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | /
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

This PR adds option to use contact field tokens in the **Send Email to User** campaign action. The tokens used must be based on a field type of `email`. Any other tokens will be rejected by the validation.

#### To Do
- [x] Validate the values for email address (exists now) OR validate them for a token with a field type of email.
- [x] Must work for TO, CC and BCC fields
- [x] If the field does not exist anymore then act like it's a blank value. We talked about validation on custom field delete action and decided not to implement it.
- [x] Comma separated values must still work for email address list.
- [x] Tokens can be also comma-separated. Even mixed comma-separated tokens and email addresses.

##### Test validation
0. Create a new contact email field with alias `email2`.
1. Create a new campaign
2. Add the "Send email to user" action.
3. Save the campaign so you won't have to configure it every time.
4. Try to save different values to the To, BC, BCC fields like
  - `some@valid.email, {invalid-token}` _should trow a validation error that the token is not valid nor an email address_
  - `some@valid.email, {contactfield=firstname}` _should throw a validation error that the field 'firstname' is not type of email_
  - `some@valid.email, {contactfield=email2|invalid-default-email-address}` _should throw a validation error that the default value of the token is not a valid email address_
5. Valid values are for example:
  - `some@valid.email, {contactfield=email2}`
  - `some@valid.email, {contactfield=email2|default@email.address}`
6. Try to save the campaign with some valid values and run it. Test that the tokens are being replaced with the correct values. If the token is evaluated as empty then it should ignore sending the email. But it should send it to all the valid email addresses or correctly replaced token values still.
7. Test also that the campaign action is working well when you unpublish the field used in the tokens or if you completely remove it.

#### Other areas of Mautic that may be affected by the change:
1. It looks like some of the code is used by the form action "send form results" and "send email to user" point action.

#### List deprecations along with the new alternative:
1. None

#### List backwards compatibility breaks:
1. None

#### New classes coverage
| class file path  | coverage  |
|---|---|
| app/bundles/CoreBundle/Exception/InvalidValueException.php  | 100%  |
| app/bundles/CoreBundle/Exception/RecordException.php  | 100%  |
| app/bundles/CoreBundle/Exception/RecordNotFoundException.php  | 100%  |
| app/bundles/CoreBundle/Exception/RecordNotPublishedException.php  | 100%  |
| app/bundles/CoreBundle/Form/DataTransformer/BarStringTransformer.php  | 100%  |
| app/bundles/EmailBundle/Validator/EmailOrEmailTokenList.php  | 100%  |
| app/bundles/EmailBundle/Validator/EmailOrEmailTokenListValidator.php  | 92%  |
| app/bundles/LeadBundle/Exception/InvalidContactFieldTokenException.php  | 100%  |
| app/bundles/LeadBundle/Validator/CustomFieldValidator.php  | 93%  |

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/9525"></a>

### CODE REVIEW

**Review by npracht — DISMISSED** [review]
I confirm this works as expected.
### Throwed error when the field is not an email type
Capture d’écran 2021-01-20 à 09 30 52

### Succes if email type
Capture d’écran 2021-01-20 à 09 31 38

## :warning: we can add wrong written info
@escopecz this is not your fault, but I believe it would be awesome as far as you check data integrity in field, that you also work on this issue.

If i add:
Capture d’écran 2021-01-20 à 09 33 22

I can save and it'll later generate an issue.

If there any chance you have a look to the validator to enable space only if there is the comma to separe the email values ? Maybe the UI must changed to use a field like tags (see under) and avoid issue ?
Capture d’écran 2021-01-20 à 09 36 29

**Comment by RCheesley** [comment]
@escopecz can you take a look at the [feedback above](https://github.com/mautic/mautic/pull/9525#pullrequestreview-571976487)? We also will need a small PR to the docs to update about this feature.

**Review by kuzmany — DISMISSED** [review]
Works as described. 
Nice PR

**Comment by npracht** [comment]
@escopecz do you think you can have a look at my comment here above or we create a separated issue and leave the issue for now ?

**Comment by npracht** [comment]
I've done a [PR for documentation](https://github.com/mautic/mautic-documentation/pull/163) as well. Maybe @escopecz you can review it.

**Comment by escopecz** [comment]
> @escopecz can you take a look at the [feedback above](https://github.com/mautic/mautic/pull/9525#pullrequestreview-571976487)? We also will need a small PR to the docs to update about this feature.


To be honest I don't understand [Norman's feedback above](https://github.com/mautic/mautic/pull/9525#pullrequestreview-571976487). I don't know what to do.

**Comment by npracht** [comment]
We just discussed in PM. He could reproduce :)

**Comment by escopecz** [comment]
I had a call with Norman. It's clear to me now. The action can be saved with value `some@valid.email {contactfield=email}` with a space there. The comma is missing. I will fix this to alert the user.

**Comment by RCheesley** [comment]
@escopecz I saw that you were going to fix the issue that @npracht mentioned but this is marked as RTC which could be confusing, so I will remove the label and if we get a test with that fix implemented we will be good to merge.

**Comment by RCheesley** [comment]
@escopecz we would like to consider this for the 4.1 release but we have conflicts and outstanding feedback to address. 

Do you think that you might be able to get this addressed so that we can get this into the milestone?

Thanks!

**Comment by escopecz** [comment]
@kuzmany @npracht @RCheesley I fixed the validation problem Norman found. This PR is good to go.

**Review by npracht — DISMISSED** [review]
This now works awesomely for me 🚀 
Thanks @escopecz !

**Review by kuzmany — DISMISSED** [review]
Works. nice PR 👍

**Comment by dennisameling** [comment]
@escopecz The PHPSTAN checks are failing now and there's another failing test as well 😅 would you mind having a look?

**Comment by escopecz** [comment]
@dennisameling this PR is green again

**Pull request merged**
