### PR TITLE
Transliterate filenames in elFinder

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

It's better sanitize filenames and directories in elFinder to prevent use special characters, accents and empty spaces. This PR deliver it

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Try create directory  `directory with čšťĺé`
3. elFinder should create `directory-with-cstle`
4. Try upload file `filename with čšťĺé.png`
5. elFinder should upload `filename-with-cstle.png`

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11324"></a>

### CODE REVIEW

**Comment by jos0405** [comment]
@kuzmany 
I'm sure I'm trying to test it wrong.
For me elfinder is not showing, just the old file manager.
I tried to regenerate assets, clear browser cache, reload page.

image

**Comment by kuzmany** [comment]
@jos0405 elfinder use old legacy builder. 
elfinder for GrapesJs is not ready yet https://github.com/mautic/mautic/pull/10902

**Comment by RCheesley** [comment]
Looks like this is blocked by both #10902 and the PR that one is waiting for #10847 so I am going to mark this as blocked until those are resolved.

**Comment by kuzmany** [comment]
@RCheesley we use elfinder also in other places like GrapesJs (code mode, legacy builder). Then we can go to test mode

**Review by volha-pivavarchyk — DISMISSED** [review]
Works well
image
image

**Comment by kuzmany** [comment]
@escopecz rebased

**Review by escopecz — APPROVED** [review]
Thanks! 👍

**Pull request merged**
