### PR TITLE
FIX leak checked attribute in cycle

### PR DESCRIPTION
**Pull request by luk4s**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [X ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

In case of definition form checkboxes/radios with default value, mautic render form "checked" attribute on every input below "matched" checkbox/radio.

In twig template there is a cycle through `list` possible value. For each listItem top-level defined variable `inputAttributes` is extended (by merge) with mandatory attributes - in every iteration. But there is a condition for default value - when condition is met, variable `inputAttributes` was extended by merge again, with `checked` attribute. This action keep persisted through iteration.

I suggest just rename variable in cycle, for prevent overwrite top-level `inputAttributes`.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Go to "Components" > "Forms" and create new "Form object"
3. Under "Fields" tab add new field "checkbox groups" or "radio groups"
4. In tab "properties" fill in at least 5 pairs
5. Return to 1st tab ("general") and fill "Default value" by value of your first property <- this is important - filll in 1st value
6. Now save the form, go to preview => you will see last radio is checked (or all checkboxes are checked)

### CODE REVIEW

**Comment by andersonjeccel** [comment]
Hey!
Would you like to fix some minor issues like this one while wait for devs to review your PR?
Here is a list:
- https://github.com/mautic/mautic/issues/13667
- https://github.com/mautic/mautic/issues/13433
- https://github.com/mautic/mautic/issues/13441
- https://github.com/mautic/mautic/issues/13730
- https://github.com/mautic/mautic/issues/13729
- https://github.com/mautic/mautic/issues/13731
- https://github.com/mautic/mautic/issues/13732

**Review by kuzmany — CHANGES_REQUESTED** [review]
I see this on preview (do not investigate if it's related to this)

image

**Comment by escopecz** [comment]
@all-contributors please add @luk4s for code. please add @luk4s for doc

**Comment by escopecz** [comment]
@all-contributors please add @luk4s for code

**Review by RCheesley — DISMISSED** [review]
I've raised the issue you mentioned @kuzmany as that exists on the 5.x branch so not related to this PR. See #13801.

Before the PR I see all the checkboxes selected:

before-pr

With this PR only the default ones are selected

after-pr

Thanks @luk4s for the PR! GTG!

**Review by escopecz — APPROVED** [review]
I found what's going on with the hidden input that was visible as HTML in the form. It needed the `|raw` filter after replace. It comes from https://github.com/mautic/mautic/pull/6282 if anyone is interested. It looks weird that there is a hidden field with the same name as the checkbox but apparently it doesn't cause any problems.

**Pull request merged**
