### PR TITLE
Update page display on timeline

### PR DESCRIPTION
**Pull request by dongilbert**
Please answer the following questions:

| Q             | A
| ------------- | ---
| Bug fix?      | Y
| New feature?  | N
| BC breaks?    | N
| Deprecations? | N
| Fixed issues  |  N/A

## Description

This PR adds a better layout for page visit lead timeline entries. It will now parse out the query parameters for a nicer layout.

### CODE REVIEW

**Comment by dbhurley** [comment]
+1 works for me

**Comment by escopecz** [comment]
I'm not quite sure if this is how it's suppose to look like:
mautic-timeline

**Comment by dongilbert** [comment]
@escopecz I've removed the gradient from the center timeline bar. That is what was causing it to be hard to see. As far as the icons are concerned, they are missing locally for me, but they are working fine on dev.mautic.com. I'm not sure what's going on there.

**Comment by escopecz** [comment]
The icons are missing in the latest staging as well, so it's not an issue of this PR. All is good :+1:

**Comment by escopecz** [comment]
Just looking at the code. The icons were loaded from the menu defined at config.php and since the config was restructured some of the icons stopped showing up.

**Pull request merged**
