### PR TITLE
Fixed Import validation when uploading a CSV file in Mautic 4.x with PHP 8

### PR DESCRIPTION
**Pull request by alinmbb**
Fixed Import validation when uploading a CSV file in Mautic 4.x with PHP 8

 ## Which branch should I use for my PR? a.b

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Make sure you use PHP 8. 
3. Go to Contacts.
4. Select Import from Arrow menu.
5. Upload a CSV file.
7. The upload should be validated successfully.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11011"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

Thanks for the PR @alinmbb and welcome to the community!  We don't yet support PHP8 so it's great to find and fix things which will speed up our adoption! 

In case it's of interest, here's the WIP PR: https://github.com/mautic/mautic/pull/9969 - if you'd be up for helping us with getting the PHP8 support finalised, we'd definitely appreciate the assistance!

**Review by escopecz — APPROVED** [review]
The code looks good to me 👍  Thanks!

**Review by RCheesley — APPROVED** [review]
Tested this while reviewing another PR that needed this fix (#11060) and this does indeed fix the issue with PHP8.

Thanks @alinmbb ! LGTM! 🚀

**Comment by RCheesley** [comment]
As this is based on the 4.x branch and to save you from having to rebase against 4.2, it will be released with 4.3 (end of May) when we're also expecting to release PHP8 support (all being well with finding a BC way to address a couple of the issues we've found this last week).

**Comment by RCheesley** [comment]
@all-contributors please add @alinmbb for code

**Pull request merged**
