### PR TITLE
Allow Record UTM Tags action for campaign forms

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging 
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Allow Record UTM Tags action for campaign forms. Nothing more, nothing less.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create campaign form
3. Create Record UTM Tags action (before you were not able to do it)

### CODE REVIEW

**Comment by RCheesley** [comment]
@kuzmany thanks for this PR! Please can you elaborate on the description so that people understand how they should test this?  Please assume that folk don't know how UTM tags work in Mautic and how they should create the conditions for this action in the campaign to be triggered.

We will also require documentation to explain how someone can use this. At the moment the only reference in the docs is to the fact that 'Record UTM Tags' can only be used [when a form submission contains them](https://docs.mautic.org/en/contacts/manage-contacts/contact-monitoring#utm-codes) - is that still the case?  It is not at all clear from your PR description.

Thanks in advance!

**Comment by kuzmany** [comment]
@RCheesley I don't know how it works either. 
Just one friend ask me If possible allow it for campaign forms too.
But yes, should works like you send. If somebody come on landing page with UTM tags, then tags are recorder if you choose action.

**Comment by RCheesley** [comment]
OK, but that goes against the whole campaign forms / standalone forms differentiator I thought, being that standalone forms have actions and campaign forms you do the actions in a campaign?

Shouldn't this be added as a campaign action, rather than as an action on the form itself?  It would make more sense to me given that when you use a campaign form you build out all your actions within the campaign itself.

**Comment by ShareBtech** [comment]
I tested this and worked well.

image



image

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by LeonOltmanns** [comment]
@kuzmany I just tried to test this PR and the Mautibox puts out the following error:

image

**Comment by LeonOltmanns** [comment]
And besides the error, I have to side with @RCheesley regarding the difference between Standalone and Campaign forms. Adding a single "Action" option to the campaign-forms would create a lot of confusion. Nevertheless, having it as a Campaign-Action would be very handy.

**Comment by escopecz** [comment]
This PR is interesting. This PR does not have any code changes. The same code changes were added in https://github.com/mautic/mautic/pull/9253

So I'm closing this PR.

**Pull request closed without merging**
