### PR TITLE
Sms send by segments

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/346
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This is huge update to text messages. 
PR added segments to SMS bundle as broadcast. 
Same approach like emails. 

- [x] Segments support for SMS in UX similar like in emails
- [x] Sent SMS by broadcast command 
`php bin/console mautic:broadcast:send --channel=sms --batch=100` 

image

- [x] Do Not Contact for channels in Contact list  view
image

- [x] Do Not Contact for channels in Contact detail view

- [x] Sent/failed logging
that means - new is_failed columns and details column in sms_message_stats table
image

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Setup SMS transport
3. Try create SMS
4. Now you can choose between segments/campaign SMS type
5. Create campaign SMS type and test as usual
6. Create segments SMS type and setup publish from/up date
7. Then wait to `mautic:broadcast:sent` cron or try `php bin/console mautic:broadcast:send --channel=sms`
8. You should receive SMS to your list  of contacts from selected segments

### CODE REVIEW

**Review by npracht — DISMISSED** [review]
I works like in emails ;)

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
Bumping to 3.2 due to unresolved conflicts.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by npracht** [comment]
@mabumusa1 i cannot review this one, Zdeno is in my team and we're using it in production for... 1 year !

**Comment by mabumusa1** [comment]
> @mabumusa1 i cannot review this one, Zdeno is in my team and we're using it in production for... 1 year !

I will test this after the current release hopefully we can get it into the next release. this is an important feature!

**Comment by mabumusa1** [comment]
@kuzmany when you have time please fix travis issue. Thanks

**Comment by kuzmany** [comment]
@mabumusa1 Yes, I will work on it this week I hope
We're using this PR in production along with https://github.com/mautic/mautic/pull/8558

**Review by mabumusa1 — APPROVED** [review]
I manually tested this feature with Twilio, it worked as expected. it adds a very nice feature to SMS. 

I think this should be considered in v3.2

**Comment by npracht** [comment]
I don't know why codecov is complaining as far as we increase code coverage. I'll merge, nevermind.

**Pull request merged**
