### PR TITLE
Fix campaign trigger inactive schedule decision after scheduled event

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.2
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
Noticed ugly issue.
If you use scheduled event in campaigns, then events after false decision are triggered, even thought parent event was not triggered yet.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create campaign like this 
- action scheduled to 5 minutes
- attach any decision
- add to negative decision after 1 minute another action

image

3. Add contact and trigger campaign
4. Then re-add contact again and trigger campaign again
5. Wait one minute and trigger campaign again
6. Evet  scheduled after decision is triggered even thought the parent event was not scheduled yet

### CODE REVIEW

**Comment by RCheesley** [comment]
I have tested this locally and I was not able to get it to do what you are reporting.

I followed these steps:

1. Create the campaign as instructed, enabling contacts to rejoin the campaign
2. Trigger the campaign
3. Notice that the first tag was correctly applied
4. Remove the contact from the campaign, rebuild campaigns
5. Re-add the contact to the campaign, rebuild campaign and trigger
6. Contact had the add first tag triggered as expected
7. Contact did NOT have the second tag scheduled or triggered
8. Trigger several more times - contact still does not have the second tag added
9. Trigger after the time lapse has passed - contact has the tag added as expected.

**Comment by kuzmany** [comment]
@RCheesley did you setup same scheduling like on my screenshot?
You should not wait in first round to trigger 5 minutes action.
After re-ad contact to campaign, you should wait 1 minute and then trigger.

**Comment by RCheesley** [comment]
Yes I believe so but will test again as soon as I can! Maybe someone else will also test in the meantime!

**Comment by jos0405** [comment]
Tested, I managed the reproduce the error:
image
After PR it works as expected.
image

**Review by mohit-rocks — APPROVED** [review]
Approving the PR.
It has been already tested and code changes looks good to me.

**Pull request merged**
