### PR TITLE
Fix: Dynamic Content in emails (legacy builder)- default content - 5.X Version

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This is the companion PR of #11887 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by mabumusa1** [comment]
@irfan-synerzip I created this PR to have the same bug fix merged in 5.x

@kuzmany please confirm that this code works for 5.x as it did for 4.4

**Comment by mabumusa1** [comment]
@MadlenF can you test this PR, please?

**Comment by MadlenF** [comment]
Works as expected from user perspective :)

**Comment by mabumusa1** [comment]
@RCheesley we have a confirmation from @MadlenF that this PR works on `5.x`, let's merge it since we already did for `4.x`

**Comment by RCheesley** [comment]
Sure, if it's OK from the code perspective and assuming that @MadlenF tested on the 5.x branch then this should be OK to go.

**Comment by MadlenF** [comment]
Yep, tested this PR with Gitpod on the 5.x branch! :)

**Review by escopecz — APPROVED** [review]
👍

**Pull request merged**
