### PR TITLE
Ip service lookup changes

### LINKED ISSUE #1231: Telize : The public API will permanently shut down on November 15th
http://www.telize.com/
Just that. Better to make other IP lookup service by default ?

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**

This PR addresses and fixes #1231.  The default IP lookup service, Telize, shut down. This PR does several things:

1. It now defaults to a newly added MaxMind GeoIp2 City Download service.  This will download Maxmind's free city IP lookup database which will be used to glean general info on an IP.
2. To support such an IP lookup with accompanying form UI elements, the IpService classes have been re-organized while keeping BC support for old AbstractIpLookup use in case any 3rd party IP lookup services exist out in the wild
3. `Mautic\CoreBundle\IpLookup\AbstractLookup` replaces the deprecated `AbstractIpLookup`
3. `Mautic\CoreBundle\IpLookup\AbstractLocalDataLookup` has been added with accompanying methods for data stores that are stored locally (such as above)
4. `Mautic\CoreBundle\IpLookup\AbstractRemoteDataLookup` has been added with accompanying methods for services that use API calls to fetch IP details
5. `Mautic\CoreBundle\IpLookup\IpLookupFormInterface` has been added for services that support injecting custom config options into Mautic's configuration
6. `Mautic\CoreBundle\Factory\IpLookupFactory` has been added to create the different lookup services when necessary
7. `mautic:iplookup:download` command has been added to allow use of cron to keep local datastores up to date
8. PhpUnit was added as a dev dependency and config_test.php was slightly changed to support the basic tests included in the PR
9. Telize was converted to use it's now for pay API

**Testing**

1. Apply the PR
2. Run `composer install`
3. Run the tests if you have PhpUnit configured on your system
4. Or manually test by selecting each IP service and test by going to a public landing page on a remote Mautic system (can't be 127.0.0.1 or ::1), get details, delete details in the ip_addresses table, then try the next
5. Choose the MaxMind GeoIp2 City Download service a button should appear to download the file.  It'll be btn-danger if the file hasn't been downloaded with "Fetch..." or btn-success if it has been with "Update..." and a tooltip of when the file was last updated
6. Click the button and should get a success response after the data store has been downloaded
7. Ensure the config saves

### CODE REVIEW

**Comment by escopecz** [comment]
```
phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist app/bundles/CoreBundle/Tests`
```
command was used for running tests with result `OK (12 tests, 91 assertions)`

Everything seems to be working :+1:

**Comment by dbhurley** [comment]
Does this have everything necessary for changing defaults and notifications for existing upgrades?

**Comment by alanhartless** [comment]
Yes, to test the upgrade notification for the IP service change, use a non Git based installation, manually edit local.php and change update_stability to dev and ensure ip_lookup_service = telize (new installations won't have this in local.php by default).  Clear the cache, logout and back in to trigger the 10.0.0.1 (dev) upgrade notification.  Click upgrade and you should see the notice on the success message.

**Comment by escopecz** [comment]
I misbehaved and did not set the `ip_lookup_service = telize` in the config. Not sure if that is the reason, but I don't have the *MaxMind GeoIp2 City Download service* option in my configuration after upgrade. Upgrade itself was successful and the IP lookup notification showed up.

One problem can be that the dropdown is not complete, it doesn't fit to my screen and the bottom options are not visible:
mautic-ip-lookup-dropdown

The full list I see in the source code is
```
<select id="config_coreconfig_ip_lookup_service" name="config[coreconfig][ip_lookup_service]" class="form-control" autocomplete="false" style="display: none;">
    <option value=""></option>        <option value="freegeoip">freegeoip.net</option>
                <option value="geobytes">Geobytes</option>
                <option value="geoips">GeoIPs</option>
                <option value="ipinfodb">IPInfoDB</option>
                <option value="maxmind_country">MaxMind - Country Geolocation</option>
                <option value="maxmind_precision">MaxMind - GeoIP2 Precision</option>
                <option value="maxmind_omni">MaxMind - Insights (formerly Omni)</option>
                <option value="telize" selected="selected">Telize</option>
</select>
```

**Comment by alanhartless** [comment]
No, not having telize set in the config would cause the post-upgrade message to not show.  But it would not cause the list to not include the new option.  Did the cache not get cleared for some reason?

**Comment by alanhartless** [comment]
Let me make sure the dev package I updated had the right branch in it :-)

**Comment by alanhartless** [comment]
Haha...nope.  I rebuilt it and uploaded it last night thinking I made a change to help in the testing.  Guess I was on the wrong branch. Give me a sec and I'll repackage.

**Comment by dbhurley** [comment]
In fact, the dropdown not displaying is a common issue that occurs with any drop down that appears at the bottom of a page.

**Comment by alanhartless** [comment]
@dbhurley That's a chosen issue and not sure they've fixed it yet.  Something to look into.

**Comment by alanhartless** [comment]
https://github.com/harvesthq/chosen/issues/155 Issue for 4 years :-) 

I built and uploaded a new dev package.  I started the upgrade message in a different branch which is what I built the dev packages on.  But then saw this PR still open and just merged it into the same branch since it was all related.  But I didn't build the dev package on the merged branch.

Anyway, if you want to try the whole process again, you'll have to revert/setup a new installation prior to the changes done to upgrade to 1.2.3. But if the upgrade message showed, that was the only change since you last tested so the IP lookup stuff should still work.

**Comment by dbhurley** [comment]
:+1:

**Comment by alanhartless** [comment]
We good to merge then?

**Comment by dbhurley** [comment]
Let's do it.

**Comment by mellsaid** [comment]
@alanhartless - I just revived an old discussion about maxmind precision not working here . thought you may be able to shed some light? #1404 . Not sure if it's relevant to #1167

**Pull request merged**
