### PR TITLE
Fix datetime contact value campaign condition

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

If you use datetime field to contact value campaign condition it was not compare properly. This PR fixed it

1. Change timezone in configuration to Europe/paris
2. Create datetime field 
3. Create contact and set datetime If today is 28.10, then set 27.10. 2021 00:00
4. Create campaign with condition field value with date -1 day

image

5. Trigger campaign
6. Before contact was not true for condition because we compare datetime (yyyy-mm-dd h:i:s) with date (yyy-mm-dd). 
7. After PR should work  properly

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10560"></a>

### CODE REVIEW

**Comment by adiux** [comment]
will this fix https://github.com/mautic/mautic/issues/9040 as well?

**Comment by kuzmany** [comment]
@adiux no

**Comment by MadlenF** [comment]
@kuzmany Hi, I just tested this from a user perspective and for "days" it works fine. But if you select "hours" in the dropdown the conditions always is "true" even if it is not. So for example I create a contact and set datetime to 07.12.2021 06:00:00 (if now is 07.12.2021 10:00:00). Then I create the campaign with condition field value with hours -1 hour. So the condition is false, but Mautic says it's true (I guess it just checks for the day?). 
This is not the expected behavior, isn't it? 

@adiux  In my opinion, it does not fix #9040 but you could build birthday campaigns , date-based reminder, etc with this PR. So it would actually solve the problem and that is something many persons from the community are asking for. 

So it would be great if this PR works also for hours :)

**Comment by bradjones1** [comment]
Related for segments: https://github.com/mautic/mautic/pull/9784

**Comment by ghost** [comment]
Can this be tested ? Or does this "This branch is out-of-date with the base branch" means it has to be readapted?
Will be the comment of [MadlenF ](https://github.com/mautic/mautic/pull/10560#issuecomment-987751486)be considered?

Later edit: opened GitPod and saw by myself that it cannot be tested. Following error appears:

> Failed to start mautic: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-mautic docker-compose -f /workspace/mautic/.ddev/.ddev-docker-compose-full.yaml up --build -d', action='[up --build -d]', err='exit status 15', stdout='', stderr='services.web.extra_hosts array items[0,1] must be unique'

**Comment by kuzmany** [comment]
Close favor to M5 version https://github.com/mautic/mautic/pull/12864

**Pull request closed without merging**
