### PR TITLE
Revert back SlimScroll library to Version: 1.3.2 - fix scroll issue

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging for features or enhancements / 3.0 for bug fixes 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
I find the library what make ugly middle button scroll issue.
I've noticed it made this @anton-vlasenko  update of slimScroll library  https://github.com/mautic/mautic/commit/e7fb2616bf9bac092bb2b16e0a3503fbdcd3da00#diff-1175126cdcb0bf74d4535df8bd48e5940235520ddff2be4a4e4c9cd4177a2355 
It's not clear what Anton did make a changes, but I made a research and this comment fix issue from original 1.3.2 version - https://github.com/rochal/jQuery-slimScroll/issues/316#issuecomment-566278726  

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Change your window size to see slim scroll on left navigation menu 
3. Then try scroll in the navigation menu and try scroll in all page
4. Scrolling doesn't work
5. After patch should work

image

### CODE REVIEW

**Review by dennisameling — APPROVED** [review]
Thanks @kuzmany! Just tested and works as described 🚀

**Review by dennisameling — CHANGES_REQUESTED** [review]
Did some more testing. While this works as described, this change causes 360 (!) console errors in my browser: 

image

That was exactly the reason why https://github.com/mautic/mautic/commit/e7fb2616bf9bac092bb2b16e0a3503fbdcd3da00#diff-1175126cdcb0bf74d4535df8bd48e5940235520ddff2be4a4e4c9cd4177a2355 was done in the first place 😞 

I tried [updating the library to 1.3.8](https://github.com/rochal/jQuery-slimScroll/releases) locally (it's the latest version that was released in 2016, after that no new updates have been published), but that causes another issue where the sidebar doesn't fill the height of the screen anymore:

image

@kuzmany do you have any other suggestions how we could fix this?

**Comment by kuzmany** [comment]
@dennisameling nice catch. I've made research and it looks like 1.3.2 contains bug associate with chrome. Explanation here  https://github.com/rochal/jQuery-slimScroll/issues/316#issuecomment-566278726 and 
I've taken 1.3.2, apply solution from comment and minified it.
Now should works properly

**Comment by dennisameling** [comment]
Thanks!! I'll test again (hopefully next week) for 3.2 and then merge 👍

**Review by anton-vlasenko — CHANGES_REQUESTED** [review]
@kuzmany Thank you for fixing it.
I've updated the SlimScroll library to make it compatible with jQuery 3.x because some jQuery functions were deprecated in jQuery 3.x https://github.com/mautic/mautic/pull/8254
I've tested your fix and I confirm that it works.
But could you please regenerate assets with `bin/console mautic:asset:generate`?
Because this PR in its current state doesn't fix the issue for production mode. It only fixes the issue for instances that are in development mode.
Thank you.

**Comment by kuzmany** [comment]
@anton-vlasenko assets are regenerated on release, not for PR

**Comment by npracht** [comment]
As @dennisameling feedbacks have been addressed and @anton-vlasenko comment answered (this is true, I generate assets when creating the release), I'll merge it.
Note that we also use it in production for a while with great results.

**Comment by anton-vlasenko** [comment]
@kuzmany I thought that we have to regenerate assets for each PR. It's news to me. :)
Thank you for letting me know.

**Pull request merged**
