### PR TITLE
Plugin form loading

### PR DESCRIPTION
**Pull request by mqueme**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
|Enhancement | y
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR changes field matching to pagination
[//]: # ( As applicable: )

#### Steps to test this PR:
1.  apply this PR and see fields listed through pages
2. test that fields are mapped correctly

### CODE REVIEW

**Comment by escopecz** [comment]
Initial form load was 592 KB, 5.8s which is an improvement compared to https://github.com/mautic/mautic/pull/3648. Loading a next page of the mapping fields takes about the same memory and time. The command to fetch leads is working fine. It all looks good! 👍

**Comment by virlatinus** [comment]
It works as described! +1

**Comment by reindje** [comment]
Thanks, i did a pull request, now the mapping settings are not saved in the plugin. I do not see any error in the log but settings are not stored in the database.

**Comment by escopecz** [comment]
@reindje You'll have to build the assets if you are testing this in the production environment. Run `php app/console mautic:assets:generate` command to do so. Then refresh the page and test again.

**Comment by reindje** [comment]
@escopecz Thanks, that works!

Now i have the problem that i can not find the SF Account Name (Name) field in the Mapping Companies tab. I fixed this now by adding this field directly to the plugin settings in MySql.

On command line i get this warning when i run the integration:fetchleads command:

PHP Warning:  array_flip(): Can only flip STRING and INTEGER values! in /var/www/mautic_dev/plugins/MauticCrmBundle/Integration/CrmAbstractIntegration.php on line 229

**Comment by escopecz** [comment]
Report it as a new issue with steps to replicate, please.

**Comment by reindje** [comment]
@escopecz Ok, will do

**Comment by mqueme** [comment]
@reindje , thanks for testing this out and your feedback, I have updated this PR to fix the error you are getting.

**Comment by reindje** [comment]
Hi @mqueme It seems that companies are not synced at all on the current code (head of this pull-reqeust)

**Comment by mqueme** [comment]
@reindje I have added a fix for this, looks like it was not working when only company name was being matched

**Comment by reindje** [comment]
@mqueme Thanks, it works now!

**Pull request merged**
