### PR TITLE
Campaign table new columns

### PR DESCRIPTION
**Pull request by alfredoct96**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | features
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | N/A

#### Description:

Added three new columns to Campaign table:
* created at
* created by
* modified at

Changed default order to decreasing modified date.

### Before
campaignbefore

### After
campaignafter

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create two or more campaigns
3. Check existence of the new columns
4. Check default order

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/9692"></a>

### CODE REVIEW

**Comment by dennisameling** [comment]
Hi @alfredoct96! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since we don't have access to your branch, could you please click "Update branch" at the bottom of this PR? If that doesn't work, you can also run `git merge upstream/features` locally. Thanks in advance!

image

**Comment by alfredoct96** [comment]
> Hi @alfredoct96! Thanks for your PR  we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since we don't have access to your branch, could you please click "Update branch" at the bottom of this PR? If that doesn't work, you can also run `git merge upstream/features` locally. Thanks in advance!
> 
> image

Done @dennisameling

**Comment by atowne07** [comment]
This worked on Gitpod. 

Question about Gitpod though, is there any configuration for cron jobs that needs to be done? I tried creating a test segment with a contact to add to the campaign, but... 
- The segment membership did not populate with the test contact I created
- After manually adding the contacts to the segment, the campaign did not populate with the segment members
- After manually adding the contacts to the campaign, campaign events did not execute

Some PRs (like this one) can still be tested without actually executing anything, but others will be more challenging. Perhaps someone can guide me on what would need to be done, and if it's easy enough I may be able to test some more!

**Comment by jos0405** [comment]
> This worked on Gitpod.
> 
> Question about Gitpod though, is there any configuration for cron jobs that needs to be done? I tried creating a test segment with a contact to add to the campaign, but...
> 
> * The segment membership did not populate with the test contact I created
> * After manually adding the contacts to the segment, the campaign did not populate with the segment members
> * After manually adding the contacts to the campaign, campaign events did not execute
> 
> Some PRs (like this one) can still be tested without actually executing anything, but others will be more challenging. Perhaps someone can guide me on what would need to be done, and if it's easy enough I may be able to test some more!

This is just a visual enhancement. Crons would be needed to populate segments and run campaigns. I don't think its needed.

**Review by jos0405 — DISMISSED** [review]
Works as expected (gitpod checked)

**Comment by mabumusa1** [comment]
@alfredoct96 please rebase this PR as well, I think it is ready to commit afterwards

**Comment by alfredoct96** [comment]
> @alfredoct96 please rebase this PR as well, I think it is ready to commit afterwards

Done

**Review by jos0405 — APPROVED** [review]
Does what it claims. :)

image

**Pull request merged**
