### PR TITLE
Add empty and not empty to segment stage filters.

### PR DESCRIPTION
**Pull request by tachang**
Add empty and not empty to segment stage filters. Also fixes a bug with eq/neq.

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? |  Yes
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/2485
| BC breaks? | Not Sure (what is BC?)
| Deprecations? | No

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

Adds empty and not empty to stages in segment filters.

[//]: # ( As applicable: )
#### Steps to test this PR:
1. Create a contact and make sure stage is null / not set.
2. Create a segment where stage is set to empty.
3. Run `php app/console mautic:segments:rebuild` and make sure only 1 contact is added to segment.
4. Set the contact's stage to something not null.
5. Modify the segment to filter by stage not empty.
6. Run the segment rebuild again and make sure the contact is back in the segment.

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by tachang** [comment]
I can't seem to figure out why this expression results in multiple contacts being added. My test case is a single contact with a null stage. This code runs and I get 3 contacts being affected when I run `php app/console mautic:segments:rebuild` instead of 1 which I would expect.

Wondering if anyone can help out.

**Comment by tachang** [comment]
This PR is a work in progress.

**Comment by tachang** [comment]
Okay this PR is ready to be reviewed. The problem was I wasn't taking into account anonymous contacts so in fact it was working and I just didn't realize it.

**Comment by tachang** [comment]
Yikes I forgot about the $operand flipping it around. I will have to fix it.

**Comment by tachang** [comment]
Okay fixed the PR. Should be good to go.

**Comment by tachang** [comment]
@collinkrawll I actually had introduced the bug with the patch. Should be good now.

**Comment by tachang** [comment]
Got it. @collinkrawll I went ahead and removed `$operand` and just hard coded it in the string to be more explicit as to what we are doing.

**Comment by dongilbert** [comment]
Works as expected! Thanks for this @tachang

**Pull request merged**
