### PR TITLE
Fix for all foreign tables segment filter with empty/notEmpty  expression

### LINKED ISSUE #11178: Filter tag -> empty failed to filter contact into segment
### Mautic Version

4.2.x series

### PHP version

7.4+

### What browsers are you seeing the problem on?

Chrome

### What happened?

I accidently removed a tag on thousands of contacts that was assigned to a segment filtered with that tag.  

I figured since those contact does not have any other tags on it then I could create a segment and set filter to tag -> empty then create a segment campaign to add the tag back on to those with empty tags. 

But the the contact with no tags are not being added into segment with filter set at tag -> empty

The cron job is working fine because other filtering being processed .. just not the tag "empty" 

### How can we reproduce this issue?

Step 1: Have contact or several contacts with no tags
Step 2: Create a segment and set filter with tag = empty 

Notice that contacts with no tag are not being added to the segment. 

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/109790883-filter-tag-empty-failed-to-filter-contact-into-segment?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #11178 

#### Steps to test this PR:

I suppose to all filters generate by  ForeignValueFilterQueryBuilder https://github.com/mautic/mautic/blob/fd3cfc5d65d8c29f4a7d111e3f7fb1e6f34fd277/app/bundles/LeadBundle/Segment/Query/Filter/ForeignValueFilterQueryBuilder.php generated wrong query for empty/not empty expression. This is example for tags

### empty

Before

```
SELECT COUNT(leadIdPrimary) COUNT, MAX(leadIdPrimary) maxId, MIN(leadIdPrimary) minId
FROM (
SELECT DISTINCT l.id AS leadIdPrimary
FROM leads l
WHERE (l.id IN (
SELECT par2.lead_id
FROM lead_tags_xref par2
WHERE par2.tag_id IS NULL)) AND (l.id NOT IN (
SELECT par3.lead_id
FROM lead_lists_leads par3
WHERE par3.leadlist_id = 4))) sss {"segmentId":4}

```
After 

```
CREATE SQL:
SELECT COUNT(leadIdPrimary) COUNT, MAX(leadIdPrimary) maxId, MIN(leadIdPrimary) minId
FROM (
SELECT DISTINCT l.id AS leadIdPrimary
FROM leads l
WHERE (l.id NOT IN (
SELECT par2.lead_id
FROM lead_tags_xref par2)) AND (l.id NOT IN (
SELECT par3.lead_id
FROM lead_lists_leads par3
WHERE par3.leadlist_id = 4))) sss {"segmentId":4}
```

### notEmpty

before 

```
SELECT COUNT(leadIdPrimary) COUNT, MAX(leadIdPrimary) maxId, MIN(leadIdPrimary) minId
FROM (
SELECT DISTINCT l.id AS leadIdPrimary
FROM leads l
WHERE (l.id IN (
SELECT par2.lead_id
FROM lead_tags_xref par2
WHERE par2.tag_id IS NOT NULL)) AND (l.id NOT IN (
SELECT par3.lead_id
FROM lead_lists_leads par3
WHERE par3.leadlist_id = 4))) sss {"segmentId":4}
```

After

```
SELECT COUNT(leadIdPrimary) COUNT, MAX(leadIdPrimary) maxId, MIN(leadIdPrimary) minId
FROM (
SELECT DISTINCT l.id AS leadIdPrimary
FROM leads l
WHERE (l.id IN (
SELECT par2.lead_id
FROM lead_tags_xref par2)) AND (l.id NOT IN (
SELECT par3.lead_id
FROM lead_lists_leads par3
WHERE par3.leadlist_id = 4))) sss {"segmentId":4}
```

If join to table we cannot check `IS NULL` or `NOT IS NULL`  because we have to check just if row exist in foreign table or not. 

We should test all ForeignValueFilterQueryBuilder filters:

 ```
$this->filters['lead_email_received']           = [
            'type'                => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table_field' => 'lead_id',
            'foreign_table'       => 'email_stats',
            'field'               => 'email_id',
            'where'               => 'email_stats.is_read = 1',
        ];

        $this->filters['lead_email_sent_date']          = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'email_stats',
            'field'         => 'date_sent',
        ];
        $this->filters['hit_url_date']                  = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'page_hits',
            'field'         => 'date_hit',
        ];

   $this->filters['globalcategory']                = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'lead_categories',
            'field'         => 'category_id',
        ];
        $this->filters['tags']                          = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'lead_tags_xref',
            'field'         => 'tag_id',
        ];
        $this->filters['lead_email_sent']               = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'email_stats',
            'field'         => 'email_id',
        ];
        $this->filters['device_type']                   = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'lead_devices',
            'field'         => 'device',
        ];
        $this->filters['device_brand']                  = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'lead_devices',
            'field'         => 'device_brand',
        ];
        $this->filters['device_os']                     = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'lead_devices',
            'field'         => 'device_os_name',
        ];
        $this->filters['device_model']                  = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'lead_devices',
            'field'         => 'device_model',
        ];

  $this->filters['notification']                  = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'push_ids',
            'field'         => 'id',
        ];
        $this->filters['page_id']                       = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'page_hits',
            'foreign_field' => 'page_id',
        ];
        $this->filters['redirect_id']                   = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'page_hits',
            'foreign_field' => 'redirect_id',
        ];
        $this->filters['source']                        = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'page_hits',
            'foreign_field' => 'source',
        ];
        $this->filters['hit_url']                       = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'page_hits',
            'field'         => 'url',
        ];
        $this->filters['referer']                       = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'page_hits',
        ];
        $this->filters['source_id']                     = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'page_hits',
        ];
        $this->filters['url_title']                     = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'page_hits',
        ];
 $this->filters['utm_campaign']          = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'lead_utmtags',
        ];
        $this->filters['utm_content']           = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'lead_utmtags',
        ];
        $this->filters['utm_medium']            = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'lead_utmtags',
        ];
        $this->filters['utm_source']            = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'lead_utmtags',
        ];
        $this->filters['utm_term']              = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'lead_utmtags',
        ];
        $this->filters['campaign']              = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'campaign_leads',
            'field'         => 'campaign_id',
            'where'         => 'campaign_leads.manually_removed = 0',
        ];
        $this->filters['lead_asset_download']   = [
            'type'          => ForeignValueFilterQueryBuilder::getServiceId(),
            'foreign_table' => 'asset_downloads',
            'field'         => 'asset_id',
        ];
```

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11253"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
@kuzmany could you please add the filter with tag empty and not empty into this fixture:

https://github.com/mautic/mautic/blob/4.3/app/bundles/LeadBundle/Tests/DataFixtures/ORM/LoadSegmentsData.php

And assert that it does what it should?

**Review by escopecz — DISMISSED** [review]
Yes, this works! I added some tags to the test so we know that the not empty filter works correctly and also added one more test for empty and not empty companies. That works too. The list of filters you shared is not that long because many of them do not have the empty and not empty operators.

Nicely done, thanks!

**Review by RCheesley — DISMISSED** [review]
I checked all the device type options and tags in both segments and reports, all working as expected (thanks for adding the fixtures!)

**Comment by TechBill** [comment]
tag -> empty still not working for me

**Review by TechBill — COMMENTED** [review]
Tested via PR Gitpod 

1. Populated database with sample contact (51 visible contacts 2 with tags)
2. Added Segment with tag -> empty
3. Added Segment with tag -> not empty
4. Rebuild Segment

Result
Empty - 53 (4 anonymous contact)
Not Empty - 2

tag -> not empty is functioning if it intended to include anonymous contact into the count.

Seems to be fixed. (anonymous included in count)

**Review by escopecz — APPROVED** [review]

**Pull request merged**
