### PR TITLE
Report: The Segment Activity Log Report shows the correct entries M5

### PR DESCRIPTION
**Pull request by escopecz**
This is clone of https://github.com/mautic/mautic/pull/11256 for Mautic 5

### CODE REVIEW

**Comment by jos0405** [comment]
I really want to test this, but getting this error in Github when trying to run the segment update:

image

**Comment by jos0405** [comment]
Creating the following report generates debug:
image

image

**Comment by escopecz** [comment]
@jos0405 the debug is there in the dev environment. It's not related to this PR. Is everything else working?

**Review by volha-pivavarchyk — APPROVED** [review]
Works well

**Review by mabumusa1 — APPROVED** [review]
I tested this PR locally, it works as expected

**Pull request merged**
