### PR TITLE
Fix campaign limit

### LINKED ISSUE #9750: --campaign-limit flag on campaign trigger cron is not working after upgrading to 3.3.1
## Bug Description

Yesterday I updated from 3.2.5 to 3.3.1. I must say, I never updated to 3.3.0 - not sure if this was needed.

I have a marketing campaign scheduled with a large number of subscribers that was supposed to kick in today, but no email message shows in the calendar nor any has been sent.

| Q   | A
| --- | ---
| Mautic version | 3.3.1
| PHP version | 7.3 and 7.4 (tested both)
| Browser | Chrome

### Steps to reproduce
1. Create a segment with a arge number of contacts.
2. Create a new email using the blank template. This email was cloned from a previously sent message that worked..
3. Create a very basic marketing campaign targeting the segment, at a relative time, during business hours. This campaign adds 10 points to the contact if it logs into the site. This campaign was cloned from a previous campaign that worked.
 
### Log errors

When I run:

```
sudo -u www-data php web/list/bin/console mautic:campaigns:trigger --campaign-limit=50
[sudo] password for myusername: 
Triggering events for campaign 6
Triggering events for newly added contacts
0 total events(s) to be processed in batches of 100 contacts

0 total events were executed
0 total events were scheduled

Triggering scheduled events
0 total events(s) to be processed in batches of 100 contacts

0 total events were executed
0 total events were scheduled

Triggering events for inactive contacts

0 total events were executed
0 total events were scheduled

Triggering events for campaign 8
Triggering events for newly added contacts
16071 total events(s) to be processed in batches of 100 contacts
 16071/16071 [============================] 100%
```

... I see the following logs being added:

```
[2021-03-02 17:56:53] mautic.ERROR: CAMPAIGN: Campaign Limit exceeded [] []
[2021-03-02 18:53:31] mautic.ERROR: CAMPAIGN: Campaign Limit exceeded [] []
```

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.3
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | https://github.com/mautic/mautic/issues/9750

#### Description:
This PR revert change of campaign-limit parameter to execute campaign 

https://github.com/mautic/mautic/commit/32dbebdf7c2e4a8a866952cb8f5861e813bd376f#diff-cdc167810713fe9774f2fb69e11deed430454d5af018220dd25b3100f172f6f3R250

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create campaign and add few contacts there
3. Try run trigger `php bin/console mautic:campaign:trigger --campaign-limit=2`
4. Without PR return **Campaign Limit exceeded** 
5. After PR works as expected - limit run of campaign to exact contacts

### CODE REVIEW

**Comment by mohit-rocks** [comment]
I did a quick check with the mentioned testing steps. It seems to be working fine.
Here are the screenshots before applying patch and after patch:

Before patch:
Mautic3_Contrib_–_mautic_prod-2021-03-07_php_and_mohit_Mohits-MacBook-Pro-2___Experiments_mautic3

After patch:
Mautic3_Contrib_–_mautic_prod-2021-03-07_php_and_mohit_Mohits-MacBook-Pro-2___Experiments_mautic3

**Comment by jcmartinez** [comment]
This change removes the error. However, messages go out only if the campaign is configured to:

Execute this event = Immediately
mautic-issues-9750

Messages won't go out if the campaign is set to:

Execute this event = at a relative time period
mautic-issues-9750-B

If you want to send messages to a global audience, during business hours, in their time zone, this configurations won't generate the messages. This is what I would expect from the relative schedule setting. It may be possible that I'm missing some configuration or that my expectation is wrong. I'm very new to Mautic.

Note: I checked Saturday and Sunday on the screenshot above, because I'm testing it on a Sunday.

This may be a different problem and it may require a different ticket. This PR accomplished the goal of removing the error message and generating the email messages when [Execute this event = Immediately]. In my opinion, this shouldn't stop this PR from being merged.

**Comment by fedys** [comment]
The PR works as expected. The error `Campaign Limit exceeded` is no longer displayed. Actions are limited to the number specified via the `--campaign-limit` option.

**Comment by jcmartinez** [comment]
I agree that the PR works as expected.

Opening another ticket to track additional issue https://github.com/mautic/mautic/issues/9769

**Comment by RCheesley** [comment]
@kuzmany is there anything we need to test from the original PR where this change was introduced (https://github.com/mautic/mautic/pull/7879) or was it just a typo/misconfiguration?

**Comment by kuzmany** [comment]
@RCheesley nothing, it was misconfiguration. Should be merged this revert

**Review by RCheesley — APPROVED** [review]
LGTM based on the :+1: in the comments! Thanks all!

**Pull request merged**
