### PR TITLE
Email report graph table: Most clicked email links

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ N ]
| New feature/enhancement? (use the a.x branch)      | [ Y ]
| Deprecations?                          | [ N ]
| BC breaks? (use the c.x branch)        | [ N ]
| Automated tests included?              | [ Y ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR adds new report graph table with most clicked email links. The table is available in **Emails** and **Emails Sent** datasources.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create an email with links and send it to your contacts
3. Generate some clicks (open email and click link while not logged into Mautic in the same browser session)
4. Add new **Report** with **Email** datasource
5. Select some columns in the **Data** tab
image
6. Add **Most clicked links** in the **Graph** Tab
image
7. Click **Save and Close** to view report
8. Verify the **Most clicked links** table below the standard data table
image
9. Repeat steps 4-8 for **Emails Sent** datasource
image

### CODE REVIEW

**Comment by escopecz** [comment]
I see no issue with the code changes. Nicely done! I'll approve once the conflicts are resolved.

**Comment by patrykgruszka** [comment]
@escopecz thanks, conflicts are resolved.

**Review by escopecz — APPROVED** [review]
I see no issues with the code. Thanks! 👍

**Review by magdalenaleonow — APPROVED** [review]
Tested, everything works
image

**Pull request merged**
