### PR TITLE
fix sorting fields in contact view according to order in custom field…

### LINKED ISSUE #4168: Field order not respected on contacts/view page
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When viewing a contact detail on the contacts/view page, the display order of fields seems to be by creation date and does not respect the order as set on contacts/fields page (and stored in the database in the lead_fields table, under field_order) 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 5.6

### Steps to reproduce:
1. Change order of field on contacts/fields page
2. New field order is not reflected when viewing details on contacts/view page
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

### PR DESCRIPTION
**Pull request by deakao**
Q | A
-- | --
Bug fix? | Y
New feature? | N
Automated tests included? | N
Related user documentation PR URL | /
Related developer documentation PR URL | /
Issues addressed (#s or URLs) | Fixes [#4168](https://github.com/mautic/mautic/issues/4168) [Forum](https://forum.mautic.org/t/arranging-custom-fields-order-in-contacts-personal/11800/3)
BC breaks? | N
Deprecations? | N

**Description:**
Ordering fields on the contact view page according to the field order on the custom field page.

**Steps to reproduce the bug:**
Go to the custom fields page, click and drag on the 3 points icon on any row, drop the field row in a different order.
Go to any contact view, click on details and the fields order didn’t change.
Steps to test this PR:
Load up this PR on Mauticbox (https://mautibox.com/)
Go to the custom fields page, click and drag on the 3 points icon on any row, drop the field row in a different order.
Go to any contact view, click on details and the order will be exactly the same.

### CODE REVIEW

**Comment by npracht** [comment]
Thanks @deakao ! Is it still an issue on 3.x branch ? If yes can you rebase against this branch ?
Thanks !

**Comment by rodrideme** [comment]
I've tested here(version 2.16.2 and 2.16.1) and it worked perfectly thank you @deakao you rock!!!

**Comment by npracht** [comment]
Hello @deakao could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback. Thanks !

**Comment by npracht** [comment]
I confirm bug persists on M3.

**Comment by npracht** [comment]
Hi @deakao ! Can you please review the small conflict ? I've changed your PR to mautic 3.0 branch.
Also once solved, please confirm it still works properly :)

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Hi @deakao it looks like we have some issues with the Travis build failing. Can you take a look? I'm going to assign this to the 3.1.2 milestone as I don't feel we have time to fix and test before the upcoming release freeze on Sunday.

Therefore this means that you will have to get it fixed and tested before **Sunday, October 18th** to be considered for merging in that release. It would be super if we can get it over the line for that one!

**Comment by MilaGuilherme** [comment]
I didn't read much of the thread, sorry for that, but I've been fixing this for a year now by adding a few changes to the file "CustomFieldRepositoryTrait.php" inside /app/bundles/LeadBundle/Entity/

I did it by adding field order to the query (f.field_order) and then (->addOrderBy('f.field_order', 'asc')) , I didn't have to change anything else to get it to work.

Line 365 to 372:
```
$fq->select('f.field_order,f.id, f.label, f.alias, f.type, f.field_group as "group", f.object, f.is_fixed, f.properties, f.default_value')
                ->from(MAUTIC_TABLE_PREFIX.'lead_fields', 'f')
                ->where('f.is_published = :published')
                ->andWhere($fq->expr()->eq('object', ':object'))
                ->setParameter('published', true, 'boolean')
                ->setParameter('object', $object)
                ->addOrderBy('f.field_order', 'asc');
            $results = $fq->execute()->fetchAll();
```

**Comment by kuzmany** [comment]
@MilaGuilherme Nice catch. Seems like add addOrderBy make sense. Are you able to create pull request? 
Then we can close this PR favor to new one

**Comment by fedys** [comment]
@kuzmany I will create a PR including an automated test.

**Comment by escopecz** [comment]
Closing in favor of https://github.com/mautic/mautic/pull/9494

**Pull request closed without merging**
