### PR TITLE
Segment dependency tree

### PR DESCRIPTION
**Pull request by escopecz**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | /
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

This PR adds new tab to the segment detail page for the segments that have some **Segment Membership** filters. Segments without this filter will not have this tab visible as it would not provide any value.

This is how it draws a tree chart for those segments that have some segment membership filters:
Screen Shot 2021-09-07 at 09 39 29

This is how the chart looks like if there are either duplicate segments in the tree structure or if there is a loop:
Screen Shot 2021-09-07 at 11 08 32

This feature will not affect segment detail page load time. In fact, it will not load on the page load but it will load only when a user clicks on the tab. So no resources will be wasted to build this when not needed.

#### ToDo:
- [x] Test how it works for loops
- [x] Test how it works for duplicated segments

#### Steps to test this PR:
1. Open new Mautic instance with this change applied by clicking the GitPod button bellow.
2. Ensure the new tab is showing only on the right segments that have some segment membership filters.
3. Build a several-level deep segment dependency tree by including/excluding segments and confirm the tree chart is correct.
4. Test what happens if you create a segment loop. For example edit the segment at the end of the tree and include the segment at the top of the tree.
5. Test what happens if you duplicate including/excluding segments in different levels.

#### Other areas of Mautic that may be affected by the change:
1. Just segment detail page

[//]: # ( As applicable: )
#### List of areas covered by the unit and/or functional tests:
1. The functional test builds a 3-level segment dependency and ensures that the API endpoint returns the right data.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11276"></a>

### CODE REVIEW

**Review by RCheesley — CHANGES_REQUESTED** [review]
When testing this PR and opening the dependency graph for Segment 26 (and any other segment which has segment dependencies) in the pre-loaded fixtures I get the following warning (and the segment tree does not show) 😭 :

```
[2022-06-24 16:27:50] mautic.CRITICAL: Uncaught PHP Exception ErrorException: "PHP Notice - Undefined index: properties" at /var/www/html/app/bundles/LeadBundle/Services/SegmentDependencyTreeFactory.php line 83 {"exception":"[object] (ErrorException(code: 0): PHP Notice - Undefined index: properties at /var/www/html/app/bundles/LeadBundle/Services/SegmentDependencyTreeFactory.php:83)
[stacktrace]
#0 /var/www/html/app/bundles/LeadBundle/Services/SegmentDependencyTreeFactory.php(83): Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler->handleError(8, 'PHP Notice - Un...', '/var/www/html/a...', 83, Array)
#1 /var/www/html/app/bundles/LeadBundle/Services/SegmentDependencyTreeFactory.php(39): Mautic\\LeadBundle\\Services\\SegmentDependencyTreeFactory->findChildSegments(Object(Mautic\\LeadBundle\\Entity\\LeadList))
#2 /var/www/html/app/bundles/LeadBundle/Controller/AjaxController.php(987): Mautic\\LeadBundle\\Services\\SegmentDependencyTreeFactory->buildTree(Object(Mautic\\LeadBundle\\Entity\\LeadList))
#3 /var/www/html/app/bundles/CoreBundle/Controller/AjaxController.php(131): Mautic\\LeadBundle\\Controller\\AjaxController->getSegmentDependencyTreeAction(Object(Symfony\\Component\\HttpFoundation\\Request), 'lead')
#4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(158): Mautic\\CoreBundle\\Controller\\AjaxController->executeAjaxAction('getSegmentDepen...', Object(Symfony\\Component\\HttpFoundation\\Request), 'lead')
#5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#6 /var/www/html/vendor/symfony/framework-bundle/Controller/ControllerTrait.php(96): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#7 /var/www/html/app/bundles/CoreBundle/Controller/AjaxController.php(109): Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller->forward('MauticLeadBundl...', Array)
#8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(158): Mautic\\CoreBundle\\Controller\\AjaxController->delegateAjaxAction()
#9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#10 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 /var/www/html/app/AppKernel.php(104): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#16 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#18 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#19 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#20 {main}
"} {"hostname":"mautic-web","pid":2157}

```

Also double-checked locally to rule out Gitpod being the problem - same issue.

**Comment by escopecz** [comment]
@RCheesley great catch. I tested with fresh segments. The old ones have slightly different structure. I added support for the legacy segment structure.

**Comment by RCheesley** [comment]
I tested again doing some silly combinations to test the loop / duplicated segments but I am not seeing what I expect - maybe I am not fully getting what you want to test.

Here I have United States twice - once on its own and once with an AND join:

Edit Segment - Test 11276 _ Mautic (1)

I would have expected to see it twice per your screenshots but I am not:

Segments _ Test 11276 _ Mautic

I tried also adding it as another separate segment (not as part of an AND) but still had the same:
Edit Segment - Test 11276 _ Mautic (3)

 I am still only seeing it listed once:
Segments _ Test 11276 _ Mautic (1)

This is a brand new segment that I am testing with, in case that makes any difference.

**Comment by escopecz** [comment]
It is not checking duplicated filters in the same segment. That is easy to spot as it's in the same form. But it checks if you include or exclude the same segment somewhere in the segment dependency tree. Those are hard to spot because it's not visible on the same form/page.

So for example:
1. Create `Segment A`
2. Create `Segment B` that is including `Segment A`
3. Create `Segment C` that is including `Segment A`
4. Create `Segment D` that is including `Segment B` and `Segment C`

The dependency tree of `Segment D` should warn you that `Segment A` is included twice in the segment dependency tree.

**Comment by RCheesley** [comment]
Ahh got it - so if I include United States in one of the segments that I am including, for example! Thanks for the clarification, will look again!

**Review by RCheesley — APPROVED** [review]
The extra info helped me understand and I was able to successfully reproduce the expected behaviour.

Edit Segment - Segment Test 5 _ Mautic

I added the USA segment to this one, then created a new segment which included the USA segment and the existing one, which has the segment already in a filter. Warned me as expected! 🙌 

Segments _ Testing 11276 _ Mautic

Thanks @escopecz - a nice enhancement to assist and guide the marketer!

**Comment by RCheesley** [comment]
I have added an [issue](https://github.com/mautic/user-documentation/issues/86) so that when we get to the segments section in the docs project we make sure to add this feature as it is not currently in the documentation.

**Review by jos0405 — APPROVED** [review]
Working as expected, dependency tree shown properly.

image

Warning works for looping:

image

**Pull request merged**
