### PR TITLE
Maxmind license key

### PR DESCRIPTION
**Pull request by lukassykora**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | No
| New feature? | Yes, MaxMind requires license key
| Automated tests included? | Yes, they need license key in env variable in phpunit.xml.
| Related user documentation PR URL | No
| Related developer documentation PR URL | No
| Issues addressed (#s or URLs) | 
| BC breaks? | No
| Deprecations? | No

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )
The user can work with it in a standard way.

[//]: # ( Required: )
#### Description:
In back office a user can add license key

#### Steps to test this PR:
1. Try to download the file by MaxmindDownloadLookup->downloadRemoteDataStore()
2. The file should be unpacked and moved to MaxmindDownloadLookup->getLocalDataStoreFilepath()

### CODE REVIEW

**Comment by YosuCadilla** [comment]
Thank you very much @lukassykora for this PR, amazing work!.

Just as a possible alternative, please consider the pros and cons of removing this entirely from the UI and use the official MaxMind "geoipupdate" Application instead, so THEY are in charge of maintaining it and it will always be compatible if they decide to make any changes.
Automation via cron becomes a snap too!

If that's of any interest, please check this post with the step by step process:
https://mauteam.org/mautic/mautic-admins/solved-maxmind-geolite2-database-not-updating/

**Comment by escopecz** [comment]
> Just as a possible alternative, please consider the pros and cons of removing this entirely from the UI and use the official MaxMind "geoipupdate" Application instead

@YosuCadilla I checked your article. That would mean "geoipupdate" would be another dependency of Mautic. Do you find it to be a better solution than let Mautic manage the local IP lookup database? I mean Mautic is not able to install it during Mautic update process based on your article it needs sudo privileges:

Screenshot 2020-01-20 at 16 10 59

**Comment by YosuCadilla** [comment]
What I had in mind is:
Just like you need to install Apache2 and MySQL as well as some other 20+ packages, scripts and modules in order for Mautic to run, you now add one more and, instead of running:
apt install apache2 mysql-server etc...
You would now have to run:
apt install apache2 mysql-server geoipupdate etc...

Just like Apache updates are taken care of by the OS, geoipupdate would equally be updated automatically from the source (from the MaxMind repos), hence there would be no need for Mautic to be updating this software just like Mautic doesn't have to take care of Apache or Mysql Updates.

This way we have less code in Mautic and one less thing to worry about, since the package is maintained by the same company that could introduce changes to this process down the road.
While they might or might not care or be aware of how we have implemented compliance with their new requirements, I doubt they will break compatibility with their own script.

And finally, you also transfer the responsibility for its configuration to the System Administrator rather than the Mautic Administrator, which might or might not be a technical person (Like a head of MKTG or a CMO or in smaller companies the CTO or owner).

For those reasons, and perfectly understanding the advantages of having a GUI, I still believe this could be the best solution, unless there are new aspects of the issue I do not know about.

**Comment by YosuCadilla** [comment]
One last comment, goipupdate is compatible and tested with **many linux distros as well as Windows and Mac:**
https://github.com/maxmind/geoipupdate

**Comment by escopecz** [comment]
I see your point. The issues I see with that approach are:
1. It would be a BC break for Mautic 2. We could say it's one of the BC breaks for Mautic 3.
2. Mautic supports more vendors of IP databases than just Maxmind. That'd mean we'd have to handle each of the vendor differently.
3. If someone does not have permission to install new programs on the server then it would be a deal breaker for them.

The fix is done, so there is no reason for ways around it :)

**Comment by YosuCadilla** [comment]
2. I see how that might be a problem, but is anyone really using any other databases?
3. If someone doesn't have permission to install new programs on the server... they shouldn't be able to install Mautic anyway.

> The fix is done, so there is no reason for ways around it :)
The fix is not the best solution and shouldn't be used.
Unless you want to impose it... of course...

**Comment by escopecz** [comment]
I believe this is the proper solution to the problem. I learned from the past discussions between the two of us that it doesn't make sense to argue with you so I stop here. I said what I had on the topic and we'd run in circles from here. I let community to decide.

**Comment by YosuCadilla** [comment]
Agreed, and that's exactly the point. We have different views on how this particular issue should be solved.
I believe a proper process for solving these discussions should exist, in cases where a commonly agreed solution is not possible.

**Comment by dennisameling** [comment]
Hi, I'm the release lead for 2.16. First of all, thanks a lot @lukassykora for taking the time to create a PR. Also thanks @YosuCadilla for exploring alternative solutions. 

**End-user perspective**
The goal for 2.16 is to stay as close to 2.15's functionality as possible. Currently, Mautic supports 12 different IP lookup services, and treating Maxmind differently (e.g. by adding `geoipupdate` as a requirement) is a decision that needs to be more thoroughly discussed by the Product team and the community before changing directions. 2.16 should follow the regular update procedure through the GUI in order to make upgrading easy and smooth. Let's keep the discussion open in #8275 (or create a new issue); merging this PR won't close the issue to allow for discussion and consideration for future Mautic versions.

**Developer perspective**
Currently, merging commits into the `staging` branch results in [failed tests](https://travis-ci.org/mautic/mautic/builds/642417942?utm_source=github_status&utm_medium=notification) due to the MaxMind download not working anymore. This PR provides a fix for that (by ignoring MaxMind tests if no license key is set), and therefore it should be merged ASAP so that we can start merging other commits into the branch as well for the 2.16-beta release this Friday.

**Testing this PR**
In order to test this PR, do the following:
- Clone https://github.com/lukassykora/mautic/tree/maxmind-license-key
- Do a fresh install of Mautic (works OK). At this point, I haven't set a license key for Maxmind yet.
- Go to Configuration > System Settings > Miscellaneous Settings and click "Fetch IP Lookup Data Store". This throws an error: "Automatically fetching IP lookup data failed." as shown below, which is expected as I haven't set a license key yet.

Screenshot from 2020-01-27 17-53-42

- Open a terminal and run `php /path/to/mautic/app/console mautic:iplookup:download`. This returns the following error (also expected because no license key is set):

```
[UnexpectedValueException]                                                                                                                                
The stream or file "/var/www/html/mautic-maxmind-test/app/logs/mautic_prod-2020-01-27.php" could not be opened: failed to open stream: Permission denied
``` 

- Create a MaxMind account by going to https://www.maxmind.com/en/geolite2/signup
- After logging in, go to "My License Key" on the left hand side in the menu.
- Click "Generate new License Key". Answer "Will this key be used for GeoIP Update?" with No
- Copy the license key that you see on the screen. 
- Go to Mautic > Configuration > System Settings > Miscellaneous Settings and enter the license key into the "IP lookup service authentication" field.
- Click "Fetch IP Lookup Data Store" again. Download should work now (for me it worked).
- Try the terminal command above as well. Should also work now (worked in my tests).

Remarks (WIP):
- The console command should be changed in such a way that is shows a more user-friendly error, like "in order to use IP lookup download functionality, you need to enter Maxmind IP database credentials in Mautic".

**Comment by YosuCadilla** [comment]
Congrats on your new assignment @dennisameling 
Great job so far!
I agree with your exposition, still, we need a process...

**Pull request merged**
