### PR TITLE
Second Fixes #5532 problem with MailjetTransport header X-MJ-CUSTOMID

### LINKED ISSUE #5532: The "X-MJ-CUSTOMID" header is wrong when sending segment email.
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 🔴
| Feature request? | 
| Enhancement? | 

## Description:

Adding the 'X-MJ-CUSTOMID' header is available when sending the email in the Mailjet specific code into EmailBundle/Swiftmailer.
The header in message Swift_Mime_Message is not rewritten for the following messages because it is already present in the first message sent. But the "X-MJ-CUSTOMID" shall be unique
The solution is simply to delete the header before rewriting the correct header.

**To correct the problem** =
Add this "$message->getHeaders()->remove('X-MJ-CUSTOMID');" in line 65 in file Mautic\EmailBundle\Swiftmailer\Transport\MailjetTransport. (obviously before the line adding the correct X-MJ-CUSTOMID)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 5.6.30

### Steps to reproduce:
1. Create a segment
2. Add two leads at least in this segment
3. Create a manual email and set the precedent segment
4. Add log in Swift_Transport_AbstractSmtpTransport in the end of send function. Log this => $message->getHeaders()->get('X-MJ-CUSTOMID')->toString() before return.
5. Send this email
6. View the log. X-MJ-CUSTOMID is the same for the two differents emails. It's normally different because X-MJ-CUSTOMID is defined like this "leadIdHash-email".
 
### Log errors: 

First email headers = 
Message-ID: <f25dfe7ce718347c82e775477ac11748@mautic.localhost>
X-MJ-CUSTOMID: 5a534d0ab2e08-firstemail@gmail.com

Second email headers = 
Message-ID: <e284329bfe60c1fea2861f01799f0169@mautic.localhost>
X-MJ-CUSTOMID: 5a534d0ab2e08-firstemail@gmail.com

### PR DESCRIPTION
**Pull request by XRaccourci**
| Q  | A
| --- | ---
| Bug fix? |  #5534 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #5532 
| BC breaks? | 
| Deprecations? | 

#### Description:
Fixes issue #5532 and add another fix to PR #5534.
Delete ALL header 'X-MJ-CUSTOMID' before rewriting the correct header in MailjetTransport.
I have made a mistake in my precedent pull request. (#5534). I thought header value is only one value but it can be an array of value... Because that, to fix the bug with this header for Mailjet, I remove all headers 'X-MJ-CUSTOMID'.

#### Steps to reproduce the bug:
1. Create a segment
2. Add three leads at least in this segment
3. Create a manual email and set the precedent segment
4. Add log in Swift_Transport_AbstractSmtpTransport in the end of send function. Log this => $message->getHeaders()->get('X-MJ-CUSTOMID')->toString() before return.
5. Send this email
6. View the log. X-MJ-CUSTOMID is the same for the two end differents emails. It's normally different because X-MJ-CUSTOMID is defined like this "leadIdHash-email". After fixes, the header is correct.

#### Steps to test this PR:
1. Apply PR
2. Repeat Steps 1-6 above
3. Notice value is correct

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by XRaccourci** [comment]
Label: bug

**Comment by XRaccourci** [comment]
Label: Ready to test

**Comment by kuzmany** [comment]
Label: bug

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by Dcoutelle** [comment]
tested and it's OK

**Review by npracht — APPROVED** [review]
Tested with @Dcoutelle, this is working properly.

**Comment by npracht** [comment]
Label: Pending test confirmation

**Comment by escopecz** [comment]
Resolve the conflict please.

**Comment by XRaccourci** [comment]
@escopecz It's OK. Conflict is resolved.

**Review by alanhartless — APPROVED** [review]

**Pull request merged**
