### PR TITLE
Code Mode

### PR DESCRIPTION
**Pull request by escopecz**
# Caution: Work in progress

| Q | A |
| --- | --- |
| Bug fix? | N |
| New feature? | Y |
| Related user documentation PR URL | TODO |
| Related developer documentation PR URL | / |
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/2370, https://github.com/mautic/mautic/issues/2368, https://github.com/mautic/mautic/issues/2737 |
| BC breaks? | N |
| Deprecations? | N |
#### Description:

There has been many emotional discussions about Froala editor modifying the code. This PR creates the "Code Mode" for each email/page and removes the Content Tab. All content modifications can be done only via the Builder. If a theme is selected, the builder looks the same as before. However, if the Code Mode is selected, the builder looks like this:
mautic-code-mode-builder
The preview will refresh automatically every 10 seconds if there was a change in the code.
##### The workflows can go like this:
1. If user wants to create an email/page and use his own HTML, he goes directly to the Code Mode, paste the HTML in the Builder's code editor and save.
2. If user wants to use a theme, he select a theme and can edit the content in the Builder.
3. If user wants to edit HTML of an email/page created by a theme, he can switch to the Code Mode, but NOT BACK.
4. The same works for BC. If user wants to convert email/page created before the Code Mode was available, he can switch to Code Mode now with old emails/pages, but NOT BACK.
##### Known issues:
1. The features built into Froala won't be easily available in the Code editor (video, shortcode btn, shortcode dropdown when `{` is pressed, Dynamic email content button, images...)
2. Video and dynamic email content is not built into the Builder editors either.
#### Steps to test this PR:
1. Try to create an email with Code Mode with custom HTML. Check the email preview.
2. Try to create an email from a predefined theme, edit in Builder, save. Check the email preview.
3. Try to switch the email created from 2. to the Code Mode, edit the code, save. Check the email preview.
4. Edit all steps above with pages as well.

### CODE REVIEW

**Comment by abooster** [comment]
There was nothing "emotional" about those discussions at the beginning. 
Just people/users who don't want the Froala crap to mess with their code. 
It only started getting "emotional" after Mautic developers stubbornly kept ignoring user feedback.

**Comment by dongilbert** [comment]
@abooster - This is not a forum for generic chat or comments. It is for code discussion and +1's or -1's when testing. Let's work towards keeping it that way. Thanks.

@escopecz The initial testing I did on this during the 2.2.1 release cycle went really well. I did notice though that sometimes, on older emails, the HTML structure was lost when opening code-mode for editing; everything was inlined HTML on a single line. If we do end up going with this, we'll need to make sure that issue is addressed, probably through js to auto-indent the HTML.

**Comment by mm-manageit** [comment]
This is a good "short" term solution. But, lets be honest, Froala is terrible no matter what your experience level is. I believe and would guess that many would agree that the better path to take is replacing Froala all together with an editor that is truly compliant. This is PR is just a shortcut around the problem, that will lead to only more requests, i.e... why does dynamic not work in emails I have coded myself, etc....

**Comment by Tony-Gavin** [comment]
Froala is a giant pain and it needs to go entirely, or at the very last there needs to be a way for developers to disable Froala entirely, at the click of a button. 

I appreciate that the developer community is trying very hard the make Mautic as user-friendly as possible for non-technical users. Right now, Froala is stifling those who are technical and/or creative enough to turn Mautic into a much more effective tool for everyone.

**Comment by Elenchus** [comment]
I second Tony's post - it'd be good to be able to bypass it easily.

**Comment by mm-manageit** [comment]
@alanhartless/@escopecz Could you please comment on why the dev team is so stuck on keeping Froala? So much that you would spend all this extra time making workarounds that by now could have just replaced it?

**Comment by escopecz** [comment]
@mm-manageit there was the same discussion at Slack chat a couple of hours ago: https://mautic.slack.com/archives/general/p1477646218002459

**Comment by Tony-Gavin** [comment]
Thanks @escopecz for linking that thread on Slack. It provided a great deal of insight into why the dev community is so reluctant to trash Froala completely. I can now appreciate what a difficult job that is and how much it impacts core functionality, beyond editing.

**Comment by Dcoutelle** [comment]
Did few tests with web and mobile email content, it's very nice!

**Comment by alanhartless** [comment]
Welp - that wasn't expected. Sorry John. Seeing if I can clean that up.

**Comment by alanhartless** [comment]
@escopecz I think I found a snafu in Github's feature to guest commit. For whatever reason, it's showing all the commits already in staging. https://github.com/mautic/mautic/compare/staging...escopecz:code-mode?expand=1 Show's the correct differences. We may have to re-create this PR just to clean it up.

**Comment by escopecz** [comment]
This PR was replaced with https://github.com/mautic/mautic/pull/2988

**Comment by mmmichael** [comment]
can you estimate the release date of 2.3

**Pull request closed without merging**
