### PR TITLE
Opens email campaign decision

### LINKED ISSUE #416: Campaign opens email decision doesn't seem to work if the email is manually selected
I have setup Mautic and have successfully implemented a campaign that sent out one email message to a lead when the lead was added to a lead list. I then created a second campaign and using the campaign builder and did the following: 1. send email 2. open email wait 2 min. 3. send follow up email. The first action (1. send email ) worked correctly, the second decision (open email wait 2 min.l) did not and the third action send follow up email also did not work. This is confirmed when view the campaign page. It shows the Actions 1. send email  50%, 3. send follow up email 0%, Decisions 0%.  It may be important to note that after the email is sent when i view the email stats in (email manager) it only shows the graph for the Total, there is no graph for Email sent or Email read however it does show on the main page of the email manager 1 as the # Sent  but again does not show #read. Also when the email is received in my email client it is clicked and read.

### PR DESCRIPTION
**Pull request by alanhartless**
**Description** 

Campaign open email decisions gave the option to select the email or connect into a send email action.  The email immature field made it confusing and was broken. So this PR removes the option to select an email from the list and relies on just connecting into a Send Email action which makes more sense.  Fixes #416

**Testing**
After applying the PR, the email dropdown should not be available in the opens email decision.  The description, used also for instructions, now shows text-muted under the header. Try a basic campaign of send email then opens email.  Ensure the campaign honors the email open.

### CODE REVIEW

**Comment by escopecz** [comment]
I can confirm the drop down is gone after this PR is applied. How should I ensure this: "Ensure the campaign honors the email open"?

@alanhartless It means that a campaign cannot start with Opens email decision. Send email action has to be configured and linked before the Opens email decision. Is that OK?

**Comment by drmmr763** [comment]
So in testing this I hit this error when executing on the CLI:

```
[Symfony\Component\Debug\Exception\ContextErrorException]                                                            Notice: Undefined index: name in /var/www/mautic-gh-staging/app/bundles/LeadBundle/Helper/CampaignEventHelper.php line 71 
```

Here's what I did:
- Created campaign with send email action
- added an 'opened' email point update + 50 points
- added a 'no open after 3 minutes' point update -50 points

Ran CLI:
`php app/console mautic:campaigns:update`

Which added all the leads properly. Then executed the trigger:
`php app/console mautic:campaigns:trigger`

Which sent all the emails. I opened a few mails, and left one un-opened. After a few minutes re-did the trigger:

`php app/console mautic:campaigns:trigger`

Which then caused that error to come up.

**Comment by alanhartless** [comment]
@drmmr763 That error is not related to this PR.  But I found the issue.  Another PR coming.

@escopecz Good point; although, wondering if there is really a use case to start a campaign with an opens email decision?  Thinking if the email is going to be part of the campaign, it should be sent by the campaign. Especially in light of changes being made right now where we are differentiating standalone forms vs forms that put a lead into a campaign and also standalone emails (sent to lead lists) vs templates (can be sent by campaigns, forms, etc).

**Comment by alanhartless** [comment]
@drmmr763 see pr #464 regarding your error

**Comment by drmmr763** [comment]
+ Test okay worked this time! No errors.
+ vote +1

**Comment by dbhurley** [comment]
+1

**Pull request merged**
