### PR TITLE
[UX] Better description for existing dashboard templates

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR ensures that all default dashboard templates come with a description following this structure:
- How many widgets we have in it
- What is this template about

Example:
"Start with a dashboard of 6 reports that show the kind of requests your team receives over email."

| Before                                 | After
| -------------------------------------- | ---
|  image                                      | image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open the Dashboard, click on the page actions and enter to see the pre-defined dahboards.
3. Read each description.

### CODE REVIEW

**Review by LordRembo — COMMENTED** [review]
The 1 question/remark I have (because I know very little about the dashboards): can it be avoided to use fixed numbers in those descriptions? '13 widgets', '5 widgets', …
I understand that there are probably a fixed number of widgets in those specific dashboards but it's the kinda stuff devs will forget to update if widgets are added/removed in future releases.

**Comment by andersonjeccel** [comment]
@LordRembo that would provide less information to the user... I can create guidelines in the dev docs, but it's up to each dev to keep updated

_(perhaps let's be realistic: how many years will take until someone decides to add 1 more widget to the template and what's the probability of forgetting to change the number when doing so without anyone (of 2 needed approvals) remembering the PR author that it also needs to be changed when having numbers become a standard over the years? really high, but let's pretend it's 0)_

**Review by Esthertests — APPROVED** [review]
LGTM 
image
BEFORE
image

**Review by kuzmany — APPROVED** [review]
👍

**Comment by andersonjeccel** [comment]
> [!NOTE]
> Failing test is not related to the PR

**Pull request merged**
