### PR TITLE
Add workflow to verify E2E tests with multiple iterations

### PR DESCRIPTION
**Pull request by matbcvo**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🟢 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR adds a GitHub Actions workflow to verify the consistency and reliability of end-to-end (E2E) tests by running them 10 times consecutively. The workflow triggers on changes to the `tests/` folder or manually via `workflow_dispatch`.

Trigger Conditions:
- Runs on pushes to branches matching the pattern `[0-9].*` with changes in the `tests/` folder.
- Runs on pull requests modifying files in the `tests/` folder.
- Can also be triggered manually via `workflow_dispatch`.

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
Looks legit. Thanks! Let's test it out with https://github.com/mautic/mautic/pull/14309

**Comment by RCheesley** [comment]
@escopecz there is no 5.3 release. This will need to be made on the 5.2 branch for the patch releases, or over to 6.x for the alpha.

**Comment by escopecz** [comment]
Oh. Either way it needs a rebase either to the 5.2 branch for 5.2.1 or 6.x branch for 6.x, right? So I should revert this PR.

**Comment by matbcvo** [comment]
This workflow file needs to be added to the default branch (currently `5.x`) and other branches like `6.x` so it can run on PRs targeting these branches.

https://github.com/mautic/mautic/tree/5.x/.github/workflows
https://github.com/mautic/mautic/tree/6.x/.github/workflows

**Comment by escopecz** [comment]
Revert PR created https://github.com/mautic/mautic/pull/14317

**Pull request merged**
