### PR TITLE
Error 500 when contact have a bounce email.

### LINKED ISSUE #13530: Got error 500 when try to view contact, which has wrong email address based on bounce from mail server
### Mautic Version

5.0.x series

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.1.27

### What browsers are you seeing the problem on?

Not relevant

### What happened?

return error 500 when try to view contact, which has wrong email, which was detected based on bounce

### How can we reproduce this issue?

1. Configure and set Custom return path (bounce) address and Monitored Inbox Settings
2. Add to list contact with wrong email (non exist). Wait a while until server respond there was a wrong email.
3. Run  mautic:email:fetch
4. Go to dashboard and contacts and try to view this wrong email

### Relevant log output

```shell
Mautic log: mautic.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Key "datetime" for array with keys "0" does not exist." at /home/szczescie/mautic_szczescie/docroot/app/bundles/EmailBundle/Resources/views/SubscribedEvents/Timeline/index.html.twig line 49 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Key \"datetime\" for array with keys \"0\" does not exist. at /home/szczescie/mautic_szczescie/docroot/app/bundles/EmailBundle/Resources/views/SubscribedEvents/Timeline/index.html.twig:49)"} {"hostname":"server.webdragon.pl","pid":9649}

Probably there is relevant:
In database in email_stats for this "wrong" email in column open_details there is:
a:1:{s:7:"bounces";a:1:{i:0;a:4:{s:8:"datetime";s:19:"2024-03-08 09:56:04";s:6:"reason";s:7:"unknown";s:4:"code";s:4:"0123";s:4:"type";s:4:"hard";}}}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by lenonleite**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #13530

#### Description:
Error 500 when contact have a bounce email.
app/bundles/EmailBundle/Resources/views/SubscribedEvents/Timeline/index.html.twig in line 43

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Review by magician7 — APPROVED** [review]
it works

**Comment by RCheesley** [comment]
@all-contributors please add @magician7 for review

**Review by kuzmany — APPROVED** [review]
👍

**Review by kuzmany — APPROVED** [review]
Yes, the key should be bounces. Good catch 👍

**Pull request merged**
