### PR TITLE
Role export access in Leads, Forms, Reports 

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Yes
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Added new permission for export in form results. This PR not require migrations, exports are default enable. This permission give ability disable export permission for Contacts, Forms, Reports.

image

#### Steps to test this PR:
1.  Create new user with role and enable all permission for Contacts, Forms, Reports with unchecked new Export access: Disable 
2.  Login as new user and see If exports buttons exists and exports works properly in all sections: Contacts (batch export), Form (results exports) and Reports
3. Open HTML exports of Form results and Reports.
4. Edit in incognito user permission and disable export 
5. See If export button are hidden in Form results and  Reports and Contacts lists in batch.
6. See If opened HTML export from 3. return access denied after refresh

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/5995"></a>

### CODE REVIEW

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by kuzmany** [comment]
Label: WIP

**Review by npracht — DISMISSED** [review]
Working from a user perspective ! Bravo !

**Comment by npracht** [comment]
Label: Pending test confirmation

**Comment by npracht** [comment]
@kuzmany please solve conflicts ;)

**Comment by cykonetic** [comment]
:+1:

**Comment by RCheesley** [comment]
@kuzmany can you take a look at Travis please?

**Comment by RCheesley** [comment]
Bumping to 3.2 due to unresolved Travis failure

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@kuzmany looks like we need @cykonetic to sign the Contributors Agreement - can you reach out to them?

**Review by RCheesley — DISMISSED** [review]
Thanks for this great PR @kuzmany !

Tested as per instructions and confirm that with the option unchecked I am still able to download as I would expect.

Enabling the option to prevent export hides the export features everywhere, and also throws a 403 forbidden on the results screen:

screenshot-local mautic3-2020 11 21-13_11_40
screenshot-local mautic3-2020 11 21-13_12_46
screenshot-local mautic3-2020 11 21-13_12_46 (1)

Thank you for the detailed testing instructions, it really helped!

**Comment by RCheesley** [comment]
@kuzmany looks like we have a code style fix required based on the GH Actions tests - can you take a look? Seems this would be great to finally get merged!

**Comment by RCheesley** [comment]
Added documentation pages for users and roles which were missing, and made a PR to add this information when the feature is merged.

**Comment by RCheesley** [comment]
@kuzmany looks like three of these files need to improve test coverage before we can consider it for merging :(

**Comment by escopecz** [comment]
I would like to point out like I did in other 2 PRs that are hiding existing features behind new permissions that it is a BC break. The export feature will be suddenly hidden for non-admin users once Mautic is upgraded to 3.2.

**Review by RCheesley — DISMISSED** [review]
Adding back the dismissed review due to rebase

**Comment by RCheesley** [comment]
> The export feature will be suddenly hidden for non-admin users once Mautic is upgraded to 3.2.

Thanks for flagging that @escopecz much appreciated. 

My understanding of this having tested it is that the new feature being added allows you to select in order to prevent downloading. 

So existing roles should still be able to download as they could before because this field has not been selected, but you can now select this checkbox in the role to prevent exporting.

Could you explain how this would hide a feature for non-admin users? In my testing I could still download/export once I had applied the PR with my existing accounts.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by escopecz** [comment]
I see. I missed that the checkbox is opposite to the rest of the checkboxes. You have to check the export checkbox to disable the export. Is it the user experience we want? That all checkboxes enable a feature if checked but there is one (or 3) that disable a feature when checked?

If we're OK with this UX then yes, BC is not broken.

@kuzmany I'm missing any tests here. I'd create a functional test where you create a user without the permissions and check that the buttons are there when you load the pages with the export buttons. And that the user won't get 403 when accessing the export URLs. Then another test with a user that has the permissions and check that the buttons are missing and 403s are thrown.

**Comment by kuzmany** [comment]
@escopecz by default are checkbox unchecked and export is available for all like before. After PR you are able to disable export for some roles  If you need. I don't see any BC. We use it in production

Do we have already some examples of unit tests for these cases?

**Comment by escopecz** [comment]
There are many functional test examples: 

https://github.com/mautic/mautic/search?q=%22extends+MauticMysqlTestCase%22

However I must admit that testing roles like this is challenging as the permissions are loaded on kernel boot and updating roles in the database won't get populated. @fedys if I remember you had some way around. Do you remember how it was done?

**Comment by fedys** [comment]
@escopecz We used this approach(ugly):
```php
protected function setPermission(User $user, string $permission, array $permissionArray): void
{
    $role        = $user->getRole();
    $permissions = [
        $permission => $permissionArray,
    ];

    // delete previous permissions
    $this->em->createQueryBuilder()
        ->delete(Permission::class, 'p')
        ->where('p.bundle = :bundle')
        ->setParameter('bundle', reset(explode(':', $permission)))
        ->getQuery()
        ->execute();

    $roleModel = $this->container->get('mautic.user.model.role');
    $roleModel->setRolePermissions($role, $permissions);
    $this->em->persist($role);
    $this->em->flush();

    // reset in-memory permission cache
    $property = (new ReflectionClass(CorePermissions::class))->getProperty('grantedPermissions');
    $property->setAccessible(true);
    $property->setValue($this->container->get('mautic.security'), []);
}
```

Then we called the method like this: `$this->setPermission($user, 'some_bundle:something', ['viewown', 'viewother', 'editown']);`

The key part was `// reset in-memory permission cache`.

**Comment by RCheesley** [comment]
Still has outstanding test coverage issues, I am willing to bump this one more feature release to Mautic 4 and if we have not merged it by then we will close the PR.

**Comment by dsp76** [comment]
I tested this PR in Gitpod as described. Worked as expected. Only one comment - exporting a single contact is still possible.

**Comment by RCheesley** [comment]
PHPSTAN issues needing to be addressed here @escopecz - and still need to bump the coverage. Any chance @fedys or @dongilbert  might be able to help with that?

**Comment by escopecz** [comment]
I think the new checkbox should say "Export access: enable" instead of "Export access: disable". I understand it is done because the "enable" option would require a migration or wait for Mautic 5 that allows for some small BC change, but I suggest to do it right instead of do it easy.

**Comment by kuzmany** [comment]
@escopecz It would be nice suggest it once If it's actual, not 3 years after.  It's really getting frustrating to contribute to the community

**Comment by escopecz** [comment]
@kuzmany I know and I also suffer from the lack of testers. I commented with the same a year ago but that is still a couple years late. I have a plan how to improve this in the future and spend more time here. 🤞

**Comment by medsun88** [comment]
#7645  #6180  #7246

OMG, Since 2018 we are discussing this feature ( to restrict user from export) 
Still not sure when It will be introduced . 

I have more than, 25000 Contact in Mautic, and any of my user can easily can export them. 
Such a big loophole, and so much discussion. 

Guys, this is a Very Import Feature. When it will come ?

@kuzmany @escopecz @RCheesley 
Do you have some suggestion to fix this.

**Comment by kuzmany** [comment]
@medsun88 as you see this is PR and you can use it.

It come to stable version once when it will be approve by team/community/volunteers, finish unit tests, resolve CI checks etc etc.

**Comment by RCheesley** [comment]
@kuzmany needs some PHPSTAN attention here & the additional test coverage - would be really nice if we can aim to get this into Mautic 5 if it's BC as @escopecz suggests. I am inclined to agree that checking something should be in the affirmative, so if this means it needs to be held to 5.x that is what we should do.

Really appreciate that this is a really old PR and a pain to have to come back to after so long!

**Comment by kuzmany** [comment]
@RCheesley we build PR without BC. The suggestions from @escopecz  will make BC. 
In that case this change need a lot of hours of works, because we already use it in production and the changes make difficult to us. At the moment we are able support just this version of PR. Will see

**Comment by medsun88** [comment]
Hi @kuzmany @RCheesley 

getting error while clearing cache 
-----------------------------------------

In RegisterListenersPass.php line 111:

  Class "Mautic\LeadBundle\EventListener\SegmentFiltersSubscriber" used for service "mautic.lead.subscriber.
  segment.filter" cannot be found.

Check screenshot 
https://prnt.sc/CJP17PZobVnt

**Comment by xcellenceit** [comment]
Reviewers, pls look into this for release. Its been long for such a critical feature.

**Comment by escopecz** [comment]
@xcellenceit it's not waiting for reviewers but for the rebase and addressing the reported issue

**Comment by adiux** [comment]
I understand everybody wants this features as soon as possible (me included) as it is critical. However, from a UX standpoint, I strongly agree with @escopecz. We should not change the logic of the checkboxes: 
> "Export access: enable" instead of "Export access: disable".

It can be a BC Break with v5 now. So we don't need to do a migration. I assume the admin role will get the permission anyway.

**Comment by medsun88** [comment]
@kuzmany, @escopecz

> I understand everybody wants this features as soon as possible (me included) as it is critical. However, from a UX standpoint, I strongly agree with @escopecz. We should not change the logic of the checkboxes:
> 
> > "Export access: enable" instead of "Export access: disable".
> 
> It can be a BC Break with v5 now. So we don't need to do a migration. I assume the admin role will get the permission anyway.

@kuzmany, @escopecz
Any update, When it can be released 
it has been pending for a long time.

**Comment by kuzmany** [comment]
We will upgrade the code to 5.x, but we will keep it like this just for the community.  Anybody can pick it up. 
The reported suggestions could take a lot of hours (including migration for current customers), which is not possible at the moment.

**Comment by kuzmany** [comment]
Close favor to M5 version https://github.com/mautic/mautic/pull/12884

**Comment by kuzmany** [comment]
All guys please test updated version for M5 https://github.com/mautic/mautic/pull/12884 (unit tests added later)

**Comment by medsun88** [comment]
I am using Mautic v4.4.12
In which version will it be introduced? It long-awaited feature.

**Pull request closed without merging**
