### PR TITLE
Fix tags HTML-escaping

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/6057
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This fix is based on issues https://github.com/mautic/mautic/issues/6057 
This PR fix HTML-escaping for tags 

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a tag with the tracking script with a special character  and refresh page

    `mt('send', 'pageview', { tags: ['-test"eee', 'test"fff' ]});`

2. Too much  rows gets created in the database in lead_tags table

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat all steps 
3. Should now work properly

### CODE REVIEW

**Review by florentpetitjean — COMMENTED** [review]
Tags do not duplicate, but I can't see the first tag in my test instance  > '-test"eee' . (tags use in your test process)

**Comment by kuzmany** [comment]
@florentpetitjean that symbol `-` mean remove tags. Then you can create it and with `-` remove it.

**Comment by florentpetitjean** [comment]
Oh ok didn't know that, thanks.
So it works well !

**Review by florentpetitjean — DISMISSED** [review]
Working as intended in test.

**Review by florentpetitjean — DISMISSED** [review]

**Review by dennisameling — APPROVED** [review]
Code looks good and since @florentpetitjean tested already, I'm going ahead and will approve + merge this PR. Thanks @kuzmany :)

**Comment by kuzmany** [comment]
@dennisameling I would like rewrite this PR much much lighter. Could I get it to deadline?

**Comment by Dylan-86** [comment]
Can someone fix and deploy this?! It's a bug that is 4 years old at least.

**Comment by npracht** [comment]
Hello @Dylan-86, this was merged in 2.16.1. If you still see an issue, please create a new issue to report the bug and explain clearly how to reproduce :)

**Pull request merged**
