### PR TITLE
Remove depecrated cookies

### PR DESCRIPTION
**Pull request by putzwasser**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [x]
| BC breaks? (use the c.x branch)        | [x]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR removes the deprecated cookies `mtc_sid`. It is deprecated for at least two years because the [documentation](https://docs.mautic.org/en/contacts/manage-contacts/contact-monitoring) about it was last updated was two years ago with commit [5b45329](https://github.com/mautic/mautic-documentation/commit/5b45329925c2377e260e27d7ab35386b1d2279fa). (see https://github.com/mautic/mautic-documentation/blob/main/pages/12.contacts/01.manage-contacts/02.contact-monitoring/docs.en.md )

Removing it simplifies/improves ePrivacy compliance by removing unnecessary cookies.

### CODE REVIEW

**Review by escopecz — COMMENTED** [review]
This is correct. We are only writing that cookie, deleting it but never reading its value. Since this is a breaking backward compatibility change, it's good to merge it in before the Mautic 5.0.0 release. Please document this change in https://github.com/mautic/mautic/blob/5.x/UPGRADE-5.0.md and then this is good to go.

**Comment by putzwasser** [comment]
> Please document this change in https://github.com/mautic/mautic/blob/5.x/UPGRADE-5.0.md 

Done

**Review by escopecz — APPROVED** [review]
Looks good to me 👍

**Review by mabumusa1 — APPROVED** [review]
Good to go

**Pull request merged**
