### PR TITLE
Typo fix in the EN translation

### PR DESCRIPTION
**Pull request by escopecz**
The renamed variable is the rest of my previous PR and it wasn't added for some reason.

### CODE REVIEW

**Comment by drmmr763** [comment]
Any particular test instructions for this?

**Comment by escopecz** [comment]
Cannot remember what problem were we solving with Alan by this code. @alanhartless do you?

**Comment by dbhurley** [comment]
@escopecz can you update to latest?

**Comment by dbhurley** [comment]
Nevermind, again, I think a problem with the tests not the code.

**Comment by drmmr763** [comment]
+ Vote +1
+ Test I tested by creating a campaign event and firing it. No errors so I think this should be good to go.

**Comment by dbhurley** [comment]
+1

**Pull request merged**
