### PR TITLE
MB string functions

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [Y]
| New feature/enhancement? (use the a.x branch)      | [Y]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

We've had several bugs caused by not using PHP's mb_ string functions that can work with multibyte characters. We usually also write tests in English so that won't discover it either. [CS fixer has a handy rule](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/doc/rules/alias/mb_str_functions.rst) that will take care it for us.

The automatic changes made by the CS Fixer let to some PHPSTAN errors. I had to make quite a lot of changes to make them pass. Some of them may be considered BC breaks. So I'll plan this PR for Mautic 5.

ToDo:
- [ ] Rebase on top of 5.x
- [ ] Write the BC change notes

#### Steps to test this PR:

1. There is no change in functionality. The many changes in the .php files are done automatically by the CS Fixer. Then I had to made another bunch or changes to make the PHPSTAN pass.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11133"></a>

### CODE REVIEW

**Review by mabumusa1 — DISMISSED** [review]
I reviewed the code change, it is a new rule to php-cs-fixer and phpfixer changed the functions to use mb string. I think this PR is good to go

**Comment by escopecz** [comment]
Thanks @mabumusa1! I added more notes to the description. This still needs some work.

**Comment by jos0405** [comment]
@escopecz Do you need one more coder review to commit this or it's good to go?

**Comment by escopecz** [comment]
It has changes that can be considered breaking backwards compatibility so I want to rebase on 5.x and write about it in the changelog. Just have to get to it. So not ready for review yet.

**Comment by escopecz** [comment]
This is a nightmare to rebase. I give up.

**Pull request closed without merging**
