### PR TITLE
[DPMMA-716] Add new condition DNC to campaigns

### PR DESCRIPTION
**Pull request by tomekkowalczyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ N ]
| New feature/enhancement? (use the a.x branch)      | [ Y ]
| Deprecations?                          | [ N ]
| BC breaks? (use the c.x branch)        | [ N ]
| Automated tests included?              | [ Y ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

The functionality allows you to handle contacts from the level of the campaign condition that do not have or have the DNC flag and appropriate DNC channels, eg Emails.

image

image

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for rebasing the PR @tomekkowalczyk - looked like there was a PHPSTAN issue for PHP 8 to address, have just merged in the updates from the 5.x branch.

**Comment by tomekkowalczyk** [comment]
@RCheesley ok, thanks, I corrected files.

**Review by escopecz — CHANGES_REQUESTED** [review]
I would remove the "Has flag DNC" switch from the condition form and called this new condition "Has Do Not Contact flag". The Yes or No part is then done by the following events connected to either green or red dots of the condition. Otherwise it's very confusing when it comes to double negatives. Like "Is not do not contact". My brain has a hard time following this and this condition allows to configure such construct.

It will simplify the code too.

One field that can be added is the DNC reason:
- Unsubscribed
- Bounced
- Manual

As I can see it could be useful for marketers to target only specific reason of the DNC flag. In that case I'd suggest to create a new condition for each channel.

Also, it is unknown whether if I select the channels "email" and "sms" and one is unsubscribed, will it go the positive or negative path?

**Comment by tomekkowalczyk** [comment]
@escopecz 
According to the previous instructions https://github.com/mautic/mautic/pull/9723, the descriptions have been changed to

image
I understand that we now replace it with "Has Do Not Contact flag"?

Let's also add the DNC reason field, yes?

**Comment by escopecz** [comment]
I wanted to say that the "Marked as DNC" switch in the condition should be removed. Users will use the condition green and red connections instead of this switch. Like this:
Screenshot 2023-04-28 at 10 02 32
The switch will only complicate things. Does it make sense?

**Comment by tomekkowalczyk** [comment]
@escopecz Ok, I'll make a fix soon

**Comment by tomekkowalczyk** [comment]
@annamunk  could you verify the changes

@escopecz I corrected condtion 
image

**Review by escopecz — DISMISSED** [review]
Thanks! That's it. I see no other issues in the code. 👍 

_It would be perfect if you'd have a test that is accessing and submitting the campaign condition form. But since it's increasing the coverage already I'm not insisting on it._

**Review by annamunk — DISMISSED** [review]
tested with several contacts marked as DNC (email channel). The new campaign condition correctly separated contacts into two groups according to the DNC flag.

**Comment by tomekkowalczyk** [comment]
@escopecz Can we merge the changes?

**Comment by escopecz** [comment]
@tomekkowalczyk it looks like some other PR got merged that modified the same code. Please resolve the conflicts.

**Comment by tomekkowalczyk** [comment]
@escopecz I resolved the conflicts.

**Review by escopecz — APPROVED** [review]
Thanks! 👍

**Pull request merged**
