### PR TITLE
Fixed problem with pound sign not showing on lead card borders.

### PR DESCRIPTION
**Pull request by dbhurley**

### CODE REVIEW

**Comment by escopecz** [comment]
@dbhurley is it suppose to be pound sign (as described) or hash sign (in the code)?

**Comment by drmmr763** [comment]
@escopecz The '#' is also known as the 'pound' sign in United States. This isn't 'pound' like currency. 

http://en.wikipedia.org/wiki/Number_sign

**Comment by drmmr763** [comment]
This PR must be outdated or have a conflict - can't be automatically merged. @dbhurley can you update?

**Comment by dbhurley** [comment]
@drmmr763 Updated.

**Comment by drmmr763** [comment]
@dbhurley So after merging this I have two hashtags instead of one. What caused you to have this issue? If we are saving the color in the Db it might have been a change somewhere where in one case we saved with the hash, and another case where it saved without. 

@alanhartless any ideas here?

**Comment by alanhartless** [comment]
@drmmr763 Is your double coming from https://github.com/dbhurley/mautic/blob/MAU-226/app/bundles/LeadBundle/Views/Lead/grid_cards.html.php#L14?

@dbhurley Can you remove the pound sign from the default color

**Comment by dbhurley** [comment]
So the default is an empty color hex which is relying on the CSS default to display a black...not ideal. Even the default should be a hex code needing the hash sign.

**Comment by alanhartless** [comment]
Not sure I'm following.  The default is set at https://github.com/dbhurley/mautic/blob/MAU-226/app/bundles/LeadBundle/Views/Lead/grid_cards.html.php#L14

```
if (empty($color)) $color = '#a0acb8';
```

Which leads to a double # because of 
```
style="border-top: 3px solid #<?php echo $color; ?>;"
```

I think we need to change line 14 to so that it won't result in ##a0acb8
```
if (empty($color)) $color = 'a0acb8';
```
Where are you seeing the black?

I do see another related issue with the live lead injection for the card view.

https://github.com/dbhurley/mautic/blob/MAU-226/app/bundles/LeadBundle/Views/Lead/grid_cards.html.php#L17

Need to change line 17
```
<div data-color="<?php echo $color; ?>"
```
to 
```
<div data-color="#<?php echo $color; ?>"
```
Because the JS is restoring the color is not adding the #.
```
mQuery(that).css('border-top-color', mQuery(that).data('color'));
```

**Comment by dbhurley** [comment]
Ok, updated

**Comment by drmmr763** [comment]
+ test works great
+ vote +1

**Pull request merged**
