### PR TITLE
Do not track Bots support

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | n
| New feature? | y
| Related user documentation PR URL | n
| Related developer documentation PR URL | n
| Issues addressed (#s or URLs) | n
| BC breaks? | n
| Deprecations? | n

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR added support for do not track list of bots. 
Bots list is from https://github.com/Thomas--F/BotTracker/blob/a7a2dcb1a510a958b58ff2a2028faf84027b5637/API.php#L120

#### Steps to test this PR:
1. Add tracking code to page
2. Verify from table ip_addresses if bot wasn't created as profile with history
For example google bot has ip details Mountain View, California.....
 Also you can check if IP is bot here http://bot.myip.ms/

bots

### CODE REVIEW

**Comment by merlin0** [comment]
Great feature!

**Comment by escopecz** [comment]
I applied this PR, cleared cache. The new configuration appears in the configuration. I saved it to be sure the values are applied. I made a HTTP GET request with these headers:
```
GET /index_dev.php/oxygen-test HTTP/1.1
User-Agent: bingbot
Cookie: 9743595cf0a472cb3ec0272949ffe7e8=oqfn93g726o29qvqiret5rc3a7; mautic_session_name=9743595cf0a472cb3ec0272949ffe7e8; mautic_session_id=a1523691511b68df1148cc391ec67c3f8dcb0be0; a1523691511b68df1148cc391ec67c3f8dcb0be0=4166; mautic_referer_id=374
Host: mautic.dev
Connection: close
```
But the contact was created or updated and the page hit associated with it. What am I doing wrong?

Another question is if this PR doesn't break BC. I remember some communication with Mautic users that they value the information about bots. If they see Mountain View event in the contact logs, they know that the contact uses GMail. So I can imagine that if we suddenly add this pre-filled configuration, some users will be angry with us.

**Comment by kuzmany** [comment]
I am going to test it again.
No there is no issue with break BC compatibility. PR just blocks hits from bots crawlers. 
They have exact headers and lot of anonymous hits are from crawlers, not from users.

**Comment by kuzmany** [comment]
@escopecz I did test with bots simulator  http://www.botsimulator.com/botsim_send.php
Without bot simulator page was tracked
With bot simulator page wasn't tracked

Also doesn't work on localhost.

**Comment by escopecz** [comment]
It does work when I test it with the Bot Simulator. I cannot make it work with my own HTTP request, but that's probably my fault. Alright, I'll approve this, but I'd like @alanhartless to look at this before merge.

**Comment by mqueme** [comment]
It is not saving the selected bots for me. I've tried with choosing one, and multiple, when I go back to look at what I picked none if the options are selected

**Comment by mqueme** [comment]
This worked for me.

**Pull request merged**
