### PR TITLE
replace mrclay/minify with matthiasmullie/minify for faster asset generation

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by escopecz** [comment]
@mollux do you have some benchmarks?

**Comment by escopecz** [comment]
I think that this library swap would also deserve a note in the 5.0 BC breaking changes file.

**Comment by mollux** [comment]
@escopecz hm, somehow that info was lost, I'll redo the benchmarks and add them here.

As far as I remember it was 5 times faster

**Comment by mollux** [comment]
with mrclay/minify
```
time ./bin/console m:a:g
Production assets have been regenerated.

real	0m7.338s
user	0m6.917s
sys	0m0.419s

time ./bin/console m:a:g
Production assets have been regenerated.

real	0m7.640s
user	0m7.226s
sys	0m0.361s

time ./bin/console m:a:g
Production assets have been regenerated.

real	0m7.562s
user	0m7.169s
sys	0m0.370s
```

with matthiasmullie/minify
```
time ./bin/console m:a:g
Production assets have been regenerated.

real	0m1.211s
user	0m0.799s
sys	0m0.409s

time ./bin/console m:a:g
Production assets have been regenerated.

real	0m1.249s
user	0m0.790s
sys	0m0.440s

time ./bin/console m:a:g
Production assets have been regenerated.

real	0m1.215s
user	0m0.782s
sys	0m0.423s
```

**Review by escopecz — CHANGES_REQUESTED** [review]
Nice! Can you drop a line about this library swap to https://github.com/mautic/mautic/blob/5.x/UPGRADE-5.0.md?

**Review by escopecz — APPROVED** [review]
Thanks! It seem to be working well. I compared the prod assets. It generates a few kB larger JS files but a few kB smaller CSS files so it cancels out. 👍

**Comment by escopecz** [comment]
I'm merging this as there are no voices against this after 3 weeks.

**Pull request merged**
