### PR TITLE
Fix order of fields of form

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
In same cases with more complex forms and  conditional fields, reorder does not work.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. I don't know exactly list of fields to setup to reproduce issue, but you can try save and re-sort your forms and see If works like before
3. Of course code review should be good

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10801"></a>

### CODE REVIEW

**Comment by jos0405** [comment]
I tried to test it, but couldn't reproduce the bug in my 4.1.1 installation. What conditions have to be met in order to see the bug?

**Review by volha-pivavarchyk — DISMISSED** [review]
It works like before. But I can't reproduce the bug too

**Comment by volha-pivavarchyk** [comment]
Seems I reproduced this bug in 4.2 version. And I gave the same result with this PR.

Before saving form:
image

After saving form:
image

**Comment by RCheesley** [comment]
I noticed this some time ago on Campaign Studio but it hasn't been fixed there yet - I've asked if this PR can be tested when they come to work on it! :)

**Comment by kuzmany** [comment]
@volha-pivavarchyk It's your local enviroment? Can you share DB with me?

**Comment by volha-pivavarchyk** [comment]
@kuzmany I was testing in my local env. Share the database dump?

**Comment by kuzmany** [comment]
> @kuzmany I was testing in my local env. Share the database dump?

Yes, datavase dump

**Comment by kuzmany** [comment]
@volha-pivavarchyk our customer met the issue, and I found  the issue. Last commit should fixed it now

**Comment by volha-pivavarchyk** [comment]
@kuzmany It works fine for me now. 

Just one thing. I always get a weird result with the first field. It becomes the last one. 
image

**Comment by sebastian-fahrenkrog** [comment]
I could confirm that this pull request solved the problem! Thank you @kuzmany

**Comment by jos0405** [comment]
Hello, there is still an error here.
The JS will generate the wrong order.
However preview works!

image

**Comment by kuzmany** [comment]
Close at the moment. We will push it again once ready to M5

**Pull request closed without merging**
