### PR TITLE
Allow console to leverage the generic autoloader regardless of the location (part 2)

### LINKED ISSUE #10957: bin/console script must be update to work with composer install
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I updated my mautic to version 4.2, and everything was ok, but i read about install mautic with composer to work well with marketplace, so i did.
mautic is working, but when trying to use console commands we receive the error in log output
i think its because the folder structure with composer was change

for information, the 'app' folder out of 'docroot' is empty, and i don't know if this folder must have some files

### How can we reproduce this issue?

Step 1:  Install mautic with composer
Step 2: run any command with console

### Relevant log output

```shell
PHP Warning:  require_once(/var/www/vhosts/xxxxx/public_html/mautic/bin/../app/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/xxxxx/public_html/mautic/bin/console on line 21
PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/xxxxx/public_html/mautic/bin/../app/autoload.php' (include_path='.:/opt/plesk/php/7.4/share/pear') in /var/www/vhosts/xxxxx/public_html/mautic/bin/console on line 21
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #10957 mautic/recommended-project#7 

#### Description:

This is the successor of #10297 , and addresses the autoload issue + adds a test to checks if composer installations are not failing with the changes in a PR

This PR fixes the autoload issue, but will throw a PHP error about doctrine
```
Argument 1 passed to Doctrine\DBAL\Configuration::setResultCacheImpl()...
```
That issue will be addressed in #11053 

#### Added tests

to detect issues in the future that would break composer based installs (where the mono repo is split up, and not all files and folders are in the same place as in this repo), we want to mimic the outcome of a composer install before splitting it up.

The issue this PR fixes is one that cannot be detected without this kind of test.

This is done by using a [composer.json](https://github.com/mautic/mautic/blob/e219fd61a5782de1c6abc45f15c60215c0626abf/.github/ci-files/composer.json) that mimics the one from [mautic/recommended-project](https://github.com/mautic/recommended-project/blob/855ad15316e494150008319233a9924f1500a7c3/composer.json)

The main difference is that the `core-lib`, `plugins` and `themes` aren't pulled from packagist, but are [symlinked](https://github.com/mautic/mautic/blob/e219fd61a5782de1c6abc45f15c60215c0626abf/.github/ci-files/composer.json#L85) from the `app`, `plugins` and `themes` folders.

see e.g. the partial output of [this run](https://github.com/mautic/mautic/runs/5851982432?check_suite_focus=true):
```
...
  - Installing mautic/core-lib (4.x-dev): Symlinking from ../app
  - Installing mautic/grapes-js-builder-bundle (4.2.x-dev): Symlinking from ../plugins/GrapesJsBuilderBundle
  - Installing mautic/plugin-citrix (4.2.x-dev): Symlinking from ../plugins/MauticCitrixBundle
  - Installing mautic/plugin-clearbit (4.2.x-dev): Symlinking from ../plugins/MauticClearbitBundle
  - Installing mautic/plugin-cloudstorage (4.2.x-dev): Symlinking from ../plugins/MauticCloudStorageBundle
  - Installing mautic/plugin-crm (4.2.x-dev): Symlinking from ../plugins/MauticCrmBundle
  - Installing mautic/plugin-emailmarketing (4.2.x-dev): Symlinking from ../plugins/MauticEmailMarketingBundle
  - Installing mautic/plugin-focus (4.2.x-dev): Symlinking from ../plugins/MauticFocusBundle
  - Installing mautic/plugin-fullcontact (4.2.x-dev): Symlinking from ../plugins/MauticFullContactBundle
  - Installing mautic/plugin-gmail (4.2.x-dev): Symlinking from ../plugins/MauticGmailBundle
  - Installing mautic/plugin-outlook (4.2.x-dev): Symlinking from ../plugins/MauticOutlookBundle
  - Installing mautic/plugin-social (4.2.x-dev): Symlinking from ../plugins/MauticSocialBundle
  - Installing mautic/plugin-tagmanager (4.2.x-dev): Symlinking from ../plugins/MauticTagManagerBundle
...
```

The current test is limited to testing if the composer install works (e.g. constraint failures), and basic console commands work. This could be expanded to testing an install in the future.

#### Steps to test this PR:

* for tarball installs
  * run console commands in gitpod, they shouldn't fail
* for composer installs 
  * check the outcome of the `composer install` test
    * there is no autoload error
    * there is a doctrine error (tackled in #11053)
 

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11039"></a>

### CODE REVIEW

**Comment by mollux** [comment]
@escopecz could you have a look at this PR?

**Comment by escopecz** [comment]
@mollux please rebase on top of 4.x instead of 4.2. Also change the base branch for this PR. The next version will be 4.3.0.

**Comment by escopecz** [comment]
@mollux I'm wondering how to test the tarball instance and the composer installation without releasing this code change. Do you have a tip for that? Is the composer installation just following the commands from the new CI test?
```
          mkdir test_composer
          cd test_composer
          cp ../.github/ci-files/composer.json ./
          composer install
          php ./bin/console mautic:assets:generate
          php ./bin/console cache:clear
```
And for tarball test just test with my local git-based installation?

**Comment by mollux** [comment]
@escopecz correct!

**Comment by escopecz** [comment]
It works for tarball/git installations, but when I try to emulate the composer installation I get this after `composer install`:
```
www-data@d9710f602dd2:~/html/test_composer$ ls
Gruntfile.js  app  autoload.php  bin  composer.json  composer.lock  docroot  package-lock.json  package.json  vendor
www-data@d9710f602dd2:~/html/test_composer$ php ./bin/console m:a:g

Fatal error: Uncaught Error: Class 'Symfony\Bundle\WebProfilerBundle\WebProfilerBundle' not found in /var/www/html/app/AppKernel.php:214
Stack trace:
#0 /var/www/html/test_composer/vendor/symfony/http-kernel/Kernel.php(446): AppKernel->registerBundles()
#1 /var/www/html/app/AppKernel.php(251): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /var/www/html/test_composer/vendor/symfony/framework-bundle/Console/Application.php(169): AppKernel->boot()
#3 /var/www/html/test_composer/vendor/symfony/framework-bundle/Console/Application.php(75): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#4 /var/www/html/test_composer/vendor/symfony/console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/test_composer/bin/console(42): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Con in /var/www/html/app/AppKernel.php on line 214
```

**Review by escopecz — DISMISSED** [review]
I guess that's because of the environment. The composer install expects production. It works for production:
```
www-data@d9710f602dd2:~/html/test_composer$ php ./bin/console m:a:g -e prod
Production assets have been regenerated.
```
So I say 👍

**Comment by mollux** [comment]
@escopecz yes indeed, I was going to post the same conclusion :)

**Comment by RCheesley** [comment]
@mollux is it possible to test this with the recommended project installation method (e.g. following our docs on how to install with composer)? I couldn't seem to work it out!

**Review by RCheesley — COMMENTED** [review]
✅  Works great in Gitpod when running `ddev exec bin/console d:f:l` for example.

Not fully clear how to test with recommended project setup - I think I tested it a while ago when working on another PR test, but I can't recall how, possibly by manually copying?

I'm thinking of the perspective from those who already installed that way and needing this fix.

**Comment by RCheesley** [comment]
Given we've tested this in all the scenarios that it's possible to test in without making a release, I think we should make this RTC, and we can ensure that we fully test the Release Candidate.  There are also a couple of other PRs we need to merge in the Recommended Project so we can follow up on that alongside.

**Review by escopecz — APPROVED** [review]
👍

**Comment by mollux** [comment]
@RCheesley @escopecz 

here the steps to verify updating from 4.2.2 to 4.x (which will become 4.3.0) solves the autoload problem

- create a stable project as starting point (4.2.2)
    ```
    composer create-project mautic/recommended-project:^4.0 test_update --no-interaction`. 
    Creating a "mautic/recommended-project:^4.0" project at "./test_update"
    Installing mautic/recommended-project (4.2.2)
      - Installing mautic/recommended-project (4.2.2): Extracting archive.
    Created project in /tmp/test_update
    ```
 - cd into the dir
    ```
    cd test_update
    ```
 - update mautic core to 4.x (notice the extra scaffolded files at the end)
    ```
    composer require --with-dependencies mautic/core-lib:4.x-dev
    ./composer.json has been updated
    Running composer update mautic/core-lib --with-dependencies
    Loading composer repositories with package information
    Updating dependencies
    Lock file operations: 1 install, 2 updates, 0 removals
      - Locking beberlei/doctrineextensions (v1.3.0)
      - Upgrading jms/serializer-bundle (3.10.0 => 4.0.2)
      - Upgrading mautic/core-lib (4.2.2 => 4.x-dev c838688)
    Writing lock file
    Installing dependencies from lock file (including require-dev)
    Package operations: 1 install, 2 updates, 0 removals
      - Installing beberlei/doctrineextensions (v1.3.0): Extracting archive
      - Upgrading jms/serializer-bundle (3.10.0 => 4.0.2): Extracting archive
      - Upgrading mautic/core-lib (4.2.2 => 4.x-dev c838688): Extracting archive
    Package misd/phone-number-bundle is abandoned, you should avoid using it. Use odolbeau/phone-number-bundle instead.
    Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
    Package symfony/inflector is abandoned, you should avoid using it. Use EnglishInflector from the String component instead.
    Package symfony/swiftmailer-bundle is abandoned, you should avoid using it. Use symfony/mailer instead.
    Generating autoload files
    109 packages you are using are looking for funding.
    Use the `composer fund` command to find out more!
    Symfony recipes are disabled: "symfony/flex" not found in the root composer.json

    Scaffolding files for mautic/core-lib:
      - Copy [project-root]/Gruntfile.js from assets/scaffold/files/Gruntfile.js
      - Copy [project-root]/package.json from assets/scaffold/files/package.json
      - Copy [project-root]/package-lock.json from assets/scaffold/files/package-lock.json
      - Copy [project-root]/bin/console from assets/scaffold/files/console
      - Copy [project-root]/autoload.php from assets/scaffold/files/autoload.php
    ```
 - run a console command to verify
    ```
    php ./bin/console m:a:g
    Production assets have been regenerated.
    ```

**Pull request merged**
