### PR TITLE
Unable to perform "Change campaign" Action for removing a contact from one and adding to another campaign

### PR DESCRIPTION
**Pull request by dadarya0**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | 
| BC breaks?                             | 
| Automated tests included?              | yes
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Unable to perform "Change campaign" Action for removing a contact from one and adding to another campaign.

#### Steps to reproduce the bug:

1. Create a form FORM1
2. Create campaign B with 'source'-> FORM1 and 'action' -> anything
3. Create campaign A and go to builder of A.
4. Select 'contact source' -> FORM1 and 'action' -> 'Change Campaign'.
5. Go to that action and select 'Add to Campaign' -> 'B' and 'Remove from Campaign' -> "This campaign"
6. Publish both the campaign.
7. Go to the created form link and submit contact details.
8. Check in contact list of A and B.

**Expected :**
That newly created contact should be removed from A and added to B.

**Actual :**
That newly created contact is added to B but is not removed from A.

#### Steps to test this PR:

1. Create a form FORM1
2. Create campaign B with 'source'-> FORM1 and 'action' -> anything
3. Create campaign A and go to builder of A.
4. Select 'contact source' -> FORM1 and 'action' -> 'Change Campaign'.
5. Go to that action and select 'Add to Campaign' -> 'B' and 'Remove from Campaign' -> "This campaign"
6. Publish both the campaign.
7. Go to the created form link and submit contact details.
8. Check in contact list of A and B.
9. That newly created contact should be removed from A and added to B.

### CODE REVIEW

**Review by npracht — COMMENTED** [review]
Hello @dadarya0, i'm trying to test your PR, when i run `bin/console mautic:campaigns:trigger` i have error in CLI and my campaign is not updated.

It crashed on campaign 1 (not the one with campaign "add/remove action"). It is a simple campaign with just a "add point action".
Capture d’écran 2021-07-13 à 14 06 41


```
[2021-07-13 12:02:26] mautic.WARNING: PHP Warning - require(/var/www/html/var/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php): failed to open stream: No such file or directory - in file /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 187 {"className":"Mautic\\PluginBundle\\Entity\\Plugin","classMetadata":"[object] (Doctrine\\ORM\\Mapping\\ClassMetadata: Doctrine\\ORM\\Mapping\\ClassMetadataInfo@000000002dd36c9300000000376da674)","proxyClassName":"Proxies\\__CG__\\Mautic\\PluginBundle\\Entity\\Plugin","fileName":"/var/www/html/var/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php"} []
[2021-07-13 12:02:26] mautic.ERROR: PHP Notice: require(): Failed opening required '/var/www/html/var/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php' (include_path='.:/usr/share/php') - in file /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 187 [] []
[2021-07-13 12:02:26] mautic.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Notice: require(): Failed opening required '/var/www/html/var/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php' (include_path='.:/usr/share/php') - in file /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 187 [] []
```

**Comment by dadarya0** [comment]
> Hello @dadarya0, i'm trying to test your PR, when i run `bin/console mautic:campaigns:trigger` i have error in CLI and my campaign is not updated.
> 
> It crashed on campaign 1 (not the one with campaign "add/remove action"). It is a simple campaign with just a "add point action".
> Capture d’écran 2021-07-13 à 14 06 41
> 
> ```
> [2021-07-13 12:02:26] mautic.WARNING: PHP Warning - require(/var/www/html/var/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php): failed to open stream: No such file or directory - in file /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 187 {"className":"Mautic\\PluginBundle\\Entity\\Plugin","classMetadata":"[object] (Doctrine\\ORM\\Mapping\\ClassMetadata: Doctrine\\ORM\\Mapping\\ClassMetadataInfo@000000002dd36c9300000000376da674)","proxyClassName":"Proxies\\__CG__\\Mautic\\PluginBundle\\Entity\\Plugin","fileName":"/var/www/html/var/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php"} []
> [2021-07-13 12:02:26] mautic.ERROR: PHP Notice: require(): Failed opening required '/var/www/html/var/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php' (include_path='.:/usr/share/php') - in file /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 187 [] []
> [2021-07-13 12:02:26] mautic.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Notice: require(): Failed opening required '/var/www/html/var/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php' (include_path='.:/usr/share/php') - in file /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 187 [] []
> ```

@npracht it seems cache issue, could you please clear your cache ?

**Review by kuzmany — APPROVED** [review]
This work as expected.
Thanks!
Unit test included.
Code seems legit.

👍

**Comment by RCheesley** [comment]
Thanks for the PR @dadarya0 - tested this locally and was able to reproduce the bug, and the PR does indeed address the problem with the contact's adding/removal from campaigns!

GTG 🚀

**Pull request merged**
