### PR TITLE
[WIP] Add Mailgun Transport

### LINKED ISSUE #6536: Mailgun Integration (2nd Attempt)
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | YES
| Enhancement? | 

## Description:
MailGun integration (Webhook or Plugin) for Mautic, to allow for Unsubscribe and bounces of emails, etc.
This is a reopening of https://github.com/mautic/mautic/issues/1694 as NO answer has ever been given, and ALOT of people are requesting a solution.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/63130974-mailgun-integration-2nd-attempt?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.1
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #6536

#### Description:

Add Mailgun API as one of the transports to Mautic, this job is still in progress, I will be working on it in the next few days to get Mailgun supported hopefully by version 32.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2.

### CODE REVIEW

**Comment by escopecz** [comment]
@mabumusa1 I'm a bit confused here. It's marked for 3.2.0 release but it's a WIP draft. Which is it?

**Comment by mabumusa1** [comment]
@escopecz sorry for the confusion, I am still working on it. removed the milestone

**Comment by RCheesley** [comment]
@mabumusa1 would be awesome to get this into 3.3 if you're able to get the tests written and checks passing in time!

**Comment by mabumusa1** [comment]
@RCheesley I am working on it but slowly unfortunately. If you know someone who can assist me on this would be great as many parts of the code are there

**Comment by RCheesley** [comment]
@mabumusa1 is it likely that this will be ready for the 3.3 release freeze do you think? If not we will move it to the 4.0 mliestone.

**Comment by npracht** [comment]
@mabumusa1 do you expect continue working on it, or i close it ?

**Comment by mabumusa1** [comment]
I will revisit this PR again

**Comment by imihandstand** [comment]
Any news on this?

**Pull request closed without merging**
