### PR TITLE
Bump min PHP requirement to 8.0 (part 2)

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

in #11581 php 7.4 was dropped, but some places were missed where that change is relevant too.

DDEV was tackled in #11600

This PR ensures the release workflow will use the correct PHP version (8.0) + the `release_metadata.json` file contains some sane defaults fore the upcoming 5.0 release.

The `version` is intentionally incorrect, as this file should be checked during release flow.

#### Steps to test this PR:

1. Check the mautic source code for occurrences for `7.4` in non-test code, there should be none

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
Thank you Mattias! 👍

**Comment by escopecz** [comment]
Looking at the broken tests. Do you have any tip why would it start failing because of the changes?

**Comment by mollux** [comment]
@escopecz 
the `"version": "5.x"`  in the `release_metadata.json` file [wasn't matching the regex](https://github.com/mautic/mautic/blob/5.x/app/bundles/CoreBundle/Release/Metadata.php#L41), breaking everything :)
https://github.com/mautic/mautic/pull/11605/commits/4e150bb929b7d941bc209cfd045e206e53edee83 should fix this.

**Review by escopecz — APPROVED** [review]
Thank you!

**Pull request merged**
