### PR TITLE
WIP - Segment refactoring

### PR DESCRIPTION
**Pull request by Maxell92**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. 
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by kuzmany** [comment]
Hi @Maxell92 , 
my client has feature request add category to segments.
Do you think you're able to add to this refactor PR or I could create it and add PR to your branch https://github.com/Maxell92/mautic/tree/feature/segment-refactoring ?

**Comment by Maxell92** [comment]
Hi @kuzmany,
we continue with refactoring in this branch: https://github.com/galvani/mautic/tree/maxell92/feature/segment-refactoring

We need to make sure that new segments will give correct results first. There are lot of things that need to be refactored / added, but we want to make this PR as small as possible, because of segments are critical part of Mautic and testing and comparing results is not easy here.

So this is only first step on the work on segments. I think it would be better if you wait for merge than you can add categories.

**Comment by kuzmany** [comment]
@Maxell92 Thanks for answer.  We'll wait.

**Comment by Maxell92** [comment]
This PR is replaced by https://github.com/mautic/mautic/pull/5755.

**Pull request closed without merging**
