### PR TITLE
Fix Core.parseToObject

### LINKED ISSUE #10229: JSON.parse issue (4.0.0-beta)
## Bug Description
Bug appears similar in nature to:

https://github.com/mautic/mautic/issues/9951
https://github.com/mautic/mautic/pull/9972

The issue, of course, prevents further processing and submission of the resultant form.

| Q   | A
| --- | ---
| Mautic version | Mautic 4.0.0-beta - app/prod (env: prod, debug: false)
| PHP version | 7.4
| Browser | All (FF, Safari, Chrome, Edge)

### Steps to reproduce
1. Create a basic form (name, email, message)
2. Use "Automatic" script
 
### Console errors
```
Uncaught SyntaxError: 
JSON.parse: expected ':' after property name in object at line 1 column 13 of the JSON data
```

### Apparent offending code
```
Core.parseToObject = function(params) {
      return JSON.parse(
        '{"' +
          decodeURI(
            params
              .trim()
              .replace(/&/g, '","')
              .replace(/=/g, '":"')
          ) +
          '"}'
      );
    };
```
-----
<a href="https://rysolv.com/issues/detail/8e0bf6cb-7abd-4964-98cc-17d34524a97c"></a>

### PR DESCRIPTION
**Pull request by Bouh**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 4.0
| New feature/enhancement? (use the a.x branch)      | No
| Deprecations?                          | No
| BC breaks? (use the c.x branch)        | No
| Automated tests included?              | No
| Related user documentation PR URL      | No needs
| Related developer documentation PR URL | No needs
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/issues/10229

#### Description:

This fix formats the parameters better and handles the fancy parameters better.
Fix params parsing from this issue https://github.com/mautic/mautic/issues/10229

#### Steps to test this PR:

You can see tests in a [code sandbox here](https://codesandbox.io/s/params-fix-e8fhw?file=/src/index.js), check the console tab for more information.

### CODE REVIEW

**Comment by Bouh** [comment]
Signed here [redacted personal details]

**Comment by RCheesley** [comment]
Hi @Bouh and thanks for submitting the PR and signing the contributors agreement! 

As this is a bug fix could you please rebase on the 4.0 branch so that we can potentially get it into the next patch release? Here is some info about our branching strategy: https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#choose-the-right-branch.

@cla-bot check

**Comment by Bouh** [comment]
How to fix the latest failing test?

**Comment by RCheesley** [comment]
@Bouh it looks like the rebase hasn't quite worked, if I check the files changed tab, there are a lot of files showing as modified. Usually it means a rebase is needed but it might be just as easy to pull down the 4.0 branch and re-make the PR from the correct base and then close this one.

The failing test relates to code coverage but this is flagging up files unrelated to your PR as well.

**Comment by Bouh** [comment]
> @Bouh it looks like the rebase hasn't quite worked, if I check the files changed tab, there are a lot of files showing as modified. Usually it means a rebase is needed but it might be just as easy to pull down the 4.0 branch and re-make the PR from the correct base and then close this one.
> 
> The failing test relates to code coverage but this is flagging up files unrelated to your PR as well.

Thank you!
Re open here: https://github.com/mautic/mautic/pull/10509

**Pull request closed without merging**
