### PR TITLE
Fix: Checkbox group in form return bool

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) |  https://github.com/mautic/mautic/issues/5348
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

This bugfix/feature has been sponsored by @Webmecanik

Form checkboxgroup return array then it wansn't possible match value to contact field and was ignored.
This fix just check if value is array and with 1 size and then convert array to value.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:

1. Create a boolean contact custom field with YES and NO (
2. Create a form
3. In this form add a checkox group field and map it to the previous custom field created. 
4. In properties tab, add a value (in the value, I fill the value that equals to Yes) I tried Yes, 1 and True.
5. Fill the form and clic on the box.
6. Go to contact sheet and check the value for the the custom field create before. There is no value. It should be Yes

#### Steps to test this PR:
1.  Same like steps to reproduce
2.  But see contact profile and his contact field bool value

image

### CODE REVIEW

**Comment by npracht** [comment]
Just tested it works ! 👍

**Comment by johbuch** [comment]
@kuzmany 
I tested also. 
I got this field (mapped to a boolean field)
image
If I answer Yes > I got the good value which is 1
image
But if I choose No > I got nothing on the contact sheet 
image
On the form field, I tested with 1 and 0 as values
image
But also with true and false. It is always the same

**Comment by kuzmany** [comment]
@johbuch works just with one option in checkbox group.
If you are using more checkbox options then you need use the same or similar custom contact field  with multiple options support.

This patch resolve just one option and covert value from array to normal value. Naturally

**Comment by npracht** [comment]
So if i understand well, for this 2 options boolean, it shouldn't be a checkbox group but a radio button right ?

Thanks !

**Comment by kuzmany** [comment]
@npracht yeas multiple checkboxes return multiple values, then  we can't save multi values (array) to single contact field. 
For multiple options use radio buttons with one result use radio button.
For one option use checkbox.

**Comment by ticlekiwi** [comment]
Hi, I have the same problem, but my custom field isn't a boolean : it is a Select data type with only two values : "Yes" and "No" (don't ask me why I didn't use a boolean, I don't know). 

I previously used a checkbox form field to update my custom field in a form, but since last release (2.11.0), my value isn't saved anymore.  (I'm now using two radio inputs while waiting for a solution.)

I thought this patch would solve my problem, but sadly no. 
But it's weird because by reading the patch I really thought he was going to solve it!

**Comment by javjim-mautic** [comment]
Was able to reproduce bug and fix. Thanks

**Pull request merged**
