### PR TITLE
Add GrapesJs builder as default builder

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR require changes on plugin side https://github.com/mautic/plugin-grapesjs-builder/pull/79

#### Steps to test this PR:
1. Clone Mautic locally
2. cd to the plugins directory
2. Remove the GrapesJS plugin and clone this repo: https://github.com/mautic/plugin-grapesjs-builder into the folder `GrapesJsBuilderBundle` - can be done using `gh repo clone mautic/plugin-grapesjs-builder GrapesJsBuilderBundle` if you have GitHub CLI installed
3. cd into the `GrapesJsBuilderBundle` directory
3. Apply the PR https://github.com/mautic/plugin-grapesjs-builder/pull/79 - can be done using `gh pr checkout 79` if you have GitHub CLI installed
2. cd back to Mautic's root directory
2. Apply this PR - can be done using `gh pr checkout 9935` if you have GitHub CLI installed
3. GrapesJs should now be the default builder without additional changes being needed (enable/disable)...

### CODE REVIEW

**Comment by kuzmany** [comment]
Close this. As default builder, do not need it

**Review by RCheesley — APPROVED** [review]
I added some testing instructions to this PR and the one in the builder in case folks have not been testing one or the other!

Works great for me in that the GrapesJS builder is the default builder now for email and landing page.

Need a review from @adiux to make sure that this is compatible with the changes we are making for theme/builder relationship.

**Comment by RCheesley** [comment]
There is a conflict to address here, and we need the corresponding PR to be re-made against mautic/mautic with the option to disable the GrapesJS builder if people want to, as we are planning to fully remove the legacy builder in the 5.0 release.

**Comment by RCheesley** [comment]
Closing this PR as it does not do what we need and has conflicts. @kuzmany if you are able to adjust this PR then do re-open it, but otherwise we will need another to allow enabling by default while being able to disable at will.

**Comment by kuzmany** [comment]
@RCheesley at the moment I do not have time to write  new solution to bring  grapesJS as default.  We need write migrations and also data fixtures to load enable GrapesJs as deafult during the new installations.

**Pull request closed without merging**
