### PR TITLE
Fix campaign trigger scheduled day/hour

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging for features or enhancements / 3.0 for bug fixes 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR is based on https://github.com/mautic/mautic/pull/8874 already merged in repo.
We noticed in some cases actions were not scheduled but executed.

Steps to reproduce:

1. Create campaign with conditions and action after condition

image

2. Schedule action  run today 0 days from 23:00 to 23:30 for example

image

3. Run campaign and action is triggered now even If you enable schedule

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat all steps and check if action was scheduled properly

### CODE REVIEW

**Comment by kuzmany** [comment]
@alanhartless @hluchas would be greate If you can take a look. This PR just continue fix issue from Acquia PR https://github.com/mautic/mautic/pull/8874

**Comment by kuzmany** [comment]
@alanhartless @hluchas Can you review this PR? It's coming up your already merged PR https://github.com/mautic/mautic/pull/8874, but fixes more cases.

**Comment by RCheesley** [comment]
@kuzmany I think that this is already fixed. I ran this on Staging setting it to trigger in 1 day between 11-1130pm (my instance is set in Paris timezone, so UTC +2) and I see the correct scheduling.

Propose therefore closing this PR?

screenshot-local mautic3-2020 08 14-11_21_56


screenshot-local mautic3-2020 08 14-11_22_19

**Comment by kuzmany** [comment]
@RCheesley it's not fixed.  
Run action after condition, set 0 days and time 23:00 23:30 for example. See It's triggered now.

**Comment by RCheesley** [comment]
OK so are you saying that the problem is when 0 days is set rather than 1 day?

**Comment by RCheesley** [comment]
Aha, I found the issue. I'll re-test.

**Review by RCheesley — APPROVED** [review]
Tested the bug and found the issue when the relative day was set to zero and the time set to 2300-2330 that the scheduling was incorrect.

Applied the PR and ran several tests using +1 day, 1 month etc and all seem to now be scheduling properly (my timezone is set to Paris so the time is correct also).  Apologies for the misunderstanding of the instructions! 😊 

screenshot-local mautic3-2020 08 14-12_38_58

**Review by dennisameling — APPROVED** [review]
Works as described, nice fix! Thanks @kuzmany 

image

**Pull request merged**
