### PR TITLE
Multiple emails per lead in v1.2.3

### PR DESCRIPTION
**Pull request by that0n3guy**

### CODE REVIEW

**Comment by escopecz** [comment]
@that0n3guy could you please update description so others could understand what is this PR about and how to test it?

https://github.com/mautic/mautic/blob/staging/CONTRIBUTING.md

**Comment by alanhartless** [comment]
Looking at the code, am I understanding it right that it's restricting campaign events to only leads with email addresses?

**Comment by that0n3guy** [comment]
Ha, oops.  I didn't even realize I created the PR against `mautic/mautic`.  Sorry, it was an initial code commit and I was just reviewing on our fork.  

Since this was a big OOPS on my part, feel free to delete the pull request and I'll create another later.  

> Looking at the code, am I understanding it right that it's restricting campaign events to only leads with email addresses?

This was the first iteration Zeeshan came up with.  I already talked with him about it and he is trying something else because I think its a bad idea.

**Comment by alanhartless** [comment]
Thanks Peter!

**Pull request closed without merging**
