### PR TITLE
UI/UX bug fixes

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR fixes bugs.

- X close button was behind the text in flash messages
- no padding for conditions and decisions on campaign builder
- missing confirmation for reset learning button in account settings
- removes hardcoded stripes for timeline table in contact details
- fixes modals permanently hidden after dismissed

image

image

image

image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open the campaign builder and add conditions + decisions to see they're normal
3. Open Assets > New > Select Remote storage > Click to Browse files > Close the modal > Open again
4. Open Account and click to Reset learning experience, a flash message will appear to show it's working
5. Open Contacts > actions dropdown > export to CSV > see flash notification with X for closing

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
I don't have spare time today to test, but I reviewed the code and it looks fine 👍

**Comment by matbcvo** [comment]
I have tested this PR and it looks good to me.

### 1. no padding for conditions and decisions on campaign builder 👍

5.x branch

image

PR

image

### 2. fixes modals permanently hidden after dismissed 👍

5.x branch

Screen Recording 2024-10-31 222937

PR

Screen Recording 2024-10-31 220836

### 3. missing confirmation for reset learning button in account settings 👍

5.x branch

Screen Recording 2024-10-31 221324

PR

Screen Recording 2024-10-31 221417

### 4. X close button was behind the text in flash messages 👍

5.x branch

image

PR

image

### 5. removes hardcoded stripes for timeline table in contact details 👍

5.x branch

image

PR

image

**Review by matbcvo — APPROVED** [review]
Code changes looks good to me

**Comment by andersonjeccel** [comment]
@matbcvo how did you make those gifs? It was a beautiful review

**Comment by matbcvo** [comment]
@andersonjeccel I used the Windows Snipping Tool (Windows + Shift + S) to record the video. Since it saves the recording as an .mp4 file, I converted it to .gif using [CloudConvert](https://cloudconvert.com/mp4-to-gif). Then, I downloaded the .gif, opened it, and copy-pasted it here.

**Comment by andersonjeccel** [comment]
@matbcvo wow, I’m shocked to see your effort 😯👏

thanks for reviewing!

**Pull request merged**
