### PR TITLE
Fix normalize value for boolean contact field

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
In some cases, If properties are set in order first value Yes, second No, normalize value work not as expected. This PR fixed it

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Create boolean contact fields
3. Set properties in table to `a:2:{s:3:"yes";s:3:"Yes";s:2:"no";s:2:"No";}`
4. Create contact and set to Yes
5. Go to contact detail and see normalized value as No
6. After PR you should see Yes in contact detail

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11235"></a>

### CODE REVIEW

**Review by IrisAmrein — DISMISSED** [review]
I have tested this and it did work for me as explained. 

PS: I'm a new tester - let me know if you want me to test again after the automated checks have been fixed (not really sure if I've been too eager here ^^)

**Comment by escopecz** [comment]
@IrisAmrein thank you for testing! You make a difference! Great question. I checked the commits that were done after your test and they affect only the unit test. Not the production code. So your test is still valid 🎉

**Review by escopecz — DISMISSED** [review]
@kuzmany great work. Nice tests. Well done 👍

**Review by escopecz — APPROVED** [review]

**Comment by Shubham-Shinde-Acquia** [comment]
Hi @kuzmany , is there any way to do this via UI. As Setting properties in table to a:2:{s:3:"yes";s:3:"Yes";s:2:"no";s:2:"No";} will be not a real customer case.

**Comment by kuzmany** [comment]
@Shubham-Shinde-Acquia I found this in DB. I do not investigate how it came there. Probably something from older  M2/M3, probably from API. Who knows. But I focus on fixing this case comes to the app.

**Pull request merged**
