### PR TITLE
Release 2.14.1-beta

### PR DESCRIPTION
**Pull request by heathdutton**
This includes some 96 issues:
https://github.com/mautic/mautic/milestone/47?closed=1

### CODE REVIEW

**Comment by luizeof** [comment]
@heathdutton this release will be available as an pull-request for test or an official beta?

**Comment by YosuCadilla** [comment]
I tested with 2.14.1-beta and it seems NOT to solve the issue, here's a complete list of possibly related issues: #6515 #5546 #6482 #6419 #6211 #6433 #63

**Comment by YosuCadilla** [comment]
Seems Github has issues to solve too: #63 as seen here: https://github.com/mautic/docker-mautic/issues/63

**Comment by YosuCadilla** [comment]
#6460 maybe too

**Pull request merged**
