### PR TITLE
Confirm Me - MJML Fixes

### PR DESCRIPTION
**Pull request by jos0405**
a = current major release

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ X]
#### Description:

This PR adds code to the MJML head, makes the template more stable.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a segment or template email using this template. Edit the text - now you'll see, that font type / size is not changing.
3. Padding is set properly.

### CODE REVIEW

**Comment by FabienneAivie** [comment]
I tried to test it, but could not open it with gitpod.

**Comment by RCheesley** [comment]
I think the PR was very out of date with the main 5.x branch - I just merged in the latest changes and we seem to be up and running on Gitpod again.

Sorry for the inconvenience @FabienneAivie - do let us know in #t-product on Slack if you come across problems like this again in the future!

**Comment by sdoering** [comment]
Hi @jos0405, 

tested it. Works and looks great. 

In the Builder: 
image


In the preview: 
image

**Review by mabumusa1 — APPROVED** [review]
Changes look good, this is ready to be merged

**Review by escopecz — APPROVED** [review]
I see nothing wrong in the code. Thanks! 👍

**Pull request merged**
