### PR TITLE
Update Sendgrid library to v7 and add hash_id parameter for callback TPROD-101

### LINKED ISSUE #5967: Contact in CC does not get form results with SendGrid, Sparkpost & SMTP transport
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When sending a form result, there is the option to send this to multiple contacts in CC, seperated by a comma. But the results aren't sent to the email addresses after the comma (tried it with and without a space between the comma and email address).

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.12.2
| PHP version | 7.0.28-1~dotdeb+8.1
 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/57248547-contact-in-cc-does-not-get-form-results-with-sendgrid-sparkpost-smtp-transport?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by optimeadmin**
…tracking

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.2
| Bug fix?                               | yes
| New feature?                           | yes
| Deprecations?                          | no
| Issue(s) addressed                     | Fixes #5967  

#### Description:
Sendgrid library was updated to v7 with some differences in how CC and BCC are included in the payload. Plus, it can include other parameters that we use to track the failed statistics from SendGrid.

#### Steps to test this PR - BCC:
1. Load up [this PR](https://mautibox.com)
2. Composer install
3. Send an email with BCC
4. Check that email in BCC was received

#### Steps to test this PR - Failed tracking:
1. Load up [this PR](https://mautibox.com)
2. Composer install
3. Configure callback URL in SendGrid (not localhost)
4. Send an email with a wrong email address (for failed tracking check)
5. Wait for the wrong email address contact to update

### CODE REVIEW

**Comment by RCheesley** [comment]
Thank you for the PR @optimeadmin @ayusopatricia - it looks like you have some failing tests that will need to be addressed before we can take a look at this PR - can you take a look?

@cla-bot check

**Comment by dennisameling** [comment]
@optimeadmin just running `composer update --lock` should be enough to update the `composer.lock` file which is why the tests are failing. Thanks in advance!

**Comment by optimeadmin** [comment]
Thank you @dennisameling and @RCheesley.

**Comment by RCheesley** [comment]
Thanks for fixing the composer file @optimeadmin - could you take a look at the tests which are still failing?

**Pull request closed without merging**
