### PR TITLE
Fix date for dynamic contents

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | feature for 4.0
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      |
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
Notice issue with date field in dynamics content

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create custom contact date field
3. Create dynamic content for landing page with filter on date field with not empty operator.
4. Test dynamic content
5. Without PR you always see variant for not empty, even if your field is empty.
6. After PR you should see content properly

### CODE REVIEW

**Review by npracht — DISMISSED** [review]
Capture d’écran 2021-05-06 à 09 14 20

Works like a charm

**Comment by RCheesley** [comment]
@kuzmany looks like we have a conflict to address here, could you take a look?

**Comment by kuzmany** [comment]
@RCheesley conflicts resolved

**Review by RCheesley — APPROVED** [review]
Thanks for fixing this issue @kuzmany - I was able to reproduce the issue and when the PR was applied, the correct variant was shown based on the date field as described.

We will need a code review on this as neither of the two testers have reviewed the code, but then I think we are good to go!

**Pull request merged**
