### PR TITLE
IntegrationBundle config form notes

### PR DESCRIPTION
**Pull request by shinde-rahul**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [:x:]
| New feature/enhancement? (use the a.x branch)      | [ **5.x**]
| Deprecations?                          | [:x:]
| BC breaks? (use the c.x branch)        | [:x: ]
| Automated tests included?              | [✅  ] 
| Related user documentation PR URL      | mautic/mautic-documentation#...  
| Related developer documentation PR URL | mautic/developer-documentation#214  
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Review by kuzmany — DISMISSED** [review]
Even If it's WIP I tested it right now on new integration what I've build and works. I've used ConfigFormNotesInterface from https://github.com/mautic/plugin-helloworld/pull/9

**Review by kuzmany — DISMISSED** [review]

**Comment by kuzmany** [comment]
@shinde-rahul can we switch it to ready to test?

**Comment by shinde-rahul** [comment]
@kuzmany, I'll put it ready for review once the merge conflict is resolved. Thanks

**Comment by escopecz** [comment]
@shinde-rahul could you please fix the conflict? It should also fix the failing test. I'll make sure to highlight this PR in the Friday testing sprint to get this in.

**Review by escopecz — APPROVED** [review]
Thank you! 👍

**Pull request merged**
