### PR TITLE
fixes html issues in preference center

### LINKED ISSUE #6150: Html malformed for preference center
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
The HTML rendered for a preference page is invalid

the code of a preference center begin by :

```
<!DOCTYPE html>
<html>
    <head>
                <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" type="text/css" />
            
    </head>
    <body>
        <form novalidate autocomplete="false" data-toggle="ajax" role="form" name="lead_contact_frequency_rules" method="post" action="/email/unsubscribe/5b0ffeba88a08">

            <div>
        <!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" style="" class=" js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients no-cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths js csstransforms csstransforms3d csstransitions responsejs "><head>
```

they are 2 declarations of the doctype and the `<form>`  opened just after the body tag is :
- conflicting with the rest of the html
- not being closed

they are 2 `</body>` tags at the bottom of the page

```
</body></html>

            </div>
        
    </body>
</html>
```
It seem that the render of the preference center is in conflic somewhere in the corebundle

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1 and above
| PHP version | 7.0

### Steps to reproduce:
1. create a preference center landing page
2. configure an email with this preference page
3. open the preference page by clicking on the unsubscribe link in the email
4. look at the html source of the page
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

### PR DESCRIPTION
**Pull request by mtahiue**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | X
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Fixes #6150

#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. 
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by mtahiue** [comment]
In fact the html for prefcenter is already rendered, no need to call `$this->render($contentTemplate, $viewParams);`

so just send rendered html as a reponse

am i correct about this ?

**Comment by mtahiue** [comment]
Huuu, this is not the correct way to fixes this issue :-(

The main form for prefs center is not in the generated html from the page, the render method is needed, but the html from the page is not adapted, could a core dev help to solve this in a clean way ?

so, my PR is invalid / incomplete

**Comment by escopecz** [comment]
There are some [code standard issues](https://travis-ci.org/mautic/mautic/jobs/387646577#L697). Please fix them.

**Comment by npracht** [comment]
@kuzmany you've been working on inserting forms on PC, what do you think of this ? Anything to keep or we should close it ?

**Comment by kuzmany** [comment]
Close it due inactivity and lot of changes until now.
If there is issue, please create issue report or new pull request on last staging.

**Pull request closed without merging**
