### PR TITLE
Segment membership as a new filter for dynamic email content

### PR DESCRIPTION
**Pull request by escopecz**
| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Add ability to use segment filters in email dynamic content.

#### Steps to test this PR:

1. Create a contact with email address `contact@a.email`
2. Create another contact with email address `contact@b.email`
3. Create "Segment A" with no filters
4. Create "Segment B" with no filters
5. Add the first contact to Segment A and the second contact to Segment B
7. Create email in `Channels > Emails`
    - Click on segment email
    - Choose both segments
    - Click builder
    - Drag dynamic content to email content 
    - Customize slot content with some default text
Snímek obrazovky 2020-10-29 v 12 55 38
    - Click green `Add variant button` - and `Variation 1` will be added
    - Fill custom content for segment contacts
    - select Segment Membership 
 Snímek obrazovky 2020-10-29 v 12 47 23
    - Save the email and send
    - The contact from Segment A will have content from Variant 1 and the other will see the default content

### CODE REVIEW

**Comment by escopecz** [comment]
This is blocked by https://github.com/mautic/mautic/pull/13526. It needs method introduced there.

**Comment by rohit-sharma-1802** [comment]
@escopecz I have tested this, I am getting warning and not able to open email module [](url)

**Comment by escopecz** [comment]
@rohit-sharma-1802 that's why I labeled it as WIP and blocked. It's not finished and it's waiting for another PR I linked in my previous comment to be merged first.

**Comment by RCheesley** [comment]
@escopecz I've marked this one as draft - the PR it was dependent on is now merged but I guess it may still need some finishing up before it's ready for testing?

**Comment by escopecz** [comment]
This is ready for review and tests now.

**Comment by abhisekmazumdar** [comment]
I tested the functionality following the steps mentioned (thank you for the detailed steps). I found that the filter works and the content has been replaced in the email.

I set the segment membership as:

Screenshot 2024-06-12 at 2 26 27 PM

And the Applied text showed up in the email with the set segment.

I reviewed the code, but due to my limited expertise, I cannot say I have thoroughly examined it.

**Comment by escopecz** [comment]
@abhisekmazumdar Thanks for testing ! Could you use the approve function so it's visible how many approvals a PR has? 

Screenshot 2024-06-12 at 11 29 39

**Review by abhisekmazumdar — APPROVED** [review]
Oops, my bad. I forgot to approve it.

**Review by fedys — APPROVED** [review]
The code changes make sense. Thanks @escopecz!

**Pull request merged**
