### PR TITLE
Fix of campaign reschedule loop

### PR DESCRIPTION
**Pull request by escopecz**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | N
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/6971, https://github.com/mautic/mautic/issues/6625, https://github.com/mautic/mautic/issues/7226
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

We found a never ending loop that was creating massive amount of user notifications. When a contact is added to a campaign with the Send (marketing) Email event and the marketing email was sent to this contact previously then it the event will fail with error: `Last execution error: John Doe has already received this marketing email.`. The problem is that the event was rescheduled for another 30 minutes. And so this generated new notifications for the same contact and the same campaign event every 30 minutes.

The solution is to just send the error once without rescheduling.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a campaign that has 2 events to send the same marketing email. The second event will have delay of 3 minutes (for example)
2. Trigger the campaign for 1 contact. It will send the email properly. 
3. Wait 3 minutes and trigger the campaign again.
4. You should see the error message in the contact detail page in his history and the email should be scheduled for another 30 minutes.

You will see the notification created for every 30 minutes if you will test that long.

#### Steps to test this PR:
1. Checkout this branch.
2. Wait another 30 minutes or clone the campaign and test from the beginning.
3. The scheduled email should disappear.

Only 1 notification should be created.

### CODE REVIEW

**Comment by Carlos-mb** [comment]
I have modified the file CampaignSubscriber.php and it doesn't crash.. but it neither create the notification that the email was not sent because it was already sent.  Is it a correct behaviour?

**Comment by escopecz** [comment]
If it generates it only once and not every 30 minutes than that's how it should work after this patch is applied.

**Comment by Carlos-mb** [comment]
> If it generates it only once and not every 30 minutes than that's how it should work after this patch is applied.

It generates none. Table maujs_notifications is empty

I have activated the old campaigns and it doesn't create any notification.  I have a lot of marketing emails already sent because I have created alternative campaigns to workaround the issue. So, after activate the old campaigns, there should be about 500 notifications of marketing emails already sent.

**Comment by Carlos-mb** [comment]
This is what I have changed 

image

**Comment by escopecz** [comment]
@Carlos-mb I can't tell from your comments if it works for you or not.

**Comment by Carlos-mb** [comment]
I don't know if it works. 

1. It's not crashing (that's good)
2. It's not creating thousand of notifications (it's good)
3. It's not creating any notification (it's not good... It should create one per email already sent)
4. I haven't info enough o know it it's sending rest of emails... 

That's what I know right now.

**Comment by AlbanL74fr** [comment]
@escopecz I tried, and it's working as expected. Just a notification and no rescheduling message. Thanks

**Pull request merged**
