### PR TITLE
Page visited criteria on lists

### PR DESCRIPTION
**Pull request by Dcoutelle**
## Description
Added new field options when creating a list.
A lead can enter in a list if he visited a page.

## Steps to test
Create a new list with URL criteria.
Update list cron

### CODE REVIEW

**Comment by escopecz** [comment]
Looks good! Could you please fix the indentation so it would respect the Mautic's [coding standards](https://github.com/mautic/mautic/blob/staging/.github/CONTRIBUTING.md#coding-standards)?

**Comment by Dcoutelle** [comment]
Done!

**Comment by escopecz** [comment]
Thanks! 
I hate to be such nitpicker, but you still use tabs instead of 4 spaces in LeadListRepository.php and the indentation in ListModel.php is also somehow corrupted.

**Comment by Dcoutelle** [comment]
no problem!

This shoud be OK this time, we found a tool to format automaticly.

**Comment by escopecz** [comment]
While testing, I noticed there are 2 options for "Page URL". One of them is my custom lead field. But I wonder if the "Page URL" could be renamed to something which will less likely be the same as a lead field.
mautic-segment-url

Anyway, that's just a small issue only I and maybe one or two other weirdos will have. The PR works as described :+1:

**Comment by mqueme** [comment]
Worked for me

**Pull request merged**
