### PR TITLE
Prevent stripping of Script and Style Tags in Froala

### PR DESCRIPTION
**Pull request by inkovic**
htmlAllowedTags and htmlRemoveTags were contradicting each other, and `script` tags were being stripped within the Froala Editor. This issue has been tackled before but keep rearing its ugly head. Making the htmlRemoveTags array an empty array will fix this issue.
Ref: https://github.com/mautic/mautic/pull/2032/commits/70c8f37612909e4a0eb9e050054eda5f5c65b472

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? |  Y
| New feature? | 
| Automated tests included? | N
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1.  Add a <script> tag within the Froala WYSIWYG in Code View
2. Gets stripped on refresh.

#### Steps to test this PR:
1. 
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by heathdutton** [comment]
Instead of hacking the froala core file can't we add `htmlRemoveTags: [],` here https://github.com/mautic/mautic/blob/a1142e17322edd5b4529caf6ba971887e2db591a/app/bundles/CoreBundle/Assets/js/11.editor.js#L16  ?

**Comment by npracht** [comment]
Hi @inkovic would you consider exploring Heath suggestion?

**Comment by npracht** [comment]
Hi @heathdutton would you carry the end of this PR ? Otherwise we close it, it seems the creator won't modify it anymore.
Thanks !

**Comment by RCheesley** [comment]
@heathdutton if this is still an issue do you think you could pick this up and we could get it into 2.16.1?

**Comment by heathdutton** [comment]
> @heathdutton if this is still an issue do you think you could pick this up and we could get it into 2.16.1?

It's a preference, but I can see how it'd be frustrating for someone. I remade the PR as #8556 to do it without modifying the Froala lib file.

**Pull request closed without merging**
