### PR TITLE
Added new filter option for global email do not contact

### PR DESCRIPTION
**Pull request by th-markus**
Adds a filter which gathers all of the leads specified in the "do-not-contact" table for email.

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? |  N
| New feature? | Y
| Automated tests included? | N
| Related user documentation PR URL | N 
| Related developer documentation PR URL | N 
| Issues addressed (#s or URLs) | #4977
| BC breaks? |  N
| Deprecations? |  N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description: Adds a filter which gathers all of the leads specified in the "do-not-contact" table for email.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. Create new segement
2.  Add new "Unsubscribe - All" filter
3. Save Segement
4. run segment cron job
5. Segment should be populated with all email related do not contacts.

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by npracht** [comment]
@florentpetitjean can you test that please --> https://mautibox.com/7495

**Comment by florentpetitjean** [comment]
tested and it works on mautibox

**Comment by drimlike** [comment]
hello, any news on the merging of this feature please? Looks like it's ready to go.

**Comment by RCheesley** [comment]
@drimlike this needs one more person to test. @heathdutton it seems Mautibox doesn't like this PR, is there a problem with it?

**Comment by heathdutton** [comment]
> @drimlike this needs one more person to test. @heathdutton it seems Mautibox doesn't like this PR, is there a problem with it?

There was a merge conflict, but it was really minor so I resolved it for @th-markus (hope that's cool)

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@th-markus do you need any help with rebasing this pull request? it would be great to get this into a future release of Mautic if we can!

**Comment by RCheesley** [comment]
So I was looking into this and I noticed that we already have the ability to filter out in segments those who have unsubscribed by channel and manually, I think therefore that this PR is no longer relevant as I don't see that it has any functionality we don't already have?

screenshot-mautibox com-2020 05 16-13_57_22

Feel free to re-open this PR if you feel otherwise

**Comment by pjrobertson** [comment]
Incase any others come across this post and view @RCheesley's post as a solution, I would just like to add:

The way the 'filter' function works is to filter *all* contacts in the Mautic database, and add/remove them from the selected segment. I had the understanding that it would only filter existing contacts in the current segment to remove them from the segment. I just inadvertently added 70k subscribers to a wrong segment.

It seems that mautic doesn't allow you to choose a filter:

"Segment" - "Contains" - "<Current Segment Name>"

So the best I could come up with is to use a filter setup of:

"Unsubscribed - Email" - "Equals" - "No"

*and* 

"Campaign Membership" - "Including" - "<Name of campaign for this segment>" (assuming you have a campaign set up

Screenshot 2021-05-28 at 16 53 01

**Pull request closed without merging**
