### PR TITLE
Revert "Support for PHP 7.2"

### PR DESCRIPTION
**Pull request by Woeler**
Reverts mautic/mautic#6848

### CODE REVIEW

**Comment by kuzmany** [comment]
That means 7.2 is not comming to Mautic 2.15?
Just asking because Pipedrive PR with 7.2 need a lot of changes, now I should just revert to before PHP 7.2 was merged

**Comment by Woeler** [comment]
There are still problems, so no, currently there is no plan to include it.

**Comment by alanhartless** [comment]
We need to have that PR recreated so we can figure out what was going on with it. I'm not sure it was so much an issue with Mautic/PHP itself versus a Travis configuration issue.

**Comment by Woeler** [comment]
@alanhartless The extremely odd thing is just that the PR tests passed every time, and then when merged, staging kept failing. The PR is tested with the updated Travis config as it takes the yaml in the pr. All in all extremely weird behavior.

**Pull request merged**
