### PR TITLE
Fix the column type not match with the mysql type #562

### PR DESCRIPTION
**Pull request by kithokit**
Quick fix for the column type isn't matched with the one on custom field

### CODE REVIEW

**Comment by escopecz** [comment]
Hi @kithokit, thaks for the PR! Could you please document the problem this PR is solving in more depth? Steps to recreate the issue would be nice so we could test it and confirm this PR solves the problem.

**Comment by kithokit** [comment]
Problem, longtext fields is created in mysql database when we choose other type, like boolean, int.

Steps to recreate:
Manage New field, add new field , e.g. boolean. Check mysql leads tables, new column is created but in long text type.

Fix: the column type match with the type we created.

**Comment by escopecz** [comment]
I created float, number, date, datetime, time, boolean Lead Fields. But when I try to open a field detail, I get this error:
```
500 Internal Server Error - Could not load type "float" 
```
```
vendor/symfony/form/Symfony/Component/Form/FormRegistry.php (line #87):
vendor/symfony/form/Symfony/Component/Form/FormFactory.php (line #82): at Symfony\Component\Form\FormRegistry -> getType ( 'float' )
vendor/symfony/form/Symfony/Component/Form/FormBuilder.php (line #106): at Symfony\Component\Form\FormFactory -> createNamedBuilder ( 'floatfield', 'float', null, array('required' => false, 'label' => 'Float field', 'label_attr' => array('class' => 'control-label'), 'attr' => array('class' => 'form-control'), 'data' => null, 'mapped' => false, 'constraints' => array()) )
vendor/symfony/form/Symfony/Component/Form/FormBuilder.php (line #268): at Symfony\Component\Form\FormBuilder -> create ( 'floatfield', 'float', array('required' => false, 'label' => 'Float field', 'label_attr' => array('class' => 'control-label'), 'attr' => array('class' => 'form-control'), 'data' => null, 'mapped' => false, 'constraints' => array()) )
vendor/symfony/form/Symfony/Component/Form/FormBuilder.php (line #216): at Symfony\Component\Form\FormBuilder -> resolveChildren ( )
vendor/symfony/form/Symfony/Component/Form/FormFactory.php (line #39): at Symfony\Component\Form\FormBuilder -> getForm ( )
app/bundles/LeadBundle/Model/LeadModel.php (line #103): at Symfony\Component\Form\FormFactory -> create ( 'lead', object(Lead), array('fields' => object(Paginator), 'action' => '/mautic-github/index_dev.php/s/leads/new') )
app/bundles/LeadBundle/Controller/LeadController.php (line #448): at Mautic\LeadBundle\Model\LeadModel -> createForm ( object(Lead), object(FormFactory), '/mautic-github/index_dev.php/s/leads/new', array('fields' => object(Paginator)) )
app/bundles/CoreBundle/Controller/CommonController.php (line #303): at Mautic\LeadBundle\Controller\LeadController -> newAction ( '0', '' )
at Mautic\CoreBundle\Controller\CommonController -> executeAction ( 'new', '0', '0', '' )
app/bootstrap.php.cache (line #3001): at call_user_func_array ( array(object(LeadController), 'executeAction'), array('new', '0', '0', '') )
app/bootstrap.php.cache (line #2963): at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '1' )
app/bootstrap.php.cache (line #3112): at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '1', true )
app/bootstrap.php.cache (line #2361): at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel -> handle ( object(Request), '1', true )
app/AppKernel.php (line #115): at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), '1', true )
index_dev.php (line #38): at AppKernel -> handle ( object(Request) )
```
I think this is caused because Doctrine doesn't have the float type?
http://symfony.com/doc/current/reference/forms/types.html

If I remove the float field, the lead detail works, but when I fill the fields with random data and try to save I get
```
500 Internal Server Error - An exception occurred while executing 'UPDATE mau_leads SET numberfield = ?, numberfield2 = ?, numberfield3 = ?, datefield = ?, datetimefield = ?, timefield = ?, booleanfield = ?, facebook1 = ? WHERE id = ?' with params ["2342", "2342", "2342", "2015-07-08", "324223423", "19:00", "0", "", 96]: SQLSTATE[22007]: Invalid datetime format: 7 ERROR: invalid input syntax for type timestamp: "19:00" 
```

**Comment by mbabker** [comment]
Doctrine does have a float field - http://doctrine-dbal.readthedocs.org/en/latest/reference/types.html#float

If you're converting that to a Symfony form field, you'll need to use the number type.

**Comment by escopecz** [comment]
Thanks for correction, Michael. I'm thinking if this type specification is even good for custom fields. For example the date fields. If a lead submits some weird date format (and validation doesn't catch that) it will cause 500 error. If it will be simple text type, the date will save without problem. What would you recommend?

**Comment by mbabker** [comment]
Since forms aren't using ORM, it's a bit trickier as you'd have to make sure the date is in a valid database format based on the field type (and date, time, and datetime are all a bit different).  Using a text field bypasses that, but it weakens data integrity just a bit.  I don't think there's a "good" answer here, ultimately it's whatever is going to be most efficient for the code.

**Comment by alanhartless** [comment]
@escopecz With the date and not knowing the format submitted, could we check that the field is a date upon submission then run it through DateTimeHelper? If the format doesn't match up with what \DateTime expects, it'll use strtotime to convert it then format it.  Of course there's always a risk it'll be incorrectly converted but it might be the best we can do unless we force a specific format like we do email.

**Comment by escopecz** [comment]
Alan, yes, that would be the way to go. To force a date format. Date format is different in each country, so we would have to make it configurable. I know about big troubles with format like 4/7/15. In Czech we take it as June 4th. In US you'd take it as April 7th. Could we use some date selector JS library?

Also, how to handle a number field which gets a string value? Just convert it to integer?

**Comment by dbhurley** [comment]
Closing due to implementation in #1551

**Pull request closed without merging**
