### PR TITLE
[UX] Create a tooltip for "Custom CSS" to make sure the user does not include <style> HTML tags

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Perhaps this modification is a little more on the side of excessive security but it can be positive to avoid problems with items being deconfigured when put live.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Channels > Focus items
3. Create a new 
4. Open the Builder > Content
5. Look at the Custom CSS label, it has a tooltip

image

### CODE REVIEW

**Review by Mike-Dropsolid — CHANGES_REQUESTED** [review]
I would go with 'without <style> tags'

**Review by LordRembo — CHANGES_REQUESTED** [review]
Agreed with Mike, '<style> tags' is making it extra clear and it's concise

**Comment by andersonjeccel** [comment]
@LordRembo @Mike-Dropsolid I had the same problem on the other PR, HTML tags become part of HTML code instead of showing on the tooltip. We need to find if there's a specific escaping method

**Comment by LordRembo** [comment]
@andersonjeccel Have you tried converting the triangular brackets into html entities? I believe that should fix it.
https://www.toptal.com/designers/htmlarrows/math/

**Review by kuzmany — DISMISSED** [review]

**Comment by andersonjeccel** [comment]
@LordRembo Tried all the following:

```
mautic.focus.form.custom.css.help = "Enter your custom styles without &lt;style&gt; tags"
mautic.focus.form.custom.css.help = "Enter your custom styles without &#60;style&#62; tags"
mautic.focus.form.custom.css.help = "Enter your custom styles without \003Cstyle\003E tags"
mautic.focus.form.custom.css.help = "Enter your custom styles without <style> tags"
mautic.focus.form.custom.css.help = "Enter your custom styles without &#x3c;style&#x3e; tags"
mautic.focus.form.custom.css.help = "Enter your custom styles without \\u003Cstyle\\u003E tags"
mautic.focus.form.custom.css.help = "Enter your custom styles without '<style>' tags"
mautic.focus.form.custom.css.help = "Enter your custom styles without "<style>" tags"
mautic.focus.form.custom.css.help = 'Enter your custom styles without "<style>" tags'
mautic.focus.form.custom.css.help = "Enter your custom styles without \<style\> tags"
```

Absolutely no success.

**Comment by code5rick** [comment]
This way worked somehow:
`mautic.focus.form.custom.css.help = "Enter your custom styles without the <&#8239;style&#8239;> tag"`

image

----

_Stackoverflow @ https://stackoverflow.com/questions/11392312/zero-width-non-breaking-space_
U+202F Narrow No-Break Space `&#8239;` or `&nnbsp;`) used to separate a suffix from a word stem without indicating a word boundary. Approximately 1/3 the representative space of a normal space though it may vary by font.

**Comment by andersonjeccel** [comment]
@code5rick Thanks!

**Comment by LordRembo** [comment]
If @kuzmany or @code5rick can confirm it works as inteded, I think we're good to mark this as done.

**Review by escopecz — CHANGES_REQUESTED** [review]
This is failing a unit test somehow.

**Comment by andersonjeccel** [comment]
@escopecz Is it related to the PR?

**Comment by escopecz** [comment]
Must be. It's not failing like this on 5.x nor on other PRs.

**Comment by LordRembo** [comment]
@escopecz These are database tests that are failing. Could it be the encoding of the stuff Anderson is trying to add in translation strings? `<&#8239;style&#8239;>`

**Comment by escopecz** [comment]
Yes, it may be related to the encoded HTML element. I don't have time to dig deeper.

**Comment by andersonjeccel** [comment]
@LordRembo The same solution was applied in this PR, no errors
https://github.com/mautic/mautic/pull/13436/files

**Comment by LordRembo** [comment]
@mallezie Maybe you have some idea why these db tests may be failing?

**Comment by mallezie** [comment]
I honestly have no idea. Seeing that there are different test failures on 8.0 mariadb and 8.2 mariadb, my first thing would be to rerun the tests, sounds like some unrelated failure IMO (especially checking that the specific tests which are failing, are really far unrelated AFAICT).

**Comment by andersonjeccel** [comment]
@escopecz Should we update the branch and rerun the tests since the same encoded value is being used on another already merged PR with no errors?

**Comment by escopecz** [comment]
I merged the 5.x to this PR. But I'm not sure it will help. Some developer will have to check why the tests are really failing.

**Comment by mallezie** [comment]
Strange thing is, merging 5.x back was succesfull. Might be a retest would have been succesfull as well.

**Review by escopecz — APPROVED** [review]
Works well:
Screenshot 2024-03-19 at 14 55 56

**Pull request merged**
