### PR TITLE
Bug lead graph report with company filters

### PR DESCRIPTION
**Pull request by tomekkowalczyk**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:

When we generate the report using the company filter, we get an error that the comp column is not known.
Conditions are included but no join in the SQL query.

`mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT DATE_FORMAT(l.date_added, '%Y-%m') AS date, COUNT(*) AS count FROM leads l INNER JOIN lead_lists_leads s ON s.lead_id = l.id AND s.manually_removed = 0 WHERE (s.date_added IS NULL OR (s.date_added BETWEEN ? AND ?)) AND ((s.leadlist_id = ?) OR (comp.id = 2)) GROUP BY DATE_FORMAT(l.date_added, '%Y-%m') ORDER BY DATE_FORMAT(l.date_added, '%Y-%m') ASC LIMIT 5' with params ["2020-08-31 22:00:00", "2021-01-05 08:55:16", "2"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'comp.id'`

Anyone have any idea where it will be best to join the company table?
```
$qb->leftJoin('l', MAUTIC_TABLE_PREFIX.'companies_leads', 'companies_lead', 'l.id = companies_lead.lead_id');
$qb->leftJoin('companies_lead', MAUTIC_TABLE_PREFIX.'companies', 'comp', 'companies_lead.company_id = comp.id');
```
There is no information about the company ID in the SQL query parameters
image
image

### CODE REVIEW

**Comment by npracht** [comment]
Hi @tomekkowalczyk ! Thanks a lot for your contribution.
I just tested the PR and I still have an issue:

Capture d’écran 2021-01-20 à 09 20 49
Capture d’écran 2021-01-20 à 09 20 55


```
 500 Internal Server Error - An exception occurred while executing 'SELECT count(*) FROM (SELECT `l`.`id` AS id, `l`.`email` AS email FROM 9560_leads l WHERE (l.date_added IS NULL OR (l.date_added BETWEEN ? AND ?)) AND ((comp.id = 1) AND (comp.companycity = ?))) c' with params ["2020-12-20 00:00:00", "2021-01-20 08:19:54", "Annecy"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'comp.id' in 'where clause' 
```

```
/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60 at
/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:166 at Doctrine\DBAL\Driver\AbstractMySQLDriver -> convertException ( 'An exception occurred while executing 'SELECT count(*) FROM (SELECT `l`.`id` AS id, `l`.`email` AS email FROM 9560_leads l WHERE (l.date_added IS NULL OR (l.date_added BETWEEN ? AND ?)) AND ((comp.id = 1) AND (comp.companycity = ?))) c' with params ["2020-12-20 00:00:00", "2021-01-20 08:20:58", "Annecy"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'comp.id' in 'where clause'', object(PDOException) )
/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:146 at Doctrine\DBAL\DBALException :: wrapException ( object(Driver), object(PDOException), 'An exception occurred while executing 'SELECT count(*) FROM (SELECT `l`.`id` AS id, `l`.`email` AS email FROM 9560_leads l WHERE (l.date_added IS NULL OR (l.date_added BETWEEN ? AND ?)) AND ((comp.id = 1) AND (comp.companycity = ?))) c' with params ["2020-12-20 00:00:00", "2021-01-20 08:20:58", "Annecy"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'comp.id' in 'where clause'' )
/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:912 at Doctrine\DBAL\DBALException :: driverExceptionDuringQuery ( object(Driver), object(PDOException), 'SELECT count(*) FROM (SELECT `l`.`id` AS id, `l`.`email` AS email FROM 9560_leads l WHERE (l.date_added IS NULL OR (l.date_added BETWEEN ? AND ?)) AND ((comp.id = 1) AND (comp.companycity = ?))) c', array('2020-12-20 00:00:00', '2021-01-20 08:20:58', 'Annecy') )
/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206 at Doctrine\DBAL\Connection -> executeQuery ( 'SELECT count(*) FROM (SELECT `l`.`id` AS id, `l`.`email` AS email FROM 9560_leads l WHERE (l.date_added IS NULL OR (l.date_added BETWEEN ? AND ?)) AND ((comp.id = 1) AND (comp.companycity = ?))) c', array('2020-12-20 00:00:00', '2021-01-20 08:20:58', 'Annecy'), array('2', '2', '2') )
/app/bundles/ReportBundle/Model/ReportModel.php:759 at Doctrine\DBAL\Query\QueryBuilder -> execute ( )
/app/bundles/ReportBundle/Model/ReportModel.php:638 at Mautic\ReportBundle\Model\ReportModel -> getTotalCount ( object(QueryBuilder), array('count_query' => 'SELECT count(*) FROM (SELECT `l`.`id` AS id, `l`.`email` AS email FROM 9560_leads l WHERE (l.date_added IS NULL OR (l.date_added BETWEEN :dateFrom AND :dateTo)) AND ((comp.id = 1) AND (comp.companycity = :i3ccompcompanycity))) c') )
/app/bundles/ReportBundle/Controller/ReportController.php:661 at Mautic\ReportBundle\Model\ReportModel -> getReportData ( object(Report), object(FormFactory), array('dynamicFilters' => array(), 'paginate' => true, 'reportPage' => '1', 'dateFrom' => object(DateTime), 'dateTo' => object(DateTime), 'translator' => object(DataCollectorTranslator), 'chartQuery' => object(ChartQuery)) )
/vendor/symfony/http-kernel/HttpKernel.php:151 at Mautic\ReportBundle\Controller\ReportController -> viewAction ( '11', '1' )
/vendor/symfony/http-kernel/HttpKernel.php:68 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '2' )
/vendor/symfony/framework-bundle/Controller/ControllerTrait.php:108 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '2' )
/app/bundles/CoreBundle/Controller/CommonController.php:368 at Symfony\Bundle\FrameworkBundle\Controller\Controller -> forward ( 'MauticReportBundle:Report:view', array('objectId' => '11', '_forwarded' => object(ParameterBag), '_controller' => 'MauticReportBundle:Report:view'), array('ignoreAjax' => true, 'request' => object(Request), 'subrequest' => true) )
/app/bundles/CoreBundle/Controller/CommonController.php:298 at Mautic\CoreBundle\Controller\CommonController -> ajaxAction ( array('returnUrl' => '/9560/s/reports/view/11', 'viewParameters' => array('objectId' => '11'), 'contentTemplate' => 'MauticReportBundle:Report:view', 'passthroughVars' => array('activeLink' => 'mautic_report_index', 'mauticContent' => 'report'), 'forwardController' => true) )
/app/bundles/ReportBundle/Controller/ReportController.php:407 at Mautic\CoreBundle\Controller\CommonController -> postActionRedirect ( array('returnUrl' => '/9560/s/reports/view/11', 'viewParameters' => array('objectId' => '11'), 'contentTemplate' => 'MauticReportBundle:Report:view', 'passthroughVars' => array('activeLink' => 'mautic_report_index', 'mauticContent' => 'report'), 'forwardController' => true) )
/app/bundles/CoreBundle/Controller/CommonController.php:456 at Mautic\ReportBundle\Controller\ReportController -> editAction ( '11', '' )
/vendor/symfony/http-kernel/HttpKernel.php:151 at Mautic\CoreBundle\Controller\CommonController -> executeAction ( 'edit', '11', '0', '' )
/vendor/symfony/http-kernel/HttpKernel.php:68 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '1' )
/vendor/symfony/http-kernel/Kernel.php:200 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '1', true )
/app/AppKernel.php:104 at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), '1', true )
/app/middlewares/CORSMiddleware.php:91 at AppKernel -> handle ( object(Request), '1', true )
/app/middlewares/CatchExceptionMiddleware.php:43 at Mautic\Middleware\CORSMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/Dev/IpRestrictMiddleware.php:64 at Mautic\Middleware\CatchExceptionMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/VersionCheckMiddleware.php:67 at Mautic\Middleware\Dev\IpRestrictMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/TrustMiddleware.php:51 at Mautic\Middleware\VersionCheckMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23 at Mautic\Middleware\TrustMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/run/src/Stack/run.php:13 at Stack\StackedHttpKernel -> handle ( object(Request) )
/index_dev.php:25 at Stack\run ( object(StackedHttpKernel) )
/index.php:6 at require_once ( '/var/app/current/code/pulls/9560/index_dev.php' )

```

**Review by npracht — CHANGES_REQUESTED** [review]
Doesn't fix issue.

**Comment by tomekkowalczyk** [comment]
> Doesn't fix issue.



> Hi @tomekkowalczyk ! Thanks a lot for your contribution.
> I just tested the PR and I still have an issue:
> 
> Capture d’écran 2021-01-20 à 09 20 49
> 
> Capture d’écran 2021-01-20 à 09 20 55
> 
> ```
>  500 Internal Server Error - An exception occurred while executing 'SELECT count(*) FROM (SELECT `l`.`id` AS id, `l`.`email` AS email FROM 9560_leads l WHERE (l.date_added IS NULL OR (l.date_added BETWEEN ? AND ?)) AND ((comp.id = 1) AND (comp.companycity = ?))) c' with params ["2020-12-20 00:00:00", "2021-01-20 08:19:54", "Annecy"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'comp.id' in 'where clause' 
> ```
> 
> ```
> /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60 at
> /vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:166 at Doctrine\DBAL\Driver\AbstractMySQLDriver -> convertException ( 'An exception occurred while executing 'SELECT count(*) FROM (SELECT `l`.`id` AS id, `l`.`email` AS email FROM 9560_leads l WHERE (l.date_added IS NULL OR (l.date_added BETWEEN ? AND ?)) AND ((comp.id = 1) AND (comp.companycity = ?))) c' with params ["2020-12-20 00:00:00", "2021-01-20 08:20:58", "Annecy"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'comp.id' in 'where clause'', object(PDOException) )
> /vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:146 at Doctrine\DBAL\DBALException :: wrapException ( object(Driver), object(PDOException), 'An exception occurred while executing 'SELECT count(*) FROM (SELECT `l`.`id` AS id, `l`.`email` AS email FROM 9560_leads l WHERE (l.date_added IS NULL OR (l.date_added BETWEEN ? AND ?)) AND ((comp.id = 1) AND (comp.companycity = ?))) c' with params ["2020-12-20 00:00:00", "2021-01-20 08:20:58", "Annecy"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'comp.id' in 'where clause'' )
> /vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:912 at Doctrine\DBAL\DBALException :: driverExceptionDuringQuery ( object(Driver), object(PDOException), 'SELECT count(*) FROM (SELECT `l`.`id` AS id, `l`.`email` AS email FROM 9560_leads l WHERE (l.date_added IS NULL OR (l.date_added BETWEEN ? AND ?)) AND ((comp.id = 1) AND (comp.companycity = ?))) c', array('2020-12-20 00:00:00', '2021-01-20 08:20:58', 'Annecy') )
> /vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206 at Doctrine\DBAL\Connection -> executeQuery ( 'SELECT count(*) FROM (SELECT `l`.`id` AS id, `l`.`email` AS email FROM 9560_leads l WHERE (l.date_added IS NULL OR (l.date_added BETWEEN ? AND ?)) AND ((comp.id = 1) AND (comp.companycity = ?))) c', array('2020-12-20 00:00:00', '2021-01-20 08:20:58', 'Annecy'), array('2', '2', '2') )
> /app/bundles/ReportBundle/Model/ReportModel.php:759 at Doctrine\DBAL\Query\QueryBuilder -> execute ( )
> /app/bundles/ReportBundle/Model/ReportModel.php:638 at Mautic\ReportBundle\Model\ReportModel -> getTotalCount ( object(QueryBuilder), array('count_query' => 'SELECT count(*) FROM (SELECT `l`.`id` AS id, `l`.`email` AS email FROM 9560_leads l WHERE (l.date_added IS NULL OR (l.date_added BETWEEN :dateFrom AND :dateTo)) AND ((comp.id = 1) AND (comp.companycity = :i3ccompcompanycity))) c') )
> /app/bundles/ReportBundle/Controller/ReportController.php:661 at Mautic\ReportBundle\Model\ReportModel -> getReportData ( object(Report), object(FormFactory), array('dynamicFilters' => array(), 'paginate' => true, 'reportPage' => '1', 'dateFrom' => object(DateTime), 'dateTo' => object(DateTime), 'translator' => object(DataCollectorTranslator), 'chartQuery' => object(ChartQuery)) )
> /vendor/symfony/http-kernel/HttpKernel.php:151 at Mautic\ReportBundle\Controller\ReportController -> viewAction ( '11', '1' )
> /vendor/symfony/http-kernel/HttpKernel.php:68 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '2' )
> /vendor/symfony/framework-bundle/Controller/ControllerTrait.php:108 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '2' )
> /app/bundles/CoreBundle/Controller/CommonController.php:368 at Symfony\Bundle\FrameworkBundle\Controller\Controller -> forward ( 'MauticReportBundle:Report:view', array('objectId' => '11', '_forwarded' => object(ParameterBag), '_controller' => 'MauticReportBundle:Report:view'), array('ignoreAjax' => true, 'request' => object(Request), 'subrequest' => true) )
> /app/bundles/CoreBundle/Controller/CommonController.php:298 at Mautic\CoreBundle\Controller\CommonController -> ajaxAction ( array('returnUrl' => '/9560/s/reports/view/11', 'viewParameters' => array('objectId' => '11'), 'contentTemplate' => 'MauticReportBundle:Report:view', 'passthroughVars' => array('activeLink' => 'mautic_report_index', 'mauticContent' => 'report'), 'forwardController' => true) )
> /app/bundles/ReportBundle/Controller/ReportController.php:407 at Mautic\CoreBundle\Controller\CommonController -> postActionRedirect ( array('returnUrl' => '/9560/s/reports/view/11', 'viewParameters' => array('objectId' => '11'), 'contentTemplate' => 'MauticReportBundle:Report:view', 'passthroughVars' => array('activeLink' => 'mautic_report_index', 'mauticContent' => 'report'), 'forwardController' => true) )
> /app/bundles/CoreBundle/Controller/CommonController.php:456 at Mautic\ReportBundle\Controller\ReportController -> editAction ( '11', '' )
> /vendor/symfony/http-kernel/HttpKernel.php:151 at Mautic\CoreBundle\Controller\CommonController -> executeAction ( 'edit', '11', '0', '' )
> /vendor/symfony/http-kernel/HttpKernel.php:68 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '1' )
> /vendor/symfony/http-kernel/Kernel.php:200 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '1', true )
> /app/AppKernel.php:104 at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), '1', true )
> /app/middlewares/CORSMiddleware.php:91 at AppKernel -> handle ( object(Request), '1', true )
> /app/middlewares/CatchExceptionMiddleware.php:43 at Mautic\Middleware\CORSMiddleware -> handle ( object(Request), '1', true )
> /app/middlewares/Dev/IpRestrictMiddleware.php:64 at Mautic\Middleware\CatchExceptionMiddleware -> handle ( object(Request), '1', true )
> /app/middlewares/VersionCheckMiddleware.php:67 at Mautic\Middleware\Dev\IpRestrictMiddleware -> handle ( object(Request), '1', true )
> /app/middlewares/TrustMiddleware.php:51 at Mautic\Middleware\VersionCheckMiddleware -> handle ( object(Request), '1', true )
> /vendor/stack/builder/src/Stack/StackedHttpKernel.php:23 at Mautic\Middleware\TrustMiddleware -> handle ( object(Request), '1', true )
> /vendor/stack/run/src/Stack/run.php:13 at Stack\StackedHttpKernel -> handle ( object(Request) )
> /index_dev.php:25 at Stack\run ( object(StackedHttpKernel) )
> /index.php:6 at require_once ( '/var/app/current/code/pulls/9560/index_dev.php' )
> ```

**Comment by tomekkowalczyk** [comment]
@npracht I repeated your example and it works fine for me. You could check the example again (maybe dev cache)

**Comment by kuzmany** [comment]
Already exists method addCompanyLeftJoin which should cover your case and pretend the join table if don't need it:

https://github.com/mautic/mautic/blob/features/app/bundles/ReportBundle/Event/ReportGeneratorEvent.php#L324

**Review by kuzmany — DISMISSED** [review]
Works for me 👍

**Review by kuzmany — APPROVED** [review]

**Review by npracht — APPROVED** [review]
👍🏽

**Pull request merged**
