### PR TITLE
[WIP] M3: Fix tests on 3.x branch

### PR DESCRIPTION
**Pull request by dongilbert**
This PR is full of various fixes to get the 3.x branch in its current state able to run the unit tests.

### CODE REVIEW

**Comment by dongilbert** [comment]
@escopecz Unit tests are at least completing now with these latest changes

**Review by escopecz — APPROVED** [review]
Thanks Don! 👍

**Comment by dongilbert** [comment]
This was still a WIP. I'll create a new PR

**Comment by escopecz** [comment]
Oops, sorry. I saw it in the title but thought you forgot it there. Maybe wait till all bundles will get rid of the deprecated code as you were duplicating some work that is WIP in the M3 board.

**Pull request merged**
