### PR TITLE
[UI] Assign the background color to the token for dark mode support

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

It's already white, but this PR makes the background white using the token --background as [defined by the community here](https://mautic.slack.com/archives/C024XBCQS3Z/p1715439992447739)

Essential to use the token to have the dark mode soon.

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Look at the background, no difference

### CODE REVIEW

**Review by LordRembo — APPROVED** [review]
Cool, now that the Token approach is merged, incremental improvements like these are great to have.

**Review by PatrickJenkner — APPROVED** [review]
Works as described 👍

**Comment by andersonjeccel** [comment]
@PatrickJenkner Thanks for testing!

If you'd like to check more UX/UI-related PRs, use [The Best Link](https://github.com/mautic/mautic/pulls?q=is%3Aopen+is%3Apr+author%3Aandersonjeccel+-label%3Ablocked+-is%3Adraft+-label%3Aready-to-commit+-label%3Apending-feedback) as starting point 💡

**Review by Bastian2718 — APPROVED** [review]
Looks white 👍

**Comment by RCheesley** [comment]
@all-contributors please add @Bastian2718 for userTesting

**Review by RCheesley — APPROVED** [review]
All good, can't wait to have dark mode! 🕶️

**Pull request merged**
