### PR TITLE
Fix First/Last Touch Attribution

### PR DESCRIPTION
**Pull request by Hadamcik**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? |N
| Related user documentation PR URL | -
| Related developer documentation PR URL | -
| Issues addressed (#s or URLs) | [#5256](https://github.com/mautic/mautic/issues/5256)
| BC breaks? | N
| Deprecations? | N

[//]: # ( Required: )
#### Description:
Fixes reports for first and last touch attribution. Multi was alright, but got touched anyway.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. See issue

#### Steps to test this PR:
1. See issue

### CODE REVIEW

**Comment by javjim-mautic** [comment]
Sorry could you elaborate a little on how to test bug and fix?

**Comment by javjim-mautic** [comment]
Getting this error @Dreiser Base table or view not found:  1146 Table 'clean.campaign_lead_event_log'

I think its missing the prefix in the SQL in a couple places

could you verify or help me understand if I am doing something wrong?

**Comment by Dreiser** [comment]
You are right, there was table_prefix missing. Should be fixed

**Comment by javjim-mautic** [comment]
The error is not there anymore but same , I cant see any data

**Comment by alanhartless** [comment]
@javjim-mautic @escopecz The attribution reports are based on campaign decisions (when a contact took action or had a touchpoint). The contact needs to have an attribution date and attribution (dollar value) in their contact profile for the report to pick them up. First touch is when the first decision took place on or before the attribution date. The last touch is the last decision. Multi lists all the decisions.

**Comment by javjim-mautic** [comment]
Gettint the same error as Escopecz

**Comment by mleffler** [comment]
@Dreiser Have you looked at this?

**Comment by mleffler** [comment]
Assigning to Alan to look at next steps and help.

**Comment by alanhartless** [comment]
Putting this one on hold as I don't think there was a bug in the associated issue rather just an educational issue. This changes behavior of how attribution works in Mautic and has the issue noted by John and Javier. We may just close this if confirmed there wasn't an issue to begin with.

**Comment by zaharovrd** [comment]
Hi all. I send data via the API: amount and date of attribution, but I can’t build a report - empty data is displayed.

**Pull request closed without merging**
