### PR TITLE
Category controller code improvements

### PR DESCRIPTION
**Pull request by dadarya0**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features"
| Bug fix?                               | no
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      |
| Related developer documentation PR URL |
| Issue(s) addressed                     | 

#### Description:

This PR fixes the same issue that was already fixed in https://github.com/mautic/mautic/pull/8800. So it might seem useless. But it brings several improvements from the code perspective:
1. It removes duplicate lines.
2. It checks the existence of `'inForm'` key/value in a safer way.
3. It adds a functional test.

#### Steps to test this PR:
1. Make sure that creating a new category within creating a new form is working properly.

### CODE REVIEW

**Review by npracht — COMMENTED** [review]
Hi @dadarya0 !
I couldn't reproduce the issue (generating error) when creating a new form and category at the same time.

**Comment by fedys** [comment]
Hi @npracht,

I updated the PR's name/description as it wasn't clear. Can you please re-evaluate the PR?

**Review by npracht — APPROVED** [review]
Ok for me creating categories while creating a form still works.
I'd say now it just needs a code review, cc @kuzmany and @mohit-rocks :)

**Review by kuzmany — APPROVED** [review]
Code looks good

**Review by mohit-rocks — APPROVED** [review]
I'll merge it after the current pipeline passes.
I've updated the code with features branch.
Thanks @dadarya0

**Pull request merged**
