### PR TITLE
grapejs and ckeditor update

### PR DESCRIPTION
**Pull request by daniellord32**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ] no breaking changes will work with v4 and v5 without issue.
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Fixes a few issues such as image resizing on paste to respect the container it is being pasted in.
copy paste of text was moving the page down on each paste this also contains the fix for that,
upgraded the use of ckeditor to latest version, we also use typescript to load it into grapejs.

We also added a file manager so help with searching for assets

credit for this goes to @paulRose

#### Steps to test this PR:
1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Launch the page builder and this PR will fix a copy paste issue that we have seen where pasting caused the page to move itself down to the bottom of the view.
3. Code mode should be working again.
4. ckeditor will be upgraded and should work as expected.

### CODE REVIEW

**Comment by daniellord32** [comment]
@escopecz Here is that PR take a look, i'll try to answer any questions you have

**Comment by escopecz** [comment]
Wow, this is massive. I'm doing the opposite thing at the moment. Moving all hard-coded JS libraries out to be installable via NPM. See https://github.com/mautic/mautic/pull/12240

Is there any chance the size of this can be reduced? It looks like there are even different builds of the same file included multiple times.

Also, check the GitHub Action jobs. It seems that this code is not ready for Mautic 5.

**Comment by daniellord32** [comment]
yeah @escopecz leave it with me ill sort it out

**Comment by daniellord32** [comment]
@mabumusa1 or @escopecz  can this be closed, I've a new improved one coming instead

**Comment by escopecz** [comment]
Sure :)

**Pull request closed without merging**
