### PR TITLE
Remove extraneous periods in SQL in EmailModel.php

### LINKED ISSUE #9377: Invalid SQL query in 3.1.2
The error shows up in the logs as follows:

```
[2020-11-07 19:02:55] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'SELECT count(DISTINCT .ph.lead_id) as click_count, cs.leadlist_id FROM channel_url_trackables cut INNER JOIN page_hits ph ON ph.redirect_id = cut.redirect_id AND ph.source = cut.channel AND ph.source_id = cut.channel_id INNER JOIN lead_lists_leads cs ON cs.lead_id = ph.lead_id WHERE (cut.channel = ?) AND (cut.channel_id IN (2)) AND (cs.leadlist_id IN (2)) AND (ph.date_hit BETWEEN ? AND ?) GROUP BY cs.leadlist_id' with params ["email", "2020-10-07 00:00:00", "2020-11-07 19:02:55"]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.ph.lead_id) as click_count, cs.leadlist_id FROM channel_url_trackables cut INNE' at line 1" at /var/www/luxuriant.software/html/MAU/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 79 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'SELECT count(DISTINCT .ph.lead_id) as click_count, cs.leadlist_id FROM channel_url_trackables cut INNER JOIN page_hits ph ON ph.redirect_id = cut.redirect_id AND ph.source = cut.channel AND ph.source_id = cut.channel_id INNER JOIN lead_lists_leads cs ON cs.lead_id = ph.lead_id WHERE (cut.channel = ?) AND (cut.channel_id IN (2)) AND (cs.leadlist_id IN (2)) AND (ph.date_hit BETWEEN ? AND ?) GROUP BY cs.leadlist_id' with params [\"email\", \"2020-10-07 00:00:00\", \"2020-11-07 19:02:55\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.ph.lead_id) as click_count, cs.leadlist_id FROM channel_url_trackables cut INNE' at line 1 at /var/www/luxuriant.software/html/MAU/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:79, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.ph.lead_id) as click_count, cs.leadlist_id FROM channel_url_trackables cut INNE' at line 1 at /var/www/luxuriant.software/html/MAU/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.ph.lead_id) as click_count, cs.leadlist_id FROM channel_url_trackables cut INNE' at line 1 at /var/www/luxuriant.software/html/MAU/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)"} []
```

When properly formatted, the questionable SQL query looks like this:

```
SELECT
  count(DISTINCT.ph.lead_id) as click_count,
  cs.leadlist_id
FROM
  channel_url_trackables cut
  INNER JOIN page_hits ph ON ph.redirect_id = cut.redirect_id
  AND ph.source = cut.channel
  AND ph.source_id = cut.channel_id
  INNER JOIN lead_lists_leads cs ON cs.lead_id = ph.lead_id
WHERE
  (cut.channel = ?)
  AND (cut.channel_id IN (2))
  AND (cs.leadlist_id IN (2))
  AND (
    ph.date_hit BETWEEN ?
    AND ?
  )
GROUP BY
  cs.leadlist_id ' with params ["email", "2020-10-07 00:00:00", "2020-11-07 18:55:26"]
```

Notice the following:

```
  (cut.channel = ?)
```

This happens when accessing an email under Channels > Emails.

### PR DESCRIPTION
**Pull request by mreall**
closes https://github.com/mautic/mautic/issues/9377
 The extra period caused an exception when attempting to render the email charts.

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.2
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | Fixes #9377

#### Description:
Email charts (Channels > Emails) are not displaying because the backend SQL is invalid, resulting in an exception. This PR removes the extraneous period in the 2 SQL statements causing the exception.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Navigate to Channels > Emails and confirm the chart appears.

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Thanks for making the PR @mreall, and for signing the contributors agreement!

I've just changed the base branch as we made the 3.2 release yesterday so we'll be working from the 3.2 branch for bug fixes going forward.

**Comment by npracht** [comment]
@RCheesley does it mean it is already fixed in 3.2 branch ?

**Comment by npracht** [comment]
@mreall i am scared that this issue was fixed in 3.2.0 release by https://github.com/mautic/mautic/pull/9346

You confirm this is the same fix ?

**Comment by RCheesley** [comment]
@npracht it seems so - when I look at the git blame this was fixed in the 3.2.0-RC and therefore is now in the 3.2 branch hence when it prompted to update we now see that there is no file being changed.

Here is the commit that addressed the issue: https://github.com/mautic/mautic/commit/25f54940dc329bc646f3c712c5ea8035ed9cee15

From this PR: https://github.com/mautic/mautic/pull/9346

**Comment by npracht** [comment]
@mreall i am very sorry we didn't see it before. But your issue was solved in latest release. What we have to keep in mind from this experience is that we should always test in latest release to be sure the issue persists.

Nevertheless, thanks a lot for your first contribution, i hope you'll have to opportunity to bring more. If you want to get involved in the Product Team, join the discussion on slack :)

**Comment by mreall** [comment]
@npracht No problem. Just glad it's fixed.

**Pull request closed without merging**
