### PR TITLE
Improve tooltip of scheduled emails

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

Just small improvement to tooltip scheduled emails. Added date **start sending** at and  **stop sending at**

image

image

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create email with Publish at (date/time) in future and go to email lists and check tooltip
3. Create email with Unpublish at (date/time) in past and go to email list and related check tooltip

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Review by StrategieSociali — COMMENTED** [review]
Is just my first test and I hope everything I have done is correct. With "Published on the future" all seem ok, I can see the clock and the correct description. The past doesn't work. Whether I program in the past with published or unpublished, whether I program in the future and wait for the programming time to pass, I get the same result: the email goes in "not published"

**Review by RCheesley — DISMISSED** [review]
Thanks for the nice PR @kuzmany - a small but helpful improvement to the UX.

Confirm that the tooltip is applied with the PR as I would expect:

Emails _ Mautic

**Comment by RCheesley** [comment]
@StrategieSociali thanks for testing! To get these conditions you need to create two emails. In one of them set the publish at date/time in the future. This will be in the 'pending' status.

screenshot-local mautic3-2020 08 15-21_48_33

In the second email (I just cloned the one above in my case!) remove the publish at date, and set the unpublish at date/time to something in the past. This will be in the 'expired' status.

screenshot-local mautic3-2020 08 15-21_50_09

Hope that makes sense - the test instructions could have been clearer!

**Review by dennisameling — APPROVED** [review]
LGTM 👍

**Pull request merged**
