### PR TITLE
fix: disabled row hardcoded bg color

### LINKED ISSUE #14332: Hidden themes aren't readable in the theme table using the dark mode
### Mautic Series

5.2.x series

### Mautic installed version

5.2

### Way of installing

I cloned the Mautic repo (not recommended or supported)

### PHP version

8.3

### What browsers are you seeing the problem on?

Chrome

### What happened?

The hidden themes aren't readable in the table:
Screenshot 2024-12-05 at 14 47 21

### How can we reproduce this issue?

1. Go to your profile and select the dark theme
2. Go to themes.
3. For one theme, select the context menu in the beginning of the row.
4. Click on the hide theme option

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #14332 

## Description

fixes mentioned bug

| Before                                 | After
| -------------------------------------- | ---
|      image                                  | image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Go to your profile and select the dark theme
3. Go to themes.
4. For one theme, select the context menu in the beginning of the row.
5. Click on the hide theme option

### CODE REVIEW

**Comment by andersonjeccel** [comment]
@escopecz is the target branch right the way I created?

**Comment by escopecz** [comment]
@andersonjeccel thanks for the quick fix! Yes, 5.2 is the right branch for bug fixes. Do you also see this?
Screenshot 2024-12-05 at 17 27 28

**Comment by matbcvo** [comment]
I see the same thing as well.

image

**Comment by matbcvo** [comment]
During testing the PR, I noticed that some themes have this "extra option" which doesn't include any text.

image

image

**Review by matbcvo — APPROVED** [review]
Looks good to me, PR tested.

**Comment by andersonjeccel** [comment]
@matbcvo 
- #14240

**Pull request merged**
