### PR TITLE
Fix index names missing prefix

### PR DESCRIPTION
**Pull request by pety-dc**
https://github.com/mautic/mautic/pull/7596

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by pety-dc** [comment]
@dennisameling 
With regards to this conversion (https://github.com/mautic/mautic/pull/7596), please include this hotfix into 2.16.2

**Review by dennisameling — APPROVED** [review]
Approving after testing this DB migration. Understanding this is breaking the 2.16.1 update for all users that have a table prefix configured and custom fields with multiselect options, hence the urgency for this fix and it can't wait until 3.x.

Tested as follows:
- Do a clean installation of 2.16.0. **During the installation process**, set a database table prefix (I did `testing_`)
- Log in to Mautic and go to "Custom Fields" in the menu in the top right corner
- Create a new Custom Field and set the type to **"Select - Multiple"**
- Run `app/console mautic:update:find`
- Run `app/console mautic:update:apply`
- You'll get the following error: `An error occurred while updating the database. Check log for more details.`. The log shows the following:

```
[2020-04-10 13:23:11] mautic.NOTICE: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `testing_leads` CHANGE `multiselect_demo` `multiselect_demo` TEXT':  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'multiselect_demo' used in key specification without a key length (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 while running console command `doctrine:migrations:migrate` [] []
```

- Run `app/console doctrine:migrations:migrate`. You'll get the same error as above.
- Now download the patched migration from this PR and overwrite the one in the `migrations` folder
- Run `app/console doctrine:migrations:migrate` again, migration finishes without errors.
- (bonus) Run `app/console doctrine:migrations:migrate prev` so that Doctrine executes a rollback to the previous version. This ensures that the `down()` function in the database migration also works as expected.

**Review by npracht — APPROVED** [review]

**Comment by dennisameling** [comment]
@pety-dc for next time, please include exact steps on how to test the fix that was provided in the PR, this significantly speeds up testing times for the people testing your PR :+1:

**Comment by pety-dc** [comment]
@dennisameling Sorry, I tried to hurry for this PR to make its way to 2.16.2
Next time I'll try to give more attention to the reproduction steps.

**Pull request merged**
