### PR TITLE
A/B test chart rendering unified

### PR DESCRIPTION
**Pull request by escopecz**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Code improvement
| Automated tests included? | N
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | /
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

This PR only changes how the A/B test chart is rendered. Instead of defining the JS Chart object and configuring it it uses the template that all other charts use. The reason we needed this change was to let subscribers to change the chart data before render. It worked for all charts except this one. Plus, the new code is shorter than the previous one.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create a A/B tested email. Set the goal to be the click through rate.
3. Send the A/B tested email.
4. Open some links in an incognito browser window to get some click stats.
5. The chart renders the same as before.

### CODE REVIEW

**Review by RCheesley — COMMENTED** [review]
I tested this as described, but when I apply the patch I see a large white area above the A/B test data chart in the modal popup, which isn't there before applying.

Before:
screenshot-local mautictest-2019 10 11-09_49_56

After:
screenshot-local mautictest-2019 10 11-09_47_53

It looks like this is due to the following:

```
<div class="col-sm-12">
            <canvas id="abtest-bar-chart" height="300"></canvas>
        </div>
```

**Comment by dennisameling** [comment]
Hi @escopecz, I'm currently looking into PR candidates for 2.16.1 (bug fix release) and not sure if this would qualify as one, as it's not strictly a bug fix. What do you think? Otherwise we could target it for 3.1, for example.

**Comment by escopecz** [comment]
@dennisameling I leave it up to you. It is a bug fix for those who need to modify charts with a plugin for some reason. Nothing critical.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
Looks like this PR needs to be rebased/updated for Mautic 3.x - causes errors when I pull it down into my 3.0.2 instance. @escopecz one for you to take a look at please as it's on a protected branch.

**Comment by RCheesley** [comment]
Bumping to 3.2 due to unresolved conflicts/rebase needed.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by escopecz** [comment]
@RCheesley I did not see any conflicts, but I did the rebase.

**Comment by kuzmany** [comment]
I've seen that same space above of graph 

Tested on Mautibox

https://mautibox.com/7787/s/emails/view/7?daterange%5Bdate_to%5D=Dec%2017%2C%202020&daterange%5Bdate_from%5D=Nov%2017%2C%202020&stats=variant

image

**Comment by RCheesley** [comment]
@escopecz can you look at the issue above?

**Comment by npracht** [comment]
up up @escopecz <3

**Comment by escopecz** [comment]
@RCheesley @kuzmany sorry that it took so long. It's fixed now.
Screen Shot 2021-03-19 at 16 51 47

**Review by kuzmany — APPROVED** [review]
Works as describe 👍 

Maybe this translations issue could be resolved

image

**Comment by RCheesley** [comment]
Awesome - works great but yes I agree - can we fix that language string? Or maybe that is due to the strings not getting pushed up to Transifex on release?

screenshot-mautibox com-2021 03 19-20_47_08

**Comment by escopecz** [comment]
@kuzmany @RCheesley Please do not ask for changes that are not related to the PR. Otherwise we'll never merge it. The language string is not related to the chart and it was broken by Zedno :) https://github.com/mautic/mautic/commit/95deda00a8361edb6d39b9a840b78705b81f7f74

**Comment by RCheesley** [comment]
I was not saying fix it in this PR - I meant let's fix it generally.

**Comment by escopecz** [comment]
Understood, Ruth. I'd ignore CodeCov decrease as it reports decrease in a file that this PR is not touching.

**Pull request merged**
