### PR TITLE
Reset plain text after clone

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
We had the issue with customers who clone emails with plaintext and then wondered why they see some other links in the tracking URLs table. We decided to reset it on Clone. 
Need note: plain text is generated automatically If not exist during the send then It does not decrease send deliverability

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create an email and add plain text
3. Clone the email
4. Check If the plain text was reset

### CODE REVIEW

**Review by PatrickJenkner — APPROVED** [review]
Worked as described when tested

**Review by escopecz — DISMISSED** [review]
The code makes sense 👍

**Comment by escopecz** [comment]
@kuzmany could you please check the error
```
PHP Fatal error:  Cannot declare class Mautic\EmailBundle\Tests\Entity\EmailTest, because the name is already in use in /home/runner/work/mautic/mautic/app/bundles/EmailBundle/Tests/Entity/EmailTest.php on line 10
```
It's preventing this PR to get merged. It must be related with merging [the other email clone PR](https://github.com/mautic/mautic/pull/12784).

**Comment by kuzmany** [comment]
@escopecz fixed

**Pull request merged**
