### PR TITLE
Added support for all emoji sources

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**
This adds support for all emoji sources so hopefully all emoji's are caught.

**Testing**
Setup Twitter integration.  Find a tweet or create a tweet with the emoji \xF3\xBE\x93\xAC or \xF3\xBE\x93\xA6.  Create a lead with that twitter handle and save.  The tweets will be corrupted and refreshing the page will cause an error.  Clear out the social cache for that lead (to get past the error).  Apply the PR and try again.  It should work this time.

### CODE REVIEW

**Comment by drmmr763** [comment]
Note: to test successfully you have to use mysql. postgress doesn't mind the unicode characters at all. 

+ @ Test: reproduced error succesfully and PR fixed
+ Vote +1

**Comment by escopecz** [comment]
I found a Twitter account which tweeted the Russian flag emoji once. Created a lead with that handle and viewed the Social tab in the Lead detail page. I wasn't able to recreate the issue. Does it has to be in last X tweets? I used MySQL.

**Comment by drmmr763** [comment]
easiest thing to do is to copy / paste the emoji into a tweet for your own profile and then discover that profile. 

https://www.facebook.com/photo.php?fbid=10153556008967044

copy and paste from that directly into twitter and you should be able to trigger.

**Comment by escopecz** [comment]
I'm on the latest staging branch using MySQL, cache cleared. I tweeted a test tweet with the emoji from that facebook post and I didn't have any problem with it.
mautictwitteremojitest
I don't have any problem with the tweet after I apply this PR either, so I vote UP :+1:

**Pull request merged**
