### PR TITLE
Feature common leads in different lists

### PR DESCRIPTION
**Pull request by ps92**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

Adds a search command to find contacts that belong to multiple lists. 

#### Steps to test this PR:
1.  Apply PR, place the same contacts in multiple lists and search contacts with `common:{alias1}+{alias2}`

### CODE REVIEW

**Comment by escopecz** [comment]
Does it really work for you guys? It wasn't for me because the search command isn't registered in [getSearchCommands](https://github.com/mautic/mautic/pull/2599/files#diff-3fa38c644457bfa255aabbc8bd7e5291R887)

**Comment by ps92** [comment]
@escopecz Yes, that's new. I didn't see that. I tested it. It works fine now.

**Comment by alanhartless** [comment]
My bad for assuming - I tested the other PR and it worked. :-)

**Comment by ps92** [comment]
@alanhartless Yup, so did I. Thanks to @escopecz!

**Comment by escopecz** [comment]
Looks good now. Thanks for the quick fix! :+1:

**Comment by escopecz** [comment]
Oh, I merged it without documentation. @ps92 could you please write a short paragraph about this feature to the user documentation? https://github.com/mautic/documentation

**Comment by ps92** [comment]
@escopecz Sure, let me understand the things the documentation structure. And I will get back on this soon.

**Pull request merged**
