### PR TITLE
Reusable getStandardColumns method

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [N]
| New feature/enhancement? (use the a.x branch)      | [Y]
| Deprecations?                          | [N]
| BC breaks? (use the c.x branch)        | [N]
| Automated tests included?              | [Y] 
| Related user documentation PR URL      | /
| Related developer documentation PR URL | /
| Issue(s) addressed                     | /

#### Description:

This PR moves ReportBuilderEvent::getStandardColumns into the getStandardColumns class.
This way getStandardColumns method can be reused by different parts of the application.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create any report in Mautic and see if it works.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10898"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
@npracht @kuzmany another requirement for open sourcing the custom objects plugin

**Review by kuzmany — APPROVED** [review]
Looks good. 
Seems like minor refactoring. 
Everything works like before 👍 
Unit tests included 👍

**Review by jos0405 — APPROVED** [review]
The Report builder looks the same, columns and fields are behaving the same. I guess that is expected behaviour.
Approved.

**Review by RCheesley — APPROVED** [review]
All good from this side! 🚀

**Pull request merged**
