### PR TITLE
Fix tracking for unsubscribe landing page

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

The landing page used as the preferences page does not track contact visits. This PR fixed it

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a landing page as a preferences center
3. Send email with set preferences center page for email
4. After receiving the email go to unsubscribe page
5. After PR you should see visits stats on landing pages and hits are increased

image

### CODE REVIEW

**Review by PatrickJenkner — COMMENTED** [review]
Unfortunately, after I clicked the mail and the unsubscribe link in an incognito window, there was no page hit, neither on the page itself nor on the widget.

**Comment by kuzmany** [comment]
@PatrickJenkner did you try it in incognito window? 

It works for me , hits increased
image

**Comment by PatrickJenkner** [comment]
> @PatrickJenkner did you try it in incognito window?

Yes, I tested it with incognito mode. No idea why it isn't working, I could totally be doing something wrong.

**Review by LordRembo — APPROVED** [review]
Can confirm it works, hits are registered

**Review by patrykgruszka — CHANGES_REQUESTED** [review]
The `unsubscribeAction` has been recently updated and there are some conflicts to resolve.

**Review by escopecz — APPROVED** [review]
Code change nicely done, functional test included 👍

**Pull request merged**
