### PR TITLE
[UI] Remove search help from list toolbar

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR removes the old way to display search commands.

image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Contacts > Look at the search bar, no help button

### CODE REVIEW

**Review by abhisekmazumdar — APPROVED** [review]
Checked all the pages that have a filter input box. I can verify that the search help button has been removed from the list toolbar.

**Comment by RCheesley** [comment]
Conflicts to address here and then once the search commands PR is merged this can be brought to readiness!

**Comment by escopecz** [comment]
Shouldn't the search help icons stay and open the new search help modal open on the right section?

**Comment by andersonjeccel** [comment]
@escopecz In fact no, so we can have a general help location as a design pattern (when users want help, they'll know where to find instead of having a different way for each resource)

These search commands are rarely used by experts and customers over the years (and they're heavily developer-centric)... The quick filters I implemented aimed to bring a use case for marketers without depending on documentation to better use Mautic

What exactly from the last reviews aren't you considering as ready-to-commit?

**Comment by Mike-Dropsolid** [comment]
I agree with @escopecz. It would be useful to have them as shortcuts to the help functionality. Especially in a first phase.

**Comment by escopecz** [comment]
> What exactly from the last reviews aren't you considering as ready-to-commit?

I see just 1 approval. There are also conflicts.

**Comment by MojisolaaaO** [comment]
@andersonjeccel  Test Passed. The help button is no longer on the search bar.

**Comment by andersonjeccel** [comment]
@escopecz I want you to feel at least partially happy about this one

look at the feedback I received on the UX/UI form:

> 7/18/2024 18:47:01 [I wanted] The ability to either have a toggle on the campaign (and possible segment) pages that can filter inactive ones, or have the ability to archive them, which would effectively have them in a hidden filter).

they're asking something that already exists (is:published search command), so it makes me think that people rarely use them bc they're highly technical and maybe hard to understand for a marketer

I started addressing this issue adding some heavily focused quick filters

image

they're still not addressing the way marketers wanted to filter... so I'm still thinking and prototyping how to allow them to filter those many search options without cluttering the interface, but certainly it would avoid making a list of code something as quick accessible as a 1-click filter

**Comment by escopecz** [comment]
@andersonjeccel I don't see your response as a reason why the existing help buttons couldn't open the global search help modal. I spent some time that I didn't have to build a demo. Please take a look and tell me if that would be OK instead of removing the help buttons:

https://github.com/mautic/mautic/pull/14185

**Comment by andersonjeccel** [comment]
Following up discussions in:
- https://github.com/mautic/mautic/pull/13889

the main issue I said in my last response is that the search help is there, but people still don't use/like/understand so making it absurdly visible and on top of everywhere is not a real solution

that's why I moved to the dropup, search help will still be available in the help modal

**Comment by RCheesley** [comment]
Hi folks,

I had a chat with @andersonjeccel today about this and related PRs.

I think some of the challenge here is that perhaps the long-term goal for the UX revision of this contextual search hasn't yet been shared fully.

Here's a screencast and screenshot which hopefully makes that a bit clearer:

https://app.screencastify.com/v3/watch/i7DwPm360s71KmQoKClf

screenshot-mautic_ddev_site-2024_11_22-17_00_47

This is the UI we're moving towards (see https://github.com/mautic/mautic/pull/14275), and PRs like this are small steps along the way, so I appreciate sometimes it's not easy to see how it would be an improvement.

I'm in favour of moving forward with this PR as I feel that the next steps will be a much greater improvement.

**Pull request merged**
