### PR TITLE
Fix category type for Marketing messages

### LINKED ISSUE #8516: Category list's type filter defaults to "messages" and does nothing when selected
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
There's a random "messages" in the category type filter dropdown (/s/categories). It does nothing when selected. I assume it's probably something injected by Marketing Messages. 

| Q   | A
| --- | ---
| Mautic version | 2.16, 3.0 beta
| PHP version | 7.3
| Browser | chrome

### Steps to reproduce
1. Go to Categories (/s/categories)
2. Look at the type filter dropdown and it'll default to "messages" instead of "Select."  Changing the type to something else and back causes an empty list. 
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by kuzmany**
Closes #8516
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | yes
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #8516
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
I noticed Marketing messages has bad category type. It was store as 0, we expect messages (as other categories type)
This PR fixed it and try prevent for that situation.
Also migrate all 0 categories type to messages.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1.  Go to categories
2.  Create category with type messages
3.  Go to your database, check categories table and see type is 0.
4. We expect messages

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2.  Create category with type Marketing messages
3.  Go to your database, check categories table and see type is __messages__

### CODE REVIEW

**Comment by npracht** [comment]
I cannot reproduce on M3 branch. But i've found another bug.

**Comment by kuzmany** [comment]
I reproduce it also on M3

image

**Comment by kuzmany** [comment]
Rebased

**Review by npracht — COMMENTED** [review]
👍 using it in production for a while

**Review by RCheesley — DISMISSED** [review]
Nice catch, verified the bug and that applying the patch + migration resolves the problem!

**Comment by RCheesley** [comment]
Closing and re-opening

**Review by RCheesley — DISMISSED** [review]
Review was cancelled due to the rebase for codecov so adding it again :sweat_smile:

**Comment by RCheesley** [comment]
@kuzmany please can you take a look at the travis issue? Thanks!

**Comment by dennisameling** [comment]
Should be fixed now, let's wait for Travis to run

**Review by RCheesley — DISMISSED** [review]

**Review by dennisameling — APPROVED** [review]
Can confirm bundle equals 0 in the database:

image

After applying this PR, new categories with type `message` are created correctly in the database, and after running `bin/console doctrine:migrations:migrate` the existing wrong entries are updated to `messages`. Thanks! 🚀 

RTC since @RCheesley approved before (the formal approval got lost because I just rebased for codecov)

**Pull request merged**
