### PR TITLE
Fix SES Transport

### LINKED ISSUE #8903: Received SES webhook of type 'Notification' but couldn't understand payload
When sending emails through Amazon SES and using Amazon SNS Webhook, some bounces are successfully notified to Mautic, but others don't
 
When testing bounces with Amazon testing address (bounce@simulator.amazonses.com) it works OK.

Apparently there are some types of bounce notifications that generates this waning, and some that works OK

I tried in two different Mautic servers (2.16.2) with the same results. 

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.2.24
| Browser | Google Chrome 83.0.4103.97

### Steps to reproduce
1. Configure Amazon SES and SNS Webhook
2. Send emails to invalid addresses 
 
### Log errors
[2020-06-12 18:14:12] mautic.WARNING: Received SES webhook of type 'Notification' but couldn't understand payload [] []

### LINKED ISSUE #9137: Amazon SES API not working
The more details the better...

Hi,
Amazon API email test works fine, but it's not working for a real mass email.

When email is set to Send Immediately I get and error in the log:
mautic.ERROR: [MAIL ERROR] Token amount (51) is larger than the capacity (14). (send); XXX@XXX.COM, ...

When email is set to Queue I get and error in the console when excuting:
php ./bin/console mautic:emails:send
In AmazonApiTransport.php line 195: Attempted to call an undefined method named "getAttachments" of class "Swift_Message".

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.2.24-0ubuntu0.18.04.6
| Browser | Google Chrome 85.0.4183.83 (Official Build) (64-bit)

### Steps to reproduce
1. Configure Amazon API
2. Create and send a New Segment Email (I used a segment with 630 contacts)
 
### Log errors
mautic.ERROR: [MAIL ERROR] Token amount (51) is larger than the capacity (14). (send); XXX@XXX.COM, ...
In AmazonApiTransport.php line 195: Attempted to call an undefined method named "getAttachments" of class "Swift_Message".

### LINKED ISSUE #9156: Sending Failed- AWS API SES( Using Queue and not "Send Immediately" ) in Mautic 3.1
Mautic Version : 3.1
Php : 7.2
Description:  I tried to send an email using AWS SES API with Queue file system option and got below error:

In AmazonApiTransport.php line 195:                                                                              
  Attempted to call an undefined method named "getAttachments" of class "Swift_Message"

### Steps to reproduce:
1. In configuration change email settings-> service configuration to AWS API. 
2. Change how email should be handled to Queue.
3. Adding  credentials to connect to ses
4. Test connection shows success
5. Send test email-pop  shows as email send
6. Logging into /var/www/html/mautic/bin. 
7. sudo php console mautic:emails:send
    After step 7. it shows the error:
                In AmazonApiTransport.php line 195:                                                                              
  Attempted to call an undefined method named "getAttachments" of class "Swift_Message"

Log errors:  
-    [2020-08-30 17:41:23] mautic.NOTICE: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Swift_Message::getAttachments() (uncaught exception) at /var/www/html/mautic/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonApiTransport.php line 195 while running console command `mautic:emails:send` [] []
-   [2020-08-30 17:41:23] mautic.WARNING: Command `mautic:emails:send` exited with status code 1 [] []

### LINKED ISSUE #9345: Accented characters in mail from field are replaced by � when using Amazon SES API
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

Email from field accented characters are becoming �s when sending through Amazon SES API. The issue is not existing when sending through Amazon SES SMTP.

This is the closest possible cause of the issue I could find on Amazon's documentation:

"If you want to use Unicode characters in the “friendly from” name, you must encode the “friendly from” name using MIME encoded-word syntax, as described in Sending raw email using the Amazon SES API."

and

"To maintain compatibility with older systems, Amazon SES honors the 7-bit ASCII limitation of SMTP as defined in RFC 2821. If you want to send content that contains non-ASCII characters, you must encode those characters into a format that uses 7-bit ASCII characters."

[https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-raw.html](url)

| Q   | A
| --- | ---
| Mautic version | 3.1.2
| PHP version | 7.4.11
| Browser | Chrome 86.0.4240.111

### Steps to reproduce
1. Set up Mautic with Amazon SES API as a mailer
2. Send out an email with accented characters in the "mail from" field, like Áron Lukács or any of the Hungarian chars (öüóőúéáűí)
3. Notice the bad encoding (�ron Luk�cs) when the email is delivered
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          |no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #8903, #9262, #9156, #9137

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Setup your AWS Keys

**Prepare the email to be sent**
1. Create a new email via Channels -> Emails
2. In the subject line make sure to add a token like {contactfield=firstname}
3. In the builder fill it with anything you want, make sure you have multiple tokens like {contactfield=lastname}
4. Close the builder, go to the advanced tab, fill in the form name, from email, reply to address, and bcc  (these are optional but recommended to test all the cases)
5. Click on Auto Generate to create the plain text version of the email
6. Add two custom headers with any values you like 
7. Save this email
8. (optional but recommended), go to assets, upload a file less than 5 MB. 
9. Create another email like the first one but add an attachment to it

**Prepare a campaign**
1. Create two or more contacts 
2. Add them to a segment
3. Create a campaign with the segment you created as a source 
4. Create an action to send an email
5. Create an action send email to the user (with any settings you like)
6. Make the campaign "allow contacts to restart"
7. Keep the campaign unpublished

**Prepare a segment email**
1. Create a segment email with attachment and headers 
2. Attach the segment created above to it 

**Start case "Send Immediately"**
1. Make sure in the configuration that you have selected "Send Immediately"
2. Publish the campaign
3. let the cron job work.
4. You should get emails working as expected
5. On the contacts page, select any contact and send them an email 
6. On the configuration page click on "Test Connection" and "Send Test Email", also fill wrong username and password and check if it works as expected
7. Send the segment email
8. Send a direct email to one of your contacts
9. Create a report and send a scheduled report

**Start case "Queue"**
1. Make sure in the configuration that you have selected "Send Queue"
2. Publish the campaign
3. let the cron job work.
4. You should get emails working as expected
5. On the contacts page, select any contact and send them an email 
6. On the configuration page click on "Test Connection" and "Send Test Email", also fill wrong username and password and check if it works as expected
7. Send the segment email
8. Send a direct email to one of your contacts
9. Create a report and send a scheduled report

If all the above cases work as expected then SES API transport is ready to be merged

### CODE REVIEW

**Comment by mabumusa1** [comment]
This PR solve the existing issue we had in this integration, during the testing I found out that it takes around 11.3 Minutes to send 1000 Emails, which I find super slow given that I can send up to 160 emails/second using my SES account.

@dennisameling @npracht @kuzmany I think we need to give the queuing methods we use another look, right now the messages in the queue are being pickuped one by one which. we need to be able to catch for example 100 emails each loop and keep the connection open with any API and stream out all the messages.

Here what AWS has to say about it 

https://docs.aws.amazon.com/ses/latest/DeveloperGuide/troubleshoot-throughput-problems.html

**Comment by ceefour** [comment]
I tried to apply this directly to 3.1.1 and I got this instead:

```
[2020-10-13 13:56:01] mautic.WARNING: Command `mautic:emails:send` exited with status code 1 [] []
[2020-10-13 13:56:11] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Too few arguments to function Mautic\EmailBundle\Swiftmailer\Transport\AmazonApiTransport::__construct(), 2 passed in /var/www/html/mautic.lovia.life/var/cache/prod/ContainerFzpn1ly/getMautic_Transport_AmazonApiService.php on line 8 and exactly 8 expected" at /var/www/html/mautic.lovia.life/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonApiTransport.php line 114 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Too few arguments to function Mautic\\EmailBundle\\Swiftmailer\\Transport\\AmazonApiTransport::__construct(), 2 passed in /var/www/html/mautic.lovia.life/var/cache/prod/ContainerFzpn1ly/getMautic_Transport_AmazonApiService.php on line 8 and exactly 8 expected at /var/www/html/mautic.lovia.life/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonApiTransport.php:114)"} []
[2020-10-13 13:56:11] mautic.ERROR: PHP Error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function get() on null in /var/www/html/mautic.lovia.life/app/bundles/CoreBundle/Controller/CommonController.php:200 Stack trace: #0 /var/www/html/mautic.lovia.life/app/bundles/CoreBundle/Controller/ExceptionController.php(122): Mautic\CoreBundle\Controller\CommonController->delegateView(Array) #1 /var/www/html/mautic.lovia.life/vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\CoreBundle\Controller\ExceptionController->showAction(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\Debug\Exception\FlattenException), Object(Symfony\Bridge\Monolog\Logger)) #2 /var/www/html/mautic.lovia.life/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 2) #3 /var/www/html/mautic.lovia.life/app/bundles/CoreBundle/EventListener/ExceptionListener.php(76): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Compon - in file /var/www/html/mautic.lovia.life/app/bundles/CoreBundle/Controller/CommonController.php - at line 200 [] []
[2020-10-13 13:56:11] mautic.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function get() on null in /var/www/html/mautic.lovia.life/app/bundles/CoreBundle/Controller/CommonController.php:200 Stack trace: #0 /var/www/html/mautic.lovia.life/app/bundles/CoreBundle/Controller/ExceptionController.php(122): Mautic\CoreBundle\Controller\CommonController->delegateView(Array) #1 /var/www/html/mautic.lovia.life/vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\CoreBundle\Controller\ExceptionController->showAction(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\Debug\Exception\FlattenException), Object(Symfony\Bridge\Monolog\Logger)) #2 /var/www/html/mautic.lovia.life/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 2) #3 /var/www/html/mautic.lovia.life/app/bundles/CoreBundle/EventListener/ExceptionListener.php(76): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Compon - in file /var/www/html/mautic.lovia.life/app/bundles/CoreBundle/Controller/CommonController.php - at line 200 [] []
```

@mabumusa1 Should I apply another PR ?

**Comment by ceefour** [comment]
**Workaround:** Switching to AWS SES SMTP on port 587 is a good-enough workaround for me at this point (unpatched 3.1.1).

However would love to have better integration with AWS SES API, as it opens door for (potentially future) better reporting/analytics, performance, etc.

**Comment by mabumusa1** [comment]
@ceefour thanks for testing, I edited the code more today. Please test after 30 minutes when the build is done

**Comment by mabumusa1** [comment]
Hello All,

Please review, this PR should fix all the cases for SES API in both send immediate and queue mode, thank you for your time and contribution

@jclimac 
@benfavre 
@Wise-Gorilla
@ghost
@LevryKurniawan
@chescos
@iurisilvio
@streamworksaudio
@bobotdls
@J-Light
@tenil
@jabaco
@alexdhika 
@adamfasullo
@javiergas 
@dctechnoIn
@StoppingBuck

**Comment by mabumusa1** [comment]
> I tried to apply this directly to 3.1.1 and I got this instead:
> 
> ```
> [2020-10-13 13:56:01] mautic.WARNING: Command `mautic:emails:send` exited with status code 1 [] []
> [2020-10-13 13:56:11] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Too few arguments to function Mautic\EmailBundle\Swiftmailer\Transport\AmazonApiTransport::__construct(), 2 passed in /var/www/html/mautic.lovia.life/var/cache/prod/ContainerFzpn1ly/getMautic_Transport_AmazonApiService.php on line 8 and exactly 8 expected" at /var/www/html/mautic.lovia.life/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonApiTransport.php line 114 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Too few arguments to function Mautic\\EmailBundle\\Swiftmailer\\Transport\\AmazonApiTransport::__construct(), 2 passed in /var/www/html/mautic.lovia.life/var/cache/prod/ContainerFzpn1ly/getMautic_Transport_AmazonApiService.php on line 8 and exactly 8 expected at /var/www/html/mautic.lovia.life/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonApiTransport.php:114)"} []
> [2020-10-13 13:56:11] mautic.ERROR: PHP Error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function get() on null in /var/www/html/mautic.lovia.life/app/bundles/CoreBundle/Controller/CommonController.php:200 Stack trace: #0 /var/www/html/mautic.lovia.life/app/bundles/CoreBundle/Controller/ExceptionController.php(122): Mautic\CoreBundle\Controller\CommonController->delegateView(Array) #1 /var/www/html/mautic.lovia.life/vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\CoreBundle\Controller\ExceptionController->showAction(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\Debug\Exception\FlattenException), Object(Symfony\Bridge\Monolog\Logger)) #2 /var/www/html/mautic.lovia.life/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 2) #3 /var/www/html/mautic.lovia.life/app/bundles/CoreBundle/EventListener/ExceptionListener.php(76): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Compon - in file /var/www/html/mautic.lovia.life/app/bundles/CoreBundle/Controller/CommonController.php - at line 200 [] []
> [2020-10-13 13:56:11] mautic.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function get() on null in /var/www/html/mautic.lovia.life/app/bundles/CoreBundle/Controller/CommonController.php:200 Stack trace: #0 /var/www/html/mautic.lovia.life/app/bundles/CoreBundle/Controller/ExceptionController.php(122): Mautic\CoreBundle\Controller\CommonController->delegateView(Array) #1 /var/www/html/mautic.lovia.life/vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\CoreBundle\Controller\ExceptionController->showAction(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\Debug\Exception\FlattenException), Object(Symfony\Bridge\Monolog\Logger)) #2 /var/www/html/mautic.lovia.life/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 2) #3 /var/www/html/mautic.lovia.life/app/bundles/CoreBundle/EventListener/ExceptionListener.php(76): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Compon - in file /var/www/html/mautic.lovia.life/app/bundles/CoreBundle/Controller/CommonController.php - at line 200 [] []
> ```
> 
> @mabumusa1 Should I apply another PR ?

You need to clear the cache after you apply this patch, please apply the latest version of the patch and let me know if you find any issues

**Comment by wise-gorilla** [comment]
@mabumusa1 The segment email sending dont work and no error get logged

**Comment by mabumusa1** [comment]
> @mabumusa1 The segment email sending dont work and no error get logged

@Wise-Gorilla I tested the segment emails in both immediate send and queue and it worked on both of them

**Comment by wise-gorilla** [comment]
> > @mabumusa1 The segment email sending dont work and no error get logged
> 
> @Wise-Gorilla I tested the segment emails in both immediate send and queue and it worked on both of them

I re-checked it on a clean staging branch inistalation... the emails get delivered if i sent the email directly to the lead or sent a test/preview email but if i send to several contacts/segment email the email dont get delivered and dont get any error.
I un-applied the PR and applied my PR [#9150](https://github.com/mautic/mautic/pull/9150) and it worked normally.

**Comment by mabumusa1** [comment]
> > > @mabumusa1 The segment email sending dont work and no error get logged
> > 
> > 
> > @Wise-Gorilla I tested the segment emails in both immediate send and queue and it worked on both of them
> 
> I re-checked it on a clean staging branch inistalation... the emails get delivered if i sent the email directly to the lead or sent a test/preview email but if i send to several contacts/segment email the email dont get delivered and dont get any error.
> I un-applied the PR and applied my PR [#9150](https://github.com/mautic/mautic/pull/9150) and it worked normally.

I made more changes to enhance the code, please apply them based on the branch 3.1, I tested most of the cases, I shall test again

**Comment by wise-gorilla** [comment]
@mabumusa1 checked it, the segment issue got solved now but please note that attachments and custom headers dont work when you send the email directly to the contact

**Comment by mabumusa1** [comment]
> @mabumusa1 checked it, the segment issue got solved now but please note that attachments and custom headers dont work when you send the email directly to the contact

@Wise-Gorilla this is not an issue of the transport itself, this another bug

There are missing lines on this controller, to add attachments and headers as both of them are missing

https://github.com/mautic/mautic/blob/825e2aeea56d46f315159d6a6a70c572aa787513/app/bundles/LeadBundle/Controller/LeadController.php#L1375


I started an issue this on #9322

**Comment by mabumusa1** [comment]
Closing to restart travis

**Review by wolfadr — DISMISSED** [review]
As far as I understand the changes, the small difference in the structure of the bounce messages (key `eventType`, in case of SES Configuration Sets instead of `notificationType` in the global configuration) was included in the PR.

**Comment by Av1dLearner** [comment]
Would this also solve #9136 (when using SES API )?

**Comment by mabumusa1** [comment]
> Would this also solve #9136 (when using SES API )?

Yes, it should

**Review by kuzmany — DISMISSED** [review]
I was able to reproduce it 

> mautic.WARNING: Received SES webhook of type 'Notification' but couldn't understand payload

This PR fixed it and bounce is processed properly 

👍

**Comment by npracht** [comment]
@jclimac
@benfavre
@Wise-Gorilla
@ghost
@LevryKurniawan
@chescos
@iurisilvio
@streamworksaudio
@bobotdls
@J-Light
@tenil
@jabaco
@alexdhika
@adamfasullo
@javiergas
@dctechnoIn
@StoppingBuck

we need one more tester that confirms it works properly and we can merge it in 3.2.0 !

**Comment by benfavre** [comment]
Works for me, great !

**Comment by npracht** [comment]
Okay, then let's go for it. Thanks a lot @mabumusa1 ! you have done an amazing work that will benefit to a loooot of mautic community users :-)

**Comment by benfavre** [comment]
having issues with special chars in headers again !!

**Comment by mabumusa1** [comment]
> having issues with special chars in headers again !!

Please provide steps to reproduce, or start another issue

**Comment by benfavre** [comment]
Steps to reproduce, "send an email", documented in original PR: https://github.com/mautic/mautic/pull/9150
Also no, I will not start another issue, but I will be kind enough to document the fix here.

**Comment by mabumusa1** [comment]
@ben

> Steps to reproduce, "send an email", documented in original PR: #9150
> Also no, I will not start another issue, but I will be kind enough to document the fix here.

Did you apply this PR before testing?

**Comment by benfavre** [comment]
Yes I did if you look up I am the one that said Go for merge initially.

You are missing mb_encode_mimeheader arround sender name in both instances in the getAmazonMessage method
L 341:  $sesArray['FromEmailAddress'] =  (!empty($fromName)) ? mb_encode_mimeheader($fromName).' <'.$fromEmail.'>' : $fromEmail;
L 384: $sesArray['FromEmailAddress'] =  (!empty($tokenizedMessage['from']['name'])) ? mb_encode_mimeheader($tokenizedMessage['from']['name']).' <'.$tokenizedMessage['from']['email'].'>' : $tokenizedMessage['from']['email'];

**Comment by benfavre** [comment]
Yes I did if you look up I am the one that said Go form initially.

**Comment by benfavre** [comment]
Will open a PR later if I have time, thanks, have nice day.

**Comment by mabumusa1** [comment]
@benfavre this is a related issue, I will make a PR based on your solution and get it merged in this release, it would be great to review

https://github.com/mautic/mautic/issues/9433

**Comment by r-martins** [comment]
This doesn't fix #9345, as the reported problem (accented characters when using SES API) still persists on v. 3.2.2.

**Comment by dsp76** [comment]
I can confirm, that it doesn't fix #9345 ...
Still broken in v3.2.5 @mabumusa1 :(

**Comment by mabumusa1** [comment]
> I can confirm, that it doesn't fix #9345 ...
> Still broken in v3.2.5 @mabumusa1 :(

This the right PR, please review, hopefully we can merge it on the next release
https://github.com/mautic/mautic/pull/9434

**Pull request merged**
