### PR TITLE
Fixed MySQL DATETIME function use (doesn't exist)

### LINKED ISSUE #1031: SQL error: wrong mysql function DATETIME() - console mautic:leadlists:update
Mautic: 1.2.0

**STEPS TO REPRODUCE:**
create custom lead field: type datetime, name "date_add"
create lead list with filter: "date_add" greater than "last week"
run console mautic:leadlists:update --env=prod

Mysql doesn't have function DATETIME()

error log:
```
Rebuilding leads for list 1
  [Doctrine\DBAL\DBALException]
  An exception occurred while executing 'SELECT count(distinct(l.id)) as lead_count, max(id) as max_id FROM leads l LEFT JOIN lead_lists_leads ll ON l.id = ll.lead_id WHERE (l.id NOT IN (SELECT new_check.lead_id FROM lead_lists_le
  ads new_check WHERE (new_check.leadlist_id = 1) AND (new_check.lead_id = l.id))) AND ((DATETIME(l.date_add) > ?) AND ((ll.lead_id IS NULL) OR (ll.date_added <= '2015-10-21 12:58:51')))' with params ["2015-10-18 23:59:59"]:
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(l.date_add) > '2015-10-18 23:59:59')
   AND ((ll.lead_id IS NULL) OR (ll.date_adde' at line 1

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(l.date_add) > '2015-10-18 23:59:59')
   AND ((ll.lead_id IS NULL) OR (ll.date_adde' at line 1
```

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**

This PR fixes #1031. See the issue for steps to reproduce.

### CODE REVIEW

**Comment by dbhurley** [comment]
+1 this is an easy one.

**Comment by alanhartless** [comment]
Good point.  We probably need to use STR_TO_DATE.  I'll test using it.

**Comment by dbhurley** [comment]
The other option is a concatenation of DATE() and TIME()

**Comment by alanhartless** [comment]
Changed the mysql date/time functions to use STR_TO_DATE which works in my tests.

**Comment by dbhurley** [comment]
+1 works for me.

**Pull request merged**
