### PR TITLE
Segment query optimization

### PR DESCRIPTION
**Pull request by rohitpavaskar**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [N]
| New feature/enhancement? (use the a.x branch)      | [Y]
| Deprecations?                          | [N]
| BC breaks? (use the c.x branch)        | [N]
| Automated tests included?              | [Y] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This will increase the performance of segment queries as it will add lead limiters to inner query and lower rows scanned.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create segment with filters and test every filter is working fine.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11283"></a>

### CODE REVIEW

**Review by RCheesley — APPROVED** [review]
Thanks for the PR @rohitpavaskar - I tested all the existing segments by editing / rebuilding / adding new contacts, and also created a bunch of other segments using different filter options.

All seems to be as expected!

**Review by IrisAmrein — APPROVED** [review]
I tested this PR too and created some new segments with filters (especially also the date filters "birthday" and for example "-3 days"). everything worked smoothly and correct for me as well.

**Comment by RCheesley** [comment]
Awesome - this just needs a code review then - @kuzmany @mabumusa1 would you be able to do the honours?

**Review by kuzmany — APPROVED** [review]
I did test on customer database and didn't find any issue.
Code looks good as usual
Let's go 👍

**Pull request merged**
