### PR TITLE
Global search fix

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [Y]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [Y] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/pull/11435

#### Description:

https://github.com/mautic/mautic/pull/9693 introduced a bug that broke the global search. There is another fix for that in https://github.com/mautic/mautic/pull/11435 which is fixing the symptom, not the cause. I suggest this fix as adding the join could have break other areas where the `getEntities()` method is called like API and who knows what else. I suggest to add the join only when needed.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Test steps from https://github.com/mautic/mautic/pull/9693
3. Test steps from https://github.com/mautic/mautic/pull/11435

### CODE REVIEW

**Comment by adiux** [comment]
@escopecz This branch is out-of-date
@volha-pivavarchyk maybe you want to test it?

**Review by mabumusa1 — APPROVED** [review]
I tested on Gitpod, this PR is good to go, no errors were generated during testing

**Review by volha-pivavarchyk — APPROVED** [review]
Works well. Code looks great!

**Review by jos0405 — APPROVED** [review]
Page global search works as expected.
(There is a result count visible - not sure if its okay.)

image

I checked the landing page result count as well. Works nice. I played around with inserting the same form - the logic was not fooled, works perfectly.

image

**Pull request merged**
