### PR TITLE
Fixing campaign contact field condition on state field

### LINKED ISSUE #10868: Filter state select error (segment and campaigns)
### Mautic Version

4.1.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

In Segment (filter including state) and in Campaing (condition -> field value -> state) there a problem whe any one try to select any state. 
The interface return noname error. And block the user to select a state.
In segment, the error out after the second change. 
In Campaingn, the error persiste every when you try selec a state in condition field value -> state.

In Apache, php return:
[Tue Feb 15 15:38:47.369782 2022] [php7:warn] [pid 985131] [client 152.228.173.207:60202] PHP Warning:  array_flip(): Can only flip STRING and INTEGER values! in /mautic/app/bundles/LeadBundle/Form/Type/CampaignEventLeadFieldValueType.php on line 165, referer: https://mautic.XXXXXX.com.br/s/campaigns/edit/53

The errors meet on mautic 3 and 4.1.2

### How can we reproduce this issue?

In segment.
1:  Create a new segment, 
2: select filter state, change the operator to "include", 
3: select any state and try to save, the erros come on the first time save. 

In Campaign
1: Create a new campaing, and open the editor, select a segment from source
2: Select a condition, field value.
3: Select the value from state, and selec any state. 
4: Try to update te node, and the erros come. 

### Relevant log output

```shell
Dont generate Mautic log, but generate the Apache/php log error.

[Tue Feb 15 15:38:47.369782 2022] [php7:warn] [pid 985131] [client 152.228.173.207:60202] PHP Warning:  array_flip(): Can only flip STRING and INTEGER values! in /mautic/app/bundles/LeadBundle/Form/Type/CampaignEventLeadFieldValueType.php on line 165, referer: https://mautic.XXXXXX.com.br/s/campaigns/edit/53
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/108497552-filter-state-select-error-segment-and-campaigns?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [x] 
| Related user documentation PR URL      | \
| Related developer documentation PR URL | \
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/issues/10868

#### Description:

It's not possible to create a campaign contact field condition with the state field because the state field is not a flat array but multidimensional array so it cannot be `array_flip`ed. This PR is flattening it when checking the values before save.

#### Steps to test this PR:

0. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
1. Create a new campaign, and open the editor, select a segment from source
2. Select a condition, field value.
3. Select the value from state, and select any state.
4. Try to update the node, and the errors come.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10961"></a>

### CODE REVIEW

**Comment by npracht** [comment]
I'll test it tomorrow. It seems easy to test :)

**Review by npracht — DISMISSED** [review]
Before 🐛 :
Capture d’écran 2022-03-15 à 13 29 31

After 🦄 :
Capture d’écran 2022-03-15 à 13 30 29

**Review by RCheesley — DISMISSED** [review]
Confirmed the bug before applying:
Simple Browser — mautic — Gitpod Code (4)

After applying the PR I was able to save the filter using the state field and it works as expected!

Thanks for the PR @escopecz 🚀

**Comment by RCheesley** [comment]
Just needs a code review then RTC - @mabumusa1 / @kuzmany could you do that?

**Comment by kuzmany** [comment]
Probably we should use flipArray method from this PR 

https://github.com/mautic/mautic/pull/9339/files#diff-750c1c895627eaf34d3234ea533657ea0d21b488a023c4131430c914a6c569feR104

It allow flip both types of arrays

**Comment by RCheesley** [comment]
@escopecz any thoughts on the suggestion above?

**Comment by escopecz** [comment]
Yes, that new method could be used. However, it is in an open PR, so we'd have to merge it first.

Update: I've reviewed https://github.com/mautic/mautic/pull/9339

**Comment by RCheesley** [comment]
@escopecz now we've merged #9339 I think this PR will need to be tweaked and re-tested, so I'm going to remove the Ready to Commit label accordingly.  Please remove the pending-feedback label once it's updated and ready for testing :)

**Comment by escopecz** [comment]
@kuzmany the `ArrayHelper::flipArray()` function did not do exactly what was needed in this case. So I created new `ArrayHelper::flatten()` function so it can be reused.

**Comment by escopecz** [comment]
Rebased to fresh 4.x (v 4.4.0). We should have merged it when it was ready. I couldn't use Kuzmany's function anyway and now this simple bug fix covered with automated tests is just sitting here 3 months later. I'm getting very frustrated with this lack of testers.

**Review by kuzmany — DISMISSED** [review]
It works as expected 👍

**Comment by RCheesley** [comment]
One conflict to resolve after last week's sprint - then we are good to get this merged.

**Comment by RCheesley** [comment]
@escopecz we should also decide if we are going to push this back to 4.4 - if so we should make the PR and have that tagged as the milestone I feel.

**Comment by escopecz** [comment]
I don't plan to push this back to Mautic 4 as I had a hard time to find testers over the past 6 months for this simple fix so I assume there is very little need to fix this bug and it is not as urgent to be fixed in Mautic 4 too with a duplicated PR that would take another 6 months to get tested. I hope we'll have Mautic 5 by then.

But if I'm mistaken and this fix is needed in Mautic 4 then anyone can cherry-pick the commits on top of the 4.x branch and create the PR.

**Pull request merged**
