### PR TITLE
Mautic 3 - Checkbox is displayed after option label (not before)

### LINKED ISSUE #8986: Mautic 3 - Checkbox is displayed after option label (not before)
## Bug Description
In Mautic 3 the checkbox field presents the checkbox after the option title, not before anymore.

| Q   | A
| --- | ---
| Mautic version | 3.0.1
| PHP version | 7.3.14
| Browser | any

### Steps to reproduce
1. Create a form with a checkbox field
2. look at preview (or embedded form) - checkbox is behind of the option, not in front of it.
 
### Log errors
none

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.x
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Issue(s) addressed                     | Fixes #8986 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2.

### CODE REVIEW

**Comment by dennisameling** [comment]
Probably need to keep input and label separated, but just switch them around (first checkbox, then label). Will check further tomorrow

**Comment by dennisameling** [comment]
@mabumusa1 Thanks for this PR, however it re-introduces the invalid HTML which was the reason https://github.com/mautic/mautic/issues/8724 was created. It's enough to switch around the label and the input fields, so that the radio button is shown first. Hope you don't mind that I just committed that in https://github.com/mautic/mautic/pull/9024/commits/6c0fa012cfdd4daebcbb8097dfec17539b3bafda.

The radio buttons are now shown before the labels:

image

**Review by dennisameling — DISMISSED** [review]

**Review by RCheesley — DISMISSED** [review]
Thanks for the fix! 

Confirm the bug before the PR is applied:

screenshot-mautibox com-2020 07 22-21_16_16

And the correct way round after the patch is applied:

screenshot-local mautic3-2020 07 22-21_24_11

**Review by kuzmany — APPROVED** [review]
👍

**Comment by mabumusa1** [comment]
> @mabumusa1 Thanks for this PR, however it re-introduces the invalid HTML which was the reason #8724 was created. It's enough to switch around the label and the input fields, so that the radio button is shown first. Hope you don't mind that I just committed that in [6c0fa01](https://github.com/mautic/mautic/commit/6c0fa012cfdd4daebcbb8097dfec17539b3bafda).
> 
> The radio buttons are now shown before the labels:
> 
> image

@dennisameling of course I do not mind, this solution works fine, I tested it as well

**Pull request merged**
