### PR TITLE
HTML area for forms + choosen for form fields

### PR DESCRIPTION
**Pull request by kuzmany**
| Q  | A
| --- | ---
| Bug fix? | n
| New feature? | y
| Related user documentation PR URL | n
| Related developer documentation PR URL | n
| Issues addressed (#s or URLs) | n
| BC breaks? | n
| Deprecations? | n

[//]: # ( Required: )
#### Description:
Just add HTML area for forms. Same like Description area but without wysiwyg.
Allow add custom codes, for example facebook like button to form.

#### Steps to test this PR:
1. Apply PR +  mautic:assets:generate
2. Create form, choose new field HTML area from selectbox choosen 
3. Paste HTML code and test preview

html-area-mautic

html-area

choosen

### CODE REVIEW

**Comment by alanhartless** [comment]
The only thing holding this and the other new form fields back is the need to convert the form field dropdown into a chosen the same way we did segment filters. Reason being that as is, on smaller resolutions, the bottom options in the dropdown are inaccessible. Adding more will exacerbate the issue. If you or someone wants to spearhead the dropdown to chosen conversion - we can get these merged sooner than later.

**Comment by kuzmany** [comment]
@alanhartless added choosen for fields

**Comment by escopecz** [comment]
The field type select is chosen now, but it
1) does not add any new fields - _using dev environment, browser cache cleared, no JS errors_
2) Is 100% wide. Could it be a little smaller?
screen shot 2017-04-10 at 18 10 58

**Comment by kuzmany** [comment]
@escopecz 
Try mautic:assets:generate and browser refresh.
I am testing now and works.
Choose width update

**Comment by kuzmany** [comment]
@escopecz 
update css and choosen input width

image

**Comment by dongilbert** [comment]
+1

**Pull request merged**
