### PR TITLE
Support https through reverse proxy

### LINKED ISSUE #7577: Chrome shows Mautic dashboard as not fully secure
## Bug Description

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.1.27
| Browser | Version 71.0.3578.98 (Official Build) (64-bit)

Mautic dashboard insecurely loads the i2.wp.com avatar over http even when the Site URL is configured for https.

### Steps to reproduce
1. Deploy Mautic with nginx handling SSL termination with letsencrypt/certbot certificates
2. Visit the dashboard in Chrome
3. Look at the icon to the left of the address bar and/or visit the Security tab in the Chrome developer tools, which clearly show a request like http://i2.wp.com/my.mautic.site/media/images/avatar.png being made, despite everything else going over https:

image

### LINKED ISSUE #8944: There should be a way to set Mautic to use HTTPS in the config
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When running Mautic with SSL encryption you will get a warning for mixed content related to gravatar images. This has been reported before here: **Chrome shows Mautic dashboard as not fully secure #7577** & https://github.com/mautic/docker-mautic/issues/37

A solution to this is to add `$_SERVER['HTTPS'] = 'on';` in the `index.php` in the Mautic installation. However, when you update Mautic you will need to do this again.

Maybe there can be a setting in the configuration to set the server to use HTTPS ?

| Q   | A
| --- | ---
| Mautic version | 2.16.3
| PHP version | 7.1.33
| Browser | Chrome Version 83.0.4103.106

### Steps to reproduce
1. I am using Mautic wit this docker setup: https://github.com/mautic/docker-mautic/tree/master/examples/mautic-example-nginx-ssl behind Cloudflare
2. When you login in the dashboard and refresh the page you will get a mixed content warning because of Gravatar images requested from (http://i2.wp.com)

### PR DESCRIPTION
**Pull request by enricodeleo**
| Q  | A
| --- | ---
| Bug fix? | No
| New feature? | Feature 
| Automated tests included? | No
| Related user documentation PR URL | None
| Related developer documentation PR URL | None 
| Issues addressed (#s or URLs) | fixes #7577 resolves #8944 
| BC breaks? | No
| Deprecations? |  No

#### Description:

Several users host Mautic behind a reverse proxy. In this case, the php application thinks it is hosted on a plain http environment even if it is facing the internet through https. Most of the reverse proxies (e.g. Nginx as a reverse proxy) do expose a `HTTP_X_FORWARDED_PROTO ` header in order to transfer the original scheme used. This pull request will add https support in this very common scenario.

### CODE REVIEW

**Comment by virgilwashere** [comment]
@enricodeleo this was the nginx config I had in place last time I was doing this... assuming it works still.  Any comments?

```nginx
upstream rproxy_mautic {
    server {{ UPSTREAM_SOURCE }}:443;
}

server {
    listen          443 ssl http2;
    server_name     {{ SERVER_NAME }};

    ssl_certificate     /etc/certs/{{ SSLCERT_DOMAIN }}/fullchain.cer;
    ssl_certificate_key /etc/certs/{{ SSLCERT_DOMAIN }}/{{ SSLCERT_DOMAIN }}.key;
    ssl_verify_client   off;

	location / {
        proxy_pass              https://rproxy_mautic;

        proxy_http_version      1.1;
        proxy_redirect          http:// https://;
        proxy_ssl_server_name   on;
        proxy_ssl_session_reuse on;

        proxy_set_header        Host               $host;
        proxy_set_header        X-Real-IP          $remote_addr;
        proxy_set_header        X-Forwarded-Host   $host;
        proxy_set_header        X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto  https;
        proxy_set_header        X-Forwarded-Port   $server_port;
        proxy_set_header        Proxy "";
        proxy_buffering         off;
        proxy_cache             off;
    }
}
```

and this in `{{ UPSTREAM_SOURCE }}`'s `app/config/parameters_local.php`

```php
$parameters = array(
	'trusted_proxies'   => array(
        '0' => '{{ SERVER_NAME }}',
    ),
);
```

Virgil

**Comment by enricodeleo** [comment]
Hi Virgil. 
Your configuration is correct, the enhanchement, though, has a different meaning. 
trusted_proxies is needed to make the application accept connection from different hosts (or all in case of 0.0.0.0/0). Here we want also let the php application *know* it is under https.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
Hi @enricodeleo thanks so much for this PR - could you please take a look at resolving the conflict so that we can get this tested and merged in 3.1?  If you can also rebase against staging to trigger the code coverage report that would be awesome!

**Comment by RCheesley** [comment]
Bumping to 3.2 due to unresolved conflict - @enricodeleo if you can take a look and update the PR we can look to get it tested and merged!

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@enricodeleo thanks for signing the contributors agreement, if you could resolve the conflict that would be awesome!

**Comment by escopecz** [comment]
I'd suggest to create a new middleware for this. There should be no logic in the index.php file. See some examples: https://github.com/mautic/mautic/tree/features/app/middlewares

**Comment by christopheg** [comment]
> I'd suggest to create a new middleware for this. There should be no logic in the index.php file. See some examples: https://github.com/mautic/mautic/tree/features/app/middlewares

I agree.
This was my proposal:
https://github.com/mautic/mautic/pull/9496/commits/57f2823d12a2bf577ce88e22a80626763a6572b9

**Comment by npracht** [comment]
Okay, then i'll close this PR in favor of https://github.com/mautic/mautic/pull/9496.
@enricodeleo and @escopecz can you review it please ?

**Pull request closed without merging**
