### PR TITLE
Fix form autofill email field issue if email contains a +

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Create form with email  and enable Auto fill data from behaviour tab
3. Submit form with email address like `something+test@domain.tld`
4. Open form again and see `something test@domain.tld` as filled address
5. After PR should work properly

### CODE REVIEW

**Review by volha-pivavarchyk — APPROVED** [review]
Works well. The form  is autofilled correctly

**Review by MadlenF — APPROVED** [review]
Works as described 👍

**Comment by RCheesley** [comment]
@kuzmany this one needs a bump on test coverage

**Comment by kuzmany** [comment]
@RCheesley tests added

**Comment by RCheesley** [comment]
Awesome - thanks @kuzmany just pending a code review before merging! 🚀

**Review by escopecz — APPROVED** [review]

**Pull request merged**
