### PR TITLE
GDPR time period by parameter: Update CleanupMaintenanceCommand.php

### PR DESCRIPTION
**Pull request by technik-kvz**
* Update CleanupMaintenanceCommand.php

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Change the lines in the php script
2. Run the cleanup script with additional parameters like 'mautic:maintenance:cleanup --dry-run --gpdr --gdpr-days 365' to test 1 year as deletion period

#### Why is this feature necessary?

According to GDPR rules, one has to choose/define time periods to store the data. Once defined, you have to keep to that defined time periods. Currently it is only possible to delete it after 3 years in mautic.

If you collect personal data on behalf of the government (like we do) you have to keep that data for at least 10 years (not possible if deleted after 3 years) and for usual contracts you only have to keep the personal data only for 2 years (at least in germany).

So a fix value of 3 years is a problem.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10827"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for the PR @technik-kvz and welcome to the community!

Would you mind adding a bit of a description to the PR to explain why you think this feature is needed in addition to what is already available with the cleanup command? That might help marketers and developers reviewing the PR to understand a bit more easily.

It looks like you have some [code style issues](https://github.com/mautic/mautic/runs/5082668157?check_suite_focus=true#step:8:29) to address and also some [PHPSTAN issues](https://github.com/mautic/mautic/runs/5082668144?check_suite_focus=true#step:8:92). Let us know if you need any help with addressing them.

We will need to have a small update to the documentation for this PR as well if we are to merge this PR, the page you will need to update is here: https://docs.mautic.org/en/setup/cron-jobs#clean-up-old-data and there is a link at the bottom of the page which will take you to the page in the docs which you will need to edit.  Once the PR is made you can edit the description to add the link.

Shout if you need any help with the above!

**Comment by technik-kvz** [comment]
I added a "Why is this feature necessary?" paragraph. I hope everyone can see now, that this is not only a "nice to have" feature.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Thanks for adding the detail to the description @technik-kvz - makes a lot of sense!

**Comment by technik-kvz** [comment]
What does CS Fixer "Error: Process completed with exit code 8." mean? I don't see why it failes.

**Comment by RCheesley** [comment]
Hey there!

If you scroll up to the top it shows you the reason for failure:

https://github.com/mautic/mautic/runs/5091038328?check_suite_focus=true#step:8:29

Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) mautic/app/bundles/CoreBundle/Command/CleanupMaintenanceCommand.php (**method_argument_space**)

This relates to the following documentation: https://cs.symfony.com/doc/rules/function_notation/method_argument_space.html

> In method arguments and method call, there MUST NOT be a space before each comma and there MUST be one space after each comma. Argument lists MAY be split across multiple lines, where each subsequent line is indented once. When doing so, the first item in the list MUST be on the next line, and there MUST be only one argument per line.

Does that help?

You can run the cs-fixer git hook locally - please find the docs here: https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#code-standards.

**Comment by technik-kvz** [comment]
In my dev. environment I cannot see any errors/problems with phpstan or cs fixer, when I followed the steps in https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#code-standards

I cannot test the phpunit tests, there are a lot of fails and problems with sql commands as root and so on, but since I didn't change anything sql related there should not be a problem.

**Comment by escopecz** [comment]
@technik-kvz check https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#phpunit for configuring functional tests on your local. Ping me if you'll need some help with the test. I'd write functional test[ like this one](https://github.com/mautic/mautic/blob/8f76c3ca21bc466c3a97d95f93da8b204b542b83/app/bundles/WebhookBundle/Tests/Functional/RemoveOldLogTest.php#L78) where I'd created 2 records in the database with one older 1 year and one newer, run the command then then check that the older one is gone and the newer one is still present.

**Comment by kuzmany** [comment]
Close favor to https://github.com/mautic/mautic/pull/12332

**Pull request closed without merging**
