### PR TITLE
M3 fix multivalue custom fields

### PR DESCRIPTION
**Pull request by hluchas**
| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | -
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
There is problem with:
- lookup
- select
 - multiselect fields in M3.

Lookup field values are not saved in correct format. The rest is causing similar problems in segment filter choices for example.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. create segment or DWC filter based on title (lookup field)
2. You'll get
<details><summary>`Type error: Return value of Mautic\LeadBundle\Event\FormAdjustmentEvent::getFieldChoices() must be of the type array, string returned`</summary>

```
2020-04-22 14:11:44] php.CRITICAL: Type error: Return value of Mautic\LeadBundle\Event\FormAdjustmentEvent::getFieldChoices() must be of the type array, string returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Return value of Mautic\\LeadBundle\\Event\\FormAdjustmentEvent::getFieldChoices() must be of the type array, string returned at /Users/lukas.drahy/dev/cloud3/app/bundles/LeadBundle/Event/FormAdjustmentEvent.php:98)
[stacktrace]
#0 /Users/lukas.drahy/dev/cloud3/app/bundles/LeadBundle/EventListener/TypeOperatorSubscriber.php(266): Mautic\\LeadBundle\\Event\\FormAdjustmentEvent->getFieldChoices()
#1 /Users/lukas.drahy/dev/cloud3/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(115): Mautic\\LeadBundle\\EventListener\\TypeOperatorSubscriber->onSegmentFilterFormHandleLookup(Object(Mautic\\LeadBundle\\Event\\FormAdjustmentEvent), 'mautic.adjust_f...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#2 /Users/lukas.drahy/dev/cloud3/vendor/symfony/event-dispatcher/EventDispatcher.php(214): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Mautic\\LeadBundle\\Event\\FormAdjustmentEvent), 'mautic.adjust_f...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#3 /Users/lukas.drahy/dev/cloud3/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'mautic.adjust_f...', Object(Mautic\\LeadBundle\\Event\\FormAdjustmentEvent))
#4 /Users/lukas.drahy/dev/cloud3/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(143): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('mautic.adjust_f...', Object(Mautic\\LeadBundle\\Event\\FormAdjustmentEvent))
#5 /Users/lukas.drahy/dev/cloud3/app/bundles/LeadBundle/Provider/FormAdjustmentsProvider.php(36): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch('mautic.adjust_f...', Object(Mautic\\LeadBundle\\Event\\FormAdjustmentEvent))
#6 /Users/lukas.drahy/dev/cloud3/app/bundles/LeadBundle/Controller/AjaxController.php(201): Mautic\\LeadBundle\\Provider\\FormAdjustmentsProvider->adjustForm(Object(Symfony\\Component\\Form\\Form), 'title', 'lead', '=', Array)
#7 /Users/lukas.drahy/dev/cloud3/app/bundles/CoreBundle/Controller/AjaxController.php(132): Mautic\\LeadBundle\\Controller\\AjaxController->loadSegmentFilterFormAction(Object(Symfony\\Component\\HttpFoundation\\Request), 'lead')
#8 /Users/lukas.drahy/dev/cloud3/vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\\CoreBundle\\Controller\\AjaxController->executeAjaxAction('loadSegmentFilt...', Object(Symfony\\Component\\HttpFoundation\\Request), 'lead')
#9 /Users/lukas.drahy/dev/cloud3/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#10 /Users/lukas.drahy/dev/cloud3/vendor/symfony/framework-bundle/Controller/ControllerTrait.php(108): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#11 /Users/lukas.drahy/dev/cloud3/app/bundles/CoreBundle/Controller/AjaxController.php(110): Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller->forward('MauticLeadBundl...', Array)
#12 /Users/lukas.drahy/dev/cloud3/vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\\CoreBundle\\Controller\\AjaxController->delegateAjaxAction()
#13 /Users/lukas.drahy/dev/cloud3/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#14 /Users/lukas.drahy/dev/cloud3/vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 /Users/lukas.drahy/dev/cloud3/app/AppKernel.php(136): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#16 /Users/lukas.drahy/dev/cloud3/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 /Users/lukas.drahy/dev/cloud3/app/middlewares/CloudMiddleware.php(78): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#18 /Users/lukas.drahy/dev/cloud3/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CloudMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#19 /Users/lukas.drahy/dev/cloud3/app/middlewares/Dev/IpRestrictMiddleware.php(64): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#20 /Users/lukas.drahy/dev/cloud3/app/middlewares/VersionCheckMiddleware.php(52): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#21 /Users/lukas.drahy/dev/cloud3/app/middlewares/RedirectResponseMiddleware.php(68): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#22 /Users/lukas.drahy/dev/cloud3/app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\RedirectResponseMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#23 /Users/lukas.drahy/dev/cloud3/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#24 /Users/lukas.drahy/dev/cloud3/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#25 /Users/lukas.drahy/dev/cloud3/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#26 {main}
"} 
```
</details>

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Run migrations on this branch if you are testing locally
3. Repeat reproduction steps
4. You are able to rebuild segments with filter using these fields
5. You can edit lookup custom field (Title). You can use this field in Contact and save it.
6. You can edit select custom field (Industry is used in Company). You can use this field in Contact/Company and save it. Filer for segment will respect that relationship Contact:Company
7. You can edit multiselect custom field. You can use this field in Contact/Company and save it.
8. Ensure that dynamic content is providing and saving correct values for Title too

### CODE REVIEW

**Comment by kuzmany** [comment]
I've tested this. Looks good, but I found another issue with title field suggestion https://github.com/mautic/mautic/issues/8748

**Comment by hluchas** [comment]
> I've tested this. Looks good, but I found another issue with title field suggestion #8748

~~Good catch! I know about this. This is not solved in this PR. I'll start discussion in our team.
Please wait with merge instead. I'll come with more fixes here tomorrow.~~

TY!

**Comment by hluchas** [comment]
@kuzmany We don't have fix for this now, but we know about this ...
This PR is fixing custom fields ...

**Comment by kuzmany** [comment]
I've tried many variants of these cases. Select and Multiselect fields works properly for contact/company, DWC and email DWC too.

Title lookup fields works for DWC and email DWC, doesn't work for contact edit page.
Title lookup fields just suggests values from already set values fomm all contacts, but not from default from Contact fields.
Title lookup doesn't work  If I add variant in emails DWC (works after save email)
It's not big deal. 
We can look on it later. 
Approve it 👍

**Review by kuzmany — APPROVED** [review]

**Pull request merged**
