### PR TITLE
Fix datetime import

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for 4.0
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
Noticed date time is imported as UTC time zone. Then displayed in contact profile in time zone related to configuration.  User expect see date time same in contact profile like was imported.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Set timezone in configuration to Europe/Paris
3. Create custom date time field
4. Run this simple import
[import.zip](https://github.com/mautic/mautic/files/6220224/import.zip)
5. Based on import date time value `2020-02-02 21:49:59` expect same you should see after import in contact profile. But you see `2020-02-02 22:49:59`
6. After PR you should see after import `2020-02-02 21:49:59`. Same for both kind of imports: UI and background

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/9854"></a>

### CODE REVIEW

**Review by mabumusa1 — DISMISSED** [review]
Tested, it worked as expected

**Comment by tejasync** [comment]
I have tested this PR. Here are my observations:
1. I couldn't reproduce the bug with the steps mentioned in the description on mautic/features branch.
2. kuzmany/fix-datetime-import branch works as expected though.

**Comment by mabumusa1** [comment]
@ts-navghane I was able to reproduce the bug, can you give it a try another time? this is a good bug fix to be shipped

**Comment by kuzmany** [comment]
This fix does not work in background import.

We have two options:

- let users use in import just date time in UTC (same we need in API) - this just need be note in documentation without any additional dev touch
- normalize datetime value to UTC during the import

I marked is as WIP

**Review by npracht — DISMISSED** [review]
From UI it works as expected 👍🏽

**Comment by npracht** [comment]
@kuzmany i think we should move forward. This fixes already 1 issue. We can open an new issue for the background.

Can you fix conflicts ? Then it's ready to merge.

**Comment by RCheesley** [comment]
Bumping from the release due to failing tests.

**Comment by npracht** [comment]
@damzoneuh can you check what is going wrong with this ?
Capture d’écran 2021-08-23 à 18 10 10

**Comment by kuzmany** [comment]
Close favor to M5 version https://github.com/mautic/mautic/pull/13839

**Pull request closed without merging**
