### PR TITLE
Send SMS to contact API

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Yes
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | https://github.com/mautic/developer-documentation/pull/99
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Added support send SMS to concact by API. 
Similar to Send Email to contact API https://developer.mautic.org/#send-email-to-contact

#### Steps to test this PR:
1.  Apply PR, install API https://github.com/mautic/api-library and apply PR to API library https://github.com/mautic/api-library/pull/154 . Clear Mautic cache
2.  Setup Twillio integration https://mautic.org/docs/en/sms/index.html
3. Create contact with phone number and create text message in Mautic 
4. Test API something like:

```
<?php
use Mautic\MauticApi;
use Mautic\Auth\ApiAuth;

// ...
$initAuth = new ApiAuth();
$auth     = $initAuth->newAuth($settings);
$apiUrl   = "https://your-mautic.com";
$api      = new MauticApi();
$smsApi   = $api->newApi("smses", $auth, $apiUrl);
$result = $smsApi->sendToContact($smsId, $cotactId);
print_r($result);
```
5. Works If sms sent and response is success=1

### CODE REVIEW

**Comment by kuzmany** [comment]
Label: WIP

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by kuzmany** [comment]
@amagdy3 Mautic support just Twillio so far https://mautic.org/docs/en/sms/index.html

**Comment by galvani** [comment]
I have used some of your code and created another PR: https://github.com/mautic/mautic/pull/5854/

**Pull request closed without merging**
