### PR TITLE
A/B tests various fixes

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR cover some fixes for A/B testing
We've noticed some issues:

- switch between variant and all does not work properly 
image

- percentage and graphs doe don't work If one of email is unscheduled or unpublished 

image

- send by broadcast send also children emails, even IF we already send some emails during parent email sending
 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Create A/B testing scheduled  emails with 100 contacts for example
3.  Send it by broadcast command  `mautic:broadcast:send --limit=10` 
4.  See like your command send 20 emails (we expect 10 split 50% for each)
5. Check graphs and see like email was not send divided 50% for each email, there is diffference
6. Wait until one of the email is unscheduled or unpublished
7. Then check graphs na percentage in the A/B tabs on detail email page
8. We expect see graph and correct percentage
9. After apply PR should all these issues fixed

### CODE REVIEW

**Comment by mabumusa1** [comment]
@kuzmany please fix the conflicts on this PR, would be great to merge it

**Review by Moongazer — APPROVED** [review]

**Comment by LordRembo** [comment]
@kuzmany Could you rebase this branch and let the tests rerun?

**Comment by kuzmany** [comment]
@LordRembo it's based on the last 5.x

**Comment by LordRembo** [comment]
Weird, some of the tests seem to fail or cancel. Could you take a look @kuzmany ?

**Comment by kuzmany** [comment]
@LordRembo I'll take look on it tomorrow

**Review by PatrickJenkner — COMMENTED** [review]
I'm afraid that most of your changes don't seem to work for me:

- When I send with a limit of 10, 10 emails get sent: 5 for each variant
- The graph looks fine as long as one of the variants isn't unpublished.
- Once one of them gets unpublished, the graph is empty (see image).
Bildschirmfoto 2023-08-11 um 10 23 22
- Also, hitting "variant" and "all" doesn't change the graph (I don't know what's supposed to happen to be honest...) However, once I hit variant, both buttons become greyed out and I can't click on them anymore.


I have never worked with A/B testing before, so it's totally possible that I'm just doing something wrong. But I tried to follow your instructions as closely as possible.

**Comment by RCheesley** [comment]
@all-contributors please add @PatrickJenkner for usertesting
 
Thanks for testing the PR @PatrickJenkner - @kuzmany could you have a look at the feedback?

**Comment by LordRembo** [comment]
@PatrickJenkner @kuzmany @RCheesley Is there any way we can push this through? 
This PR needs to be updated & final review done to it.

**Comment by RCheesley** [comment]
It's going to need rebasing to the 5.0 branch for the next patch release now! Then we can try to get some eyes on it in the friday testing sprints.

**Comment by kuzmany** [comment]
Close at the moment. We will push it again once ready to M5

**Pull request closed without merging**
