### PR TITLE
Sms send example button

### PR DESCRIPTION
**Pull request by dataforxyz**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging 
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
Add 'Send Example' Button to SMS sends just like for emails. 
Follows new feature to send sms by segment https://github.com/mautic/mautic/pull/7879

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Enable the twillio plugin and configure an account.
3. Go to Channels/ Text Messages and create new Message
4. Put in some test information click save and close.
5. Click Send Example in the righthand corner. Add one or more phone numbers click send.

### CODE REVIEW

**Comment by npracht** [comment]
Hi @bobsburgers ! Thanks a lot for this great contribution.
Questions :
1. Why is M2 in the name of the PR. We won't add new feature to M2 branch (only security fixes), can you confirm your PR is up to date for staging (3.1.0) ?
2. Can you have a look at travis issue ?
3. Can you check the CLA-bot message and proceed with actions ?

Thanks again !

**Comment by dataforxyz** [comment]
thanks @npracht. 
1. m2 is in the pr because that is what I use still primarily. From my test looks like it works with M3 also. 
2. Ill try to tackle those issues this weekend. It looks like one is from my use of https://github.com/mautic/mautic/pull/7879 but I am not sure yet. 
3. i think that is fixed now.

**Comment by npracht** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by mabumusa1** [comment]
@bobsburgers you are almost done to get this PR ready, let's fix the pending issues together and get it ready to teste

**Comment by npracht** [comment]
@bobsburgers any chance to have a look at tests issues ?
Thanks !

**Pull request closed without merging**
