### PR TITLE
Add support for sms replies as a campaign decision

### PR DESCRIPTION
**Pull request by alanhartless**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This adds support to consume SMS replies through campaigns

#### Steps to test this PR:
You have to register a webhook with the service provider. For Twilio, it's done under Messaging for the phone number. The callback is `https://your.mautic.net/sms/twilio/callback`

1. Configure a SMS gateway 
2. Create a campaign with a "send text message" action then a "sends a text message" decision and do something as a result
3. Reply to a SMS 
4. The action attached to the decision should have been executed
5. Repeat to test the pattern support (use one that matches, doesn't match, etc)

#### List deprecations along with the new alternative:
1. \Mautic\SmsBundle\Api\AbstractSmsApi class is deprecated. Use \Mautic\SmsBundle\Sms\TransportInterface instead.
2. \Mautic\SmsBundle\Api\TwilioApi is deprecated. Use \Mautic\SmsBundle\Integration\Twilio\TwilioTransport instead

### CODE REVIEW

**Comment by kuzmany** [comment]
Alan, I am testing this PR. 

Does this PR cover situation with 2 smses like this? :

image

I think If I send two sms and If I receive webhook from first one, both decision will be fired?

**Comment by alanhartless** [comment]
@kuzmany that's correct. There's no way to include metadata to know which SMS is being replied to. So the marketer will have to plan accordingly by using unique reply phrases for the purpose of the campaign.

**Comment by alanhartless** [comment]
@npracht, done. Thanks!

**Comment by kuzmany** [comment]
@alanhartless I am testing this PR.
Please where could I find the place where I have to setup callback https://your.mautic.net/sms/twilio/callback

I didn't find it in twillio.

**Comment by kuzmany** [comment]
Test and works properly. 
I setup number and setup webhook 

image

I've created campaign

image

Tested:
1, SMS  without reply - decision not fired
2, SMS with reply YES and pattern YES - fired
3, SMS with reply Yes and pattern Y - fired

**Review by kuzmany — APPROVED** [review]

**Comment by ackrug** [comment]
Can someone walk a complete novice through this? I would be willing to compensate someone for assistance :D

**Comment by npracht** [comment]
@alanhartless has the documentation been done ?

**Comment by jpgiron1981** [comment]
> @kuzmany that's correct. There's no way to include metadata to know which SMS is being replied to. So the marketer will have to plan accordingly by using unique reply phrases for the purpose of the campaign.

I think that you need to set up a user contact field and store there the "level" of your campaign, and other contact fields with the branch of your campaign, and when you get and answer and fire next message, change this two fields according for identified where on your campaign its the customer. For this you need put before conditional for message answer a conditional for contact field. 

Maybe it's not an elegant solution, buy can help to move on.

**Pull request merged**
