### PR TITLE
Handle salesforce deletes gracefully

### PR DESCRIPTION
**Pull request by aarohiprasad**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? |
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

If a SF field is mapped in Mautic then later deleted, Mautic will continue to use that field in SF queries leading to failure to sync due to SF returning an error the field does not exist.

```
INTEGRATION ERROR: Salesforce - Job_Level__c, Lead_Company__c, example_Score__c__Contact, Prospecting_Qualification_Status__c ^ ERROR at Row:1:Column:113 No such column 'example_Score__c__Contact' on entity 'Lead'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.
```

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Setup Salesforce integration (https://www.mautic.org/docs/en/plugins/salesforce.html)
2. Create a text field in Salesforce for testing purposes, but it doesn't matter which field type you use. Or can use an existing field (not the obligatory one like `email`).
3. Go to Salesforce plugin settings, map your Salesforce field (contact or lead) to some Mautic field.
4. Save settings.
5. Go to your Salesforce account and delete the field you've just mapped.
6. Run `php app/console mautic:integration:fetchleads --integration=Salesforce --time-interval="10 days"`.
7. You will get an error in the console about missing column (see description above).

#### Steps to test this PR:
1. Load up this PR
2.  Repeat steps 1-6 from "Steps to reproduce the bug".
3. You should get no error in the terminal.
4. Go to Salesforce plugin settings and verify that the field you've just deleted is no longer mapped.

### CODE REVIEW

**Comment by aarohiprasad** [comment]
This depends on https://github.com/mautic/mautic/pull/13411. Will fix this after the mention PR is merged

**Comment by RCheesley** [comment]
@aarohiprasad the mentioned PR is now merged, can you please update this PR and fix the conflicts as suggested in your last reply? Thanks!

**Review by escopecz — DISMISSED** [review]
Thank you Aarohi! I see no issue. Nicely done! 👍

**Review by dadarya0 — APPROVED** [review]

**Comment by dadarya0** [comment]
Verified with same steps mention in step to test but getting exception 
```
12:56:12 ERROR     [mautic] Mautic\PluginBundle\Exception\ApiErrorException: {"error":{"message":"[{\"message\":\"\\nselect Id, Company,Email,LastName,SF_date__c, ConvertedContactId from\\n                                  ^\\nERROR at Row:1:Column:35\\nNo such column 'SF_date__c' on entity 'Lead'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.\",\"errorCode\":\"INVALID_FIELD\"}]","code":400}} (uncaught exception) at /var/www/html/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php line 1722 while running console command `mautic:integration:fetchleads`
[stack trace]
#0 /var/www/html/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php(1218): MauticPlugin\MauticCrmBundle\Integration\SalesforceIntegration->getMauticContactsToCreate(Array, Array, 'l.email, l.last...', 100, '2024-06-11 12:5...', '2024-06-21 12:5...', 0, Object(Symfony\Component\Console\Helper\ProgressBar))
#1 /var/www/html/app/bundles/PluginBundle/Command/FetchLeadsCommand.php(231): MauticPlugin\MauticCrmBundle\Integration\SalesforceIntegration->pushLeads(Array)
#2 /var/www/html/vendor/symfony/console/Command/Command.php(298): Mautic\PluginBundle\Command\FetchLeadsCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Mautic\PluginBundle\Command\FetchLeadsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Mautic\PluginBundle\Command\FetchLeadsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/bin/console(16): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main} ["hostname" => "mautic-community-web","pid" => 14373]
12:56:12 CRITICAL  [console] Error thrown while running command "mautic:integration:fetchleads --integration=Salesforce --time-interval='10 days'". Message: "{"error":{"message":"[{\"message\":\"\\nselect Id, Company,Email,LastName,SF_date__c, ConvertedContactId from\\n                                  ^\\nERROR at Row:1:Column:35\\nNo such column 'SF_date__c' on entity 'Lead'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.\",\"errorCode\":\"INVALID_FIELD\"}]","code":400}}" ["exception" => Mautic\PluginBundle\Exception\ApiErrorException^ { …},"command" => "mautic:integration:fetchleads --integration=Salesforce --time-interval='10 days'","message" => "{"error":{"message":"[{\"message\":\"\\nselect Id, Company,Email,LastName,SF_date__c, ConvertedContactId from\\n                                  ^\\nERROR at Row:1:Column:35\\nNo such column 'SF_date__c' on entity 'Lead'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.\",\"errorCode\":\"INVALID_FIELD\"}]","code":400}}"] ["hostname" => "mautic-community-web","pid" => 14373]
12:56:12 WARNING   [mautic] Command `mautic:integration:fetchleads` exited with status code 1 ["hostname" => "mautic-community-web","pid" => 14373]

In SalesforceIntegration.php line 1722:
                                                                                                                                                                                                                                                    
  {"error":{"message":"[{\"message\":\"\\nselect Id, Company,Email,LastName,SF_date__c, ConvertedContactId from\\n                                  ^\\nERROR at Row:1:Column:35\\nNo such column 'SF_date__c' on entity 'Lead'. If you are attemp  
  ting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.\",\"errorCode\":\"INVALID_FIELD\"}]","code":400}}
```

**Review by dadarya0 — CHANGES_REQUESTED** [review]
Not working as expected.

**Comment by escopecz** [comment]
@dadarya0 the error message comes from Salesforce and it looks more like a configuration issue:
```
No such column 'SF_date__c' on entity 'Lead'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.
```

**Comment by aarohiprasad** [comment]
Fixed the regex and this is working fine for me. I got an unrelated error while testing this on my local setup:
```13:46:20 ERROR     [mautic] INTEGRATION ERROR: Salesforce - Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: Can't get a way to read the property "deduplicate" in class "Mautic\CoreBundle\Entity\Notification". in /var/www/html/vendor/symfony/property-access/PropertyAccessor.php:511
Stack trace:
#0 /var/www/html/vendor/symfony/property-access/PropertyAccessor.php(154): Symfony\Component\PropertyAccess\PropertyAccessor->readProperty(Array, 'deduplicate', false)
#1 /var/www/html/app/bundles/CoreBundle/Entity/Transformer/NotificationArrayTransformer.php(30): Symfony\Component\PropertyAccess\PropertyAccessor->getValue(Object(Mautic\CoreBundle\Entity\Notification), 'deduplicate')
#2 /var/www/html/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php(920): Mautic\CoreBundle\Entity\Transformer\NotificationArrayTransformer->transform(Object(Mautic\CoreBundle\Entity\Notification))
#3 /var/www/html/plugins/MauticCrmBundle/Api/SalesforceApi.php(391): MauticPlugin\MauticCrmBundle\Integration\SalesforceIntegration->upsertUnreadAdminsNotification('Incorrect Sales...', 'It appears you ...')
#4 /var/www/html/plugins/MauticCrmBundle/Api/SalesforceApi.php(339): MauticPlugin\MauticCrmBundle\Api\SalesforceApi->requestQueryAllAndHandle('https://acquia-...', Array, 'Contact', Array)
#5 /var/www/html/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php(865): MauticPlugin\MauticCrmBundle\Api\SalesforceApi->getLeads(Array, 'Contact')
#6 /var/www/html/app/bundles/PluginBundle/Command/FetchLeadsCommand.php(165): MauticPlugin\MauticCrmBundle\Integration\SalesforceIntegration->getLeads(Array, Array, Array, Array, 'Contact')
#7 /var/www/html/vendor/symfony/console/Command/Command.php(298): Mautic\PluginBundle\Command\FetchLeadsCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Mautic\PluginBundle\Command\FetchLeadsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Mautic\PluginBundle\Command\FetchLeadsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/bin/console(16): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main} ["hostname" => "mautic-web","pid" => 2115]
```
I used a shortcut and changed the `$deduplicate` property from `protected` to `public` in `app/bundles/CoreBundle/Entity/Notification.php` on line number `55` **just for testing this out**

**Comment by aarohiprasad** [comment]
@escopecz the failing test case is completely unrelated to this PR. I ran it on local and it runs fine, without any errors. Can we ignore this failure?

**Comment by escopecz** [comment]
@aarohiprasad I retriggered the CI and it's green now

**Comment by dadarya0** [comment]
> Verified with same steps mention in step to test but getting exception
> 
> ```
> 12:56:12 ERROR     [mautic] Mautic\PluginBundle\Exception\ApiErrorException: {"error":{"message":"[{\"message\":\"\\nselect Id, Company,Email,LastName,SF_date__c, ConvertedContactId from\\n                                  ^\\nERROR at Row:1:Column:35\\nNo such column 'SF_date__c' on entity 'Lead'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.\",\"errorCode\":\"INVALID_FIELD\"}]","code":400}} (uncaught exception) at /var/www/html/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php line 1722 while running console command `mautic:integration:fetchleads`
> [stack trace]
> #0 /var/www/html/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php(1218): MauticPlugin\MauticCrmBundle\Integration\SalesforceIntegration->getMauticContactsToCreate(Array, Array, 'l.email, l.last...', 100, '2024-06-11 12:5...', '2024-06-21 12:5...', 0, Object(Symfony\Component\Console\Helper\ProgressBar))
> #1 /var/www/html/app/bundles/PluginBundle/Command/FetchLeadsCommand.php(231): MauticPlugin\MauticCrmBundle\Integration\SalesforceIntegration->pushLeads(Array)
> #2 /var/www/html/vendor/symfony/console/Command/Command.php(298): Mautic\PluginBundle\Command\FetchLeadsCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #3 /var/www/html/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #4 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Mautic\PluginBundle\Command\FetchLeadsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #5 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Mautic\PluginBundle\Command\FetchLeadsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #6 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #7 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #8 /var/www/html/bin/console(16): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #9 {main} ["hostname" => "mautic-community-web","pid" => 14373]
> 12:56:12 CRITICAL  [console] Error thrown while running command "mautic:integration:fetchleads --integration=Salesforce --time-interval='10 days'". Message: "{"error":{"message":"[{\"message\":\"\\nselect Id, Company,Email,LastName,SF_date__c, ConvertedContactId from\\n                                  ^\\nERROR at Row:1:Column:35\\nNo such column 'SF_date__c' on entity 'Lead'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.\",\"errorCode\":\"INVALID_FIELD\"}]","code":400}}" ["exception" => Mautic\PluginBundle\Exception\ApiErrorException^ { …},"command" => "mautic:integration:fetchleads --integration=Salesforce --time-interval='10 days'","message" => "{"error":{"message":"[{\"message\":\"\\nselect Id, Company,Email,LastName,SF_date__c, ConvertedContactId from\\n                                  ^\\nERROR at Row:1:Column:35\\nNo such column 'SF_date__c' on entity 'Lead'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.\",\"errorCode\":\"INVALID_FIELD\"}]","code":400}}"] ["hostname" => "mautic-community-web","pid" => 14373]
> 12:56:12 WARNING   [mautic] Command `mautic:integration:fetchleads` exited with status code 1 ["hostname" => "mautic-community-web","pid" => 14373]
> 
> In SalesforceIntegration.php line 1722:
>                                                                                                                                                                                                                                                     
>   {"error":{"message":"[{\"message\":\"\\nselect Id, Company,Email,LastName,SF_date__c, ConvertedContactId from\\n                                  ^\\nERROR at Row:1:Column:35\\nNo such column 'SF_date__c' on entity 'Lead'. If you are attemp  
>   ting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.\",\"errorCode\":\"INVALID_FIELD\"}]","code":400}}
> ```

I am also getting this error and this need to be fixed otherwise it will throw error on every sync request.

**Review by dadarya0 — APPROVED** [review]
Thanks @aarohiprasad , Tested, now working fine.

**Review by escopecz — APPROVED** [review]
Thanks! The code changes look good 👍

**Pull request merged**
