### PR TITLE
TPROD-304: Deprecated LogoutHandlerInterface, register a listener on the LogoutEvent event instead.

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR removes deprecated code and replaces with new event listeners from Symfony. 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Logout from Mautic 
3. Make sure the session is deleted

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
The code makes sense. 👍 

_Please update the description of this PR._

**Comment by mabumusa1** [comment]
> The code makes sense. +1
> 
> _Please update the description of this PR._

Thanks, Updated

**Review by volha-pivavarchyk — COMMENTED** [review]
I get an error when logging out 

image

**Comment by escopecz** [comment]
This is blocking testing of https://github.com/mautic/mautic/pull/12434

**Comment by mabumusa1** [comment]
> This is blocking testing of #12434

@escopecz Please test again, It should be working, would be optimal if we have a functional test for it. I am a bit busy today to write it **Ignore this comment, I wrote a test for it**

@volha-pivavarchyk Can you test again?

**Comment by volha-pivavarchyk** [comment]
Yes, of course

**Review by escopecz — APPROVED** [review]
Thank you! This is fixing currently broken log out. I can log in as well. Great work!

**Review by volha-pivavarchyk — APPROVED** [review]
Works as described

**Pull request merged**
