### PR TITLE
The tab Permissions should be hidden when "Has full system access?" is set to Yes

### LINKED ISSUE #13441: [UX] The tab Permissions should be disabled when "Has full system access?" is set to Yes
This issue happens when creating a new role.
Currently, the “Permissions” tab is visible even when the “Has full system access?” option is set to “Yes”.

When opening it, the tab is blank, so it can indeed lead to confusion and may give an impression of another incomplete or faulty feature. 

This issue can be resolved by hiding the “Permissions” tab when “Has full system access?” is set to “Yes”.

To reach where this bug happens, follow these steps:

1. Open Mautic
2. Open the right sidebar
3. Click on Roles
4. Create a new role (+ New)
5. Set "Has full system access?" to Yes
6. Click on Permissions tab to find it blank

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by nox1134**
Fixes #13441 by @andersonjeccel 

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Hide the "Permissions" tab in the role creation interface when "Has full system access?" is set to "Yes". This prevents confusion and ensures a smoother user experience by removing access to an irrelevant tab.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open mautic and open the right sidebar
3. Click on Roles
4. Create a new role (+ New)
4. Set "Has full system access?" to "Yes" and click save.
5. Verify that the "Permissions" tab is hidden.
6. Set "Has full system access?" to "No" and click save and verify that the "Permissions" tab becomes visible again.

#### Screenshots:
image
image

### CODE REVIEW

**Review by andersonjeccel — APPROVED** [review]
Seems great!
Thanks for this fix

**Comment by andersonjeccel** [comment]
@Esthertests Would you like to test it?

**Comment by andersonjeccel** [comment]
@nox1134 
Oh, the CS test failed (fast to fix, it's only a spacing problem)

**Comment by andersonjeccel** [comment]
@rohit-sharma-1802 We would appreciate a test here 🙏

**Review by escopecz — CHANGES_REQUESTED** [review]
It should be hidden in JS, not PHP. What if I want to change a role from full system access to a specific role? The tab will never appear:
Screenshot 2024-03-26 at 09 15 39

**Comment by andersonjeccel** [comment]
Hey @nox1134!
Would you have time to implement the suggested changes by John?

Thanks in advance!

**Comment by LordRembo** [comment]
@andersonjeccel Maybe this is also a thing that @mallezie could look at next week?

**Comment by andersonjeccel** [comment]
If Priyanshi didn't start yet and prefer to let Tim do it, that's fine

**Comment by nox1134** [comment]
Hi @andersonjeccel ! I've started working on this issue, but if I encounter any issues, Tim can collaborate on it.
Thank you!

**Comment by andersonjeccel** [comment]
@nox1134 thanks!

**Comment by nox1134** [comment]
@escopecz, the changes will only appear when you click save. So, when I set 'has full system access?' to 'no' and then click save, the permission tab appears.

**Comment by escopecz** [comment]
Isn't that confusing? I'm wondering whether it is better than the current state. A bit of JS would do it more interactively.

**Comment by LordRembo** [comment]
Having a message or notification appear, when the Permissions tab (dis)appears, would help with confusion I think. Or at least have a bit of text underneath the 'full system access'-switch that explains what happens when you toggle it.
You see the same thing in accessibility guidelines: make sure the user understands the purpose of a content change and make it detectable (in our case, a visual indication like a notification of message)

**Comment by andersonjeccel** [comment]
@LordRembo I can add a tooltip, what do you think?

**Comment by LordRembo** [comment]
@andersonjeccel I think @escopecz had the right idea here, changing the state of the 'Permissions' tab would be better when you toggle the switch, rather then on Save. That gives immediate visual feedback while the person is working. Then it also makes sense to add info in the Toggle switch tooltip, about the availability of Permissions. That just gives some extra info.
I would also suggest never hiding the tab, but simply disabling it when it's not in use. That way, the person managing a user's access at least can see that this is a potential option.

If you really want to do the changes to the 'Permissions' tab on 'Save', there's 2 things to make things less confusing:
- Don't rely on just the Tooltip. They are really bad at giving people information IF they don't know they are missing information. And since they don't see the Permissions tab unless they Save, they need an extra visual thing. Eg. an info message, a bit of text above/under the toggle, …
- disable/enable the tab, instead of hiding it.

**Comment by andersonjeccel** [comment]
@LordRembo Ok, I’ll wait for @nox1134 to finish this PR (he’s the author) then I work on the help solution in separate 

As he probably gave up on this task, I’d like to ask you if there’s a possibility for Tim to catch some of those issues on UX/UI TT project

We have a few bugs like these still open

**Comment by nox1134** [comment]
Hi @andersonjeccel ! Apologies for wasting so much time. Tim can work on this issue if he is still available.

**Comment by andersonjeccel** [comment]
Hey there! Thanks for your contribution to the project. Just wanted to let you know that the issue this PR was addressing has actually been fixed in another PR that's already been merged. So, I'm going to go ahead and close this one to avoid any confusion. Really appreciate your effort though! Feel free to check out our open issues if you'd like to tackle something else. Thanks again!

**Pull request closed without merging**
