### PR TITLE
Improve grammar for unhide

### PR DESCRIPTION
**Pull request by RCheesley**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

The terminology used of 'unhide' when reversing the action to hide a theme is grammatically incorrect. It should instead be 'reveal' or the more commonly used, 'show'.

I've opted for 'show'.

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Hide a core theme
3. Check what the wording says to display the theme again

### CODE REVIEW

**Comment by andersonjeccel** [comment]
It seems like you have to change a test too

**Review by shinde-rahul — APPROVED** [review]

**Review by escopecz — APPROVED** [review]

**Comment by escopecz** [comment]
@RCheesley it will also have to update the failing test with the new label.

**Comment by RCheesley** [comment]
Test should hopefully be fixed! 👀

**Review by escopecz — APPROVED** [review]
Thanks!

**Pull request merged**
