### PR TITLE
Upgrade dependencies (BC breaks) in preparation for PHP 8.0 support

### PR DESCRIPTION
**Pull request by RaphaelWoude**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | features
| Bug fix?                               | no
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | yes
| Automated tests included?              | no
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | Fixes #N/A

#### Description:

Updates/upgrades many of Mautic's dependencies in preparation of adding PHP 8.0 support. Although PHP 8.0 support can be added after Mautic 4 has been released, some packages have BC breaks which we already need to tackle now.

Most notably, this PR includes a refactor of `joomla/http` (`mautic.http.connector`) to Guzzle (`mautic.http.client`). More details have been added to `UPGRADE-4.0.md`.

**We had to temporarily disable Rector since it is incredibly slow and throwing dozens of errors on newer versions, which will need more investigation later**. Also lots of `Can't handle this situation`. Example run where you can see this: https://github.com/mautic/mautic/runs/2213233300

#### Things that need testing
- Pretty much all of Mautic, but since we plan to include this PR in 4.0 Alpha we'll be testing extensively anyway.

#### Some blockers for PHP 8.0 support moving forward

Though we've already updated many dependencies in preparation for PHP 8.0, some of them don't support 8.0 yet. The good news is that most of them work on 8.0 already but don't explicitly declare support in their `composer.json` files. Here's an overview of dependencies that have 8.0 support in progress, and which we can move to a separate issue later for follow-up:

- `friendsofsymfony/oauth2-php` is not PHP 8.0-ready. Turns out we're lucky and someone just created a PHP 8 PR: https://github.com/FriendsOfSymfony/oauth2-php/pull/125 - looks like no changes are needed on our side apart from just bumping the dependency
- `joomla/filter` already seems to support PHP 8.0 (their test suite runs against it), but it doesn't explicitly declare support in their `composer.json`. Created a PR for that: https://github.com/joomla-framework/filter/pull/46
- `noxlogic/ratelimit-bundle` has PHP 8.0 support in progress. Looks like no changes from our side are required apart from updating the dependency when it's ready: https://github.com/jaytaph/RateLimitBundle/pull/113
- `mautic/transifex` already works on PHP 8.0, just had to declare explicit support for it: https://github.com/mautic/Transifex-API/pull/3
- `friendsofsymfony/oauth-server-bundle` is working on a new major version, but it's not finished yet, so we can't update just yet. However, they have removed PHP templating support in favor of Twig. Since Mautic still heavily relies on PHP templates, we wouldn't be able to update this dependency once we work on PHP 8.0 support. Created a PR to re-add the templating engine: https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/pull/676

#### Steps to test this PR:
1. Checkout this PR locally
2. Ensure that `composer install` works and that you're able to access Mautic's dashboard
3. A code review would be good, but is challenging given the amount of changes and `joomla/http` refactor. The refactoring specifically took place in https://github.com/mautic/mautic/pull/9833/commits/bb0b6c15f3407e9a72b5fbd9ca5dcbca7e38c4da

### CODE REVIEW

**Comment by RCheesley** [comment]
Super excited for this - thanks for getting involved in the sprint @RaphaelWoude !

@cla-bot check

**Comment by RaphaelWoude** [comment]
# **Updated most of the dependencies to php version 8.0. 🚀**
Couple things to note.

### The 2 post install scripts are currently giving me an error after updating.
```                                                                                                                                  
[InvalidArgumentException]                                                                                                                                     
Invalid symfony/flex auto-script in composer.json: "php -r "if(file_exists('./.git')&&file_exists('./build/hooks/pre-commit'.(PHP_OS=='WINNT'?'.win':''))){co  
py('./build/hooks/pre-commit'.(PHP_OS=='WINNT'?'.win':''),'./.git/hooks/pre-commit');} if(file_exists('./.git')&&file_exists('./build/hooks/post-checkout')){  
copy('./build/hooks/post-checkout','./.git/hooks/post-checkout');}"" is not a valid type of command.        
```     
~For now I removed them from the composer.json to keep going with the update. Needs to be added back later!~ FIXED! 😄           
                                                                                                                                                                 
### Sensio package was blocking the update of a couple packages and does not support php 8.0.
For now I removed it from the composer.json to keep going with the update. Needs to be added back later!
`"sensio/framework-extra-bundle": "~3.0",`

**Comment by dennisameling** [comment]
We have a working dashboard now on PHP 7.4 after all the dependency updates - next step is to get PHP 8.0 working, which will be a challenge! 🤓 

image

**Comment by dennisameling** [comment]
@alanhartless this is ready for review! Thanks in advance 🚀

**Comment by alanhartless** [comment]
This is a lot! Nothing caught my eye as needing attention looking through the code changes. I installed other languages successfully and I tried to authorize Salesforce but hit the `The "logger" service or alias has been removed or inlined when the container was compiled.` bug that I think was fixed in another PR. 

I also tested fetching access tokens with oauth2 through postman and that seemed to work as well. 

I say we get this merged ASAP as I know other PRs will need to make some changes (such as the new Doctrine namespaces).

**Review by alanhartless — APPROVED** [review]

**Comment by dennisameling** [comment]
For the person merging this: could we please do a `Merge pull request` instead of `Squash and merge` this time? Would especially like to keep the `joomla/http` refactoring in a separate commit! https://github.com/mautic/mautic/pull/9833/commits/bb0b6c15f3407e9a72b5fbd9ca5dcbca7e38c4da

Also @RCheesley we'll need to let go of the required Rector check for now, more details above. Already created a Jira issue for this. Would you mind updating the branch protection rules accordingly? Thanks!

**Comment by jaytaph** [comment]
FYI: the noxlogic/ratelimitbundle v1.17.0 is php8 compatible.

**Pull request merged**
