### PR TITLE
Use sendRawEmail instead of SendBulkTemplatedEmail for Amazon SES API

### LINKED ISSUE #9136: Mautic 3.1 Bounce Chart not updating
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The chart on the emails doesn't show the number of bounces. I think this is a legacy bug as I've never actually had this work.

| Q   | A
| --- | ---
| Mautic version | 3.0.1 - 3.1.0

### Steps to reproduce
1. Send an email that bounces - I'm using Amazon SES and SNS.
2. Email successfully bounces, but the email chart doesn't show how many bounced from that email.
 
mautic-bounce-chart

### PR DESCRIPTION
**Pull request by wise-gorilla**
SendBulkTemplatedEmail previously used had some limitations, it doesn't support custom headers which caused an issue with bounce reporting, custom headers also helpful to add "List-Unsubscribe" which help to avoid the spam folder.

Unlike many may expect the change to use sendRawEmail instead of SendBulkTemplatedEmail will not have a big impact on the sending speed, the oposite may happen actually especially on powerful servers, for instance i was able to send a fully graphical email to 100 contact in 1.2 second using "Send immediately" on a shared hosting, on other hand the SendBulkTemplatedEmail is limited to 50 recebient per API call and most likely it cant send more than 100 email per second.

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging for features or enhancements / 3.0 for bug fixes 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | yes
| BC breaks?                             | no
| Automated tests included?              | no
| Issue(s) addressed                     | Fixes #9136 and #9137

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2.

### CODE REVIEW

**Review by jclimac — DISMISSED** [review]
This looks good. I have applied and tested this PR on my Mautic instance on production and its working great so far.

**Comment by benfavre** [comment]
When using the default current setup to send some emails with no attachements (SendBulkTemplatedEmail) I have several issues : 
- some emails do not get sent
- thoses that do have issues with character encoding (sender name)

Forcing Mautic 3.1 to use sendRawEmail by commenting out the check for attachements fixes all the sending issues I am having.
`/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonApiTransport.php l195`

Maybe SendBulkTemplatedEmail is a good tool to have ? (OP seems to imply otherwise) but currently it needs some more work since it has regressions.

DefaultinG to sendRawEmail for now seems like a huge step up from SMTP without any downsides.

**Comment by wise-gorilla** [comment]
> When using the default current setup to send some emails with no attachements (SendBulkTemplatedEmail) I have several issues :
> 
> * some emails do not get sent
> * thoses that do have issues with character encoding (sender name)
> 
> Forcing Mautic 3.1 to use sendRawEmail by commenting out the check for attachements fixes all the sending issues I am having.
> `/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonApiTransport.php l195`
> 
> Maybe SendBulkTemplatedEmail is a good tool to have ? (OP seems to imply otherwise) but currently it needs some more work since it has regressions.
> 
> DefaultinG to sendRawEmail for now seems like a huge step up from SMTP without any downsides.

T

> When using the default current setup to send some emails with no attachements (SendBulkTemplatedEmail) I have several issues :
> 
> * some emails do not get sent
> * thoses that do have issues with character encoding (sender name)
> 
> Forcing Mautic 3.1 to use sendRawEmail by commenting out the check for attachements fixes all the sending issues I am having.
> `/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonApiTransport.php l195`
> 
> Maybe SendBulkTemplatedEmail is a good tool to have ? (OP seems to imply otherwise) but currently it needs some more work since it has regressions.
> 
> DefaultinG to sendRawEmail for now seems like a huge step up from SMTP without any downsides.

@benfavre It would be great if you can test this PR ans submit review to help to get it merged with the next Mautic release 3.1.1
Also it would be great if you can report your sending speed after testing this PR.

**Comment by ghost** [comment]
I get base64 encoding issues when I tested the emails against mail-tester.com.

```
-2.636	BASE64_LENGTH_78_79	BASE64_LENGTH_78_79
-2.019	BASE64_LENGTH_79_INF	base64 encoded email part uses line length greater than 79 characters
```

**Comment by wise-gorilla** [comment]
> I get base64 encoding issues when I tested the emails against mail-tester.com.
> 
> ```
> -2.636	BASE64_LENGTH_78_79	BASE64_LENGTH_78_79
> -2.019	BASE64_LENGTH_79_INF	base64 encoded email part uses line length greater than 79 characters
> ```

@parewa-aswin Thanks for reporting that issue, fixed it and the email score now is 10/10 on mail-tester.com

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by benfavre** [comment]
Having issues with outlook showing the mail as having an attachment even when there is none with the current implementation of this PR.

Here is what I have for now. It's still missing a fix for some caracter encoding issue in the subjet and sender name.
```php
public function buildRawMessage($msg, $recipient)
    {
        $separator           = md5(time());
        $separator_multipart = md5($msg['subject'].time());
        $message             = "MIME-Version: 1.0\n";
        $message .= 'Subject: '.$msg['subject']."\n";
        $message .= 'From: '.$msg['from']['name'].' <'.$msg['from']['email'].">\n";
        $message .= "To: $recipient\n";
        if (count($msg['recipients']['cc']) > 0) {
            $message .= 'Cc: '.implode(',', array_keys($msg['recipients']['cc']))."\n";
        }
        if (count($msg['recipients']['bcc']) > 0) {
            $message .= 'Bcc: '.implode(',', array_keys($msg['recipients']['bcc']))."\n";
        }
        if (isset($msg['replyTo'])) {
            $message .= 'Reply-To: '.$msg['replyTo']['email']."\n";
        }
        if (isset($msg['returnPath'])) {
            $message .= 'Return-Path: '.$msg['returnPath']."\n";
        }
        $message .= "Content-Type: multipart/alternative; boundary=\"$separator_multipart\"\n";
        if (isset($msg['headers'])) {
            foreach ($msg['headers'] as $key => $value) {
                $message .= "$key: ".$value."\n";
            }
        }
        $message .= "\n--$separator_multipart\n";

        $message .= "Content-Type: text/alternative; boundary=\"$separator\"\n";
        if (isset($msg['text']) && strlen($msg['text']) > 0) {
            $message .= "\n--$separator\n";
            $message .= "Content-Type: text/plain; charset=\"UTF-8\"\n";
            $message .= "Content-Transfer-Encoding: base64\n";
            $message .= "\n".wordwrap(base64_encode($msg['text']), 76, "\n", true)."\n";
        }
        $message .= "\n--$separator\n";
        $message .= "Content-Type: text/html; charset=\"UTF-8\"\n";
        $message .= "\n".$msg['html']."\n";
        $message .= "\n--$separator--\n";


        foreach ($msg['attachments'] as $attachment) {
            $message .= "--$separator_multipart\n";
            $message .= 'Content-Type: '.$attachment['type'].'; name="'.$attachment['name']."\"\n";
            $message .= 'Content-Disposition: attachment; filename="'.$attachment['name']."\"\n";
            $message .= "Content-Transfer-Encoding: base64\n";
            $message .= "\n".$attachment['content']."\n";
        }

        return $message."--$separator_multipart--";
    }
`

**Comment by wise-gorilla** [comment]
> Having issues with outlook showing the mail as having an attachment even when there is none with the current implementation of this PR.
> 
> Here is what I have for now. It's still missing a fix for some caracter encoding issue in the subjet and sender name.
> 
> ```
> public function buildRawMessage($msg, $recipient)
>     {
>         $separator           = md5(time());
>         $separator_multipart = md5($msg['subject'].time());
>         $message             = "MIME-Version: 1.0\n";
>         $message .= 'Subject: '.$msg['subject']."\n";
>         $message .= 'From: '.$msg['from']['name'].' <'.$msg['from']['email'].">\n";
>         $message .= "To: $recipient\n";
>         if (count($msg['recipients']['cc']) > 0) {
>             $message .= 'Cc: '.implode(',', array_keys($msg['recipients']['cc']))."\n";
>         }
>         if (count($msg['recipients']['bcc']) > 0) {
>             $message .= 'Bcc: '.implode(',', array_keys($msg['recipients']['bcc']))."\n";
>         }
>         if (isset($msg['replyTo'])) {
>             $message .= 'Reply-To: '.$msg['replyTo']['email']."\n";
>         }
>         if (isset($msg['returnPath'])) {
>             $message .= 'Return-Path: '.$msg['returnPath']."\n";
>         }
>         $message .= "Content-Type: multipart/alternative; boundary=\"$separator_multipart\"\n";
>         if (isset($msg['headers'])) {
>             foreach ($msg['headers'] as $key => $value) {
>                 $message .= "$key: ".$value."\n";
>             }
>         }
>         $message .= "\n--$separator_multipart\n";
> 
>         $message .= "Content-Type: text/alternative; boundary=\"$separator\"\n";
>         if (isset($msg['text']) && strlen($msg['text']) > 0) {
>             $message .= "\n--$separator\n";
>             $message .= "Content-Type: text/plain; charset=\"UTF-8\"\n";
>             $message .= "Content-Transfer-Encoding: base64\n";
>             $message .= "\n".wordwrap(base64_encode($msg['text']), 76, "\n", true)."\n";
>         }
>         $message .= "\n--$separator\n";
>         $message .= "Content-Type: text/html; charset=\"UTF-8\"\n";
>         $message .= "\n".$msg['html']."\n";
>         $message .= "\n--$separator--\n";
> 
> 
>         foreach ($msg['attachments'] as $attachment) {
>             $message .= "--$separator_multipart\n";
>             $message .= 'Content-Type: '.$attachment['type'].'; name="'.$attachment['name']."\"\n";
>             $message .= 'Content-Disposition: attachment; filename="'.$attachment['name']."\"\n";
>             $message .= "Content-Transfer-Encoding: base64\n";
>             $message .= "\n".$attachment['content']."\n";
>         }
> 
>         return $message."--$separator_multipart--";
>     }
> `
> ```

@benfavre Can you give me more details about the characters encoding issue

**Comment by benfavre** [comment]
image

**Comment by wise-gorilla** [comment]
@benfavre Fixed the attachment on Outlook, I tested the character encoding and it works fine for me except for emoji
image

**Comment by ghost** [comment]
@Wise-Gorilla just wanted to know if it respects `Do not contact more than` (49.9k in my case) number? I just an email to about 130k subs the other day, Mautic reported it sent the email to all of them on the same day. However, my limit on SES is ~60k and I didn't see any emails sent after 24 hours on SES dashboard.

**Comment by benfavre** [comment]
More fixes for the buildRawMessage function related mostly to header encoding
https://github.com/webdesign29/mautic/blob/efc768009a34facbfa25ffe5eb91881d2daa87de/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonApiTransport.php#L273

**Comment by RCheesley** [comment]
Hi folks, thanks for all the hard work to address this issue!  Great to see you all coming together to work on this problem.

If we want to get this into the 3.1.1 release we will need to be clear on what this PR is addressing and get it to an 'end point' at which we will need to get a couple of good tests and a code review (as things have changed since the earlier 👍 's). 

That all needs to happen by **midnight this Sunday**.

At the moment it seems like there may still be some work that is needed to get it into a 'finished and ready to test' state? Do we think that we can get it over the line in time? If not I will tag it for the 3.1.2 release at the end of October.

**Comment by wise-gorilla** [comment]
> More fixes for the buildRawMessage function related mostly to header encoding
> https://github.com/webdesign29/mautic/blob/efc768009a34facbfa25ffe5eb91881d2daa87de/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonApiTransport.php#L273

@benfavre Thanks for that fix, I added it to the PR after doing some edits on your code since attachment didn't work on Outlook using your code, would be great if you test it and reviewed the PR code.

**Comment by RCheesley** [comment]
@Wise-Gorilla looks like there's a code style fix needed according to Travis :)

**Comment by RCheesley** [comment]
Hi folks, 

Thanks for all the work on this! As there has not been sufficient time for rigorous testing on this PR we are going to bump it to 3.1.2.

To be considered we need to have the PR finalised with all tests passing, and have sufficient tests/code reviews, by **18th October**.

**Comment by wise-gorilla** [comment]
@RCheesley Since the SES API version that got released had some issues even when using send immediately and this PR fixed those issues but still still email queue not working so i suggest to release this PR with 3.1.1 and then add the queue support later since not doing so will leave the SES API functionality not usable for many users especially for users who has a sending limit under 50/second.

**Comment by wise-gorilla** [comment]
> @Wise-Gorilla just wanted to know if it respects `Do not contact more than` (49.9k in my case) number? I just an email to about 130k subs the other day, Mautic reported it sent the email to all of them on the same day. However, my limit on SES is ~60k and I didn't see any emails sent after 24 hours on SES dashboard.

The current transport dont queue the emails to the next day yet, You can contact Amazon to increase your sending limit if you wanna send more than 60k at one day

**Comment by RCheesley** [comment]
@Wise-Gorilla I discussed this with @mabumusa1 and we both feel that the PR required more testing before being included in a release, so we can look to consider it for 3.1.2.

**Comment by mabumusa1** [comment]
Hi folks,

I am closing this PR in favor of this https://github.com/mautic/mautic/pull/9290, I had to restructure the whole integration to use Version 2 of the API provided by AWS. 

Please test the other PR and provide any feedback and testing you have to get it merged for the next release.

Thanks,

**Pull request closed without merging**
