### PR TITLE
Fix report asset downloads counts

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.3
| Bug fix?                               | ✅ 
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | 
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
This PR fix the count of assets downloads in reports in selected time frame.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create assets
3. Make download from two contacts - one download yesterday, second download today (two times)
4. Create report asset downloads with asset name, download count and unique download count
5. Select time frame for today
6. You should see count 3 downloads and  2 unique downloads on assets, but expected 2 downloads and 1 unique download for today
7. After fix should works properly
8. Try also reorder results by download count and download unique count

### CODE REVIEW

**Comment by fedys** [comment]
@kuzmany I tested the scenario and it didn't work as expected. I might have done something wrong. See the screenshots:
Snímek obrazovky 2021-03-09 v 13 28 49
Snímek obrazovky 2021-03-09 v 13 43 05
Snímek obrazovky 2021-03-09 v 13 32 06
Snímek obrazovky 2021-03-09 v 13 32 28

**Comment by kuzmany** [comment]
@fedys you should change date range for report to 9. march

image

**Comment by fedys** [comment]
@kuzmany sorry, my bad. I thought I had `Mar 9 to Mar 9`. I will re-check.

**Comment by fedys** [comment]
@kuzmany It's working as expected when I changed the date range appropriately 🙂 

Snímek obrazovky 2021-03-09 v 16 37 08

**Review by escopecz — CHANGES_REQUESTED** [review]
The fix is working 👍 

However, it lacks tests.

@kuzmany please add the test automatically so the reviewers won't have to request it every time.

**Comment by RCheesley** [comment]
If we can get tests to cover this then we are good to merge with two approvals!

**Comment by kuzmany** [comment]
@escopecz I know I have a debt with unit tests, usually caused by lack of time, I will try cover unit tests as soon as possible.

**Comment by escopecz** [comment]
I'll write tests for this so we can merge it in 3.3.3 as I have a moment.

**Comment by RCheesley** [comment]
Awesome thank you @escopecz ! 🎉

**Review by escopecz — APPROVED** [review]
I added the tests. This is good to go 👍

**Pull request merged**
