### PR TITLE
TPROD-344: Update to Symfony 5

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR will contain the minimal steps to switch to Symfony 5, without updating any non-crucual dependency.
This is on purpose, to ensure we can address issues one at a time, and not have to take into account side effects from other dependencies.

* minimal changes
    * [minimal dependency changes to switch to symfony 5](https://github.com/mautic/mautic/pull/12213/commits/ad4d991ea4f042117bd2bad822c52bca8ddf1ded)
        ```
        composer update leezy/pheanstalk-bundle litesaml/lightsaml lightsaml/sp-bundle symfony/*
        ```
    * [minimal config changes to be able to bootstrap Mautic](https://github.com/mautic/mautic/pull/12213/commits/d5137701ee7d522b325bfb0eda738ddfb14b71c5)
    * [minimal changes to be able to run tests (regardless of failures)](https://github.com/mautic/mautic/pull/12213/commits/b22252e671e9d9d0f6f0d7d3c81e47772dc39d42)
* a lot of changes to fix the tests and PHPSTAN compatibility (most important ones listed below)
    * [ensure that EventDispatcherInterface::dispatch() calls return the event](https://github.com/mautic/mautic/pull/12213/commits/5f5406ba04b75122205763402133c569f2324cb0)
    * https://github.com/symfony/symfony/issues/38627
        * [mocking event classes is not allowed anymore](https://github.com/mautic/mautic/pull/12213/commits/e9006ae93853b3910c2d65576b8a4809d482098a) 
        *  [workaround to test final ControllerEvent](https://github.com/mautic/mautic/pull/12213/commits/81d296a02e9fcb08f63e2803f20ea27f4df0fb8e)
    * [use InputBag for POST requests too, added missing scalar type hints](https://github.com/symfony/http-foundation/commit/7f7f5e3453c99d3e1f9c6c67edadae8015ed190e)
        * [workaround for inputbag not returning arrays](https://github.com/mautic/mautic/pull/12213/commits/b6a998bdf340d9caa32bac60e026e87c5bdd2e84)
        * [use InputBag instead of ParameterBag for request params](https://github.com/mautic/mautic/pull/12213/commits/3816a0dd3b65d88f0913fd4e8d0962e82257724a)
    *   [It is possible to pass request parameters of any type to the Symfony web crawler](https://github.com/symfony/symfony/issues/37740)
        * [fix tests related to the Symfony browser-kit changes](https://github.com/mautic/mautic/pull/12213/commits/4516979746b4043ba4c9c07e2d59eb38aeb04ee4)
        * [ensure that boolean parameter in tests are compatible with Symfony br…](https://github.com/mautic/mautic/pull/12213/commits/4dc13a34f95a60948e6c3ba9a4481b4d86fc0ed4)
    * method parameter of return type changes
        * [mock extra methods to ensure return value is correct](https://github.com/mautic/mautic/pull/12213/commits/c9f6099f9842ad68479ca2d50b5c59841fa7bdf7)
        * [update parameter types based on the extended method](https://github.com/mautic/mautic/pull/12213/commits/cc63c2635e631f4bb0d791983055fa0aaa0d2fae)
        * [update parameter and return types based on the extended method](https://github.com/mautic/mautic/pull/12213/commits/8e78ef7e88ef0f6a884669ad04fc1ae084a52260)
        * [adapt code to underlaying Symfony code](https://github.com/mautic/mautic/pull/12213/commits/06f9b3f0d7c4245a6a27549bafad0c62daac4753)

#### possible issues
* making the [`CoreSubscriberTes::testOnKernelController()`](https://github.com/mautic/mautic/pull/12213/commits/81d296a02e9fcb08f63e2803f20ea27f4df0fb8e) test work
    * Due to the `final` definition of `ControllerEvent` class, we can't mock it anymore.
    * Due to the way Mautic is built, there is no clear way to make this test do the same checks as now
    * possible solutions that didn't work
        * https://github.com/dg/bypass-finals doesn't solve the issue
        * creating a fake `ControllerEvent` class for test purposes has too much impact on the actual application code
    * the current implemented approach is to change as limited as possible the application code, but IMO this is a bad practice

###### Baseline of the tests errors and failures:

```
Tests: 3318, Assertions: 9600, Errors: 36, Failures: 11, Skipped: 5.
```

PHPSTAN:
```
Found 228 errors 
```

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. install Mautic via the UI
3. Install Mautic CLI
4. review the code changes to check if they are consistent

### CODE REVIEW

**Comment by mollux** [comment]
we're at following test errors and failures:
```
Tests: 3318, Assertions: 9725, Errors: 2, Failures: 5, Skipped: 5.
```

**Comment by mollux** [comment]
test errors and failures:
```
Tests: 3318, Assertions: 9942, Errors: 2, Failures: 2, Skipped: 5.
```

PHPSTAN:
```
Found 75 errors
```

**Comment by mollux** [comment]
test errors and failures:
```
Tests: 3318, Assertions: 9942, Errors: 2, Failures: 2, Skipped: 5.
```

PHPSTAN:
```
Found 8 errors
```

**Comment by mollux** [comment]
once again codedov can't handle rebases

**Review by escopecz — APPROVED** [review]
Thank you Mattias! I see nothing wrong with the code changes I tested:
- Creating a campaign with various events
- Creating an email with builder changes, visiting the preview
- Viewing contacts
- Creating segments

**Review by mabumusa1 — APPROVED** [review]
I tried several things: 

- Segments, their commands
- Campaigns, their commands
- Reports
- Emails & Forms

All worked as expected

**Comment by escopecz** [comment]
@mollux could you look into https://github.com/mautic/api-library/actions/runs/4729781677/jobs/8392678167? I run the API Library tests on this branch and we have 1 failure:

```
Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 23072768 bytes)
```

**Comment by mollux** [comment]
@escopecz hah, interesting.

I'm running the API tests locally, let's see what the result is

**Comment by mollux** [comment]
@escopecz I can't reproduce this locally

I tried multiple ways (`index_dev.php` vs `index.php`), lowered the memory limit to `64M` both for Mautic and the API, and it still works.

The tests fails with a memory limit for Mautic of `128M`

**Comment by dadarya0** [comment]
I have tested followings:-
- Contact
- Company
- Segment
- Campaign with segment/Form
- Forms 
- Email
- Page
- Assets
- Configuration

Every thing is working fine, Just found 1 issue, Page preview is not working form me

image

**Comment by escopecz** [comment]
That's weird. I've run it 3 times and it fails the same every time. Looking at the line causing the memory leak:

https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/HttpKernel/Profiler/FileProfilerStorage.php#L163

Perhaps this change would make the tests green again. https://github.com/mautic/api-library/pull/290/files#diff-9def0cf775c5847a40b42652ae378be1e447bb4972ebebb01109369161654bd9L58

Maybe Symfony 5 logs more data to the profiler. Although it's weird that you cannot reproduce it locally.

**Comment by mollux** [comment]
@dadarya0 thanks for reporting that bug!
It's not related to this PR, but I created a PR to address this: https://github.com/mautic/mautic/pull/12233

**Comment by escopecz** [comment]
API Library tests are green now 🎉 https://github.com/mautic/api-library/actions/runs/4740621774

**Pull request merged**
