### PR TITLE
Contacts assigned to imported companies added to the selected segment.

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for 4.0
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
We've added to company import segment mapping. These option allow contacts assigned to imported companies added to the selected segment. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create contacts and assign them to companies
3. Try import companies already created with assigned contacts  and select Contact segment during the import

image

4. Related contact should assigned to selected segment

image

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/9971"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
@kuzmany a bunch of conflicts to resolve here and failing tests. If you are able to provide some csv's with mock data that would be a real help to testers once the PR is in a state that it can be tested.

**Review by npracht — COMMENTED** [review]
👍🏽 nice new feature. You can easily from an Excel file with your company names (or other company UID) get all the related contacts in a segment 🚀

**Review by npracht — DISMISSED** [review]

**Comment by jos0405** [comment]
Tested, works

image

image

**Comment by RCheesley** [comment]
Taking this off the OSF board until it's rebased.

**Comment by kuzmany** [comment]
Close at the moment. We will push it again once ready to M5

**Pull request closed without merging**
