### PR TITLE
Include Amazon SNS processing

### PR DESCRIPTION
**Pull request by ecoeficiente**
Please answer the following questions:

| Q             | A
| ------------- | ---
| Bug fix?      | 
| New feature?  | x
| BC breaks?    | 
| Deprecations? | 
| Fixed issues  |  

## Description
Just a simple approach to process amazon SNS messages for bounce and complaint processing.

### CODE REVIEW

**Comment by escopecz** [comment]
Thanks a lot! 

Could you please fix the indentation to 4 spaces as described at https://github.com/mautic/mautic/blob/staging/.github/CONTRIBUTING.md ?

**Comment by ecoeficiente** [comment]
I've changed identation. Hope it's ok now.

**Comment by manuelfink** [comment]
@ecoeficiente sound like an awesome extension. Could you add some documentation as well?

**Comment by tomgoldsmith** [comment]
There seems to be an erroneous curly brace somewhere in this pull request. There is also a fair amount of trailing whitespace (less important) and some incorrect tabbing. I have got it working with some guesswork as to which curly brace to remove but if you could update this PR with a fix that would be great. Thanks!

**Comment by tomgoldsmith** [comment]
PS I forgot to say thanks for this! Its working well and we can now process SNS bounces. :-)

**Comment by ecoeficiente** [comment]
Hello Tom, I hope it is corrected now.

**Comment by iadj** [comment]
Fantastic. Just found out about Mautic and this was the first thing I was looking for!

**Comment by iadj** [comment]
@ecoeficiente How should one implement this?

**Comment by ecoeficiente** [comment]
I just followed this: https://medium.com/@AndreiVoica/how-to-integrate-mautic-with-amazon-ses-7fe066e9131c#.evoiy0iaw
Which (despite of the post last sentence) did not work until I implemented this new feature for SNS processing.

**Comment by nickian** [comment]
I tried replacing the MessageHelper.php file with the latest one you have here, but when I run `php app/console mautic:fetch:email`, I get this message for each email it processes:

`PHP Notice:  Trying to get property of non-object in /home/www/app/bundles/EmailBundle/Helper/MessageHelper.php on line 156`

This is line 156:

`$messageDetails = $this->parseBody($message->textPlain, $bouncedEmail);`

Any idea what's going on here?

**Comment by iadj** [comment]
@nickian Judging from the error, there's no `textPlain` property in the `$message` object. Try doing a var_dump of `$message` and see what it returns.

**Comment by nickian** [comment]
Nevermind! FYI, I determined this is caused by having a "Display Name" set on your SNS Topic. Leave that blank and it works!

Thanks

**Comment by maxitromer** [comment]
@ecoeficiente I think this new feature solve this #1723 too.

I don't know exactly because I don't understand the code.

Please @alanhartless can you confirm that its solved to close the open issue?

Thanks both for the new feature and the help :-)

**Pull request merged**
