### PR TITLE
Sugarcrm integration fullsync

### PR DESCRIPTION
**Pull request by clemrvt**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y 
| Related user documentation PR URL |  https://github.com/mautic/documentation/pull/164
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/3389 and https://github.com/mautic/mautic/issues/3517
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Update the SugarCRM plugin to enable full synchronization of Mautic Leads to SugarCRM Contacts and Leads and from Mautic Companies to SugarCRM Accounts, Most functionnalities are similar to Salesforce plugin.
Developped by @canal-web and @webmecanik.

[//]: # ( As applicable: )

#### Steps to test this PR:
1. Create Oauth keys in a SugarCRM 6.X instance https://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_6.5/Application_Framework/Authentication/Oauth/ (Just step 1)
2. On the Mautic side, configure the SugarCRM plugin (Sugar URL, keys, login/password)
3. On the Mautic side, configure the plugin functionnalities
4. On the Mautic side, configure the fields mapping for contacts/leads and companies
5. Run php app/console mautic:integration:fetchleads --integration=Sugarcrm
or php app/console mautic:integration:fetchleads --fetch-all --integration=Sugarcrm to synchronize all leads.
6. Optionnaly install, on the SugarCRM side, the webActivity plugin, and launch
php app/console mautic:integration:pushleadactivity
The zip from the webActivity plugin should be download from :
https://drive.google.com/file/d/0B7f6B2OD0DBrRE0tUmVTcFZNT1k/view

### CODE REVIEW

**Comment by npracht** [comment]
Thanks for that collaboration @clemrvt @webmecanik & @canal-web !
@mqueme here we go :)

**Comment by luizeof** [comment]
Works with SuiteCRM ?

**Comment by ninjoan** [comment]
Ohh boy!!! \m/

**Comment by npracht** [comment]
I've just tested it today with the last commits and modification on the documentation (commands taxonomy) and it works well.

**Comment by alanhartless** [comment]
Hi guys - can you please retest with the latest merges? I merged in staging plus #3816 because it fixed issues with wiping out fields for non object based integrations (basically everything but Salesforce and now Sugar)

**Comment by clemrvt** [comment]
Hi.
Thanks a lot. 
It tested OK for us with last line change.
Regards.

**Comment by escopecz** [comment]
I spent over a hour on step 1. I created a SugarCRM trial, but I cannot find the API credentials anywhere and I cannot find any documentation about it either. Could you please make more clear about how to get the credentials? The linked documentation doesn't provide such information either.

**Comment by dongilbert** [comment]
@clemrvt This PR has conflicts with the staging branch. Please merge the staging here to get it up to date for testing.

**Comment by escopecz** [comment]
I'm afraid we'll have to move this PR to 2.9.0, we are not able to test it in time. Help us with the above comments before 2.9.0 testing sprint, please.

**Comment by mqueme** [comment]
Pls resolve conflicts so we can test this.

**Comment by mqueme** [comment]
getting this error <Notice: Undefined index: integration_entity (uncaught exception) at /Applications/MAMP/htdocs/mautic/plugins/MauticCrmBundle/Integration/SugarcrmIntegration.php line 1292> and this error <Notice: Undefined index: email1 (uncaught exception) at /Applications/MAMP/htdocs/mautic/plugins/MauticCrmBundle/Api/SugarcrmApi.php line 417>

**Comment by mqueme** [comment]
Also after getting past errors above, Contacts are not being updated in SugarCRM. Leads did get created from Mautic to Sugar.

**Comment by mqueme** [comment]
This works for me. tested:
Full CLI sync Sugarcrm leads and contacts, pushing Mautic contacts to sugarcrm, pulling accounts from sugar.
Campaign push to integration

**Comment by ramezrafla** [comment]
I can confirm this plugin works with SuiteCRM too (which has the same api as SugarCRM v6). It also fixes a bug in required fields.

**Comment by clemrvt** [comment]
Adding partial fullsync for SugarCRM 7.x. 
Fetching Leads, Contacts and Accounts infos.  
Not fully functionnal yet.

**Comment by mqueme** [comment]
@clemrvt would it be possible to put all the SugarCRM7.x in a different PR? we would like to merge this PR for SugarCRM 6.x

**Comment by ramezrafla** [comment]
@mqueme, @clemrvt  agreed!
People still using SurgarCRM 6 and those using SuiteCRM can start using this right away.

**Comment by escopecz** [comment]
Please look at the code style issues and fix them: https://travis-ci.org/mautic/mautic/jobs/243483278#L618

**Comment by clemrvt** [comment]
I think this topic could be closed.
There is this PR for adding Sugar 7 fullsync compatibility [https://github.com/mautic/mautic/pull/4251](https://github.com/mautic/mautic/pull/4251)
And this PR for Sugar 6 only [https://github.com/mautic/mautic/pull/4247](https://github.com/mautic/mautic/pull/4247)

**Comment by mqueme** [comment]
closing this in favour of There is this PR for adding Sugar 7 fullsync compatibility #4251
And this PR for Sugar 6 only #4247

**Comment by pgorod** [comment]
Hey everyone

I apologize if this is not the appropriate place to post this, but...

[This page](https://mautic.com/help/set-sugarcrm-integration/) announcing the integration says

> How to Set Up the SugarCRM Integration
> New to Mautic in the July 2017 update (v. 2.9) is the bi-directional sync with SugarCRM. Long a favorite in the Open Source community, SugarCRM is used globally.

I'm a contributor to the SuiteCRM project and I am a bit sad to see the SuiteCRM name go unmentioned,  and seeing SugarCRM listed as "open-source". It's not open-source any more, and hasn't been for years. It's open-source turned evil, "bye, thanks for all your contributions, we're going to sell them now".

Mautic is open-source. SuiteCRM is open-source. If we wanted to invest in our open-source brotherhood, we could sell this new integration as a SuiteCRM integration, and then have a footnote casually mentioning it also works with Sugar.

I understand there are other motivations, and there are tons of SugarCRM installs (both free and paid) out there that can benefit from Mautic, and I'm not against them.

But surely Mautic can bring out the SuiteCRM aspect of this integration a bit more? Or is it considered a different integration?

(this is not meant to sound aggressive -  I come in peace and I am probably a bit biased. Please let me know what you think. Thanks!).

**Comment by jseevers** [comment]
Hello @pgorod, thanks so much for your comment, and your honesty. As an open source (OS) community we are definitely grateful for all OS solutions in our segment to work alongside. Understand that there has been no intentional motivation in our communication on one side or the other. Simply stated, there was a need for a SugarCRM integration, and one was built into the core functionality of Mautic. 

From what I understand, users of either can utilize the plugin for one or the other. However, noting that one works with the other would create challenges down the road if/when core functionality was changed for any reason.  Because they are two different solutions (although one was built from the other), we would encourage users with a need for a specific plugin/integration for SuiteCRM to develop and submit to Github.  I'm sure those users who use SuiteCRM would welcome a plugin dedicated to the functionality of the open source solution. Would you or others be willing to submit one for review?

**Comment by pgorod** [comment]
The SuiteCRM project is quite overwhelmed with too much work, and I am part of that problem... : - )
But there are a few people on a thread in the forums that are interested in Mautic, maybe somebody can help.

Anyway let me try to understand if we really need an extra plugin for this...

If I understand correctly, Mautic developed a separate solution for SugarCRM 6 and another for SugarCRM 7, because there are changes to their API's between those two versions.

Quite simply, hopefully we can say that currently SuiteCRM 7 = SugarCRM 6 (in terms of what is relevant for Mautic integration).

Then SugarCRM 7 is a separate beast, and it's closed-source, so SuiteCRM won't imitate it.

The future SuiteCRM 8 might diverge somewhat (there are promises of a new REST API), but it's not even developed yet, so it will be a long time coming. And the SuiteCRM 7.x branch will not change anything relevant, only one more version is expected in the roadmap (7.9.10) and it's aiming at unrelated things.

I believe keeping a single Mautic integration for SuiteCRM 7 / SugarCRM 6 is what makes sense. No point in splitting the integration before SuiteCRM diverges any relevant code.

I know some people tested the new Mautic code with SuiteCRM and it worked well. So maybe it is just a matter of renaming things or communicating them in the site. From what I know of the SuiteCRM roadmap, I expect this could serve well for a year or more, and that project has a lot of traction and growth, it will certainly bring in tens of thousands of new users during that time...

Apart from matters of opinion/futurology, am I at least getting the facts right about Mautic? And do my explanations of SuiteCRM roadmap change your view of this? Thanks for having this conversation.

**Comment by jseevers** [comment]
Thanks for your reply, and yes there's always room for this dialogue. 👍  While there is certainly an advantage to having a singular plugin that works for multiple systems, unfortunately co-naming/branding the plugin is not likely to happen. This would create additional work when the two solutions diverge, regardless of how far in the future this may happen. It would be my recommendation that a separate SuiteCRM plugin be created, tested, approved and added for the next round of releases. This would ensure that any collateral/documentation/etc. reflect a plugin dedicated to SuiteCRM, instead of having to tie it to a plugin that will likely have a different development trajectory. Certainly open to additional concerns, but at this point, combining them doesn't seem like good development practice.

**Comment by pgorod** [comment]
The SugarCRM 6 / SuiteCRM 7 Plugin is the most stable thing I can think of. 

SugarCRM 6 won't evolve, it's officially dead. SugarCRM 7 won't evolve in this regard, it's a branch coming to an end. The plugin could go on existing in its current form until all the users of both systems give up on them and move on to newer versions.

So there really is no rebranding needed in the future. Only a new plugin will be needed for the SuiteCRM API, but that's a matter for later, I guess the interested parties will have to come here and contribute those developments.

Should I wait for input from any more people, or are you authority here? I don't really know this community, I am an outsider...

**Comment by marfal** [comment]
Hello,

I guess I picked the right timing to post this, since we use SuiteCRM and I agree that Mautic and SuiteCRM seem to be a natural fit for open source applications that compliment each other's purpose.

I tried to implement your solution, hoping to sync SuiteCRM contacts to Mautic. The OAUTH authentication went fine and it appears that I am able to map the fields:
image

However any attempt to sync the leads using console fails:

php app/console mautic:integration:fetchleads --integration=Sugarcrm
Command to fetch contacts from integration
Fetch contacts command is starting

Fetching contacts...

0 contacts were updated and 0 contacts were created

Fetching companies
Fetch companies command is starting

0 companies were updated and 0 companies were created

Updating/creating leads from Mautic to Sugarcrm
Number of contacts pushed: 0 updated, 0 created, 0 had errors and 0 were ignored (likely duplicates or didn't match field criteria)

* * *

php app/console mautic:integration:fetchleads --fetch-all --integration=Sugarcrm
Command to fetch contacts from integration
Fetch contacts command is starting

Fetching contacts...

0 contacts were updated and 0 contacts were created

Fetching companies
Fetch companies command is starting

0 companies were updated and 0 companies were created

Updating/creating leads from Mautic to Sugarcrm
Number of contacts pushed: 0 updated, 0 created, 0 had errors and 0 were ignored (likely duplicates or didn't match field criteria)

Is there anything I missed, or is this feature not fully implemented yet? Since I would be very interested in getting this sync to work please let me know if I can contribute somehow despite my almost non existent programming skills... or if this feature is completed and functional, please advise what step am I doing incorrectly or if I missed anything that would prohibit this 2-way sync. Thank you.

My SuiteCRM Version 7.8.2 / Sugar Version 6.5.24 (Build 509)

**Comment by ssnobben** [comment]
I agree 100% with pgorod. Pls reconsider how you strategically work with real open source supporting projects where honest people dedicate 100% of their time and contribution of real open source products. Thks.

**Comment by stancel** [comment]
Hi @marfal. We have both Mautic and SuiteCRM setup as well and are working through some of the finer points of the integration now. One of the things we noticed was that it will sync existing leads from what we have seen. However, if you go into SuiteCRM and edit an existing lead and click save, or create a new lead then you should see it create one in Mautic once your cron job runs. Hope this helps.

**Comment by ssnobben** [comment]
@stancel great to know that it works with SuiteCRM and the syncing works. I would like to use it with Joomla too and hope that combination works well Mautic<-->SuiteCRM<-->Joomla

**Comment by marfal** [comment]
Hi @stancel. Thank you for your reply. I tried that, but no lead was ever created from SuiteCRM to Mautic or from Mautic to SuiteCRM. I tried to push from campaign, etc. :( It seems I am not the only one running into these problem.

Would you mind sharing which ver of SuiteCRM and Mautic are you running? Finally, which CRON job are you referring to? The mautic:webhooks:process?

Thanks.

**Comment by stancel** [comment]
Hi @marfal. We are running SuiteCRM 7.9.4 and Mautic 2.9.2. We have tested there and with Mautic Pull Request #4445 as we have encountered a few issues (see #4746 from my colleague). For the plain 7.9.4 version / tagged commit below is the cron job we are using when manually testing and trying to pull over many contacts:
php /var/www/html/app/console mautic:integration:fetchleads --time-interval="29 days" --integration=Sugarcrm

However, for the standard cron job I have this:
php /var/www/html/app/console mautic:integration:fetchleads --integration=Sugarcrm

When testing pull request #4445 we the "--fetch-all" parameter started working for us again where it had not been before (not sure because I saw references to this param in the code of 7.9.4), but that is a different story.
php /var/www/html/app/console mautic:integration:fetchleads --fetch-all --time-interval="29 days" --integration=Sugarcrm

Overall things look good but our main problem right now is that when the sync happens from SuiteCRM --> Mautic it does not assign an Account to a Contact (Mautic - Contact to a Company). That and the State field is left out in the sync of SuiteCRM: Accounts: State --> Mautic:Company:State. All of those details and steps are in issue #4746 as referenced earlier.

I saw that the version 2.10.0 milestone just hit 100% today so hopefully this next release will alleviate your issues and the ones we're seeing.

**Comment by ssnobben** [comment]
How much of features would you be possible to solve with a CRM/Marketing automation compared to solutions like Volocify loanengage you think?  https://velocify.com/products/velocify-loanengage-overview/

**Comment by hugovictor10** [comment]
Very well friends.
What I mean is that SuiteCRM died for everyone. It will only exist for the bastards who charge $ 120 a year to link to Mautic for linking free software! For all of us who love Mautic's free code, we have SuiteCRM, a junk that only serves the interest of these outcasts.
Run away from SuiteCRM, this shit has no integration with Mautic, it's just wasting precious time.

And please my friends, a simple solution.

**Pull request closed without merging**
