### PR TITLE
Add company_id search command

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
In some cases search from company list based on company name does not work for us. We add new company based on company_id

#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2. Create contacts and assign them to company
3. Go to company list
4. See if click on number of contacts works like before 

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10702"></a>

### CODE REVIEW

**Review by volha-pivavarchyk — APPROVED** [review]
Works as expected. Clicking on the number of contacts works as before

**Comment by RCheesley** [comment]
As this is an enhancement of the feature, I'm switching up the milestone to 4.3.

**Comment by kuzmany** [comment]
@RCheesley it fixed bug related to the closed PR https://github.com/mautic/mautic/pull/10126

**Comment by RCheesley** [comment]
OK, but it's labeled with enhancement and it seems that it's adding an extra query to improve the search capability for companies, is that correct? A bit confusing if it's a bug fix in that case (and it's based on the 4.x branch for the next minor release also, so if it's considered a bug fix that would need addressing as well)

**Review by jos0405 — APPROVED** [review]
This works as described.

image

**Pull request merged**
