### PR TITLE
Fix resubscribe action condition check - 5.x

### LINKED ISSUE #11784: Fatal error when resubscribe action does not find email
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When calling PublicController::resubscribeAction, if the email stat entity is not found, then we get an error from a faulty check in the code: 
https://github.com/mautic/mautic/blob/4.4/app/bundles/EmailBundle/Controller/PublicController.php#L366

This is due to the fact that we do a regular cleanup of old email stats, we end up having this error on occasions.

### How can we reproduce this issue?

Delete email stats from database and trigger a resubscribe action on an email.

### Relevant log output

```shell
Uncaught exception 'Error' with message 'Call to a member function getTemplate() on bool' in /var/www/html/app/bundles/EmailBundle/Controller/PublicController.php:366
 in Mautic\EmailBundle\Controller\PublicController::resubscribeAction called at /var/www/html/vendor/symfony/http-kernel/HttpKernel.php (169)
 in Symfony\Component\HttpKernel\HttpKernel::handleRaw called at /var/www/html/vendor/symfony/http-kernel/HttpKernel.php (81)
 in Symfony\Component\HttpKernel\HttpKernel::handle called at /var/www/html/vendor/symfony/http-kernel/Kernel.php (201)
 in Symfony\Component\HttpKernel\Kernel::handle called at /var/www/html/app/AppKernel.php (115)
 in AppKernel::handle called at /var/www/html/app/middlewares/CORSMiddleware.php (82)
 in Mautic\Middleware\CORSMiddleware::handle called at /var/www/html/app/middlewares/CatchExceptionMiddleware.php (34)
 in Mautic\Middleware\CatchExceptionMiddleware::handle called at /var/www/html/app/middlewares/VersionCheckMiddleware.php (58)
 in Mautic\Middleware\VersionCheckMiddleware::handle called at /var/www/html/app/middlewares/TrustMiddleware.php (42)
 in Mautic\Middleware\TrustMiddleware::handle called at /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php (23)
 in Stack\StackedHttpKernel::handle called at /var/www/html/vendor/stack/run/src/Stack/run.php (13)
 in Stack\run called at /var/www/html/index.php (24)
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/issues/11784. 

#### Description:

5.x version of #11785 
4.x version is now #11918

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Review by daniellord32 — APPROVED** [review]
Looks good to me

**Review by daniellord32 — DISMISSED** [review]
No issues thought I clicked approved but must not have

**Comment by mabumusa1** [comment]
@escopecz this PR has been reviewed by @daniellord32 but it is a comment not a review, so I think this PR is ready to go

**Review by npracht — APPROVED** [review]
This works for me 🚀

**Pull request merged**
