### PR TITLE
enabling company tokens in webhook campaign action

### LINKED ISSUE #7615: Contactfield tokens for company fields do not work in campaign webhook actions
## Bug Description
When creating a webhook action in a campaign, you can put tokens in for the values such as {contactfield=email}. This works great for contact level fields, but if you include a field off of the primary company, it comes back blank. 

This should work like tokens in emails, which properly resolve the primary company. 

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2
| Browser | N/A

### Steps to reproduce
1. Create a campaign with a webhook action
2. Within the webhook action, pass a parameter for company zipcode using the token {contactfield=companyzipcode}
3. view payload on the other side of the webhook

 
### Log errors
No errors present in log. It just fails silently.

### PR DESCRIPTION
**Pull request by stevedrobinson**
closes https://github.com/mautic/mautic/issues/7615
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #7615 
| BC breaks? | 
| Deprecations? | None

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Company field tokens are premissable in various places within Mautic, but not in Webhook campaign actions. If sending data to a third party system, it's likely you'll need to send company data along with contact data. 

This PR includes the company data in the contact data to be parsed by the TokenHelper.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a campaign with a webhook action
2. Within the webhook action, pass a parameter for company zipcode using the token {contactfield=companyzipcode}
3. view payload on the other side of the webhook

#### Steps to test this PR:
1. Create a campaign with a webhook action
2. Within the webhook action, pass a parameter for company zipcode using the token {contactfield=companyzipcode}
3. view payload on the other side of the webhook

### CODE REVIEW

**Comment by stevedrobinson** [comment]
Can someone help me understand why this failed scrutinizer? I'd like to get this on the radar for 2.16.0 if possible.

**Comment by stevedrobinson** [comment]
@kuzmany would you be willing to look at this and/or test it?

**Comment by mabumusa1** [comment]
@stevedrobinson Thanks for the solution it worked well for me as I have the same problem that you have. one thing that I noticed that it does not pull up custom fields. so I had to modify the `app/bundles/LeadBundle/Entity/CompanyRepository.php` to include custom fields. I added the following lines.

```
    public function getCompaniesByLeadId($leadId, $companyId = null)
    {
        $q = $this->getEntityManager()->getConnection()->createQueryBuilder();

        //Get custom fields
        $q->select('group_concat(concat("comp.",alias)) as fields')
                    ->from(MAUTIC_TABLE_PREFIX.'lead_fields', 'fields')
                    ->where('fields.object = :object')
                    ->setParameter('object', "company");
        $fields = $q->execute()->fetchAll();
        $fields = $fields[0]['fields'];

        $q->select("{$fields}, cl.is_primary")
            ->from(MAUTIC_TABLE_PREFIX.'companies', 'comp')
            ->leftJoin('comp', MAUTIC_TABLE_PREFIX.'companies_leads', 'cl', 'cl.company_id = comp.id')
            ->where('cl.lead_id = :leadId')
            ->setParameter('leadId', $leadId)
            ->orderBy('cl.is_primary', 'DESC');

        if ($companyId) {
            $q->andWhere('comp.id = :companyId')->setParameter('companyId', $companyId);
        }
        $results = $q->execute()->fetchAll();

        return $results;
    }
```

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by mabumusa1** [comment]
@npracht this still an issue within M3, I can fix, shall we create a new PR for it?

@stevedrobinson it just require rebase to 3.x, if you would like to do it

**Comment by RCheesley** [comment]
@cla-bot check

@stevedrobinson we would need you to sign the contributors agreement if we are to merge this PR.

@mabumusa1 if you're able to pick this up and make the PR 3.x compatible + including custom fields, then we could consider this for including in the 3.2 milestone.  If there is no response from the original proposer, then do create a new PR/close this one, and expand it to include the custom fields.

**Comment by mabumusa1** [comment]
@RCheesley I will look into this PR, I think the code I wrote is not compatible with M3, I work on it this week

**Comment by mabumusa1** [comment]
Closing in favor of #9371

**Pull request closed without merging**
