### PR TITLE
Queue implementation improvements

### PR DESCRIPTION
**Pull request by fedys**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [❌]
| New feature/enhancement? (use the a.x branch)      | [✅]
| Deprecations?                          | [✅]
| BC breaks? (use the c.x branch)        | [✅]
| Automated tests included?              | [✅] 
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:

This PR is based on https://github.com/mautic/mautic/pull/12314 (see the [changes](https://github.com/galvani/mautic/compare/feature/5.x-messenger...fedys:mautic:queue_implementation_improvements)) and introduces the following improvements:

1. Queue is **configurable via the existing UI**.
2. It is a lot easier to start using queue for the page and email hits.
3. The code from the original PR was simplified significantly.
4. Advanced configuration still can be set via `config_local.php`.
5. There is no need to configure buses.
6. JSON is set as a default format for all messages (including email messages) which make messages smaller and easy processable in different apps. 
7. My code review suggestions were applied from the original PR.

##### JSON format comparison:

- Original PR:
    - Size: 7068 bytes.
    - Example of data:
```
{
    "Mautic\\MessengerBundle\\Message\\EmailHitNotification": "{\"stat_id\":\"fdafaf\",\"request\":{\"attributes\":{\"_stopwatch_token\":\"bdd8b3\",\"_route\":\"mautic_email_tracker\",\"_controller\":\"Mautic\\\\EmailBundle\\\\Controller\\\\PublicController::trackingImageAction\",\"idHash\":\"fdafaf\",\"_route_params\":{\"idHash\":\"fdafaf\"},\"_firewall_context\":\"security.firewall.map.context.public\",\"_security_firewall_run\":\"_security_mautic\"},
```
- This PR:
    - Size: 6243 bytes.
    - Example of data:
```
{
    "statId": "fdafaf",
    "eventTime": "2023-08-11T14:10:01+00:00",
    "request": {
        "attributes": {
            "_stopwatch_token": "f24e90",
            "_route": "mautic_email_tracker",
            "_controller": "Mautic\\EmailBundle\\Controller\\PublicController::trackingImageAction",
            "idHash": "fdafaf",
            "_route_params": {
                "idHash": "fdafaf"
            },
            "_firewall_context": "security.firewall.map.context.public",
            "_security_firewall_run": "_security_mautic"
        },
```

#### ToDo:

- [ ] Update the documentation regarding the queue configuration.

#### Steps to test this PR:

Follow the steps from [the original PR](https://github.com/mautic/mautic/pull/12314). There is one difference, the configuration can be set via the UI at /s/config/ -> Queue settings.

Screenshot 2023-08-11 at 16 48 03

### CODE REVIEW

**Comment by galvani** [comment]
@fedys I am confused regarding the payload. how exactly do you derive the IP and device from attributes only?

**Comment by escopecz** [comment]
@galvani Fedy is OOO this week. Can you elaborate? Do you have an example of the payload what it used to be and what it is now?

**Comment by escopecz** [comment]
@fedys the serialization is either broken for email or hit queue. I'm thinking I'll wait to discuss it with you. @galvani in the mean time improved the serialization on the original PR.

**Comment by fedys** [comment]
> @fedys I am confused regarding the payload. how exactly do you derive the IP and device from attributes only?

@galvani please, can you elaborate.

**Comment by fedys** [comment]
> @fedys the serialization is either broken for email or hit queue. I'm thinking I'll wait to discuss it with you. @galvani in the mean time improved the serialization on the original PR.

@escopecz I'm looking at it.

**Comment by fedys** [comment]
@escopecz after looking at the [Symfony's issue](https://github.com/symfony/symfony/issues/33394), I realized that the best way to go is using solely PHP native serialization. Using the combination of JSON and native PHP serialization is not possible as it causes issues with the failed transport (the same also applies to https://github.com/mautic/mautic/pull/12314).

I needed to tweak the serialization of the `Request` object as I was getting an error like "Cannot serialize closure". When it comes to payload sizes, using JSON produces 7kB while native serializing does 8.7kB which is not a big deal in my opinion. After removal of duplicate data (see [46f3ae3](https://github.com/mautic/mautic/pull/12648/commits/46f3ae3392c2b05b7be0622e6b3899586e4a12cd)), the payload size went down from 8.7kB to 6.7kB.

Yes, it is shame we cannot use the JSON format for the messages by default because of the [Symfony's issue](https://github.com/symfony/symfony/issues/33394) as it would make the messages more portable among different environments. On the other hand, if someone needs to use JSON, he can do so via `config_local.php` and cope with the pitfalls themself.

**Comment by fedys** [comment]
The PR is ready to test.

**Review by kuzmany — APPROVED** [review]
I did basic tests and works for me. Sync or ASync 

I did use  free https://www.cloudamqp.com/ 

image

**Review by escopecz — APPROVED** [review]
The code is looking good. Thank you everyone!

**Pull request merged**
