### PR TITLE
Removes form alias from list view

### PR DESCRIPTION
**Pull request by dbhurley**
Takes off the form alias when viewing list of forms.

### CODE REVIEW

**Comment by escopecz** [comment]
Tested on Campaign Builder / Submit Form decision. It didn't show alias for me, but ID:
form-list
After applying this PR, IDs are still there. @dbhurley where should we test this?

**Comment by dbhurley** [comment]
This is the alias shown in the list view...so when viewing the Form -> Manage Forms list. Previously it showed the form alias in ( )

**Comment by drmmr763** [comment]
+ Test worked great
+ vote +1

**Comment by escopecz** [comment]
Works. Aliases on Forms list table is removed. :+1:

**Pull request merged**
