### PR TITLE
TPROD-382: Remove symfony/inflector

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This package is not used in Mautic, it was required because of one the dependencies this PR upgrades it and remove `inflector`

image
 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Try to export leads or companies, everything should work as always

### CODE REVIEW

**Review by kuzmany — APPROVED** [review]
Seems good 👍

**Review by escopecz — APPROVED** [review]
Nice. The first Symfony package is upgraded :)

**Comment by escopecz** [comment]
@mabumusa1 it looks like this change broke saving campaigns. If I revert this change I can save the campaign again. See https://github.com/mautic/api-library/actions/runs/4627730551/jobs/8185991670

```
Cannot find a field on \u0027Mautic\\CampaignBundle\\Entity\\Lead\u0027 that is mapped to column \u0027id\u0027. Either the field does not exist or an association exists but it has multiple join columns.
```

Will you have time to look into it?

**Comment by mabumusa1** [comment]
@escopecz I will work on it tonight

**Comment by mabumusa1** [comment]
@escopecz From what I see if upgrade doctrine packages things will work again https://github.com/symfony/symfony/issues/37982

**Comment by tomekkowalczyk** [comment]
@mabumusa1 I loaded the changes from Doctrine but still got this error 

`ddev exec php bin/console d:m:m`

Error: 
`[2023-04-07 11:15:32] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Mapping\MappingException: "Cannot find a field on 'Mautic\CampaignBundle\Entity\Lead' that is mapped to column 'id'. Either the field does not exist or an association exists but it has multiple join columns." at /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php line 684 {"exception":"[object] (Doctrine\\ORM\\Mapping\\MappingException(code: 0): Cannot find a field on 'Mautic\\CampaignBundle\\Entity\\Lead' that is mapped to column 'id'. Either the field does not exist or an association exists but it has multiple join columns. at /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:684)
`

**Comment by escopecz** [comment]
@mabumusa1 @tomekkowalczyk I found the issue and fixed it in https://github.com/mautic/mautic/pull/12207. Please give it a test

**Comment by tomekkowalczyk** [comment]
@escopecz Great

**Pull request merged**
