### PR TITLE
Bugfix for Cc and Bcc handling in Sparkpost transport

### PR DESCRIPTION
**Pull request by virlatinus**
| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Related user documentation PR URL | N/A
| Related developer documentation PR URL | N/A
| Issues addressed (#s or URLs) | N/A
| BC breaks? | N/A
| Deprecations? | N/A

#### Description:
This PR fixes an issue with Bcc email addresses not receiving the emails when using Sparkpost transport.

If you use `app/console mautic:campaign:trigger` to send an email with a bcc address, you will see the following error in the console: 
`PHP Notice:  Undefined index: address in /var/www/mautic-fork/vendor/sparkpost/sparkpost/lib/SparkPost/Transmission.php on line 116`

#### Steps to reproduce the bug:
1. Configure Mautic to use Sparkpost email transport
2. Create or edit an email and add a Bcc address in the Advanced tab
3. Send the email to a different contact through a campaign or to the segment if it is a segment email.
4. Check the inbox for the Bcc email address: the email you sent will not arrive

#### Steps to test this PR:
1. Apply this PR
2. Repeat the steps to reproduce the bug
3. This time the email will arrive to the inbox of the Bcc email address.

### CODE REVIEW

**Comment by escopecz** [comment]
@virlatinus there are some CS issues. Pre-commit hook doesn't work for you either?

**Comment by luizeof** [comment]
@virlatinus thanks for your Work. This fix #2833?

**Comment by escopecz** [comment]
I heard a story from a Mautic user that he's using BCC for all emails and he checks this way the emails are coming out to the contacts correctly. So I assumed it should send one email to a contact and the same email to the BCC email address. If that's how it work for other email transports, shouldn't it for Sparkpost too?

**Comment by versadial** [comment]
I do not know if related because I was waiting for this fix in 2.10. So I implemented, BCC does work, the only issue I have now is the {contactfield} data in the BCC email is not included. Maybe all BCC emails have this bug now, or it's only related to API sparkpost...but regular TO email has the database fields in the email appended with no issue.  But, the BCC (same exact email) is missing database info. ie: "Hello Bob" is ok in regular email, but the BCC version is just "Hello  "

**Pull request merged**
