### PR TITLE
Smart lists are more smart

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**

This PR adds support to make smart lists more smart by being able to segment by relative date strings (today, tomorrow, yesterday, this week, next week, last week, this month, last month, next month, this year, last year, next year (translatable).  Any date field will accept these although right now there is not an indicator due to the conflict with the date picker but will look at adding a UI indicator later.

It also now allows filtering by lead list membership, bounce status, unsubscribe status, date identified and date last active.  

It now allows % for like searches and adds appropriate operators based on underlying data.Updated jQuery datetimepicker.

It also fixed a scenario where some leads may be removed incorrectly then readded on the next script.

**Testing**
Build new smart lists with some of the above in both MySQL and Postgres if possible to test type casting with the relative date strings and query.

### CODE REVIEW

**Comment by escopecz** [comment]
Is this how the relative date strings should work?
mauticleadfiltertest

When I trigger `php app/console mautic:leadlists:update` I get
```
Aktualizace zájemců pro seznam 10
PHP Notice:  Undefined index: msLPbwgC in /var/www/html/mautic-github/app/bundles/LeadBundle/Entity/LeadListRepository.php on line 872
PHP Notice:  Undefined index: msLPbwgC in /var/www/html/mautic-github/app/bundles/LeadBundle/Entity/LeadListRepository.php on line 873
0 zájemců bude přidáno v dávkách po 300
PHP Notice:  Undefined index: mqTHiJaM in /var/www/html/mautic-github/app/bundles/LeadBundle/Entity/LeadListRepository.php on line 872
PHP Notice:  Undefined index: mqTHiJaM in /var/www/html/mautic-github/app/bundles/LeadBundle/Entity/LeadListRepository.php on line 873
0 zájemců bude odstraněno v dávkách po 300
0 zájemců ovlivněno
```
*It is in Czech for some reason. I tested Czech a while back, but switched back to EN and cleared cache.*

**Comment by that0n3guy** [comment]
I think this could almost be used for something like #306 (for birthdays, anniversaries, etc...).  Something like `birthday == today`.   This would add them to "Todays Birthdays" list and a birthday campaign could be started.  Then, tomorrow they would be removed from the list. 

The only issue in that is that you would have to somehow ignore year... just use day/month from "birthday".

**Comment by that0n3guy** [comment]
Also, if the fields could use **formulas** then some of this wouldn't be needed and would be more flexible. 

For example: `tomorrow, yesterday` are all pointless if I can do:

`Date added == Today - 1day` is the same as yesterday. 
`Date added == Today + 1day` is the same as tomorrow. 

Something like `Date added == Today - 1month` is sort of like "last month", but more exact.

**Comment by alanhartless** [comment]
@escopecz I fixed that PHP notice.  It was related like email statement.  

The date string looks right.  It'll be translatable based on these strings but should default to these English ones till they are translated for other locales:
```
mautic.lead.list.month_last="last month"
mautic.lead.list.month_next="next month"
mautic.lead.list.month_this="this month"
mautic.lead.list.today="today"
mautic.lead.list.tomorrow="tomorrow"
mautic.lead.list.yesterday="yesterday"
mautic.lead.list.week_last="last week"
mautic.lead.list.week_next="next week"
mautic.lead.list.week_this="this week"
mautic.lead.list.year_last="last year"
mautic.lead.list.year_next="next year"
mautic.lead.list.year_this="this year"
```

So did you have a lead you created yesterday that didn't get included?

**Comment by alanhartless** [comment]
@that0n3guy Good point about the birthday.  But afraid that is going to have to wait as our lead date fields all save dates with a year and thus birthday wouldn't work. If you saved the field as a text field, then the search queries wouldn't know to treat it as a date/time.  We're looking at improving the data structure of lead fields/columns so we can hopefully can make the lists and lead fields more flexible and query-able. In the beginning we supported like 5 database platforms and thus kept everything pretty generic to prevent from having to write platform specific code for them all.  But we're now just supporting mysql and postgresql so it won't be so bad if we have to do some wrapper stuff that is platform specific.

**Comment by that0n3guy** [comment]
@alanhartless Our CRM does something like this for reports like so (see attached screenshots):
mautic_dates_year_month

Basically, the system detects fields that is the dates and dynamically places day/month/year into the drop down.  So if birthday is 7-21-1975, then `Birthday (day)` is `21`, `Birthday (year)` is `1975`.  

This would let you do a birthday filter in mautic like so:

Birthday (day) = today-day
Birthday (day) = today-day
Birthday (day) = today-day
Birthday (day) = today-day

**Comment by escopecz** [comment]
Warnings are gone. But the `php app/console mautic:leadlists:update` command doesn't seem to add leads to the list according to the filter.

I created a new lead today and changed the condition to *greater than yesterday*, run the command, but no lead was added. I tried even less than yesterday (lot of them exists), but no lead was added. I also tried to create new list with only the yesterday condition, but still no lead was added. Then I tried to change *yesterday* to *last month* and leads were added. *this week* also works. So maybe only *yesterday* has some issue?

**Comment by escopecz** [comment]
Debugging the `yesterday` option. Here is the SQL query produced by `greater than yesterday` filter:
```
SELECT count(distinct(l.id)) as lead_count, max(id) as max_id 
FROM mau_leads l 
LEFT JOIN mau_lead_lists_leads ll ON l.id = ll.lead_id 
WHERE (
     l.id NOT IN (
        SELECT new_check.lead_id 
        FROM mau_lead_lists_leads new_check 
        WHERE (new_check.leadlist_id = 12) 
        AND (new_check.lead_id = l.id)
    )
) 
AND (
    (
        (l.date_added >= '2015-08-27') 
        AND (l.date_added <= '2015-08-27')
    ) 
    AND (
        (ll.lead_id IS NULL) 
        OR (ll.date_added <= '2015-08-28 10:53:55')
    )
)
```
The problem the query doesn't find anything is 
`(l.date_added >= '2015-08-27') AND (l.date_added <= '2015-08-27')` and it should be
`(l.date_added >= '2015-08-27') AND (l.date_added <= '2015-08-28')`
Solution would be to use full 86400 seconds instead of 86399 while building the query.

Another question is if it should really build `between` query? When originally it should work with leads added from yesterday to NOW, isn't it?

**Comment by alanhartless** [comment]
@escopecz I think I finally got this resolved now. I obviously wasn't thinking and stuck in a "between" mode.

**Comment by escopecz** [comment]
Test successful. Good to go :+1:

**Comment by npracht** [comment]
Hi guys,

There is no doc about that. Is those filter working like "date + equal + one of the list value" ?
* mautic.lead.list.month_last="last month"
* mautic.lead.list.month_next="next month"
* mautic.lead.list.month_this="this month"
* mautic.lead.list.today="today"
* mautic.lead.list.tomorrow="tomorrow"
* mautic.lead.list.yesterday="yesterday"
* mautic.lead.list.week_last="last week"
* mautic.lead.list.week_next="next week"
* mautic.lead.list.week_this="this week"
* mautic.lead.list.year_last="last year"
* mautic.lead.list.year_next="next year"
* mautic.lead.list.year_this="this year"

Let me know, thanks a lot,

N.

**Comment by mvolpato** [comment]
The possibility to use 'today' in the smart list filter is not yet on mautic.com, am I right?

**Comment by npracht** [comment]
Hi @alanhartless @escopecz @that0n3guy ,

When I save my list with date format filters including those values, the value yesterday is replaced by the real date of yesterday. I mean that the value does not stay a "variable".

What i'd love is that in my list the leads change everyday, because everyday the yesterday is a different day.

Did i do something incorrectly of is it the result i should expect from this piece of code ?

Thanks a lot,

N.

**Comment by jjroelofs** [comment]
For me the string "last month" seems to be retained in the filter and works dynamically but if I type "3 months ago" it gets translated to a fixed date and becomes static. Not sure how to properly enter "3 months ago" right now, is that not supported dynamically?

**Pull request merged**
