### PR TITLE
Fix company creation for Salesforce lead

### PR DESCRIPTION
**Pull request by Enc3phale**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | N
| Related user documentation PR URL | N
| Related developer documentation PR URL | N
| Issues addressed (#s or URLs) | N
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
On Salesforce integration, lead company is a required field. But if you map this field to a custom mautic text field (instead of Company field), company is always created within Mautic when push command is launched.

This impact only SF Lead (company field name is Company), SF Contact is not impacted (company field name is AccountId). If you map SF Lead Company field to Mautic field, it works as usual.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create Salesforce account, create a lead (not a contact).
2. In Mautic, create custom text field ex: `société`
3. Configure Salesforce
Screenshot_2019-11-19 Manage Plugins Webmecanik Automation(1)

4. Map fields
Screenshot_2019-11-19 Manage Plugins Webmecanik Automation
5. Launch sync twice : `php app/console mautic:integration:fetchleads --time-interval=80minutes --integration=Salesforce`
6. Go to companies and you should see a company, and your contact inside.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com/8140)
2. Remove lead from Mautic
3. Launch sync twice
4. No more extra company

### CODE REVIEW

**Review by florentpetitjean — DISMISSED** [review]
Tested and works with a Salesforce Sandbox

**Review by florentpetitjean — DISMISSED** [review]

**Comment by npracht** [comment]
We're using it in production environment for since **2 Dec 2019**.

**Review by npracht — DISMISSED** [review]

**Comment by RCheesley** [comment]
@Enc3phale I am unable to rebase this PR to trigger the code coverage report due to permissions - can you take a look and rebase against staging please Thank you!

**Comment by npracht** [comment]
@kuzmany will handle it

**Comment by npracht** [comment]
@kuzmany can you just add unit tests then it can be merged ?

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Bumping to 3.1.2 due to needing a rebase and testing.

**Comment by andersonjeccel** [comment]
Hey there! 👋
I noticed this PR has been open for quite a while now (wow, time flies! 🕰️) without any recent activity. Given the age of this PR and the changes that have happened in the project since then, it's probably best to close this one out.

If you still think this change would be valuable, feel free to open a fresh PR with an updated implementation. Otherwise, no worries – thanks for your interest in contributing!

I'll be closing this PR to help keep our project tidy. Thanks for understanding! 😊

**Pull request closed without merging**
