### PR TITLE
Not contains support for campaign's form value condition expression with notLike

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Added the same logic to the form field value condition as segments filter does for like/notLike.https://github.com/kuzmany/mautic/blob/f5fd2cf553eec037f7b6211c193f8675d2331b40/app/bundles/LeadBundle/Segment/Decorator/BaseDecorator.php#L131-L131

That means, If search value doesn't contain `%` symbol, we add it `%value%`

#### Steps to test this PR:
1. Create a form with a multiselect value with the options: "first, second, third."
2. Submit it with the first and third options selected.
3. Create a campaign with a form field value condition of "not like" for the multiselect, excluding the option "first."
4. You should be true in the campaign.

### CODE REVIEW

**Comment by PatrickJenkner** [comment]
I just tested it, and the condition was still false. I set the condition up as shown in the screenshot and submitted the form with "first" and "third". Was that correct or did I misunderstand something?

PR 13079

**Comment by kuzmany** [comment]
@PatrickJenkner I did test and works for me.

I checked firstname with this condition

image

test2 firstname go to false
tst firstname go to true 

image

**Review by jos0405 — APPROVED** [review]
Work for me.

image

Simple campaign adds yes and no tags:

image

Condition logic is:

image

Result: right tags added:
image

**Review by MadlenF — APPROVED** [review]
Works for me 👍

**Review by escopecz — APPROVED** [review]

**Pull request merged**
