### PR TITLE
Return campaign ID and Name for 'Campaign membership change' Events

### LINKED ISSUE #9504: Mautic contacts activity API should return campaign ID for campaign membership events.
When requesting contact activity through the API you can see `campaign_membership` events. However they do not return the campaign ID that the contact became a member of.

```
{
      "event": "campaign_membership",
      "eventId": "campaign_membership666894",
      "eventType": "Campaign membership change",
      "eventLabel": "Contact added to campaign, Abandoned cart",
      "timestamp": "2020-12-16T14:14:07+00:00",
      "contactId": "4630",
      "details": {
        "objectDescription": "Abandoned cart"
      }
    },
```

The name is returned, but the ID is not. An ID would be better because it is immutable.

### PR DESCRIPTION
**Pull request by internalfx**
closes #9504
It would be useful to have the Campaign ID available when querying events from the API.

I've also added the `campaign_name` key to add consistency with other event types.

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features"
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Fixes | #9504

### CODE REVIEW

**Review by kuzmany — DISMISSED** [review]
👍

**Comment by npracht** [comment]
@internalfx can you sign the contributor agreement please ? :)

**Comment by internalfx** [comment]
@npracht Done.

**Comment by internalfx** [comment]
This fixes #9504

**Comment by npracht** [comment]
@cla-bot check

**Comment by internalfx** [comment]
I have signed the CLA through docusign.

**Comment by npracht** [comment]
@cla-bot check

**Comment by internalfx** [comment]
@npracht I signed it yesterday before you ran `cla-bot check` last time. Something might be amiss.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Sorry for the delay, it is a manual process and nobody picked up adding the entries while I was out on vacation! All sorted now!

**Comment by internalfx** [comment]
@RCheesley Thank you

**Comment by RCheesley** [comment]
@internalfx it looks like there is a [code style fix](https://github.com/mautic/mautic/pull/9507/checks?check_run_id=1750420424) that needs some attention before this can be merged - could you take a look?

**Comment by internalfx** [comment]
I think I've made the changes the style checker wants, please review.

**Review by RCheesley — APPROVED** [review]
GTG based on earlier reviews from @kuzmany and @npracht

**Review by kuzmany — APPROVED** [review]
Make sense 👍

**Pull request merged**
