### PR TITLE
Builder tiles debug

### PR DESCRIPTION
**Pull request by GaberNeighbor**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | x
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Open email/page builder
2. Drag slot from slot types / section types onto builder
3. Observe visibility and style issues

#### Steps to test this PR:
1. Open email/page builder
2. Drag slot from slot types / section types onto builder
3. Observe visibility and style fixes

### CODE REVIEW

**Comment by npracht** [comment]
Hello @GaberNeighbor can you share a screenshot before/after please ? :)

Thanks !

**Comment by GaberNeighbor** [comment]
@npracht 
[builder-blocks-example.mov.zip](https://github.com/mautic/mautic/files/1682824/builder-blocks-example.mov.zip)

**Comment by npracht** [comment]
Label: Code Review

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Label: Pending test confirmation

**Comment by GaberNeighbor** [comment]
@mleffler this never got reviewed, but it is good to go.

**Comment by npracht** [comment]
Hi @GaberNeighbor any chance you solves conflicts to merge it in 2.14.0 please ?

**Comment by mleffler** [comment]
Hi @GaberNeighbor Can you resolve the conflicts please?

**Comment by mleffler** [comment]
I reached out to Gabe, and he will not have time to do this work in the near future.  So, I recommend we stop including it in releases unless somebody wants to take over and resolve the conflicts

**Comment by dbhurley** [comment]
Closing this - if someone else wishes to fix it they can re-open.

**Pull request closed without merging**
