### PR TITLE
TPROD-305 Twig refactoring for Api bundle

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://mautic.atlassian.net/browse/TPROD-305

#### Description:

Refactors PHP templates into Twig for the Api Bundle.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Click through the Api Bundle's Ui. 
3. Create, edit, delete API credentials, global search is not broken

Known issues that already exist on the 5.x and 4.4 version:
- Search and global search always return all results no matter what you search for
- Ordering always return the same order.
- The API config form (in global configuration) loses the "Mautic blue" title. Config bundle will have to be converted to Twig to fix that.

### CODE REVIEW

**Review by mabumusa1 — DISMISSED** [review]
I tested this PR on gitpod, it worked as expected. I created clients and did a search all worked as expected

**Review by RCheesley — CHANGES_REQUESTED** [review]
Thanks for this, found a couple of issues.

Batch change options are missing (let's write a test for that?)

screenshot-8080-escopecz-mautic-dhvhavfl3xd ws-eu81 gitpod io-2023 01 10-11_40_56

Pagination is not working: https://watch.screencastify.com/v/KD7RJQfWQ7A2lsVjmxCJ (can we do a test for that as well?)

**Comment by escopecz** [comment]
@RCheesley I just checked on 5.x and even on Acquia's Campaign studio (M4) and the issues you describe exists there as well. So this PR is not to blame. I guess no one needs pagination or batch operations for the API creds management as there is usually just one or 2 if any.

**Comment by RCheesley** [comment]
OK well let's raise it as a bug now that we know it exists.

**Pull request merged**
