### PR TITLE
Elfinder load from dev enviroment

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for features or enhancements / 3.2 for bug fixes 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR just add open elfinder window on test enviroment.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Open filemanager (elfinder) on dev enviroment
3. Before PR is loaded on url /elfinder
4. After PR is loaded on url /index_dev.php/elfinder
5. On production enviroment should still load /elfinder

### CODE REVIEW

**Comment by escopecz** [comment]
@kuzmany can you please state the problem why this change is needed?

**Comment by kuzmany** [comment]
@escopecz When I am working on dev enviroment, then elfinder is loaded from prod enviroment (without index_dev.php). Does not sound as issue?

**Comment by escopecz** [comment]
I haven't encounter any issue with it. Could you elaborate?

**Comment by kuzmany** [comment]
@escopecz If I want debug elfinder, without PR I am not able to do it on dev enviroment with toolbar as one of tool to help find the clue

image

**Review by escopecz — APPROVED** [review]

**Pull request merged**
