### PR TITLE
Update BUG-REPORT.yml to include 5.2.x series option

### PR DESCRIPTION
**Pull request by matbcvo**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR updates the `.github/ISSUE_TEMPLATE/BUG-REPORT.yml` file to include the `5.2.x series` option in the `Mautic Series` dropdown. This is necessary following the release of Mautic 5.2.0.

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Review by RCheesley — CHANGES_REQUESTED** [review]
Thanks for this! We can now mark 5.0.x and 5.1.x as unsupported, I think?

**Comment by matbcvo** [comment]
Done @RCheesley

**Review by RCheesley — APPROVED** [review]
Thanks! GTG from my side!

**Comment by RCheesley** [comment]
Going to go ahead and merge this so that new issues have the option. Thanks @matbcvo for taking the initiative!

**Pull request merged**
