### PR TITLE
Remove html switch from textarea custom field.

### LINKED ISSUE #13655: Remove HTML switch in the textarea custom field and write a migration
### Mautic Version

5.0.x series

### Way of installing

I cloned the Mautic repo (not recommended or supported)

### PHP version

8.x

### What browsers are you seeing the problem on?

Not relevant

### What happened?

This must be done to resolve https://github.com/mautic/mautic/pull/13428#issuecomment-2057908010

### How can we reproduce this issue?

Step 1: Create a textarea custom field.
There is a switch to allow HTML
And there is the new HTML field as well.

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by abhisekmazumdar**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        |  🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #13655 

## Description

Remove the "Allow HTML" property in the custom field of the `textarea`. Additionally, migrate the data that has the "Allow HTML" property set to true.

~~I don't have the permission to set the milestone but this will be part of 6.x.~~ There is no BC break. The existing data will be automatically migrated. 

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a custom field with type: Text: Paragraph.
3. The custom field shouldn't have the Allow HTML properties.
4. Also, this includes migration, which will essentially rename any custom fields that have the "Allow HTML" setting set to true in the databases.

Note: In 5.x, the Allow HTML is broken. Any newly created custom field with textarea will not set the Allow HTML properties in the database.

### CODE REVIEW

**Review by escopecz — COMMENTED** [review]
Thank you for taking care of this! I think we can merge it into M5.2. The only BC break is the removal of the `setCleaningRules` method. If you revert it and mark it as deprecated then this has no BC breaks thanks to the migration. What do you think?

**Comment by abhisekmazumdar** [comment]
Sure I can do that. Will update the PR ASAP.

**Comment by abhisekmazumdar** [comment]
This is ready for testing. Please add the required labels.

**Review by escopecz — APPROVED** [review]
This is good from the code review perspective. Once again, thank you for cleaning this up!

**Comment by escopecz** [comment]
I wasn't able to test the migration properly as I wasn't able to create the original HTML textarea anymore due to this validation on the 5.x banch:
Screenshot 2024-07-15 at 14 26 12
So if anyone else already have the textarea field created with this option, please test the migration.

**Review by shinde-rahul — APPROVED** [review]
Code changes LGTM!!!

Thanks @abhisekmazumdar!!!

**Comment by escopecz** [comment]
@andersonjeccel can you tell us why you have added the "blocked" and "bc-break" labels here? I [don't think](https://github.com/mautic/mautic/pull/13926#pullrequestreview-2163135417) it's correct.

**Comment by andersonjeccel** [comment]
@escopecz because the description says that it’s a removal for 6.0 (bc-break) and the target release doesn’t have a branch yet (blocked)

edit: I didn’t check the code (out of my knowledge) but tried to help with labels organization; now I saw your linked comment

**Comment by escopecz** [comment]
The BC break was removed as discussed in the comments. I'll update the PR description.

**Comment by andersonjeccel** [comment]
Right, I’m still learning how to use the bc-break label 
Thanks for pointing the fix! 🙏🏻

**Pull request merged**
