### PR TITLE
[DPMMA-2341] Part of the saveprefsbutton template removed

### PR DESCRIPTION
**Pull request by annamunk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [✅]
| New feature/enhancement? (use the a.x branch)      | [❌]
| Deprecations?                          | [❌]
| BC breaks? (use the c.x branch)        | [❌]
| Automated tests included?              | [❌] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR removes part of saveprefsbutton.html.twig template, which is no longer used in Mautic 5. The script causes an error and is displayed as text if the email has its own preference center (landing page) with the {saveprefsbutton} token:

save_pref

However, if part of the deleted script is needed, please let me know.

#### Steps to reproduce the error:
1. Open Mautic 5.x on Gitpod or pull down for testing locally. 
2. Create <b>Landing Page</b> with option <b>preference center page</b> switched to <b>Yes</b>. In the content add token {saveprefsbutton}. 
lp_prefs
3. Save landing page. 
4. Create a new email and include the landing page as <b>Preference center page</b> in email settings.
5. Send the email to some of your test contacts and click the unsubscribe link included in the email you received.
6. Part of the code will be displayed on the page below the <b>Save preferences</b> button.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Follow steps 2-5 in the "Steps to Reproduce the Error" section.
3. The button should be displayed with no additional text/code below.

### CODE REVIEW

**Comment by kuzmany** [comment]
I don't think removing it will make the preferences center work as expected.	
That code was there for some reason and now I do not see for example  unclosed tag  `</form>`
Also success message is shown, even If we expect to hide it before submission.

**Comment by annamunk** [comment]
@kuzmany you are right! I added a fix that will separate the closing form tag from the button template. What do you think about this change?

I also encountered a problem with saving the form and displaying the success message all the time. I think this may be a separate issue and I wanted to focus on fixing the rendering issues first.

**Review by patrykgruszka — APPROVED** [review]
The code looks good. I like the idea of moving the custom declaration logic from the `saveprefsbutton.html.twig'.

The preferences are loaded correctly. I'm getting a CSRF error when saving the form, but it's probably not caused by changes in this PR.
image

**Review by kuzmany — CHANGES_REQUESTED** [review]
It return `The CSRF token is invalid. Please try to resubmit the form.

Tested in incognito
`

image

**Comment by patrykgruszka** [comment]
@kuzmany the CSRF token issue should now be fixed.

**Review by RCheesley — APPROVED** [review]
Looks good to me - no extra code and no CSRF error either. Thanks @annamunk 🚀 

screenshot-8080-annamunk-mautic-7mlpiwqz2lf ws-eu107 gitpod io-2024 01 08-10_29_52

**Review by escopecz — APPROVED** [review]
I see no issues in the code. The removed code is PHP, not Twig so it was causing issues. Thank you! 👍

**Pull request merged**
