### PR TITLE
Added ignore tracked devices switch for shared computer page hit tracking.

### PR DESCRIPTION
**Pull request by atbrowne**
| Q  | A
| --- | ---
| Bug fix? | No
| New feature? | Yes
| Automated tests included? | No
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | No
| Deprecations? | No

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Adds handling for an `ignore_tracked_devices` switch that can be passed in to the tracking JS `mt` function as a custom parameter. When its value is set to true Mautic will generate a new contact and tracking cookies for the device regardless of previous use. This switch when combined with the Mautic API 
can be used to track separate users on a shared computer provided the pages being tracked are able to distinguish different users for example via a user login. This is done by checking the `mtc_id` cookie value against the current user with the API to see if the cookie belongs to the them. If it does not belong `mt` is called with the `ignore_tracked_devices` switch generating a new contact. The new contact can then be assigned to the current user with the API.

#### Steps to test this PR:
1. Send multiple JS tracking requests to [this PR](https://mautibox.com) with the `ignore_tracked_devices` custom parameter set to true.
2. Verify the `mtc_id` cookie's value is updated each time.

### CODE REVIEW

**Comment by kuzmany** [comment]
Hi, maybe this could be helpful for you: https://github.com/mautic/mautic/pull/7726 
Can you test it?

**Comment by atbrowne** [comment]
> 
> 
> Hi, maybe this could be helpful for you: #7726
> Can you test it?

I tested the item as requested, and noted that the feature still results in page hit history being merged. If this issue is resolved it may be a suitable replacement for this item (which does not merge page hit history).

**Comment by npracht** [comment]
@atbrowne can you review conflicts please ?

**Comment by atbrowne** [comment]
@npracht done.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@atbrowne if this is still relevant for Mautic 3.x could you please address the conflicts and we can look to get it tested (in addition to signing the contributors agreement!). Many thanks!

**Comment by RCheesley** [comment]
Closing this PR due to a lack of recent activity and outstanding conflicts. If someone would like to pick it up in the future please link to this PR in the description to maintain the connection.

**Pull request closed without merging**
