### PR TITLE
Fix IpLookupHelper bug

### PR DESCRIPTION
**Pull request by dennisameling**
I enabled PHP `strict_types` on a few files in https://github.com/mautic/mautic/pull/9667, including the IpLookupHelper. While Mautic's tests passed, there is one test that is now failing in the API Library:

https://github.com/mautic/api-library/pull/235/checks?check_run_id=1898895191

```
Response: {"errors":[{"message":"Type error: strpos() expects parameter 1 to be string, null given","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/IpLookupHelper.php","line":185,"args":[]},{"namespace":"","short_class":"","class":"","type":"","function":"strpos","file":"\/var\/www\/html\/mautic\/app\/bundles\/CoreBundle\/Helper\/IpLookupHelper.php","line":185,"args":[]},{"namespace":"Mautic\\CoreBundle\\Helper","short_class":"IpLookupHelper","class":"Mautic\\CoreBundle\\Helper\\IpLookupHelper","type":"-\u003E","function":"getIpAddress","file":"\/var\/www\/html\/mautic\/app\/bundles\/PointBundle\/Controller\/Api\/PointApiController.php","line":97,"args":[]},{"namespace":"Mautic\\PointBundle\\Controller\\Api","short_class":"PointApiController","class":"Mautic\\PointBundle\\Controller\\Api\\PointApiController","type":"-\u003E","function":"logApiPointChange","file":"\/var\/www\/...
```

**Background**
`$request->headers->get()` returns `null` by default, while `strpos()` under it requires a string. Without `strict_types`, PHP quietly converts `null` to an empty string, but now, it throws an error instead. This PR sets the default output of `$request->headers->get()` to an empty string `''` instead of `null`, fixing this issue.

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
We should be careful with adding strict types to existing Mautic files as it can cause these bugs. As our test coverage is very low we cannot be sure it won't break anything. Can we leave it for M4 or maybe even new-gen? Mautic has enough bugs as is :)

**Comment by dennisameling** [comment]
@escopecz okay, I'll revert those strict types later today in this PR. Let's not merge it until then

**Comment by dennisameling** [comment]
Alright, just reverted the strict types declarations in this PR. Should be good to go now. Also fixes the failing tests in the API library: https://github.com/mautic/api-library/runs/1911588191?check_suite_focus=true

**Review by escopecz — APPROVED** [review]
Thank you @dennisameling! 👍

**Pull request merged**
