### PR TITLE
Bugfix: incorrect check for HTTPS connection when behind reverse proxy

### LINKED ISSUE #8944: There should be a way to set Mautic to use HTTPS in the config
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When running Mautic with SSL encryption you will get a warning for mixed content related to gravatar images. This has been reported before here: **Chrome shows Mautic dashboard as not fully secure #7577** & https://github.com/mautic/docker-mautic/issues/37

A solution to this is to add `$_SERVER['HTTPS'] = 'on';` in the `index.php` in the Mautic installation. However, when you update Mautic you will need to do this again.

Maybe there can be a setting in the configuration to set the server to use HTTPS ?

| Q   | A
| --- | ---
| Mautic version | 2.16.3
| PHP version | 7.1.33
| Browser | Chrome Version 83.0.4103.106

### Steps to reproduce
1. I am using Mautic wit this docker setup: https://github.com/mautic/docker-mautic/tree/master/examples/mautic-example-nginx-ssl behind Cloudflare
2. When you login in the dashboard and refresh the page you will get a mixed content warning because of Gravatar images requested from (http://i2.wp.com)

### LINKED ISSUE #9495: SameSite=none not set behind proxy
Problem:
Tracking cookie is not set with 'SameSite=none'

Environment:
- Debian Linux 10
- PHP 7.3
- Mariadb server 10.3
- Mautc v3.2.1
- Served from behind nginx reverse proxy with SSL termination

cause:
- The connection is not seen as 'secure'
- header X-Forwarded-Proto = 'https' is set via nginx

### PR DESCRIPTION
**Pull request by christopheg**
closes https://github.com/mautic/mautic/issues/8944
closes #9495

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for features or enhancements / 3.2 for bug fixes 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | don't know
| Automated tests included?              | no
| Issue(s) addressed                     | Fixes #9495

### CODE REVIEW

**Comment by npracht** [comment]
hi @christopheg ! thanks a lot for your contribution but i think this is already addressed by https://github.com/mautic/mautic/pull/7931, do you confirm ?
Could you test the other PR and give your feedback ?

**Comment by christopheg** [comment]
Ok, that works. Not an nice solution though. I will reply in the issue.

**Comment by npracht** [comment]
@christopheg can you please:
1. Sign the Contributor agreement (from CLA-bot)
2. Rebase your PR against 3.2 branch, as far as it is a bugfix, I think we should merge it in next patch release (and not wait 3.3.0 in several weeks).

**Review by escopecz — DISMISSED** [review]
Yes, this is much better solution. I checked t[he source](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/HttpFoundation/Request.php#L1246). It also addresses the "X-Forwarded-Proto" header.

**Comment by christopheg** [comment]
> @christopheg can you please:
> 
> 1. Sign the Contributor agreement (from CLA-bot)
> 2. Rebase your PR against 3.2 branch, as far as it is a bugfix, I think we should merge it in next patch release (and not wait 3.3.0 in several weeks).

should be done.

**Comment by escopecz** [comment]
There is too many commits now. Did you rebase the code or just changed the branch here in the PR? It will need a rebase it looks like. Let me know if you need some help with that.

**Comment by npracht** [comment]
I'm scared you have to redo the work. Actually the best when you try to PR on `3.2` branch is to create your own branch from 3.2 (then you don't bring all `features` diff).

Right now you need to rebase on 3.2 (ask John on Slack if you need help).
For next time you can do `git branch your_branch_name 3.2` to directly work on good branch without rebasing issue.

**Comment by npracht** [comment]
closed in favor of https://github.com/mautic/mautic/pull/9499

**Pull request closed without merging**
