### PR TITLE
Update GrapesJs dependencies to latest version

### LINKED ISSUE #9986: Update to newest version of grapesjs
I think we should update to the newest version before we launch it:
https://github.com/artf/grapesjs/releases

### PR DESCRIPTION
**Pull request by adiux**
⚠️ First the refactoring PR should be merged: https://github.com/mautic/mautic/pull/10114/

This PR fixes: https://github.com/mautic/mautic/issues/9986 but the PR above must first be merged before we can merge this one.

### CODE REVIEW

**Comment by RCheesley** [comment]
Marking this as blocked due to the dependency on #10114 which has some issues at present.

**Comment by adiux** [comment]
merged with features, updated dev dependecies, rebuild and tested if DC works
image

**Comment by RCheesley** [comment]
I think someone else needs to test this other than me and you, I am still (with a fresh instance, force-cloning your PR to get the latest code) getting just the dynamic content variable showing on the email, not even the default content. Clearly something broken.

Have you tried testing in a completely vanilla instance just cloning down this PR without having the preset set up or building 
anything?

screenshot-mautic4 ddev site_8026-2021 08 24-19_11_01

**Review by RCheesley — DISMISSED** [review]
All good, working now - I had not refreshed the page which was causing the issue!

**Comment by RCheesley** [comment]
@adiux good to go with resolving the conflicts on this one now! 🎉

**Pull request merged**
