### PR TITLE
Fix autofilling when using multiple autofill fields

### PR DESCRIPTION
**Pull request by hluchas**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Automated tests included? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description: When using multiple checkbox groups or selects, only first one is autofilled.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create multiple Boolean or Select custom fields
2. Create form with checkbox groups mapping to those custom fields, using "Use assigned contact/company field's list choices. = Yes" in the Properties Tab
3. Add form to a landing page, then submit form with at least one of those checkboxes checked
4. Refresh landing page that the form is on 

#### Steps to test this PR:
1. Load up this PR
2. Use reproduction steps

### CODE REVIEW

**Comment by escopecz** [comment]
@kuzmany @hluchas is this duplicate of https://github.com/mautic/mautic/pull/7347?

**Comment by kuzmany** [comment]
@escopecz yes it is, our https://github.com/mautic/mautic/pull/7347 fix radio + checkbox + some boolean unexpected autofill behaviour with it

**Comment by hluchas** [comment]
Funny, but OK. I would like to merge my PR naturally and because I've better division for alias `_'.$alias.'_'.`, but @kuzmany  has more fixed in it.

I don't know.

**Comment by kuzmany** [comment]
We're going to close 2.15.2 release, then I decide to close this PR favor to https://github.com/mautic/mautic/pull/7347
Better regex division could be submitted in another PR.

**Pull request closed without merging**
