### PR TITLE
added event EmailTokenReplacedEvent

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

We need event dispatched after token are replaced in mail build process.

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Just code review

### CODE REVIEW

**Comment by mabumusa1** [comment]
@kuzmany thanks for the PR, the code looks good. may you please fix CI

**Review by mabumusa1 — CHANGES_REQUESTED** [review]
The PR is good, waiting for CI checks to turn green

**Comment by RCheesley** [comment]
@kuzmany please can you address the failing tests? Thanks!

**Comment by escopecz** [comment]
@kuzmany what's the plan with this PR? I suggested to remove the MailHelper in https://github.com/mautic/mautic/issues/12096. WDYT?

**Comment by kuzmany** [comment]
@escopecz If MailHelper gonna be removed. Then we can close it.

**Pull request closed without merging**
