### PR TITLE
added track_private_ip_ranges option to allow private IPs to be tracked

### PR DESCRIPTION
**Pull request by davidscholberg**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | No
| New feature? | Yes
| Automated tests included? | Yes
| Related user documentation PR URL |
| Related developer documentation PR URL |
| Issues addressed (#s or URLs) |
| BC breaks? | No
| Deprecations? | No

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

We run Mautic on our local office network, and as a result, we need to be able to test tracking of IPs in our private IP range. Currently, Mautic doesn't allow this because all private IPs are converted to `127.0.0.1` in the [`IpLookupHelper::ipIsValid` method](https://github.com/mautic/mautic/blob/2.14.0/app/bundles/CoreBundle/Helper/IpLookupHelper.php#L210). Specifically, the [`FILTER_FLAG_NO_PRIV_RANGE` flag](http://php.net/manual/en/filter.filters.flags.php) passed to `filter_var` filters out IPs in the given private ranges.

This PR adds a config option named `track_private_ip_ranges` that disables the usage of the `FILTER_FLAG_NO_PRIV_RANGE` flag and therefore does not convert internal IPs to `127.0.0.1`. The default value for `track_private_ip_ranges` is `false`, making this change backwards compatible with existing installations.

[//]: # ( As applicable: )
#### Steps to test this PR:
1. Set `track_private_ip_ranges` to `true` in `app/config/local.php`.
2. Clear the symfony cache (e.g. `rm -rf app/cache/*`).
3. Generate some tracking hits from an internal IP (e.g. `10/8`, `172.16/12`, or `192.168/16`) on the same network as the mautic installation.
4. Verify that the internal IP is correctly tracked.
5. Verify that external IP tracking still works with `track_private_ip_ranges` set to `true` or `false` (remember to clear the symfony cache after each config change).

### CODE REVIEW

**Comment by bpcook920** [comment]
I have tested this change and verified that the tracking JS correctly tracks private IP addresses for contact access by checking the IP access for several in-house accounts and verifying they are being tracked under their private IP and not `127.0.0.1`.

See screenshot of contact histories:
internal_tracking_private_ips

**Comment by escopecz** [comment]
@davidscholberg the PR is good to be merged, but could you please also document this configuration option here?:

https://github.com/mautic/documentation/blob/master/en/contacts/contact_monitoring.md

**Comment by escopecz** [comment]
Perfect, thanks!

**Comment by davidscholberg** [comment]
@Woeler done deal.

**Comment by cofundhub** [comment]
I am so glad that you guys added this feature, because we need to create user account for our clients and need to monitor their behavior while they browsed through the contacts. However, I can't get this working. Please advise. 

I am using AWS Bitnami Mautic v2.14.2，  successfully  upgraded to 2.15.0 via browser,

Then I did the following:
cd /opt/bitnami/apps/mautic/htdocs/app/bundles/ConfigBundle/Config
sudo chown -R bitnami:daemon *

config.php
line 1078:  'track_private_ip_ranges' => true,

Clear Cache
sudo su daemon -s /bin/bash -c "/opt/bitnami/php/bin/php /opt/bitnami/apps/mautic/htdocs/app/console cache:clear --env=prod"

Now the user page hits of the contacts' pages are still not recorded anywhere. 

Please advise!! Thank you.

**Pull request merged**
