### PR TITLE
[staging] Removed package-lock.json from git HEAD and  I have improved the contrast of sidebar and each labels. This fix can improved reading.

### PR DESCRIPTION
**Pull request by raffaelecarelle**
I wish to remove the package-lock.json. The reason is that the **separation of enviroments.**

I have improved the contrast of sidebar and each labels. This fix can improved reading.

### CODE REVIEW

**Comment by npracht** [comment]
@escopecz i don't know what to say about that, i don't handle the impact of it.

**Comment by raffaelecarelle** [comment]
The impact is a more readable menu bar.  At the moment the menu itam labels have too less contrast.

**Comment by escopecz** [comment]
Please add back all the removed files and file permissions. If you want to remove those files for some reason, make it another PR and let's discuss there.

**Comment by alanhartless** [comment]
Closing as there has not been any movement on this. Please, submit a new PR once issues are resolved.

**Pull request closed without merging**
