### PR TITLE
Fix segment membership filter build query

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✅ 
| New feature/enhancement? (use the a.x branch)      | 🟥 
| Deprecations?                          | 🟥 
| BC breaks? (use the c.x branch)        | 🟥 
| Automated tests included?              | ✅ 
| Related user documentation PR URL      | NA
| Related developer documentation PR URL | NA
| Issue(s) addressed                     | 

#### Description:

Query for include segment was build wrong. I fixed it and cover by unit tests

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create some segment with include/exclude segment membership 
3. Check If works like before

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10809"></a>

### CODE REVIEW

**Review by mmarton — DISMISSED** [review]
Tested and it works

**Comment by jos0405** [comment]
I tested it and works.
Just one comment. Is it okay, that I can choose the same segment membership which I'm editing right now? "Exclude SELF?"
image

**Comment by kuzmany** [comment]
@jos0405 This is not related to the PR, because we change logic on build query on `segments:rebuild`
You can create new issue If need it or handle by your dev ;)

**Comment by kuzmany** [comment]
@jos0405 this could be for inspiration https://github.com/mautic/mautic/pull/6540 (also note it for myself)

**Review by mabumusa1 — DISMISSED** [review]
I tested the changes, this PR looks good and works

**Comment by kuzmany** [comment]
@escopecz looks like this issue is fixed also in your PR https://github.com/mautic/mautic/pull/10903/files#diff-e305526f919971e7f5ba5d848760940416e89d89e415c68b8b15c43c32cd3f24R122 
That means during the merge 4.2 to 4.x it will make a lot of conflicts. Just note it

**Pull request merged**
