### PR TITLE
Add maker bundler

### PR DESCRIPTION
**Pull request by roboparker**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | no
| New feature/enhancement? (use the a.x branch)      | yes
| Deprecations?                          | no
| BC breaks? (use the c.x branch)        | no
| Automated tests included?              | no
| Related user documentation PR URL      | not relevant
| Related developer documentation PR URL | https://symfony.com/bundles/SymfonyMakerBundle/current/index.html
| Issue(s) addressed                     | 

#### Description:

Adding the maker bundle which add a handful of commands for generating things like controllers, entities, validators etc.

#### Steps to test this PR:

Because this is adding a command for development use only, there are no tests. You can view which commands are available with by running `php bin/console make:controller --help` in a dev environment

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11289"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
@diaboloshogunate please base all feature PRs on top of 5.x branch as there will be no more feature releases for Mautic 4.

**Review by escopecz — DISMISSED** [review]
👍

**Comment by RCheesley** [comment]
Thanks for the PR @diaboloshogunate but unfortunately on testing I am not getting the expected results:

```
gitpod /workspace/mautic (makers-bundle) $ ddev exec bin/console make:controller
                                                                                                                                                               
  There are no commands defined in the "make" namespace.                                                                                                       
                                                                                                                                                               
  You may be looking for a command provided by the "MakerBundle" which is currently not installed. Try running "composer require symfony/maker-bundle --dev".                                                                                                                                                         

Failed to execute command bin/console make:controller: exit status 1
```

I did try to install the maker-bundle, in case that resolved the issue, but instead that resulted in the following:

```
gitpod /workspace/mautic (makers-bundle) $ ddev exec composer require symfony/maker-bundle --dev
Using version ^1.43 for symfony/maker-bundle
./composer.json has been updated
Running composer update symfony/maker-bundle
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires symfony/maker-bundle ^1.43 -> satisfiable by symfony/maker-bundle[v1.43.0].
    - symfony/maker-bundle v1.43.0 requires symfony/config ^5.4.7|^6.0 -> found symfony/config[v5.4.7, v5.4.8, v5.4.9, 5.4.x-dev, v6.0.0-BETA1, ..., 6.2.x-dev] but the package is fixed to v4.4.42 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require symfony/maker-bundle:*" to figure out if any version is installable, or "composer require symfony/maker-bundle:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
Failed to execute command composer require symfony/maker-bundle --dev: exit status 2
```

**Comment by kuzmany** [comment]
@RCheesley I suppose to you need run it on dev environment ` ddev exec bin/console make:controller -e dev`

**Comment by RCheesley** [comment]
Thanks for the guidance @kuzmany indeed that was the issue.

When I run the command I do get the following message:

```
gitpod /workspace/mautic (makers-bundle) $ ddev exec bin/console make:controller -e dev

 ! [NOTE] It looks like your app may be using a namespace other than "App".                                             
 !                                                                                                                      
 !        To configure this and make your life easier, see:                                                             
 !        https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html#configuration                           

 Choose a name for your controller class (e.g. OrangePopsicleController):
 > 
```

So it seems to work with the correct documentation, but not clear if this requires any additional configuration at our side or not.  There is also a conflict to be addressed.

@diaboloshogunate this will require a small update to the developer documentation so that developers know this exists. I recommend you make the PR against https://github.com/mautic/developer-documentation-new which is the new WIP docs migration.

**Comment by roboparker** [comment]
@escopecz Would you prefer me to do this for 5.x instead? I can rebase and make a PR against the 5 branch.

@RCheesley I added config to include `Mautic` as the default default namespace. The suggested note is now removed. 

Adding a PR for the docs now. Thank you.

**Comment by RCheesley** [comment]
Thanks @diaboloshogunate ! The next release for features will be the 5.0 release so we will need it based on the 5.x branch indeed.

**Comment by roboparker** [comment]
closing in favor of https://github.com/mautic/mautic/pull/11313 which is based on 5.x

**Pull request closed without merging**
