### PR TITLE
Added new api endpoints

### PR DESCRIPTION
**Pull request by alanhartless**
This PR adds several new api endpoints:

/campaigns/{id}/lead/add/{leadId}
/campaigns/{id}/lead/remove/{leadId}
/emails/{id}/send
/emails/{id}/send/lead/{leadId}
/lists (alias of /leads/list/lists)
/lists/{id}/lead/add/{leadId}
/lists/{id}/lead/remove/{leadId}

To test, use the API tester in https://github.com/mautic/api-library/ to make API calls and examine the response and result in Mautic. https://github.com/mautic/api-library/pull/2 includes the new end points for the API library code.

### CODE REVIEW

**Comment by escopecz** [comment]
I tested this patch with your branch https://github.com/alanhartless/api-library/tree/api-updates. Authorization went well, but for every request I tested (leads, campaigns, campaigns/1, ...) I got only response as HTML page which had "Not Found" in the title.

Do you have some idea what am I doing wrong?

**Comment by escopecz** [comment]
So I was doing wrong:
- didn't append `/api/` after the base URL
- used **json** instead of just **/**

Results of testing:
:+1: `campaigns/{id}/lead/add/{leadId}`: 'success' => integer 1
:+1: `campaigns/{id}/lead/remove/{leadId}`: 'success' => integer 1
:+1: `emails/{id}/send`: 'success' => integer 1
:+1: `emails/{id}/send/lead/{leadId}`: 'success' => integer 1
:-1: `lists`: Controller "Mautic\LeadBundle\Controller\Api\LeadApiController::getListsAction" for URI "/api/lists" is not callable.
:-1: `leads/list/lists`: Controller "Mautic\LeadBundle\Controller\Api\LeadApiController::getListsAction" for URI "/api/leads/list/lists" is not callable.
:+1: `lists/{id}/lead/add/{leadId}`: 'success' => integer 1
:+1: `lists/{id}/lead/remove/{leadId}`: 'success' => integer 1

Notes:
- API Endpoint can't start with '/'
- Add, send and remove requests has to be POST the rest has to be GET.

So only '/lists/' makes problems.

**Comment by alanhartless** [comment]
@escopecz Try the last set of fixes. The lists endpoints should now work.  I also fixed the api doc generator at (/index_dev.php/s/api-docs/).  It's only available in dev mode due its dependency on twig. Not sure if the nelmio command line tools can be used to get a better formatted api docs.

**Comment by escopecz** [comment]
I can confirm that `leads/list/lists` and `lists` returns array of lists.

API doc at `/index_dev.php/s/api-docs/` works for me.

I'll merge this one.

**Pull request merged**
