### PR TITLE
Fix undefined select placeholder PHP Notice in form edit view

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.3
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Issue(s) addressed                     | Fixes #... 

#### Description:
An PHP Notice is generated every time form edit view is opened and select field has no placehodler. This PR should fix this.

```
[Thu Feb 25 11:53:34.527210 2021] [php7:notice] [pid 15968:tid 2148] [client 127.0.0.1:53252] PHP Notice:  Undefined index: placeholder in \\app\\bundles\\FormBundle\\Views\\Field\\select.html.php on line 35, referer: https://mautic3.local/s/forms/view/37
```

EDIT: This problem applies to forms created though API.

#### Steps to reproduce:
1. Create new form with `POST /api/forms/new`
```
{
    "name": "Test 2",
    "formType": "standalone",
    "description": "API test",
    "fields": [
        {
            "label": "field name",
            "type": "text"
        },
        {
            "label": "field select",
            "type": "select",
            "properties": {
                "list": {
                    "list": [
                        {
                            "label": "A",
                            "value": "A"
                        },
                        {
                            "label": "B",
                            "value": "B"
                        }
                    ]
                }
            }
        }
    ]
}
```
2. The PHP notice should be in the log after creating form and every time you open this form edit view

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat steps to reproduce

### CODE REVIEW

**Comment by npracht** [comment]
Hello @patrykgruszka can you detail a little more how to reproduce the NOTICE ? I don't find the way to generate it.

**Comment by patrykgruszka** [comment]
Hi @npracht,
I didn't notice this, but it seems like this problem applies only to forms created through API. I've updated the steps to reproduce this issue. Thanks for your comment!

**Review by mohit-rocks — APPROVED** [review]
It fixes the issue.
Here is the quick error from the log:

`[2021-07-29 13:50:48] mautic.NOTICE: PHP Notice - Undefined index: placeholder - in file /var/www/html/app/bundles/FormBundle/Views/Field/select.html.php -`

Steps performed to test it:
1. Create a form as mentioned in PR
2. Use the basic auth to create the form via API
3. Goto "forms/edit/{form id}" and you will see the errors in log.
4. With patch, error no longer appears

**Review by mohit-rocks — CHANGES_REQUESTED** [review]
@patrykgruszka You will have to rebase your current branch with latest `features` branch.
Reason is, we usually use `feature` branch for bugfixes etc.

**Comment by patrykgruszka** [comment]
@mohit-rocks sure, done.

**Review by kuzmany — APPROVED** [review]
Looks good 👍

**Review by mohit-rocks — APPROVED** [review]

**Pull request merged**
