### PR TITLE
PHPSTAN and Rector updates + baseline update

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [y]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

There should be more speed improvements for the new PHPSTAN and Rector versions. So pushing the update. Ya know, to save the planet.

#### Steps to test this PR:

1. Check that the build is green

### CODE REVIEW

**Review by mabumusa1 — APPROVED** [review]
Changes looks good

**Comment by mollux** [comment]
@escopecz really cool! I saw the release of [Rector](https://github.com/rectorphp/rector/releases/tag/0.17.3), and saw the possibilities that it brings.

**Comment by mollux** [comment]
@escopecz @mabumusa1 This seems to be merged with a failing PHPSTAN tests, see [the checks](https://github.com/mautic/mautic/actions/runs/5518110374/jobs/10061627270?pr=12531).
This impacts all current PR's against 5.x

**Comment by escopecz** [comment]
@mollux thanks for calling this out. Fixed in https://github.com/mautic/mautic/pull/12556

**Pull request merged**
