### PR TITLE
php-cs-fixer - update windows hook

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Based on this change https://github.com/mautic/mautic/commit/86cbffa8602587623640f231fad0e0bdeff1a4b7#diff-cdb9b1fbca700c14a1e4edf3a0c73e56 update for window hook

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1.  Run composer install. Try commit  cange from actual staging on Windows
2.  No code style change/fix

#### Steps to test this PR:
1.  Run composer install.  Repeat steps above.
2.  Code style fix works

### CODE REVIEW

**Comment by javjim-mautic** [comment]
Gettting this error
php-cs-fixer pre commit hook start

                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--config-file" option does not exist.              
                                                          
Running from a windows machine... Am I missing something?

**Comment by alanhartless** [comment]
@javjim-mautic the new version of PHP CS fixer uses `--config=.php_cs`

**Comment by alanhartless** [comment]
Oh that's what this PR fixes. Haha. Run `composer install` after checking out this PR to install the new hook

**Comment by javjim-mautic** [comment]
working properly on my windows machine

**Pull request merged**
