### PR TITLE
Prevent deadlocks caused by DNC changes

### PR DESCRIPTION
**Pull request by escopecz**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Scalability fix
| New feature? | N
| Automated tests included? | Y
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | /
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

We are hitting deadlocks on the leads table like this one:
```
2021-03-09 22:21:16.324 GMT
CAMPAIGN: An exception occurred while executing 'UPDATE mautic_leads SET date_modified = ?, modified_by_user = ?, company = ? WHERE id = ?' with params ["2021-03-09 22:21:16", " ", "School", "10468"]: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
```

This transaction run at the same time for the same contact ID 10468 and therefor causing the deadlock:
```
2021-03-09T22:21:16.298050Z	3912350 Query	START TRANSACTION
2021-03-09T22:21:16.298837Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10461')
2021-03-09T22:21:16.299193Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10462')
2021-03-09T22:21:16.300143Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10463')
2021-03-09T22:21:16.300514Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10464')
2021-03-09T22:21:16.300808Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10465')
2021-03-09T22:21:16.301125Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10466')
2021-03-09T22:21:16.301467Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10467')
2021-03-09T22:21:16.302652Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10468')
2021-03-09T22:21:16.302939Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10469')
2021-03-09T22:21:16.303291Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10470')
2021-03-09T22:21:16.304367Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10471')
2021-03-09T22:21:16.304773Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10472')
2021-03-09T22:21:16.305087Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10473')
2021-03-09T22:21:16.305356Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10474')
2021-03-09T22:21:16.305614Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10475')
2021-03-09T22:21:16.306917Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10476')
2021-03-09T22:21:16.307285Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10477')
2021-03-09T22:21:16.307614Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10478')
2021-03-09T22:21:16.308755Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10479')
2021-03-09T22:21:16.309074Z	3912350 Query	INSERT INTO mautic_lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES ('2021-03-09 22:21:16', 3, 'email', NULL, 'Opt out from import', '10480')
2021-03-09T22:21:16.309592Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10461'
2021-03-09T22:21:16.310149Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10462'
2021-03-09T22:21:16.311404Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10463'
2021-03-09T22:21:16.311895Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10464'
2021-03-09T22:21:16.312392Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10465'
2021-03-09T22:21:16.313754Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10466'
2021-03-09T22:21:16.314249Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10467'
2021-03-09T22:21:16.314748Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10468'
2021-03-09T22:21:16.315952Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10469'
2021-03-09T22:21:16.316560Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10470'
2021-03-09T22:21:16.318022Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10471'
2021-03-09T22:21:16.318605Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10472'
2021-03-09T22:21:16.319917Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10473'
2021-03-09T22:21:16.320586Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10474'
2021-03-09T22:21:16.321170Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10475'
2021-03-09T22:21:16.322596Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10476'
2021-03-09T22:21:16.323191Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10477'
2021-03-09T22:21:16.323915Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10478'
2021-03-09T22:21:16.324639Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10479'
2021-03-09T22:21:16.325244Z	3912350 Query	UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10480'
2021-03-09T22:21:16.326671Z	3912350 Query	COMMIT
```

The lead table updates like `UPDATE mautic_leads SET date_modified = '2021-03-09 22:21:16', modified_by_user = ' ' WHERE id = '10468'` are completely unnecessary as it's not saving any information to the lead record. The modified properties are set automatically on entity save when there are some changes in the entity. The DNC records are being set in the Lead entity changes array.

The solution is to let entities specify whether they want to set the modified properties or not. In this case the decision is whether the changes array is empty if we remove the DNC changes from it.

If a DNC record is created by a contact themselves then we also change the dateLastActive timestamp and so the contact record must be updated as well. This fix will only work for internal changes like from the UI, CSV import, API import, integration import.

Simplest way to test is from the contact list view like so:
Screen Shot 2021-03-11 at 11 19 15

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Add or modify a Do Not Contact record for a contact and check that the date modified will change for the contact entity. It should not.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat steps to reproduce and the date modified on the contact entity should not change after this change is applied.
3. When you send an email with unsubscribe link and then open the link in the incognito window then the DNC record will be created and the contact record will be updated with `dateLastActive` timestamp. So this works the same as before.
4. If you make a CSV with just DNC changes and import it then the contact `dateModified` timestamp will not be changed anymore.

#### Other areas of Mautic that may be affected by the change:
1. Basically all entities run through the changed method, so try to save other entities as well and check that the modified by and modified date are updating.

### CODE REVIEW

**Review by rohitpavaskar — DISMISSED** [review]

**Comment by dadarya0** [comment]
**Verify Date Modified is updated correctly based on the event.**


- Send an email to a contact. Click on the unsubscribe link and verify that the 'date_modified' value changes. - **PASS**
- Mark a contact as DO NOT CONTACT in ACS UI and verify that the 'date_modified' value does not change - **PASS**
- Import a list of contacts with DO NOT CONTACT property set to NO. Once import is successful, run the import again with all same values except DO NOT CONTACT set to YES. Verify that the date_modified does not change. **PASS** 
- Verify that the 'date_modified' and 'modified_by_user' changes correctly for following entities: **PASS**
  - Contacts
  - Companies
  - Segments
  - Assets
  - Forms
  - Campaigns
  - Reports
  - Landing Pages
  - Dynamic Content

**Comment by andersonjeccel** [comment]
@escopecz John, we're seeing some issues with DNC (exactly same thing on logs) but now triggered by Points Actions... do you see this issue from your customers?

**Comment by escopecz** [comment]
@andersonjeccel what issues? The same as described in this PR? This wasn't released yet.

**Comment by andersonjeccel** [comment]
@escopecz the same deadlock… it seems like the PR fixes only deadlocks caused by segments update 

we released the PR in production for ~10 instances, but we still have deadlocks caused by points actions 

the log shows exactly the same error and our devs confirmed

**Comment by escopecz** [comment]
This is fixing DNC changes specifically. I don't see a point action for the DNC record. Perhaps it's not related to this PR?

**Comment by andersonjeccel** [comment]
@escopecz got it, i'll check with them if we can release a PR to tackle that

thanks!

**Pull request merged**
