### PR TITLE
[Improvement] Add an index for manually_removed.

### PR DESCRIPTION
**Pull request by heathdutton**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | No
| Deprecations? | No

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This is used in queries for pulling segments which get very slow with 1m+ leads. Adding this index speeds those up by ~20% or more, which in our case is just enough to prevent timeouts.

### CODE REVIEW

**Comment by npracht** [comment]
@escopecz i think it is small enough and targeting perf enhancement to consider it as a 2.14 candidate ?

**Comment by npracht** [comment]
Label: Pending test confirmation

**Comment by heathdutton** [comment]
So does that mean we don't run schema:update --force during the mautic install/update process? Forgive me I don't do the UI based install/update.

**Comment by npracht** [comment]
@escopecz obviously migration file is there now, maybe that could be added to 2.14.0 ?

**Comment by npracht** [comment]
@escopecz if you can approve then it is ready to commit :)

**Pull request merged**
