### PR TITLE
Form will throw the uncaught errors if form is nor valid.

### PR DESCRIPTION
**Pull request by shinde-rahul**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ 5.x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

**Issue**: 
When attempting to upload a theme ZIP file larger than the allowed size set in the `upload_max_filesize` PHP setting, clicking the "Install" button does not result in feedback or action. An error message should be displayed to inform the user that the file exceeds the allowed limit.

#### Steps to Reproduce:

1. Update your PHP configuration (`php.ini`) to set the `upload_max_filesize` to **1M**.
    - Make sure to restart the server after making this change. (Please see [DDEV's docs](https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#custom-php-configuration-phpini))
2. Navigate to the theme upload page at `/s/themes`.
3. Click on the "Choose" button and select a theme ZIP file larger than 1MB.
4. Click on the "Install" button.
5. **Expected behavior**: Nothing happens, and no message is displayed.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Update your PHP configuration (`php.ini`) to set the `upload_max_filesize` to **1M**.
    - Please make sure you restart the server after making this change. (Please see [DDEV's docs](https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#custom-php-configuration-phpini))
3. Navigate to the theme upload page at `/s/themes`.
4. Click the "Choose" button and select a theme ZIP file larger than 1MB.
5. Click on the "Install" button.
6. **Expected behavior**: The form should display the error message `ERROR: The file is too large.` indicating that the selected file exceeds the allowed upload size.

NOTE: 
- The changes in `php.ini` are meant for testing only. Do not lower the value of the `upload_max_filesize` config setting.

#### Extras,
- Screencast

https://github.com/user-attachments/assets/c192bf33-9136-49d5-bb04-693e737b3c57

- Compressed zip
[mautic-wide.zip](https://github.com/user-attachments/files/17264739/mautic-wide.zip)

### CODE REVIEW

**Comment by RCheesley** [comment]
@shinde-rahul it might help folks testing if you are able to share a theme that they can use which will exceed the size set on Gitpod - do you have one that we can use to test with by any chance?

**Comment by shinde-rahul** [comment]
@RCheesley, I have lowered the settings to reproduce it. The instance got messy with these values, and this logical error surfaced. When I started debugging got to know the PHP configuration got messed up. Then later, set up the raw PHP app w/o altering the default values on the server, The default PHP value is 2 MB for upload_max_filesize.

**Comment by escopecz** [comment]
This should not be ready to test as it has broken CI checks

**Comment by MojisolaaaO** [comment]
@shinde-rahul I am a bit unclear on how to test this PR. Could you please add more details to the test steps like where the screen is and possibly a screenshot as well? Thank you

**Comment by shinde-rahul** [comment]
@MojisolaaaO, I have updated the PR description for more information.

**Comment by MojisolaaaO** [comment]
@shinde-rahul Thank you. I will check it out

**Comment by MojisolaaaO** [comment]
@RCheesley Kindly assign me to test this PR

**Comment by RCheesley** [comment]
@MojisolaaaO you don't need to be assigned to test a PR, so just go ahead and review/test.

@shinde-rahul it looks like there's a test failure here, can you take a peek?

**Review by imaabasiee — APPROVED** [review]
Reproduced the bug and tested the PR after. There is an error message to notify users that the file they are trying to upload exceeds 1MB.

**Review by abhisekmazumdar — APPROVED** [review]

**Comment by abhisekmazumdar** [comment]
Followed the steps. The changes LGTM.

**Review by escopecz — APPROVED** [review]
I see no problem with this code change. Thanks! 👍

**Pull request merged**
