### PR TITLE
Use Github directly for installing language packages

### PR DESCRIPTION
**Pull request by alanhartless**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Y
| Automated tests included? |Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

This simply changes Mautic to consume json configs from language files instead of PHP and changes from communicating through the legacy updates URL to using Github directly. 

[//]: # ( As applicable: )
#### Steps to test this PR:

Community: 
1. Before installing the PR, ensure that a language is installed by changing the default locale in the Configuration
2. Load up [this PR](https://mautibox.com)
3. Change the default locale through the Configuration to something that has not been used on the local installation before and click Apply. Look back at the locale list and it should have the language you chose selected.
4. Log out and back in and the language should be used
5. Run the migration `php app/console doctrine:migrations:migrate`. Look at the /translations folders. The language installed in step 1 should have a config.json instead of a config.php file.

### CODE REVIEW

**Comment by npracht** [comment]
@alanhartless can you have a look at Travis please?

**Comment by alanhartless** [comment]
Thanks @npracht! Not sure why my git hook is not working. Will see if I can get that resolved.

**Comment by RCheesley** [comment]
I've just been through the steps mentioned to test this, and indeed I see a config.json file.

However, what I am finding is that, although I've selected French as my language, both in the system settings and the user settings, I'm still seeing English.

I have logged out and logged back in, but still seeing the interface in English.

Not entirely sure if that is expected behaviour?

**Comment by kuzmany** [comment]
@alanhartless fix conflicts
Are you using it already on production?

**Comment by alanhartless** [comment]
@kuzmany fixed the conflicts by rebasing. Yes, we are using it in production.

**Comment by escopecz** [comment]
Same branch against the 3.x branch: https://github.com/mautic/mautic/pull/8225

**Comment by alanhartless** [comment]
Seems the tests are passing now but not sure why scrutinizer is failing and giving a 503.

**Comment by dennisameling** [comment]
Closing and re-opening this PR so that Scrutinizer can run again. Should work then

**Comment by RCheesley** [comment]
Setting as RTC based on test and comments re. use in production.

**Pull request merged**
