### PR TITLE
Normalize select values in form results email

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | features
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:

If you submit form with select and multiselect and receive form results you get values instead of labels. This PR fixed it

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create form
3. Create multiselect field with options - First => 1, Second => 2, Third => 3
4. Create form results to email action
5. Send form with two of selected options - First  and Seocnd
6. Check email - you receive values: 1, 2
7. After PR you receive in email: First, Second

### CODE REVIEW

**Review by RCheesley — COMMENTED** [review]
After applying the PR I see the following errors in the console and am unable to submit the form (worked fine before applying the PR)

```
Uncaught SyntaxError: Unexpected token } in JSON at position 12
    at JSON.parse (<anonymous>)
    at Object.Core.parseToObject (mautic-form-src.js?v5ca4101f:777)
    at mautic-form-src.js?v5ca4101f:834
    at mautic-form-src.js?v5ca4101f:842
Core.parseToObject @ mautic-form-src.js?v5ca4101f:777
(anonymous) @ mautic-form-src.js?v5ca4101f:834
(anonymous) @ mautic-form-src.js?v5ca4101f:842
mautic-form-src.js?v5ca4101f:183 Uncaught TypeError: Cannot read property 'test10087' of undefined
    at Object.Form.prepareValidation (mautic-form-src.js?v5ca4101f:183)
    at Object.Form.prepareForms (mautic-form-src.js?v5ca4101f:136)
    at Object.Core.onLoad (mautic-form-src.js?v5ca4101f:821)
    at HTMLScriptElement.script.onload (VM14 3:20)
Form.prepareValidation @ mautic-form-src.js?v5ca4101f:183
Form.prepareForms @ mautic-form-src.js?v5ca4101f:136
Core.onLoad @ mautic-form-src.js?v5ca4101f:821
script.onload @ VM14 3:20
load (async)
(anonymous) @ VM14 3:19
```

**Comment by kuzmany** [comment]
@RCheesley your issue is related to https://github.com/mautic/mautic/pull/9972. I update branch, please fetch it

**Review by RCheesley — CHANGES_REQUESTED** [review]
Thanks for updating the PR - I also just pulled in features as it was throwing an error.

When I test now the form submits and I receive the email with the labels rather than the ID numbers.

I noticed however that we are still using the ID in the form results layout - should we be consistent with this approach and use the labels here rather than the ID as well? 

screenshot-mautic4 ddev site-2021 06 24-16_18_23

**Comment by RCheesley** [comment]
@dadarya0 also tested this during the rotation and mentioned that issue to me but he hasn't left a comment on the PR to say that it was a successful test so have followed up on that.

**Comment by dadarya0** [comment]
I had tested it is working fine as per PR description 
I received email with the labels rather than the ID numbers.

I have a concern that we had replaced IDs to labels in email but on form result web page still it is showing IDs. should not be labels here instead of IDs same as email ?

**Comment by kuzmany** [comment]
@dadarya0 we had  report just display labels in email.
Probably we could fix display it in results in separate  PR later

**Comment by RCheesley** [comment]
OK let's aim to address the report labels issue in a separate PR (hopefully a fairly easy one to make!) so we can get this one merged.  Just running tests before merging :)

**Pull request merged**
