### PR TITLE
Workaround for lost campaign segments after clone campaign

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/5682
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This issue is reported https://github.com/mautic/mautic/issues/5682 
After clone campaign, if you launch builder and edit segments source, the campaign during save entity, lost segment source. Browser return log: **Cannot establish connection - source does not exist**
This workaround don't allow  launch builder until you save cloned campaign.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:

1. Clone a campaign that starts with a segment
2. Go on the builder
3. Click on the segment, do not change it (keep the same segment) but just click on update
4. Close the builder, save and close the campaign.
5. Go back on the campaign and go back on the builder,
6. You will see that there are no segments anymore

#### Steps to test this PR:
1.  Apply PR and clone campaign
2. Try Launch Campaign Builder
3.  See  alert and no campaign builder launched

image

### CODE REVIEW

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by npracht** [comment]
Label: Pending test confirmation

**Comment by Maxell92** [comment]
Hello @kuzmany,

It seems that there is a hidden issue. This PR helps to prevent it, but it is not a good experience for a user. Did you discovered a real reason of this issue?

It would be great if we can avoid this bug without forcing a user to save a cloned campaign.

**Comment by kuzmany** [comment]
@Maxell92 nope. I didn't discovered it. I did try, but without success

**Comment by Maxell92** [comment]
Hello @kuzmany,

We have discussed this PR and we want to discover that issue rather than force user to save incomplete campaign.

**Comment by alanhartless** [comment]
I removed this from 2.13 until we can figure out the issue.

**Comment by kuzmany** [comment]
@alanhartless can you hint some ideas how to resolve it? Or it's better wait for 2.14 with campaign refactoring and will fixed it? Thanks

**Comment by kuzmany** [comment]
Label: Pending Test Confirmation

**Comment by kuzmany** [comment]
Label: Pending Feedback

**Comment by npracht** [comment]
@kuzmany & @alanhartless maybe that could be closed in favor of https://github.com/mautic/mautic/pull/5942 ?

**Pull request closed without merging**
