### PR TITLE
[UX] Fixing page titles h-tag to improve accessibility

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
On the web, it’s common practice to use the H1 tag for the main title of a page for SEO and accessibility reasons. However, despite the hierarchy of titles (H1, H2, H3, etc.) may not have the same direct impact on SEO, as apps are not crawled by search engines in the same way web pages are, using a logical title structure is helpful for accessibility, as screen readers use this structure to assist users in navigation.

_Note! THIS INDIVIDUAL CHANGE WILL NOT CORRECT THE GROTESQUE ACCESSIBILITY PROBLEMS ON THE PLATFORM, AS OTHER CORRECTIONS ARE NECESSARY AND WILL ACT TOGETHER FOR A BETTER USE EXPERIENCE FOR USERS WITH DISABILITIES._

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Well, look at any title to see a subtle difference in its size (caused by the current CSS rules). If you are using a screen reader, you will notice that when you reach the page title it will read as level one (keep pressing tab unhurried until the reader reaches an item in the body and then use the arrow keys to try to reach the title).
3. /imagine How does a person with vision difficulties navigate the platform like this?

### CODE REVIEW

**Comment by LordRembo** [comment]
I understand the need to restructure the headings but I think you should include CSS changes to match the current styling as well. Otherwise this change 'breaks' the design. While smaller PR's with incremental changes make sense, you shouldn't introduce breaking changes into the 5.x branch. That leads us back to an earlier remark of perhaps not merging against 5.x but another branch instead, if you want to keep making small PR's like this. Eg. a UX branch to go along the UI branch.
Something to discuss next week I think.

**Review by LordRembo — CHANGES_REQUESTED** [review]
.

**Review by LordRembo — CHANGES_REQUESTED** [review]
Adding a comment to request changes:  as mentioned, I'd suggest adding the necessary CSS to make sure the changed heading matches the previous H3

**Comment by andersonjeccel** [comment]
Fixed! Thanks

@LordRembo

**Comment by LordRembo** [comment]
@andersonjeccel Is it possible the CSS/Less changes are incomplete? I'm seeing a variable was added (`@font-size-h1`), but I don't see where it is being used. I do see a change to a hardcoded px value.

**Comment by andersonjeccel** [comment]
The `@font-size-h1` is located on `node_modules/bootstrap/less/variables.less` (which are default values for bootstrap, they are not monitored by grunt compile-less nor Git changes, perhaps bc they get overwritten when you run `npm install`).

The file located on node_modules is imported by `/app/bundles/CoreBundle/Assets/css/libraries/bootstrap/bootstrap.less`. 

When I use a new value on the LESS files watched by grunt (located inside /libraries folder), it overwrites the default bootstrap value and changes the CSS you're seeing.

**Review by LordRembo — APPROVED** [review]
Alright, perfect. Looks good then.

**Comment by code5rick** [comment]
Somehow I am unable to open this PR on Gitpod, it gives me an error when initializing it 😢

**Review by RCheesley — APPROVED** [review]
Thanks for fixing this!

For sure we need to pay more attention to this - for example I noticed that when you view a report we have an H1 tag and then jump to an H5 tag!

One step at a time! 🪜

**Review by escopecz — APPROVED** [review]
Code changes are OK 👍

**Pull request merged**
