### PR TITLE
Fix replace image from file manager

### LINKED ISSUE #9116: ELFinder not inserting image in builder
## Bug Description
On 3.0.2 and 3.1-Release Candidate when selecting an image from the file manager and double clicking to insert, nothing happens and there is  no error in the log either.

Reported in the forum here: https://forum.mautic.org/t/adding-images-to-an-email-by-selecting-it-from-elfinder/15698/3

Screencast: https://youtu.be/iyW9U2l2Azo

| Q   | A
| --- | ---
| Mautic version | 3.0.2 & 3.1-Release Candidate 
| PHP version | 7.2.32
| Browser | Chrome

### Steps to reproduce
1. Open an email to edit and create a block which contains an image
2. Try to replace the image using the file manager (not drag/drop or link)
 
### Log errors
None

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.1
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/issues/9116

#### Description:
This PR fixed replace image from elfinder file manager in image slot and froala editor. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com) (without mautibox require `mautic:assets:generate`)
2. Create email and insert image from slot
3. Try replace image from any image from filemanager
4. Create text slot and insert image
5. Try replace image from any image from filemanager
6. Without patch both cases are not properly replaced

### CODE REVIEW

**Review by sPradella — APPROVED** [review]
I have tested it and it works! 
But sometimes the email builder is blank and nothing works. Or when I want to replaced the Image a second time in the froala editor, the file manager does not open. Is that a Mautibox problem or another?

**Comment by npracht** [comment]
I think it is because mautibox can be a bit slow or server issue. Nothing related with the PR itself.

**Comment by kuzmany** [comment]
- builder is blank looks like is related to Mautibox
- when I want to replaced the Image a second time in the froala editor - yes, it's issue

**Comment by sPradella** [comment]
fyi: the image issue only happened sometimes

**Review by escopecz — APPROVED** [review]
Works for me too. Thanks Zdeno! 👍

**Pull request merged**
