### PR TITLE
Code mode

### PR DESCRIPTION
**Pull request by escopecz**
This PR was created only because GitHub showed all commits for Mautic 2.3 in the old one. For all the info, go to https://github.com/mautic/mautic/pull/2653

### CODE REVIEW

**Comment by mqueme** [comment]
This is not working for me, I see no code column at all
screen shot 2016-11-24 at 15 55 52

**Comment by alanhartless** [comment]
I just retested and all worked for me. I've noticed lately that chrome is aggressively caching things. I have to often open developer console where I have cache disabled by default or clear my browser's cache to get things recognized.

**Comment by mqueme** [comment]
I have tried in chrome and firefox, nothing appears for me with ctrl+space bar, I am on mac, so I have tried cmd + spacebar. still nothing on any of the browsers. Also on some pages this is how the code view shows. and I get that js error.

screen shot 2016-11-25 at 09 41 32

**Comment by mqueme** [comment]
Just as suggestions:
1. make the window resizable to give people more control as to where the code has gone, some of it seems to be formatted in one long line. Also it feels a bit constricted when its that size for when people want to paste code from somewhere else.
2. a small text note or a tip indicating people what the ctrl command is for tokens would be a good idea.
And Tokens?
3. Will there be tokens for pages?

**Comment by Dcoutelle** [comment]
After applying PR shortcut icon on contact index page disappear, even with admin user

capture

**Comment by escopecz** [comment]
@Dcoutelle that's because of https://github.com/mautic/mautic/pull/2905, not this PR. The batch buttons were moved to the "select all" checkbox.

**Comment by escopecz** [comment]
@mqueme Please, retest.
1. Format Code button added which formats the HTML code on click. So it will fix issue if the whole HTML code is on one line.
2. The hit was added bellow the editor.
3. Pages tokens are now there.
4. I added Media Manager. It will allow to select a file and the URL will be inserted to the current cursor position.

**Comment by mqueme** [comment]
This all worked for me now. Thank you!

**Comment by alanhartless** [comment]
fantastic!

**Pull request merged**
