### PR TITLE
Fixed contenteditable content  and unscrollable e-mail (closes #2501)

### LINKED ISSUE #2501: Leaked contenteditable into e-mails when manually send to contact
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | y |
| Feature request? | n |
| Enhancement? | n |
## Description:

When e-mail is sent manually to contact there are content editable attributes leaked in e-mail. Thunderbird respects this attribute, e-mail then is editable in preview.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |
| PHP version | 5.6 |
### Steps to reproduce:
1. Create standard e-mail from any template.
2. Send it manually to any lead you have access to mailbox.
3. Open it in Thunderbird and you will be able to edit content of e-mail in preview.
### Log errors:

No errors.

### PR DESCRIPTION
**Pull request by dakur**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Related user documentation PR URL | -
| Related developer documentation PR URL | -
| Issues addressed (#s or URLs) | #2501 
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Fix of the issue. For more information see discussion at #2501.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
See #2501.

#### Steps to test this PR:
Follow steps from `Steps to reproduce the bug`.

### CODE REVIEW

**Comment by npracht** [comment]
Hi,

I just tested.
* It solves https://github.com/mautic/mautic/issues/4162 : the webview page is not editable anymore!! 👍 
* The CSS is still broken, as you can see the blocs are separated which does not happen when sending through campaigns or segment email.
capture d ecran 2017-06-06 a 10 05 23

**Comment by LucasFarley** [comment]
Dear,

Did you tested using a long e-mail to check if the scroll is working?

I tested using a long e-mail but is not working.

**Comment by dakur** [comment]
@LucasFarley I don't know what long e-mail does mean. I've tested an e-mail of usual length - let's say four paragraphs, few other lines of text and some images. Can you provide more information?

**Comment by LucasFarley** [comment]
@dakur, i tried to say "an e-mail with more than two pages when is necessary to scroll dow to see all the content."
I am sending the exemple in attached.

In order to help, i identified that the problem is happening because the parameter "overflow:hidden" in the style `<style data-fr-style="true">` in the head of html, but your code change the style in "body" however the overflow is in "head".

[mail.txt](https://github.com/mautic/mautic/files/1055773/mail.txt)

**Comment by dakur** [comment]
@LucasFarley I've tried to create really long e-mail and everything works fine. See [results on EmailsOnAcid](https://www.emailonacid.com/app/acidtest/display/summary/Oz3HVj14EYvTZQ7cUp8TaM969qCGAu9hp6rDCVPARgtDi/shared).

**Comment by dakur** [comment]
@npracht The purpose of this pull request was to fix #2501, not #4162.

**Comment by dakur** [comment]
@LucasFarley Aha, I see. It's because your webmail parses the `<style>` tag. Hmm, that's tricky. Have to think about it...

**Comment by dakur** [comment]
@LucasFarley OK, I've made some more magic. It seems it works, but please test it.  
cc @escopecz Please make another review of that crazy code.

**Comment by LucasFarley** [comment]
@dakur, I tested the last changed, but kept with error.
I advance, i applied the same code in "media/js/app.js" and tested again. **So, in this way it worked.**
So, please change the file media/js/app.js too.

**Comment by dakur** [comment]
@LucasFarley Oh, I forgot to regenerate assets, I'll do it tomorrow.

**Comment by dakur** [comment]
@LucasFarley Done.

**Comment by dakur** [comment]
So how about this? Could this be merged and shipped in 2.9.0? cc @escopecz

**Comment by dakur** [comment]
Or any earlier version, if there is any planned.

**Comment by dongilbert** [comment]
+1 thanks @dakur

**Pull request merged**
