### PR TITLE
Add an extra Emoji exception for Outlook rendering

### PR DESCRIPTION
**Pull request by MohHeader**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ Y ]
| New feature/enhancement? (use the a.x branch)      | [ N ]
| Deprecations?                          | [ N ]
| BC breaks? (use the c.x branch)        | [ N ]
| Automated tests included?              | [ N ] 

#### Description:

Building on
PR: https://github.com/mautic/mautic/pull/2706#issue-182131240
issue: https://github.com/mautic/mautic/issues/2440

Just added an extra case for exceptions : office:word

### CODE REVIEW

**Review by jos0405 — DISMISSED** [review]
This works in various outlook versions

image

image

image

**Comment by jos0405** [comment]
@MohHeader. thank you for your contribution, really appreciate it. Could you sign the cla as written above so we can merge this?

**Review by mabumusa1 — DISMISSED** [review]
The code looks good, this PR is good to go.

Thanks @MohHeader please sign the contributor agreement so we can merge this PR

**Comment by mabumusa1** [comment]
@MohHeader following up with you on the agreement signing. looking forward to having you as part of the community

**Comment by MohHeader** [comment]
> @MohHeader following up with you on the agreement signing. looking forward to having you as part of the community

Thanks, it's my honor
I have signed it already, please let me know if I need to re-sign it again.

**Comment by mabumusa1** [comment]
@cla-check

**Comment by mabumusa1** [comment]
@cla-bot

**Comment by mabumusa1** [comment]
@cla-bot check

**Comment by mabumusa1** [comment]
@MohHeader thanks for your contribution, please fix the pending issues then it will be ready to be merged

**Comment by MohHeader** [comment]
> @MohHeader thanks for your contribution, please fix the pending issues then it will be ready to be merged

@mabumusa1 I am really sorry, but I am not sure what should I do,
Can I delete my PR, and someone of the team makes the required update? to fix the original issue

I am not a PHP developer, nor I know what is "CS Fixer" that is failing 

Thanks for your understanding

**Comment by MohHeader** [comment]
@mabumusa1 I am really sorry, after 5 Months just to find all I needed to do was to add "  " extra spaces, I believe the PR is now ready

**Review by mabumusa1 — APPROVED** [review]
Looks good, and ready to merge

**Comment by mabumusa1** [comment]
> @mabumusa1 I am really sorry, after 5 Months just to find all I needed to do was to add "  " extra spaces, I believe the PR is now ready

Thanks @MohHeader I just reviewed and it will be merged soon

**Comment by RCheesley** [comment]
@all-contributors please add @MohHeader for code

**Pull request merged**
