### PR TITLE
Updating minimum version for new themes

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR sets the minimum version for new Mautic themes to 5.2

### CODE REVIEW

**Comment by escopecz** [comment]
@andersonjeccel can you please describe the reason for this change?

**Review by kuzmany — DISMISSED** [review]

**Comment by andersonjeccel** [comment]
@escopecz Ruth asked

See last 3 messages in Slack, #t-product for a bit more context, but ask her for the reason why

The main point is that these themes rely on the `@defaults` folder that is not available in versions below 5.2

**Comment by escopecz** [comment]
I wasn't asking just for me to understand but for anyone who is investigating why this was set a year later. I guess you mean:
```
Ruth Cheesley (she/her)
  5:14 PM
In particular my concern was that some changes made to the blank theme recently (which a lot of folks use) make it only suitable for use in 5.2 and above, because it's dependent on some files in the 5.2 release. Do we need to worry about someone cloning, for example, a 5.1 release or any lower release than 5.2, if we mark the Blank theme as supporting 5.2 and above?

Ruth Cheesley (she/her)
  6:38 PM
Right, all the themes are now set up on Packagist, added to composer and the lock file is updated. Just the last issue with the themes and supported versions, and the bug we found with the email builder, to address
```
What files were changed so the themes wouldn't work on M5.0? I just want to understand the reason for this change. It's not obvious to me.

cc @RCheesley

**Comment by RCheesley** [comment]
My understanding is that in the improvements to the Blank theme (merged in [this PR](https://github.com/mautic/mautic/pull/14255)), it now has a dependency on the Defaults folder (eg [here](https://github.com/mautic/mautic/pull/14255/files#diff-67589ed1dfb6069e04f919f606c72e28418402b6ed7dd58577ccad802c841b72R1)). 

This isn't present in any release prior to 5.2, so as far as I understand it, if you were to use this version of the Blank theme in a version before 5.2, it will break because those resources won't be present in the build.

**Comment by escopecz** [comment]
@RCheesley you are right. I missed that. Now it makes sense to me. Thanks!

**Review by escopecz — APPROVED** [review]
I approve these changes 👍

**Comment by RCheesley** [comment]
@andersonjeccel please can you test what happens if you're installing via Composer and you're explicitly pulling in a version under 5.2 - whether they actually get a blank theme or not? Thanks!

**Comment by andersonjeccel** [comment]
@RCheesley I have no experience with composer, so can't help that much...

**Comment by matbcvo** [comment]
I installed Mautic 5.1.1 using Composer with the following command:
```
composer create-project mautic/recommended-project mautic "5.1.1"
```
Then I checked which themes are installed and available:
```
testenv2@carbon:~/httpdocs$ ls -al mautic/docroot/themes/
total 92
drwxr-xr-x 20 testenv2 psacln 4096 Dec  2 08:45 .
drwxr-xr-x  7 testenv2 psacln 4096 Dec  2 08:45 ..
drwxr-xr-x  5 testenv2 psacln 4096 Mar 28  2023 aurora
drwxr-xr-x  4 testenv2 psacln 4096 Mar 28  2023 blank
-rw-r--r--  1 testenv2 psacln 5086 Dec  2 08:45 blank-big.png
-rw-r--r--  1 testenv2 psacln 4035 Dec  2 08:45 blank.png
drwxr-xr-x  4 testenv2 psacln 4096 Mar 28  2023 brienz
drwxr-xr-x  5 testenv2 psacln 4096 Mar 28  2023 cards
drwxr-xr-x  4 testenv2 psacln 4096 Mar 28  2023 confirmme
drwxr-xr-x  7 testenv2 psacln 4096 Mar 28  2023 fresh-center
drwxr-xr-x  7 testenv2 psacln 4096 Mar 28  2023 fresh-fixed
drwxr-xr-x  7 testenv2 psacln 4096 Mar 28  2023 fresh-left
drwxr-xr-x  7 testenv2 psacln 4096 Mar 28  2023 fresh-wide
drwxr-xr-x  4 testenv2 psacln 4096 Mar 28  2023 goldstar
drwxr-xr-x  6 testenv2 psacln 4096 Mar 28  2023 neopolitan
drwxr-xr-x  6 testenv2 psacln 4096 Mar 28  2023 oxygen
drwxr-xr-x  4 testenv2 psacln 4096 Apr 18  2024 paprika
drwxr-xr-x  6 testenv2 psacln 4096 Mar 28  2023 skyline
drwxr-xr-x  5 testenv2 psacln 4096 Mar 28  2023 sparse
drwxr-xr-x  6 testenv2 psacln 4096 Mar 28  2023 sunday
drwxr-xr-x  3 testenv2 psacln 4096 Mar 28  2023 trulypersonal
drwxr-xr-x  5 testenv2 psacln 4096 Mar 28  2023 vibrant
```

```
testenv2@carbon:~/httpdocs$ cat mautic/docroot/themes/blank/composer.json
{
  "name": "mautic/theme-blank",
  "description": "Mautic Blank Theme",
  "type": "mautic-theme",
  "keywords": ["mautic","theme"],
  "extra": {
    "install-directory-name": "blank"
  },
  "minimum-stability": "dev",
  "require": {
    "mautic/core-lib": "^5.0"
  }
}
```

I can see that there is a theme named `blank` in the `themes` folder.
Just to confirm, I completed the Mautic 5.1.1 installation and checked it in the Mautic UI. Here are the screenshots.

<details>
<summary>Screenshots</summary>

image

image

image
</details>

**Review by matbcvo — APPROVED** [review]

**Comment by RCheesley** [comment]
@matbcvo OK thanks - my concern is that merging this PR will make that package only support from 5.2 and higher due to this change in the blank theme's composer file:

https://github.com/mautic/mautic/pull/14302/files#diff-d79e26fed796ea7ba7f390e87bb1c5975a29dfc857d47851759fe635802e1a71L11

But maybe cloning from 5.1.1 will pull the state as it was then so perhaps it's not an issue (my composer knowledge is a little limited)

**Comment by matbcvo** [comment]
As long as `mautic/theme-blank` has tags with the correct `mautic/core-lib` version specified in its `composer.json`, Composer will resolve the appropriate version of the blank theme for each Mautic installation. This ensures that Mautic 5.1.1 gets the 5.1.1 tag of the blank theme, and Mautic 5.2 gets the 5.2 tag.

Since `mautic/theme-blank` has tags with the correct `core-lib` version constraints, it should be safe to merge this PR.

image

```
$ composer create-project mautic/recommended-project mautic-5.1.0 "5.1.0"
...
$ composer show mautic/theme-blank
name     : mautic/theme-blank
descrip. : Mautic Blank Theme
keywords : Mautic, theme
versions : * 5.1.0
```

```
$ composer create-project mautic/recommended-project mautic-5.1.1 "5.1.1"
...
$ composer show mautic/theme-blank
name     : mautic/theme-blank
descrip. : Mautic Blank Theme
keywords : Mautic, theme
versions : * 5.1.1
```

Since `mautic/theme-blank` shares the same tags as `mautic/mautic`, their versions are identical.

However, Mautic 5.1.0 does not pull the blank theme version 5.1.1 because the `mautic/recommended-project` `composer.json` includes this line:
```
"mautic/theme-blank": "5.1.0"
```
If the constraint was set to:
```
"mautic/theme-blank": "^5.1"
```
Composer would automatically resolve and install the latest tagged release in the 5.1.x series from the `mautic/theme-blank` repository. Composer also checks the `core-lib` version constraint specified in `mautic/theme-blank`'s `composer.json` to ensure compatibility.

**Pull request merged**
