### PR TITLE
New report: Contact's segments activity log

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

This PR added new report type: Contact's segments activity log
This PR allow working with contact event log like date added to segment and date_removed from segment

image

image

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com) + try some contacts add/remove from segments
2. Create report Contact's segments activity log
3. Play with date added to segment  and date removed segment column include filters.
4. Check if your results are correct

### CODE REVIEW

**Review by npracht — DISMISSED** [review]
Ok it works. But with a huge amount of data and without filtering on a specific segment, you may face a timeout.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebased

**Review by RCheesley — DISMISSED** [review]
Tested and works as expected, report configuration as per the PR description and I removed this contact from segments to check that the date/time was correct:

screenshot-local mautic3-2020 08 15-16_03_35

Thanks for the PR @kuzmany !

**Review by dennisameling — CHANGES_REQUESTED** [review]
Although I really like this feature, I don't feel confident merging it due to the lack of tests. Not just because we want to increase test coverage, but because it's gonna be extremely hard for another developer to understand your code without having tests that show how the code is intended to work. This is especially true because there are a lot of queries in here, which are even harder to understand for someone who sees the code for the first time. You should be able to look at `SegmentReportSubscriberTest` which I think is quite similar. Sorry 🙈

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Still waiting on tests for this one - as soon as we get the code coverage up we are good to go!

**Comment by kuzmany** [comment]
@RCheesley unit tests added by @julienWebmecanik

**Review by dennisameling — APPROVED** [review]
Thanks! 🚀

**Pull request merged**
