### PR TITLE
Add background-position and background-image to section content and wrapper

### PR DESCRIPTION
**Pull request by Enc3phale**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | N
| Related user documentation PR URL | N
| Related developer documentation PR URL | N
| Issues addressed (#s or URLs) | N
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This add background image position and all necessary fields to add image into content in Email builder and Landing builder.
Moreover this add Outlook tag for background-image when the builder is Email builder.

[//]: # ( As applicable: )
#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com/7211)
2. Clear cache and regenerate assets
3. Open Email Builder, Select a data-section element
4. Then you'll see additional field in Customize Section menu to change the background image position, and all field necessary to add image into content. Input some value to it, then save.

screenshot_2019-02-04 editer l email - double opt-in webmecanik automation

### CODE REVIEW

**Review by npracht — DISMISSED** [review]
except some version of outlook <3 it works perfectly.

**Comment by npracht** [comment]
Using in production environment.

**Comment by RCheesley** [comment]
@npracht this is a feature rather than a bugfix so it can't go into 2.16.1 - at least that is my understanding of semantic versioning. Let's move it to 3.1?

**Comment by npracht** [comment]
Yes and no. If we don’t add it in 2.x series we should close it. With the new email builder this is outdated. Let’s add it for people that will stay in 2.x version ?

N.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebased

**Comment by RCheesley** [comment]
@npracht given your comments about the email builder, do we want to merge this or not? If we go forward, @kuzmany could you rebase against staging so that we can get the code coverage report? Many thanks!

**Comment by npracht** [comment]
@RCheesley i think we should merge this, i use it very often and this is nice.
It is already up to date to staging. What do you want exactly ?

**Comment by RCheesley** [comment]
We need to rebase the PR because we don't have a code coverage report - I can't do it when it's on a Webmecanik branch as that is protected :) @kuzmany could you take a look, should be a quick task and would allow the job to get in the queue!

**Review by RCheesley — COMMENTED** [review]
Hi folks, great additions with these changes.

I had some questions around the image selection not being a click to upload feature, and the styling for the dropdown (which might be related to my browser, not sure!).  I don't know if this is a limitation of the builder, or if it is a field being the wrong type (text entry rather than file upload) so please let me know either way! 

Screencast: https://youtu.be/osrIBmBnOvE

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@npracht @kuzmany please can one of you rebase this one to update the code coverage report?

**Comment by kuzmany** [comment]
@RCheesley rebased on actual staging

**Review by RCheesley — APPROVED** [review]
Subject to tests passing given this is in use in production for some time at Webmecanik and had positive tests, LGTM! 🚀

**Pull request merged**
