### PR TITLE
Tags can be imported via csv

### PR DESCRIPTION
**Pull request by volha-pivavarchyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | https://github.com/mautic/user-documentation/pull/98/files#r1280294088
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR adds possibility to import contacts with tags from a CSV

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Import contacts with tags. The mock file can be used:  [MOCK_DATA_3_CONTACT.csv](https://github.com/mautic/mautic/files/11983946/MOCK_DATA_3_CONTACT.csv)
image

3. Checking that tags are added to contacts

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
The code looks great. 👍 

Please update the import docs for the 5.x branch that the tags should be separated by `|`. Otherwise users won't know how to import more than 1 tag.

**Review by kuzmany — APPROVED** [review]
works 👍

**Comment by escopecz** [comment]
@volha-pivavarchyk please add a note to the docs and this can be merged.

**Comment by volha-pivavarchyk** [comment]
@escopecz Is [docs.en.md](https://github.com/mautic/mautic-documentation/blob/main/pages/12.contacts/02.import-contacts/docs.en.md) the import docs ?

**Comment by volha-pivavarchyk** [comment]
@escopecz We found one small issue related to the title of the `tags` column title in a csv file. I fixed it. Should I add fix here or in the separate PR?

**Comment by escopecz** [comment]
@volha-pivavarchyk rather here to the 5.x branch:

https://github.com/mautic/user-documentation/blob/5.x/docs/contacts/import_contacts.rst

Please create another PR for the fix as this has been approved already.

**Comment by volha-pivavarchyk** [comment]
@escopecz Should I add a description of the entire import process as the page is empty? 

Or maybe I don't understand the process of updating documentation :slightly_smiling_face:

**Comment by escopecz** [comment]
@volha-pivavarchyk I missed that part that it's an empty file 🙂 Apologies. I think that it's waiting for https://github.com/mautic/mautic-documentation/blob/main/pages/12.contacts/02.import-contacts/docs.en.md to be ported over.

@RCheesley what would you suggest here? Edit the old doc or just add one line to the empty file?

**Comment by volha-pivavarchyk** [comment]
@escopecz I can create one PR with the old doc a second PR describing these changes. Only I don't know if the old document should be moved as is or if it should be corrected.

**Comment by RCheesley** [comment]
If this is going into 5.0 and beyond, I'd humbly ask if you would be willing to pull over the content to the new docs (https://github.com/mautic/user-documentation) that would be super helpful. We must have missed this in the Season of Docs work. cc @mautic/education-team for info - we should check for other missing sections.

If it helps, this is a .md to .rst converter:vertopal.com/en/convert/markdown-to-rst which I have used in the past, and I'm happy to assist with grammar checks. If you are using an IDE there is usually a Vale plugin which helps you as you type to correct the text. 

Feel free to ping me on Slack for any guidance that might be needed!

**Comment by RCheesley** [comment]
Hi folks, we can add the docs based on the work in https://github.com/mautic/user-documentation/pull/98 - hadn't realised we had a couple which were still pending changes.

I'm OK for the PR to be merged and make an issue to follow up with the docs before General Availability release.

**Comment by escopecz** [comment]
I've added docs as a PR comment: https://github.com/mautic/user-documentation/pull/98/files#r1280294088

**Pull request merged**
