### PR TITLE
Fix error when /tmp is not available

### LINKED ISSUE #9928: Mautic command cache:clear throws Exception when /tmp directory is not accessible
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The constructor of the Symfony class \Symfony\Component\Cache\Adapter\FilesystemAdapter expects a `$directory` parameter, and when it's not provided it uses the /tmp directory.

Usually on shared environments the /tmp dir isn't avaliable for usage. On my case, we have many users that use /tmp/user.

| Q   | A
| --- | ---
| Mautic version | 3.3.1
| PHP version | 7.4.16
| Browser | Any

### Steps to reproduce
1. Download Mautic on an Unix environment without access to /tmp
2. Run the cache clear command: `php path/to/your/mautic/instalation/folder/bin/console cache:clear`
 
### Log errors
```
php7.4 bin/console c:c -vvv

 // Clearing the cache for the prod environment with debug false                                                        

In CacheClearSubscriber.php line 55:
                                             
  [Exception]                                
  Failed to clear FilesystemTagAwareAdapter  
                                             

Exception trace:
  at /home/pedro/mkt/app/bundles/CacheBundle/EventListener/CacheClearSubscriber.php:55
 Mautic\CacheBundle\EventListener\CacheClearSubscriber->clear() at /home/pedro/mkt/vendor/symfony/http-kernel/CacheClearer/ChainCacheClearer.php:41
 Symfony\Component\HttpKernel\CacheClearer\ChainCacheClearer->clear() at /home/pedro/mkt/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:111
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /home/pedro/mkt/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /home/pedro/mkt/vendor/symfony/console/Application.php:1005
 Symfony\Component\Console\Application->doRunCommand() at /home/pedro/mkt/vendor/symfony/framework-bundle/Console/Application.php:86
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /home/pedro/mkt/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /home/pedro/mkt/vendor/symfony/framework-bundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/pedro/mkt/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /home/pedro/mkt/bin/console:43
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/98195151-mautic-command-cache-clear-throws-exception-when-tmp-directory-is-not-accessible?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pedrodejesus**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | features
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | Fixes #9928 

#### Description:
Mautic default tmp directory should be provided as a parameter to the \Symfony\Component\Cache\Adapter\FilesystemAdapter class constructor.

### CODE REVIEW

**Comment by RCheesley** [comment]
Hi @pedrodejesus and thank you for both reporting the issue and making a PR to address it! 🎉 

~If you could please sign the contributors agreement that would be awesome~ ✅  - there may be a delay in tests running as we are in the process of merging a bunch of PRs as part of the Mautic 4 sprint, so we are working Github Actions pretty hard! 😅

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by npracht** [comment]
How can we test it ? We need a developer eye I believe ?
cc @kuzmany @dennisameling @johbuch @mohit-rocks your help would be very (highly) appreciated ❤️

**Comment by biozshock** [comment]
This patch indeed fixes the error, when the `sys_get_temp_dir` is not available. But IMO the directory should not be passed if the directory returned by `sys_get_temp_dir` exists, and is writable, or there should be a flag that will switch between writable `sys_get_temp_dir` path or `%mautic.tmp_path%` parameter. Otherwise developers will be forced to set `%mautic.tmp_path%` to `sys_get_temp_dir`.

Also please pass the variable containing the directory to tag cache pool (2nd parameter in `parent::__construct` of `FilesystemTagAwareAdapter`)

**Review by PierreAmmeloot — DISMISSED** [review]
I have same issue, I have test this commit and it's done!

**Review by mabumusa1 — DISMISSED** [review]
I did a code review, it looks good to me

**Comment by mabumusa1** [comment]
@biozshock if you think this PR is good, we can merge it

**Comment by biozshock** [comment]
I don't think this is a Mautic issue, but a setup issue. You can set `sys_temp_dir` in `php.ini`. There are more places where code expects `sys_get_temp_dir` to return a true temporary directory path.
@kuzmany, thoughts?

**Review by PierreAmmeloot — APPROVED** [review]

**Comment by escopecz** [comment]
@pedrodejesus there is a discussion about this in https://mautic.slack.com/archives/CQMKV0RU1/p1674218992157979. Can you tell us more about why it is an issue for you?

**Comment by mabumusa1** [comment]
@pedrodejesus Following up on this PR. There was a discussion on slack with the comment above. What are your thoughts?

**Review by escopecz — APPROVED** [review]

**Comment by RCheesley** [comment]
@all-contributors please add @pedrodejesus for code

**Pull request merged**
