### PR TITLE
Japanesse fonts in forms

### PR DESCRIPTION
**Pull request by lukassykora**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Form results emails don't cooperate with template emails using Japanese fonts

#### Steps to test this PR:

- Create a template email
- Set the default font using the Japanese characters, add text TEST
- Save the email
- Create a form with just an email field (add other fields if you want, but they're not necessary)
- Add a form action to send form results
- Select the email you just created to use as a template for the form results email
- Click save/update (you even do not need to save it, it is broken in the session)
- Edit the send form results action

Expected results: The basic text TEST should still appear as what would be sent when a contact submits the form

### CODE REVIEW

**Review by kuzmany — DISMISSED** [review]
Good 👍 
Thanks

**Comment by RCheesley** [comment]
@lukassykora @kuzmany I am struggling a bit to reproduce this following the instructions.

When you say:

> Set the default font using the Japanese characters

Do you mean set the language of the email to Japanese?

In the editor these are the font families I have available - I could not see a font which relates to Japanese characters.

screenshot-mautic4 ddev site-2021 09 15-12_12_45

I tried with the language set to Japanese and could not reproduce the bug so would value some guidance!

**Comment by jos0405** [comment]
I couldn't reproduce this on Mautic 4.0.0.

image

And

image

Tried even with capital letters:

image


Both saving fine.

**Comment by RCheesley** [comment]
Removing from the milestone due to lack of clarity on the issue this is fixing - we can consider in a later release if this can be fully tested by then.

**Comment by dadarya0** [comment]
> @lukassykora @kuzmany I am struggling a bit to reproduce this following the instructions.
> 
> When you say:
> 
> > Set the default font using the Japanese characters
> 
> Do you mean set the language of the email to Japanese?
> 
> In the editor these are the font families I have available - I could not see a font which relates to Japanese characters.
> 
> screenshot-mautic4 ddev site-2021 09 15-12_12_45
> 
> I tried with the language set to Japanese and could not reproduce the bug so would value some guidance!

you can select any 1 of last 2 fonts :-

image

**Review by escopecz — APPROVED** [review]
I wasn't able to reproduce the issue on the 5.x branch. The send result action is also displaying some code that shouldn't be visible:
Screenshot 2024-02-06 at 09 45 35

It shows on both branches, this one and 5.x so it's not a regression of this PR.

Since this PR makes minimal changes to the code and adds 2 good tests, I think we should merge it as it still add value in terms of increased test coverage and doesn't break anything.

**Pull request merged**
