### PR TITLE
TPROD-233 Enable hybrid Twig templates support in Mautic (`MauticCoreBundle:Default:content.html.twig`)

### LINKED ISSUE #10852: Symfony 5 support
Symfony 4 will become unsupported from November 2022, and will no longer receive security fixes after November 2023.

This issue is to track the tasks required to implement support for Symfony 5 prior to the timelines below.

### Timelines:
[Symfony 5](https://symfony.com/releases/5.4)

- Symfony 4 active support ends November 2022
- Symfony 4 security support ends November 2023

[Symfony 6](https://symfony.com/releases/6.0)

- Symfony 5 active support ends November 2024
- Symfony 5 security support ends November 2025

**Points** for discussion:

1. Do we jump straight from 4 -> 6 and be fully 'up to date', or should we go 4 -> 5 -> 6 sequentially?
2. [more to be added]

### PR DESCRIPTION
**Pull request by dennisameling**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 4.x
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | yes
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | WIP
| Issue(s) addressed                     | Relates to #10852 

#### Description:

_First part of the Epic ["The Big PHP to Twig Template Engine migration"](https://mautic.atlassian.net/browse/TPROD-232)_

In Symfony 4, the PHP templating engine [has been officially deprecated](https://symfony.com/doc/4.4/templating/PHP.html), and has been removed in Symfony 5. This PR lays the groundwork for Twig support by introducing `MauticCoreBundle:Default:content.html.twig` which internal bundles and plugin authors can extend in preparation to the Symfony 5 migration 🎉

_Note that this PR should target the 4.x branch, as we'll need to migrate all internal bundles to Twig **before** we can go ahead and remove support for PHP templates (which will take place in the 5.x branch)._ 

The following modules are now available through Twig:
- `MauticCoreBundle:Default:content.html.twig` and all of its dependencies/children (`slim.html.twig, base.html.twig, pageheader.html.twig, navbar.html.twig, script.html.twig, head.html.twig, output.html.twig`)
- GlobalSearch
- Notifications
- Flashes
- Menus
- All Symfony custom form styles translated from PHP to Twig (`mautic_form_layout.twig`)
- `UserBundle:Views:Profile:index.html.twig`, which is the "My Account" page in Mautic

https://user-images.githubusercontent.com/17739158/162592213-337ad966-46b6-4704-a23d-f77835cbbfe8.mp4

#### Steps to test this PR:
1. Open this PR in Gitpod or locally
2. In the top right corner of the screen, click on your user name > "Account"
3. Click around and see if everything looks and works as expected
4. Click "Save". You should see a message saying "Your account has been updated."
5. Navigate to other screens. Everything should still work as expected. While other screens are not rendered through Twig yet, some of the main components _are_ rendered by Twig if the user is first on the "My Account" page.
6. Go to phpMyAdmin (https://mautic.ddev.site:8037/ in DDEV). Go to `db > notifications`. Click "SQL" on top of the screen. Execute the following query to create a new notification (if you're using a database prefix, make sure to add that before the `notifications` table name!)

```SQL
INSERT INTO `notifications` (`id`, `user_id`, `type`, `header`, `message`, `date_added`, `icon_class`, `is_read`) VALUES
(1, 1, NULL, 'Lovely header', 'Hello hello test', '2022-04-08 19:34:51', NULL, 0);
```

7. Go back to Mautic. Refresh the page. In the top left corner of the screen, click the notification bell. You should now see the notification you just created (see below for some example screenshots of notifications).

### Notification bell

Notification with no `iconClass` set (defaults to `fa-star`):

image

Notification with `iconClass` set to `fa-shower`:

image

Notification with `iconClass` set to `img:https://www.mautic.org/sites/default/files/2020-03/Mautic_Logo_LB.png`

image

Notification with header:

image

No notifications:

image

Update available:

image

### Search icon

image

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10129"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
Thank you for making a start on this - and for creating the Jira epic!

**Comment by RCheesley** [comment]
@dennisameling reopening this as it got closed by Stalebot. I believe we are still hoping to go down this route?

**Review by jos0405 — APPROVED** [review]
Works as expected.
fa icons show nicely.
Admin creation notifications shown as well

**Review by RCheesley — APPROVED** [review]
Working great for me, clicked around and did all the usual things I would do with mautic, without any errors.

All notifications appear, and search as well:
Calendar _ Mautic (1)
Contacts _ Mautic (2)

Just needs a code review prior to being RTC.

**Review by escopecz — APPROVED** [review]
I cannot find any issue worth mentioning in these code changes. I clicked trough the UI and it all works fine. I was especially concerned about the YesNoButtons as we had lost the null option earlier and had to revert. But here it works as it should. Great work @dennisameling! 👍

**Pull request merged**
