### PR TITLE
removing the remove gitsubmodules composer script

### PR DESCRIPTION
**Pull request by galvani**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [X]
| Deprecations?                          | [X]
| Issue(s) addressed                     | Fixes #... 

#### Description:

These has been short conversation on slack. the composer script remove-git-submodules is doing stuff behind developer's back. deleting .git folders is brutal and developer should take care to clean up him/her-self.

### CODE REVIEW

**Comment by escopecz** [comment]
@mollux can you please re-state the case for keeping it in the core? I don't think it should be there either as it causes data loss and developing plugins is very inconvenient because of this. We either need documentation how to develop plugins differently or remove it and you'll have to update your workflow to avoid whatever this was needed for.

**Comment by escopecz** [comment]
This is causing more issues for me. It's scanning the node_modules directory and my dev-docker filesystem won't handle it well:
```
$ composer update --lock
Loading composer repositories with package information
Updating dependencies                                 
Lock file operations: 0 installs, 0 updates, 0 removals
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package sensio/framework-extra-bundle is abandoned, you should avoid using it. Use Symfony instead.
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
150 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
phpstan/extension-installer: Extensions installed
> php -r "if(file_exists('./.git')&&file_exists('./build/hooks/pre-commit'.(PHP_OS=='WINNT'?'.win':''))){copy('./build/hooks/pre-commit'.(PHP_OS=='WINNT'?'.win':''),'./.git/hooks/pre-commit');} if(file_exists('./.git')&&file_exists('./build/hooks/post-checkout')){copy('./build/hooks/post-checkout','./.git/hooks/post-checkout');}"
> php -r "if(file_exists('./.git/hooks/pre-commit')&&(PHP_OS!='WINNT')){chmod('./.git/hooks/pre-commit',0755);} if(file_exists('./.git/hooks/post-checkout')&&(PHP_OS!='WINNT')){chmod('./.git/hooks/post-checkout',0755);}"
> find . -mindepth 2 -type d -name .git | xargs rm -rf
find: './node_modules/postcss-merge-longhand/types/lib/decl': Too many open files in system
find: './node_modules/lodash/fp': Too many open files in system
find: './node_modules/codemirror/mode/scheme': Too many open files in system
find: './node_modules/codemirror/mode/toml': No such file or directory
find: './node_modules/codemirror/mode/pig': No such file or directory
find: './node_modules/codemirror/mode/gas': No such file or directory
find: './node_modules/codemirror/mode/go': No such file or directory
find: './node_modules/codemirror/mode/apl': No such file or directory
find: './node_modules/codemirror/mode/textile': No such file or directory
find: './node_modules/codemirror/mode/turtle': No such file or directory
find: './node_modules/codemirror/mode/sparql': No such file or directory
find: './node_modules/codemirror/mode/troff': No such file or directory
find: './node_modules/codemirror/mode/cmake': No such file or directory
find: './node_modules/codemirror/mode/htmlembedded': No such file or directory
find: './node_modules/codemirror/mode/xquery': No such file or directory
find: './node_modules/codemirror/mode/python': No such file or directory
find: './node_modules/codemirror/mode/css': No such file or directory
find: './node_modules/codemirror/mode/clojure': No such file or directory
find: './node_modules/codemirror/mode/spreadsheet': No such file or directory
find: './node_modules/codemirror/mode/asn.1': No such file or directory
find: './node_modules/codemirror/src/measurement': No such file or directory
find: './node_modules/codemirror/src/util': No such file or directory
find: './node_modules/codemirror/src/input': No such file or directory
find: './node_modules/codemirror/src/edit': No such file or directory
find: './node_modules/codemirror/src/line': No such file or directory
find: './node_modules/codemirror/src/model': No such file or directory
find: './node_modules/codemirror/src/addon': No such file or directory
find: './node_modules/codemirror/src/display': No such file or directory
find: './node_modules/make-dir/node_modules': Too many open files in system
find: './node_modules/webpack-sources/lib': Too many open files in system
find: './node_modules/bootstrap/less/mixins': No such file or directory
find: './node_modules/chrome-trace-event/dist': Too many open files in system
find: './node_modules/resolve/test': Too many open files in system
find: './node_modules/chart.js/dist': Too many open files in system
find: './node_modules/fastest-levenshtein/esm': No such file or directory
find: './node_modules/css-declaration-sorter/dist': No such file or directory
find: './node_modules/css-declaration-sorter/orders': No such file or directory
find: './node_modules/css-declaration-sorter/src': No such file or directory
find: './node_modules/acorn/bin': No such file or directory
find: './node_modules/acorn/dist': No such file or directory
find: './node_modules/underscore.string/dist': No such file or directory
find: './node_modules/underscore.string/node_modules': Too many open files in system
find: './node_modules/less/lib/less/environment': Too many open files in system
find: './node_modules/cssnano-preset-default/types': No such file or directory
find: './node_modules/cssnano-preset-default/src': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-indent': Too many open files in system
find: './node_modules/@ckeditor/ckeditor5-easy-image/build': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-easy-image/src': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-image/lang': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-image/theme': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-image/build': Too many open files in system
find: './node_modules/@ckeditor/ckeditor5-editor-classic/theme': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-editor-classic/build': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-editor-classic/src': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-alignment/lang': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-alignment/build': Too many open files in system
find: './node_modules/@ckeditor/ckeditor5-alignment/src': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-font/src/ui': Too many open files in system
find: './node_modules/@ckeditor/ckeditor5-font/src/fontsize': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-font/src/fontcolor': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-font/src/fontbackgroundcolor': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-font/src/fontfamily': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-word-count/build/translations': Too many open files in system
find: './node_modules/@ckeditor/ckeditor5-list/src/listproperties/ui': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-list/src/documentlist/utils': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-paste-from-office/build': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-paste-from-office/src': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-essentials/build': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-essentials/src': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-clipboard/theme': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-clipboard/src': Too many open files in system
find: './node_modules/@ckeditor/ckeditor5-theme-lark/theme/ckeditor5-style': Too many open files in system
find: './node_modules/@ckeditor/ckeditor5-theme-lark/theme/ckeditor5-horizontal-line': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-theme-lark/theme/mixins': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-theme-lark/theme/ckeditor5-special-characters': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-theme-lark/theme/ckeditor5-list': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-theme-lark/theme/ckeditor5-clipboard': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-theme-lark/theme/ckeditor5-link': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-theme-lark/theme/ckeditor5-find-and-replace': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-theme-lark/theme/ckeditor5-media-embed': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-theme-lark/theme/ckeditor5-html-embed': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-theme-lark/theme/ckeditor5-code-block': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-theme-lark/theme/ckeditor5-engine': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-theme-lark/theme/ckeditor5-heading': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-theme-lark/theme/ckeditor5-table': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-ui/theme/components/colorgrid': Too many open files in system
find: './node_modules/@ckeditor/ckeditor5-ui/theme/components/input': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-ui/theme/components/labeledinput': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-ui/theme/components/toolbar': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-ui/theme/components/label': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-ui/theme/components/labeledfield': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-ui/theme/components/responsive-form': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-ui/theme/components/button': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-ui/theme/components/list': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-ui/theme/components/colorpicker': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-ui/theme/components/icon': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-ui/theme/components/colorselector': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-ui/src/editableui/inline': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-ui/src/inputnumber': Too many open files in system
find: './node_modules/@ckeditor/ckeditor5-media-embed/src/ui': Too many open files in system
find: './node_modules/@ckeditor/ckeditor5-typing/src': Too many open files in system
find: './node_modules/@ckeditor/ckeditor5-paragraph/src': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-adapter-ckfinder/build': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-adapter-ckfinder/src': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-cloud-services/build': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-cloud-services/src': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-ckbox/lang': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-ckbox/theme': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-ckbox/build': Too many open files in system
find: './node_modules/@ckeditor/ckeditor5-block-quote/build/translations': Too many open files in system
find: './node_modules/@ckeditor/ckeditor5-core/src/editor': Too many open files in system
find: './node_modules/@ckeditor/ckeditor5-engine/src/view/observer': Too many open files in system
find: './node_modules/@ckeditor/ckeditor5-upload/lang': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-upload/src': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-source-editing/lang': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-source-editing/theme': No such file or directory
find: './node_modules/@ckeditor/ckeditor5-source-editing/build': Too many open files in system
find: './node_modules/@ckeditor/ckeditor5-source-editing/src': No such file or directory
find: './node_modules/mini-css-extract-plugin/node_modules/ajv/dist/compile/validate': Too many open files in system
find: './node_modules/mini-css-extract-plugin/node_modules/ajv/dist/compile/codegen': No such file or directory
find: './node_modules/mini-css-extract-plugin/node_modules/ajv/dist/compile/jtd': No such file or directory
find: './vendor/friendsofphp/php-cs-fixer/src/RuleSet/Sets': No such file or directory
find: './vendor/friendsofphp/php-cs-fixer/src/Tokenizer/Transformer': No such file or directory
find: './vendor/friendsofphp/php-cs-fixer/src/Tokenizer/Analyzer': No such file or directory
find: './vendor/friendsofphp/php-cs-fixer/src/Doctrine': Too many open files in system
find: './vendor/rector/rector/rules/CodeQuality/Rector/Switch_': Too many open files in system
find: './vendor/aws/aws-sdk-php/src/data/codebuild/2016-10-06': Too many open files in system
find: './vendor/bjeavons/zxcvbn-php/src/Math': No such file or directory
find: './vendor/bjeavons/zxcvbn-php/src/Matchers': No such file or directory
find: './vendor/liip/test-fixtures-bundle/.github': No such file or directory
find: './vendor/liip/test-fixtures-bundle/doc': No such file or directory
find: './vendor/liip/test-fixtures-bundle/src': No such file or directory
find: './vendor/liip/functional-test-bundle/doc': No such file or directory
find: './vendor/liip/functional-test-bundle/src': No such file or directory
find: './vendor/wikimedia/less.php/lib': No such file or directory
find: './vendor/matomo/device-detector/Cache': No such file or directory
find: './vendor/matomo/device-detector/Parser': No such file or directory
find: './vendor/matomo/device-detector/regexes': No such file or directory
find: './vendor/matomo/device-detector/Yaml': No such file or directory
find: './vendor/twilio/sdk/src': No such file or directory
find: './media/js/ckeditor4/plugins/exportpdf/icons/hidpi': No such file or directory
find: './media/js/ckeditor4/plugins/print/lang': Too many open files in system
find: './media/js/ckeditor4/plugins/print/icons': No such file or directory
> npm ci --prefer-offline --no-audit
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs

> mautic@0.0.0 postinstall
> node_modules/modernizr/bin/modernizr -c modernizr-config.json -d node_modules/modernizr/modernizr-mautic-dist.js & npm run build


> mautic@0.0.0 build
> webpack --mode production  --config webpack.config.js

Modernizr build saved to node_modules/modernizr/modernizr-mautic-dist.js
[webpack-cli] Failed to load '/var/www/html/webpack.config.js' config
[webpack-cli] Error: ENFILE: file table overflow, open '/var/www/html/node_modules/csso/lib/replace/atrule/keyframes.js'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at Module._extensions..js (node:internal/modules/cjs/loader:1377:18)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/var/www/html/node_modules/csso/lib/replace/Atrule.js:2:25)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10) {
  errno: -23,
  syscall: 'open',
  code: 'ENFILE',
  path: '/var/www/html/node_modules/csso/lib/replace/atrule/keyframes.js'
}
npm ERR! code 2
npm ERR! path /var/www/html
npm ERR! command failed
npm ERR! command sh -c node_modules/modernizr/bin/modernizr -c modernizr-config.json -d node_modules/modernizr/modernizr-mautic-dist.js & npm run build

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/.npm/_logs/2024-01-17T08_40_12_137Z-debug-0.log
Script npm ci --prefer-offline --no-audit handling the npm-ci event returned with error code 2
Script @npm-ci was called via post-update-cmd
```
@mollux I'll merge this PR if there won't be any objections.

**Review by kuzmany — DISMISSED** [review]
Let's merge it please, it's annoying for developers to remove submodules

**Comment by escopecz** [comment]
@galvani could you please fix the conflict?

**Review by mollux — APPROVED** [review]
ok, lgtm

**Review by escopecz — APPROVED** [review]

**Pull request merged**
