### PR TITLE
Add stage name and stage date added to contacts report

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR added stage name and stage date_added to contacts reports.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create contacts with various stages
3. Create report with columns of stages

image

4. Check if show properly

### CODE REVIEW

**Review by johbuch — DISMISSED** [review]
Tested on mautibox, it works
thanks zdeno

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebased

**Comment by RCheesley** [comment]
Bumping to 3.2 as this needs to be rebased to run checks and has no tests on 3.x

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by mohit-rocks** [comment]
I tested this PR on local and I am able to see the "Stage name" and "Stage date added" filters.
Here are the screenshots for reference:

**Report configuration form:**
Edit_Report_-_Contacts___Mautic


**Report view:**
View_Report_-_Contacts___Mautic

**Review by mohit-rocks — APPROVED** [review]
I did manual testing of the issue local and seems to be working as expected.
I've attached screenshots in the following comment.
https://github.com/mautic/mautic/pull/8173#issuecomment-841636625

**Review by RCheesley — APPROVED** [review]
Had to test in prod mode as was bumping up against #9762 but the reports work well, and it's a useful addition!

screenshot-mautic4 ddev site-2021 05 15-12_39_35

Thanks @kuzmany ! LGTM 🚀

**Pull request merged**
