### PR TITLE
[UX] Differentiate types of emails

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR adds the differences between email types.
Based on:
https://docs.mautic.org/en/5.x/channels/emails.html
https://joeykeller.com/knowledge-base-2/mautic-onboarding/create-your-first-segment-or-template-email-with-mautic/

image

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Channels > Emails
3. Create new
4. See the comparison

### CODE REVIEW

**Comment by andersonjeccel** [comment]
This PR is based on the form types branch
Most of file changes will disappear when ux-types-of-form get merged

**Review by shinde-rahul — APPROVED** [review]
Code changes looks good. Have not tried on setup.

**Review by kuzmany — DISMISSED** [review]
These icons, little bit give me moment, are clickable like a checkbox. But in general, it's a good improvement.

**Comment by andersonjeccel** [comment]
> These icons, little bit give me moment, are clickable like a checkbox. But in general, it's a good improvement.

I'm trying to implement a standard (like here #13689) where clickable things get a border, and read-only elements wouldn't have

Perhaps everyone will find it strange for the first time, but soon gets natural and intuitive 😉👌

**Comment by alexhammerschmied** [comment]
I think this one is very good. Except the list icons shouldn't have a background.

**Comment by andersonjeccel** [comment]
Hey @alexhammerschmied, I’m happy you liked it

Regarding the background, it’s a common design pattern. What are your thoughts on this?

I’m following examples like these, have a look:

https://dribbble.com/shots/18272692-Scale-Pricing-Page
https://dribbble.com/shots/18147607-Pricing-page-Untitled-UI

**Comment by andersonjeccel** [comment]
@RCheesley @escopecz Conflicts fixed, seems ready to commit

**Review by escopecz — APPROVED** [review]
No issues in the code 👍

**Pull request merged**
