### PR TITLE
Map implemented to the lead profile

### PR DESCRIPTION
**Pull request by escopecz**
(closes https://github.com/mautic/mautic/issues/1435) This PR will add a new tab called **Places** to the lead profile if some of the lead's IP address detail have the latitude and longitude info like this:
mautic-lead-profile-map

The tab won't show up for the leads who doesn't have such information. 

### Testing 
1. Apply this PR.
2. Look at random lead details and check if the map is there.

If you don't have any IP lookup data in the ip_addresses, ip_details column, you can use this one:
```
a:8:{s:4:"city";s:9:"Brasília";s:6:"region";s:16:"Distrito Federal";s:7:"country";s:6:"Brazil";s:8:"latitude";d:-15.783300000000001;s:9:"longitude";d:-47.916699999999999;s:3:"isp";s:22:"Global Village Telecom";s:12:"organization";s:0:"";s:8:"timezone";s:17:"America/Sao_Paulo";}
```

### CODE REVIEW

**Comment by OlafDammann** [comment]
Hi John
I'd like to test, is there a simple way to get the files into the system? 
Olaf

**Comment by escopecz** [comment]
@OlafDammann I'm not sure you'd call it easy, but there is a way:

https://github.com/mautic/mautic#how-to-test-a-pull-request

Thanks!

**Comment by alanhartless** [comment]
Looks good. 👍

**Comment by mqueme** [comment]
works for me!

**Pull request merged**
