### PR TITLE
[UI] Minor improvement for xAxis of line charts

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR makes charts have only initial and final values, as discussed [on Slack](https://mautic.slack.com/archives/C024XBCQS3Z/p1716378761748589).

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open the dashboard and look at the charts

image

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
Looks good to me 👍 
Before:
Screenshot 2024-05-27 at 09 27 45

After:
Screenshot 2024-05-27 at 09 27 08

I can see that there is some issue with the integral background calculation but it's there on 5.x already so it's not a blocker of this PR.

**Comment by andersonjeccel** [comment]
To be honest, I've never seen this bug before
Everything has always worked just fine here

---

Do we need 2 tests? I'm trying to understand what this pending-test-confirmation label means

**Comment by escopecz** [comment]
Yes, we need a second approval

**Review by kuzmany — APPROVED** [review]
Seems good to me 👍

**Pull request merged**
