### PR TITLE
Assign category to the entity via API

### PR DESCRIPTION
**Pull request by escopecz**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | https://github.com/mautic/api-library/pull/165
| Related user documentation PR URL | /
| Related developer documentation PR URL | https://github.com/mautic/developer-documentation/pull/106
| Issues addressed (#s or URLs) | /
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Mautic API has endpoint to manage a categories, but I couldn't find any way how to assign a category to an entity.

This PR adds this possibility by simply defining `category => [ID]` to the entity that is being created or updated.

#### Steps to test this PR:
Before you checkout this PR:
1. Try to create for example asset by `POST http://mautic.test/index_dev.php/api/assets/new` with body of `title=Mautic+1.2.3&storageLocation=remote&file=https%3A%2F%2Ffile.url&category=195`. Replace 195 with a category ID that exists on your Mautic instance.
2. You'll get an error message that "category" has wrong value.
3. Checkout this PR
4. Try the same thing. The asset is created and the category associated with it.
5. Try to create an asset with non-existent category ID. You'll get an error that such category does not exist.

### CODE REVIEW

**Comment by mleffler** [comment]
This has been code reviewed and has had one test pass.

**Comment by mburamorde** [comment]
I'am not able to assign an category liked described here:
https://developer.mautic.org/?php#assign-a-category

My Version is v2.14.2

**Comment by escopecz** [comment]
@mburamorde I wrote tests for it in the API Library and they are passing for 2.14.2: https://github.com/mautic/api-library/pull/165/files

Could you double-check that you are using it correctly? Can you provide a code sample? Do you get any errors?

**Comment by mburamorde** [comment]
Below the "Rest" Patch Call ... I simple set the "category" as parameter.

**Comment by escopecz** [comment]
It's working when I try it:

screen shot 2018-11-06 at 09 10 21


Wait, now I noticed what entity you want to add to the category. Contacts cannot be added to a category. They can be added to a segment or a company.

**Comment by mburamorde** [comment]
No, thats not correct. The Table is lead_categories.

And below the GUI:

**Comment by escopecz** [comment]
I didn't know that existed. I have no time to test it now. Create an issue.

**Comment by mburamorde** [comment]
#6833

**Pull request merged**
