### PR TITLE
Fixing a typo in a controller action path

### LINKED ISSUE #13201: Error 500 upon Theme Deletion
### Mautic Version

5.0.x series

### PHP version

8.0.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

When inserting a theme of any type - email, landing page or form - in Mautic, and if we later want to delete it, an error 500 is displayed, but the theme still gets deleted. This issue occurs whether performed in bulk or individually.

**Note:** This bug has been present since version 5 beta, so it may be a duplicate issue. I do believe this bug has been reported previously but could not find it.

### How can we reproduce this issue?

**Tested on 5.0.1**

Step 1: Go to Settings > Theme
Step 2: Install a theme
Step 3: After installing it, it will be displayed on the theme list. You can either delete it individually or in bulk by checking the checkbox next to the name. Both ways will result in the same error.

image

Step 4: When clicking on delete, it will display an error 500, along with a message indicating that it was deleted successfully.

image

### Relevant log output

```shell
[2024-01-11 11:47:58] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/s/themes/batchDelete" is not callable: Controller "Mautic\CoreBundle\Controller\themeController" has required constructor arguments and does not exist in the container. Did you forget to define the controller as a service?" at /var/www/html/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 88 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/s/themes/batchDelete\" is not callable: Controller \"Mautic\\CoreBundle\\Controller\\themeController\" has required constructor arguments and does not exist in the container. Did you forget to define the controller as a service? at /var/www/html/vendor/symfony/http-kernel/Controller/ControllerResolver.php:88, InvalidArgumentException(code: 0): Controller \"Mautic\\CoreBundle\\Controller\\themeController\" has required constructor arguments and does not exist in the container. Did you forget to define the controller as a service? at /var/www/html/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php:64, ArgumentCountError(code: 0): Too few arguments to function Mautic\\CoreBundle\\Controller\\FormController::__construct(), 0 passed in /var/www/html/vendor/symfony/http-kernel/Controller/ControllerResolver.php on line 147 and exactly 12 expected at /var/www/html/app/bundles/CoreBundle/Controller/FormController.php:145)"} {"hostname":"399e2f408fe9","pid":1051}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [y]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/issues/13201

#### Description:

Deleting a theme results in a 500 error. This PR fixes it.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Follow steps in https://github.com/mautic/mautic/issues/13201

### CODE REVIEW

**Comment by code5rick** [comment]
@escopecz working perfectly! Thanks for the fast resolution of the problem, you rock👌

**Review by mollux — APPROVED** [review]
change and test make sense.

**Comment by mollux** [comment]
@escopecz can you change and rebase this against 5.0?

**Comment by mollux** [comment]
@escopecz still requires a rebase too

**Comment by escopecz** [comment]
I changed the branch in a mobile app. I was pretty sure I learned from my mistakes and based this on 5.0 but clearly, I'm still stuck in the old ways. Thanks for keeping an eye on me!

**Pull request merged**
