### PR TITLE
Dynamic Content replace slot with HTML

### PR DESCRIPTION
**Pull request by ChrisRAoW**
When a slot is replaced on a landingpages it uses the appendXML function. Like the name suggests it requires (valid) XML. HTML certainly related to XML, but has some differences. For example, if an `&` is used the XML will get stressed.

Now I had 2 cases where the replacement of the slot throwed an error:
- In the dynamic content there was een URL. The URL got replaced my mautic to enable tracking. But the mautic url (the token) contained an "&". Result: parser error
- In my template I used an `&nbsp;`. This is a typical html code. It made the XML parser fail.

Just by wrapping the new slot content into `<![CDATA[ **CONTENT**  ]]>` fixes this issue. It even supports invalid HTML.

### CODE REVIEW

**Comment by kuzmany** [comment]
@ChrisRAoW  good catch. Please can you resolve conflicting files?

**Comment by Woeler** [comment]
How to properly test this?

**Comment by ChrisRAoW** [comment]
@Woeler In current version of mautic you can't use for example &nbsp; in the dynamic content. The & is not a valid XML character. This PR is fixing that.

**Comment by Woeler** [comment]
One confirmed test on the issue.

**Pull request merged**
