### PR TITLE
Select with Mautic tokens for GrapesJS text editor

### PR DESCRIPTION
**Pull request by annamunk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | No
| New feature/enhancement? (use the a.x branch)      | Yes
| Deprecations?                          | No
| BC breaks? (use the c.x branch)        | No
| Automated tests included?              | [ ]
| Related user documentation PR URL      | []
| Related developer documentation PR URL | []
| Issue(s) addressed                     | Connected with #10966 #11344 

#### Description:

GrapesJS builder didn't have option to insert Mautic tokens ([https://docs.mautic.org/en/setup/variables](https://docs.mautic.org/en/setup/variables)) in the body of an email with help of a drop-down list with hints, just like in the old builder. 
token_prev_4

I added a dropdown with tokens as a CKEditor plugin loaded only in the GrapesJS builder. I didn't implement the option to display hints after typing {. In the drop-down variables are divided into few groups: Assets, Contact fields, Company fields, DWC, Page links, Custom tokens and are inserted into the text in the same way as in the old builder.
token_prev_1

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Enable the GrapesJS plugin.
3. Create a new e-mail or open an existing e-mail for editing.
4. Double-click any E-Mail text to display the editor toolbar.
5. The editor toolbar should contain the "Token" drop-down list. Click an option from the list to insert it into the text.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11525"></a>

### CODE REVIEW

**Review by jos0405 — DISMISSED** [review]
Works as described:
image

Results in:
image

**Review by volha-pivavarchyk — DISMISSED** [review]
Works well as described.

**Review by escopecz — DISMISSED** [review]
The code looks great 👍

**Comment by escopecz** [comment]
@annamunk can you please resolve the conflict so this can be merged?

**Comment by kuzmany** [comment]
On landing page builder I see form tokens under the custom tokens section. Expect forms section

image

**Comment by RCheesley** [comment]
@annamunk we need the conflict to be resolved before we can merge this - could you take a look please? Also the feedback from @kuzmany about the forms tokens under the custom tokens section.

**Comment by annamunk** [comment]
> On landing page builder I see form tokens under the custom tokens section. Expect forms section
> 
> image

@kuzmany I moved the forms to separate group. Please check page builder again.

token_form

**Comment by annamunk** [comment]
@RCheesley I resolved conflict and made a change for form tokens. If any improvements are needed, please let me know.

**Comment by RCheesley** [comment]
@kuzmany would be great if you can check that this meets expectations now? Thanks!

**Review by kuzmany — APPROVED** [review]
Perfect 👍

**Pull request merged**
