### PR TITLE
TPROD-272: Dropped PluginConfiguration.php

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:
Fix  https://mautic.atlassian.net/browse/TPROD-272
Blocked for Symfony 5. Seems like we do not use it anywhere

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Check If installation works like before and plugins reload works too

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11032"></a>

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
Looks good. I cannot find it used anywhere 👍

**Comment by RCheesley** [comment]
Looks like some conflicts to be resolved, but may want to wait for the 4.x->4.x merge to be completed before we address them.

**Comment by RCheesley** [comment]
@kuzmany could you please resolve the conflicts in this PR? Thanks!

**Comment by escopecz** [comment]
I was not able to rebase, merge nor cherry-pick the last commit without resolving thousands of errors, so I created a new one with the same content.

Ready for second test/review.

**Review by mollux — APPROVED** [review]
tested, looks good and indeed nowhere used

**Pull request merged**
