### PR TITLE
Report export with aggregated AVG columns are converted to integers

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ Y ]
| New feature/enhancement? (use the a.x branch)      | [ N ]
| Deprecations?                          | [ N ]
| BC breaks? (use the c.x branch)        | [ N ]
| Automated tests included?              | [ Y ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Report export to CSV, XLS and HTML with aggregated AVG columns is not correct, AVG values are converted to integers. This PR fixes this issue.

#### Steps to replicate this issue:

1. Create test contacts with points and assign them to countries (in next step we will calculate average country contact points)
2. Create report with **Contact** datasource with following settings:
obraz
3. Save report & close. Report should look like this:
obraz
4. Try different export types, result should look like this:
obraz
Note the AVG Points value is rounded to integer. It's the same for CSV, XLS and HTML export.

#### Steps to test this PR:
1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Repeat steps 1-3 from steps to replicate
3. Export result should be correct:
obraz

### CODE REVIEW

**Comment by jos0405** [comment]
Not sure if it's connected, but I got this error:
/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:98 at
/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:182 at Doctrine\DBAL\Driver\AbstractMySQLDriver -> convertException ( 'An exception occurred while executing 'SELECT count(*) FROM (SELECT `l`.`firstname` AS firstname, `l`.`lastname` AS lastname, `l`.`sum1` AS sum1, `l`.`sum2` AS sum2, `l`.`city` AS city, SUM() AS 'SUM ', SUM(l.sum1) AS 'SUM l.sum1' FROM leads l WHERE l.date_added IS NULL OR (l.date_added BETWEEN ? AND ?) GROUP BY l.city) c' with params ["2022-08-30 00:00:00", "2022-09-30 15:38:04"]: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AS 'SUM ', SUM(l.sum1) AS 'SUM l.sum1' FROM leads l WHERE l.date_added IS N...' at line 1', object(Exception) )
/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:159 at Doctrine\DBAL\DBALException :: wrapException ( object(Driver), object(Exception), 'An exception occurred while executing 'SELECT count(*) FROM (SELECT `l`.`firstname` AS firstname, `l`.`lastname` AS lastname, `l`.`sum1` AS sum1, `l`.`sum2` AS sum2, `l`.`city` AS city, SUM() AS 'SUM ', SUM(l.sum1) AS 'SUM l.sum1' FROM leads l WHERE l.date_added IS NULL OR (l.date_added BETWEEN ? AND ?) GROUP BY l.city) c' with params ["2022-08-30 00:00:00", "2022-09-30 15:38:04"]: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AS 'SUM ', SUM(l.sum1) AS 'SUM l.sum1' FROM leads l WHERE l.date_added IS N...' at line 1' )
/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:2226 at Doctrine\DBAL\DBALException :: driverExceptionDuringQuery ( object(Driver), object(Exception), 'SELECT count(*) FROM (SELECT `l`.`firstname` AS firstname, `l`.`lastname` AS lastname, `l`.`sum1` AS sum1, `l`.`sum2` AS sum2, `l`.`city` AS city, SUM() AS 'SUM ', SUM(l.sum1) AS 'SUM l.sum1' FROM leads l WHERE l.date_added IS NULL OR (l.date_added BETWEEN ? AND ?) GROUP BY l.city) c', array('2022-08-30 00:00:00', '2022-09-30 15:38:04') )
/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1313 at Doctrine\DBAL\Connection -> handleExceptionDuringQuery ( object(Exception), 'SELECT count(*) FROM (SELECT `l`.`firstname` AS firstname, `l`.`lastname` AS lastname, `l`.`sum1` AS sum1, `l`.`sum2` AS sum2, `l`.`city` AS city, SUM() AS 'SUM ', SUM(l.sum1) AS 'SUM l.sum1' FROM leads l WHERE l.date_added IS NULL OR (l.date_added BETWEEN ? AND ?) GROUP BY l.city) c', array('2022-08-30 00:00:00', '2022-09-30 15:38:04'), array('2', '2') )
/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:212 at Doctrine\DBAL\Connection -> executeQuery ( 'SELECT count(*) FROM (SELECT `l`.`firstname` AS firstname, `l`.`lastname` AS lastname, `l`.`sum1` AS sum1, `l`.`sum2` AS sum2, `l`.`city` AS city, SUM() AS 'SUM ', SUM(l.sum1) AS 'SUM l.sum1' FROM leads l WHERE l.date_added IS NULL OR (l.date_added BETWEEN ? AND ?) GROUP BY l.city) c', array('2022-08-30 00:00:00', '2022-09-30 15:38:04'), array('2', '2') )
/app/bundles/ReportBundle/Model/ReportModel.php:750 at Doctrine\DBAL\Query\QueryBuilder -> execute ( )
/app/bundles/ReportBundle/Model/ReportModel.php:629 at Mautic\ReportBundle\Model\ReportModel -> getTotalCount ( object(QueryBuilder), array('count_query' => 'SELECT count(*) FROM (SELECT `l`.`firstname` AS firstname, `l`.`lastname` AS lastname, `l`.`sum1` AS sum1, `l`.`sum2` AS sum2, `l`.`city` AS city, SUM() AS 'SUM ', SUM(l.sum1) AS 'SUM l.sum1' FROM leads l WHERE l.date_added IS NULL OR (l.date_added BETWEEN :dateFrom AND :dateTo) GROUP BY l.city) c') )
/app/bundles/ReportBundle/Controller/ReportController.php:652 at Mautic\ReportBundle\Model\ReportModel -> getReportData ( object(Report), object(FormFactory), array('dynamicFilters' => array(), 'paginate' => true, 'reportPage' => '1', 'dateFrom' => object(DateTime), 'dateTo' => object(DateTime), 'translator' => object(Translator), 'chartQuery' => object(ChartQuery)) )
/vendor/symfony/http-kernel/HttpKernel.php:159 at Mautic\ReportBundle\Controller\ReportController -> viewAction ( '6', '1' )
/vendor/symfony/http-kernel/HttpKernel.php:81 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '2' )
/vendor/symfony/framework-bundle/Controller/ControllerTrait.php:96 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '2' )
/app/bundles/CoreBundle/Controller/CommonController.php:359 at Symfony\Bundle\FrameworkBundle\Controller\AbstractController -> forward ( 'Mautic\ReportBundle\Controller\ReportController::viewAction', array('objectId' => '6', '_controller' => 'Mautic\ReportBundle\Controller\ReportController::viewAction'), array('ignoreAjax' => true, 'request' => object(Request), 'subrequest' => true) )
/app/bundles/CoreBundle/Controller/CommonController.php:289 at Mautic\CoreBundle\Controller\CommonController -> ajaxAction ( array('returnUrl' => '/index_dev.php/s/reports/view/6', 'viewParameters' => array('objectId' => '6'), 'contentTemplate' => 'Mautic\ReportBundle\Controller\ReportController::viewAction', 'passthroughVars' => array('activeLink' => 'mautic_report_index', 'mauticContent' => 'report'), 'forwardController' => true) )
/app/bundles/ReportBundle/Controller/ReportController.php:398 at Mautic\CoreBundle\Controller\CommonController -> postActionRedirect ( array('returnUrl' => '/index_dev.php/s/reports/view/6', 'viewParameters' => array('objectId' => '6'), 'contentTemplate' => 'Mautic\ReportBundle\Controller\ReportController::viewAction', 'passthroughVars' => array('activeLink' => 'mautic_report_index', 'mauticContent' => 'report'), 'forwardController' => true) )
/app/bundles/CoreBundle/Controller/CommonController.php:447 at Mautic\ReportBundle\Controller\ReportController -> editAction ( '6', '' )
/vendor/symfony/http-kernel/HttpKernel.php:159 at Mautic\CoreBundle\Controller\CommonController -> executeAction ( 'edit', '6', '0', '' )
/vendor/symfony/http-kernel/HttpKernel.php:81 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '1' )
/vendor/symfony/http-kernel/Kernel.php:201 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '1', true )
/app/AppKernel.php:104 at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), '1', true )
/app/middlewares/CORSMiddleware.php:82 at AppKernel -> handle ( object(Request), '1', true )
/app/middlewares/CatchExceptionMiddleware.php:34 at Mautic\Middleware\CORSMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/Dev/IpRestrictMiddleware.php:52 at Mautic\Middleware\CatchExceptionMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/VersionCheckMiddleware.php:58 at Mautic\Middleware\Dev\IpRestrictMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/TrustMiddleware.php:42 at Mautic\Middleware\VersionCheckMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23 at Mautic\Middleware\TrustMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/run/src/Stack/run.php:13 at Stack\StackedHttpKernel -> handle ( object(Request) )
/index_dev.php:25 at Stack\run ( object(StackedHttpKernel) )
Previous Exceptions
[SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AS 'SUM ', SUM(l.sum1) AS 'SUM l.sum1' FROM leads l WHERE l.date_added IS N...' at line 1](https://8080-patrykgruszka-mautic-6rqs1vh6hps.ws-eu67.gitpod.io/index_dev.php/s/reports/view/6#previous_body_0)
[SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AS 'SUM ', SUM(l.sum1) AS 'SUM l.sum1' FROM leads l WHERE l.date_added IS N...' at line 1](https://8080-patrykgruszka-mautic-6rqs1vh6hps.ws-eu67.gitpod.io/index_dev.php/s/reports/view/6#previous_body_1)

**Comment by jos0405** [comment]
image

**Comment by jos0405** [comment]
sum1 and sum2 are number custom fields

**Comment by patrykgruszka** [comment]
@jos0405 probably it's not related, check #11311, could you try workaround from this issue and see if it works for you?

**Review by escopecz — APPROVED** [review]
The code looks great 👍

**Review by volha-pivavarchyk — APPROVED** [review]
Works well
image

**Pull request merged**
