### PR TITLE
Fixes issue when merging leads that resulted from recent api changes

### LINKED ISSUE #272: Problems with existing Leads
Hello,

I have a existing lead and when I enter this eMail adress into another form, I get:
Catchable fatal error: Argument 1 passed to Mautic\LeadBundle\Model\ListModel::regenerateListLeads() must be an instance of Mautic\LeadBundle\Entity\LeadList, array given, called in /www/htdocs/rsieber/mautic/app/bundles/LeadBundle/Model/LeadModel.php on line 557 and defined in /www/htdocs/rsieber/mautic/app/bundles/LeadBundle/Model/ListModel.php on line 121

With new mail addresses it's working fine.

Robert

### PR DESCRIPTION
**Pull request by alanhartless**
This should fix #272.

To test, create a form, map a create/update lead action, and submit with an email from an existing lead.  Also test the /leads/{id}/lists api endpoint.  Both should be successful without hitting the error in #272.

### CODE REVIEW

**Comment by escopecz** [comment]
I was not able to recreate this issue. My steps are:
1. Use a form with Create/Update action
2. Open the form and fill in the same email which some existing lead has

I don't get any error on submit and the lead information is merged. What can I do to recreate the error?

**Comment by alanhartless** [comment]
@escopecz Make sure the lead you are using is also associated with at least one lead list.

**Comment by alanhartless** [comment]
Sorry; missed adding that to the PR test description.

**Comment by escopecz** [comment]
I'm able to see the error now. For endpoint leads/{id}/lists I get error "Sorry! The requested URL was not found.".

After applying this patch and clearing the cache, I can submit the form without error and the lead info is merged. The API endpoint also returns right information. :+1:

**Comment by drmmr763** [comment]
+ testing merge worked properly. First time I submitted it ended on a 500 error. Second time I didn't get any error. 

+ testing Api endpoint worked properly.

+ vote 1

**Pull request merged**
