### PR TITLE
Bugfix widget dropshadow

### PR DESCRIPTION
**Pull request by dongilbert**
Please answer the following questions:

| Q             | A
| ------------- | ---
| Bug fix?      | Y
| New feature?  | N
| BC breaks?    | N
| Deprecations? | N
| Fixed issues  |  N/A

## Description

This PR simply removes the dropshadow from dashboard widgets on hover per @dbhurley's request.

### CODE REVIEW

**Comment by alanhartless** [comment]
It no longer gives a more bold shadow on hover but removes it altogether. Is that the goal? There's a slight shadow by default.

**Comment by dbhurley** [comment]
Yes, goal is no bolder shadow on hover. Possibly no shadow at all, I need to test.

**Comment by alanhartless** [comment]
Right now it goes from slight shadow to no shadow at all on hover.

**Comment by dbhurley** [comment]
There's other stuff in the PR, and should this be committed to a LESS file?

**Comment by dbhurley** [comment]
Answered my question. (No). This looks good to me. +1

**Comment by alanhartless** [comment]
Looks good. Shadows are removed and no hover effect 👍

**Pull request merged**
