### PR TITLE
Marketplace v1

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features"
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | https://github.com/mautic/mautic-documentation/pull/185
| Related developer documentation PR URL | https://github.com/mautic/developer-documentation/pull/196
| Issue(s) addressed                     | /

#### Description:

The code for this read-only version of the Mautic Marketplace is mostly taken from my previous PR at https://github.com/mautic/mautic/pull/8257. I moved the MauticMarketplaceBundle to the core bundles instead of a plugin and removed my experimentation with Composer installations.

The reason this is read-only first is that we are waiting for Mautic 4 directory structure and Composer 2 to make the installations possible.

##### The list view
The data are directly loaded from Packagist.org API. They do not allow to order by specific values. It would be nice to order by some though. The search box works.
Screen Shot 2021-02-06 at 20 30 40

##### The detail view
This is the view I'd like some help from a UI/UX person.
Screen Shot 2021-02-06 at 20 31 08

##### Permissions
Only the view and create (=install) permissions are implemented. The create permissions only show/hide the install button for now. This button does not work anyway and just shows a modal that the one click install is coming soon. But the permissions are prepared there. The edit permission can be used once the user will be able to configure which stability (stable, beta, dev, ...) or certain version they want installed for each plugin. And the delete permission is reserved for deleting a plugin installed via the marketplace..
Screen Shot 2021-02-06 at 20 31 31

##### Feature flag to enable/disable the marketplace
You can disable the Mautic Marketplace from the app/config/local.php file. It is enabled by default. This is useful for Mautic providers who cannot enable the Marketplace due to security concerns.

Paste `'marketplace_enabled' => false,` to the local.php file to disable it. It will hide:
- The menu item
- The permission settings
- The marketplace routs will return 404 if accessed directly via URL

#### ToDo
- [x] Permissions
- [x] Feature flag
- [x] Functional test of the `mautic:marketplace:list` command
- [x] Functional test of the list page
- [x] Functional test of the detail page
- [x] User docs (note: it's read-only for now!)
- [x] Dev docs (how to create plugins and make them visible in the Marketplace)

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Go to the Marketplace (see the attached user docs) and click around. There should be no error and all the info presented should make sense.
3. The marketplace is read-only now. The only functionality other than viewing the info is the search on the list view.
4. There are many links to another websites in the UI. Click on them randomly and make sure it leads you to the place you'd expect.
5. If you test on local, test also the CLI command.

### CODE REVIEW

**Comment by escopecz** [comment]
The failing test is an issue in a PHPUNIT abstract class somewhere. It's passing on local but in CI it does not find any command output. @fedys did you push a fix for this to the community already?

**Review by RCheesley — DISMISSED** [review]
This is a really great start - thanks for all the work you have put into this @escopecz !

Tested the list layout and individual listing, plus responsive layout - all working as expected including the search filter!

screenshot-mautic4 ddev site-2021 03 28-11_37_47
screenshot-mautic4 ddev site-2021 03 28-11_36_33
screenshot-mautic4 ddev site-2021 03 28-11_36_17

**Review by dennisameling — DISMISSED** [review]
This is fantastic @escopecz, thanks so much for working on this! Very exciting 🚀 Both the UI and the code are looking great. Also: PHP 7.4 typed properties and arrow functions 😍 Interesting to see what you did with the static `fromArray()` methods!

Some minor nits for a future iteration:

- HTML title says `<sup>` in it, we should probably strip it out somehow

image

- `The reason for this beta release is to give you a teste` --> `teste` should be `taste`

**Comment by fedys** [comment]
> The failing test is an issue in a PHPUNIT abstract class somewhere. It's passing on local but in CI it does not find any command output. @fedys did you push a fix for this to the community already?

@escopecz No, I haven't. I will do so 😉

**Comment by fedys** [comment]
@escopecz I created a PR https://github.com/mautic/mautic/pull/9853 that restores the shell verbosity.

**Comment by escopecz** [comment]
@dennisameling @RCheesley I made some more changes to make the CI happy. But CodeCov is still complaining. I don't understand why. All the classes has greater coverage than Mautic's average. Any ideas?

**Comment by dennisameling** [comment]
It's saying that the coverage of the DateHelper has decreased slightly, which as far as I can see is not something you're touching in this PR: https://app.codecov.io/gh/mautic/mautic/compare/9650/changes

All your code is covered perfectly:

image

@RCheesley this PR is good to go

**Review by dennisameling — DISMISSED** [review]

**Comment by RCheesley** [comment]
Usually it means that a rebase is needed and that is why it is moaning about the code coverage but we should be good to go based on the feedback I believe.

**Review by dennisameling — APPROVED** [review]

**Pull request merged**
