### PR TITLE
Highlighter email theme

### PR DESCRIPTION
**Pull request by chriscalabro**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | N
| Automated tests included? | n/a
| Related user documentation PR URL | n/a
| Related developer documentation PR URL | n/a
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

Adds a new theme (email only) for basic newsletters.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. 
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by GaberNeighbor** [comment]
@chriscalabro just ran tests on this bad boy, it looks great in all email clients/browsers/devices that we care about (awesome).
We'll be including 4 new email templates internally with this release, and this fits very nicely with them! There are a couple changes that would bring it even more in line with our new out-of-the-box email template style, would you mind making these?
- Bring the header to the same width as the contained sections beneath it 
- Use this file as the logo placeholder: logo_white
(it's a white transparent logo, but you should be able to open/download it from here.)

Other than that, this is great man!

**Comment by escopecz** [comment]
The email is great, it looks great on my mobile too. The only issue I found was unstyled unsubscirbe page if the preference center is turned off in the global configuration:

screen shot 2017-11-03 at 17 07 00

@chriscalabro do you think you'll be able to style it?

**Comment by chriscalabro** [comment]
Hey @GaberNeighbor - thanks for the feedback. I'll swap in the logo you've provided.

The header is actually the same width as the rest of the email, but has background color on the section, making it appear full-width. Is that what you want changed - having the background color only as wide as the email content?

And sure @escopecz, I can give the unsubscribe page a little style. Thanks for your help :)

**Comment by GaberNeighbor** [comment]
@chriscalabro thanks man, and yes all I meant was keep the width of the background color the same width as the email.

**Comment by chriscalabro** [comment]
I'm reworking this theme a bit, and thinking perhaps it'd be best if I just submit to the new marketplace rather than core? @GaberNeighbor

**Pull request closed without merging**
