### PR TITLE
Add Missing Translations for GrapeJS

### PR DESCRIPTION
**Pull request by code5rick**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [Yes]
| New feature/enhancement? (use the a.x branch)      | [No]
| Deprecations?                          | [No]
| BC breaks? (use the c.x branch)        | [No]
| Automated tests included?              | [No] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | [Fixes #13098](https://github.com/mautic/mautic/issues/13072) 

#### Description:

The new Mautic 5 comes with some minor changes to the GrapeJS builder, and some labels have been added. This PR addresses the [issue #13098](https://github.com/mautic/mautic/issues/13072) and also resolves the absence of labels for the columns.

image

#### Note:

I have added the missing labels for the preview icon and the modal alert. However, I would recommend that someone review my PR to ensure that these two cases are handled correctly.

image

image

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
I can see those translation strings are used in builder.js but never defined. So this should work. I couldn't replicate the error myself but I saw it at some point. 👍

**Review by PatrickJenkner — COMMENTED** [review]
The columns and the preview have proper labels, but the checkmark doesn't seem to have the right tooltip:
image

**Review by escopecz — APPROVED** [review]
I added the missing translations:
Screenshot 2024-01-15 at 10 56 24
Screenshot 2024-01-15 at 10 56 03
Good to go!

**Comment by code5rick** [comment]
@escopecz line 21 and 25 use the same class. We should delete one

**Comment by escopecz** [comment]
OOps. I'll push the change. Thanks for checking!

**Comment by escopecz** [comment]
https://github.com/mautic/mautic/pull/13224 @code5rick can you please approve?

**Comment by code5rick** [comment]
@escopecz tested, and it is working perfectly! The previously missing labels are now fixed and functioning at 100% 👌

**Pull request merged**
