### PR TITLE
Add wordpress to the list of automatic integrations

### PR DESCRIPTION
**Pull request by volha-pivavarchyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [no]
| New feature/enhancement? (use the a.x branch)      | [yes]
| Deprecations?                          | [no]
| BC breaks? (use the c.x branch)        | [no]
| Automated tests included?              | [no] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

As a user I want an easy way to integrate my form with my CMS

Since Wordpress is the most commonly used CMS we should add it to the list of options to automatically integrate Forms.
#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create new form or use existing one
3. Open the modal to copy the injection code 
4. Wordpress injection code here

image

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11096"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
I'm not sure about this. It is a feature of the [WordPress plugin](https://github.com/mautic/mautic-wordpress). There are several such plugins for different CMSes. I don't think we should hard-code them all to this modal box. Users can find it disturbing when they use some other CMS. But it is good idea to let the users know they exist. Maybe a link to the docs where we document all of those plugins? That way we will be able to update the list without a need to make a new release of Mautic.

What do you think? @RCheesley @kuzmany @jos0405 and others?

**Comment by RCheesley** [comment]
I'm inclined to agree with you @escopecz - I think if we added one we'd end up adding them all and it would quickly become quite a mess.

Maybe if there were a slot here that the plugins could inject into if they were installed and configured it might be more elegant? What do you think?

**Comment by kuzmany** [comment]
Probably we can add custom hook  and anybody can extend that part by plugins. Similar like this https://github.com/mautic/mautic/pull/6840

**Comment by volha-pivavarchyk** [comment]
I will look at the WordPress plugin and figure out how I can do it. I have never used this plugin before.

**Comment by jos0405** [comment]
In my opinion WP is the most popular integration, but others might have another opinion.
I agree with @kuzmany, the hook is better solution and we can keep the page uncluttered.
I tested this PR, and it works, so I'll add an approval from functionality point of view.

**Comment by jos0405** [comment]
The link should look like:

[mautic type="form" id="1"]

No curly brackets.

**Comment by adiux** [comment]
@RCheesley Should we add WP as it is the most used CMS? Or how can we come to a decision here?

**Comment by RCheesley** [comment]
I suggest we add a custom hook as has been suggested, and allow plugins to push the information.

**Comment by adiux** [comment]
ok, therefore I will close this PR

**Pull request closed without merging**
