### PR TITLE
Apply Rector Rule: Remove Annotation

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR introduce a new set of rector rules to modify Attributes, this PR is ready for testing

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Code Review only

### CODE REVIEW

**Comment by mabumusa1** [comment]
Errors during `rector` run 

```
                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/AssetBundle/Entity/DownloadRepository.php" file, due to:          
         "System error: "An entity was not found for "Mautic\AssetBundle\Entity\DownloadRepository" repository."        
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/ApiBundle/Entity/oAuth2/ClientRepository.php" file, due to:       
         "System error: "An entity was not found for "Mautic\ApiBundle\Entity\oAuth2\ClientRepository" repository."     
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/CoreBundle/Form/DataTransformer/IdToEntityModelTransformer.php"   
         file, due to:                                                                                                  
         "System error: "Look at                                                                                        
         "Rector\Doctrine\Rector\MethodCall\ReplaceParentRepositoryCallsByRepositoryPropertyRector::resolveRepositoryNam
         e()"92"                                                                                                        
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 92
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/CampaignBundle/Entity/SummaryRepository.php" file, due to:        
         "System error: "An entity was not found for "Mautic\CampaignBundle\Entity\SummaryRepository" repository."      
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/CoreBundle/Entity/AuditLogRepository.php" file, due to:           
         "System error: "An entity was not found for "Mautic\CoreBundle\Entity\AuditLogRepository" repository."         
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/CoreBundle/Entity/IpAddressRepository.php" file, due to:          
         "System error: "An entity was not found for "Mautic\CoreBundle\Entity\IpAddressRepository" repository."        
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/CoreBundle/Entity/NotificationRepository.php" file, due to:       
         "System error: "An entity was not found for "Mautic\CoreBundle\Entity\NotificationRepository" repository."     
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/DashboardBundle/Entity/WidgetRepository.php" file, due to:        
         "System error: "An entity was not found for "Mautic\DashboardBundle\Entity\WidgetRepository" repository."      
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/CampaignBundle/Entity/FailedLeadEventLogRepository.php" file, due 
         to:                                                                                                            
         "System error: "An entity was not found for "Mautic\CampaignBundle\Entity\FailedLeadEventLogRepository"        
         repository."                                                                                                   
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/DynamicContentBundle/Entity/DynamicContentLeadDataRepository.php" 
         file, due to:                                                                                                  
         "System error: "An entity was not found for                                                                    
         "Mautic\DynamicContentBundle\Entity\DynamicContentLeadDataRepository" repository."                             
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/DynamicContentBundle/Entity/StatRepository.php" file, due to:     
         "System error: "An entity was not found for "Mautic\DynamicContentBundle\Entity\StatRepository" repository."   
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/EmailBundle/Entity/CopyRepository.php" file, due to:              
         "System error: "An entity was not found for "Mautic\EmailBundle\Entity\CopyRepository" repository."            
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/EmailBundle/Entity/EmailReplyRepository.php" file, due to:        
         "System error: "An entity was not found for "Mautic\EmailBundle\Entity\EmailReplyRepository" repository."      
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/EmailBundle/Entity/StatDeviceRepository.php" file, due to:        
         "System error: "An entity was not found for "Mautic\EmailBundle\Entity\StatDeviceRepository" repository."      
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/EmailBundle/Entity/StatRepository.php" file, due to:              
         "System error: "An entity was not found for "Mautic\EmailBundle\Entity\StatRepository" repository."            
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/FormBundle/Entity/ActionRepository.php" file, due to:             
         "System error: "An entity was not found for "Mautic\FormBundle\Entity\ActionRepository" repository."           
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/FormBundle/Entity/FieldRepository.php" file, due to:              
         "System error: "An entity was not found for "Mautic\FormBundle\Entity\FieldRepository" repository."            
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/FormBundle/Entity/FormRepository.php" file, due to:               
         "System error: "An entity was not found for "Mautic\FormBundle\Entity\FormRepository" repository."             
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/IntegrationsBundle/Entity/FieldChangeRepository.php" file, due to:
         "System error: "An entity was not found for "Mautic\IntegrationsBundle\Entity\FieldChangeRepository"           
         repository."                                                                                                   
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/LeadBundle/Form/DataTransformer/TagEntityModelTransformer.php"    
         file, due to:                                                                                                  
         "System error: "Look at                                                                                        
         "Rector\Doctrine\Rector\MethodCall\ReplaceParentRepositoryCallsByRepositoryPropertyRector::resolveRepositoryNam
         e()"92"                                                                                                        
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 92
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/LeadBundle/Entity/StagesChangeLogRepository.php" file, due to:    
         "System error: "An entity was not found for "Mautic\LeadBundle\Entity\StagesChangeLogRepository" repository."  
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/LeadBundle/Entity/UtmTagRepository.php" file, due to:             
         "System error: "An entity was not found for "Mautic\LeadBundle\Entity\UtmTagRepository" repository."           
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/NotificationBundle/Entity/PushIDRepository.php" file, due to:     
         "System error: "An entity was not found for "Mautic\NotificationBundle\Entity\PushIDRepository" repository."   
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/NotificationBundle/Entity/StatRepository.php" file, due to:       
         "System error: "An entity was not found for "Mautic\NotificationBundle\Entity\StatRepository" repository."     
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/LeadBundle/Entity/CompanyChangeLogRepository.php" file, due to:   
         "System error: "An entity was not found for "Mautic\LeadBundle\Entity\CompanyChangeLogRepository" repository." 
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/LeadBundle/Entity/CompanyLeadRepository.php" file, due to:        
         "System error: "An entity was not found for "Mautic\LeadBundle\Entity\CompanyLeadRepository" repository."      
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/LeadBundle/Entity/ContactExportSchedulerRepository.php" file, due 
         to:                                                                                                            
         "System error: "An entity was not found for "Mautic\LeadBundle\Entity\ContactExportSchedulerRepository"        
         repository."                                                                                                   
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/LeadBundle/Entity/FrequencyRuleRepository.php" file, due to:      
         "System error: "An entity was not found for "Mautic\LeadBundle\Entity\FrequencyRuleRepository" repository."    
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/LeadBundle/Entity/ImportRepository.php" file, due to:             
         "System error: "An entity was not found for "Mautic\LeadBundle\Entity\ImportRepository" repository."           
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/PointBundle/Entity/PointRepository.php" file, due to:             
         "System error: "An entity was not found for "Mautic\PointBundle\Entity\PointRepository" repository."           
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/PointBundle/Entity/TriggerEventRepository.php" file, due to:      
         "System error: "An entity was not found for "Mautic\PointBundle\Entity\TriggerEventRepository" repository."    
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/PointBundle/Entity/TriggerRepository.php" file, due to:           
         "System error: "An entity was not found for "Mautic\PointBundle\Entity\TriggerRepository" repository."         
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/PageBundle/Entity/PageRepository.php" file, due to:               
         "System error: "An entity was not found for "Mautic\PageBundle\Entity\PageRepository" repository."             
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/PageBundle/Entity/RedirectRepository.php" file, due to:           
         "System error: "An entity was not found for "Mautic\PageBundle\Entity\RedirectRepository" repository."         
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/PageBundle/Entity/TrackableRepository.php" file, due to:          
         "System error: "An entity was not found for "Mautic\PageBundle\Entity\TrackableRepository" repository."        
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/PointBundle/Entity/LeadPointLogRepository.php" file, due to:      
         "System error: "An entity was not found for "Mautic\PointBundle\Entity\LeadPointLogRepository" repository."    
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/PointBundle/Entity/LeadTriggerLogRepository.php" file, due to:    
         "System error: "An entity was not found for "Mautic\PointBundle\Entity\LeadTriggerLogRepository" repository."  
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/PluginBundle/Entity/IntegrationRepository.php" file, due to:      
         "System error: "An entity was not found for "Mautic\PluginBundle\Entity\IntegrationRepository" repository."    
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/PluginBundle/Entity/PluginRepository.php" file, due to:           
         "System error: "An entity was not found for "Mautic\PluginBundle\Entity\PluginRepository" repository."         
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/LeadBundle/Entity/LeadCategoryRepository.php" file, due to:       
         "System error: "An entity was not found for "Mautic\LeadBundle\Entity\LeadCategoryRepository" repository."     
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/LeadBundle/Entity/LeadListRepository.php" file, due to:           
         "System error: "An entity was not found for "Mautic\LeadBundle\Entity\LeadListRepository" repository."         
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/LeadBundle/Entity/ListLeadRepository.php" file, due to:           
         "System error: "An entity was not found for "Mautic\LeadBundle\Entity\ListLeadRepository" repository."         
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/LeadBundle/Entity/PointsChangeLogRepository.php" file, due to:    
         "System error: "An entity was not found for "Mautic\LeadBundle\Entity\PointsChangeLogRepository" repository."  
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/UserBundle/Entity/UserTokenRepository.php" file, due to:          
         "System error: "An entity was not found for "Mautic\UserBundle\Entity\UserTokenRepository" repository."        
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/StageBundle/Entity/LeadStageLogRepository.php" file, due to:      
         "System error: "An entity was not found for "Mautic\StageBundle\Entity\LeadStageLogRepository" repository."    
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/StageBundle/Entity/StageRepository.php" file, due to:             
         "System error: "An entity was not found for "Mautic\StageBundle\Entity\StageRepository" repository."           
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/SmsBundle/Entity/StatRepository.php" file, due to:                
         "System error: "An entity was not found for "Mautic\SmsBundle\Entity\StatRepository" repository."              
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/plugins/GrapesJsBuilderBundle/Entity/GrapesJsBuilderRepository.php" file, due 
         to:                                                                                                            
         "System error: "An entity was not found for                                                                    
         "MauticPlugin\GrapesJsBuilderBundle\Entity\GrapesJsBuilderRepository" repository."                             
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/WebhookBundle/Entity/EventRepository.php" file, due to:           
         "System error: "An entity was not found for "Mautic\WebhookBundle\Entity\EventRepository" repository."         
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/WebhookBundle/Entity/LogRepository.php" file, due to:             
         "System error: "An entity was not found for "Mautic\WebhookBundle\Entity\LogRepository" repository."           
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/WebhookBundle/Entity/WebhookQueueRepository.php" file, due to:    
         "System error: "An entity was not found for "Mautic\WebhookBundle\Entity\WebhookQueueRepository" repository."  
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/WebhookBundle/Entity/WebhookRepository.php" file, due to:         
         "System error: "An entity was not found for "Mautic\WebhookBundle\Entity\WebhookRepository" repository."       
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 48
                                                                                                                        

                                                                                                                       
 [ERROR] Could not process "/var/www/html/app/bundles/LeadBundle/Form/DataTransformer/TagEntityModelTransformer.php"    
         file, due to:                                                                                                  
         "System error: "Look at                                                                                        
         "Rector\Doctrine\Rector\MethodCall\ReplaceParentRepositoryCallsByRepositoryPropertyRector::resolveRepositoryNam
         e()"92"                                                                                                        
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 92
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/CoreBundle/Form/DataTransformer/IdToEntityModelTransformer.php"   
         file, due to:                                                                                                  
         "System error: "Look at                                                                                        
         "Rector\Doctrine\Rector\MethodCall\ReplaceParentRepositoryCallsByRepositoryPropertyRector::resolveRepositoryNam
         e()"92"                                                                                                        
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 92
                      
                      
                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/CoreBundle/Form/DataTransformer/IdToEntityModelTransformer.php"   
         file, due to:                                                                                                  
         "System error: "Look at                                                                                        
         "Rector\Doctrine\Rector\MethodCall\ReplaceParentRepositoryCallsByRepositoryPropertyRector::resolveRepositoryNam
         e()"92"                                                                                                        
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 92
                                                                                                                        

                                                                                                                        
 [ERROR] Could not process "/var/www/html/app/bundles/LeadBundle/Form/DataTransformer/TagEntityModelTransformer.php"    
         file, due to:                                                                                                  
         "System error: "Look at                                                                                        
         "Rector\Doctrine\Rector\MethodCall\ReplaceParentRepositoryCallsByRepositoryPropertyRector::resolveRepositoryNam
         e()"92"                                                                                                        
         Run Rector with "--debug" option and post the report here: https://github.com/rectorphp/rector/issues/new". On line: 92
                                                                                                                        
                      
```

**Comment by escopecz** [comment]
@mabumusa1 I'm bit confused. You've requested my review but the description say:

> this work is still under progress

Which is it?

**Comment by mabumusa1** [comment]
> @mabumusa1 I'm bit confused. You've requested my review but the description say:
> 
> > this work is still under progress
> 
> Which is it?

Sorry, I did not updated the description, this one is ready for testing

**Review by escopecz — APPROVED** [review]
This looks correct. Thanks! 👍

**Pull request merged**
