### PR TITLE
Adding the Connection: Close response header only when the request is made using HTTP/1.1.

### LINKED ISSUE #9077: Non-conformant HTTP/2 response to GET /mtracking.gif
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

| Q   | A
| --- | ---
| Mautic version |  3.0.2
| PHP version |  7.3
| Browser |  Safari
| Web server | HTTP/2

When Mautic replies to a request for the tracking pixel at /mtracking.gif, it explicitly closes the HTTP connection by adding a **Connection: Close** response header. This is valid HTTP/1.1 to tell the client to terminate the connection (no keep-alive). With HTTP/2 this header is prohibited, as the concept of connection keep-alive is handled very differently in this newer protocol. See https://tools.ietf.org/html/rfc7540#section-8.1.2.2

Responding with **Connection: Close** to a HTTP/2 request is _non-conformant_, and will generate warnings/errors at the client side:
- Safari on MacOS will report a Protocol Error
- FireFox and Chrome will not complain but will report that the /mtracking.gif request takes more than one second to complete in their dev tools
- Command line curl will report an error: “HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)”

The page hit is correctly recorded in the Mautic database, as this happens before the http response is sent. Nevertheless, responding with non-conformant HTTP/2 may have unexpected consequences. For instance, I am not sure how HTTP clients embedded in e-mail clients/webmails will handle this error.

### Steps to reproduce
1.	Use Mautic 3.0.2 behind a HTTP/2 server, in my case Nginx. But any HTTP/2 server and any Mautic version after 1.2.1 will do.
2.	Open the tracking pixel URL in Safari: https://mautic.your.domain/mtracking.gif
3.	Notice the full screen HTTP error reported _Safari Can't Open the Page  ... Protocol Error_
4.	If you do not have access to a MacOS machine with Safari, you can just run the following command on Linux:
`curl https://mautic.your.domain/mtracking.gif`
5.	Observe the curl error: _HTTP/2 stream 0 was not closed cleanly_

### Log errors
No Mautic errors added to [mautic]/var/log
No errors in Nginx logs

### Root cause
The problem is located in [Mautic\CoreBundle\Helper\TrackingPixelHelper](https://github.com/mautic/mautic/blob/473f08ba652634b59feca41c8b53d24d9d7682ed/app/bundles/CoreBundle/Helper/TrackingPixelHelper.php#L52) and was introduced in 2015 (e3fd8ca37bbef6bea25d4bee78d61183f273b0a3), well before HTTP/2 was widely used.

```php
if ('GET' == $request->getMethod()) {
    $response->headers->set('Connection', 'close');
    ...
}
```

The fix should be to test which HTTP version the client is using, and add the **Connection: Close** response header only when the request is made using HTTP/1.1. 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by nfakhour**
Adding the Connection: Close response header only when the request is made using HTTP/1.1.

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                |  3.2 for bug fixes 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #9077  

#### Description:
Responding with Connection: Close to a HTTP/2 request is non-conformant, and will generate warnings/errors on Safari , this PR prevents having this error.
Fixes https://github.com/mautic/mautic/issues/9077

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)

### CODE REVIEW

**Comment by npracht** [comment]
Bravo Najoua ! So happy to see you there.
Please follow instructions from the bot and i'm sure we can merge this very fast !

**Comment by mabumusa1** [comment]
@nfakhour Thank you for your PR, may you please look into the errors of the build, to fix CS all you have to do run is ``composer fixcs``. I think rector will not have issues once you fix CS.

I will test this PR when I get an environment that suffers from this issue, if you have a server where the issues happen, please let me know I will test it before the PR and after it to confirm the results

**Comment by Dcoutelle** [comment]
Tested behind a loadbalancer with HTTP/1.1 and it is OK
I am not able to test it in HTTP/2

**Comment by npracht** [comment]
@cla-bot check

**Comment by npracht** [comment]
@nfakhour please sign the contributor agreement :)

**Review by npracht — APPROVED** [review]
👍

**Review by mabumusa1 — APPROVED** [review]
I could not replicate the test steps, but the code review seems logical and it should fix the issue

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Thanks for this PR @nfakhour and apologies for the slight delay in getting the contributors agreement check passed! I've edited your description just to link up that it fixes the issue you mentioned, should be good to go if all are in agreement!

**Comment by hluchas** [comment]
@RCheesley we need to restart checks to run codecov again

**Pull request merged**
