### PR TITLE
Fix No Data shown for Most hit email redirects dashboard widget

### PR DESCRIPTION
**Pull request by tejasync**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✅ 
| New feature/enhancement? (use the a.x branch)      | ❌ 
| Deprecations?                          | ❌ 
| BC breaks? (use the c.x branch)        | ❌ 
| Automated tests included?              | ✅  
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR fixes no data shown for most hit email redirects dashboard widget.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Go to Email 
3. Create template Email with link in it 
4. Go to campaign 
5. Create campaign with send email action 
6. Select above created email 
7. Publish the campaign 
8. Open mailbox read email and click on link on email 
9. Go to dashboard 
10. Add Widget -> 'Most hit Email redirects'
11. Save 
12. Widget should not stay blank

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11086"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
@ts-navghane we'll need to cover the change with tests so we could merge it. Please add them.

**Comment by tejasync** [comment]
@escopecz, the lines are already covered by the test cases. I don't understand why codecov is not happy?

Screenshot 2022-04-26 at 17 31 13

**Comment by tejasync** [comment]
I'll remove the 'needs-automated-tests' label as the code is already covered.

**Review by escopecz — DISMISSED** [review]
The code change make sense. We should count with date to - end of day.

The coverage dropped because 2 lines were merged into 1 I think. The code is covered.

**Comment by volha-pivavarchyk** [comment]
My widget is still empty. Perhaps, I cannot test on the local machine.

image

**Comment by kuzmany** [comment]
@volha-pivavarchyk there is 10 minutes cache, you can try change date range

**Review by volha-pivavarchyk — DISMISSED** [review]
Works as described
image

**Review by escopecz — APPROVED** [review]

**Pull request merged**
