### PR TITLE
Feature builder secitons

### PR DESCRIPTION
**Pull request by escopecz**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | Y
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/163
| Related developer documentation PR URL | https://github.com/mautic/developer-documentation/pull/51
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/3439, https://github.com/mautic/mautic/issues/3148, possibly https://github.com/mautic/mautic/issues/3417
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR improves the Email/Page Builder sections. They can be now moved up or down, deleted and 3 new section types can be added. With 1,2 and 3 column layout.

mautic-builder-sections

+ The Medium and Large button sizes are bigger.
+ Fixed JS errror `Editor should be initialized before calling the destroy method.` when closing the builder.
+ Image slot editor fixed, aligning works.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. This PR also fixes an issue where sometimes the slots couldn't be moved or added new ones. They could be only edited. When I checked the content, the `data-*` which didn't have any value HTML attributes were removed. I added a value to them so it should fix it. I didn't have an issue with it after. I don't know how to reproduce it.
2. The dev tools console throws errors and warnings on different actions - is fixed in this PR.
3. In the code mode try to save this content:
```
<!--[if gte mso 9]><xml>
 <o:OfficeDocumentSettings>
  <o:AllowPNG/>
  <o:PixelsPerInch>96</o:PixelsPerInch>
 </o:OfficeDocumentSettings>
</xml><![endif]-->
```
The `<o:*>` and `<xml>` tags will get stripped. They won't after this PR. The unit test added to ensure that for the future updates. Feel free to run unit tests.

#### Steps to test this PR:
1. Apply this PR.
2. Clear the cache.
3. Rebuild Assets with `app/console mautic:assets:generate` command.
4. Try to edit/create email/page with different themes. The old functionality should work as before and you should be able to order/delete/create sections.
5. Test that the image slot editor aligns the image to left, right or center.

### CODE REVIEW

**Comment by MaxWebmecanik** [comment]
Great job! 😄

**Comment by moskoweb** [comment]
In addition to columns only, there could be how to create section presets when you create a theme, and that in the Builder you could drag those pre-defined sections to the email.

**Comment by escopecz** [comment]
@moskoweb that's a good idea for a feature request. It's not part of this PR. Sections can be created with a Mautic plugin, but not with a theme.

**Comment by mqueme** [comment]
This worked great! I only have one suggestion. Maybe the double arrow will look better if the icon was a reorder icon, the double icon gives the suggestion or resizing.

**Comment by merlin0** [comment]
The builder is still removing outlook code when I tested on the hosted version with code mode. The following code gets removed:
 xmlns:v="urn:schemas-microsoft-com:vml"
 xmlns:w="urn:schemas-microsoft-com:office:word"
 href="/" style="height:50px;v-text-anchor:middle;width:480px;" arcsize="50%" stroke="f" fillcolor="#d9015c">
 </v:roundrect>

**Comment by escopecz** [comment]
@merlin0 this fix allows only XML namespaces `<o:/>` and `<w:/>` which I was able to find at various places while searching for it. I didn't find any official Microsoft documentation about what namespaces are needed. Do you have a list of it?

**Comment by merlin0** [comment]
Currently we use a VML based fallback for outlook to show a consistent button across all clients.  We do this with ``` <v:> </v:> ```,``` <w:>``` and ``` <center>```.  See following [article.](https://litmus.com/blog/a-guide-to-bulletproof-buttons-in-email-design) With Mautic 2.7 the ``` <v:> ``` still get's stripped. The centre and W work fine now like you said.

**Comment by escopecz** [comment]
@merlin0 fixed in https://github.com/mautic/mautic/pull/3605

**Pull request merged**
