### PR TITLE
Corrects htaccess apache support <2.4

### PR DESCRIPTION
**Pull request by tomekkowalczyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ y]
| New feature/enhancement? (use the a.x branch)      | [n ]
| Deprecations?                          | [ n]
| BC breaks? (use the c.x branch)        | [ n]
| Automated tests included?              | [ n] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

if we are using apache version less than 2.4 support for '<if' command is not available. we get the following error: 

`[alert] /home/users/xxx/public_html/xxx/.htaccess: Invalid command '<If', perhaps misspelled or defined by a module not included in the server configuration`

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Run Mautic on a lower apache instance than 2.4
3. Run automatic update in Mautic

### CODE REVIEW

**Comment by escopecz** [comment]
I'm not sure about this change. [This page](https://endoflife.date/apache) states that Apache versions prior to 2.4 are not getting security updates for more than 5 years. There is a rule in Mautic that applies to PHP and MySql versions that Mautic will stop supporting versions that run out of security support. I think we should do the same for other requirements such as Apache and instead update https://www.mautic.org/download/requirements that Mautic requires Apache 2.4+.

@RCheesley @npracht WDYT?

**Comment by RCheesley** [comment]
I think that Mautic 5 would be the sensible time to formally drop support. That being said, as we have seen in previous releases, anything that changes the htaccess file causes quite some problems as people don't read the release notes, so if we do merge this in a patch release we will need to do a _lot_ of comms about it in advance.

**Comment by escopecz** [comment]
Well, this PR is basically reverting https://github.com/mautic/mautic/commit/cd998bdd4f5b72f7bee91898d9351919273516ba which was a fix for a security vulnerability https://github.com/advisories/GHSA-mj6m-246h-9w56, so we'd have to find some fix that prevents the security vulnerability and works for the older Apache versions. This isn't it.

**Comment by tomekkowalczyk** [comment]
@escopecz, @RCheesley Since Mautic 5 will not support Apache versions lower than 2.4, it would be nice to update https://www.mautic.org/download/requirements#footnote-apache

**Comment by RCheesley** [comment]
> @escopecz, @RCheesley Since Mautic 5 will not support Apache versions lower than 2.4, it would be nice to update https://www.mautic.org/download/requirements#footnote-apache

Yes indeed, although I don't think we have made that decision. I was suggesting that if we were going to drop support it would make sense to do it in a Major release. I do agree with @escopecz both about supporting outdated technology, and that we can't just re-introduce a security bug which has been fixed - we would need to find a way to actually fix it.

**Comment by mabumusa1** [comment]
@escopecz since we are not going to support apache < 2.4 let's close this PR, thoughts?

**Comment by escopecz** [comment]
Agreed. We can continue discussing it while closed and reopen any time when this PR will support the older Apache version as well as be secure.

**Pull request closed without merging**
