### PR TITLE
Add validation to ensure that we are not trying to access attributes …

### LINKED ISSUE #9762: Multiple areas of Mautic throw a 500 error
## Bug Description
I came across this issue when running the Cypress DWC tests and found it to also be reported in Emails (see #9646 #9755 and /https://forum.mautic.org/t/notices-trying-to-access-array-offset-on-value-of-type-null/18008).

I found it by trying to open a DWC item that was created but others find it with using certain email templates (with the legacy builder) as listed in the forum thread.

| Q   | A
| --- | ---
| Mautic version | 3.3.1
| PHP version | 7.4
| Browser | Chrome

### Steps to reproduce
1. Create dynamic content
2. Click to edit dynamic content
3. Notice a 503 error and log entry below
 
### Log errors

`mautic.NOTICE: PHP Notice - Trying to access array offset on value of type null - in file /var/www/html/app/bundles/EmailBundle/Views/FormTheme/Email/_emailform_dynamicContent_entry_filters_entry_filters_entry_widget.html.php - at line 14 {"mauticTemplateVars":{"app":"[object] (Symfony\\Bundle\\FrameworkBundle\\Templating\\GlobalVariables: {})","value":null,"attr":{"class":"form-control"},"form":"[object] (Symfony\\Component\\Form\\FormView: null)","id":"emailform_dynamicContent_0_filters_0_filters___name__","name":"__name__","full_name":"emailform[dynamicContent][0][filters][0][filters][__name__]","disabled":false,"label":false,"label_format":null,"multipart":false,"block_prefixes":["form","dynamic_content_filter_entry_filters","_emailform_dynamicContent_entry_filters_entry_filters_entry"],"unique_block_prefix":"_emailform_dynamicContent_entry_filters_entry_filters_entry","translation_domain":null,"cache_key":"_emailform_dynamicContent_entry_filters_entry_filters_entry_dynamic_content_filter_entry_filters","errors":"[object] (Symfony\\Component\\Form\\FormErrorIterator: )","valid":true,"data":null,"required":true,"size":null,"label_attr":[],"compound":true,"method":"POST","action":"","submitted":false,"mauticContent":"email","mauticTemplate":"MauticEmailBundle:FormTheme\\Email:_emailform_dynamicContent_entry_filters_entry_filters_entry_widget.html.php","view":"[object] (Mautic\\CoreBundle\\Templating\\Engine\\PhpEngine: {})"},"app":"[object] (Symfony\\Bundle\\FrameworkBundle\\Templating\\GlobalVariables: {})","value":null,"attr":{"class":"form-control"},"form":"[object] (Symfony\\Component\\Form\\FormView: null)","id":"emailform_dynamicContent_0_filters_0_filters___name__","name":"__name__","full_name":"emailform[dynamicContent][0][filters][0][filters][__name__]","disabled":false,"label":false,"label_format":null,"multipart":false,"block_prefixes":["form","dynamic_content_filter_entry_filters","_emailform_dynamicContent_entry_filters_entry_filters_entry"],"unique_block_prefix":"_emailform_dynamicContent_entry_filters_entry_filters_entry","translation_domain":null,"cache_key":"_emailform_dynamicContent_entry_filters_entry_filters_entry_dynamic_content_filter_entry_filters","errors":"[object] (Symfony\\Component\\Form\\FormErrorIterator: )","valid":true,"data":null,"required":true,"size":null,"label_attr":[],"compound":true,"method":"POST","action":"","submitted":false,"mauticContent":"email","mauticTemplate":"MauticEmailBundle:FormTheme\\Email:_emailform_dynamicContent_entry_filters_entry_filters_entry_widget.html.php","view":"[object] (Mautic\\CoreBundle\\Templating\\Engine\\PhpEngine: {})","isPrototype":true,"filterType":"","filterGroup":""} []
`

### PR DESCRIPTION
**Pull request by mohit-rocks**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/issues/9762 

#### Description:
Scenario 1: 
- Load the PR
- Try to create an email (with segment) and edit it.
- You should see the errors mentioned in https://github.com/mautic/mautic/issues/9762
- This PR fixes it.

Scenario 2:
Comment: https://github.com/mautic/mautic/pull/9795#issuecomment-834018754

Scenario 3:
Comment: https://github.com/mautic/mautic/pull/9795#issuecomment-810740477

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2.

### CODE REVIEW

**Comment by mohit-rocks** [comment]
The other two issues mentioned in https://github.com/mautic/mautic/issues/9762 are not reproducible anymore.
I think it needs some testing from community folks.

**Review by RCheesley — CHANGES_REQUESTED** [review]
@mohit-rocks This seems to resolve the issue for email - creating a new email using the Goldstar theme I no longer see the errors.

DWC does seem to have been fixed as that is no longer throwing an error for me.

Report saving is now throwing a different error for me:

```
[2021-03-19 19:18:13] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "PHP Warning - Illegal string offset 'column'" at /var/www/html/app/bundles/ReportBundle/Form/Type/FilterSelectorType.php line 88 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): PHP Warning - Illegal string offset 'column' at /var/www/html/app/bundles/ReportBundle/Form/Type/FilterSelectorType.php:88)
[stacktrace]
#0 /var/www/html/app/bundles/ReportBundle/Form/Type/FilterSelectorType.php(88): Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler->handleError(2, 'PHP Warning - I...', '/var/www/html/a...', 88, Array)
#1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(214): Mautic\\ReportBundle\\Form\\Type\\FilterSelectorType->Mautic\\ReportBundle\\Form\\Type\\{closure}(Object(Symfony\\Component\\Form\\FormEvent), 'form.pre_bind', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))
#2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'form.pre_bind', Object(Symfony\\Component\\Form\\FormEvent))
#3 /var/www/html/vendor/symfony/event-dispatcher/ImmutableEventDispatcher.php(33): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('form.pre_bind', Object(Symfony\\Component\\Form\\FormEvent))
#4 /var/www/html/vendor/symfony/form/Form.php(552): Symfony\\Component\\EventDispatcher\\ImmutableEventDispatcher->dispatch('form.pre_bind', Object(Symfony\\Component\\Form\\FormEvent))
#5 /var/www/html/vendor/symfony/form/Form.php(573): Symfony\\Component\\Form\\Form->submit(Array, true)
#6 /var/www/html/vendor/symfony/form/Form.php(573): Symfony\\Component\\Form\\Form->submit(Array, true)
#7 /var/www/html/vendor/symfony/form/Extension/HttpFoundation/HttpFoundationRequestHandler.php(109): Symfony\\Component\\Form\\Form->submit(Array, true)
#8 /var/www/html/vendor/symfony/form/Form.php(487): Symfony\\Component\\Form\\Extension\\HttpFoundation\\HttpFoundationRequestHandler->handleRequest(Object(Symfony\\Component\\Form\\Form), Object(Symfony\\Component\\HttpFoundation\\Request))
#9 /var/www/html/app/bundles/CoreBundle/Controller/AbstractFormController.php(167): Symfony\\Component\\Form\\Form->handleRequest(Object(Symfony\\Component\\HttpFoundation\\Request))
#10 /var/www/html/app/bundles/ReportBundle/Controller/ReportController.php(355): Mautic\\CoreBundle\\Controller\\AbstractFormController->isFormValid(Object(Symfony\\Component\\Form\\Form))
#11 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(456): Mautic\\ReportBundle\\Controller\\ReportController->editAction('18', '')
#12 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('edit', '18', 0, '')
#13 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#14 /var/www/html/vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 /var/www/html/app/AppKernel.php(104): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#16 /var/www/html/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#18 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(61): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#19 /var/www/html/app/middlewares/VersionCheckMiddleware.php(67): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#20 /var/www/html/app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#21 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#22 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#23 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#24 {main}
"} 

```

**Review by RCheesley — DISMISSED** [review]

**Comment by domparry** [comment]
This has fixed our email error too.

**Comment by RCheesley** [comment]
https://youtu.be/-aTz-uQV9yo Here is a screencast of the error that I was seeing with the report - it was a few days ago but I am pretty sure that I checked at the time that it did not happen before the PR was applied.

**Comment by stevedrobinson** [comment]
I was getting this error (I think it's the same) when trying to view a contacts report with a filter based on segment. 

**Before the PR**, I got this error in the log and a 500 in the browser:
`PHP message: PHP Notice:  Trying to access array offset on value of type null in /path/to/mautic/app/bundles/ReportBundle/Form/Type/FilterSelectorType.php on line 80" while reading response header from upstream, client: XX.XX.XX.XX, server: my.mauticinstance.com, request: "GET /s/reports/edit/17 HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "ma.brilliantmetrics.com", referrer: "https://my.mautic.instance/s/reports/edit/17`

**After applying the PR**, I get this error in the log and a 500 error in the browser:
`PHP message: PHP Warning:  Illegal string offset 'column' in /path/to/mautic/html/app/bundles/ReportBundle/Form/Type/FilterSelectorType.php on line 89" while reading response header from upstream, client: xx.xx.xx.xx, server: my.mauticinstance.com, request: "POST /s/reports/edit/17?mauticUserLastActive=26&mauticLastNotificationId=12179 HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "my.mauticinstance.com", referrer: "https://my.mauticinstance.com/s/reports/edit/17`

Let me know if I can offer any more info and/or test again...

**Comment by mohit-rocks** [comment]
@stevedrobinson I tried to fix that issue in last commit https://github.com/mautic/mautic/pull/9795/commits/bb577a017015af43ebfe7515196f021c6fa75798 of this PR
Can you please try to check once in MautiBox.

**Comment by RCheesley** [comment]
@mohit-rocks are you able to rebase this on features please, so it could be considered for 4.0?

**Comment by stevedrobinson** [comment]
I retested in MautiBox and if I create a contacts report and add a filter for [Email] [is not empty] I get the following errors:
```
/app/bundles/ReportBundle/Form/Type/FilterSelectorType.php:89 at
/app/bundles/ReportBundle/Form/Type/FilterSelectorType.php:89 at Mautic\CoreBundle\ErrorHandler\ErrorHandler -> handleError ( '2', 'PHP Warning - Illegal string offset 'column'', '/var/app/current/code/pulls/9795/app/bundles/ReportBundle/Form/Type/FilterSelectorType.php', '89', array('event' => object(FormEvent), 'formModifier' => object(Closure), 'data' => 'l.email') )
/vendor/symfony/event-dispatcher/EventDispatcher.php:214 at Mautic\ReportBundle\Form\Type\FilterSelectorType -> Mautic\ReportBundle\Form\Type\{closure} ( object(FormEvent), 'form.pre_bind', object(EventDispatcher) )
/vendor/symfony/event-dispatcher/EventDispatcher.php:44 at Symfony\Component\EventDispatcher\EventDispatcher -> doDispatch ( array(array(object(TrimListener), 'preSubmit'), array(object(CsrfValidationListener), 'preSubmit'), object(Closure)), 'form.pre_bind', object(FormEvent) )
```

**Comment by RCheesley** [comment]
Thanks for working further on this @mohit-rocks - am now able to create reports (including with segment filters) without getting errors!

Was this a 4.0 change that we have missed? If so let's make sure that we have it documented in the upgrade-4.0.md file.

@stevedrobinson any chance you could re-test?

**Comment by sensalot** [comment]
> Thanks for working further on this @mohit-rocks - am now able to create reports (including with segment filters) without getting errors!
> 
> Was this a 4.0 change that we have missed? If so let's make sure that we have it documented in the upgrade-4.0.md file.
> 
> @stevedrobinson any chance you could re-test?

@RCheesley Does this mean we can't create new reports / view old ones untill 4.0?

**Comment by sensalot** [comment]
We added the two files to Mautic 3.2.5.
Editing of report became possible. Applying seems to work. A save and close seems to hang. View of many report is not possible. New created report: viewing is not possible.
Tested with Chrome, Firefox Edge. 2 devices in different locations.

Updgrading to 3.3.3. fixed the problem

**Review by shinde-rahul — APPROVED** [review]
Code changes looks good to me.

**Comment by RCheesley** [comment]
@all-contributors please add @mohit-rocks for code

**Comment by RCheesley** [comment]
@all-contributors please add @domparry for userTesting

**Comment by RCheesley** [comment]
@all-contributors please add @sensalot for userTesting

**Comment by RCheesley** [comment]
@all-contributors please add @shinde-rahul for review

**Pull request merged**
