### PR TITLE
Updating to latest symfony 5.4

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

Dependabot created a bunch of PRs to upgrade to the latest Symfony 5.4 libraries:
- https://github.com/mautic/mautic/pull/14253
- https://github.com/mautic/mautic/pull/14252
- https://github.com/mautic/mautic/pull/14250
- https://github.com/mautic/mautic/pull/14249
- https://github.com/mautic/mautic/pull/14269
- https://github.com/mautic/mautic/pull/14268

This happens usually if there is reported security vulnerability in a previous version. This PR is updating all Symfony packages to the latest patch version. So there are no new features nor BC breaks. Just bug and security fixes.

I've updated the versions in the `app/composer.json` file and then run `composer update symfony/*` to update the `composer.lock` file.

Then I noticed there is another PR updating Composer dependencies:

- https://github.com/mautic/mautic/pull/14263

I run this command to update it: `composer update twig/*`

### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Since this is updating the underlying framework, there are no steps to test. It affects everything.

### CODE REVIEW

**Review by lenonleite — DISMISSED** [review]
good job

**Review by RCheesley — DISMISSED** [review]
This seems to be fine, it's tested on 5.1.0 not 5.1.1 as we haven't done the back-merge into 5.x I think from the 5.1 branch? Otherwise it's fine.

**Comment by RCheesley** [comment]
https://github.com/mautic/mautic/pull/14269 s/could we include this one, too?

**Comment by escopecz** [comment]
Aha, the world is changing so fast... I'll upgrade to [5.4.47](https://github.com/symfony/symfony/releases/tag/v5.4.47) within this PR as it contains another security fixes.

I'm merging the 5.1 branch to 5.x after every release. Here is the latest one: https://github.com/mautic/mautic/pull/14129

**Comment by RCheesley** [comment]
> I'm merging the 5.1 branch to 5.x after every release. Here is the latest one: #14129

Ah I think I was confused because I was thinking that the security release will be on the 5.1 branch, but this PR is on the 5.x branch. Guessing that it'll go out with 5.2 instead?

**Comment by escopecz** [comment]
Yes, this will go out with 5.2. There won't be any new release for 5.1, right? The next security release will on top of the 5.2 release. That's how I understand the plan https://www.mautic.org/blog/community/introducing-mautics-new-release-strategy-long-term-support-elts

**Pull request merged**
