### PR TITLE
Fix campaign event for condition "Contact field value" with utm source

### PR DESCRIPTION
**Pull request by rohitpavaskar**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | Y
| Related user documentation PR URL | N/A
| Related developer documentation PR URL | N/A 
| Issues addressed (#s or URLs) | N/A
| BC breaks? | N/A
| Deprecations? | N/A

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
While executing a campaign with condition "Contact field value" and choosen contact field as "UTM Source" we are getting following error when campaign is executing:
```
CustomFieldHelper.php line 60:
  Type error: Argument 1 passed to Mautic\LeadBundle\Helper\CustomFieldHelper  
  ::fieldValueTransfomer() must be of the type array, null given
```

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a campaign with segment as a source.
2. Add condition "Contact field value" and choose contact field as "UTM Source".
3. Add contact which will get added to Campaign's source segment.
4. On campaign execution you will get error In 
```
CustomFieldHelper.php line 60:
  Type error: Argument 1 passed to Mautic\LeadBundle\Helper\CustomFieldHelper  
  ::fieldValueTransfomer() must be of the type array, null given
```

#### Steps to test this PR:
1. Create a campaign with segment as a source.
2. Add condition "Contact field value" and choose contact field as "UTM Source".
3. Add contact which will get added to Campaign's source segment.
4. Campaign should execute successfully.

#### Other areas of Mautic that may be affected by the change:
1. Campaign event execution

#### List deprecations along with the new alternative:
1. N/A

#### List backwards compatibility breaks:
1. N/A

### CODE REVIEW

**Comment by RaianHN** [comment]
https://forum.mautic.org/t/mautic-campaign-doesnot-work/19628

**Comment by RCheesley** [comment]
Thanks for the PR @rohitpavaskar !

**Review by kuzmany — APPROVED** [review]
Works 👍

**Review by npracht — APPROVED** [review]
Before applying patch:

```
[2021-07-14 06:32:00] mautic.NOTICE: TypeError: Argument 1 passed to Mautic\LeadBundle\Helper\CustomFieldHelper::fieldValueTransfomer() must be of the type array, null given, called in /var/www/html/app/bundles/LeadBundle/EventListener/CampaignSubscriber.php on line 507 (uncaught exception) at /var/www/html/app/bundles/LeadBundle/Helper/CustomFieldHelper.php line 60 while running console command `mautic:campaigns:trigger` [] []
[2021-07-14 06:32:00] mautic.WARNING: Command `mautic:campaigns:trigger` exited with status code 1 [] []
```

After applying patch it's all good 🚀

**Comment by RCheesley** [comment]
@all-contributors please add @rohitpavaskar for code

**Pull request merged**
