### PR TITLE
Prevented constraint issue that affected some users when upgrading from older versions of Mautic

### LINKED ISSUE #1019: I install the first version of mautic 1.0
and launch the update process and everytime I get one error:

image

There is nothing in the log

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**

It seems that some users are hitting a constraint issue due to a schema change with the forms table resulting in the following error:

Migration 20150724000000 failed during Execution. Error An exception occurred while executing 'ALTER TABLE form_fields CHANGE form_id form_id INT NOT NULL':

SQLSTATE[HY000]: General error: 1832 Cannot change column 'form_id': used in a foreign key constraint 'FK_7C0B37265FF69B7D'

[Doctrine\DBAL\DBALException]
An exception occurred while executing 'ALTER TABLE form_fields CHANGE form_id form_id INT NOT NULL':
SQLSTATE[HY000]: General error: 1832 Cannot change column 'form_id': used in a foreign key constraint 'FK_7C0B37265FF69B7D'

[PDOException]
SQLSTATE[HY000]: General error: 1832 Cannot change column 'form_id': used in a foreign key constraint 'FK_7C0B37265FF69B7D'

This PR attempts to fix that by dropping and re-adding the constraint.

It also likely fixes #1019.

**Testing**
Not totally for sure as it doesn't seem to happen to everyone.  But at least try to upgrade from a 1.1.3 installation that has some forms.

### CODE REVIEW

**Comment by escopecz** [comment]
I'm not sure how can I test update from 1.1.3 with the latest code in this PR. Is there some trick for it?

**Comment by escopecz** [comment]
I tried to checkout to the 1.1.3 tag, install Mautic like that and then applied this PR.

`doctrine:schema:update --force` ends up with
```
  [Doctrine\DBAL\DBALException]                                                                   
  An exception occurred while executing 'CREATE UNIQUE INDEX unique_bundle ON plugins (bundle)':  
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "unique_bundle" already exists             
  [PDOException]                                                                       
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "unique_bundle" already exists 
```
and `doctrine:migration:migrate` ends up with
```
Migration 20150724000000 failed during Execution. Error An exception occurred while executing 'ALTER TABLE form_fields DROP CONSTRAINT ':

SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at end of input
LINE 1: ALTER TABLE form_fields DROP CONSTRAINT 
                                                ^
  [Doctrine\DBAL\DBALException]                                                      
  An exception occurred while executing 'ALTER TABLE form_fields DROP CONSTRAINT ':  
  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at end of input              
  LINE 1: ALTER TABLE form_fields DROP CONSTRAINT                                    
                                                  ^                                  
  [PDOException]                                                         
  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at end of input  
  LINE 1: ALTER TABLE form_fields DROP CONSTRAINT                        
                                                  ^   
```

**Comment by alanhartless** [comment]
Is this with postgres? I think the unique_bundle issue was something we hit way back when and it's an issue with postgres and doctrine.  Do you have the addons table in there still?  Wondering if it's picking up the index from it since postgres requires that index names be unique across all tables in the database.

Can you look at your form_fields table and post what the name of the foreign constraint is? Seems it's not finding it leading to the sql error.

**Comment by escopecz** [comment]
Yes, I tested it with Postgres. Addons table is there still. Constraint name in the form_fields table is `fk_7c0b37265ff69b7d`

**Comment by alanhartless** [comment]
Found the problem and another Postgres related issue.  I hate PgAdmin BTW :-P

**Comment by escopecz** [comment]
Migrations were executed successfully, but `doctrine:schema:update --force` still throws
```
[Doctrine\DBAL\DBALException]                                                                   
  An exception occurred while executing 'CREATE UNIQUE INDEX unique_bundle ON plugins (bundle)':  
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "unique_bundle" already exists   
```

**Comment by alanhartless** [comment]
After the migrations ran, do you still have the addons table? Do you have multiple installations in the same database separated by a prefix?

**Comment by escopecz** [comment]
Yes, there is still addons table present. No, I don't have multiple installations in the same database. I selected to not backup old tables during installation. No prefix was used.

**Comment by alanhartless** [comment]
If the addons table is still present, you're going to get that error because Postgres only allows a unique index name across all bundles.  Just dump the addons table.  In the prod environment, the addons table would have been renamed to plugins by the upgrade processes.  That may have not happened in the dev environment if you used `doctrine:schema:update

**Comment by escopecz** [comment]
If I try to delete the addons table manually (via PG admin), it throws:
```
ERROR:  cannot drop table addons because other objects depend on it
DETAIL:  constraint fk_b15ae74ccc642678 on table addon_integration_settings depends on table addons
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```
So I had to drop addon_integration_settings first. Then the `doctrine:schema:update --force` command works. :+1:

**Pull request merged**
