### PR TITLE
Add support for relative dates to campaign action - update contact 

### LINKED ISSUE #6080: issue in campaign builder with action update contact
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
In the campaign builder, you add the action "update contact" to update a "date" contact field, there is an issue if you use the word "today" on this date field. All contacts will have this field updated with the date the day you set and saved this option. (not the actual today date).

For example, when I added this action on the campaign, I filled the date filed with "today" (when I did that it was 2018-05-11.
I go through the campaign today (2018-05-14). When the campaign is done, this field has been updated for my contact with the date of 2018-05-11 and not 2018-05-14.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Create a date field
2. Create a campaign and add the action "update contact".
3. Update this date field with "today"
image
4. Click on update.
5. Go back on this action to check it. It is not filled with "today" but with the date of today
image
6. That means if 2 weeks later, a contact goes through this campaign, this field will be updated with the date 2018-05-14 and not with the date in 2 weeks.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Yes
| Automated tests included? |
| Related user documentation PR URL | https://github.com/mautic/mautic-documentation/pull/132
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | fixes https://github.com/mautic/mautic/issues/6080
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR added support for relative dates in contact update campaign condition You are able to set -5 days or +1 day to any date field to update.

For devs:

This PR added new option `ignore_date_type `(https://github.com/mautic/mautic/pull/6126/files#diff-18ab1b8c93013f1e1d5134f39010ac2aR132) to use form date field without transform date on save.

#### Steps to test this PR:
1. Create custom date field 
2. Create campaign action Update contact
3. Set today, +1 day or date 
4. Create condition with custom date field and set conditon  with relative date (less then -1 day)
5. Check if contact was update and condition works properly during the mautic campaign trigger action 
`php app/console m:c:t`

Update contact action
image

Contact conditon

image

### CODE REVIEW

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by Arsur** [comment]
Can somebody test this? I would love to use this feature, but have not system system to test this at the moment

**Comment by kuzmany** [comment]
@Arsur you can test it here: https://mautibox.com/6126

**Comment by Arsur** [comment]
okay i tested this and it works for me

**Comment by Mindbowser** [comment]
Any idea when this will be released?

**Comment by regevbr** [comment]
Any idea when this will be released?

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@kuzmany a couple of conflicts to resolve on this one

**Comment by kuzmany** [comment]
Resolved conflicts and rebased

**Comment by RCheesley** [comment]
@kuzmany could you rebase this on staging please?  Thanks!

**Comment by kuzmany** [comment]
@RCheesley There are not commits to rebase against staging. What do you mean?

**Comment by RCheesley** [comment]
https://github.com/mautic/mautic/pull/6126#issuecomment-660186302 this is picking up files which are not in your PR. Our experience has been that this is because the PR is not up to date with the staging branch.

**Review by RCheesley — DISMISSED** [review]
This PR had my brain doing somersaults trying to understand the less than negative date value side of things .. yay for dyscalculia!

Here's what I found when testing

Campaign setup:

Edit Campaign _ Mautic

Contact post-campaign:

screenshot-local mautic3-2020 08 14-15_04_53

Date correctly set to be today, and the tag applied is from the 'no' route.

Setting the custom field to be +2 day results in the field being correctly set:

screenshot-local mautic3-2020 08 14-15_13_03

So, I think this is doing what it's supposed to, mental gymnastics aside!

**Comment by RCheesley** [comment]
@cla-bot check

**Review by adiux — DISMISSED** [review]
From an end-user point of view I can approve this PR. Does what it says in the "how to test this pr" section.

**Comment by RCheesley** [comment]
@kuzmany looks like there is a conflict to address and then we should be able to merge this.

**Comment by kuzmany** [comment]
Conflicts resolved + added unit tests

**Pull request merged**
