### PR TITLE
TPROD-454, TPROD-449, TPROD-454 Remove Doctrine Deprecation 

### PR DESCRIPTION
**Pull request by lenonleite**
Problem details

- https://mautic.atlassian.net/browse/TPROD-454
- https://mautic.atlassian.net/browse/TPROD-449
- https://mautic.atlassian.net/browse/TPROD-454

Changing deprecated methods like

- exec
- executeUpdate
- execute

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Review by mabumusa1 — APPROVED** [review]
Ready to go

**Review by escopecz — APPROVED** [review]
Looks correct 👍

**Comment by mabumusa1** [comment]
@allcontributors please add @lenonleite for code

**Comment by lenonleite** [comment]
Yeahhh, 
\o
o/
\o

**Pull request merged**
