### PR TITLE
Inject a caching solution into the DeviceDetector

### PR DESCRIPTION
**Pull request by nick-vanpraet**
#### Description:

While load testing a Mautic installation's page tracking capabilities (POST to /mtc/event), when the server came under a heavy load we found that determining what device was being used took up more than half the request time (2+ seconds).

DeviceDetector::parseDevice was found to be the culprit, specifically the Spyc::loadWith methods. We saw that this part of the code was cache-ready, but no cache was ever injected so it fell back on a StaticCache.

AbstractDeviceParser::getRegexes() specifically is cache ready:

```php
    /**
     * Returns the result of the parsed yml file defined in $fixtureFile
     *
     * @return array
     */
    protected function getRegexes(): array
    {
        if (empty($this->regexList)) {
            $cacheKey        = 'DeviceDetector-' . DeviceDetector::VERSION . 'regexes-' . $this->getName();
            $cacheKey        = (string) \preg_replace('/([^a-z0-9_-]+)/i', '', $cacheKey);
            $this->regexList = $this->getCache()->fetch($cacheKey);

            if (empty($this->regexList)) {
                $this->regexList = $this->getYamlParser()->parseFile(
                    $this->getRegexesDirectory() . DIRECTORY_SEPARATOR . $this->fixtureFile
                );
                $this->getCache()->save($cacheKey, $this->regexList);
            }
        }

        return $this->regexList;
    }
```

By injecting a cache in the DeviceDetectorFactory, this bit of code now caches its getRegexes() across requests and we saw this bottleneck which took 2+ seconds disappear under a heavy load scenario.

#### Steps to test this PR:

Using your stress testing tool of choice, send too many POST calls to /mtc/event.
Using NewRelic you can inspect the trace of the calls that are timing out and see that the getRegexes() code is bottlenecking.

image

Apply this patch, then test again and the bottleneck disappears.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10665"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for the PR @nick-vanpraet - could you take a look at your git config and ensure the email you use to sign your commits is on your GitHub profile? It doesn't have to be the default but it does need to be present in order for our CLA bot to pick it up. 

Once that's fixed you'll need to sign the contributors agreement (which you can do online with Docusign): https://www.mautic.org/contributor-agreement

**Review by kuzmany — DISMISSED** [review]
Code looks legit.
Device was tracked.
Good catch 👍

**Review by escopecz — DISMISSED** [review]
The code looks good and implements the cache according to the docs:

https://github.com/matomo-org/device-detector#caching

**Comment by escopecz** [comment]
@nick-vanpraet could you please look into the failing test?
```
1) Mautic\LeadBundle\Tests\Tracker\DeviceTrackerTest::testDeviceCreatedByUserAgent
Symfony\Component\Cache\Exception\InvalidArgumentException: Requested cache adapter "" is not available

/home/runner/work/mautic/mautic/app/bundles/CacheBundle/Cache/CacheProvider.php:54
/home/runner/work/mautic/mautic/app/bundles/LeadBundle/Tracker/Factory/DeviceDetectorFactory/DeviceDetectorFactory.php:40
/home/runner/work/mautic/mautic/app/bundles/LeadBundle/Tracker/DeviceTracker.php:83
/home/runner/work/mautic/mautic/app/bundles/LeadBundle/Tests/Tracker/DeviceTrackerTest.php:82
phpvfscomposer:///home/runner/work/mautic/mautic/vendor/phpunit/phpunit/phpunit:60
```

**Comment by RCheesley** [comment]
@all-contributors please add @nick-vanpraet for code

**Pull request merged**
