### PR TITLE
fix: Trying to access array offset on value of type null in dynamicCo…

### PR DESCRIPTION
**Pull request by adiux**
Fixes a small bug that I think is only visible in the logs:
```
Symfony\Component\Debug\Exception\ContextErrorException: PHP Notice - Trying to access array offset on value of type null

/app/bundles/EmailBundle/Views/FormTheme/Email/_emailform_dynamicContent_entry_filters_entry_filters_entry_widget.html.php:14
```
#### Steps to test this PR:
1. Code review only

### CODE REVIEW

**Comment by RCheesley** [comment]
I had thought that this was fixed by a PR that we merged in the 4.0 alpha release but maybe we missed it! How are you seeing this message, is it when you are creating a new email?

**Comment by adiux** [comment]
yes, when I create a new email. I branched of features

**Review by escopecz — APPROVED** [review]
This small code change is good to go 👍

**Review by dennisameling — APPROVED** [review]

**Comment by RCheesley** [comment]
I believe the code coverage report to be inaccurate as it does not relate to the file that this PR is changing, so going to go ahead and merge this one.

**Pull request merged**
