### PR TITLE
[UX] Change Published to Available for use (Dynamic content)

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This change updates the label from ‘Published’ to ‘Available for Use’ for dynamic content settings. This terminology shift better reflects the actual status of the content, indicating that it is ready for deployment rather than simply being in a published state. This enhancement promotes a clearer understanding of content status, aiding users in managing their dynamic content more effectively.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Dynamic Content
3. Create new
4. Look at the new label

image

### CODE REVIEW

**Review by LordRembo — APPROVED** [review]
Code wise it looks fine. Makes sense to me as well but let's see what Mike and other UX minded people think of it.

**Comment by andersonjeccel** [comment]
@code5rick Come here pls

**Comment by code5rick** [comment]
Interesting approach indeed 🤔

Using "Publish" and "Unpublished" is effective for campaigns or emails. Even WordPress employs this system for pages and articles. However, when it comes to dynamic content, I am uncertain about its suitability. I would need to conduct **further study** before reaching my conclusion.

From the top of my mind, if we use "Publish" and "Unpublished" for every feature to maintain coherence and practicality, we should keep it as it is.

Every idea has potential, it's all about how it serves its purpose.

**Comment by andersonjeccel** [comment]
@code5rick Check our studies and research on the other PRs regarding this topic

Also is valid to give a try on GitHub using the 5.x branch, Published/Unpublish is being redefined on different resources 😉👌🏻

**Comment by Mike-Dropsolid** [comment]
@andersonjeccel Will you also change the documentation and make sure it's clear for the developers as well? In code/API it will remain "Publish", which makes most sense on that side.

**Comment by andersonjeccel** [comment]
@Mike-Dropsolid Content team was already using Available for use on docs

image

I'll remove the publish and unpulish words

Dev docs OK

**Comment by andersonjeccel** [comment]
@Mike-Dropsolid @LordRembo Docs OK
https://github.com/mautic/user-documentation/pull/252

**Comment by LordRembo** [comment]
@andersonjeccel You also made some changes to that docs, that are out of scope. Eg. replacing 'cog icon' with 'list items icon'. I'll put some remarks in there but that really needs to be removed.

**Comment by andersonjeccel** [comment]
@LordRembo Probably created a new branch based on the one I was editing for the cog PR
Reordered and undid the commit, thanks for pointing, I'll review twice next time

**Comment by RCheesley** [comment]
Closing this PR as it seems @andersonjeccel needs to make a new one from the comments above? If not let us know and we can move it from draft when it's ready to go.

**Pull request closed without merging**
