### PR TITLE
Grid Addition and Change in Connectors

### PR DESCRIPTION
**Pull request by moskoweb**
| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | N
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/5863
| BC breaks? | 
| Deprecations? | 

#### Description:
Implementation of the Grid system in the Campaign Builder to facilitate the organization.

Inserting icons in the upper right buttons.

And modification of the standard connector, for the style of Flowchart.

#### Steps to test this PR:
1. Clear cache from Mautic.
2. Regenerate assets by console.
3. Open Campaign Builder.

### CODE REVIEW

**Comment by luizeof** [comment]
@moskoweb great work!

to test this feature we need to regenerate assets?

**Comment by dbhurley** [comment]
This is awesome, it's not quite like the version you showed in the Fb group. Can you update this PR to match? I think it's a great contribution.

**Comment by moskoweb** [comment]
Yes @luizeof, need to regenerate from the console: php app/console mautic:assets:generate

**Comment by moskoweb** [comment]
@dbhurley thought of doing a crowdfunding to at least generate a return of time invested in the production of personalization.

Besides that I have identified some small bugs, that changing in the Campaign Builder does not cause a problem, but in the preview it breaks the visual.

**Comment by moskoweb** [comment]
Yes, I understand your point of view, @dbhurley.

But as it was a development for something of its own, I had not thought about marketing and also not passing the community.

But for the beauty to finish, I wanted to share with the Group.

Some people are already giving me some money, so I'll be adding it to the PR soon.

**Comment by dbhurley** [comment]
I hope you understand how excited I am to see your contributions and hope for many more to come in the future. And I am confident you will be rewarded for your time. Your expertise as a developer will be evident! Keep up the great work!

**Comment by npracht** [comment]
Label: Enhancement

**Pull request closed without merging**
