### PR TITLE
Fix send unpublished reports

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
We noticed unpublished reports send on schedule.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:

1. Create a report
2. Go in the "calendar" tab in the edit page
3. Activate the option and set it on a daily basis to receive the email as soon as possible.
4. Save the report WITHOUT publishing it.
5. Wait the day after and see that you receive the report email.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat all steps to reproduce

### CODE REVIEW

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebased

**Comment by RCheesley** [comment]
Close & reopen for Scrutinizer

**Review by dennisameling — APPROVED** [review]
Works as described. To test this PR quickly, make sure you do the following:
- Follow the PR steps
- Change your system time to tomorrow
- Run `bin/console mautic:reports:scheduler` to force generate the report(s)
- Don't forget to change your system date back to today 😉 

The PR was also missing a test for the new case that checks for `$report->isPublished()`, took the liberty to add the test 😊

**Review by RCheesley — APPROVED** [review]
Confirmed the bug, wrongly received the unpublished report.

After the patch the unpublished report was no longer sent :tada:

**Pull request merged**
