### PR TITLE
Delete pane:split-right

### PR DESCRIPTION
**Pull request by MaxWebmecanik**
This file appeared out of nowhere.
I think it was created by a text editor (probably Atom)

### CODE REVIEW

**Comment by escopecz** [comment]
:+1:

**Comment by dbhurley** [comment]
I accept the blame. That's totally my fault. I have been experimenting with Atom for my IDE. 😞

**Comment by alanhartless** [comment]
Let's add the file to the repo's .gitignore and it should be all good. We may have to do something to keep it from being tracked now that's it's part of the history - I can't remember how that's done but I know it's possible.

**Comment by MaxWebmecanik** [comment]
@dbhurley No problem! I personally love Atom :star: ! No harm done :smile:

**Comment by MaxWebmecanik** [comment]
@alanhartless I don't really think adding it to the gitignore is necessary... This is more of a glitch on Atom's side. It could've had another unpredictable name. Up to you.

**Comment by alanhartless** [comment]
Ok gotcha. Yea if it's a one off, not a big deal. Never used Atom :-) PhpStorm fan boy here :-)

**Comment by MaxWebmecanik** [comment]
@alanhartless I'm also a big fan of what JetBrain does but PhpStorm isn't free :disappointed:

**Comment by alanhartless** [comment]
+1

**Pull request merged**
