### PR TITLE
Re-enable rector

### PR DESCRIPTION
**Pull request by tejasync**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
https://mautic.slack.com/archives/CQMKV0RU1/p1621067730217100

#### ToDo:
- [x] verify if rector skip options are required anymore?
- [x] find alternatives for missing dependencies (in rector v0.11.0) e.g. RemoveUnusedParameterRector, RemoveDefaultArgumentValueRector, RemoveUnusedDoctrineEntityMethodAndPropertyRector, RemoveUnusedClassConstantRector, RemoveDeadRecursiveClassMethodRector

#### Notes:
rector/rector v0.11.0 requires max phpstan/phpstan v0.12.86.

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for making a start on this @ts-navghane !

**Comment by escopecz** [comment]
I had a hard time installing Rector. Described in https://github.com/rectorphp/rector/issues/6564

Now we have both Rector and Phpstan installed as dev-dependencies. I also found a rule that is working with our code base and the rule `RemoveAlwaysTrueIfConditionRector` is making some changes, so I'd uncomment that in another PR once we merge this one. Then we can continue adding more rules from https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#deadcode

**Comment by escopecz** [comment]
@RCheesley @dennisameling we are good on this PR. I'd add new rules in the future PRs so this one is only about re-enabling. It is now running on GitHub Actions again, so we know this is good to go, just make a code review.

**Comment by RCheesley** [comment]
Wonderful - thanks so much for all your work on this @escopecz - sounds like it has been quite a challenge!

**Review by kuzmany — APPROVED** [review]
Looks nice. 
I am really looking forward to more integration of Rector..

👍

**Comment by dennisameling** [comment]
Thanks so much @ts-navghane and @escopecz! When I tried this months ago it was an absolute nightmare with a bunch of incompatible dependencies etc. - great to see the dependency issue is gone, now that Rector is standalone 🚀 Also the massive PHPSTAN bump from `0.12.25` to `0.12.92` is impressive and very welcome (also for PHP 8 support)!

**Pull request merged**
