### PR TITLE
4.0  to 4.x merge

### PR DESCRIPTION
**Pull request by RCheesley**
PR to bring across the changes from 4.0 to 4.x branches.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10628"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
Some PHPSTAN things to address here @escopecz - assume these were merged before the level was increased.

**Comment by RCheesley** [comment]
Fired this up on Gitpod and all seems to be well. Just need to fix the PHPSTAN errors before merging :)

**Comment by escopecz** [comment]
I re-generated the PHPSTAN baseline in this case as this is a merge PR and I don't want to make unnecessary changes to it.

Command used:
```
$ bin/phpstan clear-result-cache && php -d memory_limit=4G bin/phpstan analyse --generate-baseline
Note: Using configuration file /var/www/html/phpstan.neon.
Result cache cleared from directory:
/tmp/phpstan
Note: Using configuration file /var/www/html/phpstan.neon.
 3083/3083 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
 [OK] Baseline generated with 20911 errors.
```

**Review by escopecz — APPROVED** [review]
I see no issue. Thanks Ruth!

**Comment by RCheesley** [comment]
Awesome, thank you @escopecz

**Pull request merged**
