### PR TITLE
[UI] Increased icon size

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR increases the icons size in tables.

| Before                                 | After
| -------------------------------------- | ---
|   image                                     | image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Segments > Create new > Save & Close > Back to the list > see

### CODE REVIEW

**Comment by abhisekmazumdar** [comment]
The icons have been tested locally and are now fairly large, appearing visually appealing:

Before:
image


After:
image

**Review by abhisekmazumdar — APPROVED** [review]

**Comment by andersonjeccel** [comment]
@abhisekmazumdar Should I make it smaller? 1px perhaps to find a mid-term, what do you think?

**Comment by abhisekmazumdar** [comment]
I feel it should match the size of the text. Maybe
But I understand that the icon's font sizing is different.

I will wait for more inputs from the community.

**Review by shinde-rahul — APPROVED** [review]
LGTM!!!

**Comment by escopecz** [comment]
@andersonjeccel please do not fill the milestone. It will be filled once the PR is being merged. Also, this is an enhancement and so it cannot go to a bug-fix-only releases.

**Comment by andersonjeccel** [comment]
@escopecz I'm confused, isn't 5.1.x (eg 5.1.1) for bug fixes and 5.2 for new features/enhancements?

**Comment by escopecz** [comment]
Oh, you got that right and I was wrong. 5.2 is for features and enhancements.

**Review by LordRembo — APPROVED** [review]
I'm all for it, bigger icons works better.

**Pull request merged**
