### PR TITLE
Channel web push

### PR DESCRIPTION
**Pull request by dongilbert**
Please answer the following questions:

| Q             | A
| ------------- | ---
| Bug fix?      | N
| New feature?  | Y
| BC breaks?    | N
| Deprecations? | N
| Fixed issues  |  N/A

## Description

New Web Push Channel

## Steps to Test

In order to test this, your mautic install must be on an HTTPS host, otherwise you cannot use web notifications (web push requires that the pushing website be https for security, and since your mautic install is the pusher, you have to have it be https). 

For those wanting to test, we've set up an environment at dev.mautic.com. You can get the login credentials from the mautic slack chat #engineering channel. 

If you simply want to test that you're able to receive notifications, I've already setup a notification campaign that will send you a push notification when you fill out the contact form found at http://dbhurley.com/contact AFTER you've subscribed. To test, you can navigate to that page, then click the "(or web notifications)" text in the sidebar. It will open a popup window (be sure not to block it) that will ask you to subscribe to web push notifications. Say allow, then close the window. Then you may fill out the contact form on that page, and you should soon receive a web push notification from your browser.

### CODE REVIEW

**Comment by alanhartless** [comment]
Don't worry about this conflict, Don. I'll get it with my PR for migrations.

**Comment by alanhartless** [comment]
Turns out Mautic does automatically load asset subfolders leading to the popup assets interfering with Mautic's layout (link colors were changed, etc).

I submitted https://github.com/dongilbert/mautic/pull/8 against this branch to limit the directories Mautic loads. This should not be a BC break for plugins since they are required to load their own assets.

**Comment by escopecz** [comment]
I applied this PR, cleared cache, run migrations and this error showed up:
```
[Doctrine\ORM\Mapping\MappingException]                                                                                        
  No identifier/primary key specified for Entity "Mautic\PageBundle\Entity\Trackable". Every Entity must have an identifier/primary key.   
```

**Comment by alanhartless** [comment]
Whoops; that wasn't supposed to make it into this branch :-)  I removed it in https://github.com/dongilbert/mautic/pull/8 for when it gets merged.

**Comment by alanhartless** [comment]
@dongilbert One more to disable the filter and category till implemented. https://github.com/dongilbert/mautic/pull/9

**Comment by npracht** [comment]
Hi @dongilbert,

Would it be possible to have a [documentation](https://github.com/mautic/documentation/pulls) for that feature. It seems great but for a non-coder, it's hard to manage.
Thanks a lot,

N.

**Comment by martinstr** [comment]
@dongilbert we have set it up and got it to work except that mautic won't send the push notifications from the campaigns. So a document would help a lot here.

**Comment by dongilbert** [comment]
@npracht & @martinstr I'll be adding the docs for this today and ping you on slack when that happens. Sorry for the delay.

**Comment by martinstr** [comment]
awesome thanks  @dongilbert ☺️

**Comment by martinstr** [comment]
How is it going with the documentation? @dongilbert

**Pull request merged**
