### PR TITLE
Update of the country name of Swaziland to Eswatini

### PR DESCRIPTION
**Pull request by AlanWierzchonCA**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [yes ]
| New feature/enhancement? (use the a.x branch)      | [ no]
| Deprecations?                          | [ no]
| BC breaks? (use the c.x branch)        | [yes ]
| Automated tests included?              | [ no] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR is rebased to 5.x PR https://github.com/mautic/mautic/pull/10954
and its update of the country name of Swaziland to Eswatini

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by AlanWierzchonCA** [comment]
Hi,
there is one unit test failure that is not related to these changes.

Best,
Alan

**Review by jos0405 — CHANGES_REQUESTED** [review]
Sorry to be a pain in the rear, but the list is not alphabetical:

image

**Comment by RCheesley** [comment]
@AlanWierzchonCA please see the feedback above!

**Comment by AlanWierzchonCA** [comment]
Hi @jos0405,
I corrected the alphabetical order of the list of countries

Best,
Alan

**Review by RCheesley — DISMISSED** [review]
Good catch with the ordering, confirm it works as expected now! 🚀

**Pull request merged**
