### PR TITLE
Fixes cloned email stats and drops unused column

### LINKED ISSUE #218: Cloning email also clones the origin email's read count
https://www.evernote.com/shard/s42/sh/6ed47c42-78a0-4496-9008-16b6cb983294/5066a146588147c2a9bb137cdffd97cf/deep/0/Mautic.png

The cloned email should not have any of the stats from the email from which it was cloned.

### PR DESCRIPTION
**Pull request by alanhartless**
This fixes #218. It also dropped readInBrowser from the email table which is not used and likely mistakenly added in place of \Mautic\EmailBundle\Entity\Stat::$viewedInBrowser. Run `php app/console doctrine:schema:update --force` to apply the changes. (The queries will need to be added to a migration file once included in a new release).

### CODE REVIEW

**Comment by escopecz** [comment]
### Testing steps

1. Created new Email
2. Sent to some leads to create some stats
3. Clone the email with stats

### Result before applying this PR
Sent is zero, but Read and Pending count are cloned from the source email as well. Pending is even raised from ~1 to ~2

### Result after applying this PR
Sent is zero, Read is zero, but Pending is still becoming ~2. 
@alanhartless Does Pending should be ~2? If yes, it can be merged.

**Comment by alanhartless** [comment]
@escopecz Pending should be based on the leads belonging to the associated lists that have not received the email yet. So for cloned emails, since it is new, pending should be the number of leads in all the associated lists. That's probably why it went from 1 to 2.

**Comment by escopecz** [comment]
When I look at email table today, all emails, cloned and original, has pending ~0. Not sure what happened since then.

**Comment by alanhartless** [comment]
Couple things to check.  Check to see if you still have leads in the lists. If so, did you send the email (so the sent counts should be up) so that Mautic thinks the email has already been sent to the leads?

**Comment by escopecz** [comment]
I made a second test. The pending is again not zero.
mautic-email-clone

**Comment by alanhartless** [comment]
That should be correct as the cloned email has not been sent to the leads yet.

**Comment by escopecz** [comment]
In that case, I'll merge it.

**Pull request merged**
