### PR TITLE
[UI] Improvements for notes

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

fixing the messy notes interface that's been bugging users for months. larger text, better organization, and cleaner design make it easier to read and manage notes. 

Specifically:
- Increases the font size
- Reorders the sequence of information
- Fixes layout bugs
- Changes icons to better express each note category
- Removes a lot of custom code

frequent note-takers will enjoy a more intuitive experience. these changes should boost productivity and reduce eye strain for everyone who relies on notes daily. a small update with big impact on usability.

It seems like we had a bug the last time a PR was merged, some classes in utilities didn't join the app.css file

| Before                                 | After
| -------------------------------------- | ---
|  image                                      | image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Contacts
3. Create new
4. Save & Close
5. Go to the Notes tab
6. Add a note for each category
7. See

### CODE REVIEW

**Comment by shinde-rahul** [comment]
@andersonjeccel,
The note icon and the note body have an extra gap. I see it as representing different things than the note itself.

Screenshot 2024-07-06 at 7 52 32 AM

Suggestion: Can we do something on similar line? (The better one, following version is to just illustrate)
Screenshot 2024-07-06 at 8 00 37 AM

**Comment by andersonjeccel** [comment]
@shinde-rahul Nice idea, how would you do it in CSS?
I’m having an issue with enforced display rules that just don’t allow me to change where it’s aligned to using flex utilities

_(I’m assuming you changed the css quickly to create this preview)_

**Comment by shinde-rahul** [comment]
@andersonjeccel, The following are the changes I made,
```css
.notes > .note-single [class*=" icon"] .icon-wrapper,
.notes > .note-single [class^="icon"] .icon-wrapper {
	width: 50px;
    /* border-radius: 100px; */
    aspect-ratio: 1 / 1;
    background-color: var(--layer-alternate);
}

.notes > .note-single [class*=" icon"], 
.notes > .note-single [class^="icon"] {
    position: static;
    padding: 0;
    width: 4.9%;
}
```
This was the quick changes to preview.

**Comment by andersonjeccel** [comment]
@shinde-rahul Thanks! Changes addressed 😉

**Review by escopecz — APPROVED** [review]
Looks great and a bunch of code was removed at the same time. Love that!
Before:
Screenshot 2024-07-19 at 17 34 09


After:
Screenshot 2024-07-19 at 17 34 46


I found a problem that a note cannot be edited when freshly created or edited. But this issue exists in the 5.x branch already, so not a blocker for this PR.

**Review by shinde-rahul — APPROVED** [review]
Thanks @andersonjeccel.

**Pull request merged**
