### PR TITLE
Fix unsubscribe form

### PR DESCRIPTION
**Pull request by galvani**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | N
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )
#### Summary of the issue:

In testing, I got an "Oh dear" error page when clicking unsubscribe. This only happened when there was no preference center page attached to an email, and "Show contact preference settings" was set to Yes. Other preference options were set to Yes.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:

1. Set "Show contact preference settings" to yes
2. Create new template or segment email, with no Preference Center page
3. Send email to contact (through campaign/form or segment)
4. Click unsubscribe

#### Expected Results:

Default preference center page should appear (with styling from default theme)

#### Actual Results:

"Oh, dear" page appears

#### Steps to test this PR:

1. Load up this PR
2. Verify above is fixed
3. Verify preferences are stored

### CODE REVIEW

**Comment by RCheesley** [comment]
Test failed on on Mautibox, when I load up the preference screen (which works) for a contact who has received the email and clicked unsubscribe, and de-select email, there's a console error:

Uncaught TypeError: Cannot set property 'disabled' of null
    at togglePreferredChannel (5d56ac8d87596262698305:36)
    at HTMLInputElement.onclick (5d56ac8d87596262698305:60)

Hitting save, it reverts to being selected and no change appears to be made to the contact record.  Will test locally to see if it's an issue with the environment.

**Comment by galvani** [comment]
@RCheesley thanks, I will check it. It's very old, things might have changed.

**Comment by npracht** [comment]
@galvani any feedback ?

**Comment by npracht** [comment]
@galvani should we still consider that? Is it used in Acquia's production environment ?

**Comment by galvani** [comment]
@npracht hey, I am no longer part of the team. I wouldn't know what's the current state. Sry, m8

**Comment by npracht** [comment]
Oh @galvani didn't know. Thanks a lot !
@escopecz do you know who could carry that ?

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by npracht** [comment]
Hello @alanhartless could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback, i would very love to merge it in 3.0.1 if still relevant. Thanks !

**Comment by RCheesley** [comment]
@alanhartless @escopecz if one of the team can pick this up and address the conflicts we can look at getting this into one of the upcoming patch releases.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by npracht** [comment]
@mautic/acquia-po can someone fix this asap ? Otherwise i'll have to postpone from next release again. Thanks.

**Review by dennisameling — COMMENTED** [review]
I tried testing this PR, but can't seem to reproduce the issue. The default preference page is shown without errors:

image

When I checkout this PR, the screenshot is still the exact same as above.

I enabled "Show contact preference settings" as described in the PR:

image

"Preference center page" is empty as well on the email:

image

I think this PR is no longer relevant and can be closed. @RCheesley could you please cross-check before we close?

**Comment by escopecz** [comment]
@dennisameling I think you are right. When I view the changes after the rebase (which was quite difficult due to indentation changes of large HTML blocks) it looks like the changes that remain are only the indentation changes. I'm closing this.

**Pull request closed without merging**
