### PR TITLE
Fix bad date format.

### PR DESCRIPTION
**Pull request by giomasce**
Signed-off-by: Giovanni Mascellani <giovanni@mascellani.eu>

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Issue(s) addressed                     | Trivial typo, no need for an issue

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Notice how log message now have the correct date instead of showing the month in the place of the minutes

### CODE REVIEW

**Comment by RCheesley** [comment]
Hi @giomasce and thanks for making the PR!  As this is a bug fix I will change the base to 3.3 as that's where we work on bugs.  Can you please do a rebase to bring this in line with the latest changes? Thank you!

**Comment by giomasce** [comment]
Done, thank you @RCheesley.

**Comment by npracht** [comment]
Hi @giomasce can you please explain how to reproduce the issue (generate the log with wrong format) before applying this fix ?
Thanks

**Comment by giomasce** [comment]
Hi @npracht, you don't have to do much to trigger this issue: just setup a campaign with some timed event, enable `'debug' => true,` in `app/config/local.php` and then let a contact enter the campaign. As soon as a contact is scheduled for the timed event, this line will appear in the log:
```
Action ID# 69 for contact ID# 11755 has timing that is not appropriate and thus scheduled for 2021-07-31 02:38:03 UTC
```

Everything is correct, except for the format of the date printed in that line. My patches fixes this last detail.

**Review by kuzmany — DISMISSED** [review]
👍

**Review by npracht — DISMISSED** [review]
GTG 🚀

**Comment by RCheesley** [comment]
This one will need to be rebased to Features if we are to merge it due to the delay in getting it tested. I'll try to update the branch & pull in the changes 🤞

**Comment by RCheesley** [comment]
We will need to rebase the PR due to the conflicts - @giomasce could you take a look at that please? Once it's rebased assuming that all the tests pass, we are good to merge.

**Comment by giomasce** [comment]
Just rebased on top of `features`. Commit is still good for me.

**Pull request merged**
