### PR TITLE
Fix change date modified If last_active date change

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✅ 
| New feature/enhancement? (use the a.x branch)      | 
| Deprecations?                          | 
| BC breaks? (use the c.x branch)        | 
| Automated tests included?              | 
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:

If we change just last_active date during some action, also date_modified of contact  is changed. What does not make sense. Last activity date and date_modified date are different columns with different ways to use. 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Create email with link and send it
3. Copy tracked link from email
4. Open it in incognito window
5. Check contact profile probably in database and see like date_modified was changed. 
6. After PR is not chang, because we want update just last activity of the contact. His profile was not modified, then last_modified date should to be changed

### CODE REVIEW

**Review by mabumusa1 — APPROVED** [review]
This PR is good to go, code changes look good

**Comment by sdoering** [comment]
In my test both columns `last_active` and `date_modified` changed to the `last_active` timestamp:

image

**Review by volha-pivavarchyk — COMMENTED** [review]
Both `date_modified` and `last_modified` have been changed 
current:
image
5.x:
image

**Comment by kuzmany** [comment]
@volha-pivavarchyk after what action?

**Comment by volha-pivavarchyk** [comment]
@kuzmany After opening a tracked link in the incognito mode

**Comment by kuzmany** [comment]
@volha-pivavarchyk did you try it more times? Probably the first time also IP address is set, then the modified change is OK. We fixed it just If only the last_active date was changed from the contact profile, not the other data. 
Data modified change is OK If another value of the profile is changed.

**Comment by volha-pivavarchyk** [comment]
@kuzmany thanks. I'll try

**Review by volha-pivavarchyk — APPROVED** [review]
Works as described
image

**Comment by volha-pivavarchyk** [comment]
@kuzmany Thanks for the tip. I retested and succeeded. 

Works well

**Pull request merged**
