### PR TITLE
Checkbox validation fix

### PR DESCRIPTION
**Pull request by escopecz**
Fix for https://github.com/mautic/mautic/issues/536

### How to test
Create a form with required checkbox field. Add few options to it. The form should not be able to submit with some checkbox checked or without. This PR fixes it. It doesn't allow to submit unless at least one required checkbox is checked and allow it if some is checked.

### CODE REVIEW

**Comment by drmmr763** [comment]
Reproduced the error, PR fixes the issue as expected.

**Comment by alanhartless** [comment]
This breaks the radio groups which doesn't use [] in the name.  Firefox ignores the [] but validation breaks for radios instead :-)

**Comment by escopecz** [comment]
Thanks Alan. Radio groups validation should work as well as checkbox groups.

**Comment by natselection** [comment]
I tried the changes, cleared the app/prod files and the issue still exists for me.

**Comment by escopecz** [comment]
@natselection you have to be running Mautic in dev mode (index_dev.php). Also clear your browser cache.

**Pull request merged**
