### PR TITLE
Form Actions Unit Test

### PR DESCRIPTION
**Pull request by mqueme**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This will test form actions, callbacks and events to be dispatched
[//]: # ( As applicable: )

#### Steps to test this PR:
1. run the unit test

### CODE REVIEW

**Comment by escopecz** [comment]
@mqueme The tests are failing on `FormAbstractTest.php`. PHPUnit tries to run tests for every file ending with `*Test.php`. Rename it to `FormTestAbstract.php` for example and it will not fail on that.

**Comment by dongilbert** [comment]
As with the abstract naming, the tests that were written needed to have their class and file names changed as well so that PHPUnit would see them. When running `phpunit --filter FormBundle` from the app directory, only the `FormSubscriberTest` was executed. I updated the file and class names per PHPUnit requirements, and ran the test again, and got test failures. I pushed the changes, but the tests still need to be fixed @mqueme

**Comment by mqueme** [comment]
@dongilbert checking

**Comment by escopecz** [comment]
I don't see any issue now. Thank you both! 👍

**Comment by dongilbert** [comment]
+1 All tests pass now

**Pull request merged**
