### PR TITLE
Fix social login with automatic generate form html code

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/4511
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Issue related to https://github.com/mautic/mautic/issues/4511 
JS include in automatic generate form couldn't be executed because inline js with document.write cannot work https://github.com/mautic/mautic/blob/afb4da4491ac2f12e8500d504906bd20f8ff47ee/plugins/MauticSocialBundle/Views/Integration/login.html.php#L35
This PR put JS code to external js link. 

[//]: # ( As applicable: )
#### Steps to reproduce the bug:

1. Enable at least one social plugin
2. Create a Form with 2 fields First name and Social Login 
3. Place automatic  form html on your page
4. Visit Landing page
5. Click on the social icon.

#### Steps to test this PR:
1. Repeat all steps and don't forget rebuild form cache
2. See if social login work

### CODE REVIEW

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by npracht** [comment]
It works ! Thanks @kuzmany

**Comment by npracht** [comment]
Label: Pending Test Confirmation

**Comment by npracht** [comment]
Label: Ready to test

**Comment by kuzmany** [comment]
Should generate this JS dynamic, like mtc.js or feature request robots.txt https://github.com/mautic/mautic/pull/5669 .  JS could  extented by plugin and developers. But not budget at this moment :(

**Comment by escopecz** [comment]
It does not work for me. When I open the page with the form (JS embed) with the Social Login button (Twitter) I can see this JS error right away:
```
mauticformjs.html:1 Uncaught SyntaxError: Unexpected identifier
    at generate.js?id=197:1
(anonymous) @ generate.js?id=197:1
```
When I click the social login button I get this new error:
```
Uncaught ReferenceError: openOAuthWindow is not defined
    at HTMLAnchorElement.onclick (VM68 mauticformjs.html:7)
onclick @ VM68 mauticformjs.html:7
```
I cleared the cache, also run `app/console mautic:assets:generate` just to be sure. Testing on index_dev.php. Still throwing the same errors.

**Comment by kuzmany** [comment]
@escopecz I bet you didn't rebuild cache of form

image

**Comment by javjim-mautic** [comment]
Works properly

**Pull request merged**
