### PR TITLE
Do not query for object ID = 0

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.0 for bug fixes 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | /
| Related developer documentation PR URL | /
| Issue(s) addressed                     | /

#### Description:
We could see unnecessary query like this one:
```
SELECT * FROM mautic_sync_object_field_change_report f WHERE (f.integration = 'IntegrationA') AND (f.object_type = 'Mautic\\\\LeadBundle\\\\Entity\\\\Lead') AND (f.object_id = '0') ORDER BY f.modified_at ASC
```
It doesn't make sense to ask for object_id = 0 and we should return earilier.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Hard to do, you'd have to monitor SQL queries.

#### Steps to test this PR:
1. As there is no community CRM integration to test this with at the moment, please code review only.

#### Other areas of Mautic that may be affected by the change:
1. Any integration built on the IntegrationsBundle will be affected.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/9314"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
~~Note for myself: Depends on https://github.com/mautic-inc/mautic-cloud/pull/857~~

worked around it

**Comment by npracht** [comment]
@escopecz does it still have a sense ? What is behind acquia/mc-cs#857 ?

**Comment by escopecz** [comment]
@npracht yes it does. It improves performance. I think that's still wanted. It's waiting for internal mysterious PR called "Dispatch new events after syncing batches" by @alanhartless to port over to the community.

**Comment by npracht** [comment]
Ok cool, then we wait for the mysterious PR :)

**Comment by escopecz** [comment]
This PR is good to go. I removed the test that belong to another PR.

**Review by kuzmany — DISMISSED** [review]

**Review by kuzmany — APPROVED** [review]
👍

**Pull request merged**
