### PR TITLE
Fix integration variable twig issue

### PR DESCRIPTION
**Pull request by kuzmany**
This reverts commit 7e92049.

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴🟢
| Deprecations?                          | 🔴🟢
| BC breaks? (use the c.x branch)        | 🔴🟢
| Automated tests included?              | 🔴🟢 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This fix 

024-12-07T15:30:52.283677+00:00] mautic.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Neither the property "filter" nor one of the methods "filter()", "getfilter()"/"isfilter()"/"hasfilter()" or "_call()" exist and have public access in class "Symfony\Component\Form\FormView" ....

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Install any integration based on integration framework with mapping fields (for example https://github.com/Webmecanik/mautic-pipedrive-bundle)
3. Try open  plugin settings
4. After fix should work properly

### CODE REVIEW

**Comment by matbcvo** [comment]
Please rebase to the 5.2 branch instead of 5.x.

**Comment by kuzmany** [comment]
@matbcvo isn't 5x gonna merged to 5.2?

**Comment by matbcvo** [comment]
@kuzmany The 5.x branch is locked and no longer accepts new PRs. Because of this, PRs that fix bugs must target the 5.2 branch instead. Mautic 5.2.1 will be released based on the 5.2 branch.

**Comment by kuzmany** [comment]
@matbcvo rebased

**Review by escopecz — APPROVED** [review]
Yes, this the hyphen would cause issues like this 👍

**Pull request merged**
