### PR TITLE
Show "added through API" event log to timeline

### PR DESCRIPTION
**Pull request by dennisameling**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | TODO
| Related developer documentation PR URL | TODO
| Issue(s) addressed                     | N/A

#### Description:

~~⚠️ **NEEDS #7538 TO BE MERGED FIRST**~~ DONE ✅ 

Builds upon #7538. That PR adds entries to the `lead_event_log` table when a contact is created through the API. This PR shows those entries in the UI, so that the user can see that the contact was created with the API.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Go to https://reqbin.com/
3. Use this config (url = https://mautibox.com/9067/api/contacts/new, credentials: admin / mautic):
image
4. In the "content" tab, copy and paste this data:

```JSON
{
      "email": "demo@demo.com",
      "firstname": "testing",
      "lastname": "test"
}
```
5. Click "Send"
6. Go to contacts: https://mautibox.com/9067/s/contacts
7. When the contact is created, you'll now see an event "Added through API":

image

### CODE REVIEW

**Comment by npracht** [comment]
This is awesome

**Comment by dennisameling** [comment]
PR unblocked now that #7538 is merged. This still needs automated tests and docs, but the functionality is ready to test already 🚀

**Review by RCheesley — DISMISSED** [review]
Nice improvement to the UI, tested using postman and confirm that it shows the contact as being created via the API:

screenshot-local mautic3-2020 08 16-15_45_13 (1)

**Review by npracht — APPROVED** [review]
👍 this is a very nice improvement :)

**Pull request merged**
