### PR TITLE
Fix 10455: Allows to reopen the code edit modal after grapesjs has been closed

### LINKED ISSUE #10455: MJML email builder - "Edit Code" function is broken
### Mautic Version

4.0.0

### PHP version

7.4.23

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

This is kind of related to #10398 & #10396.

I tried out the fix described in the issues linked above, removing the set ID when changing a picture by accessing the "Edit Code" function to manually remove the ID I encountered an Issue that I was not able to open the builder after closing and saving the email.

It seems that once you manually made any edit using the "edit code" option, save the email and re-open it, you cannot access the "edit code" option anymore.

### How can we reproduce this issue?

1. Create a new email
2. Choose a template 
3. Open the Builder 
4. Open the "Edit Code" option to manually edit the MJML
5. Make any minor change to the MJML
6. Save your edit by clicking on "edit"
7. Close the email builder
8. Save and Close you Mail
9. Re-open the mail
10. Go to the builder
11. Try to open the "edit Code"
12. It won't open

### Relevant log output

```shell
No Logs
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### LINKED ISSUE #10556: Code Mode Issue
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

**Issue:**

If you have any template selected and load up the builder and click the button for code mode it opens the box up perfectly fine but if you exit the builder and select another template and reload the builder the code mode button now no longer works for ANY email template now.

**Video of issue:** https://www.loom.com/share/0c2475b73fae4fdaad39ec8c6aa6393e

**Workaround:**

I have noticed clearing your cache and cookies seems to fix the issue but breaks again when you go to another template and try to use code mode.

### How can we reproduce this issue?

Video: https://www.loom.com/share/0c2475b73fae4fdaad39ec8c6aa6393e

Step 1: Create a new email template

Step 2: Open Code Mode

Step 3: Close the builder and select another template

Step 4: Try and open Code Mode

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by adiux**
closes #10455

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | yes
| Deprecations?                          |  no
| BC breaks? (use the c.x branch)        | no
| Automated tests included?              | N/A
| Issue(s) addressed                     |  see new pr for 4.1: https://github.com/mautic/mautic/pull/10689

#### Description:

This fixes an issue where the code editor modal did not open **again** when the grapesjs builder was closed.

#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2. See steps in the [issue](https://github.com/mautic/mautic/issues/10455)

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10564"></a>

### CODE REVIEW

**Comment by donbowman** [comment]
this works for me

**Comment by RCheesley** [comment]
Could you please rebase this against the 4.x branch? Thanks!

**Review by RCheesley — APPROVED** [review]
Tested this in Gitpod and can confirm that the modal code-mode editor now works fine when you open it after previously opening code mode and then closing the builder. Thanks for the PR @adiux 🎉

**Comment by RCheesley** [comment]
@adiux we need to get this PR rebased please - then we just need a code review to merge.

**Comment by RCheesley** [comment]
@adiux please can you rebase this onto the 4.1 branch so we can merge with the upcoming release?

**Comment by adiux** [comment]
I was not able to rebase this in a sane way. In order to keep it clean I created a new branch and a new PR based off of 4.1

**Pull request closed without merging**
