### PR TITLE
Trackable link to mailto

### PR DESCRIPTION
**Pull request by AlanWierzchonCA**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [No]
| New feature/enhancement? (use the a.x branch)      | [Yes]
| Deprecations?                          | [No]
| BC breaks? (use the c.x branch)        | [No]
| Automated tests included?              | [No] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

The enhancement allows to track a link using the mailto protocol in the body of an email.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create Email with mailto link in the body of email
3. Send Email by Campaign
4. Click mailto link in the body of email
5. Check Click Counts link in the Email view
6. Please note that links are not tracked while you are logged in to the Mautic dashboard.
 
image-2022-09-14-16-42-12-429

### CODE REVIEW

**Review by RCheesley — APPROVED** [review]
Thanks for the PR @AlanWierzchonCA - works as expected!

In the default branch, mailto links are not being tracked on the email overview, but with this PR applied they are getting logged:

screenshot-8080-alanwierzchonca-mautic-1l80hzg6u9z ws-eu67 gitpod io-2022 09 23-14_22_16

Note for testers: Go to Ports in Gitpod, make the link (8027) accessible to public by clicking on the padlock, then open it in an incognito window and click the mailto link.

**Review by kuzmany — APPROVED** [review]
👍

**Comment by AlanWierzchonCA** [comment]
Hello @RCheesley, 

Do you plan to add these changes to the milestone?

**Comment by RCheesley** [comment]
Thanks for catching that @AlanWierzchonCA

**Pull request merged**
