### PR TITLE
Html classes for generic components

### PR DESCRIPTION
**Pull request by fedys**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features"
| Bug fix?                               | no
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL |
| Issue(s) addressed                     | 

#### Description:
This PR adds some HTML class attributes so we can better customize styling.

#### Steps to test this PR:
1. There is barely anything to test apart from making sure no page layout is broken.

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Review by kuzmany — APPROVED** [review]
👍

**Review by RCheesley — APPROVED** [review]
Good to go, simple fix but improves styling possiblities!

Thanks @fedys 🚀

**Pull request merged**
