### PR TITLE
[type-coverage] Add new, ternary, param based returns

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Good to go :+1:

**Review by kuzmany — DISMISSED** [review]
Awesome 👍

**Comment by escopecz** [comment]
@TomasVotruba there is a conflict. Can you rebase, please?

**Review by escopecz — DISMISSED** [review]
I don't see any issues. It's unrealistic to confirm each and every change in this PR and others like this. I focused on those changes that CodeCov reported as uncovered. And we can rely on our CI that can uncover wrong types with good accuracy 👍

**Comment by TomasVotruba** [comment]
I'm right on rebase...

**Comment by TomasVotruba** [comment]
Good to go :+1:

**Review by escopecz — APPROVED** [review]

**Pull request merged**
