### PR TITLE
Validate multiselect input field on API to maxlen 255

### PR DESCRIPTION
**Pull request by hluchas**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Multiselect value longer than 256 chars throws DB exception.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. create custom field `multiselect` of type multiselect wit possible values `a` and `b`
2. send API request to create contact with value `multiselect` = `a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b|a|b`

#### Steps to test this PR:
1. Same as reproduction step

### CODE REVIEW

**Comment by kuzmany** [comment]
This produce a lot of errors If I am working with last staging.
Especially If works with boolean type 
For example :Form submit with forms with boolean type return error below.
Please take a look before 2.15.1 stable release. 

image

**Comment by hluchas** [comment]
@kuzmany I cannot reproduce it in cloud. 
I created form with e-mail field and send post with valid e-mail address. I "was registered" and record in form results table was created.

May there is something specific in community code.

Can you send me more info how to reproduce this?

**Comment by kuzmany** [comment]
It's not community code. Because every time when it happend.
I started worked from actual staging
I will try look deep on it.

**Comment by hluchas** [comment]
I tried staging branch, created multiselect, email and tried to use for (`/s/forms/preview/1`) and everything works. May I do something wrong here.

**Comment by kuzmany** [comment]
It happend when:

1, I create custom multiple field

image


2, Submit simple form with first/last name/email with match to contact:

image

**Comment by kuzmany** [comment]
These changes fixed it, but it's just quick fix
https://github.com/mautic/mautic/compare/staging...kuzmany:fix-multiple-custom-fild?expand=1

**Comment by npracht** [comment]
@hluchas or @kuzmany we need a long term solution merged in core ?

**Comment by hluchas** [comment]
Reproduced locally. I think I've solution for this.

**Comment by hluchas** [comment]
Have fix for this. Custom validator is missing. I will send PR in one hour

**Comment by npracht** [comment]
@hluchas please link #7344 as issue for your PR :)

**Comment by hluchas** [comment]
TY!
PR here https://github.com/mautic/mautic/pull/7375

**Comment by pety-dc** [comment]
@kuzmany I applied your quickfix to this error. The patch fixed the 500 error, but it seems that multiselect values are not saved or reloaded properly
I edit a contact, pick a value for a multiselect field, save, the values are present when I inspect the contact's details, but disappear when I start editing the contact again.

**Pull request merged**
