### PR TITLE
Fix generatePageTitle to retrieve the correct page header tag.

### PR DESCRIPTION
**Pull request by abhisekmazumdar**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

Title of the page on Ajax is broken basically when Ajax is loading a page, the window title is broken.

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Browse one of the pages by clicking on the links from the sidebar.
3. You will see without these changes the title tag is broken(example: ` | Mautic`). With these changes, you will find the title tag to have the correct header name(example: `Contacts | Mautic`).

### CODE REVIEW

**Comment by andersonjeccel** [comment]
I found other bugs happening because of this issue, not just the page title
So that's a good thing

**Review by andersonjeccel — APPROVED** [review]

**Comment by andersonjeccel** [comment]
@abhisekmazumdar Oh, bug fixes should go for the 5.1 branch

**Review by kuzmany — APPROVED** [review]
Yes, that's good catch 👍

**Comment by abhisekmazumdar** [comment]
Thanks to @mallezie for sharing this issue with me.

**Pull request merged**
