### PR TITLE
Contact manipulators added for campaigns and integrations follow-up

### PR DESCRIPTION
**Pull request by fedys**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [✅]
| New feature/enhancement? (use the a.x branch)      | [❌]
| Deprecations?                          | [❌]
| BC breaks? (use the c.x branch)        | [❌]
| Automated tests included?              | [❌] 
| Related user documentation PR URL      |  
| Related developer documentation PR URL |  
| Issue(s) addressed                     |  

#### Description:

This PR fixes [the issue](https://github.com/mautic/mautic/pull/11669#issuecomment-1306668692) reported by @kuzmany within https://github.com/mautic/mautic/pull/11669.

#### Steps to test this PR:

1. You should no longer see the `500 Internal Server Error - PHP Notice - Undefined index: integration` error after syncing some contacts via an integration.

### CODE REVIEW

**Comment by fedys** [comment]
@kuzmany please can you check if the issue is gone.

**Review by escopecz — APPROVED** [review]
Makes sense. Thanks for refactoring the class to a better state while in it!

**Review by kuzmany — APPROVED** [review]
I applied it along with https://github.com/mautic/mautic/pull/11669 and now works as expected. 
Just don't understand the setManipulator updated because at the moment it's applied just for created or identified contact's https://github.com/Webmecanik/Automation_dev/blob/15a773da3e5fe42b3a761c03c42754f3f9951a7f/app/bundles/LeadBundle/Model/LeadModel.php#L2373

But understand probably from some 3th party code If we come from anonymous to identified could work.

**Comment by fedys** [comment]
Thanks @kuzmany for testing! We added the manipulator so we can distinguish in our proprietary plugin whether contacts come from campaigns or integration respectively.

**Comment by fedys** [comment]
@escopecz Can we merge it?

**Pull request merged**
