### PR TITLE
Support translation for segment anniversary filters

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR is related to already merged to https://github.com/mautic/mautic/pull/6993
We've added support for anniversary, but now need support for translated anniversary filter.

If you're using english language:

- anniversary  
- anniversary -1 day

If you're using french language,  you are able to use these format:

- anniversary  
- anniversary -1 day
- anniversaire 
- anniversaire -1 day

This PR bring new DateRelativeParser (tests include) https://github.com/mautic/mautic/pull/7228/files#diff-bbfe9f8aca314124ce61104c7207459b
That classes also use in another PR https://github.com/mautic/mautic/pull/6710
Class parse string based on own dictionary or related date start with +/-. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com/7228)
2.  Create custom contact date field
3. Add two contacts. If today is 8. 2. 2019, then 
- first contact has custom date field set to 2019-02-08
- second contact has custom date field set to 2019-02-07
4. Create two segments with Custom date field equal
-  anniversary
-  anniversary -1 day
5. Wait for segments rebuild and see If contacts was added to segments correctly
Devs can also check logs on dev enviroment

I see for first segment

image

For second segment
image
6. Then remove segments and switch Mautic to french language
7. Create same two segments as above + create additional two segments with french language in filter:
-  anniversary
-  anniversary -1 day
- anniversaire
- anniversaire -1 day
8. Wait to segments rebuild and see If contacts was assigned to all four segments what you created

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/7228"></a>

### CODE REVIEW

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
Bumping to 3.2 due to lack of testing

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by npracht** [comment]
Documentation already mentions that it is translatable. I'll remove the label saying it misses documentation.

From : https://github.com/mautic/mautic-documentation/blob/master/pages/09.contacts/03.manage-segments/docs.en.md
>Beside this you can specify your date with text. These formulas are translatable, so make sure you use them in correct format.

**Review by RCheesley — APPROVED** [review]
Tested the PR following the instructions and all of the steps worked great in the English and French versions.

Thanks for the PR @kuzmany just needs a test/code review to be merged!

**Comment by RCheesley** [comment]
Bumping from the release due to lack of testing/code review.

**Comment by kuzmany** [comment]
Close favor to https://github.com/mautic/mautic/pull/10541

**Pull request closed without merging**
