### PR TITLE
Feature - Customize Preference Center

### PR DESCRIPTION
**Pull request by virlatinus**
| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/229
| Related developer documentation PR URL | N/A
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/4776
| BC breaks? | N/A
| Deprecations? | N/A

#### Description:
This PR gives any Mautic admin user the ability to edit text labels, format and apply themes to Preference center landing page using the landing page builder.

#### Steps to test this PR:
1. Apply this PR and run migrations (`php app/console d:m:m`)
2. Create a Landing Page and toggle *Is Preference Center* (toggling this button shows/hides the new slots)

image

3. Use the new slots in the builder to customize the page:

image

4. Optionally, you can use tokens to insert the different slots:

image

5. To finish, don't forget to include a "save preferences" button, otherwise the preferences can't be saved:

image

6. Save the page and create/edit an email
7. Select the Preference Center Page from the list:

image

8. Send the email and upon receiving it click on the Unsubscribe link, the new preference center page will be displayed.

image

9. If no Preference Center page is selected in an email, the default page is displayed.

image

### CODE REVIEW

**Comment by Maxell92** [comment]
@virlatinus Could you provide more info about how to test this PR pls?

**Comment by virlatinus** [comment]
@Maxell92 , the instructions have been updated. The user documentation will be ready shortly.

**Comment by chriscalabro** [comment]
I started testing this, and after running migrations I attempted to navigate to Landing Pages to create a new one and hit this error:
screen shot 2017-09-22 at 5 38 06 pm

Not sure if that's an issue with the PR or something unrelated?

**Comment by virlatinus** [comment]
The unknown column error means your schema is not up to date. did you run `php app/console doctrine:schema:update` ?

**Comment by chriscalabro** [comment]
Thanks @virlatinus - schema update cleaned that up, and I was able to create a customized preference center as described. Created a landing page and included the new slots, and was able to use that as the preference center for an email. Clicking unsubscribe in the email brought me to my customized page.
customized-preference-center

**Comment by mqueme** [comment]
I am getting this error when navigating to emails
`Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT e0_.is_published AS is_published_0, e0_.date_added AS date_added_1, e0_.created_by AS created_by_2, e0_.created_by_user AS created_by_user_3, e0_.date_modified AS date_modified_4, e0_.modified_by AS modified_by_5, e0_.modified_by_user AS modified_by_user_6, e0_.checked_out AS checked_out_7, e0_.checked_out_by AS checked_out_by_8, e0_.checked_out_by_user AS checked_out_by_user_9, e0_.id AS id_10, e0_.name AS name_11, e0_.description AS description_12, e0_.subject AS subject_13, e0_.from_address AS from_address_14, e0_.from_name AS from_name_15, e0_.reply_to_address AS reply_to_address_16, e0_.bcc_address AS bcc_address_17, e0_.template AS template_18, e0_.content AS content_19, e0_.utm_tags AS utm_tags_20, e0_.plain_text AS plain_text_21, e0_.custom_html AS custom_html_22, e0_.email_type AS email_type_23, e0_.publish_up AS publish_up_24, e0_.publish_down AS publish_down_25, e0_.read_count AS read_count_26, e0_.sent_count AS sent_count_27, e0_.revision AS revision_28, e0_.lang AS lang_29, e0_.variant_settings AS variant_settings_30, e0_.variant_start_date AS variant_start_date_31, e0_.dynamic_content AS dynamic_content_32, e0_.variant_sent_count AS variant_sent_count_33, e0_.variant_read_count AS variant_read_count_34, e0_.category_id AS category_id_35, e0_.translation_parent_id AS translation_parent_id_36, e0_.variant_parent_id AS variant_parent_id_37, e0_.unsubscribeform_id AS unsubscribeform_id_38, e0_.preference_center_id AS preference_center_id_39 FROM emails e0_ LEFT JOIN categories c1_ ON e0_.category_id = c1_.id WHERE e0_.variant_parent_id IS NULL AND e0_.translation_parent_id IS NULL ORDER BY e0_.subject DESC LIMIT 30 OFFSET 0': SQLSTATE[42S22]: Column not found: 1054 Unknown column 'e0_.preference_center_id' in 'field list'`

**Comment by virlatinus** [comment]
Hey @mqueme , I just modified the migration file to include the missing column. Can you please re-apply it again and test? Thanks.

**Comment by mqueme** [comment]
This is not quite working for me. It's displaying all my preferences even though I only added a couple of them in the page I built.

**Comment by virlatinus** [comment]
@mqueme try switching themes. Does it occur in a blank theme as well?

**Comment by mqueme** [comment]
@virlatinus yes same thing happens with a blank template.

**Comment by 03143059** [comment]
@mqueme I fixed that issue. Can you please try again?

**Comment by virlatinus** [comment]
@mqueme I just fixed that issue. Can you please try again?

**Comment by dongilbert** [comment]
I'm getting a weird visual error in the builder, and it seems to be due to your last commit:

screen shot 2017-10-09 at 10 39 16 pm

**Comment by alanhartless** [comment]
I'm getting same thing as Don and can't inject the submit button into the template.

**Comment by virlatinus** [comment]
The javascript error in the builder has been fixed.

**Comment by mqueme** [comment]
This worked for me now 👍

**Comment by dongilbert** [comment]
My unsubscribe links aren't linking to the preference center page. Here's my steps:

1) Create a new landing page and set it as a preference center. Add preference center slots to the landing page builder. Save it.
2) Create an email. Select the preference center page I created as the preference center page for that email.
3) Create a campaign to send that email.
4) Trigger campaign
5) Click unsubscribe link in email. It takes me to this page instead: 
screen shot 2017-10-10 at 10 55 05 am

I've tested it 3x. Am I missing a step?

**Comment by virlatinus** [comment]
@dongilbert I fixed the issue, can you please test again?

**Comment by yourdigitalclub** [comment]
question... why not add the option in configuration > email settings to set your own default preference center layout? I think it's illogical to allow it to be overridden just from email creation but no option to set it within configuration > email settings

**Comment by khaoua** [comment]
that would be good to have the option to get this feature as a possible variant handled from email building itself, and as well as a possibility to put it as a default in the main config, that would brings more flexibility and consistency between default settings, and "email-only" settings, agree with @yourdigitalclub comment

**Comment by lazmo88** [comment]
I am also having issues with the visual builder, adding save preferences button (drag&drop) will block me from saving the template. However if I add token it allows me to save the template.

However I am not able to access the preference center via link provided in the email. It gives 404 error if I click a link to the page and clicking unsubscribe will take me to default unsub page. 

PHP 5.6.32
Mautic 2.10.1

**Comment by MauriceW2** [comment]
I still have the exact same issue. 404 Page Not Found error when clicking a link to a Mautic page where the 'Is preference center' is enabled.

When I click the unsubscribe link, I get unsubscribed immediately.

Any progress on this?

PHP v7.1.0
Mautic v2.15.0

**Comment by MauriceW2** [comment]
Can anyone tell me how the Mautic redirection function actually works? My server admins says there is not /r/ directory. Therefore the server retyrns an error. I guess that's why Mautic fails to redirect.

So I want to troubleshoot this and track the whole process.

Is it correct that Mautice sees the /r/ part in the url as a redirection? And then tries to call the database and get the destination where it should direct to?

I'm trying to get as much info as possible to understand how the redirection mechanism works.

**Comment by isleshocky77** [comment]
@MauriceW2 
> Can anyone tell me how the Mautic redirection function actually works? My server admins says there is not /r/ directory. Therefore the server retyrns an error. I guess that's why Mautic fails to redirect.
> 
> So I want to troubleshoot this and track the whole process.
> 
> Is it correct that Mautice sees the /r/ part in the url as a redirection? And then tries to call the database and get the destination where it should direct to?
> 
> I'm trying to get as much info as possible to understand how the redirection mechanism works.

You're now very off topic for this issue; but please look into mod_rewrite or nginx patterns Symfony docs are here: https://symfony.com/doc/current/setup/web_server_configuration.html

**Comment by MauriceW2** [comment]
> You're now very off topic for this issue;

You're probably right about that. Thanks anyway for the direction...

**Comment by mcgumbel** [comment]
I still have an issue with the custom preference center. The slot "channel frequency" is always directly under the "save preferences" button located. It doesn't matter where I position it in the editor. Additionally, if I change the label texts in the frequency slot, still the original label texts are displayed. Any suggestions? Is there anything I can do? [ I am using Mautic 2.15.0]

**Pull request merged**
