### PR TITLE
SAML SSO support

### PR DESCRIPTION
**Pull request by alanhartless**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Y
| Related user documentation PR URL | todo
| Related developer documentation PR URL | todo
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

This adds SAML SSO support to Mautic.

#### Steps to test this PR:
1. Apply this PR and clear your cache
2. Register for a free IDP (identify provider) at http://www.ssocircle.com/en/
3. After creating the account and logging in, go to Manage Metadata.
4. Click Add a New Service Provider
5. Enter the URL of your Mautic for the FQDN
6. Check all three optional attributes
7. Visit http://yourmautic.com/saml/metadata.xml and copy the XML into the metadata box and submit.
8. Back on the "Manage Metadata" page, click on SSOCircle Public IDP Metadata link below the link to create a new service provider. It'll download a different XML page.
9. Login to Mautic and go to the configuration -> User/Authentication Settings
10. Upload SSOCircle xml file as the IDP metadata. For the attributes, fill in EmailAddress, FirstName, and LastName into their corresponding attributes fields. Select the default role and save.
11. Logout and browse to  http://yourmautic.com/saml/login.  You should be redirected to SSOCircle. Login and if all goes well, you should be redirected back to Mautic, a new user created (if email/username doesn't exist), and the user is now logged in with the defaulted role.

### CODE REVIEW

**Comment by mqueme** [comment]
I get a timeout error after applying the PR
`[2016-12-29 18:26:50] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Maximum execution time of 30 seconds exceeded" at /Applications/MAMP/htdocs/mautic/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php line 145 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Maximum execution time of 30 seconds exceeded at /Applications/MAMP/htdocs/mautic/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:145)\n[stacktrace]\n#0 {main}"} `

**Comment by alanhartless** [comment]
@dongilbert my bad. URL is /s/saml/login. Il fix the description. 

@mqueme that error seems to suggest it timed out searching a directory. Not sure why it's taking that long. Try wiping out your entire cache. Do you get it on staging as well?

**Comment by mqueme** [comment]
This worked, with the corrected login path you mentioned, the only thing I see is that when navigating to my mautic instance with no trailing path it redirects me to the SSOCircle login. Maybe it should redirect to mautic login and only let /s/saml/login redirect to SSOCircle.

**Comment by alanhartless** [comment]
Symfony handles the redirect so I couldn't find an easy way to default to the standard login when SAML is enabled. So I just made sure that the redirect doesn't happen when SAML is disabled by not registering the firewall at all. I figured that if an admin enables SAML, they are intending to use 3rd party to authenticate most users by default so didn't fight it much.

**Pull request merged**
