### PR TITLE
[type-declarations] Add known return void types in Sms bundles

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Good to go now :+1:

**Review by escopecz — DISMISSED** [review]
No issue found. Thank you! 👍

**Comment by escopecz** [comment]
There is a conflict now.

**Comment by TomasVotruba** [comment]
I'm on it...

**Comment by TomasVotruba** [comment]
Rebasing all these PRs in train with poor connection is a challange :laughing:  

Thanks for patience :pray:

**Comment by TomasVotruba** [comment]
The failing mariadb is false positive, as coverage not send happens from time to time.
Rebase usually triggers it and sometimes make it pass. Should I rebase or is it ok?

**Comment by escopecz** [comment]
It's OK. I re-triggered the failed job

**Review by escopecz — APPROVED** [review]
👍

**Pull request merged**
