### PR TITLE
Import owner by username

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/2615
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Just added support for owner username  for contact import

image

#### Steps to test this PR:
1.  Add column ownerusername to import
2. Set ownerusername at Match the columns from the imported file to Mautic's contact properties
3. Import and see of different owners were updated to contacts

### CODE REVIEW

**Comment by Maxell92** [comment]
@kuzmany Could you rebase your branch to actual staging pls? There is an conflict.

**Comment by kuzmany** [comment]
@Maxell92 yeah, give me few days...

**Comment by Maxell92** [comment]
Could you give us a purpose of this code please? It looks like you are hard coding support ownerusername CVS field?

**Comment by kuzmany** [comment]
@Maxell92 look https://github.com/mautic/mautic/issues/2615 
Before you can set owner just for all import.
This PR added import for each line  in import.

Test import looks like:

test@domain.tld,ownerusername1
test2@domain.tld,ownerusername2

**Comment by mqueme** [comment]
This worked for me.

**Comment by alanhartless** [comment]
@kuzmany can you add documentation to https://mautic.org/docs/en/contacts/import.html for `ownerusername` since the admin will need to know what to name the CSV column.

**Comment by alanhartless** [comment]
Never mind! I see it's in the UI

**Comment by alanhartless** [comment]
Wait - that import UI is no longer applicable. Does this still work with the new UI?

**Comment by alanhartless** [comment]
Ok - just checked. It's ok. Carry on!

**Pull request merged**
