### PR TITLE
Fix email is empty after switching publish status

### PR DESCRIPTION
**Pull request by volha-pivavarchyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | yes
| New feature/enhancement? (use the a.x branch)      | no
| Deprecations?                          | no
| BC breaks? (use the c.x branch)        | no
| Automated tests included?              | N/A
| Issue(s) addressed                     | Fixes #... 

#### Description:
If the email status changes (published -> unpublished) on the list of emails, this email will be blank. This affects the preview and the sending of an email

#### Steps to test this PR:

1. Open the list of emails
2. Switch the status of an email (published -> unpublished) 
3. Open this email
4. Preview the email
5. Email is empty

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10701"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
@volha-pivavarchyk thank you for the contribution! Every PR must go through a round of quality checks in order to be merged. Please fill in details about this change to the PR description, especially the steps to test. I cannot reproduce it following your steps. Here is what I did:

1. Create a new email with unpublished = true
2. Click Save&Close
3. On the email detail page click on the preview link (`email/preview/1`)

The email content showed up.

Also, every code change needs PHPUNIT tests. Let me know if you'll need help with those.

**Comment by volha-pivavarchyk** [comment]
Thank you for the comment! 
I have modified the PR description. Could you please try to reproduce issue by those steps.
I won't need help with tests. I will add them as soon as I can.

**Comment by escopecz** [comment]
I'm not able to replicate by those either. Is the email somehow special? How come it does not have any content? So the preview URL loads successfully for you but is completely blank?

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by volha-pivavarchyk** [comment]
@escopecz
I double-checked with v4.x of the GrapesJsBuilder plugin. It works normally. But it didn't work for me. Maybe it is related to lower than v4

**Pull request closed without merging**
