### PR TITLE
[Enhancement] Add field type for money, and migrate Attribution to it.

### LINKED ISSUE #5684: [Enhancement] Convert attribution from a double to a decimal (support money).
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | Yes

## Description:
The `attribution` column on the leads table is currently stored as a double floating point value. This is fine for approximate values, but since the field is intended for use as currency it could make the field a considerable headache for a finance department. In general, doubles/floats are good for science, but bad for currency.

It would be better if this were a precise decimal column instead so that rounding errors do not occur in the future. The GAAP typically recommends `DECIMAL(19, 4)` for currency which would be more than sufficient.

### PR DESCRIPTION
**Pull request by heathdutton**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? | Yes
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | fixes #5684
| BC breaks? | ?
| Deprecations? | 

[//]: # ( Required: )
#### Description:
I just wanted "Attribution" to be stored as a DECIMAL(19, 4) instead of DOUBLE so that we don't end up with weird rounding errors of thousandths of cents that make our finance people cringe... but then went down the rabbit hole and realized we really need a "Money" field type for that. So this PR adds a field type for "Money" and migrates the Attribution field over.

Money field creation screen

#### Steps to test this PR:
1. Run unit tests.
2. Create a custom field of type "Money", and ensure the field functions.
3. Check for rounding errors.

#### List backwards compatibility breaks:
1.

### CODE REVIEW

**Comment by heathdutton** [comment]
For future reference. The report bundle needs to have another output mechanism for decimal/money otherwise float/int are the only options which may not suffice for all use cases.

**Comment by virgilwashere** [comment]
> I just ... but then went down the rabbit hole

Have some ❤️ and 🍺 from the bottom of another rabbit hole.

🚧 If I keep digging, will we meet in the middle?? 🌎 ↪️ 🌏 

Oh yeah, 👍 for 💵 field.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@heathdutton can you take a look at the conflict please?

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by npracht** [comment]
Hi @heathdutton ! Any chance you have a look at it ? I'm sure it is a good enhancement.

**Comment by RCheesley** [comment]
Closing this PR due to no response from the author since Aug 2018 and outstanding conflicts.

**Pull request closed without merging**
