### PR TITLE
TPROD-143 Replaces Froala with CKEditor 4 as the default WYSIWYG

### PR DESCRIPTION
**Pull request by alanhartless**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" 
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | yes
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | n/a
| Related developer documentation PR URL | n/a
| Issue(s) addressed                     |  n/a

#### Description:

We've been locked into a very old version of Froala with no upgrade path due to Froala changing their licensing years ago. Thus, this PR replaces Froala with CKEditor 4 everywhere except for the the legacy builder since that is being replaced with Grapesjs. Froala's code will be removed once the legacy builder's code is removed. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create new Dynamic Web Content. CKEditor should be loaded and usable. 
3. Similarly use the different areas in the product that require a WYSIWYG editor (descriptions, etc).
3. Use the legacy builder to build an email or landing page which should still be usable with Froala. 

#### Deprecations
Froala is on its way out so nothing new should be dependent on it.

### CODE REVIEW

**Comment by RCheesley** [comment]
@alanhartless are there any specific things that need to be done in testing this? I have pulled the PR and cleared the cache but I am definitely still seeing Froala in DWC and other locations - no sign of CKEditor.

**Comment by RCheesley** [comment]
Spotted this weird behaviour in the Assets > New description (after clearing the cache):

https://youtu.be/vZtMt2Tg14o

**Comment by alanhartless** [comment]
@RCheesley Are you testing in index_dev.php? I didn't compile prod assets to minimize conflicts. So if using prod on the local (using index.php instead of index_dev.php), you'll need to do that with `bin/console mautic:assets:generate`.

**Comment by alanhartless** [comment]
Also are you referring to the browser's cache or Symfony's? You may need to clear the browser's.

**Comment by RCheesley** [comment]
Hurm - think I was but now I am doubting myself! Will double check - thanks for the nudge!

**Review by RCheesley — APPROVED** [review]
Tested this with the simple editor in areas like the description and also in the fully featured editors like creating dynamic content - works perfectly including the tokens!

screenshot-mautic4 ddev site-2021 03 28-17_23_50

**Review by kuzmany — APPROVED** [review]
CK Editor works as you describe.

In form Description area field type, it's editor with more options like we need (at least don't need tokens there)

image

After save field the editor is lost for description

image

We are talking about PR for alpha version of M4, we can take care this small things later. 

Approve it

**Review by mabumusa1 — APPROVED** [review]
CKEditor loaded, legecy editor is loading. 
I think this PR is good to go 

image

image

image

image

**Comment by RCheesley** [comment]
Awesome thanks all, setting this RTC - let's create issues for addressing those issues that @kuzmany raised so that we don't forget them before we merge this!

**Comment by samuelfaith** [comment]
Is this PR usable in Mautic 3.3.x?

**Comment by RCheesley** [comment]
No, I believe that this will only work on Mautic 4 @samuelfaith given that it is based on Features.

**Pull request merged**
