### PR TITLE
Custom Objects export fix for M5

### PR DESCRIPTION
**Pull request by escopecz**
This is duplicate of https://github.com/mautic/mautic/pull/11989 for M5

### CODE REVIEW

**Comment by RCheesley** [comment]
@escopecz we need @priyanshu2316 to sign the CLA please.

**Comment by escopecz** [comment]
He's not part of the Acquia dev team anymore but was. So as we discussed in the past, such devs agree by default even if they do not respond.

**Comment by RCheesley** [comment]
@escopecz looks like there are some conflicts to address with this one now.

**Review by fedys — APPROVED** [review]
Thanks @escopecz!

**Pull request merged**
