### PR TITLE
JSON object or JSON array returned, depending on whether the field is empty

### PR DESCRIPTION
**Pull request by ondrejsibl**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | Y
| Related user documentation PR URL | N
| Related developer documentation PR URL | N
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
After we make a GET request to /api/fields/contact, it appears that an empty array is returned when there are no values in the associated field and if there are values in the field, Mautic returns a JSON object. The same case is an empty list of entities.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Make a GET request and check the response for Contacts
2. Properties attributes are arrays, if empty

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Make a GET request and check the response for Contacts
3. The response for both empty and non-empty properties attributes should be an object

### CODE REVIEW

**Comment by npracht** [comment]
Hi @ondrejsibl can you check Travis issue please ?

**Comment by RCheesley** [comment]
@ondrejsibl can you take a look at the Travis issue so we can get this tested and merged please? Thanks!

**Comment by alanhartless** [comment]
@RCheesley @npracht Travis is passing now.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by npracht** [comment]
Hello @ondrejsibl could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback, i would very love to merge it in 3.0.1 if still relevant. Thanks !

**Comment by RCheesley** [comment]
@ondrejsibl @alanhartless please can you take a look at the conflicts?

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Bumping this to 3.2 due to the outstanding conflicts

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Tested before the PR and confirmed that the properties attributes are an array:

screenshot-nimbus-capture-2021 02 13-13_13_30 (1)

As expected the PR changes the properties attributes to be an object rather than an array.

screenshot-nimbus-capture-2021 02 13-13_13_30

**Comment by RCheesley** [comment]
Just need a code review and then this one will be RTC!

**Review by kuzmany — APPROVED** [review]
Looks good 👍

**Comment by RCheesley** [comment]
As this is based on Features I am going to move it to 4.0 as it's on a protected branch and will likely need to be rebased if we change the branch.

**Pull request merged**
