### PR TITLE
Bug 12241 - check list exists before looping

### LINKED ISSUE #12241: Variable list does not exist edit form
### Mautic Version

5.0.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

 Variable \"list\" does not exist.

### How can we reproduce this issue?

Step 1:  Enter page https://mautic.ddev.site/index_dev.php/s/forms/edit/[id_form]

### Relevant log output

```shell
[2023-04-20 10:16:19] mautic.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "list" does not exist." at /var/www/html/app/bundles/FormBundle/Resources/views/Field/group.html.twig line 229 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"list\" does not exist. at /var/www/html/app/bundles/FormBundle/Resources/views/Field/group.html.twig:229)
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/121828572-variable-list-does-not-exist-edit-form?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by LordRembo**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [yes ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #12241 

#### Description:

The key `list` in the `group` Twig template can be looped without checking if it actually exists. So wrapped that loop in an `if`-statement.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. See #12241

### CODE REVIEW

**Review by volha-pivavarchyk — COMMENTED** [review]
This PR fixes the described issue. 
But I couldn't reproduce it, except to manually make the radiogroup options list empty in DB. I couldn't save radiogroup or checkbox fields with empty option list via UI or API.
I don't know how the bug is achieved. If it is possible, this PR fixes it.
image

**Comment by RCheesley** [comment]
@LordRembo it looks like we have a conflict to address here, and some feedback asking for clear instructions on how to reproduce the bug in the first place.

**Comment by RCheesley** [comment]
@LordRembo will you be able to take a look at the conflict and feedback please? Thank you!

**Comment by LordRembo** [comment]
@RCheesley Sorry, completely missed there was something to fix! I fixed the merge error and syntax errors. I *think* this should be it.

**Comment by LordRembo** [comment]
Looks like someone basically fixed this issue in 5.x, so basically the only changes that now remain, are indents in the file :D

**Comment by RCheesley** [comment]
Hah, sorry for that! I have set it for code review only then, as it's not sensible to have user testing!

**Pull request closed without merging**
