### PR TITLE
Focusitems fix unique clicks link in focus view

### PR DESCRIPTION
**Pull request by AlanWierzchonCA**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [yes ]
| New feature/enhancement? (use the a.x branch)      | [ no]
| Deprecations?                          | [ no]
| BC breaks? (use the c.x branch)        | [ no]
| Automated tests included?              | [ no] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

Note: there is duplicate of this PR for M5: https://github.com/mautic/mautic/pull/11465

#### Description:

In the  Focus Item view, in the "Click count" tab, there is a tracking URL list. In this list In the Unique Click column, there is an invalid link to the contacts that clicked the URL. 

Clicking on this link does nothing. 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create Focus Item and add link to content
3. Create Landing Page with Focus Item
4. Go to the Landing Page URL and click link in focus item
5. Check Unique Clicks link in the Focus Item view
6. Please note that links are not tracked while you are logged in to the Mautic dashboard.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11418"></a>

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
Thanks for taking care of this! The code change makes sense 👍

**Comment by escopecz** [comment]
Please rebase this on 5.x branch. If you want to back-port it to some last bug-fix versions of Mautic 4 then create duplicate PR agains 4.x branch too.

**Comment by AlanWierzchonCA** [comment]
I made PR for 5.x version:

https://github.com/mautic/mautic/pull/11465

**Comment by escopecz** [comment]
@AlanWierzchonCA thank you! I made a mistake in my previous comment. It should be 4.4 branch, not 4.x. As there won't be any feature releases for M4, so all bug fixes that should make it to M4 must be against 4.4. Sorry for the confusion. Could you please rebase this to 4.4?

**Comment by AlanWierzchonCA** [comment]
@escopecz, 
I made rebase these changes to 4.4

**Review by kuzmany — APPROVED** [review]
👍

**Comment by RCheesley** [comment]
@all-contributors please add @AlanWierzchonCA for code

**Pull request merged**
