### PR TITLE
Prevented fatal errors when core fields are disabled

### PR DESCRIPTION
**Pull request by alanhartless**
Please answer the following questions:

| Q             | A
| ------------- | ---
| Bug fix?      | Y
| New feature?  | N 
| BC breaks?    | N
| Deprecations? | N
| Fixed issues  |  

## Description
This supercedes #997. When a core field is disabled, the contact form throws fatal errors and the list views throw notices.

## Steps to reproduce the bug (if applicable)

Disable a core field (name, title, address1, etc). Try to open the contact form and you should be greeted with a fatal error. 

## Steps to test this PR

Apply the PR and repeat the above. This time the contact should be editable. Email is prevented from being unpublished since it is key to all of Mautic.

### CODE REVIEW

**Comment by escopecz** [comment]
For the reference, this might fix https://github.com/mautic/mautic/issues/1780

**Comment by dbhurley** [comment]
+1 tested and prevents fatal error when disabling core field.

**Comment by escopecz** [comment]
The error is fixed with this PR :+1:

**Comment by alanhartless** [comment]
@escopecz did you mean to close this?

**Comment by escopecz** [comment]
Ah, oh, no. I probably clicked a wrong button. Apologies.

**Pull request merged**
