### PR TITLE
DPMMA-375 Flash messages are not visiblie in campaign builder

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ Y ]
| New feature/enhancement? (use the a.x branch)      | [ N ]
| Deprecations?                          | [ N ]
| BC breaks? (use the c.x branch)        | [ N ]
| Automated tests included?              | [ N ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Flash messages, such as update confirmations or warnings about unpublished campaign elements, are not visible in the Campaign Builder. This PR fixes this issue.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create new campaign
3. Add required campaign name and some campaign actions
4. Save campaign in the builder, the flash message should be visible.
image

### CODE REVIEW

**Review by escopecz — CHANGES_REQUESTED** [review]
Works as described. However, it's blocking the 2 buttons above. I cannot press those buttons until the flash message disappears.

**Comment by patrykgruszka** [comment]
@escopecz I've just checked this on GitPod and looks fine. Could be a browser cache issue. I've resolved this problem in this commit: https://github.com/mautic/mautic/pull/13205/commits/3c4968cce3fd6ec0513632f2a6ec5997837d0168

**Comment by code5rick** [comment]
@escopecz tested this PR, and it works fine! Indeed, after testing on 5.0.1, when a campaign is edited, it didn't show the notification.
Good work @patrykgruszka 👌

**Comment by escopecz** [comment]
I don't think I have outdated cache. I use the dev mode but run `composer install` which updates all the JS dependencies and builds prod assets just to be sure. In the browser I have dev tools open with cache disabled. I still cannot press the buttons if the flash message is ON. I changed the timeout for flash messages so I could inspect it. It looks like this:
Screenshot 2024-01-15 at 17 30 53
You can see that if I want to hit a button I have to do it in the very top edge of the button. Because the div margin is over the buttons. Is that different for everyone else?

And then when I manage to hit the apply button again and close the first flash message then the second will flow over the buttons like this:
Screenshot 2024-01-15 at 17 31 11

**Comment by code5rick** [comment]
@escopecz you are right, and my bad for saying that it was fine. We can only click on the top of the button, so thats why I didn't notice it. I openned this PR again on GitPod and worked with CSS to fix this issue. The workaround that I applied was:

```css
.alert-growl-container {
    point-events: none
}
``` 
```css
.alert.alert-growl {
    pointer-events: all;
}
``` 

Video of it:
https://github.com/mautic/mautic/assets/131262825/16c0902b-89c6-4384-8e77-0cfc7b860337

**Comment by patrykgruszka** [comment]
@escopecz I see it now, thanks for the explanation. This problem should be fixed now. 
@code5rick thanks for testing, I've used a position offset on the `#flashes` container instead of `pointer-events` change.

**Review by code5rick — CHANGES_REQUESTED** [review]
I tested your edited PR @patrykgruszka 

Indeed, the issue with the overlapping divs is fixed. However, now there's a new situation that wasn't present before. The first time we save the campaign, the initial warning doesn't appear, but the second and subsequent ones do.

This situation is currently happening; it wasn't the case before.

**Review by escopecz — APPROVED** [review]
Thank you! Works nicely now 👍

**Pull request merged**
