### PR TITLE
Add default reply-to address in configuration

### PR DESCRIPTION
**Pull request by dadarya0**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? |  N
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

Add a field in Configuration > Email Settings for default reply to address 
 - Field is optional, if reply to email is empty, the sender address is used
 - If value is set on the individual email, that will override the global value
 - Send email action will need to account for this change

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1.  N/A

#### Steps to test this PR:
1. Navigate to Configuration > Email Settings
2. There should be a text field **Reply to address**
3. Field should not be required but should have email type validation.
4. On send mail action following should be expected:-
    - if reply to email is empty, the sender address should be used
    - if value is set on the individual email, that will override the global value

#### Other areas of Mautic that may be affected by the change:
1. 
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by RCheesley** [comment]
@dadarya0 this should be based on the Features branch please, as is is a feature.

**Comment by dennisameling** [comment]
Hi @dadarya0! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since we don't have access to your branch, could you please click "Update branch" at the bottom of this PR? If that doesn't work, you can also run `git merge upstream/features` locally. Thanks in advance!

image

**Comment by npracht** [comment]
Hi @dadarya0 can you please explain what you mean by "**Form send email action will need to account for this change**" ?

**Comment by dadarya0** [comment]
> Hi @dadarya0 can you please explain what you mean by "**Form send email action will need to account for this change**" ?

@npracht it was acceptance criteria for developer, this statement means developer need to update code in send email action for new added configuration. so it is done https://github.com/mautic/mautic/pull/9812/files#diff-d1949283f925ccb79831f1331dca03d32cadc4cef0e05f0e9bed3f55d5d410aeR271

**Comment by npracht** [comment]
Hi @dadarya0 I am very sorry but i don't understand your comment and still don't understand "Send email action will need to account for this change".
If you think it's easier, I'm available on Slack.

Thanks !

**Comment by kuzmany** [comment]
> Error: Class 'Bazinga\OAuthServerBundle\BazingaOAuthServerBundle' not found

This PR need merge actual features branch

**Comment by RCheesley** [comment]
Please can you rebase this PR on the 4.x branch @ts-navghane

**Comment by jos0405** [comment]
I tested this, works fine.
image
Email sending also works as expected.

**Review by mohit-rocks — APPROVED** [review]

**Pull request merged**
