### PR TITLE
fixing relative date filter (eq,neq)

### PR DESCRIPTION
**Pull request by vivoconunxino**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | X
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description: Fixed bug when creating segments on leads based on relative dates using eq and neq operators (greater than, less than,.. are working well).

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a new segment and filter by "`Date Added` eq `-2 days`"
2. build the segment on the command line, an error will ocurr

#### Steps to test this PR:
1. Create a new segment and filter by "`Date Added` eq `-2 days`"
2. build the segment on the command line, this time will work

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by kuzmany** [comment]
Thanks. Please fix minor code standard https://travis-ci.org/mautic/mautic/jobs/333698415#L693

**Comment by kuzmany** [comment]
Label: Pending feedback

**Comment by vivoconunxino** [comment]
Hi kuzmany, still an error, should I really put it that way?

> Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error
>    1) app/bundles/LeadBundle/Entity/LeadListRepository.php (binary_operator_spaces)
>       ---------- begin diff ----------
> --- Original
> +++ New
> @@ @@
>                          //we want to compare only 'Y-m-d', not also the hour, minute and second.
> -                        $isTimestamp = false;
> +                        $isTimestamp     = false;
>                          $requiresBetween = true;
> -                        $modifier = '+ 1 day';
> +                        $modifier        = '+ 1 day';

**Comment by kuzmany** [comment]
Label: Pending Feedback

**Comment by kuzmany** [comment]
Label: Bug

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by kuzmany** [comment]
@vivoconunxino 
Thanks, now it's correct. 
I just copy/paste instructions from @escopecz  comments in past:
"Run bin/php-cs-fixer fix -v in Mautic root dir. It will go through all Mautic files and fix the CS for you. It will take a while. A better way is to use the pre-commit hook which will do it automatically for the files changed in your commits. All you have to do is to git clone this repository and run composer install. It should then trigger the pre-commit hook automatically for you."

I used to use pre-commit hook, it's very practical.

**Comment by Maxell92** [comment]
Hello @vivoconunxino,

We are working on a complete refactoring of segments. This bug is fixed in the new code.
You can take a look at a PR https://github.com/mautic/mautic/pull/5524 and https://github.com/galvani/mautic/commits/maxell92/feature/segment-refactoring branch, where we continue with our work.

Thank you for your contribution!

**Pull request closed without merging**
