### PR TITLE
[UX] Reorder administration panel

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Reordering administration panel based on discussion: https://mautic.slack.com/archives/C024XBCQS3Z/p1711566166387599

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open the right sidebar
3. Look, click on these things to make sure it's working

---

| Before                                      | After
| -------------------------------------- | ---
image | image

### CODE REVIEW

**Comment by kuzmany** [comment]
I see different ordering. Do I something wrong?

image

**Comment by andersonjeccel** [comment]
@kuzmany Hm, probably because there are custom plugins (the first two ones)

What is the "API credentials"?
A page similar to Webhooks but for API specifically?

**Comment by kuzmany** [comment]
@andersonjeccel API is from CORE
Wonder why configuration is so low, shouldn't it be first?` The usual first step is to go there.

**Comment by andersonjeccel** [comment]
@kuzmany I mean, they seem not available in Mautic Community releases
Probably this will be the default behaviour of the system with new menu additions, placing them at the top

Regarding the Configuration item, companies usually allow only admins to access them, while the marketing professional is kept with basic access to what is needed in order to make campaigns happen

Also, for marketeers using Mautic daily, Categories, Custom Fields and Themes have a higher access frequency

**Review by LordRembo — APPROVED** [review]
The PR is missing a bit of context: ~~the order is alphabetical, as that seemed to get the most positive feedback~~ ah, there was a custom order discussed, with 'config', 'integrations' and 'system info' put at the bottom.

**Comment by escopecz** [comment]
There are some conflicts. But I'm also wondering why the API Credentials are missing from @andersonjeccel screenshot. Could you also provide "before and after" images in the description in the future PRs so it's clearly visible what was changed?

**Comment by andersonjeccel** [comment]
Hm, it wasn't activated under settings...

Updated the description

**Comment by escopecz** [comment]
Thanks for the update! And I completely forgot that the API is disabled by default. TBH, I like the original menu better without hiding some options into submenus.  I also don't understand the new order. I let others express their opinions.

**Comment by andersonjeccel** [comment]
An explanation about the new order: It causes items most used by marketing professionals to be placed at the top while items more related to development or system configurations are placed towards the end, it was previously[ discussed on Slack](https://mautic.slack.com/archives/C024XBCQS3Z/p1711566166387599)

Now, regarding the grouping of integrations, well, it follows the same line of reasoning that already exists for Channels and Components

**Review by kuzmany — DISMISSED** [review]
Old menu was OK
New menu is OK

**Comment by escopecz** [comment]
Is it possible to put the Marketplace and Pugins next to each other? I don't get why webhooks are in between.

**Comment by RCheesley** [comment]
I would agree with the suggestion from @escopecz above - plugins and marketplace should be next to each other. Otherwise I really like the more logical organisation and grouping.

**Comment by andersonjeccel** [comment]
Nice idea, I’ll fix it soon

**Comment by andersonjeccel** [comment]
API disabled

image

API enabled

image

**Review by escopecz — APPROVED** [review]

**Pull request merged**
