### PR TITLE
SugarCRM support for store fields to tags

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR added new option to store any fields from SugarCRM to contact tags.

image

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Setup Sugar CRM integration https://www.mautic.org/docs/en/plugins/sugarcrm.html
3. Setup lead sync and see in features tab new option Sugar CRM fields to Mautic tags 
4. Select some fields in new option SugarCRM support for store fields to tags (Unique identifier at least)
5. Try sync data by `php app/console mautic:integration:fetchleads --integration=Sugarcrm --env=dev  --time-interval="10 days"`
6. Check If contacts was added to Mautic and contacts has tags from setup above

### CODE REVIEW

**Review by npracht — DISMISSED** [review]
It works, I can send data from SugarCRM to Mautic contact tags.

**Comment by kuzmany** [comment]
@npracht Can you re-test it? I added support for also for Contacts from SugarCRM

**Comment by Woeler** [comment]
Needs re-validation from someone who uses Sugar.

**Comment by florentpetitjean** [comment]
Hello, this PR doesn't use this one https://github.com/mautic/mautic/pull/7741 so Tags with special characters bugs when they come from Sugar

It works in other case

**Comment by kuzmany** [comment]
> Hello, this PR doesn't use this one #7741 so Tags with special characters bugs when they come from Sugar

What does it mean? It's not importe, return fatal error, or what?

**Comment by florentpetitjean** [comment]
They duplicate if a special character is used in the name (one different tag per contact)

**Comment by kuzmany** [comment]
@florentpetitjean 

I did test and after apply https://github.com/mautic/mautic/pull/7741 my tags looks like:

image


How could I test it?

**Comment by florentpetitjean** [comment]
You do not have any duplicate when pushing several contacts with the same tag ?

**Comment by kuzmany** [comment]
@florentpetitjean last commit should fixed it. Please re-test

**Review by npracht — DISMISSED** [review]
👍

**Comment by florentpetitjean** [comment]
Hello @kuzmany.
We still have duplication on tags,  can this come from Sugar sending encoded value for special characters instead of normal value ?
Thanks

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebased

**Comment by kuzmany** [comment]
We are not gonna use/support this PR anymore.
Anybody can take it and take care about it to release M3.1

**Pull request closed without merging**
