### PR TITLE
Support attachment for contact's note

### LINKED ISSUE #7609: How can I attach a picture file or a pdf file to a contact in the user interface?
Good day.
Thank you very much for the wonderful product.
I have a question. How can I attach a picture file or a pdf file to a contact in the user interface?
Or how can this be done in another way?
We want to attach copies of invoices to contacts.

Thanks you. Bogdan

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/75628174-how-can-i-attach-a-picture-file-or-a-pdf-file-to-a-contact-in-the-user-interface?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | Closes #7609
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR added support for attachment in contact notes

image

image

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Just test add note with/without attachment
3. Remove attachment from note by edit
4. Edit note and add attachment

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/7386"></a>

### CODE REVIEW

**Comment by DianaCruz16** [comment]
Hi, how can i export notes in CVS file, or see Notes in a Report??

**Comment by kuzmany** [comment]
@DianaCruz16 should be coded. If you have budget for it, contact me https://mtcextendee.com

**Review by Strubbel94 — DISMISSED** [review]
Feature is working as intended.
No bugs found.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebased

**Comment by RCheesley** [comment]
Bumping to 3.2 due to failing Travis tests

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Another one with a conflict to resolve @kuzmany

**Comment by npracht** [comment]
@RCheesley done

**Comment by RCheesley** [comment]
Seems like there's some fatal errors to be addressed as the tests are failing.

**Comment by antonioandrade** [comment]
This feature is badly needed.

What's the status on this PR @kuzmany? (Yes, I see the failing CI) 
Is this something you plan on pushing forward or did you go with a different solution?

**Comment by antonioandrade** [comment]
We'd also need this feature, badly. 
Ideally, not only attaching files to a Note but also directly to a Contact.

How can we help push this PR forward? Simply test on gitpod and report back? 
CI is a mostly red too right now...

**Comment by kuzmany** [comment]
@antonioandrade there is no plan to support this PR. Customer times ago does not request make it compatible with M4. For merging to official repo it also need write unit tests. If you need it you can write me and we will see

**Comment by RCheesley** [comment]
Given @kuzmany 's comments I am going to close this PR. If someone would like to pick it up again by rebasing and adding the required tests, please ping us and we can re-open the PR.

**Pull request closed without merging**
