### PR TITLE
Feature Request - Added HubSpot CRM integration #781

### PR DESCRIPTION
**Pull request by gpassarelli**
Added integrations with HubSpot CRM

### CODE REVIEW

**Comment by escopecz** [comment]
Nice work. I wrote the documentation for it while I was testing it. But the contact hasn't been created for me. Could you check my workflow if I did something wrong?

https://github.com/mautic/documentation/pull/21/files

**Comment by gpassarelli** [comment]
@escopecz, what was the properties of your lead? For this first version of the plugin, and because we needed this ASAP, I've used the endpoint for **createOrUpdate** at Hubspot API.

For this endpoint work, your lead must have a valid email address. You can read it more here:
http://developers.hubspot.com/docs/methods/contacts/create_or_update

And Hubspot also validate if is a valid email, including a valid domain. 
So if your user has an invalid email like ```dasdas@dsadsa.dasdas```  it wont't create the lead. 
But it should log as an API integration error.

**Comment by escopecz** [comment]
I didn't see the Mapping tab at all in the first test as you could see from the screenshot. I maybe cleared the cache wrong. It showed up in the second test, so that's good. The contacts weren't created after field mapping either so I looked at the logs and found:
```
[2015-10-29 15:40:33] mautic.ERROR: INTEGRATION ERROR: Hubspot - Address in mailbox given [Unknown] does not comply with RFC 2822, 3.6.2. [] []
```
So I double checked the email field mapping because I noticed it was pre-filled already. But it was pre-filled by Address1 field, not the email field. Could you check if it could be pre-filled with email field or not pre-filled at all?

After that the contact was created in the Hubspot CRM :+1: 

I updated the documentation.

**Comment by gpassarelli** [comment]
Nice,

I'll check that to pre-select the correct e-mail field. Instead of Address 1.

**Comment by gpassarelli** [comment]
@escopecz so was checking the code and apparently there is no code to "automatically match" the required fileds. So the lead field it won't match with the integration fields automatically. 
You can check the code here:
https://github.com/mautic/mautic/blob/staging/app/bundles/PluginBundle/Form/Type/FeatureSettingsType.php#L72-L74

So what was happening is, as the email field was required, it was selecting the first option of the fields dropdown, and is "Address Line 1". 

So to avoid any change request for the Core, I've disabled the email as a required field, and if no email is set for the user, it won't send the request to create the user.

**Comment by gpassarelli** [comment]
@escopecz I've changed my mind, and created another PR to auto-match the fields correctly ;)
#1099 

So with this PR, the fields should be matched correctly

**Comment by dbhurley** [comment]
:+1: Looks good, and good call to move auto-matching to a new PR.

**Pull request merged**
