### PR TITLE
Fix for duplicate contact creation by Social Monitoring of Twitter

### PR DESCRIPTION
**Pull request by github-grabaz**
Possible fix for issue [3934](https://github.com/mautic/mautic/issues/3934).

Twitter handles are not case sensitive.  However they are returned using whatever case was used during creation.  This led to a problem when a twitter handle was manually created in Mautic since there is no way to guarantee case would match.  MySQL is case insensitive and was finding the contact just fine but because of the case difference the php code was not matching and instead just creating a new contact.

Using strtolower() eliminates the problem of twitter handles not matching manually input data in the php code.

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #3934
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a twitter account (e.g. MyTwitterHandle).  Note that twitter is not case sensitive.
2. Create a contact in Mautic and enter the twitter handle making certain to use different case (e.g. myTwitterHandle).
3. Create a social monitor for twitter (e.g. #myTestHashTag).
4. Tweet out that hashtag from the twitter account.
Bug -> Mautic will create a duplicate contact.

#### Steps to test this PR:
1. Repeat steps 1-4 above.
Fix -> Mautic will update the contact.

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by github-grabaz** [comment]
To be clear, the php code that is causing the problem is on line 263 (just after my edits):
`if (isset($twitterLeads[$handle])) {`
If there is a case mismatch for $handle, this will fail and the else condition creates a duplicate contact. 
Using strtolower() as I did just makes certain that case mismatch is not possible.

I have made the change to my production system and it has fixed the problem.

**Comment by github-grabaz** [comment]
@escopecz I added additional comments that I think will help to get this reviewed/approved.

**Comment by escopecz** [comment]
I followed the steps, but I'm getting this when I execute the command:
```
$ app/console social:monitor:twitter:hashtags
no hashtag was found!
No statuses found
PHP Warning:  array_key_exists() expects parameter 2 to be array, boolean given in plugins/MauticSocialBundle/Command/MonitorTwitterBaseCommand.php on line 119
```
It doesn't seem to be related to this PR, but I cannot test it at the moment.

**Comment by escopecz** [comment]
I don't get why Travis checks CS of this PR since this PR doesn't contain the Travis update yet. I'd suggest to ignore the CS errors in this case. I tried to fix the CS in the problematic file, but the pre-commit hook changed it back to its original state.

**Comment by escopecz** [comment]
Travis CS errors fixed by merging staging in

**Comment by dongilbert** [comment]
+1 on this now thanks @escopecz

**Pull request merged**
