### PR TITLE
Copy button for segment filters

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | 

#### Description:

This new button allows users to copy segment groups to speed up segment filter building. The copy button is hidden for filters with the AND glue. It allows to copy only filters with the OR glue including all filters with the AND glue attached to it = filter group.

For reference, this is how the segment filters look before this change:

Screenshot 2024-10-18 at 17 36 18

And this is after:
Screenshot 2024-10-18 at 17 35 55

The changes aren't only about adding the button. The delete button was moved to the top right corner of the filter header and the glue (and/or selection) was moved to the top left column. The filter value is now wider and we can add as many buttons as we want without affecting the filter value.

From the dev point of view, I did a small refactoring to DRY the code out a little.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Test that the copy button works well in all cases:
3. When a new filter is added. Especially segment filter or tag filters which have multiselect as a filter value.
4. When you save the segment, you must be able to copy the filters as well.
5. When moving the filters around (changing filter order) then all the functionality must work as before and the copy button must work as well.
6. Test that the dynamic web content filters still work as before. Those share some code with segment filters.

#### Other areas of Mautic that may be affected by the change:
1. Dynamic web content

#### List deprecations along with the new alternative:
1. None

[//]: # ( As applicable: )
#### List of areas covered by the unit and/or functional tests:
1. There are no tests because the changes were made in the JS and PHPUNIT cannot test JS.

### CODE REVIEW

**Review by rahuld-dev — DISMISSED** [review]
Thanks @escopecz

**Review by andersonjeccel — APPROVED** [review]
It works


https://github.com/user-attachments/assets/477ff5ef-9c7e-46c8-b470-f7d0a854d66e

**Review by andersonjeccel — CHANGES_REQUESTED** [review]
I'll just ask to reinitialize the Bootstrap tooltips after cloning, since it disappears after the first row

**Review by kuzmany — DISMISSED** [review]
I did test and works for me for new/edited segments.
This is great improvement.
Code looks good to me.

👍

**Review by shinde-rahul — APPROVED** [review]
Code LGTM!!!

**Review by LeonOltmanns — COMMENTED** [review]
The feature worked for me, but I found one small design flaw: When copying a Segment Membership filter or Multiselect-Filter the UI changes to a list view for the filter that was copied:

image

**Review by luke-42 — CHANGES_REQUESTED** [review]
Cool feature—it worked for me!

However, when copying Tags or Multiselect Segment Membership, the UI changes slightly. After saving and re-open the the segment filter, the UI then appears correctly.

image

**Comment by escopecz** [comment]
Thank you all for detailed testing!

@andersonjeccel I fixed the tooltips in https://github.com/mautic/mautic/pull/14214/commits/a18fb35d7ce2b8ddba9835bdfa58af722d801f80

@oltmanns-leuchtfeuer @luke-42 the chosen JS UI is fixed in https://github.com/mautic/mautic/pull/14214/commits/835f6b5e8ef3395235c40cfeb869f89dafec5645

Ready for re-test.

**Review by LeonOltmanns — APPROVED** [review]
LGTM! JS UI is now fixed, thank you so much! :)

**Review by andersonjeccel — APPROVED** [review]
It works and tooltips OK 

image

Thank you

**Pull request merged**
