### PR TITLE
More email and builder changes

### LINKED ISSUE #385: 404 error when clicking on 'view email online' link in emails sent to users via form submission
I used the view online text macro to insert the view online notice on an email, but when I tried to click on that link I get a 404 - for reference, the URL is: http://mymauticinstall.com/email/view/554e3a238f405 running v1.0.5.

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**

This PR piggy backs on #463.

1) It updates the email and page forms to match the mock ups in #463.  It also adds support for visual placeholders for some of the tokens like lead fields and forms rather than raw tokens text.
2) It breaks emails into two categories, "template" and "list."  A template email can be used for campaigns, forms, etc and is editable and publishable/unpublishable for temporary disabling.  A "list" email can only be manually sent to a lead list and does not use a publish status.  Once sent, it cannot be edited however it can be sent to new leads on the list. The list and details views have been updated to match.
3) Emails can send assets as attachments which are configurable through the email form.
4) Stats are stored for users as well as leads so that viewing the email via a web link work (fixes #385).  The body of the email is now stored in the stat entry and used for the web view. All opens are now tracked (open count, open date, user agent); no UI for them yet though.

_Notes_
It adds to the existing migration file in #463. Thus the schema should be at 1.0.5 before running the migration command if you are using a DB used to test #463.  Make a backup :-)

Clear both the file cache and browser cache after applying the PR for testing.

**Testing**

Migration - The migration for emails was a bit tricky. Because we allow emails to be sent to both lists and to be used as templates in campaigns, etc, we couldn't just assume one type over the other. Otherwise end users would be forced to resend cloned emails to leads, etc. We couldn't assume "list" emails since the email IDs are embedded in serialized properties all over the place.  So, the migration file will search email stats and determine if any email has been sent to a specific lead list. If it has, that email will then be copied, along with it's variants, and made into a "list" email. Existing stats for the emails sent to a list will be updated to associate with the new clones if applicable.  The script will then make some calculations based on the sent entries to determine sent counts, read counts, and variant counts for the existing "template" email vs the new cloned "list" email.

To successfully test the migration script, emails need to be sent to both lead lists and sent via a campaign or form submission (or at least manually manipulate the email_stats table to mimic it).  Also, be sure to test with a variant or two.

You will also need to have at least one "custom HTML" and one template based email and landing page.

_Migration testing_

1) No errors executing the new schema changes.
2) Emails sent to a lead list were successfully cloned along with all it's variants.
3) Stat counts were updated to reflect the number of emails sent to the list vs those sent via a campaign, etc.
4)  Custom HTML based emails and landing pages should default with a theme of "None." Original template based emails should have the appropriate theme still chosen.
5) Email subjects should have been copied over to the email names
6) The migration file also includes rebuilding all the forms to update the cached HTML from changes in other PRs so preview the forms afterward and make sure they are intact.

_Feature testing:_

1) Test the email and page forms:
* Changing the theme from None to something should mask the Body/Custom HTML editors and visa versa.  
* If the theme has None, clicking the Builder icon should pull in content from the Body/Custom HTML and closing should inject changes back into them
* Adding a form to a landing page or a lead field to an email should use a visual placeholder rather than a raw token. The placeholder should be editable other than deleted.   Save the contents and check the database to ensure the visual HTML contents were converted to the raw token.  Reopening a form should covert the token back to the visual placeholder. (Links do not use a visual placeholder since they are links to begin with).
* Adding assets to an email should dynamically update the total size badge above the select box

2) Sending assets via email
* Assign an asset(s) to an email then send it to a test list.  The attachments should be attached to the received email of course and a download stat recorded for the lead.

3) Open a sent email and check the email_stats table.  Each time the email is opened, the open count should go up, the latest open date should update, and an entry is added to the currently array serialized column 'open_details'. Eventually we'll work these into a UI.

4) Emails are successfully sent via campaigns or form submission and to a list.

### CODE REVIEW

**Comment by escopecz** [comment]
While preparing email variants for testing migration script I had to fix https://github.com/mautic/mautic/pull/490. Also, when I save and close the email variant and I'm redirected to email view, I get this error:
```
500 Internal Server Error - An exception occurred while executing 'SELECT e.email_id, count(e.id) as the_count FROM mau_email_stats e WHERE (e.is_failed = 0) AND (e.email_id IN (8, 9)) AND (e.date_read >= '2015-06-01 12:46:29') GROUP BY e.email_id': SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: boolean = integer LINE 1: ...e_count FROM mau_email_stats e WHERE (e.is_failed = 0) AND (... ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.
```
called from `/app/bundles/EmailBundle/Entity/StatRepository.php (line #149): at Doctrine\DBAL\Query\QueryBuilder -> execute ( )`

**Comment by alanhartless** [comment]
Guessing you're using Postgres? Are you able to get a trace on that error? I'm thinking it's actually related to code that's been there for a while it looks like we have a few stats where we are doing something like is_failed = 0 which will fail for postgres because it's a boolean field.

**Comment by alanhartless** [comment]
@escopecz See if that last commit solves your 'boolean = integer' query issue

**Comment by escopecz** [comment]
I pulled fresh Mautic from master branch. Then I created some leads, a list, emails, form, pages, email stats.
Then I applied this PR, cleared dev cache. Then tried to migrate. Here is the output:
```
$ php app/console doctrine:migration:migrate
...
Migrating up to 20150521000000 from 0
  SS skipped (Reason: Schema includes this migration)
  SS skipped (Reason: Schema includes this migration)
  SS skipped (Reason: Schema includes this migration)
  ++ migrating 20150310000000
Migration 20150310000000 was executed but did not result in any SQL statements.
  ++ migrated (0.5s)
  SS skipped (Reason: Schema includes this migration)
  SS skipped (Reason: Schema includes this migration)
  ++ migrating 20150521000000
Migration 20150521000000 failed during Execution. Error Notice: Array to string conversion in /var/www/html/mautic-github2/app/migrations/Version20150521000000.php line 461
                                                    
  [Symfony\Component\Debug\Exception\ContextErrorException]                                                       
  Notice: Array to string conversion in /var/www/html/mautic/github2/app/migrations/Version20150521000000.php line 461  
```
Line 461:
```php
$this->addSql('CREATE INDEX ' . $this->generatePropertyName('email_assets_xref', 'idx', array('email_id') . '  ON ' . $this->prefix . 'email_assets_xref (email_id)'));
```

**Comment by alanhartless** [comment]
@escopecz Sorry; try the latest commit.

**Comment by dbhurley** [comment]
:+1: Works as expected and looks **way** better :sunglasses:

**Comment by escopecz** [comment]
I tried to restore the database backup from before migration, pull staging (since this is merged) and run the migration again and get this error:
```
...
     -> ALTER TABLE pages ALTER template DROP NOT NULL
Migration 20150521000000 failed during Post-Checks. Error An exception occurred while executing 'INSERT INTO emails (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, id, name, description, subject, from_address, from_name, reply_to_address, bcc_address, template, lang, content, plain_text, custom_html, email_type, publish_up, publish_down, read_count, sent_count, revision, variant_settings, variant_start_date, variant_sent_count, variant_read_count, category_id, variant_parent_id, unsubscribeform_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1, "2015-06-04 07:34:34", 1, "John Linhart", "2015-06-03 09:22:19", 1, "John Linhart", null, null, "John Linhart", 5, "Email A1 - custom HTML", null, "Email A1 - custom HTML", null, null, null, null, "", "en", "a:0:{}", null, "<html>\n<head>\n\t<title><\/title>\n<\/head>\n<body>\n<p>Hello. this is version<\/p>\n<\/body>\n<\/html>", "list", null, null, 0, 3, 1, "a:2:{s:6:\"weight\";i:50;s:14:\"winnerCriteria\";s:14:\"email.openrate\";}", "2015-06-03 08:57:12", 3, 0, null, null, null]:

SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "content_mode" violates not-null constraint
DETAIL:  Failing row contains (5, null, null, null, t, 2015-06-04 07:34:34, 1, John Linhart, 2015-06-03 09:22:19, 1, John Linhart, null, null, John Linhart, Email A1 - custom HTML, , en, a:0:{}, null, <html>
<head>
	<title></title>
</head>
<body>
<p>Hello. this is ..., null, null, null, 0, 3, 1, a:2:{s:6:"weight";i:50;s:14:"winnerCriteria";s:14:"email.openrat..., 2015-06-03 08:57:12, 3, 0, Email A1 - custom HTML, null, null, null, null, null, list).
...
```

**Pull request merged**
