### PR TITLE
Improve APCu support

### LINKED ISSUE #8208: Error apc_clear_cache with PHP 7
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Fatal error with apc_clear_cache function running PHP 7
When you are trying to create a dev environment in Mautic with PHP 7, apc_clear_cache is not working with PHP 7. The new name in PHP 7 is apcu_clear_cache.

You can try to create a function to detect php version to use one or the other one.

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.2.22
| Browser | 

### Steps to reproduce
1. Install or upgrade to PHP 7
2. Try to create a dev environment
 
### Log errors
Fatal error: Uncaught Error: Call to undefined function apc_clear_cache() in /var/www/html/index_dev.php:24 Stack trace: #0 {main} thrown in /var/www/html/index_dev.php on line 24

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/85198566-error-apc_clear_cache-with-php-7?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by heathdutton**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | Fixes #8208
| BC breaks? | No
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
There were a few APC-specific functions that will not work in PHP 7 where APCu has supplanted those methods. In addition, when available APCu caching should be used for metadata and query caching (not results) for a small bump in performance.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. You should be able to log in, and edit a contact.
3. Save changes and refresh and see your changes to the contact.

### CODE REVIEW

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@heathdutton looks like this PR needs to be rebased & conflicts addressed, would you be able to take a look please?

**Comment by RCheesley** [comment]
@heathdutton this is now throwing an error when I apply the PR:

```
Error: Class 'Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle' not found
/app/AppKernel.php:116
/app/AppKernel.php:116 at
/vendor/symfony/http-kernel/Kernel.php:446 at AppKernel -> registerBundles ( )
/app/AppKernel.php:240 at Symfony\Component\HttpKernel\Kernel -> initializeBundles ( )
/app/AppKernel.php:82 at AppKernel -> boot ( )
/app/middlewares/CORSMiddleware.php:91 at AppKernel -> handle ( object(Request), '1', true )
/app/middlewares/CatchExceptionMiddleware.php:43 at Mautic\Middleware\CORSMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/Dev/IpRestrictMiddleware.php:61 at Mautic\Middleware\CatchExceptionMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/VersionCheckMiddleware.php:67 at Mautic\Middleware\Dev\IpRestrictMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/TrustMiddleware.php:51 at Mautic\Middleware\VersionCheckMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23 at Mautic\Middleware\TrustMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/run/src/Stack/run.php:13 at Stack\StackedHttpKernel -> handle ( object(Request) )
/index_dev.php:32 at Stack\run ( object(StackedHttpKernel) )
```

Guessing this PR will need to be updated if it is still relevant?

**Comment by RCheesley** [comment]
Just trying to see if merging in the latest features branch updates will fix the issue!

**Comment by RCheesley** [comment]
@heathdutton seems that this PR is [failing with MariaDB](https://github.com/mautic/mautic/pull/7215/checks?check_run_id=2428300409#step:8:15) with the error:

> Unknown cache of type "apcu" configured for cache "metadata_cache" in entiy manager "default". 

Could you take a look?

I tested it and was able to edit a contact per the description.

**Pull request closed without merging**
