### PR TITLE
Froala library updated from 2.3.3 to 2.3.4

### PR DESCRIPTION
**Pull request by escopecz**
| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | /
| BC breaks? | N
| Deprecations? | N

#### Description:
Release notes: https://github.com/froala/wysiwyg-editor/releases/tag/v2.3.4

#### Steps to test this PR:
1. Test Froala editor in different Mautic pages and make sure all the functionality still work

### CODE REVIEW

**Comment by mqueme** [comment]
+1

**Comment by alanhartless** [comment]
Something with this seems to have reverted the gated video placeholder CSS in the Content tab ( still works in the builder).

**Comment by alanhartless** [comment]
But otherwise - I tried landing pages, emails, direct emails, and description editors and it seemed to work OK.

**Comment by dongilbert** [comment]
+1

@alanhartless - I've tested this and as you found it working. I'll resolve the gated video Content tab editing in another PR

**Pull request merged**
