### PR TITLE
API Bug Fixes for Email & Page Endpoints

### PR DESCRIPTION
**Pull request by drmmr763**
fix property error with readInBrowser for API. Fix out of order max depth method parameters for email and page bundles

### CODE REVIEW

**Comment by alanhartless** [comment]
:+1:

**Comment by escopecz** [comment]
Is there a way to test it?

**Comment by dbhurley** [comment]
+1 to code

**Comment by drmmr763** [comment]
@escopecz if you want to test this, you can reproduce the error by getting a page via the API endpoint.

**Comment by escopecz** [comment]
Yeah, by retrieving a page via API, I got this error
```
Warning: Creating default object from empty value in app/bundles/ApiBundle/Serializer/Driver/ApiMetadataDriver.php line 304
```
And this PR fixed it. :+1:

**Pull request merged**
