### PR TITLE
Mitigate missing country flags when a contact is rendered

### LINKED ISSUE #12863: Contact associated with Åland Islands: Error 500
### Mautic Version

5.0.x series

### PHP version

8.0.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

When creating a new contact and assigning the country "Åland Islands" to it, an error 500 occurs after saving. If we attempt to navigate to the contacts page, access is denied.

### How can we reproduce this issue?

Step 1: Navigate to the "Contacts" page.
Step 2: Create a new contact.
Step 3: Enter the name and email, and select "Åland Islands" from the "Country" dropdown.
Captura de ecrã 2023-11-03 104316
Step 4: Afterward, click "Save & Close". and an error 500 will be displayed.
(Optional) Step 5: When attempting to access the "Contacts" page, it denies us entry, and we remain on the same page.

----

image

I suspect that the problem may be related due to be missing the flag of that specific country/province?

### Relevant log output

```shell
[2023-11-03T10:52:53.287132+00:00] mautic.CRITICAL: Uncaught PHP Exception TypeError: "Mautic\CoreBundle\Twig\Extension\AssetExtension::getCountryFlag(): Return value must be of type string, bool returned" at /var/www/html/app/bundles/CoreBundle/Twig/Extension/AssetExtension.php line 162 {"exception":"[object] (TypeError(code: 0): Mautic\\CoreBundle\\Twig\\Extension\\AssetExtension::getCountryFlag(): Return value must be of type string, bool returned at /var/www/html/app/bundles/CoreBundle/Twig/Extension/AssetExtension.php:162)"} {"hostname":"8d0f74ea457d","pid":150487}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #12863  

#### Description:

see #12863

This PR mitigates the issue, and ensures the return value corresponds with the expected result for the method.

This is a bare minimum mitigation, as the proper solution is to use a lib like https://github.com/thephpleague/iso3166

#### Steps to test this PR:

see #12863

### CODE REVIEW

**Comment by kuzmany** [comment]
Seems duplicate of https://github.com/mautic/mautic/pull/12630

**Review by kuzmany — COMMENTED** [review]
I noticed it few times and this could fixed it

**Comment by escopecz** [comment]
@mollux @galvani could you please check the [duplicate PR](https://github.com/mautic/mautic/pull/12630) and decide which PR is the way to go?

**Review by escopecz — APPROVED** [review]
👍

**Pull request merged**
