### PR TITLE
fix a report with the same values in the bounced and unsubscribed columns

### LINKED ISSUE #8476: The Bounced and Unsubscribed columns display a wrong value in a report for a data source of emails.
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The bounced and unsubscribed columns display the same value for all emails.

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.1
| Browser | All

### Steps to reproduce
1. Send emails through an email channel.
2. Create a report based on data source of emails (Emails: Emails)
3. In the Data tab add the Unsubscribed and Bounced columns for displaying in the report.
4. Save the report.

#### The current result
The value is the same for all emails.

image

#### The expecting result
The value is unique for each email.

image

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by WaldemarOrobanche**
closes #8476 

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | yes
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #8476 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
The bounced and unsubscribed columns display the same value for all emails.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Send emails through an email channel.
2. Create a report based on data source of emails (Emails: Emails)
3. In the Data tab add the Unsubscribed and Bounced columns for displaying in the report.
4. Save the report.

### CODE REVIEW

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
Close & reopen for Scrutinizer

**Review by RCheesley — APPROVED** [review]
Confirm the issue:

screenshot-local mautic3-2020 06 27-16_16_53

After applying the patch the behaviour is as expected. 

screenshot-local mautic3-2020 06 27-16_18_28

Thanks for the contribution @WaldemarOrobanche!

@dennisameling could you review the migration please?

**Comment by dennisameling** [comment]
Can confirm the issue: 
image

After applying this PR works as expected:

image

Both the code and the DB migration look good to me as well. Thanks @WaldemarOrobanche! 🚀

**Review by dennisameling — APPROVED** [review]
Can confirm the issue: 
image

After applying this PR works as expected:

image

Both the code and the DB migration look good to me as well. Thanks @WaldemarOrobanche! 🚀

**Pull request merged**
