### PR TITLE
Fix: Domain match when submitting form when Mautic is installed in subfolder

### PR DESCRIPTION
**Pull request by chrisschrijver**
When mautic is installed in subfolder the check fails since the MauticDomain is example.com/mautic and the event.origin is example.com. This will fix it.

### CODE REVIEW

**Comment by AndrassGray** [comment]
This is similar/identical to solutions proposed in #4656

No idea, though, why all suggested solutions are rejected.

**Comment by alanhartless** [comment]
@AndrassGray This might work if testing confirms.

 #4656 was rejected because the check itself was simply removed which is not a good idea due to https://github.com/mautic/mautic/pull/4656#issuecomment-323663700.

**Comment by AndrassGray** [comment]
@alanhartless Oh, I am aware as to why you rejected this particular PR. But I am not sure I understand why you left this bug open since at least 2.9.2 when several working solutions have been presented. Is this some sort of educational punishment "we only fix bugs if you supply a PR" ?

**Comment by alanhartless** [comment]
@AndrassGray That was definitely *not* our intention.

**Comment by khaoua** [comment]
anyone succeed with this correction after upgrade on 2.12.2?

**Comment by fixmyinfo** [comment]
I am wondering if this is still working in v2.15.0? I am seeing the same issue now, and I made those changes with no luck.

**Comment by ChrisRAoW** [comment]
@fixmyinfo What is it you experience exactly?

**Pull request merged**
