### PR TITLE
Support EU region for sparkpost

### PR DESCRIPTION
**Pull request by rohitpavaskar**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [N]
| New feature/enhancement? (use the a.x branch)      | [Y]
| Deprecations?                          | [N]
| BC breaks? (use the c.x branch)        | [N]
| Automated tests included?              | [Y] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This will allow user to configure SparkPost with EU region.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Go to Config option and choose "Email Setting"
3. Select "Sparkpost in "Service to send mail through ".
4. You should able to see Dropdown to choose Sparkpost Region.
5. Send should be sent through that SparkPost region.
6. Same thing will apply while installing Mautic.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11281"></a>

### CODE REVIEW

**Review by RCheesley — APPROVED** [review]
Thanks for the PR @rohitpavaskar - was able to successfully set up Sparkpost to use the EU rather than US option, it accepted the API key and all was well!

**Review by jos0405 — APPROVED** [review]
API Key working in EU as well. Thx for the PR.

**Comment by jos0405** [comment]
@escopecz , do we still need code review or 2 user reviews are enough?

**Review by escopecz — APPROVED** [review]
Code looks good 👍

**Pull request merged**
