### PR TITLE
Allow composer scripts to use php-cs-fixer configuration to allow multiple files at once

### PR DESCRIPTION
**Pull request by tejasync**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🚫 
| New feature/enhancement? (use the a.x branch)      | enhancement
| Deprecations?                          | 🚫 
| BC breaks? (use the c.x branch)        | 🚫 
| Automated tests included?              | 🚫  
| Related user documentation PR URL      | 🚫  
| Related developer documentation PR URL | 🚫  
| Issue(s) addressed                     | 🚫  

#### Description:
Whenever `composer fixcs` is executed, it does not use configurations mentioned in `.php-cs-fixer.php`. This PR allows composer scripts to use the php-cs configurations explicitly.
The advantage of this is mentioned in the comment below: https://github.com/mautic/mautic/pull/10624#issuecomment-1049763294

#### Steps to test this PR:
1. Modify any PHP file such that there will be CS fixed to be done, like add spaces between assignment operator.
2. Run `composer fixcs`.
3. Observe that, the composer script does not use `.php-cs-fixer.php` configuration.

1. Load up [this PR](https://mautibox.com)
2. Follow steps to test this PR.
3. Observe `.php-cs-fixer.php` configuration being used and file is CS fixed.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10624"></a>

### CODE REVIEW

**Review by kuzmany — APPROVED** [review]
👍

**Comment by biozshock** [comment]
Will not hurt, but in default configuration the config file is resolved properly.
```
$ composer fixcs
> bin/php-cs-fixer fix -v
You are running PHP CS Fixer v2, which is not maintained anymore. Please update to v3.
If you need help while solving warnings, ask at https://gitter.im/PHP-CS-Fixer, we will help you!

PHP CS Fixer 2.19.2 Testament by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 7.4.26
Loaded config default from "/var/www/html/.php-cs-fixer.php".
```
Maybe composer is called from an invalid CWD? See https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.19.2/src/Console/ConfigurationResolver.php#L638

**Comment by tejasync** [comment]
The advantage of this is that it will allow multiple files when you do `composer fixcs`.

For e.g.
Without specifying the config path, `"fixcs": "bin/php-cs-fixer fix -v"`, using `composer fixcs` generates following error:
Screenshot 2022-02-24 at 16 57 00


With specifying the config path: `bin/php-cs-fixer fix --config=.php-cs-fixer.php --using-cache=no -v`, using `composer fixcs` works for multiple files:
Screenshot 2022-02-24 at 16 56 22

**Comment by tejasync** [comment]
@RCheesley Could you please take a look at above comment: https://github.com/mautic/mautic/pull/10624#issuecomment-1049763294 and delegate?

**Comment by RCheesley** [comment]
@biozshock can you confirm that with this PR all is working as expected in your situation? If this PR resolved the problem in Composer and doesn't impact non-composer instances, we should be good to go.

**Comment by biozshock** [comment]
@RCheesley as i already wrote before: this won't hurt and does not change anything critical. By default the same config file is loaded.

Though i'd say this is not a problem of mautic itself, so should not be fixed to allow later to use `.dist` file if mautic team will decide to do so.

Also the same result can be achieved without changing codebase (no code is best code):
```
$ composer fixcs app/bundles/ApiBundle/Controller/ClientController.php app/bundles/ApiBundle/Controller/CommonApiController.php -- --config=.php-cs-fixer.php
> bin/php-cs-fixer fix -v 'app/bundles/ApiBundle/Controller/ClientController.php' 'app/bundles/ApiBundle/Controller/CommonApiController.php' '--config=.php-cs-fixer.php'
You are running PHP CS Fixer v2, which is not maintained anymore. Please update to v3.
You may find an UPGRADE guide at https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.3.0/UPGRADE-v3.md .
If you need help while solving warnings, ask at https://gitter.im/PHP-CS-Fixer, we will help you!

PHP CS Fixer 2.19.3 Testament by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 7.4.26
Loaded config default from ".php-cs-fixer.php".
Using cache file ".php_cs.cache".
Paths from configuration file have been overridden by paths provided as command arguments.
SS
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error

Fixed all files in 0.004 seconds, 18.000 MB memory used
```

**Review by kuzmany — APPROVED** [review]
Confirm, It return error If you add two files at least to command fixcs  like

 `composer fixcs app/bundles/UserBundle/Controller/PublicController.php app/bundles/EmailBundle/MauticEmailBundle.php`
 
 After PR work without issue

**Review by kuzmany — APPROVED** [review]
Confirm, It return error If you add two files at least to command fixcs  like

 `composer fixcs app/bundles/UserBundle/Controller/PublicController.php app/bundles/EmailBundle/MauticEmailBundle.php`
 
 After PR work without issue

**Pull request merged**
