### PR TITLE
M3 Amazon SES API mail transport

### LINKED ISSUE #1740: Feature Request: full amazon ses integration
## Description

For now it seems to me that the sns integration is rather basic. I believe it would be a big advantage to fully integrate it. For now, it seems to me that neither bulk sending through post api nor bounce/complain handling is supported.
## Integration Steps
- Sending bulk emails through ses post api
- Throttling email sending according to limits, retry later if limit is reached
- Proper error handling
- Handle bounces and complaints through sns
- ~~Allow all aws availability zones (eu-west-1, ireland and a third availability zone allow email sending, but mautic only supports us-west-1)~~

### LINKED ISSUE #7402: Email delivery is very slow - monitor campaign delivery time?
We face very slow campaign delivery timings while have quite fast email delivery backend (PowerMTA). I was wondering if there is a way to see/track following data:

- email campaign started sending
- email campaign finished sending

This can help to start debugging in first place. I don't seem to see this information in campaign itself or anywhere in mautic interface. Logs don't contain anything related to issues with email delivery.

Thanks in advance.

### PR DESCRIPTION
**Pull request by wise-gorilla**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | No
| New feature? Yes| 
| Automated tests included? |No
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | Closes #1740, Resolves #7402, Mautic 3.x port of #6977 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR is an update for #6977 to allow it to work on Mautic 3.0 and also it adds several features and enhancments as follow and refactoring some deprecated codes..
1- ConfigurationSetName support
2- Reply-To support
3- ReturnPath support
4- RawEmail custom headers support
5- getMaxBatchLimit increased to 50 to increase sending speed
6- Add all avilable SES regions to Mautic settings

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. Load up [this PR](https://m3.mautibox.com)
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by mabumusa1** [comment]
@Wise-Gorilla How can I help? what is blocking you? from finishing this?

**Comment by wise-gorilla** [comment]
@mabumusa1 I was able to get SES API to work properly with Mautic 3.0 but im stuck with the automated unit testing, if you or anyone interested in making this PR ready to get merged in Mautic 3.1 then you can contact me to give you a write access to this PR or maybe create a new PR and use this PR as a refrance for how to get the original PR to work in M3.

**Comment by mabumusa1** [comment]
@Wise-Gorilla please give me write access to this PR, I already wrote the test suite for it. it works now

**Comment by wise-gorilla** [comment]
Hi @mabumusa1 I sent you an invitation

**Comment by mabumusa1** [comment]
@Wise-Gorilla I added some tests but it seems to be failing, maybe we need to look further into this. I will add more tests locally and fix the results. Probably I will have it ready by tomorrow

**Comment by wise-gorilla** [comment]
@mabumusa1 btw i see that you pushed many commits from other PRs

**Comment by mabumusa1** [comment]
@Wise-Gorilla are you on slack? I think I pushed the wrong branch

**Comment by chescos** [comment]
Thanks for working on this guys :heart:

**Comment by mabumusa1** [comment]
@Wise-Gorilla I made some changes to the pull request on https://github.com/mautic/mautic/pull/9005

Please review and merge to staging if everything is working as expected

**Comment by wise-gorilla** [comment]
Continuing working on that feature on #9005

**Pull request closed without merging**
