### PR TITLE
DPMMA-2679 Fix: Letters disappear when searching for emails to send in Campaign Builder

### LINKED ISSUE #13555: Letters get deleted while seaching for email to send in campaign builder
### Mautic Version

5.0.x series

### Way of installing

Other (please specify if relevant in the bug report)

### PHP version

8.2.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

After adding a "Send email" action to campaign and searching for email to send, letters get deleted while typing quickly.
Happens especially when searching for names that have the same beginning.
Tested on Gitpod (v5.0.3)

### How can we reproduce this issue?

1: Create some template emails that start the same, for example email1, email2, email template etc.
2: Create or edit a campaign
3: In builder, add "Send email" action
4: Search for email to send, for example "email"
5: When typing, letters get deleted when search for matching emails is performed - for example, "a" and "i" get deleted while typing
image
image

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #13555

## Description
This PR fixes the issue with email search in select described in #13555 and https://forum.mautic.org/t/campaign-editor-bug-when-searching-an-email/25465/16

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Follow the steps to reproduce in #13555

### CODE REVIEW

**Review by tomekkowalczyk — APPROVED** [review]
I tested manually this fix.  Changes looks good.

**Review by abhisekmazumdar — APPROVED** [review]
With these changes, I don't see disappearing characters if you type fast. Works as expected

**Comment by IonutOjicaDE** [comment]
I implemented these changes manually in mautic 4 and I do not see any difference. I have 42 template emails in my list and the letters are missing when I type fast. Is here something different to mautic 5 or you test with only a very small sample of template emails?

**Comment by patrykgruszka** [comment]
Did you rebuild the assets with `mautic:assets:generate`? https://docs.mautic.org/en/5.x/configuration/command_line_interface.html

**Comment by IonutOjicaDE** [comment]
No, at that time I did not rebuild the assets using that command. I see it for the first time.
Now I did executed it, cleared the cache, and the letters are still disappearing (do I have to clear the cache for the rebuild to work?).
Do we have to overwrite the content inside the field? Would not be enough just to update the appearing drop-down list and to not touch the textbox content?

**Comment by patrykgruszka** [comment]
@IonutOjicaDE, you only need to run the `mautic:assets:generate` command, which should generate new JS and CSS files. Also, your browser might be loading the old files from its cache, so clearing the browser cache should help in this case.

**Comment by IonutOjicaDE** [comment]
That was: the **browser cache**. It works also in Mautic 4.4.11 . Thank you many times!!!

**Pull request merged**
