### PR TITLE
Change Successful Submit Action of form behaviour

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR just reorder option for forms Successful Submit Action select box. 
Add Remain at form on the last possition. Also hide message input If you choose this input

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Just create form and check If
Message is first option from Successful Submit Action and selected by defaul:
image
3. Check also If message input is hidden of select option Remain at form

image

### CODE REVIEW

**Review by PatrickJenkner — APPROVED** [review]
Works as described 👍 
FYI: If you set & save a submit message and then change to "remain at form", the message still gets displayed, even though the field is no longer visible (and the message cannot be changed). Don't know if this is intentional

**Comment by kuzmany** [comment]
> FYI: If you set & save a submit message and then change to "remain at form", the message still gets displayed, even though the field is no longer visible (and the message cannot be changed). Don't know if this is intentional

Seems bug.

**Comment by kuzmany** [comment]
@PatrickJenkner

>  If you set & save a submit message and then change to "remain at form", the message still gets displayed


Where does it still get displayed? I try submit form and success message is not there

**Comment by PatrickJenkner** [comment]
Form

It's displayed like any other message, even though I don't have it enabled in my settings:

Setting

**Comment by code5rick** [comment]
@PatrickJenkner , there are indeed **UX issues** with the form on various fronts:

1. The success message should be positioned at the bottom of the form, below the submit button. In cases where a large form is submitted successfully, users may not realize that the form was submitted because the message is displayed at the top of the page, far from the form. I believe the optimal solution for this issue is to introduce a parameter that allows users to choose the position for displaying the message: either at the top or at the bottom.
image

2. In the form settings, the "Redirect URL/Message" field is always visible, even if the user doesn't use the associated parameter. A simple solution would be to hide the field when it's not in use and display it only when the user selects parameters that require it.
image

**Comment by kuzmany** [comment]
@code5rick don't know why you mention @PatrickJenkner , but :

1. In M5 alpha we added an option to display messages on top or bottom https://github.com/mautic/mautic/pull/10726 
2. It works like you wrote.

**Comment by kuzmany** [comment]
@PatrickJenkner thanks, fixed

**Comment by RCheesley** [comment]
Marking this one as RTC with code review as the issues raised are not related to this PR. Thanks folks!

**Comment by RCheesley** [comment]
@kuzmany as this is an enhancement could you please rebase to 5.1 as that's where it will be released. Thanks!

**Comment by kuzmany** [comment]
@RCheesley rebased

**Comment by RCheesley** [comment]
Thanks so much @kuzmany 🚀

**Review by nick-vanpraet — APPROVED** [review]
code looks good

**Review by Mike-Dropsolid — APPROVED** [review]
Works as described.

**Review by escopecz — APPROVED** [review]
👍

**Pull request merged**
