### PR TITLE
Add support for list inserted/updated contacts in import

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| Automated tests included? | yes
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | no
| Deprecations? | no 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR added new clickable columns in Import history to display contacts related to status of each import (Inserted/Updated). 

image

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com/7171)
2. Import CSV Note: mock data can be generated at https://www.mockaroo.com/ very quickly/easily to test this PR!
3. Go to Import history
4. Click on columns and see If contacts display correctly based on import status

### CODE REVIEW

**Review by johbuch — DISMISSED** [review]
works perfectly. thanks zdeno

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebased

**Review by johbuch — DISMISSED** [review]
just tested with mautibox, it works

**Review by RCheesley — DISMISSED** [review]
Before patch there are no clickable columns:

screenshot-local mautic3-2020 08 14-22_41_46

Note: mock data can be generated at https://www.mockaroo.com/ very quickly/easily to test this PR!

After applying the patch I could click through to all records, and to all imported contacts. Filtering works great and confirmed that I was only seeing the contacts I expected to see.

screenshot-local mautic3-2020 08 14-22_47_28

screenshot-local mautic3-2020 08 14-22_47_50

Thanks for the improvement @kuzmany !

**Comment by RCheesley** [comment]
@kuzmany another one that needs some work on the automated tests, sorry! 😅

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by kuzmany** [comment]
@RCheesley unit tests added

**Review by npracht — DISMISSED** [review]
👍🏽 works very great and mentioned @RCheesley and now with Unit Tests :)

**Comment by kuzmany** [comment]
Does not work for companies import. Need touch

Dňa pi 14. 5. 2021, 10:53 Norman Pracht - Webmecanik <
***@***.***> napísal(a):

**Comment by tejasync** [comment]
Tested and works fine. Code LGTM! Thank you @kuzmany!

**Comment by RCheesley** [comment]
@kuzmany did you address the issue [here](https://github.com/mautic/mautic/pull/7171#issuecomment-841113233)?

**Comment by kuzmany** [comment]
@RCheesley yes, it was fixed in commits after that.

**Comment by RCheesley** [comment]
OK this is GTG then! :)

**Review by RCheesley — APPROVED** [review]

**Comment by RCheesley** [comment]
@all-contributors please add @johbuch for userTesting

**Pull request merged**
