### PR TITLE
Sugar Integration works better when the endpoint is using HTTP GET method

### PR DESCRIPTION
**Pull request by bodrak**
https://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_11.0/Integration/Web_Services/REST_API/Endpoints/modulefilter_GET/

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | 

#### Description:

Sugar filter endpoint is using HTTP GET method.
You can check documentation: https://support.sugarcrm.com/Documentation/Sugar_Developer/Sugar_Developer_Guide_11.0/Integration/Web_Services/REST_API/Endpoints/modulefilter_GET/
I was having issues with POST method, changing them to GET solved my issues.

#### Steps to test this PR:

1. Install Mautic with this PR
2. Install SugarCRM
3. Configure the Sugar plugin integration in Mautic to work with Sugar Leads
4. Create some Leads on Sugar
5. Run command: php bin/console mautic:integration:fetchleads --fetch-all --integration=Sugarcrm --time-interval=1day

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10667"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for the PR @bodrak - it's great to have someone contributing who uses Sugar!

Could you please sign the contributors agreement using the link above?

**Comment by bodrak** [comment]
ok I just did it @RCheesley

**Review by escopecz — APPROVED** [review]
This change makes sense 👍

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@bodrak we have not received your contributors agreement yet - can you please fill out the online form? It must state your GitHub username (bodrak) so that it matches up with the username on the PR. Thanks!

**Comment by bodrak** [comment]
@RCheesley ok it's done !

**Comment by RCheesley** [comment]
@cla-bot check

**Review by kuzmany — APPROVED** [review]
Good catch

**Comment by RCheesley** [comment]
@all-contributors please add @bodrak for code

**Pull request merged**
