### PR TITLE
Segment relative date

### LINKED ISSUE #9636: Relative dates in segments don't work
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
If you specify "10 days ago" in the filter for a field with the date type, the exact date will be saved instead of the relative date.

At the same time, the filter by date with the value "today" or" yesterday" works correctly.

| Q   | A
| --- | ---
| Mautic version | 3.2.5
| PHP version | 7.2

### Steps to reproduce
1. Create a segment with a filter by the relative date "2 days ago" or "3 months ago" , etc.
2. Save and then go to edit the segment. Instead of a relative date, there will be an exact date and even a time
3. At first, the segment will work, but as soon as more than a relative date passes in time, contacts with an outdated date will not be deleted from the segment.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by shinde-rahul**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [4.1]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | https://github.com/mautic/mautic-documentation/pull/289
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #9636 

#### Description:

Added new relative dates for segment filter,
- `'first day of '`
- `'last day of '`

#### Steps to test this PR:

1. Open this PR on Gitpod or pull-down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a segment with a filter by the relative date "2 days ago" or "3 months ago", etc.
3. Save and then go to edit the segment. Instead of a relative date, there will be an exact date and even a time
4. At first, the segment will work, but as soon as more than a relative date passes in time, contacts with an outdated date will not be deleted from the segment.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10822"></a>

### CODE REVIEW

**Comment by shinde-rahul** [comment]
PR https://github.com/mautic/mautic-documentation/pull/289 for documentation update.

**Comment by kuzmany** [comment]
@shinde-rahul 

If I add 2 days ago to field, after submit it's converted to regular datetime. See screenshot. Probably you forgot cherry pick something from your custom branch

image

**Comment by RCheesley** [comment]
Thanks for updating the PR @shinde-rahul - we will need it on the 4.x branch to get it into 4.2 but 4.1->4.x should not be too painful.

**Comment by RCheesley** [comment]
Thanks for writing the docs @shinde-rahul - have added the link to the PR description.

**Comment by shinde-rahul** [comment]
> @shinde-rahul
> 
> If I add 2 days ago to field, after submit it's converted to regular datetime. See screenshot. Probably you forgot cherry pick something from your custom branch
> 
> image

Hello @kuzmany, I am unable to reproduce the same consistently. I don't see any js changing this value. Diving deeper.
Note: All required commits related to changes are pushed.

**Review by escopecz — APPROVED** [review]
The code looks good, I'm able to see the relative date value after I save and reopen the segment edit page and the segment builds without any errors 👍

**Review by dadarya0 — APPROVED** [review]
Changes looks good to me, tested segment filter with relative date, Working as expected

**Comment by RCheesley** [comment]
Updated docs: https://github.com/mautic/user-documentation/pull/267

**Pull request merged**
