### PR TITLE
Fix doctrine fixtures double loading by Rahul Shinde

### PR DESCRIPTION
**Pull request by escopecz**
This is copy of changes from https://github.com/mautic/mautic/pull/10040 which couldn't be cherry-picked as the repo was deleted

Please refer to that PR for details. I'm just a messenger as the problem was recently reported again.

### CODE REVIEW

**Review by kuzmany — DISMISSED** [review]
Fixtures were loaded properly for me.

**Comment by escopecz** [comment]
Rebased to fix the conflicts. @RCheesley can you please give it a test since you were facing the duplicated contact fields during our community sprint in Prague? Does this solve the issue?

**Comment by RCheesley** [comment]
> Rebased to fix the conflicts. @RCheesley can you please give it a test since you were facing the duplicated contact fields during our community sprint in Prague? Does this solve the issue?

On it! 👀

**Review by RCheesley — APPROVED** [review]
screenshot-8080-escopecz-mautic-s6lvu6rn930 ws-eu71 gitpod io-2022 10 17-14_44_55

Works great, custom fields are no longer duplicated, and all other data is looking good too! Thanks @shinde-rahul @escopecz 🚀

**Pull request merged**
