### PR TITLE
TPROD-283: Refactor Symfony\Bundle\FrameworkBundle\Controller\Controller to Symfony\Bundle\FrameworkBundle\Controller\AbstractController

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Just refactor https://mautic.atlassian.net/browse/TPROD-283
Deprecated since Symfony 4.2, use "Symfony\Bundle\FrameworkBundle\Controller\AbstractController" instead.
Seems like works like before

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Just  code review 

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11142"></a>

### CODE REVIEW

**Review by RCheesley — CHANGES_REQUESTED** [review]
On testing this PR I am getting 500 errors in prod mode when trying to open the configuration (as this PR seems to be changing things related to that I thought I would test it rather than just relying on code review).

The error throw in developer mode is as follows:

```
The "Mautic\ConfigBundle\Controller\ConfigController::getParameter()" method is missing a parameter bag to work properly. Did you forget to register your controller as a service subscriber? This can be fixed either by using autoconfiguration or by manually wiring a "parameter_bag" in the service locator passed to the controller.
```

Stack trace:  

```
[2022-05-26 15:30:55] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "The "Mautic\ConfigBundle\Controller\ConfigController::getParameter()" method is missing a parameter bag to work properly. Did you forget to register your controller as a service subscriber? This can be fixed either by using autoconfiguration or by manually wiring a "parameter_bag" in the service locator passed to the controller." at /var/www/html/vendor/symfony/framework-bundle/Controller/AbstractController.php line 68 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): The \"Mautic\\ConfigBundle\\Controller\\ConfigController::getParameter()\" method is missing a parameter bag to work properly. Did you forget to register your controller as a service subscriber? This can be fixed either by using autoconfiguration or by manually wiring a \"parameter_bag\" in the service locator passed to the controller. at /var/www/html/vendor/symfony/framework-bundle/Controller/AbstractController.php:68)
[stacktrace]
#0 /var/www/html/app/bundles/ConfigBundle/Controller/ConfigController.php(261): Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController->getParameter('mautic.security...')
#1 /var/www/html/app/bundles/ConfigBundle/Controller/ConfigController.php(38): Mautic\\ConfigBundle\\Controller\\ConfigController->mergeParamsWithLocal(Array)
#2 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(447): Mautic\\ConfigBundle\\Controller\\ConfigController->editAction(0, '')
#3 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(158): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('edit', 0, 0, '')
#4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#5 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#6 /var/www/html/app/AppKernel.php(115): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#7 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#8 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#9 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#10 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#14 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#15 {main}
"} 
```

**Comment by kuzmany** [comment]
@RCheesley can you check now?

**Review by RCheesley — DISMISSED** [review]
All good, config is working fine!

There are some inline warnings on PHPSTAN to address I think though.

**Comment by kuzmany** [comment]
@RCheesley CI errors gone away

**Comment by RCheesley** [comment]
Great - just needs a code review. @mollux @escopecz @fedys if you have a chance :)

**Review by escopecz — APPROVED** [review]
I see no usage of `Symfony\Bundle\FrameworkBundle\Controller\Controller` anywhere else. There are some unrelated changes in this PR but they are improvements, so 👍

**Pull request merged**
