### PR TITLE
Fix typo on EmailModel and a null notice on segments

### LINKED ISSUE #9272: SQL Migration Issues -  v3.1 to v3.1.1
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I'm going to use this Issue to record a collection of issues that have popped up due to a migration issue that happens during the migration from v2.16 to v3.  Initial thread: #9129 

The below are additional issues that have popped up due to updating from 3.1 to 3.1.1.

| Q   | A
| --- | ---
| Current Mautic version | 3.1.1
| PHP version | 
| Browser | 

### Steps to reproduce
1.  Update from version 3.1.0 to version 3.1.1
 
### Form Submissions Issue - Failed Migration Tables
For some reason, the initial migration from v2.16 to v3 did not pull all of the form tables. - This isn't true. The migration pulls the tables, the Schema update seems to delete them.

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'main_mautic.ma_form_results_4_eguide__ba' doesn't exist at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'main_mautic.ma_form_results_4_eguide__ba' doesn't exist at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:75)"} []

### Email Charts Issue
This only effects new emails created in v3.1. Emails created before updating don't present this issue. On closer inspection, this is caused due to a maximum character limit set by the new collation.

[2020-10-06 14:50:48] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'SELECT count(DISTINCT .ph.lead_id) as click_count, cs.leadlist_id FROM ma_channel_url_trackables cut INNER JOIN ma_page_hits ph ON ph.redirect_id = cut.redirect_id AND ph.source = cut.channel AND ph.source_id = cut.channel_id INNER JOIN ma_lead_lists_leads cs ON cs.lead_id = ph.lead_id WHERE (cut.channel = ?) AND (cut.channel_id IN (83)) AND (cs.leadlist_id IN (87)) AND (ph.date_hit BETWEEN ? AND ?) GROUP BY cs.leadlist_id' with params ["email", "2020-09-06 00:00:00", "2020-10-06 14:50:48"]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.ph.lead_id) as click_count, cs.leadlist_id FROM ma_channel_url_trackables cut I' at line 1" at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 79 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'SELECT count(DISTINCT .ph.lead_id) as click_count, cs.leadlist_id FROM ma_channel_url_trackables cut INNER JOIN ma_page_hits ph ON ph.redirect_id = cut.redirect_id AND ph.source = cut.channel AND ph.source_id = cut.channel_id INNER JOIN ma_lead_lists_leads cs ON cs.lead_id = ph.lead_id WHERE (cut.channel = ?) AND (cut.channel_id IN (83)) AND (cs.leadlist_id IN (87)) AND (ph.date_hit BETWEEN ? AND ?) GROUP BY cs.leadlist_id' with params [\"email\", \"2020-09-06 00:00:00\", \"2020-10-06 14:50:48\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.ph.lead_id) as click_count, cs.leadlist_id FROM ma_channel_url_trackables cut I' at line 1 at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:79, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.ph.lead_id) as click_count, cs.leadlist_id FROM ma_channel_url_trackables cut I' at line 1 at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.ph.lead_id) as click_count, cs.leadlist_id FROM ma_channel_url_trackables cut I' at line 1 at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)"} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by rwrz**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #9272 

#### Description:
It doesn't show up on the dev application because we usually don't have "bounced" or "unsubscribed" leads on the database. It doesn't show on the test, because is a DB typo related.
This fixes the issue that was not showing graphs (stats) on the e-mail screen.

And, I was adding a new Segment to test on my dev environment, this notice showed up. So I fixed as well.
Null Notice:
```php
- Symfony\Component\Debug\Exception\ContextErrorException: PHP Notice - Trying to access array offset on value of type null
/app/bundles/LeadBundle/Views/FormTheme/Filter/_leadlist_filters_entry_widget.html.php:13
```

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Add 2 Leads
3. Send them an e-mail using template mail
3. Unsubscribe one
4. The e-mail graphs (stats) should keep loading forever

### CODE REVIEW

**Review by npracht — APPROVED** [review]
👍 good catch !

**Comment by RCheesley** [comment]
Thanks for making this contribution @rwrz much appreciated!

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
I'm struggling a tiny bit to test this as I can't reproduce the issue with the charts not loading. I've checked with the reports, dashboard widgets and the email overview itself in dev and prod mode and all seem to be loading OK.

Is there a particular chart/graph I should be looking at?

Testing on 3.1.2:

screenshot-local mautic3-2020 11 08-13_22_21

**Comment by rwrz** [comment]
Interesting. I think you tested using a Campaign E-mail, not a Segment e-mail... could you test sending a Segment e-mail instead?
btw, they have different chart types.

**Review by dadarya0 — APPROVED** [review]

**Pull request merged**
