### PR TITLE
Toogle for public preview of email

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/6668
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR added option to enable/disable public view of email preview. 
New decent toggle option added before public link.

image

Also this update allow developers  use this toggle button anywhere for any boolean type:

- example: https://github.com/mautic/mautic/pull/6679/files#diff-3533e31fe48dc7cc3fcadb14a34007b1R311
- just use customToggle in param `'query' => 'customToggle=publicPreview'`
- your entity require getter and setter for that parameter

#### Steps to test this PR:
1.  Create published email
2.  Copy preview link and open it in another/incognito brower
3.  Should see  preview of email
4. Go to detail page of email and disable toggle before preview link 
image
5.  Copy preview link and open it in another/incognito brower
6. Should see access denied page

### CODE REVIEW

**Comment by npracht** [comment]
Hi @kuzmany could we keep the link working for the logged in people ?

**Comment by kuzmany** [comment]
@npracht works in that way

**Comment by npracht** [comment]
[You're simply the best](https://www.youtube.com/watch?v=FqDZOekUDzE)

**Comment by kuzmany** [comment]
@Woeler It use accessDenied();  
https://github.com/mautic/mautic/blob/fb712fa52c16ff4902eb6260df35c4a3777ec789/app/bundles/EmailBundle/Controller/PublicController.php#L440

Mautic use it everywhere I think It's legit for this case.

**Pull request merged**
