### PR TITLE
Unify leads and contacts sync

### PR DESCRIPTION
**Pull request by enable-jon**
Loop over person types to better handle CRM sync where lead/contact objects
may have pluralised object names.

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | None 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
The SugarCRM integration requires that the objects fetched use a pluralised URL in the entity name. The existing array_map and strtolower comparison was failing to  convert Contact to Contacts, and rather than fix that immediate issue it made sense to loop over both person types applying the same logic, so the PR is a little larger than it might have been

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Set up the SugarCRM sync for both Contacts and Leads
2. Run the sync using verbose (-vv)
3. Watch the output - the contact API request to Sugar uses Contact rather than Contacts in the UR and provokes an error on the Sugar server (note: this is using PHP 5.6.30), because /rest/v10/Contact/filter is not a valid endpoint on a standard SugarCRM system.

#### Steps to test this PR:
1. Test every CRM integration sync for regressions

#### List deprecations along with the new alternative:
1. None anticipated
2. 

#### List backwards compatibility breaks:
1. None anticipated
2.

### CODE REVIEW

**Comment by escopecz** [comment]
Fix the [code standards issues](https://travis-ci.org/mautic/mautic/jobs/261201753#L1149) please

**Comment by escopecz** [comment]
@enable-jon could you please rebase or merge current staging into your branch and resolve conflicts?

**Comment by escopecz** [comment]
Ok, I tried to fix the merge conflict, but it did not go well. It shows so many changes now. Any ideas how to get rid of them?

**Comment by npracht** [comment]
@YosuCadilla is it not !

**Comment by YosuCadilla** [comment]
Anything I can do to help? Needs more testing maybe?

**Comment by Maxell92** [comment]
This PR is a mess. Is it possible to rebase it to actual staging or to create a new branch with your changes only?

It is impossible to do a code review + there are lot of changes which are not related to this PR.

**Comment by alanhartless** [comment]
Seems to be a bad merge in here somewhere?

**Comment by escopecz** [comment]
I caused it by trying to fix merge conflicts. I merged staging to this branch and this is the result. I cannot find what was the original code in those commits. So I'm afraid we'll have to close this PR and if @enable-jon has the local branch on his computer he can create new PR.

**Comment by dbhurley** [comment]
Not adding to 2.13 due to the massive, messiness, plus the apparent conflicts.

**Comment by Maxell92** [comment]
We are closing this PR because of conflicts. Need to be created a new one.

**Pull request closed without merging**
