### PR TITLE
TPROD-314 - DynamicContentBundle - Migrate PHP Templates to Twig Templates

### PR DESCRIPTION
**Pull request by JoshuaEstes**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. 

- `/s/dwc`
  - page renders with and without dynamic content
  - filter
  - sort columns
  - navigate multiple pages
- `/s/dwc/new` and `/s/dwc/edit/{id}`
  - page renders correctly
  - filters render correctly
  - **NOTE** see known issues
- `/s/dwc/view/{id}`
  - page renders without errors
  - translations tab only appears if the dynamic content is a translation of or has translations

https://github.com/mautic/mautic/pull/11797

**Known Issues**
* https://github.com/mautic/mautic/issues/11730
* https://github.com/mautic/mautic/issues/11290
* When creating or editing dynamic content, when you select **Create new** from the drop down on the **Is a translation of** field, it will not create a new dynamic content. It just updates the existing dynamic content and the modal stays open.
* Cloning an existing dynamic content will not clone the filters
* If you find a bug with the functionality, check the 4.x or 5.x branches to verify it exists there, if it does please let me know so I can see if it's an easy fix or not

### CODE REVIEW

**Review by mabumusa1 — CHANGES_REQUESTED** [review]
@JoshuaEstes Please check the issue below and increase code coverage

- [X] Dashboard works with no data
- [X] Create
- [X] Add Category 
- [X] Content Dashboard
- [X] Edit
- [X] Translation
- [X] Delete
- [X] Clone
- [ ] Filter (not tested)
- [ ] Global Search (not tested)
- [ ] Dashboard with data and categories
image

**Comment by JoshuaEstes** [comment]
@mabumusa1 

> Dashboard with data and categories

Resolved https://github.com/mautic/mautic/pull/11979/commits/d92b54f5fff241e6b6d49a4749a079f56dfb7270

> Global Search

It doesn't seem this bundle has that functionality.

**Review by mabumusa1 — DISMISSED** [review]
I tested again this PR is ready to go

**Comment by mabumusa1** [comment]
@JoshuaEstes please increase test coverage so we can merge this

**Review by daniellord32 — COMMENTED** [review]
- [x]  Dashboard works with no data
- [x]  Create
- [x]  Add Category
- [x]  Content Dashboard
- [x]  Edit
- [x]  Translation
- [x]  Delete
- [x]  Clone
- [x]  Filter from dashboard
- [x] filter
- []  Global Search (not tested)
- [x]  Dashboard with data and categories

**Comment by mabumusa1** [comment]
I tested with dynamic content without a campaign filters did show and a slot was assigned 

image

**Comment by RCheesley** [comment]
RTC as soon as tests are green 🚀 thanks everybody for all your awesome work with testing!

**Pull request merged**
