### PR TITLE
Check if an entity exists in dashboard subscriber for "Recent activity".

### LINKED ISSUE #11691: Removing a stage leads to 500 error on dashboard "Recent activity" widget
### Mautic Version

5.0.x series

### PHP version

8.0.x

### What happened?

After testing #11591 i have an exception on dashboard. Probably related?

### How can we reproduce this issue?

1. Make sure you have "Recent activity" widget on dashboard.
2. Create stage.
3. Remove stage.
4. Open dashboard.

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by biozshock**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ x ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Issue(s) addressed                     | Fixes #11691 

#### Description:
Check if the removed Stage does not cause a 500 error (exception)

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Make sure you have "Recent activity" widget on dashboard.
3. Create stage.
4. Remove stage.
5. Open dashboard.

### CODE REVIEW

**Review by escopecz — CHANGES_REQUESTED** [review]
Thank you for this fix! It will need a test to make sure it won't get broken again ever. Let me know if you need some help with it.

**Comment by biozshock** [comment]
@escopecz if you can point to a rather similar test case it would be nice.
Edit: if a unit test is enough to cover this there's no need for a help.

**Comment by escopecz** [comment]
@biozshock this one could be a good starting point https://github.com/mautic/mautic/blob/5.x/app/bundles/DashboardBundle/Tests/Controller/DashboardControllerFunctionalTest.php

**Comment by biozshock** [comment]
@escopecz I've already added the unit test. Should i also add an integration test?

**Review by escopecz — DISMISSED** [review]
I see. I prefer functional/integration tests over unit but now I can see that CodeCov is just confused. It's reporting lowered coverage in a file you did not touch. So this is good from the code perspective. Thanks!

**Comment by MadlenF** [comment]
Works as expected!

**Pull request merged**
