### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by quincia**
Add check $_SERVER['HTTP_X_FORWARDED_PROTO']) and $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https' to prevent infinite loop with SAML SSO integration

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ x ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | 
| Related developer documentation PR URL |  
| Issue(s) addressed                     | 
 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Configure SAML SSO Settings in Configuration -> User/Authentication Settings
3. Logon on Mautic

### CODE REVIEW

**Comment by driskell** [comment]
It’s usually best to handle this in the server configuration as this header is very specific to being behind specific types of proxy. For example in Nginx you’d use fastcgi_param to set the correct HTTPS value from the get go (which defaults to $https variable) - rather than letting it set the wrong value then overriding it in the application.

What server are you using?

**Comment by quincia** [comment]
> It’s usually best to handle this in the server configuration as this header is very specific to being behind specific types of proxy. For example in Nginx you’d use fastcgi_param to set the correct HTTPS value from the get go (which defaults to $https variable) - rather than letting it set the wrong value then overriding it in the application.
> 
> What server are you using?

I'm using Apache 2.4.x

**Comment by escopecz** [comment]
I would also suggest to set the `$_SERVER['HTTPS']` elsewhere. It can be set as an [environmental variable](https://github.com/mautic/mautic/blob/5.x/.env). Would that work for your use case?

**Comment by escopecz** [comment]
Closing for now. We can discus here and reopen if needed.

**Pull request closed without merging**
