### PR TITLE
[BUGFIX] added parenthesis for filter String

### LINKED ISSUE #10119: Mautic 4: Clicking on view contacts for a tag shows no contacts
Mautic version: Mautic 4.0-beta

Raised by @Christophe9880 in #10110 

Have made a short vid about it: https://youtu.be/hOpjIoJfk88

I added a "tag" in a campaign, and I could see the tag was added at the contact, but when I click on "view contact" for a certain tag, no contacts were visible, but it's all clear in the vid.

### PR DESCRIPTION
**Pull request by n-azimy**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Issue(s) addressed                     | Fixes #10119

#### Description:
The issue was with having a space in the tag name and the filter was not using double quotes to search for the phrase, so it couldn't find it. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Edit a contact and add a tag containing a whitespace 
3. Open the tagmanager 
4. In the row of the corresponding tag click on "view contacts"
5. The contact with the tag should now be displayed. Also, in the filter field, the tag is displayed surrounded by double quotes

### CODE REVIEW

**Review by luguenth — APPROVED** [review]
Fixes the corresponding issue. You now can use tags with whitespace. Thanks a lot  :)

**Comment by RCheesley** [comment]
Thanks for making the PR @n-azimy!

@cla-bot check

**Review by LeonOltmanns — APPROVED** [review]
Works like a charm! My guy you are awesome!

**Review by npracht — APPROVED** [review]
👍🏽 well done

**Review by RCheesley — APPROVED** [review]
Simple change but a great improvement for the end-user. Thanks @n-azimy 🚀

**Comment by RCheesley** [comment]
@n-azimy please pull in latest features, as you made this PR on a protected branch so maintainers can't do that. In the future it really helps if you're able to use a private fork rather than one in an org :)

Once that is done we'll be able to get this merged!

**Comment by RCheesley** [comment]
@all-contributors please add @n-azimy for code

**Pull request merged**
