### PR TITLE
Fix import with stage not found

### PR DESCRIPTION
**Pull request by hluchas**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | Y
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/316
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Import is failing when relation to stage ID is not found.

Failing CSV
[failing.csv.zip](https://github.com/mautic/mautic/files/3510322/failing.csv.zip)

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create stage with name test
2. Import CSV file attached.
3. Import never stops without failing.

In my case stage is detected automatically in mapping page. When I click import, the exception is produced into log and import (in browser) never ends.

```
[2019-08-20 11:46:52] mautic.DEBUG: IMPORT(53): The import is starting on line 1  
[2019-08-20 11:46:52] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getId() on null" at /Users/lukas/dev/mautic/apps/community/app/bundles/LeadBundle/Model/LeadModel.php line 625 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getId() on null at /Users/lukas/dev/mautic/apps/community/app/bundles/LeadBundle/Model/LeadModel.php:625)
[stacktrace]
#0 /Users/lukas/dev/mautic/apps/community/app/bundles/LeadBundle/Model/LeadModel.php(1000): Mautic\\LeadBundle\\Model\\LeadModel->setFieldValues(Object(Mautic\\LeadBundle\\Entity\\Lead), Array, false, false)
#1 /Users/lukas/dev/mautic/apps/community/app/bundles/LeadBundle/Model/LeadModel.php(1394): Mautic\\LeadBundle\\Model\\LeadModel->checkForDuplicateContact(Array)
#2 /Users/lukas/dev/mautic/apps/community/app/bundles/LeadBundle/Model/ImportModel.php(398): Mautic\\LeadBundle\\Model\\LeadModel->import(Array, Array, NULL, NULL, NULL, true, Object(Mautic\\LeadBundle\\Entity\\LeadEventLog), 53)
#3 /Users/lukas/dev/mautic/apps/community/app/bundles/LeadBundle/Controller/ImportController.php(247): Mautic\\LeadBundle\\Model\\ImportModel->process(Object(Mautic\\LeadBundle\\Entity\\Import), Object(Mautic\\LeadBundle\\Helper\\Progress))
#4 /Users/lukas/dev/mautic/apps/community/app/bundles/CoreBundle/Controller/CommonController.php(474): Mautic\\LeadBundle\\Controller\\ImportController->newAction(0, '')
#5 /Users/lukas/dev/mautic/apps/community/vendor/symfony/http-kernel/HttpKernel.php(135): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('new', 0, 0, '')
#6 /Users/lukas/dev/mautic/apps/community/vendor/symfony/http-kernel/HttpKernel.php(57): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#7 /Users/lukas/dev/mautic/apps/community/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php(67): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#8 /Users/lukas/dev/mautic/apps/community/vendor/symfony/http-kernel/Kernel.php(183): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#9 /Users/lukas/dev/mautic/apps/community/app/AppKernel.php(141): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#10 /Users/lukas/dev/mautic/apps/community/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 /Users/lukas/dev/mautic/apps/community/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /Users/lukas/dev/mautic/apps/community/app/middlewares/Dev/IpRestrictMiddleware.php(66): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /Users/lukas/dev/mautic/apps/community/app/middlewares/VersionCheckMiddleware.php(57): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /Users/lukas/dev/mautic/apps/community/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 /Users/lukas/dev/mautic/apps/community/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#16 /Users/lukas/dev/mautic/apps/community/index_dev.php(33): Stack\
un(Object(Stack\\StackedHttpKernel))
#17 {main}
"} 
```

#### Steps to test this PR:
1. Same as reproduction steps.

### CODE REVIEW

**Comment by RCheesley** [comment]
@hluchas if I try to grab the file it says no file found - can you re-upload?

**Comment by hluchas** [comment]
> @hluchas if I try to grab the file it says no file found - can you re-upload on this repo so it's publicly accessible?

Done, sorry about that @RCheesley

**Comment by RCheesley** [comment]
Testing locally and providing the details as it wasn't completely clear to me if this was the correct process in the info.

**Before patch applied**
Upload file via contacts import and notice that it fails without error due to the stage not existing. I wasn't clear about the instruction to create a stage called test after the import, or whether it meant that this should be left in the import file to create?

**After patch applied**
Import fails due to lack of stage, but an error is thrown and a link to view the import screen provided

It wasn't totally clear if this is the expected outcome from the instructions!

As a side note the language string appears to be undefined: mautic.lead.import.stage.not.exists

screenshot-local mautictest-2019 08 18-17_40_39

I guess it should say "Stage does not exist" or something similar.

**Comment by hluchas** [comment]
This is fixing something different.

Correct steps to reproduce are:
1. Create stage with name test
2. Import CSV file attached.
3. Import never stops without failing.

In my case stage is detected automatically in mapping page. When I click import, the exception is produced into log and import (in browser) never ends.

```
[2019-08-20 11:46:52] mautic.DEBUG: IMPORT(53): The import is starting on line 1  
[2019-08-20 11:46:52] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getId() on null" at /Users/lukas/dev/mautic/apps/community/app/bundles/LeadBundle/Model/LeadModel.php line 625 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getId() on null at /Users/lukas/dev/mautic/apps/community/app/bundles/LeadBundle/Model/LeadModel.php:625)
[stacktrace]
#0 /Users/lukas/dev/mautic/apps/community/app/bundles/LeadBundle/Model/LeadModel.php(1000): Mautic\\LeadBundle\\Model\\LeadModel->setFieldValues(Object(Mautic\\LeadBundle\\Entity\\Lead), Array, false, false)
#1 /Users/lukas/dev/mautic/apps/community/app/bundles/LeadBundle/Model/LeadModel.php(1394): Mautic\\LeadBundle\\Model\\LeadModel->checkForDuplicateContact(Array)
#2 /Users/lukas/dev/mautic/apps/community/app/bundles/LeadBundle/Model/ImportModel.php(398): Mautic\\LeadBundle\\Model\\LeadModel->import(Array, Array, NULL, NULL, NULL, true, Object(Mautic\\LeadBundle\\Entity\\LeadEventLog), 53)
#3 /Users/lukas/dev/mautic/apps/community/app/bundles/LeadBundle/Controller/ImportController.php(247): Mautic\\LeadBundle\\Model\\ImportModel->process(Object(Mautic\\LeadBundle\\Entity\\Import), Object(Mautic\\LeadBundle\\Helper\\Progress))
#4 /Users/lukas/dev/mautic/apps/community/app/bundles/CoreBundle/Controller/CommonController.php(474): Mautic\\LeadBundle\\Controller\\ImportController->newAction(0, '')
#5 /Users/lukas/dev/mautic/apps/community/vendor/symfony/http-kernel/HttpKernel.php(135): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('new', 0, 0, '')
#6 /Users/lukas/dev/mautic/apps/community/vendor/symfony/http-kernel/HttpKernel.php(57): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#7 /Users/lukas/dev/mautic/apps/community/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php(67): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#8 /Users/lukas/dev/mautic/apps/community/vendor/symfony/http-kernel/Kernel.php(183): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#9 /Users/lukas/dev/mautic/apps/community/app/AppKernel.php(141): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#10 /Users/lukas/dev/mautic/apps/community/app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 /Users/lukas/dev/mautic/apps/community/app/middlewares/CatchExceptionMiddleware.php(45): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /Users/lukas/dev/mautic/apps/community/app/middlewares/Dev/IpRestrictMiddleware.php(66): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /Users/lukas/dev/mautic/apps/community/app/middlewares/VersionCheckMiddleware.php(57): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /Users/lukas/dev/mautic/apps/community/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 /Users/lukas/dev/mautic/apps/community/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#16 /Users/lukas/dev/mautic/apps/community/index_dev.php(33): Stack\
un(Object(Stack\\StackedHttpKernel))
#17 {main}
"} 
```

**Review by RCheesley — APPROVED** [review]
Thanks for the clarification on the test instructions (maybe edit the original post?).

Confirmed that post-patch there is no error on importing contacts.

**Comment by hluchas** [comment]
TY @RCheesley !

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by hluchas** [comment]
I've to create new PR based on cherry-picks here https://github.com/mautic/mautic/pull/8695. Closing this.

**Pull request closed without merging**
