### PR TITLE
add getEventLogRepository method for mock LeadModel and CompanyModel

### PR DESCRIPTION
**Pull request by phil-davis**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | N
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #5011 
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. look in the Travis unit test logs and see 9 warnings
2. the first 5 are related to this PR

#### Steps to test this PR:
1. look in the Travis unit test logs and see it die :(

### CODE REVIEW

**Comment by phil-davis** [comment]
I added the ``getEventLogRepository`` method to the mocks of ``LeadModel`` and ``CompanyModel`` - that gets the code past the unit test warnings:

```
1) Mautic\LeadBundle\Tests\Model\ImportModelTest::testInitEventLog
Trying to configure method "getEventLogRepository" which cannot be configured because it does not exist, has not been specified, is final, or is static
2) Mautic\LeadBundle\Tests\Model\ImportModelTest::testProcess
Trying to configure method "getEventLogRepository" which cannot be configured because it does not exist, has not been specified, is final, or is static
3) Mautic\LeadBundle\Tests\Model\ImportModelTest::testIsEmptyCsvRow
Trying to configure method "getEventLogRepository" which cannot be configured because it does not exist, has not been specified, is final, or is static
4) Mautic\LeadBundle\Tests\Model\ImportModelTest::testTrimArrayValues
Trying to configure method "getEventLogRepository" which cannot be configured because it does not exist, has not been specified, is final, or is static
5) Mautic\LeadBundle\Tests\Model\ImportModelTest::testHasMoreValuesThanColumns
Trying to configure method "getEventLogRepository" which cannot be configured because it does not exist, has not been specified, is final, or is static
```
so now ``initImportModel()`` actual finishes and returns an ``ImportModel``. So far so good.

But then when ``ImportModel`` is used in the tests, it needs a more "realistic" ``LeadModel`` that has a realistic ``CompanyModel`` injected in it. ``LeadModel`` has a large constructor that needs lots of things to be passed to it.

It seems that this test maybe never passed, and the "missing pieces" have been masked by the warnings that have been prematurely stopping the test from actually running for real.

Any guidance on where to head with this is welcome...

**Comment by dongilbert** [comment]
Thanks for this @phil-davis! Check out my commit to see how to get around building the full lead/company model's while still being able to pass your mocks using reflection.

**Comment by phil-davis** [comment]
Rebased and resolved conflicts. There have been multiple PRs in this area, e.g. #5017 - so we might be fighting against each other? to get the warnings out of the tests.

**Comment by phil-davis** [comment]
Scrutinizer is giving errors for all my PRs???
But Travis looks like it is a good thing.

**Comment by phil-davis** [comment]
@dongilbert There are 2 new warnings in the unit tests, that are introduced by some changes in ``staging`` - those are shown in the logs of any Travis-CI job off ``staging``. But staging has no other unit test warnings. So actually the warnings that this code was supposed to fix are already fixed by some other change, that must have been done in some other way.

So this can be closed?

**Comment by phil-davis** [comment]
Rebased

**Comment by Maxell92** [comment]
Not sure this PR is still valid. There are no errors on staging now. So maybe there was another PR addressing this issue?

**Comment by phil-davis** [comment]
Rebased again. @dongilbert have a look at what you and I did here and decide if it is needed/useful or not.

**Comment by dongilbert** [comment]
As there are no current warnings in staging (according to Travis), I'm closing this.

**Pull request closed without merging**
