### PR TITLE
Fixes to preferences center

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

Preferences center did a lot of strange things.   I don't remember which PR mess it, but it was during this code was changes https://github.com/kuzmany/mautic/blob/ef5c590baba41133371f9a53b76e3e7caeb3f257/app/bundles/LeadBundle/Form/Type/ContactFrequencyType.php#L53-L53

I noticed several issues:

**Enabled preferences center - use default center (not landing page)**
Generate a lot of fields even If you disabled it or enable some options. If you just enable preference center, still generate ugly frequency rules. 

**Enabled preferences center - use landing page as prefs center**
You cannot for example use just segments in your prefs center

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1.  Test preferences center on default and landing page
2.  Notice a lot of issues

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com/7006)
2.  Test again

### CODE REVIEW

**Comment by kuzmany** [comment]
This PR is based on @johbuch test of 2.15. beta. Please consider as 2.15 beta bugfix. There were a few improvements to preferences center, but together doesn't work :(

**Comment by kuzmany** [comment]
@johbuch @npracht  DNC fixed for both type of prefs center (default, custom landing page)

**Comment by cStuartHardwick** [comment]
Question: In order to test changes to preference center, we must have an email from the mautic.boxed PR site. Email appears to be configured, but I've been unable to get an email to actually go out.

I went in under preferences and changes from queued to immediate, thinking their might be no chron job, and I see in my contract record's logs a record of all the emails going out, but I've yet to actually receive any. I can't take without the email unless there is some backdoor way to calculate the preference center link URL I don't know about.

**Comment by kuzmany** [comment]
@cStuartHardwick If you're testing in Mautibox you can see emails in log https://mautibox.com/mail/ (emails are not sent )
But faster way is take url of email from contact profile, just copy link of the anchor

image

**Comment by cStuartHardwick** [comment]
Thanks @kuzmany. And what's the correct way to report results?

Here's what I found:
I copied the unsub URL out of the email source and opened that in another window. Instead of seeing the preference center as expected, I got the summary "sorry to see you go, resub if this was a mistake" message. I actually thought that was gone, but that's okay. Maybe the email config is wrong. So to test that out, I clicked "Resubscribe," but now when I try to open the unsub URL, the tab just endlessly flashes and never opens. https://mautibox.com/7006/email/unsubscribe/5c3d310ccd889976309421

**Comment by cStuartHardwick** [comment]
Tonight I have good news and back news.
The good news is, the unsub/resub functionality both work, both store the DO NOT CONTACT state correctly, and do not cause the weird hysteresis seen earlier.

Second geed news: When all six options under preference center are set ON, attempting to show the preference center no longer causes an Http 500 Oh-No. Excellent.

However, there still is no custom pref. center. I created a new landing page, made it type Pref center, and added ALL the PC components. Then I created a new template type email, set it to use the new landing page as Pref center, then went to my contact and sent a message using that email as a template. When I clicked on the anchor to open the email (All the styling was missing, which is worrying, but unrelated to the Pref center.) Then I clicked "unsubscribe" and got the generated Preference center, not the custom one the test email should have demanded.

Also, in the generated preference center, the "save preferences" button is labeled "Valider."

https://mautibox.com/7006/email/unsubscribe/5c3e056ebf304257064456

Thx

**Comment by kuzmany** [comment]
@cStuartHardwick 
https://mautibox.com/7006/email/unsubscribe/5c3e056ebf304257064456
It's not generated, It's landing page prefs center. I think It's corrrect.

I think @johbuch , who test it, switch the page to french language, this is reason why button label is Valider

**Comment by cStuartHardwick** [comment]
I'm quite certain I am not seeing a custom Preference Center based on the landing page referenced in the email. Is there a way to delete the cache in mauticbox?

**Comment by mbrinson** [comment]
Thanks for working on this kuzmany. I've been searching through the code structure for Mautic trying to see if I could fix the problems that I was seeing with my rendered custom prefs center page, then I found this PR from you that is trying to address these problems.

I hadn't heard of or used mautibox before, so thanks for mentioning that.  I did some testing in there, changing the preference center landing page that was associated with the "TEST CP7" email to CSH-CP(5). Then I pulled the end of the URL in the contact history for "csh test" as you explained above (thanks for that too!).

This does pull up the correct landing page now, but here's what I'm seeing at the unsubscribe page:



I'm not sure what that's all about.

**Comment by cStuartHardwick** [comment]
@mbrinson, @kozmany, I now see the same as mbdrinson's screenshot above. I do see the custom PC, but with errors a mostly missing style/content (i.e. no image or colored backgrounds.)

Thx.

**Comment by kuzmany** [comment]
Should fixed now. Please re-test

**Comment by mbrinson** [comment]
I'm trying to test now using that same URL (https://mautibox.com/7006/email/unsubscribe/5c418e601d20e607198857) and now it doesn't seem to be loading the custom preferences center landing page.

Here's what I get instead:

image

**Comment by mbrinson** [comment]
Wow, that's strange.  Just in case it was some kind of caching issue, I tried in an incognito session and i still get the non-customPrefs page.  I also tried setting up a new email channel and connected it to a preference center landing page, and I still got the non-customPrefs page.  Different test email as well:



Here's the link:  [https://mautibox.com/7006/email/unsubscribe/5c42572b8199d974159443](https://mautibox.com/7006/email/unsubscribe/5c42572b8199d974159443)

**Comment by kuzmany** [comment]
Everytime when I push commit, mautibox refresh settings, then you need setup configurations again.

**Comment by mbrinson** [comment]
> Everytime when I push commit, mautibox refresh settings, then you need setup configurations again.

I'm not sure what you mean.  You mean we need to log out and back in again?

**Comment by kuzmany** [comment]
Setup preferences in Configurations > Email tab

**Comment by mbrinson** [comment]
> Setup preferences in Configurations > Email tab

Oh, I see!  Okay, I'm turning that on now.  Will test again.

**Comment by mbrinson** [comment]
Okay, now I see the prefs center landing page, but I still get that symfony error message:

**Comment by mbrinson** [comment]
Okay, sorry for not understanding before.  I found the problem.
Somehow I didn't realize that we have to also enable each of the contact preference options under the configuration as well.  I just turned them on and now I'm seeing the correct layout:



The image still doesn't display, but I'm guessing that must be some kind of a rule on the server not to load external links as embedded images or something?

Thanks kuzmany!

**Comment by mbrinson** [comment]
Maybe this does bring out the point that the code needs to perform a check for whether those options are enabled and catch the error and give a better error message instead of the Symfony error message that displays?

Don't know if that's possible..

**Comment by mbrinson** [comment]
In the case of using "Code Mode" for the preferences center landing page, do you know what the minimum required divs are?

It seems that the code replaces a lot of what I put into the code.  For example, I have:

`<div class="column span_1_of_2">
	<div data-slot="channelfrequency">
		<div class="text-left">
			<input type="checkbox" checked="" />
			<label class="control-label">Contact me through %channel%</label>
		</div>
		<div id="frequency_email" class="text-left">
			<div>
				<label class="text-muted label1">Do not contact more than</label>
				<input type="text" class="frequency form-control" />
				<label class="text-muted fw-n frequency-label label2">In a</label>
				<select class="form-control">
					<option value="" selected="selected">Day/Week/Month</option>
					<option value="Day">Day</option>
					<option value="Week">Week</option>
					<option value="Month">Month</option>
				</select></div>
			<div>
				<label class="text-muted label3">Pause from</label>
				<input type="text" class="form-control datepicker" placeholder="mm/dd/yyyy" />
				<label class="frequency-label text-muted fw-n label4">to</label>
				<input type="text" class="form-control datepicker" placeholder="mm/dd/yyyy" />
			</div>
		</div>
	</div>
	<div data-slot="segmentlist">
		<div class="contact-segments">
			<div class="text-left">
				<label class="control-label">My segments</label>
			</div>
			<div id="segment-1" class="text-left">
				<input type="checkbox" id="lead_contact_frequency_rules_lead_lists_1" name="lead_contact_frequency_rules[lead_lists][]" autocomplete="false" value="" checked="checked" />
				<label for="lead_contact_frequency_rules_lead_lists_1">Contact Segment</label>
			</div>
		</div>
	</div>
	<div data-slot="successmessage">
	  <span style="color:green;font-size:2em;">Preferences Saved</span>
	</div>
	<div data-slot="saveprefsbutton">
	</div>
</div>`

Then, what actually gets generated is:

`<div class="column span_1_of_2">
	<div data-slot="channelfrequency">
		<div class="pref-channelfrequency">
			<table class="table table-striped">
			</table>
		</div>
	</div>
	<div data-slot="segmentlist">
		<div class="pref-segmentlist">
			<div class="contact-segments">
				<div class="text-left">
					<label class="control-label">My segments</label>
				</div>
				<div id="segment-1" class="text-left">
					<input type="checkbox" id="lead_contact_frequency_rules_lead_lists_1" name="zvwxvahsp" autocomplete="false" value="6">
					<label for="lead_contact_frequency_rules_lead_lists_1">Example 1</label>
				</div>
				<div id="segment-0" class="text-left">
					<input type="checkbox" id="lead_contact_frequency_rules_lead_lists_0" name="zvwxvahsp" autocomplete="false" value="1" checked="checked">
					<label for="lead_contact_frequency_rules_lead_lists_0">Example 2</label>
				</div>
			</div>
		</div>
	</div>
	<div data-slot="successmessage" style="display:none">
		<span style="color:green;font-size:2em;">Preferences Saved</span>
	</div>
	<div data-slot="saveprefsbutton">
		<div class="pref-saveprefs">
			<script src="/app/bundles/PageBundle/Assets/js/prefcenter.js"></script>
			<a href="javascript:void(null)" class="button btn btn-default btn-save disableAutoFillSubmit" onclick="saveUnsubscribePreferences('lead_contact_frequency_rules')" style="display:inline-block;text-decoration:none;border-color:#4e5d9d;border-width: 10px 20px;border-style:solid; text-decoration: none; -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px; background-color: #4e5d9d; display: inline-block;font-size: 16px; color: #ffffff; " type="button">Save preferences</a>
			<div style="clear:both"></div>
			<div class="row">
				<div class="form-group col-xs-12 ">
					<label class="required">Contact me through:</label>
					<div id="lead_contact_frequency_rules_lead_channels">
						<div class="row">
							<div class="form-group col-xs-12 ">
								<div class="choice-wrapper">
									<div class="checkbox">
										<label><input type="checkbox" id="lead_contact_frequency_rules_lead_channels_subscribed_channels_0" name="qxttsatl" onclick="Mautic.togglePreferredChannel(this.value);" autocomplete="false" value="email" checked="checked">Email</label>
									</div>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="form-group col-xs-12 ">
								<label class="control-label" for="lead_contact_frequency_rules_lead_channels_preferred_channel" data-toggle="tooltip" data-container="body" data-placement="top" title="My preferred channel">My preferred channel <i class="fa fa-question-circle"></i></label>
								<div class="choice-wrapper">
									<select id="lead_contact_frequency_rules_lead_channels_preferred_channel" name="lead_contact_frequency_rules[lead_channels][preferred_channel]" class="form-control" autocomplete="false">
										<option value="email" selected="selected">Email</option>
									</select>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="form-group col-xs-12 ">
								<label class="text-muted fw-n label1" for="lead_contact_frequency_rules_lead_channels_frequency_number_email">Do not contact more than</label>
								<input type="number" id="lead_contact_frequency_rules_lead_channels_frequency_number_email" name="crptehfgrd" class="frequency form-control" autocomplete="false" placeholder="Number of times">
							</div>
						</div>
						<div class="row">
							<div class="form-group col-xs-12 ">
								<label class="text-muted fw-n frequency-label label2" for="lead_contact_frequency_rules_lead_channels_frequency_time_email">In a</label>
								<div class="choice-wrapper">
									<select id="lead_contact_frequency_rules_lead_channels_frequency_time_email" name="lead_contact_frequency_rules[lead_channels][frequency_time_email]" class="form-control" autocomplete="false" style="color: lightgray;">
										<option value="" style="color: lightgray;">Day/Week/Month</option>
										<option value="DAY" style="color: black;">Day</option>
										<option value="WEEK" style="color: black;">Week</option>
										<option value="MONTH" style="color: black;">Month</option>
									</select>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="form-group col-xs-12 ">
								<input type="text" id="lead_contact_frequency_rules_lead_channels_contact_pause_start_date_email" name="unksdyq" data-toggle="date" class="frequency-date form-control" autocomplete="false" placeholder="yyyy-mm-dd">
							</div>
						</div>
						<div class="row">
							<div class="form-group col-xs-12 ">
								<label class="frequency-label text-muted fw-n label4" for="lead_contact_frequency_rules_lead_channels_contact_pause_end_date_email">to</label>
								<input type="text" id="lead_contact_frequency_rules_lead_channels_contact_pause_end_date_email" name="jzdphdv" data-toggle="date" class="frequency-date form-control" autocomplete="false" placeholder="yyyy-mm-dd">
							</div>
						</div>
					</div>
				</div>
			</div>
					<div id="lead_contact_frequency_rules_buttons" class="bottom-form-buttons">
					</div>
					<input type="hidden" id="lead_contact_frequency_rules__token" name="lead_contact_frequency_rules[_token]" autocomplete="false" value="..RANDOMVALUE..">

					<a name="end-lead_contact_frequency_rules"></a>
		</div>
	</div>
</div>`

**Comment by cStuartHardwick** [comment]
@Kuzmany, you da man!

All things preference center appear to be working. I WAS IN ERROR EARLIER, about the colors and image and was not using the landing page I thought I was. When I corrected that, everything looks good and as expected.  It's dinner time here, so I will log back in later to do a more thorough test, and make sure there are no issues with any of the individual PC controls, etc.

**Comment by cStuartHardwick** [comment]
> 
> 
> Maybe this does bring out the point that the code needs to perform a check for whether those options are enabled and catch the error and give a better error message instead of the Symfony error message that displays?
> 
> Don't know if that's possible..

Yes, that's not right. If you turn off PC elements on the email settings page, it breaks any existing custom PCs and causes them to display Symfony errors for those controls. That's definitely not right, because there may already be emails out in the world at the time.

When using a custom preference center, its configuration should trump that set under email settings. Email settings should only control the default generated PC.

Thx

You guys are making me want to learn Symfony & Twist. Cool tech.

**Comment by mbrinson** [comment]
Darn, I missed the point about applying this against the "staging" branch.
I applied the fixes in my 2.15.0 environment and while it fixed the generated HTML output, I'm no longer able to edit the landing page.  When I click "Edit" it spins for a bit, and then does nothing.

I'm hoping 2.15.1 gets released soon!  Can't wait for this fix to become fully available.  Thanks again kuzmany!

**Comment by mbrinson** [comment]
> Darn, I missed the point about applying this against the "staging" branch.
> I applied the fixes in my 2.15.0 environment and while it fixed the generated HTML output, I'm no longer able to edit the landing page. When I click "Edit" it spins for a bit, and then does nothing.
> 
> I'm hoping 2.15.1 gets released soon! Can't wait for this fix to become fully available. Thanks again kuzmany!

Actually, it works against 2.15.0 as well.  It turns out I had missed one ending bracket in the code I had copied from the diff.  Awesome!

**Comment by kuzmany** [comment]
If works, please approve this PR 

image

**Comment by cStuartHardwick** [comment]
Looks good. A few minor issues:

1. If a custom preference center has any PC field on it that is turned off under email settings on the configuration screen, it generates a Symfony error at run time. This is a bug. It's a bug with a simple work-around (always turn on all options under email options when using preference center) but it's still  a bug, and will certainly cause some users to have problem. This ought to be fixed or, at the very least, a check added to force all PC options to "Yes" when "Show contact preference settings" is "yes".
2. The "Show contact preference settings " control under email settings on the configuration page is confusingly named. I would suggest "Used Custom Preference Centers" as better describing what it does, with revised help text. The help text implies that setting this to "Yes" turns off the default generated preference center, but that's wrong. Unless I'm mistaken, the default PC is still shown unless or until new emails are sent, for which a PC landing page has been associated.
3. If a user who has "do not contact" set visits the custom preference center, there is no way for them to clear the "Do not contact flag". On the default generated unsubscribe screen, you have the option to "resubscribe" which clears this flag.
4. The "Categorylist" control does not display when included on the custom preferences center landing page. I don't know what this is, as there is no "Categories" field on a contact (that I can find) and Categories do not allow you to add contacts to them like segments (as far as I can see) although the email settings panel does have a switch to enable showing the category list. Something is out of sync here.

**Comment by kuzmany** [comment]
1. I didn't see any notice info. Last commit fixed it. Works for me properly
2. Will see, maybe little re-arrange the configuration
3. Require enable show_contact_frequency and same token on landing page
4. You need enable Show category list / Any global category exist  and also token on custom landing page

**Comment by kuzmany** [comment]
This issue is related to this PR https://github.com/mautic/mautic/pull/7168 
I merge it to this repo, should works now within few minutes

**Comment by leadsmania** [comment]
Hi can I get this code for preference center? I sure would like to get it working again. Do I have to wait for 2.15.1? In my emails people are seeing a server error when they click on the unsubscribe link.

**Comment by leadsmania** [comment]
I only have a small group of people that get emails but im worried that it looks unprofessional.

**Comment by cStuartHardwick** [comment]
> 
> 
> Hi can I get this code for preference center? I sure would like to get it working again. Do I have to wait for 2.15.1? In my emails people are seeing a server error when they click on the unsubscribe link.

In theory, you can download any branch from Git, and install on your site (and deal with potential merge issues later). I don't really see that as practical though, personally, even through I work in IT (in different technologies). There are databases changes as well as code changes, and the potential for things going wrong (or at least becoming a huge time sink) is large.

I too would dearly leave to give my subscribers a working preference center (which they have been complaining about) but see to practical way forward except to wait.

**Pull request merged**
