### PR TITLE
Fix graph social monitoring

### PR DESCRIPTION
**Pull request by SamWebmecanik**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | X
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #4186
| BC breaks? | 
| Deprecations? | 

[//]: # ( Required: )
#### Description:
The graph in the social monitoring is wrong because it counts the number of rows in the `monitor_post_count `table rather than adding up the `post_count` column 

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a social monitoring
2. Get some lead in monitoring
3. See the graph with only one "data" per day

#### Steps to test this PR:
1. Apply this PR
2. See the graph with the number of all "data" per day

### CODE REVIEW

**Comment by escopecz** [comment]
Please fix the code standards: https://travis-ci.org/mautic/mautic/jobs/247563104#L597

**Comment by MaxWebmecanik** [comment]
@escopecz The file shown in https://travis-ci.org/mautic/mautic/jobs/247563104#L602 has nothing to do with the changes done here https://github.com/mautic/mautic/pull/4311/files. Moreover, I can't even find the code inside the Travis build... It looks like it's a completely different version!

Also, this is not the only PR that only fails on PHP 7.1 which leads me to believe there might be a configuration issue with Travis.
image

**Comment by MaxWebmecanik** [comment]
@escopecz Nevermind, just read this
image

**Comment by MaxWebmecanik** [comment]
@escopecz But still the file mentioned in the travis build `EmailBundle/Controller/AjaxController.php` is not even touched on by this PR!

**Comment by escopecz** [comment]
Fair enough. It seems some CS breaks got into the staging.

**Comment by robwent** [comment]
I've just tested this and it's working for me.
Fixes this issue: https://github.com/mautic/mautic/issues/4186

I checked other graphs and they all seem to be working as normal.

social_monitor

**Pull request merged**
