### PR TITLE
Minor dashboard layout enhancements

### PR DESCRIPTION
**Pull request by alanhartless**
Please answer the following questions:

| Q             | A
| ------------- | ---
| Bug fix?      | N
| New feature?  |N
| BC breaks?    | N
| Deprecations? | N
| Fixed issues  |  

## Description

This does just a few minor things for the dashboard widget/layouts:

1. Uploads and lists dashboard layouts to a user specific directory. This allows each user to have their own dashboard layouts listed without getting cluttered by everyone else's. Any layouts uploaded directly into the root of the dashboard folder is considered "global" and will show for all users.

2. Prompts for a custom name on export.

3. Structures the dashboard json files to include name and description that's displayed in place of the file name if applicable. This paves the way to be able to name the default files.

## Steps to test this PR

Apply the PR and through dev (prod assets are not compiled), test exporting, importing, deleting and applying custom layouts.

### CODE REVIEW

**Comment by escopecz** [comment]
All works for me nicely except applying the default/global dashboards because Mautic is searching for them in the user dir: https://github.com/mautic/mautic/blob/staging/app/bundles/DashboardBundle/Controller/DashboardController.php#L341

So probably search in the user dir first and then look at the global dir? Or the other way around?

**Comment by dbhurley** [comment]
Yes, user than global

**Comment by alanhartless** [comment]
@escopecz Can you retest? Also check out the widget sortable updates to see what you think.

**Comment by escopecz** [comment]
The sortable update is amazing!

**Pull request merged**
