### PR TITLE
Fix/change hubspot api auth 5.x

### LINKED ISSUE #11767: Create 5.x PR and increase test coverage of new Hubspot API changes
@kuzmany @escopecz this needs to go out in 4.4.5 but it is failing on test coverage. Anything that can be done to get this over the line?

_Originally posted by @RCheesley in https://github.com/mautic/mautic/issues/11470#issuecomment-1330898518_

This needs to be merged into the next 4.4.x release and also into the 5.x branch, creating the issue so that we do not lose sight of it as the 4.4.5 release needs this PR.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/114275233-create-5-x-pr-and-increase-test-coverage-of-new-hubspot-api-changes?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by biozshock**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ x ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ x ] 
| Issue(s) addressed                     | Fixes #11767  

#### Description:
Cherry picked commits to address Hubspot changes, which are available only in 4.4.
We need to change authentication method for Hubspot plugin. New installation cannot use our plugin anymore, and existing in integration will shut down in November, 22'.

#### Steps to test this PR:
Same as in #11470

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a private app in hubspot with following rights
3. Setup plugin integration
4. See everything works

### CODE REVIEW

**Comment by npracht** [comment]
Shouldn't we merge 4.4 in 5.x to have the fix coming instead of cherry picking this specific PR (which has been merged) ?
Cc @escopecz

**Comment by biozshock** [comment]
@npracht see https://github.com/mautic/mautic/pull/11775#issuecomment-1354958779

**Comment by npracht** [comment]
Oh, i didn't know (i missed it, my fault). Then... :)

**Review by daniellord32 — COMMENTED** [review]
Testing complete, no problems to note. (Does need rebased)

- [x] Integration with hubspot's private api key
- [x] Key mappings working as expected
- [x] Features are working as expected
- [x] import from hubspot to mautic

**Comment by RCheesley** [comment]
Thanks for making the PR @biozshock and for testing @daniellord32 🚀

**Comment by biozshock** [comment]
Rebased.

**Review by escopecz — APPROVED** [review]
I don't see any issue in the code. Thanks!

**Pull request merged**
