### PR TITLE
Fix custom contact column from any group

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
We've noticed issue using columns from contact field from group different like core or social. This PR fixed it. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Go to Configuration > Contact settings and add contact field from professional or personal group. 
3. Without patch value is not displayed in columns. After patch works properly.

### CODE REVIEW

**Comment by mohit-rocks** [comment]
I did a quick test on local and this seems to be working fine.
Configuration:
Configuration___Mautic

Display on contact page:
Contacts___Mautic

**Comment by kuzmany** [comment]
@mohit-rocks I didn't mention it exactly but fields from professional or personal are not displayed.

**Comment by mohit-rocks** [comment]
@kuzmany, I enabled "Company Fax" from the Professional group. It seems to be working fine. I've attached screenshot.

For the "Personal" group, I created new field and added to the contact. It seems to be visible. Can you please confirm this covers all the test scenarios?
Contacts___Mautic

**Comment by kuzmany** [comment]
@mohit-rocks yes, looks good in your screenshot

**Review by RCheesley — APPROVED** [review]
Approving based on @mohit-rocks positive test

**Pull request merged**
