### PR TITLE
[UX] Humanized time display in Twig extension

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR allows us to have a time display like "2 hours ago", "3 minutes ago" or "just now".
Until now, we had only this format "X days ago" for dates, but not time.

---
### 📋 Steps to test this PR:

1. Pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open the file `app/bundles/CoreBundle/Resources/views/Notification/notification.html.twig`
3. Change `{{ dateToText(n.dateAdded) }}` to `{{ dateToHumanized(n.dateAdded) }}`
4. Go to Contacts > Page actions > Export to CSV to trigger a notification
5. Reload the page
6. Open the Notifications panel
7. See the humanized time

### CODE REVIEW

**Comment by abhisekmazumdar** [comment]
Before:
Screenshot 2024-07-31 at 5 33 26 PM


After:
Screenshot 2024-07-31 at 5 42 05 PM

image

**Review by abhisekmazumdar — APPROVED** [review]

**Comment by abhisekmazumdar** [comment]
Other than the CS fixes & broken test cases, everything looks good to me.

**Comment by andersonjeccel** [comment]
@abhisekmazumdar waiting for Rembrand to help with the tests, I have no idea what I'm doing and would appreciate suggestions to fix

**Comment by abhisekmazumdar** [comment]
From my understanding, I see that we will need to make changes these changes:

For `app/bundles/LeadBundle/Tests/Form/DataTransformer/FieldFilterTransformerTest.php`

Find and replace `'filter' => '2020-03-17 18:22',` with `'filter' => '2020-03-17 17:22'`

You can test it locally by running: `ddev composer test app/bundles/LeadBundle/Tests/Form/DataTransformer/FieldFilterTransformerTest.php`

For the CS fixes locally you can check whats need to be fixed by running:

```shell
ddev composer cs app/bundles/CoreBundle/Tests/Unit/Twig/Extension/DateExtensionTest.php
```

Then run 

```shell
ddev composer fixcs app/bundles/CoreBundle/Tests/Unit/Twig/Extension/DateExtensionTest.php
```

This will fix the alignment issue. You will need to do it for all the files that are throwing errors i.e.:

- `app/bundles/CoreBundle/Tests/Unit/Twig/Extension/DateExtensionTest.php`
- `app/bundles/CoreBundle/Tests/Unit/Twig/Helper/DateHelperTest.php`

**Comment by LordRembo** [comment]
@abhisekmazumdar nice catch!

**Comment by LordRembo** [comment]
@andersonjeccel See if those suggestions already help fix the tests and get the test coverage difference to be better.

**Comment by andersonjeccel** [comment]
@LordRembo 
@abhisekmazumdar 

Well, seems fixed... but have a look to be sure

**Comment by abhisekmazumdar** [comment]
Yes, I see things are fine now. The code looks good to me.

**Review by abhisekmazumdar — APPROVED** [review]

**Review by jos0405 — APPROVED** [review]
It does what it sais:

image

After


image

**Comment by RCheesley** [comment]
Just waiting on the tests to pass then we can merge! 🚀

**Comment by RCheesley** [comment]
According to the CodeCov report [here](https://app.codecov.io/github/mautic/mautic/commit/fc037efcb8d5c98d802ad4bc68598de3e7c0ca24), it's good to go (but hasn't yet been received by the GitHub Action) so merging on that basis.

**Pull request merged**
