### PR TITLE
Fix elfinder folder perms

### PR DESCRIPTION
**Pull request by tejasync**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | N.A.
| Related developer documentation PR URL | N.A.
| Issue(s) addressed                     | N.A.

#### Description:
Need to set appropriate permissions for newly created folders using el-finder.
The permissions should be:
Folders: 777
Files: 666

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Click on browse to open el finder (file explorer) in new browser window
3. Create a new folder and upload some image files in it
4. Check folder and file permissions

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10410"></a>

### CODE REVIEW

**Review by kuzmany — DISMISSED** [review]
Yes, this works 👍 
Code looks good.

**Review by mabumusa1 — DISMISSED** [review]
This PR works as expected, @ts-navghane may you please check the coverage. then this PR should be ready to go

**Comment by kuzmany** [comment]
@ts-navghane need check unit-tests

**Comment by kuzmany** [comment]
Need resolve conflicts. Then we can go

**Comment by kuzmany** [comment]
@ts-navghane looks like need fix unit tests

**Comment by kuzmany** [comment]
@ts-navghane still unit tests fail

**Comment by tejasync** [comment]
> @ts-navghane still unit tests fail

I know, still working on it.

**Review by kuzmany — APPROVED** [review]

**Pull request merged**
