### PR TITLE
Support for sub queries in segment filters

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/5732
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR trying solve https://github.com/mautic/mautic/issues/5732
Current segment filters works separately. That means IF we use page hit date condition and page count condition, both are executed independently. That cause logic when we expect communicate between table data.
We create sub query for each table (page_hit, email_stats) and  cover these queries until OR statement is executed. Or cover it on the end of filter query builder. On each cycle, we reset current sub queries.

My tests filter

image

Query:

`SELECT l.id FROM leads l WHERE (EXISTS(SELECT NULL FROM page_hits qkpoIBuO WHERE (qkpoIBuO.lead_id = l.id) AND (qkpoIBuO.url LIKE '%mautic%') AND (qkpoIBuO.date_hit > '2019-04-11') GROUP BY qkpoIBuO.lead_id HAVING count(DISTINCT qkpoIBuO.id) < 2)) AND (EXISTS(SELECT NULL FROM email_stats beuFTQCU WHERE (beuFTQCU.lead_id = l.id) AND (beuFTQCU.is_read = 1) AND (beuFTQCU.email_id IN (1, 5, 6, 10)) GROUP BY beuFTQCU.lead_id HAVING COALESCE(SUM(beuFTQCU.open_count), 0) > 1)))`

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create new segment
2. Add filter "Visited URL" and choose an URL
3. Add filter "Count Visited URL" and choose a condition
4. Inspect history of each contact added to the segment, you'll see the bug

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Test it with page hits or email hits

#### List backwards compatibility breaks:
1. We add new extra decorators, then there is no BC breaks

### CODE REVIEW

**Comment by cesarjr** [comment]
We applied the PR here and it seems working right. The problem is solved and I didn't find any other break because of it.

**Comment by RCheesley** [comment]
So, I followed these steps:

1. Create landing page with form (to identify visitor)
2. Open in an incognito window
3. Hit the page 3 times and complete the form
4. Create segment with hits URL of landing page AND number of times greater than 2

When I update the segment, I see the contact in the segment as I'd expect, having landing on the URL and having hit it three times. If I rebuild the segment when I've only hit the page once or twice, the contact is not added to the segment.

So, I'm a bit confused what I am testing for, because this is pre-patch and behaving as I would expect, having followed the testing instructions:
1. Create new segment
2. Add filter "Visited URL" and choose an URL
3. Add filter "Count Visited URL" and choose a condition
4. Inspect history of each contact added to the segment, you'll see the bug

^^ I don't see 'the bug' - maybe I am missing something?

**Comment by alanhartless** [comment]
@kuzmany how much acceptance testing was done on this with other segments? This makes me nervous that there could be a bug and/or significant behavior change and all of sudden people have segments changing unexpectedly.

**Comment by kuzmany** [comment]
@alanhartless I applied it for 2-3 clients in production, no issue reported.
@npracht Do you use this PR for some clients?

**Pull request merged**
