### PR TITLE
Fix #10877. Migration Version20201120122846: Improve logic to check table and its foreign keys

### LINKED ISSUE #9129: oAuth Access token Foreign Key on client_id
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I've had a few different SQL migration errors since updating to 3.1.0 from 2.16.3. Most I've been able to figure out, this one is stumping me however, any input would be greatly appreciated.

| Q   | A
| --- | ---
| Mautic version |  3.1.0

### Steps to reproduce
1. I deployed a clean instance of Mautic 3.0.3 which was updated using the update tool to 3.1.0.
2. I then moved my data from a 2.16.3 instance due to outdated PHP etc. This was exported via PHPmyadmin then imported into a clean database in the new mautic 3.1.0 instance. 
3. Schema update was completed successfully.
 
### Log errors

mautic-client-id-error

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/92422288-oauth-access-token-foreign-key-on-client_id?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #10860: Regexp Failed To Parse for Campaign Contact Field Regexp Match
### Mautic Version

4.1.x series

### PHP version

7.4.27

### What browsers are you seeing the problem on?

Chrome

### What happened?

I've attempted to filter contacts by using a "Contact field value" condition in the campaign builder. 
I need to filter by match against a "date-added" contact field. 

I have built a Regex pattern to match the appropriate values. Please see here: https://regex101.com/r/Qp9oCD/1

See log output for error log.

### How can we reproduce this issue?

Step 1: Create campaign with a "Contact field value" condition. 
Step 2: Set the condition to match a field containing a date formatted in the following: F j, Y G:i:s (eg: February 13, 2022 9:22:41).
Step 3: Save the campaign and allow it to run or run it manually.  

### Relevant log output

```shell
[2022-02-14 10:35:21] mautic.CRITICAL: Uncaught PHP Exception Exception: "DateTime::__construct(): Failed to parse time string (8) at position 0 (8): Unexpected character" at /var/www/mautic-xxx.xxx.xxx/app/bundles/CampaignBundle/Entity/Event.php line 1015 {"exception":"[object] (Exception(code: 0): DateTime::__construct(): Failed to parse time string (8) at position 0 (8): Unexpected character at /var/www/mautic-xxx.xxx.xxx/app/bundles/CampaignBundle/Entity/Event.php:1015)"} []
[2022-02-14 11:47:32] mautic.ERROR: CAMPAIGN: DateTime::__construct(): Failed to parse time string (\b([8-9]|[1][0-6]):[0-5][0-9](\s)?(?i)\b) at position 0 (\): Unexpected character [] []
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### LINKED ISSUE #10870: Error during upgrade from 4.1.1 to 4.1.2
### Mautic Version

4.1.x series

### PHP version

7.4.27

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Upgrading from a newly installed version 4.1.1 to version 4.1.2 results in an error while updating the database.
The upgrade tries to create the table mt_campaign_summary
This table is already present, so I think it shouldn’t be a CREATE TABLE but an ALTER TABLE

The problem appears to be in the file Version20201120122846.php
Here is the creation of table mt_campaign_summary
If you comment the creation of this table, the update end with success.
I checked the sql to create mt_campaign_summary and the table is the same as in the previous version (4.1.1).
For this reason I assume that the file Version20201120122846.php should not be included in the migrations to upgrade from 4.1.1 to 4.1.2

I did the upgrade via console.

I also opened a topic on Mautic community forum (https://forum.mautic.org/t/error-during-upgrade-from-4-1-1-to-4-1-2/22576)

### How can we reproduce this issue?

Step 1: install mautic 4.1.1
Step 2: upgrade to mautic 4.1.2 (via console)

### Relevant log output

```shell
[2022-02-02 18:02:10] console.CRITICAL: Error thrown while running command “doctrine:migrations:migrate --quiet --no-interaction”. Message: “An exception occurred while executing ’ CREATE TABLE mt_campaign_summary ( id INT UNSIGNED AUTO_INCREMENT NOT NULL, campaign_id INT UNSIGNED DEFAULT NULL, event_id INT UNSIGNED NOT NULL, date_triggered DATETIME DEFAULT NULL COMMENT ‘(DC2Type:datetime_immutable)’, scheduled_count INT NOT NULL, triggered_count INT NOT NULL, non_action_path_taken_count INT NOT NULL, failed_count INT NOT NULL, log_counts_processed INT, INDEX IDX_42D3FE64F639F774 (campaign_id), INDEX IDX_42D3FE6471F7E88B (event_id), UNIQUE INDEX campaign_event_date_triggered (campaign_id, event_id, date_triggered), PRIMARY KEY(id) ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC; ': SQLSTATE[42S01]: Base table or view already exists: 1050 Table ‘mt_campaign_summary’ already exists” {“exception”:"[object] (Doctrine\DBAL\Exception\TableExistsException(code: 0): An exception occurred while executing '\n CREATE TABLE mt_campaign_summary (\n id INT UNSIGNED AUTO_INCREMENT NOT NULL,\n campaign_id INT UNSIGNED DEFAULT NULL,\n event_id INT UNSIGNED NOT NULL,\n date_triggered DATETIME DEFAULT NULL COMMENT ‘(DC2Type:datetime_immutable)’,\n scheduled_count INT NOT NULL,\n triggered_count INT NOT NULL,\n non_action_path_taken_count INT NOT NULL,\n failed_count INT NOT NULL,\n log_counts_processed INT,\n INDEX IDX_42D3FE64F639F774 (campaign_id),\n INDEX IDX_42D3FE6471F7E88B (event_id),\n UNIQUE INDEX campaign_event_date_triggered (campaign_id, event_id, date_triggered),\n PRIMARY KEY(id)\n ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC;\n ':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table ‘mt_campaign_summary’ already exists at /var/www/castellino/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:57, Doctrine\DBAL\Driver\PDO\Exception(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table ‘mt_campaign_summary’ already exists at /var/www/castellino/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table ‘mt_campaign_summary’ already exists at /var/www/castellino/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:132)",“command”:“doctrine:migrations:migrate --quiet --no-interaction”,“message”:“An exception occurred while executing '\n CREATE TABLE mt_campaign_summary (\n id INT UNSIGNED AUTO_INCREMENT NOT NULL,\n campaign_id INT UNSIGNED DEFAULT NULL,\n event_id INT UNSIGNED NOT NULL,\n date_triggered DATETIME DEFAULT NULL COMMENT ‘(DC2Type:datetime_immutable)’,\n scheduled_count INT NOT NULL,\n triggered_count INT NOT NULL,\n non_action_path_taken_count INT NOT NULL,\n failed_count INT NOT NULL,\n log_counts_processed INT,\n INDEX IDX_42D3FE64F639F774 (campaign_id),\n INDEX IDX_42D3FE6471F7E88B (event_id),\n UNIQUE INDEX campaign_event_date_triggered (campaign_id, event_id, date_triggered),\n PRIMARY KEY(id)\n ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC;\n ':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table ‘mt_campaign_summary’ already exists”}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### LINKED ISSUE #10877: Migration Version20201120122846 has weak checks on foreign keys that causes migration to fail
### Mautic Version

4.1.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

The migration fail to complete.

### How can we reproduce this issue?

I don't know precisely how to reproduce the issue.

But the problem is in the way the migration checks the existence of foreign keys: it assumes they are deterministic, but they are not.

I explained in details the bug in https://github.com/mautic/mautic/issues/10870#issuecomment-1045982049 and in https://github.com/mautic/mautic/issues/9129#issuecomment-1044958793

### Relevant log output

```shell
SQLSTATE[42S01]: Base table or view already exists: 1050 Table '*_campaign_summary' already exists
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/108497548-migration-version20201120122846-has-weak-checks-on-foreign-keys-that-causes-migration-to-fail?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Aerendir**
Fix #10877: The logic to check if the table exists and if it has foreign keys is weak and causes issues when foreign keys have different names (as it frequently happens).

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 4.1
| New feature/enhancement? (use the a.x branch)      | No
| Deprecations?                          | [No
| BC breaks? (use the c.x branch)        | [No
| Automated tests included?              | No
| Related user documentation PR URL      |
| Related developer documentation PR URL | 
| Issue(s) addressed                     | Fixes #10877, #10870, #10865, #9129

#### Description:

The problem comes from the foreign keys: the migration assumes the names of the foreign keys are deterministic, but they aren't, and this causes the issue.

The check, in fact, groups the creation of the table and the creation of the foreign keys in one condition, but this is wrong, as maybe the table is there and the names of foreign keys are different than the ones generated by the migration: if names are different (and they are different), then the migration fail.

The refactored logic is now more solid and avoids issues running the migration, applying only the queries really necessary.

More details here: https://github.com/mautic/mautic/issues/9129#issuecomment-1044958793

#### Steps to test this PR:

This is not always testable: it works only if you updated the database schema using `bin/console doctrine:schema:update --force`.

This command, in fact, creates the foreign keys with "arbitrary" names: in a case like this, the new logic can handle anyway the checks to verify if foreign keys already exist and, if they exist, skip the query to create them.

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10878"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
@Aerendir we also have [this PR](https://github.com/mautic/mautic/pull/10931)- maybe the changes there can be combined with your suggestions?

**Comment by Aerendir** [comment]
@RCheesley , the PR you linked fixes two migrations, while mine fixes only one.

I didn't had problems with migration `Version20201125155904`, so I don't know if it is correct or not. For sure adding `IF NOT EXISTS` to the query is a possible solution.

In my PR I focused on the check about the existence of foreign keys: this check is problematic and cannot be done in a deterministic way.

When you develop locally, you create the foreign keys, then, when generating migrations, the names generated locally are used also in every other installations that run the migration.

The problem with Mautic is that this process was not followed from the start for various reasons (primarily due to the issues with migrations that often required to manually fix tables using hard commands like `doctrine:schema:update`).

When you use such "hard commands", the generated foreign keys are different on each installation. So it is not possible to predict which will be their name.

For this reason I created the method `AbstractMauticMigration::tableHasForeignKey()`: it check foreign key by foreign key to find one for the desired fields, independently by its name.

This makes possible to avoid issues caused by the names of foreign keys being not deterministic.

The other PR, instead, continues to use the old method `getForeignKeyName()` that assumes the names of foreign keys are deterministic (while they are not).

So, in the end, the other PR doesn't fix the issue we have with migration `Version20201120122846` that this PR, instead, fixes.

**Comment by kuzmany** [comment]
@escopecz can you check @Aerendir PR and comment https://github.com/mautic/mautic/pull/10878#issuecomment-1061534250 If it's duplicate. 
You're the most deep in the topic

**Comment by escopecz** [comment]
@RCheesley https://github.com/mautic/mautic/pull/10931 is not a duplicate of this PR although both target to fix the same migration.

@Aerendir 

> The other PR, instead, continues to use the old method getForeignKeyName() that assumes the names of foreign keys are deterministic (while they are not).

The foreign key names are deterministic. The problem is that the name is generated based on the table name. And Mautic inherited a nasty "feature" from Joomla CMS that it allows to define database table prefix. It caused so much bugs and pain so far and it has no real benefit as I doubt anyone hosts 2 instances in 1 database these days. I remember days when an extra database was for extra cost on shared web hostings, but that's not applicable now and for such DB-heavy app as Mautic.

@kuzmany: both PRs can be tested, reviewed and merged independently.

**Pull request closed without merging**
