### PR TITLE
Fix migrations preup with table prefix and migration performance

### PR DESCRIPTION
**Pull request by rohitpavaskar**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [Y]
| New feature/enhancement? (use the a.x branch)      | [N]
| Deprecations?                          | [N]
| BC breaks? (use the c.x branch)        | [N]
| Automated tests included?              | [N] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR fixes issue with correct preUp migration conditions with and without prefix.
Also optimise query generation

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Run the migrations on old version of Mautic and check migrations are successful

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11371"></a>

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
Thanks Rohit! 👍

**Comment by RCheesley** [comment]
Thanks @rohitp19 - would you be able to rebase this on the 4.4 branch so we could get it into the next bug fix release?

**Comment by RCheesley** [comment]
Presumably to test this we need an old (maybe Mautic 3?) version of Mautic with a database prefix in use to test the migrations are working correctly, is that a good understanding of the testing required?

**Review by kuzmany — DISMISSED** [review]
Code looks good.
I've run all migrations. Does not see issue 
We can go 👍

**Comment by escopecz** [comment]
I checked how hard it would be to rebase this on 4.4 which is the bug fix branch and there were conflicts in 86 files. Gonna merge it in 4.x and it will take longer to get to production. @rohitpavaskar please use the right branch in the future so it can be released sooner.

**Comment by escopecz** [comment]
There will be no more feature releases for M4. I'll merge this into M5 (the 5.x branch)

**Pull request merged**
