### PR TITLE
run PHPUnit tests with a random db prefix by default

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

PR is based on 4.x, once 5.x is up-to-date, I'll change the base

This PR ensures all tests are executed with a db table prefix to ensure both tests and functionality are compatible with it.
This to prevent that code covered by a test is missing awareness of a db table prefix.

This PR adds a `BeforeFirstTestHook` to the phpunit test suite, that sets a random `MAUTIC_TABLE_PREFIX` if it isn't defined yet.
All places that check the existence of `MAUTIC_TABLE_PREFIX` are removed from the tests, as those are obsolete.

If you want to use a fixed / specific prefix in the tests, it's still possible by setting the env var in the `app/phpunit.xml.dist`  file.

#### Steps to test this PR:

* nothing really to test, if tests pass, all good :)

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by mollux** [comment]
that codecov makes no sense, that file isn't even changed by this PR

**Comment by RCheesley** [comment]
> that codecov makes no sense, that file isn't even changed by this PR

Usually means that the PR needs to be updated or rebased from the base branch. This should be on the 4.3 branch really, we will not make any further releases from 4.x.

**Comment by mollux** [comment]
@RCheesley shouldn't it be on 5.x? It's not a bugfix? But 5.x is out of date :)

**Comment by RCheesley** [comment]
Sure but if it is adding a unit test and no other changes to Mautic we usually try to merge them sooner rather than later (anything labelled as a Chore does not get included in the release notes)

**Comment by mollux** [comment]
@RCheesley changing to 4.3 gives the same result, It refers to the same file not part of the PR

**Review by escopecz — APPROVED** [review]
This is good to go. Thank you @mollux !

_Since it does not touch any production code and just improves tests then one review is fine to get this merged._

**Comment by escopecz** [comment]
@mollux I'm having trouble running functional tests on local due to this change. If I comment out the inside of the `executeBeforeFirstTest` method then it starts working. The problem seem to be that the schema is created with the db prefix taken from local.php file but the test tries to access the tables with the prefix generated in `executeBeforeFirstTest`. Do you have some suggestion on how to run tests locally? I don't quite understand how come it works on GH Actions.

Steps to reproduce:
1. Run `composer test -- --filter testViewActionCompany` and get 500 error.

**Comment by escopecz** [comment]
If you check the [prepareDatabase()](https://github.com/mautic/mautic/blob/5.x/app/bundles/CoreBundle/Test/MauticMysqlTestCase.php#L169) method then the schema is cached to a file and used for the rest of the test suite. But the DB prefix is generated before each test. So I can't wrap my head around how this can work.

**Pull request merged**
