### PR TITLE
Added support for MySQL full-text search queries

### PR DESCRIPTION
**Pull request by fedys**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging for features or enhancements / 3.0 for bug fixes 
| Bug fix?                               | no
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      |
| Related developer documentation PR URL |
| Issue(s) addressed                     | 

#### Description:
We needed search using MySQL full-text indices in the Custom Objects plugin (to be open sourced soon). This PR adds support for this. The example of usage follows:

Adding a new fulltext index to a field:
```php
public static function loadMetadata(ORM\ClassMetadata $metadata): void
{
    $builder = new ClassMetadataBuilder($metadata);
    $builder->addFulltextIndex(['title'], 'title_fulltext');
```

Searching by the field:
```php
$queryBuilder->andWhere('MATCH (Entity.title) AGAINST (:search BOOLEAN) > 0');
$queryBuilder->setParameter('search', (string) new FulltextKeyword($search));
```

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/9335"></a>

### CODE REVIEW

**Comment by kuzmany** [comment]
@fedys can you check conflicts?

**Comment by fedys** [comment]
@kuzmany conflicts have been resolved.

**Comment by RCheesley** [comment]
Conflicts to be resolved again - hoping we can get it tested soon!

**Review by mabumusa1 — COMMENTED** [review]
I did code review, it looks good.

@fedys is there a specific test case that I can test locally

**Comment by fedys** [comment]
@mabumusa1 thanks for the code review. The only way to test this PR is adding an arbitrary full-text index to an entity (and running `doctrine:schema:update`)
```php
public static function loadMetadata(ORM\ClassMetadata $metadata): void
{
    // ...
    $builder->addFulltextIndex(['title'], 'title_fulltext');
```
 and a DQL condition containing `MATCH` / `AGAINST` keywords
```php
$queryBuilder->andWhere('MATCH (Entity.title) AGAINST (:search BOOLEAN) > 0');
$queryBuilder->setParameter('search', (string) new FulltextKeyword($search));
```
Then make sure the resulting SQL query is correct and returning expecting results.

**Comment by escopecz** [comment]
@npracht this one is also requirement for the custom objects plugin

**Review by kuzmany — APPROVED** [review]
I did test:
- update composer
- create fulltext alias of  Leadlist entity

        `$builder->addFulltextIndex(['alias'], 'alias_fulltext');`
        
Then I've created test method on LeadListRepository
```php

 /**
     * Return a list of global lists.
     *
     * @return array
     */
    public function getFullTestList()
    {
        $q = $this->getEntityManager()->createQueryBuilder()
            ->from(LeadList::class, 'l', 'l.id');
        $q->select('partial l.{id, name, publicName, alias}')
            ->where($q->expr()->eq('l.isPublished', ':true'))
            ->setParameter(':true', true, 'boolean')
            ->andWhere('MATCH (l.alias) AGAINST (:search BOOLEAN) > 0')
            ->setParameter('search', (string) new FulltextKeyword('segment'))
            ->orderBy('l.name');

        return $q->getQuery()->getArrayResult();
    }
```       

Method result fulltext search of segment

Nice 👍

**Comment by RCheesley** [comment]
@mabumusa1 would you be able to do the second test on this PR so we can get it merged please? Thanks!

**Review by mabumusa1 — APPROVED** [review]
I followed the same steps @kuzmany did to test this PR, it worked as expected
Thanks @fedys

**Pull request merged**
