### PR TITLE
Future browsers samesite none

### PR DESCRIPTION
**Pull request by lukassykora**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | No
| New feature? | Yes, make Mautic ready for future browsers
| Automated tests included? |Yes, they work just with Xdebug enabled. Otherwise, they are skipped.
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Steps to test this PR:
1. Enable these flags in Chrome `chrome://flags/#same-site-by-default-cookies` , `chrome://flags/#cookies-without-same-site-must-be-secure`
2. Check that you get all cookies as before and tracking works well

### CODE REVIEW

**Comment by dsp76** [comment]
If I understand correctly: the flag instructs the browser to accept the cookie, it its secure, although not from the same site? Does it work also, when the parent page has a different flag (set by the CMS)? I doubt Firefox in current standard settings would not accept a cookie from a 3rd party domain: https://support.mozilla.org/en-US/kb/disable-third-party-cookies "Cross-site tracking cookies are now blocked for all users by default."

**Comment by dennisameling** [comment]
@lukassykora Thanks for providing this PR! We have merged #8337 so that tests should pass again. Could you please rebase your branch from `staging` so that we can see if the tests indeed pass? Thanks in advance! 😄

**Comment by dennisameling** [comment]
Just got confirmed by @lukassykora (via Slack) that he will rebase this PR either today or tomorrow

**Comment by dennisameling** [comment]
@lukassykora I tested with the Mautic tracking script, but don't seem to be getting the `; samesite=none`:

**Mautic 2.15 server**
`curl -v MY_MAUTIC_2.15_SITE/mtc.js`

`set-cookie: 95e171c7d0ee2d1fb5f9b9bda735097a=1u5bofoa2lipef4q0jon82rh59; path=/; secure; HttpOnly`

image

**Mautic server PR 8347**
`curl -v https://mautic-samesite.ddev.site/mtc.js`

`set-cookie: aa77b0c860a282cddf3df03e28a1d3cc=35d607506c16e7b3f98f264713d4d54d; path=/; secure; HttpOnly`

image

Am I doing something wrong? 😕

**Pull request merged**
