### PR TITLE
fix: Has valid email address campaign condition always results true

### LINKED ISSUE #7904: Has valid email address campaign condition always results true
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The `Has valid email address` campaign condition always results true. 
I traced back the error to a point where I think I know what the problem is, but I don't know enough of how campaigns work to solve on my own

The condition is evaluated in `Mautic\EmailBundle\EventListener\CampaignConditionSubscriber` eventlister object in the `onCampaignTriggerCondition` method

```
/**
     * @param CampaignExecutionEvent $event
     */
    public function onCampaignTriggerCondition(CampaignExecutionEvent $event)
    {
        try {
            $this->validator->validate($event->getLead()->getEmail());
        } catch (InvalidEmailException $exception) {
            return $event->setResult(
                [
                    'timeline' => $exception->getMessage(),
                ]
            );
        }

        return $event->setResult(true);
    }
```

If for example the contact doesn't have email address, the validation done by `Mautic\EmailBundle\Helper\EmailValidator` throws the `InvalidEmailException`  as expected

However it seems that the result setting in the catch also leads to be evaluated as a positive result
```
$event->setResult(
                [
                    'timeline' => $exception->getMessage(),
                ]
            )
```

Now I'm not sure if the `CampaignExecutionEvent $event` param is really of `Mautic\CampaignBundle\Event\CampaignExecutionEvent` class or `Mautic\CampaignBundle\Event\ConditionEvent` (which is an descendant of the previous one)

The `CampaignExecutionEvent` seems to be some legacy stuff. It has a `setFailed` method, which seems to be more proper way of setting a failed result.
```
public function setFailed($reason = null)
    {
        $this->result = [
            'failed' => 1,
            'reason' => $reason,
        ];

        return $this;
    }
```

The `Mautic\CampaignBundle\Event\ConditionEvent` on the other hand has a different `setResult` method:
```
public function setResult($result)
    {
        $this->passed = (bool) $result;

        return $this;
    }
```
which considers every non-false parameter as true. 
I believe this is why the param array with timeline index leads to the condition always considered true.

I believe it should be corrected as this:

```
/**
     * @param CampaignExecutionEvent $event
     */
    public function onCampaignTriggerCondition(CampaignExecutionEvent $event)
    {
        try {
            $this->validator->validate($event->getLead()->getEmail());
        } catch (InvalidEmailException $exception) {
            return $event->setResult(false);
        }

        return $event->setResult(true);
    }
```

But I'm not sure what relevancy that array with timeline index has. 
Maybe someone with more experience than me can approve this solution before I initiate a PR?

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.3
| Browser | 

### Steps to reproduce
1. Create a campaign that has a `Has valid email address` condition
2. add some action to the  `true` branch of the condition
3. add a contact without email to a campaign
4. see how the action is triggered on the contact without email address
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by pety-dc**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| Automated tests included? | -
| Related user documentation PR URL | -
| Related developer documentation PR URL |  -
| Issues addressed (#s or URLs) |  -
| BC breaks? |  -
| Deprecations? |  -

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
fixes https://github.com/mautic/mautic/issues/7904 as proposed there.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
described here: https://github.com/mautic/mautic/issues/7904

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create a campaign that uses a `has valid email address` condition on contacts without email address

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Review by RCheesley — APPROVED** [review]
Thanks for this PR @pety-dc - tested per the details provided in #7904 and confirmed the problem - all contacts were taken down the valid email route.

Applied the PR and confirm that both the addition and deletion of tags based on the email being valid or invalid (which is what I used to check) is working as expected.  Great fix! 👍

**Review by kuzmany — APPROVED** [review]

**Comment by tamerzg** [comment]
Any info when this might get released?

**Comment by pety-dc** [comment]
@tamerzg 
To be honest, I don't know if 2.16.0 is ever going to be released. The main Mautic developer guys seem to have switched focus to release 3.0.0 some week ago. Ever since that the development of 2.16.0 has stalled.
I'm not in the inner circle where these kind of decisions are made. (There is maybe a discord channel for this purpose)

**Comment by npracht** [comment]
Hi @pety-dc can you check if your PR is mergeable in https://github.com/mautic/mautic/tree/3.x and manage conflicts if needed?
Then we give a chance to the PR to be merged in 3.0.0. Thanks !

**Comment by pety-dc** [comment]
@npracht 
> Hi @pety-dc can you check if your PR is mergeable in https://github.com/mautic/mautic/tree/3.x and > manage conflicts if needed?
> Then we give a chance to the PR to be merged in 3.0.0. Thanks !

Does your question imply that 2.16.0 and 3.0.0 diverged and 2.16.0 won't be merged into 3.0.0, unless each PR that was merged into 2.16.0 (or was not merged to any milestone at all) got rerequested to merge into 3.0.0?

**Comment by npracht** [comment]
Hi @pety-dc it will be merged (already merged actually). When i posted this message we didn't plan 2.16.0 as it is today ;)
Nothing to do on your side :)

**Comment by pety-dc** [comment]
@npracht 
thanks!
What about those PRs that did not make it into 2.16.0? Will there be a 2.16.1 or 2.17.0?

**Comment by npracht** [comment]
I'm currently working with @dennisameling to make them mergeable in mautic 3.x series.
We'll get back to you if we need help. Feel free to join #t-product channel on slack if you like, then we could rely on you in case we need your help ;)

**Comment by imihandstand** [comment]
I updated my Mautic to 2.16.3 just for this, however it still does not work, it still gives a "valid" to totally invalid addresses. I checked the "CampaignConditionSubscriber.php" file and it is like here the fix says ( https://github.com/mautic/mautic/pull/7960/files ) - but as said, it is still not working. How to fix this?

**Pull request merged**
