### PR TITLE
Segment fail notifications

### PR DESCRIPTION
**Pull request by escopecz**
Note: The code changes were made by Anton, I just cherry-picked them so all the glory goes to him.

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | /
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
We want to know what was the last time we have rebuilt each segment and raise a warning if it is longer than expected. 

Acceptance criteria
- [x] Add a new column to the lead_lists table called "last_built_date"
- [x] Update timestamp every time the particular segment is being rebuilt for all contacts (not just for some). In the command for the community (when called without min, max and contact ID arguments) and in the finalize job for the cloud.
- [x] Check if last_built_date is older than 30 (configurable) hours then add a red exclamation mark next to the segment name in the segment list table with tooltip "This segment hasn't been rebuilt for X hours".

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
This is not a bug so there is nothing to reproduce.

#### Steps to test this PR:
2. Create a new segment.
3. Go to the `lead_lists` table and make sure that `last_built_date` column has datetime value. Remember that value.
4. Add some contacts to your segment using a segment filter. E.g. you can create a email based segment filter to add all contacts that have email defined (not empty).
5. Make sure that `last_built_date` value has been updated.
6. Go to the Campaign Studio -> Configuration -> Segment Settings -> Show warning if segment hasn't been rebuilt for X hours. Change that value to 1.
7. Wait 1 hour, go the segments view page `/s/segments`. Make sure that you see a red exclamation mark next to the segment name. If you hover the cursor over it you should see the following text: 
"This segment hasn't been rebuilt for 1 hour."

#### Other areas of Mautic that may be affected by the change:
1. I can't think of any. 

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10772"></a>

### CODE REVIEW

**Review by kuzmany — DISMISSED** [review]
Nice addition
Works 👍 
Code looks good 👍 
Unit tests included 👍 

image

**Comment by jos0405** [comment]
@escopecz I found something weird here.
If you create the segment first time with no results, and just then create a qualifying result, then the last build date will be never updated. If you add a filter, which right away finds a contact, then it works.
See console:

# NO CONTACT QUALIFIES AT THIS POINT:

+----+-------------+--------------+---------------------+------------+-----------------+---------------+-------------+------------------+-------------+----------------+---------------------+------------+-------------+------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------+---------------------+
| id | category_id | is_published | date_added          | created_by | created_by_user | date_modified | modified_by | modified_by_user | checked_out | checked_out_by | checked_out_by_user | name       | description | alias      | public_name | filters                                                                                                                                                                                   | is_global | is_preference_center | last_built_date     |
+----+-------------+--------------+---------------------+------------+-----------------+---------------+-------------+------------------+-------------+----------------+---------------------+------------+-------------+------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------+---------------------+
|  1 |        NULL |            1 | 2022-02-04 11:22:42 |          1 | Admin Mautic    | NULL          |        NULL | NULL             | NULL        |           NULL | NULL                | Joey Email | NULL        | joey-email | Joey Email  | a:1:{i:0;a:7:{s:4:"glue";s:3:"and";s:5:"field";s:5:"email";s:6:"object";s:4:"lead";s:4:"type";s:5:"email";s:6:"filter";s:17:"jos0405@gmail.com";s:7:"display";N;s:8:"operator";s:1:"=";}} |         1 |                    0 | 2022-02-04 11:22:42 |
+----+-------------+--------------+---------------------+------------+-----------------+---------------+-------------+------------------+-------------+----------------+---------------------+------------+-------------+------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------+---------------------+
1 row in set (0.001 sec)

MariaDB [db]> exit
Bye
gitpod /workspace/mautic $ ddev exec bin/console mautic:segment:update
Rebuilding contacts for segment 1
0 total contact(s) to be added in batches of 300
0 total contact(s) to be removed in batches of 300
0 contact(s) affected
gitpod /workspace/mautic $ ddev exec mysql
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

MariaDB [db]> use db;
Database changed
MariaDB [db]> select * from lead_lists
    -> ;
+----+-------------+--------------+---------------------+------------+-----------------+---------------+-------------+------------------+-------------+----------------+---------------------+------------+-------------+------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------+---------------------+
| id | category_id | is_published | date_added          | created_by | created_by_user | date_modified | modified_by | modified_by_user | checked_out | checked_out_by | checked_out_by_user | name       | description | alias      | public_name | filters                                                                                                                                                                                   | is_global | is_preference_center | last_built_date     |
+----+-------------+--------------+---------------------+------------+-----------------+---------------+-------------+------------------+-------------+----------------+---------------------+------------+-------------+------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------+---------------------+
|  1 |        NULL |            1 | 2022-02-04 11:22:42 |          1 | Admin Mautic    | NULL          |        NULL | NULL             | NULL        |           NULL | NULL                | Joey Email | NULL        | joey-email | Joey Email  | a:1:{i:0;a:7:{s:4:"glue";s:3:"and";s:5:"field";s:5:"email";s:6:"object";s:4:"lead";s:4:"type";s:5:"email";s:6:"filter";s:17:"jos0405@gmail.com";s:7:"display";N;s:8:"operator";s:1:"=";}} |         1 |                    0 | 2022-02-04 11:22:42 |
+----+-------------+--------------+---------------------+------------+-----------------+---------------+-------------+------------------+-------------+----------------+---------------------+------------+-------------+------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------+---------------------+
1 row in set (0.001 sec)

# ADDED THE CONTACT WHO QUALIFIES

MariaDB [db]> exit
Bye
gitpod /workspace/mautic $ ddev exec bin/console mautic:segment:update
Rebuilding contacts for segment 1
1 total contact(s) to be added in batches of 300
 1/1 [============================] 100%
0 total contact(s) to be removed in batches of 300
1 contact(s) affected
gitpod /workspace/mautic $ ddev exec mysql
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 56
Server version: 10.3.32-MariaDB-1:10.3.32+maria~focal-log mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [db]> use db;
Database changed
MariaDB [db]> select * from lead_lists;
+----+-------------+--------------+---------------------+------------+-----------------+---------------+-------------+------------------+-------------+----------------+---------------------+------------+-------------+------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------+---------------------+
| id | category_id | is_published | date_added          | created_by | created_by_user | date_modified | modified_by | modified_by_user | checked_out | checked_out_by | checked_out_by_user | name       | description | alias      | public_name | filters                                                                                                                                                                                   | is_global | is_preference_center | last_built_date     |
+----+-------------+--------------+---------------------+------------+-----------------+---------------+-------------+------------------+-------------+----------------+---------------------+------------+-------------+------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------+---------------------+
|  1 |        NULL |            1 | 2022-02-04 11:22:42 |          1 | Admin Mautic    | NULL          |        NULL | NULL             | NULL        |           NULL | NULL                | Joey Email | NULL        | joey-email | Joey Email  | a:1:{i:0;a:7:{s:4:"glue";s:3:"and";s:5:"field";s:5:"email";s:6:"object";s:4:"lead";s:4:"type";s:5:"email";s:6:"filter";s:17:"jos0405@gmail.com";s:7:"display";N;s:8:"operator";s:1:"=";}} |         1 |                    0 | 2022-02-04 11:22:42 |
+----+-------------+--------------+---------------------+------------+-----------------+---------------+-------------+------------------+-------------+----------------+---------------------+------------+-------------+------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------------------+---------------------+
1 row in set (0.001 sec)

MariaDB [db]>

**Comment by jos0405** [comment]
Actually, I tested different cases now, it just doesn't work for me. Doesn't update the last build date.

**Comment by escopecz** [comment]
@jos0405 you are right. I'm looking at the code and it will execute only if the `--max` command option is set. I guess it comes from how Acquia is rebuilding the segments but it's not useful for the community usage. I'll update it. It should set the date for full rebuilds with no ID ranges or min maxes set.

**Comment by escopecz** [comment]
@jos0405 I found the problem. It is correct on our fork so the problem must have happened during the commit cherry-picking. I added functional test to ensure this works as expected. Ready to retest.

**Review by kuzmany — DISMISSED** [review]
last_build_date updated on segment rebuild 👍 
If I change it then warning  shown 👍 
image
Unit tests included 👍

**Review by jos0405 — DISMISSED** [review]
Works as expected. Very useful PR.

**Comment by kuzmany** [comment]
@escopecz some conflicts after segment refactoring merge

**Comment by escopecz** [comment]
@kuzmany rebase is done

**Review by kuzmany — APPROVED** [review]

**Pull request merged**
