### PR TITLE
flip array returned by getDateChoices

### PR DESCRIPTION
**Pull request by pety-dc**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [yes ]
| New feature/enhancement? (use the a.x branch)      | [no ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [no ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #3180 

#### Description:
While originally the method return the values in a [label => value] manner, it's clear from both CampaignEventLeadFieldValueType::buildForm and AjaxController::updateLeadFieldValuesAction that it should be flipped, because both of them adds a custom option in [value => Label] manner

This bug prevents date operator in Contact Field Value type Campaign Condition from working properly

This is how it looks like now:
image

This is how it supposed to look like:
image

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11233"></a>

### CODE REVIEW

**Review by IrisAmrein — DISMISSED** [review]
I've tested this in campaigns and it did work well for me for Date fields.

The filter doesn't work with Date/Time Fields - but that is another issue.

**Review by escopecz — DISMISSED** [review]
This change makes sense because the labels are again flipped with values in https://github.com/mautic/mautic/blob/eb4b5567303d1d2c77f44f82c88ac4b17029e65b/app/bundles/LeadBundle/Form/Type/CampaignEventLeadFieldValueType.php#L156

The AjaxController does not flip anything and the JS working with the response expects the value to be in the key position:

https://github.com/mautic/mautic/blob/eb4b5567303d1d2c77f44f82c88ac4b17029e65b/app/bundles/CoreBundle/Assets/js/6.forms.js#L596

So From code perspective this change makes sense and is the simplest way to fix the issue.

Thank you! 👍

**Comment by escopecz** [comment]
@all-contributors please add @pety-dc for code

**Comment by escopecz** [comment]
@all-contributors please add @IrisAmrein for user testing

**Review by escopecz — APPROVED** [review]

**Pull request merged**
