### PR TITLE
amazon AWS port changed from 2587 to 587

### PR DESCRIPTION
**Pull request by infinite-l00p**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | Y
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
In the app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php the port is 2587. This port doesn't work and in the "configuration/email settings/Mail Send Settings" it returns the error attached.

As per the Amazon AWS documentation the ports to be used are 25,465 or 587. 
screen shot 2017-10-06 at 11 39 28
587 works fine and I already tested it by sending 6k emails.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Set up an amazon aws account and enter the credentials in the "configuration/email settings/Mail Send Settings" , click "TEST connection" , you'll receive the error attached
screen shot 2017-10-06 at 11 38 02

2. 

#### Steps to test this PR:
1. Change the port from 2587 to 587 in the app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php #33
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by alanhartless** [comment]
This was changed to 2587 by https://github.com/infinite-l00p/mautic/commit/9de6765ed6bb5a93f92f5d025c8f5bf96c6687f2#diff-98241096c624fbe4721548066e44239b. Does your server have port 2587 open?

**Comment by AndrassGray** [comment]
Port 2587 works fine for me, and is definitely ok as per the Amazon docs here : http://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-connect.html

**Comment by infinite-l00p** [comment]
@AndrassGray which cluster are you on? I'm on us-west2
I checked the public doc link and it does say port 2587 is fine, but when I login into aws console, SES Home / SMT SETTINGS the port 2587 doesn't get mentioned

`

Server Name: | email-smtp.us-west-2.amazonaws.com
-- | --
Port: | 25, 465 or 587
Use Transport Layer Security (TLS): | Yes
Authentication: | Your SMTP credentials - see below.

`

**Comment by AndrassGray** [comment]
@infinite-l00p : I am on the good side of the pond : eu-west-1 ;)

I have the same in my SMTP settings, but still port 2587 works as documented.

Server Name: | email-smtp.eu-west-1.amazonaws.com
-- | --
Port: | 25, 465 or 587
Use Transport Layer Security (TLS): | Yes
Authentication: | Your SMTP credentials - see below.

**Comment by infinite-l00p** [comment]
@AndrassGray Lol ... technically I'd be from the same side of the pond but for some reason I got the us-west-2 instance.

When I run through ssh i get this

```
telnet email-smtp.us-west-2.amazonaws.com 2587
Trying 52.27.155.246...
telnet: connect to address 52.27.155.246: Connection refused
```

But when I do on my localhost it connects fine.
I opened a ticket with my hosting provider to open the port 2587 . 
Once they do the change I'll update you .

In the meantime, do you think would be useful to have the AmazonTransport test in sequence the port 2587 and 587 as fallback ? Maybe somebody else might experience the same problem (I'm on eHost now)

**Comment by infinite-l00p** [comment]
Hi guys, sorry I made a mistake for the last pull request
the last 4 commits were actually a fix for the #2992 issue.
How can I move it?

Thanks

**Comment by infinite-l00p** [comment]
@alanhartless @AndrassGray 
I opened a ticket to my hosting provider for opening port 2587.
Port 2587 is opened and the connection works fine again.

The provider told me that by default port 2587 is blocked on their platform.

Since other users might experience this problem and given that AWS SES can work on port 587 either, why can't we implement a fallback strategy?

-FIRST RUN 
--check if an "AWS_SES_PORT" config is present
---TRUE: use the AWS_SES_PORT
---FALSE: try the port specified in the array [2587,587] and use the first one which doesn't return error. Write the port to the config

What do you think?

**Comment by alanhartless** [comment]
Closing this only because SES API (#5263) is in the works which will make this no longer applicable.

**Pull request closed without merging**
