### PR TITLE
Changing with from px to % on the builder

### PR DESCRIPTION
**Pull request by zhakid**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? |  Y
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/4739
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Changing app.css builder panel with to 30% and content to 70%
[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1.  Enter Builder
2. See the new dimension 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by viryagroupdev** [comment]
@escopecz

**Comment by viryagroupdev** [comment]
Hi check this out @escopecz

**Comment by escopecz** [comment]
The `app.css` file is auto-generated from the less files. For example here is where [.builder-content is styled](https://github.com/mautic/mautic/blob/0e56047f252405c15635f1658f89535b021942bc/app/bundles/CoreBundle/Assets/css/app/less/components/builder.less#L51)

To see the changes, you'll have to run `grunt compile-less` command in the Mautic root dir to compile the changes in less files to app.css.

**Comment by zhakid** [comment]
Ok, On it!

**Comment by viryagroupdev** [comment]
pending for feedback?

**Comment by viryagroupdev** [comment]
@escopecz

**Comment by escopecz** [comment]
It doesn't look right to me:
screen shot 2017-09-27 at 10 21 22

I will push update to package.json since I got this error running `grunt compile-less`:
`>> Error: Cannot find module 'grunt-remove'`

Then I run `grunt compile-less` successfully, but it updated app.css a little bit, so I'm pushing that too.

**Comment by alanhartless** [comment]
@escopecz do you want to retest this? It looked fine to me and width obeyed percentages.

**Comment by javjim-mautic** [comment]
Works properly for me

**Pull request merged**
