### PR TITLE
[UI] Remove minimize sidebar feature

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR removes the minimize sidebar feature, based on [community votes in Slack](https://mautic.slack.com/archives/C024XBCQS3Z/p1721932963539929).
It also considers user feedback regarding hiding things that just don't work fully.

Until now, we had an issue with the sidebar, where in the minimized state, everything under a submenu becomes inaccessible. So replacing we can focus on improving the experience in different ways.

This PR also removes old code related to the right sidebar, replaced recently.

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open the Dashboard and check if you can use the sidebar properly.
3. Using your browser's developer tools, activate the mobile mode and check if the sidebar can be accessible and keeps working normally.

### CODE REVIEW

**Review by Esthertests — COMMENTED** [review]
@andersonjeccel are we removing the collapse on desktop view with this PR?

**Comment by andersonjeccel** [comment]
@Esthertests Yes, it seems like no one is using and we have the issue that when minimized, you become unable to access some pages

**Review by Esthertests — APPROVED** [review]
Approving this looks good to me

**Review by Bastian2718 — APPROVED** [review]
Sidebar is good. Help Symbol and Searchsymbol are no more centered to its field. 
Bildschirmfoto 2024-08-13 um 16 47 30

**Comment by andersonjeccel** [comment]
Hey @Bastian2718 

Thanks for being available to help!

I noticed something that might be helpful to check:
You're probably testing pull requests without clearing the browser's cache between each test; this causes unrelated bugs to appear (like the example you've shown)

addressing this will help us to keep reviews moving forward in a good way, tell me if you need help to disable the cache

**Review by LordRembo — APPROVED** [review]
code-wise, it's fine, just removes the things relevant to that minimized sidebar

**Comment by escopecz** [comment]
@andersonjeccel there are conflicts

**Comment by andersonjeccel** [comment]
@escopecz Solved!

**Pull request merged**
