### PR TITLE
Twitter monitoring command fixed

### PR DESCRIPTION
**Pull request by escopecz**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/4100
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

This error happened if you try to get the Twitter monitoring:
```
$ app/console mautic:social:monitoring
Executing Monitor Item 5

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 2 passed to Mautic\PluginBundle\Helper\oAuthHelper::__construct() must be an instance of Symfony\Component\HttpFoundation\Request, null given, called in app/bundles/PluginBundle/Integration/AbstractIntegration.php on line 982
```

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Make sure you have the Twitter plugin configured
2. Create a new Social Monitoring
3. Run the command mentioned above, you should get the error from above.

#### Steps to test this PR:
1. Apply this PR
2. Test again, the command works

### CODE REVIEW

**Comment by escopecz** [comment]
I also fixed 
```
$ composer update --lock
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ~5.6.19|~7.1 but your PHP version (7.0.17) does not satisfy that requirement.
```
and
```
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
```
In this PR

**Comment by robwent** [comment]
I've tested on 2 sites and twitter monitoring is working after the change

**Comment by mqueme** [comment]
👍

**Comment by billybobilly** [comment]
made the suggested changes yesterday and fixed the issue.  today, I upgraded to 2.8.2 and it's broken again.  Here's the error:

[Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                                                         
  Catchable Fatal Error: Argument 2 passed to Mautic\PluginBundle\Helper\oAuthHelper::__construct() must be an instance of Symfony\Component\HttpFoundation\Request, null given, called in /var/ww  
  w/mautic/app/bundles/PluginBundle/Integration/AbstractIntegration.php on line 1120 and defined

**Comment by escopecz** [comment]
It has been broken by other PR which was added to 2.8.2. See https://github.com/mautic/mautic/issues/4100 for further discussion.

**Pull request merged**
