### PR TITLE
Never catch all exceptions

### PR DESCRIPTION
**Pull request by jbransen**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

In two places in the code we catch all types of exceptions, and silently continue the execution when they happen. This means that the campaigns:trigger cron can exit with a zero exit code even though exceptions occured. Needless to say this is not a good idea, so this merge requests makes sure to (re)throw those exceptions.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Run Mautic on a larger scale I guess?

#### Steps to test this PR:
? 
I believe the code change should speak for itself.

### CODE REVIEW

**Comment by heathdutton** [comment]
The problem with this approach is that if you have a critical exception within one campaign, it can prevent other campaigns from running which can be a much bigger problem and isn't BC. I agree there is a problem though as I recently had SQL exceptions causing subsequent campaign triggering batches to fail.

Please see #7605 for another approach which is BC. We're running this in production now w/ ~1M new leads a day and it's very stable.

**Comment by alanhartless** [comment]
In agreement with @heathdutton and the reason we were catching the exceptions and logging them so that a bug in one campaign event does not completely halt execution for many of your campaigns, especially if the job can never get passed that one event until the bug is fixed, the event removed, or the campaign unpublished.

**Comment by jbransen** [comment]
> "if you have a critical exception within one campaign, it can prevent other campaigns from running"

Yes, that is the whole point. An exception means something exceptional has happened, the system crashed, and since your catching any exception here you don't know what happened. Maybe the system ran out of memory, maybe the database got corrupted, who knows, but I certainly don't want to continue trying to handle campaign events. #7605 does not solve that problem. It rethrows for some very specific exceptions, but still arbitrary unknown exceptions are caught and don't stop the system, even though they may have brought the system in a corrupted state.

If you want to have the behaviour you're describing, e.g. continue with the next campaign when something went wrong with a previous campaign, I would suggest to implement that differently, by:
1. Catching only specific exceptions that you want to ignore, e.g. maybe all MauticExceptions that are internally thrown, or some list, but at least as specific as possible
2. Make this optional and put it behind some `--continue-on-error` flag, which is off by default. This makes users aware of what is happening.

**Comment by heathdutton** [comment]
@jbransen Capturing exceptions is an acceptable pattern because in some cases there is much third-party plugin interaction taking place and there are always unknowns. So long as exceptions are logged, they are visible. To give context, we have hundreds of campaigns and if campaign number 43 uses a third-party plugin to send leads to a third party, which (unbeknownst to me) throws exceptions because they used Guzzle without the right options, then suddenly our entire business screeches to a halt. Campaign 44 through 789 stop functioning. It may take an hour to figure out what's going on, and it'll take up to 4 days to recover completely at our volume.

With a caught exception, only one campaign is affected. We will still notice the error in our various log tracing tools, and it may even show up in our Mautic notifications (depending on how the plugin was made). Nobody runs these commands manually, but instead by cron task... So a thrown exception is not really any *better* for non-developers.

IF you are running these manually, and suspect you have untested or unreliable code then just use --env=dev to throw those exceptions. You can run this in production, and I've done it for tracing down problems as you've described.

**Comment by jbransen** [comment]
We clearly have very different opinions on software development.

**Comment by heathdutton** [comment]
@jbransen, if your issue is the exit code, that's easy to fix... we can (and should) return a 1 if any exceptions were trapped along the way.

**Comment by jbransen** [comment]
Yes, that is my main issue, and I would have not created this merge request when the trigger command would have ended with a non-zero exit code. It would also have saved us a lot of hassle because using exit codes of processes to monitor whether everything is right is a well established method. I'll adapt the merge request to at least fix that.

I still strongly believe that exceptions that cannot be properly handled should bubble up all the way to the top so that proper exception handling can take place at each level, but I understand that it is of no use to continue that discussion.

**Comment by npracht** [comment]
@alanhartless and @heathdutton, any conclusion on that debate ?

**Comment by heathdutton** [comment]
I think the PR looks fine, and ready to test. 👍

**Review by alanhartless — DISMISSED** [review]
Code review looks good; needs to be tested

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by npracht** [comment]
Hello @jbransen could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback. Thanks !

**Comment by jbransen** [comment]
I'll have a look in October

**Comment by npracht** [comment]
Hi @jbransen ! thanks for answering. I am not sure to understand, you meant October on purpose?

**Comment by jbransen** [comment]
If you read the whole thread, I think my sarcasm should have been obvious. But yes, I wrote October on purpose, but I have no serious intend to actually do anything.

The initial version of this PR already led to some discussion, but it seemed to me that on 19 september we reached a version that everybody was happy with, which was indeed approved on 7 October 2019. To me this is a very clear code improvement, which can save people a lot of trouble, and is quite unlikely to break anything. However, somehow you decided not te merge it and let it sit there for half a year, so that it conflicts, and then suddenly you want me to fix that?

Unfortunately this is not a unique situation; the list of open PRs is very long, and some are open for years already. The fact that you open sourced this software is great, but I believe accepting community contributions is essential in open source projects. The way you are managing this (or maybe the lack thereof) made me lose all interest in this project, and therefore I will not even attempt to contribute any further.

**Comment by RCheesley** [comment]
@alanhartless @heathdutton in light of the response above from @jbransen and the earlier discussions, would you suggest that we consider creating a new PR for Mautic 3.x based on this one and address the conflicts, or close it down?

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Given the inactivity on this PR and the conflicts yet to be resolved, plus the dialogue in the PR, I am going to close this down. If anybody would like to take it up again in the future please create a new PR against the appropriate branch for the current version of Mautic and mention this PR to link up the reference.

**Pull request closed without merging**
