### PR TITLE
Added support for -1/unlimited upload size

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**
See #871.  This fixes the upload issue when limits are all set to unlimited (-1).  It also cleans up the code a bit for checking filesize, etc.

**Testing**
Change post_max_size and upload_max_filesize to 0 and memory_limit in php.ini to -1 and attempt to upload an asset which should fail.  After the PR, uploads should work.

### CODE REVIEW

**Comment by escopecz** [comment]
This PR fixed the upload issue, but when I hit Save button to save the asset, I got
```
500 Internal Server Error - Warning: strtoupper() expects parameter 1 to be string, array given 

vendor/joomla/filter/src/InputFilter.php (line #170):
at Symfony\Component\Debug\ErrorHandler -> handleError ( '2', 'strtoupper() expects parameter 1 to be string, array given', 'vendor/joomla/filter/src/InputFilter.php', '170', array('source' => null, 'type' => array('description' => 'html')) )
vendor/joomla/filter/src/InputFilter.php (line #170): at strtoupper ( array('description' => 'html') )
app/bundles/CoreBundle/Helper/InputHelper.php (line #114): at Joomla\Filter\InputFilter -> clean ( null, array('description' => 'html') )
app/bundles/CoreBundle/Form/EventListener/CleanFormSubscriber.php (line #58): at Mautic\CoreBundle\Helper\InputHelper :: _ ( null, array('description' => 'html') )
at Mautic\CoreBundle\Form\EventListener\CleanFormSubscriber -> preSubmitData ( object(FormEvent), 'form.pre_bind', object(EventDispatcher) )
app/cache/dev/classes.php (line #2171): at call_user_func ( array(object(CleanFormSubscriber), 'preSubmitData'), object(FormEvent), 'form.pre_bind', object(EventDispatcher) )
app/cache/dev/classes.php (line #2104): at Symfony\Component\EventDispatcher\EventDispatcher -> doDispatch ( array(array(object(BindRequestListener), 'preBind'), array(object(TrimListener), 'preSubmit'), array(object(CleanFormSubscriber), 'preSubmitData')), 'form.pre_bind', object(FormEvent) )
vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/ImmutableEventDispatcher.php (line #43): at Symfony\Component\EventDispatcher\EventDispatcher -> dispatch ( 'form.pre_bind', object(FormEvent) )
vendor/symfony/form/Symfony/Component/Form/Form.php (line #551): at Symfony\Component\EventDispatcher\ImmutableEventDispatcher -> dispatch ( 'form.pre_bind', object(FormEvent) )
vendor/symfony/form/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php (line #81): at Symfony\Component\Form\Form -> submit ( null, false )
vendor/symfony/form/Symfony/Component/Form/Form.php (line #498): at Symfony\Component\Form\Extension\HttpFoundation\HttpFoundationRequestHandler -> handleRequest ( object(Form), object(Request) )
app/bundles/CoreBundle/Controller/FormController.php (line #67): at Symfony\Component\Form\Form -> handleRequest ( object(Request) )
app/bundles/AssetBundle/Controller/AssetController.php (line #301): at Mautic\CoreBundle\Controller\FormController -> isFormValid ( object(Form) )
app/bundles/CoreBundle/Controller/CommonController.php (line #308): at Mautic\AssetBundle\Controller\AssetController -> newAction ( '0', '' )
at Mautic\CoreBundle\Controller\CommonController -> executeAction ( 'new', '0', '0', '' )
app/bootstrap.php.cache (line #3051): at call_user_func_array ( array(object(AssetController), 'executeAction'), array('new', '0', '0', '') )
app/bootstrap.php.cache (line #3013): at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '1' )
app/bootstrap.php.cache (line #3162): at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '1', true )
app/bootstrap.php.cache (line #2403): at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel -> handle ( object(Request), '1', true )
app/AppKernel.php (line #110): at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), '1', true )
index_dev.php (line #61): at AppKernel -> handle ( object(Request) )
```

**Comment by escopecz** [comment]
Update: That is not probably an issue of this PR. I get this error saving email on staging branch.

**Comment by escopecz** [comment]
Update of update: It was cause by bad values in php.ini so not related to this PR.

**Comment by dbhurley** [comment]
+1

**Pull request merged**
