### PR TITLE
Focus support for multi page form

### LINKED ISSUE #2992: Focus items do not seem to support multi-page forms [$50]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | x
| Enhancement? | 

## Description:
I created a multipage form which I wanted to emulate the behaviour of a Hotjar poll - asking for quick feedback and an option to give contact details on second form.

When creating the form, it works fine in preview with two pages.  When used as a data capture form in the context of a focus, however, it does not - the contact details are rendered all in one display and not as a multi-page form.

multi-page-form-mautic

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 5.6.28

### Steps to reproduce:
1. Create multi-page form
2. Create focus item for data capture, assign form
3. Form is displayed in one screen, rather than multiple pages

<bountysource-plugin>

---
There is a **[$50 open bounty](https://www.bountysource.com/issues/39478352-focus-items-do-not-seem-to-support-multi-page-forms?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for 4.0
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | Fixes: https://github.com/mautic/mautic/issues/2992

#### Description:
This PR fixed Focus items do not seem to support multi-page forms reported https://github.com/mautic/mautic/issues/2992

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create from with multi page form
3. Create focus modal with multi page form
4. Test if multi page form works properly

### CODE REVIEW

**Comment by escopecz** [comment]
@kuzmany there are many conflicts to resolve. I'll change the milestone to M4 as it's based on the features branch with some M4 changes in it.

**Comment by LeonOltmanns** [comment]
Tried to test this PR, but couldnt load it properly.

Tried to open using Chrome. Safari and Firefox.

image

**Comment by RCheesley** [comment]
@oltmanns-leuchtfeuer it seems that there are a bunch of conflicting files that need to be resolved before we can test this - @kuzmany can you take a look please?

**Comment by kuzmany** [comment]
@RCheesley I've merged with last features. Does Mautibox work for M4?

**Comment by RCheesley** [comment]
@kuzmany I am not seeing any changes when this PR is applied - video here: https://youtu.be/S6_g5VOpc4M

Form still all on one page and there is no page break happening. PR is definitely applied, and cache is cleared (GrapesJS is disabled).

**Comment by kuzmany** [comment]
@RCheesley As I check pagination in form does not work in standard font in M4

I see issue 

image

I've already reported it https://github.com/mautic/mautic/issues/9951

**Comment by kuzmany** [comment]
Should works with this fix https://github.com/mautic/mautic/pull/9972

**Review by npracht — APPROVED** [review]
Well done ! This works well :) 👍🏽

**Comment by RCheesley** [comment]
@kuzmany after checking out the PR I am still getting the same issue in both notification and modal:

screenshot-mautic4 ddev site-2021 06 02-09_26_15
screenshot-mautic4 ddev site-2021 06 02-09_25_13

Errors in console:

```
VM3258:1 Uncaught SyntaxError: Unexpected token } in JSON at position 12
    at JSON.parse (<anonymous>)
    at Object.Core.parseToObject (mautic-form.js?v0bbec77b:47)
    at mautic-form.js?v0bbec77b:48
    at mautic-form.js?v0bbec77b:49
Core.parseToObject @ mautic-form.js?v0bbec77b:47
(anonymous) @ mautic-form.js?v0bbec77b:48
(anonymous) @ mautic-form.js?v0bbec77b:49
mautic-form.js?v0bbec77b:8 Uncaught TypeError: Cannot read property 'test9737_focus' of undefined
    at Object.Form.prepareValidation (mautic-form.js?v0bbec77b:8)
    at Object.Form.prepareForms (mautic-form.js?v0bbec77b:6)
    at Object.Core.onLoad (mautic-form.js?v0bbec77b:47)
    at HTMLScriptElement.script.onload (<anonymous>:9:23)
Form.prepareValidation @ mautic-form.js?v0bbec77b:8
Form.prepareForms @ mautic-form.js?v0bbec77b:6
Core.onLoad @ mautic-form.js?v0bbec77b:47
script.onload @ VM3255:9
load (async)
(anonymous) @ VM3255:8
engageVisitor @ 1.js:191
registerFocusEvent @ 1.js:91
initialize @ 1.js:12
(anonymous) @ 1.js:371
(anonymous) @ 1.js:372
VM3235:1 GET https://mautic4.ddev.site/index_dev.php/_wdt/3b772b 404
(anonymous) @ VM3235:1
request @ testing-9737:72
load @ testing-9737:72
loadToolbar @ testing-9737:72
(anonymous) @ testing-9737:72
(anonymous) @ testing-9737:72
VM3235:1 GET https://mautic4.ddev.site/index_dev.php/_wdt/3b772b 404
```

**Comment by kuzmany** [comment]
@RCheesley  that error is still related to https://github.com/mautic/mautic/pull/9972
You need fetch actual codebase

image

**Comment by RCheesley** [comment]
Maybe I am missing something - I have Features cloned locally that is up to date with the latest upstream (including that fix) and this PR also has the latest changes from Features merged in. Pulling down this PR should then result in having the latest codebase, and your changes?  I will try again!

**Comment by RCheesley** [comment]
Here are the steps I have taken to test:

1. Clone mautic/mautic features branch
2. Pull down this PR using `gh pr checkout 9737`
2. Install Mautic
3. Create multi page form
4. Create a focus item using that form to capture data in a modal
5. Add that focus item to a Mautic landing page using a code mode block (legacy builder)
6. Focus item is loaded but there is no pagination

@npracht perhaps you could share how you tested this PR as I am unable to get a positive result. I have tried:

- In both dev mode and prod mode
- Deleting my local branch and pulling it again
- Clearing cache (done automatically with PR checkout)

 Still get all fields showing on one page rather than the paginated form.

Standalone form setup:

screenshot-mautic4 ddev site-2021 06 14-10_27_08

Output:

screenshot-mautic4 ddev site-2021 06 14-10_27_21

**Review by RCheesley — APPROVED** [review]
Yasss, finally got it to work!

Turned out that I needed to use the --force flag to pull down your updated branch as it was not getting some of the changes:

`gh pr checkout 9737 --force`

Confirmed working as expected with a two page form in the focus item - let's get that super old bug squashed!

**Pull request merged**
