### PR TITLE
Form validation improvements

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**
Well this was supposed to have made it into 1.2.0 but guess I neglected to push the local branch then deleted it while cleaning up. Yay for Git and the ability to rescue commits from deleted branches!

Anywhoo...

This PR removes the need to copy JS per form into the page.  Rather it uses data attributes to define validation requirements and so only the main JS block is required on each page.  It separates the main JS block from the form content when using the manual copy option.  This should allow more compatibility for 3rd party site editors that strip out JS.

It also fixes a bug where multiple selects failed to validate and caused a JS error that prevented the form from submitting.

**Testing**
After the patch has been applied and Symfony's cache cleared, edit a form and add some required fields with validation messages (use at least one multiple select, one text box, one checkbox group, and one radio group to ensure all work ok).  

Save and preview the form then try to submit.  The validations should work.

Now embed the automatic JS into a 3rd party script and validate that the form submits as intended and then also embed the manual copy and do the same.

### CODE REVIEW

**Comment by escopecz** [comment]
I tested BC with my old form with checkboxes. The form didn't save with empty checkboxes but also it didn't highlight the field like a text field for example so user wouldn't know what's the problem.

When I wanted to create a form with all the fields described in the description, I created them successfully, but I forgot to mark them as required. When I wanted to edit a created field, it redirected me to 
```
.../s/forms/field/edit/new4a8cef11cd5cdd9eae27b6a1f2a4096f089c981e?formId=b821865b63e9c9fad72153d5303010eca7ce05c7
```
with this error message:
```
{"error":"You do not have access to the requested area\/action."}
```
and when I went back, all my fields were gone. I have administrator permissions.

**Comment by alanhartless** [comment]
@escopecz Is this still the case? Do you have the old form HTML handy that I can test against?

**Comment by escopecz** [comment]
Yep, still the issue. Form HTML:
```
<div id="mauticform_wrapper_checkboxform" class="mauticform_wrapper">
    <form autocomplete="false" role="form" method="post" action="http://localhost/mautic-github/index_dev.php/form/submit?formId=8" id="mauticform_checkboxform" data-mautic-form="checkboxform">
        <div class="mauticform-error" id="mauticform_checkboxform_error"></div>
        <div class="mauticform-message" id="mauticform_checkboxform_message"></div>
        <div class="mauticform-innerform">

            <div id="mauticform_checkboxform_my_numbers"  class="mauticform-row mauticform-checkboxgrp mauticform-required">
                <label  class="mauticform-label" for="mauticform_checkboxgrp_checkbox_my_numbers_One">My numbers</label>
                <div class="mauticform-checkboxgrp-row">
                    <label id="mauticform_checkboxgrp_label_my_numbers_One" for="mauticform_checkboxgrp_checkbox_my_numbers_One"  class="mauticform-checkboxgrp-label">
                        <input  value="" class="mauticform-checkboxgrp-checkbox" name="mauticform[my_numbers][]" id="mauticform_checkboxgrp_checkbox_my_numbers_One" type="checkbox" value="One" />
                        One
                    </label>
                </div>
                <div class="mauticform-checkboxgrp-row">
                    <label id="mauticform_checkboxgrp_label_my_numbers_Two" for="mauticform_checkboxgrp_checkbox_my_numbers_Two"  class="mauticform-checkboxgrp-label">
                        <input  value="" class="mauticform-checkboxgrp-checkbox" name="mauticform[my_numbers][]" id="mauticform_checkboxgrp_checkbox_my_numbers_Two" type="checkbox" value="Two" />
                        Two
                    </label>
                </div>
                <div class="mauticform-checkboxgrp-row">
                    <label id="mauticform_checkboxgrp_label_my_numbers_Three" for="mauticform_checkboxgrp_checkbox_my_numbers_Three"  class="mauticform-checkboxgrp-label">
                        <input  value="" class="mauticform-checkboxgrp-checkbox" name="mauticform[my_numbers][]" id="mauticform_checkboxgrp_checkbox_my_numbers_Three" type="checkbox" value="Three" />
                        Three
                    </label>
                </div>
                <span class="mauticform-errormsg" style="display: none;">This is required.</span>
            </div>

            <div id="mauticform_checkboxform_message"  class="mauticform-row mauticform-text">
                <label id="mauticform_label_checkboxform_message" for="mauticform_input_checkboxform_message" class="mauticform-label">message</label>
                <textarea id="mauticform_input_checkboxform_message" name="mauticform[message]" value="" placeholder="Dear Lenka," class="mauticform-textarea"></textarea>
                <span class="mauticform-errormsg" style="display: none;"></span>
            </div>

            <div id="mauticform_checkboxform_radio"  class="mauticform-row mauticform-radiogrp mauticform-required">
                <label  class="mauticform-label" for="mauticform_radiogrp_radio_radio_Radio">Radio</label>
                <div class="mauticform-radiogrp-row">
                    <label id="mauticform_radiogrp_label_radio_Radio" for="mauticform_radiogrp_radio_radio_Radio"  class="mauticform-radiogrp-label">
                        <input  name="mauticform[radio]" value="" class="mauticform-radiogrp-radio" name="mauticform[radio]" id="mauticform_radiogrp_radio_radio_Radio" type="radio" value="Radio" />
                        Radio
                    </label>
                </div>
                <div class="mauticform-radiogrp-row">
                    <label id="mauticform_radiogrp_label_radio_Evropa2" for="mauticform_radiogrp_radio_radio_Evropa2"  class="mauticform-radiogrp-label">
                        <input  name="mauticform[radio]" value="" class="mauticform-radiogrp-radio" name="mauticform[radio]" id="mauticform_radiogrp_radio_radio_Evropa2" type="radio" value="Evropa2" />
                        Evropa2
                    </label>
                </div>
                <span class="mauticform-errormsg" style="display: none;">This is required.</span>
            </div>

            <div id="mauticform_checkboxform_submit"  class="mauticform-row mauticform-button-wrapper">
                <button type="submit" name="mauticform[submit]" id="mauticform_input_checkboxform_submit" name="mauticform[submit]" value="" class="mauticform-button" value="1">Submit</button>
            </div>

            <input type="hidden" name="mauticform[formId]" id="mauticform_checkboxform_id" value="8" />
            <input type="hidden" name="mauticform[return]" id="mauticform_checkboxform_return" value="" />
            <input type="hidden" name="mauticform[formName]" id="mauticform_checkboxform_name" value="checkboxform" />

        </div>
    </form>
</div>
```

**Comment by alanhartless** [comment]
@escopecz If this is a BC form, do you still have the original validation JS as well?

**Comment by escopecz** [comment]
Here is the full "Manual Copy"
[BC_form.txt](https://github.com/mautic/mautic/files/18664/BC_form.txt)

**Comment by alanhartless** [comment]
@escopecz Ok, found an issue with checkbox validations and BC. See last commit.

**Comment by escopecz** [comment]
Works OK now. Only flaw I could find is that older embedded form via automatic method is creating this JS error:

`Uncaught TypeError: Cannot set property 'emailcampaignform' of undefined`

I vote up :+1:

**Comment by alanhartless** [comment]
@escopecz Does the browser console give a trace on that?

**Comment by escopecz** [comment]
The JS console shows the link and it opens this script:
```
    /** This section is only needed once per page if manually copying **/
    if (typeof MauticSDKLoaded == 'undefined') {
        var MauticSDKLoaded = true;
        var head            = document.getElementsByTagName('head')[0];
        var script          = document.createElement('script');
        script.type         = 'text/javascript';
        script.src          = 'http://localhost/mautic-github/media/js/mautic-form-src.js';
        script.onload       = function() {
            MauticSDK.onLoad();
        };
        head.appendChild(script);
        var MauticDomain = 'http://localhost';
        var MauticLang   = {
            'submittingMessage': "Please wait..."
        }
        var MauticFormValidations  = {};
    }

    /** This is needed for each form **/
    MauticFormValidations['emailcampaignform'] = {
    };
```
The error occures on the last but one line.

**Comment by alanhartless** [comment]
Do you have a newer form loading on the same page or manually copying in ` if (typeof MauticSDKLoaded == 'undefined') {` from a this PR somewhere on the page?  Wondering if `var MauticFormValidations  = {};` is not getting loaded because `MauticSDKLoaded` is already defined.

**Comment by escopecz** [comment]
It happens if the old for is in the page alone as well as with a new form. But it doesn't seem to cause any functional trouble.

**Comment by dbhurley** [comment]
+1 sounds good!

**Comment by alanhartless** [comment]
:-) Is `MauticFormValidations['emailcampaignform'] = {};` still getting generated in the source for the new form? If so, that's a bug and a JS error could trickle into affecting other JS code on the page so we need to resolve it.  I'll see if I can replicate here in a moment.

**Comment by escopecz** [comment]
No, it's not being generated in the new form. It is part of the old form JS.

**Pull request merged**
