### PR TITLE
Migration may run in wrong order

### PR DESCRIPTION
**Pull request by escopecz**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | N
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | /
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

It happened to us that one migration that is adding new rows to the lead_field table (20180702145735) is run after a migration that is adding 2 new columns with no default value (20180921144421) and so the query breaks as MySql doesn't know what value to put there for the new row. This PR adds new migration before the problematic migration and adds default values for those fields. Another failing migration did not have permission classes generated before it was used. That another issue with 2 PR merged that did not know about each other changes.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Run `app/console doctrine:migrations:migrate`. You may see this error:
```
Migration 20180702145735 failed during Execution. Error An exception occurred while executing 'INSERT INTO `mautic_lead_fields` (`is_published`, `label`, `alias`, `type`, `field_group`, `default_value`, `is_required`, `is_fixed`, `is_visible`, `is_short_visible`, `is_listable`, `is_publicly_updatable`, `is_unique_identifer`, `field_order`, `properties`, `object`) 
VALUES 
    (1, 'Date Last Active', 'last_active', 'datetime', 'core', NULL , 0, 1, 1, 0, 1, 0, 0, 24, 'a:0:{}', 'lead')':
SQLSTATE[HY000]: General error: 1364 Field 'column_is_not_created' doesn't have a default value
```

If it's not reproducible then just test the migrations. It will not harm to have them in.

#### Steps to test this PR:
1. Run the migration command again. It should execute all SQL queries smoothly

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10213"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
I don't think the CodeCov check reports correct results. I merged 4.0 to this PR and no reported classes are present in this PR.

**Review by volha-pivavarchyk — DISMISSED** [review]
I cannot reproduce this error. I got only a warning message.

All SQL queries are executed smoothly. Works as expected.

**Comment by kuzmany** [comment]
Need rebase

**Comment by escopecz** [comment]
@kuzmany rebased

**Review by kuzmany — APPROVED** [review]

**Pull request merged**
