### PR TITLE
Fix report points change log graphs

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/6476
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Points log report work with graphs with sum in mysql select. If you 're using data table with graphs, and contact has more companies, then to SQL query are joined two categories tables.  Then points sum  number are not correct. This PR removes categories tables from graphs queries.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1.  Create contact and assign 3 companies to this contact
2. Create form with action with add points. Send two times these form for same contact. Then setup contact point log report
3. Setup data table with email and company name
image
4. Setup graphs table: Contacts with most points
image
5. See graphs table display more points like  your contact submitted via form

#### Steps to test this PR:
1.  Apply PR 
2. See correct points on graphs table

image

### CODE REVIEW

**Comment by johbuch** [comment]
works for me now. Thanks

**Comment by mleffler** [comment]
We think this code is not working properly, and seems to cause the table aliased lp to be included each time without being sure that the table has been joined, creating the exception below:  '''

```
Uncaught PHP Exception Doctrine\DBAL\Query\QueryException: "The given alias 'lp' is not part of any FROM or JOIN clause table. The currently registered aliases are: l." at /usr/local/share/mautic/preproduction/releases/2018.12.01CR/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryException.php line 37
```


@galvani will post a fix for community, and it should probably be in 2.15  @Woeler, your call.

cc: @npracht

**Comment by Woeler** [comment]
Tag me when its there, preferably today.

**Comment by npracht** [comment]
I'll take time for a test as soon as PRed !

**Pull request merged**
