### PR TITLE
Prevent SQL error when processing bad email address

### PR DESCRIPTION
**Pull request by alanhartless**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

Sending a segment email with a bad email address will fail with a SQL error due to the integer reason and comments arguments being switched. 

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Hack the database with a bad email address and add the contact to a segment
2. Create a segment email and send it
3. Not the SQL error

#### Steps to test this PR:
1. Repeat and there should be no error and the contact marked as DNC

### CODE REVIEW

**Comment by javjim-mautic** [comment]
Was able to reproduce bug but fix didn't work for me. it stays trying to send but never sends the email.

**Comment by alanhartless** [comment]
@javjim-mautic is there anything in your logs? Are you saying that the send progress bar gets stuck?

**Comment by javjim-mautic** [comment]
Yes, it doesnt do anything, the progress bar just stays there and nothing happens @alanhartless

**Comment by alanhartless** [comment]
@javjim-mautic anything in your logs?

**Comment by escopecz** [comment]
This is the error I get on staging:
```
500 Internal Server Error - An exception occurred while executing 'INSERT INTO lead_donotcontact (date_added, reason, channel, channel_id, comments, lead_id) VALUES (?, ?, ?, ?, ?, ?)' with params ["2018-01-23 15:46:41", "Incorrectly formatted email address", "email", 297, 2, 17155]: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'Incorrectly formatted email address' for column 'reason' at row 1
```
And it works correctly with this PR. The contact with bad email address is marked as bounced.

**Pull request merged**
