### PR TITLE
Fix email translations lost and overwritten by parent

### LINKED ISSUE #10618: email translations lost and overwritten by parent
### Mautic Version

4.0.0

### PHP version

PHP 7.4.23

### What browsers are you seeing the problem on?

Not relevant

### What happened?

the issue rperoted here https://github.com/mautic/mautic/pull/10525 it is still not resolved in 4.02 version

### How can we reproduce this issue?

See https://github.com/mautic/mautic/issues/10562 to steps to repeat the problem. There is a video too.

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR is follow up to https://github.com/mautic/mautic/pull/10525  and fix https://github.com/mautic/mautic/issues/10618
It's fix email translations lost and overwritten by parent 
Require https://github.com/mautic/mautic/pull/10619 

#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2. Create  segment email  with French language (`Subject FR + content Test FR`)
3. Clone it and set as translation of email `Subject FR` with language EN (`Subject EN + content Test FR`)
4.  Save and  go to email `Subject FR` and re-save.
5. This should overwrite content of email `Subject EN`. Your content of EN email should be Test FR
6. After PR should be OK

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10620"></a>

### CODE REVIEW

**Comment by garzettone** [comment]
I have applied this fix but it doesn't resolve the issue

**Comment by garzettone** [comment]
Yes. This fix the isssue

**Comment by kuzmany** [comment]
@garzettone can you go to PR and approve it . Later I will check unit tests and phpstan reports

image

**Comment by adiux** [comment]
@kuzmany how should we test this? You say you are using this in production. Do we need to test it?

**Comment by kuzmany** [comment]
@adiux check now please

**Comment by kuzmany** [comment]
@adiux I was able to reproduce now

**Review by volha-pivavarchyk — DISMISSED** [review]
It works well

**Review by volha-pivavarchyk — DISMISSED** [review]
The unit test has been added. Works as expected.

**Pull request merged**
