### PR TITLE
Initial batch of Codeception acceptance tests for Contacts

### PR DESCRIPTION
**Pull request by RCheesley**
| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | x
| Automated tests included? | x
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Required: )
#### Description:
We have almost no Codeception acceptance tests that could be run against new releases of Mautic. I've started writing some which we can hopefully use to improve our UAT process.

This PR covers what I believe to be the basic set of tests for Contacts. It can probably be improved, optimised and more tests added to make sure we have full coverage of all the possible actions that can be taken against both individual and multiple contacts, but it's a starting point!

I plan to chip away at creating a basic set of tests for each bundle, and then we can expand on them going forward to add more complexity, refine, and optimise/test cross browser/platform etc with Browserstack. If anyone would like to help with this please ping me on Slack.

A couple of points to add if testing these:

* I had to force Codeception to use max resolution using the following in my acceptance.suite.yml on all environments:
```
actor: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: http://local.mauticautomatedtests
            browser: chrome
            window_size: 1920x1080
        - \Helper\Acceptance
```
* On my Mac I had to set an argument of w2c: false per [this StackOverflow post](https://stackoverflow.com/questions/56556709/codeception-undefined-index-element-error/59875669#59875669).

* Depending on the speed of your environment, you may need to tinker with the wait periods. I tried to keep them as low as possible so as not to delay the tests overly, but if you have a slower machine you might find that errors are thrown. If you are seeing errors relating to fields not being visible or editable, throw in an `$I->makeScreenshot('file-name');` directly before the offending line and check the output to see if the field is in the process of being rendered.

* We are using a super outdated version of Codeception so some newer actions (e.g. clearField) are not available. This meant some slightly longer winded tests having to manually clear fields.

I wrote up the steps I followed to [get set up for testing and writing tests with Codeception](https://www.ruthcheesley.co.uk/blog/development/learning-to-write-acceptance-tests-with-codeception) in case it is helpful for anyone who would like to contribute to this going forward.

#### Steps to test this PR:
No testing required on the PR itself, but it would be helpful if some folk could test the acceptance tests and make sure they are correct/working as expected.

### CODE REVIEW

**Comment by escopecz** [comment]
This is amazing, Ruth! Definitely bump the codeception version. Run `composer require --dev codeception/codeception`. It should update the library to the latest we can use.

How long does it take to run these tests? I can help you get them running in Travis CI as a parallel test with other tests.

**Comment by RCheesley** [comment]
Hey @escopecz thanks for the encouragement! It takes approx 2.5-3 minutes on my Linux machine to run the contacts one from memory. @dennisameling had also talked about running them on Travis - I wasn't sure what needs doing to get that happening.

Also worth saying I am completely new to this - so as per my comment on the PR, it might be that there are better/more efficient ways of doing things (as there's quite a bit of repetition) so I might come back to it and refactor as I learn more!

I'll give it a go with updating the codeception version and let you know how it goes, thanks for the tip!

**Comment by dennisameling** [comment]
@RCheesley I'll try and see if I can get Codeception working in the Travis config, have planned to take a first look some time in the coming 2 weeks :) to be continued (or John could do it if he has time before that). We could add the updated Travis config to this PR so that not only the Codeception tests are there, but they will also start running right away in Travis 👍

**Comment by RCheesley** [comment]
OK awesome - I also finished up the essential tests for Companies (#8710) and will keep chipping away at other bundles. If there are any we feel are higher priority (maybe ones that consistently have problems with bugs) I could prioritise them.

**Comment by RCheesley** [comment]
> composer require --dev codeception/codeception

Seems we can't update Codeception:

$ composer require --dev codeception/codeception

Using version ^4.1 for codeception/codeception
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - codeception/stub 3.6.1 requires phpunit/phpunit ^8.4 | ^9.0 -> satisfiable by phpunit/phpunit[8.4.0, 8.4.1, 8.4.2, 8.4.3, 8.5.0, 8.5.1, 8.5.2, 8.5.3, 8.5.x-dev, 9.0.0, 9.0.1, 9.0.2, 9.1.0, 9.1.1, 9.1.2, 9.1.x-dev, 9.2.x-dev] but these conflict with your requirements or minimum-stability.
    - codeception/stub 3.6.0 requires phpunit/phpunit ^8.4 -> satisfiable by phpunit/phpunit[8.4.0, 8.4.1, 8.4.2, 8.4.3, 8.5.0, 8.5.1, 8.5.2, 8.5.3, 8.5.x-dev] but these conflict with your requirements or minimum-stability.
    - codeception/stub 3.5.0 requires phpunit/phpunit ^8.4 -> satisfiable by phpunit/phpunit[8.4.0, 8.4.1, 8.4.2, 8.4.3, 8.5.0, 8.5.1, 8.5.2, 8.5.3, 8.5.x-dev] but these conflict with your requirements or minimum-stability.
    - codeception/stub 3.0.0 requires phpunit/phpunit >=6.5 <9.0 -> satisfiable by phpunit/phpunit[6.5.0, 6.5.1, 6.5.10, 6.5.11, 6.5.12, 6.5.13, 6.5.14, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.6, 6.5.7, 6.5.8, 6.5.9, 7.0.0, 7.0.1, 7.0.2, 7.0.3, 7.1.0, 7.1.1, 7.1.2, 7.1.3, 7.1.4, 7.1.5, 7.2.0, 7.2.1, 7.2.2, 7.2.3, 7.2.4, 7.2.5, 7.2.6, 7.2.7, 7.3.0, 7.3.1, 7.3.2, 7.3.3, 7.3.4, 7.3.5, 7.4.0, 7.4.1, 7.4.2, 7.4.3, 7.4.4, 7.4.5, 7.5.0, 7.5.1, 7.5.10, 7.5.11, 7.5.12, 7.5.13, 7.5.14, 7.5.15, 7.5.16, 7.5.17, 7.5.18, 7.5.19, 7.5.2, 7.5.20, 7.5.3, 7.5.4, 7.5.5, 7.5.6, 7.5.7, 7.5.8, 7.5.9, 8.0.0, 8.0.1, 8.0.2, 8.0.3, 8.0.4, 8.0.5, 8.0.6, 8.1.0, 8.1.1, 8.1.2, 8.1.3, 8.1.4, 8.1.5, 8.1.6, 8.2.0, 8.2.1, 8.2.2, 8.2.3, 8.2.4, 8.2.5, 8.3.0, 8.3.1, 8.3.2, 8.3.3, 8.3.4, 8.3.5, 8.4.0, 8.4.1, 8.4.2, 8.4.3, 8.5.0, 8.5.1, 8.5.2, 8.5.3, 8.5.x-dev] but these conflict with your requirements or minimum-stability.
    - Conclusion: don’t install codeception/codeception 4.1.4
    - Conclusion: don’t install codeception/codeception 4.1.3
    - Conclusion: don’t install codeception/codeception 4.1.2
    - Conclusion: don’t install codeception/codeception 4.1.1
    - Conclusion: remove codeception/stub 1.0.1
    - Installation request for codeception/codeception ^4.1 -> satisfiable by codeception/codeception[4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4].
    - Conclusion: don’t install codeception/stub 1.0.1
    - codeception/codeception 4.1.0 requires codeception/stub ^2.0 | ^3.0 -> satisfiable by codeception/stub[2.0.0, 2.0.1, 2.0.4, 2.1.0, 3.0.0, 3.5.0, 3.6.0, 3.6.1].
    - Can only install one of: codeception/stub[2.0.0, 1.0.1].
    - Can only install one of: codeception/stub[2.0.1, 1.0.1].
    - Can only install one of: codeception/stub[2.0.4, 1.0.1].
    - Can only install one of: codeception/stub[2.1.0, 1.0.1].
    - Installation request for codeception/stub (locked at 1.0.1) -> satisfiable by codeception/stub[1.0.1].
Installation failed, reverting ./composer.json to its original content.

**Comment by escopecz** [comment]
@RCheesley I was able to reproduce. Then I thought of the IT Crowd show and tried this:
1. `composer remove --dev codeception/codeception`
2. `composer require --dev codeception/codeception`

And it installed version 4.1. However, playing with Composer I noticed I got a lot of packages downgraded with it when running it on your branch. I can see this is PRed against the `3.x` branch but probably based on a M2 branch. Is it? Do you intent these test for M2 or M3 or both? I would suggest to build it on M3 as it would make things simpler.

Then I searched how to deal with the ajax requests. Counting on the wait(X seconds) method is not reliable and can be waste of time. Some StackOverflow discussion suggested [SmartWait](https://codeception.com/docs/03-AcceptanceTests#smartwait). We should give it a try.

I followed your tutorial you mentioned in the PR description as I'm also new to this. It's very detailed and it helped a lot! Thank you for that. I got a bit stuck on the step where I should install the sample data. It's not something I'd want to do before running the tests every time.

We have functional tests in Mautic that can test database manipulations. Quite similar to what Codeception tests do. We configure separate database for those tests here:
https://github.com/mautic/mautic/blob/staging/.env.dist
And then we can run the tests and continue with manual tests at the same time. We should use another database for the Codeception tests so we could run functional tests in parallel. Then to install some sample data we use so called fixtures. Here is an example:

https://github.com/mautic/mautic/blob/3.x/app/bundles/LeadBundle/Tests/Controller/AjaxControllerFunctionalTest.php#L45

The workflow of running each test look like this (afaik):
1. If there are any tables in the test database, drop them.
2. Create fresh schema.
3. Install fixtures
4. Run the test

Point 1 and 2 are time consuming so what I'd propose is this instead:
1. Check if schema exists and create it if not.
2. Install fixtures
3. Run the test
4. Truncate the tables that were touched by the test.

It's a bit more work but it will run faster.

All that being said, configuring all this is quite a bit of work, so let's join forces on this. It will make writing and running the tests much easier.

Let me know what you thing. We can rebase this on the 3.x branch and continue.

**Comment by RCheesley** [comment]
@escopecz sounds great - I was looking at better ways to do the wait period as it was somewhat unreliable so I'll see how setting it in the webdriver config impacts the tests.

About the sample data - I've been assuming that the tests in each bundle are being run sequentially - I've been testing them individually and also when running through all the functions in the file. I haven't tested running e.g. contacts then companies on the same sample dataset, but I think it should be OK. We might need to think through what order we run the bundles in though.

I'll also look at rebasing (guess I should read my own documentation on that eh :stuck_out_tongue_winking_eye:) - I realised part way through doing these that I was branching from staging :woman_facepalming:

**Comment by RCheesley** [comment]
@escopecz  I made a mistake and nuked my fork without thinking about these PR's, so suggest we continue on the rebased PRs #8754 and #8756 - will port over suggestions as todos.

**Pull request closed without merging**
