### PR TITLE
Updated supported versions and their dates in SECURITY.md

### PR DESCRIPTION
**Pull request by BramDriesen**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          |  N/A
| New feature/enhancement? (use the a.x branch)      | 5.x
| Deprecations?                          | N/A
| BC breaks? (use the c.x branch)        | N/A
| Automated tests included?              | N/A
| Related user documentation PR URL      | mautic/mautic/blob/5.x/SECURITY.md
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | N/A

#### Description:

I was looking at the SECURITY.md and noticed that some of the dates were not matching the tagged versions in GitHub. Also some of the newer releases were completely missing so I added those as well.

Dates of beta and initial releases come from the tags here on GitHub.
Dates of security support come from the [release schedule](https://www.mautic.org/mautic-releases) where security support is listed.

I left out 5.x on purpose since there is currently only a development branch.

#### Steps to test this PR:

N/A

### CODE REVIEW

**Comment by BramDriesen** [comment]
Also signed the CLA 😄

**Comment by RCheesley** [comment]
@cla-bot check

Thanks for making the PR @BramDriesen and welcome to the community! 🙌

**Comment by BramDriesen** [comment]
Thanks @RCheesley ☺️!
Let me know if any of the dates I changed are not correct.

**Review by RCheesley — APPROVED** [review]
Looks good, I would prefer we have a single source of truth for this at some point in the future but for now this will do! 🚀

**Comment by BramDriesen** [comment]
@RCheesley Would you prefer a link to the release schedule page and a removal of the table? Everything is in the dynamic schedule except Mautic 2 (which you can probably get added. If so I can make another pr for the removal and addition for the link.

**Comment by RCheesley** [comment]
I'm not actually sure what is the best way to do it - we have it in the readme, security file etc. Ideally we should have this information in one place and just update that one place, otherwise we get out of date and have discrepancies all over the place!

All the information is at https://www.mautic.org/mautic-releases and I try to keep the chart at the bottom updated if we shift the timelines for releases etc (need to update it for the delay to 5.0 😱 ).

**Comment by BramDriesen** [comment]
I personally like the release page with the interactive diagram. Tells you a lot more in the same timespan of looking at a table. +1 for keeping things in a central place. It's probably is also written somewhere in the documentation pages as well.

**Pull request merged**
