### PR TITLE
Enable sendToContact Email API to define additional cc and bcc recipients

### PR DESCRIPTION
**Pull request by PurHur**
| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Y
| Automated tests included? | N
| Related user documentation PR URL | 
| Related developer documentation PR URL | https://github.com/mautic/developer-documentation/pull/141
| Issues addressed (#s or URLs) | 
| BC breaks? | N
| Deprecations? | N

#### Description:
This PR adds the parameters `ccRecipients` and `bccRecipients` to the sendToContact Email API.
I followed the implementation of `assetAttachments`.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Call the new API parameters like this:
  ```
$params = [
     'tokens' => $tokens,
     'assetAttachments' => $assetAttachments,
     'ccRecipients' => $ccRecipients, // [[address => name]]
     'bccRecipients' => $bccRecipients, // [[address => name]]
 ];
$response = $emailApi->sendToContact($mailId, $contactId, $params);
```

### CODE REVIEW

**Comment by RCheesley** [comment]
@PurHur could you take a look at the conflicts? Would be great to get this into 3.1 if it is still relevant!

**Comment by RCheesley** [comment]
Bumping to 3.2 due to unresolved conflicts on the PR.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by npracht** [comment]
This is too old. i'll close it and if someone want to carry it again, then we'll re-open it with huge pleasure.

**Pull request closed without merging**
