### PR TITLE
Add language support on form creation

### LINKED ISSUE #4658: Translate Please wait … message when submitting a form
| Feature request? | 

## Description:
When submitting a Mautic form, the text in the buttons says ´Please wait …´. We use Mautic for our Dutch clients and would like to see that the text in the button is translated is the language the Mautic instance is set up. So a Dutch message in Dutch language, a German in German language and so on...

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/48229346-translate-please-wait-message-when-submitting-a-form?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by enguerr**
Closes #4658
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | No
| New feature? | Yes
| Automated tests included? | No
| Related user documentation PR URL | https://github.com/enguerr/PRDOC/blob/master/PR4658.md
| Related developer documentation PR URL | https://github.com/enguerr/PRDOC/blob/master/PR4658.md
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description: Add Language support for form creation
To enable this path, please update the db schema. I've added some columns like title, noindex and lang on the form table. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create a form
3. Select the desired language in the new select at the bottom right
4. All Error message , confirmations and loading message are in the selected language (not the owner user language)

#### List deprecations along with the new alternative:
1. None

#### List backwards compatibility breaks:
1. None

### CODE REVIEW

**Comment by npracht** [comment]
Hello @enguerr ! Thanks a lot for this contribution!
Nevertheless, can you rebase it against 3.x branch ? We won’t merge any new feature in M2.

We could target a merge of your PR for 3.1.0 !

**Comment by kuzmany** [comment]
Require migration file
Check this PR, same discuss and solution here:
https://github.com/mautic/mautic/pull/7596

**Comment by enguerr** [comment]
yes PR migration missing, i will add it as soon as possible.

**Comment by enguerr** [comment]
Do you know why i cant rebase my fork to 3.x branche ?
Do i need to remove my commit in staging ? or re-create the branches manually ?
image

**Review by enguerr — COMMENTED** [review]
Remove the createfield no_index

**Review by enguerr — COMMENTED** [review]
Some corrections to pass the travsi build

**Review by enguerr — COMMENTED** [review]
Do not understand why it fail

**Review by enguerr — COMMENTED** [review]
reorder dependencies

**Review by enguerr — COMMENTED** [review]
Fu\#[@^ space char

**Review by enguerr — COMMENTED** [review]
reordered agin

**Comment by enguerr** [comment]
@npracht I've rebased it ... is it ok now ?
@kuzmany I've added the migration file

**Review by enguerr — COMMENTED** [review]
migration content

**Pull request closed without merging**
