### PR TITLE
WIP: Add Symfony Mailer (Rebase)

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Original PR: https://github.com/mautic/mautic/pull/11613

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by mabumusa1** [comment]
@fedys this is a new PR instead of the old one that is based on the latest `5.x` branch, the failing test is not related to the PR I think, and the failing `phpstan` test is a function that is used by future plugins.  Whenever you are done reviewing, let me know we can have a call to discuss the details of the changes.

Of course the changes here are not tested on the new changes yet, so we will find things that are broken

**Comment by fedys** [comment]
I started testing the basic functionality in my local environment. So far I found out the following issues:

1. After saving the email configuration page, the filled in email values are gone.
2. After pressing "Send test email" button on the email configuration page, I get http 500 with ""Service "mautic.email.mailer.email_sender" not found: even though it exists in the app's container, the container inside "Mautic\EmailBundle\Controller\AjaxController" is a smaller service locator that only knows about..."
3. Segment emails are not sent. After clicking the "Send" button on "/s/emails/send/1" page, the progress bar gets stuck at the very beginning.

@mabumusa1 do you have any bandwidth to look at the above issues now? I can take a look at it if you are busy?

**Comment by mabumusa1** [comment]
> I started testing the basic functionality in my local environment. So far I found out the following issues:
> 
> 1. After saving the email configuration page, the filled in email values are gone.
> 2. After pressing "Send test email" button on the email configuration page, I get http 500 with ""Service "mautic.email.mailer.email_sender" not found: even though it exists in the app's container, the container inside "Mautic\EmailBundle\Controller\AjaxController" is a smaller service locator that only knows about..."
> 3. Segment emails are not sent. After clicking the "Send" button on "/s/emails/send/1" page, the progress bar gets stuck at the very beginning.
> 
> @mabumusa1 do you have any bandwidth to look at the above issues now? I can take a look at it if you are busy?

@fedys those issues started to show after the upgrade to Symfony5, I will take care of them. in order to save sometime, please look into writing functional tests to increase the coverage

**Comment by mabumusa1** [comment]
@fedys All the issues are solved 

- [X] Saving Config in commit a132ba893c78331d2ccba2e6a9b32dcc77645d60
- [X] Inject Missing Service d8039e7e66dc60581c4cf23aea5f88c0965e773f
- [X] Batch Emails 764ad12cb968dc897b7295a8793ada1fee6d492d

**Comment by fedys** [comment]
@mabumusa1 please can you close this PR and move this branch to https://github.com/mautic/mautic/pull/11613, so we can continue with the previous convos. It is now confusing with the two PRs.

**Comment by fedys** [comment]
@mabumusa1 please prefer DI to using the container. See https://github.com/mautic/mautic/pull/12423/commits/816bd9e6f8c082775ff43745c7ed93dcac694aac

**Comment by mabumusa1** [comment]
Closing in favor of #11613

**Pull request closed without merging**
