### PR TITLE
Fix limit/batch for broadcast email command

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | [mautic/mautic-documentation#... ](https://github.com/mautic/mautic-documentation/pull/313)
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:
Broadcast command for emails process incorrect limit/batch parameters during the sending. This PR fixed it and make same way of processing these parameters like SMS channel.

For example

`mautic:broadcast:send --channel=email --limit=10 --batch=2`  - before process all emails in batch 10. We expect process 10 emails with command in batch 2

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create segments email and try many combinations

`mautic:broadcast:send --channel=email --limit=10 --batch=2` - should process 10emails in batch 2 (**before process all emails in batch 10**)
`mautic:broadcast:send --channel=email --batch=2` - should process all emails in batch 2
`mautic:broadcast:send --channel=email --limit=10` - should process 10 emails per  command without batch processing
`mautic:broadcast:send --channel=email` - should process all email without batch processing

# Backwards compatibility breaks
If you use limit and batch parameters for `mautic:broadcast:send`, you should  re-arrange it. Mention it in UPGRADE-5.0.md
 https://github.com/mautic/mautic/pull/11127/files#diff-f125ea0a4ebc7600394bee94245a513bc6d5b2908c5b8fe3644bcef0fe1bf9b3R6

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11127"></a>

### CODE REVIEW

**Comment by kuzmany** [comment]
@mollux can you take look on it? This is fix what I was talking about it in Ghent on dev sprint.

**Review by mabumusa1 — DISMISSED** [review]
I did a code review, the logic sounds logical

**Comment by mabumusa1** [comment]
@kuzmany please rebase this PR so it fixes github actions issues

**Comment by jos0405** [comment]
Could you plz check if this is correct?

image

This command: processes all emails:
ddev exec bin/console mautic:broadcast:send --channel=email --limit=5 --batch=1

Is that correct?

**Comment by kuzmany** [comment]
@jos0405 last commit should fixed it

**Comment by jos0405** [comment]
@kuzmany, I just tested this, but the output seems weird. It doesn't process as many as I want:
image

**Comment by jos0405** [comment]
@kuzmany could you plz take a look at my screenshot above? I think there is still something fishy.

**Comment by kuzmany** [comment]
@jos0405 can you check with last commit, It should cover all scenarious (without params, with --limit param, with --limit and --batch param, with only --batch param)

**Comment by jos0405** [comment]
If you use limits, then the broadcast is not placed in queue:

image

Without limits and batch it is:
image

**Comment by jos0405** [comment]
Using limits seems to be wroking, but NOT with batch together:

image

**Comment by jos0405** [comment]
Only --batch command will send it out all, but I guess that is expected?
image

**Comment by jos0405** [comment]
@kuzmany , so to sum up:

1. without parameters: working
2. only batch: working
3. only limit: working
4. batch + limit: NOT WORKING

**Comment by volha-pivavarchyk** [comment]
Doesn't work to me. 
image

Maybe I need to run one more command?

**Comment by kuzmany** [comment]
@volha-pivavarchyk you need set publish at date. Just emails with that date are send by command

**Comment by volha-pivavarchyk** [comment]
@kuzmany Thanks a lot!

Works well if the limit is an odd number

image

Doesn't work quite right if the limit is an even number

image

**Comment by RCheesley** [comment]
@kuzmany can you take a look at the feedback on this PR? We have it slated for the 5.0 alpha release so it would be good to get this finalised. Also a small conflict with the MD file to be addressed :) Thanks! 🚀

**Comment by mabumusa1** [comment]
@kuzmany it would be great if we can get this PR merged with M5, do you have time to work on it?

**Comment by kuzmany** [comment]
@volha-pivavarchyk @jos0405 Hope I finally fix issue with limit and batch usage. Can you re-test? 
I am gonna take look on unit tests

**Comment by mabumusa1** [comment]
@volha-pivavarchyk @jos0405 may you please re-test this PR? it has a great enhancement

**Review by volha-pivavarchyk — APPROVED** [review]
Works well.
All options work as before.
The even number works well too.
image

**Review by jos0405 — APPROVED** [review]
Restested. Works perfect, thank you

**Review by jos0405 — APPROVED** [review]
Approved

**Comment by jos0405** [comment]
@mabumusa1 Code review still needed?

**Comment by mabumusa1** [comment]
> @mabumusa1 Code review still needed?

I don't think so, I already did it twice before

**Comment by escopecz** [comment]
@kuzmany can you please resolve the conflicts? Otherwise this seem to be ready to merge.

**Comment by kuzmany** [comment]
@escopecz resolved

**Review by escopecz — APPROVED** [review]

**Pull request merged**
