### PR TITLE
Fix duplicate aliases

### LINKED ISSUE #6678: The given alias 'list' is not unique in FROM
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
I don't know the consecuences but I have found this in the log: 

[2018-10-04 15:22:27] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Query\QueryException: "The given alias 'list' is not unique in FROM and JOIN clause table. The currently registered aliases are: l, u, list_lead, list." at /home/---mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryException.php line 50 {"exception":"[object] (Doctrine\DBAL\Query\QueryException(code: 0): The given alias 'list' is not unique in FROM and JOIN clause table. The currently registered aliases are: l, u, list_lead, list. at /home/---mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryException.php:50)"} []
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.0.32

### Steps to reproduce:
1. No idea
2. 
 
### Log errors: 

[2018-10-04 15:22:27] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Query\QueryException: "The given alias 'list' is not unique in FROM and JOIN clause table. The currently registered aliases are: l, u, list_lead, list." at /home/---mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryException.php line 50 {"exception":"[object] (Doctrine\\DBAL\\Query\\QueryException(code: 0): The given alias 'list' is not unique in FROM and JOIN clause table. The currently registered aliases are: l, u, list_lead, list. at /home/---mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryException.php:50)"} []

### PR DESCRIPTION
**Pull request by galvani**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | N
| Issues addressed (#s or URLs) | fixes https://github.com/mautic/mautic/issues/6678
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
If you specify multiple segments in search box in Contact's section of Mautic, the query built will contain multiple joins to segments table with the same alias.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. put **segment:segment-a segment:segment-b** into the search box in the contact list view and see the error.

#### Steps to test this PR:
1. Apply fix
2. Try again, verify filter works correctly.

### CODE REVIEW

**Comment by TonyBogdanov** [comment]
This seems to fix the issue in Mautic 2.16.0-dev.

**Comment by kuzmany** [comment]
I've tested it on 
I've created contact and added it to segment **sa** and **sb**
Then I've used this filters

- segment:sa - WORKS
- segment:sa OR segment:sb  - DOESN'T WORK
- segment:sa segment:sb - DOESN'T WORK

But finally without  error.

**Review by kuzmany — CHANGES_REQUESTED** [review]
I've tested it on https://m3.mautibox.com/7784/s/contacts
I've created contact and added it to segment **sa** and **sb**
Then I've used this filters

- segment:sa - WORKS
- segment:sa OR segment:sb  - DOESN'T WORK
- segment:sa segment:sb - DOESN'T WORK

But finally without  error.

**Comment by RCheesley** [comment]
@galvani I am unable to rebase to trigger the code coverage report - can you take a look and rebase against staging please? Thanks!

**Comment by RCheesley** [comment]
@escopecz @alanhartless can someone rebase this PR please?

**Comment by escopecz** [comment]
@RCheesley rebased on top of current staging branch.

**Review by dennisameling — CHANGES_REQUESTED** [review]
Same feedback as @kuzmany. While the error is gone, it doesn't work to search for multiple segments at the same time.

**Comment by RCheesley** [comment]
@escopecz looks like this might need a bit of work given the feedback from both @kuzmany and @dennisameling on their tests.

**Comment by RCheesley** [comment]
Bumping to 3.1.1 due to unresolved feedback from testers.

**Comment by RCheesley** [comment]
@mautic/acquia-po is anybody able to look into this PR before the release freeze?

**Comment by chazadams** [comment]
Is this the freeze this weekend or later in the year?

**Comment by RCheesley** [comment]
This PR is tagged for 3.1.1. The release freeze for that is on Sunday 20th September.

**Comment by RCheesley** [comment]
Hi folks, bumping this to 3.1.2 due to outstanding unresolved feedback from testers.

@mautic/acquia-po the deadline will now be **18th October**.

**Comment by dongilbert** [comment]
@RCheesley Sorry about not circling back on this. I looked into fixing it this weekend. This PR does what it says it does - fixes the issue with duplicate aliases when filtering on multiple segments.

At it is today, trying to filter on multiple segments is not possible due to the error described. With this fix applied, the error is gone, but the functionality of filtering on multiple segments is still not working. This PR does not claim to fix the functionality, only the error.

I did try to fix the functionality as well, but got in to a very deep hole of refactoring required to support this. The query that currently gets generated returns an "impossible where" clause - an sql term meaning it will never return results.

With that in mind, I think it would be acceptable to merge this as is, as it does fix the error it says it does. If we would rather wait until the functionality is ready as well, then I would propose closing this PR, creating a separate issue to support multiple segments in filtering, and link to this PR with the understanding that any work that would be done on the issue should include the code from this PR as well.

Thoughts?

**Comment by RCheesley** [comment]
I think that the best course of action would be to raise an issue outlining the problem that this PR does not fix and give as much detail as possible on where to dig when looking to fix it based on your work to date. Link that to this PR so there's a reference point. 

With a bit of luck maybe someone can pick that up and get a PR over before the next release freeze (as we missed it already for this one) and we can merge both if appropriate to do so.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Based on the review from @kuzmany and @dongilbert and assuming that tests pass, this one is GTG. I have raised an issue about the separate bug relating to using multiple segments in filters.

**Pull request merged**
