### PR TITLE
fixed mautic:unusedip:delete

### LINKED ISSUE #10387: mautic:unusedip:delete not working in Mautic 4.0.0
### Mautic Version

4.0.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Calling mautic:unusedip:delete command ends with error
```
./bin/console mautic:unusedip:delete

In UnusedIpDeleteCommand.php line 55:
                                                                                                                      
  Attempted to call an undefined method named "getEntityManager" of class "Doctrine\Bundle\DoctrineBundle\Registry".  
                                                                                                                      

mautic:unusedip:delete [-l|--limit [LIMIT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

The reason for this is doctrine/doctrine-bundle package.
Mautic 3.3.3 uses
```
            "name": "doctrine/doctrine-bundle",
            "version": "1.12.13",
```
This version had `getEntityManager` method
https://github.com/doctrine/DoctrineBundle/blob/1.2.x/Registry.php

Mautic 4.0.0 uses
```
            "name": "doctrine/doctrine-bundle",
            "version": "2.4.2",
```
This version does not have that method:
https://github.com/doctrine/DoctrineBundle/blob/2.4.x/Registry.php

### How can we reproduce this issue?

Step 1: Run Mautic 4.0.0
Step 2: Run command `./bin/console mautic:unusedip:delete`

### Relevant log output

```shell
./bin/console mautic:unusedip:delete

In UnusedIpDeleteCommand.php line 55:
                                                                                                                      
  Attempted to call an undefined method named "getEntityManager" of class "Doctrine\Bundle\DoctrineBundle\Registry".  
                                                                                                                      

mautic:unusedip:delete [-l|--limit [LIMIT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by luguenth**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | Yes
| New feature/enhancement? (use the a.x branch)      | No
| Deprecations?                          | No
| BC breaks? (use the c.x branch)        | No
| Issue(s) addressed                     | Fixes #10387  

#### Description:
As mentioned in #10387 it was not possible to use `mautic:unusedip:delete` since Mautic 4.x. This PR fixes this Issue
#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2. Got to the CLI
3. execute the command `bin/console mautic:unusedip:delete`
4. There should be no exception thrown.
5. `n unused IP addresses have been deleted` should appear

### CODE REVIEW

**Review by kuzmany — DISMISSED** [review]
Good catch!
Works 👍

**Comment by donbowman** [comment]
i tested this, it worked for me

**Comment by RCheesley** [comment]
@luguenth this PR is on the 4.x branch (features and enhancements) rather than 4.0 (bug fixes).

Are you able to rebase the PR onto the 4.0 branch so that we can merge it with the next release of Mautic? Otherwise we will have to wait for the 4.1 release.

For future reference, the branching strategy is documented [here](https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#choose-the-right-branch) and hints are provided in the PR template:

```
<!-- ## Which branch should I use for my PR?

Assuming that:

a = current major release
b = current minor release
c = future major release

* a.x for any features and enhancements (e.g. 4.x)
* a.b for any bug fixes (e.g. 4.0, 4.1, 4.2)
* c.x for any features, enhancements or bug fixes with backward compatibility breaking changes (e.g. 5.x) -->

```

**Comment by luguenth** [comment]
Whoopsie. I'll rebase it tomorrow :)

**Comment by luguenth** [comment]
@RCheesley the PR is now rebased :)

**Comment by kuzmany** [comment]
@luguenth It looks like it contains some commits from 4.x branch

**Comment by luguenth** [comment]
Oh that's unfortunate. Do you know a good and Quick way to resolve this? I don't have access to the Code right now

**Comment by RCheesley** [comment]
Marking this as pending feedback as we need to get this PR fixed. By the time we get this fixed we may as well use the 4.x branch as we will be doing the minor release next month and it's too late for the patch release now.

**Review by lukassykora — DISMISSED** [review]
It seems OK, tested

**Pull request closed without merging**
