### PR TITLE
Fix UTM content longer like 191 characters

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Our customer add utm content longer like 191 characters, and then click from emails return 

`SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'utm_content' at row 1`

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Add utm tags to email
3. Add utm_content tag longer liek 191 characters
4. Send email
5. Click on the link from email
6. See like redirect link does not work
7. After PR should work

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11317"></a>

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
Great clean fix, great test. Good to go 👍

**Comment by escopecz** [comment]
Note: if you want to merge this into Mautic 4.4.1, please rebase on the 4.4 branch.

**Comment by volha-pivavarchyk** [comment]
I can't save email when the content longer than 191 characters. 
image
Am I doing something wrong?

**Comment by escopecz** [comment]
@volha-pivavarchyk that's the point. Zdeno added validation to the form so users cannot add longer value than the database can handle

**Comment by volha-pivavarchyk** [comment]
@escopecz I'm sorry. I misunderstood the description a bit

**Review by volha-pivavarchyk — APPROVED** [review]
Works well

**Pull request merged**
