### PR TITLE
Fix elFinder localization

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR fix elFinder localization.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Change locale of Mautic in configuration to French
3. Then open file manager from editor
4. You should see French version 

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10987"></a>

### CODE REVIEW

**Comment by volha-pivavarchyk** [comment]
Doesn't work for me

image

image

Maybe you mean another file manager

**Comment by kuzmany** [comment]
@volha-pivavarchyk you have to use  legacy builder (disable GrapesJs) and then image slot + filemanger el finder

image

**Comment by volha-pivavarchyk** [comment]
Works well. There is a french version.

image

**Review by escopecz — DISMISSED** [review]
The code changes make sense 👍

**Comment by RCheesley** [comment]
@kuzmany would you be able to rebase to 4.2 or should we just merge this for the 4.3 release (as it is on the 4.x branch presently)?

**Comment by escopecz** [comment]
I rebased the PR from 4.x to 4.2 but it showed other commits. So I reset it to 4.2 and cherry-picked the commit from this PR. I'll merge this once the CI is green.

**Review by escopecz — APPROVED** [review]

**Pull request merged**
