### PR TITLE
[DPMMA-507] Add permission export audit and history lead

### PR DESCRIPTION
**Pull request by tomekkowalczyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🟢 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description
The change also adds the user's history and AuditLog to the contact export permission. A bug related to a validation error and throwing error 500 in the case of empty log results has also been fixed.

image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. change the user's permissions so that he cannot export the contact
3. go to the website https://mautic5.ddev.site/s/contacts/view/{ID}, you will not be able to export data

### CODE REVIEW

**Review by escopecz — CHANGES_REQUESTED** [review]
This looks great! I can see the tests are only for the admin user. Can you also log in the sales user and test that this other user doesn't get to those export endpoints?

See https://github.com/mautic/mautic/blob/0d19f84e268a3852eb1ddd34519af69c95e42df4/app/bundles/AssetBundle/Tests/Controller/AssetControllerFunctionalTest.php#L135 for an inspiration.

**Review by AlanWierzchonCA — APPROVED** [review]
The changes look good to me.

**Comment by tomekkowalczyk** [comment]
@escopecz I added the user test you requested

**Review by patrykgruszka — APPROVED** [review]
Code looks fine. Tested manually - no problems at all

**Review by escopecz — APPROVED** [review]
Thanks for the extra tests! It would be also good to set the right permissions to the sales user and assert that this way the user can access the routes. Next time, please.

**Pull request merged**
