### PR TITLE
Fix case sensitive SugarCRM

### PR DESCRIPTION
**Pull request by kuzmany**
Add exception

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
I've noticed SugarCRM not syn on windows  because hook contain case sensitive letters.
Also I've added exception to activity sync. If lead ID doesn't exist, lead activity crash.

#### Steps to test this PR:
1. Code review
2. Then test sync leads and activities to SugarCRM

```
php app/console mautic:integration:fetchleads -i Sugarcrm  --time-interval="29 days"
php app/console mautic:integration:pushleadactivity -i Sugarcrm  --time-interval="29 days"
```
3. If sync works then 👍 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by alanhartless** [comment]
@kuzmany how did you test the activities? I'm not finding any documentation on how that works. It looks like a custom component in Sugar based on the name. If that's the case, does how it's built in Sugar affect this and by changing it to lowercase, do we break those with it already implemented?

**Comment by kuzmany** [comment]
@alanhartless there is no documentation for it. I just took some info from pull requests and some from code research. 
https://github.com/mautic/mautic/pull/4251 (in this PR I found activity module for SugarCRM)
https://github.com/mautic/mautic/pull/4247
I think It was developed some times ago for Webmecanik, then @npracht should know more.

Anyway, we can move this settings to config as parameter and the other devs could change it manually If needed.

**Comment by npracht** [comment]
Hello, not for us. I don't know how event works, if a dev can read the code and create a doc that would be awesome :)

**Comment by sensalot** [comment]
Can the Vtiger plugin be checked for this issue as well?

**Comment by RCheesley** [comment]
@kuzmany did the changes get made for this PR, and/or is it still relevant? Or can we close it down?

**Pull request closed without merging**
