### PR TITLE
Fix including/excluding operator in dwc

### PR DESCRIPTION
**Pull request by hluchas**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.2 for bug fixes
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
DWC filter is not matching in operator for countries.
Discovered when fixing https://github.com/mautic/mautic/pull/9519
Reproduction steps are almost same

#### Steps to test this PR:
0. Load up [this PR](https://mautibox.com)1. Create focus item and publish it
2. Create DWC
 - Use content 9581 DWC content {focus=1} where 1 is id of your created focus item
 - Is campaign based = no
 - Requested Slot Name = slot1
 - Add filter - Country including Czech Republic
3. Create landing page
 - with dynamic content where
 - Slot name is slot1
 - Slot content is Dynamic web content applied {dwc=slot1}‍
4. Use incognito mode in browser
 - add contact via form in incognito mode - contact should be added to CS
 - try to show page created in step 3 in incognito mode - focus item is not displayed
 - in CS set country to Czech Republic for this contact
 - reload page in incognito mode - focus item is not displayed - JS is not loaded

#### Steps to test this PR:
1. Use reproduction steps
2. Focus item is displayed and JS is loaded and operator is working correctly

### CODE REVIEW

**Comment by escopecz** [comment]
Moving to 4.0 milestone as it has the features branch merged in after the M4 was merged there.

**Review by escopecz — DISMISSED** [review]
It works as described. I saw the error in dev environment when viewing the landing page with DWC in it.

I made the code a little simpler with the last commit.

**Comment by RCheesley** [comment]
@hluchas @escopecz looks like we have a conflict to resolve here please!

**Comment by hluchas** [comment]
@RCheesley I'm sorry Ruth, but I've no plan to participate on Mautic in the future.
Thank you for understanding.

**Comment by dadarya0** [comment]
@kuzmany conflict resolved.

**Review by kuzmany — CHANGES_REQUESTED** [review]
This PR broke usage of multiselect in DWC filters. In this case the condition does not match

image

**Comment by kuzmany** [comment]
@hluchas @escopecz pending feedback https://github.com/mautic/mautic/pull/9581#pullrequestreview-755939049

**Comment by escopecz** [comment]
Closing in favore of https://github.com/mautic/mautic/pull/10871

**Pull request closed without merging**
