### PR TITLE
Track changes for Message entity and Category Entity

### PR DESCRIPTION
**Pull request by gunnrryy**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | No
| New feature/enhancement? (use the a.x branch)      | Yes
| Deprecations?                          | -
| BC breaks? (use the c.x branch)        | -
| Automated tests included?              | Yes 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | - 

#### Description:

This PR adds `is_changed` to setter functions of Entity/Message, Entity/Category.
Missing is_changed was resulting in Messages or Category being not tracked when checked via isChanged() method.

#### Note:

There are no UI changes and no manual test required. The changes are covered with Unit test.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11275"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for the PR @gunnrryy and welcome to the Mautic Community!

Looks like there is a failing test with PHP 8.0, would you be able to take a look please?

**Review by kuzmany — DISMISSED** [review]
Don't see issue.

**Comment by RCheesley** [comment]
Hi @gunnrryy and thanks for the PR, welcome to the community! 

Please can you take note of the failing test? Thanks!

**Comment by gunnrryy** [comment]
on it, sorry for the delay.

**Comment by gunnrryy** [comment]
it's all green now. Ready for review.

**Comment by jos0405** [comment]
@escopecz , @fedys  is this code review only? If so, could you plz chime in?

**Review by escopecz — DISMISSED** [review]
One way to test this is to create new category or message or edit an existing one and see that with this PR there are records in the `audit_log` table about the properties that has changed.

Tested and it works 👍

**Review by escopecz — APPROVED** [review]
I rebased this on the 5.x branch as this is an enhancement and there will be no more feature releases for M4

**Pull request merged**
