### PR TITLE
Gmail plugin

### PR DESCRIPTION
**Pull request by virlatinus**
| Q  | A
| --- | ---
| Bug fix? | No
| New feature? | Yes
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/102
| Related developer documentation PR URL | N/A
| Issues addressed (#s or URLs) | N/A
| BC breaks? | N/A
| Deprecations? | N/A

#### Description:
This plugin allows for the [Mautic Helper Chrome Extension](https://chrome.google.com/webstore/category/extensions) to keep track of emails sent to leads from within Gmail.

#### Steps to test this PR:
1. Install the Mautic plugin as usual. It will appear on the plugins page in Mautic.
image

2. Click on the Gmail plugin button and enter a secret or key to validate the Mautic Helper Chrome Extension
image

3. Install the [Mautic Helper Chrome Extension](https://chrome.google.com/webstore/category/extensions) from the Chrome Web Store
image

4. Configure the extension using the options page that will automatically be displayed. (Remember to use the same secret you entered in Mautic)
image

5. On the Chrome browser there will be a button that will notify of new events on the contacts timeline.
image

6. To track an email sent to a lead, click the Track Email button on the Compose window in Gmail
image

7. This will append a tracking GIF to the email with the following syntax:  [[MAUTIC_URL]]/index.php/gmail/tracking.gif?d=H4sIAAAAAAAEAIVRTW%2FCMAz9LRyCtgNVlFBpHHroWsRuk8ak7RpaUzqaGCUp0H8%2Fpy0TH4dJUZy892w921uLOvkCa8BGK2WLWi2dt6pUbM7PYPEcFainoFXdJKdBVvUy4quA9rxrNz9Q%2BCQ16HdgmeAenKewpfIU3lvfIO6nGyy75HNXO8LQAN3984R2X5tqMpkwnjOejrfg19%2FBJIHBJsskS3M1MOvOedChUA5HaPBAsp54a7UyBH%2BAw9YWECRrsMc6PHvFd2iR0NfW1QbcjUDwMjhctYqqq0YxkQU6SqMhNxi85GeoD8p0134zaBom%2By4ezlPMxTPFeCH5TLzI%2BdgizeEu5aIUQixmIubjSG5WAY8bC8kyC%2FvxSBX%2Flcvl3bT%2Fvr8k1oBgIQIAAA%3D%3D&sig=cf078d5b

8. The Mautic plugin will then validate the information using the secret to compare signatures and then attach that email to the contact’s profile as part of their activity history. If the lead or leads don't exist, they are created automatically
image

### CODE REVIEW

**Comment by alanhartless** [comment]
works and looks great!

**Comment by sambarnes90** [comment]
Thanks @virlatinus for this plugin. Something we've been looking at for quite some time now.

Is there any kind of debugging you would suggest we do if the contacts are not being updated?

I'm sending emails through Gmail, the tracking gif is definitely attached, the contact already exists in Mautic so it should just be updating the contact, but I can't see any of that happening.

It looks like the tracking gif has a different URL too - is that correct?

Just wondering if there is something really stupid I'm doing wrong...

I've tried:

- Clearing cache
- Sending from a couple of different accounts in Gmail
- Changing the Secret and clearing the cache, then trying again

Still been unable to add the email to the contact's timeline.

Does it have to be a mail account that's monitored?

Any advice you can give on where I might be going wrong would be much appreciated.

Thanks
Sam

**Comment by virlatinus** [comment]
Hello @sambarnes90.

If the contact's timeline is not being updated it may be the secret is not
the same in the extension options page and in the Mautic Plugin page.

You can debug by checking the log file in the app/logs folder. Check for
messages like

[timestamp] mautic.ERROR: Gmail: signatures don't match

or something like that, that can give you a clue about what's going on.

You can also check your web server's access log file and see if the
tracking gif is being requested, like:

186.151.61.100 - - [07/Oct/2016:07:40:48 -0600] "GET
/plugin/Gmail/tracking.gif?d=H4sIAAAAAAAAA71U ... ....A%3D%3D&sig=121a6bb3
HTTP/1.1" 304 -

One more thing, the URL in the extension options page should be a public
URL.

Best regards,



======================================

*Werner Garcia*
*MSN, Skype, **E-Mail:  *werner.garcia@gmail.com
*“When nine hundred years old you reach, look as good you will not." - Yoda*

**Comment by RobertAlan** [comment]
I tried to install the Mautic Helper Extension this evening. I set up the plugin and populated the 'Mautic Secret' in the Chrome plugin but I'm getting a 500 Internal Server error when trying to connect. I checked the log files as you suggested above and found this. Is there something else I need to do?

`[2017-02-26 03:56:06] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "LIMIT argument offset=-25 is not valid" at /home/MYDOMAIN/public_html/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php line 3318 {"exception":"[object] (Doctrine\\DBAL\\DBALException(code: 0): LIMIT argument offset=-25 is not valid at /home/MYDOMAIN/public_html/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php:3318)"} []
`

**Pull request merged**
