### PR TITLE
Reports: smarter query generation for faster load times

### PR DESCRIPTION
**Pull request by escopecz**
| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | Speed enhancement
| Automated tests included? | Y
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | /
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

~~⚠️ This PR modifies a file added in https://github.com/mautic/mautic/pull/7088. Merge that PR first!~~ - DONE

Reports join some tables even though the report configuration doesn't require to select, group by, order by nor filter by any column in that joined table. This PR makes the reports smarter so they would join the tables only if necessary. This will speed up some reports significantly.

This report was very slow for one of our customers:
Screenshot 2019-03-12 at 16 11 22

It generated SQL query like this:
```
SELECT es.email_address             AS email_address, 
       IF(dnc.id IS NOT NULL 
          AND dnc.reason = 2, 1, 0) AS bounced, 
       Date(es.date_read)           AS date_read 
FROM   mautic_email_stats es 
       LEFT JOIN mautic_emails e 
              ON e.id = es.email_id 
       LEFT JOIN mautic_leads l 
              ON l.id = es.lead_id 
       LEFT JOIN mautic_ip_addresses i 
              ON i.id = es.ip_id 
       LEFT JOIN mautic_emails vp 
              ON vp.id = e.variant_parent_id 
       LEFT JOIN mautic_categories c 
              ON c.id = e.category_id 
       LEFT JOIN mautic_lead_donotcontact dnc 
              ON e.id = dnc.channel_id 
                 AND dnc.channel = 'email' 
                 AND es.lead_id = dnc.lead_id 
WHERE  ( es.date_sent IS NULL 
          OR ( es.date_sent BETWEEN '2016-12-16 23:00:00' AND '2019-01-16 22:59:59' ) ) 
       AND ( es.date_read >= '2018-02-25 15:20:00' ) 
ORDER  BY es.date_read ASC 
LIMIT  30 offset 0 
```

With this PR checked out the query looks like this:
```
SELECT es.email_address             AS email_address, 
       IF(dnc.id IS NOT NULL 
          AND dnc.reason = 2, 1, 0) AS bounced, 
       Date(es.date_read)           AS date_read 
FROM   mautic_email_stats es 
       LEFT JOIN mautic_lead_donotcontact dnc 
              ON es.email_id = dnc.channel_id 
                 AND dnc.channel = 'email' 
                 AND es.lead_id = dnc.lead_id 
WHERE  ( es.date_sent IS NULL 
          OR ( es.date_sent BETWEEN '2016-12-16 23:00:00' AND '2019-03-13 22:59:59' ) ) 
       AND ( es.date_read >= '2019-03-11 08:45:46' ) 
ORDER  BY es.date_read ASC 
LIMIT  30 offset 0 
```

In this example we can remove 5 out of 6 joins and the result will be the same but faster.

#### Steps to test this PR:
This PR needs thorough testing as it may break for any report source with any configuration. The bigger the database the better. Also check that the displayed data in the reports make sense.

1. Create report for each report source and test random fields in select, order, group and filter.

### CODE REVIEW

**Comment by npracht** [comment]
@escopecz travis again

**Comment by escopecz** [comment]
That's because https://github.com/mautic/mautic/pull/7088 must be merged first.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by dennisameling** [comment]
@escopecz if you could rebase once more we'll have a proper code coverage report 😊 codecov's comment will be updated automatically. Thanks in advance

**Comment by escopecz** [comment]
@dennisameling  Rebased. Thanks for configuring CodeCov!

**Comment by RCheesley** [comment]
@escopecz looks like we have a conflict to resolve :)

**Comment by RCheesley** [comment]
Bumping to 3.2 due to unresolved conflicts.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by escopecz** [comment]
Rebased to current staging

**Review by heathdutton — APPROVED** [review]
Code reviewed. Appears to solve a long-standing issue w/ reports.

**Pull request merged**
