### PR TITLE
[Feature] Chained actions

### PR DESCRIPTION
**Pull request by heathdutton**
| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Yes
| Automated tests included? | No
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | No
| Deprecations? | 

[//]: # ( Required: )
#### Description:
Actions sometimes need to take place in sequence. Examples:
* Update a contact field before sending to an integration.
* Multiple actions that need to happen at the the same time (roughly) but in a specific sequence.
* Push to one integration before pushing to another, and another, and another, all within the same minute.

Backstory:
Versions up to 2.13.1 (secretly, or perhaps accidentally) supported chained actions internally but prevented you from creating them by hiding the "actions" panel via javascript. We "unhid" that panel and have been chaining actions ever since. Now that the campaign processing has been refactored in staging the (accidental/hidden) feature stopped working. 

This PR makes it a real feature, like so:

Two actions connected driectly

#### Steps to test this PR:
1. Create a campaign with an action chained to another action.
2. Both actions should be triggered.

### CODE REVIEW

**Comment by luizeof** [comment]
@heathdutton Great Job!!!

ready to test?

**Comment by heathdutton** [comment]
Need to add at least one test case for this, yep.

**Comment by heathdutton** [comment]
@dbhurley unit tests now include a test of chained actions.

**Comment by kgroveshok** [comment]
Worked for me. Thanks

**Comment by kgroveshok** [comment]
Oh. Only commment I have is that I couldn't add actions to existing campaigns. Please confirm this experience: is what you want 

1. Checked out base code. 
2. Created campaign to see it not allow an 'action'
3. Then checked out the PR
4. Cleared cache
5. Went back into the campaign to add the 'action', but the option is still as if no PR applied.
6. Straight to create new campaign and that showed the 'action' panel on chains of actions.

**Comment by heathdutton** [comment]
You may have still had something cached in either the browser or asset level. It does also apply to existing campaigns.

**Comment by kgroveshok** [comment]
Thanks. Most likely browser cache then as I did clear the other one. Safe to ignore me then :-)

**Comment by Woeler** [comment]
@heathdutton Could you resolve the conflicts? I would like to test this and get it on the merge line.

**Pull request merged**
