### PR TITLE
Emoji image fix and email support

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**
The updated image was left out of PR #618 so this adds it.

The PR also cleans up the EmojiHelper file and adds support for shortcode conversion in addition to HTML.  Fixed the CSS for the emoji as the other images in the sprite were visible around the edges of the emoji.  Moved the emoji stuff into the CoreBundle as it's now being used outside of just the AddonBundle.

Finally, this PR adds support for emoji in email subject, custom HTML body and builder content.  

**Testing**
Create a new email with an emoji in the subject or body and save.  Crashed system. :-) Delete the last audit log entry in the audit_log table to restore access.  Now apply the PR and try again.  Send an email with an emoji.  View the preview page of an email with an emoji.  View the details page of an email with an emoji in the subject.  Emoji's should show up just fine everywhere, including the sent email, and not have a crashed Mautic.

Send an email to a lead directly that includes an emoji in the subject and body.  The email should arrive with the emoji.  The notification should show the emoji.  If you view the lead's timeline and click on the Custom Email, it should show a copy of the email also showing the emoji.  And of course no crashed Mautic.

### CODE REVIEW

**Comment by drmmr763** [comment]
+ Test couldn't save an email with an emoji in the title. After PR could save the email and send it. 
+ test previewing online showed the emoji properly
+ send email showed emoji properly

+ vote +1

**Comment by drmmr763** [comment]
I did notice the subject emoji didn't work on the mail queue:

https://www.evernote.com/shard/s42/sh/5846175e-594f-4402-a7fe-292b356ac542/1d37765b4b33ecd6/res/13a7e03a-67b8-4b06-a448-edd144c0dbf3/skitch.png?resizeSmall&width=832

**Comment by alanhartless** [comment]
Ah forgot about that.  I'll fix it.

**Comment by dbhurley** [comment]
+1

**Pull request merged**
