### PR TITLE
Set timeout in post method to updates.mautic.org

### PR DESCRIPTION
**Pull request by tomferreira**
See #465

### CODE REVIEW

**Comment by alanhartless** [comment]
Hi Tom!

Thanks for the PR!

We're thinking that 5 seconds is a little short.  Maybe bump it to 10?

Also, while at it :-) , you may want to apply the same fix to these two uses as well:
https://github.com/mautic/mautic/blob/staging/app/bundles/CoreBundle/Helper/UpdateHelper.php#L125
https://github.com/mautic/mautic/blob/staging/app/bundles/CoreBundle/Helper/UpdateHelper.php#L138

**Comment by tomferreira** [comment]
Hi Alan,

I updated the timeout to 10 seconds and I added these new cases.

**Comment by dbhurley** [comment]
+1. Works as expected. Thanks!

**Comment by alanhartless** [comment]
:+1: from me thanks @tomferreira!

**Pull request merged**
