### PR TITLE
Fix Invalid clickthrough value exception

### LINKED ISSUE #9400: Campaign: Error with sending scheduled email and with tracking
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
This bug occurs in campaign events. DOESN'T HAPPEN IN COMMON EVENTS...

When creating a campaign that sends an email to the contact, and then tracks the action "Clicked on email", after the contact clicks the link an error in the log appears. Furthermore, Mautic stops recording any more "Contact / lead" tracking.

The same email sent outside of a campaign does not generate the error.

Also, campaign that contains the email sending rule: "in the relative time period". 1 day between the hours of 08:00 am to 03:00 pm, still sends e-mails after the scheduled time.

| Q   | A
| --- | ---
| Mautic version | 3.1.2
| PHP version | 7.3 PHP-FPM
| SMTP |  SendBlue

### Steps to reproduce
1. Create an email with a LINK.
2. Create a campaign containing: Has valid email address, Visits a page, Add Do Not Contact, Modify contact's segments, Update contact, Change campaigns.
3. Configure email delivery: "in the relative time period". 1 day between the hours of 08:00 am to 03:00 pm

### Tracking error
The tracking problem, I see that it is related to devices that have multiple users.

1. Create Two Leads.
2. Send email to the 2.
3. Click the link in the email on one of the Leads and check its history, it is working perfectly.
4. Click the link in the email with the other Lead, now look at the history of the two leads. Traking was not triggered for either lead.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )
mautic.ERROR: Invalid clickthrough value: Yjo4OntmOjk6ImZiaGVkZiI7Yjo1Ont2OjM7Zjo0NzoiZGJ6Y2J2dGEuZmlmYWciO3Y6NDt2OjQxMDg7fWY6ODoiZnpidnkiO3Y6NDk4O2Y6NzoiZmdiZyI7Zjo1NToiOGFiZGFkZTc1MTg4NTIxNjEzMjgyNiI7Zjo3OiJ5ZmJlIjtmOjk6IjY3ODc0MiI7ZjowOiJkdWJhYWZ5IjtiOjQ6e2Y6ODoiZnpidnkiO3Y6NDk4O319 {"exception":"[object] (Mautic\\CoreBundle\\Exception\\InvalidDecodedStringException(code: 0): The string b:8:{f:9:\"fbhedf\";b:5:{v:3;f:47:\"dbzcbvta.fifag\";v:4;v:4253;}f:8:\"fzbvy\";v:499;f:7:\"fgbg\";f:55:\"8abe41efff8d1525464563\";f:7:\"yfbe\";f:9:\"417552\";f:0:\"dubaafy\";b:4:{f:8:\"fzbvy\";v:499;}} is not a serialized array at /public_html/mkt.comm/app/bundles/CoreBundle/Helper/ClickthroughHelper.php:53)"} []

Editar-Campanha-Mautic (1)

image

SendBlue

It started before the scheduled time
image

It didn't stop when it should.
image

Using Amazon SES SMTP, Mautic respected the configured shipping times. However, the test was performed in another installation, both on the same server with the same settings.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/94211522-campaign-error-with-sending-scheduled-email-and-with-tracking?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #9400

#### Description:
This PR fix issue millions logs like:

`[2021-09-02 10:28:41] mautic.ERROR: Invalid clickthrough value: Yjo4OntmOjk6ImZiaGVkZiI7Yjo1Ont2OjM7Zjo4OiJmemJ2eSI7djo0O3Y6NDAyO31mOjg6ImZ6YnZ5Ijt2OjQwMjtmOjc6ImZnYmciO2Y6NTU6Ijk0NjNiNWNjMWRmNzk5MjcwNjI0NDUiO2Y6NzoieWZiZSI7ZjowOiI0OTY1Nzg1IjtmOjA6ImR1YmFhZnkiO2I6NDp7Zjo4OiJmemJ2eSI7djo0MDI7fX0= {"exception":"[object] (Mautic\\CoreBundle\\Exception\\InvalidDecodedStringException(code: 0): The string b:8:{f:9:\"fbhedf\";b:5:{v:3;f:8:\"fzbvy\";v:4;v:402;}f:8:\"fzbvy\";v:402;f:7:\"fgbg\";f:55:\"9463b5cc1df79927062445\";f:7:\"yfbe\";f:0:\"4965785\";f:0:\"dubaafy\";b:4:{f:8:\"fzbvy\";v:402;}} is not a serialized array at..`

I collect the requests, and it looks like this kind of requests are from bots (Microsoft....)
Then we should skip it.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Go to your page with tracking code
3. Add to url `?ct=Yjo4OntmOjk6ImZiaGVkZiI7Yjo1Ont2OjM7Zjo4OiJmemJ2eSI7djo0O3Y6NTM4O31mOjg6ImZ6YnZ5Ijt2OjUzODtmOjc6ImZnYmciO2Y6NTU6Ijk0NzY4Y2I4YmZhMGY4Nzc2NTMzODEiO2Y6NzoieWZiZSI7Zjo5OiI4MjM5OTgiO2Y6MDoiZHViYWFmeSI7Yjo0OntmOjg6ImZ6YnZ5Ijt2OjUzODt9fQ`
4. Check your logs and you should see error :  `mautic.ERROR: Invalid clickthrough value: `
5. After PR page you should see not tracked page in the browser console - we asume it's bot

image

### CODE REVIEW

**Comment by alanhartless** [comment]
I think it is ok to prevent an invalid CT from throwing an exception, but I wouldn't mark https://github.com/mautic/mautic/issues/9400 as solved with this. The question I'd ask for 9400 is why are CTs getting corrupted to start with?

**Comment by kuzmany** [comment]
@alanhartless now I see. I don't think ct param is corrupted during the sending. What I noticed all these CT params were with similar flags like User-Agent or IP address. 
I checked few of IP address and all was related to Microsoft. 

I suppose tracking not counted in linked issue were caused because user was logged in Mautic or something.

**Comment by alanhartless** [comment]
`I checked few of IP address and all was related to Microsoft.` That's a good clue. We've seen this in our logs as well. I'll check to see if they are also related to MS.

**Comment by alanhartless** [comment]
Yup. Good find. This seems to be related to MS 365 clients. I'll cross post to the issue.

**Review by sreenia806 — APPROVED** [review]
looks good, make sense. thank you

**Comment by RCheesley** [comment]
Chatted with @alanhartless and this is good to be merged *but* please leave the connected issue open, because this only patches up the symptoms rather than addressing the root cause.

**Comment by dennisameling** [comment]
@all-contributors please add @sreenia806 for user testing

**Comment by dennisameling** [comment]
@all-contributors please add @sreenia806 for review

**Comment by YosuCadilla** [comment]
Probably related:
https://github.com/mautic/mautic/issues/6775
https://github.com/mautic/mautic/issues/9400
https://github.com/mautic/mautic/pull/10444
https://forum.mautic.org/t/mautic-error-invalid-clickthrough-value/15833/8

**Comment by zietbukuel** [comment]
This is still happening to me on the latest Mautic version.

**Pull request merged**
