### PR TITLE
Campaign Action: Show Focus Item

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/3551
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Follow up to this PR https://github.com/mautic/mautic/pull/4253, but more clear, user friendly...
Same logic as previous my PR https://github.com/mautic/mautic/pull/4573
Focus Item could be set everywhere in Campaign after Visits a Page decision.

#### Steps to test this PR:
1.  Apply PR + depends on https://github.com/mautic/mautic/pull/4573
2.   Set Focus Item in campaign after Visits a Page decision
3. Go to tracking page and test

image

### CODE REVIEW

**Comment by luizeof** [comment]
@kuzmany Great! Today I use Dynamic Content to do this ....

+1

**Comment by kuzmany** [comment]
@escopecz Mr, Could you mark it as ready for test? (also https://github.com/mautic/mautic/pull/4573)

**Comment by escopecz** [comment]
@kuzmany is this replacement of https://github.com/mautic/mautic/pull/4253?

**Comment by kuzmany** [comment]
@escopecz yes, but better
Previous version needed new table and db migration. Also as I read from docs "Place the mautic page tracking code and the script of selected focus item in to your website source". This PR require just standard mautic page tracking code, nothing else.

**Review by virlatinus — APPROVED** [review]
It works as described. The focus item is displayed. Thanks!

**Comment by javjim-mautic** [comment]
Works properly

**Comment by oytuntez** [comment]
Minor documentation that may help someone in the future:

Showing focus items on your website as part of a campaign requires synchronous campaign processing. If you are using queues to process events such as email read, page hits, then these focus items won't be triggered properly. You need to disable the queue to get the correct result.

To overcome this case, we didn't disable the queue for good, but we did for page hits only.

**Pull request merged**
