### PR TITLE
DateTimeHelper use local timezone from configuration not from server

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This is pain from all versions Mautic. DateTimeHelper used date_default_timezone_get() to get local timezone. 
But customers can set default timezone in configuration. We should use as timezone  from configuration, it make more sense. 

Then we do not need take default_timezone from parameters on every place like here https://github.com/mautic/mautic/blob/661b0f07d1c588e01d67901b99f16e715fc72fec/app/bundles/CoreBundle/Helper/DateTime/DateTimeToken.php#L46 

Instead of

```
        $contactTimezone       = $contactTimezone ?: $this->coreParametersHelper->get('default_timezone', 'UTC');
        $dateTime              = new \DateTime('now', new \DateTimeZone($contactTimezone));
```

We can use 

`$dateTime = (new DateTimeHelper())->getLocalDateTime();`

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Probably check If date time is correct on timeline of contact etc

### CODE REVIEW

**Comment by kuzmany** [comment]
@mabumusa1 unit tests fixed

**Review by mabumusa1 — DISMISSED** [review]
Code changes look good, and there are tests attached. I think this PR is good to go

**Comment by kuzmany** [comment]
Note to myself: Once we merge this we have another two PR related to it

**Comment by escopecz** [comment]
@kuzmany seems there is a conflict now.

**Comment by kuzmany** [comment]
@escopecz fixed

**Comment by escopecz** [comment]
Now the tests are failing

**Review by escopecz — APPROVED** [review]
It makes sense. I can't forsee all the consequences of this change. I hope it won't cause any issues.

**Comment by kuzmany** [comment]
@escopecz probably some segment filters are affected. But still, date time filters for segments don't work properly. We prepare updates also for it.

**Pull request merged**
