### PR TITLE
Campaign forms source - add contact just to active campaign

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

If you use forms as campaign source, contacts are added to inactive campaigns. This PR fixed it

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create campaign form
3. Create two campaigns
- Published
- Unpublished
4. Submit form
5. See contact was added to both campaign
6. We expect add contact just to active campaigns

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11130"></a>

### CODE REVIEW

**Review by volha-pivavarchyk — DISMISSED** [review]
Works as described. Contacts are added to active campaigns

**Review by jos0405 — DISMISSED** [review]
Works as expected.
Campaign 1: (Published)
image
Campaign 2: (Unpublished)
image

**Comment by RCheesley** [comment]
@kuzmany looks like the PR I just merged has now resulted in a conflict with this PR (looks like the test you wrote).

**Comment by escopecz** [comment]
@kuzmany I'm wondering why is it bad to add contact members who submitted a form which is a source of an unpublished campaign. As the campaign is unpublished then no events will be executed.

The only difference this make is that when the campaign is published again then it will not process the contacts that submitted the form during the period of time when the campaign was unpublished. I can imagine use cases where this won't be desired behavior. Maybe the user unpublished the campaign to fix a typo in an email used in the campaign. But the user still wants to add the contacts who are submitting the source form in the mean time to go through the campaign once the campaign is published again.

**Comment by escopecz** [comment]
@kuzmany can you please rebase and resolve the conflict?

**Comment by kuzmany** [comment]
@escopecz done

**Pull request merged**
