### PR TITLE
Fixed tj-actions/changed-files GitHub action

### PR DESCRIPTION
**Pull request by fedys**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features"
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      |
| Related developer documentation PR URL |
| Issue(s) addressed                     | 

#### Description:
This PR tries to fix the following error in GitHub actions:
```bash
Warning: Unable to determine the head sha
Warning: You seem to be missing 'fetch-depth: 0' or 'fetch-depth: 2'
```

### CODE REVIEW

**Review by RCheesley — DISMISSED** [review]

**Comment by RCheesley** [comment]
This change looks good according to the instructions at https://github.com/tj-actions/changed-files#running-pre-commit-on-all-modified-files

Thanks @fedys !

**Comment by RCheesley** [comment]
There seems to be an issue with the code coverage report - I merged in the changes from Features earlier to prepare to get this merged. I think it is probably a false positive do you think @fedys seeing as the file mentioned is not part of this PR.

**Comment by fedys** [comment]
@RCheesley I tried rebasing onto current `features` which didn't help either. I would ignore the code coverage decrease as I didn't touch any PHP file.

**Comment by RCheesley** [comment]
OK - LGTM!

**Pull request merged**
