### PR TITLE
Display just published fields in form field mapping

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Unpublished contact fields are displayed in form field mapping tab. This PR fixed it

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Unpublish one of your contact fields, for example address 1
3. Go to form and try map this field with your form field
4. After PR is not possible

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10734"></a>

### CODE REVIEW

**Comment by kuzmany** [comment]
Related Mautic PR https://github.com/mautic/mautic/pull/10734

**Review by escopecz — CHANGES_REQUESTED** [review]
The code looks good, but it's does not have automated test. Could you please create a test that would:
1. Unpublish 1 existing custom field.
2. Load the FieldModel service from the container
3. Call the `getObjectFields()` method on that service
4. Assert that one published field is present in the choices and one unpublished is missing.

**Comment by kuzmany** [comment]
@escopecz unit tests added

**Review by escopecz — DISMISSED** [review]
The code makes sense. Thanks for the test! 👍

**Review by npracht — APPROVED** [review]
Perfect ✅ 
It will avoid a lot of user usage issues 🚀

**Pull request merged**
