### PR TITLE
[UX] Create a tooltip for "Placement" to explain the behavior of the bar (focus item) when it is placed at the bottom of the page

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This update introduces a tooltip for the “Positioning” feature, elucidating the behavior of the focus item when placed at the bottom of the page. It clarifies that with the sticky option disabled, the bar will appear at the end of the page content. However, if the sticky option is enabled, the bar will remain at the bottom of the user’s viewport as they scroll. This enhancement ensures users have a clear understanding of how the bar will function and appear on their page, allowing for more precise design control.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Focus Items
3. Create a new
4. On Style, choose Bar
5. Hover over Placement

image

### CODE REVIEW

**Review by LordRembo — APPROVED** [review]
Yes to more tooltips!

**Comment by andersonjeccel** [comment]
@LordRembo haha awesome! 😉👌🏻

**Review by roboparker — APPROVED** [review]

**Review by Mike-Dropsolid — APPROVED** [review]

**Comment by Woeler** [comment]
Can you stop inviting me to review your pull requests? I have nothing to do with any of this, nor have I been active in this repository for the past 5 years.

**Comment by escopecz** [comment]
CS fixer is failing.

**Comment by andersonjeccel** [comment]
@escopecz Fixed

**Comment by escopecz** [comment]
It is now failing on an error I see in other PRs. It's probably not related to this one.

**Comment by escopecz** [comment]
It seems to be fixed by updating the PR on the fresh 5.x branch. The CS fixer check tries to check for a class that does not exist in this PR but exists in 5.x. If you see it elsewhere, please update the PR.

**Pull request merged**
