### PR TITLE
Api manage lead points

### PR DESCRIPTION
**Pull request by LAN-Laurene**
| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | mautic/developer-documentation#9
| Related API-library | mautic/api-library#30
| Issues addressed (#s or URLs) | #967
| BC breaks? | 
| Deprecations? | 

#### Steps to test this PR:
1. Apply Related API Library PR
2. Apply this PR
3. Try the following api endpoints
  - set -> Overwrite the score (you can define what will be noted in the lead's history)
  - add -> add points to the score (you can define what will be noted in the lead's history)
  - substract -> substract points to the score (you can define what will be noted in the lead's history)
  - apply_rule -> applies a existing score rule to the lead (this rule must be of type "api.call")

### CODE REVIEW

**Comment by escopecz** [comment]
Looks good! Could you please fix the indentation so it would respect the Mautic's [coding standards](https://github.com/mautic/mautic/blob/staging/.github/CONTRIBUTING.md#coding-standards)?

**Comment by LAN-Laurene** [comment]
Hello, 

@escopecz, we use Eclipse, have you a formatter for Eclipse ? 

Thanks,

**Comment by escopecz** [comment]
I don't have experience with Eclipse. However, Mautic's coding standard should be the same as the one for Symfony2 as written in the linked document. I'm sure if you'll [search for it](https://www.google.cz/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8&client=ubuntu#q=eclipse%20symfony2%20formatter), you'll be able to find one.

**Comment by LAN-Laurene** [comment]
Hello,

I created a formatter from the psr-2 and modified it to make it as close as possible to your code style.

If it suits you, I will share it with my team.

**Comment by escopecz** [comment]
It'd be great if you could add it to the dev docs repo: https://github.com/mautic/developer-documentation .

Although it's bad that you couldn't make the array values in one row and everything have strictly one space. I'm not sure how others will take it.

Anyway, it seems your PR has some conflicts. Could you please merge the latest staging branch into it and deal with them?

**Comment by LAN-Laurene** [comment]
Hello,

Here is the pull request for the API-library (https://github.com/mautic/api-library/pull/30) and the documentation (https://github.com/mautic/developer-documentation/pull/9).

I will resolve the conflicts asap.

**Comment by alanhartless** [comment]
HI @LAN-Laurene. Can you please merge the conflicts and add steps how to best test this PR? Thanks!

**Comment by dongilbert** [comment]
@LAN-Laurene Please merge current staging into your branch and resolve any remaining conflicts. If you do we can get this for 2.0

**Comment by npracht** [comment]
Hi @dongilbert we had to focus on some other infra issues on our side and we're now gonna update all our use to 2.0.0. We'll pull request updated version of that after our migration.

Keep in touch,

N.

**Comment by MaxWebmecanik** [comment]
Hi, I've brought this branch back up to date.
Was there anything else we needed to do to make this PR mergeable?
Are there things we should improve?

**Comment by escopecz** [comment]
I'm having a hard time to review the code changes as it seems like half of the changed files just adds or removes some spaces and doesn't contain any code change. Is that right? Do you think you could remove those files from this PR?

It often cause troubles even later when you search for some change in the git history of a file and some PR just adds a space in it.

**Comment by MaxWebmecanik** [comment]
Sorry about that, I just committed a style fix

**Comment by escopecz** [comment]
Much cleaner, thanks! I'll give it a test in a moment.

**Comment by escopecz** [comment]
Ah, there are no testing instructions. I updated your PR description with the current PR template. Please, fill in the blanks. Also, the documentation PR is now required for each new feature.

**Comment by MaxWebmecanik** [comment]
Ok so turns out this is linked to two other pull requests:
- https://github.com/mautic/developer-documentation/pull/9
- https://github.com/mautic/api-library/pull/30

**Comment by MaxWebmecanik** [comment]
Here's the documentation for this https://github.com/Webmecanik/developer-documentation/blob/98262bf2e2cb4c551e6fbdf6a1838bd1be4c3dce/source/includes/_api_endpoint_leads.md#set-points

**Comment by escopecz** [comment]
Cool, could you please fill it in the PR description so it would be obvious? Also please fill in the steps to test this.

**Comment by escopecz** [comment]
@MaxWebmecanik Once again, please fill in description of this PR. That's probably the reason of the following.

I don't understand:

1. what are you trying to achieve with the `mautic.api_call` event
2. what is the purpose of the empty `PointActionApiCallType` class
3. what the `applyRule` endpoint is for?
4. you have API endpoints like `PATCH /leads/ID/removepoints/POINTS` in the linked documentation PR, but they are not present in this PR.
5. you have API endpoints like `/contacts/{id}/subtractpoints/{points}` which are not documented in the linked documentation PR.

**Comment by MaxWebmecanik** [comment]
Hi John,

Sorry for the lack of action on our side. I took some time with the developer who wrote this to answer your questions.

1. The `mautic.api_call` event is here to differentiate API point actions from normal point actions
2. The `PointActionApiCallType` class is just a stub to fit in the current system.
3. The `applyRule` lets you manually activate a points rule on a specific contact.
4 & 5 This is a mistake, I'll get to fixing that.

**Comment by escopecz** [comment]
Thanks you, that was helpful. I removed this PR from 2.2 milestone because we are working on a huge API update for 2.3 (I think) and we'll merge this PR to it (so you guys get the credit), modify it a bit and write the tests for it.

**Comment by escopecz** [comment]
I merged this PR to the big API update PR: https://github.com/mautic/mautic/pull/2738

Notes: I've simplified it. There is no event as you had in the code. I didn't find any use for it. If you do, please, create a new PR with it and description why it is useful. I also didn't find any reason for the "apply rule" endpoint. The points can be set in the `contacts/new` and `contacts/{id}/edit` endpoints now so I removed that special endpoint.

**Pull request closed without merging**
