### PR TITLE
Addon to plugin conversion

### PR DESCRIPTION
**Pull request by alanhartless**
**Descriptions**
Addons are being officially renamed to plugins.  This PR makes the conversion. 

1) All instances of addon have been changed to plugin.
2) /addons have been relocated to /plugins
3) All plugins are enabled by default thus removed all code related to enabled/disabled plugin bundles
4) BC/deprecated support added for addons that leverage the MauticAddon prefix, extends the AddonBundleBase class, or uses the addon prefix for models, permissions, ajax, etc.  
5) Disabled lead profile for Facebook until the API restrictions are worked around
6) Added support for plugin schema installation or update through new inheritable onPluginInstall and onPluginUpdate functions in PluginBundleBase that are executed automatically when the reload button is clicked.  Doctrine metadata is used to install or update the plugin's schema.  
7) Removed the manage addon list view and made the integration view default.  Integrations that are disabled are grayscale; enabled/published are in color.  Plugins without integrations show in color and display a simple information modal when clicked rather than a form.

**Testing**
1) Backup the database as this PR includes a migration that is irreversible.
2) Apply the PR 
3) Run `composer install` as some of the autoload stuff has to be updated
and clear browser and symfony cache.
4) Run `php app/console doctrine:migrations:migrate` to update the schema

Instead of Addons in the admin menu, you should now see Plugins. Click to configure an integration or two and they should be in color.  Test the integrations such as Twitter lead profile to ensure all works OK.

Use https://github.com/drmmr763/TestAddonBundle to test BC compatibility.  The only BC break is if the addon references the path '/addons' directly rather than using `__DIR__` or similar.

### CODE REVIEW

**Comment by dbhurley** [comment]
Tests good for me. +1

**Comment by mbabker** [comment]
The [upgrade script](https://github.com/mautic/mautic/blob/staging/upgrade.php#L169) will also need adjusted for this.

**Comment by drmmr763** [comment]
Trying to test this and I keep getting a redeclared class error for the MauticCloudStorageBundle:

` Cannot redeclare class MauticPlugin\MauticCloudStorageBundle\MauticCloudStorageBundle`

Getting this when I clear cache - I manually deleted cache but that didn't fix it either. I checked the class out and it looks correct so I'm not sure what is going on.

**Comment by alanhartless** [comment]
Did you run `composer install`?

**Comment by alanhartless** [comment]
@drmmr763 I switched things around and left /addons in place and basically just added support for the /addons directory rather than trying to trick composer/PHP into namespace/directory locations.  After updating, run `composer install` again then see how it goes.

**Comment by drmmr763** [comment]
+ test checked out the branch, cleared cache, composer install, ran the migration.
+ Enabled a plugin (authenticated twitter) - no issues
+ Installed my test addon package in the `/addon` directory - cleared cache and it showed up properly
+ vote +1

Everything appears to work great!

**Pull request merged**
