### PR TITLE
Easy grapes builder access

### LINKED ISSUE #10494: Possibility to access (grapejs) builder instance with javascript missing
### Mautic Version

3.3.x series

### PHP version

7.3

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I am trying to add sections and blocks to the grapejs builder. It is working fine, but I am missing a possibility to access the initialized builder.

A dirty solution I did was to add 
`Mautic.grapesBuilder=builder`
in Assets/library/js/builder.js right after `const builder = new BuilderService( ...` call (Line 21 in my case). I touched the dist too of course.

Is there a reason builder object is unaccessable or is there a better practice

### How can we reproduce this issue?

Try to add custom blocks to the grapejs builder

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by KALA-Typo3**
... for a possibility to extend the builder

| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10510"></a>

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
I see no harm in this change 👍

**Comment by npracht** [comment]
@KALA-Typo3 can you please sign the contributor agreement ?
Thanks !

**Comment by RCheesley** [comment]
@cla-bot check

**Review by kuzmany — APPROVED** [review]
Ok for me 👍

**Comment by adiux** [comment]
@KALA-Typo3 would it work for you if instead of making the builder public (which can have all sorts of uncontrollable side effects) we return it from the function?

like this:
```js
function launchBuilderGrapesjs(formName) {
// ...
    return builder;
// ...
}
```

**Comment by adiux** [comment]
Since we haven't heard back from @KALA-Typo3 in 2 months and we have https://github.com/mautic/mautic/pull/10781 that replaces this PR, I'm going to close it for now.

**Pull request closed without merging**
