### PR TITLE
Fix for issue 7338 - segment not added back to campaign

### PR DESCRIPTION
**Pull request by DanielCiochiu**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | No
| Automated tests included? | No
| Related user documentation PR URL | No
| Related developer documentation PR URL | No
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/7338
| BC breaks? | It shouldn't
| Deprecations? | No

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
What happens is that configuring a campaign by allowing contacts to be added back to campaign doesn't result in expected behavior. This change https://github.com/mautic/mautic/commit/087988033524cfbd5fba3a5a47fd5682ec7481fb partially fixes the issue in the way that it doesn't append the condition for a lead to not exist in the campaign_lead_event_log if campaing can be restarted. Still, the issue persists due to the previous condition append of lead not being associated to a certain campaign regardless of whether or not the campaign is to be restarted.

@alanhartless This change shouldn't break backwards compatibility, but can you please check just to be sure it doesn't rise other issues?

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Described in https://github.com/mautic/mautic/issues/7338

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by dichvuhuuich** [comment]
I've test step by step:
1. Add tag "add1point" to contact id 19
2. Create segment "Segment add 1 point" with tag including "add1point" https://mautibox.com/7704/s/segments/view/2
3. Create campaign "Campaign add 1 point" with source is segment "Segment add 1 point" and step is add 1 point
https://mautibox.com/7704/s/campaigns/view/1
4. Contact added to campaign ok
5. Remove tag "add1point" from contact id 19 and add  tag "add1point" to contact id 19 again
6. It is added to campaign "Campaign add 1 point" but it is looped add to campaign again and again and add score to contact like this: https://mautibox.com/7704/s/contacts/view/19

Please check and fix.

**Comment by dichvuhuuich** [comment]
There new improve is after added to campaign "Campaign add 1 point" and then remove from campaign "Campaign add 1 point", it has logs in contact, but it is still looped add to campaign again and again and add score to contact like this contact: https://mautibox.com/7704/s/contacts/view/19

log-add-remove-campaign

**Comment by DanielCiochiu** [comment]
@dichvuhuuich I think we were both making changes on this contact which lead to confusion. In contact's history list you can see that it after being added back to campaign, the campaign is triggered only once for it. Can you please check again while I will no longer make changes to this contact.

**Comment by ivan-newcom4u** [comment]
Hi,

Here's what I've tested on Mautibox:
- one campaign with segment source "Dynamic segment add 5 points" is adding 5 points to the contact (https://mautibox.com/7704/s/campaigns/view/2)
- another campaign with segment source "Fixed segment add 5 points" is removing and adding back the contact to the segment "Dynamic segment add 5 points" and it restarts every 13 minutes (https://mautibox.com/7704/s/campaigns/view/3)

The contact is being added to the segment "Dynamic segment add 5 points" multiple times but the campaign adding 5 points is not being triggered again (https://mautibox.com/7704/s/contacts/view/41).

My test is a bit different from the description in issue  #7338 because the source segment is not really dynamic with filtering options but another campaign is removing contacts and adding them back to the segment. I'm not sure if it's the same issue or if a new one should be opened.

This was working on Mautic 2.14.2.

**Comment by dichvuhuuich** [comment]
> @dichvuhuuich I think we were both making changes on this contact at the same time which lead to confusion. In contact's history list you can see that after being added back to campaign, the campaign is triggered only once for it. Can you please check again? I will no longer make changes in Mautic box.

It's amazing that we were both making changes on same contact. I've test again and it's working like I've expected. I'll test on my test site and hope to my production site soon. Thanks @DanielCiochiu , you're my hero.

**Comment by DanielCiochiu** [comment]
@dichvuhuuich Glad to hear it works. I'll check @ivan-newcom4u 's scenario.

**Comment by DanielCiochiu** [comment]
@ivan-newcom4u Your scenario doesn't seem to work neither on 2.15.1 without current changes. I think another issue should be opened.

**Comment by DanielCiochiu** [comment]
@ivan-newcom4u I have no idea why on Mautic Box the Add 5 points campaign doesn't get triggered. It seems to be a box configuration problem, because on my development environment your scenario works as expected on both branches: 2.15.1 release (with this patch applied) and on staging (also with this patch applied). Just to be sure, I added breakpoints and execution enters code containing my changes only on mautic:campaign:rebuild which is irrelevant for your scenario because your segments are fixed, not dynamic so campaign contacts are not changed.

My best guess is that this relates to cron configuration.

@escopecz Any hint on above scenario?

**Comment by ivan-newcom4u** [comment]
@DanielCiochiu thanks for testing it. I also tested it on my development environment with this patch applied but I couldn't get it working. Which commands do you run in your crons? I am running these commands:
 - mautic:segments:update
 - mautic:campaigns:update
 - mautic:campaigns:trigger

I also tried running the command "mautic:campaigns:rebuild" instead of "mautic:campaigns:update" but the campaign "add 5 points" is triggered only once.

**Comment by DanielCiochiu** [comment]
@ivan-newcom4u 

Here's what I've done:
1. Created a segment called "Add 5 points only once" which identifies a contact based on email
2. Created another segment called "Add 5 points multiple times" (no filtering because contacts will be added through a campaign)
3. Created campaign "Start adding 5 points" with source segment "Add 5 points only once" which "Adjust contact points" by increasing with 5 points immediately and then trigger action "Modify contact's segments" by adding contact to "Add 5 points multiple times" segment immediately:
	- Allow contacts to restart the campaign: No
	- Published: Yes	
4. Created campaign "Increase contact's points by 5" with source segment "Add 5 points multiple times". This campaign will:
	• trigger action "Change campaigns" -> Add contact to: This campaign (restart campaign) after 2 minutes
	• trigger action "Modify contact's segments" by removing it from "Add 5 points multiple times" and then evaluate condition "Contact field value" -> Core Email: not empty. If Yes -> trigger action "Modify contact's segments" by adding it back to "Add 5 points multiple times" immediately and then again trigger action "Adjust contact points" by adding 5 points
	- Allow contact to restart campaign: Yes
	- Publised: Yes

After configuring all above, I ran the following jobs in this order multiple times continously so the scheduled campaing restart gets triggered:
php app/console mautic:segments:update
php app/console mautic:campaigns:rebuild (it is the same job as 'php app/console mautic:campaigns:update' - update is an alias of rebuild so only one should be ran)
php app/console mautic:campaigns:trigger


What happens:
1. Contact gets added to campaign "Start adding 5 points" which will be ran only once for this campaign because it is not recurrent
2. After triggering above campaign, contact gets added to segment "Add 5 points multiple times"
3. At the second campaign rebuild, the contact will be removed and added back to segment "Add 5 points multiple times" and an action is scheduled for restarting campaign after two minutes and 5 points are summed to contact's points
4. At one of the next campaign rebuilds, scheduled event will be executed and campaign restarted
5. At the next following rebuild, flow gets back to step 3

Executed above flow on Mautic 2.15.1 with current patch and exactly in the described order and works as expected. After reading again you scenario, maybe triggering restart on the other campaign helps.

I hope it helps!

**Comment by ivan-newcom4u** [comment]
@DanielCiochiu it's not exactly the same scenario and yours is working indeed because of the restart campaign action. But thanks for the details, it actually helps. It's good to know I'll just have to update my campaigns and add a "Change campaigns" action to add the contacts to the desired campaigns and everything should be working.

**Comment by ChrisRAoW** [comment]
This fix only works for short campaigns where you remove the contact from the campaign / segment on the first rotation. This is because now (with this fix) if the campaign is getting updated, and checking for new contacts to add it simply excluding all the current memberships if the campaign can be restart. With that it re-adds all the existing memberships to the campaign, even if they are still actively in it.

I think it should only exclude the memberships that are currently actively in the campaign. 

@DanielCiochiu I created a PR on your fork. Can you check it out and maybe pull it in? Or should a create a new pull request on Mautic? No right?

**Review by johbuch — APPROVED** [review]
tested on mautibox, it worked. I was in the segment so in the campaign, I left segment was added back, then I started again the campaign

**Comment by DanielCiochiu** [comment]
@ChrisRAoW  I noticed that your PR is to the stating branch (my fork). Can you please checkout the issue-7388 branch (from my fork), apply the changes there and create another PR to the 'issue-7388' branch so after merging it my PR to mauting->staging gets automatically updated?

**Comment by ChrisRAoW** [comment]
@DanielCiochiu Nevermind, I saw later that you already applied the same in a later commit (a bit different though). So you can leave it like it is. Sorry for the inconvience

**Comment by DanielCiochiu** [comment]
@ChrisRAoW Ok. I will then close your PR from my fork.

**Comment by grinono** [comment]
When will a resolution of the above be available in production?

**Comment by escopecz** [comment]
@grinono once this PR will have 2 tests and a code review. If you can test it and write your test results here, it will greatly help to get it into the next release.

**Review by grinono — APPROVED** [review]

**Comment by npracht** [comment]
Hi @DanielCiochiu can you check if your PR is mergeable in https://github.com/mautic/mautic/tree/3.x and manage conflicts if needed?
Then we give a chance to the PR to be merged in 3.0.0. Thanks !

**Comment by dennisameling** [comment]
I decided to do an additional code review based on this comment: https://forum.mautic.org/t/contacts-not-running-through-campaign-again-although-restart-the-campaign-is-set/11561/13?u=dennisa

Can confirm that this PR fixes the issue described in #7338.

* Contact added to segment
* Contact added to campaign
* Contact removed from segment
* Contact removed from campaign
* Mail successfully sent
* Contact added to segment (2nd time)
* Contact added to campaign (2nd time)
* Contact removed from segment (2nd time)
* Contact removed from campaign (2nd time)
* Mail successfully sent (2nd time)
* Contact added to segment (3rd time)
* Contact added to campaign (3rd time)
* Contact removed from segment (3rd time)
* Contact removed from campaign (3rd time)
* Mail successfully sent (3rd time)

Going ahead and merging now

**Review by dennisameling — APPROVED** [review]

**Pull request merged**
