### PR TITLE
PHP error fixed while viewing campaigns with lower permissions

### PR DESCRIPTION
**Pull request by escopecz**
Fix of https://github.com/mautic/mautic/issues/931

Steps to replicate the error are described in the issue.

### CODE REVIEW

**Comment by alanhartless** [comment]
:+1:

**Comment by alanhartless** [comment]
@escopecz  Was there a reason this was labeled as code review? Wasn't for sure if that as by accident or if there was something we needed to look more closely at?

**Comment by alanhartless** [comment]
Closing in favor of #940 which provides the same fix.

**Comment by escopecz** [comment]
@alanhartless I wasn't sure about the `IDENTITY` if it was needed in some case or not.

**Pull request closed without merging**
