### PR TITLE
Fix bug in DateTimeHelper::setDatetime method.

### LINKED ISSUE #8666: Time show on Upcoming Events and Submit form always UTC
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version |  2.16.2 beta
| PHP version |  PHP Version 7.2.28-3+ubuntu18.04.1+deb.sury.org+1
| Browser |  Version 80.0.3987.163 (Official Build) (64-bit)

### Steps to reproduce
I. Upcoming Events
1. Go to configuration, set default timezone not UTC, example Ho Chi Minh (UTC+7)
2. Create a test contact
3. Create a test segment
4. Add test contact to test segment
5. Create a test campaign with source test segment
6. Add a action example +1 point immediately and an action with at a relative time 15' or at specific date/time
7. Go to contact and see campaign trigger and see History, trigger +1 point immediately time UTC+7 but on Upcoming Events, time always UTC.

II. Date on form
1. Create a test form Name and email
2. Embed form on a landing page
3. Submit form
4. Go to form results and see that Date Submitted always UTC 
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by anton-vlasenko**
There is a bug in the `DateTimeHelper::setDatetime` method and this PR fixes it.
Also this PR fixes issues with displaying `datetime` values in some places.

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | 
| Automated tests included? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) |
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
This PR fixes 3 bugs:
1. (9:17 PM doesn't equal 5:17 PM)
bug1

2. `Datetime` values marked with red are incorrect.
They are in UTC, but they should be converted to a local timezone.
bug2

3.
- Set frequency rules (global or for an individual contact) to 1 email/day
- Create campaign with actions to send multiple emails as "marketing" emails (rather than transactional)
- Check contact record at time 2nd email should send, observe the date added and rescheduled date in the Message Queue event.
- `Date Added` value is in the local timezone, but `Rescheduled Date` is in UTC.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. All the `datetime` values mentioned in the "Steps to reproduce" will be displayed in the local timezone.

### CODE REVIEW

**Review by florentpetitjean — DISMISSED** [review]
Tested and works in the 3 cases, Nice Job !

**Comment by Enc3phale** [comment]
Hi @anton-vlasenko , thank you for the correction.
But this add wrong date inside segment update launched by command `mautic:segment:update`.

I set my server timezone with **UTC** and my Mautic instance timezone with **Europe/Paris**.
If I make a segment with filter on a date field +2days, when I run `mautic:segment:update` date is generated with Paris timezone but for comparison with lead it's transformed by DateTimeHelper to UTC and I loose 1 day (instead of having 13 + 2, I have 13 + 1).

Issue come from `date_default_timezone_get()` that get server timezone instead of instance timezone.

I think, to fix a lot of date, we need to set date_default_timezone inside AppKernel within boot function with something like this : 
```
$localParams = $this->getLocalParams();

// set default timezone
if (isset($localParams['default_timezone'])) {
    date_default_timezone_set($localParams['default_timezone']);
}
```

What do you think of that?

**Comment by florentpetitjean** [comment]
Hello, any update on this subject ? @anton-vlasenko 
Thanks,

**Comment by anton-vlasenko** [comment]
Sorry for the delay. I'll check it today.

**Comment by anton-vlasenko** [comment]
@Enc3phale I'm sorry for the delay.

> If I make a segment with filter on a date field +2days, when I run mautic:segment:update date is generated with Paris timezone but for comparison with lead it's transformed by DateTimeHelper to UTC and I loose 1 day.

I would not modify AppKernel. It may introduce new bugs and from my tests `date_default_timezone_get` already returns correct local timezone, e.g. `Europe/Paris`.

Do you know exact place in the code where it is happening? 
In my opinion to fix this we need to convert times to the same timezone before comparison. It means we either have to convert lead's time to UTC or convert time returned by DateTimeHelper to the local timezone (e.g. `Europe/Paris`).

**Comment by Enc3phale** [comment]
@anton-vlasenko
Issue is when date come from console returned timezone is set by `date_default_timezone_set('UTC');` on **app\console l.5**
When date come from application returned timezone is set by local.php

If I put a breakpoint in **app\bundles\LeadBundle\Segment\Decorator\DecoratorFactory.php l.79** `$dateDecorator = $this->dateOptionFactory->getDateOption($contactSegmentFilterCrate);`
returned helper look like this (with my segment exemple):

date-breakpoint

And when `toLocalString` within **DateTimeHelper** is called to generate SQL, date is converted to UTC so I loose two hours from midnight, so one day.

I don't know exact place to fix that.

**Comment by anton-vlasenko** [comment]
@Enc3phale  Will it fix your issue if we remove a call to `date_default_timezone_set('UTC')` from console.php?
I'm asking because I've tried to reproduce your issue and `$this->dateOptionFactory->getDateOption($contactSegmentFilterCrate)` returns anything but DateTimeHelper.

https://github.com/mautic/mautic/blob/master/app/console#L5 looks weird to me.
It overwrites default timezone and sets it to `UTC`, but it doesn't have to do that, because according to https://www.php.net/manual/en/function.date-default-timezone-get.php `date_default_timezone_get` should return `UTC` anyway if it the default timezone is not set.
I'll ask around to see what others think about https://github.com/mautic/mautic/blob/master/app/console#L5.

**Comment by Enc3phale** [comment]
It doesn't work. If I remove the line, timezone is from my server configuration (php.ini).
I have set my php.ini timezone to `America/Chicago` and my instance to `Europe/Paris` and removed L.5 from console.
Local need to be Europe/Paris like my instance.

DateTimeHelper is inside dateDecorator->dateOptionParameters

datetime-helper

**Comment by anton-vlasenko** [comment]
I can't reproduce your issue:
1. I created 5 contacts (leads).
2. I changed `date_added` values in the `mautic_leads` table just as shown on the screenshot.
Snímek obrazovky 2019-10-16 v 0 51 00
3. I created a segment with the following date filter:
Snímek obrazovky 2019-10-16 v 0 54 31
4. I ran `php app/console mautic:segments:update` command.

5. Leads with IDs 3,4,5,6 were added to the segment. This is correct behaviour, because dates in the mautic_leads table are in UTC.

6. Then I repeated steps 3,4,5 using the code from my PR. I got the same results.
Leads with IDs 3, 4, 5 were added to the segment I created.

**Comment by florentpetitjean** [comment]
Hello Anton, 

Our issue is with relative date in the filter, if you set up a fix date, it will works but if you tried with relative value like "today", "birthday" or +1/-1 days.

Thanks,

**Comment by anton-vlasenko** [comment]
I'm able to reproduce the issue with relative date filter without using my PR.
I've created a bug report https://github.com/mautic/mautic/issues/7967
Therefore my PR has nothing to do with that bug, it just made it more `visible`.
My PR fixes bug in the DateTimeHelper::setDateTime method and therefore should be merged.
I will add https://github.com/mautic/mautic/issues/7967 to our internal bug tracker too.

**Comment by RCheesley** [comment]
@anton-vlasenko sorry another conflict to address but hopefully a minor one!

**Comment by RCheesley** [comment]
@anton-vlasenko do you think you might be able to address the conflicts so we can try to get this tested and merged in 2.16.1? Thanks!

**Comment by RCheesley** [comment]
@anton-vlasenko no problem, unfortunately you missed the boat for 2.16.1 which is released already.

**Comment by anton-vlasenko** [comment]
@RCheesley Oh, no :( Hopefully this PR will make its way into the next Mautic release.

**Comment by RCheesley** [comment]
Wondering if this is fixing the same issue as https://github.com/mautic/mautic/pull/8576 ?

**Comment by anton-vlasenko** [comment]
@RCheesley Yes, this PR fixes https://github.com/mautic/mautic/pull/8576. I've just reproduced it and I confirm that.

**Comment by RCheesley** [comment]
@anton-vlasenko thanks for checking, so presumably we can close down #8576 in favour of this PR, assuming it doesn't do anything that isn't already covered in this PR?

**Comment by anton-vlasenko** [comment]
> @anton-vlasenko thanks for checking, so presumably we can close down #8576 in favour of this PR, assuming it doesn't do anything that isn't already covered in this PR?

You are welcome.
Yes, I think we can close https://github.com/mautic/mautic/pull/8576 in favour of this PR.
This PR covers everything that https://github.com/mautic/mautic/pull/8576 does.

**Review by patrykgruszka — DISMISSED** [review]
I confirm that this PR fixes bug from #8576 and all 3 cases described above works fine for me.

**Comment by npracht** [comment]
Hello @anton-vlasenko could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback, i would very love to merge it in 3.0.1 if still relevant. Thanks !

**Comment by RCheesley** [comment]
@anton-vlasenko could you please address the conflicts and confirm if this is still required in Mautic 3.x?

**Review by dennisameling — APPROVED** [review]
Case 1 fixed in this PR:

image

Case 2 fixed:

image

Case 3 fixed (tested in https://github.com/mautic/mautic/issues/8666#issuecomment-650542501).

Thanks @anton-vlasenko!

**Review by RCheesley — APPROVED** [review]
Tested and replicated the bugs, a key factor in testing was to log out after making a change to the timezone!

Once the PR was applied all the dates used the correct timezones and the scheduled emails also! :tada:

**Comment by ttencate** [comment]
Will this fix #8309?

**Pull request merged**
