### PR TITLE
Show contact lists for Forms, Pages, and Assets

### PR DESCRIPTION
**Pull request by maxlawton**
| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | N
| Deprecations? | N

#### Description:

This adds a contact list similar to the one present in the Campaign details view; but for Forms, Pages, and Assets.

##### Programatically #####

1. Prepare environment for running Mautic functional tests (see `/.env.dist`)
2. Run PHPUnit tests for all or one of the updated controller actions:
    ```
    bin/phpunit -c app/phpunit.xml.dist --filter '/(Asset|Form|Page)DetailFunctionalTest/'
    ```

##### Manually #####

1. Create one (or more) of each component: Asset, Form, and Landing Page.
2. In a manner that can be identified as a Lead (e.g., on a remote host or in **dev** environment), access each of the components.
3. In the backend, navigate to the detail page for each component and then click the "Contacts" tab.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/6203"></a>

### CODE REVIEW

**Comment by maxlawton** [comment]
@dbhurley Could you point me at an example of the sort of automated test needed for this PR?

**Comment by npracht** [comment]
@escopecz could you help @maxlawton by showing him an example of tests to implement in this PR?

**Review by patrykgruszka — DISMISSED** [review]
Tested, works as described.

**Review by OxidoPL — DISMISSED** [review]
Code looks good and this feature is imporant for me. Thanks for that!

**Comment by RCheesley** [comment]
Bumping to 3.2 due to unresolved conflicts

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by maxlawton** [comment]
> Bumping to 3.2 due to unresolved conflicts

@RCheesley I've rebased this onto **staging** and fixed merge conflicts.

**Comment by RCheesley** [comment]
[2021-02-13 21:15:33] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT COUNT(*) AS dctrn_count FROM (SELECT DISTINCT id_10 FROM (SELECT m0_.is_published AS is_published_0, m0_.date_added AS date_added_1, m0_.created_by AS created_by_2, m0_.created_by_user AS created_by_user_3, m0_.date_modified AS date_modified_4, m0_.modified_by AS modified_by_5, m0_.modified_by_user AS modified_by_user_6, m0_.checked_out AS checked_out_7, m0_.checked_out_by AS checked_out_by_8, m0_.checked_out_by_user AS checked_out_by_user_9, m0_.id AS id_10, m0_.name AS name_11, m0_.description AS description_12, m0_.alias AS alias_13, m0_.form_attr AS form_attr_14, m0_.cached_html AS cached_html_15, m0_.post_action AS post_action_16, m0_.post_action_property AS post_action_property_17, m0_.publish_up AS publish_up_18, m0_.publish_down AS publish_down_19, m0_.template AS template_20, m0_.in_kiosk_mode AS in_kiosk_mode_21, m0_.render_style AS render_style_22, m0_.form_type AS form_type_23, m0_.no_index AS no_index_24, m0_.progressive_profiling_limit AS progressive_profiling_limit_25, (SELECT count(m1_.id) AS sclr_27 FROM mau_form_submissions m1_ WHERE m1_.form_id = m0_.id) AS sclr_26 FROM mau_forms m0_ LEFT JOIN mau_categories m2_ ON m0_.category_id = m2_.id ORDER BY m0_.name ASC) dctrn_result) dctrn_table':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'm0_.progressive_profiling_limit' in 'field list'" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 60 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT COUNT(*) AS dctrn_count FROM (SELECT DISTINCT id_10 FROM (SELECT m0_.is_published AS is_published_0, m0_.date_added AS date_added_1, m0_.created_by AS created_by_2, m0_.created_by_user AS created_by_user_3, m0_.date_modified AS date_modified_4, m0_.modified_by AS modified_by_5, m0_.modified_by_user AS modified_by_user_6, m0_.checked_out AS checked_out_7, m0_.checked_out_by AS checked_out_by_8, m0_.checked_out_by_user AS checked_out_by_user_9, m0_.id AS id_10, m0_.name AS name_11, m0_.description AS description_12, m0_.alias AS alias_13, m0_.form_attr AS form_attr_14, m0_.cached_html AS cached_html_15, m0_.post_action AS post_action_16, m0_.post_action_property AS post_action_property_17, m0_.publish_up AS publish_up_18, m0_.publish_down AS publish_down_19, m0_.template AS template_20, m0_.in_kiosk_mode AS in_kiosk_mode_21, m0_.render_style AS render_style_22, m0_.form_type AS form_type_23, m0_.no_index AS no_index_24, m0_.progressive_profiling_limit AS progressive_profiling_limit_25, (SELECT count(m1_.id) AS sclr_27 FROM mau_form_submissions m1_ WHERE m1_.form_id = m0_.id) AS sclr_26 FROM mau_forms m0_ LEFT JOIN mau_categories m2_ ON m0_.category_id = m2_.id ORDER BY m0_.name ASC) dctrn_result) dctrn_table':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'm0_.progressive_profiling_limit' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'm0_.progressive_profiling_limit' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'm0_.progressive_profiling_limit' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:75)"} []

**Comment by RCheesley** [comment]
Sorry .... naughty cat activity! 😊 😼

**Comment by RCheesley** [comment]
@maxlawton testing this on Mautibox and it works perfectly! Great new feature!

Unfortunately we are going to need to [increase the test coverage](https://github.com/mautic/mautic/pull/6203#issuecomment-724230116) before we are able to merge, can you take a look?

It seems that https://codecov.io/gh/mautic/mautic/pull/6203/diff?src=pr&el=tree#diff-YXBwL2J1bmRsZXMvRm9ybUJ1bmRsZS9Db250cm9sbGVyL0Zvcm1Db250cm9sbGVyLnBocA== this is one of the main culprits.

**Review by RCheesley — DISMISSED** [review]
Approve subject to test coverage being improved!

**Comment by maxlawton** [comment]
> @maxlawton testing this on Mautibox and it works perfectly! Great new feature!
> 
> Unfortunately we are going to need to [increase the test coverage](https://github.com/mautic/mautic/pull/6203#issuecomment-724230116) before we are able to merge, can you take a look?
> 
> It seems that https://codecov.io/gh/mautic/mautic/pull/6203/diff?src=pr&el=tree#diff-YXBwL2J1bmRsZXMvRm9ybUJ1bmRsZS9Db250cm9sbGVyL0Zvcm1Db250cm9sbGVyLnBocA== this is one of the main culprits.

@RCheesley the coverage changes are largely due to the addition of the `generateContactsGrid(...)` call in each of the affected controllers. I looked for existing test cases for that sort of controller action, but couldn't find an example sufficient to guide me in creating tests for my changes. Do you have any suggestions as to how the requested tests should be written, or where to find an example of that sort of test?

**Comment by RCheesley** [comment]
I can't myself but will ask one of the core team if they can give some pointers!

**Comment by alanhartless** [comment]
In terms of the test, I think I'd recommend a functional test for this using Symfony's crawler. Here's an example https://github.com/mautic/mautic/blob/b064842da1138876cdcb3be6a2c7b16cf9f38ad3/app/bundles/LeadBundle/Tests/Controller/LeadDetailFunctionalTest.php#L64-L73

Each affected controller can set up the test with the entity, contact and activity data using the models, entity manager, or a fixture. Then each test would use Symfony's crawler to grab the output of the view endpoints and the output tested to contain the expected contact. 

For the feature itself, what kind of scale has this been tested under? And for page hits specifically, how are visitors handled? Will it load in all visitors with blank profiles which wouldn't be very useful or does it only display identified contacts?

**Comment by maxlawton** [comment]
@alanhartless 

First, thanks for pointing out that functional test example. I was able to write tests for all three controllers using the crawler. 

> For the feature itself, what kind of scale has this been tested under?

We've been using this feature in production since it was originally developed ca. Mautic 2.14. At present our highest per-page contact count is ~400,000. The performance hit may be noticeable with our `page_hits` table containing over 5M rows, but it's certainly not as bad as we've experienced in other areas like stuff that relies on `email_stats`. The patch we're running does not contain the most recent commit, the performance impact of which could go either way as far as I can tell.

> And for page hits specifically, how are visitors handled? Will it load in all visitors with blank profiles which wouldn't be very useful or does it only display identified contacts?

Good question. There was previously no `$contactsFilter` argument passed to the `generateContactsGrid` call in the **PageController**. The grid was thus showing anonymous leads along with identified ones. My two most recent commits address that, passing a filter and testing that it works as expected.

**Review by RCheesley — DISMISSED** [review]
This works great and is a nice feature to add, however we have [three failing tests](https://github.com/mautic/mautic/pull/6203/checks?check_run_id=2591795513#step:9:70). Any chance you could take a look at them @maxlawton ?

Thanks for all your work on this to date!

**Comment by maxlawton** [comment]
@RCheesley I don't think the test failures are related to my changes. It looks like there might be something wrong with fixture loading for some other tests.

My tests are in:
- `app/bundles/AssetBundle/Tests/Controller/AssetDetailFunctionalTest.php`
- `app/bundles/FormBundle/Tests/Controller/FormDetailFunctionalTest.php`
- `app/bundles/PageBundle/Tests/Controller/PageDetailFunctionalTest.php`

The errors below are in:
- `app/bundles/LeadBundle/Tests/Controller/AjaxControllerFunctionalTest.php:59`
- `app/bundles/LeadBundle/Tests/Controller/Api/LeadApiControllerFunctionalTest.php:329`
- `app/bundles/LeadBundle/Tests/Controller/LeadControllerTest.php:161`

Looking at another recent PR with test failures, I see some similar, but not identical MySQL errors here: https://github.com/mautic/mautic/pull/9903/checks?check_run_id=2594745488 .

Error output from the failed tests on this PR:

```
> bin/phpunit -d memory_limit=1G --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

............................int(4)
int(2)
int(1)
int(3)
.................................   61 / 2194 (  2%)
.............................................................  122 / 2194 (  5%)
.............................................................  183 / 2194 (  8%)
.............................................................  244 / 2194 ( 11%)
.............................................................  305 / 2194 ( 13%)
.............................................................  366 / 2194 ( 16%)
....................................SS.......................  427 / 2194 ( 19%)
.............................................................  488 / 2194 ( 22%)
.............................................................  549 / 2194 ( 25%)
................................SS...........................  610 / 2194 ( 27%)
.............................................................  671 / 2194 ( 30%)
.............................................................  732 / 2194 ( 33%)
.............................................................  793 / 2194 ( 36%)
.............................................................  854 / 2194 ( 38%)
.............................................................  915 / 2194 ( 41%)
.............................................................  976 / 2194 ( 44%)
............................................................. 1037 / 2194 ( 47%)
.............ERROR 1064 (42000) at line 58: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_E...' at line 1
.ERROR 1064 (42000) at line 58: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_E...' at line 1
.ERROR 1064 (42000) at line 58: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_E...' at line 1
S............................................. 1098 / 2194 ( 50%)
............................................................. 1159 / 2194 ( 52%)
............................................................. 1220 / 2194 ( 55%)
............................................................. 1281 / 2194 ( 58%)
....................F....F............F...................... 1342 / 2194 ( 61%)
............................................................. 1403 / 2194 ( 63%)
............................................................. 1464 / 2194 ( 66%)
............................................................. 1525 / 2194 ( 69%)
.........................................ERROR 1064 (42000) at line 58: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_E...' at line 1
.ERROR 1064 (42000) at line 58: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_E...' at line 1
.ERROR 1064 (42000) at line 58: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_E...' at line 1
.ERROR 1064 (42000) at line 58: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_E...' at line 1
................. 1586 / 2194 ( 72%)
............................................................. 1647 / 2194 ( 75%)
............................................................. 1708 / 2194 ( 77%)
............................................................. 1769 / 2194 ( 80%)
............................................................. 1830 / 2194 ( 83%)
............................................................. 1891 / 2194 ( 86%)
............................................................. 1952 / 2194 ( 88%)
............................................................. 2013 / 2194 ( 91%)
............................................................. 2074 / 2194 ( 94%)
............................................................. 2135 / 2194 ( 97%)
...........................................................   2194 / 2194 (100%)

Time: 06:59.725, Memory: 358.00 MB

There were 3 failures:

1) Mautic\LeadBundle\Tests\Controller\AjaxControllerFunctionalTest::testToggleLeadCampaignAction
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
-Array &0 (
-    0 => Array &1 (
-        'lead_id' => '1'
-        'manually_added' => '1'
-        'manually_removed' => '0'
-    )
-)
+Array &0 ()

/home/runner/work/mautic/mautic/app/bundles/LeadBundle/Tests/Controller/AjaxControllerFunctionalTest.php:59

2) Mautic\LeadBundle\Tests\Controller\Api\LeadApiControllerFunctionalTest::testSingleNewEndpointCreateAndUpdate
Failed asserting that false is true.

/home/runner/work/mautic/mautic/app/bundles/LeadBundle/Tests/Controller/Api/LeadApiControllerFunctionalTest.php:329

3) Mautic\LeadBundle\Tests\Controller\LeadControllerTest::testContactsAreAddedToThenRemovedFromCampaignsInBatch
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
-Array &0 (
-    0 => Array &1 (
-        'lead_id' => '1'
-        'manually_added' => '1'
-        'manually_removed' => '0'
-        'date_last_exited' => null
-    )
-    1 => Array &2 (
-        'lead_id' => '2'
-        'manually_added' => '1'
-        'manually_removed' => '0'
-        'date_last_exited' => null
-    )
-    2 => Array &3 (
-        'lead_id' => '3'
-        'manually_added' => '1'
-        'manually_removed' => '0'
-        'date_last_exited' => null
-    )
-)
+Array &0 ()

/home/runner/work/mautic/mautic/app/bundles/LeadBundle/Tests/Controller/LeadControllerTest.php:161

FAILURES!
Tests: 2194, Assertions: 6374, Failures: 3, Skipped: 5.
Script bin/phpunit -d memory_limit=1G --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist handling the test event returned with error code 1
Error: Process completed with exit code 1.
```

**Comment by RCheesley** [comment]
@maxlawton sorry, something in this PR seems to be causing those tests to fail. It may not be relating to the tests you wrote, but some change in this PR that is breaking something in the other tests.

Until we get to the bottom of it, we can't consider the PR for merging.

**Comment by maxlawton** [comment]
> @maxlawton sorry, something in this PR seems to be causing those tests to fail. It may not be relating to the tests you wrote, but some change in this PR that is breaking something in the other tests.
> 
> Until we get to the bottom of it, we can't consider the PR for merging.

@RCheesley I merged latest *features* and the same error persists. The tests that are failing don't seem related to my changes, but it's the same ones as last time I updated the branch. Perhaps I broke something. I'll try to figure out what's going wrong. Apologies for the busted PR.

**Comment by RCheesley** [comment]
Yeah it looks like there are the same three tests failing:

https://github.com/mautic/mautic/pull/6203/checks?check_run_id=3079119984#step:9:111

```
1) Mautic\LeadBundle\Tests\Controller\AjaxControllerFunctionalTest::testToggleLeadCampaignAction
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
-Array &0 (
-    0 => Array &1 (
-        'lead_id' => '1'
-        'manually_added' => '1'
-        'manually_removed' => '0'
-    )
-)
+Array &0 ()

/home/runner/work/mautic/mautic/app/bundles/LeadBundle/Tests/Controller/AjaxControllerFunctionalTest.php:59

2) Mautic\LeadBundle\Tests\Controller\Api\LeadApiControllerFunctionalTest::testSingleNewEndpointCreateAndUpdate
Failed asserting that false is true.

/home/runner/work/mautic/mautic/app/bundles/LeadBundle/Tests/Controller/Api/LeadApiControllerFunctionalTest.php:329

3) Mautic\LeadBundle\Tests\Controller\LeadControllerTest::testContactsAreAddedToThenRemovedFromCampaignsInBatch
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
-Array &0 (
-    0 => Array &1 (
-        'lead_id' => '1'
-        'manually_added' => '1'
-        'manually_removed' => '0'
-        'date_last_exited' => null
-    )
-    1 => Array &2 (
-        'lead_id' => '2'
-        'manually_added' => '1'
-        'manually_removed' => '0'
-        'date_last_exited' => null
-    )
-    2 => Array &3 (
-        'lead_id' => '3'
-        'manually_added' => '1'
-        'manually_removed' => '0'
-        'date_last_exited' => null
-    )
-)
+Array &0 ()

/home/runner/work/mautic/mautic/app/bundles/LeadBundle/Tests/Controller/LeadControllerTest.php:161

```

So something is getting broken - those tests are all passing on other PR's that we've merged today.

**Comment by jos0405** [comment]
Hello @maxlawton, could you plz rebase this PR? Let's fast track it and try to merge it asap, so you don't have to rebase it again.

**Comment by escopecz** [comment]
I know I come late to the party. When we pulled community changes for M3 for our customers we found out that the company detail page has horrible experience and we had to load the chart and list of contacts asynchronously.

_Side note: @dadarya0 please push [this optimization](https://github.com/acquia/mc-cs/pull/1760) to the community._

We had to do the same optimization for segments (https://github.com/mautic/mautic/pull/11005) a while ago. What I worry is that once our customers get this feature we'll get tickets that the platform is to slow or timing out and we'll have to do the hot fixes as we had to do for the company page and load these list asynchronously. So what I'm wondering is whether we could load those asynchronously from the beginning and save some troubles. What do you think?

**Comment by maxlawton** [comment]
> Hello @maxlawton, could you plz rebase this PR? Let's fast track it and try to merge it asap, so you don't have to rebase it again.

@jos0405,
I've rebased it and updated the views/controllers to use the asynchronous loading mentioned by @escopecz. I expect some of the tests may fail as there were all kinds of unrelated things wrong with the tests when I ran locally. I'll see what the automated tasks say, but I may need some suggestions in dealing with feedback from those.

**Comment by escopecz** [comment]
@maxlawton I'm happy to help with whatever you get stuck on. Let me know.

I also like to run only the test I'm working on. You may be aware, but here's how I do it in case you are not:
`composer test -- --filter nameOfTheTestMethodHere`

**Comment by ghost** [comment]
In this state, should the tag pending-test-confirmation be removed? Actually the test at this state is not possible, or am I misunderstanding last comments?

**Comment by escopecz** [comment]
@IonutOjica you are right. I'll update the labels.

**Comment by escopecz** [comment]
@andersonjeccel please provide reason why this was closed.

**Comment by andersonjeccel** [comment]
@escopecz It's from 6 years ago and it seems no one is still working, should we keep active?

**Comment by escopecz** [comment]
@andersonjeccel I'm all for the PR list cleanup. All I wanted was to at least write a sentence about why this work was thrown away.

**Pull request closed without merging**
