### PR TITLE
[UX] Scheduling sending, availability and activation

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR addresses users confusion re. status labels.

Now we have 11 variations.

**Active**:
- Active
- Inactive
- Not started yet
- Expired on schedule

**Available**:
- Available for use
- Unavailable
- Scheduled for upcoming use
- No longer available

**Sending**:
- Sending
- Unavailable
- Scheduled for future send
- Sending period expired

---

This PR also:
- Adds a tag to indicate the type of email, dynamic content, SMS and form
- Adds an icon on dynamic contents on their list page to indicate if they're campaign based
- Improves the translation re. variantes to add a mention to A/B as "variant" only could feel out of context for some people
- Adds a tag to indicate if a landing page is preference center
- Includes logic to enable or disable scheduling fields depending on the "Available for use" toggle
- Includes dynamic labels that change as you set scheduling options to tell the user how the item will behave

https://github.com/user-attachments/assets/fce62798-7165-465c-9b1a-a3272787bc30

image

image

image

image
image
image
image

### Availability (asset as example)
When **Available for use** is **Yes**:
- The resource becomes available and can be downloaded accessing the link, including the green Available tag in its details page
- If you set an Available from date, it becomes "Not started yet" and contacts cannot download accessing the link, it'll show a blue tag
- When the Available from date comes, it becomes "Available for use" with green tag and contacts can download accessing the link again
- If you set an Unavailable from date, just defining it does nothing on the status until it comes
- When the date for Unavailable from comes, it becomes "Expired on schedule" with blue tag and the respective status message, and the download link cannot be accessed anymore

When **Available for use** is **No**:
- Contacts cannot download the asset accessing the link
- No matter what you set for Available from or Unavailable from, none has effect
- The Available from field doesn't make the asset become available and downloadable
- It'll be always "Unavailable" label

### Sending (segment email as example)
When **Available for use** is **Yes**:
- The email becomes available and can be sent, including the green Available tag in its details page (only if Start sending at is empty)
- If you set a Start sending at date, it becomes pending with the blue label "Scheduled for future send" to indicate the system is waiting for the date to come so it can start sending
- When the Start sending at date comes, it becomes "Sending" with green tag and the system starts sending emails in batches to the contacts
- If you set a Stop sending at date for the email without a Start sending at date, just defining it does nothing on the status until it comes (before the Stop sending at date it'll keep Available for use but won't send; after the Stop sending at date, it'll turn into Unavailable)
- When the date for Stop sending at comes and you defined a Start sending at date previously, it becomes expired with the blue label "Sending period expired" and stops sending emails that started on the start date

When **Available for use** is **No**:
- System users can't send emails
- No matter what you set for Start sending at date or Stop sending at, none has effect
- Scheduled (using Start and Stop sending at) emails are not sent
- The Start sending at field doesn't make the email become available
- It'll be always "Unavailable" label

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Emails > New > Select the Segment type, play with the scheduling options then Save & Close and see the tags
3. Now create a Triggered email repeating the same process
4. Create A/B variations of these emails and see tags
5. Clone these emails to set as a different translation from the first ones and check tags
6. Repeat the process for SMS, landing pages, forms
7. Open Dynamic Content > New > Select an option for "Is campaign based" then Save & Close and see the tags
8. Create another Dynamic Content, but selecting the opposite for "Is campaign based" then Save & Close and see the tags

### CODE REVIEW

**Comment by andersonjeccel** [comment]
@abhisekmazumdar in this one, I'm wondering that the issue might be 

(a) the changes I had to do in the `mautic_form_layout.html.twig` file to allow custom attributes for the widget coming from the main form, or 
(b) changing the block where the close action appear (instead of the `actions` block, the new `indexButton` block)

do you see anything in the output that could help?

**Review by jos0405 — DISMISSED** [review]
Not available:
image

Available (triggered)
image

Sending Period expired
image

Scheduled for future
image

Translation
image

**Comment by jos0405** [comment]
I did various tests, it looks really good, couldn't break it.

**Review by LeonOltmanns — COMMENTED** [review]
It seems like the creation of marketing messages got broken in this PR. When trying to create one, following error pops up:

`Twig\Error\RuntimeError
/html/app/bundles/CoreBundle/Resources/views/Helper/publishstatus_badge.html.twig:31 at
/html/vendor/twig/twig/src/Environment.php(391) : eval()'d code:62 at __TwigTemplate_e664f7ecfc8dcdc5dd98f46017bbab07 -> {closure} ( )
/html/vendor/twig/twig/src/Template.php:393 at __TwigTemplate_e664f7ecfc8dcdc5dd98f46017bbab07 -> doDisplay ( )
/html/vendor/twig/twig/src/Template.php:349 at Twig\Template -> yield ( )
/html/vendor/twig/twig/src/Template.php:364 at Twig\Template -> display ( )
/html/vendor/twig/twig/src/TemplateWrapper.php:35 at Twig\Template -> render ( )
/html/vendor/twig/twig/src/Extension/CoreExtension.php:1452 at Twig\TemplateWrapper -> render ( )
/html/vendor/twig/twig/src/Environment.php(391) : eval()'d code:160 at Twig\Extension\CoreExtension :: include ( )
/html/vendor/twig/twig/src/Template.php:437 at __TwigTemplate_3e8c399e56a8e950d5f2a8c0d63f6cee -> block_publishStatus ( )
/html/vendor/twig/twig/src/Template.php:145 at Twig\Template -> yieldBlock ( )
/html/vendor/twig/twig/src/Template.php:206 at Twig\Template -> displayBlock ( )
/html/vendor/twig/twig/src/Environment.php(391) : eval()'d code:74 at Twig\Template -> renderBlock ( )
/html/vendor/twig/twig/src/Template.php:393 at __TwigTemplate_ad4f814433d65fc31e42a8c08067829e -> doDisplay ( )
/html/vendor/twig/twig/src/Environment.php(391) : eval()'d code:58 at Twig\Template -> yield ( )
/html/vendor/twig/twig/src/Template.php:393 at __TwigTemplate_3e8c399e56a8e950d5f2a8c0d63f6cee -> doDisplay ( )
/html/vendor/twig/twig/src/Template.php:349 at Twig\Template -> yield ( )
/html/vendor/twig/twig/src/Template.php:364 at Twig\Template -> display ( )
/html/vendor/twig/twig/src/TemplateWrapper.php:35 at Twig\Template -> render ( )
/html/vendor/twig/twig/src/Environment.php:306 at Twig\TemplateWrapper -> render ( )
/html/vendor/symfony/framework-bundle/Controller/AbstractController.php:258 at Twig\Environment -> render ( )
/html/vendor/symfony/framework-bundle/Controller/AbstractController.php:266 at Symfony\Bundle\FrameworkBundle\Controller\AbstractController -> renderView ( )
/html/app/bundles/CoreBundle/Controller/CommonController.php:180 at Symfony\Bundle\FrameworkBundle\Controller\AbstractController -> render ( )
/html/app/bundles/CoreBundle/Controller/AbstractStandardFormController.php:1130 at Mautic\CoreBundle\Controller\CommonController -> delegateView ( )
/html/app/bundles/ChannelBundle/Controller/MessageController.php:94 at Mautic\CoreBundle\Controller\AbstractStandardFormController -> viewStandard ( )
/html/vendor/symfony/http-kernel/HttpKernel.php:163 at Mautic\ChannelBundle\Controller\MessageController -> viewAction ( )
/html/vendor/symfony/http-kernel/HttpKernel.php:75 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( )
/html/vendor/symfony/framework-bundle/Controller/AbstractController.php:156 at Symfony\Component\HttpKernel\HttpKernel -> handle ( )
/html/app/bundles/CoreBundle/Controller/CommonController.php:325 at Symfony\Bundle\FrameworkBundle\Controller\AbstractController -> forward ( )
/html/app/bundles/CoreBundle/Controller/CommonController.php:257 at Mautic\CoreBundle\Controller\CommonController -> ajaxAction ( )
/html/app/bundles/CoreBundle/Controller/AbstractStandardFormController.php:981 at Mautic\CoreBundle\Controller\CommonController -> postActionRedirect ( )
/html/app/bundles/ChannelBundle/Controller/MessageController.php:86 at Mautic\CoreBundle\Controller\AbstractStandardFormController -> newStandard ( )
/html/vendor/symfony/http-kernel/HttpKernel.php:163 at Mautic\ChannelBundle\Controller\MessageController -> newAction ( )
/html/vendor/symfony/http-kernel/HttpKernel.php:75 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( )
/html/vendor/symfony/framework-bundle/Controller/AbstractController.php:156 at Symfony\Component\HttpKernel\HttpKernel -> handle ( )
/html/app/bundles/CoreBundle/Controller/CommonController.php:415 at Symfony\Bundle\FrameworkBundle\Controller\AbstractController -> forward ( )
/html/vendor/symfony/http-kernel/HttpKernel.php:163 at Mautic\CoreBundle\Controller\CommonController -> executeAction ( )
/html/vendor/symfony/http-kernel/HttpKernel.php:75 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( )
/html/vendor/symfony/http-kernel/Kernel.php:202 at Symfony\Component\HttpKernel\HttpKernel -> handle ( )
/html/app/AppKernel.php:109 at Symfony\Component\HttpKernel\Kernel -> handle ( )
/html/app/middlewares/CORSMiddleware.php:76 at AppKernel -> handle ( )
/html/app/middlewares/HSTSMiddleware.php:39 at Mautic\Middleware\CORSMiddleware -> handle ( )
/html/app/middlewares/CatchExceptionMiddleware.php:28 at Mautic\Middleware\HSTSMiddleware -> handle ( )
/html/app/middlewares/Dev/IpRestrictMiddleware.php:52 at Mautic\Middleware\CatchExceptionMiddleware -> handle ( )
/html/app/middlewares/VersionCheckMiddleware.php:58 at Mautic\Middleware\Dev\IpRestrictMiddleware -> handle ( )
/html/app/middlewares/TrustMiddleware.php:42 at Mautic\Middleware\VersionCheckMiddleware -> handle ( )
/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23 at Mautic\Middleware\TrustMiddleware -> handle ( )
/html/index.php:19 at Stack\StackedHttpKernel -> handle ( )`

How to Reproduce:

1. Open the PR
2. Go to Marketing Messages
3. Give it a name and click Save
4. See Error

**Review by luke-42 — APPROVED** [review]
Works as expected for Segment Mailings (not tested for Marketing Msgs)

Unavailable
image


Available for use
image


Sending
image

No longer available
image

Sending period expired
image


Scheduled for future send
image

**Comment by andersonjeccel** [comment]
@abhisekmazumdar the errors for phpunit are new

**Comment by abhisekmazumdar** [comment]
I tested the changes, and overall, the form on the page was causing the test to fail. Everything looks good to me now.

**Review by abhisekmazumdar — APPROVED** [review]

**Review by LeonOltmanns — APPROVED** [review]
Tested after the fixes and now Marketing Messages work again - thanks for the fix and the great feature overall! :)

**Review by jos0405 — DISMISSED** [review]
Tested the changes, they all look good also for Marketing Messages

**Pull request merged**
