### PR TITLE
[UX] Email theme: Creative

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR adds a new email theme.

screencapture-127-0-0-1-32772-email-preview-36-2024-10-15-10_49_12

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Emails
3. Click to create New
4. Find and select the Attract theme
5. Open the builder and see
6. Click to save then Preview
7. Look if the preview looks like in the builder

### CODE REVIEW

**Comment by RaffyRod** [comment]
@andersonjeccel can I test this one too?

**Review by shinde-rahul — APPROVED** [review]
Code LGTM!!!

**Comment by RCheesley** [comment]
@RaffyRod you don't need to ask to review PRs, just jump in if they need testing! 

Please be sure when you leave your review to follow these instructions: https://contribute.mautic.org/contributing-to-mautic/tester#leaving-your-review that way your review is actually counted and to be listed as a reviewer, rather than just leaving a comment in the stream which counts as a 'conversation' but not a formal review. 

If you also want to get a credit for Hacktoberfest, remember to edit this file: https://github.com/mautic/hacktoberfest-no-code/blob/main/2024.md and add your details at the bottom. One edit per PR you review, because Hacktoberfest requires that there is a PR made in order for it to count as a contribution.

**Review by RaffyRod — APPROVED** [review]
Tested by using the following steps:
**Test Review:**  
1. Open this PR on Gitpod or clone it locally for testing.  
2. Navigate to the Emails section and click "Create New".  
3. Find and select the "Attract" theme.  
4. Open the builder, click save, then preview the email.  
5. Ensure the preview matches the builder layout as shown in the image.
And worked as expected for me..

**Review by MojisolaaaO — APPROVED** [review]
Test Passed. The template looks the same in the builder and preview.

**Pull request merged**
