### PR TITLE
Mail status count display

### PR DESCRIPTION
**Pull request by ravikumarps88**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | No
| New feature? | No (Minor enhancement)
| Related user documentation PR URL | https://mautic.org/docs/en/campaigns/index.html
| Issues addressed (#s or URLs) | No
| BC breaks? | No
| Deprecations? | No

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Showing mail send count along with the percentage value

#### Steps to test this PR:
1. After sending campaign mails, check-on the Campaign view page
2. Please check the "Action" tab, there we can see the actual count of mail send
55 hubs by 55 weeks

### CODE REVIEW

**Comment by escopecz** [comment]
@ravikumarps88 thanks for this PR! It has some merge conflicts. Please merge the latest staging branch into your branch, resolve the conflicts and push again.

It's better to start new branches from the latest staging branch to avoid these issues.

**Comment by dongilbert** [comment]
This works as expected, but I'm not sure about the formatting. @alanhartless @dbhurley What do you think here? (see screenshot)

screen shot 2017-06-15 at 10 11 55 am

**Comment by mqueme** [comment]
Maybe something like this?
screen shot 2017-06-16 at 14 00 21

**Comment by mqueme** [comment]
@dongilbert I happened to save the changes I made for the GUI to look as the screenshot, so I just uploaded the changes. if you can test, and confirm, that would be great :)

**Comment by dongilbert** [comment]
This works as described. @matishaladiwala Is this UI ok to add without further changes? (see attached)
screen shot 2017-06-26 at 2 40 18 pm

**Comment by dongilbert** [comment]
We're going to push this out of the 2.9 release, but we want to update the UI still a bit more, reordering the buttons and clarifying what they mean.

**Comment by dbhurley** [comment]
Agreed, need to have text next to success and fail labels just like completed and pending so that it can be readable.

**Comment by alanhartless** [comment]
Please resubmit this addressing the feedback if you'd like this to be reconsidered for merge. Thank!

**Pull request closed without merging**
