### PR TITLE
Avoid using empty expression + applyTagFilter moved

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This refactoring is needed to enable https://github.com/mautic/mautic/pull/12396#issuecomment-1567192589

The applyTagFilter was moved from the Event to the Builder because it uses Connection so it makes more sense to have it in the builder.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Test a report with multiple conditions connected with AND and OR conditions. Especially with and without a tag based filter. It should show the data you expect.

### CODE REVIEW

**Review by mabumusa1 — DISMISSED** [review]
Let's merge, looks good

Thanks for your help

**Comment by escopecz** [comment]
@mabumusa1 I found an error with the filter logic with OR conditions. Fixed in https://github.com/mautic/mautic/pull/12403/commits/05d19de83e1fd1e44917dedb47337a8aac383358

Also got an error when changing a tag based filter to a text filter that the filter expected array but got string. I added some conditions to ensure that the `CollectionType` will only get an array value to prevent this error. Please re-review

**Review by mabumusa1 — CHANGES_REQUESTED** [review]
- [X] Report without tags work 

- [ ] Report with tags fail

```
[2023-05-30 07:43:18] mautic.CRITICAL: Uncaught PHP Exception TypeError: "array_key_exists(): Argument #2 ($array) must be of type array, null given" at /var/www/html/app/bundles/ReportBundle/Form/Type/FilterSelectorType.php line 67 {"exception":"[object] (TypeError(code: 0): array_key_exists(): Argument #2 ($array) must be of type array, null given at /var/www/html/app/bundles/ReportBundle/Form/Type/FilterSelectorType.php:67)"} {"hostname":"mautic-web","pid":1987}
```

**Review by mabumusa1 — APPROVED** [review]
Tested again, it works now with tags and without tags. 

Thanks @escopecz

**Pull request merged**
