### PR TITLE
Webhook fail notification by e-mail

### PR DESCRIPTION
**Pull request by hluchas**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Y
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) |
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Mautic user  needs to be notified about failing webhook by e-mail.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create webhook targeting to not existing url connected to edit contact event.
2. Temporarily decrease value `webhook_disable_limit` to `1` in `app/bundles/WebhookBundle/Config/config.php`
3. Edit and save contact.
4. Webhook is unpublished, notification send, but no e-mail received.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Publish webhook.
3. Same as reproduction steps, but you will receive e-mail.
4. Test e-mail link redirection on Mautic app side

### CODE REVIEW

**Comment by npracht** [comment]
Hi @hluchas can you have a look at Travis ?

**Comment by hluchas** [comment]
Thank you @npracht . Fixed!

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by hluchas** [comment]
Created PR against 3.x https://github.com/mautic/mautic/pull/8782

**Pull request closed without merging**
