### PR TITLE
Devices report

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ N ]
| New feature/enhancement? (use the a.x branch)      | [ Y ]
| Deprecations?                          | [ N ]
| BC breaks? (use the c.x branch)        | [ N ]
| Automated tests included?              | [ Y ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR adds new Devices source to the reports.
obraz

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create new Devices report
3. Add all or some devices columns to report
4. Save and see that the data are shown and are correct.
5. Try to filter and group by some devices columns to ensure these features work.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11422"></a>

### CODE REVIEW

**Review by escopecz — COMMENTED** [review]
Thanks for this great feature! The code looks great. I can see that many lines are not covered by tests. The coverage report is somewhat off as it mentions files you haven't touched in this PR. Can you please improve the tests? Since reports are heavily database related I'd suggest to build functional test(s) to confirm the new report works correctly.

**Comment by patrykgruszka** [comment]
@escopecz I have added functional tests, the coverage should now be much better.

**Review by escopecz — APPROVED** [review]
Thank you! The code and tests look good 👍

**Review by kuzmany — COMMENTED** [review]
Works for me 👍

**Pull request merged**
