### PR TITLE
Timeline event for queued messages

### PR DESCRIPTION
**Pull request by mqueme**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR adds a new timeline event in the contact details to view queued messages and to be able to view them cancel them if the message is no longer relevant.

#### Steps to test this PR:
1. Apply this PR go to the contact's timeline and see the new message queue timeline event with details of when it was  first created, number of attempts, date that it will be rescheduled if it failed, and the ability to cancel them from the contact's timeline.

### CODE REVIEW

**Comment by mqueme** [comment]
It should be when refreshing the page, but I can add a javascript... I didn't at first because of translations.

**Comment by Maxell92** [comment]
@mqueme Will you add a JS? Should we wait with testing?
+ This PR has conflicts, could you rebase it on actual staging?

**Comment by alanhartless** [comment]
I'll fix the translation so we can merge this. As a FYI, any translation added to javascript.ini is available to Javascript via the Mautic.translate() JS method

**Comment by alanhartless** [comment]
Also for any table that lists the raw channel from the DB, we should use the ChannelListHelper to translate.

**Pull request merged**
