### PR TITLE
Fix dependency issue

### PR DESCRIPTION
**Pull request by tejasync**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✅ 
| New feature/enhancement? (use the a.x branch)      | ❌ 
| Deprecations?                          | ❌ 
| BC breaks? (use the c.x branch)        | ❌ 
| Automated tests included?              | ✅  
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR fixes the dependency issues within the functional tests.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Execute LoadAssetData fixture

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11085"></a>

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
The code make sense 👍

**Comment by renatocron** [comment]
I tested this on my install, 4.2.2, the `/s/assets` is all working, even without app/bundles/AssetBundle/DataFixtures/ORM/LoadAssetData.php as I think this is used only during tests

What else could be tested to approve this merge, @escopecz ?

**Comment by escopecz** [comment]
Correct. I checked why the Acquia team was fixing this and it was used in a test of a custom plugin. I don't see it used anywhere in the core code. So I'm merging this as code review and a quick test that assets can be loaded is good enough.

**Comment by escopecz** [comment]
I rebased it to 4.2. Will merge once the CI is green.

**Review by escopecz — APPROVED** [review]

**Comment by escopecz** [comment]
GH Actions aren't picking up the jobs and the time is running out. I'll try close and open.

**Pull request merged**
