### PR TITLE
TPROD-319 - LeadBundle - Custom Fields Templates

### PR DESCRIPTION
**Pull request by JoshuaEstes**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Check every aspect of Custom Fields including creating, updating and deleting all types, adding the content on the contact profile, etc

### CODE REVIEW

**Review by daniellord32 — CHANGES_REQUESTED** [review]
Add a custom field - You cannot save a custom field. There is no actions on the top right hand side
image

cannot edit a custom field throws a 500 error.
`[2022-12-16 10:29:53] mautic.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "lookupTemplate" does not exist." at /var/www/html/app/bundles/LeadBundle/Views/Field/form.html.twig line 74 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"lookupTemplate\" does not exist. at /var/www/html/app/bundles/LeadBundle/Views/Field/form.html.twig:74)"} {"hostname":"mautic-web","pid":2426}
`

**Comment by JoshuaEstes** [comment]
> cannot edit a custom field throws a 500 error. `[2022-12-16 10:29:53] mautic.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "lookupTemplate" does not exist." at /var/www/html/app/bundles/LeadBundle/Views/Field/form.html.twig line 74 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"lookupTemplate\" does not exist. at /var/www/html/app/bundles/LeadBundle/Views/Field/form.html.twig:74)"} {"hostname":"mautic-web","pid":2426} `

Twig Error has been resolved.

---

> Add a custom field - You cannot save a custom field. There is no actions on the top right hand side image

I'm at a loss as to why this is happening.

**Comment by daniellord32** [comment]
i'll review this evening

**Comment by daniellord32** [comment]
> > cannot edit a custom field throws a 500 error. `[2022-12-16 10:29:53] mautic.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "lookupTemplate" does not exist." at /var/www/html/app/bundles/LeadBundle/Views/Field/form.html.twig line 74 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"lookupTemplate\" does not exist. at /var/www/html/app/bundles/LeadBundle/Views/Field/form.html.twig:74)"} {"hostname":"mautic-web","pid":2426} `
> 
> Twig Error has been resolved.

Confirmed this is fixed!

**Comment by RCheesley** [comment]
I have the same issue as @daniellord32 in that the save/cancel buttons are missing so I can't actually save a field.

Seems that maybe part of the template needed is missing @JoshuaEstes ?

Also please check the PHP8 failure on the tests!

screenshot-8080-joshuaestes-mautic-alqi835378d ws-eu81 gitpod io-2023 01 10-14_13_57

**Comment by JoshuaEstes** [comment]
@RCheesley @daniellord32 I'm at a loss as to why the buttons are not showing up. I've tried a few things but I'm unable to figure out the root cause of this. I've referenced other controllers/templates where the buttons are showing up, yet here it doesn't seem to work correctly.

Anyone have any ideas or suggestions?

**Comment by RCheesley** [comment]
@escopecz could you take a look?

**Review by daniellord32 — DISMISSED** [review]
- [x] Create for owner
- [ x create for company
- [x] edit
- [x] delete
- [x] clone
- [x] Previous issue where buttons are not available

All tests passed previous issue is resolved

**Review by mabumusa1 — DISMISSED** [review]
I tested the same tests @daniellord32 did, all of them worked as expected

Thanks @JoshuaEstes for this PR

**Comment by RCheesley** [comment]
@JoshuaEstes could you resolve the conflict on this PR then we can get it merged.

**Pull request merged**
