### PR TITLE
Fix special characters in form condition value

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

Noticed If parent select box use special characters in value, compare function does not work properly for conditions. 

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create from with selectbox and value `čé+äà>&"`
3. Then make conditional field with condition for value in `čé+äà>&"`
4. Check the form and submit
5. See like your children field is not save to result properly because it's skipped
6. After PR should work properly

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11093"></a>

### CODE REVIEW

**Review by volha-pivavarchyk — DISMISSED** [review]
Children field is saved to result properly now.

Form:
image
Result:
image

**Comment by volha-pivavarchyk** [comment]
One more thing. This is just information.

This case works well:
image

In this case, the child will be missed:
image
image
image

**Comment by kuzmany** [comment]
@volha-pivavarchyk I think it's not related to this PR and probably your value after cleaning is empty, this is reason why is not there.

**Comment by volha-pivavarchyk** [comment]
@kuzmany I absolutely agree that it has nothing to do with this RP. It's just information.

**Review by jos0405 — DISMISSED** [review]
Works as described. I also tested multi select, also works:
image

**Pull request merged**
