### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by martinkouba**
bcmath is needed for php-amqplib

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. 
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by npracht** [comment]
Hi @martinkouba could you share a bit more of information. We're not sure to be aware of what is **bcmath** and if it is really mandatory or only mandatory for your specific configuration.

Thanks a lot for your contribution.

**Comment by martinkouba** [comment]
Hi,

I was using a dockerized php-fpm Version 7.1 and had to do this to meet the requirements

Best
Martin

**Comment by npracht** [comment]
Hi @martinkouba !
Thanks for your answer. I understand you need it, but now you're sharing it with the community, it would be very appreciated that you explain us why is it for, and how to use it.
There is a PR template to use when you create a PR, if you could complete it: description, how to test, etc.

Thanks

**Comment by rskuipers** [comment]
@npracht I ran into this issue as well. When trying to install your composer dependencies without having the bcmath PHP extension you get this:

```
/app # composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for php-amqplib/php-amqplib v2.7.2 -> satisfiable by php-amqplib/php-amqplib[v2.7.2].
    - php-amqplib/php-amqplib v2.7.2 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
  Problem 2
    - php-amqplib/php-amqplib v2.7.2 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - php-amqplib/rabbitmq-bundle v1.14.2 requires php-amqplib/php-amqplib ^2.6 -> satisfiable by php-amqplib/php-amqplib[v2.7.2].
    - Installation request for php-amqplib/rabbitmq-bundle v1.14.2 -> satisfiable by php-amqplib/rabbitmq-bundle[v1.14.2].

  To enable extensions, verify that they are enabled in your .ini files:
    - 
    - /usr/local/etc/php/conf.d/docker-php-ext-imap.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

```

So apparently the `php-amqplib/php-amqplib` package required the bcmath PHP extension. I would've been helped personally if this was indeed mentioned in the README as this PR tries to resolve.

:+1: from me

**Comment by alanhartless** [comment]
I'm going to push back on this one. It's required only when you're using rabbitmq which 99% will not be.  You can use `composer install --ignore-platform-reqs` to get around the PHP requirement.

**Comment by martinkouba** [comment]
Interesting. This is just about mentioning something in the documentation. How about mentioning that you will need php-amqplib when using rabbitmq?

**Pull request closed without merging**
