### PR TITLE
Change ajax call on keyup instead of enter key integration

### PR DESCRIPTION
**Pull request by dadarya0**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | No
| Automated tests included? | No
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Change search request on key up instead of enter key.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Go To - Plugins -> Salesforce -> Lead Field Mapping (Configure salesforce if not exists )
use  for configure salesforce.
2. In Filter user need to press "Enter" to filter field.
3. Switch to "Lead Field Mapping" tab
4. Start typing in "Filter Integration fields"
5. Type word with space Ex. "Last Name" or "Clean S".
6. The fields are available but would not display fields.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Go To - Plugins -> Salesforce -> Lead Field Mapping 
3. Field should be filter on type keyword only.
4. Switch to "Lead Field Mapping" tab
5. Start typing in "Filter Integration fields"
6. Type word with space Ex. "Last Name" or "Clean S".
7. If fields are available then should be display.

#### Other areas of Mautic that may be affected by the change:
1. 
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by RCheesley** [comment]
@dadarya0 looks like there was a problem with some of the commits in this PR which did not have an address associated hence the failing test - if it is easy to fix can you take a look? If not we can manually mark it as CLA Signed.

**Comment by dadarya0** [comment]
> @dadarya0 looks like there was a problem with some of the commits in this PR which did not have an address associated hence the failing test - if it is easy to fix can you take a look? If not we can manually mark it as CLA Signed.

@RCheesley I have tried but not able to fix CLA Signed issue.

**Review by kuzmany — DISMISSED** [review]
This work as expected. 
Good improvements.
👍

**Comment by RCheesley** [comment]
@dadarya0 has signed the CLA so this one is good to merge. It just shows that there was a git config issue with their commits. cc @npracht @dennisameling @jos0405

**Comment by RCheesley** [comment]
I bumped into https://github.com/mautic/mautic/issues/10601 when trying to test this, so might need someone who already has Salesforce set up.

**Comment by RCheesley** [comment]
This will need to be rebased for 4.x @dadarya0 and there are a couple of conflicts to address.

**Comment by kuzmany** [comment]
@dadarya0 are you able to rebase to 4.x?

**Comment by aarohiprasad** [comment]
Closing in favour of https://github.com/mautic/mautic/pull/13312

**Pull request closed without merging**
