### PR TITLE
Fix popup ABSOLUTE_URL  in campaigns

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
This fix generate absolute url to popup If you triggering it in campaign as actiona

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Just code review

### CODE REVIEW

**Comment by npracht** [comment]
Closed in favour of #9519

**Comment by kuzmany** [comment]
@npracht it's similar issue, but not same. Reopen

**Review by npracht — DISMISSED** [review]
👍

**Review by escopecz — DISMISSED** [review]
The code change make sense 👍

**Pull request merged**
