### PR TITLE
Index_dev.php removed.

### PR DESCRIPTION
**Pull request by lenonleite**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Hey @lenonleite appreciate this PR is closed but just wanted to let you know, it seems that the user you're committing with is different to the one that is making the PR (lenon v lenonleite). The CLA has to be signed by all contributors so that's why it's flagging up the issue.

Make sure that the email you're signing your commits with is on your GitHub profile and is verified, that might be the missing link.

If it's not that it might be that we need to have the username lenon on record as well (if that is your profile, of course!), in which case please just sign the form again on Docusign but with that username.

**Comment by lenonleite** [comment]
@RCheesley Yes, I talked to Abu Musa yesterday and he showed me the right way and I filled out the document as well.

Thank you. =)

**Comment by RCheesley** [comment]
Awesome! PS, love the avatar!

**Comment by lenonleite** [comment]
hahah thank you!!

**Pull request closed without merging**
