### PR TITLE
Extendable/pluginable IP lookup services

### LINKED ISSUE #743: Ability to add custom geo-IP databases
See https://www.mautic.org/community/index.php/612-using-my-ip-database

The geo IP database uses are hardcoded into Mautic (see https://github.com/mautic/mautic/blob/1.1.3/app/bundles/CoreBundle/Entity/IpAddress.php#L75 and https://github.com/mautic/mautic/blob/1.1.3/app/bundles/CoreBundle/Form/Type/ConfigType.php#L584 for example) which makes it difficult to integrate custom providers.

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**
This PR adds support for extendable/pluginable IP lookup services.  It resolves #743.

**Testing**
After applying the PR, test that IP lookups are performed for the services you have access to.  At a minimum, test the free ones.  You will have to access the site from a non-local environment to get around  local IP addresses.  Or you can hack in an IP in MauticFactory's getIpAddress to force an IP.  Make sure you wipe the ip_details column in the ip_addresses table or else the lookup won't take place.

### CODE REVIEW

**Comment by escopecz** [comment]
- Telize :heavy_check_mark: 
- Freegeoip.net :heavy_check_mark: 
- IPInfoDB :heavy_check_mark: 
- Geobytes :hand: 
```
500 Internal Server Error - Notice: Undefined index: city
```
```
app/bundles/CoreBundle/IpLookup/GeobytesIpLookup.php (line #30):
app/bundles/CoreBundle/IpLookup/GeobytesIpLookup.php (line #30): at Symfony\Component\Debug\ErrorHandler -> handleError ( '8', 'Undefined index: city', 'app/bundles/CoreBundle/IpLookup/GeobytesIpLookup.php', '30', array('http_response_header' => array('HTTP/1.1 200 OK', 'Date: Fri, 02 Oct 2015 11:45:34 GMT', 'Server: Apache/2.4.7 (Ubuntu)', 'Last-Modified: Fri, 02 Oct 2015 11:37:54 GMT', 'Accept-Ranges: bytes', 'Content-Length: 100953', 'Vary: Cookie', 'X-Pingback: http://www.geobytes.com/xmlrpc.php', 'Connection: close', 'Content-Type: text/html; charset=UTF-8'), 'tags' => array('viewport' => 'width=device-width', 'generator' => 'WordPress 4.3.1')) )
app/bundles/CoreBundle/Factory/MauticFactory.php (line #671): at Mautic\CoreBundle\IpLookup\GeobytesIpLookup -> getData ( )
app/bundles/LeadBundle/Model/LeadModel.php (line #494): at Mautic\CoreBundle\Factory\MauticFactory -> getIpAddress ( )
app/bundles/AssetBundle/EventListener/BuilderSubscriber.php (line #78): at Mautic\LeadBundle\Model\LeadModel -> getCurrentLead ( )
at Mautic\AssetBundle\EventListener\BuilderSubscriber -> onPageDisplay ( object(PageDisplayEvent), 'mautic.page_on_display', object(TraceableEventDispatcher) )
vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/Debug/WrappedListener.php (line #61): at call_user_func ( array(object(BuilderSubscriber), 'onPageDisplay'), object(PageDisplayEvent), 'mautic.page_on_display', object(TraceableEventDispatcher) )
at Symfony\Component\EventDispatcher\Debug\WrappedListener -> __invoke ( object(PageDisplayEvent), 'mautic.page_on_display', object(ContainerAwareEventDispatcher) )
app/cache/dev/classes.php (line #2171): at call_user_func ( object(WrappedListener), object(PageDisplayEvent), 'mautic.page_on_display', object(ContainerAwareEventDispatcher) )
app/cache/dev/classes.php (line #2104): at Symfony\Component\EventDispatcher\EventDispatcher -> doDispatch ( array(object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'mautic.page_on_display', object(PageDisplayEvent) )
app/cache/dev/classes.php (line #2265): at Symfony\Component\EventDispatcher\EventDispatcher -> dispatch ( 'mautic.page_on_display', object(PageDisplayEvent) )
vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php (line #124): at Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher -> dispatch ( 'mautic.page_on_display', object(PageDisplayEvent) )
app/bundles/PageBundle/Controller/PublicController.php (line #259): at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher -> dispatch ( 'mautic.page_on_display', object(PageDisplayEvent) )
at Mautic\PageBundle\Controller\PublicController -> indexAction ( 'test-user-page', object(Request) )
app/bootstrap.php.cache (line #3051): at call_user_func_array ( array(object(PublicController), 'indexAction'), array('test-user-page', object(Request)) )
app/bootstrap.php.cache (line #3013): at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '1' )
app/bootstrap.php.cache (line #3162): at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '1', true )
app/bootstrap.php.cache (line #2403): at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel -> handle ( object(Request), '1', true )
app/AppKernel.php (line #110): at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), '1', true )
index_dev.php (line #61): at AppKernel -> handle ( object(Request) )
```
- GeoIPs :hand: 
```
500 Internal Server Error - Case mismatch between loaded and declared class names: Mautic\CoreBundle\IpLookup\GeoipsIpLookup vs Mautic\CoreBundle\IpLookup\GeoIpsIpLookup
```
```
vendor/symfony/debug/Symfony/Component/Debug/DebugClassLoader.php (line #177):
at Symfony\Component\Debug\DebugClassLoader -> loadClass ( 'Mautic\CoreBundle\IpLookup\GeoipsIpLookup' )
app/bundles/CoreBundle/Factory/MauticFactory.php (line #668): at spl_autoload_call ( 'Mautic\CoreBundle\IpLookup\GeoipsIpLookup' )
app/bundles/LeadBundle/Model/LeadModel.php (line #494): at Mautic\CoreBundle\Factory\MauticFactory -> getIpAddress ( )
app/bundles/AssetBundle/EventListener/BuilderSubscriber.php (line #78): at Mautic\LeadBundle\Model\LeadModel -> getCurrentLead ( )
at Mautic\AssetBundle\EventListener\BuilderSubscriber -> onPageDisplay ( object(PageDisplayEvent), 'mautic.page_on_display', object(TraceableEventDispatcher) )
vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/Debug/WrappedListener.php (line #61): at call_user_func ( array(object(BuilderSubscriber), 'onPageDisplay'), object(PageDisplayEvent), 'mautic.page_on_display', object(TraceableEventDispatcher) )
at Symfony\Component\EventDispatcher\Debug\WrappedListener -> __invoke ( object(PageDisplayEvent), 'mautic.page_on_display', object(ContainerAwareEventDispatcher) )
app/cache/dev/classes.php (line #2171): at call_user_func ( object(WrappedListener), object(PageDisplayEvent), 'mautic.page_on_display', object(ContainerAwareEventDispatcher) )
app/cache/dev/classes.php (line #2104): at Symfony\Component\EventDispatcher\EventDispatcher -> doDispatch ( array(object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'mautic.page_on_display', object(PageDisplayEvent) )
app/cache/dev/classes.php (line #2265): at Symfony\Component\EventDispatcher\EventDispatcher -> dispatch ( 'mautic.page_on_display', object(PageDisplayEvent) )
vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php (line #124): at Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher -> dispatch ( 'mautic.page_on_display', object(PageDisplayEvent) )
app/bundles/PageBundle/Controller/PublicController.php (line #259): at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher -> dispatch ( 'mautic.page_on_display', object(PageDisplayEvent) )
at Mautic\PageBundle\Controller\PublicController -> indexAction ( 'test-user-page', object(Request) )
app/bootstrap.php.cache (line #3051): at call_user_func_array ( array(object(PublicController), 'indexAction'), array('test-user-page', object(Request)) )
app/bootstrap.php.cache (line #3013): at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '1' )
app/bootstrap.php.cache (line #3162): at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '1', true )
app/bootstrap.php.cache (line #2403): at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel -> handle ( object(Request), '1', true )
app/AppKernel.php (line #110): at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), '1', true )
index_dev.php (line #61): at AppKernel -> handle ( object(Request) )
```
- MaxMind - country geolocation :hand:
```
500 Internal Server Error - Attempted to load class "AbstractMaxmindLookup" from namespace "Mautic\CoreBundle\IpLookup". Did you forget a "use" statement for another namespace? 

app/bundles/CoreBundle/IpLookup/MaxmindCountryIpLookup.php (line #16):
```
- MaxMind - Geo2 Precision :hand:
```
500 Internal Server Error - Attempted to load class "AbstractMaxmindLookup" from namespace "Mautic\CoreBundle\IpLookup". Did you forget a "use" statement for another namespace?

app/bundles/CoreBundle/IpLookup/MaxmindPrecisionIpLookup.php (line #16):
```
- MaxMind - Insights :hand:
```
500 Internal Server Error - Attempted to load class "AbstractMaxmindLookup" from namespace "Mautic\CoreBundle\IpLookup". Did you forget a "use" statement for another namespace? 

app/bundles/CoreBundle/IpLookup/MaxmindOmniIpLookup.php (line #16):
```

**Comment by alanhartless** [comment]
Thanks @escopecz.  Fixed them. ;-)

**Comment by escopecz** [comment]
Yep, all IP lookup services works for me now. :+1:

**Comment by healthstatus** [comment]
I download a monthly file from https://www.ip2location.com/ and then use the module at https://www.ip2location.com/developers/php to access the file.  This is much faster since it is local and I am not dependant on a service to always be running.  Any way to add this into the mix?  They have example files, but if you need a file for testing I can help with that.

**Comment by Woeler** [comment]
Is there documentation somewhere as to how to use mautic with a non-core supported ip lookup?

**Pull request merged**
