### PR TITLE
Upgraded Rector to minimum 0.11.54 and phpstan to 0.12.99

### PR DESCRIPTION
**Pull request by rohitpavaskar**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [n ]
| New feature/enhancement? (use the a.x branch)      | [ y]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [n ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

The PR upgrade Rector to version to be able to use option `Option::APPLY_AUTO_IMPORT_NAMES_ON_CHANGED_FILES_ONLY `added in [0.11.54](https://github.com/rectorphp/rector/releases/tag/0.11.54)
Useful for refactor for Symfony 5

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11136"></a>

### CODE REVIEW

**Comment by rohitpavaskar** [comment]
Hi @escopecz ,
We can see this PR is failing now after upgrading PHPSTAN version.
I can see all those are failing with same reason. 
The solution for it is https://github.com/phpstan/phpstan/issues/6762#issuecomment-1061692282. As there are 168 errors what do you suggest? Should we regenerate baseline as it is showing only after PHPSTAN upgrade and no code is changed, or we should fix each file.
Thanks

**Comment by escopecz** [comment]
@rohitpavaskar isn't this duplicate of https://github.com/mautic/mautic/pull/11131?

**Comment by kuzmany** [comment]
@escopecz omg, I didn't notice yours PR.  This requests was from me to help us refactor some things

**Comment by escopecz** [comment]
Yea, I did it last Friday, so it's fresh :)

**Pull request closed without merging**
