### PR TITLE
cookie with samesite=none require secure 

### LINKED ISSUE #9019: SameSite cookie warning causing cross-site tracking problems in Mautic 3
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I'm unable to track users with a fresh Mautic install because of the following errors:
(index):1 A cookie associated with a cross-site resource at http://domain.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

It looks like Mautic isn't correctly setting this SameSite attribute when creating cross-site cookies. Therefore Chrome and other browsers are blocking them. 

| Q   | A
| --- | ---
| Mautic version | 3.0.1
| PHP version | 7.3
| Browser | Chrome/Safari/Firefox (all latest versions)

### Steps to reproduce
I've created a form with a name, last name and email. Then I created a simple DWC element and I'm trying to display this info I got from the form into this DWC widget. When tracking was working, I was seeing the name, lastname and email displayed. Now I don't see that working anymore, plus I get all these warnings about cookies being blocked. I don't have CORS enable or blocking the site and I don't have any adblockers. I've tried different configurations but nothing seems to be working here.
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #9019

#### Description:

Cookies set from different domain should send SameSite=None attribute. New standard require also use it on https with param secure.

The PR prevent

> This Set-Cookie was blocked because it had the "SameSite=None" attribute but did not have the "Secure" attribute, which is required in order to use "SameSite=None".

From documentation https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

> If SameSite=None is set, the cookie Secure attribute must also be set (or the cookie will be blocked).

The same we can expect also in chromium:

https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. This works just on https 
3. You should check after PR all using cookies parts works properly - tracking code, form submission, focus...

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/9743"></a>

### CODE REVIEW

**Review by patrykgruszka — DISMISSED** [review]
This PR also fixes issue with the `cookie_secure` config parameter. In my case even when it is set to `true` in the local.php file, it was always somehow transformed to string "1" when injected to the CookieHelper constructor. In result the samesite=none was never set, because the code is executed only when that parameter is strictly true. Setting `cookie_secure` to `true` in  `app/bundles/CoreBundle/Config/config.php` fixed this issue.

**Comment by RCheesley** [comment]
Hi there,

Thank you for your contribution!

As we have released Mautic 4 now, the 3.x version is out of active support and therefore will not receive any further bug fixes or features.

If this PR is still relevant to Mautic 4, please either 

- Rebase on the 4.0 branch (for bug fixes) or the 4.x branch (for features and enhancements), or 
- Close this PR and make a fresh one on the correct branch.

If it is no longer relevant to Mautic 4, please close the PR.

Thanks in advance!

**Comment by jd6-37** [comment]
Excuse my ignorance about the process of PRs, etc., but is this change scheduled to be made in a future update? I installed Mautic 4.0.1 and was getting the console warning in firefox about cookies will be blocked soon because of "misuse" and how samesite=none require secure. I went ahead and made the changes in commit 349e5c8ec153de9394a45a433acc1926670ddd58, and the warning went away. I'm assuming this will all get overwritten the next time I updated, which is fine, but is the Mautic team planning on implementing this change? Maybe I'm missing something or don't understand the severity but cookies being blocked seems pretty critical.

By the way, thanks for all the hard work that the Mautic team and all the contributors do. I love the software.

**Comment by RCheesley** [comment]
Hey @j26w thanks for letting us know that this PR worked for you! It was pending test confirmation which you've now given, so I think it should be good to go. We may just want to have someone do a code review first, @mohit-rocks or @mabumusa1 would you have time to take a look?

**Comment by RCheesley** [comment]
@all-contributors please add @j26w for userTesting

**Comment by jd6-37** [comment]
> Hey @j26w thanks for letting us know that this PR worked for you! It was pending test confirmation which you've now given, so I think it should be good to go. We may just want to have someone do a code review first, @mohit-rocks or @mabumusa1 would you have time to take a look?

Oh, cool! Well, I'm happy to help. :) I've tested with iOS 14 Safari, Chromium, and Firefox so far (Mac OS 11.5.2). I haven't seen any console errors, and the page hits tracking seems to be working fine. If there's anything specific I can do or test (or there's a more formal way to perform and report), please let me know.

**Comment by RCheesley** [comment]
> (or there's a more formal way to perform and report)

There is a built-in approval system on GitHub - if you go to Files at the top of the pull request, and then at the top right there should be an option to start a review - you can use that for user testing but also for code review if you're a developer.  That's generally what we use for determining if something has been reviewed in the community and it gives a 'green tick' of approval :)

Unfortunately the PR doesn't have a whole lot of test instructions -  it's something we are trying to nudge our developers towards (providing detailed test instructions) for this reason! :) I would maybe rummage around in the cookies and make sure they are getting set correctly. Might also be worth checking that focus items are working as expected (appearing when they should, and getting dismissed when they should etc).

**Review by mabumusa1 — DISMISSED** [review]
I did a code review and tested the PR on a server with nginx, the cookies are set as secured with the origin none. I think this PR is good to go

**Comment by RCheesley** [comment]
@kuzmany could you possibly rebase this on the 4.0 branch so we can merge it into an earlier release than 4.1?

**Pull request merged**
