### PR TITLE
Video hits reports

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Added new Video hits reports. 
Useful If your're using with tracked videos (https://github.com/mautic/documentation/pull/206)

#### Steps to test this PR:
1.  Apply PR
2. Go to reports and see new Videos > Video hits
3. Create reports and tests

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by javjim-mautic** [comment]
The reports are showing a lot of entries for each view. As it is updating the time the video its being seen.

its missing a group by GUID, and also should use the last value of time_watched to show how much time the user is watching the video.


Also if the video has a form it will keep adding new hits, (I believe it will fix whenever the group by guid is done)

**Comment by kuzmany** [comment]
@javjim-mautic I didn't notice that, but added groupBy and improved some stuff

My report seems ok:

image

**Comment by kuzmany** [comment]
@javjim-mautic  any answer?

**Comment by dbhurley** [comment]
Label: Ready to Test

**Comment by dbhurley** [comment]
Label: Pending Feedback

**Comment by kuzmany** [comment]
@dbhurley got It :) sorry for spam :)

**Comment by javjim-mautic** [comment]
Works properly

**Comment by Maxell92** [comment]
Does not work for me:

screen shot 2018-03-27 at 14 29 13

I tried it with this settings:

screen shot 2018-03-27 at 14 30 54

Error is same when I select all columns or when I try same report like @kuzmany:

screen shot 2018-03-27 at 14 33 46

I deleted cache and checked that I have a few rows in `video_hits` table

**Comment by kuzmany** [comment]
Label: Pending feedback

**Comment by kuzmany** [comment]
Label: WIP

**Comment by kuzmany** [comment]
@Maxell92 Fixed. You url_title column didn't exist in video_hits table.
Now work properly. Tested

**Pull request merged**
