### PR TITLE
Turkey Regions Update

### PR DESCRIPTION
**Pull request by ramazansancar**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | -
| Automated tests included?              | no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2.

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for making the PR @ramazansancar - please can you sign the contributors agreement linked above?

When I reference this list: https://en.wikipedia.org/wiki/Provinces_of_Turkey I noticed that some seem to be missing from our list, would you see a reason to not have them listed?

**Review by IrisAmrein — APPROVED** [review]
I checked the list in contacts and companies and for me everything was displayed correctly and all the regions from the wiki were included.

Disclaimer: This is my first PR review - if this was already tested, I'm sorry if I didn't understand it correctly :) Just let me know how else I can help :)

**Comment by RCheesley** [comment]
Thank you for doing the test @IrisAmrein - that's great! 

@ramazansancar there was some open feedback on this and we do need you to sign the contributors agreement before we can consider the PR for merging. Can you take a look please? We will also need to rebase as this is on an older branch, shout if you need any help with that!

**Comment by RCheesley** [comment]
@all-contributors please add @IrisAmrein for Usertesting

**Comment by ramazansancar** [comment]
> Thank you for doing the test @IrisAmrein - that's great! 
> 
> @ramazansancar there was some open feedback on this and we do need you to sign the contributors agreement before we can consider the PR for merging. Can you take a look please? We will also need to rebase as this is on an older branch, shout if you need any help with that!

Contributors agreement accepted.

**Comment by RCheesley** [comment]
@cla-bot check

Thanks @ramazansancar that is fab!

It was some time ago that I checked against the list on Wikipedia, did you have any reason to leave some of them out (I am not so familiar with the regions in Turkey myself!) or should we include them all?

Also, we will need to make a [migration](https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#step-6-migrations-needed) so that people's databases are updated to use the new values rather than be blank, do you need any help with that? Just let us know, would be great to get this merged!

**Comment by ramazansancar** [comment]
> @cla-bot check
> 
> Thanks @ramazansancar that is fab!
> 
> It was some time ago that I checked against the list on Wikipedia, did you have any reason to leave some of them out (I am not so familiar with the regions in Turkey myself!) or should we include them all?
> 
> Also, we will need to make a [migration](https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#step-6-migrations-needed) so that people's databases are updated to use the new values rather than be blank, do you need any help with that? Just let us know, would be great to get this merged!

I have edited according to the list you wrote.  There are 81 provinces in total.  I will check and PR as soon as possible.

**Comment by ramazansancar** [comment]
I'm waiting for the merge. Thank you 🤓

@IrisAmrein @RCheesley @npracht

**Comment by RCheesley** [comment]
Thanks for updating the PR, but now we are quite some time on so this will need to be rebased on the 4.4 branch (or just re-created on that branch) to be merged.

> Also, we will need to make a [migration](https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#step-6-migrations-needed) so that people's databases are updated to use the new values rather than be blank, do you need any help with that? Just let us know, would be great to get this merged!

The migration will also need to be added - do you need some help with that?

**Comment by ramazansancar** [comment]
> Thanks for updating the PR, but now we are quite some time on so this will need to be rebased on the 4.4 branch (or just re-created on that branch) to be merged.
> 
> > Also, we will need to make a [migration](https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#step-6-migrations-needed) so that people's databases are updated to use the new values rather than be blank, do you need any help with that? Just let us know, would be great to get this merged!
> 
> The migration will also need to be added - do you need some help with that?

I have completed the required update. Can you check?

**Comment by ramazansancar** [comment]
> > Thanks for updating the PR, but now we are quite some time on so this will need to be rebased on the 4.4 branch (or just re-created on that branch) to be merged.
> > > Also, we will need to make a [migration](https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#step-6-migrations-needed) so that people's databases are updated to use the new values rather than be blank, do you need any help with that? Just let us know, would be great to get this merged!
> > 
> > 
> > The migration will also need to be added - do you need some help with that?
> 
> I have completed the required update. Can you check?

Since there were too many conflicts, I updated it back to 4.0. Opening a new pr will be faster.

**Comment by RCheesley** [comment]
> Opening a new pr will be faster.

Yes that's fine,  please do it on the 4.4 branch and then make another one on the 5.x branch.  That way we can make sure this change makes it into both the 4 and 5 releases.  Thanks!

**Comment by ramazansancar** [comment]
> > Opening a new pr will be faster.
> 
> Yes that's fine, please do it on the 4.4 branch and then make another one on the 5.x branch. That way we can make sure this change makes it into both the 4 and 5 releases. Thanks!

I will make corrections and forward them when I am available. Thanks

**Pull request closed without merging**
