### PR TITLE
Fix Dynamic Content form script load

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
JS is not load for forms in dynamic content. Then conditional fields does not work. This PR fixed it

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create dynamic content with form with conditional field
3. Test dynamic content
4. See like conditional field does not work 
5. After PR should work properly

### CODE REVIEW

**Review by volha-pivavarchyk — COMMENTED** [review]
Doesn't work for me. I tried to test on gitpod and in the local env and got the same result.

@kuzmany  Perhaps my way of testing is wrong: 1. create a form -> 2. create a DWC and add the form -> 3. create a new landing page and add the dwc -> 4. create an email and add pagelink -> 5. send the email -> 6. copy the link -> 7. open the link in the incognito mode

image

image

**Comment by kuzmany** [comment]
@volha-pivavarchyk there is an issue with saving the cache of the form. If you re-save the form, then It will work. 
It's regression after twig template convert I think

**Review by volha-pivavarchyk — APPROVED** [review]
@kuzmany Thanks! You are right. Works well after rebuilding cache.

image

**Review by escopecz — APPROVED** [review]
The code change looks OK 👍

**Pull request merged**
