### PR TITLE
Form table new columns

### PR DESCRIPTION
**Pull request by alfredoct96**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | features
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | N/A

#### Description:

Added three new columns to form table:

* created at
* modified at
* created by

Changed default order to decreasing modified at

### Before
formsbefore

### After
formsafter

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create two or more forms
3. Check existence of new columns
4. Check default order

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/9686"></a>

### CODE REVIEW

**Comment by dennisameling** [comment]
Hi @alfredoct96! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since we don't have access to your branch, could you please click "Update branch" at the bottom of this PR? If that doesn't work, you can also run `git merge upstream/features` locally. Thanks in advance!

image

**Comment by alfredoct96** [comment]
> Hi @alfredoct96! Thanks for your PR  we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since we don't have access to your branch, could you please click "Update branch" at the bottom of this PR? If that doesn't work, you can also run `git merge upstream/features` locally. Thanks in advance!
> 
> image

Done @dennisameling

**Comment by Victorybrown** [comment]
@fakela I'm getting an error whenever I try to load the PR

**Comment by fakela** [comment]
> @fakela I'm getting an error whenever I try to load the PR

@RCheesley I have tried to load the PR as well and I'm getting an error. It seems the Mautibox has not be updated to M4 or maybe some other reason.

**Comment by fakela** [comment]
> > @fakela I'm getting an error whenever I try to load the PR
> 
> @RCheesley I have tried to load the PR as well and I'm getting an error. It seems the Mautibox has not be updated to M4 or maybe some other reason.

@RCheesley @dennisameling  Please this is a blocker as anyone wanting to contribute to the documentation wants to load up the PR and get screenshots when needed

**Review by mabumusa1 — CHANGES_REQUESTED** [review]
Thanks, @alfredoct96, please rebase this PR. I think it is good to be merged in the next version. When you rebase please tag me I will approve the review and make this PR ready to commit

I checked the PR, it works as expected. 

image

**Comment by alfredoct96** [comment]
> Thanks, @alfredoct96, please rebase this PR. I think it is good to be merged in the next version. When you rebase please tag me I will approve the review and make this PR ready to commit
> 
> I checked the PR, it works as expected.
> 
> image

Hi @mabumusa1, i did the rebase!

**Review by mabumusa1 — APPROVED** [review]
I tested this PR, it works as expected 

Thanks @alfredoct96  for this PR

**Comment by RCheesley** [comment]
@all-contributors please add @alfredoct96 for code

**Pull request merged**
