### PR TITLE
New blank theme

### PR DESCRIPTION
**Pull request by moskoweb**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Y
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

Trying to think of always having the best, I developed a responsive theme, using Open Sans font for good reading, and with HTML clean.

### CODE REVIEW

**Review by kuzmany — DISMISSED** [review]
I checked code and also apply pull request on my enviroment. 
New blank theme looks better and modern.

**Review by kuzmany — COMMENTED** [review]
This happend If I used {recombee=1} , my custom tag.
Affter click on Apply button

image

**Comment by kuzmany** [comment]
@moskoweb 
I like the way for Microsoft/Outlook condition for increase compatibility. 
Then we should find way how to setup Froala editor to work with it.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Review by RCheesley — APPROVED** [review]
Nice, thanks for making this PR! Confirmed that it is working responsively and much nicer than the old blank template!

I ran it through https://www.htmlemailcheck.com/ which had a couple of suggestions but they were warnings rather than errors, so think we're good to go if we get another 👍

**Review by kuzmany — APPROVED** [review]
Looks good. Thanks 👍

**Pull request merged**
