### PR TITLE
Add error message to new/update contact

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
We can't save contact profile, because some of the fields was mandatory. And didn't see context in form, looks like profile was saved correctly. 
This PR added error message, If some fields return error.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create custom field and set it as required
2. Edit contact, save and see form, looks like profile was update, but not

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat all steps
3. See error message in right corner

image

### CODE REVIEW

**Review by Strubbel94 — DISMISSED** [review]
This PR works as anticipated. ✔
No bugs encountered!

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebased

**Review by RCheesley — DISMISSED** [review]
Tested without the patch and while the field itself highlights as being required, there's no visual popup and if that field is a few scrolls down the page you can easily miss it.

The PR adds a nice popup as below, notifying the user that a field has not been completed which is mandatory. Simple but useful improvement, thanks @kuzmany !

screenshot-local mautic3-2020 08 15-13_54_04

**Comment by RCheesley** [comment]
@kuzmany another one needing to improve test coverage :)

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by kuzmany** [comment]
@RCheesley @dennisameling I do not have idea how to write  unit tests here, it's controller with a lot of the code, not services

**Comment by kuzmany** [comment]
Unit tests added

**Review by npracht — APPROVED** [review]
👍🏽 works great and now increase code coverage

**Pull request merged**
