### PR TITLE
Fix 191 characters for created lead fields

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for features or enhancements / 3.2 for bug fixes 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
In Mautic 3 we change length for indexed varchar columns to 191 https://github.com/mautic/mautic/pull/8349 
But If we create fields,  the column was created with 255 length.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create new contact text field 
3. Check database if column in leads table has 191 length

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/9460"></a>

### CODE REVIEW

**Comment by dennisameling** [comment]
Hi @kuzmany! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since this PR has conflicts now, could you please do a `git merge upstream/features` locally to resolve the conflicts? Thanks in advance!

**Comment by kuzmany** [comment]
Close favor to additional PR added soon

**Review by jos0405 — DISMISSED** [review]
Works as described. The new fields have lenght of 191.

image

**Comment by jos0405** [comment]
This still exists in 4.2.1 btw:
image

**Review by volha-pivavarchyk — DISMISSED** [review]
Works as described
image

Before this PR
image

**Comment by escopecz** [comment]
This PR is related to https://github.com/mautic/mautic/pull/10770 and will cause conflicts for it. Just a note for myself.

**Pull request merged**
