### PR TITLE
Fix issue #10675 - respect 'Reply to Contact'

### LINKED ISSUE #10675: Send form results does not respect the "Reply to contact" setting
### Mautic Version

4.1.0 (4.0.0 does not have this issue)

### PHP version

7.4.20

### What browsers are you seeing the problem on?

Safari

### What happened?

If we have a form with a **Send form results** action and we set **Reply to contact** to **Yes**, it is no longer sending the e-mail with a reply-to header matching the e-mail field.

Instead it send from the global reply to, and if we try to reply it from our mail client will send to noreply@ourcompany.com instead of the originators email

I believe this could possibly be related to #10471 or #9812 as they seem to be in the same area of development.

### How can we reproduce this issue?

All info above

### Relevant log output

Do not think it is relevant but for the completeness this appeared in the log when an incoming message arrive
```shell
[2021-12-09 08:22:27] mautic.NOTICE: PHP Notice - Trying to access array offset on value of type bool - in file /var/www/mautic/plugins/MauticFocusBundle/Include/lessc.inc.php - at line 719 {"args":[],"orderedValues":[],"keywordValues":[],"assignedValues":[],"i":0,"last":false} []
[2021-12-09 08:22:27] mautic.NOTICE: PHP Notice - Trying to access array offset on value of type bool - in file /var/www/mautic/plugins/MauticFocusBundle/Include/lessc.inc.php - at line 719 {"args":[],"orderedValues":[],"keywordValues":[],"assignedValues":[],"i":0,"last":false} []
[2021-12-09 08:22:27] mautic.NOTICE: PHP Notice - Trying to access array offset on value of type bool - in file /var/www/mautic/plugins/MauticFocusBundle/Include/lessc.inc.php - at line 719 {"args":[],"orderedValues":[],"keywordValues":[],"assignedValues":[],"i":0,"last":false} []
[2021-12-09 08:22:27] mautic.NOTICE: PHP Notice - Trying to access array offset on value of type bool - in file /var/www/mautic/plugins/MauticFocusBundle/Include/lessc.inc.php - at line 719 {"args":[],"orderedValues":[],"keywordValues":[],"assignedValues":[],"i":0,"last":false} []
[2021-12-09 08:22:27] mautic.NOTICE: PHP Notice - Trying to access array offset on value of type bool - in file /var/www/mautic/plugins/MauticFocusBundle/Include/lessc.inc.php - at line 719 {"args":[],"orderedValues":[],"keywordValues":[],"assignedValues":[],"i":0,"last":false} []
[2021-12-09 08:22:27] mautic.NOTICE: PHP Notice - Trying to access array offset on value of type bool - in file /var/www/mautic/plugins/MauticFocusBundle/Include/lessc.inc.php - at line 719 {"args":[],"orderedValues":[],"keywordValues":[],"assignedValues":[],"i":0,"last":false} []
[2021-12-09 08:22:27] mautic.NOTICE: PHP Notice - Trying to access array offset on value of type bool - in file /var/www/mautic/plugins/MauticFocusBundle/Include/lessc.inc.php - at line 719 {"args":[],"orderedValues":[],"keywordValues":[],"assignedValues":[],"i":0,"last":false} []
[2021-12-09 08:22:27] mautic.NOTICE: PHP Notice - Trying to access array offset on value of type bool - in file /var/www/mautic/plugins/MauticFocusBundle/Include/lessc.inc.php - at line 719 {"args":[],"orderedValues":[],"keywordValues":[],"assignedValues":[],"i":0,"last":false} []
[2021-12-09 08:22:27] mautic.NOTICE: PHP Notice - Trying to access array offset on value of type bool - in file /var/www/mautic/plugins/MauticFocusBundle/Include/lessc.inc.php - at line 719 {"args":[],"orderedValues":[],"keywordValues":[],"assignedValues":[],"i":0,"last":false} []
[2021-12-09 08:22:27] mautic.NOTICE: PHP Notice - Trying to access array offset on value of type bool - in file /var/www/mautic/plugins/MauticFocusBundle/Include/lessc.inc.php - at line 719 {"args":[],"orderedValues":[],"keywordValues":[],"assignedValues":[],"i":0,"last":false} []
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by J-Light**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [X]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | 
| Related developer documentation PR URL 
| Issue(s) addressed                     | Fixes #10675 

#### Description:
Fixes bug that was introduced in the Send form results action and with Reply to contact set to true.

Added check to see if reply-to is set and only set if empty.

#### Steps to test this PR:

1. Set system-wide reply-to value.
1. Create From with Send form results action.
1. Set Reply to contact set to false.
1. Submit form - verify that reply-to is system-wide setting.
1. Edit from Step 2 and set Reply to contact set to true.
1. Submit form - verify that reply-to is Lead email.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10773"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

Thanks for the PR @J-Light - and for signing the CLA!

**Review by kuzmany — DISMISSED** [review]
Looks good from my view.
I did tests and works as expected. 
It should break nothing.

**Comment by kuzmany** [comment]
@J-Light can you rebase it to against  branch 4.x? Then we can go to 4.2 release

**Comment by J-Light** [comment]
@kuzmany  rebased.

**Comment by J-Light** [comment]
@kuzmany looks like I made a mistake in rebase.

Reset the branch and force push clean rebased branch. Hopefully its okay.

**Review by kuzmany — APPROVED** [review]

**Review by RCheesley — APPROVED** [review]
Reproduced the bug, the replyto address was incorrect when the form was set to reply to contact:
MailHog

After applying the PR, the correct email address is used:

MailHog (1)

**Comment by RCheesley** [comment]
@all-contributors please add @J-Light for code

**Pull request merged**
