### PR TITLE
Fix miscellaneous tag related issue

### PR DESCRIPTION
**Pull request by dadarya0**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | Yes
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | Yes 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Fix following tag related issues :-
1. Removed description box from tag add/edit/list/detail page
2. Save and Close button doesn't work

> 1. Go to tags
> 2. Add New
> 3. Enter value 1234 save and close
> 4. Add new
> 5. Enter value 1234 save and close

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
4. Tag add/edit/detail should work properly

### CODE REVIEW

**Review by kuzmany — CHANGES_REQUESTED** [review]
The PR https://github.com/mautic/mautic/pull/10799 add description field. 
This PR remove it. Why?

**Comment by dadarya0** [comment]
> The PR #10799 add description field. This PR remove it. Why?

Description does not make sense in tags, Also we can add tag from add/edit contact form there is also we are accepting on tag name not description So we have removed description field from tag.

**Comment by dadarya0** [comment]
> The PR #10799 add description field. This PR remove it. Why?

Description does not make sense in tags, Also we can add tag from add/edit contact form there is also we are accepting on tag name not description So we have removed description field from tag.

**Comment by kuzmany** [comment]
@dadarya0 it make sense. 

> From: https://github.com/mautic/mautic/pull/10799 This PR adds summary and description on Tag form so the marketers can describe more precisely what given tag represents.

You can for example let other users know what is purpose of certain tag. 

@RCheesley @escopecz  any opinion?

**Comment by RCheesley** [comment]
This is useful for marketers - as mentioned, to add information about what a tag is used for. It means that a marketer can get a bit of context when they are for example reviewing their use of tags.

Indeed you can create a tag without adding a description, just like you can quick-add a contact without filling out the profile. I don't see those as valid reasons for removing the field.

**Comment by escopecz** [comment]
The description field was removed because it currently does not work. It's disabled and I can see many JS errors on the tag form page. So I guess removing it wouldn't be a BC break as I think it never worked.

**Comment by kuzmany** [comment]
@escopecz what do you mean?

 > it currently does not work

I think it works properly. It just add description in the tag list to tag.
But If you decide remove it, I am not gonna argue, just dev (https://github.com/mautic/mautic/pull/10799) add it for some reason.

**Comment by escopecz** [comment]
Aha, I see. You can fill in the description when you create the tag but you cannot edit it. I guess that's why we decided it's broken and rather removed it as the product dpt did not see a value in it.

**Comment by mabumusa1** [comment]
@dadarya0 may you please rebase this PR and fix the conflicts.

**Comment by mabumusa1** [comment]
@dadarya0 there are failing tests, please fix them to test

**Comment by tejasync** [comment]
We decided to revert the removal of tag description, closing this PR.

**Pull request closed without merging**
