### PR TITLE
Prevent special chars in multi select

### PR DESCRIPTION
**Pull request by Enc3phale**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | Y
| Related user documentation PR URL | N
| Related developer documentation PR URL | N
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/6356
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
It is possible to insert special chars in the `Value` field of multi select.
But special chars cause problems when used.
Constraints was added to prevent this.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a custom field with `Select - Multiple` type
2. Add one value `it doesn't`
3. No error

#### Steps to test this PR:
1. Apply PR
2. Add one value `it doesn't`
3. Now it's not possible to validate form

### CODE REVIEW

**Review by npracht — APPROVED** [review]
UI is great when creating the custom field !! 👏

**Comment by heathdutton** [comment]
This works mostly as described. There is edge case it doesn't cover (which could be solved as a follow-up PR). If the user is creating a new custom field also selects the invalid option as the "Default value" and clicks apply the field values disappear and the validation does not show up.

Even with that minor issue this PR has good value added.
https://i.imgur.com/7BxISOV.png
https://i.imgur.com/nXBwtun.png

**Comment by npracht** [comment]
@heathdutton let me check that with @Enc3phale and we try to update tomorrow lastest ;)

**Comment by Enc3phale** [comment]
@heathdutton edge case is now fixed

**Review by escopecz — APPROVED** [review]
It works well. Thanks! 👍

**Comment by alanhartless** [comment]
To be honest, I don't care for this and think it should be reverted. 

The option value specification is "cdata" which means pretty much anything should be allowed.

https://www.w3.org/TR/html401/interact/forms.html#h-17.6
```
OPTION Attribute definitions

selected [CI]
When set, this boolean attribute specifies that this option is pre-selected.
value = cdata [CS]
This attribute specifies the initial value of the control. If this attribute is not set, the initial value is set to the contents of the OPTION element.
label = text [CS]
This attribute allows authors to specify a shorter label for an option than the content of the OPTION element. When specified, user agents should use the value of this attribute rather than the content of the OPTION element as the option label.
```

The "rules" of cdata: https://www.w3.org/TR/html401/types.html#type-cdata
```
CDATA is a sequence of characters from the document character set and may include character entities. User agents should interpret attribute values as follows:
Replace character entities with characters,
Ignore line feeds,
Replace each carriage return or tab with a single space.
```

**Comment by alanhartless** [comment]
This is way too restrictive.

**Comment by alanhartless** [comment]
@escopecz .... I just read the original issue. This is your own doing! Haha.

**Comment by alanhartless** [comment]
Looking back at the original issue, I think we need to fix the validation rather than restricting what's allowed in the value. Or, just completely revert this and require the person creating the multi-select field to use html encoded versions of special characters in values so that it does match the cleaned version from the form submit. I think that's less restrictive.

**Pull request merged**
