### PR TITLE
Segment delegate decorator event

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [N]
| New feature/enhancement? (use the a.x branch)      | [Y]
| Deprecations?                          | [N]
| BC breaks? (use the c.x branch)        | [N]
| Automated tests included?              | [Y] 
| Related user documentation PR URL      | /
| Related developer documentation PR URL | /
| Issue(s) addressed                     | /

#### Description:

This PR adds new event that plugins can use to decorator is delegated segment filters. It allows segment filters to be based on objects other than lead and company. This is needed to support the Custom Objects plugin.

#### Steps to test this PR:

Just make sure the segment filters work the same way as before. There should be no change to the UI or behavior.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10890"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
@npracht @kuzmany this is another requirement for the custom objects plugin

**Review by kuzmany — DISMISSED** [review]
Looks good 👍

**Comment by RCheesley** [comment]
When testing this I reviewed all the sample data segments, and segment ID 32 throws an error after editing and saving with this PR applied:

```
In AbstractMySQLDriver.php line 98:
                                                                                                                                                                                                                         
  An exception occurred while executing 'SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM (SELECT DISTINCT l.id as leadIdPrimary, par4i.id as par4i_id, par4j.lead_id AS par4  
  j_lead_id FROM leads l LEFT JOIN companies_leads par46 ON par46.lead_id = l.id LEFT JOIN (SELECT l.id, par4a.id as par4a_id, par4f.id as par4f_id FROM leads l LEFT JOIN (SELECT l.id FROM leads l WHERE l.id IN (SEL  
  ECT par49.lead_id FROM lead_lists_leads par49 WHERE (par49.leadlist_id = 4) AND ((par49.manually_added = 1) OR (par49.manually_removed = ''))))  par4a ON par4a.id = l.id LEFT JOIN (SELECT l.id FROM leads l LEFT JO  
  IN lead_lists_leads par4d ON l.id = par4d.lead_id and par4d.leadlist_id = 8 and (par4d.manually_removed = 1) WHERE ((l.country = ?) AND (par4d.lead_id IS NULL)) OR (l.id IN (SELECT par4e.lead_id FROM lead_lists_le  
  ads par4e WHERE (par4e.leadlist_id = 8) AND ((par4e.manually_added = 1) OR (par4e.manually_removed = '')))))  par4f ON par4f.id = l.id LEFT JOIN lead_lists_leads par4g ON l.id = par4g.lead_id and par4g.leadlist_id  
   = 21 and (par4g.manually_removed = 1) WHERE (((par4a.id IS NOT NULL) OR (par4f.id IS NOT NULL)) AND (par4g.lead_id IS NULL)) OR (l.id IN (SELECT par4h.lead_id FROM lead_lists_leads par4h WHERE (par4h.leadlist_id   
  = 21) AND ((par4h.manually_added = 1) OR (par4h.manually_removed = '')))))  par4i ON par4i.id = l.id LEFT JOIN lead_lists_leads par4j ON par4j.lead_id = l.id and (par4j.leadlist_id = 32) LEFT JOIN companies par45   
  ON par45.id = par46.company_id WHERE (par45.companyindustry IN ()) AND (par4i.id IS NULL) AND (par4j.lead_id IS NULL)) sss' with params ["United States"]:                                                             
                                                                                                                                                                                                                         
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')) AND (par4i.id IS   
  NULL) AND (par4j.lead_id IS NULL)) sss' at line 1                                                                                                                                                                      
                                                                                                                                                                                                                         

In Exception.php line 18:
                                                                                                                                                                                                                         
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')) AND (par4i.id IS   
  NULL) AND (par4j.lead_id IS NULL)) sss' at line 1                                                                                                                                                                      
                                                                                                                                                                                                                         

In PDOStatement.php line 112:
                                                                                                                                                                                                                         
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')) AND (par4i.id IS   
  NULL) AND (par4j.lead_id IS NULL)) sss' at line 1    
```                                                                                                                                                                  
I think that this is an error with the sample data though, as the industry field is set to 'including' but there is nothing in that field. Sharing anyway because I should not have been able to save it without something in the field, I think?

I am also seeing this error in the logs when editing segments (in this case with United States set as the country on the filter):

```
[2022-02-25 11:02:58] mautic.CRITICAL: Uncaught PHP Exception ErrorException: "PHP Notice - unserialize(): Error at offset 6282974 of 6282976 bytes" at /var/www/html/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php line 126 {"exception":"[object] (ErrorException(code: 0): PHP Notice - unserialize(): Error at offset 6282974 of 6282976 bytes at /var/www/html/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php:126)
[stacktrace]
#0 [internal function]: Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler->handleError(8, 'PHP Notice - un...', '/var/www/html/v...', 126, Array)
#1 /var/www/html/vendor/symfony/http-kernel/Profiler/FileProfilerStorage.php(126): unserialize('a:9:{s:5:\"token...')
#2 /var/www/html/vendor/symfony/http-kernel/Profiler/Profiler.php(87): Symfony\\Component\\HttpKernel\\Profiler\\FileProfilerStorage->read('1bcb8d')
#3 /var/www/html/vendor/symfony/web-profiler-bundle/Controller/ProfilerController.php(153): Symfony\\Component\\HttpKernel\\Profiler\\Profiler->loadProfile('1bcb8d')
#4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(158): Symfony\\Bundle\\WebProfilerBundle\\Controller\\ProfilerController->toolbarAction(Object(Symfony\\Component\\HttpFoundation\\Request), '1bcb8d')
#5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#6 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#7 /var/www/html/app/AppKernel.php(115): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#8 /var/www/html/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#9 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#10 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(61): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 /var/www/html/app/middlewares/VersionCheckMiddleware.php(67): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/www/html/app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#15 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#16 {main}
"} 
```

**Comment by jos0405** [comment]
I'm not sure if it's connected to the error above.
But If I choose segment membership, then the options won't show:

image

**Comment by jos0405** [comment]
Any filter actually:
https://www.loom.com/share/c0832f683b2d4b3ca7dec4ad07c91489

**Comment by RCheesley** [comment]
@jos0405 we are seeing that with composer installations who have not regenerated assets after installation. That might possibly be the source of the problem you're seeing. Try regenerating the assets?

**Comment by escopecz** [comment]
@RCheesley I cannot find anything causing the errors you reported in this PR. Would you mind testing the same scenario on 4.x branch to rule out the same problem is already in Mautic and not introduced by this PR?

**Comment by kuzmany** [comment]
@RCheesley I see in your query `par45.companyindustry IN ()` what cause error in query execution. I think it's not related to this PR but to your sample data

**Review by kuzmany — APPROVED** [review]

**Review by RCheesley — APPROVED** [review]
I have re-tested the PR with sample data and all seems to be well with editing, creating and building segments, so it must have been something wonky with the sample data in the build I was using I guess!

**Pull request merged**
