### PR TITLE
Fix select type field issue for dynamic content

### LINKED ISSUE #11730: Dynamic content is not working if filter uses a select-field
### Mautic Version

4.4.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When using a select field as a filter for dynamic content in a MJML email 

1. the email won't be saved if label and values differ from each other
2. the filter will never work when sending the email to contacts 

### How can we reproduce this issue?

step 1: Create a Custom Field of type "select", label and values should differ from each other, e.g. label = female, value = 1 and so on
step 2: Create MJML email in GrapesJS builder
step 3: Add a dynamic content block
step 4: For the variation filter choose the custom field from step 1, operator can be „including” but also any other
step 5: Close builder, click „save & close”
step 6: See the email won’t be saved
step 7: Open builder again, click on the dynamic content, see that for the variation it says „This value is not valid.”
step 8: Now try to choose another value (note: in “4” you had to choose between the labels, now you cannot choose the labels anymore but the value)
step 9: Save the email, send it to test contact, see that the filter are never working

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by irfanhanfi**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR is to fix the issue described here - https://github.com/mautic/mautic/issues/11730

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))

### CODE REVIEW

**Comment by npracht** [comment]
Hi @irfanhanfi ! Thanks a lot for your contribution.
Is your fix doing the same thing as https://github.com/mautic/mautic/pull/11393 ?
@kuzmany any opinion ?

If same, let's keep the PR covering better the issue and including more unit tests.

**Comment by kuzmany** [comment]
The PR https://github.com/mautic/mautic/pull/11393 should fixed it

**Comment by irfanhanfi** [comment]
There are a few observations that I have -
PR #11393 - It looks like it fixes the `boolean` type field issue. This PR saves the custom `Select` field value. But it does not send the correct value in the email for that selected value. For example, if I create a Gender type dropdown and have some variation in the dynamic content. It does not send the variation content but the default one.

My PR does not fix the boolean type field. But it fixes the `Select` field and other dropdown fields like Locale, Country, State, and Timezone.

@kuzmany please let me know if you think otherwise.

**Comment by kuzmany** [comment]
@irfanhanfi that PR fix boolean and select field as well. Can you test it? I identify what commit cause it and tried fixed it in more elegant way.

**Comment by bianchim** [comment]
@kuzmany I can confirm that while your PR does fix the display of the field in the admin, the filter always evaluates to default on select fields.

When using the code from this PR in addition to yours, the condition is evaluated correctly and the field is displayed with the right key and display value in the filter form.

**Comment by jensolsson** [comment]
Thanks a lot your PR seem to have fixed the problem for me. I just changed the small number of rows in the code of my installation and it started working as expected. Thanks! Code looked very concise and I hope it can be merged into a revision of 4.x

**Comment by jensolsson** [comment]
What is required to get this into production?

**Pull request closed without merging**
