### PR TITLE
Non existent logger property fix

### PR DESCRIPTION
**Pull request by escopecz**
| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/2227
| BC breaks? | N
| Deprecations? | N

#### Description:
Calling the logger property which does not exist caused an error in prod mode

#### Steps to test this PR:
Not really sure, should be on email open action.

#### Steps to reproduce the bug:
Not really sure, should be on email open action. See https://github.com/mautic/mautic/issues/2227

### CODE REVIEW

**Comment by dongilbert** [comment]
I would actually suggest injecting the logger into the email model constructor and referencing it via `$this->logger` since we're trying to divorce the code as much as possible from MauticFactory.

**Comment by escopecz** [comment]
Good point. Updated.

**Comment by alanhartless** [comment]
Should we just make logger available to all in common model the same way we inject the other very commonly used dependency via setter methods? I think the cache compiler already looks for setLogger so just need to add setLogger to common model.  Logger is something used often enough I can't come up with an argument why to not just make it available to all models but just an option.

**Comment by escopecz** [comment]
This was a one line fix! :smile: 

But yeah, it makes sense. I'll update it.

**Comment by escopecz** [comment]
@alanhartless is this what you meant?

**Comment by mqueme** [comment]
this worked for me

**Comment by alanhartless** [comment]
+1

**Pull request merged**
