### PR TITLE
Fix Core.parseToObject 2

### PR DESCRIPTION
**Pull request by Bouh**
Original PR https://github.com/mautic/mautic/pull/10499

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 4.0
| New feature/enhancement? (use the a.x branch)      | No
| Deprecations?                          | No
| BC breaks? (use the c.x branch)        | No
| Automated tests included?              | No
| Related user documentation PR URL      | No needs
| Related developer documentation PR URL | No needs
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/issues/10229

#### Description:

This fix formats the parameters better and handles the fancy parameters better.
Fix params parsing from this issue https://github.com/mautic/mautic/issues/10229

#### Steps to test this PR:

You can see tests in a [code sandbox here](https://codesandbox.io/s/params-fix-e8fhw?file=/src/index.js), check the console tab for more information.

### CODE REVIEW

**Comment by RCheesley** [comment]
Hopefully test coverage should pass now, there was a problem with the 4.0 branch after the last release.

**Comment by Bouh** [comment]
> Hopefully test coverage should pass now, there was a problem with the 4.0 branch after the last release.

Glad to see Codecov working again ✨

**Comment by RCheesley** [comment]
@Bouh I have tried testing this locally but I am still getting the same error in the console when embedding the form using the automatic method.  Were you able to test this with Mautic, rather than just the code snippet in isolation?

To do so, if you have docker desktop and DDEV you should be able to just clone the repo and use `ddev start`.

**Review by escopecz — COMMENTED** [review]
I'm a bit torn about this change. The URL params in the test `?a=1&b= 2=` are not valid URL params. The space should be replaced with`+`. How can this happen? I think we should fix the source of the problem and not trying to fix invalid URLs. I fear this change will cause other scenarios to fail.

**Comment by humblecoder** [comment]
Been a while since I checked on this issue.  Has any progress been made?  The issue I'm having is related to *what* gets passed/parsed -- a single item.

@Bouh, if you pass a single value in the code sandbox, the error still occurs.  Basically, the only `param` being passed is from the **embedded** script using url `https://mautic.myserver.com/form/generate.js?id=1` which becomes `https://mautic.myserver.com/media/js/mautic-form.js?v50f3f8e0`.  When `parseToObject` gets called, it fails because there is only a single item (`v50f3f8e0`) being "parsed" and no true object is being created.  

Admittedly, I haven't taken a deep dive and currently have no idea why there's a need for that specific method in this regard, but I'll see what I can discover.

**Comment by Bouh** [comment]
> @Bouh, if you pass a single value in the code sandbox, the error still occurs. Basically, the only `param` being passed is from the **embedded** script using url `https://mautic.myserver.com/form/generate.js?id=1` which becomes `https://mautic.myserver.com/media/js/mautic-form.js?v50f3f8e0`. When `parseToObject` gets called, it fails because there is only a single item (`v50f3f8e0`) being "parsed" and no true object is being created.

Oh good to know! I wonder why this URL is fancy and doesn't follow the basic concepts of the web, but ok, fine.
Did you know what kind of types is supposed to be returned for this function?
Is this url can have multiple argument or not?
There is always one value returned in an object?

If yes we can [use that](https://codesandbox.io/s/params-fix-forked-g8uyl?file=/src/index.js:136-164) to return an object with one value.

**Comment by LeonOltmanns** [comment]
Hi there,
is there any update to this? I'm currently running into this issue after updating my Mautic instance from 3.3.4 to 4.1.0.

I have tried to fix this issue by patching my instance with this PR as well as generating assets which I read in a related issue to this. But I am still running into the same error as you can see:

image

**Pull request closed without merging**
