### PR TITLE
Fix: Report when use Contact Point Log as data source and filter by Segment 

### LINKED ISSUE #8365: 500 Internal Server Error: Report when use Contact Point Log as data source and filter by Segment
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When creating (or view) a report using "Contacts:Contact Point Log" as Data Source, if include a  filter by "Segment",  it shows 500 internal server error every time. 

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.2.9

### Steps to reproduce
1. Go to Reports ->"+ New"
2. Data Sources" Contacts:Contact Point Log"
3. Go to "Data" tab ->Columns-> choose some field
4. Go to "Data" tab -> Filters-> choose "Segment", condition "equals" and choose a Segment.
5. Press "Save & Close" -> Error message should appear
### Log errors
[2020-01-29 10:00:40] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT DATE_FORMAT(lp.date_added, '%Y-%m-%d') AS date, COUNT(*) AS count FROM lead_points_change_log lp LEFT JOIN leads l ON l.id = lp.lead_id WHERE (lp.date_added IS NULL OR (lp.date_added BETWEEN ? AND ?)) AND (s.leadlist_id = ?) GROUP BY DATE_FORMAT(lp.date_added, '%Y-%m-%d') ORDER BY DATE_FORMAT(lp.date_added, '%Y-%m-%d') ASC LIMIT 32' with params ["2019-12-28 23:00:00", "2020-01-29 09:00:40", "30"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 's.leadlist_id' in 'where clause'" at /XXXX/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT DATE_FORMAT(lp.date_added, '%Y-%m-%d') AS date, COUNT(*) AS count FROM lead_points_change_log lp LEFT JOIN leads l ON l.id = lp.lead_id WHERE (lp.date_added IS NULL OR (lp.date_added BETWEEN ? AND ?)) AND (s.leadlist_id = ?) GROUP BY DATE_FORMAT(lp.date_added, '%Y-%m-%d') ORDER BY DATE_FORMAT(lp.date_added, '%Y-%m-%d') ASC LIMIT 32' with params [\"2019-12-28 23:00:00\", \"2020-01-29 09:00:40\", \"30\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 's.leadlist_id' in 'where clause' at /XXXX/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 's.leadlist_id' in 'where clause' at /XXXX/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 's.leadlist_id' in 'where clause' at /XXXX/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by dev-marcel**
closes https://github.com/mautic/mautic/issues/8365

| Q  | A
| --- | ---
| Bug fix? |  Yes
| New feature? | No 
| Automated tests included? | No 
| Related user documentation PR URL |  No
| Related developer documentation PR URL | No  
| Issues addressed (#s or URLs) | #8365 
| BC breaks? |  Nope, backwards comptabible
| Deprecations? | No

## Steps to reproduce

1. Go to Reports ->"+ New"
2. Data Sources" Contacts:Contact Point Log"
3. Go to "Data" tab ->Columns-> choose some field
4. Go to "Data" tab -> Filters-> choose "Segment", condition "equals" and choose a Segment.
5. Press "Save & Close" -> Error message should appear

### CODE REVIEW

**Comment by npracht** [comment]
Hi @dev-marcel ! Is this issue still existing on M3? Could you please test on 3.x branch and (un)confirm ?
Thanks

**Comment by dev-marcel** [comment]
@npracht checkt the 3.x branch and the issue still exists there, checked it on our test environment and also checked the code: 

https://github.com/mautic/mautic/blob/3.x/app/bundles/LeadBundle/EventListener/ReportSubscriber.php 

which indicates the same.

**Comment by npracht** [comment]
Can you please rebase against M3 branch please ? :)

**Comment by kuzmany** [comment]
I've changed title, add steps to reproduce and change based to 3.x branch.
For testing on https://m3.mautibox.com/8746 require merge https://github.com/mautic/mautic/pull/8722 before

**Comment by RCheesley** [comment]
Having some issues with rebasing this to trigger the code coverage report - @dev-marcel @kuzmany can you take a look and rebase against staging? Thanks!

**Comment by dennisameling** [comment]
Just rebased, so if the tests pass we should be good to go 🚀

**Review by kuzmany — DISMISSED** [review]
👍 works

**Comment by RCheesley** [comment]
@kuzmany as this will decrease coverage we need tests before we can merge - can you take a look please?

Moving to 3.0.2 release as a result.

**Review by RCheesley — DISMISSED** [review]
Tested the bug and this PR does fix it - let's get a test written so we can get this merged in 3.0.2! :tada: :rocket:

**Comment by RCheesley** [comment]
@mabumusa1 would you be up for writing a test for this so we can get it merged in 3.1?

**Comment by mabumusa1** [comment]
@RCheesley I will do that over the weekend.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by mabumusa1** [comment]
@RCheesley I need help finishing the test, it is too big and took a lot of time, there are two cases to be tested

https://github.com/mabumusa1/mautic/blob/c34e0a8d7ddf80a71a2ffae5fabb3194b6d83776/app/bundles/LeadBundle/Tests/EventListener/ReportSubscriberTest.php

**Comment by CyberMarsl** [comment]
1. Testing it the the bug exist on the 3.1 installation.

2. In Mautibox with Fix for this: It seems to work.
Debug: 1ms
SELECT count(*) FROM (SELECT l.email AS email, l.firstname AS firstname, l.lastname AS lastname FROM 8746_lead_points_change_log lp LEFT JOIN 8746_leads l ON l.id = lp.lead_id INNER JOIN 8746_lead_lists_leads s ON s.lead_id = l.id AND s.manually_removed = 0 WHERE (lp.date_added IS NULL OR (lp.date_added BETWEEN :dateFrom AND :dateTo)) AND (s.leadlist_id = :i2csleadlistid)) c

SELECT l.email AS email, l.firstname AS firstname, l.lastname AS lastname FROM 8746_lead_points_change_log lp LEFT JOIN 8746_leads l ON l.id = lp.lead_id INNER JOIN 8746_lead_lists_leads s ON s.lead_id = l.id AND s.manually_removed = 0 WHERE (lp.date_added IS NULL OR (lp.date_added BETWEEN '2020-08-10 00:00:00' AND '2020-09-10 20:53:57')) AND (s.leadlist_id = '2') LIMIT 30

**Comment by mabumusa1** [comment]
@dev-marcel May you please sign the contributor's agreement? I would love to get this PR in the next release this week

**Comment by RCheesley** [comment]
Bumping to 3.1.2 due to unsigned contributors agreement and test coverage needing to be improved.

**Comment by mabumusa1** [comment]
For anyone interested in help me finish the automated test for this PR, I started another PR to include the automated test only, it can be found on

https://github.com/mautic/mautic/pull/9311

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by npracht** [comment]
Can you rebase this against 3.2 branch @dev-marcel ? Then we merge it now for next patch version :)

**Comment by Uebix** [comment]
Seems that the same error is in CONTEXT_CONTACT_ATTRIBUTION_MULTI.

SQLSTATE[42S22]: Column not found: 1054 Unknown column 's.leadlist_id' in 'where clause' at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 's.leadlist_id' in 'where clause'

**Comment by kuzmany** [comment]
@Uebix this PR is already merged in repot. Create issue with mention this situation and PR, please. Have to be fixed by another pull request

**Pull request merged**
