### PR TITLE
Fix regex in PageSubscriber.php

### PR DESCRIPTION
**Pull request by putzwasser**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

The regex in `onPageDisplay()` for the `onPageDisplay_bodyOpen` event for outputting the `bodyOpenScripts` is faulty and won't catch all possible scenarios.

See this regex tester with real world scenarios (and sources):
https://regex101.com/r/fXmrq6/1

See that this fix fixes this:
https://regex101.com/r/W7bwDL/3

**Additional Ressources**
- https://www.rexegg.com/regex-style.html#contrast
- https://www.rexegg.com/regex-style.html#lazy_warning
- https://www.rexegg.com/regex-quantifiers.html#negclass_solution

### CODE REVIEW

**Comment by putzwasser** [comment]
PR for 4.4 branch #12386

**Comment by RCheesley** [comment]
Hi @putzwasser and welcome to the community!

Appreciate you taking the time to make the PR for 4.4.x and 5.x, thank you!

Would you mind adding a description for testers (who most likely are not developers) so that they can understand how to reproduce the issue that is caused by this bug, and then what to expect when the PR is applied to demonstrate that it is resolved? This will ensure that we can get the PR tested and reviewed in good time.

**Review by escopecz — CHANGES_REQUESTED** [review]
Please add a unit test that will test all scenarios

**Comment by putzwasser** [comment]
@escopecz I added a test.

I'm not quite sure what you mean by _<q>all scenarios</q>_, though.

The new regex literally catches everything you could write into a body tag.

It doesn't ensure that the attribute names follow the HTML5 [spec](https://www.w3.org/TR/2011/WD-html5-20110525/syntax.html#attributes-0), but I don't think it should.

Is this sufficient to get this merged?

**Comment by escopecz** [comment]
I'll take a look. Could you resolve the conflict in the mean time?

**Comment by escopecz** [comment]
Yep, the test looks good. We'll also need the steps to test as Ruth requested earlier. Can you provide some custom landing page theme that has this complicated `</body>` tag attributes? Or is there some easier way how to replicate the bug?

**Comment by putzwasser** [comment]
> Or is there some easier way how to replicate the bug?

Yep, either create a landing page using the code mode "template" or open the raw code editor in your grapesjs editor.

Both ways let you add attributes to the body tag.

Simple HTML for using with code mode:

```
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>{pagetitle}</title>
            <meta name="description" content="{pagemetadescription}">
    </head>
    <body class="mt-6 p-[5px] max-w-xl md:max-w-2xl" onclick="myFunction()" style="width: 200px;">
        
        <div data-section-wrapper="1">
    <center>
        <table data-section="1" style="width: 600;" width="600" cellpadding="0" cellspacing="0">
            <tbody>
                <tr>
                    <td>
                        <div data-slot-container="1" style="min-height: 30px">
                            <div data-slot="text">
                                <br>
                                <h2>Hello there!</h2>
                                <br>
                                We haven't heard from you for a while...
                                <br>
                                <br>
                                <br>
                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </center>
</div>
        
    </body>
</html>
```

### testing
> this complicated </body> tag attributes

My use case was arbitrary tailwind-css classes. They look strange, but are pretty common.

Thing is (as this is over a year old) I don't recall where the content from `$bodyOpenScripts` came from in my use case. :sweat_smile: 

So, you won't see a difference in code mode, TBH.

You would need to have some PHP event listeners that add scripts to
 * - </head> : onPageDisplay_headClose
 * - <body>  : **onPageDisplay_bodyOpen**
  * - </body> : onPageDisplay_bodyClose.

To confirm this PR works as intended, now. I don't have one at hand, RN  :man_facepalming:

Maybe someone has. If so:
1. Add a breaking attribute to your body tag (e.g. `style="padding: 5px; margin: 5px"`; the semicolon will break processing of the regex and, thus, prevent `onPageDisplay_bodyOpen` to get inserted right after the opening `<body>`)
2. See that your scripts won't get added to your page (because the regex fails)
3. load this PR
4. The scripts get added to your page.

In any case:
1. Inspect your landing page source code
2. Load this PR
3. Inspect your landing page source code, again
4. See that nothing has changed. I.e. this fix doesn't break anything.

As soon as I recall how to add contents to `onPageDisplay_bodyOpen` I will extend testing instructions.

**Comment by escopecz** [comment]
There is also a conflict

**Comment by putzwasser** [comment]
Tried to resolve the conflict, but I don't know if I did it correctly, as there are over 4k changed files, now.

Did I do something wrong?

**Comment by escopecz** [comment]
@putzwasser hard to tell without mentioning what you did exactly. But please check [the diff](https://github.com/mautic/mautic/pull/12385/files) if those changes are what you wanted. There are failing checks in GitHub Actions so please check what's wrong there.

**Comment by putzwasser** [comment]
> hard to tell without mentioning what you did exactly

I tried to resolve the conflicts. Merged 5.x into this PR branch locally, edited the conflicts and pushed it. I guess it was right, but GitHub just showed all merged files for some time. :shrug: 

> But please check [the diff](https://github.com/mautic/mautic/pull/12385/files) if those changes are what you wanted.

Looks good now (2 files).

> There are failing checks in GitHub Actions so please check what's wrong there.

Solved it.

**Review by escopecz — APPROVED** [review]
The code looks good! 👍 

I also asked GPT to review:
Screenshot 2024-06-12 at 10 34 55

**Pull request merged**
