### PR TITLE
Fix report with aggregated columns is not saved properly

### LINKED ISSUE #11311: Report with calculated columns is not saved properly
### Mautic Version

4.3.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

There is some kind of UI problem with saving the report with aggregated columns properly.

### How can we reproduce this issue?

Steps to reproduce issue:
1. Go to reports and create a new report
2. Fill name field and select type Emails sent
3. Add column `ID` and group by `ID`. Add Two aggregated columns: SUM Read, SUM Bounce
obraz
4. Click Save & Close
5. 500 Internal server error message should appear
6. Go to Reports and edit created report
7. Select `Data` tab. One of calculated columns has different value than previously selected
obraz
8. Select SUM Read again and click Save & Close
9. Report should work now

### Relevant log output

```shell
[2022-07-04 11:01:14] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'SELECT count(*) FROM (SELECT `e`.`id` AS e_id, SUM() AS 'SUM ', SUM(IF(dnc.id IS NOT NULL AND dnc.reason=2, 1, 0)) AS 'SUM bounced' FROM mc_email_stats es LEFT JOIN mc_emails e ON e.id = es.email_id LEFT JOIN mc_lead_donotcontact dnc ON es.email_id = dnc.channel_id AND dnc.channel='email' AND es.lead_id = dnc.lead_id WHERE es.date_sent IS NULL OR (es.date_sent BETWEEN ? AND ?) GROUP BY e.id) c' with params ["2022-06-03 22:00:00", "2022-07-04 09:01:13"]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AS 'SUM ', SUM(IF(dnc.id IS NOT NULL AND dnc.reason=2, 1, 0)) AS 'SUM bounced'' at line 1" at /home/www/mautic./www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 98 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'SELECT count(*) FROM (SELECT `e`.`id` AS e_id, SUM() AS 'SUM ', SUM(IF(dnc.id IS NOT NULL AND dnc.reason=2, 1, 0)) AS 'SUM bounced' FROM mc_email_stats es LEFT JOIN mc_emails e ON e.id = es.email_id LEFT JOIN mc_lead_donotcontact dnc ON es.email_id = dnc.channel_id AND dnc.channel='email' AND es.lead_id = dnc.lead_id WHERE es.date_sent IS NULL OR (es.date_sent BETWEEN ? AND ?) GROUP BY e.id) c' with params [\"2022-06-03 22:00:00\", \"2022-07-04 09:01:13\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AS 'SUM ', SUM(IF(dnc.id IS NOT NULL AND dnc.reason=2, 1, 0)) AS 'SUM bounced'' at line 1 at /home/www/mautic./www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:98, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AS 'SUM ', SUM(IF(dnc.id IS NOT NULL AND dnc.reason=2, 1, 0)) AS 'SUM bounced'' at line 1 at /home/www/mautic./www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AS 'SUM ', SUM(IF(dnc.id IS NOT NULL AND dnc.reason=2, 1, 0)) AS 'SUM bounced'' at line 1 at /home/www/mautic./www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117)"} {"hostname":"v4.mautic","pid":31703}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/109790802-report-with-calculated-columns-is-not-saved-properly?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ Y ]
| New feature/enhancement? (use the a.x branch)      | [ N ]
| Deprecations?                          | [ N ]
| BC breaks? (use the c.x branch)        | [ N ]
| Automated tests included?              | [ N ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #11311 

#### Description:
This PR fixes issue with saving report with aggregated columns #11311

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Go to reports and create a new report
3. Fill name field and select type Emails sent
4. Add column `ID` and group by `ID`. Add Two aggregated columns: SUM Read, SUM Bounce
obraz
5. Click Save & Close
6. Report should be saved successfully

### CODE REVIEW

**Comment by patrykgruszka** [comment]
I'm not sure why the code coverage has dropped, since I didn't modified any PHP files. Nevertheless it would require some JS engine test this change.

**Review by escopecz — APPROVED** [review]
Code looks good. Don't worry about the test coverage.

**Comment by volha-pivavarchyk** [comment]
When I click to the save&close button the first time, it is broken. After that it works fine
image

When I click to the save button, it works well

**Review by volha-pivavarchyk — APPROVED** [review]
Works well. I tested it on gitpod.

**Comment by escopecz** [comment]
The PHPSTAN issue is not related to this PR and will be fixed by https://github.com/mautic/mautic/pull/11599, so merging.

**Pull request merged**
