### PR TITLE
Safe join company table

### LINKED ISSUE #9785: Using Company ID in a report throws a 500 error
## Bug Description
Came across this while testing a PR. Create a report including Company ID - I used Contacts as the source and these options:

screenshot-mautic32 ddev site-2021 03 13-19_01_12

Save the report and try to view it.

| Q   | A
| --- | ---
| Mautic version | 3.3.1
| PHP version | 7.4
| Browser | Chrome

### Steps to reproduce
1. Create a report with the Contacts source and Company ID along with the other fields in the screenshot
2. View the report
 
### Log errors
[2021-03-13 19:57:00] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Query\QueryException: "The given alias 'companies_lead' is not unique in FROM and JOIN clause table. The currently registered aliases are: l, companies_lead." at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryException.php line 31 {"exception":"[object] (Doctrine\\DBAL\\Query\\QueryException(code: 0): The given alias 'companies_lead' is not unique in FROM and JOIN clause table. The currently registered aliases are: l, companies_lead. at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryException.php:31)"} []

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/97219513-using-company-id-in-a-report-throws-a-500-error?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by snoblucha**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          |no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #9785

#### Description:

As described in https://github.com/mautic/mautic/issues/9785 - when generating reports from Leads with Company data the report will throw 500. 

It is called at least twice 

- from docker/data/mautic/app/bundles/LeadBundle/EventListener/ReportSubscriber.php:250
- and from docker/data/mautic/app/bundles/LeadBundle/EventListener/ReportSubscriber.php:382

This allows this function to be called more than once safely.

#### Steps to test this PR:
1. Load up
2. Create report from Contact dataset and add field from company
3. report shows without a problem

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for making the PR to fix this @snoblucha - if you can sign the contributors agreement that would be awesome!

**Comment by stevedrobinson** [comment]
Tested on a 3.3 instance and it works. Thank you, @snoblucha!

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@snoblucha could you take care of the [code style](https://github.com/mautic/mautic/pull/9973/checks?check_run_id=2525786210#step:6:77) issue please?

We will also need to take care of the test coverage as this PR will result in [decreased coverage](https://github.com/mautic/mautic/pull/9973#issuecomment-834194500). Are you able to take a look at the relevant tests and update/improve them?

**Review by kuzmany — APPROVED** [review]
Meet same issue and this PR fixed it 👍

**Comment by npracht** [comment]
@all-contributors please add @kuzmany for userTesting

**Comment by npracht** [comment]
@all-contributors please add @kuzmany for review

**Review by RCheesley — APPROVED** [review]
Thanks for the PR @snoblucha - was able to reproduce the issue and the PR has addressed it! 🎉 

LGTM 🚀

**Comment by RCheesley** [comment]
@all-contributors please add @stevedrobinson for userTesting

**Comment by RCheesley** [comment]
@all-contributors please add @snoblucha for code and bug

**Pull request merged**
