### PR TITLE
Fixing DNC add API endpoint with defined channel ID

### PR DESCRIPTION
**Pull request by escopecz**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | N
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | https://mautic.slack.com/archives/C02HU8BUT/p1541033878117300
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

While helping a Mautician on Slack I found that the DNC API endpoint doesn't work correctly if the `channelId` is set in the request. If it is set then the channel nor the channel ID is saved to the DNC record. The record is created but it is not possible to remove it through the UI as it has an empty channel.

Endpoint: `POST /contacts/ID/dnc/CHANNEL/add`

Body:
```JSON
{
  "channelId": "26",
  "reason": "Integration issued DNC",
  "comments": "Unsubscribed via API"
}
```

Header: `Content-Type: application/json`

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Try to unsubscribe an existing contact from an existing email. You can use the body above. Don't forget the header if you use the JSON format.
2. Notice the contact has a DNC record in the timeline but it has no channel. You cannot remove this DNC record from the UI.

#### Steps to test this PR:
1. Try again. This time the channel will be set, properly displayed in the UI and you can also remove it.

### CODE REVIEW

**Comment by escopecz** [comment]
There are lots of tests failing, but I don't believe it's all because of the change I made. I merged staging in that brief moment when it had PHP 7.2 PR merged in it. I'll wait for fix of that and merge staging again if it will fix it.

**Comment by Woeler** [comment]
Might be my ignorance here, but what is that eventname 1 and that random 0 doing there? I used the request body you described, just changed the channel id to a channel I have.
image

**Comment by escopecz** [comment]
I did not look into that. Might by unrelated bug. Could you look at preference center for that contact to see if the right checkboxes are checked?

**Comment by Woeler** [comment]
Okay yea, nevermind I was doing something stupid. Okay I got it to work, now I just need to know what you mean by "remove dnc via the UI", where do I do this?

**Comment by escopecz** [comment]
On contact's detail open the action menu (arrow down next to the close button) and click on Preferences. Check that the contact is subscribed to all channels and save.

**Comment by Woeler** [comment]
Looks like this. Checking all and saving does not remove dnc for me. The icon stays.
image

**Comment by escopecz** [comment]
What channel did you unsubscribe via API? I can see only the email channel enabled there.

**Comment by Woeler** [comment]
I had an email that a contact was in. Channel id 1, email. Then I called the API to unsub. Now it looks like this. Unsub is in the contact logs though.

**Comment by escopecz** [comment]
Maybe there is a bug in the preference center form when there is only one channel. I can see this:
screen shot 2018-11-12 at 10 58 35

**Comment by mleffler** [comment]
@escopecz Can you tag the community member who needed this so they can give it a test pass - if they are not already using it?  TY!

**Comment by escopecz** [comment]
I pinged the Slack user who reported it. The Slack discussion is linked in the PR description.

**Pull request merged**
