### PR TITLE
Fixed cs-fixer in GitHub actions

### PR DESCRIPTION
**Pull request by fedys**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features"
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      |
| Related developer documentation PR URL |
| Issue(s) addressed                     | 

#### Description:
This PR fixes `CS Fixer` GitHub Action. There were several issues:
1. #10023 was failing with `[Symfony\Component\Console\Exception\RuntimeException] The "--git" option does not exist.`
2. When there was no `*.php` modified file,  `bin/php-cs-fixer fix ...` checked all PHP files in the project.
3. As there was `git diff "HEAD~..HEAD"`, `bin/php-cs-fixer fix ...` checked only PHP files that had been changed in the very last commit.
4. Now when there is no changed  `*.php` file, `bin/php-cs-fixer fix ...` is not executed at all.

#### Steps to test this PR:
1. Try changing several PHP files so they break CS rules => GitHub CS Fixer action should fail.
2. Try changing several non-PHP files while not changing any PHP file =>  GitHub CS Fixer should not execute `bin/php-cs-fixer fix ...` command at all.

### CODE REVIEW

**Comment by dennisameling** [comment]
Thanks a lot for the research and this PR @fedys, will review it on Friday or latest Saturday!

**Review by dennisameling — APPROVED** [review]
This is looking great, thanks @fedys! One thing I'm not entirely sure about (but that's quite unrelated to this PR, as it was already like that) is that we only check _changed_ files in the CS step. For safety, I think it'd be better if we just let `php-cs-fixer` scan the whole repo instead. Newer versions of the CS fixer are faster, so speed shouldn't really be an issue anymore then (assuming we'll update soon). Curious to hear @RCheesley's thoughts on this!

Approving for now as it does fix the reported issues and unblocks several PRs 🚀

**Comment by RCheesley** [comment]
Won't we be doing that (checking the whole repo) with the daily checks anyway? Shouldn't it throw up an error if there are issues that way? 

Would prefer to have a smooth and slick CI pipeline and not add overhead we don't need if at all possible. Let's get this merged and we can come to a decision on your question in the next product team meeting (cc @mohit-rocks please add to the agenda so we don't forget!)

**Comment by dennisameling** [comment]
> Won't we be doing that (checking the whole repo) with the daily checks anyway?

Nope, because the daily checks workflow is the exact same as the one we run on new commits and PRs: https://github.com/mautic/mautic/blob/features/.github/workflows/tests.yml#L153-L161

It's rather easy in GH Actions to add an `if` clause that checks the whole repo only in the daily checks, and not on new commits/PRs. Let me know what the outcome of the product team meeting is, happy to create a PR for it 👍🏼

**Pull request merged**
