### PR TITLE
Ignore queue mode for send email action

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/3828
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

This bugfix/feature has been sponsored by @Webmecanik

[//]: # ( Required: )
#### Description:
Added option to  send email immediately  even if queue email mode is enabled.

image

#### Steps to test this PR:
1.  Apply PR and got to Configurations > Emails > and  Enable queue
2.  Create form with Send email to  Contact action with new Send immediately option set to No
3:  Send form, email should go to queue (verify it in directory app\spool\default\) 
4. Then Go to form and edit action to Send immediately YES
5. Send from, email should send immediately without queue  (again verify it in directory app\spool\default\ - new file shoudn't create) 
6. Then change Configurations > Emails > and change  Queue to immediately 
7. Send form and email should send immediately    (again verify it in directory app\spool\default\ - new file shoudn't create)

### CODE REVIEW

**Comment by javjim-mautic** [comment]
Need some clarification. I do see the button of send immeaditately on "Send form results" but not on Send email to contact or "send email to user"

Is that intended behaviour? @kuzmany

**Comment by alanhartless** [comment]
@javjim-mautic  you have to change Mautic's configuration to Queue mode in the email settings tab.

**Comment by npracht** [comment]
I've been testing it and it works ❤️

**Comment by javjim-mautic** [comment]
After some clarification with @alanhartless re tested and working properly

**Pull request merged**
