### PR TITLE
Style and Script tags are allowed in the Email/Page HTMLs

### PR DESCRIPTION
**Pull request by escopecz**
Please answer the following questions:

| Q             | A
| ------------- | ---
| Bug fix?      | Y
| New feature?  | N
| BC breaks?    | N
| Deprecations? | N
| Fixed issues  |  #1959 

## Description

**Warning:** https://github.com/mautic/mautic/pull/1962 and https://github.com/mautic/mautic/pull/1992 must be merged first in order to test this PR successfully.

The full-page Froala editor was removing `<style/>` and `<script/>` tags which caused a big issues as discussed in #1959. After discussion with Froala guys I found out there is another option which removes them (https://github.com/froala/wysiwyg-editor/issues/1396). This PR clears this option.

## Steps to reproduce the bug (if applicable)
1. Create an email or a page.
2. Save it and review the code. You will notice that all the style tags are gone.

## Steps to test this PR
1. Apply this PR
2. Rebuild prod assets with `app/console mautic:assets:generate` command
3. Try again (create a new page/email, because the old one won't get fixed). The style tags should remain.

### CODE REVIEW

**Comment by mqueme** [comment]
I tried this

<style>
.boldme{
  font-weight: bold;
}
</style>

it removed the tags

**Comment by mqueme** [comment]
it removed my tags.

**Comment by escopecz** [comment]
@mqueme have you used the dev mode and refreshed the browser? Could you write down the steps you've used to test it?

**Comment by dongilbert** [comment]
@escopecz What other PR's must be merged prior to this?

**Comment by escopecz** [comment]
Ehm, where my description update went? I probably didn't save it or something. Right now only this one: https://github.com/mautic/mautic/pull/1992

**Comment by escopecz** [comment]
Ok, I found the warning in another PR... Moved here.

**Comment by mqueme** [comment]
+1

**Pull request merged**
