### PR TITLE
Feature: Mautic Tag Manager MR-51

### PR DESCRIPTION
**Pull request by luguenth**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | yes
| Automated tests included?              | no
| Related user documentation PR URL      | https://github.com/mautic/mautic-documentation/pull/134
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

The Tag Manager can be used to have a quick overview over existing Tags. It's also possible to create, edit or delete Tags.
Further it's possible to see how many contacts are holding a specific tag.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Open the Tag Manager (Last Item on the left Menu)
3. Create, Edit and Delete Tags

##### Known Issues
When clicking on the "# of contacts" label and the tag has a white space, it's not possible to pass the tag-string in parenthesis. So there'll be no contacts shown. But Mautic shouldn't accept Tags with whitespace, so maybe this is more of a Mautic-Issue.

### CODE REVIEW

**Comment by RCheesley** [comment]
Hi @luguenth thanks for making this PR - looks like a great feature and a much-requested addition to Mautic!

It looks like @nikolanedic might need to add the email address they have registered on Git against their Github profile, so that our CLA bot knows who you are.

Also if you haven't already, please can all contributors sign the Mautic Contributors Agreement here: https://www.mautic.org/contributor-agreement

**Comment by RCheesley** [comment]
@luguenth can you please take a look at the Travis tests that are failing? Many thanks!

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by nikolanedic** [comment]
All changes in this PR are within the "plugins" directory so fulfilling "codecov/patch" requirement is not possible since "plugins" directory seems to be ignored on Codecov.
It's strange that when I added tests to the PR overall project coverage improved, but patch coverage did not. Does anyone have an idea of what should we do in this situation?

**Comment by RCheesley** [comment]
@nikolanedic  it looks at a glance like you might need to rebase, as Codecov is pulling in more files than are changed/added in this PR which can mean that you're out of date with the base branch. As we are merging in PRs for the 3.2 release this is going to happen as they are merged into Staging.

With new files it doesn't have anything to compare to for the change in coverage, but we do need to try to have as high a test coverage as possible for new PR's. I haven't had the time to look in detail yet at this PR - will do so soon.

**Comment by dennisameling** [comment]
@luguenth [We just merged a PR](https://github.com/mautic/mautic/pull/9423) which fixes the `0.00%` `codecov/patch`. I think if you rebase you should be good to go:

`git fetch upstream` 
and then
`git rebase upstream/staging`

Let us know here if you need help with the rebase, we could checkout your PR locally and do it for you 👍

**Comment by RCheesley** [comment]
Looks likely that we are going to need to improve test coverage on this before we can merge, we will also need to add this to the documentation.

**Comment by RCheesley** [comment]
@dennisameling @mabumusa1 could you help with the rebasing?

**Comment by dennisameling** [comment]
Rebased! I didn't have time to run the test suite locally, so let's see what CI comes up with. CC @RCheesley @luguenth

**Comment by dennisameling** [comment]
@luguenth would you mind having a look at the failing tests? Looks like you're inserting a duplicate entry into the database in your tests. Thanks!

**Comment by RCheesley** [comment]
@luguenth this all seems great but I have a question on the 'new' feature - when testing this I am not seeing this open in a modal but is the page - is that expected?

The reason I ask is because it looks a little odd- there is a grey area bottom right of the page which doesn't look quite right.

Vid here: https://youtu.be/5IQw9cWmlgQ

**Comment by RCheesley** [comment]
Also, I was able to create two tags exactly the same - this should not be allowed, I would have thought?

screenshot-mautic32 ddev site-2021 02 12-20_49_35

I can assign both to a contact in the UI:

screenshot-mautic32 ddev site-2021 02 12-20_55_10

But then I see only one of them in the contact profile:

screenshot-mautic32 ddev site-2021 02 12-20_55_34

This is the first tag with that name that is being assigned:

screenshot-mautic32 ddev site-2021 02 12-20_55_59

So I am assuming that there is a check missing in the create new tag part which is failing to check for an existing tag.

**Comment by npracht** [comment]
@luguenth any chance you have a look at @RCheesley feedbacks ? :)

**Comment by RCheesley** [comment]
@luguenth thanks for adding in the validation for existing tags, that is a much better experience now!  I think that you will also need to rebase the PR but let me just double check with the team as we may need to switch this to the 4.0 branch now!

**Comment by RCheesley** [comment]
@luguenth it looks like we need to [improve the test coverage](https://github.com/mautic/mautic/pull/9364/checks?check_run_id=2202668766) on this PR - are you able to look into that?

Here is the [info from CodeCov](https://app.codecov.io/gh/mautic/mautic/compare/9364/diff) on where we have missing coverage.

**Comment by luguenth** [comment]
I tried to do that, but I'm not getting what I'm missing. Very new to Codecov

**Comment by anton-vlasenko** [comment]
@luguenth 
[coverage-report.zip](https://github.com/mautic/mautic/files/6415399/coverage-report.zip)
I've attached a coverage report for your convenience so you can see which lines are not covered by the unit tests (unzip and open index.html).

**Comment by anton-vlasenko** [comment]
`codecov` shows all the new lines as not covered as if it didn't perform any coverage test at all. `codecov` is definitely not working correctly here.
I've just ran the coverage manually and the unit tests in this PR  cover 47.13% of new lines, so the coverage percentage should not drop.

**Comment by dennisameling** [comment]
The code coverage drop seems to be in the unrelated `AbstractChart.php` - I had this issue in my recent PRs as well, so as soon as one PR is merged (don't think it matters a lot which one), we can re-run the tests and should be good then. Thanks for looking into this @anton-vlasenko

**Comment by anton-vlasenko** [comment]
I've just rebased the branch. Let's see if it fixes the issue with codecov.
Update: Oh, it didn't fix the issue. I did what I could.

**Comment by RCheesley** [comment]
@all-contributors please add @luguenth for code and doc

**Comment by RCheesley** [comment]
@all-contributors please add @rcheesley for userTesting and review

**Comment by RCheesley** [comment]
@all-contributors please add @anton-vlasenko for code and test

**Comment by RCheesley** [comment]
@all-contributors please add @fedys for code and test

**Pull request merged**
