### PR TITLE
TPROD-324 - PointBundle - Migrate PHP Templates to Twig Templates

### PR DESCRIPTION
**Pull request by JoshuaEstes**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. 

- `/s/points` (Actions)
  - works with and without data
  - filter
  - sort by columns
- `/s/points/new` and `/s/points/edit/{id}`
  - form renders correctly
  - Make sure each selection from **When a contact...** renders correctly
- `/s/points/triggers` (Triggers)
  - filter
  - sort by columns
- `/s/points/triggers/new` and `/s/points/triggers/edit/{id}`
  - form renders correctly
  - select events to make sure they render correctly
  - GIVEN you and editing a trigger AND it has an existing event THEN make sure when you try to edit the event that the form renders correctly
- global search will display trigger
- global search will display action

**Known Issues**
- GIVEN you are on the index/list route WHEN you click on the publish icon next to the name of the action or trigger THEN it will no longer work and must reload the page
- Global search will sometimes display an error https://github.com/mautic/mautic/issues/11977
- Cloning a trigger will not clone the events https://github.com/mautic/mautic/issues/11978

### CODE REVIEW

**Review by mabumusa1 — CHANGES_REQUESTED** [review]
- [X] Actions Dashboard
- [X] Global Filter
- [X] Sort by column 
- [X] Create Action
- [X] Create a Category
- [X] When Contact Changes the condition changes
- [X] Publish/Unpublish 
- [X] Edit
- [X] Delete
- [X] Clone
- [X] Trigger Dashboard
- [X] Global Filter
- [X] Sort by column 
- [X] Create Action
- [X] Create a Category
- [X] Edit
- [ ] **Clone does not clone events**
- [X]  Delete

**Comment by sdoering** [comment]
**/s/points (Actions)**

- [x] works with and without data
- [x] filter
- [x] sort by columns 

**/s/points/new and /s/points/edit/{id}**
- [x] form renders correctly
- [x] Make sure each selection from When a contact... renders correctly

**/s/points/triggers (Triggers)**
- [x] filter (does filter on Name, doesn't filter on Category)
- [ ] sort by columns (Does not sort by Category: See [1] & [2]

**/s/points/triggers/new and /s/points/triggers/edit/{id}**
- [x] form renders correctly
- [x] select events to make sure they render correctly
- [x] GIVEN you and editing a trigger AND it has an existing event THEN make sure when you try to edit the event that the form renders correctly

Screenshots: 
[1] Sorted ASC: image
[2] Sorted DESC: image

**Comment by JoshuaEstes** [comment]
@sdoering 

> sort by columns (Does not sort by Category: See [1] & [2]

Resolved: https://github.com/mautic/mautic/pull/11968/commits/22d8e141591aeac033587883264b745d6904c8cd

**Review by RCheesley — CHANGES_REQUESTED** [review]
Things I noticed:

- On Triggers, selecting events > add to integration, I am not able to cancel the popup, following in the logs:

```
[2023-02-14 19:19:28] mautic.CRITICAL: Uncaught PHP Exception TypeError: "method_exists(): Argument #1 ($object_or_class) must be of type object|string, bool given" at /var/www/html/app/bundles/PluginBundle/Form/Type/IntegrationsListType.php line 77 {"exception":"[object] (TypeError(code: 0): method_exists(): Argument #1 ($object_or_class) must be of type object|string, bool given at /var/www/html/app/bundles/PluginBundle/Form/Type/IntegrationsListType.php:77)
[stacktrace]
#0 /var/www/html/app/bundles/PluginBundle/Form/Type/IntegrationsListType.php(77): method_exists(false, 'getCampaigns')
#1 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Mautic\\PluginBundle\\Form\\Type\\IntegrationsListType->Mautic\\PluginBundle\\Form\\Type\\{closure}(Object(Symfony\\Component\\Form\\Event\\PreSetDataEvent), 'form.pre_set_da...', Object(Symfony\\Component\\EventDispatcher\\EventDispatcher))
#2 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'form.pre_set_da...', Object(Symfony\\Component\\Form\\Event\\PreSetDataEvent))
#3 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners(Array, 'form.pre_set_da...', Object(Symfony\\Component\\Form\\Event\\PreSetDataEvent))
#4 /var/www/html/vendor/symfony/event-dispatcher/ImmutableEventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch(Object(Symfony\\Component\\Form\\Event\\PreSetDataEvent), 'form.pre_set_da...')
#5 /var/www/html/vendor/symfony/form/Form.php(353): Symfony\\Component\\EventDispatcher\\ImmutableEventDispatcher->dispatch(Object(Symfony\\Component\\Form\\Event\\PreSetDataEvent), 'form.pre_set_da...')
#6 /var/www/html/vendor/symfony/form/Extension/Core/DataMapper/PropertyPathMapper.php(52): Symfony\\Component\\Form\\Form->setData(Array)
#7 /var/www/html/vendor/symfony/form/Form.php(389): Symfony\\Component\\Form\\Extension\\Core\\DataMapper\\PropertyPathMapper->mapDataToForms(Array, Object(RecursiveIteratorIterator))
#8 /var/www/html/vendor/symfony/form/Form.php(493): Symfony\\Component\\Form\\Form->setData(Array)
#9 /var/www/html/vendor/symfony/form/FormBuilder.php(208): Symfony\\Component\\Form\\Form->initialize()
#10 /var/www/html/vendor/symfony/form/FormFactory.php(32): Symfony\\Component\\Form\\FormBuilder->getForm()
#11 /var/www/html/app/bundles/PointBundle/Controller/TriggerEventController.php(60): Symfony\\Component\\Form\\FormFactory->create('Mautic\\\\PointBun...', Array, Array)
#12 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(458): Mautic\\PointBundle\\Controller\\TriggerEventController->newAction(0, '')
#13 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(159): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('new', 0, 0, '')
#14 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#15 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#16 /var/www/html/app/AppKernel.php(105): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#18 /var/www/html/app/middlewares/HSTSMiddleware.php(35): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#19 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\HSTSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#20 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#21 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#22 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#23 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#24 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#25 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#26 {main}
"} {"hostname":"mautic-web","pid":3775}
```
- Saved a trigger without publishing, then clicked the toggle within the edit screen to publish, press save, and a warning flash shows with this error in the logs:

```
[2023-02-14 19:21:37] mautic.CRITICAL: Uncaught PHP Exception ErrorException: "PHP Warning - Undefined array key "eventName"" at /var/www/html/app/bundles/PointBundle/Model/TriggerModel.php line 356 {"exception":"[object] (ErrorException(code: 0): PHP Warning - Undefined array key \"eventName\" at /var/www/html/app/bundles/PointBundle/Model/TriggerModel.php:356)
[stacktrace]
#0 /var/www/html/app/bundles/PointBundle/Model/TriggerModel.php(356): Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler->handleError(2, 'PHP Warning - U...', '/var/www/html/a...', 356)
#1 /var/www/html/app/bundles/PointBundle/Model/TriggerModel.php(166): Mautic\\PointBundle\\Model\\TriggerModel->triggerEvent(Array, Object(Mautic\\LeadBundle\\Entity\\Lead), true)
#2 /var/www/html/app/bundles/PointBundle/Controller/TriggerController.php(358): Mautic\\PointBundle\\Model\\TriggerModel->saveEntity(Object(Mautic\\PointBundle\\Entity\\Trigger), false)
#3 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(458): Mautic\\PointBundle\\Controller\\TriggerController->editAction('1', '')
#4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(159): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('edit', '1', 0, '')
#5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#6 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#7 /var/www/html/app/AppKernel.php(105): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#8 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#9 /var/www/html/app/middlewares/HSTSMiddleware.php(35): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#10 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\HSTSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#16 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#17 {main}
"} {"hostname":"mautic-web","pid":3775}

```

- Editing a trigger and deleting one of the events, I can't save. Then I try to undo delete and this error shows in the logs:

```
[2023-02-14 19:23:58] mautic.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "sessionId" does not exist." at /var/www/html/app/bundles/PointBundle/Views/Event/generic.html.twig line 14 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"sessionId\" does not exist. at /var/www/html/app/bundles/PointBundle/Views/Event/generic.html.twig:14)
[stacktrace]
#0 /var/www/html/vendor/twig/twig/src/Environment.php(358) : eval()'d code(57): __TwigTemplate_33346734a014cee993c36bc89e092408e33dfe52f520a3ffbe8165b97205c52f->{closure}()
#1 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_33346734a014cee993c36bc89e092408e33dfe52f520a3ffbe8165b97205c52f->doDisplay(Array, Array)
#2 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\\Template->displayWithErrorHandling(Array, Array)
#3 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\\Template->display(Array)
#4 /var/www/html/vendor/symfony/twig-bridge/TwigEngine.php(54): Twig\\Template->render(Array)
#5 /var/www/html/vendor/symfony/templating/DelegatingEngine.php(41): Symfony\\Bridge\\Twig\\TwigEngine->render('MauticPointBund...', Array)
#6 /var/www/html/vendor/symfony/framework-bundle/Controller/ControllerTrait.php(213): Symfony\\Component\\Templating\\DelegatingEngine->render('MauticPointBund...', Array)
#7 /var/www/html/app/bundles/PointBundle/Controller/TriggerEventController.php(375): Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController->renderView('MauticPointBund...', Array)
#8 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(458): Mautic\\PointBundle\\Controller\\TriggerEventController->undeleteAction('3', '')
#9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(159): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('undelete', '3', 0, '')
#10 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#11 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/www/html/app/AppKernel.php(105): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /var/www/html/app/middlewares/HSTSMiddleware.php(35): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\HSTSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#16 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#18 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#19 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#20 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#21 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#22 {main}
"} {"hostname":"mautic-web","pid":3775}
```

- Cloning a trigger loses all the events associated with it - only the details are retained
- Pagination is not working in the Triggers section - I have 6 triggers, set the pagination to 5 and nothing happens: https://watch.screencastify.com/v/0dj2n7XIBeD1avZFuMAT

**Comment by JoshuaEstes** [comment]
@RCheesley 

> On Triggers, selecting events > add to integration, I am not able to cancel the popup

Only way I was able to reproduce this error was to select **Push contact to integration** and not select an integration. Resolved https://github.com/mautic/mautic/pull/11968/commits/67150b6f00e2aed91680c96145eb39435cf674d2

> Saved a trigger without publishing, then clicked the toggle within the edit screen to publish, press save, and a warning flash shows

This is another one that I cannot seem to reproduce.

> Editing a trigger and deleting one of the events, I can't save. Then I try to undo delete and this error shows

Resolved https://github.com/mautic/mautic/pull/11968/commits/8a3de504fdabf31cccd76f390b71f818a5e1baad

> Cloning a trigger loses all the events associated with it - only the details are retained

Seems to happen on 5.x as well. I'm not sure how deep the rabbit hole would go on this one. I tried to see if this was something that could be done pretty quick, but looks like it's going to take a little effort.

> Pagination is not working in the Triggers section - I have 6 triggers, set the pagination to 5 and nothing happens

Resolved https://github.com/mautic/mautic/pull/11968/commits/469c91f26c553d928b04523b00b131c8d837c58d

**Comment by mabumusa1** [comment]
@JoshuaEstes may you please increase it code coverage?

**Comment by mabumusa1** [comment]
@allcontributors please add @sdoering for userTesting

**Review by alexhammerschmied — COMMENTED** [review]
- [ ] clone doesn't clone events for triggers
- [ ] global search gives unclear message (see screenshot)

Screenshot 2023-02-15 at 16 10 40

**Comment by JoshuaEstes** [comment]
@alexhammerschmied 

> clone doesn't clone events for triggers

This is a known issue and has been discussed Reference: https://github.com/mautic/mautic/pull/11968#issuecomment-1430668206

>  global search gives unclear message (see screenshot)

This is a known issue and happens on all branches.

---

I added these to the known issues in the description as well

**Review by mabumusa1 — APPROVED** [review]
I tested this PR, I think it is good to go

**Comment by mabumusa1** [comment]
@RCheesley may you please take a final look at this PR, I think it is good to merge. If you agree with the few comments above, let's merge it, please

**Review by RCheesley — APPROVED** [review]
All the issues I previously reported are now resolved and the only issues left are those already called out in separate issues to be addressed.

Great work and thanks to everyone who has helped with the testing! 🚀

**Comment by RCheesley** [comment]
@all-contributors please add @alexhammerschmied for userTesting

**Pull request merged**
