### PR TITLE
Blank theme if no theme exists

### PR DESCRIPTION
**Pull request by lukassykora**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
If the template is removed for email or landing page, the blank theme should be selected.

#### Steps to test this PR:
1. Remove template from the code
2. Check if blank template is selected

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10154"></a>

### CODE REVIEW

**Comment by npracht** [comment]
Hi @lukassykora can you please rebase your PR against `features` branch please ?

**Review by npracht — COMMENTED** [review]
I tried to reproduce the issue on `feature` branch. I can see that when I edit the email with removed template, it has no theme selected but i can still edit it and save it. It generates no error.

Did you see the same behaviour ?

**Comment by RCheesley** [comment]
Hi there,

Thank you for your contribution!

As we have released Mautic 4 now, the 3.x version is out of active support and therefore will not receive any further bug fixes or features.

If this PR is still relevant to Mautic 4, please either 

- Rebase on the 4.0 branch (for bug fixes) or the 4.x branch (for features and enhancements), or 
- Close this PR and make a fresh one on the correct branch.

If it is no longer relevant to Mautic 4, please close the PR.

Thanks in advance!

**Comment by RCheesley** [comment]
@escopecz can you please rebase this to 4.x as it's based on the Acquia fork and I haven't got write access. Thanks!

**Comment by escopecz** [comment]
@RCheesley It's rebased. It was conflicting with https://github.com/mautic/mautic/pull/9189 so I did my best to merge the 2 together. I used the config option `theme_email_default` from Kuzmany's PR and used it in this one as well.

**Review by jos0405 — APPROVED** [review]
Works as expected, thank you for creating this!

**Review by mabumusa1 — APPROVED** [review]
it works as expected. tested on gitpod

**Comment by automatyzuj** [comment]
I must ask - why blank theme and not HTML editor? The current blank theme has a big problem with not working CSS, which is thrown at the end of the email. Consequently, after removing theme, custom html will be completely broken.

**Comment by jos0405** [comment]
@lukassykora 
Maybe this is causing the bug mentioned in the forum above?

**Comment by escopecz** [comment]
Yes, fixed in https://github.com/mautic/mautic/pull/11221

**Pull request merged**
