### PR TITLE
Fix Batch select on list causes arrow to disappear

### LINKED ISSUE #13705: Batch select on list causes arrow to disappear
### Mautic Version

5.0.x series

### Way of installing

I cloned the Mautic repo (not recommended or supported)

### PHP version

8

### What browsers are you seeing the problem on?

_No response_

### What happened?

Noticed when batch-rebuilding forms that when you select multiple then the arrow at the topmost check box disappears (assume it goes white) which isn't so helpful:

https://app.screencastify.com/v3/watch/aHM9rtVdEumL5JckGvuO

### How can we reproduce this issue?

Step 1: select multiple forms
Step 2: Notice that the arrow which denotes there's some function you can perform from the topmost checkbox disappears.

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #13705 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Forms
3. Create one
4. Go back to the list
5. Click on the check all checkbox to select multiple forms
6. Notice that the arrow which denotes there's some function you can perform from the topmost checkbox keeps visible.

### CODE REVIEW

**Review by RCheesley — APPROVED** [review]
This is much better and addresses the issue flagged.

Thanks @andersonjeccel

**Comment by andersonjeccel** [comment]
@shinde-rahul We need a test here to fix the dropdown bug

**Review by shinde-rahul — APPROVED** [review]
Thanks @andersonjeccel.

Works as expected!!!

**Review by escopecz — APPROVED** [review]
I see no issue with the simple code changes 👍

**Pull request merged**
