### PR TITLE
Enable code coverage reports with Codecov

### PR DESCRIPTION
**Pull request by dennisameling**
This PR is not touching Mautic as a product, but rather the CI pipeline. 

After discussion with @RCheesley @npracht ([after initial discussion in the Trello board](https://trello.com/c/I4qWCnQi/34-add-code-coverage-report-to-mautic-repo)), we decided to start by implementing Codecov as the provider that will parse our coverage report XMLs. Given the fact that the lack of code coverage insights is quite a long-lasting and urgent issue, we fast-forwarded this.

If you are reading this and want to suggest a different approach, please do so in the #t-product team [on Slack](https://www.mautic.org/slack).

### CODE REVIEW

**Review by RCheesley — APPROVED** [review]
An important and much needed step towards a more stable Mautic. Thank you for looking into this and getting it implemented! :rocket:

**Review by npracht — APPROVED** [review]
🚀

**Comment by escopecz** [comment]
I'm wondering whether it has any advantage to run the coverage report on all PHP versions. Maybe one is enough? It would speed up the other one.

**Comment by dennisameling** [comment]
@escopecz Agree it's probably best to do the coverage report on just one PHP version. Would you run it on 7.2 or 7.3 then? Probably won't really matter. Happy to provide a PR some time next week for that

Before Codecov: https://travis-ci.org/github/mautic/mautic/builds/701628297
After Codecov (few mins slower): https://travis-ci.org/github/mautic/mautic/builds/702168027

**Comment by escopecz** [comment]
@dennisameling check https://github.com/mautic/mautic/pull/8954 when you get a minute.

**Pull request merged**
