### PR TITLE
Added live lead list update feature

### PR DESCRIPTION
**Pull request by alanhartless**
This adds a "live mode" to inject newly added leads to the top of a list/grid.  It can be activated by the Live button next to the batch delete button.  When activated, it'll do an ajax request every 5 seconds to check for new leads and inject them to the top of the list/grid. It should honor the current search filter.  It of course will not honor the ordering as the leads are simply injected to the top of the list and highlighted to signify it's a new lead.

### CODE REVIEW

**Comment by drmmr763** [comment]
So I tested this using dev mode. It worked but had an issue that once I inserted a new lead via a form submit, it kept returning that lead each time the JS ran. 

[img]https://www.evernote.com/l/ACqVvVpZgDpOHa8Q58XS-j2t8aSXwUvx0msB/image.png[/img]

**Comment by alanhartless** [comment]
@drmmr763 Can you use the console and watch the data attributes of the live button? Each ajax return is suppose to update that with the latest lead ID so that existing ones aren't reinfected.  See if that data attribute is updated and then included in the ajax request's data.

**Comment by alanhartless** [comment]
@drmmr763  NM, I'm reproducing it.

**Comment by alanhartless** [comment]
@drmmr763 Okay, try that.

**Comment by drmmr763** [comment]
+ test worked great now!

**Comment by dbhurley** [comment]
Vote +1

**Pull request merged**
