### PR TITLE
Fix campaign looping issue

### LINKED ISSUE #11061: Cron Job doesn't finish after update to 4.2.1
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

After migrate from 4.1.2 to 4.2.1 the jobs campaigns:rebuild and campaigns:update does never ends. 

When executed from console the process gets 100% but keeps summing and never ends. 

Sorry, it's in Spanish:

Recuperando contactos para la campaña 47
3 total de contacto(s) a ser agregados en lotes de 300
 1102/1102 [============================] 100%^C

It means:
Retreaving contacts for campaign 47
3 contacts to be adder in groups of 300
 1102/1102 [============================] 100%^C

The log reports this:

[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 7369 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 12782 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 12884 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 7369 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 12782 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 12884 could not be added to campaign ID 47. 
[...] this sequence repeats for many lines. 

I have checked than those contacts are already in the campaign. 

I have tried  bin/console m:a:g and didn't work
mautilc/s/update/schema reports schema is up to date
doctrine:migration:migrate reports nothing to migrate 
doctrine:schema:update --dump-sql reports errors:

> In AbstractMySQLDriver.php line 128:
> 
>   An exception occurred while executing 'ALTER TABLE maujs_oauth2_accesstokens CHANGE client_id c
>   lient_id INT UNSIGNED NOT NULL, CHANGE user_id user_id INT UNSIGNED DEFAULT NULL, CHANGE token
>   token VARCHAR(191) NOT NULL, CHANGE scope scope VARCHAR(191) DEFAULT NULL':
> 
>   SQLSTATE[HY000]: General error: 1832 Cannot change column 'client_id': used in a foreign key co
>   nstraint 'FK_5DD8E68219EB6921'
> 
> 
> In Exception.php line 18:
> 
>   SQLSTATE[HY000]: General error: 1832 Cannot change column 'client_id': used in a foreign key co
>   nstraint 'FK_5DD8E68219EB6921'
> 
> 
> In PDOConnection.php line 132:
> 
>   SQLSTATE[HY000]: General error: 1832 Cannot change column 'client_id': used in a foreign key co
>   nstraint 'FK_5DD8E68219EB6921'

### How can we reproduce this issue?

I'm not sure how to reproduce this in a clean installation. 

### Relevant log output

```shell
The log reports this:

[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 7369 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 12782 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 12884 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 7369 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 12782 could not be added to campaign ID 47.  
[2022-04-07 20:43:04] mautic.DEBUG: CAMPAIGN: Contact ID 12884 could not be added to campaign ID 47. 
[...] this sequence repeats for many lines.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/issues/11061

#### Description:

Ugly looping issue while campaign rebuild use with `Allow contacts to restart the campaign `

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Add to segment two contacts by filter not manually
3. Create campaign with segment
4. Rebuild segment 
5. Then manually remove from campaign one contact
6. Then rebuild campaign 
7. See rebuild looping
8. After PR should work properly

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11318"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
Please add tests. This is very fragile feature and in order to stabilize it so another fix won't break this again we need to have it covered with good functional tests.

**Review by volha-pivavarchyk — DISMISSED** [review]
Works as described. The condition leading to an infinite loop is handled by this PR 
image

Works before:
image

Adding tests would be good to check the conditions for selecting contacts when the campaign is built.

**Comment by RCheesley** [comment]
Will this need to be rebased on 4.4 as a bug fix?

**Comment by RCheesley** [comment]
@kuzmany will you be able to add tests so that we can get this PR merged into the next patch release (end of August)?

**Comment by adiux** [comment]
Would be great if we can get this in the next release. Anything I can do?

**Review by ghost — COMMENTED** [review]
What have I done:

Point 1: to reproduce Issue, I opened mautic without the PR:
++1. opened: https://gitpod.io/#https://github.com/mautic/mautic
++2. Logged in with user admin and pass mautic

Point 2: Add to segment two contacts by filter not manually
++3. created 3 contacts, assigned a tag to two of them
++4. created a segment with filter: not empty tag

Point 3: Create campaign with segment
++5. created a campaign from this segment, and added the action to add another tag

[only to test the console - my first run :)]
++6. in console run: `ddev exec bin/console cache:clear --env=dev` ; Result: [OK]

Point 4: Rebuild segment
=> I suppose is meant: Update the segment, so run command:
++7. `ddev exec bin/console mautic:segments:update`

> Rebuilding contacts for segment 1
> 2 total contact(s) to be added in batches of 300
>  2/2 [============================] 100%
> 0 total contact(s) to be removed in batches of 300
> 2 contact(s) affected

Point 5: Then manually remove from campaign one contact
=> any contact had been assigned to the campaing
=> so I run:
++8. `ddev exec bin/console mautic:campaigns:update`

> Rebuilding contacts for campaign 1
> 2 total contact(s) to be added in batches of 300
>  2/2 [============================] 100%
> 0 total contact(s) to be removed in batches of 300

++9. now removed one contact manually from the campaign
20220908 212536-Contacts _ ionut2@yahoo com - _ Mautic — Mozilla Firefox

Point 6: Then rebuild campaign
=> I missed the thing, that a campaign can be updated and rebuild and are two sepparate commands, so I run
++10. `ddev exec bin/console mautic:campaigns:update`

> Rebuilding contacts for campaign 1
> 0 total contact(s) to be added in batches of 300
> 0 total contact(s) to be removed in batches of 300

=> then I saw that rebuilding the campaign has its own command, so I run
++11. `ddev exec bin/console mautic:campaigns:rebuild --campaign-id 1`

> Rebuilding contacts for campaign 1
> 0 total contact(s) to be added in batches of 300
> 0 total contact(s) to be removed in batches of 300

Point 7: See rebuild looping
=> no loop. What do I miss? Should have I did not have to run the mautic:campaigns:update, but only mautic:campaigns:rebuild ?


PS: after ++3 clicked on Companies and then clicked on Segments => resulted in this message that I cannot evaluate (I clicked ok and refreshed the page):
20220908 210020-Companies _ Mautic — Mozilla Firefox

**Review by escopecz — APPROVED** [review]
👍

**Comment by carukc** [comment]
The above states that this was included in the 4.4.3 milestone but I do not see it in the list anymore.

Does this mean that it will NOT be included in 4.4.3?

If so, can we apply the patch to an instance of 4.4.2?  We are at a complete standstill due to this issue.  None of our campaigns will work unless we manually kill the campaign update script.

Is there another workaround?

**Comment by RCheesley** [comment]
It's merged and will be in the next release. You're probably looking at open PRs only if it's not showing 😁

To apply the fix check the files changed and apply those changes to your Mautic instance (take a backup first) and clear the cache etc.

**Comment by escopecz** [comment]
~~@carukc what list do you mean? 4.4.3 hasn't been released yet. This will be included in 4.4.3 release.~~

**Comment by escopecz** [comment]
Ah, wait, I know where you come from: https://github.com/mautic/mautic/issues/11061#issuecomment-1247889421

Yes, this will not be in 4.4.3, but can easily be rebased to a new PR against 4.4 branch, tested and released in 4.4.3.

**Comment by RCheesley** [comment]
Ahh yes sorry I didn't look at the branch it was merged into! @carukc if you need this in your current instance we would need someone to make the PR on the relevant branch (4.4) to be included in the upcoming bugfix. Do you have anyone who might be able to do this?

**Comment by carukc** [comment]
Yes... it looks like it was added as a milestone for 4.4.3 6 days ago and then later the milestone was modified... if you look at the list of closed issues in the 4.4.3 milestone then this issue is not present which led me to the conclusion that it would not be included.

"[escopecz](https://github.com/escopecz) added this to the [4.4.3](https://github.com/mautic/mautic/milestone/96) milestone [6 days ago](https://github.com/mautic/mautic/pull/11318#event-7393451489)"

Yes, I may have someone who should be able to help with this.  I will check to see if he can create a PR for us.

Thanks

**Comment by ludovicfourrage** [comment]
Hello, could this PR be implemented on 4.4.7?

I'm currently experiencing the issue in 4.4.7 with multiple campaigns that have "Allow contacts to restart the campaign" on.
I am using the --max-contacts=1000 flag to the cron which allows the script to continue past it, but I'm not sure if the campaign update still works on these campaigns or ignores them?

A comment on either point would be welcome. Thank you!

**Pull request merged**
