### PR TITLE
Add dynamic content to the Email Builder in MJML mode

### LINKED ISSUE #10240: Dynamic Content is not possible for Mjml Emails
Currently, dynamic content is only enabled for HTML emails. We should enable it for MJML emails too

### PR DESCRIPTION
**Pull request by adiux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          |  no
| New feature/enhancement? (use the a.x branch)      |  yes
| Deprecations?                          |  no
| BC breaks? (use the c.x branch)        |  no
| Automated tests included?              |  no
| Related user documentation PR URL      | no
| Related developer documentation PR URL | in the code
| Issue(s) addressed                     | Fixes #10240

#### Description:

Makes the existing Dynamic Content block available in MJML. 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a new MJML E-Mail (e.g. Brienz theme)
3. Drag the Dynamic Content block to the canvas and configure it
4. Save and Close
5. Preview the E-Mail in the HTML Preview: Default content should be shown
6. Send a Test Email: Default content should be shown
7. Send a real segment or campaign email and check in the E-Mail client to see if the parameters worked as expected. Either the default or the variant should be shown

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10782"></a>

### CODE REVIEW

**Comment by kuzmany** [comment]
@adiux I do not see DC token in builder.  Do I make something wrong?

image

**Comment by RCheesley** [comment]
I also had the same problem as mentioned above - after applying the PR, clearing my browser cache and Mautic cache, in dev mode, I am not seeing the Dynamic Content block in the builder. @adiux any advice?

**Comment by bradycargle** [comment]
Same holds true for me. No Dynamic Content block in the builder

**Comment by kuzmany** [comment]
@adiux we waiting for response. We want it to 4.2 🥇

**Comment by adiux** [comment]
@kuzmany can we look at it on Friday?

**Review by kuzmany — DISMISSED** [review]
Works!
Brilliant

**Review by bradycargle — APPROVED** [review]
All working as expected for me! Nice job

**Review by kuzmany — APPROVED** [review]

**Comment by ghost** [comment]
I've got problem with this. After any save I see new: {dynamiccontent="Dynamic Content (id)}

image
image

And with next dynamic content:
image
Mautic 4.2
PHP Version 7.4.28
Edge

**Pull request merged**
