### PR TITLE
Contact email validation

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
Validation of email not check so strict as we need. We are able to save for example : 
`{test@test.com}`.
Mautic already have service to validation of email. This PR added it as constraint validator.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create contact
3. Then edit it with email `{test@test.com}`
4. Without PR contact is edited without error
5. After PR  you receive error
image

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10273"></a>

### CODE REVIEW

**Review by npracht — CHANGES_REQUESTED** [review]
@kuzmany i don't know if it is me the issue, but with ddev, your PR does not solve the issue:
Capture d’écran 2021-08-20 à 09 56 05


_NB: i cleared cache and generated assets._

**Comment by kuzmany** [comment]
@npracht your email address  is valid format 

image


https://verifalia.com/validate-email

This PR talkin about `{test@test.com}` and this kind of addresss

**Review by npracht — DISMISSED** [review]
Okayyyyyy 🚀 
Capture d’écran 2021-08-20 à 17 11 19

**Review by RCheesley — DISMISSED** [review]
Thanks for the PR @kuzmany - confirmed the issue and the resolution when the PR is applied. Just a code style issue to be addressed and code review, then we are good to merge. 

Can you please rebase onto 4.x and we can aim to get this in the 4.2 release at the end of February. Thanks!

**Review by PierreAmmeloot — APPROVED** [review]

**Comment by biozshock** [comment]
After applying the PR the email address `test@test.com` is valid. Probably second argument is missing https://github.com/mautic/mautic/pull/10273/files#diff-53aa680948bc7ab48f301356468088ec78e162d6de9a1a87565d7cb53df5cc9bR38

**Comment by kuzmany** [comment]
@biozshock It's correct we do not want check DNS validation, because it depend on connection and can make troubles. 
We just validate syntax like  `{test@test.com}`

**Comment by kuzmany** [comment]
@biozshock DNS check is in campaign like condition `Has valid address`

**Review by RCheesley — CHANGES_REQUESTED** [review]
While this did work for me, it made some strange behaviours in the quick add feature.

Take a look here: https://watch.screencastify.com/v/KXoO5ZdMhUDXCJLZsAAj

It seems to be loading up the regular screen for creating a new contact, within the quick-add modal, definitely not desired behaviour.

I'm not sure if this is as a result of this PR, or if it's something we already have as a bug.

**Comment by biozshock** [comment]
@RCheesley same issue on clean installation of latest 4.x
@kuzmany Okay, then i'd approve this pr. The validator is called and developers may add an even subsciber to validate the email more strictly.

**Comment by kuzmany** [comment]
@RCheesley That issue is not related to the PR. If you mark firstname as required and then try submit quick add window, it's same result. You have to create new issue

**Review by RCheesley — APPROVED** [review]
OK have added the separate issue, otherwise this should be GTG! 🚀

**Pull request merged**
