### PR TITLE
[TPROD-399]: Contact merger should not use repository::clear.

### PR DESCRIPTION
**Pull request by biozshock**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ x ]
| Automated tests included?              | [ z ] 

#### Description:
Remove deprecated repository::clear.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a unique field for Lead.
3. Create 2 leads with same unique field.
4. Run `mautic:contacts:deduplicate:ids` command.
5. Check two leads have merged into one.

### CODE REVIEW

**Comment by escopecz** [comment]
@biozshock this is good but the `$em->clear()` method is called in many other places in the code base. Do you intend to create one PR for each usage?

**Comment by biozshock** [comment]
@escopecz if you want i can do all in one PR.

**Comment by escopecz** [comment]
That's tricky :) How about 1 PR per bundle? Meaning somehow split the big task into manageable chunks.

**Review by escopecz — APPROVED** [review]
I think this is the correct change. The repos should not be cleared in this place as there are other operations on the same entity that follow. And it removes a deprecation.

**Pull request merged**
