### PR TITLE
WIP Add initial batch of Cypress E2E tests (from Acquia's QE team)

### PR DESCRIPTION
**Pull request by RCheesley**
⚠️ 🚧  This is a WIP PR 🚧  ⚠️ 

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes :tada:
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | Coming soon, WIP: [https://docs.google.com/document/d/13r8k1x4C1v4Y5-0rXbzGJ5i7ksa47qFpv5YnczwAh3o/edit?usp=sharing](https://docs.google.com/document/d/13r8k1x4C1v4Y5-0rXbzGJ5i7ksa47qFpv5YnczwAh3o/edit?usp=sharing)
| Issue(s) addressed                     | N/A

#### Description:

This PR adds a basic set of end-to-end tests that can be run to check the features and tasks within Mautic as if a real user was going through the steps within the application.

It uses the Cypress framework. We aim to integrate this into our CI process in due course.  The public dashboard is [here](https://dashboard.cypress.io/projects/1urw52).

Huge thanks to @AkshayHUkire @Mufeez and team for writing these tests and helping us to develop the E2E testing framework!

#### CI (Continuous Integration):

For any CI-related questions feel free to ping @dennisameling. This PR adds the following to the CI pipeline:
- Install and configure Apache at `http://localhost` (because Cypress needs to run its tests against an actual webserver)
- Install Mautic using the `bin/console mautic:install` command
- Install and configure Cypress, then run the tests against the Mautic instance at `http://localhost`
- Every run uploads artifacts (videos + screen shots), which makes it very easy to debug things. Example: https://github.com/mautic/mautic/actions/runs/364790301

#### Steps to test this PR:
1. Follow the docs linked above to set up Cypress
2. Configure your environment
3. Run tests!

### CODE REVIEW

**Comment by RCheesley** [comment]
Done a bunch of work to fix the incorrect selectors and other parts which were causing the tests to fail. 

I'm now getting them passing locally, however as soon as I push them up to Cypress the last part (searching and deleting) is failing with an error about the selector being detached from the DOM. 

Can't reproduce it locally so may need some help to figure out a workaround!  Dashboard: https://dashboard.cypress.io/projects/ozaou3/runs

**Comment by dennisameling** [comment]
@RCheesley any update on this one? 10/13 tests are finishing successfully, so we're almost there 🚀 

One thing that I'd like to hear your opinion on: currently, the Cypress test suite takes 22m to run. It looks like we can't enable parallel tests on PRs, since GH doesn't expose secrets to PR runs (which makes sense in terms of security). Do we want to have Cypress run on each and every PR?

What I'd like to suggest instead is the following:
- When a PR is created, automatically add a label `needs-cypress-test` so we know it needs a Cypress test later on
- Add [this GH action](https://github.com/marketplace/actions/pull-request-comment-trigger) which allows us to manually trigger Cypress on a PR (e.g. when we're sure a PR is complete and all other tests are passing). It could be that a PR has dozens of commits in it over time, then having to run Cypress on every commit is expensive. We'd just have to put a comment like `@ci/cypress` and it will start a Cypress run.
- DO run Cypress on every commit to the `features`, `3.2`, etc. branch - this is the case e.g. when a PR is merged. Parallel tests should then be enabled automatically 🧙🏼 

As an alternative, we could also start only with the last one in the list above, but it will just be a bit trickier as we'll find out about potential problems only after a PR is already merged.

**Comment by RCheesley** [comment]
> @RCheesley any update on this one? 10/13 tests are finishing successfully, so we're almost there 🚀

I have a bunch more tests to add but have been a bit swamped and need to set this up locally again to do that.

I think your suggestion is a good one to run the tests on command - we will need to add that to the triage team/release lead procedures and make sure that it is documented!

**Comment by RCheesley** [comment]
@dennisameling something seems wonky with the GH Action install mautic step - the tests are failing because it has not completed setup:

Add new local asset -- before all hook Perform login (failed)

Will need to see if we have to bring over changes from the other actions in core maybe?

**Comment by dennisameling** [comment]
Yep, that's due to the recent bug we fixed in Mautic's CLI installation - we now have to add `--force` to the installation command for the installation to succeed. Let me add that now!

Update: done in https://github.com/mautic/mautic/pull/9338/commits/33341c70d06fda50547f09ff8b6021b34c2d3bac

image

**Comment by dennisameling** [comment]
@RCheesley I just read the Cypress docs and saw it's possible to [preserve cookies using a RegExp](https://docs.cypress.io/api/cypress-api/cookies.html#Preserve-RegExp). That's great news, because Mautic's session cookie name is a unique string every time, so we can't hardcode it. Instead, I now took the approach to preserve **all** cookies in https://github.com/mautic/mautic/pull/9338/commits/13db2c2e962f30ec25533af50ea429c54616fd05. That should do the trick! 🚀

**Comment by RCheesley** [comment]
I have fixed the issue of the cron paths being different locally to the CI pipeline by:

* Adding an environment variable to cypress.env.json which defaults to that required by GH Actions (https://github.com/mautic/mautic/pull/9338/commits/5f7573f317e2b1e56ace4fb0d84fa10a6e30e59b)
* Set the variable (https://github.com/mautic/mautic/pull/9338/commits/1f49404be7f16952a78f56668d99bc0d3c045bb9#diff-c6e8d4c072858750828f765275f06b8c5b594f9deb6029acb5c8b1c5456efa3cR23) in the files where a cron task needs to run and use that variable to execute the cron (https://github.com/mautic/mautic/pull/9338/commits/1f49404be7f16952a78f56668d99bc0d3c045bb9#diff-c6e8d4c072858750828f765275f06b8c5b594f9deb6029acb5c8b1c5456efa3cR166)

🚀  🎉  Getting closer!

**Comment by RCheesley** [comment]
Closed in favour of #9851

**Pull request closed without merging**
