### PR TITLE
Segment date filtering can handle relative times

### PR DESCRIPTION
**Pull request by bradjones1**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Replaces #9784

#### Description:

Follow-on to #9784

#### Steps to test this PR:

TBD

### CODE REVIEW

**Comment by bradjones1** [comment]
This is a rebase on 4.4 (since I believe this to be a bugfix) and I also found that the TZ handling here is incorrect. I'm not 100% sure about the current date-only handling, but I think that is probably incorrect as well from the perspective of taking a "local" time and comparing it to the UTC date in the database.

This kind of slop is acceptable when you've only got to be within a day of correct, but relative times like hours or minutes is much more sensitive to TZ comparison. I found that the existing code generated a local-formatted time to compare to the db, which would be off by 0-24 hours, depending on the TZ. So I have changed this to explicitly use UTC if it is a relative comparison. I didn't touch the behavior, otherwise, because that would be a BC break?

**Comment by RCheesley** [comment]
@cla-bot check

Thanks for the PR @bradjones1 and welcome to the community!

If it's a bug fix can you please make a duplicate PR in the 5.x branch so that we can get it merged into both 4 and 5 when it is tested?

Testers will need step by step instructions on how to reproduce the bug and test the fix, please add them (you may be able to copy from issues/PRs from before).

**Comment by jos0405** [comment]
I'm excited to test this.

**Comment by bradjones1** [comment]
I'm not sure if it's a blocker here, or how to perform such validation, but it's worth noting that this field will take a value like `-12 hours` and not work; there are no plurals allowed. `-12 hour` does the trick.

AFAICT this is MySQL handling the string instead of like, `strtotime()` so I'm not sure if there's a library or regex that can handle this kind of validation in the form. But it's definitely possible to easily misconfigure.

**Comment by jos0405** [comment]
Testing steps are missing, but I assume:
- check if relative filters work
- check if 1 day is really 24h difference
- check with using different time zones

**Review by jos0405 — APPROVED** [review]
Tested with different variations, also changed the timezones.
Works well.

image

**Comment by escopecz** [comment]
Please fix the failed CI and create a duplicate PR against the 5.x branch. We cannot merge this unless we'll have that duplicate so this bug fix won't be missing the the upcoming Mautic 5.

**Comment by kuzmany** [comment]
Original code was from me and as I said from that PR, it was not work properly.
We have new solution for timezone relative segment filter WIP status at the moment https://github.com/mautic/mautic/pull/11835

**Comment by escopecz** [comment]
Ok, I will close this PR so it is obvious that it should not be tested.

**Pull request closed without merging**
