### PR TITLE
Process email queue lock

### PR DESCRIPTION
**Pull request by chandon**
Please answer the following questions. 

| Q | A |
| --- | --- |
| Bug fix? | Y |
| New feature? | N |
| Related user documentation PR URL | N |
| Related developer documentation PR URL |  |
| Issues addressed (#s or URLs) | #1737 #2215 |
| BC breaks? | N |
| Deprecations? | N |

**Note that all new features should have a related user and/or developer documentation PR in their respective repositories.** 
#### Description:

Avoid process **mautic:emails:send** to be run twice.
--force option can bypass this new check
#### Steps to test this PR:
1. Run php app/console mautic:emails:send & twice at the same time from console
2. The second process should return "Process already running."
#### Steps to reproduce the bug:

see #2215

### CODE REVIEW

**Comment by chandon** [comment]
Only if you use 1 computer, see 
http://symfony.com/doc/current/components/filesystem/lock_handler.html#usage

**Comment by escopecz** [comment]
I'm not sure if this has anything to do with this PR, because I don't see any reason for it in the added code, but when turn on the email queue, send a segment email which has 3 contacts in it, I receive only one email after I trigger the command.

I repeated the same steps on current staging and the email was sent also only to one contact out of 3. I guess there might be some issue with doNotContact even though I don't see it in the contact details.

I repeated the test when the queue switched off and I got all 3 emails. That's weird.

Another issue I noticed is that if I change the queue settings, the command does not work until I clear the cache. Doesn't matter how many times I save the configuration.

Fellow testers, do you also have this issues?

I think this PR can be merged. The issues described above are not related with it :+1:

**Comment by alanhartless** [comment]
As a side note - I had no idea this feature existed in Symfony. This is the intent of the Mautic\CoreBundle\Command\ModeratedCommand. I'm thinking we should use one or the other though - or maybe both by updating ModeratedCommand to leverage Symfony's built in lock() support. I'm not immediately sure which is the better implementation, although I'm leaning towards Symfony's lock() over encoding/decoding a json file as we are. The only main benefit of the encoded json file is that it has a "override lock" built in if the time goes over a specified amount of time.

**Comment by dongilbert** [comment]
+1, This did work as described, but I did have the cache issue that @escopecz was seeing.

**Comment by chandon** [comment]
up ?

**Comment by chandon** [comment]
@escopecz  no chance to be in 2.3 ? it was in 2.1.1, 2.2 milestone ...

**Comment by alanhartless** [comment]
@chandon I'm currently working on merging this technique with #2453 and plan to get it into 2.3.

**Comment by chandon** [comment]
@alanhartless thanks

**Comment by alanhartless** [comment]
@chandon please test #2998. You'll still get credit for the technique.

**Pull request closed without merging**
