### PR TITLE
Fix contact batch api for single id value

### PR DESCRIPTION
**Pull request by rahuld-dev**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          |[x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [x] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
API endpoint: /api/contacts/batch/* - It works only if the ids value contains at least one comma ['id' => '1,2,3'].
It is not working with single id value. ['id' => '1'].

#### Steps to reproduce the bug:
1. Open postman
2. Create a request for contacts batch delete api with single id [Ex. https://your.mautic.net/api/contacts/batch/delete?ids=1 ]
3. Click on send.
4. Verify the response - Contact is not deleted for requested Id.

#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2. Follow the steps to reproduce the bug.
3. Verify the response - Contact should deleted for requested Id.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10700"></a>

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
This is very clear, simple and tested change

**Comment by biozshock** [comment]
Tested the PR. Works as expected and fixes the issue.

**Comment by RCheesley** [comment]
@all-contributors please add @rahuld-dev for code

**Comment by RCheesley** [comment]
@all-contributors please add @biozshock for userTesting

**Pull request merged**
