### PR TITLE
Add segment activity log + fix Company log

### PR DESCRIPTION
**Pull request by hluchas**
| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | n
| Related developer documentation PR URL | n
| Issues addressed (#s or URLs) | n
| BC breaks? | n
| Deprecations? | n

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Added segment activity log. I've found bug in company logging. That is fixed in this PR.
Added unit tests for company and segment logging.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. On company delete action it was producing log entry with type "field". Fixed to type "company".
2. Actions such as add/edit/delete segment was not logged.

#### Steps to test this PR:
1. Delete some company and check last record in audit_log table.
2. Add/edit/delete segment and check latest audit_log table rows.

#### List deprecations along with the new alternative:
None.

#### List backwards compatibility breaks:
None.

### CODE REVIEW

**Comment by mleffler** [comment]
This has been code reviewed and has had two test passes from the Mautic Inc team.

**Comment by mleffler** [comment]
Yes - for straightforward fixes like this (I think I marked a handful), where Mautic Inc has had two test passes and a code review, I moved to Ready to Commit.  For others, I marked as one test pass (even though we did two), because I thought someone from outside of Mautic Inc should take a look.  Happy to have the review, and if you feel every PR needs two totally separate people testing, I am totally fine with all of your judgment on that.

**Comment by npracht** [comment]
@mleffler i feel good with that on my side. Nevertheless, the Github processes requires that there is at least 1 person with write access on the repository that approves the PR (with the feature review of GH).
Several options:

1. You get the writing rights and use the review feature of GH.
2. You ask the testers from your team (hoping that one has the rights) to review themselves
3. We see with DB if we'd like to change those rules to be changed.

What do you think ? @dbhurley maybe you have an opinion ?

**Comment by Woeler** [comment]
@mleffler Ah, alright I didn't know that. Alright I'll keep that in mind when I see you add this label. Makes it easier for all of us :)

**Pull request merged**
