### PR TITLE
[WIP] Test Mautic against Composer v2

### PR DESCRIPTION
**Pull request by dennisameling**
When running `composer install`, the following warning shows up:

```
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is about to be released and the older 1.x releases will self-update directly to it once it is released. To avoid surprises update now to the latest 1.x version which will prompt you before self-updating to 2.x.
```

This PR is to test with Travis against Composer v2, to see if any issues will arise.

### CODE REVIEW

**Comment by dennisameling** [comment]
Just tried with the new Composer version locally (`composer self-update --preview`) and getting the following errors:

```bash
dennis@mautic3-web:/var/www/html$ composer install
The "ocramius/package-versions" plugin was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "robloach/component-installer" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - ocramius/package-versions is locked to version 1.4.2 and an update of this package was not requested.
    - ocramius/package-versions 1.4.2 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - robloach/component-installer is locked to version 0.2.3 and an update of this package was not requested.
    - robloach/component-installer 0.2.3 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 3
    - robloach/component-installer 0.2.3 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - helios-ag/fm-elfinder-bundle 9.3.2 requires robloach/component-installer ~0.2 -> satisfiable by robloach/component-installer[0.2.3].
    - helios-ag/fm-elfinder-bundle is locked to version 9.3.2 and an update of this package was not requested.

ocramius/package-versions only provides support for Composer 2 in 1.8+, which requires PHP 7.4.
If you can not upgrade PHP you can require composer/package-versions-deprecated to resolve this with PHP 7.0+.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
```

Looks like we need to update `helios-ag/fm-elfinder-bundle` to [at least version 10](https://packagist.org/packages/helios-ag/fm-elfinder-bundle), so that the dependency on `robloach/component-installer` is removed. 

I'll have a look at this later, so that we can fix this for Mautic's 3.2 release 👍

**Comment by RCheesley** [comment]
Thanks for this, I saw that Composer 2 potentially brings some significant performance boosts!

**Comment by dennisameling** [comment]
Problem: `helios-ag/fm-elfinder-bundle` version 10+ requires Symfony 4.4 or higher 🙈 we'll only be able to go to Symfony 4.4 in May 2021 with the release of Mautic 4... 

```
Problem 1
    - helios-ag/fm-elfinder-bundle[10, ..., 10.0.4] require symfony/framework-bundle ^4.4 || ^5.0 -> found symfony/framework-bundle[v4.4.0, ..., v4.4.15, v5.0.0, ..., v5.1.7] but it conflicts with your root composer.json require (~3.4.0).
    - Root composer.json requires helios-ag/fm-elfinder-bundle ~10 -> satisfiable by helios-ag/fm-elfinder-bundle[10, ..., 10.0.4].
```

I'll check more later, for now I downgraded Travis to Composer 1.10 (https://github.com/mautic/mautic/pull/9331 and https://github.com/mautic/mautic/pull/9332)

**Comment by RCheesley** [comment]
Ah, darn! I've added this PR to the M4 milestone - at least we know where we are with it!

**Comment by dennisameling** [comment]
Mautic 4 will add support for Composer v2 due to the dependency [mentioned above](https://github.com/mautic/mautic/pull/9315#issuecomment-716174652). The following PR already includes the support for Composer v2: https://github.com/mautic/mautic/pull/9409. Therefore closing this one.

**Pull request closed without merging**
