### PR TITLE
Tests for #11767.

### PR DESCRIPTION
**Pull request by biozshock**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ x ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ x ] 

#### Description:
Added tests for #11470. Complimentary PR for #11767 for 4.4 branch.

#### Steps to test this PR:

1. See GH actions are good.

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks so much @biozshock 🤗

**Comment by RCheesley** [comment]
Looks like it needs some PHPSTAN love according to the checks!

**Comment by RCheesley** [comment]
Can we push this to the 5.x branch as well please? Thanks!

**Review by escopecz — APPROVED** [review]
This PR does not add only tests but also changes the code slightly. I consider most of the changes for the better. But this will require additional testing which wouldn't be the case if only tests would be added.

From code review perspective I give 👍 

Thank you!

**Comment by escopecz** [comment]
@npracht @kuzmany could you please test Hubspot with these changes if it works for you?

**Review by RCheesley — APPROVED** [review]
Tested the Hubspot integration and I was able to add the integration, configure it, run the sync cron jobs and also to push to integration in a campaign.

GTG 🚀

**Comment by escopecz** [comment]
@clabot check

**Comment by escopecz** [comment]
[clabot:check]

**Comment by escopecz** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@biozshock I think this one also needs to be raised on 5.x? I didn't see anything mentioned in the activity above for a companion PR but maybe I missed it!

**Comment by biozshock** [comment]
@RCheesley won't this be merged into 5.x later?

**Comment by RCheesley** [comment]
Yes - if you make a PR on the 5.x branch. We don't do back-merges any more as it creates hundreds of conflicts.

**Comment by RCheesley** [comment]
https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#choose-the-right-branch have a look here - the docs are updated with the new strategy but haven't got around to updating the PR template yet!

**Pull request merged**
