### PR TITLE
Enqueue Integration

### PR DESCRIPTION
**Pull request by ASKozienko**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? |N
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | N
| Deprecations? |N 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR brings an integration with Enqueue in. It provides advanced messaging capabilities, well tested, already supports many popular transports, configurable with Mautic UI and so on. 

Looking forward to getting your feedback on it

#### Steps to test this PR:
1. Checkout this PR
2. Run composer install
3. Configure Enqueue on Web UI.
4. Use it the same way you use other queues.

### CODE REVIEW

**Comment by npracht** [comment]
@dbhurley should we target that for core or require that as external plugin/bundle we could offer as another repo in mautic.org ?

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@ASKozienko it looks like this needs a bit of work to resolve the conflicts and make the PR Mautic 3.x compatible - are you able to pick this up?

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
As there has been no activity on this PR in the past 6+ months I am going to close it. If you would like to pick it up again in the future please create a new PR and link to this one in the description.

**Pull request closed without merging**
