### PR TITLE
Render help text for form fields

### PR DESCRIPTION
**Pull request by volha-pivavarchyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR provides rendering the help message option for from fields.  A call to the [form_help](https://symfony.com/doc/current/form/form_customization.html#reference-forms-twig-help) function for the form_row and form_start blocks are added.
To use it, the `help` option needs to be added to form field.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.This PR is difficult to test because the `help` option must be added to the form fields. Therefore, a code review is needed.

### CODE REVIEW

**Comment by escopecz** [comment]
@volha-pivavarchyk can you please describe the use case? If it's not testable, do we need it? Is it for plugins? How would anyone use it? How does it look like when it's used? Do you have a screenshot?

**Comment by volha-pivavarchyk** [comment]
@escopecz This allows to define a help message for the form field, which is rendered below the field. It will look like [here](https://symfony.com/doc/current/form/form_customization.html#form-rendering-functions). 

Use cases:
 1. Providing field descriptions. E.g., in a registration form, a help message can be used to explain the password requirements such as minimum length, special character requirements, etc.
 2. Offering input examples. E.g., a help message can be included for a date field that provides an example in the format "DD/MM/YYYY."
 3. Clarifying field purpose. E.g. a help message can be used for a field for the user's address to explain that the address is needed for shipping purposes.

E.g. we've added a description for the dynamic content field on how to write it. This is very easy to reach it by just adding the `help` options to the form field.

The following code leads in a display as shown in the screenshot
```
    $builder->add(
       'content',
       TextareaType::class,
       [
           'label'      => 'mautic.dynamicContent.form.content',
           'label_attr' => ['class' => 'control-label'],
           'attr'       => [
                'tooltip'              => 'mautic.dynamicContent.form.content.help',
                'class'                => 'form-control editor editor-advanced editor-builder-tokens',
                'data-token-callback'  => 'email:getBuilderTokens',
                'data-token-activator' => '{',
                'rows'                 => '15',
            ],
            'required' => false,
            'help'     => $this->templating->getTemplating()->render('DynamicContentBundle:DynamicContent:explain.html.php'),
            'help_html' => true,
            'help_attr' => [
                'class' => 'control-label',
             ],
         ]
      );
```
image

**Comment by mabumusa1** [comment]
@volha-pivavarchyk thanks for this PR, please notice that we removed templating engine, so the code sample above will not work since it is using PHP template and using the PHP rendering engine

**Review by escopecz — APPROVED** [review]
@volha-pivavarchyk I see. Mautic uses tooltips for the same purpose but I understand this adds an option for more prominent (all time visible) help messages and/or messages with formatting. Thanks for the link to the docs.

@mabumusa1 I understood what Volha meant to say from her code example. Yes. it should be a twig template nowadays. But I'm OK with adding this improvement 👍

**Comment by volha-pivavarchyk** [comment]
@mabumusa1 @escopecz  Thank you for your comments. Sorry, I used the example from v4. 
In reality, we use extensions to modify core forms. That's why I changed our code a bit to make it more informative.

**Pull request merged**
