### PR TITLE
Minor fix to form submission

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Just minor to code 
 
Steps to reproduce: 
1. Create focus with form
2. See source code of preview and start of tag `<form`
3. You should see something like `mauticform<?php echo $formName ?>` on input hidden  line

Steps to test:
1. Repeat all steps
2: See source code and see correct name of hidden input (mauticform_formalias_focus_id)

### CODE REVIEW

**Comment by alanhartless** [comment]
I'm not able to reproduce this. focusId is appended to all the forms with the token via this code https://github.com/mautic/mautic/blob/4b46c63e08ce8907c195e0cbb7c20d41dadf5f77/plugins/MauticFocusBundle/Views/Builder/form.html.php#L117 although that code needs to have the php tags removed in the heredoc although it's cosmetic and doesn't affect function.

**Comment by kuzmany** [comment]
@alanhartless changed this PR to minor code

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by Maxell92** [comment]
@kuzmany,

I am not sure what this change should do. Could you provide us any description?

**Comment by kuzmany** [comment]
@Maxell92 before was <?php inside <?php
 and in source code you saw
mauticform<?php echo $formName ?>

after

mauticform_myformname

**Comment by Maxell92** [comment]
Yes, I can see this from a code. But I have no context to find out what this change should do and how to test it.

**Comment by kuzmany** [comment]
@Maxell92 added

**Comment by escopecz** [comment]
@kuzmany I got identical form IDs on staging and on your branch:

`id="mauticform_standaloneformwithemail_focus"`

So is the change only a syntax change or is it meant to also change the ID value?

To clear out some questions, after I applied your PR and cleared the Mautic cache, re-saved the Focus item and refreshed the page with the item to get the fresh HTML.

**Comment by kuzmany** [comment]
Closed, after merge with actually staging, no issue there.
Sorry guys :)

**Pull request closed without merging**
