### PR TITLE
Custom object export fix

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ N]
| New feature/enhancement? (use the a.x branch)      | [ Y]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ Y] 
| Related user documentation PR URL      | mautic/mautic-documentation#
| Related developer documentation PR URL | mautic/developer-documentation#
| Issue(s) addressed                     |  https://github.com/acquia/mc-cs-plugin-custom-objects/issues/303, https://github.com/acquia/mc-cs-plugin-custom-objects/issues/302

#### Description:

This is fixing the https://github.com/acquia/mc-cs-plugin-custom-objects plugin.

This PR is for feature which allows user to export customItems linked to contactIds.

#### Steps to test this PR:
1. create a custom object with any number of fields.
2. create any number of custom items for newly created custom object in step 1.
3. can link any number of custom items to contacts.(can link more than 1 contacts to any customItem).
4. beside new button in custom item list page , will view a button for export as csv, click on that.
5. Can check the email will receive a link to a file in zip format, click on the file, it will download the file. can view the contents and check with data we created in steps 1-3.

note: 
1. linkedContactIds will be comma separated, if the custom item is linked to multiple contact ids or will be empty if no contact id is linked. please check https://github.com/acquia/mc-cs-plugin-custom-objects/wiki/Import for format of csv file.

### CODE REVIEW

**Comment by escopecz** [comment]
@priyanshu2316 please resolve https://github.com/mautic/mautic/pull/11989#issuecomment-1434542200

**Comment by escopecz** [comment]
@kuzmany please check if this PR resolves https://github.com/acquia/mc-cs-plugin-custom-objects/issues/303, https://github.com/acquia/mc-cs-plugin-custom-objects/issues/302

**Review by kuzmany — APPROVED** [review]
Looks good to me. Just fix the ExitCode.php  namespace https://github.com/mautic/mautic/pull/11989/commits/cff7c428ca990e3393980f9ad3878902e9bb02c3

**Comment by escopecz** [comment]
Thanks! I'll create a duplicate PR for M5 so this can be merged to both versions.

**Comment by escopecz** [comment]
Here is the duplicate PR for M5: https://github.com/mautic/mautic/pull/11995

**Pull request merged**
