### PR TITLE
Added IP2Location.io Geolocation API Service

### PR DESCRIPTION
**Pull request by ip2location-com**
Added IP2Location.io geolocation API service as an alternative of existing IP2LocationAPI geolocation lookup.

### CODE REVIEW

**Comment by kuzmany** [comment]
@RCheesley @escopecz Not sure, but new providers should be added with a plugin by the marketplace.

**Comment by escopecz** [comment]
Agreed. Please wrap this new service to a new bundle and anyone can install it via the [Marketplace](https://docs.mautic.org/en/marketplace). Also, please do not add more tech debt to the `phpstan-baseline.neon` file and instead resolve the issues in the future pull requests.

**Comment by ip2location-com** [comment]
@escopecz Since mautic already using our services (IP2LocationBINLookup, IP2LocationAPILookup) as core bundle, can you add in IP2LocationIO as a core bundle as well?

**Comment by escopecz** [comment]
We've removed 3 core plugins in Mautic 5 and this will continue in the future. The aim is to have lean core and users can install plugins based on the custom features and service providers they choose. So the way we want to go is to extract all the IP2Location services as their own plugins.

**Pull request closed without merging**
