### PR TITLE
Fixed issue #2788

### PR DESCRIPTION
**Pull request by FlamesRunner**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | n
| Related user documentation PR URL | n/a
| Related developer documentation PR URL | n/a
| Issues addressed (#s or URLs) | 1
| BC breaks? | n
| Deprecations? | n

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description: Fixed issue 2788

### CODE REVIEW

**Comment by devcircus** [comment]
change ```#mautic_focus_index``` to ```'#mautic_focus_index'```
As that parameter is a string, it should be wrapped in single quotes.

**Comment by FlamesRunner** [comment]
@devcircus

Thanks. Looks like I confused my data types again :/

**Comment by FlamesRunner** [comment]
Oddly enough, it doesn't build. I'll pull changes from the top branch and try again.

**Comment by FlamesRunner** [comment]
This is no longer relevant as the change was already completed.

**Pull request closed without merging**
