### PR TITLE
TPROD-321 - NotificationBundle - Complete PHP Templates to Twig

### PR DESCRIPTION
**Pull request by JoshuaEstes**
This contains the existing PRs for the NotificationBundle along with all the final updates and changes to complete the upgrade of the NotificationBundle

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create or Edit a Campaign
3. Open the Campaign Builder
4. Verify that the action **Send mobile notification** can be added to the campaign
5. Verify that the action **Send web notification** can be added to the campaign

### CODE REVIEW

**Review by mabumusa1 — DISMISSED** [review]
- [X] Create  a mobile notification in a campaign 
- [X] Create a web notification in a campaign

**Comment by mabumusa1** [comment]
@JoshuaEstes would be great if can make all CI to green, we do not want these PRs to lower the coverage

**Comment by sdoering** [comment]
I was able to validate this and add both actions to a campaign. 

image

**Comment by mabumusa1** [comment]
@allcontributors please add @sdoering for userTesting

**Comment by mabumusa1** [comment]
@JoshuaEstes This PR is ready to be merged, we just need to increase the coverage. I think it is like three lines of code

**Comment by JoshuaEstes** [comment]
@mabumusa1 Updated

**Comment by RCheesley** [comment]
Uh oh - conflict to resolve @JoshuaEstes but should be quick I think, then we can go ahead and merge.

**Pull request merged**
