### PR TITLE
Capaign events with 0 delay ignore day of week restrictions

### PR DESCRIPTION
**Pull request by roboparker**
| Q                                      | A
| -------------------------------------- | ---
| Branch  | staging
| Bug fix  | yes
| New feature? | no
| Deprecations? | no
| BC breaks  | no
| Automated tests included? | yes
| Related user documentation PR URL | NA
| Related developer documentation PR URL | NA
| Issue(s) addressed | 

#### Description:
Campaign events with a 0 delay would ignore the day of week restrictions.

#### Steps to test this PR:
1. Load up this pr
2. Create a 0 delay event that restricts the days so that only the previous day of week is allowed.
3. When saving the event should not fire immediately

#### Other areas of Mautic that may be affected by the change:
None

#### List deprecations along with the new alternative:
No deprecations have been added

[//]: # ( As applicable: )
#### List of areas covered by the unit and/or functional tests:
1. Added many unit test and a few functional test.

A cleaner PR in favor of https://github.com/mautic/mautic/pull/11292

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11332"></a>

### CODE REVIEW

**Comment by roboparker** [comment]
@RCheesley You are correct in the other PR that this was an issue only present in out fork.

The only change this PR now makes is it exposes the DOW restrictions for all interval units.
The test are refactored to include a lot more tests and adjusted to match the community version.
The interval class includes a few extract method refactors

**Comment by roboparker** [comment]
The PR is now ready and no longer a draft.

**Review by escopecz — APPROVED** [review]
I see no problem in the code 👍 

Thank you Robert!

**Review by RCheesley — APPROVED** [review]
Works as expected - the tag I set to be assigned on a Monday is scheduled to be assigned next Monday and is not immediately applied.

Contacts _ Lewis Syed - Record Bar _ Mautic (4)

Thanks @diaboloshogunate - PR is good to go 🚀

**Comment by RCheesley** [comment]
This is based on 5.x but I think it is a bug fix (hence should be on 4.4) - up to you if we should merge it sooner and therefore rebase to 4.4, or just merge to the 5.0 alpha release which may be some time away.

**Comment by roboparker** [comment]
@RCheesley 5.0 makes more sense for this one imo

**Pull request merged**
