### PR TITLE
reprocess errored leads when the contact in mautic has been updated

### PR DESCRIPTION
**Pull request by mqueme**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
If a contact fails to push to the Salesforce integration it doesn't get reprocessed if the cause for that error was fixed in the contact record. This bug fix allows for that updated contact to be reprocessed

There was a bug also when trying to map the contact Id or Lead Id, when creating new leads it sends all fields to SF and SF query doesn't allow the Id to come in the query

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. run the Salesforce from the CLI, try to have a lead that will error the sync
2. you should see a record in the integration table marked as lead-error
3. try to update the lead to fix the erroring issue, the contact doesn't get updated
4. mapp Lead Id or Contact Id you should get an error when trying to run the CLI command or creating a Lead through the push through integration actions 

#### Steps to test this PR:
1. Run this PR and follow steps above...
2. after the contact gets updated it should be reprocessed when running the CLI command again.
3. With this PR the Id bug in the query should not continue to happen
#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by escopecz** [comment]
> run the Salesforce from the CLI, try to have a lead that will error the sync

@mqueme any hint on how to do that?

**Comment by mqueme** [comment]
@escopecz you can map the Lead Id field to something in Mautic and try to sync a new contact to SF, after this PR both errors should be resolved

**Comment by escopecz** [comment]
1. I configured the contact ID and lead ID mapping to some Mautic field.
2. Created a new Mautic contact.
3. Run the SF sync command. - No error appeared, the contact appeared in SF
4. Applied this PR, cleared the cache.
5. Updated the contact from 2. at Mautic
6. Run the SF sync again. - Update I made at Mautic was cleared to the previous state.

I tried 5. and 6. 2 more times, but the Mautic contact update is always cleared to the previous state and SF lead stays the same.

**Comment by alanhartless** [comment]
Closed in favor of #4094

**Pull request closed without merging**
