### PR TITLE
Minor UI updates

### PR DESCRIPTION
**Pull request by alanhartless**
## Description
This PR makes a few UI changes:

1. The connecting lines and arrows in the campaign builder were made thinner and smaller. 
2. Changes the apps link color to be Mautic blue by default and darken on hover (versus bootstrap default to lighten the primary color with primary on hover)
3. Fixed issue where Segments and Contacts did not turn gold on active
4. Moved assets and forms to a new Components menu item

## Steps to test

Apply the PR, clear Symfony's cache, then check the above areas in the UI. Use dev mode since prod assets are not updated.

### CODE REVIEW

**Comment by mqueme** [comment]
Assets menu doesn't turn gold either.

**Comment by alanhartless** [comment]
@mqueme Should be fixed.

This happens when the activeLink returned in the ajax response for a controller action does not match the ID of the menu item.

**Comment by dbhurley** [comment]
+1 works for me.

**Comment by escopecz** [comment]
Ahh, I hate it when it doesn't work only for me :/

I have this error message in the div where the left menu is:
```
 500 Internal Server Error - Notice: Undefined index: depth 

Symfony\Component\Debug\Exception\ContextErrorException
app/bundles/CoreBundle/Views/Menu/main.html.php (line #60):
app/bundles/CoreBundle/Views/Menu/main.html.php (line #60): at Symfony\Component\Debug\ErrorHandler -> handleError ( '8', 'Undefined index: depth', 'app/bundles/CoreBundle/Views/Menu/main.html.php', '60', array('view' => object(TimedPhpEngine), 'this' => object(TimedPhpEngine), 'app' => object(GlobalVariables), 'item' => object(MenuItem), 'options' => array('depth' => '', 'matchingDepth' => '', 'currentAsLink' => true, 'currentClass' => 'active', 'ancestorClass' => 'open', 'firstClass' => 'first', 'lastClass' => 'last', 'template' => 'MauticCoreBundle:Menu:main.html.php', 'compressed' => false, 'allow_safe_labels' => false, 'clear_matcher' => true, 'menu' => 'main'), 'matcher' => object(Matcher), 'child' => object(MenuItem), 'showChildren' => false, 'liAttributes' => array('class' => 'last nav-group'), 'isAncestor' => false, 'linkAttributes' => array(), 'extras' => array(), 'url' => 'javascript:void(0);', 'labelAttributes' => array('class' => 'nav-item-name'), 'labelPull' => ' pull-left', 'levelClass' => 'nav-submenu collapse') )
vendor/symfony/templating/Symfony/Component/Templating/PhpEngine.php (line #159): at require ( 'app/bundles/CoreBundle/Views/Menu/main.html.php' )
vendor/symfony/templating/Symfony/Component/Templating/PhpEngine.php (line #84): at Symfony\Component\Templating\PhpEngine -> evaluate ( object(FileStorage), array('app' => object(GlobalVariables), 'item' => object(MenuItem), 'options' => array('depth' => null, 'matchingDepth' => null, 'currentAsLink' => true, 'currentClass' => 'active', 'ancestorClass' => 'open', 'firstClass' => 'first', 'lastClass' => 'last', 'template' => 'MauticCoreBundle:Menu:main.html.php', 'compressed' => false, 'allow_safe_labels' => false, 'clear_matcher' => true, 'menu' => 'main'), 'matcher' => object(Matcher)) )
vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Templating/TimedPhpEngine.php (line #51): at Symfony\Component\Templating\PhpEngine -> render ( 'MauticCoreBundle:Menu:main.html.php', array('item' => object(MenuItem), 'options' => array('depth' => null, 'matchingDepth' => null, 'currentAsLink' => true, 'currentClass' => 'active', 'ancestorClass' => 'open', 'firstClass' => 'first', 'lastClass' => 'last', 'template' => 'MauticCoreBundle:Menu:main.html.php', 'compressed' => false, 'allow_safe_labels' => false, 'clear_matcher' => true, 'menu' => 'main'), 'matcher' => object(Matcher)) )
vendor/symfony/templating/Symfony/Component/Templating/DelegatingEngine.php (line #49): at Symfony\Bundle\FrameworkBundle\Templating\TimedPhpEngine -> render ( 'MauticCoreBundle:Menu:main.html.php', array('item' => object(MenuItem), 'options' => array('depth' => null, 'matchingDepth' => null, 'currentAsLink' => true, 'currentClass' => 'active', 'ancestorClass' => 'open', 'firstClass' => 'first', 'lastClass' => 'last', 'template' => 'MauticCoreBundle:Menu:main.html.php', 'compressed' => false, 'allow_safe_labels' => false, 'clear_matcher' => true, 'menu' => 'main'), 'matcher' => object(Matcher)) )
app/bundles/CoreBundle/Menu/MenuRenderer.php (line #99): at Symfony\Component\Templating\DelegatingEngine -> render ( 'MauticCoreBundle:Menu:main.html.php', array('item' => object(MenuItem), 'options' => array('depth' => null, 'matchingDepth' => null, 'currentAsLink' => true, 'currentClass' => 'active', 'ancestorClass' => 'open', 'firstClass' => 'first', 'lastClass' => 'last', 'template' => 'MauticCoreBundle:Menu:main.html.php', 'compressed' => false, 'allow_safe_labels' => false, 'clear_matcher' => true, 'menu' => 'main'), 'matcher' => object(Matcher)) )
vendor/knplabs/knp-menu/src/Knp/Menu/Twig/Helper.php (line #89): at Mautic\CoreBundle\Menu\MenuRenderer -> render ( object(MenuItem), array('menu' => 'main') )
vendor/knplabs/knp-menu-bundle/Templating/Helper/MenuHelper.php (line #52): at Knp\Menu\Twig\Helper -> render ( 'main', array('menu' => 'main'), null )
app/bundles/CoreBundle/Views/LeftPanel/index.html.php (line #64): at Knp\Bundle\MenuBundle\Templating\Helper\MenuHelper -> render ( 'main', array('menu' => 'main') )
vendor/symfony/templating/Symfony/Component/Templating/PhpEngine.php (line #159): at require ( 'app/bundles/CoreBundle/Views/LeftPanel/index.html.php' )
vendor/symfony/templating/Symfony/Component/Templating/PhpEngine.php (line #84): at Symfony\Component\Templating\PhpEngine -> evaluate ( object(FileStorage), array('app' => object(GlobalVariables)) )
vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Templating/TimedPhpEngine.php (line #51): at Symfony\Component\Templating\PhpEngine -> render ( 'MauticCoreBundle:LeftPanel:index.html.php', array() )
app/bundles/CoreBundle/Views/Default/base.html.php (line #21): at Symfony\Bundle\FrameworkBundle\Templating\TimedPhpEngine -> render ( 'MauticCoreBundle:LeftPanel:index.html.php' )
vendor/symfony/templating/Symfony/Component/Templating/PhpEngine.php (line #159): at require ( 'app/bundles/CoreBundle/Views/Default/base.html.php' )
vendor/symfony/templating/Symfony/Component/Templating/PhpEngine.php (line #84): at Symfony\Component\Templating\PhpEngine -> evaluate ( object(FileStorage), array('app' => object(GlobalVariables), 'security' => object(CorePermissions), 'widgets' => object(Paginator), 'dateRangeForm' => object(FormView), 'currentRoute' => '/mautic-github/index_dev.php/s/dashboard') )
vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Templating/TimedPhpEngine.php (line #51): at Symfony\Component\Templating\PhpEngine -> render ( 'MauticCoreBundle:Default:base.html.php', array('app' => object(GlobalVariables), 'security' => object(CorePermissions), 'widgets' => object(Paginator), 'dateRangeForm' => object(FormView), 'currentRoute' => '/mautic-github/index_dev.php/s/dashboard') )
vendor/symfony/templating/Symfony/Component/Templating/PhpEngine.php (line #94): at Symfony\Bundle\FrameworkBundle\Templating\TimedPhpEngine -> render ( 'MauticCoreBundle:Default:base.html.php', array('app' => object(GlobalVariables), 'security' => object(CorePermissions), 'widgets' => object(Paginator), 'dateRangeForm' => object(FormView), 'currentRoute' => '/mautic-github/index_dev.php/s/dashboard') )
vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Templating/TimedPhpEngine.php (line #51): at Symfony\Component\Templating\PhpEngine -> render ( 'MauticCoreBundle:Default:content.html.php', array('app' => object(GlobalVariables), 'security' => object(CorePermissions), 'widgets' => object(Paginator), 'dateRangeForm' => object(FormView), 'currentRoute' => '/mautic-github/index_dev.php/s/dashboard') )
vendor/symfony/templating/Symfony/Component/Templating/PhpEngine.php (line #94): at Symfony\Bundle\FrameworkBundle\Templating\TimedPhpEngine -> render ( 'MauticCoreBundle:Default:content.html.php', array('app' => object(GlobalVariables), 'security' => object(CorePermissions), 'widgets' => object(Paginator), 'dateRangeForm' => object(FormView), 'currentRoute' => '/mautic-github/index_dev.php/s/dashboard') )
vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Templating/TimedPhpEngine.php (line #51): at Symfony\Component\Templating\PhpEngine -> render ( 'MauticDashboardBundle:Dashboard:index.html.php', array('security' => object(CorePermissions), 'widgets' => object(Paginator), 'dateRangeForm' => object(FormView), 'currentRoute' => '/mautic-github/index_dev.php/s/dashboard') )
vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Templating/PhpEngine.php (line #82): at Symfony\Bundle\FrameworkBundle\Templating\TimedPhpEngine -> render ( 'MauticDashboardBundle:Dashboard:index.html.php', array('security' => object(CorePermissions), 'widgets' => object(Paginator), 'dateRangeForm' => object(FormView), 'currentRoute' => '/mautic-github/index_dev.php/s/dashboard') )
vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Templating/DelegatingEngine.php (line #57): at Symfony\Bundle\FrameworkBundle\Templating\PhpEngine -> renderResponse ( 'MauticDashboardBundle:Dashboard:index.html.php', array('security' => object(CorePermissions), 'widgets' => object(Paginator), 'dateRangeForm' => object(FormView), 'currentRoute' => '/mautic-github/index_dev.php/s/dashboard'), null )
vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Controller/Controller.php (line #108): at Symfony\Bundle\FrameworkBundle\Templating\DelegatingEngine -> renderResponse ( 'MauticDashboardBundle:Dashboard:index.html.php', array('security' => object(CorePermissions), 'widgets' => object(Paginator), 'dateRangeForm' => object(FormView), 'currentRoute' => '/mautic-github/index_dev.php/s/dashboard'), null )
app/bundles/CoreBundle/Controller/CommonController.php (line #96): at Symfony\Bundle\FrameworkBundle\Controller\Controller -> render ( 'MauticDashboardBundle:Dashboard:index.html.php', array('security' => object(CorePermissions), 'widgets' => object(Paginator), 'dateRangeForm' => object(FormView), 'currentRoute' => '/mautic-github/index_dev.php/s/dashboard') )
app/bundles/DashboardBundle/Controller/DashboardController.php (line #81): at Mautic\CoreBundle\Controller\CommonController -> delegateView ( array('viewParameters' => array('security' => object(CorePermissions), 'widgets' => object(Paginator), 'dateRangeForm' => object(FormView)), 'contentTemplate' => 'MauticDashboardBundle:Dashboard:index.html.php', 'passthroughVars' => array('activeLink' => '#mautic_dashboard_index', 'mauticContent' => 'dashboard', 'route' => '/mautic-github/index_dev.php/s/dashboard')) )
at Mautic\DashboardBundle\Controller\DashboardController -> indexAction ( )
app/bootstrap.php.cache (line #3054): at call_user_func_array ( array(object(DashboardController), 'indexAction'), array() )
app/bootstrap.php.cache (line #3016): at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '1' )
app/bootstrap.php.cache (line #3165): at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '1', true )
app/bootstrap.php.cache (line #2406): at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel -> handle ( object(Request), '1', true )
app/AppKernel.php (line #112): at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), '1', true )
index_dev.php (line #61): at AppKernel -> handle ( object(Request) )
```

**Comment by mqueme** [comment]
with this change we lost landing pages again

**Comment by alanhartless** [comment]
@mqueme Added back the landing page as root item.

@escopecz I'm not able to reproduce the `Undefined index: depth` notice and having a hard time finding why `depth` would not be set. I could add a catch in the template file but would rather solve it at the menu building stage.

Did you happen to clear your cache after applying the PR? The menu structure is cached since each bundle's config is cached. It's possible something old was causing it. If you did clear the cache and still getting it, could you try to drill down with die/var_dumps in https://github.com/mautic/mautic/blob/d9c5f14e057d266b6b7cf037bfc26a01ee203930/app/bundles/CoreBundle/EventListener/CommonSubscriber.php#L158-L158 to see which item (don't forget to drill down into `children` as well) does not have `['extras']['depth']` set?

**Comment by escopecz** [comment]
I'm pretty sure I cleared the cache twice to be sure it's not that. But when I try it now, it works as described and no error appears anywhere :+1:

**Pull request merged**
