### PR TITLE
[UX] Change bundles statuses from Published to Active

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
In this PR, we introduce a terminology update for bundles statuses to improve user experience. The status label “Published” has been revised to “Active,”. This consistency in terminology aids users in better understanding the status of features, streamlining their workflow. The modification is particularly beneficial for users managing campaigns, segments and webhooks etc, ensuring a cohesive and straightforward interface.

Based on https://community.mautic.org/assemblies/ux-ui-tiger-team/f/59/debates/4

These items will be affected:

- Segments
- Campaigns
- Focus items
- Points (Actions, Triggers)
- Stages
- Users
- Webhooks

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open something like Webhooks
3. Create a new
4. Look at the label

image

### CODE REVIEW

**Review by Esthertests — APPROVED** [review]
LGTM 
on prod
image

PR changes
image

**Review by RCheesley — COMMENTED** [review]
While I agree that Active might be a more user friendly term, I am not sure making a specific label for Webhooks is the right way to go with this.

Should we not rather change the general `form.isPublished` label to be Active instead, and fix this issue everywhere?

Or is there a valid reason why webhooks should use a different term to the rest of the application's published state label?

**Comment by Mike-Dropsolid** [comment]
> While I agree that Active might be a more user friendly term, I am not sure making a specific label for Webhooks is the right way to go with this.
> 
> Should we not rather change the general `form.isPublished` label to be Active instead, and fix this issue everywhere?
> 
> Or is there a valid reason why webhooks should use a different term to the rest of the application's published state label?

The idea is to change the Publish label to work in its specific context. It's not only for webhooks. Users, Dynamic content, tags, ... While Published does work best in some cases, active works better in other cases. But there's also "Available for use", ...

It's just the label of course. Backend it stays the same.

Documentation needs changing before we can merge this.

**Review by Mike-Dropsolid — APPROVED** [review]
Approving the idea. Documentation needs to be up-to-date to move on.

**Comment by andersonjeccel** [comment]
@Mike-Dropsolid @RCheesley User docs OK

https://docs.mautic.org/en/latest/configuration/settings.html?highlight=webhook%20publish#webhook-settings
https://docs.mautic.org/en/latest/channels/emails.html?highlight=webhook%20publish#webhook-bounce-management
https://docs.mautic.org/en/latest/configuration/cron_jobs.html?highlight=webhook%20publish#webhooks-cron-job
https://docs.mautic.org/en/latest/points/point_groups.html?highlight=webhook%20publish#webhooks
https://docs.mautic.org/en/latest/search.html?q=webhook+publish&check_keywords=yes&area=default#

Dev docs also OK
https://devdocs.mautic.org/en/5.x/webhooks/getting_started.html

**Review by LordRembo — CHANGES_REQUESTED** [review]
Purely checking for the info on Webhooks in the shared links, I am noticing the word 'Published' is used in at least one page, so there's some changes needed:

https://docs.mautic.org/en/latest/configuration/settings.html?highlight=webhook%20publish#webhook-settings
> If a Campaign or Webhook is automatically unpublished

and further:

> the User who created the unpublished Campaign or Webhook.

**Comment by RCheesley** [comment]
Please see the conversation in the related PR: https://github.com/mautic/mautic/pull/13502#issuecomment-1997438085

These PRs changing the terminology for the actions should be held until there is a clear direction from users of Mautic to change from a single term which is used across the platform, to bundle-specific terminology.

**Review by shinde-rahul — APPROVED** [review]
Code changes LGTM!!!

**Comment by andersonjeccel** [comment]
@escopecz Ready to commit
@RCheesley 
Docs OK https://github.com/mautic/user-documentation/pull/304

**Pull request merged**
