### PR TITLE
Fix search by company name

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for 4.0
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
If we coming  from companies list to contacts assigned to company, sometimes show more contacts like we expect. This PR fixed it

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Creat contacts
3. Create two companies `Mautic` and `Mautic inc` and assign one contact to each of them
4. Go to companies list
5. Click on 1 contacts  of `Mautic` company
6. You should see both contact from Mautic and Mautic inc company, but we expect just like one contact
7. After PR works properly

### CODE REVIEW

**Review by npracht — DISMISSED** [review]
much better 👍🏽

**Review by dadarya0 — DISMISSED** [review]
Nice job 👍 , Thank you
Working fine ,
@kuzmany  some checks are failing in build please fix that.

**Comment by RCheesley** [comment]
Looks like we need to bump up the test coverage slightly before we can merge this one @kuzmany - hopefully not too complicated! 🤞

**Comment by RCheesley** [comment]
Removing this from the milestone as it still needs test coverage to be improved. As soon as that is addressed we can merge into the next available release.

**Comment by kuzmany** [comment]
@RCheesley @npracht @dadarya0 I've changed method to search by company name after click on contact counts. Now we use standard operator "+company" what allow us search in strict mode without touch codebase.

Please re-test

**Comment by kuzmany** [comment]
Close favor to https://github.com/mautic/mautic/pull/10702/

**Pull request closed without merging**
