### PR TITLE
Fix issue with dynamic content showing '{dynamiccontent = "undefined"}' after re-opening email

### PR DESCRIPTION
**Pull request by irfanhanfi**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ 5.x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

This issue fixes the issue mentioned here - https://github.com/mautic/mautic/pull/13431#issuecomment-2039777272

#### Description:

The code `this.editor.setComponents(components);` triggers some events internally, resulting in the removal of dynamic contents and displaying `undefined`.

#### Steps to reproduce -
1. Create an Email - Channel >> Emails >> Create Email
2. Add a Dynamic Content block and set some values
3. Close the editor and reopen it using the Builder button
4. Issue - Dynamic Content is not editable and the popup does not open
5. Once you close and open it again, it shows "undefined"

Screenshot 2024-04-08 at 11 41 46 PM

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))

### CODE REVIEW

**Comment by LordRembo** [comment]
There is a 'remove' event that fires and removes the ID's from storage, when reopening a mail with a dynamic content block. The problem is in the repo for the preset for grapesjs which has [this similar ticket that I think has the same root cause](https://github.com/mautic/grapesjs-preset-mautic/issues/48).

My proposed PRs to [update GrapesJS](https://github.com/mautic/mautic/pull/13283), and [the dependent preset](https://github.com/mautic/grapesjs-preset-mautic/pull/49), also fixes that problem.

**Comment by LordRembo** [comment]
I made [a PR to resolve this issue via the grapesjs mautic preset](https://github.com/mautic/grapesjs-preset-mautic/pull/52), but it would be helpful if you could test that solution as part of [my GrapesJSBuilder update PR](https://github.com/mautic/grapesjs-preset-mautic/pull/49), so we can merge the big update at once.

**Comment by LordRembo** [comment]
I checked your PR, there's no conflict between both our fixes, just a check on another level. So I'm gonna leave it alone.

**Review by LordRembo — APPROVED** [review]
The code itself makes sense: the previous `setComponents` overrides the Components instead, which is less clean than removing them and adding them in. 
I guess this avoids some kind of caching issue which caused the stored block id to be targetted? I'd be interested to hear what you think went wrong with the 'remove' event (I think there's a bug in how the event is handled/the data is collected by GrapesJS itself), but in any case, this works.

**Comment by irfan-synerzip** [comment]
@LordRembo I don't believe there is anything wrong with the remove event. When we call setComponents, it triggers the remove event, which then removes the DynamicContent. My fix does not call those events when we set the components.

Although I haven't tested this, I believe that the approach mentioned in the linked pull request will also work  - https://github.com/mautic/grapesjs-preset-mautic/pull/52

If your GrapesJS upgrade works, then we can also proceed with that.

**Comment by LordRembo** [comment]
We'll see which gets merged first :D  I think this one has the best chance because the change is small and easy to test. Hopefully it gets picked up and approved on Open source Friday

**Comment by irfanhanfi** [comment]
One reason that we need this PR is that in the previous changes `components` has been removed from `grapesjs.init`. There are some functionalities for which we need component data to make some block initialization.

**Comment by RCheesley** [comment]
Hi folks, this would need to be based on the **5.x** branch for it to be merged in 5.1 or later, as we won't have any more releases on the 5.0 branch. Can you rebase it @irfanhanfi ?

**Comment by irfanhanfi** [comment]
> Hi folks, this would need to be based on the **5.x** branch for it to be merged in 5.1 or later, as we won't have any more releases on the 5.0 branch. Can you rebase it @irfanhanfi ?

I have rebased it.

**Comment by RCheesley** [comment]
Thanks @irfanhanfi - looks like a conflict to fix then we should be able to test.

**Review by LordRembo — APPROVED** [review]
All looking good now

**Comment by LordRembo** [comment]
I think we can close this now. A fix got merged alongside other PR's.

**Pull request closed without merging**
