### PR TITLE
Fix 500 error on contact API batch endpoint

### PR DESCRIPTION
**Pull request by escopecz**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | Y
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | /
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

There is a problem with the `PUT|PATCH api/contacts/batch/edit` when pushing one or more contacts with IDs that do not exist in Mautic anymore. It can happen if those contacts were deleted. Then the API returns:

```
{"errors":[{"message":"Looks like I encountered an error (error #500). If I do it again, please report me to the system administrator!","code":500,"type":null}]} 
```

And in the logs we can see this error:
```
Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Mautic\ApiBundle\Helper\BatchIdToEntityHelper::orderByOriginalKey() must be of the type array, object given, called in /app/bundles/ApiBundle/Controller/CommonApiController.php on line 819 in /app/bundles/ApiBundle/Helper/BatchIdToEntityHelper.php:94
```

Another but that the test discovered is bad SQL query param handling for in/notIn conditions.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Try to edit a contact via the `PUT|PATCH api/contacts/batch/edit` endpoint with ID that does not exist in the Mautic instance. For example ID of a contact you deleted.

You'll get the 500 error

#### Steps to test this PR:
1. Resend the API request once more

You'll get 201 (created) status code and the contact will be created as a new contact with new ID.

#### Other areas of Mautic that may be affected by the change:
1. The SQL fix can affect other parts of Mautic such as reports or segments.

[//]: # ( As applicable: )
#### List of areas covered by the unit and/or functional tests:
1. The `PUT|PATCH api/contacts/batch/edit` API endpoint with rubbish contact ID and with existing ID.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10724"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
Add the commits from this PR except the first one to https://github.com/mautic/mautic/pull/10724

**Comment by volha-pivavarchyk** [comment]
I can't reproduce the issue. 

I used 4.x branch to reproduce the bug. I tried to edit a contact via the PUT api/contacts/batch/edit endpoint with ID 4. That contact had been removed. I got the next result:
image

Using this PR, I got the same result.
image

**Comment by escopecz** [comment]
@volha-pivavarchyk I see. I found out that the same issue was fixed in https://github.com/mautic/mautic/pull/10065. I fixed it the same way at first, but when we deployed it it caused a BC break for our customers as it returned empty array of customers as JSON array `[]` but when the endpoint returns some contacts then it returns JSON object `{}`. That's why there was `ArrayObject` returned in case of no contacts at the first place. So https://github.com/mautic/mautic/pull/10065 fixed the problem but introduced a BC break. This PR fixes the problem and keeps the BC.

**Review by volha-pivavarchyk — DISMISSED** [review]
Works as described

**Review by mabumusa1 — DISMISSED** [review]
Tested locally with postman, works as expected, fixed error 500

**Pull request merged**
