### PR TITLE
Added merge contacts to contact edit API action 

### PR DESCRIPTION
**Pull request by kuzmany**
| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | n
| Related user documentation PR URL | n
| Related developer documentation PR URL | n
| Issues addressed (#s or URLs) | #3108
| BC breaks? | n
| Deprecations? | n

[//]: # ( Required: )
#### Description:
Added merge contacts to contact edit API.

#### Steps to test this PR:
1. Create contact with email address
2. Go to website with tracking code and clear cookies on tracking url and mautic url.
3. Add to website with tracking code edit  action https://developer.mautic.org/#edit-contact

```
if(isset($_COOKIE['mtc_id'])){
$contactApi->edit($_COOKIE['mtc_id'], $data);
}
```
4. See if older contact was marger with current mtc_id on the tracking site.
5. _Edit by @escopecz: Run the [API Library test](https://github.com/mautic/api-library/pull/105)_

~~Doesn't work for create action, logical.~~ _Edit by @escopecz: works for edit and create_

### CODE REVIEW

**Comment by iadj** [comment]
Absolute lifesaver. Works perfectly in production here.

**Comment by reachadam** [comment]
Wow, testing right now!!! Will report back at the end of the day.

**Comment by reachadam** [comment]
Ok done testing, its working again! Thank GOD! So with v2.6 coming any day now, I guess we will have to reapply this fix.

**Comment by reachadam** [comment]
Ok so after a day of using this, the results were not so good. It resulted in creation of duplicate contact records. Some as many as 10 all created at the same time.

**Comment by kuzmany** [comment]
Maybe  it's related to this PR  https://github.com/mautic/mautic/pull/2950

**Comment by kuzmany** [comment]
@escopecz conflicts resolved

**Comment by escopecz** [comment]
I tried to create a system test for it in [ContactsTest.php](https://github.com/mautic/api-library/blob/master/tests/Api/ContactsTest.php) to make sure the desired functionality will be tested in the future. I applied this PR added this to the test file method. Also the contact payload needs some email to test the merging successfully.
```
public function testMergingDuplicateContacts()
    {
        // Create contact A
        $response = $this->api->create($this->testPayload);
        $this->assertPayload($response);
        $contactA = $response[$this->api->itemName()];

        // Create contact B
        $response = $this->api->create($this->testPayload);
        $this->assertPayload($response);
        $contactBc = $response[$this->api->itemName()];

        $response = $this->api->edit($contactBc['id'], $this->testPayload);
        $this->assertPayload($response);
        $contactBe = $response[$this->api->itemName()];

        echo "<pre>";var_dump($contactA['id'], $contactBc['id'], $contactBe['id']);die("</pre>");
    }
```
The dump is:
```
int(4443)
int(4444)
int(4444)
```
If I check the Mautic database, the contact with ID 4443 exists as well as contact 4444. No contact was merged.
screen shot 2017-04-11 at 15 15 56
So is this PR not working as I thought it should or is there some problem with my test code?

Could you please finish the test method and PR it to the api-library repo? A note to the developer docs about contact merging will help many users. Could you please add it?

**Comment by kuzmany** [comment]
@escopecz updated. 
Before code merged just anounymous with old identified profile.
Now merge both cases. 
Test added to API https://github.com/mautic/api-library/pull/105/files

**Comment by escopecz** [comment]
I made some changes to the PR:
1. resource/speed optimization - do not fetch more contacts than needed
2. When creating a new contact, it firstly edited the existing contact (if any) and then it created another one. I added `return` on line 53 to end the method there.

I also update the [test](https://github.com/mautic/api-library/pull/105) with some assertions that really test this PR.

**Comment by dongilbert** [comment]
Api Library tests pass. +1

**Pull request merged**
