### PR TITLE
Fix IdentifyCompanyHelper  for unique fields of companies

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:

This is regression fix of Add support for unique fields for companies https://github.com/mautic/mautic/pull/9461

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create form with email and text field companyaddress1
3. Try submit
4. Return errror 
`mautic.CRITICAL: Uncaught PHP Exception Mautic\LeadBundle\Exception\UniqueFieldNotFoundException:`

After PR should works properly

### CODE REVIEW

**Review by RCheesley — DISMISSED** [review]
Thanks for the PR @kuzmany - confirmed the issue before applying the PR and when the fix is applied I was able to submit the information without error.

**Comment by RCheesley** [comment]
Looks like we need to bump up the test coverage according to Codecov - have just pulled in the latest from Features.

**Comment by kuzmany** [comment]
@RCheesley Unit tests added

**Comment by RCheesley** [comment]
Awesome, thanks @kuzmany ! Just needs a code review and we'll be good to go :) 🚀

**Review by npracht — APPROVED** [review]
@mohit-rocks could you please take a technical look at it (code review) ? From user side, this is working as expected.

**Review by mohit-rocks — APPROVED** [review]
The implementation looks good to me.
I'll merge it after CI run is complete.

**Pull request merged**
