### PR TITLE
Adding a new boolean option system setting to transliterate p…

### LINKED ISSUE #7525: Hebrew Page Title Tracking Error
## Bug Description

@escopecz I have an issue with Hebrew Language. After update to 2.15.1, Tracking URL is not storing original page title but a different not hebrew not english. Gibrish. 

Take a look at the screenshot. The original page been tracked is in Hebrew. Before update it worked fine. Now we have this strange behavior.  Any idea? 

hebrew error

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version |  7.0.32-4+ubuntu18.04.1+deb.sury.org+1
| Browser |  Chrome

### Steps to reproduce
1. Visit a page been tracked in Hebrew language
2. Open Contacts on Mautic 
3. See the page title been tracked
 
### Log errors
There are no error log related to this issue at Mautic.

### LINKED ISSUE #8984: Hebrew Page Title Tracking Error in Mautic 3
## Bug Description
The page titles are still in wrong names in Mautic 3.0.1, the issue has been opened since Mautic 2.15, see  [7525 ](https://github.com/mautic/mautic/issues/7525)

In the dicussion in [7525 ](https://github.com/mautic/mautic/issues/7525), it says the issue will be fixed in Mautic 3, but I still see the issue in Mautic 3.0.1 version:

image

| Q   | A
| --- | ---
| Mautic version | 3.0.1
| PHP version | 7.3
| Browser | Chrome

### Steps to reproduce
1.  Install Mautic track code at any non-english web page, such as Japanese, Chinese 
2. check the contact info and see page view events
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by Mohammad-Fayoumi**
…age titles

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | mautic/mautic-documentation#118
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | fixes #8984 fixes #7525 

#### Description: 
Transliteration of input for UTF8 characters was introduced in Mautic to prevent MySQL from failing when adding Cyrillic languages or emojis.

Now that Mautic 3 ships with UTF8mb4, we can make the Transliteration a "setting" under the Configuration of Mautic.

This new feature does the following:

Introduce a new checkbox option in Mautic Configuration as: "Transliterate page titles"
Add an if statement in PageModel.php to check if the option is on or not.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Test instructions:

Note: When enabling/disabling the setting please ensure that the cache is cleared.

Case 1: when the Transliterate page titles option is disabled then the page titles in the contacts page will be displayed in their native language, so if the title in Chinese then it will be displayed as-is in Chinese.

Case 1 example:
If the provided title is 你好，世界 then the expected title will be 你好，世界

Case 2: when the Transliterate page titles option is enabled then the page titles in the contacts page will be transliterated to the corresponding spelling in the English language, so if the title in Chinese then it will be transliterated to English.

Case 2 example:
If the provided title is 你好，世界 then the expected title will be ni hao, shi jie

Note: The same example with its values is used in the unit tests.

### CODE REVIEW

**Comment by RCheesley** [comment]
@Mohammad-Fayoumi thanks for making this PR - I believe that it resolves the bug reported in #8984 so I just added this to your description.

Could you take a look at the errors in Travis?

We will also need a small documentation update once we are ready to merge so that we can explain what the feature does to end-users.  [Here](https://github.com/mautic/mautic-documentation) is the docs repo and the [guide to contributing](https://docs.mautic.org/en/home/contributing).

**Comment by oalahmed** [comment]
Three unit tests have been added: one test for form config type (**class ConfigTypeTest**), two tests for the PageModelTest when page title transliteration enabled (**function testUtf8CharsInTitleWithTransletirationEnabled**) and when it's disabled (**function testUtf8CharsInTitleWithTransletirationDisabled**).

**Comment by RCheesley** [comment]
Thanks @oalahmed for adding the tests! We have a bit of a backlog in Travis at the moment due to the sprint over the last two days, so it might take a little while to process the checks!

Please can you make a PR to the documentation explaining what this setting is, and why you'd want to turn it on?

I think [this page](https://github.com/mautic/mautic-documentation/blob/master/pages/10.Components/04.Pages/01.Managing%20Pages/docs.en.md) is where you'd want to add the information.

Our docs styleguide can be found [here](https://docs.mautic.org/en/home/contributing).

It may be possible to find a couple of folk to test this over the weekend and sneak it into the 3.1 milestone if the checks all pass.

**Comment by oalahmed** [comment]
Thanks @RCheesley for adding this to [3.1.0](https://github.com/mautic/mautic/milestone/59) milestone.

Sure, I will make a new PR to the documentation and I will explain in it when transliterating page title option should be turned on/off.

**Comment by RCheesley** [comment]
@oalahmed @Mohammad-Fayoumi thanks for all the work. on this, it looks like there was an issue we're seeing with a few PR's that the rebase happened while some PR's were being merged, so the code coverage is a bit wonky. Can you possibly rebase against staging once more while we have a hold on PR's getting merged, so we can get the accurate report?

You will also need to add more detailed instructions in the PR description. Explain step by step how someone can see this in action, how to test the PR and what they should see happen, what they should test/look out for (e.g. they should thoroughly test landing pages in multiple languages, including those with A/B tests and with/without foreign characters (maybe give some examples of page titles they can use to force the behaviour to occur. 

That way you're helping folk who don't know about transliteration, multilingual and page titles and whatnot be able to test your PR thoroughly.

**Comment by RCheesley** [comment]
Hi folks, I am trying to test this but perhaps I am misunderstanding how to create page hit titles.

I created a few landing pages with different languages in the title - French, Greek, and Arabic.

I tried with the setting enabled, and disabled, and nothing is happening to how they are displayed in the contact event log:

Setting disabled:

screenshot-local mautic3-2020 08 16-16_40_04

Setting enabled:

screenshot-local mautic3-2020 08 16-16_41_07

So either I'm not doing it right, or the setting is not making the expected changes. Can someone please improve the test instructions if it's the former, or take a look if it's the latter? Thanks folks! Bumping to 3.2 so that we have time to thoroughly test this :)

**Comment by oalahmed** [comment]
Hi RCheesley,

I will take a look and update the instructions with the needed.

**Comment by RCheesley** [comment]
@oalahmed wonderful, many thanks!

**Comment by oalahmed** [comment]
After checking the issue, I enabled and then disabled **Transliterate page titles** option from the configuration page (/s/config/edit) and then I found that this option is not reflected directly to the contacts page, it seems caching issue. Although after clearing the site cache it took a couple of minutes and then it worked, as displayed in the below screenshot.


Mautic-transliterate-page-title


Actually, I'm not aware of how Mautic configuration caching works to give more details, however, I think the feature works properly.

 @RCheesley I'd like to have this feature released in the next milestone so could you please tell me what's remaining to achieve that.

Thanks in advance

**Comment by oalahmed** [comment]
**Test instructions:**

**Case 1:** when the **Transliterate page titles** option is **disabled** (in the configuration page /s/config/edit) then the page titles in the contacts page will be displayed in their native language, so if the title in Chinese then it will be displayed as-is in Chinese.

Case 1 example:
If the provided title is **你好，世界** then the expected title will be **你好，世界**

**Case 2:** when the **Transliterate page titles** option is **enabled** (in the configuration page /s/config/edit) then the page titles in the contacts page will be transliterated to the corresponding spelling in the English language, so if the title in Chinese then it will be transliterated to English.

Case 2 example:
If the provided title is **你好，世界** then the expected title will be **ni hao, shi jie**

**Notes:** 
- The cache should be cleared after enabling/disabling the option, this might take a couple of minutes before it's refelcted.
- The same example with its values is used in the unit tests.

**Comment by RCheesley** [comment]
Awesome thanks - I have added this to the PR test instructions!

**Comment by oalahmed** [comment]
Kindly note that the cache should be cleared after enabling/disabling the option. I added this note to the test instructions.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@Mohammad-Fayoumi could you take a look at the message above regarding your Git config?

@oalahmed to answer your question, in terms of getting this into the next feature release, as a Tier 2 PR we need to have:

- Thorough testing to ensure that it does what it’s expected to do and does not break anything else ❌ 
- Full unit/functional test coverage ✅ 
- Full documentation support if it’s a feature change/addition ❌ 
- Code review from 1 core team member ❌ 
- Full testing and approval by at least one community member (could be the person doing the code review, but should not be from the same company/organisation as the person submitting the PR as mentioned above) ❌ 
- All contributors signed the Contributors Agreement ❌ 

The next feature release is [3.2](https://github.com/mautic/mautic/milestone/66) at the end of November. 

I'd suggest joining in with some of the community testing initiatives (e.g. the pre-release sprints, product team on Slack, etc) as a way of getting to know other contributors in the community. We wrote about the next few that are coming up [here](https://www.mautic.org/blog/community/mautic-3-1-new-beginnings).

While features aren't our top priority for testing at this moment as the upcoming releases are bug fixes, we are trying to keep testing consistent over time. We'd very much appreciate help with this, and I'm sure that would also mean folk are more able to test your PR and give feedback as needed 👍

**Comment by moerazem** [comment]
@RCheesley what's the link to CLA to sign? Also, can an organization sign the CLA for all its contributors instead of individually (we did that when contributing to Google)?

**Comment by RCheesley** [comment]
@moerazem the link is here: https://www.mautic.org/contributor-agreement and it works on Github usernames, I do not believe that we presently have the capability for this to be signed at an organisational level (we only just implemented this system a few weeks ago, before that it was entirely manual!)

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by mabumusa1** [comment]
@oalahmed please sign the contributor agreement, this PR is valuable to have in the next release https://www.mautic.org/contributor-agreement

**Comment by RCheesley** [comment]
> @oalahmed please sign the contributor agreement, this PR is valuable to have in the next release https://www.mautic.org/contributor-agreement

It was signed - the label is applied so should be good to go on that front! :)

**Comment by moerazem** [comment]
Yes @mabumusa1! We're missing a review now. Would you like to review this to push it to the next step?

**Review by mabumusa1 — APPROVED** [review]
I tested this PR on arabic pages and worked as expected

**Comment by moerazem** [comment]
Thanks @mabumusa1.

@RCheesley - in regards to:

- Thorough testing to ensure that it does what it’s expected to do and does not break anything else ❌

We have been running a production installation (https://engage.vardot.com/s) and (https://mautic.forus.jo/s) with this patch and everything has been working well.
Knowing that the scope of this PR is only to change the why data is rendered (doesn't affect any data model, campaigns logic, emails, SMS, landing pages ...etc., or database entries) - the testing is really limited to verifying there are no PHP warning and no broken functionality in the contact's history.

I can confirm that the functionality has been tested in production installations and everything is working well.

**Comment by moerazem** [comment]
To summarize, I believe we're at this stage:

- Thorough testing to ensure that it does what it’s expected to do and does not break anything else ✅
- Full unit/functional test coverage ✅
- Full documentation support if it’s a feature change/addition ✅
- Code review from 1 core team member ❌
- Full testing and approval by at least one community member (could be the person doing the code review, but should not be from the same company/organisation as the person submitting the PR as mentioned above) ✅
- All contributors signed the Contributors Agreement ✅


Can you confirm @RCheesley?

**Comment by moerazem** [comment]
@RCheesley Can you help in what's for this PR to get moved forward?

**Comment by npracht** [comment]
Hi @Mohammad-Fayoumi ! As far as it is a PR introducing a feature, it cannot go into a patch release, it needs to wait a minor release. So next will be 3.2.0. At that time we'll do as much as we can to merge it if relevant :)

In the meanwhile, feel free to test pending PR with bug label, then we can merge them asap in 3.1.2.

Thanks !

**Comment by RCheesley** [comment]
Thanks for all the tests on this folks, with the 👍  from @mabumusa1 and @moerazem I'm good for us to merge this into 3.2.

**Pull request merged**
