### PR TITLE
[UI] Modals

### LINKED ISSUE #13164: Align modals to the design system
### Description
Modals in the application are currently not in alignment with the established design system, resulting in visual disparities and a lack of design consistency; our aim is to bring modals in line with the design system's standards.

The most part provides information about variables and things like this.

### Impact
Aligning modals with the design system will enhance the overall visual cohesiveness of the interface, ensuring a consistent and user-friendly experience when displaying critical information or interactions, ultimately improving user engagement and satisfaction.

## Tasks

- [ ] Quick add modal
- [ ] Information modals
- [ ] Notes modal
- [ ] Search for the other modals

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #13164 

## Description

Specifically:
- Makes overlays blurred when a modal is open
- Integrates with #13752 to ensure fields keep visible while on top of the modal background

| Before                                 | After
| -------------------------------------- | ---
|  image                                       |image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Categories > New > See white fields and blurred background

### CODE REVIEW

**Review by LordRembo — APPROVED** [review]
Code wise, looks good. The blur effect is a good idea for usability & accessibility. I've seen this being recommended in a recent accessibility review, following user tests.

**Comment by andersonjeccel** [comment]
@LordRembo Apple uses a shadow with blur effect in iOS for notifications that feels natural as this experience is close to what happens in our eyes when focusing on things

**Review by LeonOltmanns — APPROVED** [review]
Nice Improvement, really puts an emphasis on the modal and increases its visibility by alot.

**Comment by MojisolaaaO** [comment]
@andersonjeccel Nice job improving the visibility of the field! However, the buttons on the modal are purple, which doesn't match the color scheme in the UI design. [Here is a screenshot] (https://monosnap.com/file/taVpdpTV2IBffuAbAULULXMYhWpVnV)

**Comment by MojisolaaaO** [comment]
Nice job improving the visibility of the field! However, the buttons on the modal are purple, which doesn't match the color scheme in the UI design. 
[View screenshot attached](https://monosnap.com/file/taVpdpTV2IBffuAbAULULXMYhWpVnV)

**Comment by andersonjeccel** [comment]
@MojisolaaaO Hm, I'm a bit confused... Mautic's brand color is the same color you're showing on the screenshot. Could you provide more details?

**Comment by MojisolaaaO** [comment]
@andersonjeccel The color of the buttons in the screenshot does not match the color of the buttons in the description above; however, since it in line with Mautic's brand color, it is fine.

**Review by MojisolaaaO — APPROVED** [review]

**Comment by andersonjeccel** [comment]
@MojisolaaaO Oh, my PR only changed the modals, the buttons were redesigned through other PR :) 

Thanks for reviewing!

**Comment by andersonjeccel** [comment]
Well, this PR was merged in #13767 so I'll close it

**Pull request closed without merging**
