### PR TITLE
Update UPGRADE-PHP-TO-TWIG-TEMPLATES.md

### PR DESCRIPTION
**Pull request by LordRembo**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Added extra info about the Twig's `default` filter and how it handles FALSE

#### Steps to test this PR:
Check if the added lines make sense (includes reference link)

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by LordRembo** [comment]
The CLA was signed hours ago. Did it again for good measure.

**Comment by mabumusa1** [comment]
@cla-bot check

**Comment by LordRembo** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

Hi @LordRembo thanks for the PR and welcome to the community! 

As explained in the text from CLA Bot it's a manual process (we have to grab the signatory from a PDF file and add it to a list at this time). So sometimes that takes time if nobody has checked it yet.

All done now!

**Review by RCheesley — APPROVED** [review]

**Pull request merged**
