### PR TITLE
Site Url is validated in the UI to be a valid url

### PR DESCRIPTION
**Pull request by volha-pivavarchyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [:heavy_multiplication_x:]
| New feature/enhancement? (use the a.x branch)      | [:heavy_check_mark:]
| Deprecations?                          | [:heavy_multiplication_x: ]
| BC breaks? (use the c.x branch)        | [:heavy_multiplication_x:]
| Automated tests included?              | [:heavy_multiplication_x:] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR prevents saving the url field in the config form without a protocol. If the url value does not start with any protocol (e.g. https://) when submitting the configuration form, the `https` protocol will be prepended to the string.

image
is saved as
image

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open the configuration page.
3. Open System Settings and try to save the `Site URL` field without a protocol. E.g. `mautic.ddev.site`.
4. `https://mautic.ddev.site` is saved.

### CODE REVIEW

**Comment by mollux** [comment]
@volha-pivavarchyk I like the idea of this PR, and definitely makes sense to validate this.

but maybe it makes sense to look at it broader:

* There are multiple places in Mautic core that require urls containing a protocol, and where this not properly validated:
    * external assets
    * webhooks
* Symfony has a [form field `UrlType`](https://symfony.com/doc/5.4/reference/forms/types/url.html) that may be a better fit in general for all fields that should be an url (instead of the current `TextType` that used).
This type is already used in e.g. [`WebhookType`](https://github.com/mautic/mautic/blob/d4ef86f5eee2ae17265fc32e4a44d4b7efb7c8ad/app/bundles/WebhookBundle/Form/Type/WebhookType.php#L56)

So maybe we should make a custom field type that does the proper validation, instead of repeating this for every occurence in the codebase.

Does this make sense to you?

**Review by kuzmany — DISMISSED** [review]
👍

**Review by mollux — COMMENTED** [review]
@volha-pivavarchyk I like the idea of this PR, and definitely makes sense to validate this.

but maybe it makes sense to look at it broader:

* There are multiple places in Mautic core that require urls containing a protocol, and where this not properly validated:
    * external assets
    * webhooks
* Symfony has a [form field `UrlType`](https://symfony.com/doc/5.4/reference/forms/types/url.html) that may be a better fit in general for all fields that should be an url (instead of the current `TextType` that used).
This type is already used in e.g. [`WebhookType`](https://github.com/mautic/mautic/blob/d4ef86f5eee2ae17265fc32e4a44d4b7efb7c8ad/app/bundles/WebhookBundle/Form/Type/WebhookType.php#L56)

So maybe we should make a custom field type that does the proper validation, instead of repeating this for every occurrence in the codebase.

Does this make sense to you?

**Comment by volha-pivavarchyk** [comment]
@mollux Of course, it makes sense to me. It was a second solution to use `urlType`, but that's what I used. 
And it's a good idea to use one custom field type. I can improve this PR by implementing it here, if you don't mind.

**Comment by volha-pivavarchyk** [comment]
@mollux @kuzmany 

I changed the previous solution to use  the `UrlType` form field. Could you please take a look at this.

At first glance, using a custom UrlType seemed like the best solution. I analysed existing form types with url fields that may use UrlType. It doesn't seem to be the best solution anymore. Firstly, it uses a different set of options. Secondly, this is a Symfony field type, and we can just override it.

[WebhookType](https://github.com/mautic/mautic/blob/d4ef86f5eee2ae17265fc32e4a44d4b7efb7c8ad/app/bundles/WebhookBundle/Form/Type/WebhookType.php#L56)
[AssetType](https://github.com/mautic/mautic/blob/d4ef86f5eee2ae17265fc32e4a44d4b7efb7c8ad/app/bundles/AssetBundle/Form/Type/AssetType.php#L90)
[SlotSocialFollowType](https://github.com/mautic/mautic/blob/d4ef86f5eee2ae17265fc32e4a44d4b7efb7c8ad/app/bundles/CoreBundle/Form/Type/SlotSocialFollowType.php#L14)
[CampaignConditionLeadPageHitType](https://github.com/mautic/mautic/blob/d4ef86f5eee2ae17265fc32e4a44d4b7efb7c8ad/app/bundles/LeadBundle/Form/Type/CampaignConditionLeadPageHitType.php#L24)
[CampaignEventPageHitType](https://github.com/mautic/mautic/blob/d4ef86f5eee2ae17265fc32e4a44d4b7efb7c8ad/app/bundles/PageBundle/Form/Type/CampaignEventPageHitType.php#L28)
[PointActionUrlHitType](https://github.com/mautic/mautic/blob/d4ef86f5eee2ae17265fc32e4a44d4b7efb7c8ad/app/bundles/PageBundle/Form/Type/PointActionUrlHitType.php#L25)

**Review by kuzmany — APPROVED** [review]
Seems better now 👍

**Review by jcrandell7 — APPROVED** [review]
Expected to enter in URL in the indicated field without "https://", save, and then come back and see that it was added. Worked without issue. Thanks for this!

**Comment by RCheesley** [comment]
@all-contributors please add @jcrandell7 for usertesting 

Thanks for reviewing the PR @jcrandell7 ! 🚀

**Pull request merged**
