### PR TITLE
Bump dependencies to align with composer based installs

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

The current version of Composer dependencies are locked in the `composer.lock` file.
There dependencies are used during development en when running the tests.

However, that lock file is not used when installing Mautic via composer, and that makes sense.

This means we need to ensure every on a regular basis that these dependencies are up-to-date.

This PR updates all(*) dependencies to the latest available version, and makes some changes to the tests to ensure they pass successfully.

2 packages have temporarily been locked more strictly, to ensure a version compatible with Mautic is used, as the composer based releases **may** experience a different outcome:
* the `phpoffice/phpspreadsheet` is restricted to `^1.15 < 1.28`, to ensure the data types of fields stay the same. 
In the tests some data changed from int|float to string, and this needs further investigation.
* `doctrine/dbal` is restriced to `^3.6.2 < 3.8.0`, to ensure we don't need to change a lot of logic as some methods got deprecated. 
  * See https://github.com/doctrine/dbal/pull/6179 and https://github.com/doctrine/dbal/pull/6193
  * Another change in `doctrine/dbal:^3.8.0` is the rework of `QueryBuilder::getSQLForSelect()`, see 
 https://github.com/doctrine/dbal/pull/6191. 
 I already started to work on support for `3.8.0` by adding a trait for to easily work with this in the tests, see app/bundles/CoreBundle/Test/Doctrine/MockedConnectionTrait.php.

See the individual commits for more context.
Following table was generated using the [ion-bazan/composer-diff](https://github.com/IonBazan/composer-diff) Composer plugin, and running following command: `composer diff --no-dev -l`.

| Prod Packages                                                                               | Operation  | Base                 | Target               | Link                                                                                      |
|---------------------------------------------------------------------------------------------|------------|----------------------|----------------------|-------------------------------------------------------------------------------------------|
| [aws/aws-sdk-php](https://github.com/aws/aws-sdk-php)                                       | Upgraded   | 3.294.5              | 3.298.2              | [Diff](https://github.com/aws/aws-sdk-php/compare/3.294.5..3.298.2)                    |
| [composer/ca-bundle](https://github.com/composer/ca-bundle)                                 | Upgraded   | 1.3.7                | 1.4.0                | [Diff](https://github.com/composer/ca-bundle/compare/1.3.7..1.4.0)                     |
| [composer/composer](https://github.com/composer/composer)                                   | Upgraded   | 2.6.4                | 2.6.6                | [Diff](https://github.com/composer/composer/compare/2.6.4..2.6.6)                      |
| [composer/pcre](https://github.com/composer/pcre)                                           | Upgraded   | 3.1.0                | 3.1.1                | [Diff](https://github.com/composer/pcre/compare/3.1.0..3.1.1)                          |
| [composer/spdx-licenses](https://github.com/composer/spdx-licenses)                         | Upgraded   | 1.5.7                | 1.5.8                | [Diff](https://github.com/composer/spdx-licenses/compare/1.5.7..1.5.8)                 |
| [doctrine/data-fixtures](https://github.com/doctrine/data-fixtures)                         | Upgraded   | 1.6.6                | 1.7.0                | [Diff](https://github.com/doctrine/data-fixtures/compare/1.6.6..1.7.0)                 |
| [doctrine/dbal](https://github.com/doctrine/dbal)                                           | Upgraded   | 3.6.2                | 3.7.2                | [Diff](https://github.com/doctrine/dbal/compare/3.6.2..3.7.2)                          |
| [doctrine/deprecations](https://github.com/doctrine/deprecations)                           | Upgraded   | 1.1.2                | 1.1.3                | [Diff](https://github.com/doctrine/deprecations/compare/1.1.2..1.1.3)                  |
| [doctrine/doctrine-bundle](https://github.com/doctrine/DoctrineBundle)                      | Upgraded   | 2.9.1                | 2.11.1               | [Diff](https://github.com/doctrine/DoctrineBundle/compare/2.9.1..2.11.1)               |
| [doctrine/doctrine-fixtures-bundle](https://github.com/doctrine/DoctrineFixturesBundle)     | Upgraded   | 3.4.4                | 3.5.1                | [Diff](https://github.com/doctrine/DoctrineFixturesBundle/compare/3.4.4..3.5.1)        |
| [doctrine/doctrine-migrations-bundle](https://github.com/doctrine/DoctrineMigrationsBundle) | Upgraded   | 3.2.2                | 3.3.0                | [Diff](https://github.com/doctrine/DoctrineMigrationsBundle/compare/3.2.2..3.3.0)      |
| [doctrine/inflector](https://github.com/doctrine/inflector)                                 | Upgraded   | 2.0.6                | 2.0.9                | [Diff](https://github.com/doctrine/inflector/compare/2.0.6..2.0.9)                     |
| [doctrine/orm](https://github.com/doctrine/orm)                                             | Upgraded   | 2.15.1               | 2.18.0               | [Diff](https://github.com/doctrine/orm/compare/2.15.1..2.18.0)                         |
| [egulias/email-validator](https://github.com/egulias/EmailValidator)                        | Upgraded   | 3.2.5                | 3.2.6                | [Diff](https://github.com/egulias/EmailValidator/compare/3.2.5..3.2.6)                 |
| [exercise/htmlpurifier-bundle](https://github.com/Exercise/HTMLPurifierBundle)              | Upgraded   | 4.1.1                | 4.1.2                | [Diff](https://github.com/Exercise/HTMLPurifierBundle/compare/4.1.1..4.1.2)            |
| [ezyang/htmlpurifier](https://github.com/ezyang/htmlpurifier)                               | Upgraded   | v4.14.0              | v4.17.0              | [Diff](https://github.com/ezyang/htmlpurifier/compare/v4.14.0..v4.17.0)                |
| [friendsofphp/proxy-manager-lts](https://github.com/FriendsOfPHP/proxy-manager-lts)         | Upgraded   | v1.0.12              | v1.0.16              | [Diff](https://github.com/FriendsOfPHP/proxy-manager-lts/compare/v1.0.12..v1.0.16)     |
| [friendsofsymfony/rest-bundle](https://github.com/FriendsOfSymfony/FOSRestBundle)           | Upgraded   | 3.5.0                | 3.6.0                | [Diff](https://github.com/FriendsOfSymfony/FOSRestBundle/compare/3.5.0..3.6.0)         |
| [giggsey/libphonenumber-for-php](https://github.com/giggsey/libphonenumber-for-php)         | Upgraded   | 8.12.56              | 8.13.29              | [Diff](https://github.com/giggsey/libphonenumber-for-php/compare/8.12.56..8.13.29)     |
| [giggsey/locale](https://github.com/giggsey/Locale)                                         | Upgraded   | 2.2                  | 2.5                  | [Diff](https://github.com/giggsey/Locale/compare/2.2..2.5)                             |
| [helios-ag/fm-elfinder-bundle](https://github.com/helios-ag/FMElfinderBundle)               | Upgraded   | 12.3                 | 12.5                 | [Diff](https://github.com/helios-ag/FMElfinderBundle/compare/12.3..12.5)               |
| [jms/metadata](https://github.com/schmittjoh/metadata)                                      | Upgraded   | 2.6.1                | 2.8.0                | [Diff](https://github.com/schmittjoh/metadata/compare/2.6.1..2.8.0)                    |
| [jms/serializer](https://github.com/schmittjoh/serializer)                                  | Upgraded   | 3.23.0               | 3.29.1               | [Diff](https://github.com/schmittjoh/serializer/compare/3.23.0..3.29.1)                |
| [jms/serializer-bundle](https://github.com/schmittjoh/JMSSerializerBundle)                  | Upgraded   | 5.1.0                | 5.4.0                | [Diff](https://github.com/schmittjoh/JMSSerializerBundle/compare/5.1.0..5.4.0)         |
| [joomla/string](https://github.com/joomla-framework/string)                                 | Downgraded | 2.0.1                | 1.4.6                | [Diff](https://github.com/joomla-framework/string/compare/2.0.1..1.4.6)                |
| [kamermans/guzzle-oauth2-subscriber](https://github.com/kamermans/guzzle-oauth2-subscriber) | Upgraded   | v1.0.12              | v1.0.13              | [Diff](https://github.com/kamermans/guzzle-oauth2-subscriber/compare/v1.0.12..v1.0.13) |
| [knplabs/knp-menu](https://github.com/KnpLabs/KnpMenu)                                      | Upgraded   | v3.3.0               | v3.4.0               | [Diff](https://github.com/KnpLabs/KnpMenu/compare/v3.3.0..v3.4.0)                      |
| [laminas/laminas-code](https://github.com/laminas/laminas-code)                             | Upgraded   | 4.6.0                | 4.7.1                | [Diff](https://github.com/laminas/laminas-code/compare/4.6.0..4.7.1)                   |
| [league/flysystem](https://github.com/thephpleague/flysystem)                               | Upgraded   | 3.15.1               | 3.24.0               | [Diff](https://github.com/thephpleague/flysystem/compare/3.15.1..3.24.0)               |
| [league/flysystem-local](https://github.com/thephpleague/flysystem-local)                   | Upgraded   | 3.15.0               | 3.23.1               | [Diff](https://github.com/thephpleague/flysystem-local/compare/3.15.0..3.23.1)         |
| [league/mime-type-detection](https://github.com/thephpleague/mime-type-detection)           | Upgraded   | 1.11.0               | 1.15.0               | [Diff](https://github.com/thephpleague/mime-type-detection/compare/1.11.0..1.15.0)     |
| [lightsaml/sp-bundle](https://github.com/mautic/SpBundle)                                   | Changed    | dev-symfony5 b73d6b9 | dev-symfony5 91f36a5 | [Diff](https://github.com/mautic/SpBundle/compare/b73d6b9..91f36a5)                    |
| [lightsaml/symfony-bridge](https://github.com/mautic/SymfonyBridgeBundle)                   | Changed    | dev-symfony5 2d84638 | dev-symfony5 26f58d3 | [Diff](https://github.com/mautic/SymfonyBridgeBundle/compare/2d84638..26f58d3)         |
| [litesaml/lightsaml](https://github.com/litesaml/lightsaml)                                 | Upgraded   | v4.1.4               | v4.1.6               | [Diff](https://github.com/litesaml/lightsaml/compare/v4.1.4..v4.1.6)                   |
| [maennchen/zipstream-php](https://github.com/maennchen/ZipStream-PHP)                       | Upgraded   | 2.2.1                | 2.4.0                | [Diff](https://github.com/maennchen/ZipStream-PHP/compare/2.2.1..2.4.0)                |
| [markbaker/complex](https://github.com/MarkBaker/PHPComplex)                                | Upgraded   | 3.0.1                | 3.0.2                | [Diff](https://github.com/MarkBaker/PHPComplex/compare/3.0.1..3.0.2)                   |
| [markbaker/matrix](https://github.com/MarkBaker/PHPMatrix)                                  | Upgraded   | 3.0.0                | 3.0.1                | [Diff](https://github.com/MarkBaker/PHPMatrix/compare/3.0.0..3.0.1)                    |
| [maxmind-db/reader](https://github.com/maxmind/MaxMind-DB-Reader-php)                       | Upgraded   | v1.11.0              | v1.11.1              | [Diff](https://github.com/maxmind/MaxMind-DB-Reader-php/compare/v1.11.0..v1.11.1)      |
| [monolog/monolog](https://github.com/Seldaek/monolog)                                       | Upgraded   | 1.27.1               | 2.9.2                | [Diff](https://github.com/Seldaek/monolog/compare/1.27.1..2.9.2)                       |
| [nikic/php-parser](https://github.com/nikic/PHP-Parser)                                     | Upgraded   | v4.15.1              | v4.18.0              | [Diff](https://github.com/nikic/PHP-Parser/compare/v4.15.1..v4.18.0)                   |
| [paragonie/constant_time_encoding](https://github.com/paragonie/constant_time_encoding)     | New        | -                    | v2.6.3               | [Diff](https://github.com/paragonie/constant_time_encoding/releases/tag/v2.6.3)        |
| [pda/pheanstalk](https://github.com/pheanstalk/pheanstalk)                                  | Upgraded   | v4.0.4               | v4.0.5               | [Diff](https://github.com/pheanstalk/pheanstalk/compare/v4.0.4..v4.0.5)                |
| [php-amqplib/php-amqplib](https://github.com/php-amqplib/php-amqplib)                       | Upgraded   | v2.11.0              | v3.6.0               | [Diff](https://github.com/php-amqplib/php-amqplib/compare/v2.11.0..v3.6.0)             |
| [php-amqplib/rabbitmq-bundle](https://github.com/php-amqplib/RabbitMqBundle)                | Upgraded   | 2.5.3                | 2.14.0               | [Diff](https://github.com/php-amqplib/RabbitMqBundle/compare/2.5.3..2.14.0)            |
| [php-http/httplug](https://github.com/php-http/httplug)                                     | Upgraded   | 2.3.0                | 2.4.0                | [Diff](https://github.com/php-http/httplug/compare/2.3.0..2.4.0)                       |
| [php-http/promise](https://github.com/php-http/promise)                                     | Upgraded   | 1.1.0                | 1.3.0                | [Diff](https://github.com/php-http/promise/compare/1.1.0..1.3.0)                       |
| [phpoffice/phpspreadsheet](https://github.com/PHPOffice/PhpSpreadsheet)                     | Upgraded   | 1.24.1               | 1.27.1               | [Diff](https://github.com/PHPOffice/PhpSpreadsheet/compare/1.24.1..1.27.1)             |
| [phpseclib/phpseclib](https://github.com/phpseclib/phpseclib)                               | Upgraded   | 2.0.38               | 3.0.35               | [Diff](https://github.com/phpseclib/phpseclib/compare/2.0.38..3.0.35)                  |
| [phpstan/phpdoc-parser](https://github.com/phpstan/phpdoc-parser)                           | Upgraded   | 1.24.2               | 1.25.0               | [Diff](https://github.com/phpstan/phpdoc-parser/compare/1.24.2..1.25.0)                |
| [ramsey/uuid](https://github.com/ramsey/uuid)                                               | Upgraded   | 4.7.4                | 4.7.5                | [Diff](https://github.com/ramsey/uuid/compare/4.7.4..4.7.5)                            |
| [seld/jsonlint](https://github.com/Seldaek/jsonlint)                                        | Upgraded   | 1.10.0               | 1.10.1               | [Diff](https://github.com/Seldaek/jsonlint/compare/1.10.0..1.10.1)                     |
| [simshaun/recurr](https://github.com/simshaun/recurr)                                       | Upgraded   | v5.0.1               | v5.0.2               | [Diff](https://github.com/simshaun/recurr/compare/v5.0.1..v5.0.2)                      |
| [studio-42/elfinder](https://github.com/Studio-42/elFinder)                                 | Upgraded   | 2.1.62               | 2.1.65               | [Diff](https://github.com/Studio-42/elFinder/compare/2.1.62..2.1.65)                   |
| [symfony/amqp-messenger](https://github.com/symfony/amqp-messenger)                         | Upgraded   | v5.4.22              | v5.4.35              | [Diff](https://github.com/symfony/amqp-messenger/compare/v5.4.22..v5.4.35)             |
| [symfony/asset](https://github.com/symfony/asset)                                           | Upgraded   | v5.4.21              | v5.4.35              | [Diff](https://github.com/symfony/asset/compare/v5.4.21..v5.4.35)                      |
| [symfony/cache](https://github.com/symfony/cache)                                           | Upgraded   | v5.4.23              | v5.4.35              | [Diff](https://github.com/symfony/cache/compare/v5.4.23..v5.4.35)                      |
| [symfony/config](https://github.com/symfony/config)                                         | Upgraded   | v5.4.21              | v5.4.35              | [Diff](https://github.com/symfony/config/compare/v5.4.21..v5.4.35)                     |
| [symfony/console](https://github.com/symfony/console)                                       | Upgraded   | v5.4.28              | v5.4.35              | [Diff](https://github.com/symfony/console/compare/v5.4.28..v5.4.35)                    |
| [symfony/css-selector](https://github.com/symfony/css-selector)                             | Upgraded   | v5.4.21              | v5.4.35              | [Diff](https://github.com/symfony/css-selector/compare/v5.4.21..v5.4.35)               |
| [symfony/dependency-injection](https://github.com/symfony/dependency-injection)             | Upgraded   | v5.4.24              | v5.4.35              | [Diff](https://github.com/symfony/dependency-injection/compare/v5.4.24..v5.4.35)       |
| [symfony/deprecation-contracts](https://github.com/symfony/deprecation-contracts)           | Upgraded   | v2.5.2               | v3.0.2               | [Diff](https://github.com/symfony/deprecation-contracts/compare/v2.5.2..v3.0.2)        |
| [symfony/doctrine-bridge](https://github.com/symfony/doctrine-bridge)                       | Upgraded   | v5.4.22              | v5.4.35              | [Diff](https://github.com/symfony/doctrine-bridge/compare/v5.4.22..v5.4.35)            |
| [symfony/doctrine-messenger](https://github.com/symfony/doctrine-messenger)                 | Upgraded   | v5.4.21              | v5.4.35              | [Diff](https://github.com/symfony/doctrine-messenger/compare/v5.4.21..v5.4.35)         |
| [symfony/dotenv](https://github.com/symfony/dotenv)                                         | Upgraded   | v5.4.22              | v5.4.35              | [Diff](https://github.com/symfony/dotenv/compare/v5.4.22..v5.4.35)                     |
| [symfony/error-handler](https://github.com/symfony/error-handler)                           | Upgraded   | v5.4.29              | v5.4.35              | [Diff](https://github.com/symfony/error-handler/compare/v5.4.29..v5.4.35)              |
| [symfony/event-dispatcher](https://github.com/symfony/event-dispatcher)                     | Upgraded   | v5.4.26              | v5.4.35              | [Diff](https://github.com/symfony/event-dispatcher/compare/v5.4.26..v5.4.35)           |
| [symfony/expression-language](https://github.com/symfony/expression-language)               | Upgraded   | v5.4.21              | v5.4.35              | [Diff](https://github.com/symfony/expression-language/compare/v5.4.21..v5.4.35)        |
| [symfony/filesystem](https://github.com/symfony/filesystem)                                 | Upgraded   | v5.4.25              | v5.4.35              | [Diff](https://github.com/symfony/filesystem/compare/v5.4.25..v5.4.35)                 |
| [symfony/finder](https://github.com/symfony/finder)                                         | Upgraded   | v5.4.27              | v5.4.35              | [Diff](https://github.com/symfony/finder/compare/v5.4.27..v5.4.35)                     |
| [symfony/form](https://github.com/symfony/form)                                             | Upgraded   | v5.4.22              | v5.4.35              | [Diff](https://github.com/symfony/form/compare/v5.4.22..v5.4.35)                       |
| [symfony/framework-bundle](https://github.com/symfony/framework-bundle)                     | Upgraded   | v5.4.24              | v5.4.35              | [Diff](https://github.com/symfony/framework-bundle/compare/v5.4.24..v5.4.35)           |
| [symfony/http-client](https://github.com/symfony/http-client)                               | Upgraded   | v5.4.22              | v5.4.35              | [Diff](https://github.com/symfony/http-client/compare/v5.4.22..v5.4.35)                |
| [symfony/http-foundation](https://github.com/symfony/http-foundation)                       | Upgraded   | v5.4.31              | v5.4.35              | [Diff](https://github.com/symfony/http-foundation/compare/v5.4.31..v5.4.35)            |
| [symfony/http-kernel](https://github.com/symfony/http-kernel)                               | Upgraded   | v5.4.31              | v5.4.35              | [Diff](https://github.com/symfony/http-kernel/compare/v5.4.31..v5.4.35)                |
| [symfony/intl](https://github.com/symfony/intl)                                             | Upgraded   | v5.4.22              | v5.4.35              | [Diff](https://github.com/symfony/intl/compare/v5.4.22..v5.4.35)                       |
| [symfony/lock](https://github.com/symfony/lock)                                             | Upgraded   | v5.4.22              | v5.4.35              | [Diff](https://github.com/symfony/lock/compare/v5.4.22..v5.4.35)                       |
| [symfony/mailer](https://github.com/symfony/mailer)                                         | Upgraded   | v5.4.22              | v5.4.35              | [Diff](https://github.com/symfony/mailer/compare/v5.4.22..v5.4.35)                     |
| [symfony/messenger](https://github.com/symfony/messenger)                                   | Upgraded   | v5.4.22              | v5.4.35              | [Diff](https://github.com/symfony/messenger/compare/v5.4.22..v5.4.35)                  |
| [symfony/mime](https://github.com/symfony/mime)                                             | Upgraded   | v5.4.26              | v5.4.35              | [Diff](https://github.com/symfony/mime/compare/v5.4.26..v5.4.35)                       |
| [symfony/monolog-bridge](https://github.com/symfony/monolog-bridge)                         | Upgraded   | v5.4.22              | v5.4.35              | [Diff](https://github.com/symfony/monolog-bridge/compare/v5.4.22..v5.4.35)             |
| [symfony/polyfill-intl-icu](https://github.com/symfony/polyfill-intl-icu)                   | Upgraded   | v1.27.0              | v1.28.0              | [Diff](https://github.com/symfony/polyfill-intl-icu/compare/v1.27.0..v1.28.0)          |
| [symfony/process](https://github.com/symfony/process)                                       | Upgraded   | v5.4.28              | v5.4.35              | [Diff](https://github.com/symfony/process/compare/v5.4.28..v5.4.35)                    |
| [symfony/property-access](https://github.com/symfony/property-access)                       | Upgraded   | v5.4.26              | v5.4.35              | [Diff](https://github.com/symfony/property-access/compare/v5.4.26..v5.4.35)            |
| [symfony/redis-messenger](https://github.com/symfony/redis-messenger)                       | Upgraded   | v5.4.22              | v6.0.19              | [Diff](https://github.com/symfony/redis-messenger/compare/v5.4.22..v6.0.19)            |
| [symfony/routing](https://github.com/symfony/routing)                                       | Upgraded   | v5.4.22              | v5.4.35              | [Diff](https://github.com/symfony/routing/compare/v5.4.22..v5.4.35)                    |
| [symfony/security-bundle](https://github.com/symfony/security-bundle)                       | Upgraded   | v5.4.22              | v5.4.35              | [Diff](https://github.com/symfony/security-bundle/compare/v5.4.22..v5.4.35)            |
| [symfony/security-core](https://github.com/symfony/security-core)                           | Upgraded   | v5.4.30              | v5.4.35              | [Diff](https://github.com/symfony/security-core/compare/v5.4.30..v5.4.35)              |
| [symfony/security-csrf](https://github.com/symfony/security-csrf)                           | Upgraded   | v5.4.21              | v5.4.35              | [Diff](https://github.com/symfony/security-csrf/compare/v5.4.21..v5.4.35)              |
| [symfony/security-guard](https://github.com/symfony/security-guard)                         | Upgraded   | v5.4.22              | v5.4.35              | [Diff](https://github.com/symfony/security-guard/compare/v5.4.22..v5.4.35)             |
| [symfony/security-http](https://github.com/symfony/security-http)                           | Upgraded   | v5.4.31              | v5.4.35              | [Diff](https://github.com/symfony/security-http/compare/v5.4.31..v5.4.35)              |
| [symfony/stopwatch](https://github.com/symfony/stopwatch)                                   | Upgraded   | v5.4.21              | v5.4.35              | [Diff](https://github.com/symfony/stopwatch/compare/v5.4.21..v5.4.35)                  |
| [symfony/templating](https://github.com/symfony/templating)                                 | Upgraded   | v5.4.21              | v5.4.35              | [Diff](https://github.com/symfony/templating/compare/v5.4.21..v5.4.35)                 |
| [symfony/translation](https://github.com/symfony/translation)                               | Upgraded   | v5.4.24              | v5.4.35              | [Diff](https://github.com/symfony/translation/compare/v5.4.24..v5.4.35)                |
| [symfony/twig-bridge](https://github.com/symfony/twig-bridge)                               | Upgraded   | v5.4.31              | v5.4.35              | [Diff](https://github.com/symfony/twig-bridge/compare/v5.4.31..v5.4.35)                |
| [symfony/twig-bundle](https://github.com/symfony/twig-bundle)                               | Upgraded   | v5.4.21              | v5.4.35              | [Diff](https://github.com/symfony/twig-bundle/compare/v5.4.21..v5.4.35)                |
| [symfony/validator](https://github.com/symfony/validator)                                   | Upgraded   | v5.4.22              | v5.4.35              | [Diff](https://github.com/symfony/validator/compare/v5.4.22..v5.4.35)                  |
| [symfony/var-dumper](https://github.com/symfony/var-dumper)                                 | Upgraded   | v5.4.29              | v5.4.35              | [Diff](https://github.com/symfony/var-dumper/compare/v5.4.29..v5.4.35)                 |
| [symfony/yaml](https://github.com/symfony/yaml)                                             | Upgraded   | v5.4.21              | v5.4.35              | [Diff](https://github.com/symfony/yaml/compare/v5.4.21..v5.4.35)                       |
| [tightenco/collect](https://github.com/tighten/collect)                                     | Upgraded   | v8.83.23             | v8.83.27             | [Diff](https://github.com/tighten/collect/compare/v8.83.23..v8.83.27)                  |
| [twig/twig](https://github.com/twigphp/Twig)                                                | Upgraded   | v3.7.1               | v3.8.0               | [Diff](https://github.com/twigphp/Twig/compare/v3.7.1..v3.8.0)                         |
| [wikimedia/less.php](https://github.com/wikimedia/less.php)                                 | Upgraded   | v4.1.0               | v4.1.1               | [Diff](https://github.com/wikimedia/less.php/compare/v4.1.0..v4.1.1)                   |
| [bjeavons/zxcvbn-php](https://github.com/bjeavons/zxcvbn-php)                               | Removed    | 1.3.1                | -                    | [Diff](https://github.com/bjeavons/zxcvbn-php/releases/tag/1.3.1)                      |

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by mollux** [comment]
I ran the `mautic/api-library` tests, as the `jms/serializer` package was updated, which may impact the API output.
https://github.com/mautic/api-library/actions/runs/7776166026/job/21202996646
API tests still pass with the updated dependencies.

**Comment by mallezie** [comment]
Might be i'm a bit too conservative here. But wouldn't working the other way around actually make more sense? 
So this means locking (in composer.json) the versions to the one in composer.lock (which are the tested versions). 
Then we could update more conscious afterwards from there. (For example in here i would split updates between simple composer updates (passing all tests) and in seperate PRs, updates which needs code changes). That would also make PR's much more easy for code-review.

**Comment by mollux** [comment]
@mallezie I get your point, and I also thought about this.
That would be a good approach is the release process and governance allows you to release often.
This is unfortunately not the case at this point.
And even then, we would easily slip into the same issues as Drupal encountered (e.g. https://www.drupal.org/project/drupal/issues/3198340).

So for now, I see this as the middle ground, and will propose this to core team:
* for every every patch, minor, and major RC release), we update the dependencies so those get testes via the automated tests and the users tests when reviewing bugfixes and features.
* we review all dependencies and restrict them if they would allow to do major updates (e.g. see the `monolog/monolog` package above).

**Review by escopecz — APPROVED** [review]
Looks good to me 👍  Thanks for taking care of this!

**Comment by mollux** [comment]
@mallezie do you agree with my POV on this issue? or do you see any blockers to merge this?

**Comment by mallezie** [comment]
No blockers to merging this from me. (Did not test anything). 
We might think about how to do this in the future without holding this one up.

**Pull request merged**
