### PR TITLE
Email dc multi select filter

### LINKED ISSUE #10797: Filters for Dynamic Web Content no longer respect "Including" logic [$100]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When creating a filter for slot-based dynamic web content, using an including filter like this...
image
...should work and did work in version 3. However, since the upgarde to version 4, only equals works. 

It seems that since version 4.0, the "Including" operator no longer works and always returns false, causing any dynamic content using "Including" and a select field to never show.  If you use the same field and value with equals, it works just fine.

### How can we reproduce this issue?

Step 1: Create a slot-based dynamic web content block
Step 2: Set the filter to Country Including [your country] [another country]
Step 3: Embed the slot on a web page
Step 4: validate it doesn't load
Step 5: Modify the filter to be Country Equals [your country]
Step 6: validate content does load

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Did you fix this issue? Go claim the **[$100 bounty](https://app.bountysource.com/issues/106643135-filters-for-dynamic-web-content-no-longer-respect-including-logic?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** on [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by shinde-rahul**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [✅ ]
| New feature/enhancement? (use the a.x branch)      | [4.3]
| Deprecations?                          | [:x:]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [Yes] 
| Related user documentation PR URL      | /
| Related developer documentation PR URL | /
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/issues/10797

#### Description:

The multi-select field is not working as expected with the dynamic content block. 

**This must be tested in the legacy builder as GrapeJS does not have dynamic content yet (I think). So go to plugins and disable the GrapeJS plugin**

#### Steps to test this PR:

Tip for testing:

> When testing dynamic web content visit the page in an incognito browser window. Then go to the Mautic administration and view anonymous contacts ordered by date last active. Edit the contact you just created in the anonymous window. It should be the one on the top of the list as it was just active. Now edit it to fit your dynamic content filters and test that they show up.

DWC docs: https://docs.mautic.org/en/components/dynamic-web-content

##### Test 1:
1. Open this PR on Gitpod or pull-down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a custom field of type multiple-select
3. Update contacts for a newly created custom field.
4. Create an email with a dynamic content block, add variants based on multi-select field filter criteria 

##### Test 2:

Step 1: Create a slot-based dynamic web content block
Step 2: Set the filter to Country Including [your country] [another country]
Step 3: Embed the slot on a web page
Step 4: validate content does load

##### Test 3:

Step 1: Create a slot-based dynamic web content block
Step 2: Use the Multiselect field from Test 1 and set including operator and some value from the multiselect.
Step 3: Embed the slot on a web page
Step 6: validate content does load

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10871"></a>

### CODE REVIEW

**Comment by volha-pivavarchyk** [comment]
Could you please specify how to reproduce the issue. It works well for me with the 4.2 branch and with this branch too.

E.g. I have got the same result for two branches.
dc settings:
image
email content:
image

**Comment by escopecz** [comment]
@shinde-rahul I cannot replicate the issue either. Please double-check the steps to recreate.

**Comment by escopecz** [comment]
I added some more steps to replicate as this fixes https://github.com/mautic/mautic/issues/10797

**Review by escopecz — APPROVED** [review]
I confirm this fixes the dynamic web content including operator for selects and multiselects.

**Review by kuzmany — APPROVED** [review]
Works as expected

**Pull request merged**
