### PR TITLE
Fix flip array for DC

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Select and boolean fields does not work for email dynamic content properly. This issue bring this commit https://github.com/mautic/mautic/commit/1b48802c2a796fd72f1b5b787cc06c08b9aa6666
There is mismatch with label/values 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create select field with options
- `first` label / `1` value
- `second` label / `2` value

Create boolean field

3. Create email and select code mode
4. On Dynamic Content tab add two condition
- select field with second value (you should see correct labels/values)
- boolean field with no (you should see wrong labels/values - numbers as labels)

5.  Then try save email
6. You should see wrong label/values for select field and wrong label/values for boolean field too
7. After PR should works properly

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11393"></a>

### CODE REVIEW

**Comment by kuzmany** [comment]
@escopecz I've marked it as regression because It was bring by this commit https://github.com/mautic/mautic/commit/1b48802c2a796fd72f1b5b787cc06c08b9aa6666

**Review by npracht — APPROVED** [review]
✅ for me it fixes the issue and now works properly.
I have no clue about code quality 🙉

**Comment by RCheesley** [comment]
This will need to be rebased to 4.4 if we are going to merge it into a bugfix release.

**Review by volha-pivavarchyk — APPROVED** [review]
The issue was fixed. Works well now

**Comment by bianchim** [comment]
While the display of select list is fine, the filter does not seem to work still for select list fields. The PR #11735 does fix the filter behavior when actually sending the emails.

Might be worth considering either merging the two or making a new PR with both changes.

**Comment by RCheesley** [comment]
This one needs to be rebased so I've removed the ready to commit label, as it'll need re-testing post-rebase. Should be a quick test though!

**Comment by kuzmany** [comment]
Close at the moment. We will push it again once ready to M5

**Pull request closed without merging**
