### PR TITLE
Replace continue in switch statement with break

### PR DESCRIPTION
**Pull request by Woeler**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/7843
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by npracht** [comment]
@kuzmany @escopecz just a code review?

**Comment by escopecz** [comment]
TBH, I can't wrap my head around it. @Woeler could you describe why you did the change and how to test it? It would be clear if it would have a unit tests.

**Comment by Woeler** [comment]
@escopecz This PR does not change any behaviour at all. Continue and Break in PHP operate exactly the same in switch statements. The only thing is that break is the way to go in a switch statement, and it will warn you when using continue in a switch statement.

**Comment by heathdutton** [comment]
Older PHP versions don't complain, but due to ambiguity and confusion around switches there are now warnings, so the change is valid. #6991 had to make similar changes.

**Comment by escopecz** [comment]
Thanks guys! It makes sense. Let's try to keep this valuable info in PR description going forward so everyone understands why the change is made.

**Comment by Woeler** [comment]
Yea, sorry should have put something in the description.

**Pull request merged**
