### PR TITLE
Email A/B test fixes

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**
1) The big thing with this PR is that it fixes an issue where single emails sent via campaigns, etc never used a variant regardless of the weight assigned to it due to the EmailModel::sendEmail function calculating the weights and limits, but not ignoring an email with a calculated weight of 0. 

2) For batch emails, such as list sends, one extra email was sent for each variant email due to the use of > rather than >=.

3) It also fixes an issue where the A/B winning criteria, "Read Rate," compared the a/b test start date with the read_date of the stat rather than the sent_date skewing the results.

4) Finally, the stats displayed in the list were of the parent only making it confusing as to the real send/read counts overall.  So this PR ensures that the sent/read counts in the Manage Emails lists include a summation of all variants.  It also adjusted the graph to give an option to view the counts for the specific variant or for all variants.  It defaults to "all" for the "parent" and "variant" for "children."

**Testing**
Create an template email with at least one A/B variant of 50% and a read rate winning criteria.  Then create a campaign to send the email and assign at least two leads to the campaign. Run the command `mautic:campaign:trigger.` The emails should be sent out to the leads. Do not open the emails sent to the leads.

Things to note:
1) Browse to the email's details page. All emails were sent to the one email when it should have been divided 50/50 with the variant. (# 1 under Description)

2) Click the Variants tab then A/B Test Stats. Notice that the sent counts are 0 when they should be the total number sent. (# 3  under Description)

Now create a new list based email, assign it to a list with at 4 leads, and then create an A/B variant of 50% and a read rate winning criteria.  Send the email to the list.

Things to note:
1) Look at the stats in the Manage Email list for the email just created. It'll only show the stats for the parent email and does not include those sent to the variants. (# 4  under Description)

2) One extra email is sent to the parent email. So 3 was sent to the parent and 1 to the variant when it should be 2 and 2. (# 2 under Description)

Apply the PR and repeat the process.  It's best and easiest to create new emails.
1) The stats in the Manage Email list will now include a summation of all variants.
2) The emails sent through the campaign should be properly distributed 50/50
3) The emails sent via a  list should be properly distributed 50/50
4) The A/B Test Stats graph should now have a proper sent count
5) The summary graphs of each template/list email should default to include stats for all variants. Click on the Variant link above upper right corner of the graph and it will show stats just for the specific variant.  (Defaults to "all" for the parent but if you click on a variant from the Variants tab, it'll default to just the variant's stats).

### CODE REVIEW

**Comment by escopecz** [comment]
During testing, when triggering `mautic:campaign:update` command to add leads from a lead list to the campaign I got this error
```
 [Doctrine\DBAL\DBALException]                                                                                   
  An exception occurred while executing 'SELECT max(ll.lead_id) as max_id, count(distinct(ll.lead_id)) as lead_c  
  ount FROM mau_lead_lists_leads ll WHERE (ll.leadlist_id IN (7)) AND (ll.manually_removed = ?) AND (ll.date_add  
  ed <= '2015-07-16 16:32:02') AND (ll.lead_id NOT IN (SELECT cl.lead_id FROM mau_campaign_leads cl WHERE cl.cam  
  paign_id = 7)) ORDER BY ll.lead_id ASC' with params [0]:                                                        
  SQLSTATE[42803]: Grouping error: 7 ERROR:  column "ll.lead_id" must appear in the GROUP BY clause or be used i  
  n an aggregate function                                                                                         
  LINE 1: ...aign_leads cl WHERE cl.campaign_id = 7)) ORDER BY ll.lead_id...                                      
                                                               ^       
```
I talked to Alan and he said it is the similar issue as in https://github.com/mautic/mautic/pull/665 and that he'll add it there. So I'll test that PR first, merge it and get back to this one.

**Comment by escopecz** [comment]
I was able to reproduce the problems, but when I execute the `mautic:campaigns:trigger` command, the command line writes this:
```
Triggering events for campaign 8
Triggering first level events
4 total events(s) to be processed in batches of 100
 1/4 [=======>--------------------]  25%float(1)
float(0.5)
float(1)
float(0.5)
```
and only one email from 4 is sent. Probably the var_dump on line 947? But why it sent only one email?

**Comment by alanhartless** [comment]
Because I managed to leave in a die() statement in there as well as a var_dump().  I should be developer of the year :clap: :tada: :blush: :wink:

**Comment by dbhurley** [comment]
+1 worked for me

**Comment by ps92** [comment]
@alanhartless This problem still exists in v1.2.4!

**Pull request merged**
