### PR TITLE
Change OAuth2 Package to use twig

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [X]
| BC breaks? (use the c.x branch)        | [X]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

We are using a forked repo to get th a version of `FriendsOfSymfony/FOSOAuthServerBundle` that supports PHP templates, since we are moving away from it, the old discussion is mentioned on this [thread](https://github.com/mautic/mautic/pull/10111#issuecomment-854641323)

This PR is needed to use the twig version 

Few notices on this PR: 
1- The only version of `FOSOAuthServerBundle` that supports php8 is v2 which is hosted in the `dev-master` branch on their repo, they do not have a new released version, here is their [changelog](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/CHANGELOG-2.0.md)
2. I removed all the references on the fork we are using. 
3. Refactored the code to match the changes on `FOSOAuthServerBundle`
4. Renamed the event listener name and that causes phpstan to fail.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Test Oauth2 capabilities

### CODE REVIEW

**Comment by escopecz** [comment]
@mabumusa1 @mollux I worry that this is not good enough for us as we aim to support also PHP 8.1 and hopefully also 8.2 with Mautic 5. This will cause troubles to get there. https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/blob/master/composer.json#L23

**Comment by mabumusa1** [comment]
@escopecz We need a replacement to this package, it will be blocking the removal of PHP engine on this PR https://github.com/mautic/mautic/actions/runs/4447068293/jobs/7808152825?pr=12089

https://github.com/mautic/mautic/pull/12089


I noticed that this bundle is not heavily maintained, maybe https://github.com/thephpleague/oauth2-server-bundle is a better alternative?

**Comment by escopecz** [comment]
I was testing with API-Library's API tester and got this when I tried to authenticate with OAuth2:
```
{"errors":[{"message":"Mautic\\ApiBundle\\Controller\\oAuth2\\AuthorizeController::__construct(): Argument #5 ($tokenStorage) must be of type Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\TokenStorageInterface, Symfony\\Bundle\\FrameworkBundle\\Templating\\DelegatingEngine given, called in \/var\/www\/html\/var\/cache\/dev\/ContainerNVSkkcc\/getMautic_Api_Oauth2_AuthorizeControllerService.php on line 9","code":500,"type":null}],"trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/app\/bundles\/ApiBundle\/Controller\/oAuth2\/AuthorizeController.php","line":61,"args":[]},{"namespace":"Mautic\\ApiBundle\\Controller\\oAuth2","short_class":"AuthorizeController","class":"Mautic\\ApiBundle\\Controller\\oAuth2\\AuthorizeController","type":"-\u003E","function":"__construct","file":"\/var\/www\/html\/var\/cache\/dev\/ContainerNVSkkcc\/getMautic_Api_Oauth2_AuthorizeControllerService.php","line":9,"args":[["object","Symfony\\Component\\HttpFoundation\\RequestStack"],["object","Symfony\\Component\\Form\\Form"],["object","FOS\\OAuthServerBundle\\Form\\Handler\\AuthorizeFormHandler"],["object","OAuth2\\OAuth2"],["object","Symfony\\Bundle\\FrameworkBundle\\Templating\\DelegatingEngine"],["object","Symfony\\Component\\Security\\Core\\Authentication\\Token\\Storage\\UsageTrackingTokenStorage"],["object","Symfony\\Bundle\\FrameworkBundle\\Routing\\Router"],["object","FOS\\OAuthServerBundle\\Entity\\ClientManager"],["object","Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"],["object","Symfony\\Component\\HttpFoundation\\Session\\Session"]]},{"namespace":"","short_class":"","class":"","type":"","function":"require","file":"\/var\/www\/html\/var\/cache\/dev\/ContainerNVSkkcc\/appAppKernelDevDebugContainer.php","line":2302,"args":[["string","\/var\/www\/html\/var\/cache\/dev\/ContainerNVSkkcc\/getMautic_Api_Oauth2_AuthorizeControllerService.php"]]},{"namespace":"ContainerNVSkkcc","short_class":"appAppKernelDevDebugContainer","class":"ContainerNVSkkcc\\appAppKernelDevDebugContainer","type":"-\u003E","function":"load","file":"\/var\/www\/html\/vendor\/symfony\/dependency-injection\/Container.php","line":255,"args":[["string","getMautic_Api_Oauth2_AuthorizeControllerService.php"]]},{"namespace":"Symfony\\Component\\DependencyInjection","short_class":"Container","class":"Symfony\\Component\\DependencyInjection\\Container","type":"-\u003E","function":"make","file":"\/var\/www\/html\/vendor\/symfony\/dependency-injection\/Container.php","line":231,"args":[["string","mautic.api.oauth2.authorize_controller"],["integer",1]]},{"namespace":"Symfony\\Component\\DependencyInjection","short_class":"Container","class":"Symfony\\Component\\DependencyInjection\\Container","type":"-\u003E","function":"get","file":"\/var\/www\/html\/vendor\/symfony\/http-kernel\/Controller\/ContainerControllerResolver.php","line":53,"args":[["string","mautic.api.oauth2.authorize_controller"]]},{"namespace":"Symfony\\Component\\HttpKernel\\Controller","short_class":"ContainerControllerResolver","class":"Symfony\\Component\\HttpKernel\\Controller\\ContainerControllerResolver","type":"-\u003E","function":"instantiateController","file":"\/var\/www\/html\/vendor\/symfony\/framework-bundle\/Controller\/ControllerResolver.php","line":70,"args":[["string","Mautic\\ApiBundle\\Controller\\oAuth2\\AuthorizeController"]]},{"namespace":"Symfony\\Bundle\\FrameworkBundle\\Controller","short_class":"ControllerResolver","class":"Symfony\\Bundle\\FrameworkBundle\\Controller\\ControllerResolver","type":"-\u003E","function":"instantiateController","file":"\/var\/www\/html\/vendor\/symfony\/http-kernel\/Controller\/ControllerResolver.php","line":122,"args":[["string","Mautic\\ApiBundle\\Controller\\oAuth2\\AuthorizeController"]]},{"namespace":"Symfony\\Component\\HttpKernel\\Controller","short_class":"ControllerResolver","class":"Symfony\\Component\\HttpKernel\\Controller\\ControllerResolver","type":"-\u003E","function":"createController","file":"\/var\/www\/html\/vendor\/symfony\/http-kernel\/Controller\/ContainerControllerResolver.php","line":42,"args":[["string","Mautic\\ApiBundle\\Controller\\oAuth2\\AuthorizeController::authorizeAction"]]},{"namespace":"Symfony\\Component\\HttpKernel\\Controller","short_class":"ContainerControllerResolver","class":"Symfony\\Component\\HttpKernel\\Controller\\ContainerControllerResolver","type":"-\u003E","function":"createController","file":"\/var\/www\/html\/vendor\/symfony\/framework-bundle\/Controller\/ControllerResolver.php","line":62,"args":[["string","Mautic\\ApiBundle\\Controller\\oAuth2\\AuthorizeController::authorizeAction"]]},{"namespace":"Symfony\\Bundle\\FrameworkBundle\\Controller","short_class":"ControllerResolver","class":"Symfony\\Bundle\\FrameworkBundle\\Controller\\ControllerResolver","type":"-\u003E","function":"createController","file":"\/var\/www\/html\/vendor\/symfony\/http-kernel\/Controller\/ControllerResolver.php","line":86,"args":[["string","Mautic\\ApiBundle\\Controller\\oAuth2\\AuthorizeController::authorizeAction"]]},{"namespace":"Symfony\\Component\\HttpKernel\\Controller","short_class":"ControllerResolver","class":"Symfony\\Component\\HttpKernel\\Controller\\ControllerResolver","type":"-\u003E","function":"getController","file":"\/var\/www\/html\/vendor\/symfony\/http-kernel\/Controller\/TraceableControllerResolver.php","line":38,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"]]},{"namespace":"Symfony\\Component\\HttpKernel\\Controller","short_class":"TraceableControllerResolver","class":"Symfony\\Component\\HttpKernel\\Controller\\TraceableControllerResolver","type":"-\u003E","function":"getController","file":"\/var\/www\/html\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":152,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E","function":"handleRaw","file":"\/var\/www\/html\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":81,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E","function":"handle","file":"\/var\/www\/html\/vendor\/symfony\/http-kernel\/Kernel.php","line":201,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1],["boolean",true]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"Kernel","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"-\u003E","function":"handle","file":"\/var\/www\/html\/app\/AppKernel.php","line":105,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1],["boolean",true]]},{"namespace":"","short_class":"AppKernel","class":"AppKernel","type":"-\u003E","function":"handle","file":"\/var\/www\/html\/app\/middlewares\/CORSMiddleware.php","line":82,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1],["boolean",true]]},{"namespace":"Mautic\\Middleware","short_class":"CORSMiddleware","class":"Mautic\\Middleware\\CORSMiddleware","type":"-\u003E","function":"handle","file":"\/var\/www\/html\/app\/middlewares\/HSTSMiddleware.php","line":35,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1],["boolean",true]]},{"namespace":"Mautic\\Middleware","short_class":"HSTSMiddleware","class":"Mautic\\Middleware\\HSTSMiddleware","type":"-\u003E","function":"handle","file":"\/var\/www\/html\/app\/middlewares\/CatchExceptionMiddleware.php","line":34,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1],["boolean",true]]},{"namespace":"Mautic\\Middleware","short_class":"CatchExceptionMiddleware","class":"Mautic\\Middleware\\CatchExceptionMiddleware","type":"-\u003E","function":"handle","file":"\/var\/www\/html\/app\/middlewares\/Dev\/IpRestrictMiddleware.php","line":52,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1],["boolean",true]]},{"namespace":"Mautic\\Middleware\\Dev","short_class":"IpRestrictMiddleware","class":"Mautic\\Middleware\\Dev\\IpRestrictMiddleware","type":"-\u003E","function":"handle","file":"\/var\/www\/html\/app\/middlewares\/VersionCheckMiddleware.php","line":58,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1],["boolean",true]]},{"namespace":"Mautic\\Middleware","short_class":"VersionCheckMiddleware","class":"Mautic\\Middleware\\VersionCheckMiddleware","type":"-\u003E","function":"handle","file":"\/var\/www\/html\/app\/middlewares\/TrustMiddleware.php","line":42,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1],["boolean",true]]},{"namespace":"Mautic\\Middleware","short_class":"TrustMiddleware","class":"Mautic\\Middleware\\TrustMiddleware","type":"-\u003E","function":"handle","file":"\/var\/www\/html\/vendor\/stack\/builder\/src\/Stack\/StackedHttpKernel.php","line":23,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1],["boolean",true]]},{"namespace":"Stack","short_class":"StackedHttpKernel","class":"Stack\\StackedHttpKernel","type":"-\u003E","function":"handle","file":"\/var\/www\/html\/vendor\/stack\/run\/src\/Stack\/run.php","line":13,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"]]},{"namespace":"","short_class":"","class":"","type":"","function":"Stack\\run","file":"\/var\/www\/html\/index_dev.php","line":25,"args":[["object","Stack\\StackedHttpKernel"]]}]}
```

**Comment by escopecz** [comment]
What thing will be easier? We can update our for to their master and prepare support for PHP 8.1, 8.2 like we did so far.

**Comment by mabumusa1** [comment]
> tokenStorage

Fixed on the last commit

**Comment by mabumusa1** [comment]
> What thing will be easier? We can update us for to their master and prepare support for PHP 8.1, and 8.2 as we did so far.

I am not sure if we want to have more things to maintain, but so far we did not make so many changes to their package, so it could be easy to just make some changes to it directly

**Comment by escopecz** [comment]
The problem with that repository is that they did not merge any of our PRs so far. That's why we were forced to fork it.

I can confirm that the oAuth2 is working with the latest commit:
Screenshot 2023-03-17 at 16 01 01

During the test I found bugs from the twig refactoring. Do you think those could be fixed in this PR as well?
Screenshot 2023-03-17 at 15 57 32
Screenshot 2023-03-17 at 15 57 23

**Comment by mabumusa1** [comment]
@escopecz I will fix the bugs you found in twig, I suggest we keep using the `master-dev` version until we make the changes we want to our fork after that, we will make a new PR to use our fork

This PR is a blocker to https://github.com/mautic/mautic/pull/12089, so I want to finish that PR over the weekend

**Comment by mollux** [comment]
@escopecz @mabumusa1 I share the concern about the PHP compatibility and the inability to get PR's merged.

Best way forward for now is (unfortunately) keep the fork, and ensure it's compatible with the twig (and other changes in Mautic)

@mabumusa1 I will QA further once you reverted the composer changes so the fork is used again.

**Comment by mabumusa1** [comment]
@mollux are you aware of the status of our fork? I suggest we make a new branch based on their master-dev and apply our PRs.

The current branch is based on an old version and it adds PHP engine which I am trying to remove.

**Comment by mabumusa1** [comment]
@escopecz @mollux I checked the commits we have in our branch, there are two commits one by @dennisameling and the other one by @mollux. The first one the same changes are reflected on their `master` branch and the other commit is just increase PHP version.

I suggest we keep the fork, but use `master` branch instead, if we agree on this I will adjust this PR

**Comment by escopecz** [comment]
I agree with keeping Mautic's fork that we reset on the upstream master branch that will enable us to increase the PHP support based on Mautic's needs.

**Comment by mabumusa1** [comment]
@escopecz I fixed the issue with the twig template.

For the oAuth bundle, I created a new branch called `upgrade-2` which is basically a clone of `master-dev`, https://github.com/mautic/FOSOAuthServerBundle/tree/upgrade-2

Then I made this PR take from that branch, whenever we want to upgrade that bundle we just have to increase PHP version and then we are ready to go. I think it is a good practice to merge their changes to our branch

This PR is ready for review again, there will be a failing test for stan baseline which is expected since I changed neon file

**Review by escopecz — CHANGES_REQUESTED** [review]
Please check Rector and PHPStan. They discovered a bug. Also, I'm wondering whether we could also add support for PHP 8.1 and 8.2 in https://github.com/mautic/FOSOAuthServerBundle/blob/upgrade-2/composer.json#L23.

**Comment by mabumusa1** [comment]
> Please check Rector and PHPStan. They discovered a bug. Also, I'm wondering whether we could also add support for PHP 8.1 and 8.2 in https://github.com/mautic/FOSOAuthServerBundle/blob/upgrade-2/composer.json#L23.

I fixed the pending issues, I think it is a good idea to add support for 8.1 & 8.2, I took a quick look at their code could not find anything that might break if support those versions

**Comment by escopecz** [comment]
@mabumusa1 djd you forget to push? I still see the same code.

**Comment by mabumusa1** [comment]
> @mabumusa1 djd you forget to push? I still see the same code.

@escopecz I just did

**Review by escopecz — DISMISSED** [review]
I'm still getting the same UI issues as in https://github.com/mautic/mautic/pull/12091#issuecomment-1473979617 but that was not caused by this PR so I don't want to block its merge. I see no other issues and I can use Oauth2 api authentication.

**Comment by mabumusa1** [comment]
> I'm still getting the same UI issues as in https://github.com/mautic/mautic/pull/12091#issuecomment-1473979617 but that was not caused by this PR so I don't want to block its merge. I see no other issues and I can use Oauth2 api authentication.

Awesome, let's merge this one, I will start an issue with the comment

**Comment by escopecz** [comment]
@mabumusa1 I fixed the UI issues in https://github.com/mautic/mautic/pull/12091/commits/d0f4b5ecc2b60e7f2d133f419d0da15339c23c5c

**Comment by mabumusa1** [comment]
> @mabumusa1 I fixed the UI issues in https://github.com/mautic/mautic/pull/12091/commits/d0f4b5ecc2b60e7f2d133f419d0da15339c23c5c

Awesome, thanks.

Once we get this merged I will continue the removal of templating engine

**Comment by mabumusa1** [comment]
@mollux may you please review this PR so we can merge it, it is blocking my work on the removal of the templating engine

**Comment by escopecz** [comment]
I'll merge this to unblock further work.

**Pull request merged**
