### PR TITLE
[Enhancement] Allow filtering contacts by UTM data for segments.

### PR DESCRIPTION
**Pull request by heathdutton**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Yes
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #5885
| BC breaks? |
| Deprecations? | 

#### Description:
See #5885

#### Steps to test this PR:
1. Ensure you have a contact with a unique UTM Source.
2. Create a segment to filter based on the UTM Source value provided.
3. Trigger `console mautic:segments:update` or wait for your typical cron tasks to run.
4. Check that your contact is now in the new segment, and none others are.

UTM Filtering in Segment view

### CODE REVIEW

**Comment by Maxell92** [comment]
Hello @heathdutton,  I reverted your condition's changes in repository (`yoda style`, which follows a Symfony standards), it will be hard for us to keep changes with the new segment's code.
These methods will be deprecated and removed later anyway, so I think it is not a big deal.

**Comment by Maxell92** [comment]
I have added this functionality to refactored segments. We are ready to use it in the old old same as in the new one.

**Comment by heathdutton** [comment]
Thanks @Maxell92 

Appreciate all the effort, since I'm busy doing other plugin-related lately :)

**Comment by javjim-mautic** [comment]
Tested and works properly

**Pull request merged**
