### PR TITLE
Theme panel headers

### PR DESCRIPTION
**Pull request by moskoweb**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? |N
| Related user documentation PR URL | https://github.com/mautic/mautic/pull/5661
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Simple correction.

### CODE REVIEW

**Comment by kuzmany** [comment]
I am not sure If this is good way how to resolve it @Woeler  @escopecz 

I see 

image

**Comment by Woeler** [comment]
I also don't see why this is a problem. I'd rather have the full name on multiple lines than having the name cut-off. I don't see the benefit of that.

**Comment by escopecz** [comment]
I like that @moskoweb added the title attribute when making the change. So the full theme name can be visible when hover over it. I'm fine either way. I'll leave the decision on the release leader.

**Comment by moskoweb** [comment]
A 'tooltip' can be placed if it is more visually pleasing than just the 'title'.

**Comment by kuzmany** [comment]
What about little lower font size and two lines (max-height:2.4em for example)

**Comment by alanhartless** [comment]
@moskoweb this is only applied for code mode. Did you  mean to apply it to all headers (line 53)? After adding it there, I feel this is fine. Otherwise we are always chasing "how long is too long of a name?" when two lines are not enough.

**Comment by RCheesley** [comment]
@cla-bot check

Hi @moskoweb sorry we haven't got around to getting this merged. I noticed that there were [some suggestions](https://github.com/mautic/mautic/pull/6860#issuecomment-459121132) for improvements which haven't been actioned - if this PR is still relevant in Mautic 3.x could you take a look?

If we don't hear back from you within 14 days we'll close the PR due to inactivity.

**Comment by RCheesley** [comment]
Closing in favour of #9230

**Pull request closed without merging**
