### PR TITLE
Stop lead creation in case the form has validation errors

### LINKED ISSUE #5220: Spam / Injected Contacts being added to Mautic externally.
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:
Is this a security vulnerability in Mautic? I've recently setup a clean install of Mautic. I have a single form as the only way to add new contacts and capture some data I need.

Despite this, I am seeing new Contacts being injected without using the form and appearing directly in Contacts.

They look like obvious spam and don't include all the data I capture in my form.

So far, I've had two new contacts added which have completely bypassed my form and simply appearing in Mautic's contacts lists.

They do not look like normal Contacts.

I deleted the first one, but a very similar contact was added again today and this may now be a daily addition. Here is what it looks like:

Name: steve.web.jobs+TeddyDenet@gmail.com
Email: steve.web.jobs+TeddyDenet@gmail.com
City/Country: Dallas, Texas, United States
IP: 23.236.171.249

Events show this IP, Contact Identified and then Contact Added.

How is this being added to Mautic?

The API is disabled. I've never imported a CSV file. There are no log files being generated.

The only 'Legitimate' way should be via the form I setup or the control panel manually.

The box is Ubuntu 16.04, managed by Serverpilot and patched, with Firewall enabled, SSL enabled.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.10 
| PHP version | 7.1

### Steps to reproduce:
1. Open contacts 
2. New contact has been added 
 
### Log errors: 

There are no logs being created in relation to this issue.

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

### PR DESCRIPTION
**Pull request by carlosreig**
Fixes #5220 

This PR applies the patch provided by @marcel-ambta. I just applied his patch and created the PR.

### CODE REVIEW

**Comment by virgilwashere** [comment]
Not sure  this output really qualifies as "PASS"

```log
............PHP Notice:  Undefined offset: 0 in /home/travis/build/mautic/mautic/app/bundles/LeadBundle/Tests/Controller/Api/LeadApiControllerFunctionalTest.php on line 201
```

**Comment by alanhartless** [comment]
Won't this break the form behavior feature to hide if value exists?  https://github.com/mautic/mautic/pull/7570/files#diff-93de7d27865690af0cae5ea03e7b9433R402

**Comment by npracht** [comment]
@carlosreig please answer Alan's question and review Travis issue.

**Comment by anton-vlasenko** [comment]
I propose to merge https://github.com/mautic/mautic/pull/7818 instead and close this PR.
https://github.com/mautic/mautic/pull/7818 fixes the bug described here and doesn't break "Hide if value exists" feature.

**Comment by npracht** [comment]
Closing in favor of https://github.com/mautic/mautic/pull/7818. @carlosreig thanks a lot for pointing this out.

**Pull request closed without merging**
