### PR TITLE
[UI] Define the right cursor for interface elements

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR makes:
- Page headings and other interface text use the default cursor instead of text cursor, inheriting from body
- Everything that is in a field use the text cursor
- All clickable things use the pointer cursor

The overall idea is to improve the interaction feedback

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Contacts
3. Hover over the heading (normal cursor)
4. Create a new Contact > Fill the fields and hover over the text inside the fields (will display the text cursor)
5. Hover over the Saving & Close to see the pointer cursor

### CODE REVIEW

**Comment by andersonjeccel** [comment]
About the companies column

Before:

image

After:

image

**Review by LordRembo — CHANGES_REQUESTED** [review]
This is a problem from a UX point of view. If there is no explicit reason to disable a default functionality for a website, it shouldn't be done as it introduces potential friction for the end user.
We don't know how a user interacts with the various bits of text on a page. A website is not an app, they might very well have a good reason to copy headings for example.

**Comment by LordRembo** [comment]
@Mike-Dropsolid Would be good to have your input here as well, in light of priorities and validating the list of UI changes.

**Review by Esthertests — APPROVED** [review]
having LordRembo concern in mind, this PR is a great UX change. Nice work @andersonjeccel

**Comment by andersonjeccel** [comment]
Concerns by Rembrand were addressed, I'll ask him to review again

@Esthertests Thanks for testing!

**Comment by Esthertests** [comment]
> Concerns by Rembrand were addressed, I'll ask him to review again
> 
> 
> 
> @Esthertests Thanks for testing!

Yes they were, I checked it also

**Comment by andersonjeccel** [comment]
> [!WARNING]
> All Tier 1 PRs [need only 1 code review and 1 user testing](https://contribute.mautic.org/governance/code-governance#:~:text=Full%20testing%20and%20approval%20by%20at%20least%20one%20community%20member%20(could%20be%20the%20person%20doing%20the%20code%20review%2C%20but%20should%20not%20be%20from%20the%20same%20company/organisation%20as%20the%20person%20submitting%20the%20PR).) before able to merge. I'll update accordingly.

**Review by shinde-rahul — APPROVED** [review]
Code changes LGTM!!!

**Pull request merged**
