### PR TITLE
[UI] Fix width and spacing issues

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR:
- Fixes rows on the last column when importing contacts (they weren't filling 100%)
- Fixes issues with forms mentioned here https://mautic.slack.com/archives/C024XBCQS3Z/p1717572447130569
- Fixes icon spacing bug mentioned by john https://mautic.slack.com/archives/C024XBCQS3Z/p1717690551844149
- Makes the UI seen by Mautic users start to use separate styles from the ones used to render forms on external websites
- Organizes the form.css file
- Removes duplicates from form.css

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Components > Forms > New > Fields > Add fields then go to the Actions tab and add actions
3. Contacts > Import > Select a file and Next > See all fields rendered equally
4. Channels > Email > New > Builder > Add a Dynamic Content block > Click to create variant and see > Click on the dropdown to view filters and see the icons

### CODE REVIEW

**Comment by andersonjeccel** [comment]
Found more bugs on the 5.x branch

image



Fixed in this pr

image

**Review by RCheesley — DISMISSED** [review]
Fix for the icons in dynamic content on emails ✅ 

screenshot-mautic ddev site-2024 06 11-14_37_04

I noticed a layout issue when creating the form - the tabs are breaking onto two lines which looks a little untidy:

screenshot-mautic ddev site-2024 06 11-14_33_47

Issue with width of checkbox item text label is fixed:
screenshot-mautic ddev site-2024 06 11-14_40_33

Something I noticed during this was that the text here seems a little difficult to read, maybe because of the colours used? The white on teal looks a bit difficult to read. Could be fixed in a separate PR, though, as it doesn't relate to this bugfix PR, I don't think.

screenshot-mautic ddev site-2024 06 11-14_35_24

**Comment by andersonjeccel** [comment]
@RCheesley The tabs are an old issue, it's there in 4.4

image

I fixed it

image


But in the future, adding new tabs will get weird (I duplicated to see the behavior and they get out of the modal)
_(or something I don't know just broke right now in another place while fixing this, you'll have to check the entire platform for all nav tabs before releasing 5.1)_

image

**Comment by RCheesley** [comment]
Thanks for fixing it @andersonjeccel - indeed possibly something that needs to be looked at going forward :)

**Review by escopecz — DISMISSED** [review]
The code changes seem OK. I tested forms, they look fine in the edit as well as in the preview. The form action modals load fine as well. The DEC slot as well:
Screenshot 2024-06-11 at 18 28 20

**Review by RCheesley — CHANGES_REQUESTED** [review]
Thanks, the tabs issue is fixed now. I raised #13826 which I noticed in testing this - on mobiles currently the tabs are stacked into a few different levels so at least you can access them. Not the best experience, admittedly, but it does work:

screenshot-mautic ddev site-2024 06 11-17_30_12

So maybe we should find a way to fix that?

**Comment by andersonjeccel** [comment]
@RCheesley Released another fix
On mobile, it will wrap

**Review by RCheesley — APPROVED** [review]
Awesome, thanks for picking that up and fixing it @andersonjeccel - GTG 🚀

**Pull request merged**
