### PR TITLE
Change function renderArray() to use single quotes for key and value strings

### PR DESCRIPTION
**Pull request by Woeler**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | X
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

This is the same as #5648 but fixed the issues with the pr as the author is not responding.

Description of 5684
Changes function renderArray() to use single quotes for key and value strings instead of double quotes. This allows to use $ in passwords which otherwise gets parsed as variable. If the password contains {$ – without the closing bracket of the complex syntax for variables like {$foo} – this leads to parsing errors of …/app/config/local.php.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1.    Use a password containing {$ in Configuration > Email Settings > Monitored Inbox Settings > Default Mailbox > IMAP password.
2.    'Save & Close' should throw: Parse error: syntax error, unexpected ')', expecting variable (T_VARIABLE) or '{' or '$' - in file /…/app/config/local.php

#### Steps to test this PR:
Same as above

### CODE REVIEW

**Comment by Woeler** [comment]
Agreed, double quotes should be avoided at all costs anyway.

**Comment by Woeler** [comment]
Thanks @kuzmany

**Comment by dongilbert** [comment]
Probably a question for another time, but I'm curious why we're using our own `renderArray()` method instead of PHP's built in `var_export` function to build the contents of the config file? @alanhartless

**Comment by alanhartless** [comment]
@dongilbert No idea :-) It was written that way by another dev back before
Mautic 1.0.

**Pull request merged**
