### PR TITLE
Fixed sendgrid bounce email count for email channel.

### LINKED ISSUE #9045: Sendgrid Bounce details not showing in graph for email chanel tab
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
In the Mautic email channel I had sent a broadcast mail to around 5000 contacts and it was delivered properly.
But for some contact it was bounce, but it is not the problem.
The problem is, the bounce count is not showing in the channel graph but the contacts are added to the bounce segment.

On further check I got to know that the bounce email id is coming  to Mautic properly but it is not storing the details properly due to which we are not able to see the graph.

It is storing null as value for channel id in the bounce details table, which is lead_donotcontact.

On further checking I got known that the **channel ID** is not passed to storing function in the details table.
I am using the **2.16.3** version but the code is the same for **3.0.2**.
Please check the screenshot http://prntscr.com/tqjy70 

Please let us know if it has any solution.

| Q   | A
| --- | ---
| Mautic version | 2.16.3 (also present on 3.0.2)
| PHP version |  7.2.30
| Browser | Mozilla Firefox

### Steps to reproduce
1. Create an Email channel with segment
2. Add some contact with some bounce contact
3. Then send a broadcast mail
 
### Log errors
No error log

Mautic email channel graph is not showing bounce contact count.
Please check the screenshot http://prntscr.com/tqk2ps

For any question I will be more than happy to answer :)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/92170324-sendgrid-bounce-details-not-showing-in-graph-for-email-chanel-tab?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #9532: Reporting problem: Bounce callback via endpoint (SendGrid webhook) Recorded & Processed BUT not showing up on reports
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I have been using the SendGrid callback endpoint on MAUTIC to manage bounces and while they are being recorded and processed, it looks as though they are absent from the reports.

| Q   | A
| --- | ---
| Mautic version | 3.2.1
| PHP version | 7.3
| Browser | Chrome

### Steps to reproduce
1. Configure SendGrid Webhook with the MAUTIC Sendgrid callback with Bounces.
2. Send a deliberate Bounce
3. Notice Bounce is recorded and processed for contact via callback but...
4. Notice it doesn't show up on Reports.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by Bibhudatta-Sahoo-ASMB**
When you send an email from an email channel with sendgrid API as service to send mail and if an email bounces from Sendgrid then the email channel details is not able to store on the `lead_donotcontact` table for that email.
Which in result the email channel graph is not able to show the bounce count details in the email channel page.

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging for  3.0 for bug fixes 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #9045 

#### Description:

Now I am including the channel details to the request data from the mautic side.
So that when Mautic processes the request further, it will be able to store the channel detail in the bounce table. 

#### Steps to test this PR:

1. Use Sendgrid API for "Service to send mail"
2. Create a segment and add some bounced emails
3. Create a email channel with the segment
4. Send a test mail to the contacts
5. After process completed, you are able to see bounce count in the email graph

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/9106"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
@Bibhudatta-Sahoo-ASMB thanks for submitting the PR, it looks like there's something to check on Travis if you could take a look please!

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Hi @TravisBuddy,
I have done the required changes.
So please have a look.

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Hi @TravisBuddy ,
Update the code please check once.

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Hi All,
I am not getting what is the issue? and why it is failed.
I do not know, what to do next?
If any one assist then it will be better.
Thanks

**Comment by RCheesley** [comment]
Hi @Bibhudatta-Sahoo-ASMB thanks for fixing the issues with Travis - I have just rebased against Staging as there have been some PR's merged since you submitted this one, so the branch was out of date causing the code coverage report to be incorrect.

Once the Travis build completes we should hopefully be good to go!

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Hi I have set my email to git.

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Hi @RCheesley,
I am not getting, why the PR is still on pending state. 
Is there any thing pending form my side?
Please let me know.

Thanks,
Bibhudatta Sahoo

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@Bibhudatta-Sahoo-ASMB there still seems to be a problem with your Git configuration.  Please check that the email address you used to make your commits is added to your Git account.

You will need to sign the contributors agreement here: https://www.mautic.org/contributor-agreement anyway regardless of fixing the missing email address. 

You will also need to improve the test coverage before we can merge this pull request, as Codecov is reporting that it will [decrease coverage](https://github.com/mautic/mautic/pull/9106#issuecomment-677107949).  If you need some help with writing the unit tests, I'd suggest reaching out on the [Product Team slack channel](https://mautic.slack.com/archives/CQMKV0RU1), you can get an invite to slack at https://mautic.org/slack.

**Comment by RCheesley** [comment]
@Bibhudatta-Sahoo-ASMB as this requires some work to improve the test coverage, I'm going to assign it to the 3.1.2 milestone. So the deadlines you need to work with are:

* 18th October - 3.1.2 release freeze 

By that time the test coverage needs to be either not changing or improving coverage, and we need to have sufficient tests and code review according to our [governance process](https://www.mautic.org/blog/developer/update-mautic-community-code-governance-processes) for a Tier-2 PR.

**Comment by mabumusa1** [comment]
@Bibhudatta-Sahoo-ASMB I am happy to help you with this PR, I am sure we can get it evaluated before the next release

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Hi @mabumusa1 ,
I want to work on it but actually I do not know what to do next.
Can you help me for that?

Regards,
Bibhudatta Sahoo

**Comment by mabumusa1** [comment]
@Bibhudatta-Sahoo-ASMB sorry I did not reply earlier, I think I got a lot of emails from github so this message must be slipped between them.

We need to do two things: 

1. Get you signed the contributor agreement.
2. Add some tests to the new code you wrote, (the test suite for the EmailBundle can be found inside it)

I am on slack if you want faster communications

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Hi @mabumusa1 , It is okay and thanks for the help.

**Comment by RCheesley** [comment]
@Bibhudatta-Sahoo-ASMB we cannot merge this until you sign the Contributors Agreement - if this is not done by the end of March we will close the PR. Here is the link: https://www.mautic.org/contributor-agreement.

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Hi @RCheesley ,
I have signed the agreement now. Please let me know if you need any thing else.

**Comment by RCheesley** [comment]
@Cla-bot check

**Comment by RCheesley** [comment]
@Bibhudatta-Sahoo-ASMB thanks for that! Are you able to address the automated test coverage issue? We need to add some tests so that this PR either maintains or improves coverage.  At the moment we have a [decrease in coverage ](https://github.com/mautic/mautic/pull/9106#issuecomment-677107949)so this needs to be addressed before we can merge the PR.

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Hi,
I have updated my email id, So please proceed further.

**Comment by riazanovslv** [comment]
I also look forward to this merge.

**Comment by mabumusa1** [comment]
Let's pickup this PR again

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Just to confirm that @Bibhudatta-Sahoo-ASMB has signed the CLA, but the git commits seem to be missing their email address. So this is OK to proceed from the contributors agreement perspective.

**Comment by mabumusa1** [comment]
@Bibhudatta-Sahoo-ASMB thanks for this PR, let's start with the basics your commits are signed with this email `@automate.com`, please sign the contributor agreement with the same email

**Comment by RCheesley** [comment]
@mabumusa1 it's more likely that this email needs to be added to their Github profile - it needs to be there, but doesn't have to be the primary mail.  The CLA bot looks for the email being associated with the GitHub username we have on file, so that's why it's complaining :)

**Comment by mabumusa1** [comment]
> @mabumusa1 it's more likely that this email needs to be added to their Github profile - it needs to be there, but doesn't have to be the primary mail. The CLA bot looks for the email being associated with the GitHub username we have on file, so that's why it's complaining :)

Thanks, @RCheesley for the input.

@Bibhudatta-Sahoo-ASMB May you please check your Github profile and verify that you have your email there, if not please add this email and verify it.

**Comment by mabumusa1** [comment]
@Bibhudatta-Sahoo-ASMB I rebased this PR to the new version of Mautic, it works as expected but we need to verify the coverage before we can test it and make it ready to commit

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Hi,
Thanks for the assistance,
And I have added the email.

**Comment by mabumusa1** [comment]
@cla-bot check

**Comment by mabumusa1** [comment]
@Bibhudatta-Sahoo-ASMB the issue is is still there, please connect with me on Slack we can solve it in a minute

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
> @Bibhudatta-Sahoo-ASMB the issue is is still there, please connect with me on Slack we can solve it in a minute

I have send you the invite

**Comment by mabumusa1** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Hey folks!

Just following up on this PR - would be great to finally get it merged!

@mabumusa1 can you help with the test coverage and the codestyle issue? Then we should be good to go hopefully.

**Comment by escopecz** [comment]
I'm closing this PR in favor of https://github.com/mautic/mautic/pull/11052. Please shout if you disagree. It can be re-opened.

**Pull request closed without merging**
