### PR TITLE
TPROD-356 Removing sortable panels

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [y]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [y] (added a note to the change log)
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://mautic.atlassian.net/browse/TPROD-356

#### Description:

There are PHP templates that we need to refactor to Twig but we couldn't find any place where they are used. The code was introduced in this massive commit https://github.com/mautic/mautic/commit/c90f59d5b56608190fac791f6c008f40db29c733# but I cannot find it used there either. So instead of migrating those PHP templates to Twig we are removing it together with related JS and CSS.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. As it was added in the PR that was adding the ChannelBundle aka Marketing Messages then click through the UI and make sure it works as before.

### CODE REVIEW

**Comment by escopecz** [comment]
This is blocked until https://github.com/mautic/mautic/pull/12021 is merged as Marketing Messages are broken right now

**Review by RCheesley — CHANGES_REQUESTED** [review]
When changing the date on the filter for a marketing message:

```
[2023-02-23 18:55:59] mautic.CRITICAL: Exception thrown when handling an exception (Twig\Error\SyntaxError: Unknown "mautibotGetImage" function. at /var/www/html/app/bundles/CoreBundle/Views/Exception/500.html.twig line 3) {"exception":"[object] (Twig\\Error\\SyntaxError(code: 0): Unknown \"mautibotGetImage\" function. at /var/www/html/app/bundles/CoreBundle/Views/Exception/500.html.twig:3)
[stacktrace]
#0 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(457): Twig\\ExpressionParser->getFunctionNodeClass('mautibotGetImag...', 3)
#1 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(235): Twig\\ExpressionParser->getFunctionNode('mautibotGetImag...', 3)
#2 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(175): Twig\\ExpressionParser->parsePrimaryExpression()
#3 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(70): Twig\\ExpressionParser->getPrimary()
#4 /var/www/html/vendor/twig/twig/src/ExpressionParser.php(674): Twig\\ExpressionParser->parseExpression()
#5 /var/www/html/vendor/twig/twig/src/TokenParser/SetTokenParser.php(41): Twig\\ExpressionParser->parseMultitargetExpression()
#6 /var/www/html/vendor/twig/twig/src/Parser.php(170): Twig\\TokenParser\\SetTokenParser->parse(Object(Twig\\Token))
#7 /var/www/html/vendor/twig/twig/src/Parser.php(83): Twig\\Parser->subparse(NULL, false)
#8 /var/www/html/vendor/twig/twig/src/Environment.php(488): Twig\\Parser->parse(Object(Twig\\TokenStream))
#9 /var/www/html/vendor/twig/twig/src/Environment.php(516): Twig\\Environment->parse(Object(Twig\\TokenStream))
#10 /var/www/html/vendor/twig/twig/src/Environment.php(348): Twig\\Environment->compileSource(Object(Twig\\Source))
#11 /var/www/html/vendor/twig/twig/src/Environment.php(309): Twig\\Environment->loadTemplate('__TwigTemplate_...', 'MauticCoreBundl...')
#12 /var/www/html/vendor/symfony/twig-bridge/TwigEngine.php(135): Twig\\Environment->load('MauticCoreBundl...')
#13 /var/www/html/vendor/symfony/twig-bridge/TwigEngine.php(54): Symfony\\Bridge\\Twig\\TwigEngine->load('MauticCoreBundl...')
#14 /var/www/html/vendor/symfony/templating/DelegatingEngine.php(41): Symfony\\Bridge\\Twig\\TwigEngine->render('MauticCoreBundl...', Array)
#15 /var/www/html/vendor/symfony/framework-bundle/Controller/ControllerTrait.php(213): Symfony\\Component\\Templating\\DelegatingEngine->render('MauticCoreBundl...', Array)
#16 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(380): Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController->renderView('MauticCoreBundl...', Array)
#17 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(213): Mautic\\CoreBundle\\Controller\\CommonController->ajaxAction(Array)
#18 /var/www/html/app/bundles/CoreBundle/Controller/ExceptionController.php(111): Mautic\\CoreBundle\\Controller\\CommonController->delegateView(Array)
#19 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(169): Mautic\\CoreBundle\\Controller\\ExceptionController->showAction(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Symfony\\Component\\ErrorHandler\\Exception\\FlattenException), Object(Symfony\\Bridge\\Monolog\\Logger))
#20 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 2)
#21 /var/www/html/app/bundles/CoreBundle/EventListener/ExceptionListener.php(63): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 2, false)
#22 /var/www/html/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(126): Mautic\\CoreBundle\\EventListener\\ExceptionListener->onKernelException(Object(Symfony\\Component\\HttpKernel\\Event\\ExceptionEvent), 'kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#23 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener->__invoke(Object(Symfony\\Component\\HttpKernel\\Event\\ExceptionEvent), 'kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher))
#24 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Event\\ExceptionEvent))
#25 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners(Array, 'kernel.exceptio...', Object(Symfony\\Component\\HttpKernel\\Event\\ExceptionEvent))
#26 /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(168): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch(Object(Symfony\\Component\\HttpKernel\\Event\\ExceptionEvent), 'kernel.exceptio...')
#27 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(229): Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher->dispatch(Object(Symfony\\Component\\HttpKernel\\Event\\ExceptionEvent), 'kernel.exceptio...')
#28 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(92): Symfony\\Component\\HttpKernel\\HttpKernel->handleThrowable(Object(ErrorException), Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#29 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#30 /var/www/html/app/AppKernel.php(105): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#31 /var/www/html/app/middlewares/CORSMiddleware.php(82): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#32 /var/www/html/app/middlewares/HSTSMiddleware.php(35): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#33 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(34): Mautic\\Middleware\\HSTSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#34 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(52): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#35 /var/www/html/app/middlewares/VersionCheckMiddleware.php(58): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#36 /var/www/html/app/middlewares/TrustMiddleware.php(42): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#37 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#38 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#39 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#40 {main}
"} {"hostname":"mautic-web","pid":3190}
[2023-02-23 18:55:59] mautic.ERROR: Twig\Error\SyntaxError: Unknown "mautibotGetImage" function. - in file /var/www/html/app/bundles/CoreBundle/Views/Exception/500.html.twig - at line 3  {"hostname":"mautic-web","pid":3190}

```

Also, when I send a marketing message, the tabs are not working as I would expect them to, nor is the chart at the top. Video: https://watch.screencastify.com/v/P0DcsMzcYlhIB8MLZugf

**Comment by escopecz** [comment]
@RCheesley I don't think any of that is related to the removed code. Could you test on the 5.x branch to confirm it behaves the same?

**Comment by mabumusa1** [comment]
I think this error is related to this [line](https://github.com/mautic/mautic/blob/5.x/app/bundles/CoreBundle/Views/Exception/500.html.twig#L3), although we tested this twig file. it is strange that this error shows here

**Comment by RCheesley** [comment]
Indeed looks like a bug on the 5.x branch (#12028) and was not able to reproduce the issue with the 500 error since that time so must have been a transient gremlin!

**Review by RCheesley — APPROVED** [review]

**Review by mabumusa1 — APPROVED** [review]
I did a code review, this PR looks good to go

**Review by volha-pivavarchyk — APPROVED** [review]
UI works well as before.

**Pull request merged**
