### PR TITLE
Feature new click filters

### PR DESCRIPTION
**Pull request by alanhartless**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" 
| Bug fix?                               |no
| New feature?                           | yes
| Deprecations?                          |no
| BC breaks?                             |no
| Automated tests included?    | yes

#### Description:
This PR is dependent on https://github.com/mautic/mautic/pull/8649 which must be merged first. 

#8649 had code that included filters from #7786 and #7194. They were removed in https://github.com/mautic/mautic/pull/8649/commits/2cd018a59c214fe45d353e82c7dd22d249cc4b51 so they could be introduced by a new PR (this one). 

This introduces the following new segment filters:
1. Unsubscribed SMS - Manual
2. Clicked any link from any email (existed as `URL from email` but uses a new query builder service now)
2. Clicked any link from any email (date)
3. Clicked any link from any text message
4. Clicked any link from any text message (date)

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Test each of the filters above. They should be self explanatory. 
3. For the unsubscribed SMS, the easiest way to test is to simply publish twilio manually in plugin_integration_settings then go to a contact's profile -> Preference Center -> uncheck the Text Messages channel
4. For the others, you'll need to configure URLs in the channel content and send either the email or SMS to the contact then click the link. 
5. Review the functional tests

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/9852"></a>

### CODE REVIEW

**Review by RCheesley — COMMENTED** [review]
While it does actually work, I think that we should be preventing people from saving if they have not populated the field with the date option. At the moment it throws a 500 error.

1. Unsubscribed SMS - Manual ✅ 
2. Clicked any link from any email (existed as URL from email but uses a new query builder service now) ✅ 
3. Clicked any link from any email (date) ❌ 
4. Clicked any link from any text message ✅ 
5. Clicked any link from any text message (date) ❌ 

3 & 5: Error on saving the segment **without anything in the date field** - save should be blocked, I think: 500 Internal Server Error - PHP Notice - Uninitialized string offset: 0

Log:

```
[2022-02-25 17:35:55] mautic.CRITICAL: Uncaught PHP Exception ErrorException: "PHP Notice - Uninitialized string offset: 0" at /var/www/html/app/bundles/LeadBundle/Form/DataTransformer/FieldFilterTransformer.php line 94 {"exception":"[object] (ErrorException(code: 0): PHP Notice - Uninitialized string offset: 0 at /var/www/html/app/bundles/LeadBundle/Form/DataTransformer/FieldFilterTransformer.php:94)
[stacktrace]
#0 /var/www/html/app/bundles/LeadBundle/Form/DataTransformer/FieldFilterTransformer.php(94): Mautic\\CoreBundle\\ErrorHandler\\ErrorHandler->handleError(8, 'PHP Notice - Un...', '/var/www/html/a...', 94, Array)
#1 /var/www/html/vendor/symfony/form/Form.php(1078): Mautic\\LeadBundle\\Form\\DataTransformer\\FieldFilterTransformer->reverseTransform(Array)
#2 /var/www/html/vendor/symfony/form/Form.php(649): Symfony\\Component\\Form\\Form->normToModel(Array)
#3 /var/www/html/vendor/symfony/form/Form.php(579): Symfony\\Component\\Form\\Form->submit(Array, true)
#4 /var/www/html/vendor/symfony/form/Extension/HttpFoundation/HttpFoundationRequestHandler.php(109): Symfony\\Component\\Form\\Form->submit(Array, true)
#5 /var/www/html/vendor/symfony/form/Form.php(493): Symfony\\Component\\Form\\Extension\\HttpFoundation\\HttpFoundationRequestHandler->handleRequest(Object(Symfony\\Component\\Form\\Form), Object(Symfony\\Component\\HttpFoundation\\Request))
#6 /var/www/html/app/bundles/CoreBundle/Controller/AbstractFormController.php(167): Symfony\\Component\\Form\\Form->handleRequest(Object(Symfony\\Component\\HttpFoundation\\Request))
#7 /var/www/html/app/bundles/LeadBundle/Controller/ListController.php(185): Mautic\\CoreBundle\\Controller\\AbstractFormController->isFormValid(Object(Symfony\\Component\\Form\\Form))
#8 /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php(456): Mautic\\LeadBundle\\Controller\\ListController->newAction(0, '')
#9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(158): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('new', 0, 0, '')
#10 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#11 /var/www/html/vendor/symfony/http-kernel/Kernel.php(201): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /var/www/html/app/AppKernel.php(115): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /var/www/html/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /var/www/html/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 /var/www/html/app/middlewares/Dev/IpRestrictMiddleware.php(61): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#16 /var/www/html/app/middlewares/VersionCheckMiddleware.php(67): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 /var/www/html/app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#18 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#19 /var/www/html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#20 /var/www/html/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#21 {main}
"} 
```

**Comment by escopecz** [comment]
Thanks Ruth! I fixed the PHP notice so it wouldn't show up in the logs on production or caused troubles in dev env. The date field can be empty now. Setting validation that some value is required would be difficult as we don't have that support for any filters as far as I can see. So I'd leave it for another PR.

**Comment by escopecz** [comment]
@npracht @kuzmany @RCheesley this is blocking further work on https://github.com/mautic/mautic/pull/10903 which is needed for open sourcing the Custom Objects plugin. So we have to merge this asap.

**Review by kuzmany — APPROVED** [review]
Works for me 👍 
Tested dates and clicks combination for emails and sms.
Unit tests included 👍

**Review by RCheesley — APPROVED** [review]
This is good for me given that my feedback has been addressed. The other issue around not blocking the saving of a segment with an empty field where a value is expected can be addressed in a separate issue/PR.

**Pull request merged**
