### PR TITLE
Include scheduled conditions in upcoming events and timeline

### PR DESCRIPTION
**Pull request by alanhartless**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

If a condition is scheduled, it's not displayed in the campaign upcoming events or in the timeline as a scheduled event making it difficult to know what's going on. This PR changes the behavior to include both scheduled actions and conditions.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a campaign that has a scheduled condition and a scheduled action.
2. Execute the campaign
3. View the details page for a contact in the campaign
4. Note that the condition does not show up in the upcoming events nor in the timeline

#### Steps to test this PR:
1. Apply the PR and now both the condition should show up in both places.

### CODE REVIEW

**Comment by mqueme** [comment]
I have setup a campaign with scheduled action send email, but it did not show in my campaign contact's timeline.

**Comment by escopecz** [comment]
@mqueme could you retest? It clearly worked for me. Maybe some screens will help:
scheduled-conditions
scheduled-conditions-campaign

**Comment by mqueme** [comment]
No, it still does not work. I tested like this: 
screen shot 2017-04-18 at 16 12 49
screen shot 2017-04-18 at 16 13 11

**Comment by escopecz** [comment]
The problem is that your campaign doesn't have scheduled condition, but scheduled action.

**Comment by escopecz** [comment]
I retested with campaign action as well as condition and it worked.
screen shot 2017-04-20 at 15 51 40
screen shot 2017-04-20 at 15 51 18

**Comment by mqueme** [comment]
This worked for me

**Comment by matishaladiwala** [comment]
works!

**Pull request merged**
