### PR TITLE
Added timezone and preferred_locale to JS tracking event

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR added option to set timezone and preferred_locale from JS tracking code.

Timezone detection taken from https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js#L443

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Set timezone and preferred_locale  custom fields as Publicly updatable
image
3. Then add tracking code to your page
4. Check If these fields were update based on your browser settings

image

### CODE REVIEW

**Review by florentpetitjean — APPROVED** [review]
Tested  and works great !

**Review by florentpetitjean — CHANGES_REQUESTED** [review]
Hello @kuzmany 

I notice that the preferred locale field is not really filled here.  I just check the contact page with my first test and saw this : 
image

So I tought that was good.
But when I edit the contact there is nothing in the field.
image

Preferred locale is a list  and I think the info from the script doesn't match the list value so it doesn't register. 
Can you do something about it ? 

Thanks

**Comment by kuzmany** [comment]
@florentpetitjean last commit should fixed it

**Review by florentpetitjean — DISMISSED** [review]
Works now !

Thanks

**Review by npracht — DISMISSED** [review]
Working like a charm in production environment for 3 months

**Review by RCheesley — CHANGES_REQUESTED** [review]
Struggling to get this to work - followed the instructions and set the two fields to be publicly update-able, and am accessing a landing page which has the tracking script enabled.

Mautic picks up the page hits, but the fields are not being populated.
screenshot-local mautic3-2020 08 15-16_48_23

**Comment by kuzmany** [comment]
@RCheesley If you don't work on dev enviroment, require `mautic:assets:generate`. Please check it first

**Comment by RCheesley** [comment]
I was in the dev environment (you can see the toolbar in the footer of the screenshot - mid way through as the screen scrolled when I took the screenshot :) )

**Comment by kuzmany** [comment]
@RCheesley I am not sure if on 127.0.0.1 tracking work properly. These IP is on do not track list.

You should see both parameter in tracking event in browser console (what do you see?)

image

**Comment by RCheesley** [comment]
Perhaps you could share where I can find that information, happy to check but I don't know where to start looking and the screenshot doesn't indicate to me where in developer tools I'll find that information.

**Comment by RCheesley** [comment]
Bumping to 3.2 due to lack of testing in 3.x.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by npracht** [comment]
@mautic/acquia-po can we have a developer testing that one. A little tricky for end user. Thanks

**Review by npracht — APPROVED** [review]
👍

**Comment by npracht** [comment]
@kuzmany is it the same as https://github.com/mautic/mautic/pull/7399 with less code ?

**Comment by RCheesley** [comment]
Testing this again on Mautibox and I am finding that the locale is being set to 'en' but the [timezone is not being set at all](https://mautibox.com/8205/s/contacts/view/62). Therefore unable to approve this until more detailed instructions are provided or someone else is able to test.

**Review by dadarya0 — APPROVED** [review]
No issue found in code and working as expected.

**Comment by dadarya0** [comment]
I have tested, it is working as expected.
Screenshot 2021-06-07 at 6 18 55 PM
Screenshot 2021-06-07 at 6 19 08 PM
Screenshot 2021-06-07 at 6 19 36 PM

**Comment by RCheesley** [comment]
@all-contributors please add @florentpetitjean for userTesting

**Pull request merged**
