### PR TITLE
[UX] Change "Has full system access?" label to "Is administrator?"

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR updates the user interface to enhance clarity around user permissions. By changing the label from “Has full system access?” to “Is administrator?”, we eliminate ambiguity and align with common terminology being used on user's settings. This change is accompanied by a tooltip that offers further details, ensuring users have a clear understanding of administrative roles within the system. The update benefits all users by providing a more intuitive experience and preventing potential misunderstandings regarding access levels.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Roles
3. Create new
4. Look at the label

image

### CODE REVIEW

**Review by roboparker — APPROVED** [review]

**Comment by Mike-Dropsolid** [comment]
Administrator, Super user, Super admin, ... many terms are used.

I find the original description more clear.

**Comment by RCheesley** [comment]
I don't think this is the right terminology. Being an administrator is not always synonymous with having full system access. An administrator might for example have all access rights except for delete, and a super user have full system access. The Mautic user would define that as a role, and call it 'administrator' or 'super user'. This is how Mautic is set up, and I think changing this as proposed would add more confusion.

I think this switch makes more sense as it is currently, explaining clearly what it actually does - grants full system access - rather than referring to a role title which can be ambiguous.

I'm about a 6/10 for not merging this PR for the reasons above.

**Comment by escopecz** [comment]
I'm thinking the same as Ruth and Mike. The original label was clear.

**Review by Esthertests — COMMENTED** [review]
.

**Review by Esthertests — APPROVED** [review]
LGTM
on prod
image

on pr changes
image

**Comment by RCheesley** [comment]
@andersonjeccel looks like we're not in favour of merging this PR for the reasons that have been outlined, therefore I'm going to go ahead and close it.

**Pull request closed without merging**
