### PR TITLE
Fix issue with pre-populating the value of a form field from the URL query parameters

### PR DESCRIPTION
**Pull request by volha-pivavarchyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [yes]
| New feature/enhancement? (use the a.x branch)      | [no]
| Deprecations?                          | [no]
| BC breaks? (use the c.x branch)        | [no]
| Automated tests included?              | [no] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR proposes a solution with pre-filled field values from URL request parameters.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create new form or use the existing one
3. Add the form to a landing page
4. Pass values as the URL query parameters to prefil it
5. Inject the form dynamically or copy the entire output into the external page
6. Pass values as the URL query parameters to prefil it

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11077"></a>

### CODE REVIEW

**Comment by kuzmany** [comment]
Note: we need consider if  https://github.com/mautic/mautic/pull/9239 is duplicate

**Comment by escopecz** [comment]
@volha-pivavarchyk Thanks for this! Could you please write functional tests where you create form with various field types (it's good to use API for this as it will create the submissions table for you), a landing page that embeds the form and then load it with various query params and asserting that they are properly added to the inputs? Let me know if you need any help with that.

**Review by jos0405 — DISMISSED** [review]
Works as expected, the form fields are filled with the query parameters

**Comment by escopecz** [comment]
@volha-pivavarchyk please rebase on top of 4.x instead of 4.2. Also change the base branch for this PR. The next version will be 4.3.0.

**Comment by ekkeguembel** [comment]
Not sure it's caused by this PR or never worked properly, but here's a little issue :
### URL decoding of the value %2B (i.e. the plus sign) seems broken.

Relevance: When a URL parameter - e.g. an email address - contains an encoded @ sign (typically triggered by |true in an email Token), this works fine as expected.
Example: `john%40doe.com`-> `john@doe.com`  CORRECT

But when it contains a plus sign (which is not illegal or unused; e.g. Gmail supports that), that PLUS sign is turned into a BLANK and thus breaks the email.
Example: `john%2B1%40doe.com`-> `john 1@doe.com`  BROKEN, expected value is `john+1@doe.com`

FYI other chars that I tested all seem to work

**Review by OnyXxL — APPROVED** [review]

**Review by OnyXxL — DISMISSED** [review]

**Comment by RCheesley** [comment]
Thanks for making the review @OnyXxL :)

**Comment by RCheesley** [comment]
@all-contributors please add @OnyXxL for UserTesting

**Comment by escopecz** [comment]
@volha-pivavarchyk can you please address [the comment from Ekke](https://github.com/mautic/mautic/pull/11077#issuecomment-1130032524)?

**Comment by OnyXxL** [comment]
Hi,

The issue on Mautic 4.4 is no longer encountered:
- on form preview _(e.g. https://mauticurl/s/forms/preview/1?nom=test )_
- on a landing page containing a Mautic form
The /app/bundles/FormBundle/Helper/FormFieldHelper.php was the issue, corrected with 5c50208 commit

The problem still exists on forms inserted on external pages, at least with external domain, even after:
- replacing /media/js/mautic-form-src.js and /app/bundles/FormBundle/Helper/FormFieldHelper.php with the one from the 5c50208 commit
- clearing Mautic cache from CLI: bin/console cache:clear
- rebuilding form cache from the "Components -> Forms" list

**Comment by volha-pivavarchyk** [comment]
This is actually the case. When url contains "+" sign, it will be replaced by spaces. It needs to be escaped. I'll try to come up with a solution in the next few days.

**Comment by volha-pivavarchyk** [comment]
I think [PR #9239](https://github.com/mautic/mautic/pull/9239) is a duplicate. I'll test it and see if this PR solution is better in the next few days.

**Comment by volha-pivavarchyk** [comment]
@ekkeguembel I fixed the issue. Could you please check it again.

**Comment by volha-pivavarchyk** [comment]
@OnyXxL Could you try running the `mautic:assets:generate` command before testing forms inserted on external pages

**Comment by volha-pivavarchyk** [comment]
@kuzmany The [PR #9239](https://github.com/mautic/mautic/pull/9239) is the same partly. The PR #9239 fixes the problem on form preview and on a landing page containing a form. The problem remains on forms inserted on external pages for me. The js-function fixes this in the current PR.

However, there is one small thing I like more about the PR #9239. I can integrate it into the current PR.

**Review by OnyXxL — DISMISSED** [review]

**Comment by OnyXxL** [comment]
> @OnyXxL Could you try running the `mautic:assets:generate` command before testing forms inserted on external pages

Thank you @volha-pivavarchyk , after replacing _mautic-form-src.js_ and _FormModel.php_ with the ones of the commit cddf6a5, the fields are pre-populated in Mautic 4.4.0 forms inserted in external pages.

**Review by OnyXxL — DISMISSED** [review]

**Comment by stevedrobinson** [comment]
commenting to make sure this doesn't go stale. We're still patching this on our production instances. Not sure if it's needed for M5.

**Comment by escopecz** [comment]
@volha-pivavarchyk could you please rebase this to the 5.x branch and fix the CI? Let's get this merged :)

**Comment by mabumusa1** [comment]
@volha-pivavarchyk it would be great if we can merge this PR on M5 branch, It is almost done, let's push it over the finish line.

**Comment by volha-pivavarchyk** [comment]
I'll do it today or tomorow

**Comment by volha-pivavarchyk** [comment]
@escopecz @mabumusa1 I rebased the branch

**Review by escopecz — DISMISSED** [review]
Thanks!

**Comment by escopecz** [comment]
@volha-pivavarchyk there is a failing test

**Comment by volha-pivavarchyk** [comment]
@escopecz The migration to twig templates was the reason the tests failed. I fixed the code to make the tests work and add new test cases to my test.

**Review by escopecz — APPROVED** [review]
The code looks good 👍

**Comment by escopecz** [comment]
@jos0405 @OnyXxL could one of you please re-test pre-filling the JS embedded form one more time after the changes?

**Comment by MadlenF** [comment]
Successfully tested this PR, works on Mautic landing page and external page, also the plus sign in email addresses works now! 👍

**Pull request merged**
