### PR TITLE
Fix SendGird Attachments on Queue Mode

### LINKED ISSUE #10356: SendGrid API does not send attachments on queue mode
### Mautic Version

4.0.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Send an email with attachment included, the attachment was not delivered when the queue mode is selected but it was working as expected when it was in immediate mode.

### How can we reproduce this issue?

Step 1: Select queue mode
Step 2: Select SendGrid API and configure the key
Step 3: Send an email with an attachment
Step 4: No attachment is found in the email sent

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 4.x
| New feature/enhancement? (use the a.x branch)      | No
| Deprecations?                          | No
| BC breaks? (use the c.x branch)        |  No
| Automated tests included?              | Yes 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #10356 

#### Steps to test this PR:

1. Configure SendGrid to be your email sending service
2. Create an email and attachment to it
3. Try to send the email while you are using queue mode
4. When you receive the email there will be no attachment
5. Apply this PR
6. Re-test the same email you should get an attachment this time

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10566"></a>

### CODE REVIEW

**Comment by mabumusa1** [comment]
@luizeof Please review this PR, it would solve the queue mode for sendgrid attachements

**Comment by RCheesley** [comment]
@mabumusa1 could you please provide some test instructions so that people can help with reviewing this PR? Many thanks!

Also looks like you have some PHPSTAN issues to fix now we bumped the level up.

**Review by RCheesley — APPROVED** [review]
Thanks for the PR @mabumusa1 - tested with Sendgrid and I was able to reproduce the bug (no attachment) and the PR being applied resulted in the file being correctly attached.

Just needs a code review!

screenshot-mail google com-2022 02 03-19_06_37

**Review by kuzmany — APPROVED** [review]
Code looks good.
Tests included
👍

**Pull request merged**
