### PR TITLE
Pretty PHPUNIT results

### PR DESCRIPTION
**Pull request by escopecz**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | /
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | /
| BC breaks? | /
| Deprecations? | /

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
When I saw https://laravel-news.com/phpunit-pretty-result-printer I couldn't resist to try it for Mautic. The result looks like this:
screen shot 2018-03-22 at 10 03 02

I like that better. What do you guys think?

#### Steps to test this PR:
1. Run `bin/phpunit -d memory_limit=2048M --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist`

### CODE REVIEW

**Comment by Maxell92** [comment]
Great :) 👍

**Comment by heathdutton** [comment]
Love it! 👍

**Comment by escopecz** [comment]
But it fails for PHP 5.6.19 😢

**Comment by heathdutton** [comment]
Try upgrading to 0.7.0 (latest)?

**Comment by escopecz** [comment]
Won't work. Composer resolved to 0.5.4 itself based on Mautic's minimal PHP version requirements. The thing is that this is the last version that doesn't have PHP version requirement configured. But there clearly is. Will have to close this until Mautic drops the prehistoric PHP version support.

**Pull request closed without merging**
