### PR TITLE
New date operator for campaign form field value condition

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Yes
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

Bugfix/feature donate by www.newcom4u.ch

[//]: # ( Required: )
#### Description:
PR added date  operator to campaign Form field value condition, same like you can use in Contact field value condition.

image

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1.  Create  campaign form and add multi select field. Send form  and choose more option from multi elect
2.  Create campaign and use form field condition based on multi select field
3. Condition doesn't work

#### Steps to test this PR:
1.  Apply PR, clear cache and regenerate assets   `php app/console m:a:g`
2.  Test date field type and new date operator 
Date operator works same like date operator in Contact field value condition.

### CODE REVIEW

**Comment by kuzmany** [comment]
Label: Bug

**Comment by kuzmany** [comment]
Label: WIP

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by tpilet** [comment]
Test it's work

**Comment by alanhartless** [comment]
@kuzmany The goal now is not about writing less code but writing legible code that is testable. There seem to be a lot of newly added if/else/elseifs in the PHP code.

**Comment by kuzmany** [comment]
I have to close this PR, because there is no energy and budget for rebuild this PR even it is useful :( 
If somebody want donate it, let me know and we can finish it.

**Pull request closed without merging**
