### PR TITLE
Add support for RSS feed from mautic for user notifications

### PR DESCRIPTION
**Pull request by dongilbert**
Please answer the following questions. 

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Related user documentation PR URL | N/A
| Related developer documentation PR URL | N/A
| Issues addressed (#s or URLs) | N/A
| BC breaks? | N
| Deprecations? | N

#### Description:
This PR adds support to the notifications tray to receive and display notifications from Mautic to keep you up to date on the latest news regarding updates, upcoming features, and general information from Mautic.

#### Steps to test this PR:
1. Apply the PR
2. run `composer update` from the command line.
3. Load your mautic dashboard, and you'll see new updates in your notification tray.

### CODE REVIEW

**Comment by dongilbert** [comment]
The URL in the `updateUpstreamNotifications` is subject to change.

**Comment by alanhartless** [comment]
1. The notifications are just displaying the URL to the article - is that intended? It would be good if we could instead embed the title of the article as the notification, just a touch of the body, with a read more link (if that's possible).

2. It's re-injecting the same notifications every time I clear them, log out and back in.

**Comment by mqueme** [comment]
when I click on a contact that has been created, it takes me to the edit view. Should it take me to the detail view instead?

**Comment by alanhartless** [comment]
@mqueme It was just injecting what was in the flash which returns to the lead edit form. It's now defaulted to _not_ inject flashes into the notification tray.

**Comment by escopecz** [comment]
I'm not quite sure if my test was successful:
mautic-notification

**Comment by alanhartless** [comment]
@escopecz Sorry - the default URL is currently tagged to something we don't have any actual notifications for :-D Add this to your local.php and clear the cache:
```
'rss_notification_url'           => 'https://mautic.com/?feed=rss2'
```

That'll pull in Mautic's blog entries as notifications.

**Comment by escopecz** [comment]
Yep, it works with the blog RSS :+1:

**Pull request merged**
