### PR TITLE
Copy to CC or BCC should send an email even if TO field is empty.

### LINKED ISSUE #10720: Form submission copy to bcc doesn't work
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Looks like this issue "bcc will not receive form results" (see stale: https://github.com/mautic/mautic/issues/5967 or this https://github.com/mautic/mautic/issues/10328) is still happening. In my case with Amazon SES API connection.

### How can we reproduce this issue?

1. Create a form action.
2. Reply to submitter (not necessary) and bcc your own adress.
3. Submit a form and check your inbox... 

No information.

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/108497661-form-submission-copy-to-bcc-doesn-t-work?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by biozshock**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ x ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ x ] 
| Issue(s) addressed                     | Fixes #10720 

#### Description:
Allow emails to be sent from the form if the TO or CC fields are empty.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create form and add email field. Create a "send form results" action.
3. Set CC or BCC or both w/o adding TO field.
4. Send the form via preview or via https://your.host/form/[ID]
5. Check your email/mailhog

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11405"></a>

### CODE REVIEW

**Review by kuzmany — COMMENTED** [review]
I am not sure If it is good idea.
If somebody want send email as blind copy, Mautic will send it as regular recipients.  Usage of blind copy is for some reason (do not want to show all recipients in header)

@RCheesley  @escopecz what do you think

**Comment by RCheesley** [comment]
As I understand it, the issue is that if you only include a CC or BCC, and nothing in the TO field, the email should still be sent. The emails remain in the CC or BCC field, but the TO field is empty when the email is sent.

This is quite a common practice (I have seen it quite a lot just using a BCC field).

However, the issue reported here: https://github.com/mautic/mautic/issues/10720#issuecomment-1034569944 seems to suggest that forms are not passing the CC and BCC at all - regardless of whether a TO field is set, at least that is my understanding.

I'm not able to test the PR or the bug with Gitpod as it seems to open the wrong URL on form submission (raised a bug with them about that) but I do agree that we deffo should not be surfacing the CC/BCC fields into other fields (eg the TO field). Will try to test locally and report back!

**Comment by biozshock** [comment]
Please test the newer version that does not move address headers around. I've tested with CC only, BCC only and CC+BCC and it seems that the bug mentioned in the code is not relevant for the version we are using in composer, and 5.x will have symfony/mailer i believe.

**Comment by nick-vanpraet** [comment]
Tried:

**CC+BCC**: no To header, only CC
**CC**: no To header, only CC
**BCC**: no To header, no CC header

Emails all arrived correctly. One thing, though. Now you can save the form action without filling in To, CC, or BCC. Don't know how we feel about that, or if there's an easy way Mautic can do "one of X fields must have a value".

I did notice Gitpod is creating the workspace with a us in the url, which then is unavailable. Running `ddev restart` gives me a new url with eu in it, but in Mautic's config the site url is still the us one so submitting forms redirects to that one. Easy fix is updating the site url in config, so I could properly test the entire flow.

**Comment by nick-vanpraet** [comment]
Also tried only TO header, that still works fine as well. Seeing a normal "TO" header in the email in that case.

**Review by escopecz — APPROVED** [review]
The code changes make sense. Nice tests added. Thanks!

**Comment by RCheesley** [comment]
> I did notice Gitpod is creating the workspace with a us in the url, which then is unavailable. Running `ddev restart` gives me a new url with eu in it, but in Mautic's config the site url is still the us one so submitting forms redirects to that one. Easy fix is updating the site url in config, so I could properly test the entire flow.

This is fixed in https://github.com/mautic/mautic/pull/11409 so should not be a problem going forward, just FYI :)

**Pull request merged**
