### PR TITLE
 Fix mtc.js xhr.readyState condition

### PR DESCRIPTION
**Pull request by tykarol**
| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | No
| Automated tests included? | No
| Related user documentation PR URL | No
| Related developer documentation PR URL | No
| Issues addressed (#s or URLs) | No
| BC breaks? | No
| Deprecations? | No

#### Description:
Change of the condition checking the value of xhr.readyState in the MauticJS.makeCORSRequest().

This changes fixed the problem with:
- sending next events (`mt('send', 'pageview')`)
- loading a script for Focus Item (triggered in campaign)
- others (eg. `ga()`, `fbq()`, ...) - based on code that did not run (from `mauticPageEventDelivered` event)

Issue verified on Chrome and Firefox browser on the Linux Mint.

#### Steps to reproduce the bug:
1. Open browser - Chrome or Firefox (verified on Linux)
2. Check the value of `XMLHttpRequest.DONE` and `XMLHttpRequest.UNSET` in the browser console and also compare it to expected value: `4 === XMLHttpRequest.DONE`
3. `XMLHttpRequest.DONE` is a function (native code)

#### Steps to reproduce the bug with mtc.js:
1. Add mtc.js script on your page
2. Add event listener for `mauticPageEventDelivered` event:
```
document.addEventListener('mauticPageEventDelivered', function(e) {
    console.log('TEST')
});
```
3. Add `mt('send', 'pageview')`
4. `TEST` text will never be displayed

#### Steps to reproduce the bug with mtc.js:
1. Add mtc.js script on your page
2. After page loaded run in browser console:
```
MauticJS.makeCORSRequest('POST', MauticJS.pageTrackingCORSUrl, {}, function(response) {
    console.log('SUCCESS')
}, function() {
    console.log('ERROR');
});
```
3. None of the functions have been called

### CODE REVIEW

**Comment by tykarol** [comment]
@escopecz @kuzmany can you please review?

**Comment by dennisameling** [comment]
@tykarol 
For me, both in Chrome on Windows and on Firefox Linux, `XMLHttpRequest.DONE` is not a function but the number 4:

image

Are you sure this PR is still relevant? It's been open for a while, sorry for that 😊 thanks in advace!

**Comment by tykarol** [comment]
@dennisameling  Maybe, it's no longer required. I checked also and on Chrome on Windows and Linux I get the value.

**Comment by dennisameling** [comment]
Alright, I will go ahead and close the PR for now. Should this issue pop up again, happy to re-open so we can investigate 👍 thanks for your efforts!

**Pull request closed without merging**
