### PR TITLE
Changes company links to action /view in reports

### PR DESCRIPTION
**Pull request by julienWebmecanik**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.3 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no

#### Description:
Some links in the reports details were pointing toward a /edit action and we want all of them to point to a /view action.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create a custom report and add some ID fields.
3. Check that the link on the ID point towards a 'view' action

OLD
Screenshot 2021-03-09 at 10 24 16

NEW 
Screenshot 2021-03-09 at 10 25 43

### CODE REVIEW

**Review by RCheesley — CHANGES_REQUESTED** [review]
I tried to apply this PR but I found that it forced ID's that do not have anything to view - such as owner ID or Stage ID - to use view. This results in a 404 which is a poor user experience.

We should only use /view where that exists and makes sense to use - the cases I can think of are contacts, segments, emails, AB test ID, assets, company, marketing message, campaign, form, landing pages - there may be others!

**Comment by npracht** [comment]
@RCheesley the problem was there before, check the code change, it was saying "if company ID is in columns, then add the edit view". It means that the 404 you list are already existing before.

**So this PR brings:**
1. The `view` link on the company ID that was not introduced when the company `view` page has been going live
2. Remove this dirty condition in code that was converting all links on ID in reports if the company ID was in the table (so if a company ID was displayed, the contact ID was switched to `edit`).

⚠️ Introducing a list of entity with `edit` or `view` in code would make it dangerous and we'd have to maintain it in the future for every new feature with an ID and available in report ?

**Review by escopecz — APPROVED** [review]
The removed condition was there previously because because the company view page did not exist. But it was added in https://github.com/mautic/mautic/pull/8936 so this change can be safely made.

The change touches only company, no other entity.

**Comment by RCheesley** [comment]
> @RCheesley the problem was there before, check the code change, it was saying "if company ID is in columns, then add the edit view". It means that the 404 you list are already existing before.

OK I will raise a separate issue for that if it is not already created!

 This one is GTG! Thanks @julienWebmecanik 🚀

**Review by RCheesley — APPROVED** [review]

**Pull request merged**
