### PR TITLE
Add missing translation string

### LINKED ISSUE #8492: Missing language string for default text mautic.lead.field.timezone
###  Bug Description
When creating a new contact there is a missing translation string which is showing as mautic.lead.field.timezone instead of whatever default text should be showing before the user enters the information

| Q   | A
| --- | ---
| Mautic version | 3.0 beta
| PHP version | 7.2.24
| Browser | Chrome

### Steps to reproduce
1. Create or edit a contact
2. Notice the language string instead of a regular piece of text as the default text for the Preferred Timezone field

### PR DESCRIPTION
**Pull request by RCheesley**
This should close #8492 and affects both m2 & m3.

| Q  | A
| --- | ---
| Bug fix? | x
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | resolves #8492 
| BC breaks? | 
| Deprecations? | 

#### Description:
Fixes small language string missing issue which has been bugging me for ages! I think this is the place it's missing, as it's in the lead bundle, but not in this bundle - whereas the preferred locale string is, which works fine.  It seems it's not getting added to the _lead_fields table due to being missing from this file.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Edit a contact and notice the missing language string which is rendered as mautic.lead.field.timezone in the default text

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com/8588)
2. Edit a contact and check to see if the correct language string is rendered

### CODE REVIEW

**Comment by RCheesley** [comment]
[Contact > Ensure all language strings are being correctly rendered for core fields and social fields (including default text and labels)](https://trello.com/c/KAsrI8x6/39-contact-ensure-all-language-strings-are-being-correctly-rendered-for-core-fields-and-social-fields-including-default-text-and-la)

**Comment by npracht** [comment]
Hi there!
It has been decided to do not create any extra Mautic 2 version (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Review by dennisameling — APPROVED** [review]
Looks good, thanks @RCheesley 👍

**Comment by RCheesley** [comment]
Does this one need to be rebased?

**Comment by dennisameling** [comment]
@RCheesley nope, just needs a 2nd review and then good to go for M3 👍

**Review by npracht — APPROVED** [review]
:+1:

**Pull request merged**
