### PR TITLE
Convert entities away from annotations

### PR DESCRIPTION
**Pull request by alanhartless**
Using annotations is great for quickly defining the database schema and API serializer properties. The problem is that Symfony created a single serialized cache file for every property and method in the entity files (800+ files) which caused some issues on shared hosts. By converting doctrine and JMS serializer metadata (used for the API) annotations to php static functions, those cache files are no longer generated and thus should optimize the cache on shared hosts.

To test: 

1) **Make a backup of your database as the changes in step 3 are irreversible**
2) After updating the source, delete app/cache/prod
3) Run `php app/console doctrine:migrations:migrate` to apply the intentional schema changes found while making the conversion
4) Test everything. If there are places where the doctrine annotation was not converted correctly in the static php function, there may be discrepancies in how Doctrine interacts with the database. Changing all the entity files has the potential of affecting everything in Mautic that interacts with the database. 

Preferably test in dev mode so you will catch the sql errors if any. A successful test will be no sql errors.

### CODE REVIEW

**Comment by drmmr763** [comment]
I got this error when running the database script:

```
Migration 20150330000000 failed during Execution. Error An exception occurred while executing 'ALTER TABLE email_donotemail CHANGE date_added date_added DATETIME NOT NULL':

SQLSTATE[22004]: Null value not allowed: 1138 Invalid use of NULL value
                                                                                                              
  [Doctrine\DBAL\DBALException]                                                                                         
  An exception occurred while executing 'ALTER TABLE email_donotemail CHANGE date_added date_added DATETIME NOT NULL':  
  SQLSTATE[22004]: Null value not allowed: 1138 Invalid use of NULL value                                               
                                                                           
  [PDOException]                                                           
  SQLSTATE[22004]: Null value not allowed: 1138 Invalid use of NULL value
```

**Comment by alanhartless** [comment]
Chad,

In your email_donotemail table, do you have rows where date_added is null?  If so, were they added by Mautic or some manual process (I know you've been doing some tests so just wanted to verify :-) ).

Thanks,
Alan

**Comment by drmmr763** [comment]
Huh. Yeah I do, but I have no idea how it got there. I'll remove it and try again!

**Comment by drmmr763** [comment]
After removing that migration worked fine. 

Tested:
1) login / logout works
2) manually add lead works
3) create list works
4) manual assign lead to list works
5) created campaign and assigned a download action to it - works
6) Created new email and sent successfully (note: didn't send to a real email so not sure about receipt, but showed up in Mandrill as sent)
7) Added new form with custom fields, submitted with no issue
8) Added landing page with form and asset. Form executes and asset downloads. 
9) Asset uploads successfully

I didn't run into any problems doing these things. If there's another specific function you think needs some more in depth testing let me know and I'll run it through the paces. Otherwise this looks good!

**Comment by alanhartless** [comment]
Please do not merge this till after 1.0.2 is released and the schema changes from 1.0.2 has been added to the PR :-)

**Comment by dbhurley** [comment]
Yah for removing way too many cache files! :+1:

**Comment by escopecz** [comment]
I'm having these errors on doctrine:schema:update command:

```
 [Doctrine\DBAL\DBALException]                                                
  An exception occurred while executing 'ALTER TABLE mau_oauth1_consumers ADD  
   consumer_key VARCHAR(255) NOT NULL':                                        
  SQLSTATE[23502]: Not null violation: 7 ERROR:  column "consumer_key" contai  
  ns null values                                                               

  [PDOException]                                                               
  SQLSTATE[23502]: Not null violation: 7 ERROR:  column "consumer_key" contai  
  ns null values                                                               
```

**Comment by escopecz** [comment]
Even though I had troubles with DB schema update, it was caused by not reading Alan's instructions. With the fresh Mautic Install, I had no problems with migrations when following instructions. I was able to create/view all entities from the administration without any error.

But if I delete the App/Config/local.php and try to install Mautic with this PR checkout, I get this error while saving DB settings:
```
No metadata was found to create the database.
```
(postgres DB used for testing)

**Comment by escopecz** [comment]
Tested installation with Postgres database without any problem. Random creation of items works fine. Emails get send. I didn't find any problem :+1:

**Pull request merged**
