### PR TITLE
Added report column: Date added to company

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR added new column in reports. Along  with company fields added **Date added to company** column

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create contacts report with Company Name and Date added to company column
3. Assign companie sto few contacts 
4. Check report If works properly

### CODE REVIEW

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebased

**Review by RCheesley — APPROVED** [review]
Report works as described, picked up a bug with sample data which I've raised as #9090

**Review by dennisameling — APPROVED** [review]
LGTM 👍 thanks @kuzmany!

**Comment by dennisameling** [comment]
Might be nice to have in the docs - cc @mautic/education-team

**Pull request merged**
