### PR TITLE
Fix Uncaught ReferenceError: mauticEnv is not defined from dashaboard.js

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
During the work on this https://github.com/mautic/mautic/pull/9651 I've noticed another minor issue coming from https://github.com/mautic/mautic/pull/9386 
This PR fixed it

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Open builder in dev enviroment
3. Put text slot to builder area
4. Open the browser console and see error 

> Uncaught ReferenceError: mauticEnv is not defined

This PR fixed it.

### CODE REVIEW

**Review by hluchas — APPROVED** [review]
Code looks good and I know what exactly it is.
Approving for now. I 'll test it later today.
TY!

**Review by escopecz — APPROVED** [review]

**Comment by WaldemarOrobanche** [comment]
Please regenerate assets because the changes wasn't applied to `app.js` file.

**Comment by RCheesley** [comment]
@all-contributors please add @hluchas for review

**Comment by RCheesley** [comment]
Updated the milestone as this was merged into Features, hence Mautic 4.

**Pull request merged**
