### PR TITLE
Fix DNC Action on Form Submission

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [X]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a contact and market it as DNC
3. Create a form with email field, and create an action to remove DNC
4. Contact should get the DNC removed (without this PR it will not be removed)

### CODE REVIEW

**Comment by kuzmany** [comment]
Seems this PR https://github.com/mautic/mautic/pull/12043 . Make more issues like we thought . See my comments https://github.com/mautic/mautic/pull/12043#issuecomment-1503163661

probably we should revert it and  find different way how to fix it

**Comment by escopecz** [comment]
@mabumusa1 do you think you could add this form action to some existing test, for example https://github.com/mautic/mautic/blob/5.x/app/bundles/FormBundle/Tests/Controller/SubmissionFunctionalTest.php and assert that it works as expected?

**Comment by mabumusa1** [comment]
> @mabumusa1 do you think you could add this form action to some existing test, for example https://github.com/mautic/mautic/blob/5.x/app/bundles/FormBundle/Tests/Controller/SubmissionFunctionalTest.php and assert that it works as expected?

I will add automated tests to this PR, I think the functionality is broken in the first place, here is an actual case we faced

- Create a form with an email field, and make the name of that fields something different than `email`
- DNC action will not work because it checks for the field `email`
- The code of this function work on Email DNC only and neglects other channels, so maybe this function needs restructuring

**Comment by kuzmany** [comment]
Close favor to https://github.com/mautic/mautic/pull/12272

**Pull request closed without merging**
