### PR TITLE
Adding back social monitoring command

### LINKED ISSUE #11975: mautic:social:monitoring command missing in 5.x branch
When trying to use the `mautic:social:monitoring` command on the 5.x branch it is unknown, but on the 4.4 branch it works fine.

To test:

1. Install Mautic on the 5.x branch (or use Gitpod)
2. When install is completed, run the command `ddev exec bin/console list `

This will get you a list of the available commands - notice that the `mautic:social:monitoring` command is missing from the list.

3. Run the same command by going to https://github.com/mautic/mautic under the code tab > change branch to 4.4 and then click the Gitpod link (assuming you use the Chrome extension) - do the same and notice that the command is present in the list.

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [y]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [y] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/issues/11975

#### Description:

If your try to run the social monitoring command then Mautic response that it does not exist:
```
bin/console mautic:social:monitoring

                                                                   
  There are no commands defined in the "mautic:social" namespace.
...
```
The reason was that those commands were forgotten to be hard-wired when the auto-wiring was introduced and therefore were not auto-configured as commands.

I found 2 other places where this happened and removed the hard-wiring so the auto-configuration could kick in.

All affected commands are tested by functional tests now.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Run `bin/console mautic:social:monitoring` command and it will respond. Please also be sure to check all impacted commands: 

mautic:custom-field:create-column
mautic:import
mautic:reports:scheduler
social:monitor:twitter:hashtags
social:monitor:twitter:mentions
mautic:social:monitoring

### CODE REVIEW

**Review by RCheesley — COMMENTED** [review]
Thanks for getting to this so quickly! Confirming that the social monitoring commands are back 🎉 .

What other commands should we be checking other than the social monitoring? Is it custom field creation and report scheduling?

Also, a failing test to address.

**Comment by escopecz** [comment]
@RCheesley thanks for testing! These commands were "touched" by this code change:
- mautic:custom-field:create-column
- mautic:import
- mautic:reports:scheduler
- social:monitor:twitter:hashtags
- social:monitor:twitter:mentions
- mautic:social:monitoring

**Review by RCheesley — APPROVED** [review]
Thanks for the detail! Commands present and working as expected 🚀

**Comment by adiux** [comment]
I can also confirm it works. I received:
`No published monitors found. Make sure the id you supplied is published`

**Comment by RCheesley** [comment]
Thanks for testing @adiux 🚀

**Comment by sdoering** [comment]
All listed commands are there and working as expected. 

As Twitter is not published the twitter commands throw an exception/error (as I would expect):

image

**Comment by RCheesley** [comment]
Awesome - good to go, thanks @sdoering for testing!

**Pull request merged**
