### PR TITLE
Fix DO NOT CONTACT Subscriber not listening to events

### LINKED ISSUE #9027: Unable to import contacts with DoNotContact set to TRUE
## Bug Description
Creating a simple CSV with two columns, email and donotContact.  Select the csv file, map email to email, map donotContact to Properties Do Not contact.  Import correctly imports the contacts, but the imported rows are not marked for do not contact.

| Q   | A
| --- | ---
| Mautic version | 3.0.1
| PHP version |  7.2.32
| Browser | Chrome

### Steps to reproduce
1. Create .csv with two columns, email and donotContact
2. Enter email addresses.  Set donoContact to "TRUE" "yes" or "1"
3. Run the import process.
4. View imported contacts, not that they are not marked as do not Contact
 
### Log errors
None.

### Theory
I see that donotContact information is stored in a different table (`lead_donotcontact`).  Now with a reason code, do not contact type, etc.  I'm not sure if this import process is legacy from 2.x where that flag was on the `lead` table and now it's a separate table?  Seems like there needs to be a mapping or a process job to mark these contacts as donotcontact?

Any other work arounds other than manually setting these?

### LINKED ISSUE #9175: Do Not Contact is broken in Mautic 3.1
## Bug Description
Do Not Contact no longer works as expected in 3.1, as there are multiple ways in which trying to set Do Not Contact does so with reason=0 (the corresponding row in the `lead_donotcontact` table in the DB gets a `0` in the `reason` column) thus actually rendering the contact 'Contactable' despite attempting to do the opposite.

I've found three ways in which this can happen:

- ~~Way 1: Calling the API endpoint for adding contact DNC to channel - `POST /contacts/<id>/dnc/email/add` - without a body (or with a body consisting of `{ "reason": 0 }`) causes the contact to get their DNC for the channel set to "Contactable", thus erroneously returning a response of 200 while actually not adding the contact to DNC, but merely adding a dummy row with reason=0 to the `lead_donotcontact` table. This can even be spammed to create an enormous amount of dummy rows (#9076) 
Furthermore, this runs counter to https://developer.mautic.org/#add-do-not-contact which for `reason` states that "Default is Manual", which is not currently the case. The documentation is right, the code is wrong: Default reason should be `3`, not `0`.
I'd argue that in addition to changing the default reason from `0` ==> `3`, trying to add a DNC with `{ "reason": 0 }` should cause an error, as it is misleading to return a 200 OK response from an endpoint that explicitly exists to **add** DNC if that does not actually happen.~~ (moved to a separate bug report: #9076 )

- Way 2: Setting up Monitored Inbox for automatic unsubscribe-emails also results in them being set reason=0 with the 1 accidentally being set in the comments column instead of the reason column.

- Way 3: Going to the contacts list view - `s/contacts` - and checking one or more contacts and then selecting 'Set Do Not Contact' and inputting whatever reason you want also accidentally gives them reason=0 and puts the 3 that's supposed to indicate 'Manual' as part of the `comments` column. 

This is likely due to an errant comma somewhere in the code which pushes the reason integer to the comment column in the DB instead of the reason column.

---
| Q   | A
| --- | ---
| Mautic version | 3.1
| PHP version | 7.3

### PR DESCRIPTION
**Pull request by jacobshilitz**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.x 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             |no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL |  
| Issue(s) addressed                     | Fixes #9027 and maybe #9175  

#### Steps to test this PR:
1. Create .csv with two columns, email and donotContact
2. Enter email addresses. Set donotContact to "TRUE" "yes" or "1"
3. Run the import process.
4. View imported contacts, not that they are not marked as do not Contact

Test remove via a checkbox
1. Select one or more contacts, 
2. Select the dropdown from the top
3. Select "Set Do Not Contact" and enter reason
4. Contact should be marked and reason displayed

### CODE REVIEW

**Comment by npracht** [comment]
Hi @jacobshilitz ! Thanks a lot for your contribution.
Could you please just tell us how to reproduce the issue and how to test your PR and confirm the issue is away ?

Thanks again.

**Comment by StoppingBuck** [comment]
@jacobshilitz Thank you for this PR! I see you've fixed one of the wrongly formatted `addDncForContact()` (which render the contact still Contactable). Would it be possible for you to do the same for the lines mentioned [here](https://github.com/mautic/mautic/issues/9175#issuecomment-689447518) and [here](https://github.com/mautic/mautic/issues/9175#issuecomment-689454263) as well? The only change needed is making sure that the $reason parameter is provided as the **third** parameter in all calls to `addDncForContact()`. That would likely fix the DNC bugs in Monitored Inbox and perhaps the API as well :slightly_smiling_face:

**Comment by jacobshilitz** [comment]
@StoppingBuck Yes, I'm still checking where it's being used. the main fix was the broken listener.

I still not understand why we have 2 listeners `CampaignActionDNCSubscriber` and `DoNotContactSubscriber` 

@npracht how to test is in #9027 - Updated in the description

**Comment by jacobshilitz** [comment]
i see now `addDncForContact` method and the `DoNotContactAddEvent` constructer take the parmaters in a diffrant order.  

we need to decide what order we want to keep. 

(I'm sorry if I miss something because I'm really new here)

**Comment by StoppingBuck** [comment]
@jacobshilitz Just to re-iterate:

Currently, `addDncForContact()` expects the **third** parameter to be the reason (the integer 1, 2 or 3) and the **fourth** (optional) parameter to be the comments (can be whatever).

As I mentioned in my linked comments there are a handful of lines in the code where `addDncForContact` is accidentally called with the comment as third parameter and reason as fourth parameter. I think it makes the most sense to change the calls to the function rather than mess with the function itself. 

Thus, in order to fix that, those lines need to be changed to pass the reason as **third** parameter and comment as **fourth** parameter. 

These are the lines in question:
* https://github.com/mautic/mautic/blob/8cb3c509a09224fe9c71abe84faebdb69c11c934/app/bundles/EmailBundle/MonitoredEmail/Processor/FeedbackLoop.php#L96
* https://github.com/mautic/mautic/blob/8cb3c509a09224fe9c71abe84faebdb69c11c934/app/bundles/SmsBundle/Helper/SmsHelper.php#L108
* https://github.com/mautic/mautic/blob/8cb3c509a09224fe9c71abe84faebdb69c11c934/app/bundles/EmailBundle/MonitoredEmail/Processor/Unsubscribe.php#L119
* https://github.com/mautic/mautic/blob/8cb3c509a09224fe9c71abe84faebdb69c11c934/app/bundles/EmailBundle/MonitoredEmail/Processor/Bounce.php#L144 (this one doesn't even pass a reason, causing the comments to be passed as the reason by accident)
* https://github.com/mautic/mautic/blob/8cb3c509a09224fe9c71abe84faebdb69c11c934/app/bundles/LeadBundle/Controller/AjaxController.php#L357
* https://github.com/mautic/mautic/blob/d2018fb96beeec25eae200caa286444e12608ba8/app/bundles/EmailBundle/Model/EmailModel.php#L1763
* https://github.com/mautic/mautic/blob/5ca3b842fcc57dc5c73b5b06a37fcb1dc19ef551/app/bundles/LeadBundle/Controller/LeadController.php#L1643
* https://github.com/mautic/mautic/blob/25c203b54527d3636c5cad917d178e32a02bd4d6/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php#L2717

Alternatively, I could fix the above in a separate PR, but since you started this one I think it makes the most sense to include the changes in this one :slightly_smiling_face:

**Comment by jacobshilitz** [comment]
@StoppingBuck sorry, I will fix all occurrences. basically I fixed it for myself, but I wanted to give back to the community 
> * https://github.com/mautic/mautic/blob/8cb3c509a09224fe9c71abe84faebdb69c11c934/app/bundles/EmailBundle/MonitoredEmail/Processor/Bounce.php#L144
>    (this one doesn't even pass a reason, causing the comments to be passed as the reason by accident)

`reason` has a default in `addDncForContact()` to `DNC::BOUNCED`.

should I add it as param?

**Comment by StoppingBuck** [comment]
> > * https://github.com/mautic/mautic/blob/8cb3c509a09224fe9c71abe84faebdb69c11c934/app/bundles/EmailBundle/MonitoredEmail/Processor/Bounce.php#L144
> >   
> >   (this one doesn't even pass a reason, causing the comments to be passed as the reason by accident)
> 
> `reason` has a default in `addDncForContact()` to `DNC::BOUNCED`.
> 
> should I add it as param?

Yes, that seems like the best solution. :+1:

**Comment by StoppingBuck** [comment]
And I'm happy to hear you want to give back to the community. This is how we make Mautic stronger together :muscle: :smile:

**Review by StoppingBuck — DISMISSED** [review]
Everything looks good to me :+1:

**Comment by StoppingBuck** [comment]
Using https://mautibox.com/9186 I can confirm that at least selecting someone in the Contact list and marking them DNC actually sets them properly as DNC now (that is broken in 3.1).

I don't know how to test the Bounces/Unsubscribes from Monitored Inbox as I don't know how to set up Monitored Inbox on Mautibox, but the change is fairly transparent and looks good to me.

As for the API part I currently have trouble figuring out how to test it on Mautibox, but looking at the above I actually don't think this PR solves that problem (that is, the problem of 'calling the API without a reason defaults to reason=0 instead of reason=3'), but I think this PR is starting to grow to cover a bunch of different things so maybe that should be dealt with in a separate PR.

**Comment by jacobshilitz** [comment]
@StoppingBuck my branch was not based on staging I rebased now,

**Comment by mabumusa1** [comment]
@jacobshilitz @StoppingBuck I hope we can get this PR merged in the next release by the end of the month, how can I help you get this PR tested and ready for merging?

**Comment by StoppingBuck** [comment]
@mabumusa1 This PR covers a bunch of different things, but as to the regressions in #9175 I'll quote the description:

> I've found three ways in which this can happen:
> 
> * Way 1: Calling the API endpoint for adding contact DNC to channel - `POST /contacts/<id>/dnc/email/add` - without a body (or with a body consisting of `{ "reason": 0 }`) causes the contact to get their DNC for the channel set to "Contactable", thus erroneously returning a response of 200 while actually not adding the contact to DNC, but merely adding a dummy row with reason=0 to the `lead_donotcontact` table. This can even be spammed to create an enormous amount of dummy rows (#9076)
>   Furthermore, this runs counter to https://developer.mautic.org/#add-do-not-contact which for `reason` states that "Default is Manual", which is not currently the case. The documentation is right, the code is wrong: Default reason should be `3`, not `0`.
>   I'd argue that in addition to changing the default reason from `0` ==> `3`, trying to add a DNC with `{ "reason": 0 }` should cause an error, as it is misleading to return a 200 OK response from an endpoint that explicitly exists to **add** DNC if that does not actually happen.
> * Way 2: Setting up Monitored Inbox for automatic unsubscribe-emails also results in them being set reason=0 with the 1 accidentally being set in the comments column instead of the reason column.
> * Way 3: Going to the contacts list view - `s/contacts` - and checking one or more contacts and then selecting 'Set Do Not Contact' and inputting whatever reason you want also accidentally gives them reason=0 and puts the 3 that's supposed to indicate 'Manual' as part of the `comments` column.

Ideally we should test if all three of these are fixed. I tested Way 3 on Mautibox and it seems to have been fixed, but I'm not sure how to properly test Way 1 (API). As for Way 2, I didn't directly test the PR, but I made the same code changes on my Mautic installation and it fixed the Monitoring Inbox issue for me, so I guess that could count as a test :+1: 

I didn't test anything after the rebase, but I highly doubt anything actually changed(?)

**Comment by mabumusa1** [comment]
@StoppingBuck do you think it would be better to have three separate PRs to test each case? since you already fixed Way 3, let's get that tested and merged then we look into the API (way-1), then (way-3)

**Comment by StoppingBuck** [comment]
@mabumusa1 I don't have a lot of Git experience, and have no idea how to split a PR or only merge part of a PR. Maybe just keep it in one PR, since the cases are very different from each other.

**Comment by mabumusa1** [comment]
@StoppingBuck I can help you get familiar with git, you can start with this guide 
https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests

You will get the same base as we have in the `staging` branch, they you apply your code, push to your forked repo, and start a PR, if you want do it for `way-1`. we can do it bite-sized solution

**Review by kuzmany — APPROVED** [review]
Looks good and looks like fix a lot of issues with probably wrong DNC 👍

**Comment by RCheesley** [comment]
Came across https://github.com/mautic/mautic/pull/9106 which also mentions the DNC not being updated - may also be related/relevant.

**Comment by RCheesley** [comment]
Hi folks,

Please can we add all the tests that folk need to check in order to approve this PR to the description? That way we can be sure that we're being rigorous in our testing.  I noticed that a few more cases have been added to the PR since it was created so we need to make sure that we're testing all of them before we merge.

**Comment by RCheesley** [comment]
Another PR that might be related by @ramandi :
https://github.com/mautic/mautic/pull/9081

Note that this suggests also modifying [line 466](https://github.com/mautic/mautic/pull/9081/files#diff-effadf31fa0a0906daae388dc7dc4999L466) which doesn't seem to be catered for in this PR.

**Comment by StoppingBuck** [comment]
@RCheesley This one is growing into being a bit of a mess (the coordination, not the code). Here's what I know:

AFAIK #9076 is not currently addressed by this PR. I've edited that bug report's title and description to reflect this. It will have to be addressed by a separate PR.

As for the issues in #9175 I've also edited its title and description to better reflect what it's about. It references two different situations that I believe this PR fixes:

- Test I: 
1. Set up [Monitored Inbox](https://docs.mautic.org/en/channels/emails/bounce-management)
2. Send an email from a Contact to the inbox in question
3. Run the `mautic:email:fetch` cronjob
4. The Contact belonging to the email address which sent the email should now be DNC with the reason 1 ("Unsubscribed"). (before the PR, reason would be 0 ("Contactable"))

- Test II:
1. Go to the contacts list view - s/contacts - and check the boxes next to one or more contacts
2. Select 'Set Do Not Contact' from the drop-down menu
3. Input whatever comment in the reason box you want
4. The Contacts should now be DNC with the reason 3 ("Manual") (before the PR, reason would be 0 ("Contactable"))

Keep in mind that none of these two cases have anything to do with the issue that @jacobshilitz originally created this PR to fix, so whatever that was should also be tested.

I'm sorry that we ended up mixing a lot of different things together like this 😞

**Comment by RCheesley** [comment]
@StoppingBuck thanks for the clarification - indeed it would have perhaps been better to separate them out into individual PR's as @mabumusa1 suggested - hindsight eh! 👀 

Do we think we need to add the extra line I mentioned [here](https://github.com/mautic/mautic/pull/9186#issuecomment-695200596)?

Given the complexity of this area, I would favour moving this PR back a few weeks to 3.1.2 (release freeze 18th October) to give us more time to fully dig into what's going on as I am not confident that we have covered all bases or will be able to confidently do that by tomorrow evening.

We need to make sure that we cover all the places where DNC may not be working properly - given the importance to this feature in the marketing process (GDPR and all the other associated legislations) I feel we owe it to our users to fully fix and test this, rather than rush out a partial fix.

**Comment by StoppingBuck** [comment]
@RCheesley If it's going to be delayed then sure, it makes sense to include that extra line 👍 

I feel like a bit of the confusion is about whohas done / is going to do what. I found the (likely) causes of the issues I described in #9175 , @jacobshilitz included my proposed fixes in this PR, and now there's a bit of confusion who is going to do / has done tests of the PR as well as what issues the PR actually claims to fix.

As for me, I've made the changes I referenced in [my comment above](https://github.com/mautic/mautic/pull/9186#issuecomment-691114042) to our production Mautic and that fixed the issues described in #9175 . However, I haven't - strictly speaking - tested this PR *itself* (as I couldn't wait that long), and so, the issue is 'what counts as test and what does not?'

Speaking for myself and my company, I'm fine with pushing this to 3.1.2 as I've already fixed things on my end, but it's a pretty serious regression so I feel for the people out there who may not have the capacity to edit the code themselves...

**Comment by RCheesley** [comment]
Some really good points there @StoppingBuck - I think it's worth discussing with @jacobshilitz and the 3.1.1 release lead @mabumusa1 what route we should take forward as to whether we include it now, or wait for the next release.  Given we know about that extra line I'd like someone to take a look about whether it should be included - no point fixing it in one place and not in another further down the file.

If it's something we can get tested (and by tested I mean, testing all the cases that this PR fixes) before the end of Sunday then we could potentially get it out in the 3.1.1 release.

It's a bit late now time wise so we may need to roll this over to tomorrow.

**Comment by dennisameling** [comment]
Hi! To keep things central regarding issues around Do Not Contact (DNC), I created a JIRA issue to track all issues related to DNC in a single place. That way, we can more efficiently fix the several bugs that were reported. Please check it out: https://mautic.atlassian.net/browse/TPROD-72

**Comment by dennisameling** [comment]
Just leaving this here for visibility: when this PR has automated tests and is merged, we can work on https://github.com/mautic/mautic/pull/9227 which will prevent many of such cases from happening in the future, as it strictly checks whether the right types are provided (int, string, etc.)

**Review by dennisameling — APPROVED** [review]
Looking at the code, this makes perfect sense. Not all cases are covered by automated tests, so if someone wants to make 100% sure that this works as expected, here are some things to test:

- Set up bounce integration and test if a contact bounces correctly
- Set up Monitored Email, make sure an email bounces (e.g. spam report). The contact should now be marked as DNC/bounced
- Set up Monitored Email, make sure someone emails to the unsubscribe email address. The contact should now be marked as DNC/bounced
- Manually set a user to DNC in Mautic's interface
- Set up SMS integration and test if unsubscribing works, the contact should be marked as DNC/manual.

**Comment by mabumusa1** [comment]
It would be better to add this PR to the next release to get automated testing for it and more reviews

**Comment by RCheesley** [comment]
Hi folks,

We have decided to push this PR back to 3.1.2 as we did not have sufficient time to test fully and there are areas not covered by tests as mentioned above.

We will link to the PR in the release notes and explain that this PR can be tested if folk are experiencing this issue.

**Comment by jacobshilitz** [comment]
> Came across #9106 which also mentions the DNC not being updated - may also be related/relevant.
@RCheesley It seems to be a complete other problem. maybe we keep that PR too?

**Comment by jacobshilitz** [comment]
I guess it was sort of my mistake to fixes everywhere the reason was misplaced. the main fix here was the listener. without fixing the listener there will not be a DNC event that will work

should I remove the other commits, and just leave my first [commit](https://github.com/mautic/mautic/pull/9186/commits/953cc964a371c4b25187414c5365e45414d76375)?

**Comment by StoppingBuck** [comment]
> I guess it was sort of my mistake to fixes everywhere the reason was misplaced. 

If anyone is to blame here, it's me. I'm pretty new to the whole Git thing and just figured 'Hey, why don't we just put all the DNC related fixes in one PR to save time?'

Needless to say, I won't do that again. I apologize for the mess.

**Comment by kuzmany** [comment]
Two core developers approve this, then not exist reason to postpone to next release. Please, let's focus to cover unit test for new code/services, not for every bot crying. 
We are doing it in free time.

**Comment by RCheesley** [comment]
@kuzmany we have already missed the release freeze, so it is to be considered for 3.1.2.

We are not merging any PR's that decrease coverage, project wide. This is a general policy, and while we appreciate it adds inconvenience for developers having to write more tests, the aim is to move toward a more stable product.

In this case, the reference to more tests being needed was **not** about the automated test coverage or about 'bots crying' - this PR is actually passing on that.

One of the core team's review [explicitly points out](https://github.com/mautic/mautic/pull/9186#pullrequestreview-492536716) that there is not full test coverage in some areas, and that to be absolutely certain this does what it says, there are some areas that should be double-checked. 

We now have several weeks in order to test those things, which we can do with the PR's that we've merged in 3.1.1 relating to other aspects of the DNC functionality applied.

**Comment by jacobshilitz** [comment]
> If anyone is to blame here, it's me. I'm pretty new to the whole Git thing and just figured 'Hey, why don't we just put all the DNC related fixes in one PR to save time?'
> 
> Needless to say, I won't do that again. I apologize for the mess.

I'm sorry I'm new here as well. it's all good. (you really helped me)
I was just pointing out that it's an important fix to something broken. in that case its not something that can make anything worse. I understand that things need tests. but this should have done before v3. it's already nonstable for such an important core feature that is now fully broken. (my fix cant makes it worse.) not that I care whether it's implemented now or never. 

now I will just write here a few bugs that I still see in DNC:
1. when adding a new contact with DNC it does not work, because we cant add DNC to a contact that is not created yet, I guess need to do it later or create the lead in DB before (CORE devs please help!)
2. when trying to remove a DNC via the orange button in the contact page it returns 500

**Comment by dennisameling** [comment]
@jacobshilitz there is a function called `createDncRecord` which can create a DNC record even without an existing contact. It works like this:
- The function sets a `dnc_channel_status` key on the contact object
- Contact is created
- [`onLeadPostSave`](https://github.com/mautic/mautic/blob/3.1/app/bundles/IntegrationsBundle/EventListener/LeadSubscriber.php#L80) is triggered which checks if `dnc_channel_status` exists; if yes, it will create a DNC record to the contact that was just created. 

I used `createDncRecord` in https://github.com/mautic/mautic/pull/9226/files, so at least that fixes the scenario where a contact is created through the API together with DNC information. This was working in 2.16 but broke in 3.0 due to a major refactoring of the DNC internals.

Hope this helps, if I can be of any further help with this, let me know 👍

**Comment by jacobshilitz** [comment]
@dennisameling in your PR you use the DNC model directly, [in the import code](https://github.com/mautic/mautic/blob/267795ded684121cd856973d3fa41aee07500dce/app/bundles/LeadBundle/Model/LeadModel.php#L1436), we use the `DoNotContactAddEvent()` event. (the event that was meant to be fixed with this PR) 
should we change it to access the entity directly instead of using the event? 

I think that now we use a few different approaches and its a bit confusing. do I miss something?

**Comment by kuzmany** [comment]
@jacobshilitz This PR fixed error while remove bounce flag from contact detail (review it please) https://github.com/mautic/mautic/pull/9261

**Comment by kuzmany** [comment]
@jacobshilitz 
> when adding a new contact with DNC it does not work, because we cant add DNC to a contact that is not created yet, I guess need to do it later or create the lead in DB before (CORE devs please help!)

Can you tell me more when this happend? How you add contact? By import/web/API? I am able to try look on it.

**Comment by jacobshilitz** [comment]
@kuzmany 
> Can you tell me more when this happend? How you add contact? By import/web/API? I am able to try look on it.

when you import from csv
Step 1. make a CSV with a new email you don't have in the system
```
email,doNotEmail
new_user@sample.com,true
```
Step 2. import 
no DNC will be added

**Pull request merged**
