### PR TITLE
issue-9545-forms-not-prefilling-fixed-regex

### LINKED ISSUE #9545: Landing page doesn't autofill form with querystring parameters
## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.2.2
| PHP version | 7.2.34

### Steps to reproduce
1. Create form with fields email_address, first_name, last_name

image

2. Create landing page with form embedded

3. Create e-mail with link to landing page
`{pagelink=2}?email_address={contactfield=email}&first_name={contactfield=firstname}&last_name={contactfield=lastname}`

    3a. Attempts to use the URL Encode filter (i.e. `{contactfield=email|true}`) seems to break things as the pipe character is encoded by the page builder.

image

4. Send e-mail, click link.

5. Form does not autofill with query string parameters.

    5a. Assuming maybe URL Encoding with the e-mail address (due to the `@` character) may be an issue, removing that and just going with `?first_name=Shaun&last_name=McPeck` still fails to populate (and hide) the fields for which values were provided.
 
I know the page/email builder is being revamped for a future release, so I know there's not a lot of work being done on that existing code base, but a quick hack that might fix this would be great!  (Also, maybe I'm just missing something and/or doing something wrong so there's a better "do it the right way" fix. 🤣)

Any guidance would be a great help. Cheers!

An old thread that I found didn't seem to have anything helpful for me: https://forum.mautic.org/t/how-to-pass-url-parameters-to-a-form/15315/13

### PR DESCRIPTION
**Pull request by saitanay**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.2
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | https://docs.mautic.org/en/components/forms/managing-forms
| Related developer documentation PR URL | Documentation update not required
| Issue(s) addressed                     | Fixes #9545

#### Description:
The source of this issue seems to be the regex written in `app/bundles/FormBundle/Helper/FormFieldHelper.php`

`if (preg_match('/<input(.*?)id="mauticform_input_'.$formName.'_'.$alias.'"(.*?)value="(.*?)"(.*?)\/>/i', $formHtml, $match)) {`

This tries to match the HTML which is
`<input id="mauticform_input_mauticissues9545_first_name" name="mauticform[first_name]" value="" class="mauticform-input" type="text" />\n`

This seems to have worked in the past, although some regression seems to have caused changed over time to the form HTML markup that has caused the regex to break. 
The current regex works only if
* id is the first param in the input tage
* **value** attribute in the html of the input element comes right after the **id** attribute
* The input tag has a "/" before the closing ">"

**This is failing now because the form markup generated inserts a name attribute between the id and value attributes of the input field markup. Further the "/" before the closing ">" is gone now. ** 

This will likely affect other types of fields than just text as well. 

Fixing the regex accordingly. I have tested the updated regex for Text Field only. This might need further changes to other field types. 

#### Steps to test this PR:
1. Create a form, add fields and save the form. 
2. Open the form url and try to pass values for fields as per https://docs.mautic.org/en/components/forms/managing-forms and check if the values are populating in the form . 
Example: if form url is http://localhost/mauticissues9545-landing-page and if it has a email_address field, try to open http://localhost/mauticissues9545-landing-page?email_address=saitanay@example.com and check if email address is prepopulated

### CODE REVIEW

**Comment by kuzmany** [comment]
This is duplicate of https://github.com/mautic/mautic/pull/9239 what this issue resolve in more complex way

**Review by escopecz — CHANGES_REQUESTED** [review]
@saitanay could you please add a test for this in https://github.com/mautic/mautic/blob/features/app/bundles/FormBundle/Tests/Helper/FormFieldHelperTest.php?

**Comment by escopecz** [comment]
Now reading @kuzmany's comment. He's right. @saitanay are you OK to close this as a duplicate?

**Comment by saitanay** [comment]
@kuzmany @escopecz 

Sorry - i had not noted the other existing PR. 

There are 2 issues here - 
- #1 the current form markup generated inserts a **name attribute between the id and value attributes** of the input field markup. While the existing code **expects value attribute in the html of the input element  right after the id attribute**
- #2 The "/" closing tag 

I believe https://github.com/mautic/mautic/pull/9239 addresses only #2. I don't think https://github.com/mautic/mautic/pull/9239 addresses #1.

I could be wrong but AFAICU, 9239 won't fix the pre-population of forms.

**Comment by kuzmany** [comment]
@escopecz decide what PR will close. But need unit tests cover all that situations

**Comment by pety-dc** [comment]
The `(.*?)` in the regex between id and value should catch anything between the two attributes. I don't see how the name attribute inbetween would introduce a problem.
https://regex101.com/r/SWUCIE/1/

Nevertheless making these asterisks greedy (`(.*?)` => `(.*)?`) can result in errors if another attribute follows the `value`
https://regex101.com/r/njz9QG/1

When I investigated the form pre-popuplation problem I found that the bug was only related to the missing enclosure. Fixing that made the pre-population work again. My PR has been stalled for a several months now. I'm quite surprised that suddenly closing it became urgent.

**Comment by escopecz** [comment]
@pety-dc It's not urgent. Just with the small number of testers we have we should avoid having duplicated PRs. I let you and Tanay work it out and choose which solution is better.

**Comment by saitanay** [comment]
`I'm quite surprised that suddenly closing it became urgent.`

@pety-dc - I think the new activity on this ticket was caused by my triage of the duplicate issue https://github.com/mautic/mautic/issues/9545 logged recently. No other intention there. 

`When I investigated the form pre-popuplation problem I found that the bug was only related to the missing enclosure. Fixing that made the pre-population work again.`
You are right. I think there was some additional regression that happened after your fix in the PR. Let us proceed with your PR as it was the original fix. But let us  retest it https://github.com/mautic/mautic/pull/9239 with the latest 3.2 code, and check if the additional change is required for the regression, and update https://github.com/mautic/mautic/pull/9239 if you see it required. 

Once updated, I am happy to test the PR https://github.com/mautic/mautic/pull/9239 

Cheers

**Comment by pety-dc** [comment]
@escopecz Would you please add the `ready-to-test` label to #9239. I suppose that makes it appear in the list on mautibox.com

**Comment by pety-dc** [comment]
@saitanay https://github.com/mautic/mautic/pull/9239#issuecomment-759584271

**Review by anton-vlasenko — CHANGES_REQUESTED** [review]
Unit tests are failing and in my opinion there is something wrong with the regular expression.
Will you be able to check it, @saitanay?
https://github.com/mautic/mautic/pull/9550/checks?check_run_id=2478689564

```
1) Mautic\FormBundle\Tests\Helper\FormFieldHelperTest::testPopulateField with data set #0 (Mautic\FormBundle\Entity\Field Object (...), '%22%2F%3E%3Cscript%3Ealert%28...ipt%3E', '<input id="mauticform_input_m...="" />', '<input id="mauticform_input_m...0)" />', 'Tags should be stripped from ...t XSS.')
Tags should be stripped from text field values submitted via GET to prevent XSS.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<input id="mauticform_input_mautic_firstname" value="&quot;/&gt;alert(0)" />'
+'<input id="mauticform_input_mautic_firstname" value="&quot;/&gt;alert(0)" //>'

/var/www/html/app/bundles/FormBundle/Tests/Helper/FormFieldHelperTest.php:37

2) Mautic\FormBundle\Tests\Helper\FormFieldHelperTest::testPopulateField with data set #1 (Mautic\FormBundle\Entity\Field Object (...), '%22%20onfocus=%22alert(123)', '<input id="mauticform_input_m...="" />', '<input id="mauticform_input_m...3)" />', 'Inline JS values should not b...t XSS.')
Inline JS values should not be allowed via GET to prevent XSS.
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<input id="mauticform_input_mautic_firstname" value="&quot; onfocus=&quot;alert(123)" />'
+'<input id="mauticform_input_mautic_firstname" value="&quot; onfocus=&quot;alert(123)" //>'
```

**Comment by dadarya0** [comment]
@RCheesley @escopecz @saitanay @kuzmany @pety-dc 
I have tested both PRs (#9550  & #9239) 

#9239 - This is working fine, No issue found
#9550 - Functionality wise this PR also working fine but In this I got css issue after filling values. after filling value, it is removing class attribute.

Without pre-filling :-
Screenshot 2021-09-20 at 4 26 15 PM

After pre-filling value :-

Screenshot 2021-09-20 at 4 30 02 PM

So IMO we should close #9550 and should merge #9239

**Comment by RCheesley** [comment]
Closing in favour of #9239

**Pull request closed without merging**
