### PR TITLE
Fix release process for Mautic 5

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

this PR addresses the isssues when releasing Mautic 5.0.0-beta1, as encountered in https://github.com/mautic/mautic/actions/runs/6509076538 and when testing the outcome of the release process locally.

Those are not the best solutions, but the minimum to get the tarball releases (well zip releases for Mautic) out.
The whole package release process needs an overhaul to be in line with the current state of Mautic

The following issues are addressed (via separate commits):
* Ensure the `/config/.gitkeep` file exists, so the dir and file are present in the zip files
* Ensure the upgrade path from 4 to 5 can be tested (different location for the config file)
* Ensure the needed files for local config detection (`composer.json`)  and asser generation (`package.json` and `package-lock.json`) are present.
* Ensure all versions between the minimal and current release are processed. 
  As there have been releases for the `4.4` branch and the `5.x` branch, not all tags were processed:
  **before fix**
  ```
  4.4.10
  5.0.0-beta1
  ```
  **after fix**
  ```
  4.4.10
  5.0.0-alpha
  5.0.0-alpha1
  5.0.0-beta1
  ```
* Ensure files have the correct permissions (non-executable).
  This fix is not trivial to the release process, but it's a fix for incorrect file permissions

Following issues still need to be addressed:
* after running the update, the `media/js` and `media/css` folders are empty, and `media/libraries` is missing. This means Mautic is unusable

there are still many other issues in the release process that need to be addressed:
* the current upgrade test **inside** the codebase dir (the `mautic-testing` dir is created [inside the codebase](https://github.com/mautic/mautic/blob/88a27b72b23f6ecf220b91f42afc3245680199d9/.github/workflows/release.yml#L156)) masks issues. 
  This PR addressed that the `composer.json` file for `project_root` detection is missing, as it just goes up to the parent folder. It will not fail during tests, but the results in broken zip files. 
  There are probably other 
* the `deleted_files.txt` does not take into account any changes in the [`exclude_file.txt`](https://github.com/mautic/mautic/blob/88a27b72b23f6ecf220b91f42afc3245680199d9/build/exclude_files.txt) or the [`processfiles.php`](https://github.com/mautic/mautic/blob/88a27b72b23f6ecf220b91f42afc3245680199d9/build/processfiles.php)
  E.g. recently the [`phpstan.neon` exclusion was changed to `phpstan*.neon`](https://github.com/mautic/mautic/blob/88a27b72b23f6ecf220b91f42afc3245680199d9/build/exclude_files.txt#L33) (to ensure the `phpstan-baseline.neon` file is not present. But for **existing** installs, that file will never be deleted, as it's not a change in git. This may result in unwanted files still present in existing installs that are upgraded.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
I see no issue. Thank you Mattias!

**Review by escopecz — DISMISSED** [review]
Thank you for fixing this! 👍

**Comment by mollux** [comment]
for future reference: 

**how to test the release process:**

* compile the package based on the branch you want to test
  `php build/package_release.php -b=fix-release-process`
* go 1 level **above** your Mautic root, to ensure no side effects are in place
* execute following script
  ```
  rm -rf mautic-testing
  
  wget https://github.com/mautic/mautic/releases/download/4.4.10/4.4.10.zip
  cp mautic/build/packages/5.0.0-beta1-update.zip 5.0.0-beta1-update.zip
  
  unzip -q 4.4.10.zip -d ./mautic-testing
  mkdir -p ./mautic-testing/var/logs
  if [[ "$(jq -r '.version | .[0:1]' ./mautic-testing/app/release_metadata.json)" == "4" ]]; then
      cp ./local.php ./mautic-testing/app/config/local.php
  else
      cp ./local.php ./mautic-testing/config/local.php
  fi
  cd ./mautic-testing
  
  DB_PORT=3306 php bin/console mautic:install --force http://localhost
  
  php bin/console mautic:update:apply --force --update-package=../5.0.0-beta1-update.zip
  php bin/console mautic:update:apply --finish
  php bin/console doctrine:migrations:sync-metadata-storage
  php bin/console doctrine:migrations:list

  ```

**Comment by mollux** [comment]
found one last issue:

the move of the config file needs to run as last step, to ensure the migrations changing config (e.g. `Version20230627140512` and `Version20230615101328` can check the file being loaded in the container.

This is addressed in the last commit

**Review by escopecz — APPROVED** [review]

**Pull request merged**
