### PR TITLE
[UX] Separate user account fields in sections

### LINKED ISSUE #13140: Organize the fields in the user profile
### Description
The task involves reorganizing the fields within the user profile to create a more structured and user-friendly layout, enhancing the way users access and manage their personal information.

### Impact
Reorganizing user profile fields would greatly improve the user experience by simplifying data input and retrieval, reducing confusion, and ensuring efficient management of user information, ultimately resulting in increased user satisfaction and ease of use.

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #13140 

#### Description:
This PR improves the user experience by simplifying data input and retrieval, reducing confusion, and ensuring efficient management of user information, ultimately resulting in increased user satisfaction and ease of use.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Click on the profile picture
3. Click to open Account
4. Look at the new titles

image

### CODE REVIEW

**Review by shinde-rahul — APPROVED** [review]
Looks good!!

Thanks @andersonjeccel!!!

**Comment by shinde-rahul** [comment]
One question: are we implementing this for user pages, too?

**Review by PatrickJenkner — APPROVED** [review]
Works as described and looks much better. Thanks!

**Comment by andersonjeccel** [comment]
@shinde-rahul Nice idea, thanks!

**Review by roboparker — APPROVED** [review]

**Review by Mike-Dropsolid — APPROVED** [review]

**Comment by escopecz** [comment]
@andersonjeccel could you please resolve the conflict? I'll merge it right after.

**Comment by andersonjeccel** [comment]
@escopecz Could you tell me what might be causing these conflicts? It's often happening

**Comment by escopecz** [comment]
@andersonjeccel it happens if the open PR is making changes on the same rows as other PRs that were just merged into the 5.x branch.

**Pull request merged**
