### PR TITLE
Add amqp to ddev configuration

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Updated DDEV Config to Include AMQP Extension"

Fix "amqp" extension is not installed.  during the save form

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Run `ddev start`
3. See everything works as before

### CODE REVIEW

**Comment by mollux** [comment]
@kuzmany 

I get the PR, just wondering if the requirement of that extension for specific functionality also need to be documented somewhere else (the installer checks, dev docs, ...)

**Comment by kuzmany** [comment]
@mollux Suppose messenger integration using `symfony/amqp-messenger`. I just noticed an error after saving the form, but I don't know why or what caused it. I didn't have time to dig into it.

**Comment by escopecz** [comment]
@kuzmany can you please make the testing steps clear? You mention that it happens on a form save? Which form?

**Comment by kuzmany** [comment]
Close it, pick it up once If I noticed again

**Pull request closed without merging**
