### PR TITLE
Public preview email disabled by default

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

We noticed preview url of email is enabled by default.  But preview url is incrementally and anybody can pick up url of any email.  This PR add preview url disabled by default  

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create new email and check If preview url is disabled by default 
image

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10845"></a>

### CODE REVIEW

**Review by npracht — DISMISSED** [review]
Good for me. By default it should be private because if people don't pay attention, all emails are easily accessible.

**Review by shinde-rahul — DISMISSED** [review]
LGTM!!
Thanks @kuzmany

**Comment by RCheesley** [comment]
When toggling the email preview I am seeing the following error in the console (in dev mode, so should not be an asset loading issue?) and then I am not able to toggle it back to the previous state.

```
3.bootstrap.js?v22f74e22:1735 Uncaught TypeError: Cannot read properties of null (reading 'off')
    at 3.bootstrap.js?v22f74e22:1735:27
    at HTMLDivElement.complete (3.bootstrap.js?v22f74e22:1581:25)
    at HTMLDivElement.fn (2.jquery.js?v22f74e22:4932:19)
    at HTMLDivElement.handle (3.bootstrap.js?v22f74e22:72:70)
    at HTMLDivElement.dispatch (2.jquery.js?v22f74e22:5183:28)
    at HTMLDivElement.elemData.handle (2.jquery.js?v22f74e22:4991:29)
    at Object.trigger (2.jquery.js?v22f74e22:8249:13)
    at HTMLDivElement.<anonymous> (2.jquery.js?v22f74e22:8327:18)
    at Function.each (2.jquery.js?v22f74e22:354:20)
    at jQuery.fn.init.each (2.jquery.js?v22f74e22:189:18)
```

**Comment by RCheesley** [comment]
@kuzmany can you take a look at the error above please, before this can be merged. Thanks!

**Comment by kuzmany** [comment]
@RCheesley It's not related to this PR.
After research I noticed it happen because this PR https://github.com/mautic/mautic/pull/10705
It does not work properly on more places (emails list too)
We need check it in separate PR
Probably @shinde-rahul  could put eyes on it

**Comment by RCheesley** [comment]
OK I will raise that as another issue, thanks for looking into it! I think I saw someone else reporting it somewhere else so I'll try to dig that out. It does mean it's not possible to test this until that problem is addressed though!

**Comment by kuzmany** [comment]
It's possible test it. Just need check if new emails got disabled this option by default - already approved. There are also unit tests.

**Pull request merged**
