### PR TITLE
Email kill switch

### PR DESCRIPTION
**Pull request by indorock**
I added this custom feature to Mautic 2.16 and now updated it to work with M3. It adds a switch at the top of email settings that will disable email sending of any kind, it has saved our skins in different occasions when segments were incorrect resulting in the wrong leads being sent an email blast, and also when setting up a new environment alongside an old one with the same leads and you don't want duplicate emails sent out, etc.

### CODE REVIEW

**Comment by npracht** [comment]
Hi @indorock ! Thanks a lot for that. Could you please add a clear "how to reproduce" in your PR description.
Also, we'll need documentation for that PR.

Thanks !

**Comment by RCheesley** [comment]
This will likely resolve https://github.com/mautic/mautic-documentation/issues/26 (at least partially!) - one of my longstanding documentation requests:  :tada:

**Comment by PurHur** [comment]
Hey i have the same problem! Would it be in the same scope if you can set this value right in the install process when configuring the outgoing email service?

**Comment by RCheesley** [comment]
Close & open for travis

**Comment by RCheesley** [comment]
@indorock please also take a look at the Travis error!

**Comment by RCheesley** [comment]
Bumping this to 3.2 due to the lack of response to failing Travis build. @indorock if you can please address those issues we can look to get this tested and merged for 3.2 in November.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@indorock could you please take a look at and resolve the conflicts (in addition to signing the contributors agreement!) - many thanks!

**Comment by npracht** [comment]
This is too old. i'll close it and if someone want to carry it again, then we'll re-open it with huge pleasure.

**Pull request closed without merging**
