### PR TITLE
Updates emoji helper with the latest emoji

### PR DESCRIPTION
**Pull request by alanhartless**
Please answer the following questions:

| Q             | A
| ------------- | ---
| Bug fix?      | N
| New feature?  | Y 
| BC breaks?    | N
| Deprecations? | N
| Fixed issues  |  N

## Description

Background: Because Mautic uses utf8 for the database schema, 4 bit emojis cannot be saved. This helper converts the emojis back and forth. 

This PR simply updates the massive EmojiHelper with the latest emojis from php-emoji.

## Steps to test this PR

Create emails, landing pages, etc with emoji and make sure they save, are viewable, and editable

### CODE REVIEW

**Comment by escopecz** [comment]
I tested :rage: emoji in email. It appears in the preview like this:
mautic-rage-emoji
The emoji does not get replaced in the contact notes. I didn't get any error, so :+1:

**Comment by dbhurley** [comment]
+1 works for me.

**Comment by mqueme** [comment]
I tested this with PHP 7 and it didn't work, gave me this error -> Mautic does not support PHP version 7.0.0 at this time. To use Mautic, you will need to downgrade to an earlier version.

**Comment by dongilbert** [comment]
Alan - I tested @mqueme's comment there and it's true - this PR doesn't work on PHP 7, but it's just because you haven't merged the latest staging branch into your branch.

**Comment by alanhartless** [comment]
@dongilbert and @mqueme I merged staging

**Comment by mqueme** [comment]
+1. works for me!

**Pull request merged**
