### PR TITLE
Add function to recursively utf8 encode social cache. 

### PR DESCRIPTION
**Pull request by drmmr763**
fixes issue where non utf8 chars cant save to db. 

How to test:
Add a lead which has UTF-8 characters in their twitter profile. Before patch it should error out. 

After patch, it should work successfully. 

here's a twitter profile that has the problem: `FareehaSKhan`

Caused by the little 'heart' character in their profile description. The patch should allow the item to be added successfully. 

Don't merge this just yet till we have some more discussion on it as a solution for dealing with these character encoding.

### CODE REVIEW

**Comment by drmmr763** [comment]
Closed to use https://github.com/mautic/mautic/pull/404 instead

**Comment by escopecz** [comment]
I tried to authorize Twitter integration (assuming it has to be done to test this), but while authorizing twitter app I got this error:
`You are not allowed to access this file. Check index_dev.php for more information.`
on this URL:
`http://mymautic/index_dev.php/s/addon/integrations/authcallback/Twitter?oauth_token=******&oauth_verifier=******`

**Comment by drmmr763** [comment]
@escopecz I closed this PR a while back in favor of the #404 instead. Thanks!

**Comment by escopecz** [comment]
Oh, right. I commented under wrong PR. I noticed this is linked and has more information so I tested by description here. I'll copy my comment to #404.

**Pull request closed without merging**
