### PR TITLE
Match CSV imported contacts by ID

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features"
| Bug fix?                               | no
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR adds possibility to match contacts imported from CSV by ID

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Import contact from CSV with matched ID column
3. If contact with ID already exists then it will be updated, otherwise new contact will be created. Matching contacts by ID has higher priority than other unique fields.

### CODE REVIEW

**Comment by npracht** [comment]
@patrykgruszka can you have a look at conflicts ?

**Comment by patrykgruszka** [comment]
@npracht sure, done.

**Review by kuzmany — CHANGES_REQUESTED** [review]
I don't see ID in field lists for import matching. Do I something wrong?

image

I think it's related to this change https://github.com/mautic/mautic/pull/7308

**Comment by patrykgruszka** [comment]
@kuzmany you're right, there was some changes in ImportController recently and needed some adjustments. I've moved the ID to special fields mapping in ImportContactSubscriber just like the others. It's working now, but there is needed some translation that is probably not in the repository. Where should I register this `mautic.lead.import.label.id` key?

**Comment by kuzmany** [comment]
@patrykgruszka you can add new translation string here https://github.com/mautic/mautic/blob/09fb766d78a06c7efed5876222d715ac8b60dcb4/app/bundles/LeadBundle/Translations/en_US/messages.ini#L200-L199

**Comment by patrykgruszka** [comment]
@kuzmany thanks, I don't know why my IDE has not indexed this file. It's ready to test now.

**Review by kuzmany — CHANGES_REQUESTED** [review]
It works now, but ID is under properties.

image

I suggest it merge  to contact fields list few lines bellow

https://github.com/mautic/mautic/pull/9780/files#diff-75bcc4ca900275b4bb2142463d20f3ea95881a7c2d8c93aedc7e67cf2a256ee8R88

Something like

`array_merge(['id' => 'mautic.lead.import.label.id'], $this->fieldList->getFieldList(false, false))`

**Comment by patrykgruszka** [comment]
Ok, fixed this. Thanks for suggestions.

**Review by kuzmany — APPROVED** [review]
Looks good to me 👍 
Great addition

**Review by npracht — APPROVED** [review]
✅ It works as expected with higher priority on ID match than any other field.

**Pull request merged**
