### PR TITLE
Using "anonymous: lazy" to make the firewall lazy is deprecated, use "anonymous: true" and "lazy: true" instead.

### PR DESCRIPTION
**Pull request by biozshock**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 

## Description
The PR presents the change in config values that will be compatible with Symfony 6.

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Check anonymous pages works, e.g. public pages.

### CODE REVIEW

**Review by andersonjeccel — COMMENTED** [review]
I'm not sure if it's related, but it fails when I try to use the public preview URL for landing pages

image

**Comment by biozshock** [comment]
> I'm not sure if it's related, but it fails when I try to use the public preview URL for landing pages
> 
@andersonjeccel  If i read the screenshot correctly: you've tried to open a preview of a public page designated for the creator of the page and/or admin (has the URL /page/preview/{id}) in the incognito mode without logging in, which properly produced the 403 Forbidden, because the anonymous user must not have access to preview pages, as they may be under construction/obsolete/etc. 
What you really need to do in the incognito mode is to open the URL indicated in the black box instead of the blue box on the screenshot below. That one is dedicated to anonymous users and will be available if the page is published.

image

But anyway a good test! Now we know that the pages that should not be accessible by the anonymous users are still fine. Keep it up.

**Comment by andersonjeccel** [comment]
@biozshock got it, I’ll bring the label to review UX because it might be confusing the way it is now 

I also tested the page URL marked in pink, it was working as expected

**Review by andersonjeccel — APPROVED** [review]
Updating the review
Seems to be working as expected

**Review by escopecz — APPROVED** [review]
I was forced to do the same change in https://github.com/mautic/mautic/pull/13962. Thanks!

**Pull request merged**
