### PR TITLE
remove all pipedrive related files and functions

### PR DESCRIPTION
**Pull request by npracht**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 
| New feature/enhancement? (use the a.x branch)      | 
| Deprecations?                          | ✅ 
| BC breaks? (use the c.x branch)        | ✅ 
| Automated tests included?              | N/A
| Related user documentation PR URL      | Need to be removed from doc
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
Current Pipedrive plugin stopped working due to Pipedrive API deprecations.
Knowing that Mautic Community policy is to not carry in core third party plugins and move them to marketplace, I supply suggest we remove it from core:
1. No more maintenance
2. No more issue on mautic/mautic repo for outdated plugin

#### To do left
@kuzmany we need to remove dead code of Pipedrive on this 2 last files, but I was scared to touch these functions 👀 
- [x] plugins/MauticCrmBundle/EventListener/CompanySubscriber.php
- [x] plugins/MauticCrmBundle/EventListener/LeadSubscriber.php

### CODE REVIEW

**Comment by kuzmany** [comment]
I cleanup phpbaseline.neon
Also I've added migration to remove all integration_entity table records (If do not need it I can revert it).

**Review by escopecz — DISMISSED** [review]
The code changes look good to me. Thanks for removing a plugin that is no longer working. Let's use the new one instead.

**Comment by escopecz** [comment]
@npracht @kuzmany I can see we did not get the second approval for this and now we have some conflicts. Could you please resolve those?

@RCheesley as there is basically nothing to test as it's removing a plugin, can you give your approval on this?

**Comment by RCheesley** [comment]
Happy to approve once the conflicts are resolved and I am able to do some basic testing. Knowing how there have been in the past some issues with removing plugins breaking things I do think we need to do some basic user testing.

I still think that we need to post a [front-end notice](https://contribute.mautic.org/community-structure/governance/code-governance/deprecation-policy#front-end-notice-format) for people who are using this version of the Pipedrive plugin in a 4.4.x release to notify them that it is going to be removed in Mautic 5.0 and telling them to update to the new plugin, pointing them at the blog post on mautic.org. This is in line with our policy on deprecating features - is that feasible to do in a separate PR please?

I know that folks should have already noticed that the plugin stopped working but we should follow our own guidance as best we can.

**Comment by escopecz** [comment]
@RCheesley I can create the PR for the UI notices that this plugin will be removed in Mautic 5.0.0 for the Mautic 4.4.9 release. Where should I add the UI notices? In the plugin config form?

**Comment by RCheesley** [comment]
> Where should I add the UI notices? In the plugin config form?

I was thinking that a cancel-able message on the dashboard would be helpful, perhaps? Otherwise we are expecting the user to go to the plugin screen which, let's face it, they usually only do when configuring the plugin. I'd suggest displaying it with the yellow background, with the option to close it via a cross button

If it's possible to only show it when the plugin in question is enabled that would be ideal - this is code that I think we will re-use so maybe having some documented best practice which we can add to the deprecation policy would be helpful in the future?

**Comment by escopecz** [comment]
@RCheesley we have this notification area in Mautic:
Screenshot 2023-05-18 at 14 56 04
We can easily create a migration to add a message there. Creating some special new notification that we'll need to show only once per each user and remember when they dismiss it would be quite a big feature. As we struggle with resources to finish M5 there is no space to implement something new or make the existing notification center somehow better. Is adding a message there good enough?

**Comment by RCheesley** [comment]
>  Is adding a message there good enough?

Yes I think that is fine for what we need!

**Comment by escopecz** [comment]
Here is the PR for M4.4 with deprecation messages regarding removal of the PipeDrive plugin. Please review and  test so we can get this merged. 

https://github.com/mautic/mautic/pull/12364

**Review by escopecz — APPROVED** [review]
I rebased this, fixed a couple of issues. Good to go now 👍

**Review by mabumusa1 — APPROVED** [review]
Changes looks good, Migration changes are great

**Pull request merged**
