### PR TITLE
[type-declarations] Add known return array type declarations

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
The PHPStan check is missleading, as more errors were fixed than added :slightly_smiling_face: 

It's ready to review and go :+1:

**Comment by TomasVotruba** [comment]
Good to go :+1:

**Review by escopecz — APPROVED** [review]
I confirmed in 35 files out of 120 that there is no doubt that the method must return an array. Scanned through the rest of the changes. Everything looks fine 👍 

The baseline did not add any issue, just reduced a count which counts as modification, but a good one.

**Comment by TomasVotruba** [comment]
This is awesome :hugs:

**Pull request merged**
