### PR TITLE
Asset removing php templates

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [Y]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/pull/11610

#### Description:

In https://github.com/mautic/mautic/pull/11610 the old PHP templates weren't removed. Removing them here.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Same as for https://github.com/mautic/mautic/pull/11610

### CODE REVIEW

**Comment by jos0405** [comment]
@escopecz , something is off with the html:

image

image

**Comment by escopecz** [comment]
@jos0405 good catch. Fixed in https://github.com/mautic/mautic/pull/11846/commits/e2c97bb56e950efb32cc411f96450c52fb2c06a2

**Review by jos0405 — APPROVED** [review]
Tested, works as expected. HTML is also displayed properly.

image
image

Looks good:
image



image

**Review by mabumusa1 — APPROVED** [review]
I just tested this PR, it looks good to go

**Pull request merged**
