### PR TITLE
Master.duplicate points fix

### PR DESCRIPTION
**Pull request by Dreiser**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. 
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by alanhartless** [comment]
Thanks for looking at this Jakub! This breaks all the unit tests for incrementing points :-) See the travis CI job above https://travis-ci.org/mautic/mautic/jobs/299627661

**Comment by Dreiser** [comment]
Fixed, bad use of resetPointChanges method

**Comment by Maxell92** [comment]
I think we can merge this @alanhartless ?

**Comment by alanhartless** [comment]
Need to make sure it passes the new test I added to the other PR before we merge.

**Comment by alanhartless** [comment]
@Dreiser can you move that test into this PR?

**Pull request merged**
