### PR TITLE
fix: update labeler permission structure

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR fixes the permission structure for the labeler action.

---

### CODE REVIEW

**Comment by andersonjeccel** [comment]
@escopecz I placed the permissions directly on the labeler stucture instead of giving the permission for all steps... can we try this way or should I bring the permission above, to all jobs?

**Comment by andersonjeccel** [comment]
@escopecz If no success with this fix, just revert everything

**Review by escopecz — APPROVED** [review]
Let's try this. Thanks!

**Comment by escopecz** [comment]
Nope, still failing in https://github.com/mautic/mautic/actions/runs/10056031811/job/27793996544?pr=13775 with
```
Warning: The action requires write permission to add labels to pull requests. For more information please refer to the action documentation: https://github.com/actions/labeler#permissions
Error: Resource not accessible by integration
```
I'll revert this and https://github.com/mautic/mautic/pull/13874

**Comment by escopecz** [comment]
Reverted in https://github.com/mautic/mautic/pull/13992

**Pull request merged**
