### PR TITLE
Refactor  deprecated setMethod in unit tests

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

setMethod in unit tests marked as @deprecated https://github.com/sebastianbergmann/phpunit/pull/3687
This PR refactor it

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Wait to pass CI

### CODE REVIEW

**Comment by escopecz** [comment]
The tests are failing mostly with message
```
Trying to set mock method "setFirstResult" with onlyMethods, but it does not exist in class "Doctrine\ORM\AbstractQuery". Use addMethods() for methods that do not exist in the class
```
@kuzmany can you look into this? Otherwise thanks for taking care of that!

**Comment by kuzmany** [comment]
@escopecz I had little time to finish it. Now unit tests passed

**Comment by kuzmany** [comment]
@fedys Can you look on this PR?

**Comment by fedys** [comment]
@kuzmany I'm on it

**Review by fedys — APPROVED** [review]
Thera are no issues. Thanks @kuzmany !

**Review by escopecz — APPROVED** [review]
👍

**Pull request merged**
