### PR TITLE
add companies permissions (separate lead:leads)

### PR DESCRIPTION
**Pull request by qneyrat**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | x
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #3083 #2806
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
I have rename Contact Permissions in Lead Permissions and I have separate lead:leads role in new role for companies lead:companies

Imgur

#### Steps to test this PR:
1. create new role
2. Lead Permissions -> Companies - User has access to

### CODE REVIEW

**Comment by alanhartless** [comment]
Hi @qneyrat,

Thanks for this! Does it address backwards compatibility? If we all of a sudden require permissions for companies, any existing users who had access before would now be blocked without the interference of an admin updating all the roles.

**Comment by qneyrat** [comment]
Yes, it's true :). Maybe it's possible to add by default companies permission?

**Comment by mqueme** [comment]
Will a migration be needed for this? in order to update the roles with the new company permissions set to what the role has set for the lead permissions?

**Comment by alanhartless** [comment]
Just checking on an update for this addressing BC?

**Comment by BatchHeader** [comment]
I have just come accross this issue where non-admin users are unable to access companies on our Mautic install and wondered if this PR will be merged into a release?

**Pull request closed without merging**
