### PR TITLE
Fix companies in webhook

### PR DESCRIPTION
**Pull request by webalexstudio**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/3950
| BC breaks? | no
| Deprecations? | no

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description: 

Fixing of the problem with empty company info on creating new contact webhook.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Add new webhook on new create new contact
2. Catch webhook event and parse post
3. Company field is empty even if contact was linked to it.

#### Steps to test this PR:
1. Add new webhook on new create new contact
2. Catch webhook event and parse post
3. Company field now is json array with id of the company and name. Json array, because contact can be linked to several companies.

### CODE REVIEW

**Comment by escopecz** [comment]
It works as described, but I don't get why the companies array must be json decoded? I get the JSON webhook request like this:
```
                       "company":{  
                            "id":4,
                            "group":"core",
                            "label":"Company 3",
                            "alias":"company",
                            "type":"text",
                            "value":"[{\"id\":\"1\",\"name\":\"Allyde\"},{\"id\":\"2\",\"name\":\"Delta\"},{\"id\":\"3\",\"name\":\"Github\"}]"
                        },
```
Why do I have to json decode the value to be able to work with it?

**Comment by webalexstudio** [comment]
Hi.
Contact can be linked to several companies. I thought that will be good to have all ids and names of the companies on getting contact webhook. Basically it is useful for our company to get such information, because we can control linking. 
As I understand you prefer to see there object instead of json array? But type of that filed is "text", so as to me json string is ok.
But I am open for proposals.

**Comment by escopecz** [comment]
You are right about the text field. From history point of view, it should hold name of the current company. If we'd want to send also the list of all contact's companies, it should not be in the company field, but as a "companies" attribute of the contact's object. Like it has "tags" or "ips".

**Comment by webalexstudio** [comment]
What if there are two or more companies? Which company is current? First one?

**Comment by escopecz** [comment]
There is flag `is_primary` which can be selected in the contact's detail page, but automatically it is added to the latest company.

**Comment by webalexstudio** [comment]
As I understand if linking to several companies on create contact, take last one? Right?

**Comment by escopecz** [comment]
In case of adding several companies at once, it doesn't matter which one you choose.

**Comment by webalexstudio** [comment]
Ok, I will change the code later. Thanks.

**Comment by dongilbert** [comment]
Pending code update, so removed "Ready to Test" label.

**Comment by dongilbert** [comment]
This doesn't take into account adding contacts via the API, or anywhere besides the `newAction` on the `LeadController`. It's not an acceptable solution to the problem (not a knock against you, we didn't realize it at first either). We'll need to push it out of the 2.9 release and come up with a better solution.

**Comment by webalexstudio** [comment]
Thanks for attention to this problem and to my fast solution.

**Comment by alanhartless** [comment]
@webalexstudio Will you be able to address https://github.com/mautic/mautic/pull/3958#issuecomment-311463071 so we can get this one in?

**Comment by alanhartless** [comment]
Closing due to lack of feedback. If you'd like us to reconsider this, please submit a new PR addressing the feedback. Thanks!

**Pull request closed without merging**
