### PR TITLE
Dashboard widget: Best tracking pages

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR added best tracking page for as dashboard widget

image

#### Steps to test this PR:
1. Apply PR on Mautic instance with a lot of page hits
2. Then add dashboard widget - Best tracking pages
3. Chcek If stats are related to your expection

### CODE REVIEW

**Review by npracht — DISMISSED** [review]
Working from a user perspective !

**Comment by npracht** [comment]
Using in production environment.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by mohit-rocks** [comment]
@npracht  I tried to rebase it with 3.x. It is working fine without any conflicts. We can change the base directly.

**Comment by npracht** [comment]
I confirm ;)

**Comment by RCheesley** [comment]
Bumping to 3.2 due to unresolved Travis failure

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@kuzmany conflicts on this one, closing/opening for tests to run.

**Comment by kuzmany** [comment]
@RCheesley thanks, conflicts resolved.
We are using it on production.

**Comment by kuzmany** [comment]
Unit tests added

**Comment by RCheesley** [comment]
@kuzmany this one has the base of 4.1 and when I change it to 4.x we have a lot of conflicts. It might be better to create a new PR on 4.x?

**Comment by kuzmany** [comment]
Close favor to https://github.com/mautic/mautic/pull/12623

**Pull request closed without merging**
