### PR TITLE
Campaign builder improvements and marketing/transactional emails for campaigns

### PR DESCRIPTION
**Pull request by alanhartless**
Please answer the following questions. 

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/77
| Related developer documentation PR URL | https://github.com/mautic/developer-documentation/pull/25
| Issues addressed (#s or URLs) | 
| BC breaks? | N
| Deprecations? | N

#### Description:

1. This PR revamps our campaign builder. It does away with the right side menu and uses plus signs or buttons on the anchors to inject events. It also provides a way for developers to configure if an action or decision should be restricted from connecting into other actions/decisions (i.e. opens email will only appear in the list if adding to a send email action or dynamic web content action can only be connected into a dynamic web content requested decision along with preventing the dynamic web content action from connecting into the inaction path of a the dwc request decision). Finally the UI redo made the decision action/inaction wording for timing a little clearer. 

2. It adds the concept of transactional/marketing email types to campaign email sends. Transactional will allow a contact to be sent the same email across campaigns multiple times. Marketing emails will check to see if the contact already has received the email (even from another source such as a different campaign, form, etc), and if so not send it again; although the contact continues through the campaign. 

3. It adds dev support to assign channel/channel ID to the event log for statistical/display purposes. I.e. being able to query which email triggered specific campaign events. 

#### Steps to test this PR:
1. Run doctrine:migrations:migrate
2. In dev mode (or build prod assets), build new and test old campaigns including some of the scenarios in the description.
3. For transactional/marketing emails, create a new campaign like this:

Execute the campaign and open each email sent. Upon opening, the transactional email should be sent again. But the marketing email should not although registered as completed.

### CODE REVIEW

**Comment by dbhurley** [comment]
Looking pretty good! I noticed a bug we've had all along I believe with the campaign builder. Required fields (denoted with the red asterisk) are not truly required but allow the modal to be accepted and return to campaign builder.

**Comment by dongilbert** [comment]
+1 just needs docs. Great job!

**Comment by escopecz** [comment]
I got this error on a campaign clone action:

`Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT cl.leadlist_id, l.name FROM mau_campaign_leadlist_xref cl INNER JOIN mau_lead_lists l ON l.id = cl.leadlist_id WHERE cl.campaign_id = mautic_cbeb41124ad193cab522e3c2c005f418462f81ba':  Unknown column 'mautic_cbeb41124ad193cab522e3c2c005f418462f81ba' in 'where clause'" at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT cl.leadlist_id, l.name FROM mau_campaign_leadlist_xref cl INNER JOIN mau_lead_lists l ON l.id = cl.leadlist_id WHERE cl.campaign_id = mautic_cbeb41124ad193cab522e3c2c005f418462f81ba':\n\nUnknown column 'mautic_cbeb41124ad193cab522e3c2c005f418462f81ba' in 'where clause' at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\Mysqli\\MysqliException(code: 0): Unknown column 'mautic_cbeb41124ad193cab522e3c2c005f418462f81ba' in 'where clause' at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php:94)"} []'

**Comment by alanhartless** [comment]
@escopecz Good catch. Cloning was completely botched. Should be fixed now. Give it another whirl?

**Comment by dongilbert** [comment]
Cloning works now. Sorry I missed that in my testing. Great job fixing it though!

**Comment by escopecz** [comment]
Everything works for me now :+1:

**Pull request merged**
