### PR TITLE
Prevent run report scheduler If already run

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for 4.0
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
If you use send reports to email, and your report processing take more time like your cron timeout `mautic:report:scheduler`, command start process same report again. This make issue on big reports

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create report with large data
3. Use export & send 
image
4. Try run command and few seconds after same command again
5. After this PR you should see `Script in progress. Can force execution by using --force.`

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10121"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
Updated the branch but this needs to be rebased.

**Comment by volha-pivavarchyk** [comment]
I ran command mautic:report:scheduler and three seconds later do it again. 

I got the next result:
image

My max report processing was taking some seconds. Should I create a larger report to better test this PR?

**Comment by kuzmany** [comment]
@volha-pivavarchyk I think it works like expected. You are not able to run second command until first finish.

**Comment by npracht** [comment]
Closed in favor of https://github.com/mautic/mautic/pull/13764 rebased against M5.

**Pull request closed without merging**
