### PR TITLE
Fixed modal window responsiveness

### PR DESCRIPTION
**Pull request by karser**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | yes
| New feature? | 
| MauticBox URL |  https://mautibox.com/7534/page/preview/4
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Discord conversation:
image

Before:
image

After:
image

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Put a form snippet on a Landing Page, e.g {form=2}
2. Add a call-to-action button which opens the form in a modal window. See [the docs](https://github.com/mautic/documentation/tree/master/en/forms#how-to-open-an-opt-in-form-in-a-modal-window-when-the-call-to-action-button-is-clicked)
```
<a class="btn btn-default" href="#" id="call-to-action-one">Click me</a> <!-- trigger button -->
{mauticform id=2 style=modal element=#call-to-action-one} <!-- setup modal form -->
```
3. Emulate mobile screen using Chrome Dev Tools and click the button.

### CODE REVIEW

**Comment by karser** [comment]
Hello @npracht, is there a chance to see this PR merged in 2.15.x? It doesn't break BC, it's a bug-fix, isn't it?

**Comment by npracht** [comment]
Hi,

It needs to be tested first by 2 persons.
As far as I know, 2.15.2 is closed now. @kuzmany ?

N.

**Comment by kuzmany** [comment]
First, remove media/css/modal.min.css  from pull requests (add from staging).
With new release we will regenrate minified css and js.

If you will make two tests today, I can add it to 2.15.2.

**Comment by karser** [comment]
I tested this PR on Mautibox. https://mautibox.com/7534/s/pages/edit/4

I discovered 2 issues:

1. The file `media/css/modal.min.css` is not updated.
That it, neither `app/console mautic:assets:generate` nor `grunt less` updates `media/css/modal.min.css`. Speaking of which, is there a reason the minified asset is under VCS?

In this PR I generated it using
```
npm install uglifycss -g
uglifycss media/css/modal.css > media/css/modal.min.css
```

I will revert and commit `modal.min.css`.

2. Due to the different Mauticbox webserver configuration I encounter the insecure https => http redirect error when trying to open a form in the iframe.

It happens in mautic-form-src.js:
```
        Form.getFormLink = function(options) {
            var index = (Core.devMode()) ? 'index_dev.php' : 'index.php';
            return Core.getMauticBaseUrl() + index + '/form/' + options.data['id'] + '?' + options.params;
        };
```
Here is the behavior on mauticbox:
```
https://mautibox.com/7534/index.php/form/2 [301] => https://mautibox.com/7534/form/2 [200]
https://mautibox.com/7534/index_dev.php/form/2 [200]
```

So I'll remove `index.php` from `getFormLink` function.

**Comment by karser** [comment]
Done, everything works as expected: https://mautibox.com/7534/page/preview/4
Click on the link and see if modal is responsive on mobile.
cc @kuzmany @npracht

**Comment by kuzmany** [comment]
media/css/modal.min.css  it's not reverted
Mautibox should regenerate assets on every commit is pushed.

**Comment by karser** [comment]
>media/css/modal.min.css it's not reverted

After you first comment I removed the file and I was surprised that `modal.min.css` wasn't generated by Mauticbox.
Then I reverted it, meaning committed back generated file(see my previous comment)

**Comment by karser** [comment]
What does Mauticbox launches to generate assets?
Neither `app/console mautic:assets:generate` nor `grunt less` updates `media/css/modal.min.css`

**Comment by kuzmany** [comment]
@karser You're right. Then it's okay.

**Comment by RCheesley** [comment]
Similar to #7510 I am unable to reproduce this. I can't get it to show the form in a modal. Perhaps you can provide some guidance @karser ?

**Comment by dennisameling** [comment]
Also tested on a production instance and cannot get this to work in 2.16.0: 

image

Looks like `{mauticform}` isn't replaced, could it be that it was renamed to `{form}` instead? With `{form}` it seems to ignore the `style=modal` and show the form immediately instead. Something might have changed after this PR was created in May 2019. :(

**Comment by RCheesley** [comment]
I tend to agree, I think therefore we should close the PR - if it can be refactored at a later date we can re-open and consider then.

**Pull request closed without merging**
