### PR TITLE
Remove pending count

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [x] 
| Related user documentation PR URL      | /
| Related developer documentation PR URL | /
| Issue(s) addressed                     | /

#### Description:

The query to count the pending emails is slowing down the email detail page significantly when the email was sent to several thousands contacts. We decided to get rid of it completely because the information is hidden and to view it the user must open the details table. The majority of users do not even know the information is hidden there. It's much easier and more visible to get the pending count in the email list page.

Screen Shot 2021-11-09 at 10 31 29

#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2. View the email details page that the pending count line is gone.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10590"></a>

### CODE REVIEW

**Comment by npracht** [comment]
Didn't test but i'm okay with it. It terms of feature this is useless to have it here ✅

**Comment by mlahlouh** [comment]
I tested it and the pending row disappeared.

**Review by mabumusa1 — APPROVED** [review]
Did a code review, everything looks as expected. I also checked the functionality and it worked as expected

**Review by kuzmany — APPROVED** [review]
Code looks good. 
Works. 
Unit test included.
👍

**Comment by RCheesley** [comment]
Confirmed with @escopecz that we're most likely expecting a code coverage reduction due to the nature of the PR. Good to go.

**Comment by RCheesley** [comment]
@All-contributors please add @mlahlouh for usertesting

**Pull request merged**
