### PR TITLE
Fix ampersand encoding in tokens - backport to 4.4

### LINKED ISSUE #11643: URL's used as email token are malformed
### Mautic Version

4.4.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When you use an URL as a token in an email, it converts `&` to `&#38;`, breaking the URL. I can find [several](https://github.com/mautic/mautic/blob/5.x/app/bundles/PageBundle/Model/RedirectModel.php#L114-L117) [workarounds](https://github.com/mautic/mautic/blob/5.x/app/bundles/PageBundle/Model/TrackableModel.php#L118-L121) in the code that replace `&amp;` with `&` before it is inserted as tracking link, but these do not decode the decimal version.

API endpoint used: https://developer.mautic.org/?php#send-email-to-contact

Relevant code points:
 * https://github.com/mautic/mautic/blob/5.x/app/bundles/EmailBundle/Controller/Api/EmailApiController.php#L125
 * https://github.com/mautic/mautic/blob/5.x/app/bundles/CoreBundle/Helper/InputHelper.php#L193

Demo of extracted code that causes the issue: https://3v4l.org/c8rgB

### How can we reproduce this issue?

1. Make sure you have a contact;
2. Create a template email and use `{url}` as the URL of a link;
4. Call the API endpoint: `/api/emails/[ID OF EMAIL]/contact/[ID OF CONTACT]/send` with body:
```
{
    "tokens": {
        "url": "https://localhost/test?foo=bar&email=john.doe%40example.com"
    }
}
```
4. Click the link in the received email;
5. See you're redirected to `https://localhost/test?foo=bar&#38;email=john.doe%40example.com`.

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by JaZo**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [x] 
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | Fixes #11643 

#### Description:

Backport of #11644.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester));
2. Make sure you have a contact;
3. Create a template email and use `{url}` as the URL of a link;
4. Call the API endpoint: `/api/emails/[ID OF EMAIL]/contact/[ID OF CONTACT]/send` with body:
```
{
    "tokens": {
        "url": "https://localhost/test?foo=bar&email=john.doe%40example.com"
    }
}
```
5. Click the link in the received email;
6. See you're redirected to `https://localhost/test?foo=bar&email=john.doe%40example.com` instead of `https://localhost/test?foo=bar&#38;email=john.doe%40example.com`.

### CODE REVIEW

**Comment by escopecz** [comment]
Please check the failing STAN issues.

**Comment by JaZo** [comment]
> Please check the failing STAN issues.

Done!

**Review by escopecz — APPROVED** [review]
Thanks! The code looks good 👍

**Review by volha-pivavarchyk — APPROVED** [review]
Works well

image

**Pull request merged**
