### PR TITLE
Sugar bugs

### PR DESCRIPTION
**Pull request by mqueme**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/4956
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
SugarCRM 6 Community stopped fetching contacts
[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. try to fetch contacts from SugarCRM
2. no new contacts will sync over

#### Steps to test this PR:
1. Apply this PR try again
2. New contacts should come over

### CODE REVIEW

**Comment by isleshocky77** [comment]
This is now fetching Accounts, Contacts, and Leads from SugarCrm (SuiteCrm). Just a heads up that it's not respecting the `fetch-all` option which is now on the `mautic:integration:synccontacts`

**Comment by isleshocky77** [comment]
I've tested the following

`./app/console mautic:integration:synccontacts -i Sugarcrm -a '2 hour'`

- [X] Pull **Leads** from SuiteCrm -> Mautic Contacts
- [X] Pull **Contact** from SuiteCrm -> Mautic Contacts
- [X] Push Contacts from Mautic -> SuiteCrm Leads
- [X] Pull changed **Lead** data, SuiteCrm -> Mautic Contacts
- [X] Follows sync path when conflict in data (i.e I change first name on Mautic, it was overwritten by First Name on SuiteCrm)
- [ ] Muatic pushes Contact Timeline Link to SuiteCrm **Lead**
- [ ] Muatic pushes Contact Timeline Link to SuiteCrm **Contact**

SuiteCrm v7.9.7
Mautic v2.11.0

# ContactTimelineLink

```
Updating/creating leads from Mautic to Sugarcrm

                                                                                                                                                                                                              
  [Doctrine\DBAL\Exception\InvalidFieldNameException]                                                                                                                                                         
  An exception occurred while executing 'SELECT i.integration_entity_id, i.integration_entity, i.id, i.internal_entity_id,l.owner_id,l.email, l.lastname, l.email, l.lastname, l.firstname, l.firstname, l.m  
  auticContactTimelineLink FROM integration_entity i INNER JOIN leads l ON l.id = i.internal_entity_id WHERE (i.integration = ?) AND ((i.integration_entity = ?) OR (i.integration_entity = ?)) AND (i.inter  
  nal_entity = ?) AND ((i.integration_entity_id IS NOT NULL) AND (((i.last_sync_date IS NOT NULL) AND (l.date_modified > i.last_sync_date)) OR ((i.last_sync_date IS NULL) AND (l.date_modified IS NOT NULL)  
   AND (l.date_modified > l.date_added)))) AND (l.email IS NOT NULL) AND (l.date_modified BETWEEN ? and ?) LIMIT 100' with params ["Sugarcrm", "Contacts", "Leads", "lead", "2017-11-13 18:09:47", "2017-11-  
  13 20:09:47"]:                                                                                                                                                                                              
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.mauticContactTimelineLink' in 'field list'                                                                                                        
                                                                                                                                                                                                              

                                                                                                        
  [Doctrine\DBAL\Driver\PDOException]                                                                   
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.mauticContactTimelineLink' in 'field list'  
                                                                                                        

                                                                                                        
  [PDOException]                                                                                        
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.mauticContactTimelineLink' in 'field list'  
```

**Comment by isleshocky77** [comment]
@mqueme It looks like that error comes from having the `mauticContactTimelineLink` assigned to both a `Contact` field as well as a `Lead` field. The code only unsets the first instance.

**Comment by isleshocky77** [comment]
@mqueme Sorry to kill this thread, but even only having one match for just Contact is not pushing the ContactLink back to the Crm field

**Comment by pstevens71** [comment]
So I can get Mautic to pull contacts from SuiteCRM (after I applied the fix re: contact"s".  However, if I map the Account Name in SuiteCRM with the Mautic Core:Company then it fails with the following error:

[2017-11-14 17:25:36] mautic.ERROR: INTEGRATION ERROR: Sugarcrm - A new entity was found through the relationship 'Mautic\LeadBundle\Entity\CompanyLead#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #751. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). [] []

**Comment by isleshocky77** [comment]
I have some larger questions about the code for the SugarCrm integration. It appears that it probably should be entirely cleaned up like the Salesforce Integration was. It looks as if the ContactLink property is updated in pushLead, but not in pushLeads.

I would guess this integration would benefit a lot from an IntegrationTest similar to the SalesforceIntegrationTest.

**Comment by pstevens71** [comment]
@isleshocky77 I've also found it only imports "leads"  so far no luck with "contacts" and "accounts" which I've checked to bring over in the integration options.  I also haven't been able to get it to update leads where a change was made in SuiteCRM, or Visa Versa, I have the "mautic points" field set to push back to SuiteCRM and that doesn't seem to work either.   My cron job runs without error.

**Comment by pstevens71** [comment]
So I fixed my error issue, turns out my Cron jobs were running at default PHP settings and not the settings of the domain.  So I was running out of memory.
1.Leads push to SuiteCRM
2. Leads/Contacts pull from SuiteCRM

"sync" is not working to update changes though.  I get the following error:
[2017-11-17 17:30:04] mautic.ERROR: INTEGRATION ERROR: Sugarcrm - Module Does Not Exist mtc_WebActivities set_entries POST [] []

**Comment by javjim-mautic** [comment]
works properly

**Comment by isleshocky77** [comment]
@alanhartless @javjim-mautic Did you two test that this sends over ContactTimelineLink during the ```./app/console mautic:integration:synccontacts -i Sugarcrm``` command? Cause for me it's still not working. I dont' see anything in the two commits since my last comment which would enable this.

**Comment by alanhartless** [comment]
I did for both 6 and 7 and both worked.

**Comment by isleshocky77** [comment]
@alanhartless hmm. I'm actually running SuiteCrm 7.9.x which is just Sugar Version 6.5.25. I wonder why I'm having difficulties with this.

My process for testing is the follow, let me know if you see anything funky.

1. Match up bare minimum fields
** Contact.FirstName -> Lead.FirstName
** Contact.LastName -> Lead.LastName
** Contact.Email -> Lead.Email
** Contact.Description -> Lead.ContactTimelineLink
** Lead.FirstName -> Lead.FirstName
** Lead.LastName -> Lead.LastName
** Lead.Email -> Lead.Email
** Lead.Description -> Lead.ContactTimelineLink
2. Create new Lead in SuiteCrm
3. Run ```./app/console mautic:integration:synccontacts -i Sugarcrm -a '1 hour'```
4. Follow results
** Says fetched one Lead
** Fetched Lead is in Mautic
** Lead in SuiteCrm does not have an updated "Description" field.

I'm not seeing any errors, warnings, or even Mautic notifications.

**Comment by isleshocky77** [comment]
@alanhartless I'm not sure how this is working for you but I tracked down a major issue on the pushing of leads from mautic to Sugar. It seems that it always updates the last_sync_date of the integration when fetching the contact. Then in the looking for leads to update it checks to make sure the last modified > last_sync_date. This means, it **never** finds leads to push back to the integration - even when data has changed on mautic. When I commented out the following block of code I finally saw Mautic noting that 

> Number of leads/contacts fetched: 2
> 
> Fetching companies
> Fetch companies command is starting
> 
> 0 companies were updated and 0 companies were created
> 
> Updating/creating leads from Mautic to Sugarcrm
> Number of contacts pushed: 2 updated, 0 created, 0 had errors and 0 were ignored (likely duplicates or didn't match field criteria)

**NOTE** It was always marking __2 fetched__ but was always stating __0 updated__. Now it is showing __2 updated__ and my updated information (including the contactTimelineLink) ends up back in Sugar (Mautic).

```php
// app/bundles/PluginBundle/Entity/IntegrationEntityRepository.php:233
        $q->andWhere(
                $q->expr()->andX(
                    $q->expr()->isNotNull('i.integration_entity_id'),
                    $q->expr()->orX(
                        $q->expr()->andX(
                            $q->expr()->isNotNull('i.last_sync_date'),
                            $q->expr()->gt('l.date_modified', 'i.last_sync_date')
                        ),
                        $q->expr()->andX(
                            $q->expr()->isNull('i.last_sync_date'),
                            $q->expr()->isNotNull('l.date_modified'),
                            $q->expr()->gt('l.date_modified', 'l.date_added')
                        )
                    )
                )
            );
```

**Comment by alanhartless** [comment]
Did you get the latest pushed to this PR? I fixed several issues after your initial tests.

**Comment by isleshocky77** [comment]
@alanhartless did you push it to this PR? Cause I'm only seeing those two commits above since my original testing; however, my newest testing is running the latest staging which looks like this PR was also merged into.

**Comment by mfvetter** [comment]
I'm not sure if this is the right place to continue issues about Mautic and SuiteCRM sync problems.
I just upgraded to Mautic 2.12.0. I'm using SuiteCRM LTS 7.8.8 (Sugar 6.5.25).
I'm trying to make Mautic the system of record and push contacts and changes to SuiteCRM.

The contacts are being created and pushed to SuiteCRM. But if I update fields of a lead/contact in Mautic, the changes are not being pushed to SuiteCRM. So SuiteCRM has an outdated record of my leads/contacts when they get updated in Mautic. Once in a while it even creates a duplicate contact/lead in SuiteCRM.

I just want to update simple fields, let's say a phone number from xxx-xxx-xxxx to yyy-yyy-yyyy, but I don't see it updating in SuiteCRM. Below is my setup:

screen shot 2017-12-07 at 12 11 08 pm
screen shot 2017-12-07 at 12 11 30 pm
screen shot 2017-12-07 at 12 11 48 pm
screen shot 2017-12-07 at 12 12 30 pm
The same setup for Leads.

Am I missing something?

**Comment by isleshocky77** [comment]
@mfvetter This is a Pull Request which has now been merged and released as 2.12.0. If I had to guess, you should probably open up that last comment as a new comment and mention this PR with it.

I think this PR was specific to "SugarCRM 6 Community stopped fetching contacts"

**Comment by agentscript** [comment]
@pstevens71  I am also getting this error 
" mautic.ERROR: INTEGRATION ERROR: Sugarcrm - Module Does Not Exist mtc_WebActivities set_entries POST [] []"

Can you please explain how you resolved it ?

**Comment by pstevens71** [comment]
I still get that error.  However, all my leads, contacts, and accounts now synch.  I think what's not getting sync'd is the activity from Mautic.  Haven't figured that one out yet.

**Comment by agentscript** [comment]
Thanks for your quick reply so that means you are able to see the activities? Like  URL visited and Emails Read etc ?

**Comment by pstevens71** [comment]
No, no activities sync.  I get the error.

**Pull request merged**
