### PR TITLE
DPMMA-1020 Fix search email with special characters in campaign action

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features"
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Special characters in email name (e.g. `'"<>&`) are not escaped when entity is stored in database. In other hand the AJAX email lookup `ajax?action=email:getLookupChoiceList` escapes the query when performing a search. In effect when an email name contains special characters it can't be found.

This will also affect actions, and fixes similar issues with company, dynamicContent, message, sms, mauticSocial.

#### Steps to reproduce:
1. Create an email with name containing special characters e.g `It's an email`
2. Create campaign and add email send action
3. Try to search email typing the name with special character. While you type there will be a message "No matches found it's". The email appears on the list only because it was preloaded. If there were more emails in the system it would not show the result at all.
image

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat steps to reproduce
obraz

### CODE REVIEW

**Comment by mabumusa1** [comment]
@patrykgruszka please fix the conflicts, this PR is easy to test. let's get it across the finish line

**Comment by patrykgruszka** [comment]
@mabumusa1 The `AjaxLookupControllerTrait` file has been removed in this commit https://github.com/mautic/mautic/commit/54e30a1f9d5eb994a82497dd7cae935be31c0826 (CC @biozshock). This seems to have been done by accident as the lookup functionality no longer works. I can restore this in my PR, or you can do a separate PR to make this work before merging this PR. Just let me know.

**Review by annamunk — APPROVED** [review]
:white_check_mark: fix works fine and the test passes 
letsgo

**Comment by RCheesley** [comment]
I'm struggling to reproduce this in the 5.x branch:

Create email: It's an email

Create campaign, add a send email action, search for 'It's an email':

screenshot-8080-mautic-mautic-3183ptn7h2l ws-eu106 gitpod io-2023 11 10-18_46_19

Is it possible this is addressed already?

**Comment by patrykgruszka** [comment]
@RCheesley I see, it will only work if the email you are looking for is preloaded in the initial list. I've checked this and the backend returns an empty list if the `'` character is in the query. That's why in my case the result is displayed next to the "no matches found" message. So this PR still fixes the bug if you have a lot of emails. 
image

**Review by magdalenaleonow — APPROVED** [review]
I tested some special characters, everything works!
image

**Review by tomekkowalczyk — APPROVED** [review]
Code looks good

**Pull request merged**
