### PR TITLE
9097 Add missing tests

### LINKED ISSUE #9097: Add tests for "User notify campaign has unpublished mail"
This issue is to track the decreased test coverage in #8697.

In order to make the code easier to understand for other developers and increase stability of the feature/product, I'd like to urgently ask @hluchas to add tests for this feature that's scheduled for the 3.1 release. We've already merged the feature functionality-wise into 3.1-RC so that folks can start testing in the coming week. The tests should be in before the final 3.1 release on August 24, 2020.

Please ping me if you need help/guidance, thanks in advance 🚀

### PR DESCRIPTION
**Pull request by hluchas**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging 
| Bug fix?                               | no
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | -
| Related developer documentation PR URL | -
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/issues/9097

#### Description:
Adding missing tests mentioned
- https://github.com/mautic/mautic/issues/9097
- https://github.com/mautic/mautic/pull/8697/files

### CODE REVIEW

**Comment by hluchas** [comment]
We have to plan this kind of additional or community work into one of our sprints so I will need to discuss with our product owner. This is edge case and I need to discuss this with internal team, because next PRs which are older will have the same problem as mentioned in issue and we have to plan this. 
@dennisameling 
@alanhartless @RCheesley @escopecz

**Review by dennisameling — DISMISSED** [review]

**Comment by RCheesley** [comment]
@mautic/acquia-po we need these tests completed by Monday 24th August (afternoon at the very latest) if we are to merge the feature in 3.1.

**Comment by hluchas** [comment]
@dennisameling @RCheesley @chazadams  It should be good but waiting for coverage report over two hours now

**Review by dennisameling — APPROVED** [review]
LGTM 👍 thanks!! Code coverage comment was updated 3 hours ago, so it did work, the check status just wasn't updated.

**Pull request merged**
