### PR TITLE
Autowire repositories

### PR DESCRIPTION
**Pull request by biozshock**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ x ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ x ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
PR adds autowiring for repositories. This is needed for cleaner and more symfony-like code.

Should this target 5.x or 5.1?

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open any page. If that fails the PR contains an error.

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
Amazing! There is no BC break but let's merge it to RC2 to get this fully tested within the RC period.

**Comment by RCheesley** [comment]
I think this is based on 5.1 @escopecz ?

**Comment by biozshock** [comment]
@escopecz should i create a PR for 5.0, or you will cherry-pick this into that branch?

**Comment by escopecz** [comment]
I leave it up to you. If you need this in M5.0 and M5.1 is too late, feel free to create a PR for M5.0

**Pull request merged**
