### PR TITLE
Contact timezone saved to the contact from the page hit tracking

### PR DESCRIPTION
**Pull request by escopecz**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | false
| New feature? | true
| Related user documentation PR URL | Do we need to document this?
| Related developer documentation PR URL | null
| Issues addressed (#s or URLs) | Preparation for https://github.com/mautic/mautic/issues/539
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR adds a new Timezone custom field and fills it with a timezone in the PHP's timezone format (continent/city_or_country) based on what Fingerprint2 library sends us as timezone offset in the page hits.

If the Timezone field already exists among the contact custom fields, the migration will just update it.

#### Steps to test this PR:
1. Pull this PR
2. Run `app/console doctrine:migrations:migrate`
3. Check that the Timezone custom field was created or set as a core field if existed before
4. Visit a page tracked by Mautic JS tracking in a incognito browser window
5. Check that the contact who was just tracked is the correct timezone in the contact detail view as well as in the contact edit view.
6. You can also run `phpunit` in the app folder to test one unit test that was added.

This PR also fixes the timezone field type which stored only one part of the timezone previously.

### CODE REVIEW

**Comment by mqueme** [comment]
👍

**Comment by dongilbert** [comment]
Got this error while executing the migration: 

screen shot 2017-01-30 at 8 21 21 pm

**Comment by escopecz** [comment]
Thanks Don. The object value added. Try now, please.

**Comment by mbernabeu** [comment]
I think I'm having problems with this feature

Log prints this:

```
[2017-02-10 16:01:26] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Method getTimezone not exists" at /var/www/html/app/bundles/CoreBundle/Entity/CommonEntity.php line 39 {"exception":"[object] (InvalidArgumentException(code: 0): Method getTimezone not exists at /var/www/html/app/bundles/CoreBundle/Entity/CommonEntity.php:39)"} []
```


If I make a backtrack of the function where the error is generated I get this
```
#0 Called __call in /var/www/html/app/bundles/LeadBundle/Entity/CustomFieldEntityTrait.php on line 73
#1 Called __call in /var/www/html/app/bundles/PageBundle/Model/PageModel.php on line 462
#2 Called getTimezone in /var/www/html/app/bundles/PageBundle/Model/PageModel.php on line 462
#3 Called hitPage in /var/www/html/app/bundles/PageBundle/Controller/PublicController.php on line 353
#4 Called trackingImageAction in  on line 
#5 Called call_user_func_array in /var/www/html/vendor/symfony/http-kernel/HttpKernel.php on line 144
#6 Called handleRaw in /var/www/html/vendor/symfony/http-kernel/HttpKernel.php on line 64
#7 Called handle in /var/www/html/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php on line 69
#8 Called handle in /var/www/html/vendor/symfony/http-kernel/Kernel.php on line 185
#9 Called handle in /var/www/html/app/AppKernel.php on line 132
#10 Called handle in /var/www/html/app/middlewares/CORSMiddleware.php on line 92
#11 Called handle in /var/www/html/app/middlewares/CatchExceptionMiddleware.php on line 45
#12 Called handle in /var/www/html/app/middlewares/VersionCheckMiddleware.php on line 57
#13 Called handle in /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php on line 23
#14 Called handle in /var/www/html/vendor/stack/run/src/Stack/run.php on line 13
#15 Called Stack\run in /var/www/html/index.php on line 34
```

And getTimezone is called here

```
if (isset($query['timezone_offset']) && !$lead->getTimezone()) {
    // timezone_offset holds timezone offset in minutes. Multiply by 60 to get seconds.
    // Multiply by -1 because Firgerprint2 seems to have it the other way around.
    $timezone = (-1 * $query['timezone_offset'] * 60);
    $lead->setTimezone($this->dateTimeHelper->guessTimezoneFromOffset($timezone));
}
```

**Comment by escopecz** [comment]
@mbernabeu report it as a new issue, please. It will get forgotten here.

**Pull request merged**
