### PR TITLE
Support tokens in an email entity's "from address" override

### PR DESCRIPTION
**Pull request by alanhartless**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR adds the feature to use a custom field value as the email's "from address" on the advanced tab. This also does a little refactoring in order to use a testable class. 

Edit: I (@escopecz ) have updated this PR to work with the current code as it was written 5 years ago and it required some refactoring and added more tests.

[//]: # ( As applicable: )

#### Steps to test this PR:
1. Create a new custom email field.
2. Create a new email and on the advanced tab, test that the form address will validate with an email address or a custom field token `{contactfield=other_email}` but will reject anything that is not
3. Edit a contact and fill in an email address different than the system's default or the user's email if mail is owner is enabled. 
4. Create a segment with some contacts and send the email
5. The emails should arrive from the appropriate email addresses, if they had a token value, then it should be from that email, if the contact has an owner and mail is owner is enabled then from the owner, otherwise from the system default. 

Test with the following scenarios with both a SMTP mailer _and_ a token mailer such as Sparkpost or Sendgrid to ensure that the hierarchy below is obeyed. 
1. With a token as the advanced tab's from email and mailer is owner enabled.
2. With a token as the advanced tab's from email and mailer is owner disabled.
3. With a normal email address as the advanced tab's from email and mailer is owner enabled
4. With a normal email address as the advanced tab's from email and mailer is owner disabled
5. Nothing in the advanced tab's from email and mailer is owner enabled
6. Nothing in the advanced tab's from email and mailer is owner disabled

The hierarchy is as follows:
1. Email on advanced tab with custom field token if the value exists (otherwise it proceeds to the owner if applicable or default if no owner/owner is disabled)
2. Owner if mail is owner is enabled and contact is assigned to owner
2. Email on advanced tab with a standard email address defined
4. System default

### CODE REVIEW

**Comment by npracht** [comment]
(@alanhartless again Travis)

**Comment by alanhartless** [comment]
Thanks @npracht! Not sure why my git hook is not working. Will see if I can get that resolved.

**Comment by AndrassGray** [comment]
A more general thought : I am wondering why a new feature doesn't find it's way into the user documentation ?

**Comment by npracht** [comment]
@AndrassGray we have to agree ! ---> https://github.com/mautic/documentation/pull/334

**Comment by toledomarcela** [comment]
I've made a test. I've follow the step 1 and 3, I created the contact custom field and created the contacts with this field filled. But when I tried to save the email, it caused an error when I filled the "From Address" option on advanced tab.

image

Is this code ready to test? Is there anything we could do to help with the tests?

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@alanhartless sorry, more conflicts to address!

**Comment by RCheesley** [comment]
Bumping to 3.2 due to unresolved conflicts.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by alanhartless** [comment]
Conflicts resolved. 

@toledomarcela could you please try again? I'm not able to reproduce that using this branch. 

Screen Shot 2020-11-05 at 17 06 50

**Comment by lukassykora** [comment]
There are no conflicts but when I tested it did not work as described. It needs more work.

**Comment by fedys** [comment]
After some investigations with @alanhartless we found out there is a problem when sending an email via SMTP (a mail transport not supporting tokens) to multiple contacts. This [condition](https://github.com/mautic/mautic/pull/7811/files#diff-d1949283f925ccb79831f1331dca03d32cadc4cef0e05f0e9bed3f55d5d410aeR2141) causes that the `from address` is set only once. The question is how to fix this to not break other functionality such as sending an email to a single contacts.

Snímek obrazovky 2021-03-09 v 15 56 19

**Comment by RCheesley** [comment]
Removing this from the milestone and setting to draft due to it requiring more work and having conflicting files. When it is ready to be tested again, we can consider it for including in a future release.

**Comment by RCheesley** [comment]
@fedys @escopecz if this is still required, are you able to pick it up again? Otherwise let's close the PR.

**Comment by mabumusa1** [comment]
@RCheesley I do not think this relevant to Symfony mailer.

**Comment by escopecz** [comment]
Unfortunately, this is dependency for other PRs like https://github.com/mautic/mautic/pull/10846. So if we want other PRs from Acquia, we must merge this one.

**Comment by escopecz** [comment]
This PR took quite a lot of work to make it work with M5. Luckily, there are many tests from the mailer refactoring and I added some more. It took some refactoring to make all the tests pass.

**Review by escopecz — DISMISSED** [review]
I reviewed the code again after my changes. I see no issues. A functional test added shows that the tokens are being replaced.

**Review by volha-pivavarchyk — COMMENTED** [review]
It works the following way for me:

When the custom field and owner are set:
1. With a token as the advanced tab's from email and mailer is owner enabled - **the owner's email is used**
2. With a token as the advanced tab's from email and mailer is owner disabled - **the custom field is used**
3. With a normal email address as the advanced tab's from email and mailer is owner enabled - **the owner's email  is used**
4. With a normal email address as the advanced tab's from email and mailer is owner disabled - **the normal email is used**
5. Nothing in the advanced tab's from email and mailer is owner enabled - **the owner's email is used**
6. Nothing in the advanced tab's from email and mailer is owner disabled - **the system email is used**


A custom field is null, owner is set up:
1. With a token as the advanced tab's from email and mailer is owner enabled - **the owner's email is used**
2. With a token as the advanced tab's from email and mailer is owner disabled - **the system email is used** <<< **I think it works by a wrong way. The owner's email should be used.**
3. With a normal email address as the advanced tab's from email and mailer is owner enabled - **the owner's email is used**
4. With a normal email address as the advanced tab's from email and mailer is owner disabled - **the normal email is used**


I got an issue. If there are two or more contacts in a segment, the email of the first contact's custom field is used for all. E.g. if the value of the first contact custom field is `test@test.com`, then the email of all contacts will be `test@test.com`. If no email is set, then the system email will be used for all contacts.

**Comment by dadarya0** [comment]
@escopecz  I have also tested same it is not working as expected.
If there are two or more contacts in a segment, the email of the first contact's custom field is used for all. E.g. if the value of the first contact custom field is test@test.com, then the email of all contacts will be test@test.com.

**Comment by kuzmany** [comment]
@escopecz should we close it favor to https://github.com/mautic/mautic/pull/13241 ?

**Comment by escopecz** [comment]
I'll use this PR and close 13241

**Review by fedys — APPROVED** [review]
Thanks @escopecz!

**Review by dongilbert — APPROVED** [review]

**Comment by RCheesley** [comment]
The docs were lost in the mists of time so I have created https://github.com/mautic/user-documentation/pull/264.

**Pull request merged**
