### PR TITLE
Fix for Amazon API transport return-path when sending emails immediately

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 4.x
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Email messages sent immediately through Amazon SES API do not include the return-path property.  Custom return path (bounce) address works fine when email is sent through queue.

This PR also includes minor `AmazonApiTransport` and `AmazonApiTransportTest` code cleanup (types declaration, comment fixes, unnecessary statements removed, etc.).

#### Steps to test this PR:
1. Setup Mautic with `Amazon SES - API` email setting
2. Set `Custom return path (bounce) address`
3. Set `How should email be handled?` to `Send immediately`
4. Send email to contact that will bounce, using `From email` other than `Custom return path (bounce) address`
5. The Delivery Status Notification should be sent to `Custom return path (bounce) address`, not `From email`

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10474"></a>

### CODE REVIEW

**Review by mabumusa1 — DISMISSED** [review]
I reviewed the code, great improvments. I think this PR will make the transport better.

**Comment by RCheesley** [comment]
@patrykgruszka please could you fix the conflict? Thanks!

**Comment by mabumusa1** [comment]
> @patrykgruszka please could you fix the conflict? Thanks!

@RCheesley conflicts and tests are working as expected

**Review by kuzmany — DISMISSED** [review]

**Comment by kuzmany** [comment]
@escopecz are we able to merge it , even If small coverage on it?

**Comment by escopecz** [comment]
@patrykgruszka please revert the public and protected method signature changes. It is considered a BC change if some plugin extends the class it will break the plugin. It can be done for Mautic 5.0.

@kuzmany I would rather wait for Patryk to improve the code coverage than to force-merge it.

**Comment by patrykgruszka** [comment]
@escopecz good point, I have reverted those return types. There was one test missing after merge, the coverage should be good now.

**Comment by kuzmany** [comment]
Should commit after @escopecz  review. Move to 4.2.1

**Review by escopecz — DISMISSED** [review]
I see no problem in the code 👍

**Pull request merged**
