### PR TITLE
[UX] Change "Published" to "Active" in user settings and add a tooltip

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This update changes the user status label from “Published” to “Active” to eliminate ambiguity. Additionally, a tooltip is introduced to inform users that disabling this setting will prevent login access. This clarification ensures users understand the implications of the status setting, enhancing the platform’s usability and user autonomy in managing access rights.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Users
3. Edit yourself
4. Look at the label

image

### CODE REVIEW

**Review by roboparker — APPROVED** [review]

**Review by patrykgruszka — APPROVED** [review]
Code looks good and the change makes sense 👍

**Review by Mike-Dropsolid — APPROVED** [review]
Makes sense to specify the generic "Publish" to fit its specific use.

**Comment by andersonjeccel** [comment]
User and dev docs ok!

**Comment by RCheesley** [comment]
https://github.com/mautic/user-documentation/pull/274 docs update here.

**Pull request merged**
