### PR TITLE
Focus preview even If website fetch url doesn't exist

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging for features or enhancements / 3.0 for bug fixes 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
PR https://github.com/mautic/mautic/pull/8894 rework the preview of Focus with iframe. It works properly, but preview display just If website url to fetch exists.
But in Mautic 2 preview works even If website URL not exists.
This is confusing for migrate instances from M2 to M3. 
This PR allow generate preview even If url does not exists.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create focus without URL. 
3. Check If preview is generated
4. Also check If preview is generated after re-open focus builder.

### CODE REVIEW

**Review by mabumusa1 — APPROVED** [review]
Tested the code locally, it worked as expected

**Review by dennisameling — APPROVED** [review]
Works as described

**Comment by nickveenhof** [comment]
Tried this but have not successfully been able to confirm this fixes anything. Could also be that it wasn't clear what it exactly fixes.

**Comment by dennisameling** [comment]
@nickveenhof 

- Create a new focus item
- Make sure you leave the "website" field empty:

image

- Open the Builder
- Select "display a notice" and select "modal". You'll notice that the preview screen on the left doesn't show anything:

image

- Checkout this PR 
- Try again, you should see the preview work correctly now:

image

**Pull request merged**
