### PR TITLE
Fixing Import custom email template functionality

### LINKED ISSUE #12296: Import custom email template broken
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

Custom email template no longer loads or renders in template editor box when a custom email template is imported.

### How can we reproduce this issue?

1:  Go to Contact page
2: Select a contact to send custom email
3: Click on Send Email on top of contact page
4: Select an email template from "Import from an existing template" drop down menu at bottom

After selecting an email template, the template will no longer load or render in Send Email editor box above in 4.4.8 

### Relevant log output

```shell
[2023-07-26 17:39:00] mautic.CRITICAL: Uncaught PHP Exception TypeError: "Mautic\CoreBundle\Helper\EmojiHelper::toEmoji(): Argument #1 ($text) must be of type string, null given, called in /var/www/html/app/bundles/EmailBundle/Helper/MailHelper.php on line 1355" at /var/www/html/app/bundles/CoreBundle/Helper/EmojiHelper.php line 23 {"exception":"[object] (TypeError(code: 0): Mautic\\CoreBundle\\Helper\\EmojiHelper::toEmoji(): Argument #1 ($text) must be of type string, null given, called in /var/www/html/app/bundles/EmailBundle/Helper/MailHelper.php on line 1355 at /var/www/html/app/bundles/CoreBundle/Helper/EmojiHelper.php:23)"} {"hostname":"mautic-web","pid":2813}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/121828554-import-custom-email-template-broken?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by shinde-rahul**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ✅ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #12296  

#### Description:

Custom email template no longer loads or renders in template editor box when a custom email template is imported.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a couple of emails (template type)
3. Go to the Contact page
4. Select a contact to send a custom email
5. Click on **Send Email** on top of contact page
6. Select an email template from the "Import from an existing template" drop-down menu at the bottom
7. After selecting an email template, the template will load or render in Send Email editor box above

Companion PR for Mautic 5: https://github.com/mautic/mautic/pull/12680

### CODE REVIEW

**Comment by RCheesley** [comment]
@shinde-rahul was there an accompanying PR for the 5.x branch for this fix?

**Review by volha-pivavarchyk — APPROVED** [review]
Works well

**Comment by RCheesley** [comment]
@shinde-rahul we can't merge this until there is a PR for the 5.x branch - can you make one please? Many thanks!

**Comment by shinde-rahul** [comment]
> @shinde-rahul we can't merge this until there is a PR for the 5.x branch - can you make one please? Many thanks!

@RCheesley Here you can find the PR #12680 against 5.x

**Comment by shinde-rahul** [comment]
> > @shinde-rahul we can't merge this until there is a PR for the 5.x branch - can you make one please? Many thanks!
> 
> @RCheesley Here you can find the PR #12680 against 5.x

@RCheesley, the 5.x PR is merged. And requested @escopecz to review it.

**Review by escopecz — APPROVED** [review]
This should be fine and already merged to M5 👍

**Pull request merged**
