### PR TITLE
Rss to email

### PR DESCRIPTION
**Pull request by npracht**
| Q  | A
| --- | ---
| Bug fix? | -
| New feature? | X
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/125
| Related developer documentation PR URL | -
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/1116 https://github.com/mautic/mautic/issues/1307 https://github.com/mautic/mautic/issues/1888
| BC breaks? | -
| Deprecations? | -

# This PR is not finished. Must be updated to finish it and make it compatible to current mautic version

#### Description:
RSS emails feature allows you to send automatic and recurrent emails generated from a RSS or ATOM feed to a selected segment(s). A great way to nurture your contacts automatically with the content published on your blog!

- Please refer to the user documentation: https://github.com/mautic/documentation/pull/125
- @webmecanik didn't have time to finish it and it was at the beginning of our work on **mautic in `v.1.3`**. We brought it today to the community in the view to do not waste it and let it being finished by community members.

## Still to do and context:
We had trouble to construct a correct architecture and finally it's a bit complex but understandable if we add the reason why.

**One of the expected feature by the marketer is to be sure that the automatically generated email does not contain a content already sent to the contact. We constructed a history snapshot of sent emails to be sure to never resend already sent content. Then instead of the number of feed items, you could send `all since last`**

Feel free to ask your questions to @Dcoutelle and @MaxWebmecanik.
### Still to do:

- [ ]  Add `all since last` field on RSS email setting instead of number of items and finish the work in the code.
- [ ]  Make beginning date mandatory
- [ ]  Bring it from `1.3` to `current version`

## Steps to test this PR:
1. Create a new email
2. Select RSS type
3. Fulfill info on right panel
4. Activate email
5. You can preview the content of the email
6. You'll receive the email within the set period

### CODE REVIEW

**Comment by SvetZitrka** [comment]
Are there any news regarding this extension?

**Comment by alanhartless** [comment]
@npracht It seems that this has not been able to pick up any steam with community devs and we don't have the capacity right now to work on it ourselves. So I'm going to close this PR for now as we're working through "cleaning house." If you want to drum up support for it from the community, try to get them to clone or checkout from your working branch.

**Comment by npracht** [comment]
Clear. It's a pity knowing that main of the work is done and it is requested by many users and a great competitive advantage...

N.

**Comment by mhamm777** [comment]
RSS-to-Email is a basic and much needed feature for Marketing professionals using Mautic.
Hope this gets delivered - Thanks!

**Comment by justlevine** [comment]
As requested [on the blog](https://www.mautic.org/community-blog/moving-feature-requests/), Ive moved this feature request over to the [forums](https://www.mautic.org/topic/rss-based-email-automation-feature-request/).

**Pull request closed without merging**
