### PR TITLE
Import selecting matched column multiple - bug fix  

### PR DESCRIPTION
**Pull request by arulrajsm28**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Issues addressed (#s or URLs) | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
When importing contacts you have to match the "colums" of your csv-file with the corresponding fields in mautic. Currently it is possible to select the same colum several times and therefore importing the same value out of you csv-file to different fields in mautic. 
This will help to prevent selecting same column several times.

#### Steps to test this PR:
1. Apply PR 
2. Navigate to contacts section
3. Click import 
4. upload valid csv file to import
5. select matched column in contact field 
6. check whether the already selected column is listed in other drop down in contact field

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Navigate to contacts section
2. Click import 
3. upload valid csv file to import
4. select same column in all contact field
5. it is possible to select the same matched column in all contact field

### CODE REVIEW

**Comment by alanhartless** [comment]
Hi! Can you describe the problem this PR is seeking to solve? What if a marketer _wanted_ to map the same CSV field to multiple Mautic fields?

**Comment by arulrajsm28** [comment]
i think it will avoid duplicated imports and also check whether all the colums out of your csv-file have been matched in mautic fields. There is possibility to make mistakes selecting multiple column when the column field is larger. If need to map same column to mautic field, can duplicate csv column.

**Comment by niklausmoser** [comment]
Exactly as @arulrajsm28 explained - it is sometimes tricky to check whether all the columns out of your .csv-file have been matched in Mautic fields. When updating the available fields in the .csv-file while mapping will help to ensures that all the values out of your .csv-file get imported.

**Comment by alanhartless** [comment]
But this blocks the ability to map the same CSV field to multiple Mautic fields which in some cases is useful. thoughts?

**Comment by niklausmoser** [comment]
@alanhartless - may I ask you to name one case in which it is useful to have the ability to map the same CSV field to multiple Mautic fields? I find it very tiring and error-prone if you have to figure out which fields are already mapped and which ones are not especially if you do an import which does not include all Mautic field (which is mostly the case). In the rare case you would need a multiple match, you could still change the CSV file accordingly (e.g. duplicate the requested field).

**Pull request closed without merging**
