### PR TITLE
Fix: Relative dates in segments don't work

### LINKED ISSUE #9636: Relative dates in segments don't work
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
If you specify "10 days ago" in the filter for a field with the date type, the exact date will be saved instead of the relative date.

At the same time, the filter by date with the value "today" or" yesterday" works correctly.

| Q   | A
| --- | ---
| Mautic version | 3.2.5
| PHP version | 7.2

### Steps to reproduce
1. Create a segment with a filter by the relative date "2 days ago" or "3 months ago" , etc.
2. Save and then go to edit the segment. Instead of a relative date, there will be an exact date and even a time
3. At first, the segment will work, but as soon as more than a relative date passes in time, contacts with an outdated date will not be deleted from the segment.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by shinde-rahul**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                |  3.2
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #9636 

#### Description:

Added new relative dates for segment filter,
- `'first day of '`
- `'last day of '`

#### Change log
- Updated DateOptionFactory to pick relative formats like "first day of " and "last day of "

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create a segment with a filter by the relative date "2 days ago" or "3 months ago", etc.
3. Save and then go to edit the segment. Instead of a relative date, there will be an exact date and even a time
4. At first, the segment will work, but as soon as more than a relative date passes in time, contacts with an outdated date will not be deleted from the segment.

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@shinde-rahul I think that your branch is out of date causing the tests to fail, please rebase on the Features branch?

**Comment by RCheesley** [comment]
I think that rebase should have sorted out the file that was in conflict 🤞

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@shinde-rahul looks like the tests are now passing but you will need to improve the automated test coverage before we can merge the PR. Are you OK to do that, or would you need any help?

**Comment by shinde-rahul** [comment]
> @shinde-rahul looks like the tests are now passing but you will need to improve the automated test coverage before we can merge the PR. Are you OK to do that, or would you need any help?

The following changes make code coverage happy, but I am not sure how the `isRelativeFormatsPresent` method is not being covered while this works as expected.
```
diff --git a/app/bundles/LeadBundle/Segment/Decorator/Date/DateOptionFactory.php b/app/bundles/LeadBundle/Segment/Decorator/Date/DateOptionFactory.php
index 46074194d..f73856956 100644
--- a/app/bundles/LeadBundle/Segment/Decorator/Date/DateOptionFactory.php
+++ b/app/bundles/LeadBundle/Segment/Decorator/Date/DateOptionFactory.php
@@ -109,7 +109,9 @@ class DateOptionFactory
             case $timeframe && (
                     false !== strpos($timeframe[0], '-') || // -5 days
                     false !== strpos($timeframe[0], '+') || // +5 days
-                    false !== $this->isRelativeFormatsPresent($timeframe)
+                    false !== strpos($timeframe, ' ago') || // 5 days ago
+                    false !== strpos($timeframe, 'first day of ') || // first day of January 2021
+                    false !== strpos($timeframe, 'last day of ') // last day of January 2021
                 ):
                 return new DateRelativeInterval($this->dateDecorator, $originalValue, $dateOptionParameters);
             default:
@@ -117,20 +119,4 @@ class DateOptionFactory
         }
     }
 
-    protected function isRelativeFormatsPresent($timeframe): bool
-    {
-        $notations = [
-            'first day of ', // first day of January 2021
-            'last day of ', // last day of January 2021
-            ' ago', // 5 days ago
-        ];
-
-        foreach ($notations as $notation) {
-            if (false !== strpos($timeframe, $notation)) {
-                return true;
-            }
-        }
-
-        return false;
-    }
 }
```

@RCheesley, will need some guidance to make it correct.

**Comment by shinde-rahul** [comment]
@RCheesley, updated coverage.

**Comment by npracht** [comment]
Hello @shinde-rahul ! I wanted to test your PR but your description and the title of the PR itself don't talk about the same thing. Can you modify title and/or description then I'm sure what to test ?

Thanks

**Comment by RCheesley** [comment]
@shinde-rahul I am struggling to test this with your PR applied. Here are the steps that I have taken:

1. Set a bunch of contacts to have a custom date/time field to use with the segment filter
2. Create a segment with a filter by the relative date "2 days ago" or "3 months ago", etc.
2. Save and then go to edit the segment. Instead of a relative date, there will be an exact date and even a time

✅  Reproduced this and can see that this saves a fixed date. Contacts matching that filter at that time are indeed added.

I applied the PR.

❌  I am still seeing a fixed date in the field, even if I create a new segment with the same information, a fixed date is saved.

❌  I tried changing the time of my machine and rebuilding the segment to see if it would bring in new contacts since there would now be more that fit in the range, but it did not - this would suggest that it is still saving a fixed date.

🙏  Some more detailed test instructions would go a long way to helping us reproduce the issue and test the PR thoroughly :)

**Review by alexhammerschmied — APPROVED** [review]
I tested this function in the last few days with "today", "x days ago", "in x days" and it works great.
The only thing missing is the "now" function. This is sill hard coding the current date and time into the database (but it was not the scope of this pr anyway).

I think we're good to go with that PR. Thank you @shinde-rahul :)

**Comment by shinde-rahul** [comment]
Thank you @alexhammerschmied.

**Comment by RCheesley** [comment]
@shinde-rahul I wondered if it was possible to give some more detailed test instructions? I tried to test this PR some time ago but was not able to see what I understood you suggest I would see in the segment.

Some clearer details on the *how* part of the testing would be really helpful so we can look at getting this merged.

**Comment by npracht** [comment]
@shinde-rahul can you please add user doc then we know what to test ?
Here --> https://github.com/mautic/mautic-documentation/blob/main/pages/12.contacts/03.manage-segments/docs.en.md?plain=1#L88

Thanks !

**Comment by RCheesley** [comment]
@shinde-rahul could you please rebase to the 4.1 branch? Thanks!

**Comment by shinde-rahul** [comment]
Sure.

**Comment by RCheesley** [comment]
Final milestone bump before closing the PR, please address the issues that are mentioned above so we can look at merging this PR with the 4.2 release on 21st February @shinde-rahul.

**Comment by shinde-rahul** [comment]
@RCheesley, the steps are not helping reproduce, but the changes are needed for relative dates.
While re-creating fork, all the branches got deleted; this is PR with no branch. The followings are the todos I'll be working on,

- [x] Creating a new branch based on the 4.1.
- [x] Updating the document https://github.com/mautic/mautic-documentation/blob/main/pages/12.contacts/03.manage-segments/docs.en.md?plain=1#L88 and adding reference of it on new PR
- [x] Closing this PR after the new branch

**Comment by kuzmany** [comment]
Does it not goal of this string date options  stay at string and then replace during the segment build? 
I mean If I use tomorrow , it will still check date of field to tomorrow date time.

image

In your case is 2 days ago replace to date time , what is not correct to me


image

**Comment by shinde-rahul** [comment]
> @RCheesley, the steps are not helping reproduce, but the changes are needed for relative dates. While re-creating fork, all the branches got deleted; this is PR with no branch. The followings are the todos I'll be working on,
> 
> * [x]  Creating a new branch based on the 4.1.
> * [x]  Updating the document https://github.com/mautic/mautic-documentation/blob/main/pages/12.contacts/03.manage-segments/docs.en.md?plain=1#L88 and adding reference of it on new PR
> * [x]  Closing this PR after the new branch

@RCheesley, Find the new PR here https://github.com/mautic/mautic/pull/10822 with new branch and documentation PR https://github.com/mautic/mautic-documentation/pull/289.

**Comment by shinde-rahul** [comment]
> Does it not goal of this string date options stay at string and then replace during the segment build? I mean If I use tomorrow , it will still check date of field to tomorrow date time.
> 
> image
> 
> In your case is 2 days ago replace to date time , what is not correct to me
> 
> image

@kuzmany, 
I have created a segment with two filters, please find the screenshot,
Screenshot 2022-02-03 at 10 47 18 AM
Then ran the `bin/console m:s:u`, it updated the segment with contacts, and when editing the segment it stays the same above image.
Am I missing something?

Please help me re-produce the same.

**Comment by RCheesley** [comment]
OK closing this PR in favour of the updated PR here: https://github.com/mautic/mautic/pull/10822

**Pull request closed without merging**
