### PR TITLE
Fixing Undefined project root

### LINKED ISSUE #12874: Many problems after update to Mautic 5
### Mautic Version

5.0.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

After update to Mautic 5, the focus and campaign is not working.

### What happened?

focus links is show error 500 and in log there is this error message:
[2023-11-06 22:30:24] mautic.WARNING: PHP Warning - Undefined variable $projectRoot - in file xxxx/app/config/paths.php - at line 15 [] {"hostname":"debian","pid":139689}

CAMPAIGN: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'e0_.body_text' in 'field list' [] {"hostname":"debian","pid":141488}

### How can we reproduce this issue?

Step 1: create a new focus and go to link /focus/1.js (change id)
image

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [y]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/issues/12874

#### Description:

Is there some reason why we have to define `$root` and `$projectRoot` in the `app/config/paths.php` file instead of creating them there? It seems it's not defined everywhere it's included.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Not sure how to reproduce it, just trying to resolve https://github.com/mautic/mautic/issues/12874

### CODE REVIEW

**Review by Tie-fighter — COMMENTED** [review]
I added these two lines in my broken production, because I was receiving this:

```
2024/01/11 10:06:33 [error] 13580#13580: *258 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $projectRoot in /var/www/mautic/app/config/paths.php on 
line 15" while reading response header from upstream, client: 84.115.223.241, server: mautic.section8.eu, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "[redacted]"
```

After adding these two lines, the error message above disappeared, but a new one appeared in mautic prod logs:

So I am not sure if this is a new problem or the fix is incomplete.

```
[2024-01-11 14:53:02] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Cannot rename "/tmp/url_matching_routes.phpHxF3Bv" to "/var/www/mautic/var/cache/prod/url_matching_routes.php": rename(/tmp/url_matching_routes.phpHxF3Bv,/var/www/mautic/var/cache/prod/url_matching_routes.php): Permission denied" at /var/www/mautic/vendor/symfony/filesystem/Filesystem.php line 305 {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Cannot rename \"/tmp/url_matching_routes.phpHxF3Bv\" to \"/var/www/mautic/var/cache/prod/url_matching_routes.php\": rename(/tmp/url_matching_routes.phpHxF3Bv,/var/www/mautic/var/cache/prod/url_matching_routes.php): Permission denied at /var/www/mautic/vendor/symfony/filesystem/Filesystem.php:305)"} {"hostname":"[redacted]","pid":59709}
[2024-01-11 14:53:02] mautic.CRITICAL: Exception thrown when handling an exception (Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("Cannot rename "/tmp/url_generating_routes.phpHJBMsg" to "/var/www/mautic/var/cache/prod/url_generating_routes.php": rename(/tmp/url_generating_routes.phpHJBMsg,/var/www/mautic/var/cache/prod/url_generating_routes.php): Permission denied"). at /var/www/mautic/app/bundles/CoreBundle/Resources/views/Default/script.html.twig line 5) {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Cannot rename \"/tmp/url_generating_routes.phpHJBMsg\" to \"/var/www/mautic/var/cache/prod/url_generating_routes.php\": rename(/tmp/url_generating_routes.phpHJBMsg,/var/www/mautic/var/cache/prod/url_generating_routes.php): Permission denied\"). at /var/www/mautic/app/bundles/CoreBundle/Resources/views/Default/script.html.twig:5, Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Cannot rename \"/tmp/url_generating_routes.phpHJBMsg\" to \"/var/www/mautic/var/cache/prod/url_generating_routes.php\": rename(/tmp/url_generating_routes.phpHJBMsg,/var/www/mautic/var/cache/prod/url_generating_routes.php): Permission denied at /var/www/mautic/vendor/symfony/filesystem/Filesystem.php:305)"} {"hostname":"[redacted]","pid":59709}
[2024-01-11 14:53:02] mautic.ERROR: Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("Cannot rename "/tmp/url_generating_routes.phpHJBMsg" to "/var/www/mautic/var/cache/prod/url_generating_routes.php": rename(/tmp/url_generating_routes.phpHJBMsg,/var/www/mautic/var/cache/prod/url_generating_routes.php): Permission denied"). - in file /var/www/mautic/app/bundles/CoreBundle/Resources/views/Default/script.html.twig - at line 5 [] {"hostname":"[redacted]","pid":59709}
```

**Comment by Tie-fighter** [comment]
Running `rm -rf var/cache/*` fixed the follow up issue.
Thank you @escopecz for the great support!

**Review by Tie-fighter — APPROVED** [review]
After adding these two lines and running `rm -rf var/cache/*` everything seems to be working again on my broken production.

**Comment by saenzramiro** [comment]
Solved! 👏🏼

**Review by mollux — APPROVED** [review]
as discussed changes make sense

**Pull request merged**
