### PR TITLE
[type-declarations] Add known return void types in Notification bundle

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
No issue found 👍

**Comment by escopecz** [comment]
@TomasVotruba the CI is failing. Please take a look.

**Comment by TomasVotruba** [comment]
I'm on it :+1:

**Comment by TomasVotruba** [comment]
Just rebased and fixed :+1: should be ok and ready to merge 

Gotta run for lunch now :runner:

**Review by kuzmany — DISMISSED** [review]
Well done 👍

**Comment by escopecz** [comment]
There is still one PHPSTAN issue

**Comment by TomasVotruba** [comment]
Good to go now :+1:

**Review by escopecz — APPROVED** [review]
Thank you! 👍

**Pull request merged**
