### PR TITLE
Update app/bundles/CoreBundle/Views/Helper/theme_select.html.php

### PR DESCRIPTION
**Pull request by moskoweb**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.2| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | 
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This is a Mautic3 version of #6860.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2.

### CODE REVIEW

**Comment by RCheesley** [comment]
Hi @moskoweb thanks for the PR! You'll need to sign the contributors agreement before we can accept any of your PR's, could you do that please?

Is this PR meant to be instead of #6860? I wasn't quite sure why it was in the bc breaks row on the table above. Let me know and we can close that PR if appropriate.

**Comment by moskoweb** [comment]
@RCheesley it would be to change the pull to Mautic 3, instead of the 2 that was.

**Comment by RCheesley** [comment]
@moskoweb ok thank you for the explanation!

**Review by sPradella — COMMENTED** [review]
Something doesn't fit yet. The title goes beyond the field
Bildschirmfoto 2020-10-08 um 12 03 46

**Comment by RCheesley** [comment]
@cla-bot check

**Review by escopecz — DISMISSED** [review]
I've rebased this as I'd have to downgrade PHP to test it on my local. Also implemented the code to cover [Alan's comment](https://github.com/mautic/mautic/pull/6860#issuecomment-459121132)

**Comment by npracht** [comment]
@moskoweb can you sign the contributor agreement please?

**Comment by moskoweb** [comment]
Hello, I could check again, why the email is already signed.

**Comment by moskoweb** [comment]
@cla-bot check

**Comment by npracht** [comment]
@RCheesley can you check in CLA history if we have something ? Obviously @moskoweb signed it.
We could merge it then :)

**Comment by RCheesley** [comment]
The issue is that the Git commit was incorrectly signed without the appropriate details so the bot is unable to detect the email address. If the username is in the CLA bot list we are ok to merge using the admin override.

**Pull request closed without merging**
