### PR TITLE
feat[DPMMA-2324]: Correct integration plugin dependencies

### PR DESCRIPTION
**Pull request by tomekkowalczyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [yes ]
| New feature/enhancement? (use the a.x branch)      | [ no]
| Deprecations?                          | [ no]
| BC breaks? (use the c.x branch)        | [ no]
| Automated tests included?              | [ no] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
When creating an integration plugin and running the action as a step of the "push to integration" campaign, I encountered a problem related to the lack of the integrationHelper object in the PluginBundle/EventListener/PushToIntegrationTrait.php file. Services were removed when updating to version 5.x. They were removed

image

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by escopecz** [comment]
@tomekkowalczyk why do you need the subscribers to be defined in the `config.php` file? Those are autowired and autoconfigured.

Can you share the full error and trace and steps to reproduce?

**Comment by patrykgruszka** [comment]
Steps to reproduce:
1. Open this PR on Gitpod or your local instance
2. Enable any plugin that adds the Push To Integration action. For example vTiger, you can fake credentials just to reproduce this autowiring issue. 
image
3. Create campaign with Push to Integration action.
image
4. Build the campaign `ddev exec php bin/console mautic:campaigns:update `
5. Run the campaign `ddev exec php bin/console mautic:campaigns:trigger `

The last command should result in an error:
```
Error: Call to a member function getIntegrationObjects() on null (uncaught exception) at /var/www/html/app/bundles/PluginBundle/EventListener/PushToIntegrationTrait.php line 52 while running console command `mautic:campaigns:trigger`
[stack trace]
#0 /var/www/html/app/bundles/PluginBundle/EventListener/PushToIntegrationTrait.php(40): Mautic\PluginBundle\EventListener\CampaignSubscriber::pushIt(Array, Object(Mautic\LeadBundle\Entity\Lead), Array)
#1 /var/www/html/app/bundles/PluginBundle/EventListener/CampaignSubscriber.php(44): Mautic\PluginBundle\EventListener\CampaignSubscriber->pushToIntegration(Array, Object(Mautic\LeadBundle\Entity\Lead), Array)
#2 /var/www/html/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(118): Mautic\PluginBundle\EventListener\CampaignSubscriber->onCampaignTriggerAction(Object(Mautic\CampaignBundle\Event\CampaignExecutionEvent), 'mautic.plugin.o...', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#3 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Mautic\CampaignBundle\Event\CampaignExecutionEvent), 'mautic.plugin.o...', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#4 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'mautic.plugin.o...', Object(Mautic\CampaignBundle\Event\CampaignExecutionEvent))
#5 /var/www/html/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(154): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Mautic\CampaignBundle\Event\CampaignExecutionEvent), 'mautic.plugin.o...')
#6 /var/www/html/app/bundles/CampaignBundle/Executioner/Dispatcher/LegacyEventDispatcher.php(165): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(Object(Mautic\CampaignBundle\Event\CampaignExecutionEvent), 'mautic.plugin.o...')
#7 /var/www/html/app/bundles/CampaignBundle/Executioner/Dispatcher/LegacyEventDispatcher.php(63): Mautic\CampaignBundle\Executioner\Dispatcher\LegacyEventDispatcher->dispatchEventName('mautic.plugin.o...', Array, Object(Mautic\CampaignBundle\Entity\LeadEventLog))
#8 /var/www/html/app/bundles/CampaignBundle/Executioner/Dispatcher/ActionDispatcher.php(64): Mautic\CampaignBundle\Executioner\Dispatcher\LegacyEventDispatcher->dispatchCustomEvent(Object(Mautic\CampaignBundle\EventCollector\Accessor\Event\ActionAccessor), Object(Doctrine\Common\Collections\ArrayCollection), NULL, Object(Mautic\CampaignBundle\Event\PendingEvent))
#9 /var/www/html/app/bundles/CampaignBundle/Executioner/Event/ActionExecutioner.php(46): Mautic\CampaignBundle\Executioner\Dispatcher\ActionDispatcher->dispatchEvent(Object(Mautic\CampaignBundle\EventCollector\Accessor\Event\ActionAccessor), Object(Mautic\CampaignBundle\Entity\Event), Object(Doctrine\Common\Collections\ArrayCollection))
#10 /var/www/html/app/bundles/CampaignBundle/Executioner/EventExecutioner.php(127): Mautic\CampaignBundle\Executioner\Event\ActionExecutioner->execute(Object(Mautic\CampaignBundle\EventCollector\Accessor\Event\ActionAccessor), Object(Doctrine\Common\Collections\ArrayCollection))
#11 /var/www/html/app/bundles/CampaignBundle/Executioner/EventExecutioner.php(98): Mautic\CampaignBundle\Executioner\EventExecutioner->executeLogs(Object(Mautic\CampaignBundle\Entity\Event), Object(Doctrine\Common\Collections\ArrayCollection), Object(Mautic\CampaignBundle\Executioner\Result\Counter))
#12 /var/www/html/app/bundles/CampaignBundle/Executioner/EventExecutioner.php(169): Mautic\CampaignBundle\Executioner\EventExecutioner->executeForContacts(Object(Mautic\CampaignBundle\Entity\Event), Object(Doctrine\Common\Collections\ArrayCollection), Object(Mautic\CampaignBundle\Executioner\Result\Counter), false)
#13 /var/www/html/app/bundles/CampaignBundle/Executioner/KickoffExecutioner.php(159): Mautic\CampaignBundle\Executioner\EventExecutioner->executeEventsForContacts(Object(Doctrine\Common\Collections\ArrayCollection), Object(Doctrine\Common\Collections\ArrayCollection), Object(Mautic\CampaignBundle\Executioner\Result\Counter))
#14 /var/www/html/app/bundles/CampaignBundle/Executioner/KickoffExecutioner.php(60): Mautic\CampaignBundle\Executioner\KickoffExecutioner->executeOrScheduleEvent()
#15 /var/www/html/app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php(332): Mautic\CampaignBundle\Executioner\KickoffExecutioner->execute(Object(Mautic\CampaignBundle\Entity\Campaign), Object(Mautic\CampaignBundle\Executioner\ContactFinder\Limiter\ContactLimiter), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php(285): Mautic\CampaignBundle\Command\TriggerCampaignCommand->executeKickoff()
#17 /var/www/html/app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php(234): Mautic\CampaignBundle\Command\TriggerCampaignCommand->triggerCampaign(Object(Mautic\CampaignBundle\Entity\Campaign))
#18 /var/www/html/vendor/symfony/console/Command/Command.php(298): Mautic\CampaignBundle\Command\TriggerCampaignCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Mautic\CampaignBundle\Command\TriggerCampaignCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Mautic\CampaignBundle\Command\TriggerCampaignCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/bin/console(16): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main} ["hostname" => "mautic-web","pid" => 4255]
10:07:45 CRITICAL  [console] Error thrown while running command "mautic:campaigns:trigger --campaign-limit=1". Message: "Call to a member function getIntegrationObjects() on null" ["exception" => Error { …},"command" => "mautic:campaigns:trigger --campaign-limit=1","message" => "Call to a member function getIntegrationObjects() on null"] ["hostname" => "mautic-web","pid" => 4255]
10:07:45 WARNING   [mautic] Command `mautic:campaigns:trigger` exited with status code 1 ["hostname" => "mautic-web","pid" => 4255]
```

**Review by patrykgruszka — APPROVED** [review]
The autowiring mechanism fails to set the static property of the trait. Calling the `setIntegration` method explicitly fixes this issue. I could not find a better way to initialize the IntegrationHelper without making a BC.

**Comment by escopecz** [comment]
Please use the services.php file instead of config.php file for defining special cases of services that the autowiring does not cover. See https://symfony.com/doc/current/service_container/calls.html

From the example:
```php
$services->set(MessageGenerator::class)
        ->call('setLogger', [service('logger')]);
```
it should be simple to get it working.

**Comment by patrykgruszka** [comment]
@escopecz I've made the changes in #13470. @tomekkowalczyk we can close this PR.

**Comment by escopecz** [comment]
Closing in favore of https://github.com/mautic/mautic/pull/13470

**Pull request closed without merging**
