### PR TITLE
Fixed API inconsistencies

### PR DESCRIPTION
**Pull request by mqueme**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
When creating a new contact through the api, a boolean value of 'True', 'Yes', 'On' or anything that would compute to true or false other than 1 or 0 would give an error. But when updating these values where taken as valid. This PR will now allow these values when creating new contacts through the API.
[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. create a new contact through the API with a boolean value of True. this will error
2. update an existing contact through the API with a boolean value of True this is valid

#### Steps to test this PR:
1. Apply PR and follow steps 1 and 2 above
2. Both cases will be valid

### CODE REVIEW

**Comment by Gregy** [comment]
I don't like supporting anything else then json true/false for boolean fields. Why is it needed? 

If we really want to support other values then we need to strictly define what values will be accepted and reject all others. For example right now this PR accepts value "enabled" but converts it to false which is very confusing. I would expect error to be thrown instead of bad interpretation.

**Comment by mqueme** [comment]
@Gregy acording to php documentation: Returns TRUE for "1", "true", "on" and "yes". Returns FALSE otherwise.

**Comment by Gregy** [comment]
My point still stands. If we really want to support multiple different aliases for booleans (which I think is a bad idea) then we need to only accept the ones we define and refuse all others. Otherwise hidden bugs and bad surprises are bound to happen.

**Comment by alanhartless** [comment]
Some people aren't posting JSON so TRUE will come as a string not a boolean. So we still need to use it. But, @mqueme, that code was added because Symfony forms had an issue with either false or true values. Test that you can toggle true to false and false to true through the API and that it sticks.

**Comment by mqueme** [comment]
then add the exception when editing as well. which we don't at the moment.

**Comment by mqueme** [comment]
@alanhartless yes it does stick. both through the API and through the UI.

**Comment by alanhartless** [comment]
With these changes, I can't update from false to true for a boolean field when using PATCH.

**Comment by escopecz** [comment]
Yup, it's failing this test: https://github.com/mautic/api-library/blob/master/tests/Api/ContactFieldsTest.php#L52

**Comment by dongilbert** [comment]
+1

**Pull request merged**
