### PR TITLE
Fix property must not be accessed before initialization error

### PR DESCRIPTION
**Pull request by tejasync**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✅ 
| New feature/enhancement? (use the a.x branch)      | ❌ 
| Deprecations?                          | ❌ 
| BC breaks? (use the c.x branch)        | ❌ 
| Automated tests included?              | ❌  
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes Custom Objects Imports 

#### Description:

Since PHP 7.4 introduces type-hinting for properties, it is particularly important to provide valid values for all properties, so that all properties have values that match their declared types.

A property that has never been assigned doesn't have a null value, but it is on an uninitialized (undefined) state, which will never match any declared type (undefined !== null).

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create custom object with some fields
3. Now, try to import a CSV with relevant fields for custom objects
4. Observe the "Property must not be accessed before initialization error" message in the logs before the PR is applied
5. After PR, you should be able to import CSV for custom objects 

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11388"></a>

### CODE REVIEW

**Review by jos0405 — DISMISSED** [review]
This PR solves the bug, amazing.
image

**Comment by jos0405** [comment]
Can we merge it into M4 next bugfix release maybe?

**Comment by RCheesley** [comment]
Yep - just needs a code review and one more test :)

**Comment by escopecz** [comment]
@ts-navghane can you please rebase this on the 4.4 branch so it can go into 4.4.2 release since this is a bug fix and we know that M5 release won't be soon?

**Review by escopecz — DISMISSED** [review]
The code change makes sense. Thanks Tejas! 👍

**Review by kuzmany — APPROVED** [review]

**Pull request merged**
