### PR TITLE
Add support to check duplicates for api/companies/batch/new

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description: 

This PR enabled check unique identified fields for company API create/ and batch create endpoint.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create batch API  with any combination of unique fields

`POST api/companies/batch/new`

```
[
    {
        "companyname": "test",
        "custom_company_field": "x2"
    },
    {
        "companyname": "test2",
        "custom_company_field": "x1"
    }
]
```
3. Run it again. It should not create new companies, because API now detect duplicate companies

### CODE REVIEW

**Comment by RCheesley** [comment]
Conflict to be resolved here @kuzmany

**Comment by kuzmany** [comment]
@RCheesley Conflicts resolved

**Comment by RCheesley** [comment]
Awesome thanks for getting on that so fast! Added it to the OSF board! 🚀

**Review by volha-pivavarchyk — APPROVED** [review]
Works well as described.

**Comment by RCheesley** [comment]
There's a conflict to address here but should be a quick one to test afterwards - thanks for the test instructions @kuzmany 🚀

**Comment by abhisekmazumdar** [comment]
I feel this PR is not relevant anymore as now in 5.x all the entities are always checking for duplicates or existing entities. That's my understanding.

Upon doing some curl request I see the following with these changes:

```shell
curl -X POST https://mautic.ddev.site/api/companies/batch/new \
--header 'Authorization: Basic YWRtaW46TWF1dDFjUjBja3Mh' \
-H "Content-Type: application/json" \
-d '[
    {
        "companyname": "test",
        "custom_company_field": "x2"
    },
    {
        "companyname": "test2",
        "custom_company_field": "x1"
    }
]'
{"companies":[{"id":1,"score":0,"fields":{"core":{"companyaddress1":{"id":"29","label":"Address 1","alias":"companyaddress1","type":"text","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""},"companyaddress2":{"id":"30","label":"Address 2","alias":"companyaddress2","type":"text","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""},"companyemail":{"id":"31","label":"Company Email","alias":"companyemail","type":"email","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""},"companyphone":{"id":"32","label":"Phone","alias":"companyphone","type":"tel","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""},"companycity":{"id":"33","label":"City","alias":"companycity","type":"text","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""},"companystate":{"id":"34","label":"State","alias":"companystate","type":"region","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""},"companyzipcode":{"id":"35","label":"Zip Code","alias":"companyzipcode","type":"text","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""},"companycountry":{"id":"36","label":"Country","alias":"companycountry","type":"country","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""},"companyname":{"id":"37","label":"Company Name","alias":"companyname","type":"text","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":"test","normalizedValue":"test"},"companywebsite":{"id":"38","label":"Website","alias":"companywebsite","type":"url","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""}},"professional":{"companynumber_of_employees":{"id":"39","label":"Number of Employees","alias":"companynumber_of_employees","type":"number","group":"professional","object":"company","is_fixed":"0","properties":"a:2:{s:9:\"roundmode\";i:4;s:5:\"scale\";i:0;}","default_value":null,"value":null,"normalizedValue":""},"companyfax":{"id":"40","label":"Fax","alias":"companyfax","type":"tel","group":"professional","object":"company","is_fixed":"0","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""},"companyannual_revenue":{"id":"41","label":"Annual Revenue","alias":"companyannual_revenue","type":"number","group":"professional","object":"company","is_fixed":"0","properties":"a:2:{s:9:\"roundmode\";i:4;s:5:\"scale\";i:2;}","default_value":null,"value":null,"normalizedValue":""},"companyindustry":{"id":"42","label":"Industry","alias":"companyindustry","type":"select","group":"professional","object":"company","is_fixed":"1","properties":"a:1:{s:4:\"list\";a:41:{i:0;a:2:{s:5:\"label\";s:19:\"Aerospace & Defense\";s:5:\"value\";s:19:\"Aerospace & Defense\";}i:1;a:2:{s:5:\"label\";s:11:\"Agriculture\";s:5:\"value\";s:11:\"Agriculture\";}i:2;a:2:{s:5:\"label\";s:7:\"Apparel\";s:5:\"value\";s:7:\"Apparel\";}i:3;a:2:{s:5:\"label\";s:21:\"Automotive & Assembly\";s:5:\"value\";s:21:\"Automotive & Assembly\";}i:4;a:2:{s:5:\"label\";s:7:\"Banking\";s:5:\"value\";s:7:\"Banking\";}i:5;a:2:{s:5:\"label\";s:13:\"Biotechnology\";s:5:\"value\";s:13:\"Biotechnology\";}i:6;a:2:{s:5:\"label\";s:9:\"Chemicals\";s:5:\"value\";s:9:\"Chemicals\";}i:7;a:2:{s:5:\"label\";s:14:\"Communications\";s:5:\"value\";s:14:\"Communications\";}i:8;a:2:{s:5:\"label\";s:12:\"Construction\";s:5:\"value\";s:12:\"Construction\";}i:9;a:2:{s:5:\"label\";s:23:\"Consumer Packaged Goods\";s:5:\"value\";s:23:\"Consumer Packaged Goods\";}i:10;a:2:{s:5:\"label\";s:9:\"Education\";s:5:\"value\";s:9:\"Education\";}i:11;a:2:{s:5:\"label\";s:11:\"Electronics\";s:5:\"value\";s:11:\"Electronics\";}i:12;a:2:{s:5:\"label\";s:6:\"Energy\";s:5:\"value\";s:6:\"Energy\";}i:13;a:2:{s:5:\"label\";s:11:\"Engineering\";s:5:\"value\";s:11:\"Engineering\";}i:14;a:2:{s:5:\"label\";s:13:\"Entertainment\";s:5:\"value\";s:13:\"Entertainment\";}i:15;a:2:{s:5:\"label\";s:13:\"Environmental\";s:5:\"value\";s:13:\"Environmental\";}i:16;a:2:{s:5:\"label\";s:7:\"Finance\";s:5:\"value\";s:7:\"Finance\";}i:17;a:2:{s:5:\"label\";s:15:\"Food & Beverage\";s:5:\"value\";s:15:\"Food & Beverage\";}i:18;a:2:{s:5:\"label\";s:10:\"Government\";s:5:\"value\";s:10:\"Government\";}i:19;a:2:{s:5:\"label\";s:10:\"Healthcare\";s:5:\"value\";s:10:\"Healthcare\";}i:20;a:2:{s:5:\"label\";s:11:\"Hospitality\";s:5:\"value\";s:11:\"Hospitality\";}i:21;a:2:{s:5:\"label\";s:9:\"Insurance\";s:5:\"value\";s:9:\"Insurance\";}i:22;a:2:{s:5:\"label\";s:9:\"Machinery\";s:5:\"value\";s:9:\"Machinery\";}i:23;a:2:{s:5:\"label\";s:13:\"Manufacturing\";s:5:\"value\";s:13:\"Manufacturing\";}i:24;a:2:{s:5:\"label\";s:5:\"Media\";s:5:\"value\";s:5:\"Media\";}i:25;a:2:{s:5:\"label\";s:15:\"Metals & Mining\";s:5:\"value\";s:15:\"Metals & Mining\";}i:26;a:2:{s:5:\"label\";s:14:\"Not for Profit\";s:5:\"value\";s:14:\"Not for Profit\";}i:27;a:2:{s:5:\"label\";s:9:\"Oil & Gas\";s:5:\"value\";s:9:\"Oil & Gas\";}i:28;a:2:{s:5:\"label\";s:17:\"Packaging & Paper\";s:5:\"value\";s:17:\"Packaging & Paper\";}i:29;a:2:{s:5:\"label\";s:36:\"Private Equity & Principal Investors\";s:5:\"value\";s:36:\"Private Equity & Principal Investors\";}i:30;a:2:{s:5:\"label\";s:10:\"Recreation\";s:5:\"value\";s:10:\"Recreation\";}i:31;a:2:{s:5:\"label\";s:11:\"Real Estate\";s:5:\"value\";s:11:\"Real Estate\";}i:32;a:2:{s:5:\"label\";s:6:\"Retail\";s:5:\"value\";s:6:\"Retail\";}i:33;a:2:{s:5:\"label\";s:14:\"Semiconductors\";s:5:\"value\";s:14:\"Semiconductors\";}i:34;a:2:{s:5:\"label\";s:8:\"Shipping\";s:5:\"value\";s:8:\"Shipping\";}i:35;a:2:{s:5:\"label\";s:13:\"Social Sector\";s:5:\"value\";s:13:\"Social Sector\";}i:36;a:2:{s:5:\"label\";s:10:\"Technology\";s:5:\"value\";s:10:\"Technology\";}i:37;a:2:{s:5:\"label\";s:18:\"Telecommunications\";s:5:\"value\";s:18:\"Telecommunications\";}i:38;a:2:{s:5:\"label\";s:14:\"Transportation\";s:5:\"value\";s:14:\"Transportation\";}i:39;a:2:{s:5:\"label\";s:9:\"Utilities\";s:5:\"value\";s:9:\"Utilities\";}i:40;a:2:{s:5:\"label\";s:5:\"Other\";s:5:\"value\";s:5:\"Other\";}}}","default_value":null,"value":null,"normalizedValue":""},"companydescription":{"id":"43","label":"Description","alias":"companydescription","type":"text","group":"professional","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""}},"other":[],"all":{"id":1,"companyaddress1":null,"companyaddress2":null,"companyemail":null,"companyphone":null,"companycity":null,"companystate":null,"companyzipcode":null,"companycountry":null,"companyname":"test","companywebsite":null,"companynumber_of_employees":null,"companyfax":null,"companyannual_revenue":null,"companyindustry":null,"companydescription":null}}},{"id":3,"score":0,"fields":{"core":{"companyaddress1":{"id":"29","label":"Address 1","alias":"companyaddress1","type":"text","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""},"companyaddress2":{"id":"30","label":"Address 2","alias":"companyaddress2","type":"text","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""},"companyemail":{"id":"31","label":"Company Email","alias":"companyemail","type":"email","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""},"companyphone":{"id":"32","label":"Phone","alias":"companyphone","type":"tel","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""},"companycity":{"id":"33","label":"City","alias":"companycity","type":"text","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""},"companystate":{"id":"34","label":"State","alias":"companystate","type":"region","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""},"companyzipcode":{"id":"35","label":"Zip Code","alias":"companyzipcode","type":"text","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""},"companycountry":{"id":"36","label":"Country","alias":"companycountry","type":"country","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""},"companyname":{"id":"37","label":"Company Name","alias":"companyname","type":"text","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":"test2","normalizedValue":"test2"},"companywebsite":{"id":"38","label":"Website","alias":"companywebsite","type":"url","group":"core","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""}},"professional":{"companynumber_of_employees":{"id":"39","label":"Number of Employees","alias":"companynumber_of_employees","type":"number","group":"professional","object":"company","is_fixed":"0","properties":"a:2:{s:9:\"roundmode\";i:4;s:5:\"scale\";i:0;}","default_value":null,"value":null,"normalizedValue":""},"companyfax":{"id":"40","label":"Fax","alias":"companyfax","type":"tel","group":"professional","object":"company","is_fixed":"0","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""},"companyannual_revenue":{"id":"41","label":"Annual Revenue","alias":"companyannual_revenue","type":"number","group":"professional","object":"company","is_fixed":"0","properties":"a:2:{s:9:\"roundmode\";i:4;s:5:\"scale\";i:2;}","default_value":null,"value":null,"normalizedValue":""},"companyindustry":{"id":"42","label":"Industry","alias":"companyindustry","type":"select","group":"professional","object":"company","is_fixed":"1","properties":"a:1:{s:4:\"list\";a:41:{i:0;a:2:{s:5:\"label\";s:19:\"Aerospace & Defense\";s:5:\"value\";s:19:\"Aerospace & Defense\";}i:1;a:2:{s:5:\"label\";s:11:\"Agriculture\";s:5:\"value\";s:11:\"Agriculture\";}i:2;a:2:{s:5:\"label\";s:7:\"Apparel\";s:5:\"value\";s:7:\"Apparel\";}i:3;a:2:{s:5:\"label\";s:21:\"Automotive & Assembly\";s:5:\"value\";s:21:\"Automotive & Assembly\";}i:4;a:2:{s:5:\"label\";s:7:\"Banking\";s:5:\"value\";s:7:\"Banking\";}i:5;a:2:{s:5:\"label\";s:13:\"Biotechnology\";s:5:\"value\";s:13:\"Biotechnology\";}i:6;a:2:{s:5:\"label\";s:9:\"Chemicals\";s:5:\"value\";s:9:\"Chemicals\";}i:7;a:2:{s:5:\"label\";s:14:\"Communications\";s:5:\"value\";s:14:\"Communications\";}i:8;a:2:{s:5:\"label\";s:12:\"Construction\";s:5:\"value\";s:12:\"Construction\";}i:9;a:2:{s:5:\"label\";s:23:\"Consumer Packaged Goods\";s:5:\"value\";s:23:\"Consumer Packaged Goods\";}i:10;a:2:{s:5:\"label\";s:9:\"Education\";s:5:\"value\";s:9:\"Education\";}i:11;a:2:{s:5:\"label\";s:11:\"Electronics\";s:5:\"value\";s:11:\"Electronics\";}i:12;a:2:{s:5:\"label\";s:6:\"Energy\";s:5:\"value\";s:6:\"Energy\";}i:13;a:2:{s:5:\"label\";s:11:\"Engineering\";s:5:\"value\";s:11:\"Engineering\";}i:14;a:2:{s:5:\"label\";s:13:\"Entertainment\";s:5:\"value\";s:13:\"Entertainment\";}i:15;a:2:{s:5:\"label\";s:13:\"Environmental\";s:5:\"value\";s:13:\"Environmental\";}i:16;a:2:{s:5:\"label\";s:7:\"Finance\";s:5:\"value\";s:7:\"Finance\";}i:17;a:2:{s:5:\"label\";s:15:\"Food & Beverage\";s:5:\"value\";s:15:\"Food & Beverage\";}i:18;a:2:{s:5:\"label\";s:10:\"Government\";s:5:\"value\";s:10:\"Government\";}i:19;a:2:{s:5:\"label\";s:10:\"Healthcare\";s:5:\"value\";s:10:\"Healthcare\";}i:20;a:2:{s:5:\"label\";s:11:\"Hospitality\";s:5:\"value\";s:11:\"Hospitality\";}i:21;a:2:{s:5:\"label\";s:9:\"Insurance\";s:5:\"value\";s:9:\"Insurance\";}i:22;a:2:{s:5:\"label\";s:9:\"Machinery\";s:5:\"value\";s:9:\"Machinery\";}i:23;a:2:{s:5:\"label\";s:13:\"Manufacturing\";s:5:\"value\";s:13:\"Manufacturing\";}i:24;a:2:{s:5:\"label\";s:5:\"Media\";s:5:\"value\";s:5:\"Media\";}i:25;a:2:{s:5:\"label\";s:15:\"Metals & Mining\";s:5:\"value\";s:15:\"Metals & Mining\";}i:26;a:2:{s:5:\"label\";s:14:\"Not for Profit\";s:5:\"value\";s:14:\"Not for Profit\";}i:27;a:2:{s:5:\"label\";s:9:\"Oil & Gas\";s:5:\"value\";s:9:\"Oil & Gas\";}i:28;a:2:{s:5:\"label\";s:17:\"Packaging & Paper\";s:5:\"value\";s:17:\"Packaging & Paper\";}i:29;a:2:{s:5:\"label\";s:36:\"Private Equity & Principal Investors\";s:5:\"value\";s:36:\"Private Equity & Principal Investors\";}i:30;a:2:{s:5:\"label\";s:10:\"Recreation\";s:5:\"value\";s:10:\"Recreation\";}i:31;a:2:{s:5:\"label\";s:11:\"Real Estate\";s:5:\"value\";s:11:\"Real Estate\";}i:32;a:2:{s:5:\"label\";s:6:\"Retail\";s:5:\"value\";s:6:\"Retail\";}i:33;a:2:{s:5:\"label\";s:14:\"Semiconductors\";s:5:\"value\";s:14:\"Semiconductors\";}i:34;a:2:{s:5:\"label\";s:8:\"Shipping\";s:5:\"value\";s:8:\"Shipping\";}i:35;a:2:{s:5:\"label\";s:13:\"Social Sector\";s:5:\"value\";s:13:\"Social Sector\";}i:36;a:2:{s:5:\"label\";s:10:\"Technology\";s:5:\"value\";s:10:\"Technology\";}i:37;a:2:{s:5:\"label\";s:18:\"Telecommunications\";s:5:\"value\";s:18:\"Telecommunications\";}i:38;a:2:{s:5:\"label\";s:14:\"Transportation\";s:5:\"value\";s:14:\"Transportation\";}i:39;a:2:{s:5:\"label\";s:9:\"Utilities\";s:5:\"value\";s:9:\"Utilities\";}i:40;a:2:{s:5:\"label\";s:5:\"Other\";s:5:\"value\";s:5:\"Other\";}}}","default_value":null,"value":null,"normalizedValue":""},"companydescription":{"id":"43","label":"Description","alias":"companydescription","type":"text","group":"professional","object":"company","is_fixed":"1","properties":"a:0:{}","default_value":null,"value":null,"normalizedValue":""}},"other":[],"all":{"id":3,"companyaddress1":null,"companyaddress2":null,"companyemail":null,"companyphone":null,"companycity":null,"companystate":null,"companyzipcode":null,"companycountry":null,"companyname":"test2","companywebsite":null,"companynumber_of_employees":null,"companyfax":null,"companyannual_revenue":null,"companyindustry":null,"companydescription":null}}}],"statusCodes":[200,200]}%                                                                                                             
```

Without these changes, just using the latest 5.x branch:

```shell
curl -X POST https://mautic.ddev.site/api/companies/batch/new \
--header 'Authorization: Basic YWRtaW46TWF1dDFjUjBja3Mh' \
-H "Content-Type: application/json" \
-d '[
    {
        "companyname": "test",
        "custom_company_field": "x2"
    },
    {
        "companyname": "test2",
        "custom_company_field": "x1"
    }
]'
{"companies":[],"statusCodes":[422,422],"errors":[{"code":422,"message":"companyname: This field must be unique.","details":{"companyname":["This field must be unique."]},"type":null},{"code":422,"message":"companyname: This field must be unique.","details":{"companyname":["This field must be unique."]},"type":null}]}%                                              
```

**Comment by kuzmany** [comment]
@abhisekmazumdar Ok, I will try check it. It's cherry pick from M4

**Comment by kuzmany** [comment]
@abhisekmazumdar I did try it on last 5 branch and  seems does work for me

On second same payload call I get error. After patch it run properly.

image

**Review by abhisekmazumdar — APPROVED** [review]
Upon testing this again, I found that duplicates are created for companies and no error is thrown either.

**Review by shinde-rahul — APPROVED** [review]

**Review by JonasLudwig1998 — APPROVED** [review]
In the current mantic version:
After running the post request once in the current Mautic version the companies were added in Mautic. When running it a second time I got the response: 
{"companies":[],"statusCodes":[422,422],"errors":[{"code":422,"message":"companyname: This field must be unique.","details":{"companyname":["This field must be unique."]},"type":null},{"code":422,"message":"companyname: This field must be unique.","details":{"companyname":["This field must be unique."]},"type":null}]}

When running the post request in Mautic with the PR I could run the post request multiple times and the response contained no error. In the user interface I could see that just the two companies:
    {
        "companyname": "test",
        "custom_company_field": "x2"
    },
    {
        "companyname": "test2",
        "custom_company_field": "x1"
    }
 were added one time.
 
 So everything is working fine. Good job

**Comment by shinde-rahul** [comment]
- Sending name only, where `companyname` is unique field.

01 - Created

-  Resending the payload updates the company
02 - Updated

-  Sending name and custom field (a unique field) with different values
03 - With unique field

-  Sending name and custom field (a unique field) with similar values
04 - With unique duplicate data

@kuzmany, the error message should be `company_identifier: This field must be unique.` instead of `companyname: This field must be unique.`

**Pull request merged**
