### PR TITLE
[dead-code] Remove unnecesary array check

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Ready for review :+1:

**Review by escopecz — APPROVED** [review]
This is amazing. A lot of this code simplification was enabled by the Doctrine refactoring that happened for M5 as Doctrine itself now returns strict types so additional checks aren't necessary.

This will reduce cognitive complexity of the changed code significantly.

I went through the first 50% of these changes and confirmed that all the removed if statement were not necessary. After that I did only random checks but it was all the same. Rector did good here 👍 

There are some method signature changes so I'll merge it now to get it into the major release.

**Comment by TomasVotruba** [comment]
Thanks for such a specific feedbacks!
This would be normally a challenge to verify, but thanks to high quality CI, I was able to collect failures and fix them at once. Good job 👍

**Comment by TomasVotruba** [comment]
Btw, when is the major release happening? Just so I know how much time is left for more risky changes.

**Comment by escopecz** [comment]
Any day now 🤞

**Comment by TomasVotruba** [comment]
I see. Can we squeeze few return type declaration PRs? 🙏

**Comment by escopecz** [comment]
If you hurry :) Otherwise we'll be using the good old annotations for that until we start a new branch on Mautic 6

**Comment by TomasVotruba** [comment]
We have to avoid such a disaster :)

Here you go:
https://github.com/mautic/mautic/pulls?q=is%3Apr+is%3Aopen+author%3ATomasVotruba+sort%3Aupdated-desc+draft%3Afalse

**Pull request merged**
