### PR TITLE
Re: FullCalendar localization

### PR DESCRIPTION
**Pull request by hissy**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging for features or enhancements
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | N/A

#### Description:

Retry to localize fullcalendar. #8251 is the previous pull request but it made for mautic v2.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Go to Configuration page then choose Language
3. Logout from Mautic
3. Go to the Calendar page and see your language

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/9432"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
@hissy there is a conflict to address here if you are able to please address it? Thanks!

**Comment by hissy** [comment]
@RCheesley  I don't have permission to push the "Resolve conflicts" button, but you can fix it. Just keep both of them.

```
<<<<<<< fix/translate-fullcalendar-1
    var mauticLocale      = '<?php echo $app->getRequest()->getLocale(); ?>';
=======
    var mauticEditorFonts = <?php echo json_encode($view['config']->get('editor_fonts')); ?>;
>>>>>>> features
```

**Comment by hissy** [comment]
thanks stale bot, I'm still waiting for @RCheesley to merge this PR, no need to close

**Comment by RCheesley** [comment]
@hissy we need this to be tested and code reviewed before it can be considered for merging.

Perhaps you could give a bit more detail as to how people can test - for example what specifically are they looking for when they go to the calendar?

**Comment by hissy** [comment]
@RCheesley I wrote how to test on previous pull request: #8251

**Review by kuzmany — DISMISSED** [review]
It works. Just need logout/login

image

**Comment by kuzmany** [comment]
@hissy can you remove media/js/app.js and media/js/libraries.js from PR. These files are generated during build production release

**Comment by hissy** [comment]
@kuzmany 

How should I remove generated assets? Any suggestions? Just revert the commit or re-create a new PR from 4.x branch

**Comment by kuzmany** [comment]
@hissy revert commit should work in this case. Thanks

**Comment by RCheesley** [comment]
I'm struggling to test this - I've tried in dev and prod mode, and I have got French set at the global and user level, but the calendar itself is not getting translated:

Calendrier _ Mautic

I have logged out and logged back in (several times!) and it still shows the days in English, and the month.

Maybe I missed a step someplace? The rest of Mautic is translated as expected.

Also, it looks like this PR might need to be rebased to 4.x going on the code coverage report.

**Comment by kuzmany** [comment]
@RCheesley did you regenerate assets? What language did you switch in configuration?

**Comment by RCheesley** [comment]
> @RCheesley did you regenerate assets?

Should not be needed in developer mode? I did make sure I was in dev mode before starting.

> What language did you switch in configuration?

From my default (English) to French. The rest of the instance is in French as you can see in the screenshot. Just not the calendar itself 🤔

**Comment by kuzmany** [comment]
@RCheesley try refresh browser, or try incognito. I did test on french as well

**Review by mabumusa1 — DISMISSED** [review]
I tested this on gitpod, you need to login and logout to change the language. it works as expected

**Comment by kuzmany** [comment]
@hissy need remove both files from media/js from this PR

**Review by kuzmany — APPROVED** [review]

**Pull request merged**
