### PR TITLE
Clarify global segment setting's tooltip

### PR DESCRIPTION
**Pull request by bradjones1**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | X
| Deprecations?                          | No
| BC breaks? (use the c.x branch)        | No
| Automated tests included?              | Translations change only.
| Issue(s) addressed                     | Refs https://github.com/mautic/mautic/issues/11808

#### Description:

This tooltip is confusing. It should reflect the docs, see https://docs.mautic.org/en/contacts/manage-segments#public-and-private-segments

#### Steps to test this PR:

1. Apply and view new tooltip/option title.

### CODE REVIEW

**Comment by escopecz** [comment]
@kuzmany or @npracht can you please validate this change? I think this field was also abused for the preference center visibility so it should have both descriptions?

**Comment by npracht** [comment]
For me @escopecz it sounds good. Available in PC is now contrôles by another toggle.

**Comment by escopecz** [comment]
Aha, so this was really wrong. Thanks for confirmaiton!

**Comment by escopecz** [comment]
@bradjones1 please create a duplicate PR for the 5.x branch. This cannot be merged until we have a duplicate for the main branch as well so it won't happen that this is fixed for M4 but left buggy in M5

**Review by mabumusa1 — APPROVED** [review]
This PR is good to go

**Comment by mabumusa1** [comment]
@escopecz this is ready

**Pull request merged**
