### PR TITLE
enhance form progressive profiling to make it compatible cross forms and more flexible

### LINKED ISSUE #2545: Progressive profiling improvement - could benefit from queued questions
What type of report is this:

| Feature request? | 
## Description:

Progressive profiling feature on 2.1 is a great benefit on the forms completed by potential clients. However, an additional feature would be to be able to use queued questions as per hubspot. Means that forms could pick say 4 fields out of information that is either a) not already collated and b) required.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/37936463-progressive-profiling-improvement-could-benefit-from-queued-questions?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by kuzmany**
closes https://github.com/mautic/mautic/issues/2545
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | https://github.com/mautic/mautic-documentation/pull/42
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | Resolves https://github.com/mautic/mautic/issues/2545
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR adds:
* the ability to queue as much fields as we want in a form
* add a property to form to display only a certain amount of fields
* add a property to form fields to always display even if value is known
* add cross form support of progressive profiling (today only working form by form)

image

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Test forms and all combinations
3. Set max fields to display  with combination behaviour settings
- Show when value exists 
- Show after X submissions 
- Auto fill data

### CODE REVIEW

**Review by florentpetitjean — DISMISSED** [review]
Tested and working : 
Scenario like this :

5 fields
Display only 3
- field 1
- field 2
- field 3
- field 4
- field 5 always display
it should result if unknown

- field 1
- field 2
- field 5 always display

it should result if known

- field 3
- field 4
- field 5 always display

is working
good job !

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by npracht** [comment]
>Show after X submissions

This should be removed. From a user (marketeer) perspective, the question is not about amont of form submission for a specific form, but it is "do we know visitor data". This is how progressive profiling works.

**Comment by npracht** [comment]
@florentpetitjean can you retest please?

**Comment by florentpetitjean** [comment]
I'm on it

**Review by florentpetitjean — DISMISSED** [review]
Always display works well. 
Nice job :)

**Comment by kuzmany** [comment]
Rebased, resolved conflicts and tested

**Comment by RCheesley** [comment]
Bumping to 3.2 due to Travis builds failing.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by tejasync** [comment]
Hi,
I found out that if a field is made ‘required’ and not ‘always display’, on submit it may show validation errors even if the field is not present in the form.
I believe if the field is not shown on the form it shouldn’t be validated.

Please refer to the screenshots:
Screenshot 2020-11-23 at 10 31 29 AM
Screenshot 2020-11-23 at 10 33 47 AM
Screenshot 2020-11-23 at 10 34 15 AM

**Comment by tejasync** [comment]
A simple solution would be to always display a required field.

**Comment by npracht** [comment]
Hi @ts-navghane ! You can also simply prepopulate the field if the data is known. Then if it hides, it also prepopulate = no issue.

**Comment by tejasync** [comment]
Hey @npracht, I hope by prepopulate you mean Default value. I tried setting it, but didn't work.
I have observed that the form input is not render in the HTML if it is set to 'always display = no' (it is not hidden).

**Comment by kuzmany** [comment]
@ts-navghane I will reset, but hidden required field couldn't be validated
Did you test on test enviroment?
Did you re-generate assets? (`php bin/console m:a:g`)

**Comment by kuzmany** [comment]
BTW: we are using it on production

**Comment by escopecz** [comment]
@kuzmany please make CI pass

**Comment by tejasync** [comment]
@kuzmany, I'm testing it for prod env on local (shouldn't be an issue).
Yes, the assets were regenerated, it was a fresh setup done for your PR.

**Comment by kuzmany** [comment]
@ts-navghane I am able to reproduce it. I will take look on it today. Thanks for reporting

**Comment by kuzmany** [comment]
@ts-navghane I've checked it and it works
Just doesn't work in preview mode , because progressive profiling require tracked contact, on preview you are not tracked contact. 

You can test on mautibox 
 - this is the form  what I've created https://mautibox.com/8611/s/forms/edit/3
- this is form what you can test https://mautibox.com/8611/form/3 (cannot be logged in Mautic, try in incognito window)

**Comment by tejasync** [comment]
@kuzmany, Awesome! This works as expected!
But should it not work in preview mode as well?

**Comment by kuzmany** [comment]
@ts-navghane yes

**Comment by npracht** [comment]
@mautic/acquia-po do you think we can have someone from your marketing/PO team testing it ? I'm sure it would be super useful for your customers as it was important to have Conditional fields ;)

**Comment by RCheesley** [comment]
Subject to tests passing and having had the +1 from @ts-navghane and @npracht reporting that this is in use on production, I am good for us to merge this assuming that the test coverage is good :)

**Pull request merged**
