### PR TITLE
Push lead owner to Sugar CRM through forms and campaigns

### PR DESCRIPTION
**Pull request by MaxWebmecanik**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | ✓
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

Lead owners were not being pushed to Sugar CRM through forms and campaigns. This PR fixes that.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Connect your instance to Sugar CRM
2. Make a form to push leads to Sugar
3. Make a lead with all the necessary data as well as an owner
4. Submit the form with the lead's email
5. Notice the lead has no owner in Sugar

#### Steps to test this PR:
1. Connect your instance to Sugar CRM
2. Make a form to push leads to Sugar
3. Make a lead with all the necessary data as well as an owner
4. Submit the form with the lead's email
5. Notice the lead has an owner in Sugar

### CODE REVIEW

**Comment by npracht** [comment]
Previously only the CLI command was sending the owner and now it works from actions (points, campaigns, forms)!

**Comment by npracht** [comment]
@alanhartless We just added a commit to correct an issue when the contact was pushed to Sugar with a leadowner that was not existing in Sugar.
Now, in that case, the owner is not pushed (empty).

**Comment by escopecz** [comment]
I think there is some step missing in the steps to test. I submitted the form with push to integration - Sugar CRM. Then I edited that contact - added some owner to it. Submitted the form once more. But no assignee is added to the Sugar lead. Should it be assignee? I don't see an owner in Sugar CRM. Maybe the Sugar assignee must exist first? At least that's what I read from the code. Could you help me with how to create one?

**Comment by npracht** [comment]
Hello @escopecz you must have the same owners in Sugar as Users (contact owner) un mautic if you want the sync. to be working.
In Sugar, you cannot have (same in mautic) an owner which is not defined.

**Comment by escopecz** [comment]
Ok, I managed to make it work like this:

0. Authenticate and map Sugar CRM plugin.
1. Create a new user in Sugar CRM with the same address as your user in Mautic.
2. Create a contact with email for example `me@sugar.com`, some first and last name.
3. Create the form with the send to integration: Sugar CRM action.
4. Submit the form with email address `me@sugar.com`.
5. Such form submission will appear in Sugar Leads and will have the assignee filled in.

The updates did not work for me. That's why you have to create the Mautic contact first and assign it the owner before you submit the form.

**Comment by npracht** [comment]
## Sync owner
@escopecz this is the way it should be done and that confirm that the PR allow the sync. of the owner. Thanks.

## Owner update
Now, you're saying that if:

1. you sync. a lead without owner
2. you add owner to mautic contact (being sure that the user mautic is existing as a Sugar user)
3. you sync again (via form or campaign) ---> The owner is not updated in Sugar

This is what you have expercienced ?

**Comment by escopecz** [comment]
I have 0 experience with Sugar CRM, so if this functionality is what you need for your workflow I'm OK with approving it. It's definitely an improvement.

**Comment by npracht** [comment]
Yes the fact of have the same users in both plateform is very important and logic.
And yes, having the sync. of the lead owner by actions (form, campaign and point trigger) is an improvement :)

Thanks

**Comment by isleshocky77** [comment]
@npracht Does this only concern PUSH (Mautic -> Sugar), or did you test PULL (Sugar to Mautic)?

**Comment by npracht** [comment]
@isleshocky77 that was a push issue, i didn't test pulling on that feature.

**Pull request merged**
