### PR TITLE
Add rector to pre-commit

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:
Same like we do cs fixes on pre commit, I've added rector.

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Remove .git/hooks/pre-commit file If exists
3. Run composer install
4. Try commit some change, for example  remove : void type declaration from some class
5. Commit should automatically add it

### CODE REVIEW

**Review by escopecz — COMMENTED** [review]
It's a good idea, but I've seen Rector doing bad choices from time to time. So this may introduce a bug without the author knowing about it. I know it would save a lot of time but I'm not sure it it's worth introducing a potential bug.

**Comment by kuzmany** [comment]
@escopecz After Tomas's changes, Rector started reporting more issues. In the last few PRs, I had to run separate Rector calls, which just increased maintenance time for PRs. Really, we should start decreasing the time for maintenance. I spent hours on Friday rebasing and resolving conflicts again and again. It's a never-ending story.

**Review by escopecz — APPROVED** [review]
I hear you. Luckily, in case of Rector, it's 99% of time just running `composer rector` to fix it. I prefer explicitly calling that command rather than magic on commit. But I understand the pain. I'm fine with trying this out and evaluate after some time 👍

**Comment by kuzmany** [comment]
@escopecz 
Do not need this PR, but I think it brings more and more work for other devs, CI will complain so often, then we need to ask devs to fix it etc etc.  We can try it and If it make troubles, we can revert it.

**Comment by kuzmany** [comment]
With the changes introduced in https://github.com/mautic/mautic/pull/13185, we have modified the behavior of cs fixe during commit. As a result, this pull request is no longer applicable.

**Pull request closed without merging**
