### PR TITLE
Css fixes

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**
This PR fixes two issues.

1) The layout in Safari 9 (10.11 beta) was messed up due to errors in the CSS file related to the use of lesshat library.  See https://github.com/davipt/lesshat/commit/3614be1530e33e7c25592137c02a7c2c37b3ad3f

2) The loading bar had a constant animation going even though it was hidden.  This caused constant reflow and higher cpu usage. This was fixed by only showing the animation on the active class of the loading bar.

**Testing**
1) Becomes apparent with Safari 9 but can read the notes from the issues linked to in that commit.
2) I used Chrome Canary and Firefox to discover this.  But you can see the constant reflow by enabling firefox developer tools, click console, click the dropdown on the css tab and select reflows.  You'll see the console just start going crazy.  After the PR and a refresh, the reflow will only show when navigating between pages (or normal usage based on interaction with the site).

http://dvkrd.co/drop/2015-07-11_15-41-02-1.png

### CODE REVIEW

**Comment by alanhartless** [comment]
Hey @gjergjie, tagging you in case you're not on Slack much.  I think I found the CPU issue you brought up.  Would you be willing to test this to validate?

Thanks!
Alan

**Comment by gjergjie** [comment]
hey Alan, man you really quick, did you figured out what it was? Is there any commit ready so I can pull and test?

**Comment by alanhartless** [comment]
Yea, click on the commits tab or the files tab of this PR and you'll see the changes.  

Got to reading on causes for high CPU for webpages which lead to reflows which led to how to see the reflows and saw that Firefox was going crazy with it.  But Firefox doesn't show what's causing it other than a general CSSAnimations notation.  So then used Chrome Canary's developer tools to figure out what frame was causing the reflow which revealed it was the animated loading bar.

Thanks!
Alan

**Comment by drmmr763** [comment]
Reproduced the reflow test with Firefox. 

+ @ Test PR resolved the error successfully. 
+ @ Vote +1

**Comment by escopecz** [comment]
I can confirm that the 2nd issue is much better after applying this PR. :+1:

**Pull request merged**
