### PR TITLE
Fix progressive forms

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... https://github.com/mautic/mautic/issues/11073

#### Description:
After merge https://github.com/mautic/mautic/pull/8794 we lost some progressive profiling features. This PR fixed it 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a form with 8 fields, set the "Maximum fields displayed at a time" to 4, and make sure to set "Always display" to "No" on all the fields. It should show only 4 fields but it shows all 8.
3. You need these settings for each field
image

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11125"></a>

### CODE REVIEW

**Review by volha-pivavarchyk — DISMISSED** [review]
Works as expected. 

Now four fields are displayed:
image

**Review by jos0405 — DISMISSED** [review]
Works as expected.

image

**Comment by RCheesley** [comment]
Thanks folks, LGTM as soon as the tests pass! 🚀

**Comment by RCheesley** [comment]
As we have missed this in the past, I'd like it if we could write some kind of test to make sure that the progressive profiling is working as expected. Otherwise we run the risk of this breaking again in the future and we not realise it. @kuzmany do you think you (or someone else) could contribute a test to check this?

**Comment by kuzmany** [comment]
@RCheesley I will do

**Pull request merged**
