### PR TITLE
Fix resubscribe action condition check

### LINKED ISSUE #11784: Fatal error when resubscribe action does not find email
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When calling PublicController::resubscribeAction, if the email stat entity is not found, then we get an error from a faulty check in the code: 
https://github.com/mautic/mautic/blob/4.4/app/bundles/EmailBundle/Controller/PublicController.php#L366

This is due to the fact that we do a regular cleanup of old email stats, we end up having this error on occasions.

### How can we reproduce this issue?

Delete email stats from database and trigger a resubscribe action on an email.

### Relevant log output

```shell
Uncaught exception 'Error' with message 'Call to a member function getTemplate() on bool' in /var/www/html/app/bundles/EmailBundle/Controller/PublicController.php:366
 in Mautic\EmailBundle\Controller\PublicController::resubscribeAction called at /var/www/html/vendor/symfony/http-kernel/HttpKernel.php (169)
 in Symfony\Component\HttpKernel\HttpKernel::handleRaw called at /var/www/html/vendor/symfony/http-kernel/HttpKernel.php (81)
 in Symfony\Component\HttpKernel\HttpKernel::handle called at /var/www/html/vendor/symfony/http-kernel/Kernel.php (201)
 in Symfony\Component\HttpKernel\Kernel::handle called at /var/www/html/app/AppKernel.php (115)
 in AppKernel::handle called at /var/www/html/app/middlewares/CORSMiddleware.php (82)
 in Mautic\Middleware\CORSMiddleware::handle called at /var/www/html/app/middlewares/CatchExceptionMiddleware.php (34)
 in Mautic\Middleware\CatchExceptionMiddleware::handle called at /var/www/html/app/middlewares/VersionCheckMiddleware.php (58)
 in Mautic\Middleware\VersionCheckMiddleware::handle called at /var/www/html/app/middlewares/TrustMiddleware.php (42)
 in Mautic\Middleware\TrustMiddleware::handle called at /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php (23)
 in Stack\StackedHttpKernel::handle called at /var/www/html/vendor/stack/run/src/Stack/run.php (13)
 in Stack\run called at /var/www/html/index.php (24)
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bianchim**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #11784

### CODE REVIEW

**Review by escopecz — COMMENTED** [review]
The code change is save and I can see that the `$email` variable can be `false` so this is fixing for that value. 👍 

Please rebase this PR on top of the 5.x branch and if you wish to fix it in the last versions of Mautic 4 then pleasecreate a duplicate PR against the 4.4  branch.

**Comment by mabumusa1** [comment]
@bianchim thank you for your contribution, let's get this PR merged. 

Please sign the CLA and create a duplicate PR for 5.x, so we can get this PR in M4 and M5

**Comment by mabumusa1** [comment]
@cla-bot check

**Review by mabumusa1 — APPROVED** [review]
This PR is good to go

**Comment by mabumusa1** [comment]
@bianchim thank you for this PR, it is almost ready to be merged, may you please check CLA bot issues, there are the ones preventing this PR from merging

**Comment by mabumusa1** [comment]
Closing in favor of #11918, due to lack of activity

**Pull request closed without merging**
