### PR TITLE
Amazon SES bounce&complaint webhook

### PR DESCRIPTION
**Pull request by wittwerch**
Please answer the following questions. 

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | yes | 
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/92
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

**Note that all new features should have a related user and/or developer documentation PR in their respective repositories.** 

#### Description:
Extend the Amazon mail transport with ability to receive bounce and complaint notifications from Amazon SES/SNS.

#### Steps to test this PR:
1. Enable the Amazon transport
1. Create a lead with a non-existing e-mail address
1. Configure Amazon SES to send bounce&complaints into a Amazon SNS topic
1. Create a subscriber in Amazon SNS pointing to http://your-mautic/mailer/amazon/callback
1. Make sure the  subscriber changed from pending to confirmed (the transport will automatically call the subscriber url)
1. Send an e-mail to the non-existing e-mail address
1. Go to /s/contacts and check that the lead is marked as bounce

I'll write some documentation how to setup when you agree with the implementation

### CODE REVIEW

**Comment by wittwerch** [comment]
Totally forgot: If you want to test the pull request, make sure you apply #2300 as well. Otherwise the dnc entries are not persisted.

**Comment by amagdy3** [comment]
Great work. Used to enjoy it with "Sendy" and it makes mautic even more great.

I updated the pull here and at #2300 yet mautic went offline and got the below errors. I copied the new files all together other changing the lines of code. 

Could this be a reason and how to fix it? Thanks

[2016-09-20 09:52:11] mautic.ERROR: Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so: cannot open shared object file: No such file or directory - in file Unknown - at line 0 [] []
[2016-09-20 09:52:53] mautic.ERROR: PHP Error: Declaration of Mautic\LeadBundle\Model\LeadModel::setLogger() should be compatible with Mautic\CoreBundle\Model\AbstractCommonModel::setLogger(Psr\Log\LoggerInterface $logger) - in file /home/egyprene/public_html/mautic/app/bundles/LeadBundle/Model/LeadModel.php - at line 1716 [] []
[2016-09-20 09:53:02] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 1 passed to Mautic\EmailBundle\MonitoredEmail\Mailbox::__construct() must be an instance of Mautic\CoreBundle\Helper\CoreParametersHelper, instance of Mautic\CoreBundle\Factory\MauticFactory given, called in /home/egyprene/cache/mautic/prod/appProdProjectContainer.php on line 6493 and defined" at /home/egyprene/public_html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php line 168 {"exception":"object"} []
[2016-09-20 09:53:02] mautic.ERROR: Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so: cannot open shared object file: No such file or directory - in file Unknown - at line 0 [] []
[2016-09-20 09:53:08] mautic.ERROR: PHP Error: Declaration of Mautic\LeadBundle\Model\LeadModel::setLogger() should be compatible with Mautic\CoreBundle\Model\AbstractCommonModel::setLogger(Psr\Log\LoggerInterface $logger) - in file /home/egyprene/public_html/mautic/app/bundles/LeadBundle/Model/LeadModel.php - at line 1716 [] []
[2016-09-20 09:53:16] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 1 passed to Mautic\EmailBundle\MonitoredEmail\Mailbox::__construct() must be an instance of Mautic\CoreBundle\Helper\CoreParametersHelper, instance of Mautic\CoreBundle\Factory\MauticFactory given, called in /home/egyprene/cache/mautic/prod/appProdProjectContainer.php on line 6493 and defined" at /home/egyprene/public_html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php line 168 {"exception":"object"} []
[2016-09-20 09:53:16] mautic.ERROR: Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so: cannot open shared object file: No such file or directory - in file Unknown - at line 0 [] []
[2016-09-20 09:55:08] mautic.NOTICE: Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 1 passed to Mautic\EmailBundle\MonitoredEmail\Mailbox::__construct() must be an instance of Mautic\CoreBundle\Helper\CoreParametersHelper, instance of Mautic\CoreBundle\Factory\MauticFactory given, called in /home/egyprene/cache/mautic/prod/appProdProjectContainer.php on line 6493 and defined (uncaught exception) at /home/egyprene/public_html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php line 168 while running console command mautic:email:fetch [] []
[2016-09-20 11:55:10] mautic.ERROR: Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so: cannot open shared object file: No such file or directory - in file Unknown - at line 0 [] []
[2016-09-20 11:55:14] mautic.ERROR: Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20131226/pdo_mysql.so: cannot open shared object file: No such file or directory - in file Unknown - at line 0 [] []

**Comment by amagdy3** [comment]
I managed to clear the cache folder and now getting this error:

Strict Standards: Declaration of Mautic\LeadBundle\Model\LeadModel::setLogger() should be compatible with Mautic\CoreBundle\Model\AbstractCommonModel::setLogger(Psr\Log\LoggerInterface $logger) in /home/egyprene/public_html/mautic/app/bundles/LeadBundle/Model/LeadModel.php on line 1716

**Comment by wittwerch** [comment]
@amagdy3 What php version are you using? Can you please checkout the lastest staging branch and see if the error happens there too? I doubt that the error is related to my PR, because it is complaining about code that I did not touch.. can't really explain that.

**Comment by amagdy3** [comment]
I tried this again, and it's working. The error only shows up when I change something in the configurations and save it again, it appears once and as I move to the root folder. It disappears. 

Could it be that some files in CoreBundle need to be updated to match the new modifications. Or the modifications have called some deprecated functions in the core? 

I'm still having an issue with Amazon not reading the callback url. When I try [amazon_url]mailer/amazon/callback on my browser it gives internal server error. Any guidance on that?

**Comment by amagdy3** [comment]
This error is repeated very frequently:

[2016-09-26 11:03:02] mautic.ERROR: PHP Error: Declaration of Mautic\LeadBundle\Model\LeadModel::setLogger() should be compatible with Mautic\CoreBundle\Model\AbstractCommonModel::setLogger(Psr\Log\LoggerInterface $logger) - in file /home/egyprene/public_html/mautic/app/bundles/LeadBundle/Model/LeadModel.php - at line 1716 [] []

**Comment by amagdy3** [comment]
The error above was caused due to copying the whole files from #2300 and was fixed by applying #2228 

Now, I'm getting the below error. Any idea where it might be coming from?

mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "swiftmailer.mailer.transport.smtp"." at /home/egyprene/public_html/mautic/app/bootstrap.php.cache line 2193 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"swiftmailer.mailer.transport.smtp\". at /home/egyprene/public_html/mautic/app/bootstrap.php.cache:2193)"} []

**Comment by amagdy3** [comment]
@wittwerch I'm getting this error from Amazon SNS as I post the subscription confirmation url. Any idea what might be going wrong?

1 validation error detected: Value null at 'token' failed to satisfy constraint: Member must not be null (Service: AmazonSNS; Status Code: 400; Error Code: ValidationError; Request ID: cec62087-dc7b-5191-a3cc-70e2620d5e43)
capturesns

**Comment by amagdy3** [comment]
@wittwerch I'm also getting this on my error log

[2016-09-28 12:46:24] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "swiftmailer.mailer.transport.smtp"." at /home/muxlim/public_html/comm/app/bootstrap.php.cache line 2193 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"swiftmailer.mailer.transport.smtp\". at /home/muxlim/public_html/comm/app/bootstrap.php.cache:2193)"} []

**Comment by amagdy3** [comment]
I deleted he bootstrap.php.cache file and got the below error instead

[2016-09-28 12:57:56] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "swiftmailer.mailer.transport.smtp"." at /home/muxlim/public_html/comm/vendor/symfony/dependency-injection/Container.php line 305 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"swiftmailer.mailer.transport.smtp\". at /home/muxlim/public_html/comm/vendor/symfony/dependency-injection/Container.php:305)"} []

**Comment by escopecz** [comment]
Like Alan, I don't have a SES to test with, but the unit tests run smoothly for me. I didn't notice any error in the UI, emails send OK. :+1:

**Comment by amagdy3** [comment]
@wittwerch does this require that the "Service to send mail through" to be selected as Amazon SES other than Amazon SES details inserted through "Other SMTP Settings"

If so then a possible cause of this not working with my setup. And I think it will also happen with lots of mautic users who are sending through Amazon SES
captureamazon2

In my Email configuration "Service to send mail through" I'm choosing "Other SMTP Settings" and changing the SMTP port to 2587 other than the standard 587 because it doesn't work.

I understand upon choosing Amazon SES, I can't change the standard SMTP service from 587 which gives the error shown below.
capture587

Below are threads discussing the issue and no solution found except using "Other SMTP Settings" and changing the SMTP port to 2587 

https://www.mautic.org/community/index.php/904-amazon-ses-issue/0
https://www.mautic.org/community/index.php/2922-integration-amazon-ses-error/0
https://www.mautic.org/community/index.php/3426-unable-to-connect-with-tls-encryption/0
https://www.mautic.org/community/index.php/871-issue-with-amazon-ses/0

-> Only solution for me now is to serach the Amazon Transport code and manually change the port from 587 to 2587 if it's possible and see if it works.

**Comment by amagdy3** [comment]
I'm confirming that this is working like magic now. I had to "Disable" an SMTP Restriction in my server environment which had been blocking the connection with 587 port. Attached screenshot shows how.

"This feature prevents users from bypassing the mail server to send mail, a common practice used by spammers. It will allow only the MTA, mailman, and root to connect to remote SMTP servers."

Afterwards, I was able to change my "Service to send Email through" to Amazon SES and it successes. That's only when Amazon SNS subscription was approved.

Thanks a lot guys! I hope this will be helpful to others as plenty of threads were complaining on the same issue as above.

capturesmtprestriction

**Comment by w3update** [comment]
image
**** Why I am getting mails in different labels instead of Inbox ?
this way Mautic bounce not able to processed,

Can any help me about this?

**Comment by w3update** [comment]
I checked with catch-all domain as well, not working.

the catch domain email id will work fine if you use it without any + sign i.e. bouncebounce_45646bbf04c47@domain.tld it will store email in inbox folder.
**if you use + sign i.e. bounce+bounce_45646bbf04c47@domain.tld it is creating new folder like inbox and store email there.**

**Comment by w3update** [comment]
I able to fix it with postfix catchall_maps.cf query by removing support for +

query       = SELECT alias.goto FROM alias,domain WHERE alias.address='%d' ~~AND '%u' NOT LIKE '%%+%%'~~ AND alias.address=domain.domain AND alias.active=1 AND domain.active=1 AND domain.backupmx=0

**Pull request merged**
