### PR TITLE
Security Fix for Username Enumeration - huntr.dev

### PR DESCRIPTION
**Pull request by huntr-helper**
https://huntr.dev/users/arthepsy has fixed the Username Enumeration vulnerability 🔨. arthepsy has been awarded $25 for fixing the vulnerability through the huntr bug bounty program 💵. Think you could fix a vulnerability like this?

Get involved at https://huntr.dev/

Q | A
Version Affected | ALL
Bug Fix | YES
Original Pull Request | https://github.com/418sec/mautic/pull/1
Vulnerability README | https://github.com/418sec/huntr/blob/master/bounties/packagist/mautic/core/1/README.md

#### Bounty URL: https://www.huntr.dev/bounties/1-packagist-mautic%2Fcore

### CODE REVIEW

**Comment by JamieSlome** [comment]
@arthepsy - are you able to sign the CLA, cheers! 👍

**Comment by arthepsy** [comment]
@JamieSlome , signed the CLA.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Hi folks, looks like we need to rebase against staging please!

**Comment by JamieSlome** [comment]
@RCheesley - will get the CLA and rebase sorted now - cheers! 🍰

**Comment by JamieSlome** [comment]
@RCheesley - that is the re-base with staging sorted! 👍

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
It would be super helpful if you could provide some test instructions to reproduce the issue and test that it is resolved @arthepsy @JamieSlome ?

**Comment by RCheesley** [comment]
Also please take a look at the code style issue :)

**Comment by escopecz** [comment]
I don't understand why this PR contains report test from https://github.com/mautic/mautic/pull/9311. The PR was already merged. @huntr-helper can you rebase. I'm missing some related tests.

**Comment by RCheesley** [comment]
@arthepsy @JamieSlome could you please take a look at the comments above so we can get this into the next release?

**Comment by npracht** [comment]
@huntr-helper is that still actual ?
Thanks

**Pull request closed without merging**
