### PR TITLE
missing table prefix on campaign repository

### LINKED ISSUE #9558: missing table prefix on campaign repository
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.2.2 -rc
| PHP version | 7.3.25
| Browser | firefox

### Steps to reproduce
1. update mautic to 3.2.2
2. go to segments and open one of them
 
### Log errors
mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT c.id, c.name, ROUND(IFNULL(COUNT(DISTINCT t.lead_id)/COUNT(DISTINCT cl.lead_id)*100, 0),1) segmentCampaignShare FROM mgtcampaigns c LEFT JOIN mgtcampaign_leads cl ON cl.campaign_id = c.id AND cl.manually_removed = 0 LEFT JOIN (SELECT lll.lead_id AS ll, lll.lead_id FROM lead_lists_leads lll WHERE lll.leadlist_id = 40 AND lll.manually_removed = 0) t ON t.lead_id = cl.lead_id WHERE c.id IN (31, 30, 26) GROUP BY c.id':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic_gt.lead_lists_leads' doesn't exist" at /var/www/mautic_gt/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 42 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT c.id, c.name, ROUND(IFNULL(COUNT(DISTINCT t.lead_id)/COUNT(DISTINCT cl.lead_id)*100, 0),1) segmentCampaignShare FROM mgtcampaigns c LEFT JOIN mgtcampaign_leads cl ON cl.campaign_id = c.id AND cl.manually_removed = 0 LEFT JOIN (SELECT lll.lead_id AS ll, lll.lead_id FROM lead_lists_leads lll WHERE lll.leadlist_id = 40 AND lll.manually_removed = 0) t ON t.lead_id = cl.lead_id WHERE c.id IN (31, 30, 26) GROUP BY c.id':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic_gt.lead_lists_leads' doesn't exist at /var/www/mautic_gt/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:42, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic_gt.lead_lists_leads' doesn't exist at /var/www/mautic_gt/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic_gt.lead_lists_leads' doesn't exist at /var/www/mautic_gt/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:75)"} []

### Solution
the issue caused by missing table extension in the campaign repository ('CampaignBundle\Entity\CampaignRepository.php')
replace  '(SELECT lll.lead_id AS ll, lll.lead_id FROM lead_lists_leads lll WHERE lll.leadlist_id = '  with '(SELECT lll.lead_id AS ll, lll.lead_id FROM '.MAUTIC_TABLE_PREFIX.'lead_lists_leads lll WHERE lll.leadlist_id = ' should solve the issue

image

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by adirbnology**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for features or enhancements / 3.2 for bug fixes 
| Bug fix?                               | yes
| New feature?                           | no
| Automated tests included?              | no
| Issue(s) addressed                     | Fixes #9558

this PR fixes issue #9558 

If you are using mautic with a prefix on your tables (eg mau_) you would be able to reproduce this issue by loading segment view. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. open segment view (e. https://mautic.yourbrand.com/s/segments/view/71)

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for making the PR @adirbnology - we just need to rebase it so that we're on the 3.2 branch then we will be good to go! :tada:

**Comment by RCheesley** [comment]
@cla-bot check

**Review by patrykgruszka — APPROVED** [review]
Tested, this solves the issue in segment view.

**Review by kuzmany — APPROVED** [review]
Make sense
Thanks.
Approve it 👍

**Pull request merged**
