### PR TITLE
Segments mapping if contact is created or identified

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR add segments mapping for new contacts and identified contacts.

#### Steps to test this PR:
1.  Apply PR
2.  Go to Configurations > Contacts settings - see new Segments mapping area
3. Setup segments for new/identified contact
4.  Try test 
- create contact from Mautic
- create from form
- create via import
etc..
5. Check If segments were added to contact

image

### CODE REVIEW

**Comment by escopecz** [comment]
What is the use case for this? It both can be created via segment filters.

**Comment by alanhartless** [comment]
@matishaladiwala thoughts on this?

**Comment by kuzmany** [comment]
Any thoughts on this, guys?
Main reason for this is work with new visitors. 
For example new visitor come to site, then go to product detail and I want to show focus for this visitor.
Now It's not possible, because we have to wait for cron.
Maybe we could find good way for integrate this option, it's very powerfull.

**Comment by alanhartless** [comment]
After discussing this one, we feel it's a redundant feature. But it would be easy enough to convert to a plugin and link to in the Mautic marketplace. Thanks!

**Pull request closed without merging**
