### PR TITLE
New webhook: Company Create/Update Event

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR added new webhook when company is created or updated.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create and copy test webhook url https://webhook.site/
3. Go to Mautic > Webhook and create new one with checked Company Create/Update Event

image
4. Go to companies section and try create/update companies. 
5. Check If your https://webhook.site/ receive info about your companies create/update actions

### CODE REVIEW

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebased

**Review by RCheesley — DISMISSED** [review]
Company create webhook sent successfully:

screenshot-webhook site-2020 08 15-16_15_22

Company update webhook sent successfully:

screenshot-webhook site-2020 08 15-16_16_22

Also tested company deleted webhook:

screenshot-webhook site-2020 08 15-16_14_10

Thanks for the PR @kuzmany :rocket:

**Review by dennisameling — CHANGES_REQUESTED** [review]
Code LGTM. @kuzmany could you please add tests? There's already a `WebhookSubscriberTest` so it should be relatively easy to do 👍 let me know if I can support in any way

**Review by dennisameling — APPROVED** [review]

**Pull request merged**
