### PR TITLE
Custom Field Alias constraint for special keywords added

### PR DESCRIPTION
**Pull request by escopecz**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | Y
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/5694
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
The problem is that if a user creates new custom field with alias of `hit_url_count` for example and then she'll create new segment filter for this `hit_url_count` it won't work with the values of that custom field but with the page hit counts. This may be confusing and even cause bugs. This PR adds validation which doesn't allow user to save a custom field with such keyword.
screen shot 2018-03-20 at 16 54 05

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Try to create new custom field with alias of `sessions` or `hit_url_count`. It will let you do that. Bad!

#### Steps to test this PR:
1. Checkout this PR
2. Clear cache
3. Delete the CF you created during testing.
4. Try to create it again. It will show you a validation error message as in the screenshot above. Good!
5. Try to save with another alias to ensure that's not broken.

### CODE REVIEW

**Comment by Maxell92** [comment]
Validation works in case I write alias into an alias field directly.
However it does not work if I create CF with label `hit_url_count` only. Alias will be created automatically and custom field will be created.

**Comment by Dreiser** [comment]
Works for me!

**Comment by javjim-mautic** [comment]
Works properly

**Comment by javjim-mautic** [comment]
Tested and reproduced bug and fix. working properly

**Pull request merged**
