### PR TITLE
[Bug] SQL error if no field is chosen for "Form field value" conditional.

### PR DESCRIPTION
**Pull request by heathdutton**
| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #5874
| BC breaks? | No
| Deprecations? | No

[//]: # ( Required: )
#### Description:
When no form field is selected, the campaign will hit a SQL error. That field is marked as required but not validated as not-empty. The simple fix is to not permit the condition from being saved as blank.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
See #5874

#### Steps to test this PR:
1. Try creating a "Form field value" condition within a campaign, with no field selected.
2. You should receive "A value is required" for the field like so:
Validation appearance

### CODE REVIEW

**Comment by escopecz** [comment]
When following the steps to replicate I get:

```
500 Internal Server Error - PHP Notice - Undefined index: field
/app/bundles/FormBundle/Form/Type/CampaignEventFormFieldValueType.php:136
```
(When on index_dev.php. If on production the same notice should be logged.)

Another issue I found is that if I try to save the modal form without a value I get.

Yet another request I have. I noticed that if I select a form and then unselect it again I get

```
500 Internal Server Error - Call to a member function getFields() on null
/app/bundles/FormBundle/Controller/AjaxController.php:72 at
/app/bundles/CoreBundle/Controller/AjaxController.php:130 at Mautic\FormBundle\Controller\AjaxController -> updateFormFieldsAction ( object(Request), 'form' )
```
Could you please modify [this line](https://github.com/mautic/mautic/blob/staging/app/bundles/FormBundle/Controller/AjaxController.php#L72) to `$formFields = empty($entity) ? [] : $entity->getFields();` or something like it?

**Comment by heathdutton** [comment]
Good call. Requested change made.

**Comment by escopecz** [comment]
Thanks! Were you able to track down also the PHP notice I posted?

**Comment by heathdutton** [comment]
Didn't see that one myself, but simple enough to fix.

**Pull request merged**
