### PR TITLE
Add notification settings for webhook and campaign unpublish

### PR DESCRIPTION
**Pull request by dadarya0**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | 
| BC breaks?                             | 
| Automated tests included?              | yes
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
As a user  if I am not the owner of certain resources within the instance I will not receive notifications about actions such as campaigns unpublishing. I want to be able to configure one to many email addresses to receive key notifications for my instance

#### Steps to test this PR:
Require run `doctrine:migrations:execute 20210217115150`

1. Load up [this PR](https://mautibox.com)
2.Switch to Configuration > Notification Settings
3. Yes/No button should be available for Send notification to author
4. If select No then new field should be display for Email addresses to receive notification here user can add multiple comma separated email addresses.
5. Above 3 step should be performed for both section (Campaign and Webhook)
6. Send mail when campaign or webhook unpublished due to failure should work as per above configuration.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10299"></a>

### CODE REVIEW

**Comment by kuzmany** [comment]
Hello @dadarya0 ,
I tested it and works perfectly. I receive email after webhook fails and cross the limit to fails

image

How could I sumulate campaign failed events? I tried force return       `$event->failRemaining('xxx');` on `onCampaignTriggerActionSendEmailToContact`. But without success. Can you point me details?

**Review by kuzmany — DISMISSED** [review]
This is nice improvement and understand the solution.
Works for me.
Code looks good.
Unit test included
Thank you 👍

**Comment by RCheesley** [comment]
@dadarya0 looks like we have some failing tests to be addressed here.

**Comment by dadarya0** [comment]
> @dadarya0 looks like we have some failing tests to be addressed here.

@RCheesley  failing tests are fixed.

**Review by mabumusa1 — DISMISSED** [review]
I checked the code and tested with an unpublished campaign, it worked as expected. 

This PR should not be confused with the timeline of the contact, so for example if you create a webhook with a wrong URL it will not send a notification email telling that there was an error

**Comment by kuzmany** [comment]
@mabumusa1 how did you test campaign unpublished? How did you force unpublish campaign on failed events?

**Comment by RCheesley** [comment]
@dadarya0 there's a PHPSTAN issue to fix here please :) 

cc @escopecz

**Pull request merged**
