### PR TITLE
Contact manipulators added for campaigns and integrations

### PR DESCRIPTION
**Pull request by fedys**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [❌]
| New feature/enhancement? (use the a.x branch)      | [✅]
| Deprecations?                          | [❌]
| BC breaks? (use the c.x branch)        | [❌]
| Automated tests included?              | [✅] 
| Related user documentation PR URL      |  
| Related developer documentation PR URL |  
| Issue(s) addressed                     | 

#### Description:

This PR adds contact manipulators for campaigns and integrations. The manipulator info can be used in plugins for example.

#### Steps to test this PR:

1. There is no way to test this PR via the UI as there are changes that are not directly used by the current codebase.

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
The code looks great. Since this cannot be manually tested and is covered with tests thoroughly I'm merging it.

**Comment by kuzmany** [comment]
This PR make regression for us:
If I sync contact from integration I see on timeline:

image

With notice error:

 500 Internal Server Error - PHP Notice - Undefined index: integration 

With trace:

```
/bundles/IntegrationsBundle/EventListener/TimelineSubscriber.php:102 at
/bundles/IntegrationsBundle/EventListener/TimelineSubscriber.php:102 at Mautic\CoreBundle\ErrorHandler\ErrorHandler -> handleError ( '8', 'PHP Notice - Undefined index: integration', '/app/app/bundles/IntegrationsBundle/EventListener/TimelineSubscriber.php', '102', array('log' => array('id' => '201638', 'lead_id' => '186410', 'user_id' => null, 'user_name' => null, 'bundle' => 'integrations', 'object' => 'create', 'action' => 'identified_contact', 'object_id' => null, 'date_added' => object(DateTime), 'properties' => '{"object_description":null}'), 'eventType' => 'integration_sync_issues', 'eventTypeName' => 'Integration sync notice', 'icon' => 'fa-refresh', 'properties' => array('object_description' => null)) )
/bundles/IntegrationsBundle/EventListener/TimelineSubscriber.php:79 at Mautic\IntegrationsBundle\EventListener\TimelineSubscriber -> getEventEntry ( array('id' => '201638', 'lead_id' => '186410', 'user_id' => null, 'user_name' => null, 'bundle' => 'integrations', 'object' => 'create', 'action' => 'identified_contact', 'object_id' => null, 'date_added' => object(DateTime), 'properties' => '{"object_description":null}'), 'integration_sync_issues', 'Integration sync notice', 'fa-refresh' )
/bundles/IntegrationsBundle/EventListener/TimelineSubscriber.php:121 at Mautic\IntegrationsBundle\EventListener\TimelineSubscriber -> addEvents ( object(LeadTimelineEvent), 'integration_sync_issues', 'Integration sync notice', 'fa-refresh', 'integrations' )
```

Probably could be related to another PR https://github.com/mautic/mautic/pull/11303

**Comment by escopecz** [comment]
@kuzmany thanks for reporting this!

@fedys please take a look.

**Comment by fedys** [comment]
@kuzmany I fixed the issue via https://github.com/mautic/mautic/pull/11686. Thanks for catching that!

**Pull request merged**
