### PR TITLE
Changed path for mautic tracking cookies to /

### PR DESCRIPTION
**Pull request by shershennm**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | x
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #6035 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Changed path for mautic tracking cookies to /

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Load page with Mautic tracking code
2. Check cookie path on JS load - current page path

#### Steps to test this PR:
1. Load page with Mautic tracking code
2. Check cookie path on JS load - `/` path

### CODE REVIEW

**Comment by escopecz** [comment]
Could you please elaborate on how to test this properly? What ajax call are you talking about in the issue? A real world example would be very helpful.

But if this is breaks BC then there is small chance for a merge in Mautic 2.x.x. Please provide more info about this too.

**Comment by shershennm** [comment]
For example, I have a page (not with root path, for example `/site/test`) with installed mautic tracking code. When a user lands on this page, tracking code makes the request to mautic and after that sets mtc_id and mtc_sid cookie with current page path. At this page I need to make request to my backend with XMLHttpRequest, $.ajax, axios, etc, and I am waiting for this cookies at backend, but it doesn't exist, because it was set with current page path. 
It doesn't break BC

**Comment by shershennm** [comment]
Sorry for this. I forget to remove it. The table is correct now

**Comment by mattlevine** [comment]
This would be fantastic to have fixed!

**Pull request merged**
