### PR TITLE
TPROD-338 - OutlookBundle - Migrate PHP Templates to Twig Templates

### PR DESCRIPTION
**Pull request by JoshuaEstes**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Navigate to Settings -> Plugins
3. Click on the Outlook plugin
4. Verify the bottom of the modal content is rendered correctly. Only the gray box was converted

### CODE REVIEW

**Review by mabumusa1 — DISMISSED** [review]
- [X] The modal worked as expected 

image

**Comment by mabumusa1** [comment]
@JoshuaEstes please increase the coverage so we can merge this

**Comment by JoshuaEstes** [comment]
@mabumusa1 Tests added to increase code coverage https://github.com/mautic/mautic/pull/11959/commits/ebfc73e86745551fb32489f782883c5a06947d21

**Comment by mabumusa1** [comment]
@JoshuaEstes `Stan` needs some love. I think this PR is good to go once we get all CI green

**Comment by JoshuaEstes** [comment]
@mabumusa1 This should do it.

**Comment by sdoering** [comment]
Tested it succesfully:

image

**Review by mabumusa1 — APPROVED** [review]
This PR is good to go, we have two tests

**Pull request merged**
