### PR TITLE
Various fixes with token in URL

### LINKED ISSUE #6011: Trackable URL in emails breaking dynamic fields in href links
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When Tracking URLs are enabled and I try to create a link with a dynamic field in it, the trackable URL doesn't render dynamic fields like this `{formfield=name}` properly inside HTML A tags.

If I disable the trackable links in `Configuration > Email Settings > Disable trackable links > Yes`, then the dynamic content in an HREF link works. 

**Example WITHOUT trackable links enabled:**
`<a href="https://example.com/?name={formfield=name}">{formfield=name}</a>`
Converts to:
`<a href="https://example.com/?name=John">John</a>` 😀 

**Example WITH trackable links enabled:**
`<a href="https://example.com/?name={formfield=name}">{formfield=name}</a>`
Converts to:
`<a href="https://example.com/?name=%7Bformfield=name%7D">John</a>` 😞 

The issue might be in this file:

> `/app/bundles/EmailBundle/EventListener/BuilderSubscriber.php`

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.1.16

This might be related to this issue as well: #3825
 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/57655431-trackable-url-in-emails-breaking-dynamic-fields-in-href-links?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #8446: URLs don't replace tokens
## Bug Description
When sending transactional emails, urls may be dynamic. If the configuration is set to allow tracking clicks on urls, then Mautic does not replace tokens in the url, it only replaces them in the text.

Here's a sample email

```
<a href="https://example.com/email/verify/{EMAIL_VERIFICATION_CODE}" rel="noopener noreferrer" target="_blank">https://example.com/email/verify/{EMAIL_VERIFICATION_CODE}</a>
```

This results in:

```
<a href="https://mautic.example.com/r/hadshedcontent?ct=jkgqfyegwkfyg" rel="noopener noreferrer" target="_blank">https://example.com/email/verify/theTokenValue</a>
```

The redirected url is:
```
https://example.com/email/verify/%7BEMAIL_VERIFICATION_CODE%7D
```

| Q   | A
| --- | ---
| Mautic version | 2.16.0
| PHP version | 7.1
| Browser | Chrome

### Steps to reproduce
1. Create an email with an "A" tag with href containing a token
2. Send the email
3. URL does not have the token replaced.
4. Disable link tracking and the token in the URL gets replaced as expected.
 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/88593192-urls-don-t-replace-tokens?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | Fixes #8446
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR resolved servera issues with tokens in url.

1, Noticed If we use in href token with modifier:

`<a href="{pagelink=1}?special={contactfield=email|true}&date={contactfield=email}">my link</a>`

froala change it to 

`<a href="{pagelink=1}?special={contactfield=email%7Ctrue}&date={contactfield=email}">my link</a>`

2, Pagelink token is note replaced with link to page

- `<a href="{pagelink=1}?website={contactfield=website}">website</a>` 

Now working versions are:

- `<a href="{pagelink=1}?website={contactfield=website}">go to page</a>`
- `<a href="{contactfield=website}?email={contactfield=email}">go to website</a>`

3. sanitizeUrlQuery doesn't work If query already have ? symbol

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create email and add HTML 
`<a href="{pagelink=1}?website={contactfield=website}">got to link </a> <br /> 
<a href="{contactfield=website}">go to website</a>`
- add UTM tags to emal
- website in contact profile add as http://domain.tld/?some=example
2. Reopen HTML from wysiwyg  and you see encode `{contactfield=email%7Ctrue}` (first bug)
3. If you send email, these tokens are not like you expected
- `{pagelink=1}` is trackable, but redirect is 404 with `{pagelink=1}` in URL
- `{contactfield=email%7Ctrue}` is also not replaced with contact email address
- `{contactfield=website}` were created as redirect URL, but redirection is to wrong address with encoded symbols `http://domain.tld?some%3Dexample%3Futm_source%3Dtest&utm_medium=newsletter`. We expect `http://domain.tld?some%3DexampleF&utm_source=test&utm_medium=newsletter`

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com/7548)
2. Repeat all steps and see If token is replaced correctly and redirection works

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/7548"></a>

### CODE REVIEW

**Review by npracht — DISMISSED** [review]
Tested and running in production environment.

**Comment by RCheesley** [comment]
Tried to follow the instructions and found the following:

- No problems with editor changing the code at all, whether I add directly by copy/pasting in the editor, or in code mode
- Links are not 404'ing but going as expected to the Mautic landing page, or the contact URL - header: GET 
http://local.mautictest/@vcs/mautic/testing-7424?special=ruth%2Bmeep%40domain.co.uk&date=ruth+meep@domain.co.uk
Status: HTTP/1.1 200 OK
- Visits to the Mautic landing page don't seem to be getting tracked in Mautic (tried in incognito window)
- No UTM tags were appended despite being provided (possibly due to not inserting the links with the Add url feature in the editor but following instructions above and copy/pasting?)
- Initial email (the one with |true) has special characters replaced e.g.?special=ruth%2Bmeep%40domain.co.uk&date=ruth+meep@domain.co.uk) but the second email address in the link (in the date field) is properly formatted

Note: The email part referenced earlier in the issue report (point 1) is not included in the test instructions

So a bit stuck, as I can't seem to reproduce the problems being reported pre-patch!

**Comment by RCheesley** [comment]
I have just tried to test this again using Mautibox and I am finding these issues:

* Links are not including the UTM tags
* Clicks on the links once sent via email are not being reported in Mautic (using Mautibox / Mailhog)

Here's a short walk through: https://youtu.be/TinprFxlisY (sorry for the poor audio on the last part)

@kuzmany perhaps you can take a look and point out where I'm going wrong or what might be missing from the steps I've been following.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
Please can you address the conflicts @kuzmany ? Thanks!

**Comment by RCheesley** [comment]
Bumping to 3.1.1 due to failing Travis build.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by heroic** [comment]
@kuzmany Is this still on track for 3.1.1?

**Comment by mabumusa1** [comment]
@kuzmany what is missing for this PR? do you think we can merge it with the next release?

**Comment by RCheesley** [comment]
Looks like Travis is failing on this PR, @heroic have you been using this in production? We have yet to get positive tests on this and I struggled back when I was testing this PR last year and again in March. It would be great to hear if folk are actually able to confirm this PR works as expected and are able to do all the things that are suggested in the description. I'll look at testing it again myself tomorrow.

**Comment by heroic** [comment]
@RCheesley i haven't used this yet

**Comment by RCheesley** [comment]
Hi folks, we are bumping this to 3.1.2 to allow time to fix the Travis issue and get this tested.

@kuzmany this will need to be done by **18th October** to be considered.

**Comment by mabumusa1** [comment]
@kuzmany when you have time, please take a look at this PR, it fixes multiple issues and it would be great to have it merged in the next release

**Comment by heroic** [comment]
Any updates on this? We're not able to use url tracking and hence drip campaigns because of this

**Comment by kuzmany** [comment]
Rebased and resolved conflicts.
We use it in production.

**Comment by RCheesley** [comment]
@kuzmany could you take a look at the failing tests?

**Comment by npracht** [comment]
@kuzmany can you have a look at tests issue please ?

**Review by danilovq — COMMENTED** [review]
I checked the patch. Generally it works, but I see the following problem: if the RedirectEvent listener is implemented then all bundles tokens must be replaced in bundle event subscriber separately and not in Page bundle controller code.

**Comment by kuzmany** [comment]
@danilovq I've added it to PageRedirectSubscriber

https://github.com/mautic/mautic/pull/7548/files#diff-f06a3f92c9829ff597a99ac3d0f0f876784f3e08c0a79cb3c5fa47763837079c

**Comment by RCheesley** [comment]
@kuzmany this one has conflicts to be addressed

**Comment by dennisameling** [comment]
Hi @kuzmany! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since this PR has conflicts now, could you please do a `git merge upstream/features` locally to resolve the conflicts? Thanks in advance!

**Comment by RCheesley** [comment]
Bumping from the release due to lack of testing and conflicts.

**Comment by escopecz** [comment]
@kuzmany do you plan to finish this PR or can we close it?

**Comment by RCheesley** [comment]
As there has not been any response and this PR was started in 2019, let's close it. We can always re-open in the future but I expect it will need re-creating by that time anyway!

**Comment by kuzmany** [comment]
@RCheesley  I am okay with close it, just wanted to note for other devs we use it on production, then issues (or some of them) still persist

**Pull request closed without merging**
