### PR TITLE
Updated Japan Flag

### PR DESCRIPTION
**Pull request by mining016**
Japan flag white background was mixing with background of webpage so it was looking only red dot. Added border across flag for correct conveying country flag.

**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | No 
| Automated tests included? | Not Required
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Only Japan Flag image is updated with border so white background of webpage and flag do not get mixed. 

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by RCheesley** [comment]
@mining016 can you give a short explanation of how to see the problem in action and how to test? I confess I don't really know where the image file is used!

**Comment by mining016** [comment]
> @mining016 can you give a short explanation of how to see the problem in action and how to test? I confess I don't really know where the image file is used!

Hi,
In mautic there is a country flag indicating country of lead. Japan flag is having white background and red dot in middle. In mautic there is also white background which mix with the flag of Japan and indicating as just red dot which is confusing user.  So i have updated existing flag file and added border across the flag. 

To recreate situation you just need to add lead from Japan and you will see in contact list the flag will show just red dot . Border across the flag will fix the flag. 

Thank you

**Comment by mining016** [comment]
> @mining016 can you give a short explanation of how to see the problem in action and how to test? I confess I don't really know where the image file is used!

Sir any update? 
It is just added border in Japan flag to prevent it mixing with background of Mautic.

**Review by RCheesley — APPROVED** [review]
Thanks for making this PR @mining016 - confirm that without the PR the flag associated with contacts that have the country set to Japan disappears into the background somewhat. 

screenshot-local mautic3-2020 08 15-14_51_47

After applying the PR, the box around the flag makes it much easier to see!

screenshot-local mautic3-2020 08 15-15_46_28

**Review by dennisameling — APPROVED** [review]

**Pull request merged**
