### PR TITLE
Bugfix for Points Triggers

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | n
| Related user documentation PR URL | n
| Related developer documentation PR URL | n
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/3235
| BC breaks? | n
| Deprecations? | n

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Point triggers never fired..
https://github.com/mautic/mautic/issues/3235

#### Steps to test this PR:
1. Create Points Trigger, set points to 1, set event to Create Tag, save
2. Generate new Contact from form submission, ensure Points Action allocates >1 points
3. Check contact to see if Tag has been added

### CODE REVIEW

**Comment by mqueme** [comment]
same here, it did not work the first time, but it did the second time.

**Comment by escopecz** [comment]
Works when the contact is created now. Thanks Mars!

**Comment by thecodeine** [comment]
Hello,

regarding to "it did not work the first time", in my opinion is caused by (line 483):

`$current = ($oldValue) ? $oldValue : $this->$getter();`

Check http://php.net/manual/en/types.comparisons.php as referance. So when Lead has 0 points `$current` variable will be equal to actual number of points. Thats why it's not working for the second time. 

```
$oldValue = (int) null; // 0
$current = ($oldValue) ? $oldValue : 'current_value'; // current_value
```

Best

**Comment by escopecz** [comment]
Yea, Marianela fixed it in the last commit.

**Pull request merged**
