### PR TITLE
Add link to profile for integration

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging 
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Allow add link to object for linked integration in contact profile.

image

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Just code review is enought

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Review by mabumusa1 — APPROVED** [review]
The code looks logical and gets the required logic implemented

**Comment by mabumusa1** [comment]
@RCheesley please review to get this PR merged. I checked the code and looks to do the job

**Comment by RCheesley** [comment]
@mabumusa1 as this is a feature, it will be considered for inclusion in 3.2 rather than 3.1.1. I've assigned it to the correct milestone accordingly.

@kuzmany please make sure you only add features and enhancements to minor rather than patch releases, per semver.org.

**Pull request merged**
