### PR TITLE
Ui refresh

### PR DESCRIPTION
**Pull request by mqueme**
## Description
Pull Request from previous #1502 
## Steps to test

### CODE REVIEW

**Comment by escopecz** [comment]
Looks good. But what was the reason to remove search boxes?

**Comment by alanhartless** [comment]
That's something that still needs to be worked out I think.

https://github.com/mautic/mautic/pull/1502#issuecomment-192428539

**Comment by mqueme** [comment]
I readded the search on leads

**Comment by alanhartless** [comment]
@mqueme Can we add back the list filters to all of the pages (not just leads) then we can merge this. We'll push the list filter changes to another release.

**Comment by mqueme** [comment]
Search is back.

**Comment by dbhurley** [comment]
+1 this works for me.

**Comment by escopecz** [comment]
Yep, search boxes are back :+1:

**Pull request merged**
