### PR TITLE
WIP: Convert2codecption

### PR DESCRIPTION
**Pull request by cykonetic**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes. Currently codeception is only functional at the root of the project. I would like to extend is functionality to all bundles.
| New feature? | Sort of. codeception is already part of the project. I hope to expand its usefulness by expanding it's capabilities.
| Automated tests included? | It is a test framework...
| Related user documentation PR URL | I hope to get these tests to function as currently described in the documentation
| Related developer documentation PR URL | As per the phpunit and codeception docs
| Issues addressed (#s or URLs) | 
| BC breaks? | No. the goal is to not break anything, just make the existing work as designed
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description: This goal is to properly enable the codeception tests while maintaining the current phpunit functionality. I also believe I can make these tests perform better.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Run composer test after setting up the correct .env file

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by npracht** [comment]
Hi @cykonetic & @escopecz what do we do with that ?

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@cykonetic are you still working on this? It has a bunch of conflicts to be resolved at the moment!

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
As we are planning to move away from Codeception I am going to close this PR down. Thank you for making the contributions, if you'd like to help us with implementing Cypress or working on unit testing we'd love to hear from you - just hop into slack (get an invite at https://mautic.org/slack) and join the #t-product channel!

**Pull request closed without merging**
