### PR TITLE
New webhook: Contact Company Subscription Change 

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
New webhook event send when contact's companies are changed (added/removed).

Response return 
- added (true or false in case if company is removed from contact)
- contact object
- company object in this event (added/removed)

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create webhook with **Contact Company Subscription Change Event** (test endpoint could be take from webhook.site)
image
3. Try create contact + assign/remove companies
4. Check webhook.site if your response contains
- added (true or false if removed)
- contact
- company 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebsed

**Review by mabumusa1 — DISMISSED** [review]
I tested this PR, it works as expected I got a webhook on company change and it included the company that got added correctly to the contact

**Review by RCheesley — DISMISSED** [review]
Tested and works great - adding and removing companies - and the content includes the information about both the company and the contact.

Thanks for the PR @kuzmany 🙇

**Comment by RCheesley** [comment]
Marking this as RTC subject to the checks being passed successfully - I have a suspicion it might possibly need tests but we'll see!

**Comment by dennisameling** [comment]
@kuzmany I just added a test for this PR, if Travis/Codecov pass this is RTC 👍

**Review by dennisameling — APPROVED** [review]

**Pull request merged**
