### PR TITLE
 Allow to exclude campaigns and segments from processing.

### PR DESCRIPTION
**Pull request by biozshock**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ x ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Commands: `mautic:campaigns:trigger`, `mautic:campaigns:rebuild`, `mautic:segments:update` allow to exclude processed entities.
4.x version: #13382 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create at least 2 campaigns and segments.
3. `mautic:campaigns:trigger`, `mautic:campaigns:rebuild`, `mautic:segments:update` with new `--exclude` option and check that excluded campaign(s)/segment(s) were *not* executed.

### CODE REVIEW

**Review by kuzmany — APPROVED** [review]
It works as expected 👍 
Code looks good 🫰

**Review by MadlenF — APPROVED** [review]
Works as expected 👍

**Review by LeonOltmanns — APPROVED** [review]
Works like a charm! :)

**Comment by RCheesley** [comment]
@biozshock this PR needs docs - probably user docs if there isn't anything dev-docs related?

Can you please help by making the PRs? I think it needs to be done on the cron jobs page: https://docs.mautic.org/en/5.x/configuration/cron_jobs.html

cc @mautic/education-team for the 5.1 release.

**Comment by biozshock** [comment]
@RCheesley see https://github.com/mautic/user-documentation/pull/293

**Pull request merged**
