### PR TITLE
Fix Timeline View Filters Broken issue

### PR DESCRIPTION
**Pull request by dadarya0**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | No 
| Automated tests included? | No 
| Related user documentation PR URL | No
| Related developer documentation PR URL | No
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

The SalesForce UI Timeline Filters do not display correctly.  When viewing this particular timeline if you select a filter the screen contents distort and do not properly filter the data

image

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1.  It cannot be navigate from dashboard. It’s meant to be embedded via iframe to other systems  But you can go to the same route and use any contact ID at the end and should get to it.
2. use url {Instance URL}/s/plugin/Salesforce/timeline/view/{Contact ID}
Use contact ID that exists in your instance If you don’t have any then go to the Contacts menu item and create one.
3. Page becomes unresponsive and screen contents will be distort after selecting a filter.

#### Steps to test this PR:
1.  It cannot be navigate from dashboard. It’s meant to be embedded via iframe to other systems  But you can go to the same route and use any contact ID at the end and should get to it.
2. use url {Instance URL}/s/plugin/Salesforce/timeline/view/{Contact ID}
Use contact ID that exists in your instance If you don’t have any then go to the Contacts menu item and create one.
3. Filter should be works fine.
 

#### Other areas of Mautic that may be affected by the change:
1. 
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by dadarya0** [comment]
@RCheesley this should be based on the staging branch or 4.0 branch ?

**Comment by RCheesley** [comment]
Features for now. We are doing a bunch of work this weekend on the Symfony 4 stuff and then we will merge that into the 4.0 branch and start to rebase at that point.

In the future it helps us a lot if you can make the PR's from your personal fork rather than the Acquia one, as the community are not able to work collaboratively on a protected organisation fork.

**Comment by dadarya0** [comment]
> Features for now. We are doing a bunch of work this weekend on the Symfony 4 stuff and then we will merge that into the 4.0 branch and start to rebase at that point.
> 
> In the future it helps us a lot if you can make the PR's from your personal fork rather than the Acquia one, as the community are not able to work collaboratively on a protected organisation fork.

OK, will take care from next time.

**Comment by dennisameling** [comment]
Hi @dadarya0! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since we don't have access to your branch, could you please click "Update branch" at the bottom of this PR? If that doesn't work, you can also run `git merge upstream/features` locally. Thanks in advance!

image

**Review by kuzmany — APPROVED** [review]
From context understand and should works 👍

**Review by npracht — APPROVED** [review]
It works for me too 👍🏽

**Pull request merged**
