### PR TITLE
DPMMA-903 Change campaign trigger order

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ N ]
| New feature/enhancement? (use the a.x branch)      | [ Y ]
| Deprecations?                          | [ N ]
| BC breaks? (use the c.x branch)        | [ N ]
| Automated tests included?              | [ Y ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:
This PR changes the order of the campaigns processed by the `mautic:campaigns:trigger` command. The campaigns will be processed from the newest to the oldest.

With this change the most recent campaigns would be processed faster.

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Add two campaigns
4. Run the trigger command `ddev exec bin/console mautic:campaigns:trigger`
5. The second  campaign should be processed first
```
Triggering events for campaign 2
Triggering events for newly added contacts
0 total events(s) to be processed in batches of 100 contacts
....
Triggering events for campaign 1
Triggering events for newly added contacts
0 total events(s) to be processed in batches of 100 contacts
```

### CODE REVIEW

**Review by kuzmany — DISMISSED** [review]
Why not. Approve it

**Review by escopecz — DISMISSED** [review]
I also see no problem with this 👍

**Comment by escopecz** [comment]
Please rebase on top of the 5.1 branch as this is an enhancement. 5.0 (or 5.x at the moment) will get only bug fixes.

**Comment by patrykgruszka** [comment]
Right, just this rebased on 5.1

**Review by escopecz — APPROVED** [review]

**Comment by RCheesley** [comment]
Small docs PR https://github.com/mautic/user-documentation/pull/294

**Pull request merged**
