### PR TITLE
Campaign email click decision

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | n
| New feature? | y
| Related user documentation PR URL | n
| Related developer documentation PR URL | n
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/1126 https://github.com/mautic/mautic/issues/124  https://github.com/mautic/mautic/issues/1653
| BC breaks? | n
| Deprecations? | 

[//]: # ( Required: )
#### Description:

PR add campaign click decision, similar to emails open decision.

#### Steps to test this PR:
1. Apply PR
2. Create campaign with send email and add click condition
3. Test without Limit to Urls contains (apply to any link in email)
4.  Test with Limit to Urls contains (apply to matched keyword)

image

### CODE REVIEW

**Comment by jdecampos** [comment]
Hello,
As far as the decision click, where is it?
Is there a need for further development? If so, we can work on it

**Comment by kuzmany** [comment]
@escopecz ready for tests ;)

**Comment by jdecampos** [comment]
+1

**Comment by luizeof** [comment]
@escopecz this will be on 2.10 release?

**Comment by escopecz** [comment]
It will have to go through the review and test process, but it should be. Can you test if it works for you? It'd help.

@kuzmany can you fix the merge conflict, please?

**Pull request merged**
