### PR TITLE
Merging of grapesjs with history

### PR DESCRIPTION
**Pull request by nickveenhof**
This should pull in grapesjs mautic3x branch with history into mautic.

To test this PR:

1. Clone the features branch
2. Delete the references to the GrapesJS builder in composer.json and composer.lock so that we do not have the folder on installation
3. Check out this PR
4. Go to plugins and enable GrapesJS (you might need to install plugins depending on how you installed Mautic) and refresh the page to check that it has been enabled successfully
5. Create new email and landing pages - confirm that the new builder is working as expected

### CODE REVIEW

**Review by RCheesley — DISMISSED** [review]
Works as expected - new builder is available and can be enabled. Works in email and in the landing pages.

**Comment by dennisameling** [comment]
@nickveenhof just FYI - I added two commits to fix the plugin from missing in the `.gitignore` exclusions (otherwise I couldn't make any commits to it) and to declare PHP 8.0 support (we'll test later if it _actually_ works on PHP 8, but for now it blocks the installation at https://github.com/mautic/mautic/pull/9969)

**Comment by mabumusa1** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@mabumusa1 don't worry about the clabot - it is an old, unsigned commit so we can manually approve this!

**Comment by dennisameling** [comment]
@RCheesley Can we please merge this PR already? @mabumusa1 was adding commits to add tests, but it broke the CS fixer (completely unrelated to his tests). I just removed those commits so the PR is in a mergeable state again, then @mabumusa1 will create a separate PR to add the tests 👍🏼

**Comment by RCheesley** [comment]
We have a PR coming to add the tests so that we get the coverage back up, so let's get this merged so that work can proceed.

**Review by RCheesley — APPROVED** [review]

**Comment by mabumusa1** [comment]
Automated Tests are WIP under the PR #10006 10006

**Pull request merged**
