### PR TITLE
DPMMA-375 Alert variant styles

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ N ]
| New feature/enhancement? (use the a.x branch)      | [ Y ]
| Deprecations?                          | [ N ]
| BC breaks? (use the c.x branch)        | [ N ]
| Automated tests included?              | [ N ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR includes: 
- Different styling for warning and error alerts to make them more noticeable.
- Bold and lighter font colour for links in alerts for better visibility
- Make the hover transition brighter instead of darker because the alert background is dark.

Current alert for all types:
image

New Notice (standard):
image

New Error:
image

New Warning (not sure if is used anywhere now, but I think it could be useful):
image

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Test different alert types (Error alert can be triggered using invalid email for contact. I'm not sure how to trigger warning without code changes).

### CODE REVIEW

**Review by Mike-Dropsolid — APPROVED** [review]
Looks good. Nice UX improvement!

**Comment by RCheesley** [comment]
@patrykgruszka could you rebase this one to 5.1 please, as it will be merged in that release. Might need to touch base with @andersonjeccel to determine if it impacts the new UX though.

**Comment by andersonjeccel** [comment]
It's possible that changes made in the dropdown could be overwritten by the changes I made in my pull request to align to the design system

Also, I'm sure that the @font-face code will be fully replaced

@RCheesley

**Comment by patrykgruszka** [comment]
@RCheesley are you sure about the rebase? I think that we should use 5.x at this point for new features. 

@andersonjeccel I've removed the font-face and dropdown changes. This was auto-generated by grunt script anyway, it's not needed in this PR.

**Comment by RCheesley** [comment]
Ah shoot sorry you're totally right @patrykgruszka ... sorry was a long day yesterday! 🤦

**Review by PatrickJenkner — APPROVED** [review]
Looks good and works just as described 👍

**Comment by escopecz** [comment]
This seem to be a duplicate of https://github.com/mautic/mautic/pull/10819. Which one shall we go with?

**Review by escopecz — APPROVED** [review]
The code is fine 👍 Thanks!

**Pull request merged**
