### PR TITLE
[UX] No data found message for dashboard charts

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR returns a message "No data found" when a chart is empty instead of just leaving everything blank (which seemed broken/faulty/buggy).

image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open the Dashboard and check the widgets that don't have data

### CODE REVIEW

**Review by patrykgruszka — APPROVED** [review]
The code changes look good. I tested them on GitPod, and everything works well :+1:

**Review by Esthertests — CHANGES_REQUESTED** [review]
This works except for the recent activity chart which is still empty 
image

**Comment by andersonjeccel** [comment]
Good catch, I'll leave the custom widgets for another PR to avoid mixing several kinds of changes 

@Esthertests Thanks for testing!

**Comment by RCheesley** [comment]
@andersonjeccel is there another PR for the custom widgets yet? If not let's raise an issue just so we don't lose sight of adding this new message for those widgets, too. Just waiting on the tests to pass after merging in the other PRs then we can merge.

**Comment by andersonjeccel** [comment]
@RCheesley Hm, not yet
Would you be up for creating the issue?

**Comment by RCheesley** [comment]
Sure thing, the issue is https://github.com/mautic/mautic/issues/14072.

**Pull request merged**
