### PR TITLE
Contacts custom field tags

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Yes
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
We are thinking about  create new custom contact /company field tags.  But before start working on it, we need open discuss with Mautic core team.

@alanhartless @npracht 

Questions is: Current tags feature migrate as contact custom field? Or tags  leave in current mode, just add new custom field type (tags) what is easier for us :)? 

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. 
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by npracht** [comment]
Yes @kuzmany @alanhartless the tags field type is very useful and it would be awesome as a user to be able to have different fields of this type.

**Comment by npracht** [comment]
Hi @alanhartless !
We'd like to contribute but we need feedbacks from the core team to be able to work in correct conditions. Could you please advise or tell to whom refer?

Thanks,
N.

**Comment by alanhartless** [comment]
I don't understand the feature. Current tags are a one to many relationship and cannot be converted to a custom field. Also naming a custom field `tags` will collide with the existing `tags` fields in forms, API, etc.

**Comment by kuzmany** [comment]
@alanhartless mean something like grouping of tags for contact:
Fav colours:
Fav futball club:

Custom field tag will use different alias (as another custom fields) and use same database like tags.

**Comment by alanhartless** [comment]
I'm still not understanding the use case. Wouldn't you just use a standard custom field or maybe a multi-select for those two scenarios?

**Comment by npracht** [comment]
The issue with standard custom field @alanhartless is that you have to define values to have suggestions or then it is totally free.
The suggestion of existing values but freedom of adding any is a very nice feature.

**Pull request closed without merging**
