### PR TITLE
Added link to notification errors for integrations and made notification errors for campaigns usable in listeners

### PR DESCRIPTION
**Pull request by mqueme**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
when adding a notification to the notification window whenever there is a Salesforce error, it would not show due to it not being assigned to a user. Also this adds a link to contact that is erroring when trying to push to SF
[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Try running CLI command to sync contacts in SF, if there is an error a notification in Mautic's notification window should appear, but doesn't 

#### Steps to test this PR:
1. The notification should now appear, with a link to the contact that had the error

### CODE REVIEW

**Comment by alanhartless** [comment]
@mqueme Can you test this? I had similar code and so merged it into this one. It only records API errors (so that code exceptions don't show up in the notifications for users), allows use by any integration, and makes the contact link congruent.

**Comment by mqueme** [comment]
Worked for me @alanhartless Thanks!

**Comment by mqueme** [comment]
I just fixed some errors I got on the link for contact in the notification window. after that, looks good.

**Comment by escopecz** [comment]
If I comment out https://github.com/mautic/mautic/blob/staging/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php#L1192 and run the command I get the same error as in #3925. But the notification shows up, which is good:
sf-notification
But it's not clickable. It does not contain any link:
```
<div class="media pt-sm pb-sm pr-md pl-md nm bdr-b notification" id="notification199">
    <span class="pull-left mt-xs" style="width:36px">
                        <i class="fa fa-2x text-danger fa-exclamation-circle" data-toggle="tooltip" title="" data-original-title="mautic.notifications.type.Salesforce"></i>
            </span>
    <a href="javascript:void(0);" class="btn btn-default btn-xs btn-nospin pull-right do-not-close" data-toggle="tooltip" title="" onclick="Mautic.clearNotification(199);" data-original-title="Clear this notification"><i class="fa fa-times do-not-close"></i></a>
            
        <div class="media-body">
                    <div class="media-heading fw-sb mb-0 text-primary">exception 'Mautic\PluginBundle\Exception\ApiErrorException' with message 'The Id field should not be specified in the sobject data.' in plugins/MauticCrmBundle/Integration/SalesforceIntegration.php:1253
Stack trace:
</div>
                <div>Salesforce Error</div>
        <div class="clearfix mt-xs">
            <span class="fa fa-clock-o text-success pull-left mr-xs"></span>
            <span class="fs-10 text-muted pull-left">Today, 11:37 am</span>
        </div>
    </div>
</div>
```

**Comment by mqueme** [comment]
I think it doesn't contain an error because this is not tied to a specific Contact, it's more of a request error.

**Comment by mqueme** [comment]
After applying this PR companies still showed for me, so as @escopecz says if it helps on some network configurations, I am merging this.

**Comment by escopecz** [comment]
So the problem for me was that `id__Lead` SF field was mapped to Mautic's `zipcode` field. When it was unmapped, the notification with the link showed up correctly.
screen shot 2017-05-05 at 15 47 22
👍

**Pull request merged**
