### PR TITLE
Minify HTML email

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR added  new option to enable minify HTML output during the sending. It should increase deliverability of email 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Go to Config   and Email Settings and enable Minify HTML

image

3. Send broadcast email or campaign email
4. Check email source If was minified. 
5. Check If all tokens was replaced properly

### CODE REVIEW

**Comment by escopecz** [comment]
@kuzmany similar here. `app/bundles/EmailBundle/Views/FormTheme/Config/_config_emailconfig_widget.html.php` has been removed with the Twig refactoring.

**Comment by escopecz** [comment]
@kuzmany @npracht I haven't heard about minifying helping the email deliverability yet. But it looks like it is a thing! I found this warning though:

> Minify your code. Minifying code will remove unnecessary spaces and comments. This can have a huge effect but **be careful as many ESPs enforce a maximum line length that could force a new line and break the code**.

__Source: https://www.sparkpost.com/blog/importance-file-size/__

Can you look into it? I worry this limitation could hurt us more than help

**Comment by npracht** [comment]
I don't know much about this limit. And I don't find literature about it.
Also i am not sure how a break line would break the code. In my basic HTML understanding, breaking a line (even a tag) is not an issue for rendering.

In conclusion, the benefit looks more important gaining ±25% of displayed content in Gmail & cie, than this risk.

**Comment by kuzmany** [comment]
Answer from ChatGPT

Yes, minifying HTML can have some advantages and disadvantages when it comes to sending marketing and transactional emails. 

Advantages of minifying HTML for email:

1. Faster loading times: Minifying HTML can help to reduce the size of the email, making it quicker to load for the recipient. This can be particularly important for transactional emails, which need to be delivered quickly and reliably.

2. Improved deliverability: Some email clients and spam filters may flag large emails as suspicious or spammy. By reducing the size of your email through minification, you can improve the chances that your email will be delivered to your recipient's inbox.

3. Improved readability: By reducing the amount of code in your email, you can make it easier to read and navigate for both humans and machines.

Disadvantages of minifying HTML for email:

1. Reduced readability: While minification can make HTML easier to read in some cases, it can also make it more difficult to understand and troubleshoot, especially for less experienced developers.

2. Risk of errors: Minifying HTML can introduce errors and bugs into your code if it's not done correctly. This can be particularly problematic if the email is mission-critical or time-sensitive.

3. Difficulty in making changes: Minified code can be more difficult to edit and update, which can be a problem if you need to make changes to your email on short notice.

Overall, whether or not to minify HTML for your marketing and transactional emails depends on your specific needs and priorities. If faster load times and improved deliverability are your top concerns, then minification may be worth considering. However, if readability and ease of editing are more important to you, then you may want to stick with uncompressed HTML.

Here are some sources that discuss the pros and cons of minifying HTML for emails:

1. "The Pros and Cons of HTML Minification" by Aaron Gustafson on A List Apart: https://alistapart.com/article/the-pros-and-cons-of-html-minification/

2. "Should You Minify Your HTML?" by Rachel Andrew on Smashing Magazine: https://www.smashingmagazine.com/2015/06/should-you-minify-your-html/

3. "The Pros and Cons of Minifying Your Code" by Aaron Peters on CSS-Tricks: https://css-tricks.com/the-pros-and-cons-of-minifying-your-code/

4. "Minifying HTML, CSS and JavaScript" on Google Developers: https://developers.google.com/speed/docs/insights/MinifyResources

**Comment by kuzmany** [comment]
Also Gmail has a size limit of 102KB for each email message. Once that limit is reached, the remaining content is clipped and becomes hidden behind a link to view the entire message. Every element making up the email, from the HTML to the written text and images, has an impact on file size.

**Comment by escopecz** [comment]
@npracht I found this as an indication it is a problem:

https://techcommunity.microsoft.com/t5/outlook/550-maximum-allowed-line-length-is-998-octets-got-1012/m-p/3615831

@kuzmany can you please confirm if the minification script removes "\n" characters and adds everything into 1 line? I can't tell based on the unit tests.

**Comment by mabumusa1** [comment]
@kuzmany please fix the conflicts, so we can start testing.

Personally, I agree with minification, I have not see any impact on delivery when the HTML was minified or not

**Comment by kuzmany** [comment]
@escopecz @mabumusa1 conflicts resolved

**Review by escopecz — DISMISSED** [review]
I see nothing wrong with the code. The only issue with this I described above with the long line. But since this is disabled by default it's simple enough for the users to try it and turn it off if it will cause issues. 👍

**Comment by escopecz** [comment]
@kuzmany I'm not sure if this is ready for testing, but there are some unrelated changes in the PR diff. Just in case you are not aware.

**Comment by kuzmany** [comment]
@escopecz do not see anything wrong? Probably you mean HTML, these files are related to unite tests.

**Comment by escopecz** [comment]
@kuzmany it happened to me today for another PR. I was looking at the last merge commit instead of the PR diff by clicking the GH email. There is nothing wrong with the PR diff code.

**Review by mabumusa1 — APPROVED** [review]
Code changes looks good, I tested and HTML and CSS got minified

**Review by jos0405 — APPROVED** [review]

**Comment by jos0405** [comment]
Does what it promises: minifies CSS and HTMl without impacting the code outcome.

image

**Pull request merged**
