### PR TITLE
Add additional checks to installation + update process 

### LINKED ISSUE #9607: Add checks from Mautic 3.x upgrade script into the install and upgrade process
## Description
We frequently see people having problems with installing and/or updating Mautic because there are issues with their server resourcing or configuration.

In the Mautic 3 upgrade script we have a [pretty comprehensive set of checks](https://github.com/mautic/mautic/blob/2.16/upgrade_v3.php#L137) that are run to determine whether the environment is suitable, however **we do not yet have all of these introduced into the regular install and upgrade process**.

### This would help users because: 

- it would proactively prevent people from updating where there is a risk of it not being able to complete, 
-  it gives us an opportunity to dramatically improve the messaging we provide to these users, pushing them to relevant documentation which helps them to understand 
    - what the problem is, 
    - why they are being warned about it or blocked from updating, 
    - what to do about it, and 
    - where to get help if they are stuck.

### This would help the project because:
-  As we move to introduce new features such as Composer 2 support and the Mautic Marketplace, the requirements for Mautic to run are going to become somewhat higher. 
- We need to start setting expectations and prompting people to start dealing with those instances where the environment is not suitable sooner rather than later.
- We should be consistent with checking across migrations and install/upgrade processes
- It will help us in the future when we introduce other updates/requirements to be able to have these checks in place

If you would like to work on this issue please:

1. Join #i-install-upgrade on Slack (https://mautic.org/slack for an invite to Slack)
2. Ping in the channel and ask to be assigned
3. Take inspiration from the work that has been done already in the [Mautic 3.x upgrade script](https://github.com/mautic/mautic/blob/2.16/upgrade_v3.php#L137)
4. Create a WIP PR and mention that it resolves this issue. 
5. Create a WIP PR for the [Mautic Docs](https://github.com/mautic/mautic-documentation) to add relevant information about any error messages a user might encounter
6. Flag up with the Education Team (#t-education on Slack) any resources that might be helpful to have in the knowledgebase or docs to support the errors that a user may encounter (eg changing server settings, updating PHP etc)

## Useful resources:
* [Contributing to Mautic](https://contribute.mautic.org/contributing-to-mautic/developer)
* [Mautic Docs](https://docs.mautic.org/en) & [Styleguide](https://docs.mautic.org/en/home/contributing)

## Technical details

This list aims to provide a comprehensive overview of the checks that were present in the Mautic 3 upgrade script, but not in Mautic's built-in installer and updater.

| Check | Present in installer? | Present in updater? | Level
| --- | --- | --- | --- |
| PHP version | yes | yes | error
| Using MySQL or MariaDB database driver*** | yes (#10459) | yes (#10459) | error
| MySQL/MariaDB version check | yes (#10459) | yes (#10459) | error
| Minimum Mautic version needed to upgrade to a specific version | n/a | yes | N/A (update won't be offered)
| Check if critical folders are writable by the webserver* | no | no | warning
| Check if there's enough free disk space to run the installation/upgrade | no | no | warning
| Ensure PHPs `max_execution_time` is at least 240 seconds**** | no | no | warning
| Check if Mautic's upgrade kill switch is enabled** | no | no | N/A

\* = this is a tricky one. Let's say the user has Apache as the webserver, but also has PHP installed on the CLI. It might very well be that Apache and the CLI are different OS users, meaning that they might clash in terms of filesystem permissions. If a user runs the `php bin/console cache:warmup` command on the CLI, it could be that the Apache user doesn't have write permissions in the same folder, leading to server errors for users.

** = the upgrade kill switch was put in place to allow the team to put a stop on users upgrading to the new version. It basically checks a URL and checks if a property called `killSwitchActivated` is set to `true`. Since Mautic 3, however, we use GitHub releases, and could simply choose to take a release offline by either removing it completely, or by converting it back to a draft. So the kill switch should no longer be necessary.

*** = the UI installer only shows `MySQL PDO` and `MySQLi` as options in the DB configuration step dropdown, but folks installing through the CLI can provide any Doctrine driver they want, and Mautic won't complain (but probably crash at some point during or after installation). 

**** = some parts of Mautic use `ini_set('max_execution_time', ...)` to set the execution time to 300 seconds. This is not very reliable as it might be blocked in shared hosting environments (so we should probably check for it and throw an error/warning instead)

**Other checks that might be good to have but that weren't present in the Mautic 3 upgrade script are:**
- Check if the user is running Linux or macOS. PHP on Windows is rapidly becoming more uncommon [thanks to WSL2](https://docs.microsoft.com/en-us/windows/wsl/about). **We could already mention this in the Mautic 4 upgrade docs maybe?**
- The current "database backup" feature in the installation process is rather buggy and there are reports of users complaining about it. The Product Team should decide whether they want to keep this feature or simply remove the whole database (if it exists) prior to a clean installation. Of course, that should happen with a large warning before proceeding.
- Check if plugins are compatible with the new Mautic version or whether they might cause conflicts (becoming more relevant when the Marketplace goes live)

## Important note

Currently, Mautic has a standalone `upgrade.php` file which is cricital during the upgrade process. Much logic could and should be re-used from Mautic's bundles, but having the standalone file has a great benefit, namely that in case we need to move around Mautic's folder structure (which happened in the M2 > M3 upgrade), we actually can do that without breaking the world. A good strategy should be found to keep the ability to have a standalone upgrade script, without having to squeeze all logic into a single file.

On top of that, Mautic currently doesn't fully follow [Symfony's recommended folder structure](https://symfony.com/doc/current/configuration/override_dir_structure.html), which has a `public` folder that's the only publicly accessible directory. This is considered good security practice, because it prevents a lot of potential security issues. In Mautic's folder structure, the root folder is accessible by default (legacy) but the team partly worked around that by creating `.htaccess` files in e.g. the `vendor` folder so it's not publicly accessible over the internet. However, `.htaccess` files can only be processed by the Apache webserver and doesn't work with Nginx. This is a potential security risk for folks that don't know what they're doing.

### LINKED ISSUE #10472: Mautic shows it's running the latest version when new version requires higher PHP version
### Mautic Version

3.0.0 and later (including Mautic 4)

### PHP version

7.3.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When running Mautic 3.x and PHP 7.3, Mautic doesn't inform the user that Mautic 4 is available. This is because the minimum PHP version in Mautic 4 is 7.4, so the update logic simply marks Mautic 4 as "incompatible" and skips it. This way, users will never know that Mautic 4 is available, unless they upgrade to PHP 7.4.

This problem is caused by the following code snippet:

https://github.com/mautic/mautic/blob/bf37c06008a936fe9e2919b4baa2d3220cfb6ad1/app/bundles/CoreBundle/Helper/Update/Github/ReleaseParser.php#L54-L60

I'm considering to include a fix for this bug as part of the work in https://github.com/mautic/mautic/issues/9607.

### How can we reproduce this issue?

Step 1: Install Mautic 3.2.0 or later on PHP 7.3
Step 2: Open the dashboard. No notification shows up that a new version is available.
Step 3: To double-check, run this on the command line:

```
$ php bin/console mautic:update:find
Great! You are running the current version of Mautic.
```

Step 4: Switch to PHP 7.4
Step 5: Re-run the CLI command above. Mautic now tells you that version 4 is available:

```
$ php bin/console mautic:update:find
Version 4.0.0 of Mautic is available for download. Please visit https://github.com/mautic/mautic/releases/tag/4.0.0 for more information.
To update, you can run 'php bin/console mautic:update:apply' from the command line.
```

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dennisameling**
~⚠️ **This PR needs #10481 to be merged first** ⚠️~ Done ✅ 

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 4.x
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Related to #9607, fixes #10472

#### Description:

As described in https://github.com/mautic/mautic/issues/9607, we wanted to have additional checks in the Mautic installation and update process, like PHP version, database driver/version, etc.

This PR lays the foundation for pre-update checks. Those checks are executed both in the UI and CLI update processes. This looks as follows (ignore the actual versions shown in the screenshots):

**Pre-update checks in the UI**

image

**Pre-update checks in the CLI**

image

New pre-update checks can be added easily by creating a new check in `app/bundles/CoreBundle/Helper/Update/PreUpdateChecks`, then tagging it with `mautic.update_check` in the bundle's `config.php`. Then it will be picked up as a pre-update check.

This PR adds the following checks as a starting point:
- Database driver (MariaDB or MySQL)
- Database version (MySQL 5.7.14+ or MariaDB 10.2.7+) --> these can now be configured dynamically in `app/release_metadata.json`)
- PHP version (`minimum_php_version` and `maximum_php_version` in `app/release_metadata.json`)

**Other fixes/changes in this PR**
- Fixes #10472 where the user wasn't informed at all if a newer Mautic version was available, but the user's PHP version was too low. The user now sees that a new Mautic version is available, but the update will fail at the pre-update check step, telling the user that their PHP version is too old.
- Don't run `upload-release-asset` GitHub action on forks (created a test release for this PR at https://github.com/dennisameling/mautic/releases/tag/4.9.99-alpha so ran into this issue there)
- Remove a bunch of legacy code in `upgrade.php` that's no longer used
- Fixed bug where the CLI installation defaults to pdo_mysql (`db_driver`) if a database driver is set in `app/config/local.php` but not in the CLI options. The same goes for `db_backup_tables` and `db_backup_prefix`.
- Now leverages more [PHP typed properties](https://stitcher.io/blog/typed-properties-in-php-74) (this is possible since we require PHP 7.4 as of Mautic 4)

#### Steps to test this PR:
1. Checkout this PR locally: `gh pr checkout 10459`
2. For the remainder of the steps, we assume that you're using DDEV for local development. This allows you to easily change your PHP/database versions 
3. **Before testing each scenario below**, please ensure you have a clean state where Mautic is not installed: `ddev delete --omit-snapshot --yes && rm -rf var/cache && rm app/config/local.php`
4. Before every test run you do, set the correct PHP/database versions in the DDEV config:
  - Open `.ddev/config.yaml`
  - Change `php_version` (don't forget to update the version in `webimage_extra_packages` as well), `mariadb_version`, `mysql_version` as needed. NOTE: you can only have EITHER a `mariadb_version` OR a `mysql_version` active, not both!
5. Run `ddev restart` so that the appropriate PHP/database versions will be activated.

For testing the **CLI installation**, please run `ddev exec php bin/console mautic:install https://mautic.ddev.site --db_driver=pdo_mysql --db_host=db --db_user=db --db_name=db --db_password=db --db_port=3306 --admin_password=mautic --admin_email="demo@ddev.local"` - you can change the database driver by changing `db_driver` accordingly in this command.

**Here's the text matrix for the installation process - all scenarios below have to be tested.** 

| Action | PHP version | Database driver | Database version | Expected outcome
|--|--|--|--|--|
| Install using UI | 7.3.x | pdo_mysql | 10.3.x | ❌ on PHP version
| Install using CLI | 7.3.x | pdo_mysql | 10.3.x | ❌ on PHP version
| Install using CLI | 7.4.x | pdo_sqlite | 10.3.x | ❌ on database driver
| Install using UI | 7.4.x | pdo_mysql | MariaDB 10.1.x | ❌ on database version
| Install using CLI | 7.4.x | pdo_mysql | MariaDB 10.1.x | ❌ on database version
| Install using UI | 7.4.x | pdo_mysql | MySQL 5.6.x | ❌ on database version
| Install using CLI | 7.4.x | pdo_mysql | MySQL 5.6.x | ❌ on database version
| Install using UI | 7.4.x | pdo_mysql | MariaDB 10.3.x | ✅ 
| Install using CLI | 7.4.x | pdo_mysql | MariaDB 10.3.x | ✅ 
| Install using UI | 7.4.x | pdo_mysql | MySQL 5.7.x | ✅ 
| Install using CLI | 7.4.x | pdo_mysql | MySQL 5.7.x | ✅ 

Once you have a working Mautic installation, we can start testing the update scenario as well. **Before you start testing the update scenario, please head over to `app/config/local.php` and add the following lines at the bottom**:

```
'system_update_url' => 'https://api.github.com/repos/dennisameling/mautic/releases',
'update_stability' => 'alpha',
```

Then run `rm -rf var/cache` to remove the cache and `ddev exec "php bin/console mautic:update:find"` to check for updates. Please only proceed if you see "Version 4.9.99-alpha of Mautic is available for download". I bumped the minimum PHP version to 8.0.0, MySQL version to 8.0.0 and MariaDB version to 10.5.0 so that you can see the update errors show up.

- You can try the **CLI** update by running `ddev exec "php bin/console mautic:update:apply"`.
- You can try the **UI** update by going to https://mautic.ddev.site/index_dev.php/s/update in your browser (it's important you use the dev version as the production assets will only be generated when we release a new Mautic version)

| Action | PHP version | Database driver | Database version | Expected outcome
|--|--|--|--|--|
| Update using UI | 7.4.x | pdo_mysql | 10.3.x | ❌ on PHP version and database version
| Update using CLI | 7.4.x | pdo_mysql | 10.3.x | ❌ on PHP version and database version

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10459"></a>

### CODE REVIEW

**Comment by dennisameling** [comment]
This PR is now ready to test 🎉 ~please wait with the code review until https://github.com/mautic/mautic/pull/10537 is merged, as I cherry-picked https://github.com/mautic/mautic/pull/10459/commits/1bfbf33a750a173895f33c18453b2f6642c75966 into this branch which makes it harder to do a code review.~ Merged ✅

**Review by RCheesley — DISMISSED** [review]
Phew, that was quite some test matrix to get through! Thanks for all your work on this, here's my findings:

| Action | PHP version | Database driver | Database version | Expected outcome | Actual outcome
|--|--|--|--|--|--|
Install using UI | 7.3.x | pdo_mysql | 10.3.x | ❌ on PHP version | Unable to test
Install using CLI | 7.3.x | pdo_mysql | 10.3.x | ❌ on PHP version | Unable to test
Install using CLI | 7.4.x | pdo_sqlite | 10.3.x | ❌ on database driver | Failed on database driver
Install using UI | 7.4.x | pdo_mysql | MariaDB 10.1.x | ❌ on database version | Failed on database version 
Install using CLI | 7.4.x | pdo_mysql | MariaDB 10.1.x | ❌ on database version | Failed on database version
Install using UI | 7.4.x | pdo_mysql | MySQL 5.6.x | ❌ on database version | Failed on database version
Install using CLI | 7.4.x | pdo_mysql | MySQL 5.6.x | ❌ on database version | Failed on database version
Install using UI | 7.4.x | pdo_mysql | MariaDB 10.3.x | ✅| Installed, unable to upgrade due to PHP and database versions
Install using CLI | 7.4.x | pdo_mysql | MariaDB 10.3.x | ✅| Installed, unable to upgrade due to PHP and database versions
Install using UI | 7.4.x | pdo_mysql | MySQL 5.7.x | ✅| Installed, unable to upgrade due to PHP and database versions
Install using CLI | 7.4.x | pdo_mysql | MySQL 5.7.x | ✅| Installed, unable to upgrade due to PHP and database versions

So aside from the 7.3 part which I am unable to test, this is a solid ✅  from me!

**Review by escopecz — DISMISSED** [review]
I see no problem in the code 👍

**Review by escopecz — APPROVED** [review]
Added one more test. Re-approving and merging 👍

**Pull request merged**
