### PR TITLE
Returning custom field view permission

### LINKED ISSUE #13602: Missing Custom fields view permission
### Mautic Version

5.0.x series

### Way of installing

I cloned the Mautic repo (not recommended or supported)

### PHP version

8.2.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

In recent 5.x version there is missing permission setting for contact custom fields.

5.x branch:
image

5.0.3:
image

In result of this change introduced in #13321 I can no longer get the custom field list from API. The `lead:fields:view` is still used in the controller.

Related files:
 https://github.com/mautic/mautic/pull/13321/files#diff-fc1c6863009fa9dbb412ad96ef474537d4e3d72c2ccc90f126e7bd808b0e45a7L64

### How can we reproduce this issue?

1. Go to the roles permission settings
2. Select the Contact Permissions
3. Check if the View permission is available

### Relevant log output

```shell
{"errors":[{"code":403,"message":"The response has unexpected status code (403).\n\nResponse: {\"errors\":[{\"code\":403,\"message\":\"Permission not found. 'lead:fields:view' given.\",\"details\":[]}]}"}]}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [y]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [y] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/issues/13602

#### Description:

This line got removed in https://github.com/mautic/mautic/pull/13321/files#diff-fc1c6863009fa9dbb412ad96ef474537d4e3d72c2ccc90f126e7bd808b0e45a7L64 by accident. Probably due to extensive conflicts when updating that PR and its predecessor to updated target branch.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Follow the steps from https://github.com/mautic/mautic/issues/13602

### CODE REVIEW

**Review by RCheesley — CHANGES_REQUESTED** [review]
I checked out this PR but I'm still not seeing the view permission for this.

screenshot-mautic ddev site-2024 05 10-14_02_37

**Comment by escopecz** [comment]
Oops, I was so sure I found the problem. There was another line missing. Added that and then updated the existing test that confirms there are 2 permissions for the contact fields now.

**Comment by RCheesley** [comment]
Thanks @escopecz - when I try to view the custom fields logged in with a user who has 'view' permission:

screenshot-mautic ddev site-2024 05 10-15_28_04

I don't actually see it in the settings menu at all. I think that I should at least be able to view them? 

screenshot-mautic ddev site-2024 05 10-15_26_08

**Comment by jos0405** [comment]
Custom fields are not visible yet.
image

**Review by patrykgruszka — APPROVED** [review]
Code looks fine :+1: 

Works well from API perspective - can get all custom fields with both - view or manage permissions.

The problem with accessing Mautic Panel custom fields with view-only permissions is also present in the 4.x version. So this issue is not a regression.  In my opinion, it's good to go.

image

**Comment by escopecz** [comment]
Thanks for confirming. Since this fixes the regression described in https://github.com/mautic/mautic/issues/13602 I'm merging this to unblock the release of 5.1.0

**Pull request merged**
