### PR TITLE
Remove LinkedIn from core

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Based on https://github.com/mautic/mautic/issues/8895  LinkedIn API not working anymore.  Let's remove and any company can pick it, build based on IntegrationBundle and the put to marketplace

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by RCheesley** [comment]
Please take a look at the conflict @kuzmany

**Comment by mabumusa1** [comment]
Thanks @kuzmany , I would vote for the removal of anything that is not supported anymore. I will review as soon as you are done with this PR

**Comment by RCheesley** [comment]
I have set this back to draft while the conflicts are resolved so it doesn't confuse folks.

**Review by mabumusa1 — APPROVED** [review]
Changes are good. let's merge it

**Review by escopecz — APPROVED** [review]
Makes sense. Thanks! 👍

**Pull request merged**
