### PR TITLE
Moving themes and plugins to root level so scaffolding can take advantage of that

### LINKED ISSUE #10092: Site installation throws errors after `composer create-project`
## Bug Description
After `composer create-project mautic/recommended-project:4.x-dev` completes, the `[web-root]\plugins` and its subdirectories are missing. Please find the `Log errors` section for PHP errors.

| Q   | A
| --- | ---
| Mautic version | feature-dev
| PHP version | 7.4

### Steps to reproduce
1. Run `composer create-project mautic/recommended-project:4.x-dev`
2. Create a local server pointing to the `docroot` as webroot for the site
3. Visit the site
 
### Log errors
```
[25-May-2021 08:27:29 UTC] Symfony\Component\Finder\Exception\DirectoryNotFoundException: The "/var/www/mautic/docroot/app/bundles/CoreBundle/Loader/../../../../plugins/*/Config" directory does not exist. - in file /var/www/mautic/vendor/symfony/finder/Finder.php - at line 603
[25-May-2021 08:27:29 UTC] Symfony\Component\Finder\Exception\DirectoryNotFoundException: The "/var/www/mautic/docroot/app/bundles/CoreBundle/Loader/../../../../plugins/*/Config" directory does not exist. - in file /var/www/mautic/vendor/symfony/finder/Finder.php - at line 603
[25-May-2021 08:27:29 UTC] Symfony\Component\Finder\Exception\DirectoryNotFoundException: The "/var/www/mautic/docroot/app/bundles/CoreBundle/Loader/../../../../plugins/*/Config" directory does not exist. - in file /var/www/mautic/vendor/symfony/finder/Finder.php - at line 603
[25-May-2021 08:29:35 UTC] Symfony\Component\Finder\Exception\DirectoryNotFoundException: The "/var/www/mautic/docroot/plugins" directory does not exist. - in file /var/www/mautic/vendor/symfony/finder/Finder.php - at line 603
[25-May-2021 08:29:36 UTC] Symfony\Component\Finder\Exception\DirectoryNotFoundException: The "/var/www/mautic/docroot/plugins" directory does not exist. - in file /var/www/mautic/vendor/symfony/finder/Finder.php - at line 603
[25-May-2021 08:29:36 UTC] Symfony\Component\Finder\Exception\DirectoryNotFoundException: The "/var/www/mautic/docroot/plugins" directory does not exist. - in file /var/www/mautic/vendor/symfony/finder/Finder.php - at line 603
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by nickveenhof**
Mautic Version: 4.0 Beta

Fixes #10092

When trying out mautic/recommended-project I came aware of the limitation that you could not overrule a "replace" parameter in composer. The replace parameter was within core-lib and I got stuck there causing the whole reason of this composerisation to become annulled. This PR moves the plugins and themes to the root level composer, which makes sense but also adds a bit more complexity as we need to keep the dependencies in sync with mautic/recommended-project.

The automation that needs to follow is a good 2nd phase, but for now I think this PR will solve that issue and doesn't change anything to the regular mautic repository or development flow.

## Steps to reproduce the issue

`git clone git@github.com:mautic/recommended-project.git`
`cd recommended-project`
`composer install`

After you do this, composer will be happy, but you will see that none of the themes or plugins actually were installed. This is not a desired outcome

## Testing the PR
:warning: Remove the previous folder so we can start fresh

`git clone git@github.com:mautic/recommended-project.git`
`cd recommended-project`
`git checkout fix-plugins-and-themes-to-actually-install`
`composer install`

Verify if the plugins & themes are there and mautic is installable!

### CODE REVIEW

**Comment by RCheesley** [comment]
@nickveenhof some test instructions would be super helpful - could you share in the description how we can make sure that this is working and any commands that should be used?  Thanks!

**Comment by nickveenhof** [comment]
Sure - testing this can be done as follows:

Steps to reproduce the issue:
```
git clone git@github.com:mautic/recommended-project.git
cd recommended-project
composer install
```
After you do this, composer will be happy but you will see that none of the themes or plugins actually were installed. This is not a desired outcome

```
# remove the previous folder so we can start fresh
git clone git@github.com:mautic/recommended-project.git
cd recommended-project
git checkout fix-plugins-and-themes-to-actually-install
composer install
```

Verify if the plugins & themes are there and mautic is installable!

**Comment by nickveenhof** [comment]
An update also removes the blank grapesjs dependency as it was made obsolete by the blank theme that has support for both builders and is not present in the repository at all.

**Review by RCheesley — COMMENTED** [review]
Before the PR I was experiencing the issues reported in #10092 due to the missing folders:

screenshot-nimbus-capture-2021 06 02-11_54_27

After applying the changes as instructed the folders are in the right places, and I was able to successfully install Mautic! 🎉 

screenshot-nimbus-capture-2021 06 02-12_01_18

I did notice one thing that the URL had index.php in it (which I fixed by removing it in the installation process and all was well).

Also, maybe the Media folder is incorrect? In the folder structure it is in docroot/media but that is not reflected in the configuration:

screenshot-composertest ddev site-2021 06 03-11_57_58

I was able to save images for example when creating an email and they were sent in the email correctly - so this may be by design as the image does appear in that folder.

Otherwise, all good! 

If you can clarify those points then I will approve.

**Comment by nickveenhof** [comment]
The media path is actually by design like that. Mautic expects this path to be part of the webroot, not the application root. So it's all good. Also that is not something that is set in mautic/mautic :-) I'd say good to go then no?

**Review by RCheesley — APPROVED** [review]

**Review by shinde-rahul — APPROVED** [review]
LGTM!

**Pull request merged**
