### PR TITLE
Update oneup/uploader-bundle to 2.1.5 (security release)

### PR DESCRIPTION
**Pull request by bytehead**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes (Security) |
| New feature? | No |
| Automated tests included? | No |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/1up-lab/OneupUploaderBundle/security/advisories/GHSA-x8wj-6m73-gfqp |
| BC breaks? | No |
| Deprecations? | No |

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Relative Path Traversal (CWE-23) in chunked uploads. See more here: https://github.com/1up-lab/OneupUploaderBundle/security/advisories/GHSA-x8wj-6m73-gfqp

### CODE REVIEW

**Comment by RCheesley** [comment]
Hi @bytehead thanks for the PR, could you take a look at the conflict?

**Comment by bytehead** [comment]
I've changed the target branch to `3.0`, is that the correct branch for a bugfix?

**Comment by bytehead** [comment]
Security fix for 2.16 see #9025

**Review by escopecz — APPROVED** [review]
Thanks! Mautic already uses version 2.2.0 (see https://github.com/mautic/mautic/blob/staging/composer.lock#L5783) but it's always good to require healthy versions 👍

**Comment by RCheesley** [comment]
Thanks, that's perfect!

**Review by RCheesley — APPROVED** [review]

**Pull request merged**
