### PR TITLE
Bug twitter fix

### LINKED ISSUE #1742: Social plugins not working as they should after update
Just installed a new version of Mautic - must admit to being really impressed.

However, if I have a lead, when I click on Social in that lead, I get details of my Twitter account and nothing else. I have the correct @twittter handle as well as other web addresses for facebook, LinkedIn, G+ etc and although the apps are setup they are not working.

I have also cleared the cache out too.

## Steps to reproduce

- I updated to the new version through the link that came through on the Alerts icon with in Mautic

- Having updated initially the plugins link would not work so we cleared the cache this solved the problem accessing the plugins section.

- from that point on any contact that has twitter handle included in their profile started showing the twitter details from the authorized account from the plugin rather than the details on that contacts Twitter activity.

Please help Im losing my mind trying to find out whats happened.

### PR DESCRIPTION
**Pull request by alanhartless**
Please answer the following questions:

| Q             | A
| ------------- | ---
| Bug fix?      |  Y
| New feature?  | N 
| BC breaks?    |  N
| Deprecations? |  N
| Fixed issues  |  

## Description

These commits were cherry-picked from #1766 to be included in 1.4.1 bug fix release.

Fixes #1742 where Twitter populated contact data with the authorized user rather than the contact

It also updates some of the code for the other social networks to match Twitters. 
## Steps to reproduce the bug (if applicable)

See #1742

## Steps to test this PR

Edit a contact with a twitter handle and the contact should be populated with their own Twitter data. 

Test each social network integration if possible with both lead gleaning (save a lead with the handle) and the new form SSO buttons.

### CODE REVIEW

**Comment by escopecz** [comment]
I don't know what I'm doing wrong. I'm not able to display the Twitter widget at a contact's Social tab. I authorized the Twitter plugin successfully, configured the Twitter handle, saved many times, cleared cache many times, but the contact with my Twitter handle (or any other) does not display the widget whatever I do. I wish someone could write the docs for it.

**Comment by escopecz** [comment]
I managed to display the Twitter widget in a contact Social tab at my public testing Mautic instance, but it still displays the Twitter defined in the plugin detail and not the one in the contact edit form. This PR was applied, cache cleared, callback URL in the Twitter app updated to the new one, Twitter plugin re-authorized, the contact re-saved.

**Comment by alanhartless** [comment]
@escopecz Can you give it another shot to see if that last commit fixes it? I was able to reproduce after testing the form SSO which led me to realizing we were not removing the token from session after it was used and stored in the lead's social details...so it continued to be used for all leads.

**Comment by escopecz** [comment]
Yes, if I pull the last commit and re-save the contact, I can see the Twitter of the contact. :+1:

**Pull request merged**
