### PR TITLE
Support for click tracking with extra query parameters

### LINKED ISSUE #643: Dynamic Link Parameter in E-Mail
If I try to send an email with an dynamic parameter like 

http://domain.com/landing-page?email={leadfield=email}

the link got converted like this: 

http://domain.com/r/cccf1270c4c07ba41f7683bfa?ct=YTozOntzOjY6InNvdXJjZSI7YTowOnt9czo1OiJlbWFpbCI7TjtzOjQ6ImxlYWQiO2k6MjM7fQ%3D%3D=email@test.de

this redirects to a link like: 

http://example.com/landing-page?email   

So it seems as if only the part http://domain.com/landing-page?email= get converted into a link and after that the leadfield got replaced. 

Maybe a good solution would be to first replace all leadfields in the email and then convert the links? 

Seen with Mautic v1.1.2

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**
Hopefully fixes #643 

Using a link like `{pagelink=1}&email={leadfield=email|true}` would at best create a trackable link for the landing page but the &email query would not be fowarded on to the final page.  Also, when editing the email, the visual token for the leadfield breaks the link (as a span is inserted inside the link's href tag).  

So this PR adds support to Mautic's redirect links to forward extra query parameters on to the final destination (it removes the ct query param of course).  

It also prevents the editor from corrupting the HTML on edit when a leadfield token is used inside a link.  This is only for edited emails so any existing email with this problem will have to be cleaned up and resaved (the problem only becomes an issue when editing the content of the email as the original content saved to the database is fine _the first time_).

**Testing**
Create a new email and add various types of urls and tokens. For example,
```
Hi {leadfield=firstname}, 
<br/ ><br />
Check out these links: <br />
<a href="{pagelink=1}&email={leadfield=email|true}">Landing page token with lead field as query param</a><br />
<a href="{pagelink=1}">Landing page</a><br />
<a href="https://github.com?email={leadfield=email|true}">General link with lead field as query param</a><br />
<a href="https://github.com">Normal external link</a>
```
Before the PR, clicking on the landing page token with lead field as query param will land on the landing page but without the email query.  Editing the email will result in broken HTML.

After the PR, editing the content should be as expected (although the brackets for the leadfield token in the query param are encoded which is how they are preserved).  Sending the email should result in all working links and the email query params should make it to the final destination.

### CODE REVIEW

**Comment by escopecz** [comment]
Tested and the links seem to be correct after redirect. :+1:

**Comment by drmmr763** [comment]
+ test definitely saves the markup properly after PR 
+ vote +1

**Comment by sfahrenkrog** [comment]
vote +1

**Comment by vlordier** [comment]
well, for whatever reason, in my case the parameters don't get passed when using 
<a href="https://github.com?email={leadfield=email|true}">General link with lead field as query param</a><br />

any idea why ?

**Pull request merged**
