### PR TITLE
Missing include/exclude operator for text field in segment filters

### LINKED ISSUE #10947: Segment filter not saved or editable.
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

We create a tag to apply it to contacts then we wanted to create a Contact Segment filtered by a tag but the segment filter is not being saved or producing a filter box to apply to the segment. 

### How can we reproduce this issue?

Step 1: Create a new Contact Segment 
Step 2: Give it a name then go to filter tab
Step 3: Select any filter.

Filter input box never appear or saved in filter tab when a filter is selected from the drop down menu. 

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### LINKED ISSUE #10962: Segments operator does'nt work anymore since update 4.2
### Mautic Version

4.2.x series

### PHP version

7.4.26

### What browsers are you seeing the problem on?

Chrome

### What happened?

i've create a segment under v4.1 with email read date >= -4 weeks
now i've update mautic to the last version (4.2) (console mautic:update:find,apply,finish stuff)
now on my segment , the selectbox operator is empty and the value disappeared
error on the js console when i had a new filter

indeed, in the js function , filterId, and operator were never defined
on the following call Mautic.setProcessorForFilterValue(filterId, operator);

```
Mautic.convertLeadFilterInput = function(el) {
    var operatorSelect = mQuery(el);
    
    // Extract the filter number
    var regExp = /_filters_(\d+)_operator/;
    var matches = regExp.exec(operatorSelect.attr('id'));
    var filterNum = matches[1];
    var fieldAlias = mQuery('#leadlist_filters_'+filterNum+'_field');
    var fieldObject = mQuery('#leadlist_filters_'+filterNum+'_object');
    var filterValue = mQuery('#leadlist_filters_'+filterNum+'_properties_filter').val();

    Mautic.loadFilterForm(filterNum, fieldObject.val(), fieldAlias.val(), operatorSelect.val(), function(propertiesFields) {
        var selector = '#leadlist_filters_'+filterNum;
        mQuery(selector+'_properties').html(propertiesFields);

        Mautic.triggerOnPropertiesFormLoadedEvent(selector, filterValue);
    });

    Mautic.setProcessorForFilterValue(filterId, operator);
};
```

### How can we reproduce this issue?

First case : 
Step 1: create a segmentt under a previous version of mautic (4.0, 4.1)
Stetp 2 : use a filter like "email date read greater of equals -4 weeks"
Step 3 : save the segment
Step 4 : update mautic to the last version (4.2)
Step 5 : edit your segment and you'll see that the operator and the value disappeared

Second case : 
Step 1 : under mautic 4.2
step 2: create a segment
step 3: add a new filter "email read date"
step 4 : go to the js console log and you'll see operator not defined error

### Relevant log output

```shell
app.js?v07e9c379:657 Uncaught ReferenceError: operator is not defined
    at Object.Mautic.convertLeadFilterInput (app.js?v07e9c379:657:1206)
    at Object.Mautic.addLeadListFilter (app.js?v07e9c379:664:751)
    at HTMLSelectElement.<anonymous> (app.js?v07e9c379:648:132)
    at HTMLSelectElement.dispatch (libraries.js?v07e9c379:465:447)
    at HTMLSelectElement.elemData.handle (libraries.js?v07e9c379:451:166)
    at Object.trigger (libraries.js?v07e9c379:682:227)
    at HTMLSelectElement.<anonymous> (libraries.js?v07e9c379:688:258)
    at Function.each (libraries.js?v07e9c379:153:170)
    at jQuery.fn.init.each (libraries.js?v07e9c379:144:192)
    at jQuery.fn.init.trigger (libraries.js?v07e9c379:688:229)
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/108497460-segments-operator-does-nt-work-anymore-since-update-4-2?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/issues/10962, possibly https://github.com/mautic/mautic/issues/10947

#### Description:

The include/exclude operators are missing for text field in segment filters.

This PR is also fixing a JS error reported in https://github.com/mautic/mautic/issues/10962

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create 3 contacts with zip code: 1,2,3
3. Create segment with zip code filter include `1|2`
4. Rebuild segment
5. See first two contacts are assign to segment

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10985"></a>

### CODE REVIEW

**Review by RCheesley — APPROVED** [review]
Tested this with a new segment which has zip of 1 or 2 and works as expected.

Also checked all the sample data segments which have the correct filters set and are working as expected - note, need to be in developer mode or regenerate the assets.

**Comment by RCheesley** [comment]
@escopecz I checked this in dev mode with mautic/mautic using https://gitpod.io/#https://github.com/mautic/mautic and I was able to get this behaviour working without applying this PR. Maybe another PR already fixed it?

**Comment by escopecz** [comment]
I checked again. Here is the operators I see on the 4.x branch:
Screen Shot 2022-03-23 at 15 58 56
And this is on this branch:
Screen Shot 2022-03-23 at 15 59 58

**Comment by RCheesley** [comment]
Just confirmed that is indeed missing, thanks for the clarification (no idea how I managed to find it working OK, must have been a mistake on my part, apologies!)

**Review by kuzmany — APPROVED** [review]
Works properly 👍

**Pull request merged**
