### PR TITLE
PHP 8.2 support

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR contains the minimal changes to get Mautic working on PHP 8.2 and get the CI green.

The UTF8 conversions aren't necessary since Mautic 3 when we started using UTF8MB4 encoding. I think it's safe to get rid of it. The methods used for it were removed in PHP 8.2.

The `ext-iconv` should be required as we use it in the code without any checks if it is installed or not.

##### Old description:

~~This PR is just to test if there is some BC break required to support PHP 8.2. Based on the PHPUNIT output there doesn't seem to be. Many deprecations and failed tests are due to Swiftmaier which is going to be removed in https://github.com/mautic/mautic/pull/11613. So we can do this any time after that is merged. Even after M5.0.0 release.~~

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Gitpod was updated to PHP 8.2 as well so you can test it on this newer PHP version. There is nothing specific to test. Everything should work as before.
3. One thing I'd recommend to focus on is sending emails with some UTF8 characters like emojis.

### CODE REVIEW

**Comment by gnovaro** [comment]
Any update about this?

**Comment by escopecz** [comment]
Not on the top of my list at the moment. Feel free to take over.

**Comment by escopecz** [comment]
Test failures on PHP 8.2 reduced from `Errors: 31, Failures: 70` to `Errors: 0, Failures: 9`. I really have to move to other issues although I'd like to get this done. If anyone has a free evening, please take over.

**Comment by RCheesley** [comment]
Could you update the DDEV configuration so folks will be testing it on 8.2 as well?

**Review by kuzmany — DISMISSED** [review]
Looks good to me. 
I did basic tests 
Nice job 👍 
Tested on ddev

**Comment by escopecz** [comment]
A followup PR: https://github.com/mautic/mautic/pull/12469

**Comment by kou** [comment]
I'm interesting in PHP 8.2 support because Debian GNU/Linux bookworm (the current stable) uses PHP 8.2.

@mollux It seems that your review is a blocker of this PR. Could you take a look at this?

**Comment by escopecz** [comment]
This PR needs a rebase but I'm not going to do that until I someone will ensure that they will make the second test/review because I don't want to keep this PR up to date and wait for someone who will actually approve the PR for the second time.

**Review by gnovaro — APPROVED** [review]
Looks good to me!

**Comment by escopecz** [comment]
Thanks for the approval! Rebased. Will merge once the CI is green.

**Comment by escopecz** [comment]
Ok, there is some new issue. I'll have to look at that later.

**Comment by kou** [comment]
How about this like https://github.com/mautic/mautic/commit/33e48637a68ae6daabec4257144c9e35b32a72a5 ?

```diff
diff --git a/app/bundles/ReportBundle/Tests/Controller/ReportControllerFunctionalTest.php b/app/bundles/ReportBundle/Tests/Controller/ReportControllerFunctionalTest.php
index 171b071f8a..1f0b54fa2d 100644
--- a/app/bundles/ReportBundle/Tests/Controller/ReportControllerFunctionalTest.php
+++ b/app/bundles/ReportBundle/Tests/Controller/ReportControllerFunctionalTest.php
@@ -225,7 +225,7 @@ class ReportControllerFunctionalTest extends MauticMysqlTestCase
 
         $dom     = new \DOMDocument('1.0', 'utf-8');
 
-        $dom->loadHTML(mb_convert_encoding($content, 'HTML-ENTITIES', 'UTF-8'), LIBXML_NOERROR);
+        $dom->loadHTML(mb_encode_numericentity($content, [0x80, 0x10FFFF, 0, 0xFFFFF], 'UTF-8'), LIBXML_NOERROR);
         $tbody = $dom->getElementById('reportTable')->getElementsByTagName('tbody')[0];
         $rows  = $tbody->getElementsByTagName('tr');
 
```

**Comment by escopecz** [comment]
@kou would you be able to push such fix as a PR against this branch on my fork? I'm swamped and cannot get to this any time soon.

**Comment by kou** [comment]
Sure!
https://github.com/escopecz/mautic/pull/21

**Pull request merged**
