### PR TITLE
TPROD-319 - LeadBundle - Lead PHP Templates to Twig

### PR DESCRIPTION
**Pull request by JoshuaEstes**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Test everything related to the Leads part of the system, like viewing logs, social ,notes, list of leads, editing leads, deleting leads etc.

### CODE REVIEW

**Comment by RCheesley** [comment]
Could you take a look at the PHP 8 test failures please @JoshuaEstes ? Thanks!

**Comment by JoshuaEstes** [comment]
@RCheesley Yeah, this one is WIP and I'm finding a few issues within it so I just moved it back into Draft status.

**Comment by RCheesley** [comment]
Ah OK perfect, I'll leave it until you shout then!

**Review by mabumusa1 — CHANGES_REQUESTED** [review]
Here are my results: 

- [X] List leads
- [X] Quick Add 
- [X] Search leads
- [X] Edit lead including adding  a company and tag
- [X] Social Media fields get filled, there is no validation on the format of the field, I am not sure if it is an old issue or introduced by this PR 
- [X] Custom profile avatar 
- [X] History show entries correctly
- [X] Audit log shows entries correctly 
- [X] Notes add, edit, delete worked 
- [X] Send email worked
- [X] Contact Export worked
- [X] Prefernces worked
- [X] Delete contact
- [ ] Campaigns did not work, it shows an empty box instead of showing the campaigns

image

**Comment by JoshuaEstes** [comment]
> Campaigns did not work, it shows an empty box instead of showing the campaigns

The only way I can reproduce the issue is when I unpublish all the Campaigns. Once I do that, I get a screen similar to yours.

**Review by daniellord32 — DISMISSED** [review]
- [x]  List leads
- [x]  Quick Add
- [x]  Search leads
- [x]  Edit lead including adding a company and tag
- [x]  Social Media fields get filled
- [x]  Custom profile avatar
- [x]  History show entries correctly
- [x]  Audit log shows entries correctly
- [x]  Notes add, edit, delete worked
- [x]  Send email worked
- [x]  Contact Export worked
- [x]  Prefernces worked
- [x]  Delete contact
- [x]  Campaigns list

view looks good and nothing looks like it's missing

**Comment by volha-pivavarchyk** [comment]
Here are my results
- [X] Quick Add
- [X]  Search leads
- [X]  Add/Edit lead including adding a company and tag
- [X]  Social Media fields get filled
- [X]  Custom profile avatar
- [X]  Audit log shows entries correctly
- [X]  Send email worked
- [X]  Contact Export worked
- [X]  Delete contact
- [X]  Campaigns list
- [ ]  List leads
I got an error after calling `Change Campaigns`, `Change Owner`, `Set Do Not Contact`. 
image
- [ ]  History show entries correctly
After submitting the form.
image
- [ ]  Notes add, edit, delete worked
After changing the pagination, the filtering block disappears.
image
- [ ]  Prefernces worked
I'm not sure if this block should be here. It wasn't here before. Maybe I've missed something.
image

**Comment by JoshuaEstes** [comment]
> List leads

Resolved

> History show entries correctly

Resolved

> Notes add, edit, delete worked

This seems to be a bug on the 5.x branch as well. While tested this, it also looks like it changes the HTML title tag as well. @RCheesley @escopecz 

>  Prefernces worked

Resolved

---

@volha-pivavarchyk thanks for finding these! Please let me know if you find anything else

**Comment by RCheesley** [comment]
@volha-pivavarchyk would you mind raising a bug separately to this PR about the issue you found, as it looks like this is on the 5.x branch and not relating to this PR. Thanks for fixing the issues identified @JoshuaEstes 🚀

**Review by daniellord32 — APPROVED** [review]
- [x]  List leads
- [x]  Quick Add
- [x]  Search leads
- [x]  Edit lead including adding a company and tag
- [x]  Social Media fields get filled, there is no validation on the format of the field, I am not sure if it is an old issue or introduced by this PR
- [x]  Custom profile avatar
- [x]  History show entries correctly
- [x]  Audit log shows entries correctly
- [x]  Notes add, edit, delete worked
- [x]  Send email worked
- [x]  Contact Export worked
- [x]  Prefernces worked
- [x]  Delete contact
- [x]  Campaigns List

All tests have passed for me

**Review by mabumusa1 — APPROVED** [review]
I tested again, this works as expected

**Pull request merged**
