### PR TITLE
Add gated video css to iframeStyle

### PR DESCRIPTION
**Pull request by dongilbert**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | n
| New feature? | n
| Related user documentation PR URL | n
| Related developer documentation PR URL | n
| Issues addressed (#s or URLs) | n
| BC breaks? | n
| Deprecations? | n

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Styling for the gated video on the content tab quit working in staging recently. This fixes it.

#### Steps to test this PR:
1. Apply the PR
2. Ensure gated video styling looks good on landing page edit outside of the builder.

### CODE REVIEW

**Comment by escopecz** [comment]
Works for me :+1:

**Comment by alanhartless** [comment]
@escopecz @dongilbert  Wasn't it iframeStyle that was removed because it caused an issue with stripping stuff from the source?

**Comment by escopecz** [comment]
It was, but I tested it with the new Froala version (merged to 2.1.1) and it works now. Or does it cause the issues for you?

**Comment by dongilbert** [comment]
It wasn't `iframeStyle` that was removed, it was `iframeStyleFiles`. This uses a different approach.

**Comment by alanhartless** [comment]
ah - either way, it works and none of my head tags were removed so +1

**Pull request merged**
