### PR TITLE
Add the Pepipost SMTP service

### PR DESCRIPTION
**Pull request by moskoweb**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | N
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Adding a new SMTP service to be used on Mautic, including handling the status of the lead through webhook feedback from Pepipost itself.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. 

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Review by Hiteshpandey — CHANGES_REQUESTED** [review]
I've tested your PR against current 2.16.1 version of mautic, there are some issues with this and some suggested updates shown below.

# Tests: 
Listed are the tests on webhooks, these tests were made using offical pepipost webhooks integration.  
 - unsubscribed - Working after updates  
 - invalid - Working after updates  
 - bounced -> HARDBOUNCE  - Working after updates  
 - bounced -> SOFTBOUNCE - Working after updates  
 - spam - Working after updates (Was tested by sending request through postman since real life scenario was hard to reproduce)
 - dropped (New event should be added) - Working after updates  

With each individual webhooks it was tested if the contacts gets tagged dynamically at the webhook call and bounce handling was done accordingly. Setup was made according to mautic offical guide for bounce handling through webhooks.

# Issues:
```sh
$email    = rawurldecode($request->get(0)['FROMADDRESS']);
```
 - The contact updates should be done based on from address.  
 - To change that Email identifier should be [EMAIL] instead of [FROMADDRESS]

# Updates:
### Line 73
### Current Code: 
```sh
$email    = rawurldecode($request->get(0)['FROMADDRESS']);
```
### Update: 
```sh
$email    = rawurldecode($request->get(0)['EMAIL']);
```
# Additions:
Add a missed out pepipost webhook event named (dropped)
### Line 89:
### Current code : 
```sh
elseif ($event == 'spam') {
            $this->transportCallback->addFailureByAddress($email, $this->translator->trans('mautic.email.bounce.reason.spam'));
        }
```
### Update: 
```sh
elseif ($event == 'spam') {
            $this->transportCallback->addFailureByAddress($email, $this->translator->trans('mautic.email.bounce.reason.spam'));
        }
elseif ($event == 'dropped') {
            $this->transportCallback->addFailureByAddress($email, $this->translator->trans('mautic.email.bounce.reason.dropped'));
        }
```

**Comment by npracht** [comment]
Hi @hiteshpandey can you apply your suggestions directly on the PR ?

**Comment by Hiteshpandey** [comment]
> 
> 
> Hi @Hiteshpandey can you apply your suggestions directly on the PR ?

Sure. Will push a new branch pepipost_pr_7480_updates.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by npracht** [comment]
Closed in favor of #8637

**Pull request closed without merging**
