### PR TITLE
JS tracking API changed to require less change in the future

### PR DESCRIPTION
**Pull request by escopecz**
Please answer the following questions:

| Q             | A
| ------------- | ---
| Bug fix?      | N
| New feature?  | N
| BC breaks?    | N
| Deprecations? | N
| Fixed issues  |  /

## Description
I suggest to build the JS tracking API the way it will suite even future needs for example for event tracking. This way our users won't have to change their tracking code so often. Current implementation triggered pageview query every time the JS was loaded. It's not that different from using the tracking pixel.

So my improvements are:

### GA-like initiation
The tracking code will change from simple
```
<script>
    MauticJS.trackingPixelParams = {email: 'me@gmail.com'};
</script>
<script src="http://me.mautic.com/mtc.js"></script>
```
to
```
<script>
    (function(w,d,t,u,n,a,m){w['MauticTrackingObject']=n;
        w[n]=w[n]||function(){(w[n].q=w[n].q||[]).push(arguments)},a=d.createElement(t),
        m=d.getElementsByTagName(t)[0];a.async=1;a.src=u;m.parentNode.insertBefore(a,m)
    })(window,document,'script','http://mautic.io/mautic-github/index_dev.php/mtc.js','mt');

    mt('send', 'pageview', {email: 'me@gmail.com'});
</script>
```

Advantages:
- User will define the pageview when he wants, not necessarily on JS load. This will allow tracking for example single page applications which can execute many pageviews without JS loading.
- User can define how the global var for Mautic Tracking will be called to avoid JS conflicts. In this case it's called `mt`, but can be changed easily.
- Plugins/bundles can implement more tracking events. For example [GA has](https://developers.google.com/analytics/devguides/collection/analyticsjs/pages) 'pageviews', 'events', 'social', 'screenview', 'timing', 'exception'

The implementation at mtc.js is not optimal and I'm sure it can be improved (we can get rid of the global MauticJS variable now) and more features can be added, but now we can change it without need for changing the public tracking code. That's the main purpose of this PR.

Because the tracking code is becoming more complicated, this PR generates it for each Mautic in the configuration:
mautic-tracking-code

## Steps to test this PR
1. apply this PR
2. copy the tracking code from configuration to a 3rd party website
3. Check that the tracking works
4. Try to add some additional params like `mt('send', 'pageview', {email: 'me@gmail.com'});` and check that the tracked lead is recorded with that email. (The email field must be publicly updatable)

### CODE REVIEW

**Comment by dbhurley** [comment]
+1

**Comment by alanhartless** [comment]
+1 worked greated

**Comment by amit777** [comment]
awesome, just what I've been waiting for! Thanks!

**Comment by isleshocky77** [comment]
@escopecz You specifically mention above that you believe this is needed so you can send multiple pageviews from the same page; however, I'm finding this is not working as expected.  I've tried it in few different ways just to test to see if the events make it through.

## Fire off two sends together

Here I end up getting alerted to "Page 1 Sent" and the view shows up in Mautic. The second one never makes it to Mautic.

```javascript
<html><body>
(function(w,d,t,u,n,a,m){w['MauticTrackingObject']=n;
            w[n]=w[n]||function(){(w[n].q=w[n].q||[]).push(arguments)},a=d.createElement(t),
                m=d.getElementsByTagName(t)[0];a.async=1;a.src=u;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://mautic.localhost/mtc.js','mt');

        // Send PageView 1
        mt('send', 'pageview', {
            page_url: '/page1',
            page_title: 'Page 1'
        }, { onload: function() { alert('Page 1 Sent');}});

        // Send PageView 2
        mt('send', 'pageview', {
            page_url: '/page2',
            page_title: 'Page 2'
        }, { onload: function() { alert('Page 2 Sent');}});
    </script>
</body></html>
```

## Fire off one send with load, another on event

Here I end up getting alerted to "Page 1 Sent" and the view shows up in Mautic. 
When I click the button I get an alert for sending, but I never receive the Sent. The second one never makes it to Mautic.

```javascript
<html><body>
(function(w,d,t,u,n,a,m){w['MauticTrackingObject']=n;
            w[n]=w[n]||function(){(w[n].q=w[n].q||[]).push(arguments)},a=d.createElement(t),
                m=d.getElementsByTagName(t)[0];a.async=1;a.src=u;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://mautic.localhost/mtc.js','mt');

        // Send PageView 1
        mt('send', 'pageview', {
            page_url: '/page1',
            page_title: 'Page 1'
        }, { onload: function() { alert('Page 1 Sent');}});

        var sendPage2 = function() {
            // Send PageView 2
            alert('Sending Page 2');
            mt('send', 'pageview', {
                page_url: '/page2',
                page_title: 'Page 2'
            }, { onload: function() { alert('Page 2 Sent');}});
        };
    </script>
    <input type="button" onclick="sendPage2();" value="Send Page 2" />
</body></html>
```

## Fire off both on events

Here I get a javascript error on loading the page

> mtc.js:12 Uncaught TypeError: Cannot read property 'length' of undefined

When clicking the buttons the alerts for Sending are shown. I never receive either Sent alert and neither pageview makes it to Mautic.

```javascript
<html><body>
(function(w,d,t,u,n,a,m){w['MauticTrackingObject']=n;
            w[n]=w[n]||function(){(w[n].q=w[n].q||[]).push(arguments)},a=d.createElement(t),
                m=d.getElementsByTagName(t)[0];a.async=1;a.src=u;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://mautic.localhost/mtc.js','mt');

        var sendPage1 = function() {
            // Send PageView 1
            alert('Sending Page 1');
            mt('send', 'pageview', {
                page_url: '/page1',
                page_title: 'Page 1'
            }, { onload: function () { alert('Page 1 Sent'); }});
        };

        var sendPage2 = function() {
            // Send PageView 2
            alert('Sending Page 2');
            mt('send', 'pageview', {
                page_url: '/page2',
                page_title: 'Page 2'
            }, { onload: function() { alert('Page 2 Sent');}});
        };
    </script>
    <input type="button" onclick="sendPage1();" value="Send Page 1" />
    <input type="button" onclick="sendPage2();" value="Send Page 2" />
</body></html>
```

**Comment by escopecz** [comment]
Hi, yes, the current state of JS tracking doesn't support multiple asynchronous page hits. See https://github.com/mautic/mautic/issues/1861. This PR made it possible to implement it without change of the original tracking code and breaking backward compatibility. But no one implemented it yet.

**Pull request merged**
