### PR TITLE
Patch for #6788 - Update PageModel.php

### PR DESCRIPTION
**Pull request by jrpub**
Updating PageModel.php to handle correctly POSTed data from mtc.js.
See #6788 

Testing:
Make sure that JS tracking as well as tracking pixel with or without additional params still work.

### CODE REVIEW

**Comment by Woeler** [comment]
Have a look at this. Same? https://github.com/mautic/mautic/pull/6802

**Comment by jrpub** [comment]
Yes, it is the same. Patch #6802 seems better as there is a test of the POST or GET. You can reject this one and merge 6802 I guess.

**Comment by escopecz** [comment]
I like this one more as it's less code that does the same thing as #6802.

**Comment by Woeler** [comment]
Alrighty, closing this one if favor of https://github.com/mautic/mautic/pull/6802 where we now catch both POST and GET parameters

**Pull request closed without merging**
