### PR TITLE
New Slot | Signature

### PR DESCRIPTION
**Pull request by moskoweb**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | N
| Related user documentation PR URL | N
| Related developer documentation PR URL | N
| Issues addressed (#s or URLs) | N
| BC breaks? | 
| Deprecations? | 

[//]: # ( Required: )
#### Description:
Creation of a new Slot for the creator of email, this time a practical way of putting a professional signature in the emails.

You can customize with name, bio, image, email, phone and website.

In addition to the colors that can be customized as desired.

[//]: # ( As applicable: )
#### Steps to reproduce:
1. Create new email
2. Add slot Signature

### CODE REVIEW

**Review by Strubbel94 — CHANGES_REQUESTED** [review]
**Minor Issue:**
After saving the Email or applying changes the Email field in the Customize Slot appears empty.

Despite this issue, the Feature is working fine.

Slot Signature Testing

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@cla-bot check

Hi @moskoweb thanks for this PR! It looks like we have a config file conflict that needs to be addressed if this is still good to go for Mautic 3.x and you need to sign the contributors agreement - could you take a look?

I'll tag it for the 3.2 release provisionally, that would mean getting it tested and ready to go no later than **Sunday, 15th November**.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@moskoweb I am not sure if this PR is still relevant given the new builder, but if you do still want it to be considered please can you take a look at the codestyle issues and the failing tests?

If you prefer not to take this forward, let's close the PR.

**Comment by RCheesley** [comment]
@moskoweb given this has had no activity in many months I am going to close the PR. If you want to pick it up again in the future just comment to let us know.

**Pull request closed without merging**
