### PR TITLE
Refactor onCampaignTriggerActionSendEmailToUser

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/8058
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
https://github.com/mautic/mautic/issues/8058

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create campaign with action Send email to user
3. Trigger campaign and check if email was sent to user properly

### CODE REVIEW

**Comment by hluchas** [comment]
@kuzmany Can you fix conflict and tests? TY!

**Comment by escopecz** [comment]
@kuzmany there are still some failing tests.

**Comment by kuzmany** [comment]
@escopecz I am not able to rewrite unit tests in next few days.  Sorry.
Can somebody from Mautic do that?

**Comment by hluchas** [comment]
Closing as I continue here https://github.com/mautic/mautic/pull/8236

**Pull request closed without merging**
