### PR TITLE
Social buttons form field

### PR DESCRIPTION
**Pull request by mqueme**
| Q | A |
| --- | --- |
| Bug fix? | y |
| New feature? |  |
| Related user documentation PR URL | https://github.com/mautic/documentation/blob/master/en/plugins/social_login.md |
| Related developer documentation PR URL |  |
| Issues addressed (#s or URLs) | #2772 #2804  |
| BC breaks? |  |
| Deprecations? |  |
#### Description:

This PR fixes the social login buttons that stopped working.
#### Steps to test this PR:
1. [Follow these steps prior to testing](https://github.com/mautic/documentation/blob/master/en/plugins/social_login.md). Please clear cache after applying this PR.
2. Create a form and select social login. The SL buttons should now appear.
3. place the form on a page for public anonymous viewing. Test that you are able to log in. if a new contact is created this should be updated with their social cache.
4. **If you have an existing form that does not show the button images correctly you will need to go to your form in Mautic click the edit button for the social login field, and click update. This will update the full URL of your mautic installation and path to images.**

#### Steps to reproduce the bug:
1. Follow the same steps above prior to creating a form
2. Select social login buttons and an error should be logged in your logs.

### CODE REVIEW

**Comment by luizeof** [comment]
@mqueme this feature works on any form? even on forms placed by script on external websites or only on mautic landing pages?

Great Work!

**Comment by mqueme** [comment]
Not sure about this error, have you tried to delete your cache
Also you need to update forms that were updated previous to this update.

**Comment by Rikk03** [comment]
@luizeof It works on any form, however its not working right now.  Posted a bug issue about it.

**Comment by mqueme** [comment]
please see new changes for images path, follow step 4 for existing forms

**Comment by escopecz** [comment]
I'm getting
```
Uncaught PHP Exception InvalidArgumentException: "The template "MauticFormBundle:Field:plugin.loginSocial.html.php" does not exist.
```
on form edit form and form detail page for the form with social login button created before this PR was applied.

**Comment by mqueme** [comment]
fixed, thanks

**Comment by escopecz** [comment]
I'm still getting the same error on both my local and remote instances.

**Comment by alanhartless** [comment]
I cleared my cache and didn't get @escopecz error. I updated the algorithm for matching a bit as I couldn't get it to initially to work. But all seems to work now.

**Comment by escopecz** [comment]
@alanhartless could you test it on a form with the social login button created prior to applying this PR and then apply this PR?

If I look at the form_fields table, the `type` of the field causing the error is `plugin.loginSocial`. What it should be to not fire this error?

I'd like to create a new form with this PR to find out, but I cannot see the option anymore:
mautic-forms-social-missing

**Comment by virlatinus** [comment]
It works. After applying the PR, the social login buttons appear on the form.

**Comment by escopecz** [comment]
It works for me on forms with social login created after this PR was applied. It does not fix the legacy forms. It's definitely good to have it working on the new ones :+1:

**Pull request merged**
