### PR TITLE
[UX] Add a link to campaign creation in the Dashboard

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
The latest update to the Dashboard introduces a direct link for creating new campaigns, streamlining the user workflow. This addition makes it more convenient for users to initiate campaign creation without navigating away from the Dashboard. It’s a quality-of-life improvement that benefits users who frequently create campaigns, enhancing their productivity and simplifying the process.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Dashboard
3. Look at the new button

image

### CODE REVIEW

**Review by LordRembo — APPROVED** [review]
Better/easier access seems like a good idea.

**Comment by andersonjeccel** [comment]
@RCheesley Your review would be appreciated in this one, I'm happy about this enhancement 💖

**Review by roboparker — APPROVED** [review]

**Comment by kuzmany** [comment]
Why focus solely on campaigns? The Dashboard isn't just about campaigns. Mautic isn't limited to just campaigns either. We have customers who hardly ever use campaigns.

**Comment by Mike-Dropsolid** [comment]
> Why focus solely on campaigns? The Dashboard isn't just about campaigns. Mautic isn't limited to just campaigns either. We have customers who hardly ever use campaigns.

I agree that it might as well be the 2 or 3 most used (manual) create actions. But what would those be...? For me, from most important to less important:

- Mail
- Campaign
- Segment
- Form

**Comment by kuzmany** [comment]
I believe you're focusing your efforts in the wrong direction. This job is better suited for a plugin. Any company or developer could create a plugin for this and possibly make money from it. However, I don't see it as a main feature of core.

**Comment by Mike-Dropsolid** [comment]
> I believe you're focusing your efforts in the wrong direction. This job is better suited for a plugin. Any company or developer could create a plugin for this and possibly make money from it. However, I don't see it as a main feature of core.

Why would this not be an improvement to the general usability/UX of Mautic?

There has been a lot of focus on the core, by developers, leaving the needs of the target group behind. It's nice to have both.

**Comment by kuzmany** [comment]
Actions should be included within widgets, rather than in the dashboard actions toolbar.
 In the dashboard actions toolbar, I expect actions related to the dashboard. 
 In the campaign actions toolbar, I expect actions related to the campaign, etc.

**Review by RCheesley — CHANGES_REQUESTED** [review]
I'm also agreeing with @kuzmany on this one, I don't think that this is the right way to go. Campaigns are just one thing that people do in Mautic - if we add this button, what's not to say you'd end up with five of them, and then that is just a horrible user experience how it's done right now.

What would make much more sense is having a tour, which we're already working on, to help people get to the most popular things in a way that is optional, especially if they are new to Mautic and need help finding their way to things. If you find the tour helpful, it can be shown, and if not, it's dismissed and doesn't show.

I don't support adding buttons in this way to core (I'm about an 8/10 for **not** merging this PR), because I think it unnecessarily clutters the interface with only one of many useful shortcuts, and doesn't improve the experience for the average Mautic user by reducing two clicks (Campaigns > New) to one. The benefits do not outweigh the visual clutter, in my opinion.

**Comment by Mike-Dropsolid** [comment]
> Actions should be included within widgets, rather than in the dashboard actions toolbar. In the dashboard actions toolbar, I expect actions related to the dashboard. In the campaign actions toolbar, I expect actions related to the campaign, etc.

Makes sense.

**Comment by andersonjeccel** [comment]
@Mike-Dropsolid I have a greater plan for all this, I will close this PR now and reopen in another moment when new resources become ready.

**Pull request closed without merging**
