### PR TITLE
bugfix - add back variant button on email dyn content

### PR DESCRIPTION
**Pull request by Dcoutelle**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/4089
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Add back the button "new" bellow and make is works
image

#### Steps to test this PR:
1. Apply the PR
2. Make dyn content with variant and save it.
3. Come back and check the content is here

### CODE REVIEW

**Comment by npracht** [comment]
Test and it works:

- Add variation button is there
- Dynamic content is well replaced in the email when sent
_______
capture d ecran 2017-07-07 a 11 19 19
capture d ecran 2017-07-07 a 11 19 24
capture d ecran 2017-07-07 a 11 19 28
capture d ecran 2017-07-07 a 11 19 46

**Comment by npracht** [comment]
Just one thing, in the builder we now have the 2 buttons, i think we should keep only one.
capture d ecran 2017-07-07 a 11 23 05

**Comment by npracht** [comment]
## much better !
capture d ecran 2017-07-07 a 17 14 46

**Comment by Loanatik** [comment]
Not sure if you were trying to nail both places where the add variant button was missing, but, it seems to still be missing from Dynamic Content tab:
image

**Comment by Dcoutelle** [comment]
@Loanatik , It look like OK to me.

If you are working in production environnement, you have to re-generate your assets.

**Comment by KbyersLT** [comment]
As @Loanatik above, it seems it is still missing from dynamic content tab in code mode.

image

**Comment by npracht** [comment]
As said @Dcoutelle i think if you generated assets it works correctly.
capture d ecran 2017-07-12 a 09 46 03
capture d ecran 2017-07-12 a 09 46 53

**Comment by KbyersLT** [comment]
@npracht @Dcoutelle I'm new to mautic and use it from the marketing side of things, could you explain what you mean by re-generate assets - is this a job for my system admin?

Referring to the mautic documentation below:

image

**Comment by npracht** [comment]
@KbyersLT one of my teammate is gonna contact you in private message to explain you that.

**Comment by KbyersLT** [comment]
Thank you @npracht :)

**Comment by npracht** [comment]
@KbyersLT i don't have your contact information. Can you send me an email ? You have my email on my GitHub profile. Thanks

**Comment by virlatinus** [comment]
It works as described. +1

**Comment by orangeattitude** [comment]
@npracht I try use php app/console mautic:assets:generate to re-generate assets and clear cache, but still missing from dynamic content tab in code mode. I can't add more variants.
I'm on 2.9.2

**Comment by escopecz** [comment]
I can see it:
dec-code-mode
Note: DEC exists only for Emails - wont show on Landing Pages form.

**Comment by orangeattitude** [comment]
mautic

I meant the button to add a new variant within the dynamic content.

**Comment by escopecz** [comment]
I see. I'll re-open the issue https://github.com/mautic/mautic/issues/4089

**Pull request merged**
