### PR TITLE
Generate elfinder assets

### LINKED ISSUE #11897: elFinder fails due to old version bug
### Mautic Version

5.0.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Try to open the path `/elfinder`, you will get 500 Error with the following log

```Uncaught PHP Exception Error: "Undefined constant "ELFINDER_IMAGEMAGICK_PS"" at /home/code/public_html/vendor/studio-42/elfinder/php/elFinderVolumeDriver.class.php line 5570```

This is a reported issue on https://github.com/helios-ag/FMElfinderBundle/pull/437 and the issue has been fixed

so we need to upgrade the package `helios-ag/fm-elfinder-bundle` to solve this issue 

### How can we reproduce this issue?

Step 1: Open elfinder
Step2: get the error

### Relevant log output

```shell
PHP Exception Error: "Undefined constant "ELFINDER_IMAGEMAGICK_PS"" at /home/code/public_html/vendor/studio-42/elfinder/php/elFinderVolumeDriver.class.php line 5570
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [upgrade]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://mautic.atlassian.net/browse/TPROD-442

#### Description:

This PR does several things but the goal is to update ElFinder which seem to have some security issues in the version we use today:

> WARNING: IF YOU HAVE OLDER (IN PARTICULAR 2.1.60 OR EARLIER) VERSIONS OF ELFINDER ON PUBLIC SERVERS, IT MAY CAUSE SERIOUS DAMAGE TO YOUR SERVER AND VISITED USER. YOU SHOULD UPDATE TO THE LATEST VERSION OR REMOVE IT FROM THE SERVER.

https://github.com/Studio-42/elFinder

This is what has been done here:
1. The plugin edit for was broken from Twig refactoring. Fixed in https://github.com/mautic/mautic/commit/7421285586e3bdaabe985bb02f03ba3b44a41368
2. The ElFinder assets are present in the ElFinder Bundle and yet we had them also hard-coded in Mautic. The bundle has a command that will move them to whatever folder we want. So I added that command to our `bin/console mautic:assets:generate` command and installed them in the `node_modules` directory where we want to have the rest of the JS libraries. See https://github.com/mautic/mautic/commit/60425560550b7cc53a164805c8cf488284e1cc9e and https://github.com/mautic/mautic/pull/12271/commits/9facef7daf92c7feaed46ce925745b72b7e3e214
3. Updating the ElFinder PHP dependencies and thanks to step 1 we also updated the JS dependencies to fix the security vulnerability
4. Deleting unused or replaced JS and CSS files related to ElFinder that were hard-coded in Mautic.

~~@mollux also created a [fix for the ElFinder Bundle](https://github.com/helios-ag/FMElfinderBundle/pull/499) and since they take time to merge it we had to point to the branch that had the fix as the composer installation step was failing because of it. [This change](https://github.com/mautic/mautic/pull/12271/commits/0459d2c5f3d928c4a939034229e5f097dcc9e34f) should be reverted once that PR is merged.~~

⬆️  Fixed in https://github.com/helios-ag/FMElfinderBundle/releases/tag/12.3

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Disable the GrapeJS plugin
3. Create new email
4. Select the Mauve theme
6. Open the builder
7. Click on some text slot
8. In the right hand column you'll see a WYSIWYG editor for that text slot
9. Click on the image for uploading images
10. Click on the folder to select some image that was already uploaded. This will load the ElFinder UI where you can browse and manage images. With double-click you can add an image to the email content.

### CODE REVIEW

**Comment by rahuld-dev** [comment]
Hello @escopecz 

I am testing this PR on local env.
After click on folder it is showing an error. please see the following screenshot.
image

When I inspect element on elfinder tab i found some error in console tab

image

**Comment by mabumusa1** [comment]
> Hello @escopecz 
> 
> I am testing this PR on local env.
> After click on folder it is showing an error. please see the following screenshot.
> image
> 
> When I inspect element on elfinder tab i found some error in console tab
> 
> image
> 



Hello @rahuld-dev 

This issue is solved by https://github.com/helios-ag/FMElfinderBundle/pull/437

I think we need to upgrade the bundle

**Comment by rahuld-dev** [comment]
I have updated my comment with correct error screenshot.

**Review by rahuld-dev — APPROVED** [review]
Hello @escopecz 
The elfinder working as expected.

But when I click on image for uploading images and try to upload images without elfinder I'm not able to select any images.
image

**Review by rahuld-dev — CHANGES_REQUESTED** [review]
Hello @escopecz
The elfinder working as expected.

But when I click on image for uploading images and try to upload images without elfinder I'm not able to select any images.
image

**Comment by escopecz** [comment]
@rahuld-dev I can't make this button:
Screenshot 2023-05-11 at 17 04 08
work on the 5.x branch nor on a commit from a month ago and not even on the 4.4 branch. Are you sure it used to work before this PR?

**Comment by escopecz** [comment]
Oops, I did not want to merge this PR but another. Damn you, too many tabs opened! I'll revert if you find more issues with this or fix them in another PR. Apologies for breaking the processes!

**Review by mabumusa1 — APPROVED** [review]
@escopecz do not stress much, I tested this PR, it works as expected

**Pull request merged**
