### PR TITLE
feat: [DPMMA-796] Add export lead contact info

### PR DESCRIPTION
**Pull request by tomekkowalczyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🟢 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description
The change adds a dedicated rotating log to the export of contacts with information on who performed the export and with what parameters it was performed. 

image

Data is saved in the database in the Audit Log table. We can generate a report with data from the table.
image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Eksport contact https://mautic5.ddev.site/s/contacts/batchExport?filetype=csv
3. A log file should be created in audit log

### CODE REVIEW

**Review by escopecz — CHANGES_REQUESTED** [review]
Please check how to set a new monolog handler in https://symfony.com/doc/5.x/logging.html. This is where they are configured for prod in Mautic:

https://github.com/mautic/mautic/blob/5.x/app/config/config_prod.php#L32

But I would simply suggest to use some logging service like SumoLogic for this use case where you can search for specific log in the all log messages. There is no need for specific file for specific logs.

Another option could be to write these actions to the audit log table instead of a file. This way you can search for it in the database and/or in the audit log report.

**Comment by tomekkowalczyk** [comment]
@escopecz thanks for the tips. I liked the idea of ​​placing the logs in the database. Have you thought about adding an entry to the audit_log table, from what I see, the table stores references to entities, e.g. a similar object that is saved ContactExportScheduler, only here we don't have an export object. Or would we rather go to a separate audit_log_exports table? I'd rather ask so as not to make corrections later.

**Comment by escopecz** [comment]
If you need an export feature, you can use the [Audit Log Report](https://github.com/mautic/mautic/pull/13373) added in M5.1. It allows admins to filter for whatever information they want in the audit log table and review the data. And it plays nicely with the export feature in Mautic reports. The reports can be also scheduled and sent to some email address based on the schedule the user configures. Is that what you meant?

**Comment by tomekkowalczyk** [comment]
@escopecz I have corrected the solution based on your comments.

**Review by AlanWierzchonCA — APPROVED** [review]
Looks good to me.

**Review by patrykgruszka — CHANGES_REQUESTED** [review]
Works fine, the export info is stored in audit_log table.

Would be good to add the `ContactExports` type to list in `CoreBundle/EventListener/ReportSubscriber.php:66`, so it could be available in report filter, like the `ContactExportScheduler`.

image

**Comment by tomekkowalczyk** [comment]
@patrykgruszka great idea, I added a filter
image
image

**Review by patrykgruszka — APPROVED** [review]

**Pull request merged**
