### PR TITLE
Fix getUrl for Mautic in directory

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
When I used Mautic in directory (for example http://mautic.test/mautic/)  Mautic gave me errors. This should fix it.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1.  Use mautic in directory (http://mautic.test/mautic/)
2.  Create form and use it test page
3. See browser console and 404 error (scritp call non exist http://mautic.test/mautic/mautic/media/js/mautic-form.js)

#### Steps to test this PR:
1. Repeat steps
2. See brower console clear

### CODE REVIEW

**Comment by robwent** [comment]
I have just tested this on 2 installs where images were not showing in the email builder.

One site is on localhost:6060/mautic/ and the other is in a folder on a subdomain apps.domain.com/mautic

In both cases, this broke the paths for all assets making the admin area unusable.

**Comment by kuzmany** [comment]
@robwent confirmed :( i'll try fix it

**Comment by yakov116** [comment]
@kuzmany any update?

**Comment by kuzmany** [comment]
@yakov116  @robwent  Could you test update?

**Comment by robwent** [comment]
I've tested on 3 domains.
A localhost folder
http://localhost:6060/mautic/
a live sub folder
http://domain.com/mautic/
and a normal install in the root of a subdomain
http://marketing.domain.com/

CSS and JS links are fine on all 3 sites.

Images now show in email previews in the first 2 sites but are now broken in the site that's in the root.
All the slashes are stripped so they look like this:

    https://marketing.domain.com/themessundayimglogo.gif

**Comment by rodrake1** [comment]
This fix didn't work for me: "Fix getUrl for Mautic in directory			8436808"

When I change: $url = $this->packages->getUrl($path, $packageName, $version);
for this: $url = ((strpos($path, '/') !== 0)?'/':'').$path;
on the file "AssetsHelper.php, my Mautic Dashboard loses all the styling like the image.

This happens even when I set my SiteUrl to http://mydomain.com/mautic or just http://mydomain.com

So I had to turn back the changes but my campaign links keeps doubling mautic folder in url paths. Anyone knows how to solve or am I doing this wrong?

printscr

**Comment by robwent** [comment]
@rodrake1 I think that was the previous version. The latest is here https://github.com/mautic/mautic/pull/4148/commits/a1a29e5340b22dd5f3e8faf50a5937e9d9a7e417

**Comment by kuzmany** [comment]
@robwent thanks for tests. Bugfix need another touch again  👍

**Comment by kuzmany** [comment]
@robwent could you test again? Hope now works everywhwere

**Comment by rodrake1** [comment]
When I make this changes, the Site Url on settings should me http://mydomain.com/mautic or just http://mydomain.com ?

**Comment by kuggaa** [comment]
Choice like word press but alway default to tld.com/mautic-version

**Comment by dongilbert** [comment]
+1

**Comment by YosuCadilla** [comment]
I had a similar problem with the landingpage/email builder where images would not show...

mautic-page-builder-missing-images

It got fixed by simply removing the extra " /mautic" in mautic's configuration...

However now accessing the builder seems to break SSL protocol, which keeps broken in the rest of mautic until you log out and log back in.

**Pull request merged**
