### PR TITLE
Add Symphony Messenger Only

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | Y
| Deprecations?                          | N
| BC breaks? (use the c.x branch)        | N
| Automated tests included?              | Y 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes  

#### Description:

I think PR #11180 is too big and it makes it hard for other developers to test and review file changes, I made this new PR to install `symfony/messenger` as a new bundle and install the required packages along with the configuration UI for the new bundle. **Once we get this PR approved and merged, I will make a new PR that will contain messenger alone**

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Go to the configuration page, check for `Messenger Configuration`
3. Go to `local.php` and see the values of `messenger_dsn` changes according to the settings you fill
4. If you disabled Messenger you should see in `local.php` `messenger_type`  => `sync`
5. Messenger configuration for doctrine variables can be found on https://symfony.com/doc/current/messenger.html#doctrine-transport

### CODE REVIEW

**Comment by mabumusa1** [comment]
@escopecz @mollux I can not figure out why `phpstan` is failing for this PR, I did not change these two files and I am not sure why `phpstan` is not accepting them

**Comment by mollux** [comment]
@mabumusa1 

there are **a lot** more packages updated than you probably intended.
One of them being `phpstan/phpstan`, which is most likely the reason you see phpstan failures for files you didn't change.

Please change this PR to only modify packages related to the change you want to do.

```
composer2 diff -b 5.x
| Prod Packages                  | Operation | Base     | Target   |
|--------------------------------|-----------|----------|----------|
| aws/aws-sdk-php                | Upgraded  | 3.235.1  | 3.238.5  |
| composer/ca-bundle             | Upgraded  | 1.3.3    | 1.3.4    |
| doctrine/collections           | Upgraded  | 1.7.2    | 1.8.0    |
| doctrine/common                | Upgraded  | 3.4.0    | 3.4.3    |
| doctrine/event-manager         | Upgraded  | 1.1.2    | 1.2.0    |
| doctrine/inflector             | Upgraded  | 2.0.4    | 2.0.5    |
| doctrine/orm                   | Upgraded  | 2.13.1   | 2.13.3   |
| doctrine/persistence           | Upgraded  | 2.5.4    | 2.5.5    |
| ezyang/htmlpurifier            | Upgraded  | v4.14.0  | v4.16.0  |
| friendsofsymfony/rest-bundle   | Upgraded  | 3.3.0    | 3.4.0    |
| giggsey/libphonenumber-for-php | Upgraded  | 8.12.56  | 8.12.57  |
| jms/metadata                   | Upgraded  | 2.6.1    | 2.7.0    |
| jms/serializer                 | Upgraded  | 3.18.1   | 3.18.2   |
| jms/serializer-bundle          | Upgraded  | 4.0.2    | 4.2.0    |
| laminas/laminas-code           | Upgraded  | 4.6.0    | 4.7.0    |
| league/flysystem               | Upgraded  | 1.1.9    | 1.1.10   |
| phpoffice/phpspreadsheet       | Upgraded  | 1.24.1   | 1.25.2   |
| phpstan/phpdoc-parser          | Upgraded  | 1.9.0    | 1.11.0   |
| psr/event-dispatcher           | New       | -        | 1.0.0    |
| symfony/amqp-messenger         | New       | -        | v5.4.13  |
| symfony/asset                  | Upgraded  | v4.4.40  | v4.4.46  |
| symfony/cache                  | Upgraded  | v4.4.44  | v4.4.46  |
| symfony/console                | Upgraded  | v4.4.45  | v4.4.47  |
| symfony/doctrine-bridge        | Upgraded  | v4.4.44  | v4.4.46  |
| symfony/doctrine-messenger     | New       | -        | v5.4.12  |
| symfony/expression-language    | Upgraded  | v4.4.44  | v4.4.47  |
| symfony/form                   | Upgraded  | v4.4.45  | v4.4.46  |
| symfony/framework-bundle       | Upgraded  | v4.4.45  | v4.4.47  |
| symfony/http-client            | Upgraded  | v4.4.45  | v4.4.47  |
| symfony/http-foundation        | Upgraded  | v4.4.45  | v4.4.47  |
| symfony/http-kernel            | Upgraded  | v4.4.45  | v4.4.47  |
| symfony/intl                   | Upgraded  | v4.4.44  | v4.4.47  |
| symfony/mailer                 | New       | -        | v5.4.13  |
| symfony/messenger              | New       | -        | v5.4.14  |
| symfony/mime                   | Upgraded  | v5.4.12  | v5.4.14  |
| symfony/redis-messenger        | New       | -        | v5.4.13  |
| symfony/security               | Upgraded  | v4.4.44  | v4.4.47  |
| symfony/stopwatch              | Upgraded  | v4.4.38  | v4.4.46  |
| symfony/string                 | Upgraded  | v5.4.12  | v5.4.14  |
| symfony/translation            | Upgraded  | v4.4.45  | v4.4.47  |
| symfony/validator              | Upgraded  | v4.4.45  | v4.4.47  |
| symfony/var-dumper             | Upgraded  | v4.4.41  | v4.4.47  |
| tightenco/collect              | Upgraded  | v8.83.23 | v8.83.25 |

| Dev Packages                      | Operation | Base    | Target  |
|-----------------------------------|-----------|---------|---------|
| php-http/client-common            | Upgraded  | 2.5.0   | 2.6.0   |
| phpstan/phpstan                   | Upgraded  | 1.8.6   | 1.8.9   |
| phpunit/php-code-coverage         | Upgraded  | 9.2.15  | 9.2.17  |
| phpunit/phpunit                   | Upgraded  | 9.5.20  | 9.5.25  |
| rector/rector                     | Upgraded  | 0.14.3  | 0.14.5  |
| sebastian/comparator              | Upgraded  | 4.0.6   | 4.0.8   |
| sebastian/exporter                | Upgraded  | 4.0.4   | 4.0.5   |
| sebastian/type                    | Upgraded  | 3.0.0   | 3.2.0   |
| symfony/browser-kit               | Upgraded  | v4.4.37 | v4.4.44 |
| symfony/dom-crawler               | Upgraded  | v4.4.39 | v4.4.45 |
| symfony/maker-bundle              | Upgraded  | v1.39.0 | v1.39.1 |
| symfony/web-profiler-bundle       | Upgraded  | v4.4.41 | v4.4.47 |
| phpdocumentor/reflection-common   | Removed   | 2.2.0   | -       |
| phpdocumentor/reflection-docblock | Removed   | 5.3.0   | -       |
| phpdocumentor/type-resolver       | Removed   | 1.6.1   | -       |
| phpspec/prophecy                  | Removed   | v1.15.0 | -       |
| webmozart/assert                  | Removed   | 1.11.0  | -       |
```

**Review by mollux — CHANGES_REQUESTED** [review]
Please only modify packages related to this PR, see https://github.com/mautic/mautic/pull/11596#issuecomment-1279959930 for more context

**Comment by mabumusa1** [comment]
> Please only modify packages related to this PR, see [#11596 (comment)](https://github.com/mautic/mautic/pull/11596#issuecomment-1279959930) for more context

Thanks @mollux for the tip, I fixed the issue, I think this PR is ready for review now

**Comment by mabumusa1** [comment]
> @escopecz @mollux I can not figure out why `phpstan` is failing for this PR, I did not change these two files and I am not sure why `phpstan` is not accepting them

For future developers who might have this issue, when you add new packages to `app/composer.json` do not use `composer install` but use `composer update --lock`

**Comment by mabumusa1** [comment]
This PR is closed in favor of #11598, I created a branch on Mautic repo instead of my fork

**Pull request closed without merging**
