### PR TITLE
Add segment filter to various reports

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR added segment filter to several reports type:
- assets download
- email stats
- form submission
- page hits
- video hits

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create item related to some contact for each entities above
3. Then test segment filter for each entities report.

image

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/7585"></a>

### CODE REVIEW

**Comment by aymericfrancois** [comment]
Tested this PR. Everything works except the "E-mail sent" report.

How to reproduce :
1. Create two contacts "One" and "Two".
2. Create a segment "Segment A" and add contacts "One" and "Two" in it.
3. Create a segment "Segment B" and add contact "One" in it.
4. Create a "Segment Email" and send it to the segment "Segment A".
5. Create a report with "Email sent" data source.
6. In data, add : "ID" and "Contact email"
7. In filters, add "Segment" equals "Segment B".
8. Save and close.

Then, this happens.

2019-06-05_10h44_11

**Comment by kuzmany** [comment]
@aymericfrancois fixed. Please re-test

**Comment by aymericfrancois** [comment]
Works perfectly ! :)

**Review by aymericfrancois — DISMISSED** [review]

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
Bumping to 3.2 due to unresolved Travis build failure.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by dennisameling** [comment]
Hi @kuzmany! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since this PR has conflicts now, could you please do a `git merge upstream/features` locally to resolve the conflicts? Thanks in advance!

**Comment by PatrickJenkner** [comment]
I was unable to start this on Gitpod. It gave the following error: 
Failed to start mautic: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-mautic docker-compose -f /workspace/mautic/.ddev/.ddev-docker-compose-full.yaml up --build -d', action='[up --build -d]', err='exit status 15', stdout='', stderr='services.web.extra_hosts array items[0,1] must be unique'

**Comment by RCheesley** [comment]
@kuzmany conflicts to resolve here - @PatrickJenkner sorry about that, I expect that it's because there are file conflicts which need resolving which breaks the build.

**Comment by RCheesley** [comment]
Removing from the OSF board until conflicts are addressed.

**Comment by RCheesley** [comment]
@kuzmany is this a keep or a close PR?

**Comment by kuzmany** [comment]
Close at the moment. We will push it again once ready to M5

**Pull request closed without merging**
