### PR TITLE
Connectwise plugin

### PR DESCRIPTION
**Pull request by mqueme**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/198
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This is first introduction to connectwise plugin.

Steps to test this PR.
1. you will need a Connectwise Manage account and companyId in order to test this PR
2. an API member, this can be done in the thick Client.
3. enter you companyId+publicKey and your privateKey
4. map your fields for companies and contacts
5. use the CLI command to pull contacts and companies from Connectwise <php app/console mautic:integration:fetchleads  --integration=Connectwise --time-interval='29 days' --env dev>
6. use a campaign action to push Contacts to connectwise

### CODE REVIEW

**Comment by escopecz** [comment]
@mqueme this is failing some CI tests. Please look at it.

**Comment by mqueme** [comment]
@escopecz it was some declarations

**Comment by matishaladiwala** [comment]
I was able to send contacts to CW through a campaign action and the form. However, I was not able to pull back any contact info into Mautic. Also there is no option in the plugin config to enable the overall sync.

**Comment by matishaladiwala** [comment]
Works for me now!

**Pull request merged**
