### PR TITLE
Focus items in dynamic web content

### PR DESCRIPTION
**Pull request by hluchas**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for features or enhancements / 3.2 for bug fixes 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
Issue: When using the

{focus=_ID#_}

token in dynamic web content, the js link is relative rather than absolute. For example, instead of src="http://your.etsu.edu/focus/20.js", it's src=”/focus/20.js”.

#### Steps to reproduce the bug:
1. Use test steps. Focus Item does not work

#### Steps to test this PR:
1. Create focus item and publish it
2. Create DWC 
 	- Use content `MAUT-4230 DWC content {focus=1}` where `1` is id of your created focus item
	- Is campaign based = no
	- Requested Slot Name = `slot1`
	- Add filter - `Country = Czech Republic`
3. Create landing page 
	- with dynamic content where
	- Slot name is `slot1`
	- Slot content is `Dynamic web content applied {dwc=slot1}‍ `
4. Use incognito mode in browser
	- add conrtact via form in incognito mode - contact should be added to CS
	- try to show page created in step 3 in incognito mode - focus item is not displayed
	- in CS set country to Czech Republic for this contact
	- reload page in incognito mode - focus item is displayed - JS is loaded

Snímek obrazovky 2020-12-11 v 13 43 28
Snímek obrazovky 2020-12-11 v 13 46 24
Snímek obrazovky 2020-12-11 v 13 46 35

### CODE REVIEW

**Review by kuzmany — APPROVED** [review]
Similar fix like https://github.com/mautic/mautic/pull/9349
Code looks good.
Unit test 👍

**Comment by hluchas** [comment]
> Similar fix like #9349
> Code looks good.
> Unit test 👍

Ups. Your PR should be closed I think .... ;-)

**Comment by kuzmany** [comment]
@hluchas It's just similar issue, but not same ;) Both resolve same issue but in different part of Mautic ;)

**Comment by hluchas** [comment]
Tested and works well ---
Snimek obrazovky 2021-01-08 v 10 39 44

**Pull request merged**
