### PR TITLE
[UI] Replace most of FA icons

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR replaces most used FA icons with the new icon pack.

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Reports > Open a few
3. Contacts > Open and see the history (you have to have contacts first)

### CODE REVIEW

**Comment by andersonjeccel** [comment]
I'm afraid to keep going bc of how many files would be changed
Would it be a problem to review?

**Comment by escopecz** [comment]
Thanks for taking care of this! It will prepare the project to remove Font Awesome in M6!. 

Yep, let's split it into more manageable chunks. Or at least do not add more until this is merged. Get this ready for review. There is 1 CS issue.

**Comment by andersonjeccel** [comment]
Next steps would be to:
1st: change remaining icons
Then remove classes like `fa fa-fw` and also check JS code using the prefix `fa`

**Comment by andersonjeccel** [comment]
@escopecz 
Fixed
Why can't the CS task automatically fix instead of asking for devs to manually go there?

**Comment by escopecz** [comment]
There were some discussions on this topic. For example https://github.com/mautic/mautic/pull/11876. But I think it's better to configure PHP CS Fixer on your IDE then having extra commits by some bot in a PR that you are working on.

**Review by kuzmany — DISMISSED** [review]
I didn't understand just  these two icons:

image

But If it's Intent, then go 👍

**Comment by andersonjeccel** [comment]
@kuzmany 

Group icon to indicate it's available to other users

image

Fixed search

image

Thanks for testing!

**Review by LordRembo — CHANGES_REQUESTED** [review]
I propose to make those small icons that were mentioned, a bit bigger if possible. Eg. the ones @kuzmany mentioned. I don't have terrible eyesight but I can't determine what these icons are at that scale.

**Comment by andersonjeccel** [comment]
@LordRembo What do you think about the text itself? 
13px font size 
Sometimes I think that perhaps 10 years ago, high screen resolutions might were not widely available, it always seemed too small for me

If we increase the font size by 1px, the icons will follow with their relative unit for font size (and if not, I can increase manually anyway)

**Comment by andersonjeccel** [comment]
@escopecz It seems like GitHub actions issues instead of something related to the PR

**Comment by andersonjeccel** [comment]
PR increasing icons size here: https://github.com/mautic/mautic/pull/13825

**Comment by andersonjeccel** [comment]
@abhisekmazumdar Would you like to test this one? We just need one before it's ready to commit

**Review by abhisekmazumdar — APPROVED** [review]
Visually, I see the icons look good and are being replaced.

**Comment by escopecz** [comment]
@andersonjeccel ignore the Codecov push errors. It's [reported](https://github.com/codecov/feedback/issues/358) but still not resolved.

**Pull request merged**
