### PR TITLE
Improve notification readability with max width

### PR DESCRIPTION
**Pull request by dadarya0**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | Yes
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | No 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Improve notification readability width max width

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Set config  `create_custom_field_in_background` => true
3. create a new custom field
4. execute `bin/console mautic:custom-field:create-column` to create custom field in background
5. Now notification should be ready in notification section
6. It should be readable properly

### CODE REVIEW

**Review by rohitpavaskar — APPROVED** [review]

**Review by rohitpavaskar — DISMISSED** [review]

**Comment by Galokh66** [comment]
Tested the new notification width
Screenshot 2024-04-18 at 7 29 04 PM

**Review by Galokh66 — DISMISSED** [review]

**Comment by escopecz** [comment]
@dadarya0 there is a conflict. That got me thinking that app.css is autogenerated from the LESS files, isn't it? So making changes to it without making the changes to a LESS file doesn't make sense. See https://contribute.mautic.org/contributing-to-mautic/developer/local-environment-setup#development-environment to read about the CSS from LESS generation.

**Comment by dadarya0** [comment]
@rohitpavaskar @Galokh66 please reapprove PR, conflict resolved.

**Review by Galokh66 — APPROVED** [review]

**Review by escopecz — APPROVED** [review]
Thanks! 👍

**Pull request merged**
