### PR TITLE
improve utf8 support for themes

### PR DESCRIPTION
**Pull request by galvani**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [X]
| New feature/enhancement? (use the a.x branch)      | [X]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [X] 
| Issue(s) addressed                     | Fixes #... 

#### Description:

json may contain encoded utf8 strings and should be parsed accordingly. 

#### Steps to test this PR:

there is unit test included that explains the issue. I have no recommendation how to test it.

### CODE REVIEW

**Comment by kuzmany** [comment]
@galvani can you please add steps to reproduce?

**Review by escopecz — APPROVED** [review]
I see no issue with the changed code.

**Comment by RCheesley** [comment]
@galvani if you wish this to be merged, testers need instructions. Please provide them with step by step processes to follow to confirm this does what it should.  I'll bring it back into the open source friday board once you've done this. Thanks!

**Comment by galvani** [comment]
actually this is not needed, the exception was caused by ut8_encode functions from the beginnig on.

**Pull request closed without merging**
