### PR TITLE
Fixing Custom Objects plugin - Upsert functionality 4.4

### PR DESCRIPTION
**Pull request by aarohiprasad**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #11654 https://github.com/mautic/mautic/pull/11654#issuecomment-1326170804

#### Description:

Contains cherry picked commits from https://github.com/mautic/mautic/pull/11654
See: https://github.com/mautic/mautic/pull/11654#issuecomment-1326170804

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. 

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11746"></a>

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
Thank you! Looks good. Merging as it cannot be tested manually and the code changes are the same as for the M5 PR.

**Comment by Moongazer** [comment]
+1 upvote for this

**Comment by escopecz** [comment]
@Moongazer no need for a +1. It's been released in Mautic 4.4.5

**Comment by Moongazer** [comment]
Sorry just saw the release of 2 days ago, awesome! Thanks a lot

**Pull request merged**
