### PR TITLE
Clean push data before we send to integration

### PR DESCRIPTION
**Pull request by alanhartless**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

If a contact value contains an encoded html entity, that entity is passed to the integration in raw text. This PR decodes and strips tags (for safety) to ensure that things like `&#39;` are sent as `'`. 

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a contact with `McDonald's` in the name. Check the database directly and the name should be `McDonald&#39;s`. 
2. Push to Salesforce
3. Note that the name remains with the decoded entity

#### Steps to test this PR:
1. Repeat and the name should have a single quote now

### CODE REVIEW

**Comment by mqueme** [comment]
This did not work for me: text in Last Name = 'International&#39; 
what it imported to in SF 
screen shot 2017-05-05 at 12 59 51

**Comment by alanhartless** [comment]
Can you look at your database record to see if `&#39;` is double encoded?

**Comment by alanhartless** [comment]
@mqueme ^

**Comment by escopecz** [comment]
I think it didn't work for me either. This is how it's looking in Mautic:
screen shot 2017-05-05 at 14 53 29
And when pushed to SF:
screen shot 2017-05-05 at 14 53 16

**Comment by alanhartless** [comment]
I missed the composite one. Try again. I also updated the instructions.

**Comment by mqueme** [comment]
it worked this time for me.

**Pull request merged**
