### PR TITLE
Dropping support for PHP 8.0

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🟢
| BC breaks? (use the c.x branch)        | grey area
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

As PHP 8.0 doesn't get security updates for over 6 months now ([source](https://www.php.net/supported-versions.php)) and Mautic now supports PHP 8.1, 8.2 and 8.3 it's time to drop 8.0.

We've never done this step in a minor Mautic release AFAIK, but I can see it's very common in other projects and libraries. Composer won't allow to update if the PHP version is not up for it.

But I'm OK if the community decides to wait for Mautic 6 with this change. The main issues in my mind are:
- Lack of security support.
- Developers cannot use the [PHP 8.1 features](https://www.php.net/releases/8.1/en.php) until we drop the support for 8.0. So we are forced to write dated code that we'll have to update at some point. And developers would be more productive with those features.
- The Github Actions now run for 4 different PHP versions which is waste of resources.

---
### 📋 Steps to test this PR:

1. Nothing to test as we are removing support, not adding anything new.

### CODE REVIEW

**Comment by matbcvo** [comment]
I fully support dropping PHP 8.0 support starting from the next minor release, such as version 5.x. However, implementing this change in Mautic 6 is also fine. Given that PHP 8.0 has reached end of life and no longer receives security updates.

**Review by matbcvo — APPROVED** [review]
Code changes looks good

**Review by andersonjeccel — APPROVED** [review]
Testing: everything seems normal 👌

**Comment by andersonjeccel** [comment]
but there are PHPSTAN errors, could you check the automated test?

**Comment by escopecz** [comment]
I've resolved the failing PHPSTAN issues in the last 2 commits. Please re-review.

**Review by RCheesley — APPROVED** [review]
Fine with me but let's make sure the marketing team are aware so they can make this clear in the 5.2 release marketing.

**Review by andersonjeccel — APPROVED** [review]
It's working in PHP 8.3.10 and most server panels already inform users to upgrade

image

**Pull request merged**
