### PR TITLE
Hide the input field for the batch size

### PR DESCRIPTION
**Pull request by volha-pivavarchyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [yes]
| Deprecations?                          | [x]
| BC breaks? (use the c.x branch)        | [x]
| Automated tests included?              | [x] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

The input field for the batch size on the email sending screen was hidden. See https://github.com/mautic/mautic/pull/10967 for previous discussions leading up to this decision.

image

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create new segment email
3. Try to send it
4. The input field is hidden

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11167"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
@volha-pivavarchyk why did you choose to hide it by CSS instead of removing it from the form completely?

**Comment by volha-pivavarchyk** [comment]
@escopecz 

Expected question. I tried to change the code as little as possible. If it is better to get rid of it completely, I will do that

**Comment by escopecz** [comment]
I'd vote for complete removal as it leads to leaner code. This way it leads more to dead code which we have a lot in this project already and everyone is afraid to touch it in case it's used in some weird cases.

**Comment by volha-pivavarchyk** [comment]
It will be done.

**Comment by volha-pivavarchyk** [comment]
@escopecz I removed the input field from the form completely

**Review by escopecz — DISMISSED** [review]
The code change looks good! Thank you! Please rebase on top of 5.x as there will be no other feature release for 4.x.

**Review by kuzmany — APPROVED** [review]

**Pull request merged**
