### PR TITLE
Multiple form on one page validation fix

### PR DESCRIPTION
**Pull request by escopecz**
Reported here https://www.mautic.org/community/index.php/556-multiple-forms-on-one-page

When 2 different forms are embedded to one page and both has field with the same name ("email" for example) the validation messages shows up only on the first form even though the second one was submitted.

#### How to test
1. Create the first form with required email field.
2. Create the second form with required email field.
3. Create a Landing Page.
4. Embed both forms to the Landing page.
5. Open the landing page on public URL
6. Try to submit the second form with empty email field.

Result: The error message shows up at the email field of the first form.

After applying this PR the message should appear on the form where the submit button was pressed.

Please, test also other fields than just email. The code had to be changed for all of them.

This PR also fixes populating field values from URL. For example:
```http://your-mautic.com/form/1/?email=leademail%40gmail.com``` wouldn't prefill the email field before the PR, but it does prefill it after this PR.

### CODE REVIEW

**Comment by drmmr763** [comment]
Needed to merge in https://github.com/mautic/mautic/pull/709 to test as well. 

Reproduced the error, tested multiple elements and validation scenarios. PR fixes it all. 
+ vote +1
+ vote +1

**Comment by Jornve** [comment]
After merging this PR i had problems creating new forms. Iv'e created a new form for testing, that works fine. (I did not got any error messages, but it could by my fault.) But when you want to edit the form in Mautic (clicking the edit icon on a form element), sometimes that form element was duplicated in the view, and i was unable to save it. (Mautic error page). Currently i'm deleting my entire installation to start with a fresh one. I'll keep you posted

**Comment by Jornve** [comment]
Just tested a fresh copy of Mautic with these PR and i found a bug. Like i said, when you create new form and you want to edit a form field, you got an error. Check the images. Anyone have a suggestion? 
screen shot 2015-08-05 at 14 17 03
screen shot 2015-08-05 at 14 17 06

**Comment by Jornve** [comment]
It seems to only throw this error when you want to modify a field when you did not have saved the form. As soon as you saved it, everything works :+1:

**Comment by Jornve** [comment]
I keep finding bugs, can someone test this to please? Validation works if you add one field to the form, if you have more than one form field the validation does not appear... 

I need to know if i'm the one making mistakes, it's the first time i work with git. I downloaded this PR, ran composer update and then installed a fresh Mautic true my browser to test this.

**Comment by mbabker** [comment]
If you ran `composer update` then it's possible you've updated Mautic's dependencies to versions we haven't tested with and may cause issues on its own.  When you download the repo, you'll want to run `composer install` which will install all the dependencies at the versions we have locked to.

**Comment by Jornve** [comment]
Thanks for answering mbabker. Did you test this PR yourself? I will retry.

**Comment by Jornve** [comment]
Thanks mbabker, you are the hero of the day! :+1:  I indeed made a mistake by running composer update instead of composer install. I downloaded the repo again, did composer update and now it everything works. I'm sorry for my shitty posts above, but it's my first time using git to download and install stuff :+1:

**Comment by alanhartless** [comment]
Added BC support for the old field names in the JS file since that file will be loaded for existing forms. But otherwise; worked for me.

**Pull request merged**
