### PR TITLE
Fix segment multiselect filters

### PR DESCRIPTION
**Pull request by MaxWebmecanik**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | ✔️ 
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #4075 #3357
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Segment filters on multiselect fields used to only let in contacts with only one matching option from that multiselect selected. This PR fixes that for contacts with multiple options selected.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
0. **(:star:BONUS:star:)** apply @kuzmany's PR #4080 for proper segment filter display
1. Create a multiselect field image
2. Create a segment filtering that field image
3. Create a few contacts using that field
    - One with only a single option selected
    - Another with multiple options selected
    - Another with all options selected
4. Run `mautic:segments:update`
5. Only the contacts with only a **single** matching option will get into the segment, those with multiple or all of them will not.

#### Steps to test this PR:
1. Repeat steps 1 to 4 above
2. Check that contacts with multiple or all options selected get in as well

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by jordan8037310** [comment]
Works for me! 🎉

**Comment by mqueme** [comment]
This doesn't work for me. it added a contact that had a|b|c selected.

screen shot 2017-06-16 at 14 14 11

**Comment by MaxWebmecanik** [comment]
@mqueme Does a simple exclusion work though?

**Comment by mqueme** [comment]
screen shot 2017-06-21 at 15 46 32
No, it still adds a contact that had a|b|c selected.

**Comment by MaxWebmecanik** [comment]
@mqueme Just did a bit of work, seems to fix it! Let me know how it works for you :)

**Comment by mqueme** [comment]
it worked now. Thanks!

**Pull request merged**
