### PR TITLE
[UX] Dashboard date range quick filters

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

Dependency:
- #13770 

This PR adds quick filters for date ranges on the dashboard.
It allows you to select ranges with 1 click instead of manually selecting each date on the calendar.

image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open the Dashboard, click on Quick filters and select any of them. See if the range date was automatically applied and all widgets updated.

### CODE REVIEW

**Review by MojisolaaaO — APPROVED** [review]
@andersonjeccel Test Passed. I was able to select ranges instead of manually selecting each date on the calendar. The date range was automatically applied and and all the widgets updated.

**Comment by MojisolaaaO** [comment]
@andersonjeccel Test Passed

**Review by Adedayo-Olaoluwa — APPROVED** [review]
@andersonjeccel test passed. Quick filters automatically applies date range to all the widgets on the dashboard.

**Comment by andersonjeccel** [comment]
@Adedayo-Olaoluwa @MojisolaaaO Thanks for reviewing! :)

**Pull request merged**
