### PR TITLE
Update date time text values

### PR DESCRIPTION
**Pull request by mqueme**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR allows users to enter human readable date values into date fields in the contact fields.

#### Steps to test this PR:
1. Apply PR and try to enter dates with the calendar, and dates with format like NOW, YESTERDAY, TOMORROW, it should not accept values like BLA or any non time word. 
2. these should be converted.
3. Test this in the contact edit page, campaign action to update a contact, form mapped to a datefield, integration mapped to a datefield.

### CODE REVIEW

**Comment by npracht** [comment]
@mqueme this for the edit contact page ?

**Comment by mqueme** [comment]
@npracht yes, also if you want to update a field with the campaign action to <update contact>

**Comment by npracht** [comment]
That is great !! Don't forget the documentation :P
Good job.

I know it is not exactly the same story, but it is also about the usage of this kind of values.
Can you have a look at https://github.com/mautic/mautic/issues/3495 ?

**Comment by javjim-mautic** [comment]
Tested failed:  @mqueme 
Didn't work  when creating custom date field in the default value

Test pass:
Worked on Contact edit page
worked on campaign

**Pull request merged**
