### PR TITLE
New Campaign actions:  Add/Remove Do Not Contact

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR added Add/Remove DNC as campaign actions

image

image

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create campaign and add contacts
3. Set Add Do Not Contact action
4. See If contacts were marked as DNC
5. Remove action and add new action: Remove Do Not Contact
6. See If contacts were unmarked as DNC

### CODE REVIEW

**Comment by florentpetitjean** [comment]
Hello,
The Remove Do not contact action doesn't work for contact that unsubscribe from email. Is that normal ? thanks,

**Comment by kuzmany** [comment]
Hi,

pricing is available now on website https://mtcextendee.com/multiple/

It’ 199€ unlimited use + 1 year free updates + another updates for 20% of price

--
Kind regards
Zdeno Kuzmany
Mautic Developer Expert
zdeno@kuzmany.biz<mailto:zdeno@kuzmany.biz>

Mautic extensions family
https://mtcextendee.com


________________________________

**Comment by kuzmany** [comment]
@florentpetitjean you're true.  
Last commit should fixed it. Please re-test

**Comment by florentpetitjean** [comment]
Tested and it works now

**Comment by drimlike** [comment]
+1 to get this feature available asap :)

**Comment by dennisameling** [comment]
Given the fact that multiple people are confirming here that the feature is working is expected, I'm gonna go ahead and merge this PR for the 2.16 release :)

**Pull request merged**
