### PR TITLE
Fix typo in SendEmailToContact.php

### PR DESCRIPTION
**Pull request by eltociear**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features"
| Bug fix?                               | yes

#### Description:
availble -> available

### CODE REVIEW

**Comment by npracht** [comment]
@cla-bot check

**Review by npracht — APPROVED** [review]
👍🏽

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Thanks for making the PR @eltociear - as soon as the tests are passing we will be good to merge! 🚀

**Comment by RCheesley** [comment]
@all-contributors please add @eltociear for code

**Pull request merged**
