### PR TITLE
Fix unique vs returning visitors widget

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
Unique vs returning visitors dashboard widget return wrong data. This PR try rebuild queryto return expected data

Query before

`SELECT COUNT(t.id) AS count FROM page_hits t WHERE t.date_hit BETWEEN :dateFrom AND :dateTo`

`SELECT COUNT(t.id) AS count FROM page_hits t WHERE (lead_id IS NULL) AND (t.date_hit BETWEEN :dateFrom AND :dateTo)`

Query after

`SELECT COUNT(*) as count FROM (SELECT t.id FROM page_hits t WHERE (lead_id IS NOT NULL) AND (date_left IS NULL) AND (redirect_id IS NULL)  AND (email_id IS NULL) AND (t.date_hit BETWEEN :dateFrom AND :dateTo) GROUP BY t.lead_id) tt`

`SELECT COUNT(*) as count FROM (SELECT t.id FROM page_hits t WHERE (lead_id IS NOT NULL) AND (date_left IS NULL) AND (redirect_id IS NULL)  AND (email_id IS NULL) AND (t.date_hit BETWEEN :dateFrom AND :dateTo) GROUP BY t.lead_id  HAVING COUNT(t.id) > 1) tt`

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create unique vs returning visitors dashboard widget on your instances with page_hits data
3. Check If you see correct pie graph 

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10302"></a>

### CODE REVIEW

**Comment by mlahlouh** [comment]
@kuzmany from DB perspective its a great improvement, But I need to change a small thing, starting from MySQL 5.7 the default value for SQL_MODE has ONLY_FULL_GROUP_BY, which means disallow SELECTing columns that are not referred to in the GROUP BY clause unless they are passed to an aggregate function like COUNT() or MAX().

So to avoid this just change query from:

- `SELECT COUNT(*) as count FROM (SELECT t.id FROM page_hits t WHERE (lead_id IS NOT NULL) AND (date_left IS NULL) AND (redirect_id IS NULL) AND (email_id IS NULL) AND (t.date_hit BETWEEN :dateFrom AND :dateTo) GROUP BY t.lead_id) tt`
- `SELECT COUNT(*) as count FROM (SELECT t.id FROM page_hits t WHERE (lead_id IS NOT NULL) AND (date_left IS NULL) AND (redirect_id IS NULL) AND (email_id IS NULL) AND (t.date_hit BETWEEN :dateFrom AND :dateTo) GROUP BY t.lead_id HAVING COUNT(t.id) > 1) tt`

To:
- `SELECT COUNT(*) as count FROM (SELECT t.lead_id FROM page_hits t WHERE (lead_id IS NOT NULL) AND (date_left IS NULL) AND (redirect_id IS NULL) AND (email_id IS NULL) AND (t.date_hit BETWEEN :dateFrom AND :dateTo) GROUP BY t.lead_id) tt`
- `SELECT COUNT(*) as count FROM (SELECT t.lead_id FROM page_hits t WHERE (lead_id IS NOT NULL) AND (date_left IS NULL) AND (redirect_id IS NULL) AND (email_id IS NULL) AND (t.date_hit BETWEEN :dateFrom AND :dateTo) GROUP BY t.lead_id HAVING COUNT(t.id) > 1) tt`


changing `t.id` to `t.lead_id`

BR.

**Comment by kuzmany** [comment]
@mlahlouh good catch. Thank you, I commit your suggestion.

**Comment by RCheesley** [comment]
Updated but this needs to be rebased.

**Comment by RCheesley** [comment]
Looks like a PHPSTAN error to fix on this one :)

**Comment by RCheesley** [comment]
Needs rebasing @kuzmany

**Comment by RCheesley** [comment]
Taking this off the OSF board until it's rebased.

**Comment by kuzmany** [comment]
Close favor to M5 version https://github.com/mautic/mautic/pull/12704

**Pull request closed without merging**
