### PR TITLE
[UI] Place UTM tags under accordion

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#200 
| Issue(s) addressed                     | Fixes #... 

## Description

Dependencies:
- #13940 

This PR:
- Creates a reusable accordion component in Twig
- Replaces all manual ways to display UTM fields and centralizes in one file (creates a reusable UTM tags fields component) to help us maintain them
- Then place UTM tags field under the accordion everywhere, reducing cognitive load caused by the amount of total fields on the screen when creating emails
Example (before):
image

- Adds padding-inline utilities, which applies both padding left and right using only one class, replacing the use of separate pr- (padding-right) and pl- (padding-left) classes for situations where you need them together.

| Before                                 | After
| -------------------------------------- | ---
| image                                        | image

When opened, works just fine:
image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Dynamic content > Create new > Check for the UTM tags on the panel
3. Repeat the same for Emails, Mobile notifications, Web notifications and Focus items
4. See if they are displaying all fields when clicked, with proper alignment

### CODE REVIEW

**Comment by MojisolaaaO** [comment]
@andersonjeccel Test Passed; the UTM tags fields are under an accordion. However, the "UTM Tags" text displayed above the accordion should be removed from the Dynamic Content, Emails, Mobile notifications, Web notifications, and Focus items screens, as it is already labeled on the accordion. [See Screenshot attached](https://monosnap.com/file/eIPToBM2hfiDJo08TdERyDxSINwQLn)

**Review by imaabasiee — APPROVED** [review]
Tested this PR [mautic/mautic#13984](https://github.com/mautic/mautic/pull/13984) and it passed. The UTM tags fields are under an accordion. Just as Mojisola said, there is a  "UTM Tags" text just above the UTM tags accordion, the text should be taken out. But in my own case, I found this on the Dynamic Content and Focus.

**Review by Aleks0129 — APPROVED** [review]
Looks good. 

Screenshot 2024-10-10 at 18 28 27

Screenshot 2024-10-10 at 18 27 53

Screenshot 2024-10-10 at 18 29 12

**Review by shinde-rahul — APPROVED** [review]
Code LGTM!!!

**Pull request merged**
