### PR TITLE
Fix typo in mautic-form-src.js

### PR DESCRIPTION
**Pull request by eltociear**
accoding -> according

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10553"></a>

### CODE REVIEW

**Review by npracht — APPROVED** [review]

**Comment by RCheesley** [comment]
As this was made on the 4.x rather than 4.0 branch this will go out in the 4.1 release next month.

**Comment by npracht** [comment]
@eltociear can you rebase against 4.0 branch please ?

**Review by escopecz — APPROVED** [review]
👍

**Comment by RCheesley** [comment]
As this doesn't make any changes in Mautic due to fixing a small typo in the comment, I'd say leave it on 4.x and it will be released with 4.1 at the end of the month, to save faffing about with a rebase.

**Pull request merged**
