### PR TITLE
Fix Salesforce multiselect field sync

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR fixed sync multiselect fiedls from and to Mautic.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Setup salesforce sync https://www.mautic.org/docs/en/plugins/salesforce.html
2. Create multiselect field in mautic and multiselect field in Salesforce 
3. Try sync it with at least two selected options from multiselect view
4. You should see nothing/or wrong/or error sync of this field

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat all steps and multiselect field should be synced properly

### CODE REVIEW

**Review by florentpetitjean — DISMISSED** [review]
Test and working

**Comment by dennisameling** [comment]
Taking this out of the 2.16.2 milestone since we need a 2nd test

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebased

**Comment by RCheesley** [comment]
Close & reopen for Scrutinizer

**Review by dennisameling — APPROVED** [review]
Set up a Salesforce dev account, then created a multiselect field:

image

The field shows up correctly in the Mautic field mapping UI:

image

Created a lead in Salesforce with 2 values selected:

image

Then ran `php bin/console mautic:integration:synccontacts --integration=Salesforce`:

```
denni@mautic3-web:/var/www/html$ php bin/console mautic:integration:synccontacts --integration=Salesforce --env=dev
Command to fetch contacts from integration
Fetch contacts command is starting
 1/1 [============================] 100% (Lead)
Fetching contacts...
    0/0 [>---------------------------]   0% (Contact)
0 contacts were updated and 1 contacts were created

Fetching companies
Fetch companies command is starting
    0/0 [>---------------------------]   0% (Account)
0 companies were updated and 0 companies were created

Updating/creating leads from Mautic to Salesforce
Number of contacts pushed: 0 updated, 0 created, 0 had errors and 0 were ignored (likely duplicates or didn't match field criteria)

Updating/creating companies from Mautic to Salesforce
About 0 to update and about 1 to create/update
 1/1 [============================] 100%
Number of companies pushed: 0 updated, 1 created, 0 had errors and 0 were ignored (likely duplicates or didn't match field criteria)
```

The "demo multiselect" field is indeed empty:

image

After applying this PR, creating a new lead in Salesforce, then syncing again, the lead has the proper demo multiselect field:

image

I had to make sure that the custom field values **exactly** matches those in Salesforce (case-sensitive).

Thanks a lot for this fix @kuzmany!!! 🚀

**Pull request merged**
