### PR TITLE
Fix Doctrine metadata cache handling during installation

### LINKED ISSUE #10480: Exception handling in UI installer (database step) broken
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

In https://github.com/mautic/mautic/pull/9934, a change was introduced in the UI and CLI installers that clears the cache before Mautic's database is installed. For the UI installer, it's these lines specifically:

https://github.com/mautic/mautic/blob/bf37c06008a936fe9e2919b4baa2d3220cfb6ad1/app/bundles/InstallBundle/Install/InstallService.php#L260-L262

This is executed right after a user enters their database credentials, but before we actually try to connect to the database and install the database structure. This is problematic, because when the cache folder is removed while running the script, it breaks Symfony's dependency injection. In simple terms: if anything goes wrong after the user entered their database credentials (wrong username, connection errors, etc.), the user is presented with a "This site is offline" error.

When running the installer in dev mode (`/index_dev.php/installer`), the actual error details pop up. At this point, the `cache/dev` folder was deleted completely by the `nukeCache()` function, which is causing this issue:

```
ErrorException: PHP Warning - require(/var/www/html/var/cache/dev/ContainerZboib0b/getMautic_Exception_ListenerService.php): failed to open stream: No such file or directory
```

image

Luckily, we don't _actually_ need to remove the entire cache folder during the installation process 🎉 It's enough [to just remove Doctrine's metadata cache](https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/reference/caching.html#clearing-the-cache), which fixes this issue. I've applied just that in #10481.

### How can we reproduce this issue?

Step 1: Open Mautic's UI installer (the dev version at `/index_dev.php/installer` is best for testing, as it shows the actual error in the browser instead of "this site is offline") 
Step 2: Go to the database step. **Make sure to enter incorrect database credentials** (e.g. set everything to 'dbdb')
Step 3: See the error

### Relevant log output

```shell
Prod log:


[2021-09-27 15:36:11] mautic.WARNING: PHP Warning - require(/var/www/html/var/cache/prod/ContainerXeQBF7N/getTranslation_Loader_PhpService.php): failed to open stream: No such file or directory - in file /var/www/html/var/cache/prod/ContainerXeQBF7N/appAppKernelProdContainer.php - at line 2225 {"file":"getTranslation_Loader_PhpService.php","lazyLoad":true} []
[2021-09-27 15:36:11] mautic.ERROR: PHP Notice: require(): Failed opening required '/var/www/html/var/cache/prod/ContainerXeQBF7N/getTranslation_Loader_PhpService.php' (include_path='.:/usr/share/php') - in file /var/www/html/var/cache/prod/ContainerXeQBF7N/appAppKernelProdContainer.php - at line 2225 [] []
[2021-09-27 15:36:11] mautic.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Notice: require(): Failed opening required '/var/www/html/var/cache/prod/ContainerXeQBF7N/getTranslation_Loader_PhpService.php' (include_path='.:/usr/share/php') - in file /var/www/html/var/cache/prod/ContainerXeQBF7N/appAppKernelProdContainer.php - at line 2225 [] []
```

Dev log (in browser):

```
ErrorException: PHP Warning - require(/var/www/html/var/cache/dev/ContainerZboib0b/getMautic_Exception_ListenerService.php): failed to open stream: No such file or directory
```
```


### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dennisameling**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 4.x
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | Fixes #10480 

#### Description:

As described in #10480, we currently remove the cache folder during the installation process. More specifically, just before the database is installed. This approach is problematic because it breaks things like Symfony's Dependency Injection, causing invalid database credentials and/or connection errors to completely crash the installer. Luckily, [Doctrine has an option to only remove the metadata cache](https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/reference/caching.html#clearing-the-cache), which is all we need (more context in https://github.com/mautic/mautic/pull/10481#issuecomment-930137452). This PR changes our logic so that we only clear the metadata cache. This fixes #10480 and significantly improves Mautic's installation speed.

#### Steps to test this PR:
1. Load up this PR locally
2. For the remainder of the steps, we assume that you're using DDEV for local development. This allows you to easily drop the database and start clean
3. Before testing each scenario below, please ensure you have a clean state where Mautic is not installed: `ddev delete --omit-snapshot --yes && rm -rf var/cache && rm app/config/local.php && ddev start`

**Scenarios to test**:

For testing the **CLI installation**, please run `ddev exec php bin/console mautic:install https://mautic.ddev.site --db_driver=pdo_mysql --db_host=db --db_user=db --db_name=db --db_password=db --db_port=3306 --db_table_prefix="mau_" --admin_password=mautic --admin_email="demo@ddev.local"` - simply remove `--db_table_prefix="mau_"` if you want to test without a prefix.

|Type| Database info | Expected outcome
|--|--|--|
|UI installation| Wrong credentials, NO prefix | ❌
|UI installation| Wrong credentials, WITH prefix | ❌
|UI installation| Correct credentials, NO prefix | ✅
|UI installation| Correct credentials, WITH prefix | ✅
|CLI installation| Wrong credentials, NO prefix | ❌
|CLI installation| Wrong credentials, WITH prefix | ❌
|CLI installation| Correct credentials, NO prefix | ✅
|CLI installation| Correct credentials, WITH prefix | ✅

### CODE REVIEW

**Review by kuzmany — CHANGES_REQUESTED** [review]
This looks good.
I tested ddev exec install, standard install with ddev start - both works
But If I make clean installation and run from browser `https://mautic.ddev.site/index_dev.php/installer` It  return error 

image

**Comment by dennisameling** [comment]
@kuzmany thanks for testing! I wasn't able to reproduce the `Connection refused` error - I ran `ddev delete --omit-snapshot --yes && rm -rf var/cache && rm app/config/local.php && ddev start` to ensure that I didn't have any cache or `local.php` file. I'm able to get through the database step without problems:

https://user-images.githubusercontent.com/17739158/134959722-18e9ef50-b361-4f72-b762-dfa57b75fb26.mp4

Would you mind showing me what exact steps you're taking to trigger this error? Thanks!

**Review by kuzmany — DISMISSED** [review]
Now works like charm. 
It was blocked by two 3th party plugins. 
Code make sense. 
Nice PR

**Comment by RCheesley** [comment]
@dennisameling should this be on the 4.x branch or 4.0? If we keep it to 4.x it won't get released until the end of November.

**Comment by dennisameling** [comment]
@RCheesley 4.0 in that case - wasn't aware of that sorry. Could we please update the PR template to mention this info? 😊  https://github.com/mautic/mautic/blob/4.x/.github/PULL_REQUEST_TEMPLATE.md

**Comment by RCheesley** [comment]
> Could we please update the PR template to mention this info? 😊 https://github.com/mautic/mautic/blob/4.x/.github/PULL_REQUEST_TEMPLATE.md

Absolutely - please review my open PRs:
https://github.com/mautic/mautic/pull/10440
https://github.com/mautic/mautic/pull/10439

**Comment by RCheesley** [comment]
When I am testing the UI installation with the prefix I am getting the error that the clearing cache was I believe implemented to fix:

> An error occurred while attempting to add default data: Table mau_leads does not exist!

screenshot-nimbus-capture-2021 09 28-14_16_08

**Comment by dennisameling** [comment]
> An error occurred while attempting to add default data: Table mau_leads does not exist!

@RCheesley Thanks for reporting this! I didn't run into this issue while testing as I was working with `/index_dev.php/installer`, where the error doesn't occur. So this is definitely a good catch 🕵🏼‍♀️ 

Found a solution for this in https://github.com/mautic/mautic/pull/10481/commits/040ee053e43108ec1ae2dbcb0a4ac1b89b1c097a! 🎉 Doctrine maintains a cache of metadata (e.g. table names). Once the installer starts for the first time, this cache is built without table prefixes (e.g. `oauth2_clients`). The user is able to provide a table prefix in the database step of the installer. After that, the database tables are created.

Just before we create the database tables, the cached metadata needs to be updated somehow in case the user provided a table prefix. Then, the table name mentioned earlier becomes `mau_oauth2_clients` for example. We don't need to remove the full cache folder (which is problematic as reported in https://github.com/mautic/mautic/issues/10480), but we can tell Doctrine to delete the cached metadata only. When running from the CLI, this can be done through `php bin/console orm:clear-cache:metadata`, but since we're running inside a script, we can run `$entityManager->getConfiguration()->getMetadataCache()->clear();` which does the trick as well.

Could you please test again now?

**Review by kuzmany — APPROVED** [review]
Looks good to me. 
Good catch. 
Unit tests included 
Approve it 👍

**Pull request merged**
