### PR TITLE
Removed event.origin check from embedded forms (javascript)

### PR DESCRIPTION
**Pull request by marcel-ambta**
| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | No 
| Related user documentation PR URL | No
| Related developer documentation PR URL |  No
| Issues addressed (#s or URLs) | #4287 #4588
| BC breaks? |  No
| Deprecations? |  No

#### Description:
If using the javascript function for placing forms, the postback is not handled because there is a check if the event origin is the same as the mautic domain, which is not always the case.

mautic-form-src.js line: 623
if (event.origin !== MauticDomain) return;

#### Steps to reproduce the bug:
1. Set-up Mautic envoirment
2. Make form, and copy javascript
3. Place form on other domain.

#### Steps to test this PR:
1. Set-up Mautic envoirment
2. Make form, and copy javascript
3. Place form on other domain.

### CODE REVIEW

**Comment by MichaelvanLaar** [comment]
I don’t know why this `MauticDomain` check exists at this point. But it definitely needs a fix because `MauticDomain` returns the Mautic URL, including the path—while `event.origin` returns only the protocol and the domain. That’s why a Mautic form doesn’t redirect anywhere if Mautic is installed in a subdirectory.

But instead of getting rid of the line completely, as suggested by @marcel-ambta, why not leave the test where it is and only fix the path problem. This can easily be done by replacing

```javascript
if (event.origin !== MauticDomain) return;
```

with

```javascript
var MauticDomainWithoutPath = MauticDomain.match(/https?:\/\/[^\/]*/);
if (event.origin != MauticDomainWithoutPath) return;
```

**Comment by KJURKOWSKIHCS** [comment]
Can confirm this works! Update in both /mautic-form-src.js and /mautic-form.js, the code [code]if (event.origin !== MauticDomain) return;[/code] is in both of them. Search for "event.origin" if you can't find that line, that'll help find it.

Then replace [code]if (event.origin !== MauticDomain) return;[/code] 

with 

[code]var MauticDomainWithoutPath = MauticDomain.match(/https?:\/\/[^\/]*/);
if (event.origin != MauticDomainWithoutPath) return;[/code] 

in both files like PR says.

Thanks @MichaelvanLaar !

PS: You need SSL for your mautic domain, or at least I did (https://www.mautic.org/community/index.php/2802-mautic-http-to-https/0), and you can't be logged in to your mautic account in the same browser as trying to submit the form (at least I couldn't be), or it'll hang. After applying the code change in both /mautic-form-src.js and /mautic-form.js and having SSL, it'll submit in incognito window every time.

**Comment by marcel-ambta** [comment]
@MichaelvanLaar The check is client-side and does not add any security advantage in my opinion. 

Your solution does not work if you run your Mautic environments on another domain. I have suggested to use the CORS list but still it does not add anything security wise.  So in my opinion we can just remove the line.

**Comment by MichaelvanLaar** [comment]
@marcel-ambta I tested a Mautic form embedded via script in a page on another domain and it worked. Of course I adapted the CORS setting in my Mautic instance accordingly.

As far as I got it right, the check compares the origin of the mautic-form.js file (= event.origin) with the content of the “Mautic URL” field of the Mautic configuration page. The only reason for this test I can think of is making sure that the “original” mautic-form.js is used and not a mautic-form.js file served from a different location. But if somebody would like to do some kind of hacking by using a modified mautic-form.js, I’m sure they would delete or adapt this line. So in the end I can’t see much use of it either.

**Comment by escopecz** [comment]
I'll put [this hidden comment](https://github.com/mautic/mautic/issues/4287#issuecomment-321979438) about this issue here so we can consider it:

> please be aware that removing this check may create issues with other embeds (like video, facebook etc.). Many of the embeds (based on iframe) communicate with main page using post message, therefor mautic callback will start handing (and failing) messages from 3rd party embeds.
In my case ( #4588 ) I had issues with MauticDomain being a subfolder of main domain. So I solved it by substring check. Please be aware that specification of event.origin states that origin will not include subfolders - only host part. IMHO if mautic JS and the form are hosted on same domain it should work.

**Comment by pavel-janicek** [comment]
Solved probem when manually generated forms were not forwarding the user after submit.
+1 Thanks for this solution

**Comment by MichaelvanLaar** [comment]
@marcel-ambta and @escopecz and @leonidr: 
To be absolutely sure, I tested the solution I suggested above again and included `console.log` output (as well as a breakpoint to be able to read the output before the redirect happens).

**Here is my test setup:**
- Base URL of my Mautic installation for testing purposes: https://dev.michaelvanlaar.com/mautic/
- Test page with the embedded form: https://digitalardor.com/mautic-test/ (not publicly accessible)
- “Successful Submit Action setting”: Redirect to https://www.google.com/

**I included the form in all possible ways:**

1. option “Automatic, via JavaScript”
2. option “Automatic, via iframe”
3. option “Manual Copy”

**The result:**
All three of them worked. On submission the form input was sent to Mautic and the redirect was executed.

The `console.log` output was the same in all three cases:
```
event.origin:            https://dev.michaelvanlaar.com
MauticDomain:            https://dev.michaelvanlaar.com/mautic
MauticDomainWithoutPath: https://dev.michaelvanlaar.com
```

The surrounding page of the embedded form never showed up as `event.origin`.

So even if my suggested solution is not the best one (… instead the variable `MauticDomain` should be renamed to `MauticURL` system-wide because its value is not a domain but a URL …), it worked in all of my test cases.

If the queried line `if (event.origin !== MauticDomain) return;` actually makes sense—and thus should be modified instead of being deleted—is beyond my insight into the Mautic code so far.

**Comment by alanhartless** [comment]
This is the reason I don't want to remove it: https://github.com/mautic/mautic/pull/4656#issuecomment-323663700

So instead of removing the line, let's fix it to work correctly with subfolders.

**Comment by orangeattitude** [comment]
Hi guys, this solution still doesn't work on 2.10 +

**Comment by Schokolader** [comment]
how is this going? Maybe this is related to that: https://github.com/mautic/mautic/issues/4652 

Still on 2.10.1 not working

**Comment by khaoua** [comment]
@MichaelvanLaar thanks for the sharing, is it working on version 2.10.1 ? I haven't tested it yet, only thing I know is that it was working before on 2.8 and a bit later versions. I then updated mautic domain as described on this link below, but still, issue happens on landing pages although domain is aligned in wp-plugin, form and 3rd party website tracking code

tracking works, but submit button keeps showing "please wait..."

https://mautic.com/help/forms-hanging/

**Comment by khaoua** [comment]
tested just now on 2.10.1, it works on my side

**Comment by leonidr** [comment]
@MichaelvanLaar , manually applied you proposal to 2.10.1. Works in my case. Thanks!

**Comment by bossanyit** [comment]
Actually, a working regexp for the mautic-form.js and mautic-form-src.js is
```
  var MauticDomainWithoutPath = MauticDomain.match(/https?:\/\/[^\/]*/);
  if (event.origin != MauticDomainWithoutPath) return;
```
It works with 2.10.1

**Comment by langetacuna** [comment]
Confirmed bossanyit's fix works with 2.11.0.

**Comment by alanhartless** [comment]
Closing this because of https://github.com/mautic/mautic/pull/4656#issuecomment-328890594. Please submit a new PR better handling this issue.

**Pull request closed without merging**
