### PR TITLE
FIX: Ignoring of custom option list for mapped fields

### LINKED ISSUE #13306: Radio group in Forms doesn't respect properties
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When I create a radio group in a form and select NO for "Use assigned contact/company field's list choices" with only one optionlist, I get the original fields anyway.
I suspect it happens for Checkbox group.
Sorry, my Mautic is in italian

### How can we reproduce this issue?

Step 1: Create a form with a Radio Group
Step 2: Map a field which has got some options in "Mapped Field" tab, for example "Title" field.
Step 3:  Select NO in Properties tab on "Use assigned contact/company field's list choices" and add only one option list item
Step 4: Click on save or update
Step 5: You get Mr, Mrs, Miss choices anyway

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by putzwasser**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #13306 and #13542 

## Description

This PR fixes #13306 and #13542.

Currently, Mautic ignores dedicated labels for radio groups if they are mapped with a custom lead field. A new TWIG check prevents this behavior.

---
### 📋 Steps to test this PR:

1. Create a custom lead field:
    image

2. Create a form, add a radio group element and link it to the custom field
    image

3. Preview the form and see that these custom labels are ignored and the lead field's labels are used.
    image

4. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))

7. Reload the form and see that the custom labels are used instead of the lead field's labels.
    image

8. Set `Use assigned contact/company field's list choices.` to `Yes` and reload the form. See that the lead field's labels are used—just as expected.

**IMPORTANT:** If you don't see a change, then reload the dashboard. Mautic might override your custom labels, but this isn't reflected by the UI. It becomes visible after reloading the whole dashboard. Add your custom labels again.

### CODE REVIEW

**Review by Aleks0129 — APPROVED** [review]
Does what it says.

Screenshot 2024-09-28 at 18 38 50

Screenshot 2024-09-28 at 18 40 04

Once translating the field values the proper text appears 

Screenshot 2024-09-28 at 18 41 32

**Review by shinde-rahul — APPROVED** [review]
Code LGTM!!!

**Review by MojisolaaaO — CHANGES_REQUESTED** [review]
@putzwasser Test Passed. The custom labels are now used instead of the lead field's labels and setting the "Use assigned contact/company field's list choices" to "Yes"  uses the lead field's labels.

**Comment by MojisolaaaO** [comment]
@putzwasser Great work on the implementation. However, I noticed that when the "Use assigned contact/company field's list choices" is set back to "No", and the option list is not updated, the lead field labels are still used.

**Comment by putzwasser** [comment]
@MojisolaaaO That's to be expected as Mautic will override your custom labels with the ones specified for the custom lead field. Your custom labels aren't stored anywhere else, thus Mautic has no possibility to restore them.

You have to manually re-add your custom labels again.

Preserving your custom labels when switching to the default labels is out of scope for this PR.

**Review by escopecz — APPROVED** [review]
Code looks OK

**Pull request merged**
