### PR TITLE
[rector] [dead-code] Remove few ifs that are always true

### PR DESCRIPTION
**Pull request by TomasVotruba**
This is follow up to Rector integration https://github.com/mautic/mautic/pull/12676

I'm taking dead-code set rule by rule and slowly making changes, to make sure it's alligned with CI and everything is revied :+1: 
In the end @rectorphp will keep eye on the code with full dead-code set integration.

Thanks to the Rector I've also found 2 bugs :slightly_smiling_face:  - fix is coming in next PR.

This is ready to review :+1:

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I'm finished with changes :heavy_check_mark:

**Comment by TomasVotruba** [comment]
CI fail is unrelated, it's due Github CI issues - https://www.githubstatus.com

**Comment by TomasVotruba** [comment]
Good to go :heavy_check_mark:

**Review by escopecz — APPROVED** [review]
I reviewed all the removed if statements and I can confirm they were not needed. Thank you Tomas! 👍

**Comment by TomasVotruba** [comment]
Hi, just checking it there is any blocker to merge this one as it's been approved  :slightly_smiling_face: 

I have few other PRs coming up and these might get conflicts soon. I'd love avoid rebases if possible :+1: 

Thanks

**Comment by escopecz** [comment]
You know how open source contributors work. But since there are no voices against merging it and it's blocking you pushing more optimizations to the project, I'm merging it as I did check all the changes and they make logical sense. Thank you Tomas!

**Comment by TomasVotruba** [comment]
Thank you 🙏

My goal is to get Rector-core level quality here, so you can code with feedback and let Rector work for you.

**Pull request merged**
