### PR TITLE
Add support for PHP 7.1

### PR DESCRIPTION
**Pull request by mbardelmeijer**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | N
| Related user documentation PR URL | None
| Related developer documentation PR URL | None needed
| Issues addressed (#s or URLs) | None
| BC breaks? | None
| Deprecations? | None

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Add support for using mautic in a PHP 7.1 environment

### CODE REVIEW

**Comment by alanhartless** [comment]
@mbardelmeijer Have you noticed any issues with 7.1? The only thing that sticks out to me as a potential issue is that the DateTime objects now use microseconds in comparisons. Not sure if that will affect us or not.

**Comment by mbardelmeijer** [comment]
Haven't ran in any issues myself, but only run a single instance. If some more people could test this patch, that would be great 😄

**Comment by escopecz** [comment]
We had to revert changes with https://github.com/mautic/mautic/pull/3573 in this PR because of issue described there. Please, try to resove that issue and submit this PR again.

**Comment by alanhartless** [comment]
@mbardelmeijer Are you running cli/cron jobs on 7.1?

**Comment by mbardelmeijer** [comment]
Think i ran CLI on 7.0 :/ Will look into it when i have some spare time and create a new MR.

**Comment by vesper8** [comment]
+1 looking forward to support for 7.1 so I don't have to spawn a new vps just to run Mautic

**Comment by vesper8** [comment]
@mbardelmeijer I could be wrong but the 

```
An error occurred when executing the "'cache:clear --no-warmup'" command:

    [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
    You have requested a non-existent service "kernel.debug".
```

error seems to be related to https://github.com/sensiolabs/SensioDistributionBundle ?

This issue appears to be troubleshooting the same (or very similar) problem
https://github.com/sensiolabs/SensioDistributionBundle/issues/302

Also is it possible that running cache:clear with the --no-debug flag would also work as a workaround?

**Pull request merged**
