### PR TITLE
Fixed batch delete response inconsistencies

### PR DESCRIPTION
**Pull request by alanhartless**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Automated tests included? | y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This fixes the issue with inconsistent response formats when using the batch entity delete endpoint. It basically ensures that if the ID list from the request is keyed as an associative array, it'll return a json object response. If it's a simple array (sequential numeric array that starts with 0), it'll return a json array.

Yes, the implementation to start with is undesirable but this fixes the issue without introducing a BC break nor rewriting our API ;-) 

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Hit up the /api/contacts/batch/delete end a few times with different IDs
2. Note the response that sometimes the `contacts` array is json array and that sometimes it's a json object (keyed by a number)
3. Run the new unit tests

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat and the response should be consistent

### CODE REVIEW

**Comment by dennisameling** [comment]
@alanhartless would you mind fixing the conflicting file? Thanks 😊

**Comment by alanhartless** [comment]
I'll try tomorrow. I just tried to do it quickly and hit with errors around that stupid rename of unit to Unit and functional to Functional we did which the mac gives me a really hard time about. I might have to do this manually on a linux machine. 😅

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by npracht** [comment]
Hello @alanhartless could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback, i would very love to merge it in 3.0.1 if still relevant. Thanks !

**Comment by RCheesley** [comment]
@alanhartless can you take a look at the conflicts and if it is still relevant we can get it into one of the upcoming patch releases!

**Comment by RCheesley** [comment]
Bumping to 3.1.1 due to unresolved conflicts.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Hi folks, bumping this to 3.1.2 due to unresolved conflicts. 

@mautic/acquia-po this will need to be addressed by **18th October**

**Comment by dennisameling** [comment]
Bumping this to 3.2 due to unresolved conflicts. CC @mautic/acquia-po

**Comment by alanhartless** [comment]
Conflicts resolved.

**Review by dennisameling — APPROVED** [review]
Took some time to figure out how to properly use this undocumented API 😅 https://github.com/mautic/mautic/issues/6040

Can confirm the buggy behavior, sometimes it's a proper JSON array and sometimes it's objects:

`https://mautic3.ddev.site/api/contacts/batch/delete?ids[]=1&ids[]=2`

image

`https://mautic3.ddev.site/api/contacts/batch/delete?ids[]=11&ids[]=12`

image

After applying this PR, the responses are consistent:

`https://mautic3.ddev.site/api/contacts/batch/delete?ids[]=3&ids[]=4`

image

`https://mautic3.ddev.site/api/contacts/batch/delete?ids[]=5&ids[]=6`

image

Thanks @alanhartless!

**Pull request merged**
