### PR TITLE
Add a file form field

### PR DESCRIPTION
**Pull request by coudenysj**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #221
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

This pull request adds the possibility to add file fields to forms.

#### Steps to test this PR:
1. Edit or create a form
2. Add a form field

#### Todo

* Move validation
* Add more/less validation
* Decide where to store the binary data

### CODE REVIEW

**Comment by qneyrat** [comment]
Good job, I test it asap !

**Comment by coudenysj** [comment]
No review?

**Comment by Apaflesk** [comment]
@coudenysj @qneyrat this would be a great feature! How is the reviewing going?

**Comment by qneyrat** [comment]
It's good for me

**Comment by alanhartless** [comment]
@coudenysj It seemed this is incomplete. Is it possible to wrap it up so we can consider it for merger?

**Comment by coudenysj** [comment]
@alanhartless Happy to do so, but I need some feedback from you guys (see the TODO items in the description).

**Comment by escopecz** [comment]
Hi, what feedback do you need? Where did you get stuck?

**Comment by Maxell92** [comment]
We used this PR for https://github.com/mautic/mautic/pull/5082. Thank you.

**Pull request closed without merging**
