### PR TITLE
[UI] Enhance page body

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR fixes the grid system by applying the indicated structure in the [Bootstrap v3.4.1 documentation](https://getbootstrap.com/docs/3.4/css/#grid).

> Bootstrap requires a containing element to wrap site contents and house our grid system.

> Rows must be placed within a .container (fixed-width) or .container-fluid (full-width) for proper alignment and padding.

In a practical scenario, it increases a bit of the body padding and avoid bugs with new components. 
I applied the full-width container to ensure a standard experience later.

It also reduces the top navbar size from 60px to 48 pixels.

This allows users to focus on the most important information without being distracted by too many elements piled up on the screen. In addition, more white space can make the interface more pleasing to the eyes.

| Before | After
| -------------------------------------- | ---
| image   | image

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. You can open any page to see the space (16px horizontal for the body content)
3. Look at the top navbar to see the height reduction

### CODE REVIEW

**Comment by andersonjeccel** [comment]
@RCheesley the ui-redesign branch needs rebase

**Comment by escopecz** [comment]
Could you instead base your changes on the `ui-redesign` if you target the `ui-redesign` branch?

**Review by shinde-rahul — APPROVED** [review]
LGTM!!!

Thanks @andersonjeccel!!!

**Comment by andersonjeccel** [comment]
Hey @shinde-rahul, thanks for the review!
Would you mind adding a `code-review-passed` and/or `user-testing-passed` labels, based on what you did?

This way we understand exactly what’s still needed 🚀

**Comment by shinde-rahul** [comment]
For all the following reviews, I'll add appropriate labels. 

Thanks, @andersonjeccel, for all your efforts to improve UX.

**Review by LordRembo — CHANGES_REQUESTED** [review]
There's a whole bunch of (variable) changes happening here (eg. in builder.css), which I'm guessing are partly to ensure you can restyle stuff in Dark mode, but seems like a lot of (structural) changes happening all at once.
Wouldn't it be better to separate some parts from this PR until other reworks are done? Eg. the PR about the token-based approach, the label colors (where I had some remarks on color as well), …
I would suggest focusing this 'enhancement' PR on small manageable aspects like spacing, borders, the font-size, … and not these very impactful structural changes.

**Comment by andersonjeccel** [comment]
### How to test dark mode?
1. Open dev tools on your browser (F12)
2. Open the Console tab
3. On the field, paste `document.documentElement.setAttribute('color-theme', 'dark');` and hit Enter
4. The components changed by the specific PR you're seeing will become dark

**Review by LordRembo — APPROVED** [review]
With the token-based stuff merged, I think this looks better code-wise.

**Comment by escopecz** [comment]
@andersonjeccel is there a reason for this PR being a draft or is it ready to merge?

**Comment by andersonjeccel** [comment]
@escopecz I was separating this PR in smaller ones because there was a lot of big differences and also checking if there was a better way to add lateral padding

I plan to reduce the scope of this PR

**Comment by andersonjeccel** [comment]
@escopecz Oh, all PRs are organized
So everything open instead of draft is ready

**Comment by escopecz** [comment]
I can see some conflicts now

**Comment by andersonjeccel** [comment]
@escopecz OK to proceed, following the Bootstrap standards instead of custom code

**Comment by escopecz** [comment]
@andersonjeccel here are conflicts too

**Comment by andersonjeccel** [comment]
@escopecz Conflicts solved here too

**Review by escopecz — APPROVED** [review]

**Pull request merged**
