### PR TITLE
Add border radius to button slot type

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Not always rounded buttons are  cool :)
Also fix bug with styling all A elements

#### Steps to test this PR:
1.  Apply PR  and call command php app/console mautic:aassets:generate
2. Add button to template  and try change border radius
3. Change background color and check if close button didn't change background color

### CODE REVIEW

**Comment by escopecz** [comment]
@kuzmany could you specify what the problem is? Maybe a screenshot before and after? Or what HTML to use? I don't know how to test it properly.

**Comment by kuzmany** [comment]
@escopecz just added new option to button slot type. See image

image

**Comment by kuzmany** [comment]
@escopecz fixed. Also fixed bug what styling close button (cross)

**Comment by luizeof** [comment]
@kuzmany can you add some padding option to Text widget? There are no padding from content and section slot

Thanks!

**Comment by virlatinus** [comment]
It works! Thanks!

**Pull request merged**
