### PR TITLE
Improve no campaings lead modal message.

### PR DESCRIPTION
**Pull request by mallezie**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ 5.x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

See issue https://github.com/mautic/mautic/issues/13472
This PR tries to improve that, by making a slight change to the header title of the modal, and to add a no-campaigns found message. 

When there is a campaign. 
image

When there is no campaign. 
image

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Check campaign modal for contact in campaign. 
3. Check campaign modal for contact not in campaign.

### CODE REVIEW

**Review by andersonjeccel — APPROVED** [review]
It's much better now, thanks!

**Comment by andersonjeccel** [comment]
@Esthertests Would you be up for testing it?

**Comment by Esthertests** [comment]
> @Esthertests Would you be up for testing it?

I'll get on it

**Review by kuzmany — APPROVED** [review]

**Comment by andersonjeccel** [comment]
@all-contributors please add @andersonjeccel for review

**Pull request merged**
