### PR TITLE
lower sleep times for faster tests

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

There are some `sleep` calls in the the tests that are really conservative.
Lowering it should not give issues, not local or on Github

#### Steps to test this PR:

1. run the tests and see if the phpunit tests succeed and are faster

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
Looks good. Thanks! 👍

**Comment by escopecz** [comment]
@mollux it looks like 4 seconds is too fast for some cases:
```
There was 1 failure:

1) Mautic\CampaignBundle\Tests\Command\TriggerCampaignCommandTest::testCampaignExecutionForAll
Failed asserting that actual size 50 matches expected size 0.

/home/runner/work/mautic/mautic/app/bundles/CampaignBundle/Tests/Command/TriggerCampaignCommandTest.php:104
```
Check the [recent failing CI check](https://github.com/mautic/mautic/actions/runs/3135855495/jobs/5092042986).

**Review by RCheesley — DISMISSED** [review]
Good to go once the feedback from @escopecz re. the failing test is addressed. Thanks for helping speed up our workflows!

**Comment by mollux** [comment]
@escopecz 

I made is 6 seconds, and all tests succeeded 3 times in a row, see 

https://github.com/mautic/mautic/actions/runs/3138563305/attempts/1
https://github.com/mautic/mautic/actions/runs/3138563305/attempts/2
https://github.com/mautic/mautic/actions/runs/3138563305/attempts/2

**Review by kuzmany — APPROVED** [review]
Before 

image

After 

image


Nice 👍

**Review by escopecz — APPROVED** [review]
Thank you Mattias! 👍

**Pull request merged**
