### PR TITLE
Fix "Send a webhook" action does not work in campaigns

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

Step 1: Run Mautic
Step 2: Create a campaign with "Send a webhook" action(with proper segment, contacts etc.). Campaign can contain just "Send a webhook" action, add some data fields with POST request
Step 3: Trigger campaign, see that "Send a webhook" is successfully completed in campaign Action summary.
Step 4: Check details of one of contacts that was in the campaign, you will see that webhook action failed;

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10580"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
@kuzmany I'm wondering whether we should use `RequestOptions::BODY` when `content-type` === `'application/json'` and `RequestOptions::FORM_PARAMS` when content-type header is not set. What do you think?

**Comment by ShareBtech** [comment]
I have tested this fix on 4.0.1 and it worked for me.  Thank you

**Comment by jstawski** [comment]
I can confirm this fix worked for us on 4.0.1

**Comment by npracht** [comment]
@kuzmany if you address John's feedback this is ready to merge :)

**Comment by kuzmany** [comment]
It cannot be ready to commit If @escopecz request changes. Need additional work, I take a look this week I hope

**Comment by RCheesley** [comment]
@kuzmany I've set it to pending feedback based on it needing further attention, just to be sure it doesn't get accidentally merged! Once the feedback is addressed it would be good to get it checked again with any new changes in place (assuming the code is changed) before merging.

**Comment by kuzmany** [comment]
@escopecz fixed

I tested all GET/POST/DELETE and POST with content-type === 'application/json' in headers. 
Works properly. Please re-test

**Review by jos0405 — APPROVED** [review]
Works.
Webhooks posted as expected:
image
image
Tested: PUT, POST, DELETE, GET, PATCH

**Review by mabumusa1 — APPROVED** [review]
I tested with pipedream, the requests went as expected

**Review by escopecz — APPROVED** [review]
The code looks good. Thanks @kuzmany!

**Pull request merged**
