### PR TITLE
adding to salesforce campaign members from Mautic campaign

### PR DESCRIPTION
**Pull request by mqueme**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR creates a new fields in the push to integration action in a campaign to be able to add campaign contact to an integration campaign.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1.Apply this PR, make sure you have salesforce plugin enabled and fields matched 
2. create a new campaign with push to integration action.
3. Select salesforce and see new dropdown fields (Campaign, Campaign contact status)
4. Select a campaign and a campaign contact status.
5. Trigger the campaign and contacts from Mautic should be pushed to Salesforce and put in the Salesforce campaign selected as campaign members
6. Test the following scenarios: 
a. If a campaign member doesn't exists Mautic should create the campaign member, if it exists is should update it with it's new status  if status is sent.
 b. A campaign member that was previously pushed by Mautic was deleted from a campaign in SF, the campaign member should be created again if pushed by a different campaign or same campaign in Mautic.
c. if there is a contact in Mautic and this contact's email address exists multiple times in SF (as a Lead, converted Lead or Contact) all matching SF leads or contacts should be created as campaign members in SF

### CODE REVIEW

**Comment by escopecz** [comment]
sf-push

**Comment by escopecz** [comment]
Now I cannot even select the status - the select is empty. Every time I select a different campaign, the new status select box is added. Please test it carefully.
screen shot 2017-04-18 at 16 06 22

**Comment by matishaladiwala** [comment]
Campaign member status does not show up as on option 
screen shot 2017-04-18 at 4 27 59 pm

**Comment by escopecz** [comment]
While testing 6.a I cloned the campaign, changed the status and run the campaign commands. When trigger command was run, this happened:
```
Triggering events for campaign 13
Triggering first level events
2 total events(s) to be processed in batches of 100
 0/2 [>---------------------------]   0%

  [Doctrine\ORM\EntityNotFoundException]
  Entity of type 'Mautic\PluginBundle\Entity\IntegrationEntity' for IDs id(70158000000UFQ9AAO) was not found
```

**Comment by escopecz** [comment]
It all works except a part of 6.c. SF lead with the same email address as the Mautic contact that Mautic campaign pushed to SF was added to the SF campaign, but SF contact with the same email address was not added to the SF campaign.

**Comment by matishaladiwala** [comment]
Works!

**Pull request merged**
