### PR TITLE
Focus: Remove click event anywhere to close modal

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
If the page contains a consent window, then it's impossible to use a popup or notification.  
There is on click event that closes it after clicking anywhere. We removed it and now it's possible to close the modal just with the cross button. 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Add consent window to the page to confirm cookie
3. Create notification and put it to the page
4. If you click on the consent cookie window, then the notification is closed too.
5. After PR you are able to close it just on cross button in notification

### CODE REVIEW

**Comment by kuzmany** [comment]
@RCheesley Not possible to add unit tests, it's a JS change

**Comment by RCheesley** [comment]
Do you happen to have a script snippet we could use to test this with?

**Review by LordRembo — APPROVED** [review]
Good that this is getting removed, that's far too broad a solution to close a modal.

**Comment by kuzmany** [comment]
@RCheesley I'm not sure what you mean. As a ddev user, you simply create a focus item. Then, take the JS script and place it in the focus.html file in the root directory of your Mautic. After that, try loading the page (ddev.site/focus.html) in incognito mode, and you'll be able to see if you can close the window just by clicking on the close icon.

**Comment by RCheesley** [comment]
> Then, take the JS script and place it in the focus.html file in the root directory of your Mautic.

I was asking for such a snippet/js file example that could be used to test with. I (and others, probably) didn't have anything to hand to use for this purpose, so it's not a case of 'simply' doing anything :)

**Comment by LordRembo** [comment]
I'm having some issues as well. 
- made a focus item with a notification
- made an html page called 'focus.html' in the root of my Mautic (just has a doctype, html, head, body tags and an H1 for a title).
- include `1.js` using the provided script tag code
- the JS file is giving a JS error.

```
Uncaught SyntaxError: Unexpected end of input
    at Object.engageVisitor (1.js:28:92)
    at Object.registerFocusEvent (1.js:8:39)
    at Object.initialize (1.js:3:63)
    at 1.js:53:16
    at 1.js:53:30
```

I can still submit the form but it's causing the html of the page to be repeated (so I see the H1 printed twice)

**Comment by kuzmany** [comment]
@LordRembo Could you please check now? I merged it with the last version 5.x, which included some changes. You can find the details here: https://github.com/mautic/mautic/pull/11945.

**Comment by LordRembo** [comment]
Alrighty, I'll have a look on Monday morning. I'm gonna be afk for the weekend.

**Review by patrykgruszka — APPROVED** [review]
The code change looks OK. It removes the possibility to close the focus item by clicking on the background.

**Comment by LordRembo** [comment]
won't be able to review it today, got sick over the weekend. Will take another look when I'm back at work. Or maybe there can be another second reviewer to check this instead.

**Comment by LordRembo** [comment]
I can confirm the modal now closes just with the close button, as intended by the PR. There's still JS errors but they are unrelated to this PR. I get them in another PR as well, so it's coming from 5.x

**Review by LordRembo — APPROVED** [review]

**Review by LordRembo — APPROVED** [review]
Looking good

**Pull request merged**
