### PR TITLE
Add unit test for extractCompanyDataFromImport

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features"
| Bug fix?                               | no
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Issue(s) addressed            | Related with #9764

#### Description:
I was working on fix for #9764 and noticed that is already fixed by #9461. This PR just adds unit test to ensure that everything works as expected.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2.

### CODE REVIEW

**Comment by RCheesley** [comment]
Awesome, thank you so much for taking the time to add the test! 

Just needs a code review then should be good to merge!

**Comment by RCheesley** [comment]
@all-contributors please add @patrykgruszka for test

**Comment by RCheesley** [comment]
Bump

**Review by kuzmany — DISMISSED** [review]
Let's merge it. Looks good 👍

**Comment by RCheesley** [comment]
@patrykgruszka sorry but we seem to have a conflict to address with this PR now.

**Comment by patrykgruszka** [comment]
@RCheesley I've resolved the conflicts, but now the codecov/project test is failing. It was fine before the merge and nothing in my code has changed. Is it failing because it's compared to 4.x branch instead of 4.0?

**Review by dennisameling — APPROVED** [review]

**Pull request merged**
