### PR TITLE
Fix unsubscribe form usage

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.3
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
In some cases unsubscribe form in emails make issues. This PR fixed it

#### Steps to test this PR:
2. Upload **Blank test** theme [blank-test.zip](https://github.com/mautic/mautic/files/6074396/blank-test.zip) - it's just email theme
3. Create form
4. Create email with **Blank test** theme and choose unsubscribe form
5. Send email
6. Try unsubscribe in email - you should see error
7. Enable in configuration Preferences center
8. Try unsubscribe in email again - you should see error
9. Create landing page as preferences center and assign this page to email created above
10. Try unsubscribe in email again - you should see error

After Patch all this situation should works properly

1. Load up [this PR](https://mautibox.com)
2. Repeat the steps above which should not cause an error
3. Check:

- disabled preferences center + unsubscribe form
- enabled preferences center + unsubscribe form
- enable preferences center + preferences center landing page + unsubscribe form

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/9752"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
@kuzmany could you give a bit more detail as to the issues that we should expect to see when testing before applying this PR?

For example I have followed steps 1-6 and there is no error. The email is sent, the form is used when clicking to unsubscribe, and when the form is submitted the contact is correctly flagged as DNC.

I am therefore not clear what I am missing! :)

**Comment by RCheesley** [comment]
Found it - was not in dev mode 😊 

```
[2021-03-13 13:21:20] mautic.DEBUG: CONTACT: 47 set as current lead.  
[2021-03-13 13:21:20] mautic.DEBUG: LEAD: 47 set as system lead.  
[2021-03-13 13:21:20] mautic.DEBUG: CAMPAIGN: Campaign triggered for event type email.open(email / 6)  
[2021-03-13 13:21:20] mautic.DEBUG: CONTACT: System lead is being used  
[2021-03-13 13:21:20] mautic.DEBUG: CAMPAIGN: Current contact ID# 47  
[2021-03-13 13:21:20] mautic.DEBUG: CAMPAIGN: Contact does not have any applicable email.open associations.  
[2021-03-13 13:21:24] mautic.DEBUG: CONTACT: 47 set as current lead.  
[2021-03-13 13:21:24] mautic.DEBUG: LEAD: 47 set as system lead.  
[2021-03-13 13:21:24] mautic.ERROR: Symfony\Component\Debug\Exception\ContextErrorException: PHP Notice - Undefined variable: name - in file /var/www/html/app/bundles/FormBundle/Views/form.html.php - at line 14  

```

**Review by RCheesley — DISMISSED** [review]
OK so here are my findings:

Before patch:

❌  Form associated with email - error thrown

❌  PC enabled in config but not associated with email - error thrown

✅   PC enabled in config and associated with email - no error, able to submit the unsub request and the contact is successfully marked as DNC 

After patch:

✅  Form associated with email - works - able to unsub and DNC correctly assigned

✅  PC enabled in config but not associated with email - works - able to unsub and DNC correctly assigned

✅  PC enabled in config and associated with email - works, able to submit the unsub request and the contact is successfully marked as DNC

**Comment by RCheesley** [comment]
@kuzmany just need to improve test coverage and this will be good to go :)

**Review by escopecz — CHANGES_REQUESTED** [review]
This would deserve a functional test. If I understand the code change correctly then it will not allow form themes anymore but only displays a message?

**Comment by RCheesley** [comment]
@kuzmany quite a few conflicts to address on this one :(

**Comment by kuzmany** [comment]
@escopecz If Form render on unsubscribe page has not theme, it was used default theme (include header, metadata...) https://github.com/mautic/mautic/blob/6a24ef990355e1b0eb475154227f960c9549083e/app/bundles/FormBundle/Views/form.html.php

But on unsubscribe page is inject form to specific place, this is reason why include just formContent code after preferences center code.

**Comment by RCheesley** [comment]
@kuzmany some codestyle and test coverage issues to be addressed here before it can be considered for the milestone. Are you able to take a look please?

**Comment by kuzmany** [comment]
@RCheesley I am on it.

**Comment by kuzmany** [comment]
@RCheesley unit tests added

**Comment by RCheesley** [comment]
@kuzmany maybe this PR needs to be rebased or something? The code coverage is reporting files which do not relate to this PR.

**Comment by RCheesley** [comment]
Coverage is failing so this has to be removed from the milestone - can consider for a later release if this is addressed :)

**Comment by kuzmany** [comment]
@RCheesley we've already added unit tests. Don't have idea why Codecov still reporting some percentage. 
We cannot do more. The best would be go ahead

**Comment by RCheesley** [comment]
If @escopecz is good with this PR (he has outstanding changes requested) then it should be good to go, I think.

**Comment by escopecz** [comment]
@kuzmany the changed code is in an `else` statement that depend on a theme configuration. The test does not set any theme to the email. Is it possible that the changed code is never executed and that it works with the `if` part? Could you copy-paste the test and set a theme that does not have the "form" feature?

**Comment by kuzmany** [comment]
@escopecz I suppose form without theme is enough for that. But I will check it and add case with theme too. 
I would like add also test for preferences center. How could I modify configuration? I need set `show_contact_preferences to 1`. I cannot find it

**Comment by escopecz** [comment]
I don't have much experience with the preference center, but I think you'll have to create a new landing page as preference center, add the right slots into the content and then attach the landing page as a preference center of the email entity.

**Comment by kuzmany** [comment]
@escopecz I am asking how I set show_contact_preferences to 1 in local.php for functional test?

**Comment by escopecz** [comment]
@kuzmany gotcha. Here is an example: https://github.com/mautic/mautic/blob/4.x/app/bundles/CoreBundle/Tests/Functional/EventListener/EditorFontsSubscriberTest.php#L22-L38

**Review by escopecz — APPROVED** [review]
Nice work with the tests! 👍

**Pull request merged**
