### PR TITLE
Add Guadeloupe and Saint Pierre and Miquelon

### PR DESCRIPTION
**Pull request by MaxWebmecanik**
Please answer the following questions. 

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Related user documentation PR URL | N
| Related developer documentation PR URL | N
| Issues addressed (#s or URLs) | #2079
| BC breaks? | N
| Deprecations? | N

#### Description:

This pull request simply adds Guadeloupe and Saint Pierre and Miquelon to the countries list

#### Steps to test this PR:
1. Go to any countries list in Mautic
2. Check that Guadeloupe and Saint Pierre and Miquelon are available

### CODE REVIEW

**Comment by chandon** [comment]
Guadeloupe is not a country, it's an overseas region of France.

Please see https://en.wikipedia.org/wiki/List_of_sovereign_states_and_dependencies_by_area

**Comment by npracht** [comment]
Technically as you can see in my issue, this "region" has its own worldwide country number according to the standard of ISO 3166.
https://en.wikipedia.org/wiki/ISO_3166-1

**Comment by chandon** [comment]
@npracht ok

**Comment by escopecz** [comment]
:+1:

**Comment by alanhartless** [comment]
👍

**Pull request merged**
