### PR TITLE
Running `composer fixcs` after CS Fixer update

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [y]
| New feature/enhancement? (use the a.x branch)      | [y]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

These are automatic CS Fixer changes after https://github.com/mautic/mautic/pull/13637

The changes results in way more readable code.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Nothing should break. PHPUNIT tests should catch issues. But feel free to test whatever you can think of. There are changes in almost all files.

### CODE REVIEW

**Review by RCheesley — DISMISSED** [review]
I reviewed on Gitpod and clicked into all sections, created/updated/deleted and all seems to be fine.

**Review by obamwonyi — APPROVED** [review]
I reviewed it on gitpod by running a fixer command below 
```
ddev exec php-cs-fixer fix --dry-run --diff 
```
and php-cs-fixer worked fine and there was 0 files that needed fixing.

**Comment by escopecz** [comment]
i just noticed there are many issues with PHPSTAN. I'll have to look into that.

**Review by RCheesley — APPROVED** [review]
Re-checked after the changes and all seems to be as expected - also ran the command mentioned by another reviewer:

gitpod /workspace/mautic (cs-fixes) $ ddev exec php-cs-fixer fix --dry-run --diff
PHP CS Fixer 3.53.0 15 Keys by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.2.18
Loaded config default from "/var/www/html/.php-cs-fixer.php".
 3636/3636 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%


Found 0 of 3636 files that can be fixed in 144.424 seconds, 58.000 MB memory used

**Pull request merged**
