### PR TITLE
Pipedrive fixes to company sync

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging for features or enhancements / 3.0 for bug fixes 
| Bug fix?                               | yes/no
| New feature?                           | yes/no
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes/no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR prevent a few issues with sync of contacts and their companies. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Just setup Pipedrive and try sync contact with/without company in both  ways

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@kuzmany any thoughts on when this might be in a condition to be tested? Just looking at what milestone we might want to aim for with this PR. Let me know if you have any thoughts!

**Comment by kuzmany** [comment]
@RCheesley we are using it in production. Just need find time to write description

**Review by jos0405 — APPROVED** [review]
Works as described.
Into both directions.

image

**Comment by npracht** [comment]
Hi there, as far as this plugin is outdated due to recent API BC from Pipedrive + the fact that Mautic Community policy is to not carry anymore third party plugins and move them slowly to marketplace, i'll close this issue.
You can still take advantage and contribute to a new Pipedrive plugin offered by a community contributor: https://github.com/Webmecanik/mautic-pipedrive-bundle

[See more on Mautic Community blog post](https://www.mautic.org/blog/integrator/exciting-news-new-integration-plugin-pipedrive-crm)

**Pull request closed without merging**
