### PR TITLE
Campaign bugfix contact condition with lost values after re-open 

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

Bugfix with resets operator and value after re-opened lead field condition or change field type (video http://somup.com/cbnY2i87s)

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Apply and use mautic:assets:generate
2. Test this bug http://somup.com/cbnY2i87s with conditions

### CODE REVIEW

**Comment by escopecz** [comment]
This works for me only partly. The operator stays, but the value disappears on condition re-edit.

**Comment by kuzmany** [comment]
@escopecz  now works better
Script remove value If field is change from select to text field  or if expression is change to empty/notEmpty operator.
Also PR was merged with last staging

**Comment by virlatinus** [comment]
It works as described, but I wasn't able to replicate John's issue with the attribution field.

**Comment by isleshocky77** [comment]
Had the issue described by this PR and it is fixed in staging thanks to this PR.

**Pull request merged**
