### PR TITLE
Disable search indexing with noindex on landing page

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Yes
| Automated tests included? |
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/267
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/3896
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Block search indexing with 'noindex' https://support.google.com/webmasters/answer/93710?hl=en 
Add button for non tech editors 

#### Steps to test this PR:
1.  Apply PR and test migrations `php app/console doctrine:migrations:migrate`
2. Create landing page and see in right column new option to Disable search indexing
3. Enable it and test it in Noindex checker https://seositecheckup.com/tools/noindex-checker

Example:

image

### CODE REVIEW

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by npracht** [comment]
In terms of UI, maybe it could be ?

### Indexing
with button

. | . |
-- | -- |
Index | No index

**Comment by kuzmany** [comment]
Index doesn't exist, just disable indexing in search terminology

**Comment by javjim-mautic** [comment]
Works correctly

**Comment by escopecz** [comment]
@kuzmany the feature is ready to go. Before we merge, can you please write some docs on this feature so users would know what it's good for?

**Comment by kuzmany** [comment]
@escopecz docs added

**Pull request merged**
