### PR TITLE
when syncing Leads get company name from SF if empty in Mautic

### PR DESCRIPTION
**Pull request by mqueme**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | enhancement
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
When pushing contacts from Mautic so Salesforce Lead object if "company" is mapped to update in SF and mautic's contact's company is empty it will overwrite whatever data is in SF with "Unknown". what we are doing with this PR is if it's populated in Salesforce then we write it back to mautic and update the record in mautic regardless of direction of company field in the plugin configuration.
[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Make sure you have "Push to integration" selected in the plugin config
2. Map company field (it is required) to point to Salesforce.
3. try updating a contact in mautic that has no company assigned to it.
4. Run the cron job to sync contacts <php app/console mautic:integration:fetchleads  --env dev --integration=Salesforce >
5. Company in leads in Salesforce should be overwritten with Unknown.

#### Steps to test this PR:
1. Try the above, company in SF should not be overwritten and Mautic should be updated with the company in SF.

### CODE REVIEW

**Comment by escopecz** [comment]
This happened when running the command:
```
$ php app/console mautic:integration:fetchleads --env dev --integration=Salesforce
Command to fetch contacts from integration
Fetch contacts command is starting
Number of contacts fetched: 26

Fetching companies
Fetch companies command is starting
Number of companies fetched: 0

Updating/creating leads from Mautic to Salesforce
[2017-05-05 11:37:44] mautic.ERROR: INTEGRATION ERROR: Salesforce - exception 'Mautic\PluginBundle\Exception\ApiErrorException' with message 'The Id field should not be specified in the sobject data.' in plugins/MauticCrmBundle/Integration/SalesforceIntegration.php:1253 Stack trace: #0 plugins/MauticCrmBundle/Integration/SalesforceIntegration.php(1141): MauticPlugin\MauticCrmBundle\Integration\SalesforceIntegration->processCompositeResponse(Array, Array) #1 app/bundles/PluginBundle/Command/FetchLeadsCommand.php(144): MauticPlugin\MauticCrmBundle\Integration\SalesforceIntegration->pushLeads(Array) #2 vendor/symfony/console/Command/Command.php(257): Mautic\PluginBundle\Command\FetchLeadsCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #3 vendor/symfony/console/Application.php(872): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #4 vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Mautic\PluginBundle\Command\FetchLeadsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #5 vendor/symfony/framework-bundle/Console/Application.php(92): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #6 vendor/symfony/console/Application.php(124): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #7 app/console(41): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), NULL) #8 {main} <a href="https://m.johnlinhart.com/s/contacts/view/31524">Contact ID# 31524</a>
Number of contacts pushed: 0 updated and 0 created
```

**Comment by escopecz** [comment]
Ignore previous comment, the PR was not applied correctly. I double checked it is and tested again. If I run the command, it finishes without error, but if I edit the contact in Mautic and run the command again, I get this:
```
$ php app/console mautic:integration:fetchleads --env dev --integration=Salesforce
Command to fetch contacts from integration
Fetch contacts command is starting
Number of contacts fetched: 100

Fetching companies
Fetch companies command is starting
Number of companies fetched: 0

Updating/creating leads from Mautic to Salesforce
[2017-05-05 12:32:41] mautic.ERROR: INTEGRATION ERROR: Salesforce - exception 'Exception' with message 'The Id field should not be specified in the sobject data.-31524-Lead-54' in plugins/MauticCrmBundle/Integration/SalesforceIntegration.php:1269 Stack trace: #0 plugins/MauticCrmBundle/Integration/SalesforceIntegration.php(1151): MauticPlugin\MauticCrmBundle\Integration\SalesforceIntegration->processCompositeResponse(Array, Array) #1 app/bundles/PluginBundle/Command/FetchLeadsCommand.php(144): MauticPlugin\MauticCrmBundle\Integration\SalesforceIntegration->pushLeads(Array) #2 vendor/symfony/console/Command/Command.php(257): Mautic\PluginBundle\Command\FetchLeadsCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #3 vendor/symfony/console/Application.php(872): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #4 vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Mautic\PluginBundle\Command\FetchLeadsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #5 vendor/symfony/framework-bundle/Console/Application.php(92): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #6 vendor/symfony/console/Application.php(124): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #7 app/console(41): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), NULL) #8 {main}
Number of contacts pushed: 0 updated and 0 created
```

**Comment by escopecz** [comment]
The SF company is no longer overwritten, but it's not saved from SF lead to the Mautic contact.

**Comment by mqueme** [comment]
@escopecz can you retest pls?

**Pull request merged**
