### PR TITLE
IMPORTANT BUGFIX: fix to get the query parameter like fingerprint if submitted by POST

### PR DESCRIPTION
**Pull request by zdreicom**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| Automated tests included? | no
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | no
| Deprecations? |

### CODE REVIEW

**Comment by escopecz** [comment]
Looks like duplicate of https://github.com/mautic/mautic/pull/6791. Could you test that PR please?

**Comment by Woeler** [comment]
@escopecz I will make sure to go over this in a bit

**Comment by escopecz** [comment]
If we'll go with this PR over #6791 then please switch the if like this:
```
            if ($request->getMethod() === 'GET') {
                $query = $request->query->all();
            } else {
                $query = $request->request->all();
            }
```
And also remove the `if (!isset($query)) {` surrounding it as it doesn't make sense. It will always be true.

I'll leave the 2.15.0 release leader (unknown at this moment) to pick the right version of the bug fix.

**Comment by Woeler** [comment]
That is a rather odd test failure?

**Comment by escopecz** [comment]
If you are talking about failed Travis CI then we are hunting it down internally. It's because of the winter time difference. It started to happen today. Not related to this or any other PR.

**Comment by dirtroof** [comment]
> If we'll go with this PR over #6791 then please switch the if like this:
> 
> ```
>             if ($request->getMethod() === 'GET') {
>                 $query = $request->query->all();
>             } else {
>                 $query = $request->request->all();
>             }
> ```
> And also remove the `if (!isset($query)) {` surrounding it as it doesn't make sense. It will always be true.
> 
> I'll leave the 2.15.0 release leader (unknown at this moment) to pick the right version of the bug fix.

Just tested this out, along with the proposed fix. Both work in my testing.

**Comment by Woeler** [comment]
Thanks @dirtroof

**Comment by tarunmangukiya** [comment]
Any ideas when this will be merged to release version?

**Comment by escopecz** [comment]
@tarunmangukiya you can see the answers already in this PR:
important bugfix fix to get the query parameter like fingerprint if submitted by post by zdreicom pull request 6802 mautic mautic



If you help us test what's in the 2.15.0 milestone it will help to get the release out ASAP.

**Pull request merged**
