### PR TITLE
Prevent duplicate rows in email stats reports  with campaign columns

### LINKED ISSUE #5598: email report : data duplicate in mail sent report
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  x
| Feature request? | 
| Enhancement? | 

## Description:
when you create a report to view email-sent data, and filter it by email_id, everything works fine if the email has been used in a single campaign. But if you create a new campaign, and use on it an email already used in another campaign, the report show data duplicated.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  v2.12.1
| PHP version |  PHP 7.0.27-0+deb9u1 

### Steps to reproduce:
1.  create a template mail.
2.  create a campaign with action send-email, and specify the email just created.
3.  launch the campaign.
4.  create a report that show email sent, and filter by email-id, specifying email-id of the email just created.
5. create a new campaign with action send-email. Use the email used in the previous campaign.
6. refresh the page of report created and you can see that the real number of email send is exactly twice.
 
### Log errors: 
_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for 4.0
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | ✅ 
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | https://github.com/mautic/mautic/issues/5598

#### Description:

This is follow up of https://github.com/mautic/mautic/pull/8919. This is more safe fix

Reports based on Emails Sent data source will contain duplicated rows when any campaign field is selected and that campaign has an action event (e.g Email read) based on emails sent.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create new template email
2. Create segment
3. Create campaign based on that segment with action **Send mail** and decision **Opens email**
image
4. Add contact to this campaign and trigger **all** campaign elements (open email)
5. Create report based on Emails Sent data source with campaign field as column
image
6. Generated report will contain double rows for this contact
image

### CODE REVIEW

**Review by npracht — APPROVED** [review]
Just tested and i cannot reproduce the issue after the patch 👍🏽

**Comment by dadarya0** [comment]
Working fine after the patch 👍

I have performed following Steps:-
1. Create a template email
2. Create 2 contacts
3. Create a segment for add above 2 contacts in segment
4. Create campaign with Action Send Email and Decision Opens email
5. Trigger campaign (Mail sent to both contacts)
6. Read received mail 
7. Create report based on Emails Sent data source with campaign field as column

Result in `features` branch :-

It is showing duplicate rows.

Screenshot 2021-06-01 at 1 19 24 PM

Result in `fix-duplicate-email-stats-campaign-columns` branch :-

It is not showing duplicate rows.

Screenshot 2021-06-01 at 1 22 32 PM

**Review by patrykgruszka — APPROVED** [review]
Issue is fixed after applying this patch. I must admit, your solution is better than mine :thumbsup:

**Comment by RCheesley** [comment]
@all-contributors please add @patrykgruszka for review and userTesting

**Pull request merged**
