### PR TITLE
[UX] Change "When a contact..." to improve accessibility

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Imagine that you are not seeing all the content on the screen and only one reader speaks a label for the entire page while you fill in the fields. When the screen reader reaches this label, the way it is written does not provide enough context and may sound random.

This update enhances accessibility by revising the ambiguous “When a contact…” label to the more descriptive “Action taken by user”. This change provides better context for screen reader users, ensuring that each label is self-explanatory and contributes to a coherent understanding of the page content. By improving label clarity, we facilitate a more inclusive and navigable experience for all users.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Point > Manage actions
3. Look at the new label

image

### CODE REVIEW

**Review by LordRembo — APPROVED** [review]
Agreed, labels like this should convey the intention and be more 'complete'

**Comment by andersonjeccel** [comment]
@RCheesley We could give a tip to the marketing team about the accessibility improvements for 5.0.4, what do you think?

It could be a great start for us to get more involved in accessible technologies

**Comment by RCheesley** [comment]
@andersonjeccel yes that sounds good, but we're probably going to be releasing 5.1 instead of a patch release due to the volume of PRs that are merged and awaiting release. If you're up for summarising the key changes that have been merged I am sure the marketing team would greatly value that input. Please ping them on Slack in the relevant channel (#t-marketing). Thanks!

**Comment by andersonjeccel** [comment]
@RCheesley How can we move this PR forward?

**Review by rohit-sharma-1802 — APPROVED** [review]
image
I have tested this PR. It is working fine and no conflict with other.

**Comment by andersonjeccel** [comment]
@rohit-sharma-1802 A huge thanks!

Would you be up for testing other UX-related PRs?

**Comment by rohit-sharma-1802** [comment]
@andersonjeccel sure, I can.

**Comment by andersonjeccel** [comment]
@escopecz Ready-to-commit here?

**Comment by RCheesley** [comment]
I have made the necessary docs update here: https://github.com/mautic/user-documentation/pull/266

**Pull request merged**
