### PR TITLE
Enable MX DNS validation when validating email addresses in a campaign.

### LINKED ISSUE #9131: Campaign condition 'Has valid email address' always returning positive.
## Bug Description
Campaign condition 'Has valid email address' always returning positive results, regardless if the email address is valid or not. Several tests were attempted with invalid WHOIS, non-existent MX DNS record, and nonexistent email account (on a valid domain with valid MX record)

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.3.21
| Browser | Safari 13.1.2

### Steps to reproduce
1. Create a test campaign, with a 'test segment'. (see example screenshot). 
2. Add  'Has valid email address' condition to campaign.
3. Wire up +5/-5 contact points, to be able to test. 
4. Add a contact with correctly formatted email address but with non-existent domain - e.g. test@test123testinvalid.com 
(verify domain has no WHOIS record by using an online WHOIS tool). 
5. Update contact points to 100, so points can be subtracted from.
6. Add contact to test segment / or to test campaign. 
7.  Observe condition 'Has valid email address' always returning positive results. See the contact's history log and the contact points wrongly increasing. 

Screenshot 2020-08-26 at 15 32 47
 
### Log errors
None observed in Mautic or apache log files.

### PR DESCRIPTION
**Pull request by evgu**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging (for v3.1.x
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              |  no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #9131

#### Description:
#9131

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. In a campaign, test an email address (with invalid domain or non-existent MX record). Previously used to pass, now it should fail.

### CODE REVIEW

**Review by kuzmany — APPROVED** [review]
Works 👍

**Comment by evgu** [comment]
@kuzmany, Can you also apply this PR to 3.0 and 3.x branches, as this issue seems to be present there as well? Alternatively I can produce PRs for these braches, too - let me know.

**Comment by kuzmany** [comment]
@evgu PR is under staging branch,then after second approve It will be added to next release 3.1.1

**Comment by RCheesley** [comment]
@evgu thanks for submitting the PR! Could you please sign the contributors agreement?

Will test the PR shortly :)

**Review by RCheesley — APPROVED** [review]
For info there is a list of invalid emails to use for testing here: https://gist.github.com/cjaoude/fd9910626629b53c4d25

I created a contact with the address email@example.web which should be invalid.  My campaign simply added a tag for valid or invalid emails so easy to see the results!

Without the PR I see the bug - it is not flagged as invalid.

screenshot-local mautic3-2020 08 28-12_31_48

With the PR applied, correct behaviour is happening 🎉 
screenshot-local mautic3-2020 08 28-12_31_48 (1)

**Comment by evgu** [comment]
@RCheesley not sure if this PR is still blocked from merging into 3.1.1. 
Im happy for an authorised developer to copy my code changes and push a new PR so we can get this fix in 3.1.1 milestone.

**Comment by RCheesley** [comment]
@evgu we are not able to merge the PR until the Contributors Agreement is signed so that is what is blocking this one currently.

**Comment by evgu** [comment]
@RCheesley and I will not be signing it anytime soon, thus suggested someone who has it signed copies my PR so we can move on.

**Comment by RCheesley** [comment]
OK sorry to hear that, we will close down the PR in that case.

**Pull request closed without merging**
