### PR TITLE
Add the Psysh REPL for dev usage

### PR DESCRIPTION
**Pull request by dongilbert**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? | N
| Related user documentation PR URL | N
| Related developer documentation PR URL |  N/A
| Issues addressed (#s or URLs) | N/A
| BC breaks? | N/A
| Deprecations? | N/A

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR adds the Psysh Bundle for Symfony2 to our `require-dev` block in `composer.json`.

It allows devs access to the `$container`, `$kernel`, and `$self` (which is the `Psy\Shell` instance itself) from the command line. This lets devs test using their services from the container, as well as improve general debugging capabilities of the app.

You can start the repl after applying the PR and running `composer install`. 

Please test on PHP 5.6 & 7.1

Some usages examples (after starting the repl):

```sh
# Update a mautic user's password
$model = $container->get('mautic.lead.model.lead');
$user = $model->getEntity(1); // pick an appropriate user ID
$encoder = $container->get('security.encoder_factory');
$user->setPassword($encoder->encodePassword('NEW_PASSWORD', $user->getSalt()));
$em = $container->get('doctrine')->getEntityManager();
$em->persist($user);
$em->flush();

# Test a method from your service
$myService = $container->get('mautic.my.service.key');
$myService->myMethodToTest();
```

### Bonus PHP Docs
Follow instructions here: https://github.com/bobthecow/psysh/wiki/PHP-manual to get docs for built in PHP functions and classes via `doc function_name`

```sh
dgilbert ~/Sites/mautic (feature.dev-repl) $ app/console psysh -e dev
Psy Shell v0.9.8 (PHP 7.1.20 — cli) by Justin Hileman
>>> doc array_map
function array_map($callback, $arrays)

Description:
  Applies the callback to the elements of the given arrays
  
  array_map() returns an array containing all the elements of $array1 after applying the $callback
  function to each one. The number of parameters that the $callback function accepts should match
  the number of arrays passed to the array_map()

Param:
  callable  $callback  Callback function to run for each element in each array.
  array     $array1    An array to run through the $callback function.
  array     $...       Variable list of array arguments to run through the $callback function.

Return:
  array  Returns an array containing all the elements of $array1 after applying the $callback
         function to each one.

See Also:
   * array_filter()
   * array_reduce()
   * array_walk()
   * information about the callback type

>>> 
```

### CODE REVIEW

**Comment by digitall-it** [comment]
I would like to thank you @dongilbert for the work you are doing.

**Comment by dongilbert** [comment]
Updated to fix merge conflict with composer.lock again. @alanhartless

**Comment by dongilbert** [comment]
Rebased on current staging to address `composer.lock` conflict

**Review by alanhartless — DISMISSED** [review]
This just saved my bacon and worked beautifully.

**Comment by dongilbert** [comment]
Rebased to staging

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@dongilbert looks like this needs updating if it is still relevant - can you take a look?

**Comment by dongilbert** [comment]
@RCheesley This has been updated to be compatible with Mautic 3. It was approved long ago for Mautic 2. @alanhartless If you could give your stamp again we could hopefully get this merged soon.

**Comment by RCheesley** [comment]
@dongilbert wonderful, thanks for getting that sorted!

**Review by dennisameling — APPROVED** [review]
Works - as this is a small change that doesn't affect Mautic's functionality directly, I'll go ahead and merge this one. Thanks @dongilbert for the PR and your patience!

**Comment by dennisameling** [comment]
cc @mautic/education-team FYI I just created two issues to add this new functionality to the docs: https://github.com/mautic/mautic-community-handbook/issues/19 https://github.com/mautic/developer-documentation/issues/163

**Pull request merged**
