### PR TITLE
Replaced %contacts% to %leads%

### PR DESCRIPTION
**Pull request by escopecz**
Please answer the following questions:

| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed issues  |  N/A

## Description
~~A few %leads% occurrences were missed while renaming to %contacts% and so some contact counts does not display.~~

All occurrences of %contacts% and replaced them back to %leads% to keep BC for translations.

## Steps to reproduce the bug (if applicable)
Try to run `app/console mautic:campaigns:update`. The output does not display the contact count like this:

> %contacts% total contact(s) to be added in batches of 300

## Steps to test this PR

Apply this PR, clear the cache and run the command again. It should display the contact count like before renaming:

> 0 total contact(s) to be added in batches of 300

### CODE REVIEW

**Comment by alanhartless** [comment]
This will break BC for translations. Maybe pass in both `%leads%` and `%contacts%` with a `//@todo` to remove in 2.0?

**Comment by dbhurley** [comment]
Agreed, pass both for now, mark for deprecation in 2.0 +1

**Comment by escopecz** [comment]
I didn't break BC, I just fixed what was missed in the leads to contacts switch and didn't work. But I agree that it is better not to make our translators furious. I found and replaced all occurrences of `%contacts%` and replaced them back to `%leads%`

**Comment by alanhartless** [comment]
By breaking BC, I mean that if a translation is not immediately updated, they would have had something like `%leads% some translated text` because `%leads%` would no longer have a match with `array('%contacts%' => $processed)`.

But if you pass an array like `array('%leads%' => $processed, '%contacts%' => $processed)` then the updated English text, translations that are up to date, and translations that still have ``%leads% some translated text` would all work.

**Comment by alanhartless** [comment]
I see what you meant :-) You personally didn't break BC. Since this restores original strings, I'm merging.

**Pull request merged**
