### PR TITLE
Segment filter refactoring

### PR DESCRIPTION
**Pull request by escopecz**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Code enhancement of existing feature
| Automated tests included? | Y
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | /
| BC breaks? | N
| Deprecations? | Y

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

The list of segment operators and functionality around that was hard-coded in the LeadBundle and not open for extension by plugins. This PR refactors that and adds new events that the plugins can hook into.

Most of the code changes are refactoring hard-coded switches into events. But there is one change in UI that may be noticeable. Every time you select an operator in a segment filter then the filter field(s) is being regenerated on server. It used to be hard-coded in JS what field type should show up. It was impossible to plugins to modify it. Now any plugin can.

#### Steps to test this PR:
1. Ensure you have multiple segments with multiple filters already before you check out this PR so you could test that existing segments still work.
2. Once you check out this branch, run the `bin/console mautic:segments:update` command and check that the command worked as before and no contacts were added or removed. The contact count for each existing segment should be the same.
3. Edit an existing segment and check that the filter values are as it used to be. You should check selects, multiselects, tags, segment membership, owner, text, boolean and country filters at least.
4. Try to create multiple segments with different filters at least type of mentioned in the step 3. You should have no problem create those filters, save them and the segments should contain the right contacts once you run the update command.
5. Test also dynamic email content filters. Should work as before.
6. Test also dynamic web content filters. Should work as before.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/8649"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
@escopecz some conflicts to resolve here :)

**Comment by RCheesley** [comment]
Bumping to 3.2 due to unresolved conflicts.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by escopecz** [comment]
Rebased to resolve conflicts

**Comment by RCheesley** [comment]
Looks like we have conflicts to be resolved here :)

**Comment by alanhartless** [comment]
I'm working on rebasing this. Seems that it is doing changes similar to https://github.com/mautic/mautic/pull/9260 so now conflicting and duplicating.

**Comment by alanhartless** [comment]
I've rebased and reconciled with #9260. But I've found that this PR has parts from https://github.com/mautic/mautic/pull/7786 and https://github.com/mautic/mautic/pull/7194. But other parts of the two PRs are no longer valid because of this one. So I'm going to merge the parts from those two PRs that's needed here (i.e. translation strings), remove the SMS filters from this PR because execution is dependent on the other two PRs, and then create one new PR for SMS click and unsubscribes that can be merged after this as new filters. 

Also, https://github.com/mautic/mautic/pull/8739 would need to be tested exactly the same as this PR as it's all related to the underlying generation/display of segment filters so I'll merge it into this one as well, fix it up, and close the other.

**Review by RCheesley — CHANGES_REQUESTED** [review]
Testing this and so far so good except for with contact owner being empty - before applying the PR I can create that segment fine but after applying the PR it throws an error saying input is required, and the field is not being greyed out:

Before:
screenshot-mautic4 ddev site-2021 04 24-21_11_46

After:
screenshot-mautic4 ddev site-2021 04 24-21_15_08

This works fine with Tags + empty so seems maybe unique to the owner field.

I also tested dynamic content (web) which seems to be OK (I could create them all fine).

Dynamic content for emails. when I try to select I get the following notice (in this case using a boolean field or city - guess it is with all but not related to this PR) which prevented me from testing this aspect.

`[2021-04-24 20:28:03] mautic.ERROR: ErrorException: PHP Notice - Trying to access array offset on value of type null - in file /var/www/html/app/bundles/EmailBundle/Views/FormTheme/Email/_emailform_dynamicContent_entry_filters_entry_filters_entry_widget.html.php - at line 14  
`

**Comment by RCheesley** [comment]
@escopecz a conflict to address on this one as well!

**Comment by escopecz** [comment]
@RCheesley thanks for the test. It is fixed in https://github.com/mautic/mautic/pull/8649/commits/7b34138b15b5371169cf59be607fc9d4c3b26469. This PR is ready to test again.

**Comment by kuzmany** [comment]
Web dynamic content return error

image

**Comment by escopecz** [comment]
I see. @RCheesley reported similar notice but it was fixed in https://github.com/mautic/mautic/commit/c6b7ae73c6b0c701e21aba5fa068b840a45e0017 in the mean time.

I fixed this new PHP notice in commit e74e372c5c157f7ff4d0fb32eb0318169b716bb8 but it does now show in this PR for some reason. 

```
~/dev/mautic-community (segment-filter-refactoring) $ git push
Everything up-to-date
~/dev/mautic-community (segment-filter-refactoring) $ git log
commit e74e372c5c157f7ff4d0fb32eb0318169b716bb8 (HEAD -> segment-filter-refactoring, escopecz/segment-filter-refactoring)
Author: John Linhart <admin@escope.cz>
Date:   Tue Oct 5 15:59:23 2021 +0200

    Fixing "Trying to access array offset on value of type null"

commit 7b34138b15b5371169cf59be607fc9d4c3b26469
Author: John Linhart <admin@escope.cz>
Date:   Tue Oct 5 13:10:24 2021 +0200

    Fixing owner (lookup) segment filter with not/empty operators
```
what is going on?

Update: The commit is visible here: https://github.com/escopecz/mautic/commit/e74e372c5c157f7ff4d0fb32eb0318169b716bb8 but still missing in this PR 🤷

**Comment by escopecz** [comment]
@kuzmany can you retest? The commit https://github.com/escopecz/mautic/commit/e74e372c5c157f7ff4d0fb32eb0318169b716bb8 is present in my branch but not visible in this PR. But theoretically, it should work.

**Comment by escopecz** [comment]
When I compare the branches with https://github.com/mautic/mautic/compare/4.x...escopecz:segment-filter-refactoring the commit https://github.com/escopecz/mautic/commit/e74e372c5c157f7ff4d0fb32eb0318169b716bb8 is there. So if it will make problems to test this PR we can close it and create it again. We'd lose the comment history though.

**Comment by kuzmany** [comment]
@escopecz now works
I noticed campaign share ajax request return error

` 500 Internal Server Error - An exception occurred while executing 'SELECT c.id, c.name, ROUND(IFNULL(COUNT(DISTINCT t.lead_id)/COUNT(DISTINCT cl.lead_id)*100, 0),1) segmentCampaignShare FROM campaigns c LEFT JOIN campaign_leads cl ON cl.campaign_id = c.id AND cl.manually_removed = 0 LEFT JOIN (SELECT lll.lead_id AS ll, lll.lead_id FROM lead_lists_leads lll WHERE lll.leadlist_id = AND lll.manually_removed = 0) t ON t.lead_id = cl.lead_id GROUP BY c.id': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND lll.manually_removed = 0) t ON t.lead_id = cl.lead_id GROUP BY c.id' at line 1 `

look like `lll.leadlist_id = ` pass empty ID

**Comment by RCheesley** [comment]
@escopecz it would be awesome to try to get this merged in 4.1 as it is blocking a whole bunch of other PRs. Could you look at the [feedback from @kuzmany](https://github.com/mautic/mautic/pull/8649#issuecomment-936800047) above?

**Comment by escopecz** [comment]
@kuzmany can you please share steps to replicate that error?

**Review by kuzmany — DISMISSED** [review]
I did test again and looks good now. 
Let's merge it soon as possible, because it's big change to segments and we need move forward.

👍

**Comment by kuzmany** [comment]
@escopecz need resolve conflicts

@RCheesley @mabumusa1 after resolve conflicts can you make fast tests and let's merge it  to 4.2

**Comment by mabumusa1** [comment]
> @escopecz need resolve conflicts
> 
> @RCheesley @mabumusa1 after resolve conflicts can you make fast tests and let's merge it to 4.2

@kuzmany I will review directly, thanks for pointing it out

**Comment by escopecz** [comment]
Ok. Let's retest this beast. I spent most of today just to refresh this PR for god knows how many times. I would really appreciate not to do it again. This PR is also blocking lots of other segment related PRs from Acquia.

**Review by kuzmany — APPROVED** [review]
Everything what I test looks good 👍 
We need go to 4.2 avoid never ending story

**Comment by kuzmany** [comment]
@mabumusa1 can you test it?

**Review by mabumusa1 — APPROVED** [review]
I went through the test steps described in this PR, everything seems to be working as expected. 

Contact counts were correct
Filters and commands were working as expected
Dynamic content worked without issues

I think this PR is good to go

**Comment by kuzmany** [comment]
@RCheesley looks like your requested for review blocking the PR

**Review by RCheesley — APPROVED** [review]
The previous bug I had found has now been resolved so from my perspective this is good to go 🚀

**Pull request merged**
