### PR TITLE
TPROD-385 - "lightsaml/sp-bundle" upgraded to dev-symfony5

### PR DESCRIPTION
**Pull request by fedys**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

We had to fork 2 repos that are not accepting PRs with Symofny 5 upgrades. Here are the branches with the changes needed for Symfony 5 commits:
https://github.com/mautic/SymfonyBridgeBundle/commits/symfony5
https://github.com/mautic/SpBundle/commits/symfony5

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Test SSO

### CODE REVIEW

**Comment by fedys** [comment]
@volha-pivavarchyk please can you test that the SSO is working fine. @escopecz told me you have experience with testing SSO.

**Review by escopecz — APPROVED** [review]
The changes are looking good. Thanks Fedy! 👍

**Review by mabumusa1 — APPROVED** [review]
Changes looks good, this PR is good to go

**Comment by mabumusa1** [comment]
I used https://samltest.id/ to test the login, it worked as expected. I will merge this PR as I work during the weekend on Symfony 5 upgrade

**Comment by volha-pivavarchyk** [comment]
@fedys Sure I'll test. I can do it tommorow.

**Comment by pasxel** [comment]
Hi All

I have prepared additional changes for this issue. Could you please check from your side?
https://github.com/mautic/SpBundle/pull/1

**Pull request merged**
