### PR TITLE
Asset download segment filter

### PR DESCRIPTION
**Pull request by maxlawton**
| Q  | A
| --- | ---
| Bug fix? | N
| New feature? |  Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | N
| Deprecations? | N

#### Description:

Adds asset multi selector support. 
Adds segment filter for leads having downloaded an asset.

#### Steps to test this PR:

1. Create an asset.
2. Download the asset as a lead.
3. Create segment selecting the created asset.
3. Update the segment and check if it contains the lead.

### CODE REVIEW

**Comment by luizeof** [comment]
@npracht this will be added to 2.15.0 or 2.15.1?

**Comment by npracht** [comment]
Hi @luizeof ! Until now 2.15.0 is closed, so we can candidate it for 2.15.1 !

**Comment by npracht** [comment]
Hi @maxlawton could you please solve conflicts ?
Thanks !

**Comment by johbuch** [comment]
just tested on mautibox.
It does not seems to work
I have downloaded the asset
image
created a segment this filter
image
after the crons runned, no contact in the segment
image

**Comment by maxlawton** [comment]
@johbuch Your screenshots indicate that you're using this filter as expected, so I see no obvious reason for its failure.

This filter has been used with success in production, but merged into an outdated revision of the **staging** branch. It is possible that something changed between the original development and the latest commit to resolve merge conflicts between **staging** and this branch.

Unless anyone else can verify that this branch does in fact work as expected, I'll try to figure out what has gone wrong. Any clues to a fix would be appreciated.

**Comment by kuzmany** [comment]
Cannot work because 
LeadListRepository > getListFilterExpr is method for filter contacts to segments before Mautic 2.14

Mautic 2.14 and above (after segments refactoring https://github.com/mautic/mautic/pull/5755) use SegmentFilterQuery and decorators
https://github.com/mautic/mautic/tree/staging/app/bundles/LeadBundle/Segment

This PR require add new FilterQuery for assets  like segments do https://github.com/mautic/mautic/blob/staging/app/bundles/LeadBundle/Segment/Query/Filter/SegmentReferenceFilterQueryBuilder.php

**Comment by maxlawton** [comment]
@kuzmany Thanks! I'll refactor accordingly.

**Comment by maxlawton** [comment]
Hmm. I may have screwed up my merge. The diff looked good locally, but I'm seeing a bunch of unrelated changes here. 

@alanhartless Would a rebase and force-push to my branch be unwelcome?

**Comment by maxlawton** [comment]
I've rebased on **staging** and force-pushed, so this PR should be good to go now.

**Comment by npracht** [comment]
@johbuch can you try again please ?

**Comment by npracht** [comment]
@kuzmany can you review code again please ?

**Comment by maxlawton** [comment]
@kuzmany Where/when is `app.js` regenerated? I had to manually build it locally via the console command in order to get those changes to propagate.

**Comment by kuzmany** [comment]
assets are generate on each version https://github.com/mautic/mautic/commit/f5504d81e6cab6bf99c29573eca12764b255b9dd
Just commit it from github https://github.com/mautic/mautic/blob/staging/media/js/app.js

**Comment by wucherpfennig** [comment]
We have been waiting for this functionality for so long... Thank you!

BUT while testing the new filter we discovered that most of the assets do not appear in the dropdown and they are also not accessible via autocompletion.
(We have currently 150+ assets in use)

Does anybody have an idea why?

**Comment by npracht** [comment]
@Woeler or @maxlawton could it be because a pagination or something like that ?
@wucherpfennig can you create a new issue explaining how to reproduce and the reference to that PR ?

Thanks !

**Pull request merged**
