### PR TITLE
Fix public preview email for expired emails

### LINKED ISSUE #10955: Public preview link should also work for unpublished mails
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I think if I'm able to enable and disable the public preview link, it should also work when the mail is not yet published? This is useful for not yet approved mails to be shared with the customer for approval.

Logic should be as follows:
* mail unpublished, preview link disabled by default - can be enabled
* mail published, preview link enabled by default - can be disabled,

Thanks!

### How can we reproduce this issue?

* create a mail
* leave it unpublished, preview link switch is on public by default
* try to open the preview link without being logged into the system

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #10955

#### Description:
Public preview email now working If email is in expired state. This make troubles If you use segment emails (usually expired)
This PR fixed it

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create email with Unpublish at (date/time)  lower like now
3.  Go to detail of email
4. Make public preview url and try open it in incognito window
5. Before it return Unauthorized access to requested
6. After return preview of email

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10971"></a>

### CODE REVIEW

**Comment by volha-pivavarchyk** [comment]
in incognito window
image

in usual mode
image

Is this expected behavior?

**Review by escopecz — APPROVED** [review]
The code changes make sense. Thanks for the test!

**Comment by escopecz** [comment]
@volha-pivavarchyk yes, it is by design. The preview should not be accessible without authorization.

**Review by RCheesley — APPROVED** [review]
With the PR applied I was able to open an email which has an unpublish date in the past (eg expired) when the preview was switched on for the email.

**Pull request merged**
