### PR TITLE
[UI] Better publish badge

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

Dependency:
- #13689 

This PR introduces an enhancement for the active/available labels.
Now, they are context-specific to show the right label for each resource.

| Before                                 | After
| -------------------------------------- | ---
|  image                                      | image image image image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a new campaign and save it. Then, close the campaign and verify that the "Active/Inactive" label is visible.

### CODE REVIEW

**Review by shinde-rahul — CHANGES_REQUESTED** [review]
It works as expected.
- Badges displayed **Unavailable** and **Available for use** for
   - Asset
   - Form
   - Landing Page
   - Dynamic content
   - Email
- Badges **Inactive** and **Active** displayed  for, 
   - Campaign
   - Segment
   - Marketing message

Its failing for 

- Focus Item
Screenshot 2024-07-26 at 12 30 25 PM
Screenshot 2024-07-26 at 12 31 32 PM

**Comment by andersonjeccel** [comment]
@shinde-rahul Thanks for testing! this issue is a bug, we just need to bring the fix from 5.1 to 5.x

@escopecz Could you merge the fix focus item published #13944 into 5.x?

**Comment by escopecz** [comment]
@andersonjeccel I can't see why not. We do that during the release but it won't hurt to do any time. See https://github.com/mautic/mautic/pull/14012

**Comment by andersonjeccel** [comment]
thanks! 🙏

**Comment by escopecz** [comment]
I merged 5.1 into 5.x so this should be unblocked, right?

**Comment by andersonjeccel** [comment]
@escopecz Yes!

**Review by Esthertests — COMMENTED** [review]
The badges are displayed correctly but my concern is the toggle behaviour, maybe could be fixed in another PR>

here is a recording https://jam.dev/c/a560e1df-6bfd-4422-a7cd-37aaba3b791f

**Comment by andersonjeccel** [comment]
@Esthertests Thanks for testing!

That icon spinning seems to be a bug (unrelated to the badge), I'll check asap

**Review by shinde-rahul — APPROVED** [review]
Works as expected.

**Review by RCheesley — APPROVED** [review]
Love these improvements, just waiting for the tests to pass! 🚀

**Pull request merged**
