### PR TITLE
Fix csv header with 'file' column issue while contact import

### PR DESCRIPTION
**Pull request by tejasync**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | ✅ 
| New feature/enhancement? (use the a.x branch)      | ❌ 
| Deprecations?                          | ❌ 
| BC breaks? (use the c.x branch)        | ❌ 
| Automated tests included?              | ✅ 
| Related user documentation PR URL      | ❌ 
| Related developer documentation PR URL | ❌ 
| Issue(s) addressed                     | ❌ 

#### Description:
Having "file" as the name of a column in a CSV breaks the contact import. This PR address the issue by prefixing the CSV headers to avoid form rendering errors in contact import.
Error message:

> Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\FormHelper::widget() must be an instance of Symfony\Component\Form\FormView, null given, called in themes/system/MauticLeadBundle/Import/upload_form.html.php on line 44" at vendor/symfony/framework-bundle/Templating/Helper/FormHelper.php line 136

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create CSV with 'file' header and some contacts
3. Upload the CSV to import contacts
4. Mapping screen should be visible and contact import should be successful

### CODE REVIEW

**Review by kuzmany — DISMISSED** [review]
Works. Nice catch.
Unit tests included
Code looks good 

👍

**Comment by RCheesley** [comment]
This needs to be rebased as it's on an outdated branch. Bumping to the 4.2 release when we should hopefully be good to go once the rebase is done!

**Comment by biozshock** [comment]
PR fixes the issue. Tested on v4.1.2.

**Comment by kuzmany** [comment]
@biozshock yes, but this PR still bring one improvement to return ORMException If entity is closed. Code review and small test If import works like before and we can go to Ready to commit

https://github.com/mautic/mautic/pull/10744/files#diff-7dd9cc1b2476d838fda48a9a22d1d991d760f5975c4b77e5eb09dc28106dd879R375

**Comment by RCheesley** [comment]
This PR cannot be merged until it is rebased. @ts-navghane are you able to rebase it to 4.x please? Once that's done and assuming tests pass, it's good to merge. Thanks, and sorry for the faff!

**Comment by tejasync** [comment]
Closing in favour of https://github.com/mautic/mautic/pull/10823

**Pull request closed without merging**
