### PR TITLE
TPROD-350 - CoreBundle - FormTheme

### PR DESCRIPTION
**Pull request by JoshuaEstes**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

* This will break any PHP template that uses the `FormTheme/Custom/*.php` files
* File `entity_properties.html.php` appears to not be used in the code base so it was not converted to php
* This should not impact any templates that have already been migrated to twig

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by mabumusa1** [comment]
@JoshuaEstes is there a specific way to test this PR, I can share it with the community to get it tested.

**Comment by JoshuaEstes** [comment]
@mabumusa1 Not really, that's the issue with these CoreBundle PRs. They are basically deleting files and cleaning things up since the files were converted in other PRs that required them

**Review by escopecz — APPROVED** [review]
I see no issue with these code changes 👍

**Review by mabumusa1 — APPROVED** [review]
I did a code review, this PR is hard to test from a user perspective

**Pull request merged**
