### PR TITLE
Implement automatic conversion of embed image as base64 

### PR DESCRIPTION
**Pull request by Salamek**
## Description

Implements automatic conversion of email image to embed base64  for #1511 
## Warning:

Would be good to add configuration option for this somewhere in mautic before merging this PR so ppl can decide if they want to use this feature or not

### CODE REVIEW

**Comment by escopecz** [comment]
Looks good! Could you please fix the indentation so it would respect the Mautic's [coding standards](https://github.com/mautic/mautic/blob/staging/.github/CONTRIBUTING.md#coding-standards)?

**Comment by Salamek** [comment]
@escopecz better now ? :)

**Comment by escopecz** [comment]
Yes, that's it. Tanks!

**Comment by escopecz** [comment]
@Salamek you are right about the configuration option. Could you add it before the test rounds and merge?

**Comment by Salamek** [comment]
@escopecz Where to put it ? to config/edit#emailconfig like ? : 
mauticmod

**Comment by escopecz** [comment]
I think it can be there. Thanks!

**Comment by Salamek** [comment]
@escopecz ok added into config

**Comment by Salamek** [comment]
Default state is Disabled, so users must enable this feature if they want to use it

**Comment by escopecz** [comment]
Because no test instructions were provided, here's how I tested this PR:

### Test instructions
1. Clear cache
2. Create an email with an image in it.
3. Firstly, check that the image works without any configuration change for backward compatibility. Send the email. The image should show up in the received email. If not, make sure you did not use a localhost URL for it. In that case the image won't obviously load. I used email with this content:
```
<html>
<head>
	<title></title>
</head>
<body>
<p><img alt="" src="http://www.mediacollege.com/video/test-patterns/television/bbc-g.jpg" style="width: 543px; height: 373px;" /></p>

<p><a href="http://johnlinhart.com">link</a></p>

<p><strong contenteditable="false" data-token="{unsubscribe_text}">**Unsubscribe Text**</strong></p>
</body>
</html>
```
4. Configure Mautic to send emails with base64 encoded images and send the email again.

The second time, the image wasn't just a link, but was part of the email like this:
```
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<html>
<head>
=09<title></title>
</head>
<body>
<p><img alt=3D"" =
src=3D"cid:a397cc76b1c16521b483ea95574b761e@mautic.io" style=3D"width: 543p=
x; height: 373px;" /></p>

<p><a href=3D"http://mautic.io/mautic-github=
/index_dev.php/r/667047cb49cc501089770cfcc?ct=3DYTo0OntzOjY6InNvdXJjZSI7YTo=
yOntpOjA7czo1OiJlbWFpbCI7aToxO2k6MTI1O31zOjU6ImVtYWlsIjtpOjEyNTtzOjQ6InN0YX=
QiO3M6MTM6IjU3MThiZGRiMWYwODYiO3M6NDoibGVhZCI7aTo5NTt9">link</a></p>

<=
p><a href=3D'http://mautic.io/mautic-github/index_dev.php/email/unsubscribe=
/5718bddb1f086'>Unsubscribe</a> to no longer receive emails from us. %test%=
</p>
<img style=3D"display: none;" height=3D"1" width=3D"1" src=3D"http:/=
/mautic.io/mautic-github/index_dev.php/email/5718bddb1f086.gif" alt=3D"Maut=
ic is open source marketing automation" /></body>
</html>

--_=_swift_v4_1461239259_38d312f9d300f9dc2ea7a439895b8982_=_
Content-Type: image/jpeg; name=bbc-g.jpg
Content-Transfer-Encoding: base64
Content-Disposition: inline; filename=bbc-g.jpg
Content-ID: <a397cc76b1c16521b483ea95574b761e@mautic.io>

/9j/4AAQSkZJRgABAgEASABIAAD/4RZLRXhpZgAATU0AKgAAAAgABwESAAMAAAABAAEAAAEaAAUA
AAABAAAAYgEbAAUAAAABAAAAagEoAAMAAAABAAIAAAExAAIAAAAUAAAAcgEyAAIAAAAUAAAAhodp
AAQAAAABAAAAnAAAAMgAAABIAAAAAQAAAEgAAAABQWRvYmUgUGhvdG9zaG9wIDcuMAAyMDAzOjA5
OjAxIDAwOjQ2OjI3AAAAAAOgAQADAAAAAf//AACgAgAEAAAAAQAAAoCgAwAEAAAAAQAAAeAAAAAA
...
```

I thought that this way GMail won't ask me if I want to display the image but display it automatically. But no, I had to approve I want to see the image anyway. So what is the advantage of sending images encoded in base64?

Anyway, the PR works, so :+1:

**Comment by Salamek** [comment]
@escopecz gmail (or any other email client) dont ask for normal images in base64, it asks cos this:

```html
<img style=3D"display: none;" height=3D"1" width=3D"1" src=3D"http:/=
/mautic.io/mautic-github/index_dev.php/email/5718bddb1f086.gif" alt=3D"Maut=
ic is open source marketing automation" />
```

It is caused by mautic tracking pixel (it is 1x1px image in each send email), but images are shown just OK

So this change is not to "prevent asking to show images" (cos that is caused by tracking pixel now) but to show images withnout any need to allow showing images! (you can disable remote images or ignore enable/disable dialog, but images in email will be still ok)

To prevent email clients to asking to show remote images, we need to add option to disable tracking pixel in emails (it is other request of my customer - already implemented in their mautic). For some ppl is more important to show email properly, withnout any irritating dialogs etc. then tracking email reads... i will create PR with this when ready

**Comment by Salamek** [comment]
@escopecz btw, we tested that this PR allows showing images without confirmation on these clients:

* Gmail
* M$ Outlook
* Gmail Android
* Email Android
* Thunderbird
* Seznam.cz

**Comment by escopecz** [comment]
Here is how I see it in my GMail. I added the source of the email next to it.
base64-email-question
I thought/hoped that it will work as you describe it and I'm glad it does for you. I'm just saying I'm disappointed it doesn't work for me.

**Comment by Salamek** [comment]
@escopecz maybe Gmail blocks all images when it finds one remote image in email body ? ... we removed tracking pixel from emails and gmail works just fine:
gmail

Other emails in my gmail box with remote images have blocked images like this:
remote

So looks like it needs to remove all remote images to get gmail show images withnout any issues...

**Comment by escopecz** [comment]
Well, that's too bad. Mautic needs the tracking pixel for tracking email open actions. Anyway, if it works in the rest of email clients, that's big improvement. As I said above, I vote for this PR to be merged :+1:

**Comment by alanhartless** [comment]
Let's move the new config setting down into the Message Settings panel maybe within the same div.row as default signature.

**Comment by alanhartless** [comment]
Seems to work well! Just move that config setting down into Message Settings and we'll merge this. 👍

**Comment by Salamek** [comment]
@alanhartless moved

**Comment by escopecz** [comment]
@Salamek could you please merge the latest staging to your branch and resolve the conflicts?

**Comment by Salamek** [comment]
@escopecz done

**Comment by alanhartless** [comment]
@Salamek Thanks! Is that `Append tracking pixel into email body?` something new?

**Comment by alanhartless** [comment]
Oh, nm. Just saw your other PR

**Pull request merged**
