### PR TITLE
"IF NOT EXISTS" added to all "CREATE TABLE" migrations

### PR DESCRIPTION
**Pull request by escopecz**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | N
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/5496, [Slack report](https://mautic.slack.com/archives/C02HU8BUT/p1516163740000245)
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
When fresh Mautic instance is installed it creates all DB tables from entities. When upgrade is executed and all the migrations kick in they try to create some tables again. But they exist already and it will lead to a SQL error described in linked reports.

This PR adds `IF NOT EXISTS` statement into each `CREATE TABLE` query so it will skip creating tables which already exist.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Install fresh Mautic from git.
2. Run `app/console doctrine:migrations:migrate` - the errors should appear

#### Steps to test this PR:
1. Checkout this PR
2. Run the migrations again, they all should pass.

### CODE REVIEW

**Comment by galvani** [comment]
I think I don't like the idea of prefixing ALL creates with IF EXISTS, this way the migrations may create problems/inconsistencies. I think you should  prefix just the 3 migrations failing to make this all work. The idea of rewriting migration is wrong and rewriting such a bunch....

**Comment by escopecz** [comment]
I can't think of a scenario where the `IF NOT EXISTS` could do some harm. Can you?

**Comment by javjim-mautic** [comment]
was able to reproduce the bug but got error with duplicate key in table.
QLSTATE[23000]: Integrity constraint violation: 1022 Can't write; duplicate key in table '#sql-561c_13'


  [Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'ALTER TABLE mautic_email_stat_replies ADD CONSTRAINT FK_D1A064B19502F0B F
  OREIGN KEY (stat_id) REFERENCES mautic_email_stats (id) ON DELETE CASCADE;':

  SQLSTATE[23000]: Integrity constraint violation: 1022 Can't write; duplicate key in table '#sql-561c_13'



  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1022 Can't write; duplicate key in table '#sql-561c_13'



  [PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1022 Can't write; duplicate key in table '#sql-561c_13'

But the way I see it is that it shouldnt have 2 creates for the same table or object, instead it should have a alter table

**Comment by javjim-mautic** [comment]
was able to verify that this PR fixes the issue I mentioned here.
https://github.com/mautic/mautic/pull/5555
so it has to have both applied.

**Pull request merged**
