### PR TITLE
New campaign condition: Has click from channels

### LINKED ISSUE #6466: separate contacts that only open email or click emails
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

## Description:
At the moment, it is not possible in a campaign to separate contacts that just open emails and contacts that click.
Loo at this below
image
Contacts that clicked on the email will follow the decision click emails but will obviously follow the decision open email (if a contact clicked on an email, he obviously opened it).

What could a nice feature would be to separate these two decisions. 
If a contact clicked on a email, having the possibility that contacts just follow decision click email (and not open email)

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | closes https://github.com/mautic/mautic/issues/6466
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Based on discussion  https://github.com/mautic/mautic/issues/6466#issuecomment-414236170

We can work with all clicked/non clicked contacts by new Campaign condition: Has click from channels 

image

#### Steps to test this PR:
1.  Create clicks from channels (notification, email, sms..)
2.  Create campaign with new condition: Has click from channels  + test include/exclude URLs with * (see tooltip for more info)
3. Test If return true/false based on your contact state

Test by Mautibox: https://mautibox.com/6488/s/login 

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/6488"></a>

### CODE REVIEW

**Comment by johbuch** [comment]
tested it --> works ! 
thanks

**Review by johbuch — DISMISSED** [review]
works for me

**Comment by kuzmany** [comment]
@johbuch  can you test again with include/exclude Urls function 

image

**Comment by kuzmany** [comment]
@johbuch can you retest it? 🥇

**Comment by YosuCadilla** [comment]
Tested with existing campaign, when I clicked on the link I got -10 points, when I opened the email but did NOT click on the link, I also got -10 points so I would think it's rather not counting clicks.

**Comment by kuzmany** [comment]
@YosuCadilla can you share that campaign?

**Comment by Mr-Binary** [comment]
It's the campaign that came "pre-installed" on the Mautic instance.

**Comment by YosuCadilla** [comment]
It's the campaign that came "pre-installed" on the instance.

**Comment by YosuCadilla** [comment]
I finally got my 33 points added, **test passed!**
Thank you for the additional instructions @kuzmany

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebased

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@kuzmany we would like to consider this for the 4.1 release however there is a conflict to address and the test coverage needs to be improved.

Will you be able to address this so that we can get it added to the milestone? Thanks!

**Comment by kuzmany** [comment]
@RCheesley we use it in production, then we will support it for M4 too

**Comment by RCheesley** [comment]
OK great - once the conflict is resolved and the test coverage is up we will consider it for adding to the milestone :)

**Comment by RCheesley** [comment]
@kuzmany please rebase this if you want to have this PR merged? Otherwise feel free to close it. Thanks!

**Comment by kuzmany** [comment]
Close at the moment. We will push it again once ready to M5

**Pull request closed without merging**
