### PR TITLE
Drop PHP 7.2 support

### LINKED ISSUE #9593: Deprecating PHP 7.2 support
As discussed in https://github.com/mautic/mautic/pull/9451, we are planning to deprecate and remove PHP 7.2 support in Mautic.

This process will consist of two stages:

1. Show deprecation warning starting with Mautic 3.2.5 - PR: #9594 
2. Fully remove support in Mautic 3.3.x - PR: #9451 

Removing PHP 7.2 support unblocks the upgrade to PHPUnit 9, which in turn should make it easier to upgrade to Symfony 4 soon.

### PR DESCRIPTION
**Pull request by dennisameling**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | features
| Bug fix?                               | n/a
| New feature?                           | n/a
| Deprecations?                          | n/a
| BC breaks?                             | n/a
| Automated tests included?              | n/a
| Related user documentation PR URL      | n/a
| Related developer documentation PR URL | n/a
| Issue(s) addressed                     | n/a

#### Description:

Part of #9593, this PR drops support for PHP 7.2 (targeted for Mautic 3.3.0).

PHP 7.2 [went EOL (End of Life) on November 30, 2020](https://www.php.net/supported-versions.php) and therefore isn't receiving security updates anymore. It is now safe to drop support for it, as Mautic 3.2 supports both PHP 7.3 and 7.4. It will also allow us to do things like [upgrading to PHPUnit 9](https://phpunit.de/supported-versions.html).

**We just need to decide whether we want to drop support in Mautic 3.2.1 already (scheduled for December 28, 2020) or for Mautic 3.3.0 (February 22, 2021)** @mautic/core-team 

#### Steps to test this PR:
1. Checkout this PR locally
2. Make sure you're running PHP 7.2
3. You should receive an error message that the PHP version is too low

### CODE REVIEW

**Comment by RCheesley** [comment]
I would rather not add the extra stress so close to the winter holidays for folk who may be on 7.2 and accidentally update (as we don't have those checks in place yet I think to prevent updating in environments that won't support the new version) - could we slate it for 3.2.2 and show a deprecation warning if they are using 7.2.x between 3.2->3.2.2?

May tie into the install/update initiative work also.

**Comment by escopecz** [comment]
So far we've been removing PHP versions support only in major releases. Although to be clear the support for PHP 7.2 will be removed only in terms of:
1. CI checks
2. Composer checks
3. Production package installation check

Is that right? So it will not affect anyone using Mautic on PHP 7.2. It will allow them to upgrade to latest release. It will not break any functionality for them. It will not limit them in any way. Everything will work for them as it used to. So it's not really a BC break.

The only break will be noticeable for developers as the PHPUNIT version will increase and if they develop on PHP 7.2 then Composer will force them to upgrade their localhost.

Considering my brain dump above I'm OK to merge this to a minor release. But we should put on a warning for existing instances out there still running on PHP 7.2 to upgrade ASAP for security reasons.

**Review by escopecz — DISMISSED** [review]

**Comment by dennisameling** [comment]
> could we slate it for 3.2.2 and show a deprecation warning if they are using 7.2.x between 3.2->3.2.2?

Will create a deprecation warning during the weekend. Assuming that a message under the notification bell in the top left corner is OK?

> So it will not affect anyone using Mautic on PHP 7.2

It will actually, since this PR touches `app/release_metadata.json`. It shows a hard error that the user is using an unsupported PHP version and Mautic will simply not boot.

Proposal:
- Make this a "soft deprecation" PR which doesn't affect any PHP 7.2 users until Mautic 3.3 is released (only devs as @escopecz mentioned)
- Show a deprecation warning in versions 3.2.1 + 3.2.2, saying that Mautic 3.3 (or even Mautic 4?) won't work on PHP 7.2 anymore

**Comment by dennisameling** [comment]
@escopecz as mentioned in https://github.com/mautic/mautic/issues/9593, there's a separate PR now which adds a warning in Mautic 3.2.5: https://github.com/mautic/mautic/pull/9594 - this PR fully removes 7.2 support in the `features` branch, so it will apply starting with Mautic 3.3.0.

@RCheesley can we turn off the required `PHPUnit 7.2 mariadb` and `PHPUnit 7.2 mysql` tests on the `features` branch? When this PR is merged, those checks are no longer relevant 👍🏼

**Comment by RCheesley** [comment]
Yes - want me to turn it off now? Or when this is merged?

**Comment by dennisameling** [comment]
If you could do it now that'd be great, otherwise non-admins can't merge this PR 🙈

**Comment by RCheesley** [comment]
Your wish is my command :mage_woman: :sparkles:

**Comment by RCheesley** [comment]
@escopecz just pending a review and I would prefer if this comes from a developer - could you take a look and give it a 👍  if we are good to go? Then we can crack on with other stuff in the features and 4.0 branch!

**Review by escopecz — APPROVED** [review]
:+1:

**Pull request merged**
