### PR TITLE
Fix Dynamic content block in email behaving differently in first save and edit [4.4]

### PR DESCRIPTION
**Pull request by danadelion**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [y]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/issues/12293

#### Description:

See https://github.com/mautic/mautic/issues/12293

Check #12637 for the Mautic 5.x PR.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. See https://github.com/mautic/mautic/issues/12293

### CODE REVIEW

**Review by RCheesley — APPROVED** [review]
Thanks for the PR @danadelion and welcome to the community! 🚀 

I've tested this and can see that the correct language is shown now instead of the language code. Thanks for the fix!

screenshot-8080-danadelion-mautic-qdyycegmzzy ws-eu102 gitpod io-2023 08 08-11_42_27

If you can please make the same PR against the 5.x branch as well that would ensure it is released with the 5.x releases too.

**Comment by RCheesley** [comment]
@all-contributors please add @danadelion for code

**Review by MadlenF — APPROVED** [review]
Works as described! 👍

**Comment by RCheesley** [comment]
Marking as RTC with a code review 🚀 thanks folks!

**Pull request merged**
