### PR TITLE
Trying to get PHPUNIT working on the 3.x branch

### PR DESCRIPTION
**Pull request by escopecz**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/8028
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR resolves issue related to PHPUNIT upgrade. Most of the issues were with fixtures that relates to Liip* bundles upgrade.

All the tests aren't passing still but that's because all the bundle refactoring weren't merged yet. I consider this done and we will have to revisit after all deprecated (and now removed) code will be refactored. It's still much better than the original state where the tests did not run at all.

For code reviewers: It will be faster to review commit by commit and skip those commits titled `Automatic CS fixes after running bin/php-cs-fixer fix` as there is gazillion automatic changes there.

#### Steps to test this PR:
1. Check the travis output. The failed tests are related to bundles that are waiting to be merged.

#### List backwards compatibility breaks:
1. See https://docs.google.com/document/d/1lHNK8hHQtvyWlz9OtfAoLupDVb5-QunQjq-HAGlAsS4/edit#heading=h.qork18mo6yws

### CODE REVIEW

**Comment by escopecz** [comment]
@anton-vlasenko what is the reason for the suggested change?

**Comment by anton-vlasenko** [comment]
To fix "This test did not perform any assertions" you had to add something like
https://github.com/mautic/mautic/commit/e1d6d5d0dc42818c7dbf98c305654e89c100d289#diff-842b3c6560e07fb7433ea0e2eac4e0d9R66

**Comment by escopecz** [comment]
Understood. I improved several the tests in that commit so it's ugly only in few. And it does the same thing. I'll leave it as is.

**Comment by dongilbert** [comment]
Merged, so moving the JIRA issue to done

**Comment by dongilbert** [comment]
oh, nvm. I had an outdated sprint board. :P

**Pull request merged**
