### PR TITLE
[dead-code] Remove unused variable assigns

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Ready to go :+1:

**Comment by escopecz** [comment]
@TomasVotruba can you please resolve the conflict?

**Comment by TomasVotruba** [comment]
I'm on it :+1:

**Review by escopecz — APPROVED** [review]
All cases of removed unused variables look good. The tricky part was in app/bundles/StageBundle/Event/StageBuilderEvent.php where the variable was unused but the method had to be called to populate the object property. Although working with the returned value would be better. It's impressive if Rector can understand that 👍

**Comment by TomasVotruba** [comment]
Thanks for solid review :+1:

**Pull request merged**
