### PR TITLE
Enable code owners on repo

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [X]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

One of the great features of Github is [code owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners), which is a great way to keep track of PRs that changes parts of the contributors make code changes to the most

For example, I have an interest in following any PRs that make changes to `EmailBundle` so I created this file to notify me when there is a PR made on that bundle and it auto-assigns me to review it. 

It could be a great feature to use, where we ask the core team and community members to focus their efforts on topics they are most interested in 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
Good idea 👍

**Comment by RCheesley** [comment]
@mabumusa1 @escopecz would we want to have the code owners approve any PRs which touch their areas of speciality before they are merged (we can turn it on in branch restrictions I believe)?

This is how I would see the Tiger Teams working, so it would be a good first step IMO.

Some things to bear in mind:

- The people you choose as code owners must have write permissions for the repository (so only the core team, I think?)
- We can assign teams and individuals 
- When the code owner is a team, that team must be visible and it must have write permissions

**Comment by escopecz** [comment]
Yes, it would be great to have devs who takes care of specific bundle(s). Perhaps creating a team for EmailBundle and using that instead of @mabumusa1 directly would be cleaner solution as we could then add/remove GH users any time without a need for a code change. WDYT?

**Comment by mabumusa1** [comment]
@escopecz check what those did 
https://www.fullstory.com/blog/taming-github-codeowners-with-bots/

**Comment by escopecz** [comment]
Maybe I misunderstand that article but it seems overcomplicated. Especially when we don't have enough devs who would be interested to be notified to review PRs.

**Comment by RCheesley** [comment]
I think this is a good place to start, but going forward indeed it would be better to have this work with teams rather than individuals.

cc @mollux for visibility.

**Review by RCheesley — APPROVED** [review]

**Pull request merged**
