### PR TITLE
Update contact campaign action - new options to update fields

### LINKED ISSUE #6553: features - campaign update contacts
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | 

## Description:
In a campaign, there is the possiblity to update contact field with the action
image

Currently if you let fields blank, nothing happens which is good. 
But another opportunity would be to choose to remove values of select or select multiple fields.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/63266249-features-campaign-update-contacts?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by kuzmany**
closes https://github.com/mautic/mautic/issues/6553
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | x
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/6553
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Follow up to https://github.com/mautic/mautic/pull/6587

This PR extend Update contact campaign action with 3 actions:
- update field
- empty field 
- add values (for multiple select field)
- remove values (for multiple select field)

image

#### Steps to test this PR:
Require `php bin/console mautic:assets:generate`
1.  Create update action and test update/empty field
2.  Test also add/remove values from multiple select field
3.  Also test migrations with from old to new update campaign action

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/6805"></a>

### CODE REVIEW

**Comment by johbuch** [comment]
@kuzmany  I just tested on mautibox but it did not work for me
Here what I set
image

After campaign triggered
image

nothings changed
image

**Comment by kuzmany** [comment]
@johbuch now it's ready to test ;)

**Review by johbuch — APPROVED** [review]
@kuzmany sorry about the 1st test (I thought it was ok), so i just tested again and it works

**Comment by escopecz** [comment]
@kuzmany there are some conflicts

**Comment by kuzmany** [comment]
guys wait, need re-test and improve migrations

**Comment by kuzmany** [comment]
Now fixed. Please re-test and focus also on migrations.

**Comment by kuzmany** [comment]
@npracht added Add values, please test ;)

**Review by johbuch — DISMISSED** [review]
just tested the new feature add values on mautibox, works great !
thanks

**Comment by dichvuhuuich** [comment]
Will this feature be added to Mautic?

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@kuzmany another one with conflicts :)

**Comment by kuzmany** [comment]
Rebased and re-tester for M3. Works

**Comment by RCheesley** [comment]
@cla-bot check

**Review by sPradella — DISMISSED** [review]
all fine thank you

**Comment by stevedrobinson** [comment]
@kuzmany I patched an instance with 3.2.5 and ran the migration. I'm getting errors and the UI isn't fully loading.

image


Javascript Console:
```
28:1 Uncaught TypeError: Mautic.updateContactActionModifiers is not a function
    at HTMLSelectElement.onchange (28:1)
```

Mautic log:
```
[2021-02-13 14:00:51] mautic.NOTICE: PHP Notice - Trying to access array offset on value of type null - in file /mautic/root/folder/app/bundles/LeadBundle/Form/Type/UpdateLeadActionType.php - at line 83 {"builder":"[object] (Ivory\\OrderedForm\\Builder\\OrderedFormBuilder: {})","options":{"block_name":null,"disabled":false,"label_format":null,"translation_domain":null,"auto_initialize":true,"trim":true,"required":true,"property_path":null,"mapped":true,"by_reference":true,"inherit_data":false,"compound":true,"method":"POST","action":"","post_max_size_message":"The uploaded file was too large. Please try to upload a smaller file.","allow_file_upload":false,"error_mapping":[],"invalid_message":"This value is not valid.","invalid_message_parameters":[],"allow_extra_fields":false,"extra_fields_message":"This form should not contain extra fields.","csrf_protection":true,"csrf_field_name":"_token","csrf_message":"The CSRF token is invalid. Please try to resubmit the form.","csrf_token_manager":"[object] (Symfony\\Component\\Security\\Csrf\\CsrfTokenManager: {})","csrf_token_id":null,"label":false,"attr":[],"data":null,"data_class":null,"empty_data":"[object] (Closure: {})","error_bubbling":true,"label_attr":[],"upload_max_size_message":"[object] (Closure: {})","validation_groups":null,"constraints":[],"position":null,"fields":"[object] (Doctrine\\ORM\\Tools\\Pagination\\Paginator: {})","ignore_required_constraints":true,"ignore_date_type":true},"leadFields":"[object] (Doctrine\\ORM\\Tools\\Pagination\\Paginator: {})"} []
```

**Comment by kuzmany** [comment]
@stevedrobinson probably you need regenerate assets in production mautic:assets:generate

**Comment by stevedrobinson** [comment]
@kuzmany that was the issue. I've tested this and it works great. I hope we don't really have to wait until Mautic 4.0 for this!

**Comment by RCheesley** [comment]
@kuzmany we would like to consider this for the 4.1 release but there is a conflict to be addressed. Can you take a look so that we can add it to the milestone? Thanks!

**Comment by mabumusa1** [comment]
@kuzmany I tried to implement this PR on the latest branch but it seems it is not working. the exception happens on line #74 on the file `app/bundles/LeadBundle/Form/Type/UpdateLeadActionType.php` it seems that  does not exist in the incoming array

```          
      'actions' => $options['data']['actions'],
       'data'    => $options['data']['fields'],
```

image

**Comment by kuzmany** [comment]
@mabumusa1 did you run migrations?

**Comment by mabumusa1** [comment]
> @mabumusa1 did you run migrations?

@kuzmany yes, I ran the migration and generated new assets, but the problem still persists. the array `$options` is missing `data` therefore it fires an exception on line 72 `app/bundles/LeadBundle/Form/Type/UpdateLeadActionType.php`

**Comment by kuzmany** [comment]
@mabumusa1 Ok, I'll check it

**Comment by stevedrobinson** [comment]
@kuzmany I was running this in production on our version 3 instances with no problem, but I'm getting issues on our version 4 instances as @mabumusa1 mentioned. 

This is what I see in the UI: 
image

Here is the error log output:
```[2021-12-20 11:34:53] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException: "An error has occurred resolving the options of the form "Symfony\Component\Form\Extension\Core\Type\ChoiceType": The option "choices_as_values" does not exist. Defined options are: "action", "allow_extra_fields", "allow_file_upload", "attr", "attr_translation_parameters", "auto_initialize", "block_name", "block_prefix", "by_reference", "choice_attr", "choice_label", "choice_loader", "choice_name", "choice_translation_domain", "choice_value", "choices", "compound", "constraints", "csrf_field_name", "csrf_message", "csrf_protection", "csrf_token_id", "csrf_token_manager", "data", "data_class", "disabled", "empty_data", "error_bubbling", "error_mapping", "expanded", "extra_fields_message", "group_by", "help", "help_attr", "help_html", "help_translation_parameters", "inherit_data", "invalid_message", "invalid_message_parameters", "label", "label_attr", "label_format", "label_translation_parameters", "mapped", "method", "multiple", "placeholder", "post_max_size_message", "preferred_choices", "property_path", "required", "row_attr", "translation_domain", "trim", "upload_max_size_message", "validation_groups"." at /WEB_ROOT/vendor/symfony/form/ResolvedFormType.php line 99 {"exception":"[object] (Symfony\\Component\\OptionsResolver\\Exception\\UndefinedOptionsException(code: 0): An error has occurred resolving the options of the form \"Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType\": The option \"choices_as_values\" does not exist. Defined options are: \"action\", \"allow_extra_fields\", \"allow_file_upload\", \"attr\", \"attr_translation_parameters\", \"auto_initialize\", \"block_name\", \"block_prefix\", \"by_reference\", \"choice_attr\", \"choice_label\", \"choice_loader\", \"choice_name\", \"choice_translation_domain\", \"choice_value\", \"choices\", \"compound\", \"constraints\", \"csrf_field_name\", \"csrf_message\", \"csrf_protection\", \"csrf_token_id\", \"csrf_token_manager\", \"data\", \"data_class\", \"disabled\", \"empty_data\", \"error_bubbling\", \"error_mapping\", \"expanded\", \"extra_fields_message\", \"group_by\", \"help\", \"help_attr\", \"help_html\", \"help_translation_parameters\", \"inherit_data\", \"invalid_message\", \"invalid_message_parameters\", \"label\", \"label_attr\", \"label_format\", \"label_translation_parameters\", \"mapped\", \"method\", \"multiple\", \"placeholder\", \"post_max_size_message\", \"preferred_choices\", \"property_path\", \"required\", \"row_attr\", \"translation_domain\", \"trim\", \"upload_max_size_message\", \"validation_groups\". at /WEB_ROOT/html/vendor/symfony/form/ResolvedFormType.php:99, Symfony\\Component\\OptionsResolver\\Exception\\UndefinedOptionsException(code: 0): The option \"choices_as_values\" does not exist. Defined options are: \"action\", \"allow_extra_fields\", \"allow_file_upload\", \"attr\", \"attr_translation_parameters\", \"auto_initialize\", \"block_name\", \"block_prefix\", \"by_reference\", \"choice_attr\", \"choice_label\", \"choice_loader\", \"choice_name\", \"choice_translation_domain\", \"choice_value\", \"choices\", \"compound\", \"constraints\", \"csrf_field_name\", \"csrf_message\", \"csrf_protection\", \"csrf_token_id\", \"csrf_token_manager\", \"data\", \"data_class\", \"disabled\", \"empty_data\", \"error_bubbling\", \"error_mapping\", \"expanded\", \"extra_fields_message\", \"group_by\", \"help\", \"help_attr\", \"help_html\", \"help_translation_parameters\", \"inherit_data\", \"invalid_message\", \"invalid_message_parameters\", \"label\", \"label_attr\", \"label_format\", \"label_translation_parameters\", \"mapped\", \"method\", \"multiple\", \"placeholder\", \"post_max_size_message\", \"preferred_choices\", \"property_path\", \"required\", \"row_attr\", \"translation_domain\", \"trim\", \"upload_max_size_message\", \"validation_groups\". at /WEB_ROOT/html/vendor/symfony/options-resolver/OptionsResolver.php:799)"} []```

Could this be because the migration was already run under version 3, but undone with the upgrade to 4 somehow? Sorry, I'm not clear on how migrations work in Symfony.

**Comment by stevedrobinson** [comment]
@kuzmany Is there anything I can do to help get this updated to be compatible with version 4?

**Comment by kuzmany** [comment]
@stevedrobinson @mabumusa1 can you test now?

**Comment by escopecz** [comment]
@kuzmany maybe take a look at the failing test before it will be tested so it does not have to be retested afterwards. It will speed up the process.
```
/home/runner/work/mautic/mautic/app/bundles/LeadBundle/Tests/EventListener/CampaignSubscriberFunctionalTest.php:113

3) Mautic\LeadBundle\Tests\EventListener\CampaignSubscriberTest::testOnCampaignTriggerActiononUpdateCompany
Expectation failed for method name is "getEntities" when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.
```

**Comment by stevedrobinson** [comment]
I can wait to user test until the automated test is resolved.

**Comment by stevedrobinson** [comment]
Tested on 4.1.2 and looks good! Thank you, @kuzmany!

**Comment by stevedrobinson** [comment]
What is the status on this PR?

**Comment by stevedrobinson** [comment]
This is an invaluable enhancement. We've been running this in production for well over a year now. 

@kuzmany @RCheesley  do you think this will make it in 4.4? I'm not able to write the automated tests for this, but is there some other way I can help?

**Comment by ghost** [comment]
Hi, I opened the Gitpod:
[Open in Gitpod](https://kuzmany-mautic-yhmtn02bya1.ws-eu96.gitpod.io/)
image

and got this error
`Failed to start mautic: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-mautic docker-compose -f /workspace/mautic/.ddev/.ddev-docker-compose-full.yaml up --build -d', action='[up --build -d]', err='exit status 15', stdout='', stderr='services.web.extra_hosts array items[0,1] must be unique' `
image

**Should I test another way?**

If not ready to test, should the tag `pending-test-confirmation` be removed?

**Comment by escopecz** [comment]
Might be because of the conflicts. @kuzmany please take a look

**Comment by djmonzyk** [comment]
I too would love to see this merged into core....Thanks all for contributing to this key functionality.

**Comment by RCheesley** [comment]
Hi folks, looks like there's a lot of interest in this enhancement - @kuzmany would you consider rebasing to 5.x and fixing the conflicts? Then we can finally get this merged if folks still want it in Mautic!

**Comment by DCCRUHR** [comment]
Hey guys. We would also love to see the function in the core. That would significantly strengthen the campaign feature. Thanks for the effort!

**Comment by kuzmany** [comment]
Close this feature request for now

**Pull request closed without merging**
