### PR TITLE
New feature: Sending Emails through the Amazon SES API instead of SMTP

### PR DESCRIPTION
**Pull request by chimme**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | #1740 
| BC breaks? | /
| Deprecations? | /

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

This Pull Request implements the AWS SES sending process from SMTP to the AWS SES API and for better performance with a tokenBucket. 
There is still some improvement potential for sending various mails through a queue.

### CODE REVIEW

**Comment by escopecz** [comment]
Fix the [failing CI tests](https://travis-ci.org/mautic/mautic/builds/263445790?utm_source=github_status&utm_medium=notification) please.

**Comment by wittwerch** [comment]
@escopecz is it possible that the 5.6 build is failing because the composer.lock is not updated in the staging branch and it now pops up because @chimme added one package to the composer.json?
When I checkout the lastest staging a64d70c79ea91032ddd4041df7b19af13d4c17aa and run a `composer update`it updates the composer.lock, which should not be the case without touching the composer.json?

**Comment by escopecz** [comment]
I think the problem is that you run `composer update` This updates all dependencies and it may cause problems that does not have anything to do with your PR. Like you can see now. So the rule number 1 is to never run `composer update` but use `composer install` instead which updates dependencies based on composer.lock file.

Rule number 2: If you want to add a new dependency (`bandwidth-throttle/token-bucket` in your case), run `composer require bandwidth-throttle/token-bucket'. This will add it to composer.json and updates composer.lock only with this one package.

I'd suggest to revert composer.json and composer.lock changes and run the `composer require...` command above. Then commit those changes.

**Comment by Arjoni** [comment]
Will this also integrate bounces automatically or the webhook is still needed?

**Comment by chimme** [comment]
This PR doesn't change the bounce handling. So far I just implemented the E-Mail sending through the SES API. Thus you probably still need the Webhook.

**Comment by alanhartless** [comment]
@chimme Looking at the code on this, I don't see where attachments are handled at all which is important for the New/Edit Email -> Advanced tab -> Attachments feature. 

Also by extending the `AbstractTokenHttpTransport` class, Mautic is going to group all the emails together when possible, for example with sending through a broadcast (segment) email. This means that each recipient's tokens are going to be accessible via `$this->getMetadata()`. From what I can tell in the code, the email sent through Amazon is raw leaving tokens not replaced. Does SES API have a merge vars feature?

**Comment by maxitromer** [comment]
We are waiting for this feature a long time ...

Thanks @chimme and all the people working here.

I have a question for you.

Is there a safe way use this code in a production instance of Mautic (we doesnt use attachments in our emails) while we wait for the final solution without losing the Mautic updates?

We need this to speed up the sending because we have a big list of suscribers (150.000 and counting).

Thanks in advance for your advice and your answer.

**Comment by chimme** [comment]
@alanhartless Thank you for your feedback. I changed the class so that it is possible to send embed images and attachments (assets) with a raw sending method. You're right Amazon SES doesn't have merge vars so I put the extension via the `AbstraktTokenArrayTransport` class . I don't know if this is a bug, but i needed to disable `$this->tokenizationEnabled` in the `MailHelper` class, otherwise assets wouldn't get send. 

@maxitromer Thank you too for your interest in my PR. It's difficult to say if it's a safe way, because it isn't fully tested yet (I spend much time with testing, but there can always appear some bugs), although after all I mostly changed the sending process through the Amazon SES API.

**Comment by alanhartless** [comment]
It's not a bug. tokenizationEnabled is determined by the use of the InterfaceTokenTransport which should only be used if the transport supports merge vars. Otherwise, the emails will not contain the correct replacements for the contact's field data.

**Comment by wittwerch** [comment]
AWS SES now supports tokens: https://aws.amazon.com/blogs/ses/introducing-email-templates-and-bulk-sending/
We will update the PR with that new token support to speed up the delivery of emails.

**Comment by nithinga** [comment]
The new PR based on AWS SES token : https://github.com/mautic/mautic/pull/5263/

**Comment by alanhartless** [comment]
Closing in favor of #5263

**Comment by RCheesley** [comment]
Hi folks, I just wanted to say a big thank you for your work on this PR all the way back in 2017. We finally are getting it merged into Mautic 3.1!

Your work is very much appreciated! 🎉

**Pull request closed without merging**
