### PR TITLE
Fix Imports create Duplicates when Email is publicly updatable

### PR DESCRIPTION
**Pull request by Dcoutelle**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? |N
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #5281 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Avoid duplicate lead on import when email is publicUpdatable
[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Make the email field publicly updatable
2. Import a CSV file as simple as the following:
```
email
test@example.com
```
 3. Import that same file again
 4. You should have two identical leads
2. 

#### Steps to test this PR:
1. apply this PR
2. Import the same file to see contact are merged

### CODE REVIEW

**Comment by escopecz** [comment]
@Dcoutelle Thanks for the fix! 

I don't understand why the code was changed the way it was too. Although it clearly fixes the issue. Could you please write unit test to cover the bug to ensure it won't return? Every PR must contain unit tests if possible.

**Comment by MaxWebmecanik** [comment]
Hey @escopecz, I appreciate that Mautic is improving its testing policy and I do believe that any new feature, developed by the core team or the community, should be accompanied by automated tests. That is unit tests or feature tests or system tests or whatever jargon people like to throw around these days.

However, the bug addressed by this PR is one of the more critical bugs to have befallen Mautic as it allows imports on some instances to create as many duplicates as the CSV file holds. This means that some instances easily end up having thousands of duplicated contacts which is critical.

With such critical cases, I believe it is imperative to implement the fix as quickly as possible, even if not accompanied by tests, and in cases where the fix is brought on by the community, do your best to help the community member write the accompanying tests. I do not think it is reasonable to ask of the community to withhold their (possibly critical) bug fixes until they write automated tests which they might not be experienced in writing, especially in the context of Mautic.

All that being said, if you need more information on what this does, we'd be happy to fill you in, and if you help us write the tests, we'll be happy to give it our best. But please, do not let such bugs remain unfixed, when the community fixes a feature that was developed by the core team in the first place.

**Comment by escopecz** [comment]
@MaxWebmecanik I didn't say anything about withholding fixes. There is no new release date even scheduled. Plenty of time to add the test to this PR. Just let us know whether you will add it.

If you are saying that you won't be providing tests to your PRs at all for some reason, let's discuss it at Slack.

**Comment by MaxWebmecanik** [comment]
@escopecz That's good to hear, if you give us pointers on how to write tests for this PR, maybe by showing us similar existing test cases, we'll gladly try to write our own. I'm not at all suggesting we would categorically refuse to write such tests. I simply want to make it clear that I would find it a waste not to include such a fix in the next release, simply because it's not tested. Thanks for your feedback :)

**Comment by escopecz** [comment]
I'm glad we cleared that up! I don't see any unit tests started for the LeadModel class, so please create it at `app/bundles/LeadBundle/Tests/Model/LeadModelTest.php`. Find an inspiration in other model tests. For example:
https://github.com/mautic/mautic/blob/staging/app/bundles/LeadBundle/Tests/Model/ImportModelTest.php

**Comment by alanhartless** [comment]
I think we've all been there where we say "oh we'll get to that later" and it the reality is later never comes. That's the story of Mautic with automatic tests and it's biting us in the ass nearly daily. :-) So I may not hold up a critical fix because it doesn't have a test but it's even more critical to have test for critical fixes to ensure we don't break it again :-) 

Right now due to Mautic's code base, it may be easier to write a functional test versus a unit test. And that's fine. For example, I just wrote https://github.com/mautic/mautic/pull/5309/files#diff-0f90e70bb5662a6b0798025f470f2731R97

Thanks guys!

**Comment by MaxWebmecanik** [comment]
Hey @alanhartless,

Thanks a lot for the example! This should definitely help us test this bug fix.
I'm a 100% with you on your point, delaying tests until _later_ means _later_, more often than not, ends up being _never_.
The point I want to get across is that with critical bug fixes like that, I'm hoping that the Mautic core team will be as helpful as it can helping the community write automated tests. For this particular instance, I would even go as far as to say that if the community failed to deliver the tests, the core team should take it over, and write the tests itself (considering the defect had already been introduced...)
That said, I'll try to write the tests for this PR tonight (CET) or tomorrow morning.

Thanks again for the very relevant example 😀

**Comment by MaxWebmecanik** [comment]
Hey @alanhartless. I can't get the tests to run for the life of me...

Cries of dispair: https://mautic.slack.com/archives/C02HV76BW/p1510224160000250

Failed attempt #1:
```
bin/phpunit --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist --fail-on-warning app/bundles/LeadBundle/Tests/Model/LeadModelFunctionalTest.php
```

Failed attempt #2: `bin/codecept run`

Could you guide me as to how to set up the test database and run a specific test file (rather than the whole test suite) 😢

**Comment by alanhartless** [comment]
@MaxWebmecanik I think there was some discussion on Slack. Did you get the unit tests to run? I'm updating the readme on leveraging the .env file.

**Comment by dongilbert** [comment]
@Dcoutelle @npracht @MaxWebmecanik I added unit tests to this to ensure we're passing the correct parameters to the `getFieldList` call.

**Comment by npracht** [comment]
@dongilbert thanks a lot for that example. I'll ask David to have a close look at it to try to introduce it in our next contributions :)

**Pull request merged**
