### PR TITLE
DPMMA-1696 optionally stop engaging after closing the focus

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ N ]
| New feature/enhancement? (use the a.x branch)      | [ Y ]
| Deprecations?                          | [ N ]
| BC breaks? (use the c.x branch)        | [ N ]
| Automated tests included?              | [ N ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR adds a new option to the focus item builder to stop engaging when the user directly closes the focus (using the x key).
The implementation is similar to the existing **Stop engaging after a conversion** and is based on cookies. Therefore, the focus will no longer be displayed until the visitor clears their cookies.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create new Focus Item with selected option **Stop engaging after a closing the focus?**
image
3. Create Landing Page and add Focus Item (via script in head/footer or token in builder)
4. Open the landing page in a private window, the Focus Item should appear
5. Refresh the page without closing the Focus Item, it should appear again
6. Close the Focus Item with the 'x' button
7. Refresh the page
8. The Focus item should not appear until you clear your cookies

### CODE REVIEW

**Review by kuzmany — COMMENTED** [review]
Why we do it so complicated?
Why we just  after close do  not set mautic_focus_id to -1 same like after submission
https://github.com/mautic/mautic/blob/bb501e9da23447155a2b5e6583c62335442a1516/plugins/MauticFocusBundle/Resources/views/Builder/generate.js.twig#L643

**Comment by patrykgruszka** [comment]
@kuzmany sure, we could use `mautic_focus_id`, but that will not give us any information about why the focus item is no longer displayed. I wanted to use a separate cookie to separate this behaviour.

`mautic_focus_id=-1` Could mean anything
`mautic_focus_id_closed=2` Gives you exact info, that the Focus Item was closed two times and you can handle it in the code.

**Comment by kuzmany** [comment]
@patrykgruszka Ok, understand. I prefer simplicity, but cannot block it just for that reason.  Thanks. I will test it

**Review by annamunk — APPROVED** [review]
I checked the changes and tested with "Stop engaging after closing" set to Yes, the cookie is set correctly. I like the idea of creating separate cookie that only stores information about closing the Focus Item, so the value won't be misleading.
focus_item_close

**Review by kuzmany — APPROVED** [review]
I've made basic tests and it works on my side.

**Comment by kuzmany** [comment]
It needs rebase onto 5.1

**Comment by patrykgruszka** [comment]
@kuzmany right, I've just rebased this on 5.1. Thanks.

@annamunk thanks for your review.

**Comment by RCheesley** [comment]
@patrykgruszka this needs a small update to the docs on this page: https://docs.mautic.org/en/5.x/channels/focus_items.html - could you do that?

cc @mautic/education-team for 5.1 release.

**Comment by RCheesley** [comment]
Docs are now done: https://github.com/mautic/user-documentation/pull/273

**Pull request merged**
