### PR TITLE
Unsubscribe fix

### PR DESCRIPTION
**Pull request by escopecz**
Please answer the following questions:

| Q             | A
| ------------- | ---
| Bug fix?      | Y
| New feature?  | N
| BC breaks?    | N
| Deprecations? | N
| Fixed issues  |  https://github.com/mautic/mautic/issues/1947

## Description
The unsubscribe and resubscribe pages throw a SQL error.

## Steps to reproduce the bug (if applicable)
Send an email with `{unsubscribe_text}‍` token. Send the email to an actual lead with your email address. Click the unsubscribe link.

Also, removing the Unsubscribe feedback form throws an error. Try to add one, save the form. Remove it and save again. You should see the error.

## Steps to test this PR
Apply this PR and click the link again. Also, try to resubscribe. That was also broken.

Try to remove the Unsubscribe feedback form now, it should work.

### CODE REVIEW

**Comment by ipso** [comment]
I can confirm that this fixes the issue. Thank you!

**Comment by dongilbert** [comment]
+1

**Comment by martinstr** [comment]
This fixed my unsubscribe problem for the contacts but it is still showing 500 Internal Server Error on the page when contacts click the link in there emails. {unsubscribe_text}‍

**Comment by martinstr** [comment]
Here is the log, the 3 last lines can probably have sometime to do with it?

`[2016-07-11 00:11:14] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 00:14:38] mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Requested URL not found: /xmlrpc.php" at /opt/bitnami/apps/mautic/htdocs/app/bundles/CoreBundle/Controller/CommonController.php line 411 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Requested URL not found: /xmlrpc.php at /opt/bitnami/apps/mautic/htdocs/app/bundles/CoreBundle/Controller/CommonController.php:411)"} []
[2016-07-11 00:18:28] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 00:42:37] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 00:51:12] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 00:52:13] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 00:53:58] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 00:57:09] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 01:05:24] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 01:27:47] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 01:39:31] mautic.WARNING: PHP Warning: include(/opt/bitnami/apps/mautic/htdocs/vendor/twig/twig/lib/Twig/Node/Expression/Test/Defined.php): failed to open stream: No such file or directory - in file /opt/bitnami/apps/mautic/htdocs/vendor/composer/ClassLoader.php - at line 412 [] []
[2016-07-11 01:39:31] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Twig_Node_Expression_Test_Defined" from the global namespace. Did you forget a "use" statement?" at /opt/bitnami/apps/mautic/cache/prod/classes.php line 6705 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Twig_Node_Expression_Test_Defined\" from the global namespace.\nDid you forget a \"use\" statement? at /opt/bitnami/apps/mautic/cache/prod/classes.php:6705)"} []
[2016-07-11 01:39:31] mautic.ERROR: Error: Class 'Twig_Node_Expression_Test_Defined' not found - in file /opt/bitnami/apps/mautic/cache/prod/classes.php - at line 6705 [] []
[2016-07-11 01:39:46] mautic.WARNING: PHP Warning: include(/opt/bitnami/apps/mautic/htdocs/vendor/twig/twig/lib/Twig/Node/Expression/Test/Defined.php): failed to open stream: No such file or directory - in file /opt/bitnami/apps/mautic/htdocs/vendor/composer/ClassLoader.php - at line 412 [] []
[2016-07-11 01:39:46] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Twig_Node_Expression_Test_Defined" from the global namespace. Did you forget a "use" statement?" at /opt/bitnami/apps/mautic/cache/prod/classes.php line 6705 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Twig_Node_Expression_Test_Defined\" from the global namespace.\nDid you forget a \"use\" statement? at /opt/bitnami/apps/mautic/cache/prod/classes.php:6705)"} []
[2016-07-11 01:39:46] mautic.ERROR: Error: Class 'Twig_Node_Expression_Test_Defined' not found - in file /opt/bitnami/apps/mautic/cache/prod/classes.php - at line 6705 [] []
[2016-07-11 01:42:24] mautic.WARNING: PHP Warning: include(/opt/bitnami/apps/mautic/htdocs/vendor/twig/twig/lib/Twig/Node/Expression/Test/Defined.php): failed to open stream: No such file or directory - in file /opt/bitnami/apps/mautic/htdocs/vendor/composer/ClassLoader.php - at line 412 [] []
[2016-07-11 01:42:24] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Twig_Node_Expression_Test_Defined" from the global namespace. Did you forget a "use" statement?" at /opt/bitnami/apps/mautic/cache/prod/classes.php line 6705 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Twig_Node_Expression_Test_Defined\" from the global namespace.\nDid you forget a \"use\" statement? at /opt/bitnami/apps/mautic/cache/prod/classes.php:6705)"} []
[2016-07-11 01:42:24] mautic.ERROR: Error: Class 'Twig_Node_Expression_Test_Defined' not found - in file /opt/bitnami/apps/mautic/cache/prod/classes.php - at line 6705 [] []
[2016-07-11 01:49:35] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 01:50:15] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 01:55:16] mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Unauthorized access to requested URL: /form/submit?formId=10" at /opt/bitnami/apps/mautic/htdocs/app/bundles/CoreBundle/Controller/CommonController.php line 387 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Unauthorized access to requested URL: /form/submit?formId=10 at /opt/bitnami/apps/mautic/htdocs/app/bundles/CoreBundle/Controller/CommonController.php:387)"} []
[2016-07-11 01:55:18] mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Unauthorized access to requested URL: /form/submit?formId=10" at /opt/bitnami/apps/mautic/htdocs/app/bundles/CoreBundle/Controller/CommonController.php line 387 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Unauthorized access to requested URL: /form/submit?formId=10 at /opt/bitnami/apps/mautic/htdocs/app/bundles/CoreBundle/Controller/CommonController.php:387)"} []
[2016-07-11 02:05:04] mautic.WARNING: PHP Warning: include(/opt/bitnami/apps/mautic/htdocs/vendor/twig/twig/lib/Twig/Node/Expression/Test/Defined.php): failed to open stream: No such file or directory - in file /opt/bitnami/apps/mautic/htdocs/vendor/composer/ClassLoader.php - at line 412 [] []
[2016-07-11 02:05:04] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Twig_Node_Expression_Test_Defined" from the global namespace. Did you forget a "use" statement?" at /opt/bitnami/apps/mautic/cache/prod/classes.php line 6705 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Twig_Node_Expression_Test_Defined\" from the global namespace.\nDid you forget a \"use\" statement? at /opt/bitnami/apps/mautic/cache/prod/classes.php:6705)"} []
[2016-07-11 02:05:04] mautic.ERROR: Error: Class 'Twig_Node_Expression_Test_Defined' not found - in file /opt/bitnami/apps/mautic/cache/prod/classes.php - at line 6705 [] []
[2016-07-11 02:05:05] mautic.WARNING: PHP Warning: include(/opt/bitnami/apps/mautic/htdocs/vendor/twig/twig/lib/Twig/Node/Expression/Test/Defined.php): failed to open stream: No such file or directory - in file /opt/bitnami/apps/mautic/htdocs/vendor/composer/ClassLoader.php - at line 412 [] []
[2016-07-11 02:05:05] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Twig_Node_Expression_Test_Defined" from the global namespace. Did you forget a "use" statement?" at /opt/bitnami/apps/mautic/cache/prod/classes.php line 6705 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Twig_Node_Expression_Test_Defined\" from the global namespace.\nDid you forget a \"use\" statement? at /opt/bitnami/apps/mautic/cache/prod/classes.php:6705)"} []
[2016-07-11 02:05:05] mautic.ERROR: Error: Class 'Twig_Node_Expression_Test_Defined' not found - in file /opt/bitnami/apps/mautic/cache/prod/classes.php - at line 6705 [] []
[2016-07-11 02:05:12] mautic.WARNING: PHP Warning: include(/opt/bitnami/apps/mautic/htdocs/vendor/twig/twig/lib/Twig/Node/Expression/Test/Defined.php): failed to open stream: No such file or directory - in file /opt/bitnami/apps/mautic/htdocs/vendor/composer/ClassLoader.php - at line 412 [] []
[2016-07-11 02:05:12] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Twig_Node_Expression_Test_Defined" from the global namespace. Did you forget a "use" statement?" at /opt/bitnami/apps/mautic/cache/prod/classes.php line 6705 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Twig_Node_Expression_Test_Defined\" from the global namespace.\nDid you forget a \"use\" statement? at /opt/bitnami/apps/mautic/cache/prod/classes.php:6705)"} []
[2016-07-11 02:05:12] mautic.ERROR: Error: Class 'Twig_Node_Expression_Test_Defined' not found - in file /opt/bitnami/apps/mautic/cache/prod/classes.php - at line 6705 [] []
[2016-07-11 02:05:13] mautic.WARNING: PHP Warning: include(/opt/bitnami/apps/mautic/htdocs/vendor/twig/twig/lib/Twig/Node/Expression/Test/Defined.php): failed to open stream: No such file or directory - in file /opt/bitnami/apps/mautic/htdocs/vendor/composer/ClassLoader.php - at line 412 [] []
[2016-07-11 02:05:13] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Twig_Node_Expression_Test_Defined" from the global namespace. Did you forget a "use" statement?" at /opt/bitnami/apps/mautic/cache/prod/classes.php line 6705 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Twig_Node_Expression_Test_Defined\" from the global namespace.\nDid you forget a \"use\" statement? at /opt/bitnami/apps/mautic/cache/prod/classes.php:6705)"} []
[2016-07-11 02:05:13] mautic.ERROR: Error: Class 'Twig_Node_Expression_Test_Defined' not found - in file /opt/bitnami/apps/mautic/cache/prod/classes.php - at line 6705 [] []
[2016-07-11 02:05:45] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 02:06:06] mautic.WARNING: PHP Warning: include(/opt/bitnami/apps/mautic/htdocs/vendor/twig/twig/lib/Twig/Node/Expression/Test/Defined.php): failed to open stream: No such file or directory - in file /opt/bitnami/apps/mautic/htdocs/vendor/composer/ClassLoader.php - at line 412 [] []
[2016-07-11 02:06:07] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Twig_Node_Expression_Test_Defined" from the global namespace. Did you forget a "use" statement?" at /opt/bitnami/apps/mautic/cache/prod/classes.php line 6705 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Twig_Node_Expression_Test_Defined\" from the global namespace.\nDid you forget a \"use\" statement? at /opt/bitnami/apps/mautic/cache/prod/classes.php:6705)"} []
[2016-07-11 02:06:07] mautic.ERROR: Error: Class 'Twig_Node_Expression_Test_Defined' not found - in file /opt/bitnami/apps/mautic/cache/prod/classes.php - at line 6705 [] []
[2016-07-11 02:06:08] mautic.WARNING: PHP Warning: include(/opt/bitnami/apps/mautic/htdocs/vendor/twig/twig/lib/Twig/Node/Expression/Test/Defined.php): failed to open stream: No such file or directory - in file /opt/bitnami/apps/mautic/htdocs/vendor/composer/ClassLoader.php - at line 412 [] []
[2016-07-11 02:06:08] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Twig_Node_Expression_Test_Defined" from the global namespace. Did you forget a "use" statement?" at /opt/bitnami/apps/mautic/cache/prod/classes.php line 6705 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Twig_Node_Expression_Test_Defined\" from the global namespace.\nDid you forget a \"use\" statement? at /opt/bitnami/apps/mautic/cache/prod/classes.php:6705)"} []
[2016-07-11 02:06:08] mautic.ERROR: Error: Class 'Twig_Node_Expression_Test_Defined' not found - in file /opt/bitnami/apps/mautic/cache/prod/classes.php - at line 6705 [] []
[2016-07-11 02:06:13] mautic.WARNING: PHP Warning: include(/opt/bitnami/apps/mautic/htdocs/vendor/twig/twig/lib/Twig/Node/Expression/Test/Defined.php): failed to open stream: No such file or directory - in file /opt/bitnami/apps/mautic/htdocs/vendor/composer/ClassLoader.php - at line 412 [] []
[2016-07-11 02:06:13] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Twig_Node_Expression_Test_Defined" from the global namespace. Did you forget a "use" statement?" at /opt/bitnami/apps/mautic/cache/prod/classes.php line 6705 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Twig_Node_Expression_Test_Defined\" from the global namespace.\nDid you forget a \"use\" statement? at /opt/bitnami/apps/mautic/cache/prod/classes.php:6705)"} []
[2016-07-11 02:06:13] mautic.ERROR: Error: Class 'Twig_Node_Expression_Test_Defined' not found - in file /opt/bitnami/apps/mautic/cache/prod/classes.php - at line 6705 [] []
[2016-07-11 02:06:14] mautic.WARNING: PHP Warning: include(/opt/bitnami/apps/mautic/htdocs/vendor/twig/twig/lib/Twig/Node/Expression/Test/Defined.php): failed to open stream: No such file or directory - in file /opt/bitnami/apps/mautic/htdocs/vendor/composer/ClassLoader.php - at line 412 [] []
[2016-07-11 02:06:14] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Twig_Node_Expression_Test_Defined" from the global namespace. Did you forget a "use" statement?" at /opt/bitnami/apps/mautic/cache/prod/classes.php line 6705 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Twig_Node_Expression_Test_Defined\" from the global namespace.\nDid you forget a \"use\" statement? at /opt/bitnami/apps/mautic/cache/prod/classes.php:6705)"} []
[2016-07-11 02:06:14] mautic.ERROR: Error: Class 'Twig_Node_Expression_Test_Defined' not found - in file /opt/bitnami/apps/mautic/cache/prod/classes.php - at line 6705 [] []
[2016-07-11 02:24:50] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 02:34:07] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 02:39:29] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 02:49:56] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 03:10:17] mautic.WARNING: PHP Warning: include(/opt/bitnami/apps/mautic/htdocs/vendor/twig/twig/lib/Twig/Node/Expression/Test/Defined.php): failed to open stream: No such file or directory - in file /opt/bitnami/apps/mautic/htdocs/vendor/composer/ClassLoader.php - at line 412 [] []
[2016-07-11 03:10:17] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Twig_Node_Expression_Test_Defined" from the global namespace. Did you forget a "use" statement?" at /opt/bitnami/apps/mautic/cache/prod/classes.php line 6705 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Twig_Node_Expression_Test_Defined\" from the global namespace.\nDid you forget a \"use\" statement? at /opt/bitnami/apps/mautic/cache/prod/classes.php:6705)"} []
[2016-07-11 03:10:17] mautic.ERROR: Error: Class 'Twig_Node_Expression_Test_Defined' not found - in file /opt/bitnami/apps/mautic/cache/prod/classes.php - at line 6705 [] []
[2016-07-11 03:10:32] mautic.WARNING: PHP Warning: include(/opt/bitnami/apps/mautic/htdocs/vendor/twig/twig/lib/Twig/Node/Expression/Test/Defined.php): failed to open stream: No such file or directory - in file /opt/bitnami/apps/mautic/htdocs/vendor/composer/ClassLoader.php - at line 412 [] []
[2016-07-11 03:10:32] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Twig_Node_Expression_Test_Defined" from the global namespace. Did you forget a "use" statement?" at /opt/bitnami/apps/mautic/cache/prod/classes.php line 6705 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Twig_Node_Expression_Test_Defined\" from the global namespace.\nDid you forget a \"use\" statement? at /opt/bitnami/apps/mautic/cache/prod/classes.php:6705)"} []
[2016-07-11 03:10:32] mautic.ERROR: Error: Class 'Twig_Node_Expression_Test_Defined' not found - in file /opt/bitnami/apps/mautic/cache/prod/classes.php - at line 6705 [] []
[2016-07-11 03:10:39] mautic.WARNING: PHP Warning: include(/opt/bitnami/apps/mautic/htdocs/vendor/twig/twig/lib/Twig/Node/Expression/Test/Defined.php): failed to open stream: No such file or directory - in file /opt/bitnami/apps/mautic/htdocs/vendor/composer/ClassLoader.php - at line 412 [] []
[2016-07-11 03:10:39] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Twig_Node_Expression_Test_Defined" from the global namespace. Did you forget a "use" statement?" at /opt/bitnami/apps/mautic/cache/prod/classes.php line 6705 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Twig_Node_Expression_Test_Defined\" from the global namespace.\nDid you forget a \"use\" statement? at /opt/bitnami/apps/mautic/cache/prod/classes.php:6705)"} []
[2016-07-11 03:10:39] mautic.ERROR: Error: Class 'Twig_Node_Expression_Test_Defined' not found - in file /opt/bitnami/apps/mautic/cache/prod/classes.php - at line 6705 [] []
[2016-07-11 03:46:36] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 03:55:54] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 04:06:26] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 04:18:32] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 04:23:24] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 05:56:00] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 06:24:12] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 06:46:36] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 07:07:41] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 07:16:23] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 07:28:40] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 74 [] []
[2016-07-11 07:55:02] mautic.WARNING: PHP Warning: include(/opt/bitnami/apps/mautic/htdocs/vendor/twig/twig/lib/Twig/Node/Expression/Test/Defined.php): failed to open stream: No such file or directory - in file /opt/bitnami/apps/mautic/htdocs/vendor/composer/ClassLoader.php - at line 412 [] []
[2016-07-11 07:55:02] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Twig_Node_Expression_Test_Defined" from the global namespace. Did you forget a "use" statement?" at /opt/bitnami/apps/mautic/cache/prod/classes.php line 6705 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Twig_Node_Expression_Test_Defined\" from the global namespace.\nDid you forget a \"use\" statement? at /opt/bitnami/apps/mautic/cache/prod/classes.php:6705)"} []
[2016-07-11 07:55:02] mautic.ERROR: Error: Class 'Twig_Node_Expression_Test_Defined' not found - in file /opt/bitnami/apps/mautic/cache/prod/classes.php - at line 6705 [] []
[2016-07-11 07:57:28] mautic.WARNING: PHP Warning: include(/opt/bitnami/apps/mautic/htdocs/vendor/twig/twig/lib/Twig/Node/Expression/Test/Defined.php): failed to open stream: No such file or directory - in file /opt/bitnami/apps/mautic/htdocs/vendor/composer/ClassLoader.php - at line 412 [] []
[2016-07-11 07:57:28] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Twig_Node_Expression_Test_Defined" from the global namespace. Did you forget a "use" statement?" at /opt/bitnami/apps/mautic/cache/prod/classes.php line 6705 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Twig_Node_Expression_Test_Defined\" from the global namespace.\nDid you forget a \"use\" statement? at /opt/bitnami/apps/mautic/cache/prod/classes.php:6705)"} []
[2016-07-11 07:57:28] mautic.ERROR: Error: Class 'Twig_Node_Expression_Test_Defined' not found - in file /opt/bitnami/apps/mautic/cache/prod/classes.php - at line 6705 [] []
[2016-07-11 07:57:52] mautic.WARNING: PHP Warning: include(/opt/bitnami/apps/mautic/htdocs/vendor/twig/twig/lib/Twig/Node/Expression/Test/Defined.php): failed to open stream: No such file or directory - in file /opt/bitnami/apps/mautic/htdocs/vendor/composer/ClassLoader.php - at line 412 [] []
[2016-07-11 07:57:52] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "Twig_Node_Expression_Test_Defined" from the global namespace. Did you forget a "use" statement?" at /opt/bitnami/apps/mautic/cache/prod/classes.php line 6705 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"Twig_Node_Expression_Test_Defined\" from the global namespace.\nDid you forget a \"use\" statement? at /opt/bitnami/apps/mautic/cache/prod/classes.php:6705)"} []
[2016-07-11 07:57:52] mautic.ERROR: Error: Class 'Twig_Node_Expression_Test_Defined' not found - in file /opt/bitnami/apps/mautic/cache/prod/classes.php - at line 6705 [] []
`

**Comment by escopecz** [comment]
Oh yes, follow https://github.com/mautic/mautic/issues/1983 for more details on that issue.

**Comment by npracht** [comment]
Do you think https://github.com/mautic/mautic/issues/2001 is related?

**Comment by escopecz** [comment]
@npracht I'm not sure what's #2001 about to be honest.

**Pull request merged**
