### PR TITLE
Bugfix: Create email using API fails because of DEC filters

### PR DESCRIPTION
**Pull request by virlatinus**
| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Related user documentation PR URL | N/A
| Related developer documentation PR URL | N/A
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/pull/3719
| BC breaks? | N/A
| Deprecations? | N/A

#### Description:
This PR fixes an issue with https://github.com/mautic/mautic/pull/3719 that prevented emails created using the API to be created because of a constraint for filters being empty.

#### Steps to reproduce the bug:
1. Apply https://github.com/mautic/mautic/pull/3719
2. Try to create an email using the API.
3. An API error will be returned: "filter: A value is required" 

#### Steps to test this PR: 
1. Apply this PR (it already includes the files from #3719)
2. Try to create an email using the API.
3. The error for the filter being empty will be gone and the email will be created.

### CODE REVIEW

**Comment by escopecz** [comment]
Most of the PHP API library tests for Emails fails with this PR:
```
$ phpunit --filter test tests/Api/EmailsTest.php
PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

.FFFFFFFF.                                                        10 / 10 (100%)

Time: 21.84 seconds, Memory: 40.00MB

There were 8 failures:

1) Mautic\Tests\Api\EmailsTest::testGetListOfSpecificIds
PHP Notice - Undefined index: display
Failed asserting that false is true.

/Users/jan/dev/mautic-api/tests/Api/MauticApiTestCase.php:89
/Users/jan/dev/mautic-api/tests/Api/MauticApiTestCase.php:154
/Users/jan/dev/mautic-api/tests/Api/EmailsTest.php:111

2) Mautic\Tests\Api\EmailsTest::testCreateGetAndDelete
PHP Notice - Undefined index: display
Failed asserting that false is true.

/Users/jan/dev/mautic-api/tests/Api/MauticApiTestCase.php:89
/Users/jan/dev/mautic-api/tests/Api/MauticApiTestCase.php:99
/Users/jan/dev/mautic-api/tests/Api/EmailsTest.php:121

3) Mautic\Tests\Api\EmailsTest::testEditPatch
PHP Notice - Undefined index: display
Failed asserting that false is true.

/Users/jan/dev/mautic-api/tests/Api/MauticApiTestCase.php:89
/Users/jan/dev/mautic-api/tests/Api/EmailsTest.php:146

4) Mautic\Tests\Api\EmailsTest::testEditPut
PHP Notice - Undefined index: display
Failed asserting that false is true.

/Users/jan/dev/mautic-api/tests/Api/MauticApiTestCase.php:89
/Users/jan/dev/mautic-api/tests/Api/EmailsTest.php:175

5) Mautic\Tests\Api\EmailsTest::testSendToSegment
PHP Notice - Undefined index: display
Failed asserting that false is true.

/Users/jan/dev/mautic-api/tests/Api/MauticApiTestCase.php:89
/Users/jan/dev/mautic-api/tests/Api/EmailsTest.php:213

6) Mautic\Tests\Api\EmailsTest::testSendToContact
PHP Notice - Undefined index: display
Failed asserting that false is true.

/Users/jan/dev/mautic-api/tests/Api/MauticApiTestCase.php:89
/Users/jan/dev/mautic-api/tests/Api/EmailsTest.php:250

7) Mautic\Tests\Api\EmailsTest::testBatchEndpoints
PHP Notice - Undefined index: display
Failed asserting that false is true.

/Users/jan/dev/mautic-api/tests/Api/MauticApiTestCase.php:89
/Users/jan/dev/mautic-api/tests/Api/MauticApiTestCase.php:99
/Users/jan/dev/mautic-api/tests/Api/MauticApiTestCase.php:240
/Users/jan/dev/mautic-api/tests/Api/EmailsTest.php:272

8) Mautic\Tests\Api\EmailsTest::testBCEndpoints
PHP Notice - Undefined index: display
Failed asserting that false is true.

/Users/jan/dev/mautic-api/tests/Api/MauticApiTestCase.php:89
/Users/jan/dev/mautic-api/tests/Api/EmailsTest.php:250
/Users/jan/dev/mautic-api/tests/Api/EmailsTest.php:278

FAILURES!
Tests: 10, Assertions: 29, Failures: 8.
```

**Comment by escopecz** [comment]
BTW it works on mautic staging:
```
$ phpunit --filter test tests/Api/EmailsTest.php
PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

..........                                                        10 / 10 (100%)

Time: 1.3 minutes, Memory: 16.00MB

OK (10 tests, 218 assertions)
```

**Comment by dongilbert** [comment]
I resolved the conflicts, and got the same test results as @escopecz

**Comment by virlatinus** [comment]
This will need to be approached a different way. This fix breaks unit tests

**Pull request closed without merging**
