### PR TITLE
Add created by to report and segments

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
We need use **created by** on leads in segment filters and in contacts reports.  This PR added select field with users 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create contact
3. Create segment with filter Created By user who create contact
4. Rebuild segment
5. You should see created contact in segment
6. Create contacts report
7. Add column Created By
8. Use created by in filter and filter by user who create contact
9. Check report
10. You should see your contact  there

### CODE REVIEW

**Comment by RCheesley** [comment]
Hi there!

I have just tested this in dev mode, and when the PR is applied and I create a contact (both with quick add and the full form) and then set up the segment as explained, they are not added to the segment on rebuild.

Here are the segment settings:

screenshot-mautic4 ddev site-2021 07 02-19_35_36

Also tested the report and nothing is appearing.

screenshot-mautic4 ddev site-2021 07 02-19_38_12

**Comment by kuzmany** [comment]
@RCheesley looks like M4 does not add create by.  You can check it in DB. In M3 working, because we've already use it in production.
I will try look on it.

**Comment by RCheesley** [comment]
OK great, thanks @kuzmany :)

**Comment by npracht** [comment]
I add the `regression` tag as far as it would be good that someone add to this PR the fact of re-introducing the creator (created_by) value on contacts, which seems missing in M4.

**Comment by RCheesley** [comment]
Conflicts to address and needs rebasing.

**Comment by RCheesley** [comment]
Taking this off the OSF board until it's rebased.

**Comment by kuzmany** [comment]
Close favor to M5 version https://github.com/mautic/mautic/pull/12815

**Pull request closed without merging**
