### PR TITLE
Update filemanager

### PR DESCRIPTION
**Pull request by anton-vlasenko**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | Y
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | https://github.com/helios-ag/FMElfinderBundle
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/8259
| BC breaks? | The old filemanager is removed.
| Deprecations? | The old filemanager is removed. 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Mautic's filemanager is EOL and the replacement doesn't look very active.

We could use something like https://github.com/helios-ag/FMElfinderBundle which uses Elfinder.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Go to the filemanager and try to use it. It should be working.

#### List deprecations along with the new alternative:
1. The old filemanager has been removed.
2.  All the related jQuery plugins needed for the old filemanager have aslo been removed.

#### List backwards compatibility breaks:
1. The old filemanager has been removed.

### CODE REVIEW

**Review by hluchas — CHANGES_REQUESTED** [review]
Problems
1. Uploaded files can't have UTF-8 chars in filename
2. When I click to existing or uploaded image, preview fails (on http://mautic-fork.local/index.php/media/images/apple-touch-icon.png?_t=1572604169 url example) with 404 HTTP code, download works, get info works
3. How can I create forder?

**Comment by anton-vlasenko** [comment]
@hluchas 
1. Fixed in https://github.com/mautic/mautic/pull/8306/commits/0c12df33ecfa1367fe4804dc400309894044f8c4
2. Fixed in https://github.com/mautic/mautic/pull/8306/commits/983e4e1f2d9051a372b060d4bec8e71581b81ea0
3. You can create a folder if you right-click on any empty space inside the folder and choose appropriate menu item.
Also, there are icons at the top of the page. You can create a new folder there as well.

**Review by hluchas — APPROVED** [review]
👍 good work. TY!

**Comment by dongilbert** [comment]
Drag and drop upload in the WYSIWYG is not working from what I can tell @anton-vlasenko

**Comment by anton-vlasenko** [comment]
@dongilbert I reproduced it yesterday, but I can't reproduce it today.
I don't know why. Can we just close it?

**Comment by dongilbert** [comment]
I'll check again

**Comment by dongilbert** [comment]
Drag and drop in Landing Pages & Emails is working now. Maybe it was a caching issue before?

**Review by dongilbert — APPROVED** [review]

**Pull request merged**
