### PR TITLE
[type-declarations] Re-run rector rules on plugins, Report, Sms, User, Lead, Dynamic, Config bundles

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Good to go :+1:

**Comment by escopecz** [comment]
Quite a lot of conflicts here. Will it be faster to re-run Rector? I can see you had to do some manual fixes after that.

**Comment by TomasVotruba** [comment]
Good to go :+1:

**Review by escopecz — APPROVED** [review]
No issue spotted 👍 Thanks!

**Pull request merged**
