### PR TITLE
Batch support for lead lists, campaigns, and unsubscribe status

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**
This PR adds support to mass/batch change lead's campaigns, lists, and add them to the unsubscribe list.

It also relaxes the sleep times for batch processing with building lists, executing events, etc to improve scalability.

**Testing**
After applying the PR, clearing the cache and updating schema (one new column added), go to the lead list, select some leads and add/remove them from lists, campaigns, and the unsubscribe status.  Currently it not possible to batch remove from the unsubscribe list but can on individual lead pages.

### CODE REVIEW

**Comment by escopecz** [comment]
I guess this is not problem of this PR, but I get this error on schema update command:
```                                                                                 
  [Doctrine\DBAL\DBALException]                                                                           
  An exception occurred while executing 'CREATE UNIQUE INDEX mau_unique_bundle ON mau_plugins (bundle)':  
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "mau_unique_bundle" already exists    
```
Is this problem of my local install or can you replicate it on yours Mautics with Postgres DB?

**Comment by dbhurley** [comment]
This works just fine but I think these buttons are getting excessive:
http://drop.dbh.li/image/1Y0G130F213g

I believe a better solution will be a dropdown for group actions: delete, campaigns, lists, dnc with accompanying text and placed in the top menu row... quick add,new import, and if a checkbox (or more) is checked then a group button dropdown displays in this top location. 

This means the secondary menu bar has only live-toggle, anon-toggle, card-toggle

**Comment by dbhurley** [comment]
Vote +1

**Comment by escopecz** [comment]
When I click on the *Batch edit of leads* campaigns' button, I get
```
500 Internal Server Error - [Semantical Error] line 0, col 37 near 'l.{campaign,': Error: 'l' is not defined.
```
```
vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php (line #63):
vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php (line #483): at Doctrine\ORM\Query\QueryException :: semanticalError ( 'line 0, col 37 near 'l.{campaign,': Error: 'l' is not defined.', object(QueryException) )
vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php (line #586): at Doctrine\ORM\Query\Parser -> semanticalError ( ''l' is not defined.', array('value' => 'l', 'type' => '100', 'position' => '37') )
vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php (line #272): at Doctrine\ORM\Query\Parser -> processDeferredIdentificationVariables ( )
vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php (line #351): at Doctrine\ORM\Query\Parser -> getAST ( )
vendor/doctrine/orm/lib/Doctrine/ORM/Query.php (line #255): at Doctrine\ORM\Query\Parser -> parse ( )
vendor/doctrine/orm/lib/Doctrine/ORM/Query.php (line #267): at Doctrine\ORM\Query -> _parse ( )
vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php (line #794): at Doctrine\ORM\Query -> _doExecute ( )
vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php (line #586): at Doctrine\ORM\AbstractQuery -> execute ( null, '2' )
app/bundles/CampaignBundle/Entity/CampaignRepository.php (line #116): at Doctrine\ORM\AbstractQuery -> getArrayResult ( )
app/bundles/CampaignBundle/Model/CampaignModel.php (line #590): at Mautic\CampaignBundle\Entity\CampaignRepository -> getPublishedCampaigns ( null, null, true )
app/bundles/LeadBundle/Controller/LeadController.php (line #1701): at Mautic\CampaignBundle\Model\CampaignModel -> getPublishedCampaigns ( true )
app/bundles/CoreBundle/Controller/CommonController.php (line #308): at Mautic\LeadBundle\Controller\LeadController -> batchCampaignsAction ( '0', '' )
at Mautic\CoreBundle\Controller\CommonController -> executeAction ( 'batchCampaigns', '0', '0', '' )
app/bootstrap.php.cache (line #3051): at call_user_func_array ( array(object(LeadController), 'executeAction'), array('batchCampaigns', '0', '0', '') )
app/bootstrap.php.cache (line #3013): at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '1' )
app/bootstrap.php.cache (line #3162): at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '1', true )
app/bootstrap.php.cache (line #2403): at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel -> handle ( object(Request), '1', true )
app/AppKernel.php (line #110): at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), '1', true )
index_dev.php (line #56): at AppKernel -> handle ( object(Request) )
```
Previous exception:
```
SELECT partial c.{id, name}, partial l.{campaign, lead, dateAdded, manuallyAdded, manuallyRemoved}, partial ll.{id} FROM MauticCampaignBundle:Campaign c INDEX BY c.id LEFT JOIN c.lists ll WHERE c.isPublished = :true AND (c.publishUp IS NULL OR c.publishUp <= :now) AND (c.publishDown IS NULL OR c.publishDown >= :now)
```

*Batch lead list edit* and *Batch do not contact* button works.

**Comment by alanhartless** [comment]
Does #819 fix this?

**Comment by escopecz** [comment]
Not sure. I'll try to checkout to this PR and merge it with staging if it helps

**Comment by escopecz** [comment]
Yes, that works. I vote :+1:

**Pull request merged**
