### PR TITLE
Gated video - support for iframe tag

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | https://github.com/mautic/mautic-documentation/pull/353
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

In Europe due to GDPR every visitor is able to disable any tracking script. If disable `mtc.js` then YouTube/Vimeo gated videos do not play, because by default gated video use video tag, what does not support external links. This PR add support for Iframe tag

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Add gated video for youtube/video to the page https://docs.mautic.org/en/gated-video without tracking code (`mtc.js`)
3. See like you re not able to play it
4. After PR you are able to play video and If you add tracking code, then it's converted to custom player with gated video support

### CODE REVIEW

**Comment by FabienneAivie** [comment]
I tried to test it and this error came up..after trying to add a gated video:
I tried to add the video via youtube, or should i test it another way..?
Bildschirmfoto 2023-03-03 um 11 27 06

**Comment by kuzmany** [comment]
@volha-pivavarchyk give me your example of code

**Comment by volha-pivavarchyk** [comment]
@kuzmany What do you mean? I don't seem to have written anything related to this code

**Comment by kuzmany** [comment]
@volha-pivavarchyk I suppose you are pasting the wrong youtube URL. For the video tag, we are using the URL like the docs recommend. But for iframe, we use standard iframe code that shares the function youtube provides.

**Comment by volha-pivavarchyk** [comment]
@kuzmany I suppose you mean @FabienneAivie. I'll tell her or test it myself today afternoon.

**Comment by kuzmany** [comment]
@FabienneAivie I suppose you are pasting the wrong youtube URL. For the video tag, we are using the URL like the docs recommend. But for iframe, we use standard iframe code that shares the function youtube provides. Can you send me your code?

**Comment by FabienneAivie** [comment]
@kuzmany - yes you were right, first i tried to embed the video with the code from the [gated video site](https://docs.mautic.org/en/gated-video) which did not work but with the iframe it works wonderful. 👍🏻 thanks for the help.

**Review by jos0405 — APPROVED** [review]
Yeah it works as described. Now the iframe tag also supports data-gate-time and form-id

image

**Review by escopecz — APPROVED** [review]

**Pull request merged**
