### PR TITLE
fix reference to incorrect template (lead grid display)

### LINKED ISSUE #12587: Unable to switch to card layout for Contacts
### Mautic Version

5.0.x series

### PHP version

8

### What browsers are you seeing the problem on?

Not relevant

### What happened?

You should be able to switch to card / grid layout using the keyboard shortcut 'c', but this is broken since the Twig refactor.

### How can we reproduce this issue?

Step 1: Go to contacts
Step 2: Press 'c'
Step 3: Note flash error message and log entry
Step 4: Note that you can't access contacts any more! Tip: Delete the session cookie and log in again to reset to table view!

### Relevant log output

```shell
[2023-07-26 14:56:56] mautic.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "@MauticLead/Lead/index.html.twig" (looked into: /var/www/html/app/bundles/LeadBundle/Resources/views)." at /var/www/html/app/bundles/LeadBundle/Resources/views/Lead/grid.html.twig line 19 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Unable to find template \"@MauticLead/Lead/index.html.twig\" (looked into: /var/www/html/app/bundles/LeadBundle/Resources/views). at /var/www/html/app/bundles/LeadBundle/Resources/views/Lead/grid.html.twig:19)"} {"hostname":"mautic-web","pid":2081}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #12587 

#### Description:

fixes incorrect reference of template when switching to card lay-out on contact overview page

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. see steps in #12587

### CODE REVIEW

**Review by RCheesley — CHANGES_REQUESTED** [review]
Works great - able to switch from card to list view!

When I switch back and forth from card to table view though, the following error shows in the console:

```
app.js?v749f06f9:52 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Mautic.generatePageTitle (app.js?v749f06f9:52:103)
    at Object.complete (app.js?v749f06f9:45:8)
    at fire (libraries.js?v749f06f9:280:231)
    at Object.fireWith (libraries.js?v749f06f9:286:181)
    at done (libraries.js?v749f06f9:699:18)
    at XMLHttpRequest.<anonymous> (libraries.js?v749f06f9:710:314)
```

**Comment by mollux** [comment]
@RCheesley that's another bug :)

just tested it, it's also present in 4.4.9, and looking at the code, it has been there for ages (well 6 years)

**Review by escopecz — APPROVED** [review]
👍

**Review by RCheesley — APPROVED** [review]
OK good to go - will raise as a separate bug if not already done!

**Comment by RCheesley** [comment]
https://github.com/mautic/mautic/issues/12604 for the other bug.

**Pull request merged**
