### PR TITLE
Segment membership as a new filter for dynamic web content

### PR DESCRIPTION
**Pull request by escopecz**
| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #2856
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Add ability to use segment filters in dynamic content.

#### Steps to test this PR:
0. Not needed in beta - Run ` dcp bin/console mautic:assets:generate` if you don't want to use dev local env.  
1. Create segment to match contact in step 5
2. Create dynamic content
    - `Is campaign based?` = NO
Snímek obrazovky 2020-10-29 v 12 31 39
    - then click filter in the top > select `Segment membership` 
    - use existing segment in which is created contact added
Snímek obrazovky 2020-10-29 v 12 31 50
3. Create dynamic content page in `Components > Landing pages`
    - Fill required info
    - Go to `Builder`
    - Drag `Dynamic content` into page content
    - Click on it
    - In right box select your dynamic content by name and use `test` as requested slot name
Snímek obrazovky 2020-10-29 v 12 36 43
    - Close builder and save
    - with url `https://yourmautic.coml/test` check landing page
    - You 'll see content from step 5
4. Create form with possibility to add contact `Components > Forms` 
    - mapped and required fields Firstname, Lastname, Email
5. Use this form in anonymous browser session 
    - with url `https://mautic-cloud.local/form/[ID]` to add contact with criteria matching created segment in step 1
    - keep this browser window open
    - open new tab with landing page from step 3
    - You'll see dynamic content defined in step 2

#### Other areas of Mautic that may be affected by the change:
1. `CustomObjectsBundle\EventListener\DynamicContentSubscriber::evaluateFilters()` is using `stopPropagation` method. This could eliminate further listeners from running if incorrect priority is set- https://github.com/mautic-inc/plugin-custom-objects/blob/b2ed6c064e3e256f2640fdb456bbf2cfb879300b/EventListener/DynamicContentSubscriber.php#L117

#### TODO
- [x] Frontend (form handling, js)
- [x] `PHP Notice - Array to string conversion``$choice` contains [] in 
```
/vendor/symfony/form/ChoiceList/ArrayChoiceList.php:68 at 
```
When saving form kwith operator `empty`/`not empty`. Selected value before is saved in the same way as in lead_list table
- [x] Landing pages are not working for me with DWC. John has no prob. Confirmed as working in my beta instance. Something wrong in my docker env. - ,Mistake in DC & landing page config
- [x] Implementation into landing pages
- [x] Unit tests
- [x] ~~Functional test for landing page~~ removed here https://github.com/mautic-inc/mautic-cloud/pull/1037/commits/86ac47c73891ee6561caccf4589949920b4e514a. HTTP requests from local are blocked in staging.

### CODE REVIEW

**Review by rohitp19 — APPROVED** [review]

**Review by rohitpavaskar — DISMISSED** [review]

**Review by RCheesley — CHANGES_REQUESTED** [review]
Testing this with sample data, when I search for a segment none are found:

screenshot-mautic ddev site-2024 04 19-15_35_21

**Comment by RCheesley** [comment]
I checked it on GitPod and I got something different - the ID rather than the name of the segment:

screenshot-8080-escopecz-mautic-mi0gs1eb5fq ws-eu110 gitpod io-2024 04 19-15_44_14

**Comment by escopecz** [comment]
Interesting. It works well for existing DWC but when creating one from scratch I also see this issue.

**Comment by escopecz** [comment]
It looks like it's not a bug in this PR but in general When loading the select type of filters when creating a DWC from scratch then all the values are switched with keys. See for example locale:
Screenshot 2024-04-22 at 10 52 26

**Comment by escopecz** [comment]
Wow, this was quite a long trip to fix it all. The select type fields were broken and not only in 1 place but 3. Each different type of select field on a different place. It originates from Mautic 3 refactoring where we had to swap all select keys with labels and this was broken ever since. It suggests something about the usage of these fields in DWC as no one noticed for years?

Some field choices are generated via jS. so I fixed it there. Others are generated via HTML templates so I fixed it there. A special case is for States which use index instead of the normal key. The rest of the template fields are using keys.

And then there are custom field selects, multiselects and booleans. Those were swapped twice on one place so I removed the additional swap. It seems that the code is used only for DWC, not for segments anymore so it shouldn't break anything else.

Field types to test:
- State
- Preferred Locale
- Preferred Timezone
- Segment Membership
- Custom selects, multiselects, boolean fields.

**Comment by RCheesley** [comment]
I reported the locale bug when it happened as we have had this issue since then in our download form on mautic.org/download. See https://github.com/mautic/mautic/issues/12851 :) Hurrah for fixing it finally!

**Comment by escopecz** [comment]
@RCheesley I'm not sure it will fix https://github.com/mautic/mautic/issues/12851 but it would be a nice side effect.

**Review by rohitp19 — APPROVED** [review]
LGTM. Thanks @escopecz

**Review by RCheesley — APPROVED** [review]
Thanks for fixing those issues @escopecz - checked and it's indeed working as expected for include and exclude on segment membership and the other things.

Sadly it doesn't fix https://github.com/mautic/mautic/issues/12851 in forms but I guess it's a very similar issue responsible!

**Pull request merged**
