### PR TITLE
Improve Campaign Trigger command Scheduled Events Queries

### PR DESCRIPTION
**Pull request by scottshipman**
⚠️ **REQUIRES PR 6247 (https://github.com/mautic/mautic/pull/6247) TO BE MERGED/APPLIED FIRST** ⚠️ 

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | N
| Automated tests included? | N
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
**REQUIRES PR 6247 (https://github.com/mautic/mautic/pull/6247)**

Campaigns with large ingestion (~100k + daily) create a bottlenecks when processing scheduled events. The existing query for GetScheduledCounts relied on joins and aggregations with large cardinality. This change hopes to mitigate that with no backwards breaking issues. Also avoids doing Counts if the command is run in --quiet mode (which should be the production use case to minimize log noise).

#### Steps to reproduce the bug:
1. 
2. 

#### Steps to test this PR:
1. push leads into a campaign that has a delayed event
2. run command mautic:campaign:trigger -i [x] where x is the affected campaign.
3. Check that any scheduled events ran correctly
4. repeat steps 1-3 with command mautic:campaign:trigger -i [x] --quiet

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Comment by alanhartless** [comment]
This needs a migration for the new index.

**Comment by npracht** [comment]
@scottshipman could you add the migration as requested by @alanhartless ?
Thanks !

**Comment by heathdutton** [comment]
Note, locally if I apply PR #6247 this *does* pass tests.

**Comment by alanhartless** [comment]
If this has a dependency on #6247, I'll move it to 2.16.

**Review by heathdutton — DISMISSED** [review]

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@scottshipman can you take a look at the conflict please?

**Comment by RCheesley** [comment]
Hi folks,

If this is still relevant for 3.x we could look to get this merged in 3.2 if we can get the conflict fixed, add the migration requested by @alanhartless [here](https://github.com/mautic/mautic/pull/6787#issuecomment-437909476), and have it tested by **Sunday, 15th November**.

Does that sound feasible?

**Comment by npracht** [comment]
I'll close this PR as far as there is no feedbacks about the owner. Don't take it wrong, part of it is our fault, we've been too long (on the Mautic Community Product Team side) to handle it at the time the PR has been offer.

If someone want to take it, i'll reopen it or they can create a new PR.

**Pull request closed without merging**
