### PR TITLE
Bug fix - Onesignal(Push Notification Service) : Server Name is not Defined for HTTP

### PR DESCRIPTION
**Pull request by heanfig**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? |  y
| New feature? | y
| Related user documentation PR URL | y
| Related developer documentation PR URL | y
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/3198
| BC breaks? | n
| Deprecations? | n 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

The problem
When I made a landing page in the landing page option of mautic and set the app id and the rest api key In the landing page you need the subdomain url (assuming my site does not have HTTPS) You need to add an option in the configuration where the subdomain name

The Solution
Add field "Subdomain name" in the web notification Pane of oneSignal

#### Steps to test this PR:
1. (Using Mautic for HTTP) Create Account for oneSignal and configure site works on HTTP 
2. Set field "Subdomain name" in the web notification Pane
3. Create Landing page
4. Preview or view 

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
https://github.com/mautic/mautic/issues/3198

### CODE REVIEW

**Comment by kuzmany** [comment]
I added support for non https sites in #3274 with more code.

**Comment by alanhartless** [comment]
@kuzmany @heanfig are both PRs addressing the same issue? If so, which should be used or is there anyway that one can be incorporated into the other so no work is lost?

**Comment by kuzmany** [comment]
@alanhartless my PR is more complex and not https sites support is just part of it.
OneSignal support https primary.
Non https sites are supported also, but visitor need confirm subscription in popup.
I create workround for non https sites and confirmation is not necessary (popup is close after very short settimeout).
Also my PR added tracking code to BuildJSSubscriber and recognition site protol (https/http).

**Comment by escopecz** [comment]
Closing this PR in favour of #3274

**Pull request closed without merging**
