### PR TITLE
Add possibility to extend the email form template (edit emails)

### PR DESCRIPTION
**Pull request by ChrisRAoW**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | features
| Bug fix?                               |no
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | not provided
| Related developer documentation PR URL | not provided
| Issue(s) addressed                     | not provided

I'm currently developing a plugin where I want to extend the email form template. I want to implement a new tab where i can insert additional settings to. These "hooks" give me te possibility to do so.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10401"></a>

### CODE REVIEW

**Review by kuzmany — DISMISSED** [review]
This looks good to me 👍 
Just probably need rebase to branch 4.0 based on our new branch strategy. 
@RCheesley Am I right??

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@kuzmany yes that's right, at present the 4.0 branch is equal with the 4.x/features so we should be OK to just change the branch, until we start merging PRs when the branches will diverge and it will need a rebase. I'm hoping to work through changing all the bases today.

**Comment by ChrisRAoW** [comment]
@RCheesley Do you want me something to do here?

**Comment by RCheesley** [comment]
@ChrisRAoW I think we are good - the CLA is a manual process and I was out on leave / others had not picked it up. I have now added you to the list and the bot is happy! Just needs another test I think, then we are good to go.

**Comment by ChrisRAoW** [comment]
@RCheesley Awesome! Thank yoU!

**Review by kuzmany — APPROVED** [review]

**Comment by jos0405** [comment]
Do we need a test here, or code review is enough?

**Comment by kuzmany** [comment]
@jos0405 do not need tests

**Comment by RCheesley** [comment]
Hi folks, this has the wrong milestone as it is a feature. Setting it to the correct milestone.

**Pull request merged**
