### PR TITLE
Fix gated video showing play button above form (Issue #9431)

### LINKED ISSUE #9431: Gated video showing play button above form
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I created an mp4 gated video following the instructions [here](https://docs.mautic.org/en/gated-video).  Everything worked well except after the form shows up and pauses the video, the play button for the video is on top of the form so the user can just press play and not fill out the form.

| Q   | A
| --- | ---
| Mautic version | 3.1.2
| PHP version | 7.2.24
| Browser | Chrome 86

### Steps to reproduce
1. Follow [these instructions](https://docs.mautic.org/en/gated-video) to include a gated video either on landing page or on any site that has mautic enabled.
2. Play the video until the form shows up and you'll see the play button clickable above the form.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by gabepri**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                |3.2
| Bug fix?                               | yes
| Issue(s) addressed                     | Fixes #9431

#### Description:

Gated video was not working correctly because the z-index of the play button was lower than that of the form. This PR addressed the issue but it didn't make the changes to the minified css file. I'm updating the minified css file here.

Originally created [this PR](https://github.com/mautic/mautic/pull/9436) but it was accidentally closed so recreating it here.

### CODE REVIEW

**Comment by npracht** [comment]
@gabepri can you please rebase against 3.2 branch please ?

**Comment by gabepri** [comment]
It's showing me my fork is already up-to-date with the 3.2 branch of Mautic.  Am I missing something?

**Comment by npracht** [comment]
Yes, the branch is not 3.2.
I changed it but it creates conflicts. I let you have a look at it.

Capture d’écran 2020-12-08 à 08 18 31

**Comment by npracht** [comment]
Thanks !

**Comment by npracht** [comment]
@escopecz is it normal to change the minified file when changing CSS ?

**Comment by escopecz** [comment]
I'm not sure about this css file. As I asked in the original PR, @dongilbert do you know?

**Comment by dongilbert** [comment]
The form is designed to overlay the play button so that the video stops and the form must be filled out prior to continuing the video.

**Comment by escopecz** [comment]
@dongilbert I think that is not the issue here. The change was made in `media/css/mediaelementplayer.min.css` but there is also `media/css/mediaelementplayer.css` available. In what file should the change be done? How is the minified version being build?

**Comment by gabepri** [comment]
To be clear, there were changes made years ago in `media/css/mediaelementplayer.css` and all I did was make the matching change in `media/css/mediaelementplayer.min.css`.  If there is a process to update the minified file, it hasn't been run in years.  Seems like a separate issue that should be addressed...

**Comment by gabepri** [comment]
@dongilbert @escopecz what's going on with this?

**Review by npracht — COMMENTED** [review]
👍 this works.. So i'd say let move fwd i agree with author.

**Pull request merged**
