### PR TITLE
Bug.email partial failures

### LINKED ISSUE #8802: Marketing Messages sent multiple times to the same contact
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Looks similar to https://github.com/mautic/mautic/pull/7733, but it happens with marketing messages.
We have a Marketing Message that is supposed to be sent to a contact two days after joining the campaign. For some reason it is sent over and over again to the same contact.
Our cron jobs are set as follows:
mautic:segments:update - every minute
mautic:campaigns:update - every 5 minutes
mautic:campaigns:trigger - every 10 minutes

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.0
| Browser | Chrome

### Steps to reproduce
1. Create a campaign that sends Marketing Message two days after contact joined the campaign
2. Schedule the message to be sent on Sunday,Monday,Tuesday,Wednesday,Thursday (not Weekdays)
 
### Log errors
No errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by alanhartless**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Y
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This adds support for 3rd party transports to partially fail a send that batches together multiple contacts (a tokenized transport for example). The transport would hydrate the failed emails in the `$failedRecipients` array then throw a `PartialEmailSendFailure` exception. The MailHelper will then not fail the entire message where it will delete contact stats resulting in duplicate sends for some contacts.  

[//]: # ( As applicable: )
#### Steps to test this PR:
1. Code review (no default transport in Mautic leverages this yet)

### CODE REVIEW

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
Another conflict to be resolved @alanhartless

**Comment by RCheesley** [comment]
Bumping to 3.1.1 (as I believe this to be a bug fix based on the description) due to unresolved conflicts.

**Comment by RCheesley** [comment]
@cla-bot check

**Review by kuzmany — APPROVED** [review]
Understand this PR and code looks good 👍 
Resolve conflicts need

**Comment by mabumusa1** [comment]
@RCheesley let's get this fixed today, the conflict is not relevant anymore because parts of the code are already in the staging branch

**Comment by RCheesley** [comment]
@cla-bot check

@mabumusa1 we need to get a code coverage report on this PR, I don't think we're able to do that on a protected branch unless @alanhartless @escopecz are able to do that as I think it's on a protected branch. If we can resolve the conflicts then we should be good to go.

**Comment by RCheesley** [comment]
@mautic/acquia-po this one also still has conflicts and needs to be rebased to trigger a code coverage report, so we are bumping to 3.1.2. Needs to be addressed by **18th October**.

**Review by escopecz — APPROVED** [review]

**Comment by npracht** [comment]
@escopecz there is a conflict to be solved first + alan is in your team. From what i understood we need 2 third party testers ?

**Comment by escopecz** [comment]
@npracht you are right. I will avoid PRs from my teammates. This PR needs just code review which I thought can provide.

The issue is that there is very little PRs in the 3.1.2 milestone that:
1. Are not failing CI tests.
2. Are not from my teammates.
3. Do not have the Pending feedback label.
4. I can test (for example I can't test SES integration without credentials)

Which means even if I would like to help I'm very limited.

**Comment by escopecz** [comment]
@RCheesley I'm 🤔  about the `essential` label. The PR description mentions:

> no default transport in Mautic leverages this yet

It doesn't look like this is essential as much as I'd like Alan's code to be merged as it will help with future email transports.

**Comment by npracht** [comment]
@escopecz on my side i'm okay with it ! more merged nicer it is.
**Can you at least have a look at the conflict ?**

I think there is an issue with Travis on the 3.1 branch, due to a CS problem. @dennisameling said he'll take a look asap.

**Review by kuzmany — APPROVED** [review]
Code looks good 👍

**Comment by escopecz** [comment]
@npracht I'm a bit worried that Travis failed. It looks like there was some problem on their end. But either way we should merge only PRs with green tests. Hunting failed test on 3.1 branch would be much harder than to wait till the tests will be green.

**Pull request merged**
