### PR TITLE
Lead edit : companies is lost

### PR DESCRIPTION
**Pull request by tchiotludo**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Related user documentation PR URL | N/A
| Related developer documentation PR URL | N/A
| Issues addressed (#s or URLs) | N/A
| BC breaks? | N
| Deprecations? | N

#### Description:
The companies is lost on edit form /s/contacts/edit/[-ID-]

#### Steps to reproduce the bug:
1. add a companies to a lead & save
2. edit once again the leads and see that the companies select is empty
3. if you save the form, the companies is removed from the lead

### CODE REVIEW

**Comment by escopecz** [comment]
Actually, I cannot replicate the issue. Are there any more steps to take? Special browser to use?

**Comment by tchiotludo** [comment]
I have the bug on chrome, but since this was a server side bug (the option
doesn't have the attribute selected), it must be because I'm on PHP 7
installation and there strict type on this version

Le 13 févr. 2017 8:23 PM, "John Linhart" <notifications@github.com> a
écrit :

**Comment by netinteractive** [comment]
I have same issue. It appears on PHP 5.6 and 7.0 on Firefox and Chrome. I upgrade Mautic from 2.5 to 2.6.

This : https://github.com/mautic/mautic/pull/3388/commits/20c01d3042fac362a7ab61c9f23ae194b172a4a3  not fixed problem. 

Steps : 
1. Create new lead, add there company
2. edit once again the leads and see that the companies select is empty
if you save the form, the companies is removed from the lead

Funny is that for some companies its working fine, but for some form is empty -  I check companies records in base but it looks same.

**Comment by mqueme** [comment]
I cannot replicate either

**Comment by tchiotludo** [comment]
Here is the live output of my current installation : 
```html
<select id="lead_companies" name="lead[companies][]" class="form-control lead.company-select" data-chosen-lookup="lead:getLookupChoiceList" data-model="lead.company" data-new-route="/s/companies/new" data-header="New Company" data-chosen-placeholder="Search options..." autocomplete="false"     multiple="multiple">
    <option value="new" >Create new...</option>
    <option value="1" >XXX café</option>
</select>   
```
The option "1" is not `selected` and the company is lost

Here is the docker image I used : https://hub.docker.com/r/nightech/mautic/

**Comment by escopecz** [comment]
@tchiotludo would you be able to test https://github.com/mautic/mautic/pull/3449? Or wait for 2.6.1 release and test with it. I think that PR should fix the issue.

**Comment by tchiotludo** [comment]
@escopecz : just tested
I pull the full upstream staging branch and this don't work.
My patch is still needed to be working as expected

**Comment by tchiotludo** [comment]
Just a precision that may help, I'm on mysqlnd and not pdo mysql

**Comment by alanhartless** [comment]
What PHP version are you using?

**Comment by tchiotludo** [comment]
```
$ php -v 
PHP 7.0.15 (cli) (built: Jan 24 2017 19:06:16) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by alanhartless** [comment]
I can't reproduce this either I'm afraid. And I'm not sure why the proposed fix would resolve anything. Could you give some back ground on how this fixes the issue you've experienced?

**Comment by tchiotludo** [comment]
vendor/symfony/form/Extension/Core/Type/ChoiceType.php Line 194 
```php
        if ($options['multiple']) {
/*+*/            if ($form->getName() === 'companies') {
/*+*/                dump($view->vars);
/*+*/                exit();
/*+*/            }

            $view->vars['is_selected'] = function ($choice, array $values) {
/*+*/                if ($form->getName() === 'companies') {
/*+*/                    var_dump($choice, $values);
/*+*/                }

                return in_array($choice, $values, true);
            };
```
will dump : 
```
  "choices" => array:2 [▼
    0 => ChoiceView {#7243 ▼
      +attr: []
      +label: "Create new..."
      +value: "new"
      +data: "new"
    }
    1 => ChoiceView {#7244 ▼
      +attr: []
      +label: "World Company"
      +value: "1"
      +data: 1
    }
  ]

string(3) "new"
array(1) {
  [1]=>
  int(1)
}

string(1) "1"
array(1) {
  [1]=>
  int(1)
}
```
The comparison is type sensitive and has you can see the the values is send as `string(1) "1"` so this can't work and the value is not selected (so the company is lost).
I haven't digg farest but I've the impression that the `"new"` value change the int type of the companies and failed to select it

**Comment by alanhartless** [comment]
Are you able to give us steps to help us reproduce this so we can trace it?

**Comment by tchiotludo** [comment]
You can run this docker image : https://github.com/nightech/docker-mautic following the README instruction.
Once the mautic is installed, just create a company and create a lead with this company.
When you edit the lead, you could see that the company is not selected anymore, and saving the lead will remove the company from the lead.

**Comment by escopecz** [comment]
Since none of the core devs can replicate the issue, I'm pushing it out of 2.8.0 to discuss it more.

**Comment by mqueme** [comment]
Still not able to replicate

**Pull request merged**
