### PR TITLE
Close button in segments redirect to view controller

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Just improve close behavior in segments.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1.  Edit segment
2.  Save and close  
3. Close redirect to  list view of all segments, not to detail view expect
4. Edit segment and
5. Close
6. Close redirect to  list view of all segments, not to detail view as we expect

#### Steps to test this PR:
1.  Repeat all steps
2.  See if close button redirect to detail view in both cases

### CODE REVIEW

**Comment by kuzmany** [comment]
Label: Bug

**Comment by kuzmany** [comment]
Label: Enhancement

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by npracht** [comment]
@kuzmany i couldn't reproduce the issue. When i click on save and close i arrive on the view of the segment itself, not the segment list.

**Comment by kuzmany** [comment]
@npracht on last staging?

**Comment by npracht** [comment]
Released 2.13.0

N.

**Comment by kuzmany** [comment]
@npracht meh, save and close works for me. I bet It wasn't.
But this situation? Close http://youtu.be/AWNQYfozAc8?hd=1

**Comment by npracht** [comment]
For that situation I think it would be better that it comes back on the segment detail page then segments list.

N.

**Comment by npracht** [comment]
@escopecz you have been approving this PR. Any reason to do not consider it as candidate for 2.14?

**Pull request merged**
