### PR TITLE
Label support for contactfield token

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | no
| New feature/enhancement? (use the a.x branch)      | ✅ 
| Deprecations?                          | no
| BC breaks? (use the c.x branch)        | no
| Automated tests included?              | ✅ 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | no need
| Issue(s) addressed                     | 

#### Description:
This PR follow up https://github.com/mautic/mautic/pull/10623
Enable new modifier to contactfield token to display label of values for select and boolean type.  To display label we can use:

`{contactfield=select_alias|label}`

#### Steps to test this PR:

1. Load up [this PR](https://mautibox.com)
2. Create contact and company select and boolean  fields
3.  Create contact and set value to these fields
4. Create email and put tokens
Contact fields:

contact select field with value `{contactfield=select_alias}`
contact select field with label  `{contactfield=select_alias|label}`
contact bool field with value `{contactfield=bool_alias}`
contact bool  field with label  `{contactfield=bool_alias|label}`

Company fields:

company select field with value `{contactfield=company_select_alias}`
company select field with label  `{contactfield=company_select_alias|label}`
company bool field with value `{contactfield=company_bool_alias}`
company bool  field with label  `{contactfield=company_bool_alias|label}`

5. Send email and check If you receive values as you requested

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10626"></a>

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Hi, I tried to test this Enhancement by clicking on the button Open_in_Gitpod [ link: https://gitpod.io/#https://github.com/mautic/mautic/pull/10626 ].

Unfortunately Gitpod is in error at starting mautic and I do not have enough knowledge to understand/solve the error:

`sh-agent container is running: If you want to add authentication to the ssh-agent container, run 'ddev auth ssh' to enable your keys.`
`services.web.extra_hosts array items[0,1] must be unique`
**`Failed to start mautic: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-mautic docker-compose -f /workspace/mautic/.ddev/.ddev-docker-compose-full.yaml up --build -d', action='[up --build -d]', err='exit status 15', stdout='', stderr='services.web.extra_hosts array items[0,1] must be unique'`**

image

_Should I test another way?_
Greetings from Ionut

**Review by volha-pivavarchyk — APPROVED** [review]
Code looks good. 

Works well.
image

**Comment by volha-pivavarchyk** [comment]
@kuzmany Could you please rebase on v5 or create a new PR to v5. It's such a nice feature.

**Comment by kuzmany** [comment]
Close favor to https://github.com/mautic/mautic/pull/12620

**Comment by kuzmany** [comment]
@volha-pivavarchyk @escopecz I create new PR against 5.x branch https://github.com/mautic/mautic/pull/12620

**Pull request closed without merging**
