### PR TITLE
ownerfield tokens

### LINKED ISSUE #7964: Manual emails, {signature} token generates incorrect signature
The manual "Send a custom email to [contact email]" dialogue, as accessed via "Send Email" button in contact detail page does not respect the "Mailer is Owner" setting OR use the currently logged in user's signature when replacing the {signature} token. The signature used is always the "Default email signature" as defined at /s/config/edit

[Docs state](https://www.mautic.org/docs/en/emails/mailer_is_owner.html) "There is one exception where the contact owner's signature won't be used. When a user sends an email directly from a contact detail, the currently logged in user's signature will be used. It doesn't matter if the contact has another owner assigned or if it doesn't have an owner at all."

| Mautic version | 2.15.3
| PHP version | 7.2.10

### PR DESCRIPTION
**Pull request by kuzmany**
closes #7964 
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR is follow up to https://github.com/mautic/mautic/pull/7066 by @isleshocky77 

Reworked with better performance

Tokens
- `{ownerfield=firstname}`
- `{ownerfield=lastname}`
- `{ownerfield=email}`
- `{ownerfield=position}`
- `{ownerfield=signature}`

This PR also fixed tokens in Send custom email from contact profile. 
Now If you have enabled Mailer is owner and contact has owner, then owner data will be tokenized

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create email with tokens above
3. Create contact without owner and with owner
4. Try Send email from contact profile
5. Try send segment email
6. Try send campaign email

Check If owner's details are filled properly as you expected.

### CODE REVIEW

**Review by dsp76 — DISMISSED** [review]
I have it working in production in 2.15.3 since a while. Working without an issue so far.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by npracht** [comment]
@kuzmany does this PR need https://github.com/mautic/mautic/pull/7066 or you took the code from the previous PR and we can close it ?

**Comment by kuzmany** [comment]
No need that PR

**Comment by kuzmany** [comment]
Rebased

**Review by mabumusa1 — DISMISSED** [review]
I tried this commit, it is working and pretty useful

**Review by dennisameling — APPROVED** [review]
Just rebased, this should be RTC once the code coverage report is in 👍 

Needs documentation, will create an issue in the appropriate repo prior to merging this PR

**Comment by dennisameling** [comment]
cc @mautic/education-team https://github.com/mautic/mautic-documentation/issues/106

**Pull request merged**
