### PR TITLE
Typo fixed ('underfined' -> 'undefined')

### LINKED ISSUE #14133: Typo in the code that prevent adding files/images  Froalaeditor
### Mautic Series

5.1.x series

### Mautic installed version

5.1.1

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.2.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Since commit: ed9a9bef2809d0fdab1b93de38dd2d9138c8f190

There is a typo in the builder.js code, line 1368. This prevent file/images integration.

Should be : typeof FroalaEditorForFileManager !== 'undefined' not **underfined**

```
window.document.fileManagerInsertImageCallback = function(selector, url) {
    if (Mautic.isCodeMode()) {
        Mautic.insertTextAtCMCursor(url);
    } else {
HERE  ====>>>     if (typeof FroalaEditorForFileManager !== 'underfined') { <<<==== HERE
            if (typeof FroalaEditorForFileManagerCurrentImage !== 'undefined') {
                FroalaEditorForFileManager.image.insert(url, false, {}, FroalaEditorForFileManagerCurrentImage);
            } else {
                FroalaEditorForFileManager.image.insert(url);
            }
        } else {
            if (typeof FroalaEditorForFileManagerCurrentImage !== 'undefined') {
                mQuery(selector).froalaEditor('image.insert', url, false, {}, FroalaEditorForFileManagerCurrentImage);
            } else {
                mQuery(selector).froalaEditor('image.insert', url);
            }
        }
    }
};
```

### How can we reproduce this issue?

Try uploading image/files Froalaeditor from Elfinder, Ex: Dynamic content.

### Relevant log output

Capture d’écran, le 2024-09-20 à 13 45 59

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by TheMarvelFan**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #14133  

## Description
Fixed typo in app/bundles/CoreBundle/Assets/js/4.builder.js

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Try uploading image/files Froalaeditor from Elfinder, Ex: Dynamic content. It should now work correctly.

### CODE REVIEW

**Comment by RCheesley** [comment]
@all-contributors please add @TheMarvelFan for code.

Welcome to the community @TheMarvelFan - thanks for the PR! Should hopefully be a quick one to fix and merge! 🚀

**Comment by RaffyRod** [comment]
Hi, @RCheesley can you tell me in which part of the application can I find this: Froalaeditor from Elfinder? or send me the URL?

**Review by RaffyRod — APPROVED** [review]
Code typo was fix and LGTM : 
image

**Review by escopecz — APPROVED** [review]
Yes, this is correct. Thank you! 👍

**Pull request merged**
