### PR TITLE
Report filters like and notLike expression with wildcards by default

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
This just add the same behaviour like we use in segment filters and dynamics content filters. 
For like and notLike add wildcards If not exists

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create reports for contacts
3. Add filter to like or notLike wiht some strings what are you expect do you see in report
4. Without PR you don't see related results
5. After PR you see expected results

### CODE REVIEW

**Review by PatrickJenkner — APPROVED** [review]
Worked just as described when tested 👍

**Comment by escopecz** [comment]
I changed the target branch from 5.1 to 5.x as we are getting back to our classic branching strategy where 5.x will be for features and 5.0 for bug fixes.

**Review by nick-vanpraet — APPROVED** [review]
Looks good, works as expected.

**Comment by escopecz** [comment]
Isn't this a BC break? What will happen with the segment filters that already have the wildcard in them? Perhaps we should add a migration to remove them?

Then the question is also in performance. Someone can have filters like `abc%` which use indexes but you'll change it to `%abc%%` or if you add the migration to avoid BC breaks then it will become `%abc%` but that changes the logic and also indexes cannot be used anymore so it will degrade performance.

I'd rather not merge this PR and instead add a note to the UI that if the like or notlike filters are used, then they can use the wildcards.

**Comment by kuzmany** [comment]
@escopecz I don't see BC. If you use the percentage sign (%), it works as it did before. However, if you add a string without the percentage sign, "%string%" is automatically added. This functionality applies to both segment filters and dynamic content filters. Having consistent behavior everywhere would be better, rather than having inconsistency.

**Review by escopecz — APPROVED** [review]
I misread the code. You are right! Your code solves the BC break I described. In that case, I don't see an issue here 👍

**Pull request merged**
