### PR TITLE
Update redis-commander to a newer image

### PR DESCRIPTION
**Pull request by nox1134**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [X]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Mautic is currently using an old version of the redis-commander (https://hub.docker.com/r/rediscommander/redis-commander) which hasn't been updated since last 3 years. This image is vulnerable and also doesn't support multiple platforms (For eg. It doesn't support linux/arm64) due to which docker has to emulate the image for different platforms causing performance issues and containers to fail due to health check.
We should use an updated redis-commander (https://github.com/joeferner/redis-commander) image which is widely adopted in the community and offers multiple-platform support with frequent updates.
For more details regarding the issue: https://forum.mautic.org/t/setting-up-mautic-on-mac-m1-health-check-failing/31253

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Start the dev environment using `ddev start` and it will pull the updated redis-commander image.

### CODE REVIEW

**Comment by nox1134** [comment]
cc: @RCheesley 

Can you review the PR and please let me know if i opened the issue for the correct branch?

**Comment by RCheesley** [comment]
cc @mautic/core-team to discuss if we're OK with moving away from the unmaintained package. To be tested in Open Source Friday sprint.

**Review by RCheesley — APPROVED** [review]
From the localhost perspective with an M2 Mac this works great, I don't get the healthcheck warning any more and I'm able to access Redis Commander without a problem.

@kuzmany I think you've been the main driver adding Redis / Redis Commander to the DDEV image, any thoughts on this?

**Comment by escopecz** [comment]
This is probably unrelated as I get it on 5.x as well as on this PR, but any ideas how to resolve this?
```
jan ~/dev/mautic [pr/nox1134/13550] $ ddev stop
Project mautic is already stopped. 
Project mautic has been stopped. 
jan ~/dev/mautic [pr/nox1134/13550] $ ddev start
Starting mautic... 
failed to solve: process "/bin/sh -c apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::=\"--force-confold\" --no-install-recommends --no-install-suggests php8.2-imap" did not complete successfully: exit code: 100 
Failed to start mautic: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-mautic docker-compose -f /Users/jan/dev/mautic/.ddev/.ddev-docker-compose-full.yaml up --build -d', action='[up --build -d]', err='exit status 17', stdout='#1 [drud/ddev-dbserver-mariadb-10.3:v1.21.4-mautic-built internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.0s

#2 [drud/ddev-webserver:v1.21.4-mautic-built internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [drud/ddev-dbserver-mariadb-10.3:v1.21.4-mautic-built internal] load build definition from Dockerfile
#3 transferring dockerfile: 591B done
#3 DONE 0.0s

#4 [drud/ddev-dbserver-mariadb-10.3:v1.21.4-mautic-built internal] load metadata for docker.io/drud/ddev-dbserver-mariadb-10.3:v1.21.4
#4 DONE 0.0s

#5 [drud/ddev-dbserver-mariadb-10.3:v1.21.4-mautic-built 1/2] FROM docker.io/drud/ddev-dbserver-mariadb-10.3:v1.21.4
#5 DONE 0.0s

#6 [drud/ddev-dbserver-mariadb-10.3:v1.21.4-mautic-built 2/2] RUN (groupadd --gid 20 "jan" || groupadd "jan" || true) && (useradd  -l -m -s "/bin/bash" --gid "jan" --comment '' --uid 501 "jan" || useradd  -l -m -s "/bin/bash" --gid "jan" --comment '' "jan" || useradd  -l -m -s "/bin/bash" --gid "20" --comment '' "jan" || useradd -l -m -s "/bin/bash" --comment '' jan )
#6 CACHED

#7 [drud/ddev-dbserver-mariadb-10.3:v1.21.4-mautic-built] exporting to image
#7 exporting layers done
#7 writing image sha256:e9e6d93182d46663de2c25325151cf4bdbb15fdc4c3ecb5b77c4c562520a80dc done
#7 naming to docker.io/drud/ddev-dbserver-mariadb-10.3:v1.21.4-mautic-built done
#7 DONE 0.0s

#8 [drud/ddev-webserver:v1.21.4-mautic-built internal] load build definition from Dockerfile
#8 transferring dockerfile: 1.17kB done
#8 DONE 0.0s

#9 [drud/ddev-webserver:v1.21.4-mautic-built internal] load metadata for docker.io/drud/ddev-webserver:v1.21.4
#9 DONE 0.0s

#10 [drud/ddev-webserver:v1.21.4-mautic-built 1/5] FROM docker.io/drud/ddev-webserver:v1.21.4
#10 DONE 0.0s

#11 [drud/ddev-webserver:v1.21.4-mautic-built 2/5] RUN (groupadd --gid 20 "jan" || groupadd "jan" || true) && (useradd  -l -m -s "/bin/bash" --gid "jan" --comment '' --uid 501 "jan" || useradd  -l -m -s "/bin/bash" --gid "jan" --comment '' "jan" || useradd  -l -m -s "/bin/bash" --gid "20" --comment '' "jan" || useradd -l -m -s "/bin/bash" --comment '' jan )
#11 CACHED

#12 [drud/ddev-webserver:v1.21.4-mautic-built 3/5] RUN apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests php8.2-imap
#12 3.242 W: GPG error: https://packages.sury.org/php bullseye InRelease: The following signatures were invalid: EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
#12 3.242 E: The repository 'https://packages.sury.org/php bullseye InRelease' is not signed.
#12 ERROR: process "/bin/sh -c apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::=\"--force-confold\" --no-install-recommends --no-install-suggests php8.2-imap" did not complete successfully: exit code: 100
------
 > [drud/ddev-webserver:v1.21.4-mautic-built 3/5] RUN apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests php8.2-imap:
#12 3.242 W: GPG error: https://packages.sury.org/php bullseye InRelease: The following signatures were invalid: EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
#12 3.242 E: The repository 'https://packages.sury.org/php bullseye InRelease' is not signed.
------
', stderr='failed to solve: process "/bin/sh -c apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y -o Dpkg::Options::=\"--force-confold\" --no-install-recommends --no-install-suggests php8.2-imap" did not complete successfully: exit code: 100'
```

**Comment by RCheesley** [comment]
@escopecz I had that before and I had to delete the DDEV install with -O and rebuild it. On Gitpod I had to delete the image and restart it again. I don't know what causes it and it only seems to happen on some PRs.

As a side note, the officially supported DDEV add-on for Redis Commander: https://github.com/ddev/ddev-redis-commander uses this other repo, rather than the official, we should be OK?

**Comment by RCheesley** [comment]
@escopecz the cause of the issue is #13551 :)

**Review by escopecz — APPROVED** [review]
That was it! Outdated DDEV. It works after upgrade

**Pull request merged**
