### PR TITLE
Fixed issue where the tracking pixel for a custom HTML email was appended outside the closing body tag

### PR DESCRIPTION
**Pull request by alanhartless**

### CODE REVIEW

**Comment by escopecz** [comment]
I wanted to test this one, but the Custom HTML Message does not save. If I fill in a text to the textarea, hit the Apply button, the text is gone. I tested this on 2 different instances, but both are latest GH master versions. Am I the only one with this issue?

**Comment by alanhartless** [comment]
John I haven't hit this one. Was it tested against existing installs? If so, maybe try clearing your browsers cache. Also check to another browser if you can so we can narrow the issue down to browser or code.

**Comment by escopecz** [comment]
Ok, so it was me. More specifically Gammaraly Chrome extension.

But if I switch Grammaraly off and send the email, look at the source, I see this bellow the email header:
```
<html>
<head>
=09<title></title>
</head>
<body>
<p><strong>yuityu=
ity</strong></p>
</body>
</html>
```
The tracking image is not there.

**Comment by alanhartless** [comment]
Can you try adding a die statement or something before https://github.com/mautic/mautic/pull/122/files#diff-ca25c3d5ae42a898e6b89103a1acc8efR820 to see what the source is before sent through the mail service?

**Comment by escopecz** [comment]
The main problem was that I was testing it via 'Send Example' button which obviously doesn't insert the tracking code. It hit me when the die statement you suggested wasn't triggering. But if I send it to a lead, I get this email body:

```
<html>
<head>
=09<title></title>
</head>
<body>
<p><strong>yuityu=
ity</strong></p>
</body>
</html><img height=3D"1" width=3D"1" src=3D"ht=
tp://localhost/mautic-github/index_dev.php/email/54f9d71191838.gif" />
```
which is not good, right?

**Comment by escopecz** [comment]
Yes, this branch fix it:
```
<html>
<head>
=09<title></title>
</head>
<body>
<p>sdfasdf asdfsa=
df sadf</p>
<img height=3D"1" width=3D"1" src=3D"http://localhost/mautic-=
github/index_dev.php/email/54f9d9bc89565.gif" /></body>
</html>
```
We are good for merge

**Pull request merged**
