### PR TITLE
Option to change Region for Amazon SES #559

### PR DESCRIPTION
**Pull request by nithinga**
## Description

Feature to change region for Amazon SES done based on feature request in 

https://github.com/mautic/mautic/issues/559

## Steps to test

1. Apply the PR.

2. Clear Mautic cache.

3. Go to "Email Settings" in Mautic configuration.

4. Select "Amazon SES" option in "Service to send mail through" drop-down.

5. Apply the new setting "Amazon SES Host" along with the Amazon SES username and password. 

6. Do "Test connection" and "Send test email" to check if the connection is correct.

### CODE REVIEW

**Comment by escopecz** [comment]
I tested that the new options are there, but I don't want to give my credit card to Amazon just to test a PR. Anyway, I say :+1:

**Comment by mqueme** [comment]
Tested that options are there, could not test Test connection and Send test email options as I don't have an amazon SES account. But aside from that, looks good!

**Comment by jordan8037310** [comment]
I just dragged my feet through this mess and was finally able to get Amazon SES to work once I merged this pull request to my master from mautic/stage.

Some pro tips for those of you trying to set this up the first time:

* Make sure you confirm your domain and are verified
* Make sure you confirm your email address and verify that. Even setting up the SNS does not exclude you from verifying receipt of emails. I used a domain alias for my mautic subdomain on Google Apps, and forwarded that email to a group.
* IF THIS IS THE FIRST TIME USING SES, you have to request your account be approved for production mode. Honestly the most frustrating thing I've ever dealt with.

**Comment by jordan8037310** [comment]
I may have spoken too soon here. When the SES region is applied, the selection of the second or third option is *not* saved

**Comment by nithinga** [comment]
@jordan8037310 It is working in version 1.4.0.... I just tested it out, second or third option is getting saved. Please clear Mautic cache and test again.

**Comment by tachang** [comment]
Not entirely sure the region is being saved. I set us-west-2 but it goes back to us-east

**Comment by tachang** [comment]
```
[2017-02-06 07:47:13] mautic.ERROR: PHP Error: Call to undefined method setApiKey - in file /var/www/mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php - at line 291 [] []

```

**Pull request merged**
