### PR TITLE
wip docker build

### PR DESCRIPTION
**Pull request by jasonmccallister**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? |  N
| New feature? | N
| Automated tests included? | N
| Related user documentation PR URL |  
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Adds the ability to run via Docker on local machines, the Dockerfile provided can also be used to deploy to production.

#### Steps to test this PR:
1. `docker-compose up -d`
2. visit `localhost:8000`

### CODE REVIEW

**Comment by jasonmccallister** [comment]
Running into the following issue on the Docker build locally:

```
[2019-08-30 01:15:13] mautic.WARNING: PHP Warning - require(/var/www/html/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php): failed to open stream: No such file or directory - in file /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 {"className":"Mautic\\UserBundle\\Entity\\Role","classMetadata":"[object] (Doctrine\\ORM\\Mapping\\ClassMetadata: Doctrine\\ORM\\Mapping\\ClassMetadataInfo@000000007162954b000000002e4bb850)","proxyClassName":"Proxies\\__CG__\\Mautic\\UserBundle\\Entity\\Role","fileName":"/var/www/html/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php"} []
[2019-08-30 01:15:13] mautic.ERROR: PHP Notice: require(): Failed opening required '/var/www/html/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php' (include_path='/var/www/html/vendor/phpunit/phpunit-selenium:.:/usr/local/lib/php') - in file /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 [] []
[2019-08-30 01:15:13] mautic.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Notice: require(): Failed opening required '/var/www/html/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php' (include_path='/var/www/html/vendor/phpunit/phpunit-selenium:.:/usr/local/lib/php') - in file /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 [] []
[2019-08-30 01:15:13] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: require(): Failed opening required '/var/www/html/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php' (include_path='/var/www/html/vendor/phpunit/phpunit-selenium:.:/usr/local/lib/php')" at /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php line 209 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: require(): Failed opening required '/var/www/html/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php' (include_path='/var/www/html/vendor/phpunit/phpunit-selenium:.:/usr/local/lib/php') at /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php:209)"} []
[2019-08-30 01:17:52] mautic.WARNING: PHP Warning - require(/var/www/html/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php): failed to open stream: No such file or directory - in file /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 {"className":"Mautic\\UserBundle\\Entity\\Role","classMetadata":"[object] (Doctrine\\ORM\\Mapping\\ClassMetadata: Doctrine\\ORM\\Mapping\\ClassMetadataInfo@000000002302ec0d000000004061ef89)","proxyClassName":"Proxies\\__CG__\\Mautic\\UserBundle\\Entity\\Role","fileName":"/var/www/html/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php"} []
[2019-08-30 01:17:52] mautic.ERROR: PHP Notice: require(): Failed opening required '/var/www/html/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php' (include_path='/var/www/html/vendor/phpunit/phpunit-selenium:.:/usr/local/lib/php') - in file /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 [] []
[2019-08-30 01:17:52] mautic.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Notice: require(): Failed opening required '/var/www/html/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php' (include_path='/var/www/html/vendor/phpunit/phpunit-selenium:.:/usr/local/lib/php') - in file /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 [] []
[2019-08-30 01:17:52] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: require(): Failed opening required '/var/www/html/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php' (include_path='/var/www/html/vendor/phpunit/phpunit-selenium:.:/usr/local/lib/php')" at /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php line 209 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: require(): Failed opening required '/var/www/html/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php' (include_path='/var/www/html/vendor/phpunit/phpunit-selenium:.:/usr/local/lib/php') at /var/www/html/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php:209)"} []
```

**Comment by Woeler** [comment]
I like Docker, but does this belong in the main repository? Once in, it basically adds the responsibility of maintaining it to the core. Thoughts @alanhartless @escopecz @kuzmany

**Comment by jasonmccallister** [comment]
The purpose of shipping a Dockerfile in the main repo would be for quick setup locally but also the ability to ship. While we ship this in our specific projects, we also ship this in our boilerplate projects. 

This will make an image that is specific that project and it would be up to Mautic to publish that image on Docker Hub (which I would so not too).

Of course this is ultimately their call or it can be moved to an article on documentation.

**Comment by Woeler** [comment]
Thanks for the explanation!

**Pull request closed without merging**
