### PR TITLE
Update editors to display minimal buttons whenever possible.

### PR DESCRIPTION
**Pull request by dbhurley**
Please answer the following questions. 

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | N
| Related user documentation PR URL | N/A
| Related developer documentation PR URL | N/A
| Issues addressed (#s or URLs) | N/A
| BC breaks? | N
| Deprecations? | N

#### Description:
This pull request updates the various text editors to display minimal toolbar buttons whenever possible. 

#### Steps to test this PR:
1. Apply the PR
2. Rebuild assets if in production environment
3. Navigate throughout Mautic examining the various textarea editors. 
4. Verify Email and builder editors still have all appropriate buttons. 
5. *Check for edge case uses of textarea toolbar usage.*

### CODE REVIEW

**Comment by escopecz** [comment]
This is duplicate of https://github.com/mautic/mautic/pull/2032

**Comment by dbhurley** [comment]
Sorry I read that PR but didn't immediately see toolbars addressed. I'll properly test #2032 and close this PR if appropriate

**Comment by dbhurley** [comment]
Please merge #2032 prior to merging this PR.

**Comment by alanhartless** [comment]
Did as described. 👍 Be prepared for a conflict when #2032 is merged.

**Comment by dongilbert** [comment]
#2032 was merged first but this still has some conflicts.

**Pull request merged**
