### PR TITLE
Fix #13920 changed behavior send from hour introduced in 5.1

### LINKED ISSUE #13920: Segment change schedule works differently in 5.1 than 5.0.4 - different aproach to "Send from" hour.
### Mautic Version

5.1

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8,2

### What browsers are you seeing the problem on?

Not relevant

### What happened?

In 5.0.4 when I setup change segments in this way:
obraz
then if the campaign runs this step on Monday - changes fire up immediately. On other day than Monday - fire up closest Monday. As I expected.

But after upgrading Mautic to 5.1 this behavior changed, even the campaign ran this step on Monday, the segments change was planned to NEXT Monday instead of present Monday.

### How can we reproduce this issue?

Step 1: Setup segment's change this way:
obraz
Step 2: Run a campaign with this step on Monday

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by magician7**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (5.1)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (it brings back behavior from 5.0.4)        | 🔴🟢
| Automated tests included?              | 🔴
| Issue(s) addressed                     | Fixes #13920

## Description

Changes introduced in 5.1 (https://github.com/magician7/mautic/commit/894929c85743dd2728f1e274bc43683e40549b16) brakes the functionality of executing campaigns when set "Start from hour".
This push request brings this back to previous behavior. When you set Start from specific hour was in 5.1:
if it is earlier then it's planned for a specific hour and fired up correctly BUT
when it is later then it's scheduled for the selected hour BUT for NEXT day.

Now it works as before.

When it is earlier than it's planned for a specific hour and fired up correctly AND
when it is later, then it fires immediately.

### CODE REVIEW

**Comment by escopecz** [comment]
I'm afraid this PR contains more changes than expected. Can you please update the PR so it contains on the the change you are proposing?

**Comment by magician7** [comment]
> I'm afraid this PR contains more changes than expected. Can you please update the PR so it contains on the the change you are proposing?

Yes, now I can see that. This is my first pull request and I definitly made a mistake. My PR should modify only one file. Commit 51c71e2917cf25e8070ea01b11bc75cde1c82ee3.

I'll try to correct this. 

I'm open if you have suggestion how to do this. Next time will be better then ;-)

EDIT: Ok, now It's ok I suppose.

**Comment by escopecz** [comment]
I'm not sure what you did. But the best way to create a PR is to:
1. `git checkout 5.x` to get to the branch with the latest changes
2. `git pull` to make sure you have the latest changes
3. make the changes, commit, push

Now that you are in this state, I'd recommend to:
1. Make a backup of your branch just in case something goes wrong with `git checkout fix_13920-changed-behavior-send-from-hour` and `git checkout fix_13920-changed-behavior-send-from-hour-backup`
2. Go back to this branch with `git checkout fix_13920-changed-behavior-send-from-hour`
3. Reset to the latest 5.x branch with `git fetch upstream` I assume the mautic/mautic repository is called upstream on your local. Confirm that with `git remote -v` and update the name of the remote accordingly. Then perform the hard reset with `git reset --hard upstream/5.x` again, update the remote name if necessary.
4. Cherry-pick your commit with `git cherry-pick  51c71e2917cf25e8070ea01b11bc75cde1c82ee3`
5. Force-push with `git push --force`

But in order to accept these changes it will have to be covered by PHPUNIT tests. Ideally a functional test.

**Comment by magician7** [comment]
Thank you for your specific instructions.

In this commit, I only removed unnecessary code from one file which caused this problem.

**Comment by escopecz** [comment]
@rahuld-dev can you please look at this change as you are the original author (https://github.com/mautic/mautic/pull/13263)? Why was this code added?

**Comment by magician7** [comment]
What if @rahuld-dev doesn`t response? Any chance to approve this PR?

**Comment by rahuld-dev** [comment]
@magician7 Will check and update here...Thanks!

**Comment by magician7** [comment]
Ehm.., ehm... little reminder here ;-) @rahuld-dev

**Comment by kuzmany** [comment]
@rahuld-dev can we move with this task please?

**Comment by magician7** [comment]
Any progres?

**Comment by StudioMaX** [comment]
I encountered the same bug, only with xdebug I was able to understand why the event is moved forward every day for a day instead of triggering. The date changes are not reflected in the contact logs, which is the worst thing, and it is not visually noticeable that the campaigns are not actually sent out, but only scheduled - only the reports show that there are no sent emails from this campaign.
As mentioned, what helped us was simply changing the "Send from" value from "10:00" to "between hours" from "10:00" to "12:00".

I also didn't understand what problem the specified commit was trying to fix, and if no one has any ideas, I think it's easier to revert it until someone finds the root cause of the bug that the first author was trying to fix.

**Comment by escopecz** [comment]
I was checking what other changes we have in our fork that are waiting to be pushed and found this: https://github.com/mautic/mautic/pull/14289

Can you please test if it fixes this issue?

**Comment by StudioMaX** [comment]
@escopecz 
Tried to create a new campaign with similar properties - this patch didn't fix the problem. Manually changed the values ​​of `date_triggered` and `trigger_date` in `campaign_lead_event_log` to a month ago to make sure the time was in the past - did not help. After the campaign was triggered, the date in `trigger_date` is overwritten and just increases to tomorrow.

**Comment by escopecz** [comment]
I found out what's going on. Fixed in https://github.com/mautic/mautic/pull/14312. Closing this PR as that one isn't breaking other workflows and contains automated tests.

**Pull request closed without merging**
