### PR TITLE
[UX] Create tooltips for the "Script inside Head/Footer" labels

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

When we are creating a page, there is the option for you to place a script but there is no specification of how this script should be placed. If you place it without HTML tags, the code is printed on the page screen, this shouldn't happen.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Landing pages
3. Create a new
4. See the new tooltips on the right side of the screen

image

### CODE REVIEW

**Review by Mike-Dropsolid — CHANGES_REQUESTED** [review]
It makes sense to me that it should be between script tags but I it might not be the case for everyone. So good addition for sure.

Maybe it's even better to make it '<script> tags' instead of 'HTML script tags'.

**Review by LordRembo — CHANGES_REQUESTED** [review]
Agree with Mike here, calling it '<script>' tags makes it extra clear

**Comment by andersonjeccel** [comment]
@LordRembo @Mike-Dropsolid Tried to escape the <script> tag, but it gets hidden on the tooltip anyway. Do you know how to fix?

**Comment by LordRembo** [comment]
See my comment on PR #13440, you should be able to write the brackets as html entities.

**Review by RCheesley — CHANGES_REQUESTED** [review]
I think this is a good improvement but I have two suggestions:

1. As others have said, explicitly mention using the `<script>` tags so it's clear
2. Perhaps we should get into the habit of using active rather than passive voice in the same way we do with the docs? So something like: 'It is displayed' rather than 'It will be displayed'?

**Comment by code5rick** [comment]
As @andersonjeccel explained, it's somewhat tricky to write '<script>' in the .ini file since the '</>' doesn't get recognized and somehow disappears. One solution that worked, although not perfect, is by adding a very small space between the word 'style' and the '</>'; it then gets recognized and works. I referred to this solution here: https://github.com/mautic/mautic/pull/13440#issuecomment-1968774811

**Comment by andersonjeccel** [comment]
Hi @RCheesley, would you mind not merging things before the final changes? It makes it hard to work with the files and prevents me from amending commits. 😉

**Comment by RCheesley** [comment]
@andersonjeccel could you clarify what you mean by 'would you mind not merging things before the final changes'? I haven't merged anything?

**Comment by andersonjeccel** [comment]
@RCheesley Oh, here:

image

A lot of other commits appeared, git doesn't allow to amend a commit if there are others after my changes :) 

Then it looks like this and much more:

image

**Comment by RCheesley** [comment]
@andersonjeccel before a PR can be merged, and during testing, it must be up to date with the latest changes from the branch which it is based on. Otherwise people are potentially testing against outdated code.

This is a standard practice in keeping PRs up to date with the latest codebase (we have a button which allows us to update the branch by pulling in the latest changes), and it should not make any impact on your work. If you need to work on your branch, you just need to do a `git pull` to get the latest changes from the PR.

**Comment by RCheesley** [comment]
I think the test failure was due to something unrelated to this PR, hopefully the latest updates from 5.x will mean it passes the tests! 🚀

**Comment by Woeler** [comment]
Can you stop inviting me to review your pull requests? I have nothing to do with any of this, nor have I been active in this repository for the past 5 years.

**Comment by andersonjeccel** [comment]
> @andersonjeccel before a PR can be merged, and during testing, it must be up to date with the latest changes from the branch which it is based on. Otherwise people are potentially testing against outdated code.
> 
> This is a standard practice in keeping PRs up to date with the latest codebase (we have a button which allows us to update the branch by pulling in the latest changes), and it should not make any impact on your work. If you need to work on your branch, you just need to do a `git pull` to get the latest changes from the PR.

Thanks for explaining!

**Comment by andersonjeccel** [comment]
@RCheesley I think Woeler is added to organization, it might be useful to remove him

**Comment by RCheesley** [comment]
@Woeler sorry for this, we've had discussions with the UX team about not inviting inappropriate people to review PRs so this should not happen going forward.

**Comment by escopecz** [comment]
@andersonjeccel there are CS issues too

**Comment by andersonjeccel** [comment]
@escopecz fixed

**Review by escopecz — APPROVED** [review]
👍

**Pull request merged**
