### PR TITLE
Allow plugin create own deduplicate logic

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | y
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Common `mautic:contacts:deduplicate` already deduplicate contacts by unique fields from configurations. But sometimes we need custom check for duplications (for example based on firstname/lastname/phone). This PR added dispatcher to checkForDuplicateContacts method allow load duplicate contacts by plugin. 
This allow also create own command (for example `mautic:contacts:deduplicate:custom`) along with core one. 

#### Steps to test this PR:
1. Install and setup MauticCustomDeduplicateBundle https://github.com/mtcextendee/mautic-custom-deduplicate-bundle
2. Choose in plugins settings:
firstname, lastname, phone
and not empty email
3. Create two contacts without email but with same firstname, lastname, and phone.
4. Run `php app/console mautic:contacts:deduplicate:custom`
5. See If contacts were merged
6. Then create two contacts again
7. Go to Mautic > Contacts
8. Run Custom deduplicate from menu
image
9. Wait and then see If you have at least two notification in notification area (started, finished)
image
10. Check If contacts were merged

### CODE REVIEW

**Comment by dichvuhuuich** [comment]
Hi, I've install MauticCustomDeduplicateBundle in Mautic site 2.15.1 by steps:

Step 1: Upload MauticCustomDeduplicateBundle to plugin folder
Step 2: Clear cache folder
Step 3: Reload Mautic site, can not access, show error: "The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.
System administrators, check server logs for errors."

Server Error log is:

[07-Sep-2019 04:27:08 UTC] Symfony\Component\Debug\Exception\FatalThrowableError: Undefined class constant 'CHECK_FOR_DUPLICATE_CONTACTS_EVENT' - in file /home//mt/plugins/MauticCustomDeduplicateBundle/EventListener/CheckDeduplicateContactsListener.php - at line 48

**I try another way by change files but I can not find the last file app/bundles/LeadBundle/Tests/Deduplicate/ContactDeduperTest.php, please show me how to use this plugin**

image

**Comment by kuzmany** [comment]
@dichvuhuuich tha plugin reguire this pull requests https://github.com/mautic/mautic/pull/7502

Need apply pull request first

**Comment by dichvuhuuich** [comment]
> @dichvuhuuich tha plugin reguire this pull requests #7502
> 
> Need apply pull request first

Thank you, don't need change this file app/bundles/LeadBundle/Tests/Deduplicate/ContactDeduperTest.php, I can install plugin after change 5 files about. I work like a charm.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by elilogan** [comment]
This will be one of the most important evolutions in Mautic. When this is in place, Mautic can enrich contact data from multiple sources and merge them. I look forward to this.

**Comment by RCheesley** [comment]
@elilogan please do help to test the PR then - it looks like there are some conflicts for @kuzmany to resolve first though :)

**Comment by kuzmany** [comment]
@elilogan I am not sure what do you mean. I am using it with https://github.com/mtcextendee/mautic-custom-deduplicate-bundle what is just different logic to find same contacts in Mautic

**Comment by dennisameling** [comment]
Hi @kuzmany! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since this PR has conflicts now, could you please do a `git merge upstream/features` locally to resolve the conflicts? Thanks in advance!

**Comment by kuzmany** [comment]
Close favor to https://github.com/mautic/mautic/pull/9844

**Pull request closed without merging**
