### PR TITLE
Do not trigger assignment rules when updating a Lead

### PR DESCRIPTION
**Pull request by mqueme**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Salesforce applies assignment rules when a Lead is created or updated. This PR assignment rules are only triggered when a lead is created, but not when it's updated.
[//]: # ( As applicable: )

#### Steps to test this PR:
1. Create an assignment rule on Salesforce
2. Run the CLI to sync contacts from Mautic to SF.
3. If it's a new Contact it should create a Lead and trigger the assignment rule `php app/console mautic:integration:fetchleads --time-interval="2 minutes" --env dev --integration=Salesforce`
4. If a contact is being updated, it should not trigger the assignment rule.

### CODE REVIEW

**Comment by alanhartless** [comment]
I added support for the composite requests since they are sent as POST and thus not caught by the PATCH if statement.

**Comment by mqueme** [comment]
It was meant not to. Assignments rules should be trigger when creating new Leads.

**Comment by alanhartless** [comment]
Right but we POST and PATCH in composite.

**Comment by alanhartless** [comment]
https://github.com/mautic/mautic/pull/3978/files#diff-9b15b6be04482d6f57b012a98d72e58aR1639

**Comment by mqueme** [comment]
I see, it should only send false when patching. Thanks!

**Pull request merged**
