### PR TITLE
Identify contact from  tracking url by params

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/196
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | #2787
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
When contact come to page from channel we could identify it by url. 
Identify contact from contact id from ?ct=
Also added new configuration for Landing page

tracking

**Case study:**
Lead browse  webpage at home as identified contact.
When come to office, continue  on another workstation. 
If open newsletter on another workstation we can identify and merge both profiles.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Open browser and open page with tracking code. I
Identify contact by tracking code or form (email is enought). 
**Now contact is identified**
2. Open incognito browser and open same page with tracking code. 
**This contact is not identified** 
3. Send email to idendified contact with link to this page. 
Copy link from email and open  in incognito window. 
**Contact is not identified** even come from channel where we know lead ID in url.

#### Steps to test this PR:
1. Repeat Steps to reproduce the bug steps.
2. Last step will identify contact also incognito browser.  

Now we have merged history from identified browser and not identified browser which is using by same contact.

### CODE REVIEW

**Comment by kuzmany** [comment]
@alanhartless 
this PR allow track from multiple device after, it's game changer :)
You are able to track on desktop after form filling and on mobile after open from email. Both device will be tracked.
Another company, your competitor , use similar way how to track contact from different devices.  
They also have controller with redirect generator. This controller is similar like your assets and their customers are able to create redirect link and us it in non mautic campaigns (banners, rtb, retargeting...). 
Maybe you can consider add Links components to roadmap.

**Comment by escopecz** [comment]
I'm a bit confused with this change. Here is what I got from testing:
1. The contact fills in the form embedded to a landing page. 
2. The form will send an email with link back to the landing page.
3. I'll open an incognito window with the landing page. So far, I can see one fresh identified contact and one anonymous.
4. I'll open the trackable link in the incognito browser. The page hit was added to the **identified user**, not the anonymous as you wrote in the steps to reproduce.

The only problem I see here is that the anonymous contact was not merged to the identified. Is that what this PR should do?

I dumped what I get on the line of your change from `$queryFields` variable:
```
app/bundles/LeadBundle/Model/LeadModel.php:868:
array (size=2)
  'ct' => 
    array (size=5)
      'source' => 
        array (size=2)
          0 => string 'form' (length=4)
          1 => int 4
      'email' => int 1452
      'stat' => string '58e755eb36c75' (length=13)
      'lead' => int 4346
      'channel' => 
        array (size=1)
          'email' => int 1452
  'page_url' => string 'http://mautic.dev/index_dev.php/page-with-form' (length=46)
```
Now if I compare it with your condition:
```
if(!isset($queryFields['email']) && empty($queryFields['email']) && $lead && $email = $lead->getEmail()) {
```
The content of your condition was not executed, because the `$lead` is null, but it seems that `$queryFields['email']` will always be empty. Maybe you meant to use `$clickthrough['email']`?

Small note:
`empty($queryFields['email'])` will cover also `!isset($queryFields['email'])`, so it doesn't have to be there. And check the code styles manually. The pre-commit hook is not working correctly.

Uff, what a test for one simple condition :)

**Comment by mqueme** [comment]
The way I tested this:
First opened the link from my PC local home IP, created anonymous contact. I then changed that contact to be identified with my email address, sent myself the link through an email. Opened the email from my mobile phone, different IP address. clicked on the link from the email, it identified me. merged history, then I opened incognito window from my mobile phone, it again identified me, merged my history.  I this not the way it should work?  To me it seems to be working correctly.

**Comment by kuzmany** [comment]
@mqueme yes that's correct way ;)

**Comment by escopecz** [comment]
I wasn't clear on what I was testing. I tested firstly staging code and it was working as this PR describes it. Then I applied this PR, it worked the same way. I did not notice any difference. And as I posted before, I don't understand what the code does since it looks that it checks for wrong variables.

@mqueme Was your comment about testing staging or this PR?

**Comment by escopecz** [comment]
@kuzmany could you look at my previous comment where I was trying to debug the code and didn't make sense to me? I pushed this PR out of 2.8.0 so we could discuss it.

**Comment by mqueme** [comment]
@escopecz @kuzmany yes I tested this on staging before applying the PR.

**Comment by kuzmany** [comment]
@escopecz @mqueme I did John's steps to tests and works for me.
But anyway I updated PR and add new configuration to landing page - Identify visitor by tracking url (default enabled).

This PR simulate Tracking of custom parameters (https://mautic.org/docs/en/contacts/contact_monitoring.html). If we continue to websites and contact identifiy from URL has email, we add this email address to $queryFields['email'] which works same like when you sent email address  in tracking code.

**Comment by escopecz** [comment]
I was able to reproduce the issue. But this PR did not fix it when I applied it, cleared cache. It does not merge the anonymous contact with the identified contact from the email trackable link.

**Comment by kuzmany** [comment]
@escopecz I bet You have to set email as public updatable (i forgoted mention it, sorry)

**Comment by escopecz** [comment]
Yep, that was it. It works when I make the email field updatable. This will need some docs or add this info to the tooltip, please. When that's done, I'll approve this PR.

**Comment by escopecz** [comment]
Thanks! Looks good to me 👍

**Comment by kuzmany** [comment]
@escopecz docs added

**Comment by mqueme** [comment]
This worked for me as well now. thanks.

**Pull request merged**
