### PR TITLE
fix reordering issue in form action

### LINKED ISSUE #12591: Bug with ordering form actions
### Mautic Version

5.0.x series

### PHP version

8

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Weird behaviour when trying to change the order of form actions: 

https://watch.screencastify.com/v/UNzycbO0NjzgN7kDvkab

After the form is saved I can sometimes change the order, sometimes not. Seems a little flukey.

### How can we reproduce this issue?

Step 1: Add a form action to a form
Step 2: Add another form action
Step 3: Try to change the order of the form actions by dragging them

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dadarya0**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | Yes
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://github.com/mautic/mautic/issues/12591 

#### Description:
ordering form actions not working.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Add a form action to a form
3. Add multiple form action
4. Try to change the order of the form actions by dragging them, it should work

### CODE REVIEW

**Comment by escopecz** [comment]
I can't make the ordering work with this patch. Every time I save the form the actions are in the previous order.

**Comment by dadarya0** [comment]
> I can't make the ordering work with this patch. Every time I save the form the actions are in the previous order.

This is another issue, I was fixing issue which was described in screen recording attached in issue.

**Comment by escopecz** [comment]
I see. It's not jumping around like this anymore. But still, the issue is about the ordering not working. So shall we fix it in this PR or create another issue for it?

**Comment by dadarya0** [comment]
> I see. It's not jumping around like this anymore. But still, the issue is about the ordering not working. So shall we fix it in this PR or create another issue for it?

yes, we should fix that issue in other PR.

**Comment by escopecz** [comment]
Well, if we merge this it will get to the release notes and people will expect that the form action reordering works which won't be the case. Let's fix it completely. This fix won't help anyone. Or am I missing something?

**Comment by RCheesley** [comment]
Clearing the milestone as it seems there's still work to do here to fix the issue.

**Comment by laurielim** [comment]
Since this has been inactive, I went ahead and made a new [PR](https://github.com/mautic/mautic/pull/14213) (as I can't push to this branch). The new PR includes dadarya0's commit + the fix for reordering not being saved issue.

**Comment by escopecz** [comment]
Thanks @laurielim ! I'm closing this as a duplicate

**Pull request closed without merging**
