### PR TITLE
Update github actions to latest versions.

### PR DESCRIPTION
**Pull request by biozshock**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ x ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Remove deprecation warnings from github actions.

#### Steps to test this PR:
Open the "Actions" tab on github. Observe there are no deprecations on "Summary" tab.

### CODE REVIEW

**Comment by mollux** [comment]
@biozshock nice! I had the same idea to do so :)

strange thing however: https://github.com/mautic/mautic/actions/runs/7682012989 still shows deprecations for `actions/cache@v3`, even though you changed it to `actions/cache@v4`.
Any idea why?

**Review by mollux — APPROVED** [review]
Looks good, and the changes in the `tests.yml`, which are tested by the CI run on this PR, show that the changes in the other files will also work, as we can't directly test e.g. the `release.yml`.

**Review by kuzmany — APPROVED** [review]
👍

**Comment by biozshock** [comment]
> @biozshock nice! I had the same idea to do so :)
> 
> strange thing however: https://github.com/mautic/mautic/actions/runs/7682012989 still shows deprecations for `actions/cache@v3`, even though you changed it to `actions/cache@v4`. Any idea why?

No idea why the v3 is still in the output. Probably other tools use the older action and it raises the deprecation?

**Pull request merged**
