### PR TITLE
Sendgrid report send fix

### LINKED ISSUE #5493: Unable to sent scheduled Reports
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

Mautic sucessful schedule an report with mautic:reports:scheduler command, but this e-mail fail on mautic:emails:send

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.0
| PHP version | 7.0

### Steps to reproduce:
1.  Schedule an Report on Mautic 2.12.0
2. See Log File
 
### Log errors: 

[2017-12-26 11:35:04] mautic.NOTICE: Swift_IoException: Unable to open file for reading [/var/www/html/app/../media/files/temp/2017-12-21_Alunos-o-Curso-de-Elementor-Essencial.csv] (uncaught exception) at /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php line 144 while running console command `mautic:emails:send` [] []

### PR DESCRIPTION
**Pull request by escopecz**
closes https://github.com/mautic/mautic/issues/5493
⚠️ Achtung, achtung. This PR is based on https://github.com/mautic/mautic/pull/7432 so this can be merged only after that PR is.

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | Y
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/5493
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

Sendgrid API transport failed if the attachment file name was not set. This PR sets the file name.

Error:
```
Swift_TransportException: The attachment filename parameter is required. in app/bundles/EmailBundle/Swiftmailer/SendGrid/SendGridApiFacade.php:61
```
[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Configure Sendgrid - API email transport.
2. Go to the report list page, in the context menu of one report row select the "Export & Send" option.
3. Execute `app/console mautic:reports:scheduler` command to send the report.

- You'll see the error mentioned in the description.

#### Steps to test this PR:
1. Send the report again.

- It should not produce any error and the report should arrive to your inbox.

### CODE REVIEW

**Comment by RCheesley** [comment]
Tagging this for 2.16.1 as it's a bugfix for https://github.com/mautic/mautic/issues/5493 however it is dependent on [this PR](https://github.com/mautic/mautic/pull/7432) being merged which is a new feature - so we might want to slate it for 3.1 as a result. Open to discussion either way!

**Comment by RCheesley** [comment]
Actually reading up on semantic versioning and realised we can't do that so it will have to wait on the next feature release :(

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by npracht** [comment]
Hello @escopecz could you please test mautic 3.0.0-beta2 and tell me if the issue is still existing?
- If no, i'll tag this issue at `M2 only relevant`
- If yes, could you please rebase your branch against 3.x branch ?

Waiting for your feedback, i would very love to merge it in 3.0.1 if still relevant. Thanks !

**Comment by escopecz** [comment]
The commit from this PR was cherry-picked into https://github.com/mautic/mautic/pull/7432 so this can be closed.

**Pull request closed without merging**
