### PR TITLE
Remove font-size:0

### PR DESCRIPTION
**Pull request by moskoweb**
There is a font-size:0 error in Gmail, which ignores the CSS font-size, and applies the table one to everything.

| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging for features or enhancements / 3.0 for bug fixes 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | 
| BC breaks?                             | 
| Automated tests included?              | yes
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
There is a "font-size: 0" error in Gmail, which ignores the CSS font-size, and applies the table one to everything.

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for submitting this @moskoweb - can you please sign the Contributors Agreement linked in the message above?

I've seen this reported in the forums so I'll try to find the thread and link them up!

**Comment by moskoweb** [comment]
> Thanks for submitting this @moskoweb - can you please sign the Contributors Agreement linked in the message above?
> 
> I've seen this reported in the forums so I'll try to find the thread and link them up!

Hello, for me I already signed, but how do you even sign?

**Review by kuzmany — APPROVED** [review]
Looks good to me 👍

**Review by npracht — APPROVED** [review]
👍

**Comment by npracht** [comment]
@moskoweb you need to sign here https://na2.docusign.net/Member/PowerFormSigning.aspx?PowerFormId=63edd18a-f645-43d0-ab6b-cba70e5b1173&env=na2 with same email address as the one you use on GitHub :)

**Comment by RCheesley** [comment]
@cla-bot check

**Pull request merged**
