### PR TITLE
Web Push Notification update with new options and images/badge/icons upload 

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

[//]: # ( Required: )
#### Description:

Added new cool features to web notifications

- Setting the Icon, Image, Badge  https://documentation.onesignal.com/docs/web-push-notification-icons (badge not included - don't have api support)
- Customize action buttons https://documentation.onesignal.com/docs/action-buttons
- Time to live https://documentation.onesignal.com/docs/sending-notifications#section-time-to-live
- Priority - https://documentation.onesignal.com/reference#section-delivery 

How should it look:

new web notification mautic

#### Steps to test this PR:

**Test DB migration**:

1.  Apply PR and run `php bin/console doctrine:migrations:migrate`
2. Run  `php bin/console doctrine:schema:update --dump-sql` 
3. Works If nothing is to update in DB schema

**Test feature request**: 

4.  Setup OneSignal integration https://mautic.org/docs/en/notifications/index.html  and enable web push notification
5. Go to website with Mautic tracking code from Chrome and Firefox brower
6. Confirm notification 
7. Create new web push notification in Matutic, setup both action buttons and icon and image
8. Run campaign with send  web notification action
9. Works If you received  both type of notification
- Chrome https://documentation.onesignal.com/docs/web-push-notification-icons#section-image
- Firefox https://documentation.onesignal.com/docs/web-push-notification-icons#section-icon
10. Works if you see both action button in Chrome 
https://documentation.onesignal.com/docs/action-buttons

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11395"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
This looks awesome! Please can you rebase to the 5.x branch as that is where the next feature based release will be made. Also some PHPSTAN love needed. Thanks!

**Review by RCheesley — COMMENTED** [review]
I have failed at the first hurdle with this PR - when I run the doctrine migrations, it says there are none to update:

```
gitpod /workspace/mautic $ ddev exec bin/console doctrine:migrations:migrate
                                                         
                    Mautic Migrations                    
                                                        
WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)y
No migrations to execute.
```

Output from schema update dump:

```
gitpod /workspace/mautic $ ddev exec bin/console doctrine:schema:update --dump-sql

 The following SQL statements will be executed:

 * DROP INDEX IDX_1AE3441319EB6921 ON oauth2_user_client_xref
 * DROP INDEX IDX_6480052EF639F774 ON campaign_leadlist_xref
 * DROP INDEX IDX_3048A8B2F639F774 ON campaign_form_xref
 * DROP INDEX IDX_5995213DF639F774 ON campaign_leads
 * DROP INDEX IDX_2E24F01CA832C1C9 ON email_list_xref
 * DROP INDEX IDX_CA315778A832C1C9 ON email_assets_xref
 * CREATE INDEX title_search ON leads (title)
 * DROP INDEX IDX_9EED7E6655458D ON lead_ips_xref
 * DROP INDEX IDX_F2E51EB655458D ON lead_tags_xref
 * DROP INDEX IDX_F5F47C7CB9FC8874 ON lead_lists_leads
 * DROP INDEX IDX_F4190AB6979B1AD6 ON companies_leads
 * DROP INDEX IDX_473919EFEF1A9D84 ON push_notification_list_xref
 * DROP INDEX IDX_2F81A41DB42D874D ON channel_url_trackables
 * DROP INDEX IDX_6DF94A56C028CEA2 ON point_lead_action_log
 * DROP INDEX IDX_C2A3BDBA71F7E88B ON point_lead_event_log
 * DROP INDEX IDX_B032FC2EBD5C7E60 ON sms_message_list_xref
 * DROP INDEX IDX_A506AFBE2298D193 ON stage_lead_action_log
 * DROP INDEX IDX_45207A4A4CE1C902 ON monitoring_leads
```

**Comment by RCheesley** [comment]
@kuzmany we will need to rebase to consider this one, however I have not been able to test as I can't seem to get the migration to trigger. Any suggestions?

**Comment by RCheesley** [comment]
Removing this from the Open Source Friday testing list due to outstanding feedback.

**Comment by kuzmany** [comment]
We do not use it in production. At the moment close it, anybody can pick it up

**Pull request closed without merging**
