### PR TITLE
DPMMA-2600 Fix for Grapesjs-Mjml self-closing tag issue

### LINKED ISSUE #12549: Builder not showcasing the code correctly
### Mautic Version

5.0.x series

### PHP version

8.0.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

I'm experiencing an error with the GrapeJS builder in Mautic, specifically in the Email campaigns. This bug is related to version 5, and in parallel, I'm also using version 4.4.9 to confirm that it is indeed an error, and I can guarantee that it is.

I encountered this error initially because I'm creating an email theme in MJML for Mautic, and when testing it in version 5, I'm experiencing several errors that I didn't have in the previous version. Text elements and buttons were disappearing in version 5, while everything was perfectly normal in version 4. Since the theme I'm working on is somewhat complex, I decided to try something shorter to really determine if it's a bug or a coding error, despite having analyzed the errors multiple times and not detected any.

After testing, I believe that the `mjml-image` tag has some issues in the builder.

### How can we reproduce this issue?

Mautic 5/4
1: Go to Channels > Emails
2: Create new
3: Select "New template email"
4: Fill in a name for "Subject" and "Internal name"
5: Select the "Brienz" theme - because it uses MJML
6: Go to "Builder"
7: Click on the pencil icon that corresponds to "Edit code"
8: Delete all the code and paste it (from [https://mjml.io/try-it-live](https://mjml.io/try-it-live))
```
<mjml>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-image width="100px" src="https://mjml.io/assets/img/logo-small.png"></mj-image>
        <mj-divider border-color="#F45E43"></mj-divider>
        <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```
9: Result:
Mautic 4:
image
**Mautic 5**:
image

Save, and previewing the email on Mautic 4 and 5, is exacly the same:
image

-----------------------------------------

Upon investigating the bug on Mautic 5, I decided to remove parts of the code to identify what was causing the conflict. When I removed the image, I noticed that the hidden content immediately appeared.
```
<mjml>
  <mj-body>
	<mj-section>
	  <mj-column>
		<mj-divider border-color="#F45E43"/>
		<mj-text font-size="20px" color="#F45E43" font-family="helvetica">Hello World
		</mj-text>
	  </mj-column>
	</mj-section>
  </mj-body>
</mjml>
```
image

This was the error I was experiencing with my theme on version 5 when I had an image, text, and button together inside an `mj-column`.

----------

My custom theme on Mautic 4:
image
My custom theme on Mautic 5:
image

### Relevant log output

_No response_

### Code of Conduct

- [x] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ Y ]
| New feature/enhancement? (use the a.x branch)      | [ N ]
| Deprecations?                          | [ N ]
| BC breaks? (use the c.x branch)        | [ N ]
| Automated tests included?              | [ N ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #12549

#### Description:
This pull request resolves an issue where self-closing tags, like `<mj-image />` were causing rendering problems in Grapesjs-Mjml. Currently, the parser doesn't handle these tags properly, leading to incorrect output.

To tackle this, the PR temporarily disables the parsing of self-closing tags. Although it's not a complete fix, it ensures that code is properly generated unit a more robust solution is implemented in https://github.com/GrapesJS/mjml/issues/149.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Repeat the steps from this issue: https://github.com/mautic/mautic/issues/12549#issuecomment-1648270897

### CODE REVIEW

**Comment by code5rick** [comment]
Tested and fixed the issue!! 🥳
#12549

**Comment by patrykgruszka** [comment]
The problem may still occur when loading the mjml code with self-closed tags from the template. I'll look into this.

**Comment by patrykgruszka** [comment]
I've added a fix in case there are self-closing MJML tags used in template or in the code editor. They will be automatically converted to avoid this type of issue.

**Review by annamunk — APPROVED** [review]
The change works great, good job!

**Comment by markusVJH** [comment]
We are having issues with this bug as well, I have been testing this solution and it is working great. Awesome stuff @patrykgruszka 

I am new to the community and am wondering about the workflow, it seems that there is an approval already, but it is not merged. So can I review and merge this?

**Comment by patrykgruszka** [comment]
Thanks, @markusVJH! Now we need the approval of a reviewer from the Mautic core team. However, you can also leave your review in the "Files Changed" tab, as it's more visible than just a comment.

@annamunk, did your review include a code review as well?

**Review by markusVJH — APPROVED** [review]
Everything looks good to me as well. Solution is working :) Thank for the reply @patrykgruszka

**Comment by annamunk** [comment]
@patrykgruszka yes, the code looks good and works!

**Comment by patrykgruszka** [comment]
@escopecz is there a plan to roll out the 5.0.4 version, or should I rebase this on 5.x?

**Comment by escopecz** [comment]
At this moment we plan to release 5.1.0. But all the PRs we already merged to 5.0 will be merged to 5.x so they aren't missed. I can see this has 2 tests already so it's ready to merged. Do you want me to merge it to 5.0 or do you want to rebase to 5.x? It will be released as 5.1.0 anyway.

**Comment by patrykgruszka** [comment]
Let's merge it into 5.0 then, thanks!

**Review by kuzmany — APPROVED** [review]
Seems good to me. I made basic tests and it works

**Comment by RCheesley** [comment]
@all-contributors please add @markusVJH for review

**Comment by jordankittle** [comment]
Experiencing this bug

**Comment by MadlenF** [comment]
Hi @patrykgruszka , I tested the PR with Gitpod and had issues with dynamic content afterwards. 
I had added a dynamic content element to my email, left the builder, saved & closed the email. When re-opening the email and saving it again, the dynamic content would only show {dynamiccontent = "undefined"}
Bildschirmfoto 2024-04-05 um 14 58 00

@irfan-synerzip  helped me with a fix, should he open a new PR or what would be the best solution? /cc @escopecz

**Comment by patrykgruszka** [comment]
@MadlenF a new PR is needed as this has already been merged, thanks!

**Comment by LordRembo** [comment]
[I believe this PR fixes the issue too](https://github.com/mautic/grapesjs-preset-mautic/pull/52). It is in one of the Mautic dependencies, however, not in Mautic itself. ~~Not sure if there's another workaround you had in mind @irfan-synerzip @MadlenF ?~~ It doesn't conflict with the PR of @irfan-synerzip so I'm gonna leave my fix in the preset as well.

**Pull request merged**
