### PR TITLE
fix the responsiveness for columns in natives themes

### PR DESCRIPTION
**Pull request by guillaumedufour**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? |  X
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/5831
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

https://mautibox.com/5856

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. create landing page or email with one of the mautic native's theme.
2. make a 2 or 3 section in the builder
3. save and go to the preview.
4. change de the width from the window and see it's NOT responsive.

#### Steps to test this PR:
1. create landing page or email with one of the mautic native's theme.
2. make a 2 or 3 section in the builder
3. save and go to the preview.
4. change de the width from the window and see it's now responsive.

### CODE REVIEW

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Label: Ready to test

**Comment by khaoua** [comment]
tested and so far it is not working

**Comment by escopecz** [comment]
I can see the email responsive:
screen shot 2018-09-24 at 20 51 33

Can you share a screenshot of what are you fixing?

**Comment by heathdutton** [comment]
@guillaumedufour could you resolve the conflicts for us?

**Comment by guillaumedufour** [comment]
Sorry i'm not working for mautic for a couple of months

**Pull request closed without merging**
