### PR TITLE
[DPMMA-2108] Add UTM to Asset download

### PR DESCRIPTION
**Pull request by tomekkowalczyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ N ]
| New feature/enhancement? (use the a.x branch)      | [ Y ]
| Deprecations?                          | [ N ]
| BC breaks? (use the c.x branch)        | [ N ]
| Automated tests included?              | [ Y ] 
| Related user documentation PR URL      | https://github.com/mautic/user-documentation/pull/157
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

The functionality allows you to register UTM tags from asset links through GET parameters. UTM columns are added to the asset download table, where the data is retrieved.

These parameters can be read from the level of asset download reports.

URL:https://mautic.ddev.site/index_dev.php/asset/15:test?utm_source=test2&utm_medium=test3&utm_campaign=test6&utm_id=test1&utm_term=test4&utm_content=test4

image

Report Asset Downloads
image

### CODE REVIEW

**Comment by escopecz** [comment]
Please check the failing tests.

**Comment by tomekkowalczyk** [comment]
@escopecz 
We have error `1) Mautic\AssetBundle\Tests\Controller\PublicControllerFunctionalTest::testDownloadActionWithUTM
Error: Call to a member function getUtmSource() on null` but I run the tests locally and it passes
image

There is a migration in the changes, I don't know if it performs correctly.

**Comment by escopecz** [comment]
It may be conflicting with other tests. If you'd run all the Mautic tests on your local you should get the same error. Some test before this one is setting some constant or something similar that is disabling the asset tracking. It's PITA to find such tests. Try to use these PHPUNIT comments for your test method:
```php
/**
 * @runTestsInSeparateProcesses
 * @preserveGlobalState disabled
 */
```

**Comment by tomekkowalczyk** [comment]
@escopecz, @annamunk  could you do a CR?

**Review by escopecz — APPROVED** [review]
The code change is clean and tested. Thanks! 👍

**Comment by escopecz** [comment]
I have one request. This feature would be hidden to people unless documented. Please drop a note about this new feature in https://github.com/mautic/user-documentation/blob/main/docs/components/assets.rst

**Comment by tomekkowalczyk** [comment]
@escopecz I added https://github.com/mautic/user-documentation/pull/157

**Review by volha-pivavarchyk — APPROVED** [review]
Utm tags are added well to the report and database.
image

There are no steps to test. And I have only one problem. I didn't find the other way to add the UTM tags to url unless manually. If that's ok, works fine.

**Review by annamunk — APPROVED** [review]
UTM saving works and the code looks good 😄

**Comment by tomekkowalczyk** [comment]
> Utm tags are added well to the report and database. image
> 
> There are no steps to test. And I have only one problem. I didn't find the other way to add the UTM tags to url unless manually. If that's ok, works fine.

@volha-pivavarchyk Thanks for CR. UTM will be added manually.

**Comment by tomekkowalczyk** [comment]
@escopecz Can we merge the changes?

**Pull request merged**
