### PR TITLE
Minify CSS used for Gated Video

### PR DESCRIPTION
**Pull request by squeral**
| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | N
| Automated tests included? | N
| Related user documentation PR URL | N
| Related developer documentation PR URL | N
| Issues addressed (#s or URLs) | 
| BC breaks? | N
| Deprecations? | N

[//]: # ( Required: )
#### Steps to test this PR:
1. Include http(s)://yourmautic.com/mtc.js on your page
2. Look for a loaded CSS file http(s)://yourmautic.com/media/css/mediaelementplayer.min.css

### CODE REVIEW

**Comment by escopecz** [comment]
Good idea!

Although I don't see any description on how did you made the minified version? There must be a process on how to do that next time someone modifies the [raw version](https://github.com/mautic/mautic/blob/staging/media/css/mediaelementplayer.css).

There already is a command to compile production assets: `app/console mautic:assets:generate` [source code](https://github.com/mautic/mautic/blob/staging/app/bundles/CoreBundle/Command/GenerateProductionAssetsCommand.php) Do you think you could add the file there to minify automatically when this command runs?

**Comment by squeral** [comment]
Sorry, my knowledge of PHP is limited and I used https://github.com/fmarcia/UglifyCSS to minify the CSS. I can't see how to integrate it into your command.

**Pull request merged**
