### PR TITLE
[UI] Styling for HTML keyboard tags

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR styles kbd tags to look better.

| Before                                 | After
| -------------------------------------- | ---
|    image                                    |  image

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Type in your keyboard `Shift + ?` to open the keyboard shortcuts menu
3. See the style

### CODE REVIEW

**Review by Esthertests — APPROVED** [review]
This is a niceimprovement 
image
FROM THIS
image

**Comment by Esthertests** [comment]
> This is a niceimprovement image FROM THIS image

@andersonjeccel  I am using a mac for this test, do i still need to test on a windows?

**Comment by andersonjeccel** [comment]
@Esthertests It's the same for Mac and Windows users, so don't worry

Thanks for testing!

**Review by kuzmany — APPROVED** [review]
👍

**Review by RCheesley — APPROVED** [review]
SOOOO much better! Just waiting for the tests to pass then will get it merged! 🚀

**Pull request merged**
