### PR TITLE
Import validation

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR adds validation to required fields during the import process. Imports will fail to be created and notify the user that they must map all required fields before allowing them to create the import. It also validates that a file was selected and warns users that they are submitting the upload form without a file.

#### Steps to test this PR:
1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Make a required custom field
3. Import a CSV file without this required field - it not validate the mapping form.
3. With this PR the import form will fail to submit until you map all required fields.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10884"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
@npracht @kuzmany this is needed for open sourcing the custom objects plugin. Please test with priority.

**Review by kuzmany — CHANGES_REQUESTED** [review]
IfI click on import I receive this error 

` 500 Internal Server Error - Return value of Mautic\LeadBundle\Controller\ImportController::getModel() must be an instance of Mautic\LeadBundle\Model\ImportModel, instance of Mautic\CoreBundle\Model\NotificationModel returned `

Trace

```
/app/bundles/LeadBundle/Controller/ImportController.php:78 at
/app/bundles/CoreBundle/Controller/CommonController.php:612 at Mautic\LeadBundle\Controller\ImportController -> getModel ( 'core.notification' )
/app/bundles/CoreBundle/Controller/CommonController.php:394 at Mautic\CoreBundle\Controller\CommonController -> getNotificationContent ( )
/app/bundles/CoreBundle/Controller/CommonController.php:210 at Mautic\CoreBundle\Controller\CommonController -> ajaxAction ( array('viewParameters' => array('form' => object(FormView), 'objectName' => 'mautic.lead.leads', 'step' => '1', 'currentRoute' => '/index_dev.php/s/contacts/import/new', 'mauticContent' => 'leadImport'), 'contentTemplate' => 'MauticLeadBundle:Import:new.html.php', 'passthroughVars' => array('activeLink' => '#mautic_contact_index', 'mauticContent' => 'leadImport', 'route' => '/index_dev.php/s/contacts/import/new', 'step' => '1', 'progress' => object(Progress))) )
/app/bundles/LeadBundle/Controller/ImportController.php:518 at Mautic\CoreBundle\Controller\CommonController -> delegateView ( array('viewParameters' => array('form' => object(FormView), 'objectName' => 'mautic.lead.leads', 'step' => '1', 'currentRoute' => '/index_dev.php/s/contacts/import/new', 'mauticContent' => 'leadImport'), 'contentTemplate' => 'MauticLeadBundle:Import:new.html.php', 'passthroughVars' => array('activeLink' => '#mautic_contact_index', 'mauticContent' => 'leadImport', 'route' => '/index_dev.php/s/contacts/import/new', 'step' => '1', 'progress' => object(Progress))) )
/app/bundles/CoreBundle/Controller/CommonController.php:456 at Mautic\LeadBundle\Controller\ImportController -> newAction ( '0', '' )
```

**Review by kuzmany — CHANGES_REQUESTED** [review]
Does work with custom fields. But If I use firstname as required, then I am able to make import even If required field is empty.

**Comment by kuzmany** [comment]
@escopecz can you check it?

**Comment by escopecz** [comment]
Yes, it is on my todo list. The weird part is that I've created a functional test for phone (default) field and it works:

https://github.com/mautic/mautic/pull/10884/files#diff-da26d06d8c656891904ba0c945f78eec6c1d4c1df9f067a919a0f87d71e18da5R48

**Review by RCheesley — DISMISSED** [review]
This worked for me using the field of companyemail and not including Company Name - both fields are required.

What might cause a problem with the gitpod / ddev environments is that we're duplicating the custom fields for some reason with the d:f:l command, and I found that I had to set both the duplicated fields to required.

So maybe check if there is field duplication going on in your testing instances?

**Comment by escopecz** [comment]
@kuzmany can you retest with this in mind?

> So maybe check if there is field duplication going on in your testing instances?

**Review by kuzmany — DISMISSED** [review]
It works as expected 👍 
I thought it validate also import data and that means contacts without firstname should not be imported.
But this is validation on mapping import tab. 

image

**Comment by RCheesley** [comment]
Just to clarify, this is labelled as a bug, but assigned to the 4.3 release.  Is it a bugfix or an enhancement @escopecz ?

**Comment by escopecz** [comment]
@RCheesley I changed the label to `enhancement` as it is adding new validation.

**Pull request merged**
