### PR TITLE
Fix PHP Notice on show_php_version_warning_if_under

### LINKED ISSUE #9619: Users seeing log entries relating to PHP version since 3.2.5
## Bug Description

From Slack:

> Just tried the last update to 3.2.5 ... Now I have this notice in the error log, every time I log into Mautic:
> mautic.NOTICE: PHP Notice - Undefined index: show_php_version_warning_if_under - in file /var/www/htdocs/app/bundles/CoreBundle/Release/Metadata.php - at line 82 {"metadata":{"version":"3.0.0-beta2","stability":"beta","minimum_php_version":"7.2.21","maximum_php_version":"7.3.99","minimum_mautic_version":"3.0.0-alpha","announcement_url":""}} []

Users are on 7.3.x and 7.4.14 versions of PHP.

| Q   | A
| --- | ---
| Mautic version | 3.2.5
| PHP version | 7.3.x and 7.4.14
| Browser | N/A

### PR DESCRIPTION
**Pull request by dennisameling**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.2
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | Fixes #9619

#### Description:

We added `show_php_version_warning_if_under` in Mautic 3.2.5. However, the `mautic:update:find` action will also fetch previous releases from GitHub which don't have this key in their `app/release_metadata.json`, hence triggering PHP notices. This PR fixes that issue by first checking if `show_php_version_warning_if_under` exists in the metadata.

#### Steps to test this PR:
1. Load up this PR locally (you can't test this on Mautibox)
2. Run `bin/console mautic:update:find`. Before applying this PR, you'll likely see PHP notices:
```
dennis@mautic3-web:/var/www/html$ bin/console mautic:update:find
PHP Notice:  Undefined index: show_php_version_warning_if_under in /var/www/html/app/bundles/CoreBundle/Release/Metadata.php on line 82

Notice: Undefined index: show_php_version_warning_if_under in /var/www/html/app/bundles/CoreBundle/Release/Metadata.php on line 82
PHP Notice:  Undefined index: show_php_version_warning_if_under in /var/www/html/app/bundles/CoreBundle/Release/Metadata.php on line 82

Notice: Undefined index: show_php_version_warning_if_under in /var/www/html/app/bundles/CoreBundle/Release/Metadata.php on line 82
Great! You are running the current version of Mautic.
```

After applying this PR, the PHP Notices should be gone:

```
dennis@mautic3-web:/var/www/html$ bin/console mautic:update:find
Great! You are running the current version of Mautic.
```

### CODE REVIEW

**Review by RCheesley — DISMISSED** [review]
Had this issue when updating and the PR removed the warnings as described - also there was a +1 on Slack.

**Comment by RCheesley** [comment]
@dennisameling just double checking the base branch - is this getting merged into features for the 3.3 release? Or 3.2 branch?

**Comment by dennisameling** [comment]
@RCheesley do we want to do a hotfix release 3.2.6 or wait until 3.3.0 instead? It's "just" a PHP notice so it won't break stuff for users, but might be a minor annoyance for some. If we go for 3.3.0 then `features`  is the right branch indeed

**Comment by RCheesley** [comment]
I think that given it is only a notice we should be OK to wait for 3.3 unless there are objections - we can point folk at this as a workaround if they are bothered by it enough to want to fix it sooner.

**Comment by dennisameling** [comment]
Changed branch to features @RCheesley - should be good to go now 👍🏼

**Comment by RCheesley** [comment]
Awesome - just rebased to features then we should be good to go once all the tests are passing!

**Comment by mohit-rocks** [comment]
Looks good to me as well.
I've tested on local as well.
Adding screenshot for reference.
mohit_Mohits-MacBook-Pro___Experiments_mautic3

**Review by RCheesley — APPROVED** [review]

**Pull request merged**
