### PR TITLE
[UX] New default dashboard templates

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

This PR adds 2 new dashboard templates:
- Forms and Assets
- Landing pages

using related widgets in each.
The first aims to show submissions, related downloaded assets and identified contacts.
The second aims to show page visits, all contacts created (including anonymous) and a bit of assets.

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open the Dashboard, click on the page actions then Select pre-defined dashboard.
3. Check the list and test the 2 new ones.

### CODE REVIEW

**Review by LeonOltmanns — COMMENTED** [review]
@andersonjeccel I just tested and found two things:

1. Saving one of the newly added Templates doesnt actually change the dashboard. The page reloads but the old widgets stay and no new widget is being added.

2. 
image

I would change the names to include spacing instead of "_" and also add "Example" to the titles.

**Comment by andersonjeccel** [comment]
@oltmanns-leuchtfeuer Good catch, thanks for testing!

**Comment by andersonjeccel** [comment]
> [!WARNING]
> All Tier 1 PRs [need only 1 code review and 1 user testing](https://contribute.mautic.org/governance/code-governance#:~:text=Full%20testing%20and%20approval%20by%20at%20least%20one%20community%20member%20(could%20be%20the%20person%20doing%20the%20code%20review%2C%20but%20should%20not%20be%20from%20the%20same%20company/organisation%20as%20the%20person%20submitting%20the%20PR).) before able to merge. I'll update accordingly.

**Review by LordRembo — APPROVED** [review]
The code looks fine, it's just valid json.

**Review by Adedayo-Olaoluwa — CHANGES_REQUESTED** [review]
@andersonjeccel test failed.  Kindly review the feedback below.

1. Forms and Assets work as expected, with 14 widgets on display on the dashboard when previewed and saved, showing contact info.
2. Landing pages test failed, with 18 widgets on display when previewed and saved, showing page insights. It was found that the "Downloads in time" widget was duplicated (appeared twice as the 1st widget and 7th widget from top to bottom) which accounts for the 18 widgets displayed as opposed 17 widgets expected. 

Check the attached images below for more clarity.

Landing Page Dashboard Snapshot
Landing Page Dashboard View
Pre defined dashboard template view

**Comment by andersonjeccel** [comment]
Hi @Adedayo-Olaoluwa 

First of all, thanks for reviewing!

Some of the widgets had the same name, but their configuration was a bit different (for example, showing only new contacts that have email instead of contacts that we have IP address)

To improve that specific template, I removed some of the widgets and reordered to maybe become easier to understand
There will be 11 in total now

I'll appreciate if you could review again :)

Have a nice day!

**Review by Adedayo-Olaoluwa — APPROVED** [review]
Great work! @andersonjeccel 
I've tested the revised implementation and test passed. Here's a quick summary below;

- Forms and Assets displayed 14 widgets, previewed and saved successfully.
- Landing pages displayed 11 widgets, previewed and saved successfully.
- Latest data refresh info, Edit, and Remove are functional on the dashboard. 

Thank you for your contribution. Cheers!

**Pull request merged**
