### PR TITLE
Added support for redirect on unpublished landing pages

### PR DESCRIPTION
**Pull request by guestisp**
With this commit we add the support for redirect when a landing page become unpublished. It's possible to do a 301 permanent or a 302 temporary redirect.

How to test it:
- Create a landing page or pick up an existing one.
- Unpublish it.
- In the "Edit" section of the page, select the "Redirect type" (**301 permanent** or **302 temporary**). **None** won't handle any redirection. 
- In the "Redirect URL" field write the URL where the user will be redirected to. It's possible to select an alias of already published pages or write a new URL.

### CODE REVIEW

**Comment by escopecz** [comment]
I went through all steps described above. One more note: Use incognito window of your browser. Admin session causes the unpublish not to take the effect. It kept me busy for a while.

I can confirm that:
- 302 redirect works
- 301 redirect works
- Redirect to a URL works (http://...)
- Redirect to another Landing Page by alias works
- None option throws 404
- Published Landing Page still works ;)

Test result: Works as described. Awesome feature. Great Job! :+1: 

Only tiny detail I noticed in the code review is that there is problem with code format (tabs vs spaces). @guestisp could you replace tabs with 4 spaces?

**Comment by guestisp** [comment]
Hi @escopecz , thanks for the review! 

I have just added another commit with the fix on tabs issue. I hope that I correct all!

**Comment by escopecz** [comment]
I think you did. I vote for adding this PR to the core :+1:

**Comment by guestisp** [comment]
:+1:

**Comment by drmmr763** [comment]
Testing went well. A few notes for anyone else who wants to test:

1) You need to update entities: `php app/console doctrine:schema:update --force` to do that.
2) definitely need to use a new browser window, the mautic admin session takes over and nothing works the way it will for users. 

Some other "ideas"
- It might be good to auto show / hide the URL redirect field if "none" is selected. 
- Perhaps instead of "none" as the option use "No Redirect". That way we won't confuse users who don't know the difference between a 301 or 302 header compared to a "none" header. (I can just see that getting a little confusing).

Other than that:
@ Test: Worked great
@ Vote: +1! 

Thanks so much @guestisp for contributing! :rocket:

**Comment by guestisp** [comment]
Hi @drmmr763 
I pushed 2 commits with your suggestions.

:+1:

**Comment by escopecz** [comment]
Tested. Chad's ideas are implemented and work great :+1:

**Comment by alanhartless** [comment]
@guestisp Great job! I have a few suggestions:

1) https://github.com/mautic/mautic/pull/611/files#diff-4e014d969e262ad0a5a10ad8cecd0f43R210 Change the text type to url to ensure some level of URL integrity.  

2) https://github.com/guestisp/mautic/blob/add-redirect-support/app/bundles/PageBundle/Form/Type/PageType.php#L73
Add 'redirectUrl' => 'url' to the array so that the input is cleaned as a URL

3) https://github.com/guestisp/mautic/blob/add-redirect-support/app/bundles/PageBundle/Form/Type/PageType.php#L212

Change required to true (since it technical needs to be required if a redirect is supposed to happen) then add form validation.  This can be  by leveraging https://github.com/guestisp/mautic/blob/add-redirect-support/app/bundles/PageBundle/Entity/Page.php#L240. However it needs a little extra since it would only be required IF a redirect type is chosen. To do that, you would need to leverage validation groups.  The FormBundle does something similar:

Determines what groups should be applied based on submitted form data:
https://github.com/guestisp/mautic/blob/add-redirect-support/app/bundles/FormBundle/Entity/Form.php#L213

Define the validations and what groups they belong to:
https://github.com/guestisp/mautic/blob/add-redirect-support/app/bundles/FormBundle/Entity/Form.php#L185

You can use the generic validation message 
https://github.com/guestisp/mautic/blob/add-redirect-support/app/bundles/CoreBundle/Translations/en_US/validators.ini#L4

Or add a custom one to
https://github.com/guestisp/mautic/blob/add-redirect-support/app/bundles/PageBundle/Translations/en_US/validators.ini

**Comment by alanhartless** [comment]
Forgot to note that you have to define the validation group in PageType class similar to the FormBundle's https://github.com/guestisp/mautic/blob/add-redirect-support/app/bundles/FormBundle/Form/Type/FormType.php#L177.

**Pull request merged**
