### PR TITLE
Request URL header in request to webhooks

### PR DESCRIPTION
**Pull request by hluchas**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Automatically include URL of Mautic instance in the payload 

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Use any existing webhook to send data to service such as https://webhook.site

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Same as reproduction steps but X-Origin-Base-URL header is present

### CODE REVIEW

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by dongilbert** [comment]
@hluchas Please review this - I've rebased it to 3.x

@mtshaw3 I've merged #8656 to this as suggested by @escopecz

**Comment by dongilbert** [comment]
Tested @ webhook.site and it's working as expected. It also has the signature from @mtshaw3's PR

**Review by dongilbert — APPROVED** [review]

**Comment by dongilbert** [comment]
Tests are good with latest, and manual testing passed. Merging

**Pull request merged**
