### PR TITLE
Fix cancel scheduled campaign event log

### LINKED ISSUE #8867: Reschedule event or cancel event in contact's history isn't working
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
In contact's history, specifically at scheduled event, we have an option to cancel event or reschedule event, but, this feature isn't working.

| Q   | A
| --- | ---
| Mautic version | 3.0.0-beta2 and 2.16.0
| PHP version | For M3 PHP 7.3 for M2 PHP 7.1
| Browser | Google Chrome

### Steps to reproduce
1. Add contact to campaign that has an event scheduled to future.

example...
Anotação 2020-06-01 222312

2. Try cancel this event in contact's history. Visually, the event was canceled, but if you refresh page, the event it's still scheduled and will be fired.

3. Try reschedule this event in contact's history. Reschedule to be executed now, early or future, isn't working.
 
### Log errors
Today's Mautic error log is empty. Check server error log for error messages Mautic didn't have a chance to catch.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | x
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | Fixes #8867
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

I noticed schedule campaign  actions cannot cancel via timeline. This PR should fixed it.

image

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create campaign
2. Setup scheduled event (Change contacts tags for example)
3. Trigger campaign
4. Go to contact profile and see schedule campaign event action
5. Try cancel it
6. Reload page and see schedule event action still exists

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat all steps and see If scheduled action is non scheduled now

You should see in timeline 

image

### CODE REVIEW

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 versions (except for major security purpose) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.0.1 candidate.**

## How to do?
1. Check if the bug still present in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please comment on your PR: “This PR only applies to Mautic 2.x”

**Please report results by commenting on your PR to make us administration easier.**

_In case your bugfix only apply to Mautic 2, we'll consider adding it in an extra Mautic 2 version._
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebased

**Comment by RCheesley** [comment]
Close & reopen for Scrutinizer

**Review by RCheesley — CHANGES_REQUESTED** [review]
The PR does actually resolve the issue in that the emails are being cancelled, but we seem to lose the message that shows with the notice informing that it was cancelled and the reschedule button:

screenshot-local mautic3-2020 06 27-17_06_26

Screencast: https://youtu.be/CFOg3mqD_9c

**Comment by kuzmany** [comment]
@RCheesley this is just bug fix of current Mautic feature  and at the moment doesn't work at all. That could be fine If we have working feature, instead waiting to upgrade feature
Your suggestion looks like enhancement, maybe we should create another request/issue for that and this bug fix applied.

**Comment by kuzmany** [comment]
I will add note tomorrow to deleted event.

**Comment by dennisameling** [comment]
Moving this to 3.0.2 because we just want to double-check whether the cancellation message should show up. From a user perspective that's a crucial aspect in terms of transparency.

**Comment by kuzmany** [comment]
@RCheesley I've added note for cancelled events

image

**Review by RCheesley — DISMISSED** [review]
Thanks for adding the message @kuzmany  - good to go!

**Comment by RCheesley** [comment]
@kuzmany it looks like this PR reduces the test coverage so we'll need to look into that. Can you possibly add or expand some tests so that we can at least get the coverage so it isn't decreasing?

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
Bumping to 3.1.2 due to needing some attention on the automated tests. @kuzmany this will need to be done by the **18th October** if we are to consider it for the next release.

**Comment by npracht** [comment]
@kuzmany can you have a look at unit tests, then we can merge it.

**Comment by kuzmany** [comment]
@dennisameling really this need unit tests?

**Comment by dennisameling** [comment]
@kuzmany yes please. I'm aware that the AjaxController currently doesn't have any tests, but if we can add them now that'll help us in the future. You can take inspiration from this PR, which adds a functional test to the AjaxController in the LeadBundle: https://github.com/mautic/mautic/pull/8526/files

I've done some first work in  https://github.com/mautic/mautic/pull/8116/commits/a13c52ff7b7343fd3d8d3cb63cb2babbc431f53f, you should be able to build further on that. Let me know if I can help 👍

**Review by escopecz — APPROVED** [review]
I tested the fix and it works 👍 

I also rebased from 3.1 to 3.3 and added missing functional test.

**Pull request merged**
