### PR TITLE
Fix form mapped field radio and checkbox group company 

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Yes
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
I bet this issue was already fixed, maybe by me or @escopecz . But issue  now is back :(

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1.  Create select custom company (don't forget company object select) field with 3 options
2.  Create form and create radio and checkbox group with  enabled Use assigned contact/company field's list choices from properties tab.
3. See preview form and see form fields wasn't fill with options from custom fields

#### Steps to test this PR:
1.  Repeat all steps
2.  See  all form fields are pre-filled with custom company field options

### CODE REVIEW

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by johbuch** [comment]
I tested on a 2.13.1 without merged this PR and it works.

**Comment by escopecz** [comment]
@johbuch may be right. [Alan fixed it](https://github.com/mautic/mautic/commit/6ad3d37cab43afc51f831b9ff4c323b10d0f4722#diff-c6e41373282ebd7a1262eea0170bc587R126) 2 months ago. 

@kuzmany can you re-test on staging? It should be working.

**Comment by kuzmany** [comment]
@johbuch @escopecz but last staging missing this changes. I usually using last Mautic staging for  reproduce issue

https://github.com/mautic/mautic/blob/e601801bab4c1e071ddac745b1a8e4c0be823ea8/app/bundles/FormBundle/Views/Field/checkboxgrp.html.php#L20 
https://github.com/mautic/mautic/blob/e601801bab4c1e071ddac745b1a8e4c0be823ea8/app/bundles/FormBundle/Views/Field/radiogrp.html.php#L20

**Comment by escopecz** [comment]
Ok, I tested it properly now. @kuzmany is right. The problem is on staging and this PR fixes it. I checked out to 2.13.1 and it's not working there either. Thanks Zdeno for being persistent!

**Comment by johbuch** [comment]
@escopecz do you mean that it is not working for you in 2.13.1 ? Because it worked for me

**Comment by kuzmany** [comment]
@johbuch can't work. Did you test company select custom field? Not custom contact field, but company.

**Comment by johbuch** [comment]
Ok indeed it was on contact field. 
On the issue I reported https://github.com/mautic/mautic/issues/5852 it was about contact field (but I maybe forgot to precise it was contact field) because now it works.

**Comment by johbuch** [comment]
@kuzmany  @escopecz I tested for company field in 2.13 it works

**Pull request merged**
