### PR TITLE
Do Not Contact Plugin

### PR DESCRIPTION
**Pull request by moskoweb**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | N
| New feature? | **Y**
| Automated tests included? | N
| Related user documentation PR URL | N
| Related developer documentation PR URL | N
| Issues addressed (#s or URLs) | N
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
With this plugin, you can put the action of adding or removing a contact from the "Do Not Contact" status of a chosen channel.

#### Steps to test this PR:
1. Create new campaign.
2. Add new action, in the action list, the two new options appear.

### CODE REVIEW

**Comment by moskoweb** [comment]
@kuzmany It would be a pleasure if you could test, and give feedback.

**Comment by kuzmany** [comment]
@moskoweb 
Nice plugin.
If you would like release plugin you can do it by composer.
See https://github.com/TheDMSGroup or some of mine https://github.com/kuzmany?utf8=%E2%9C%93&tab=repositories&q=bundle&type=&language=

But you can take your code and add it to core of Mautic as PR.  I mean add code to related DoNotContact model, CampaignSubsriber etc.

**Comment by moskoweb** [comment]
> @moskoweb
> Nice plugin.
> If you would like release plugin you can do it by composer.
> See https://github.com/TheDMSGroup or some of mine https://github.com/kuzmany?utf8=%E2%9C%93&tab=repositories&q=bundle&type=&language=
> 
> But you can take your code and add it to core of Mautic as PR. I mean add code to related DoNotContact model, CampaignSubsriber etc.

Thank you, I thought of putting it as something from Mautic itself, but as a plugin it is possible for someone to move or better, without great needs.

**Comment by escopecz** [comment]
I'd suggest to make this plugin downloadable and installable from its own repository. Not to add it to the core. We'd like to do this with core plugins as well, but it would be a BC change.

**Comment by alanhartless** [comment]
Closing this as we are not adding new plugins to core.

**Comment by bergisch-media** [comment]
Sorry people but this feature is a must have and should be a core feature. The topic is also discussed in the forum.

**Comment by moskoweb** [comment]
> @bergisch-media should be in core, but not as plugin.
> I can take some code from it and integrate it to core with few changes.
> But without budget can't work on it.

How much time do you think you can do? What would be the value? We can see to make a donation.

**Comment by sourabhde18** [comment]
Hello guys,can you please help me I want encryption and decryption of mautic database. is there any solution available

**Comment by coreyworrell** [comment]
@moskoweb Hi I have installed your plugin, but having an issue where the "Set Do Not Contact" action is just toggling the DNC for each contact. If I have a number of contacts in a campaign, some already are DNC, after running them through the campaign the ones that were already DNC had that removed, and the others that were not were correctly set to DNC. Looking through the code it doesn't seem possible, but maybe you have an idea what could be happening?

**Comment by drimlike** [comment]
+1 to get this integrated in Mautic as native

**Comment by heathdutton** [comment]
Mautic core has too many plugins as it is @drimlike. The stock DNC functionality is more than enough for most use-cases. That being said, we've started work on another DNC plugin for those who need extra functionality. PRs and suggestions welcome there https://github.com/TheDMSGroup/mautic-dnc-extras

**Pull request closed without merging**
