### PR TITLE
add mjml theme paprika

### PR DESCRIPTION
**Pull request by jos0405**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
A theme for the grapesjs builder written in MJML, in order to test you need to be running the Mautic release candidate 3.3 or later.

#### Steps to test this PR:
Put these files into your theme directory (template upload doesn't work yet)
you can test it in [mautibox.com](https://mautibox.com)

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Review by RCheesley — APPROVED** [review]
Installed via GH (Mautibox not working at present) and theme is installed and can be used in email building!

screenshot-mautic32 ddev site-2021 02 22-11_23_26
screenshot-mautic32 ddev site-2021 02 22-11_24_41

**Comment by chizuoka** [comment]
> Installed via GH (Mautibox not working at present) and theme is installed and can be used in email building!
> 
> screenshot-mautic32 ddev site-2021 02 22-11_23_26
> screenshot-mautic32 ddev site-2021 02 22-11_24_41

How do we get to this screen? I dont see the paprika template when i create a new email. Just updated to 3.3.1

**Edit**

Oh wait i saw it.. its a new entry in the gear icon. Then need to go to plugins to update plugins, then activate the grapejs and refresh the entire browser. Thanks.

**Pull request merged**
