### PR TITLE
UI - Change word "lead" to "contact" in several bundles

### PR DESCRIPTION
**Pull request by npracht**
| Q  | A
| --- | ---
| Bug fix? | No
| New feature? | No
| Related user documentation PR URL | N/A
| Related developer documentation PR URL | N/A
| Issues addressed (#s or URLs) | N/A
| BC breaks? | No
| Deprecations? | No

# Description
When the change from `lead` to `contact` has been introduced in 1.4.0 for marketing use, several english strings has not been changed from lead to contact.
I also noticed that the new bundles created for SMS and Web Notification didn't take into account this changing (it probably has been started to be developed before the 1.4.0 update).

## Need feedback
I didn't change it **everywhere**. I have the feeling that certain strings are not used in the app. Should i simply change **everywhere** `lead` to `contact` or keep it like that ?

Thanks for feedback,

N.

### CODE REVIEW

**Comment by escopecz** [comment]
:+1:

**Comment by dbhurley** [comment]
+1 this affects strings only.

**Comment by npracht** [comment]
Hi @dbhurley should i also change values in this file? https://github.com/mautic/mautic/blob/staging/app/bundles/ReportBundle/Translations/en_US/messages.ini

**Comment by alanhartless** [comment]
@npracht If you don't mind, that'd be great. Then we can merge this.

**Pull request merged**
