### PR TITLE
Dynamics: Fix process error

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
AbstractIntegration retunr from some time error as array https://github.com/mautic/mautic/blob/973e9ca377032576472d2818fd3e9882f2d76f4c/app/bundles/PluginBundle/Integration/AbstractIntegration.php#L829

This PR fix process error in Dynamics

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  You catch error during sync. Then process error not finish with fatal error

### CODE REVIEW

**Comment by jos0405** [comment]
I'm a bit confused about this PR and other Dynamics related PRs.
I tried to set up Dynamics and got it working from great help from @kuzmany and @npracht .
What does this PR have to do with the PRs that fix Mautic and Dynamics's synch?

**Comment by kuzmany** [comment]
This fix process error handling from API. Before If you sync for example wrong value and API get errror, sync failed. Now log it and continue as before.

**Comment by jos0405** [comment]
> This fix process error handling from API. Before If you sync for example wrong value and API get errror, sync failed. Now log it and continue as before.

I would say: great.
But I have the feeling, that the synch doesn't work without adding a bunch of other PRs first, am I correct?
I can't even test this unless the synch is fixed.
In my opinion there should be a package of PRs that fix the synch with Dynamics otherwise how is it testable?

ADDITION: I understand now what you mean. My synch will be still wrong, but not 100% wrong, just some contacts won't update. I will get an error, and synch will continue. So at least I have a chance to understand what field value is the problem.

**Comment by RCheesley** [comment]
@kuzmany a conflict to resolve here - would be great to get the @mautic/dynamics-tiger-team to review once it's ready!

**Comment by kuzmany** [comment]
Close at the moment. We will push it again once ready to M5

**Pull request closed without merging**
