### PR TITLE
Adding wrongly removed migration back

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes https://forum.mautic.org/t/upgrade-from-v4-4-10-to-5-renders-forms-not-accessable-schema-issues/30415/4

#### Description:

There was a migration added in https://github.com/mautic/mautic/pull/11905/files#diff-77db4abc4be5950896e8ba8200e42c2fe9abdd165eabb3f1cc27d7a0805d022dR1 which was merged into m5-alpha. Later on I made this PR that cleaned old migrations for M5:

https://github.com/mautic/mautic/pull/12441/files#diff-77db4abc4be5950896e8ba8200e42c2fe9abdd165eabb3f1cc27d7a0805d022dL1

And I removed also this new migration. I was pretty sure that I removed only the old ones. Clearly, I was wrong.

#### Steps to test this PR:

1. Test migration from M4.4 to M5 and then access the forms. More details in the linked forum thread.

### CODE REVIEW

**Comment by mollux** [comment]
@escopecz before checking myself, did you go over all deleted migrations to check their original Mautic version? To check of others got deleted by accident?

**Comment by escopecz** [comment]
@mollux Doing that now.

**Comment by escopecz** [comment]
This is the list of [M4 migrations](https://github.com/mautic/mautic/tree/4.4/app/migrations):
```
Version20180508202930.php
Version20180702014364.php
Version20180702014365.php
Version20180821144204.php
Version20180921144421.php
Version20181111095447.php
Version20190704154940.php
Version20190724110039.php
Version20191017140848.php
Version20191126093923.php
Version20191206113956.php
Version20191219155630.php
Version20200211095409.php
Version20200212141530.php
Version20200220172041.php
Version20200227110431.php
Version20200302164801.php
Version20200331160919.php
Version20200409102100.php
Version20200422144300.php
Version20200507122854.php
Version20200729170800.php
Version20200805185714.php
Version20200810153131.php
Version20200812180900.php
Version20200815153711.php
Version20200924080139.php
Version20201015084627.php
Version20201102120710.php
Version20201102133546.php
Version20201105120328.php
Version20201120122846.php
Version20201123070813.php
Version20201125155904.php
Version20201130201631.php
Version20201207114926.php
Version20201207140911.php
Version20201228041109.php
Version20210104171005.php
Version20210203143600.php
Version20210223174702.php
Version20210502162314.php
Version20210520100503.php
Version20210609191822.php
Version20210614151138.php
Version20210623071326.php
Version20220111202917.php
Version20230519081315.php
Version20230522115137.php
```
This is the list of migrations [I removed](https://github.com/mautic/mautic/pull/12441):
```
Version20180508202930.php
Version20180702014364.php
Version20180702014365.php
Version20180821144204.php
Version20180921144421.php
Version20181111095447.php
Version20190704154940.php
Version20190724110039.php
Version20191017140848.php
Version20191126093923.php
Version20191206113956.php
Version20191219155630.php
Version20200211095409.php
Version20200212141530.php
Version20200220172041.php
Version20200227110431.php
Version20200302164801.php
Version20200331160919.php
Version20200409102100.php
Version20200415135706.php
Version20200422144300.php
Version20200507122854.php
Version20200513162918.php
Version20200729170800.php
Version20200805185714.php
Version20200810153131.php
Version20200812180900.php
Version20200815153711.php
Version20200924080139.php
Version20201015084627.php
Version20201102120710.php
Version20201102133546.php
Version20201105120328.php
Version20201120122846.php
Version20201123070813.php
Version20201125155904.php
Version20201130201631.php
Version20201207114926.php
Version20201207140911.php
Version20201228041109.php
Version20210104171005.php
Version20210203143600.php
Version20210223174702.php
Version20210502162314.php
Version20210520100503.php
Version20210609191822.php
Version20210614151138.php
Version20210623071326.php
Version20220111202917.php
```
When I do a diff, these migrations are missing:
```
Version20200415135706.php
Version20200513162918.php
```
So I'll add the other one as well

**Comment by mollux** [comment]
@escopecz this should target the 5.0 branch?

**Comment by escopecz** [comment]
Thanks for checking. Updated

**Comment by mollux** [comment]
you'll need to rebase the branch too

**Review by mollux — APPROVED** [review]
changes look good!

**Pull request merged**
