### PR TITLE
add safari support for state drop down

### PR DESCRIPTION
**Pull request by roboparker**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Adds safari support for state dropdown

#### Description:

Forms with country and state fields do not correctly filter out states when selecting a country in safari

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a form with country and state field
    - The State select field needs to be added via the Add field based on selected value.
    - The condition should be any.
    - Mapped should be set to the State.
    - Use assigned contact/company field's list choices should be toggled on.
4. in safari select a country and verify the state dropdown only shows states for that country.

### CODE REVIEW

**Review by PatrickJenkner — COMMENTED** [review]
This doesn't seem to work for me. No matter that country I select, I always get shown the whole list of states for all countries.

**Comment by roboparker** [comment]
> This doesn't seem to work for me. No matter that country I select, I always get shown the whole list of states for all countries.

Did you recompile the js and clear cache? I didn't include that in the steps.

**Comment by RCheesley** [comment]
Hi @diaboloshogunate we have a conflict to address here please! Thanks!

**Comment by roboparker** [comment]
@RCheesley Ill take a look today

**Comment by RCheesley** [comment]
Hi @diaboloshogunate I tried to test this with the following:

1. Create a standalone form
2. Add a field using list - country as the type
3. Add a Select field and map it to the contact field state
4. Preview the form, select a country and check the state field
5. All the entries available for every country show in the state dropdown - not just the ones for the country selected.

Is this the correct way to do it per your bug report instructions?

Perhaps we need more guidance? Cache clearing now happens by default in the build process so I don't think that is behind it.

**Comment by roboparker** [comment]
@RCheesley I believe so. Ill double check it this this week.

**Comment by roboparker** [comment]
@RCheesley I think I might know what we are doing different.

The State select field needs to be added via the `Add field based on selected value`. 
The condition should be any. 
Mapped should be set to the State.
Use assigned contact/company field's list choices should be toggled on.

I believe you will need to run `bin/console mautic:assets:generate` and clear your cache as well

**Review by PatrickJenkner — APPROVED** [review]
Just tested it with your new specifications @diaboloshogunate , and now it works perfectly; thanks! I didn't even need to clear the cache or generate assets.

**Review by escopecz — APPROVED** [review]
Nice workaround for Safari. Thanks! 👍

**Pull request merged**
