### PR TITLE
Fixed company name is not showing on contact edit page

### PR DESCRIPTION
**Pull request by rahuld-dev**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | Yes
| New feature/enhancement? (use the a.x branch)      | No
| Deprecations?                          | No
| BC breaks? (use the c.x branch)        | No
| Automated tests included?              | Yes 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
The company name is not showing on contact edit page.
However, we can see the company name getting populated on the right hand-side of the contact name on the contact details page. Also, when you expand the details on the contact details page, you can see the company name.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create more than 100 companies - here is a link where you can download some sample data: https://www.datablist.com/learn/csv/download-sample-csv-files
3. From company list page, find name of last company
4. Assign last company to contact which found from step 2
5. Save contact and edit again
6. Company should be display in Company filed on contact's edit page.

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
The code looks great. Thanks!

**Comment by RCheesley** [comment]
I am struggling a bit with testing this one.

Here's a screencast: https://watch.screencastify.com/v/pmnpKUhslSkKeRQGiUs1

I can't search in the company field at all for the company names that I have imported - even if I can see the name in the list below.

Will check to see if this is a general error or unique to this PR.

**Comment by RCheesley** [comment]
https://github.com/mautic/mautic/issues/12650 this issue blocked me from testing :( Will try a company starting with A which I can click to select rather than searching for the name - is that still a valid way to test @rahuld-dev ?

**Comment by rahuld-dev** [comment]
> #12650 this issue blocked me from testing :( Will try a company starting with A which I can click to select rather than searching for the name - is that still a valid way to test @rahuld-dev ?

No, These issue is related when we select company which is not available in initial dropdown list. We need to attach the company which is not available in initial dropdown to contacts.

**Review by PatrickJenkner — COMMENTED** [review]
I ran into the same issue as @RCheesley. So I created a new company during contact creation that wouldn't show up in the initial dropdown. It worked as you described for that scenario, the company was still displayed in the contact. I don't know if this is a valid test though.

**Comment by escopecz** [comment]
The regression that is blocking this PR is fixed in https://github.com/mautic/mautic/pull/12652

**Comment by escopecz** [comment]
The regression fix has been merged. This is now ready for a retest.

**Review by PatrickJenkner — APPROVED** [review]
Works exactly as described now for a user. Thanks!

**Pull request merged**
