### PR TITLE
Add truly personal theme to root composer.json

### PR DESCRIPTION
**Pull request by RCheesley**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | features
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | N/A

#### Description:

This PR adds the new Simply Personal theme to the app/composer.json file so that it is picked up for composer-based installations (just added it to Packagist).

#### Steps to test this PR:

Just requires a code review please.

### CODE REVIEW

**Comment by escopecz** [comment]
@RCheesley please rebase on 5.x

**Comment by shinde-rahul** [comment]
@RCheesley, This needs rebase.

**Comment by RCheesley** [comment]
Probably much easier to do a new PR given the timespan! I'll get this done shortly.

**Comment by RCheesley** [comment]
See #14202 as replacement for this PR!

**Pull request closed without merging**
