### PR TITLE
Disable merge identified contacts by tracking code

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR added new option to configuration to disable merge identified contacts from tracking code. This is helpful for shared computers. This allow switch contact/or create new one if not same like current tracked contact.

image

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Enable new option in configuration > Trackign settings > Disable merge identified contacts 
3. Enable Publicly updatable for unique custom fields (email propably)
4. Create page with tracking code and use

`mt('send', 'pageview', {email: 'test@gmail.com'});`

See test@gmail.com is created and should be tracked contact now (check mtc_id cookie)

5. Change tracking code to another email address:

`mt('send', 'pageview', {email: 'test2@gmail.com'});`

See test2@gmail.com is created should be tracked contact now (check changed mtc_id cookie)

6. Change tracking code to email address from step 4:

`mt('send', 'pageview', {email: 'test@gmail.com'});`

See test@gmail.com is updated and should be tracked contact now (check mtc_id cookie)

### CODE REVIEW

**Comment by stevedrobinson** [comment]
Tested and worked as described. 

This is a huge help for a client of ours who keeps seeing records "disappear" from their database because they are merged inappropriately when their audience uses other people's email addresses in unexpected places.

**Comment by atbrowne** [comment]
Tested.

While contact details are no longer merged incorrectly tracking information i.e. page hit history is still merged incorrectly making the feature's usefulness limited as it is currently.

**Comment by kuzmany** [comment]
@atbrowne don't understand.

**Comment by atbrowne** [comment]
@kuzmany following your testing steps upon executing step 5 all test@gmail.com's pages hits are transferred to test2@gmail.com. See the included image:   
page-hit-merge

**Comment by kuzmany** [comment]
@atbrowne how did you test it? Did you change your configuration? Clear cache? 
Can you re-test it?

**Comment by kuzmany** [comment]
@atbrowne @stevedrobinson please re-test

**Comment by atbrowne** [comment]
@kuzmany the mauticbox for this PR is not working.

**Comment by kuzmany** [comment]
@atbrowne now working, please try  https://mautibox.com/7726

**Comment by stevedrobinson** [comment]
Just retested covering all scenarios and works great.

**Comment by atbrowne** [comment]
@kuzmany the issue I reported is still not resolved. In order to produce it I am setting `Disable merge identified contacts` to `Yes` and `Restirct Domains` under `CORS Settings` to `No`. Then including the following script on a is a simple php page:
```js
var mauticUrl = 'https://mautibox.com/7726';

(function(w,d,t,u,n,a,m){w['MauticTrackingObject']=n;
   w[n]=w[n]||function(){(w[n].q=w[n].q||[]).push(arguments)},a=d.createElement(t),
   m=d.getElementsByTagName(t)[0];a.async=1;a.src=u;m.parentNode.insertBefore(a,m)
})(window,document,'script',mauticUrl + '/mtc.js','mt');

mt('send', 'pageview', {email: 'test@gmail.com'});
```

After hitting the php page look up the page hit for `test@gmail.com` in the mauticbox. Now edit the hard coded email in the script to `test2@gmail.com` and refresh the php page. Look up `test@gmail.com` in the mautic box and you should see that the page hit that was previously there is gone. Look up `test2@gmail.com` in mautic box and you should see the page hit from `test@gmail.com` is assigned to it in addition to the page hit entry generated with the refresh. You can keep alternating between the two emails and refreshing the page to see all of the page hits transferred back and forth between the two accounts.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
As this has quite a bit of work to be done and outstanding conflicts, I've set this for the 3.3 milestone. If it is in mergeable condition sooner than that we can consider it for inclusion in the 3.2 milestone.

**Comment by npracht** [comment]
I'll close this PR as far as there is no feedbacks about the owner. Don't take it wrong, part of it is our fault, we've been too long (on the Mautic Community Product Team side) to handle it at the time the PR has been offer.

If someone want to take it, i'll reopen it or they can create a new PR.

**Comment by powertictech** [comment]
just curious but the PR "owner" work doesn't work at the same company?

**Comment by npracht** [comment]
He does. But I have a job and a role inc immunity. Those 2 positions are different.

**Comment by stevedrobinson** [comment]
Tossing a note on this PR for anyone stumbling on this in the future. The default behavior in Mautic, at least of 4.4.4, is to no longer merge contacts when the same browser submits a form for two different existing contact records. This new default behavior makes this PR no longer necessary.

**Pull request closed without merging**
