### PR TITLE
February and week fix

### PR DESCRIPTION
**Pull request by escopecz**
Please answer the following questions:

| Q             | A
| ------------- | ---
| Bug fix?      | Y
| New feature?  | N
| BC breaks?    | N
| Deprecations? | N
| Fixed issues  |  /

## Description
This fixes some line chart inconsistencies with different time views and different date ranges. For example for my data, the week 18 showed 0 contact when I was looking 3 months back, but 2 contacts (correct) when I was looking 2 months back. In the month view, I saw 0 contacts for April, but it wasn't true since 2 contact were created there.

## Steps to test this PR
Make sure that all time units and date ranges display the same data.

### CODE REVIEW

**Comment by mqueme** [comment]
I think this is still not quite right. I am attaching some screen shots.
screenshot from 2016-05-09 14 38 04
screenshot from 2016-05-09 14 38 26

**Comment by escopecz** [comment]
@mqueme could you please retest?

**Comment by mqueme** [comment]
It worked this time!

**Comment by dongilbert** [comment]
+1 Thanks @escopecz

**Pull request merged**
