### PR TITLE
Report query for debug mode

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

If you use dev environment you can see  query on report's detail page. This PR added support also for enabled debug mode. This allow you print query for fast check on production enviroment.

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Check report detail page on production
3. Check same report detail page with enabled debug = true in local.php. You should see sql queries on the bottom of reports 

image

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11397"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for the PR @kuzmany - please base it on 4.4 for the upcoming bug fix releases as we are not releasing anything further from the 4.x branch. Thanks!

**Review by escopecz — APPROVED** [review]
The code is solid. Thanks Zdeno! 👍

**Comment by escopecz** [comment]
@RCheesley I've created the 4.5.0 milestone as we won't be able to release M5 soon so we may as well release another minor M4 release. If not, I can merge 4.x to 5.x so the work won't be lost. This is a small enhancement, so it cannot go to a patch release.

**Comment by RCheesley** [comment]
Ah OK sorry I misread the description. Makes sense then if we don't want to wait for 5.x.

**Review by biozshock — APPROVED** [review]
If this does not intend to show queries for table-less reports, then the change is ok.

**Comment by escopecz** [comment]
There will be no more feature releases for M4. I'll merge this into M5 (the 5.x branch)

**Pull request merged**
