### PR TITLE
Updated push to integration campaign action to use configuration from action.

### PR DESCRIPTION
**Pull request by shinde-rahul**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This pull request addresses an issue encountered while working on the custom Salesforce (SF) integration. The problem arises when the custom integration injects certain fields into the `Push to Integration` campaign action within the `CustomSalesforceIntegration::appendToForm` method, using `$formArea` as `integration`. These injected settings need to be accessible within the `CustomSalesforceIntegration::pushLeadToCampaign` method.

To resolve this issue, the following changes have been made:

- Modified the `CustomSalesforceIntegration::appendToForm` method to inject the required fields into the "Push to Integration" campaign action with `$formArea` as `integration`.
- Updated the `CustomSalesforceIntegration::pushLeadToCampaign` method to access and utilize the injected settings.

With these modifications, the custom Salesforce integration now properly handles the injected fields in the "Push to Integration" campaign action, ensuring the availability of required settings within the `CustomSalesforceIntegration::pushLeadToCampaign` method.

This pull request aims to enhance the functionality and reliability of the custom Salesforce integration, improving its integration capabilities with Mautic.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by RCheesley** [comment]
@shinde-rahul we need a PR on the 5.x branch as well please, to consider this one for merging. Thanks!

Also when you talk about the custom Salesforce integration, is this something the community can test or would this need reviewing at the code level / checking by someone from Acquia?

**Comment by RCheesley** [comment]
@shinde-rahul could you make the PR for 5.x and clarify re. the test instructions?

**Comment by shinde-rahul** [comment]
5.x PR https://github.com/mautic/mautic/pull/12853.
To test this, please apply the following diff patch, which is only for testing purposes,
```
diff --git a/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php b/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php
index 6ae77a0b0c..99aa095d89 100644
--- a/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php
+++ b/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php
@@ -2,6 +2,7 @@
 
 namespace MauticPlugin\MauticCrmBundle\Integration;
 
+use Mautic\CoreBundle\Form\Type\YesNoButtonGroupType;
 use Mautic\CoreBundle\Helper\InputHelper;
 use Mautic\LeadBundle\Entity\Company;
 use Mautic\LeadBundle\Entity\DoNotContact;
@@ -662,6 +663,17 @@ class SalesforceIntegration extends CrmAbstractIntegration
                 ]
             );
         }
+
+        if ('integration' == $formArea) {
+            $builder->add(
+                'notify_member',
+                YesNoButtonGroupType::class,
+                [
+                    'label'      => 'mautic.salesforce.form.field.notify_member',
+                    'empty_data' => '0',
+                ]
+            );
+        }
     }
 
     /**
@@ -1524,7 +1536,8 @@ class SalesforceIntegration extends CrmAbstractIntegration
         $integrationEntityRepo = $this->em->getRepository('MauticPluginBundle:IntegrationEntity');
 
         $body = [
-            'Status' => (!empty($config['campaign_member_status']['campaign_member_status'])) ? $config['campaign_member_status']['campaign_member_status'] : null,
+            'Status'          => (!empty($config['campaign_member_status']['campaign_member_status'])) ? $config['campaign_member_status']['campaign_member_status'] : null,
+            'Notification__c' => isset($config['config']['notify_member']) && 1 === $config['config']['notify_member'],
         ];
         $object = 'CampaignMember';
         $url    = '/services/data/v38.0/sobjects/'.$object;
diff --git a/plugins/MauticCrmBundle/Translations/en_US/messages.ini b/plugins/MauticCrmBundle/Translations/en_US/messages.ini
index 3fe410a9f0..02a901420b 100644
--- a/plugins/MauticCrmBundle/Translations/en_US/messages.ini
+++ b/plugins/MauticCrmBundle/Translations/en_US/messages.ini
@@ -99,3 +99,4 @@ mautic.plugin.integration.campaigns.connectwise.members="Assign to member"
 mautic.plugin.config.push.activities="Push contact activities"
 mautic.plugin.config.integration.restart="Restart integration"
 mautic.plugin.config.integration.restarted="%integration% restarted"
+mautic.salesforce.form.field.notify_member="Notify member"

```

The requirement was to push extra configurable details to the Campaign Membership API. I created an SF field for the Campaign Membership object and then updated the code base according to the need.

@RCheesley, hope this helps.

**Comment by RCheesley** [comment]
@shinde-rahul I was asking for _user testing_ instructions - what do they need to physically test in a Mautic instance, in order to check that this PR is working?  You've given a great technical explanation, but that does not help a user of Mautic (maybe a marketer) who wants to help testing that this fixes the issue.

It sounds like it is to do with the campaign action for an integration and certain fields not getting passed over, so perhaps you can explain what the symptom is of the problem it's fixing (eg the bug report), and what should happen once it's applied (eg the acceptance criteria. Maybe even include screenshots/screen recording if it's complex.

 If folks don't know what to actually test, they can't help get this merged.

Hope that helps, ping me on Slack if you need any more guidance!

**Comment by shinde-rahul** [comment]
Closing this in favor of https://github.com/mautic/mautic/pull/12853.

**Pull request closed without merging**
