### PR TITLE
M3: Refactor BuilderTokenHelper away from MauticFactory #8088

### PR DESCRIPTION
**Pull request by mtshaw3**
\Mautic\CoreBundle\Helper\BuilderTokenHelper is dependent on MauticFactory and thus needs to be refactored to a service instead in order to use dependency injection.

### CODE REVIEW

**Comment by escopecz** [comment]
@mtshaw3 @dongilbert I will change the m2-to-m3 branch for this PR. The 3.x branch is not ready to be used for testing. Also Travis is failing terribly.

**Comment by escopecz** [comment]
Oops, Was this rebased?

**Comment by mtshaw3** [comment]
Yes, I believe Don rebased to 3.x branch

**Comment by anton-vlasenko** [comment]
@mtshaw3 I suppose those merge conflicts have to be resolved.
Another option would be to create a new PR that will go into m2-to-m3 branch and cherry-pick your existing commits into that new PR.
But those merge conflicts have to be resolved somehow before we code review and test this task.

**Comment by mtshaw3** [comment]
Because this PR had so many issues, multiple rebase, merge conflicts, force pushes etc, I cherry-picked the good commits and created a clean PR https://github.com/mautic/mautic/pull/8204/

**Pull request closed without merging**
