### PR TITLE
Fix operators for text type report filters

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
We use on  few reports text type for reports columns setup. 
This type does not support startsWith,endsWith, contains return error.

Related error log:

`[2020-11-27 10:28:53] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "contains" of class "Doctrine\DBAL\Query\Expression\ExpressionBuilder"." at .../app/bundles/ReportBundle/Builder/MauticReportBuilder.php line 487 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"contains\" of class \"Doctrine\\DBAL\\Query\\Expression\\ExpressionBuilder\". at ...app/bundles/ReportBundle/Builder/MauticReportBuilder.php:487)"} []`

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create UTM codes report
3. Choose any columns and add to filter 
UTM contains xxx
  
image
4. Save and check report
5. Before apply PR return error 500

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
The code change make sense. Just needs some tests.

**Comment by RCheesley** [comment]
Updated the branch but this needs to be rebased.

**Comment by abhisekmazumdar** [comment]
I can confirm that this issue still exists in the latest 5.x. 

The DNC Comment field is also been marked as type text: https://github.com/mautic/mautic/blob/5.x/app/bundles/LeadBundle/Entity/DoNotContact.php#L86-L88

So to reproduce this issue one can follow the following steps:

1. Create a new Report.
2. Over the filters add Column: `DNC Comment` | Condition: `contains` | Value: `sometext` 
3. Save & Close

If these changes are not present, we get an error screen; otherwise, the report works.

@kuzmany can you please rebase this with the latest code.

**Comment by abhisekmazumdar** [comment]
@kuzmany do you think you will be able to rebase this with 5.x. As this is still an issue as mentioned here: https://github.com/mautic/mautic/pull/9447#issuecomment-2142076267

**Comment by kuzmany** [comment]
Close favor to M5 version https://github.com/mautic/mautic/pull/13867

**Pull request closed without merging**
