### PR TITLE
[UI] Change navigation menu icons

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR started with the discussion here:
[UX] Improve the comparison between the two form type options https://github.com/mautic/mautic/pull/13381

This discussion generated another PR:
[UI] Change Form, SMS and Email types header https://github.com/mautic/mautic/pull/13582

Then the second PR raised needs:

> I like that we have the goal to make this more clean and we remove the "new". Great idea.
> 
> The goal of this screen is for the user to decide quickly which one of the two options to choose.
> 
> So for the icons, we should use the same icons across Mautic. So a user can quickly see that this is a segment email. So anything segment is always a segment icon, and a campaign icon is always a campaign icon.

So this PR aims to solve the need to see standard icons across the entire UI.
This move is backed by the addition of Remix icon pack https://github.com/mautic/mautic/pull/13318, where we need to replace FontAwesome icons until it's completely removed and the code clean.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Look at both sidebars

image

image

### CODE REVIEW

**Comment by adiux** [comment]
@andersonjeccel would you mind adding a printscreen of the new icons to the PR for easier review and discussion? The code looks good to me.

**Comment by andersonjeccel** [comment]
@adiux Of course!
Edited the description

**Comment by andersonjeccel** [comment]
@RCheesley It needs docs, right?

**Comment by andersonjeccel** [comment]
@RCheesley This PR needs docs?

**Review by LordRembo — APPROVED** [review]
Looks good.

**Comment by RCheesley** [comment]
> @RCheesley This PR needs docs?

Yes, anywhere in the docs where either menu is shown needs to be updated accordingly.

cc @mautic/education-team-leaders - perhaps you can support this change and/or find someone to help with making the PR in time for the release next week assuming we get it reviewed by another in time.

**Review by kuzmany — APPROVED** [review]
See nothing wrong 👍

**Pull request merged**
