### PR TITLE
Doctrine result cache with automatic invalidation

### PR DESCRIPTION
**Pull request by fedys**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [❌]
| New feature/enhancement? (use the a.x branch)      | [✅]
| Deprecations?                          | [❌]
| BC breaks? (use the c.x branch)        | [❌]
| Automated tests included?              | [❌] 
| Related user documentation PR URL      |  
| Related developer documentation PR URL |  
| Issue(s) addressed                     |  

#### Description:

This PR introduces database query result caching with an automatic cache invalidation. In this PR the result cache was applied to queries that return the same results most of the time. See the list of queries executed when requesting /s/contacts endpoint:

**Before** this PR
```sql
SELECT u0_.is_published AS is_published_0, u0_.date_added AS date_added_1, u0_.created_by AS created_by_2, u0_.created_by_user AS created_by_user_3, u0_.date_modified AS date_modified_4, u0_.modified_by AS modified_by_5, u0_.modified_by_user AS modified_by_user_6, u0_.checked_out AS checked_out_7, u0_.checked_out_by AS checked_out_by_8, u0_.checked_out_by_user AS checked_out_by_user_9, u0_.id AS id_10, u0_.username AS username_11, u0_.password AS password_12, u0_.first_name AS first_name_13, u0_.last_name AS last_name_14, u0_.email AS email_15, u0_.position AS position_16, u0_.timezone AS timezone_17, u0_.locale AS locale_18, u0_.last_login AS last_login_19, u0_.last_active AS last_active_20, u0_.preferences AS preferences_21, u0_.signature AS signature_22, r1_.is_published AS is_published_23, r1_.date_added AS date_added_24, r1_.created_by AS created_by_25, r1_.created_by_user AS created_by_user_26, r1_.date_modified AS date_modified_27, r1_.modified_by AS modified_by_28, r1_.modified_by_user AS modified_by_user_29, r1_.checked_out AS checked_out_30, r1_.checked_out_by AS checked_out_by_31, r1_.checked_out_by_user AS checked_out_by_user_32, r1_.id AS id_33, r1_.name AS name_34, r1_.description AS description_35, r1_.is_admin AS is_admin_36, r1_.readable_permissions AS readable_permissions_37, u0_.role_id AS role_id_38 FROM users u0_ LEFT JOIN roles r1_ ON u0_.role_id = r1_.id WHERE (u0_.username = 'admin' OR u0_.email = 'admin') AND u0_.is_published = 1
SELECT p0_.id AS id_0, p0_.bundle AS bundle_1, p0_.name AS name_2, p0_.bitwise AS bitwise_3 FROM permissions p0_ WHERE p0_.role_id = 1 ORDER BY p0_.bundle ASC
SELECT t0.id AS id_1, t0.name AS name_2, t0.is_published AS is_published_3, t0.supported_features AS supported_features_4, t0.api_keys AS api_keys_5, t0.feature_settings AS feature_settings_6, t0.plugin_id AS plugin_id_7 FROM plugin_integration_settings t0 WHERE t0.name = 'grapesjsbuilder' LIMIT 1
SELECT f.id as value, f.name as label FROM forms f WHERE f.is_published = 1 ORDER BY f.name ASC
SELECT l0_.is_published AS is_published_0, l0_.date_added AS date_added_1, l0_.created_by AS created_by_2, l0_.created_by_user AS created_by_user_3, l0_.date_modified AS date_modified_4, l0_.modified_by AS modified_by_5, l0_.modified_by_user AS modified_by_user_6, l0_.checked_out AS checked_out_7, l0_.checked_out_by AS checked_out_by_8, l0_.checked_out_by_user AS checked_out_by_user_9, l0_.id AS id_10, l0_.label AS label_11, l0_.alias AS alias_12, l0_.type AS type_13, l0_.field_group AS field_group_14, l0_.default_value AS default_value_15, l0_.is_required AS is_required_16, l0_.is_fixed AS is_fixed_17, l0_.is_visible AS is_visible_18, l0_.is_short_visible AS is_short_visible_19, l0_.is_listable AS is_listable_20, l0_.is_publicly_updatable AS is_publicly_updatable_21, l0_.is_unique_identifer AS is_unique_identifer_22, l0_.field_order AS field_order_23, l0_.object AS object_24, l0_.properties AS properties_25, l0_.column_is_not_created AS column_is_not_created_26, l0_.original_is_published_value AS original_is_published_value_27 FROM lead_fields l0_ WHERE l0_.is_published = 1 AND l0_.object = 'lead' ORDER BY l0_.field_order ASC
SELECT f.id, f.label, f.alias, f.type, f.field_group as "group", f.object, f.is_fixed, f.properties, f.default_value FROM lead_fields f WHERE (f.is_published = 1) AND (object = 'lead') ORDER BY f.field_order asc
SELECT COUNT(l.id) as count FROM leads l LEFT JOIN users u ON u.id = l.owner_id WHERE l.date_identified IS NOT NULL
SELECT l.* FROM leads l LEFT JOIN users u ON u.id = l.owner_id WHERE l.date_identified IS NOT NULL ORDER BY l.last_active DESC, l.id DESC LIMIT 30
SELECT (CASE WHEN l0_.id = 1 THEN 0 ELSE 1 END) AS sclr_0, l0_.is_published AS is_published_1, l0_.date_added AS date_added_2, l0_.created_by AS created_by_3, l0_.created_by_user AS created_by_user_4, l0_.date_modified AS date_modified_5, l0_.modified_by AS modified_by_6, l0_.modified_by_user AS modified_by_user_7, l0_.checked_out AS checked_out_8, l0_.checked_out_by AS checked_out_by_9, l0_.checked_out_by_user AS checked_out_by_user_10, l0_.id AS id_11, l0_.points AS points_12, l0_.last_active AS last_active_13, l0_.internal AS internal_14, l0_.social_cache AS social_cache_15, l0_.date_identified AS date_identified_16, l0_.preferred_profile_image AS preferred_profile_image_17, l0_.title AS title_18, l0_.firstname AS firstname_19, l0_.lastname AS lastname_20, l0_.company AS company_21, l0_.position AS position_22, l0_.email AS email_23, l0_.phone AS phone_24, l0_.mobile AS mobile_25, l0_.address1 AS address1_26, l0_.address2 AS address2_27, l0_.city AS city_28, l0_.state AS state_29, l0_.zipcode AS zipcode_30, l0_.timezone AS timezone_31, l0_.country AS country_32, u1_.is_published AS is_published_33, u1_.date_added AS date_added_34, u1_.created_by AS created_by_35, u1_.created_by_user AS created_by_user_36, u1_.date_modified AS date_modified_37, u1_.modified_by AS modified_by_38, u1_.modified_by_user AS modified_by_user_39, u1_.checked_out AS checked_out_40, u1_.checked_out_by AS checked_out_by_41, u1_.checked_out_by_user AS checked_out_by_user_42, u1_.id AS id_43, u1_.username AS username_44, u1_.password AS password_45, u1_.first_name AS first_name_46, u1_.last_name AS last_name_47, u1_.email AS email_48, u1_.position AS position_49, u1_.timezone AS timezone_50, u1_.locale AS locale_51, u1_.last_login AS last_login_52, u1_.last_active AS last_active_53, u1_.preferences AS preferences_54, u1_.signature AS signature_55, l0_.owner_id AS owner_id_56, l0_.stage_id AS stage_id_57, u1_.role_id AS role_id_58 FROM leads l0_ LEFT JOIN users u1_ ON l0_.owner_id = u1_.id WHERE l0_.id IN (1) ORDER BY sclr_0 ASC
SELECT l0_.id AS id_0, l0_.name AS name_1, l0_.alias AS alias_2 FROM lead_lists l0_ WHERE l0_.is_published = 1 ORDER BY l0_.name ASC
SELECT max(id) as max_lead_id FROM leads l
SELECT l0_.is_published AS is_published_0, l0_.date_added AS date_added_1, l0_.created_by AS created_by_2, l0_.created_by_user AS created_by_user_3, l0_.date_modified AS date_modified_4, l0_.modified_by AS modified_by_5, l0_.modified_by_user AS modified_by_user_6, l0_.checked_out AS checked_out_7, l0_.checked_out_by AS checked_out_by_8, l0_.checked_out_by_user AS checked_out_by_user_9, l0_.id AS id_10, l0_.label AS label_11, l0_.alias AS alias_12, l0_.type AS type_13, l0_.field_group AS field_group_14, l0_.default_value AS default_value_15, l0_.is_required AS is_required_16, l0_.is_fixed AS is_fixed_17, l0_.is_visible AS is_visible_18, l0_.is_short_visible AS is_short_visible_19, l0_.is_listable AS is_listable_20, l0_.is_publicly_updatable AS is_publicly_updatable_21, l0_.is_unique_identifer AS is_unique_identifer_22, l0_.field_order AS field_order_23, l0_.object AS object_24, l0_.properties AS properties_25, l0_.column_is_not_created AS column_is_not_created_26, l0_.original_is_published_value AS original_is_published_value_27 FROM lead_fields l0_ WHERE l0_.is_published = 1 AND l0_.object = 'lead' ORDER BY l0_.field_order ASC
SELECT dnc.channel, dnc.reason, l.id as lead_id FROM lead_donotcontact dnc LEFT JOIN leads l ON l.id = dnc.lead_id WHERE l.id IN (1)
SELECT p0_.id AS id_0, p0_.name AS name_1, p0_.is_published AS is_published_2, p0_.supported_features AS supported_features_3, p0_.api_keys AS api_keys_4, p0_.feature_settings AS feature_settings_5, p0_.plugin_id AS plugin_id_6 FROM plugin_integration_settings p0_ INNER JOIN plugins p1_ ON p0_.plugin_id = p1_.id
SELECT p0_.id AS id_0, p0_.name AS name_1, p0_.description AS description_2, p0_.is_missing AS is_missing_3, p0_.bundle AS bundle_4, p0_.version AS version_5, p0_.author AS author_6 FROM plugins p0_ ORDER BY p0_.name ASC
SELECT p0_.id AS id_0, p0_.name AS name_1, p0_.is_published AS is_published_2, p0_.supported_features AS supported_features_3, p0_.api_keys AS api_keys_4, p0_.feature_settings AS feature_settings_5, p0_.plugin_id AS plugin_id_6 FROM plugin_integration_settings p0_
SELECT t0.id AS id_1, t0.name AS name_2, t0.is_published AS is_published_3, t0.supported_features AS supported_features_4, t0.api_keys AS api_keys_5, t0.feature_settings AS feature_settings_6, t0.plugin_id AS plugin_id_7 FROM plugin_integration_settings t0 WHERE t0.name = 'grapesjsbuilder' LIMIT 1
SELECT n0_.id AS id_0, n0_.type AS type_1, n0_.header AS header_2, n0_.message AS message_3, n0_.date_added AS date_added_4, n0_.icon_class AS icon_class_5, n0_.is_read AS is_read_6, n0_.deduplicate AS deduplicate_7 FROM notifications n0_ WHERE n0_.user_id = 1 AND n0_.is_read = 0 ORDER BY n0_.date_added DESC LIMIT 200
```

**After** this PR:
```sql
SELECT f.id as value, f.name as label FROM forms f WHERE f.is_published = 1 ORDER BY f.name ASC
SELECT COUNT(l.id) as count FROM leads l LEFT JOIN users u ON u.id = l.owner_id WHERE l.date_identified IS NOT NULL
SELECT l.* FROM leads l LEFT JOIN users u ON u.id = l.owner_id WHERE l.date_identified IS NOT NULL ORDER BY l.last_active DESC, l.id DESC LIMIT 30
SELECT (CASE WHEN l0_.id = 1 THEN 0 ELSE 1 END) AS sclr_0, l0_.is_published AS is_published_1, l0_.date_added AS date_added_2, l0_.created_by AS created_by_3, l0_.created_by_user AS created_by_user_4, l0_.date_modified AS date_modified_5, l0_.modified_by AS modified_by_6, l0_.modified_by_user AS modified_by_user_7, l0_.checked_out AS checked_out_8, l0_.checked_out_by AS checked_out_by_9, l0_.checked_out_by_user AS checked_out_by_user_10, l0_.id AS id_11, l0_.points AS points_12, l0_.last_active AS last_active_13, l0_.internal AS internal_14, l0_.social_cache AS social_cache_15, l0_.date_identified AS date_identified_16, l0_.preferred_profile_image AS preferred_profile_image_17, l0_.title AS title_18, l0_.firstname AS firstname_19, l0_.lastname AS lastname_20, l0_.company AS company_21, l0_.position AS position_22, l0_.email AS email_23, l0_.phone AS phone_24, l0_.mobile AS mobile_25, l0_.address1 AS address1_26, l0_.address2 AS address2_27, l0_.city AS city_28, l0_.state AS state_29, l0_.zipcode AS zipcode_30, l0_.timezone AS timezone_31, l0_.country AS country_32, u1_.is_published AS is_published_33, u1_.date_added AS date_added_34, u1_.created_by AS created_by_35, u1_.created_by_user AS created_by_user_36, u1_.date_modified AS date_modified_37, u1_.modified_by AS modified_by_38, u1_.modified_by_user AS modified_by_user_39, u1_.checked_out AS checked_out_40, u1_.checked_out_by AS checked_out_by_41, u1_.checked_out_by_user AS checked_out_by_user_42, u1_.id AS id_43, u1_.username AS username_44, u1_.password AS password_45, u1_.first_name AS first_name_46, u1_.last_name AS last_name_47, u1_.email AS email_48, u1_.position AS position_49, u1_.timezone AS timezone_50, u1_.locale AS locale_51, u1_.last_login AS last_login_52, u1_.last_active AS last_active_53, u1_.preferences AS preferences_54, u1_.signature AS signature_55, l0_.owner_id AS owner_id_56, l0_.stage_id AS stage_id_57, u1_.role_id AS role_id_58 FROM leads l0_ LEFT JOIN users u1_ ON l0_.owner_id = u1_.id WHERE l0_.id IN (1) ORDER BY sclr_0 ASC
SELECT l0_.id AS id_0, l0_.name AS name_1, l0_.alias AS alias_2 FROM lead_lists l0_ WHERE l0_.is_published = 1 ORDER BY l0_.name ASC
SELECT max(id) as max_lead_id FROM leads l
SELECT dnc.channel, dnc.reason, l.id as lead_id FROM lead_donotcontact dnc LEFT JOIN leads l ON l.id = dnc.lead_id WHERE l.id IN (1)
SELECT n0_.id AS id_0, n0_.type AS type_1, n0_.header AS header_2, n0_.message AS message_3, n0_.date_added AS date_added_4, n0_.icon_class AS icon_class_5, n0_.is_read AS is_read_6, n0_.deduplicate AS deduplicate_7 FROM notifications n0_ WHERE n0_.user_id = 1 AND n0_.is_read = 0 ORDER BY n0_.date_added DESC LIMIT 200
```

You can see that we **saved 10 queries** on a single request!

The caching and the cache invalidation is implemented in a generic way, so it is very easy to add that to other places within the codebase. See below how the cache with automatic invalidation was implemented for the `User` entity

- [Make the entity ready for the cache auto invalidation](https://github.com/mautic/mautic/pull/13073/commits/a33b41b32a2bce629b15c6098a71da071a080a4c#diff-c358558fd16be3fe003aa7f096514fd1416d3979f15e54df6bde95ea1a014769R19)
- [Execute the query using the result cache](https://github.com/mautic/mautic/pull/13073/commits/a33b41b32a2bce629b15c6098a71da071a080a4c#diff-efbe6d2d155c58e781f7affa192e8b6661a0081387386e5c5dd87d8c38ea0363R80)

The caching can be easily enabled to both ORM and DBAL queries. See the helper methods:

- [ResultCacheHelper::enableOrmQueryCache()](https://github.com/mautic/mautic/blob/a33b41b32a2bce629b15c6098a71da071a080a4c/app/bundles/CoreBundle/Cache/ResultCacheHelper.php#L18)
- [ResultCacheHelper::executeCachedDbalQuery()](https://github.com/mautic/mautic/blob/a33b41b32a2bce629b15c6098a71da071a080a4c/app/bundles/CoreBundle/Cache/ResultCacheHelper.php#L38)

By default the [array cache adapter](https://github.com/mautic/mautic/blob/a33b41b32a2bce629b15c6098a71da071a080a4c/app/config/config.php#L272) is used which does not require any configuration. The queries are cached only within a given http request. You need to configure your own cache adapter to fully utilize the query result caching. In the example below I used Redis as an cache adapter.

```php
// config/config_override.php
<?php

use Predis\Client;
use Symfony\Component\Cache\Adapter\RedisAdapter;
use Symfony\Component\DependencyInjection\Reference;

$container->register(Client::class)
    ->addArgument('tcp://redis:6379');

$container->register(RedisAdapter::class)
    ->addArgument(new Reference(Client::class))
    ->addArgument('orm_result_cache')
    ->addArgument(60 * 60);

$container->loadFromExtension('doctrine', [
    'orm' => [
        'result_cache_driver' => [
            'type' => 'service',
            'id'   => RedisAdapter::class,
        ],
    ],
]);

```

#### Steps to test this PR:

The PR introduce the cache in various places. See the list below to have an idea what needs to be tested.

1. Configure a persistent cache adapter like Redis, Memcache, ...
2. Custom fields
    - Make sure that changes (creating, updating and deleting) made on custom fields are correctly reflected on contacts and companies.
3. Plugins
    - Choose one of the plugins and make sure that changes in that plugins settings are respected.
4. User
    - Make sure that changes to users, roles and permissions are respected.

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
The code changes look great! Nice, clean implementation of very useful and extensible query caching layer 👍

**Review by kuzmany — APPROVED** [review]
Seems good to me on our side.
We played with similar apprach , good to see final solution.

**Comment by galvani** [comment]
@fedys this is really nice job.

**Comment by fedys** [comment]
Thanks @galvani!

**Pull request merged**
