### PR TITLE
Updating symfony/flex 

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

because composer install fails with
```
Fatal error: Declaration of Symfony\Flex\Command\RemoveCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Composer\Command\RemoveCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /var/www/html/vendor/symfony/flex/src/Command/RemoveCommand.php on line 30
```

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. CI must be green. It was failing because of this error.

### CODE REVIEW

**Review by patrykgruszka — APPROVED** [review]
symfony/flex bumped to the last compatible version, changes look fine

**Comment by RCheesley** [comment]
Tried to test this on Gitpod but it seems there are some (probably unrelated) issues, will try again later unless someone else gets there first!

**Comment by escopecz** [comment]
It's failing with
```
', stderr='redis-commander Pulling 
redis Pulling 
339de151aab4 Pulling fs layer 
f732fa32fc61 Pulling fs layer 
...
23acdbbf5eef Extracting     572B/572B
23acdbbf5eef Pull complete 
redis Pulled 
1 error occurred:
        * Status: The command '/bin/sh -c apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests php7.4-imap' returned a non-zero code: 100, Code: 100
```
It seems we'll need to duplicate https://github.com/mautic/mautic/pull/13550 for 4.4 branch as well.

**Comment by escopecz** [comment]
I cherry-picked the commit https://github.com/mautic/mautic/pull/13550/commits/564e5e24d40b3863680a625c788cb21a1c6d5786 into this PR so we can test both here.

**Comment by escopecz** [comment]
It's failing with
```
Reading package lists...
W: GPG error: https://packages.sury.org/php bullseye InRelease: The following signatures were invalid: EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
E: The repository 'https://packages.sury.org/php bullseye InRelease' is not signed.
```
Anyone available to debug that?
cc @mollux

**Comment by mallezie** [comment]
Tested the composer.lock changes manually and this get's through the composer install phase on local M4. Those changes do look good. 
Persobally i would focus on getting those in first before fixing gitpod.

**Review by mallezie — APPROVED** [review]

**Review by shinde-rahul — APPROVED** [review]
LGTM. 
Thanks, @escopecz!!

**Pull request merged**
