### PR TITLE
Tokens can use the Label instead of value of select fields

### PR DESCRIPTION
**Pull request by volha-pivavarchyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR adds labels of select and multiselect custom fields to emails instead of values. This corresponds to the contact profile.

Contact's profile
image

Email
image

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a new custom field with the select or/and multiple select type.
3. Assign the field to a contact.
4. Create new segment and template emails and add token {contactfield=<created field>}
5. Send emails. The label is used in emails.

### CODE REVIEW

**Comment by kuzmany** [comment]
Some customers wanted to use values instead of labels.
Also for me it's BC if somebody process emails and expect values, then it stop working for it.

We resolve it before with {contactfield=select_alias|label} variant for select and boolean types
https://github.com/mautic/mautic/pull/10626

**Review by escopecz — CHANGES_REQUESTED** [review]
I'm wondering whether it shouldn't be the `normalizedValue` every time? If not, I'd suggest to create a new method `getProfileFieldsWithNormalizedValues()` that will do this instead of adding the param. It's not very readable what the param does.

Could you write tests for this?

**Comment by npracht** [comment]
@escopecz i strongly suggest to close this PR and invest effort on https://github.com/mautic/mautic/pull/10626 which is much more flexible.
@volha-pivavarchyk are you ok to review https://github.com/mautic/mautic/pull/10626 instead please ?

**Comment by volha-pivavarchyk** [comment]
@npracht 
I am ok to review. I can do it next week. I've been overloaded the last two weeks, and couldn't respond to the review. At first sight I agree with @kuzmany about the solution {contactfield=select_alias|label}. But I didn't have time to pay attention. I'll do it and test the PR.

**Comment by npracht** [comment]
No problem, i know we all do this on community side depending on our availabilities. I just wanted to double check which solution we should keep.

**Comment by volha-pivavarchyk** [comment]
Closing in favor PR #10626

**Pull request closed without merging**
