### PR TITLE
Fix prevent save alias of contact field already used in segments

### LINKED ISSUE #9647: Add reserved keywords to create custom fields alias
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
- [x] contact_id
- [x] company_id
- [x] source
- [x] campaign

If you create custom field with alias `campaign` then you're not able to use segment filter campaign membership. This filter use same naming 'campaign' and If you try use campaign membership filter, query is made  as custom field.

It would be good to make reserved keywords during the alias already exists validation for custom field. This could be provide by dispatcher to allow plugin extend that list.

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### PR DESCRIPTION
**Pull request by Damzoneuh**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features, enhancements and bug fixes (until 3.3.0 is released) 
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | no
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
Custom field alias generation was using reserved words, This PR prevents it.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create custom field with company_id or contact_id alias
3. Submit
4. Check if the field is created (You should have an error)
5. Create custom field with random alias 
6. Submit
7. Check if field is created (You should have your field created)

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10224"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for the PR @Damzoneuh and welcome to the Mautic Community! 🎉

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by Damzoneuh** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@Damzoneuh it looks like you've got a codestyle issue to address with this PR - while you're at it, could you rebase onto the 4.1 branch? Hoping to get this in for the 4.1.1 release.

**Review by RCheesley — DISMISSED** [review]
Thanks for the PR @Damzoneuh - works as described and prevented me from using these terms as the alias for the custom field. Just need a code review and it will be good to go!

**Review by volha-pivavarchyk — APPROVED** [review]
Works as expected

**Comment by RCheesley** [comment]
@all-contributors please add @Damzoneuh for code

**Pull request merged**
