### PR TITLE
Report email stats enhacement

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
This PR change logic to generate email stats (Data Source: Email).

Before update the emails are listed with date_added limit  and numbers (sent, read, unsubscribed) are loaded global for all period. This a lot of users make confused.

Now
- If Hide date range is enabled - the dater range filter don't apply https://github.com/mautic/mautic/pull/7214/files#diff-5295a31f5d6a0e3c5ab1b7d4bc36f45dR373  . Thats what we expect, If I don't see date range forms, then date range cannot be apply to query.
- Data Source: Email - with date range now loaded emails active from date range and related stats (unsubscribed, ratio, read etc). That means If choose range last month, then I will see just emails and stats to that related month. 

With enabled **Hide date range** SQL use the global dat from **emails table** (sent_count, read_count ...)
With disable **Hide date range** SQL query create **inner JOIN** to other huge tables (page_hits, email_stats..) with date range limit. This prevent load the large table more times. 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com/7214) or load to you local enviroment with stats
2. Jus retest both case
- If Hide date range is enabled/disabled
image
- If enabled - then try load custom date range and see If stats are related and what do you expect from that range
If disabled - see global stats to each email
Also try filters for both state

image

#### List deprecations along with the new alternative:
1. 
2. 

#### List backwards compatibility breaks:
1. 
2.

### CODE REVIEW

**Review by npracht — COMMENTED** [review]
I think there is an issue, i'm running the creation of a new report on a DB with data and the creation of the report is running still running for ages.
Here is the query:
```sql
SELECT SUM(DISTINCT e.sent_count) as sent_count, SUM(DISTINCT e.read_count) as read_count, count(CASE WHEN dnc.id and dnc.reason = 1 THEN 1 ELSE null END) as unsubscribed, count(CASE WHEN dnc.id and dnc.reason = 2 THEN 1 ELSE null END) as bounced FROM emails e LEFT JOIN emails vp ON vp.id = e.variant_parent_id INNER JOIN email_stats es ON e.id = es.email_id LEFT JOIN categories c ON c.id = e.category_id LEFT JOIN (SELECT COUNT(cut2.channel_id) AS trackable_count, SUM(cut2.hits) AS hits, SUM(cut2.unique_hits) AS unique_hits, cut2.channel_id FROM channel_url_trackables cut2 WHERE cut2.channel = 'email' GROUP BY cut2.channel_id) cut ON e.id = cut.channel_id LEFT JOIN lead_donotcontact dnc ON e.id = dnc.channel_id AND dnc.channel='email' WHERE es.date_sent IS NULL OR (es.date_sent BETWEEN '2019-01-05 23:00:00' AND '2019-02-06 09:09:14')
```

**Comment by kuzmany** [comment]
@npracht this could be related to this PR https://github.com/mautic/mautic/pull/7221

**Review by npracht — DISMISSED** [review]
**Tested and i confirm it works. this is such an amazing improvement to follow email stats in time !!**
🍾

**Comment by johbuch** [comment]
@kuzmany seems much better with your last commit ! thanks ;)

**Review by npracht — CHANGES_REQUESTED** [review]
# Error
1. Create an `emails` type report
2. Add columns ID, Name, Unsub ratio
3. See error 500

```
 500 Internal Server Error - An exception occurred while executing 'SELECT count(*) FROM (SELECT e.id AS e_id1, e.name AS e_name1, CONCAT('', ROUND(IFNULL((dnc.unsubscribed/stats.sent_count)*100,0),2),'%') AS unsubscribed_ratio1 FROM 7214_emails e LEFT JOIN 7214_emails vp ON vp.id = e.variant_parent_id LEFT JOIN 7214_categories c ON c.id = e.category_id LEFT JOIN (SELECT SUM(IF(donot.reason = 1,1, 0)) as unsubscribed, SUM(IF(donot.reason = 2,1, 0)) as bounced, donot.channel_id as channel_id FROM 7214_lead_donotcontact donot WHERE (donot.date_added BETWEEN ? AND ?) AND (donot.channel='email') GROUP BY donot.channel_id) dnc ON e.id = dnc.channel_id GROUP BY e.id) c' with params ["2019-06-02 00:00:00", "2019-07-02 09:52:54"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'stats.sent_count' in 'field list' 
```

```
/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71 at
/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:128 at Doctrine\DBAL\Driver\AbstractMySQLDriver -> convertException ( 'An exception occurred while executing 'SELECT count(*) FROM (SELECT e.id AS e_id1, e.name AS e_name1, CONCAT('', ROUND(IFNULL((dnc.unsubscribed/stats.sent_count)*100,0),2),'%') AS unsubscribed_ratio1 FROM 7214_emails e LEFT JOIN 7214_emails vp ON vp.id = e.variant_parent_id LEFT JOIN 7214_categories c ON c.id = e.category_id LEFT JOIN (SELECT SUM(IF(donot.reason = 1,1, 0)) as unsubscribed, SUM(IF(donot.reason = 2,1, 0)) as bounced, donot.channel_id as channel_id FROM 7214_lead_donotcontact donot WHERE (donot.date_added BETWEEN ? AND ?) AND (donot.channel='email') GROUP BY donot.channel_id) dnc ON e.id = dnc.channel_id GROUP BY e.id) c' with params ["2019-06-02 00:00:00", "2019-07-02 09:52:54"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'stats.sent_count' in 'field list'', object(PDOException) )
/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:855 at Doctrine\DBAL\DBALException :: driverExceptionDuringQuery ( object(Driver), object(PDOException), 'SELECT count(*) FROM (SELECT e.id AS e_id1, e.name AS e_name1, CONCAT('', ROUND(IFNULL((dnc.unsubscribed/stats.sent_count)*100,0),2),'%') AS unsubscribed_ratio1 FROM 7214_emails e LEFT JOIN 7214_emails vp ON vp.id = e.variant_parent_id LEFT JOIN 7214_categories c ON c.id = e.category_id LEFT JOIN (SELECT SUM(IF(donot.reason = 1,1, 0)) as unsubscribed, SUM(IF(donot.reason = 2,1, 0)) as bounced, donot.channel_id as channel_id FROM 7214_lead_donotcontact donot WHERE (donot.date_added BETWEEN ? AND ?) AND (donot.channel='email') GROUP BY donot.channel_id) dnc ON e.id = dnc.channel_id GROUP BY e.id) c', array('2019-06-02 00:00:00', '2019-07-02 09:52:54') )
/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206 at Doctrine\DBAL\Connection -> executeQuery ( 'SELECT count(*) FROM (SELECT e.id AS e_id1, e.name AS e_name1, CONCAT('', ROUND(IFNULL((dnc.unsubscribed/stats.sent_count)*100,0),2),'%') AS unsubscribed_ratio1 FROM 7214_emails e LEFT JOIN 7214_emails vp ON vp.id = e.variant_parent_id LEFT JOIN 7214_categories c ON c.id = e.category_id LEFT JOIN (SELECT SUM(IF(donot.reason = 1,1, 0)) as unsubscribed, SUM(IF(donot.reason = 2,1, 0)) as bounced, donot.channel_id as channel_id FROM 7214_lead_donotcontact donot WHERE (donot.date_added BETWEEN ? AND ?) AND (donot.channel='email') GROUP BY donot.channel_id) dnc ON e.id = dnc.channel_id GROUP BY e.id) c', array('2019-06-02 00:00:00', '2019-07-02 09:52:54'), array('2', '2') )
/app/bundles/ReportBundle/Model/ReportModel.php:777 at Doctrine\DBAL\Query\QueryBuilder -> execute ( )
/app/bundles/ReportBundle/Model/ReportModel.php:654 at Mautic\ReportBundle\Model\ReportModel -> getTotalCount ( object(QueryBuilder), array('count_query' => 'SELECT count(*) FROM (SELECT e.id AS e_id1, e.name AS e_name1, CONCAT('', ROUND(IFNULL((dnc.unsubscribed/stats.sent_count)*100,0),2),'%') AS unsubscribed_ratio1 FROM 7214_emails e LEFT JOIN 7214_emails vp ON vp.id = e.variant_parent_id LEFT JOIN 7214_categories c ON c.id = e.category_id LEFT JOIN (SELECT SUM(IF(donot.reason = 1,1, 0)) as unsubscribed, SUM(IF(donot.reason = 2,1, 0)) as bounced, donot.channel_id as channel_id FROM 7214_lead_donotcontact donot WHERE (donot.date_added BETWEEN :dateFrom AND :dateTo) AND (donot.channel='email') GROUP BY donot.channel_id) dnc ON e.id = dnc.channel_id GROUP BY e.id) c') )
/app/bundles/ReportBundle/Controller/ReportController.php:665 at Mautic\ReportBundle\Model\ReportModel -> getReportData ( object(Report), object(FormFactory), array('dynamicFilters' => array(), 'paginate' => true, 'reportPage' => '1', 'dateFrom' => object(DateTime), 'dateTo' => object(DateTime), 'translator' => object(DataCollectorTranslator), 'chartQuery' => object(ChartQuery)) )
/vendor/symfony/http-kernel/HttpKernel.php:135 at Mautic\ReportBundle\Controller\ReportController -> viewAction ( '8', '1' )
/vendor/symfony/http-kernel/HttpKernel.php:57 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '2' )
/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php:67 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '2', true )
/vendor/symfony/framework-bundle/Controller/Controller.php:69 at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel -> handle ( object(Request), '2' )
/app/bundles/CoreBundle/Controller/CommonController.php:385 at Symfony\Bundle\FrameworkBundle\Controller\Controller -> forward ( 'MauticReportBundle:Report:view', array('objectId' => '8', '_controller' => 'MauticReportBundle:Report:view'), array('ignoreAjax' => true, 'request' => object(Request), 'subrequest' => true) )
/app/bundles/CoreBundle/Controller/CommonController.php:315 at Mautic\CoreBundle\Controller\CommonController -> ajaxAction ( array('returnUrl' => '/7214/s/reports/view/8', 'viewParameters' => array('objectId' => '8'), 'contentTemplate' => 'MauticReportBundle:Report:view', 'passthroughVars' => array('activeLink' => 'mautic_asset_index', 'mauticContent' => 'asset'), 'forwardController' => true) )
/app/bundles/ReportBundle/Controller/ReportController.php:516 at Mautic\CoreBundle\Controller\CommonController -> postActionRedirect ( array('returnUrl' => '/7214/s/reports/view/8', 'viewParameters' => array('objectId' => '8'), 'contentTemplate' => 'MauticReportBundle:Report:view', 'passthroughVars' => array('activeLink' => 'mautic_asset_index', 'mauticContent' => 'asset'), 'forwardController' => true) )
/app/bundles/CoreBundle/Controller/CommonController.php:475 at Mautic\ReportBundle\Controller\ReportController -> newAction ( object(Report), '' )
/vendor/symfony/http-kernel/HttpKernel.php:135 at Mautic\CoreBundle\Controller\CommonController -> executeAction ( 'new', '0', '0', '' )
/vendor/symfony/http-kernel/HttpKernel.php:57 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '1' )
/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php:67 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '1', true )
/vendor/symfony/http-kernel/Kernel.php:183 at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel -> handle ( object(Request), '1', true )
/app/AppKernel.php:141 at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), '1', true )
/app/middlewares/CORSMiddleware.php:93 at AppKernel -> handle ( object(Request), '1', true )
/app/middlewares/CatchExceptionMiddleware.php:45 at Mautic\Middleware\CORSMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/Dev/IpRestrictMiddleware.php:55 at Mautic\Middleware\CatchExceptionMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/VersionCheckMiddleware.php:57 at Mautic\Middleware\Dev\IpRestrictMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23 at Mautic\Middleware\VersionCheckMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/run/src/Stack/run.php:13 at Stack\StackedHttpKernel -> handle ( object(Request) )
/index_dev.php:33 at Stack\run ( object(StackedHttpKernel) )
/index.php:6 at require_once ( '/var/app/current/code/pulls/7214/index_dev.php' )
```

**Comment by kuzmany** [comment]
@npracht please test last commit

**Review by npracht — DISMISSED** [review]
👍

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by npracht** [comment]
Closing in favor of https://github.com/mautic/mautic/pull/8711 which is rebased for M3

**Pull request closed without merging**
