### PR TITLE
TPROD-311 - ConfigBundle - Convert PHP Templates to Twig Templates

### PR DESCRIPTION
**Pull request by JoshuaEstes**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. 

* Navigate to `/s/config/edit` and verify each tab renders correctly
* Navigate to `/s/sysinfo` and verify it renders correctly

### CODE REVIEW

**Review by mabumusa1 — DISMISSED** [review]
- [X] All the tabs in the config menu shows correctly 
image

- [X] System Info works as expected 
image

**Review by kuzmany — CHANGES_REQUESTED** [review]
Monitored inboxes ruined in Emails Settings tab 

image

Messenger setings  are broken (probably not related to PR)

image

**Comment by jos0405** [comment]
@JoshuaEstes
I can confirm the same issue as Zdeno above.
Additionally:
Screenshot 2023-02-09 at 14 47 23
See "code".

**Comment by jos0405** [comment]
@mabumusa1 @JoshuaEstes 
Is this part changing because of symfony messenger?
Screenshot 2023-02-09 at 14 48 17
I can see the new menu "Messenger Settings" that should handle that?

**Review by jos0405 — CHANGES_REQUESTED** [review]
Plz

- fix "code" in the SAML SSO header

**Comment by mabumusa1** [comment]
@jos0405 yes, there is a new tab added called messenger settings, email settings are still as is.

There is another PR to merged that will change these settings

**Comment by JoshuaEstes** [comment]
@kuzmany @jos0405 

> Monitored inboxes ruined in Emails Settings tab

Resolved: https://github.com/mautic/mautic/pull/11938/commits/11fababea0479526f50461731706528698dca75a

> fix "code" in the SAML SSO header

Resolved: https://github.com/mautic/mautic/pull/11938/commits/408d8ba1c967fd8d6d06bdeb0e42ab03204e6253

> Messenger setings are broken (probably not related to PR)

I'm not able to reproduce the strange symbols in these fields.

---

For the most part, the conversion from the PHP templates to Twig templates, if done with no typos or errors, shouldn't do anything. It should look and function the same as what you see on the 5.x branch.

Currently on the 5.x branch, a few of these tabs are not formatted. Also, there were a few inconsistencies as to how things were formatted. When I noticed things like that, I make sure to try to keep the look similar. Also, when I find simple/easy bugs that exist on the 5.x branch, I'll make sure to fix those as well.

Let me know if there is anything else

**Review by kuzmany — APPROVED** [review]
Looks good to me 👍

**Review by jos0405 — APPROVED** [review]
Looks good, issues addressed.

**Pull request merged**
