### PR TITLE
[UX] Disable "Visible on quick add" when creating a Custom Field for Company object with data-disable-on

### LINKED ISSUE #14178: "Visible on quick add" should be disabled when creating a Custom Field for Company object
### Mautic Series

5.1.x series

### Mautic installed version

5.x

### Way of installing

I cloned the Mautic repo (not recommended or supported)

### PHP version

Not relevant

### What browsers are you seeing the problem on?

Chrome

### What happened?

When creating a custom field, you have some options like choosing whether your field will be available for contacts or companies. When you select the object Contact, it makes sense to provide the option "Visible on quick add", because contacts actually have the quick add functionality where you make this field available on a modal with some other few fields to avoid opening the screen where all contact fields are displayed.

But when you are creating a custom field for a company, you do not have the quick add functionality,  but this toggle keeps visible and interactive anyway. That's problematic and confusing for the user because no matter what you choose, absolutely nothing will happen.

To fix this, the `<div class="toggle">` element for the field "Visible on quick add" must receive the class `toggle--disabled` when Object is set to Company, so the final element becomes `<div class="toggle toggle--disabled">` to block user interaction and display the not-allowed cursor.

### How can we reproduce this issue?

1. Open Custom Fields
2. Create New
3. In the select field Object, choose Company
4. See that the toggle for Visible on quick add remains active and interactive

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by laurielim**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes [#14178](https://github.com/mautic/mautic/issues/14178)

## Description
In this PR, i've modified switchFormFieldVisibilty to switchFormFieldState so that you can add the following attributes:
- data-disable-on (new)
- data-enable-on (new)
- data-show-on
- data-hide-on

Based on the state, the element will be either visible or disabled. Disabled means that a disable class witll be added to the input.

Additionally, I updated the styling for toggle elements so that the element will look/be disabled if it has child element with class `disabled`.

This implementation is based on discussion on #14211

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open Custom Fields
3. Create a new custom field
4. Set "Visible on quick add" to yes
5. Change Object to company and see that "Visible on quick add" is disabled and set to "No" automatically
6. Fill the required fields and hit save
7. The page should refresh and the field should still be disabled.
8. Repeat step 3 & 4
9. Change Object back to contact and the field should be enabled again
10. Fill the required fields and hit save
11. The page should refresh and the field should still be enabled.

Also see that `data-show-on` still works
  - Create a new custom field
  - See that `Maximum character length` is only visible when the following are selected as Data Type:
    - text - Text: Short answer
    - select -Select: Single choice
    - email - Email
    - url - URL
    - phone - ??? (Phone has value tel, may be a bug)

### CODE REVIEW

**Review by escopecz — DISMISSED** [review]
It works nicely:

https://github.com/user-attachments/assets/81263509-5336-4d03-b6d6-b0434598eaae

I also tested that the original `data-show-on` still works too:

https://github.com/user-attachments/assets/ad9b7804-71da-48b3-9e18-6e5d0459c111

**Review by andersonjeccel — CHANGES_REQUESTED** [review]
We still have a way to create custom fields for Company with Visible on quick add On

image

When disabling toggles, we have to ensure they are updated to no (or cleared in case of select fields)

**Comment by laurielim** [comment]
I added a resetField that will reset Yes/No toggles to No if disabled.

Not sure how to go about it with `select` fields, based on Group and Data Type where they have values by default so what happens if they get disabled but then enabled again?

**Comment by andersonjeccel** [comment]
@laurielim it's perfect now, thanks!

the `select` fields stuff is what I did here to clear the chosen theme: https://github.com/mautic/mautic/pull/14003

it's basically clearing the value from the field, but I'm not sure how much reliable would be to change your JS to tackle cases where the input is text, or selection etc

so we can finish this way for now

**Pull request merged**
