### PR TITLE
Fixing bug where the company/contact relationship was not created aft…

### PR DESCRIPTION
**Pull request by escopecz**
…er the submission of a form with the company field

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Related user documentation PR URL | /
| Related developer documentation PR URL | /
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/3425
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
The companies weren't created and the relationship with contact was not created on form submission when the form contained the company field.

#### Steps to test this PR:
1. Apply this PR.
2. Repeat the test - the company should be there.
3. Test with existing company - it should only create the relationship with the contact, not create another company.
4. Test with a new company - it should create the company and the relationship with the contact.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a form with the company field.
2. Map the form field with the company contact field.
3. Submit the form in a incognito browser window.
4. Open the form results page and click on the date.
5. You should be redirected to the contact who submitted the form.
- The company is not there.

### CODE REVIEW

**Comment by mqueme** [comment]
This does map the company to a contact created, but it's not fill in other fields (in may case I had, email, first name and company, it only filled in company), it only identifies a contact through ip address, but not through main identifiers such as email address

**Comment by escopecz** [comment]
Good catch @mqueme! Test it with the last commit, please.

**Comment by mqueme** [comment]
it now fills in the other fields, but it doesn't identify the contact based on Is Unique Identifier such as email.

**Comment by escopecz** [comment]
Closing in favour of https://github.com/mautic/mautic/pull/3449

**Pull request closed without merging**
