### PR TITLE
Sync leaking memory

### PR DESCRIPTION
**Pull request by hluchas**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | 3.0 for bug fixes
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          |no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | -
| Related developer documentation PR URL | -
| Issue(s) addressed                     | -

#### Description:
Sync is leaking memory with huge amount of data. After measurement we decided to fix growing array in `CommonRepository::usedParameterNames`

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Try to sync data with any plugin
3. Try to use segments & segment build
4. View contacts in UI

### CODE REVIEW

**Comment by hluchas** [comment]
This has the same problem as here https://github.com/mautic/mautic/pull/9297#issuecomment-708324891 , but target is correct for bugfix

**Comment by escopecz** [comment]
@hluchas can you double-check? The 3.1 branch and the staging branch both have the condition correct: https://github.com/mautic/mautic/blob/3.1/app/bundles/FormBundle/Helper/FormUploader.php#L154 https://github.com/mautic/mautic/blob/staging/app/bundles/FormBundle/Helper/FormUploader.php#L154

Your base must be off.

**Comment by hluchas** [comment]
@escopecz Fixed in https://github.com/mautic/mautic/pull/9299/commits/7820a2f172d9227b41049735c39aff5baf8ccabc
Taking a look on https://github.com/mautic/mautic/pull/9297 with the same prob
TY!

**Review by kuzmany — DISMISSED** [review]
Works for me. 
I sync our integration and rebuild segments.
Code looks good.
Unit tests included, then approve it 👍

**Comment by RCheesley** [comment]
GTG when tests pass based on the dismissed review and that it has test coverage.

**Comment by hluchas** [comment]
I added missing coverage ;-)

**Review by kuzmany — APPROVED** [review]

**Comment by RCheesley** [comment]
@all-contributors please add @hluchas for code

**Pull request merged**
