### PR TITLE
Skip field import If value exists

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Yes
| Automated tests included? |
| Related user documentation PR URL | https://github.com/mautic/mautic-documentation/pull/156
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | No
| Deprecations? | No

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
I got feature request from community to add option to import.
Skip field import If contact's field value already exists.
This is useful If we wanna import just data and not overwrite already existed data.

image

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com/7460)
2. Try import data (email, customfield)
3. Then change customfield in contact profile
4. Then create new import and enable Skip field import If value exists
5. The customfield shouldn't be imported
6. Then remove value from customfield 
7. Create new import and enable Skip field import If value exists
8. The customfield should be imported
9. Same steps to test company import

### CODE REVIEW

**Review by dsp76 — COMMENTED** [review]
Tested it with Mautibox, worked as described.

**Comment by stevedrobinson** [comment]
Tested with Mauticbox, works as expected. Great work, @kuzmany!

**Comment by stevedrobinson** [comment]
Tested updates to include on company import and looks good.

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by kuzmany** [comment]
Rebased

**Comment by kuzmany** [comment]
@dsp76 @stevedrobinson Can you re-test now for Mautic 3 on https://m3.mautibox.com/7460?

**Review by RCheesley — CHANGES_REQUESTED** [review]
@kuzmany I am testing this out locally.

Tested importing the data on Staging, all fine. Import file is uploaded without incident, data is imported. 

Pulled your PR and cleared the cache.

Tried to upload a set of sample data, and I got the following error when trying to upload the file:

```
[2020-08-15 09:01:50] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\InvalidArgumentException: "Could not load type "yesno_button_group": class does not exist." at /Users/ruth.cheesley/Sites/local.mautic3/mautic/vendor/symfony/form/FormRegistry.php line 86 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\InvalidArgumentException(code: 0): Could not load type \"yesno_button_group\": class does not exist. at /Users/ruth.cheesley/Sites/local.mautic3/mautic/vendor/symfony/form/FormRegistry.php:86)
[stacktrace]
#0 /Users/ruth.cheesley/Sites/local.mautic3/mautic/vendor/symfony/form/FormFactory.php(74): Symfony\\Component\\Form\\FormRegistry->getType('yesno_button_gr...')
#1 /Users/ruth.cheesley/Sites/local.mautic3/mautic/vendor/symfony/form/FormBuilder.php(98): Symfony\\Component\\Form\\FormFactory->createNamedBuilder('skip_if_exists', 'yesno_button_gr...', NULL, Array)
#2 /Users/ruth.cheesley/Sites/local.mautic3/mautic/vendor/symfony/form/FormBuilder.php(252): Symfony\\Component\\Form\\FormBuilder->create('skip_if_exists', 'yesno_button_gr...', Array)
#3 /Users/ruth.cheesley/Sites/local.mautic3/mautic/vendor/symfony/form/FormBuilder.php(199): Symfony\\Component\\Form\\FormBuilder->resolveChildren()
#4 /Users/ruth.cheesley/Sites/local.mautic3/mautic/vendor/symfony/form/FormFactory.php(30): Symfony\\Component\\Form\\FormBuilder->getForm()
#5 /Users/ruth.cheesley/Sites/local.mautic3/mautic/app/bundles/LeadBundle/Controller/ImportController.php(219): Symfony\\Component\\Form\\FormFactory->create('Mautic\\\\LeadBund...', Array, Array)
#6 /Users/ruth.cheesley/Sites/local.mautic3/mautic/app/bundles/CoreBundle/Controller/CommonController.php(449): Mautic\\LeadBundle\\Controller\\ImportController->newAction(0, '')
#7 /Users/ruth.cheesley/Sites/local.mautic3/mautic/vendor/symfony/http-kernel/HttpKernel.php(151): Mautic\\CoreBundle\\Controller\\CommonController->executeAction('new', 0, 0, '')
#8 /Users/ruth.cheesley/Sites/local.mautic3/mautic/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)
#9 /Users/ruth.cheesley/Sites/local.mautic3/mautic/vendor/symfony/http-kernel/Kernel.php(200): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#10 /Users/ruth.cheesley/Sites/local.mautic3/mautic/app/AppKernel.php(104): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#11 /Users/ruth.cheesley/Sites/local.mautic3/mautic/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#12 /Users/ruth.cheesley/Sites/local.mautic3/mautic/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#13 /Users/ruth.cheesley/Sites/local.mautic3/mautic/app/middlewares/Dev/IpRestrictMiddleware.php(61): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#14 /Users/ruth.cheesley/Sites/local.mautic3/mautic/app/middlewares/VersionCheckMiddleware.php(67): Mautic\\Middleware\\Dev\\IpRestrictMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#15 /Users/ruth.cheesley/Sites/local.mautic3/mautic/app/middlewares/TrustMiddleware.php(51): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#16 /Users/ruth.cheesley/Sites/local.mautic3/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\TrustMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)
#17 /Users/ruth.cheesley/Sites/local.mautic3/mautic/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))
#18 /Users/ruth.cheesley/Sites/local.mautic3/mautic/index_dev.php(25): Stack\
un(Object(Stack\\StackedHttpKernel))
#19 {main}
"} 

```

I have double checked that:

* I have pulled down the PR correctly (using the Github CLI)
* I have cleared the cache
* This works perfectly fine on staging, breaks as soon as I load up your PR

This is all done in dev mode.

Maybe there's an issue with the button group syntax that changed with Mautic 3.x?

**Comment by kuzmany** [comment]
@RCheesley Sorry. Fixed and re-test. Should work now

**Comment by RCheesley** [comment]
Thanks @kuzmany that's great. Looks like a couple of files need some test love:

[CompanyModel.php](https://codecov.io/gh/mautic/mautic/pull/7460/diff?src=pr&el=tree#diff-YXBwL2J1bmRsZXMvTGVhZEJ1bmRsZS9Nb2RlbC9Db21wYW55TW9kZWwucGhw)

and 

[LeadModel.php](https://codecov.io/gh/mautic/mautic/pull/7460/diff?src=pr&el=tree#diff-YXBwL2J1bmRsZXMvTGVhZEJ1bmRsZS9Nb2RlbC9MZWFkTW9kZWwucGhw)

are both decreasing coverage. Could you take a look and see if we can bump up the coverage to either not change or improve coverage %?

In the meantime I'll retest!

**Review by RCheesley — DISMISSED** [review]
Tested this and the feature works for both companies and contacts so I'm approving it, but I think the UX could be improved either in this PR, or in a future PR.

At the moment, when we do the import with the switch enabled it behaves as expected - the custom field is ignored and not overwritten.  However, in the import screen there is no notification to the user that custom fields have been ignored.

I feel like this is something that would be helpful to let the user know, because they are explicitly asking for these fields to be ignored and they get no notification that this has happened.

screenshot-local mautic3-2020 08 15-10_48_12

This will also require documentation so I'll add the flag and make sure someone from @mautic/education-team picks this up next week if we end up merging it.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by npracht** [comment]
@kuzmany could you please add few tests then we can merge it asap ? It is not only an enhancement, it is half bug i think we can milestone it 3.1.2.

**Comment by stevedrobinson** [comment]
What needs to happen to get this through? How can I help?

**Comment by kuzmany** [comment]
@stevedrobinson need write unit tests and some documentation.
I would like look on unit test soon

**Comment by npracht** [comment]
Doc added https://github.com/mautic/mautic-documentation/pull/156

**Comment by npracht** [comment]
@stevedrobinson would you feel comfortable adding tests to this PR ? I believe you can directly add them on this branch : https://github.com/kuzmany/mautic/tree/import-overwrite-not-blank then it comes into the PR :)

**Comment by stevedrobinson** [comment]
@npracht My php skills predate TDD, so I'm afraid I'm not in the best position to write the unit tests. I'm sorry I can't help.  I'm happy to test and update documentation as needed, though!

**Comment by RCheesley** [comment]
@kuzmany a conflict here and tests to increase coverage before we can merge - but it has enough tests to get merged when that is addressed!

**Comment by kuzmany** [comment]
@RCheesley unit tests added

**Review by dadarya0 — APPROVED** [review]
Code looks good and working fine for both company and contacts.

**Comment by RCheesley** [comment]
@all-contributors please add @dsp76 for userTesting

**Pull request merged**
