### PR TITLE
[UX] Sections for user management

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

Adds sections when editing users and fixes the buggy mobile layout.

https://github.com/mautic/mautic/pull/13473#issuecomment-1968182405

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Click to open the right sidebar
3. Go to Users
4. Click to open user details
5. See those new sections

Before:
image

image

After:
image

image

### CODE REVIEW

**Review by LordRembo — APPROVED** [review]
Grouping/sectioning makes sense, yeah.

**Comment by andersonjeccel** [comment]
@LordRembo Also there's a fix for the mobile layout, before it was buggy :)

**Review by shinde-rahul — APPROVED** [review]
LGTM!!!

Thanks  @andersonjeccel!!!

**Comment by andersonjeccel** [comment]
@RCheesley It would be nice if we could move this enhancement forward

**Pull request merged**
