### PR TITLE
Fix error on custom field creation

### PR DESCRIPTION
**Pull request by TheOsch**
This is a fix for https://github.com/mautic/mautic/issues/11299 .

Maybe it's not the best solution, but it makes the form work.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11320"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
@cla-bot check

Thanks for the PR @TheOsch and for signing the CLA! Welcome to the community!

**Review by RCheesley — APPROVED** [review]
I checked the PR with date, boolean and lookup fields and all are working again. This will require a code review to determine which is the most appropriate fix.

**Review by jos0405 — APPROVED** [review]
Checked various custom field formats, they all seem to work.

**Comment by escopecz** [comment]
Thank you @TheOsch! I'm closing this in favor of https://github.com/mautic/mautic/pull/11321 as this code change is suppressing the problem where https://github.com/mautic/mautic/pull/11321 is fixing it.

**Comment by TheOsch** [comment]
> Thank you @TheOsch! I'm closing this in favor of #11321 as this code change is suppressing the problem where #11321 is fixing it.

Yes, it's fair.

**Pull request closed without merging**
