### PR TITLE
Delete campaign event log using query instead on delete cascade

### PR DESCRIPTION
**Pull request by dadarya0**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix?                               | yes, from the bigger data standpoint
| New feature?                           | yes
| Deprecations?                          | yes/no
| BC breaks?                             | yes/no
| Automated tests included?              | yes
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
On campaign event deletion, event and event history was not deleting properly because on campaign delete, campaign events and event log will be deleted because of on delete cascade in foreign key relationship. 
Now campaign event log table have millions records so due to on delete cascade some time mysql stuck and not able to delete record associated record properly.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create a campaign
3. add an event to the campaign
4. Save and close
5. Edit campaign again and delete event
6. Event and event history should be deleted.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10219"></a>

### CODE REVIEW

**Comment by RCheesley** [comment]
@dadarya0 looks like you have a failing test to address in this PR - would be great if we can get that fixed so we can include this in the milestone for the 4.0.2 release!

**Comment by kuzmany** [comment]
@dadarya0 this need rebase

**Comment by escopecz** [comment]
Rebased from 4.2 to 4.x. I think this is more of an enhancement over a bug fix. CI does not want to kick in. I'll close and reopen.

**Comment by ghost** [comment]
I receive error by opening this Issue in [ Gitpod ]( https://gitpod.io/#https://github.com/mautic/mautic/pull/10219 ) 

`Status: Downloaded newer image for busybox:stable`
`docker.io/library/busybox:stable`
`Downloading https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-linux-x86_64 ... `
**`Failed to start mautic: download link https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-linux-x86_64 returned wrong status code: got 503 want 200 `**
`gitpod /workspace/mautic (delete-campaign-event-log-using-query-instead-on-delete-cascade) $ `

image

How should I test this integration?
Greetings from Germany
Ionut

**Review by escopecz — APPROVED** [review]
The code looks great. I get no errors when executing the command. Well covered by tests 👍

**Review by kuzmany — APPROVED** [review]
I did test both states of delete_campaign_event_log_in_background local.php parameter. 
Both works as expected.

**Pull request merged**
