### PR TITLE
Add support for include/exclude operator for text field with clipboard support

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features" for all features
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | https://github.com/mautic/mautic-documentation/pull/236
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:
This PR add support for include/exclude  operator for text field in segment filters.
You are able then filter for example `city include Paris|London|New York`
Values has to be divided by separator `|`
Also it support copy from clipboard from excel column. You can copy values and paste to input. Values will be processed to `|` list of values.

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Create 3 contacts with zip code: 1,2,3
3. Create segment with zip code filter include 1|2
4. Rebuild segment
5. See first two contacts are assign to segment
8. Create excel and fill 2 and 3 to column
9. Copy it
10. Go back to segment filter and paste value to zip code filter
11. You should see 2|3 
12. Reload segments
13. You should see contact 2 and contact 3 in segment

This PR require `mautic:assets:generate`

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/10256"></a>

### CODE REVIEW

**Review by RCheesley — COMMENTED** [review]
Tested this PR and the feature works, but when I pasted in from LibreOffice or a GSheet, I did not get the pipe appearing (in Dev mode):

screenshot-mautic4 ddev site-2021 07 16-13_48_52

I do not have MS Office to test that part of the PR with so someone else will need to do that!

So a ✅  for the main feature and a ❓ for the pasting from Excel part!

**Comment by kuzmany** [comment]
@RCheesley we tested it with GSheet too. This PR use change in assets, If you are in dev mode try in incognito window.

**Comment by RCheesley** [comment]
OK will give it a go - I was in dev mode so assumed I didn't need to regenerate to assets after pulling the PR - maybe that's a wrong assumption! 😊

**Comment by kuzmany** [comment]
@RCheesley In dev you don't need regenerate assets, but you need refresh browser cache. Incognito window is the best for the case

**Comment by RCheesley** [comment]
Even after regeneration of assets and clearing the browser cache I am still getting the same.

Screen recording here: https://youtu.be/3jUGSRDKf5M

**Comment by kuzmany** [comment]
@RCheesley I'll test it again

**Comment by kuzmany** [comment]
@RCheesley I tested google sheets and work for me http://somup.com/critYtYwNq 
@npracht can you test it too?

**Comment by npracht** [comment]
I've added user doc. I'll retest with ddev :)
https://github.com/mautic/mautic-documentation/pull/236

**Review by npracht — DISMISSED** [review]
Works perfectly on my side ! ✅ 
https://recordit.co/SXeD0dxyBL

**Comment by jos0405** [comment]
Tested works as expected.
image
image

**Comment by RCheesley** [comment]
PHPSTAN issue here too @kuzmany :) 

cc @escopecz

**Comment by kuzmany** [comment]
@escopecz thanks for resolve phpstan conflicts ;)

**Pull request merged**
