### PR TITLE
Fetch the list of IP's from Maxmind that should not be tracked due to CCPA requests

### PR DESCRIPTION
**Pull request by lukassykora**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | Y
| Automated tests included? | Y
| Related user documentation PR URL | 
| Related developer documentation PR URL | https://dev.maxmind.com/geoip/privacy-exclusions-api/
| Issues addressed (#s or URLs) | 
| BC breaks? | MaxMind auth information must be in the form: ID:LicenseKey
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Steps to test this PR:
0. Set up Maxmind in your Mautic instance (see [docs](https://docs.mautic.org/en/setup/maxmind-license))
0. Load up [this PR](https://mautibox.com) 
1. Add to your local.php file the following to specify the file path: `'maxmind_do_not_sell_list_path' => './maxmind.json',`
 **NOTE: Change your license key settings to AccountID:Licensekey. Account ID is displayed above the license keys table**
2. Run  `bin/console mautic:donotsell:download`
3. Check the JSON file in the path specified above

#### List backwards compatibility breaks:
1. MaxMind auth information must be in the form: ID:LicenseKey

### CODE REVIEW

**Comment by hluchas** [comment]
@lukassykora could you. please resolve the conflict?
Blocker for https://github.com/mautic/mautic/pull/8769

**Comment by RCheesley** [comment]
@lukassykora we also need a PR for the documentation please. Repo is [here](https://github.com/mautic/mautic-documentation), contribution guidelines [here](https://docs.mautic.org/en/home/contributing)!

**Comment by hluchas** [comment]
> @lukassykora we also need a PR for the documentation please. Repo is [here](https://github.com/mautic/mautic-documentation), contribution guidelines [here](https://docs.mautic.org/en/home/contributing)!

Lukas has been ill for a long time. I 'll try to help.

**Comment by hluchas** [comment]
@lukassykora FYI https://github.com/mautic/mautic/pull/8647#issuecomment-655674364

**Comment by RCheesley** [comment]
Bumping to 3.2 due to unresolved conflicts

**Comment by RCheesley** [comment]
Trying to test this locally but I am getting the following:

`Automatically fetching the Do Not Sell data failed. Download https://api.maxmind.com/privacy/exclusions, extract if necessary, and upload to ./maxmind.json.
`

**Comment by RCheesley** [comment]
Added details to the test instructions  to help other testers - works as described but note you have to change the format of the license key!

This will definitely need documentation updates!

**Review by RCheesley — APPROVED** [review]

**Review by RCheesley — CHANGES_REQUESTED** [review]
While this command works it seems to have broken the regular IP lookup:

ruth.cheesley@MacBookPro-RuthCheesley mautic % bin/console mautic:iplookup:download

In Type.php line 246:
                                                                                             
  Attempted to load class "GeneratedType" from namespace "Mautic\CoreBundle\Doctrine\Type".  
  Did you forget a "use" statement for another namespace?

**Review by RCheesley — APPROVED** [review]
PR works as intended - the error was from applying the related PR.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by hluchas** [comment]
> @lukassykora could you. please resolve the conflict?
> Blocker for #8769

@lukassykora Could you please take a look on this PR? Still blocker for https://github.com/mautic/mautic/pull/8769

**Pull request merged**
