### PR TITLE
[UX] Change sidebar icon to list settings icon

### PR DESCRIPTION
**Pull request by andersonjeccel**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Change based on feedbacks.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Look at the new icon on navbar

image

### CODE REVIEW

**Comment by andersonjeccel** [comment]
@Mike-Dropsolid 
@LordRembo

**Comment by code5rick** [comment]
My position on this suggestion is the same: https://github.com/mautic/mautic/pull/13365#issuecomment-1966438107

**Comment by LordRembo** [comment]
Okay, maybe to recap the options and suggestions so far to have it all in 1 place (apologies for the simplification):
* use the icon with sidebar (that's what got merged in PR #13365) BUT make sure the 'sidebar' is on the right (so flip the icon)
  * ➕  because it reflects the purpose better (open/close a sidebar). Points towards the actual function (opening/closing a sidebar). 
  * ➖ might actually confuse users who are looking to change configuration or settings and expect to find this in 1 place. 
* keep using a cog icon (but use the new icon system instead of FontAwesome)
  * ➕  it's very visible + already established
  * ➖  it means 'configuration/settings' but contains more than just config. Maybe makes sense to not be explicit about the content and point more towards function (open/close a sidebar)
* use the 'list with a small cog' (proposal of this PR), because it reflects changing settings as well as config. So it still has a 'flavor' of the old icon (full cog)
  * ➕  tries to marry both views a bit: point to config/settings but make it look less technical 
  * ➖  cog would be very small so you'd see more of the 'list' part and maybe miss the 'cog' part

**Comment by LordRembo** [comment]
There's 1 vote so far for reinstating the full cog, 1 for the 'list+cog'. I'm curious to here from other reviewers

**Comment by Mike-Dropsolid** [comment]
I do like this proposal. It makes sense to me.

But... I feel if we can't get to a clear consensus, we should stick with the cog. It is doing its job atm.

More opinions needed :)

**Comment by escopecz** [comment]
I like this better than the sidebar icon. It still has a cog in it so all the texts written about Mautic over the years will still make sense. Although I have to zoom my head closer to the monitor to see that it is a cog icon. It may be less about the icon and more about my eye sight. But UX should be also about accessibility. So I too would like the full cog icon rather than this. But I'm fine merging this too.

**Comment by Mike-Dropsolid** [comment]
> I like this better than the sidebar icon. It still has a cog in it so all the texts written about Mautic over the years will still make sense. Although I have to zoom my head closer to the monitor to see that it is a cog icon. It may be less about the icon and more about my eye sight. But UX should be also about accessibility. So I too would like the full cog icon rather than this. But I'm fine merging this too.

Very good point.

**Review by rohit-sharma-1802 — APPROVED** [review]
Yes, so far it is done as per the requirements. It is matching with the result output..

**Review by shinde-rahul — APPROVED** [review]
LGTM!!!

Thanks @andersonjeccel.

**Comment by andersonjeccel** [comment]
@escopecz Doc changes:
https://github.com/mautic/user-documentation/pull/250

**Comment by escopecz** [comment]
In this case I was hoping to get back to the cog icon. It's not only about the official docs but there are so many mentions of this icon in the forums and 3rd party pages that we can't change. I still don't understand why this icon had to be changed without considering all the texts written about Mautic in past 10 years. Let's change icons and texts if there is a good reason for it or if a bunch of people write here that the cog list is better than cog itself. I don't see either.

**Comment by LordRembo** [comment]
I think we learned a lesson from how the previous PR and the pushback went, so we now know to involve more reviewers now and that these icons are a tricky matter, but also to consider the documentation and historic usage/knowledge. 

Reading through these comments (and the prev. PR), I don't think we can really form a consensus for a replacement. As Mike suggested, let's then revert back to a cog icon? This PR proposal can be amended to do that instead of the list icon.
@code5rick @escopecz @Mike-Dropsolid what do you think?

**Comment by andersonjeccel** [comment]
@LordRembo @escopecz 

Votes in favor:
- rohit-sharma-1802
- andersonjeccel
- shinde-rahul


- Mike-Dropsolid

> I do like this proposal. It makes sense to me.

- Maybe code5rick (mentioned the conflict of having different cogs to be placed on docs)

> When I was writing documents explaining Mautic for internal use, I came across this problem and realized there are two types of cogs being used.

- [x] PR to update the docs OK

Opposed:
- escopecz

No opinion:
- LordRembo

-----

It would be great to fix this before the next version gets released

I'll add more information to help everyone make a solid decision:

These are all the icons related to settings/cog:
image


We will change all Font Awesome icons. So we still need an icon for admin things like:
- Configuration (it needs a cog)
- Marketplace (probably a tool icon, the + icon currently used is a bit vague)
image
- Plugins (there is a plug icon)
image
- Roles (shield with a user
image
- Users
image
- System info
image
- Categories
image


We can certainly choose one cog to the sidebar and another cog to configuration, but it could become problematic since the difference is not that big...

**Comment by Mike-Dropsolid** [comment]
> I think we learned a lesson from how the previous PR and the pushback went, so we now know to involve more reviewers now and that these icons are a tricky matter, but also to consider the documentation and historic usage/knowledge.
> 
> Reading through these comments (and the prev. PR), I don't think we can really form a consensus for a replacement. As Mike suggested, let's then revert back to a cog icon? This PR proposal can be amended to do that instead of the list icon. @code5rick @escopecz @Mike-Dropsolid what do you think?

Agreed. Let's leave it a cog. @escopecz has some very valid remarks.

**Comment by escopecz** [comment]
@RCheesley we may need some kind of polls for PRs like this. Otherwise I'm not sure how to come to some consensus.

@andersonjeccel did you close this PR by accident? Or shall we revert https://github.com/mautic/mautic/pull/13365 to be able to release M5.1.0?

**Comment by RCheesley** [comment]
We have debates and proposals on the community portal - that's where this kind of debate can be moved (either in the product team assembly or in the new features process for things which are features.

**Comment by escopecz** [comment]
Here is the successor PR with the cog icon: https://github.com/mautic/mautic/pull/13525

**Pull request closed without merging**
