### PR TITLE
Fixes issue with social profile fetching and prevent lead from being anonymous if they have a social identity

### PR DESCRIPTION
**Pull request by alanhartless**
**Description**

If a lead did not have any vales for the core group, social profile fetching would fail due to an if statement that checked for the core group existence.  This PR should fix that.

Also this PR will consider leads with a social identity as NOT anonymous. The lead list is also searchable by social profile handles.

**Testing**
Setup Twitter integration. Create a new lead with only a twitter handle.  The twitter profile will not be found.  Apply the PR and repeat and this time it should fetch.

### CODE REVIEW

**Comment by escopecz** [comment]
While trying to authorize the Twitter integration I got this error:
```
500 Internal Server Error - Notice: Undefined index: oauth_token in /var/www/html/mautic-github/addons/MauticSocialBundle/Integration/TwitterIntegration.php line 79
```
```
/var/www/html/mautic-github/addons/MauticSocialBundle/Integration/TwitterIntegration.php (line #79):
/var/www/html/mautic-github/addons/MauticSocialBundle/Integration/TwitterIntegration.php (line #79): at Symfony\Component\Debug\ErrorHandler -> handle ( '8', 'Undefined index: oauth_token', '/var/www/html/mautic-github/addons/MauticSocialBundle/Integration/TwitterIntegration.php', '79', array('url' => 'https://api.twitter.com/oauth/authorize', 'requestToken' => array('{"errors":' => array('{"code":32,"message":"Could not authenticate you."}' => ''))) )
/var/www/html/mautic-github/app/bundles/AddonBundle/Controller/IntegrationController.php (line #179): at MauticAddon\MauticSocialBundle\Integration\TwitterIntegration -> getAuthLoginUrl ( )
at Mautic\AddonBundle\Controller\IntegrationController -> editAction ( 'Twitter' )
/var/www/html/mautic-github/app/bootstrap.php.cache (line #3001): at call_user_func_array ( array(object(IntegrationController), 'editAction'), array('Twitter') )
/var/www/html/mautic-github/app/bootstrap.php.cache (line #2963): at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '1' )
/var/www/html/mautic-github/app/bootstrap.php.cache (line #3112): at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '1', true )
/var/www/html/mautic-github/app/bootstrap.php.cache (line #2361): at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel -> handle ( object(Request), '1', true )
/var/www/html/mautic-github/app/AppKernel.php (line #115): at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), '1', true )
/var/www/html/mautic-github/index_dev.php (line #38): at AppKernel -> handle ( object(Request) )
```

**Comment by alanhartless** [comment]
@escopecz Some thoughts to check:

1) Is the Twitter integration published? If you are using an instance of Mautic that's been around for a while, you might want to make sure the features are checked on the Features tab as well (defaults to checked since 1.1 I think).
2) Do you get a authorization success message when authorizing with Twitter?
3) Are you using a handle without the `@` in the lead's twitter profile field?

I added a check to prevent the PHP notice if fetching a request token fails for some reason.

**Comment by escopecz** [comment]
1) Yes, Twitter integration is published. When I click on reauthorize button, it reauthorizes successfully. All features are checked by the default.
2) Yes.
3) I do use a handle without `@` in the lead form.

I tested all again and made sure the cache is cleared for prod and dev, db schema is up to date and all migrations are applied. I followed your testing description:

1. I created a new lead manually.
2. I added an existing Twitter handle `calculoidapp` to the Twitter field in the social tab of the form.
3. I saved the lead.

Result: There was no Social tab on lead detail.

Interestingly, I tried to 
1. edit the lead again. 
2. I added a first and a last name.
3. I saved the lead.

Result: The Social tab is on Lead detail and the Twitter profile is loaded successfully (with this PR applied)

So for me, this PR works for identified leads. It does not work for leads with only the Twitter handle.

**Comment by drmmr763** [comment]
I got the same error earlier when I used invalid oauth credentials. Seems the error check doesn't skip trying to verify the oauth token.

**Comment by alanhartless** [comment]
So I obviously was missing something as it's coded to NOT show the Social tab when the lead is considered anonymous so maybe I discovered this while debugging something else. 

BUT, with my last commits, I made it so that a lead is not considered anonymous with if they have a social profile identity. 

So now the social tab should show show along with the lead should not be considered "Anonymous" in the list and you can search by social profiles.

**Comment by drmmr763** [comment]
+ test checked an anonymous lead with only a twitter profile. Social tab was not showing. Checked out PR, social tab showed up properly. 

+ test `is:anonymous` search, lead does _not_ show when searching for anonymous leads (with PR)

+ vote +1

**Pull request merged**
