### PR TITLE
Command mautic:update:find will return exit codes.

### LINKED ISSUE #11152: mautic:update:find doesn't have an exit/error code (for automation/scripting)
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

running` php bin/console mautic:update:find 
`doesn't give back an exit code. we would like to run `php bin/console mautic:update:apply` only when an update is available

### How can we reproduce this issue?

Step 1: php bin/console mautic:update:find
Step 2: echo $?

returns 0 even if update is available

### Relevant log output

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/108497323-mautic-update-find-doesn-t-have-an-exit-error-code-for-automation-scripting?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F5355074&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by biozshock**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ 4.0 ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Issue(s) addressed                     | Fixes #11152 

#### Description:

Running `php bin/console mautic:update:find` gives back an exit code.

| Code | Description
| ----- | ------------------------------------------------
| 0 | An update is available for Mautic.
| 1 | Running latest version of Mautic.
| 2 | An error occurred while fetching available updates of Mautic.

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. In the console run the command `bin/console mautic:update:find`
3. In console run `echo $?`
4. Depending on the mautic installation it should output codes mentioned above.

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11349"></a>

### CODE REVIEW

**Comment by escopecz** [comment]
Are you sure this is a good idea? The exit code 2 means

> Misuse of shell builtins (according to Bash documentation)

https://tldp.org/LDP/abs/html/exitcodes.html

I thing it should return 0 when the command is successful otherwise it will be marked as error in the logs. What is the reason you want to change it?

**Comment by biozshock** [comment]
Well, these codes are valid only in bash, but i can change these to any. For example return 180 (seems not used) instead of 2.

**Comment by escopecz** [comment]
The thing is that any exit code other than 0 is considered as an error and will be labeled as such in the logs and counted as an error in monitoring. Changes like these can wake some engineer "on call duty" up in the middle of the night. So I ask again, what is the reason you want to make this change? Is there a chance you can listen to the output message if you wan to distinguish between the success states?

**Comment by biozshock** [comment]
The reporter in the linked issue can answer all these questions.

**Comment by escopecz** [comment]
@perler can you please join the conversation and let us know your point of view?

**Comment by perler** [comment]
> @perler can you please join the conversation and let us know your point of view?

first, "Running latest version of Mautic." should be 0, as this means "nothing to do".

also, someone monitoring "anything but 0" and reacting on this by setting himself a wake up call deserves it ;) - these are exit codes and their purpose is to being able to execute other processes depending on the result of a script, so, I don't see the problem..

**Comment by escopecz** [comment]
@perler I'd like Mautic to keep some standards with the rest of the world. So I'm googling more information about the exit statuses and all I can find confirms that 0 = success, 1-255 = error.

> Exit status is an integer number. 0 exit status means the command was successful without any errors. A non-zero (1-255 values) exit status means command was a failure.

Source: https://www.cyberciti.biz/faq/bash-get-exit-code-of-command/

> A successful command returns a 0, while an unsuccessful one returns a non-zero value that usually can be interpreted as an error code.

Source: https://tldp.org/LDP/abs/html/exit-status.html

Can you share some docs saying that returning anything than 0 can be a success exit code?

And I'm asking for the 3rd and last time: What is the reason for this change?

**Comment by perler** [comment]
just close the ticket please. I would like to automate the updates, that's the reason, but these happen so seldom that I can manage. 

You have bigger problems within your app to make it to standard IMO. for instace I need to run your cronjob every three minutes as my client for whom I maintain your app wants realtime handling of web requests and this seems to be quite "standard" (his words), so I wonder why these jobs work on a polling base and not triggered. looks clumsy to me. and is a  bigger concern for me as an admin.

**Comment by escopecz** [comment]
@perler thanks for the resolution. Yes, you are right.  But adding more non-standard behavior on top of it is not a good idea. Let's focus on those more pressing issues.

**Pull request closed without merging**
