### PR TITLE
remove hardcoded ddev name to ensure you can run multiple instances n…

### PR DESCRIPTION
**Pull request by mollux**
…ext to each other

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

The name of the ddev project is currently hardcoded to `mautic`. This leads to problems when you want to run 2 different instances (e.g. `4.x` and `5.x`) next to each other.

DDEV by default takes t[he name of the folder](https://ddev.readthedocs.io/en/latest/users/configuration/config/#name) as project name.

If there is no agreeent on this PR, it should at least be documented in the devdocs how to do this

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. test if Gitpod still works without a hardcoded name

### CODE REVIEW

**Comment by escopecz** [comment]
It seems like it installs Mautic correctly but it doesn't open it in the top right hand box like it used to
Screenshot 2024-01-31 at 12 47 37

**Review by kuzmany — APPROVED** [review]
Good 👍

**Comment by mollux** [comment]
> It seems like it installs Mautic correctly but it doesn't open it in the top right hand box like it used to Screenshot 2024-01-31 at 12 47 37

@escopecz 
Hm, interesting. That sounds more like a gitpod issue. Do you experience the same thing with any other PR?

**Comment by escopecz** [comment]
@mollux I tried it with https://github.com/mautic/mautic/pull/13296 and I can see the browser window there:
Screenshot 2024-01-31 at 20 11 46

**Comment by mollux** [comment]
@escopecz ok interesting, I'll check

**Comment by mollux** [comment]
@escopecz 
I tested it, and it works.
I can't reproduce the missing browser

I also checked what name ddev gives the project, and it's still `mautic`, as it inherits the name from the folder `/workspace/mautic` 

Seems like a one-off, or a project that wasn't fully loaded.
Could you retest with this PR?

Screenshot 2024-01-31 at 21 42 11

**Comment by kuzmany** [comment]
It opens the window on Gitpod correctly for me. Seems not related to the PR

image

**Review by escopecz — APPROVED** [review]
It must have been a glitch yesterday. Although I tried twice with the same result. It loaded today:
Screenshot 2024-02-01 at 11 43 41

**Pull request merged**
