### PR TITLE
Report new columns

### PR DESCRIPTION
**Pull request by kuzmany**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 
| New feature/enhancement? (use the a.x branch)      | 🟢 
| Deprecations?                          | 
| BC breaks? (use the c.x branch)        | 
| Automated tests included?              | Not relevant
| Related user documentation PR URL      | 
| Related developer documentation PR URL | 
| Issue(s) addressed                     | 

#### Description:

Added new columns to report section include Data Source to know what kind of report it is

image

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.  Go to reports and check  it's OK

### CODE REVIEW

**Review by PatrickJenkner — APPROVED** [review]
Works as described for a user.

**Review by patrykgruszka — APPROVED** [review]
Code looks fine, good improvement.

**Review by escopecz — CHANGES_REQUESTED** [review]
I'm not sure, folks. The alphabet works differently where I live.
Screenshot 2023-10-25 at 14 14 45
I suggest to remove the option to order by report type because the report type key can start from different letter than what the translation is which will lead to this type of issues. Even worse for other languages.

**Comment by kuzmany** [comment]
@escopecz good catch, I removed order by option on that column 

image

**Review by escopecz — APPROVED** [review]
Thank you, Zdeno! 👍

**Pull request merged**
