### PR TITLE
Fix for scenario where landing pages built with GrapesJS include unnecessary JS/CSS

### LINKED ISSUE #9998: Live page render includes links to plugin javascript and css
When viewing the final page created by the builder (not logged into Mautic, as an outside visitor), the builder javascript and css are linked from the page html, resulting in errors in the console:
image

### PR DESCRIPTION
**Pull request by dennisameling**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | features
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | N/A
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | Fixes #9998

#### Description:

As described in https://github.com/mautic/mautic/issues/9998#issuecomment-898915035, the reported issue is caused by JS and CSS tags having the `data-source="mautic"` attribute, which normally shouldn't be persisted to the database.

Before this change, HTML head JS/CSS tags with `data-source="mautic"` would incorrectly end up in the database:

image

After this change, HTML head JS/CSS tags don't end up in the database anymore, except the ones that are explicitly defined in the theme (`/nonexistent.js` in this case):

image

For the actual fix, please refer to https://github.com/mautic/grapesjs-preset-mautic/pull/20.

#### Reproducing the bug:
1. Checkout the latest `features` branch
2. Update `themes/blank/html/base.html.twig` by adding `<script src="/nonexistent.js"></script>` somewhere in between the `<head></head>` tags (just before the closing `</head>` tag would be a good place
3. Open Mautic in developer mode: `https://mautic.ddev.site/index_dev.php`
4. Go to Components > Landing pages and create a new landing page.
5. Launch and close the builder, then save the landing page with a name you like
6. Go to https://mautic.ddev.site:8037/ in your browser, this opens phpMyAdmin. Find the `pages` table and click "edit" next to the page you just created
7. Find the `custom_html` column. See that all tags with the `data-source="mautic"` attribute are still there (see the first screenshot above)

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat the steps above
3. Note that all tags with `data-source="mautic"` have correctly been stripped out before the page was persisted to the database (see the second screenshot above). Your custom `/nonexistent.js` from the theme should still be there.

**Important note when merging this PR**

This PR was created just so that end-users can test the fix that we created in https://github.com/mautic/grapesjs-preset-mautic/pull/20. The order of merging should be:
1. Merge https://github.com/mautic/grapesjs-preset-mautic/pull/20
2. Update the referenced Git commit by doing `cd plugins/GrapesJsBuilderBundle && npm update grapesjs-preset-mautic`
3. Run `npm run build` to generate the new dist files
4. Merge this PR

### CODE REVIEW

**Comment by RCheesley** [comment]
@dennisameling other than clearing the cache which is done automatically, is there anything else that needs to be updated/cleared after applying this PR?

I am not seeing the stripping out once the PR is being applied and I am creating a new landing page exactly the same way as before.

**Comment by dennisameling** [comment]
@RCheesley it might be needed to disable browser cache when testing this PR:

image

I see that some query parameter is added (`?vba6086d5`) which should make the browser invalidate its cache for that file, but the query parameter doesn't seem to update across requests.

If it works when disabling browser cache, please let me know, and I'll create a separate issue for the browser cache issue for future reference.

**Comment by RCheesley** [comment]
OK will give it a go!

**Comment by RCheesley** [comment]
screenshot-mautic4 ddev site_8037-2021 08 24-12_58_15

Still getting the same saved to the database, have cleared the browser and Mautic cache (in dev mode within Mautic), and have also tried with the developer tools console open and 'disable cache' selected.

screenshot-nimbus-capture-2021 08 24-12_59_30

**Comment by dennisameling** [comment]
@RCheesley is this on a clean instance? And is this when creating a new landing page, or updating an existing one? I'm not sure if we can fix the scenario where a landing page already exists in the database, but it should work in that case as well.

Just to be sure, I just created a separate, completely fresh DDEV instance by doing `mkdir mauticgrapes && gh repo clone mautic/mautic mauticgrapes && cd mauticgrapes && gh pr checkout 10360 && ddev config --project-name="mauticgrapes" && ddev start` and the JS/CSS tags don't end up in the database:

image

Very strange that you're not seeing it on your side 🤷🏼‍♂️

**Comment by RCheesley** [comment]
Yes on my local Mautic instance but I will try to wipe it and start again from scratch!

**Review by RCheesley — APPROVED** [review]
Welp ... no idea why but wiping out my instance and starting from scratch seemed to do the trick! 🤦‍♀️ 

screenshot-nimbus-capture-2021 08 24-14_43_39

**Review by adiux — APPROVED** [review]

**Comment by dennisameling** [comment]
For the person doing a code review here, please check https://github.com/mautic/grapesjs-preset-mautic/pull/20 as that contains the code that's actually changed. This PR is nothing more than an `npm build` to generate updated assets from the preset

**Pull request merged**
