### PR TITLE
SAMl login fix and test.

### LINKED ISSUE #13808: SAML login shows 'Unknown inResponseTo' error when logging in
Identified when testing #13742 (see instructions there for mocking a local SAML server for testing locally)

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.05.31-13_56_24.webm](https://github.com/mautic/mautic/assets/2930593/6ffeef98-29fc-406e-a9e2-b355b9ecee1e)

Here's a screencast. I get to the Mautic login screen with the error, then I use the back button (on my mouse) and it goes back to the SAML (URL is http://localhost:8080/simplesaml/saml2/idp/SSOService.php?spentityid=https%3A%2F%2Fmautic.ddev.site&cookieTime=1717160195) and then logs into Mautic.

_Originally posted by @RCheesley in https://github.com/mautic/mautic/issues/13742#issuecomment-2142079751_
            

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

### PR DESCRIPTION
**Pull request by biozshock**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🟢 
| New feature/enhancement? (use the a.x branch)      | 🔴
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🟢 
| Issue(s) addressed                     | Fixes #13808 

## Description
An automated test, as described in the #13742 

---
### 📋 Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Follow instructions in the #13742 , or just check if all tests have passed.

### CODE REVIEW

**Comment by matbcvo** [comment]
Thanks for the PR, @biozshock. There’s one failing test related to the code style fixer. Please run the code style fixer on your changes to resolve it.

**Comment by daltonm-GEM** [comment]
God bless you!  This fixed SAML for my installations using Microsoft Entra (Azure) as my IdP.

**Comment by gregharvey** [comment]
Yup, confirmed, manually patched our dev version of Mautic and it worked. Thanks!

**Comment by matbcvo** [comment]
After configuring SAML on the Mautic configuration page, I encountered an error when attempting to log in (`user1`/`password`) via the SAML login page in incognito mode:
```
500 Internal Server Error - Mautic\UserBundle\Entity\User::getUserIdentifier(): Return value must be of type string, null returned
```
image

Here's the configuration

image

I have SAML running in Docker on port 8086, and I was able to obtain the metadata from it.

**Comment by biozshock** [comment]
@matbcvo are you testing on the 5.2 branch?

**Comment by matbcvo** [comment]
@biozshock Yes

**Comment by biozshock** [comment]
@matbcvo You must enter "email" into the _Email_, _First name_ and _Last name_ fields, as those are mappings, not the values.

**Comment by matbcvo** [comment]
@biozshock Thanks! I can verify that it works.

**Review by matbcvo — APPROVED** [review]
The code changes look good to me. I have tested the PR, and it works as expected.

**Review by escopecz — APPROVED** [review]
I find no issues in the code 👍

**Pull request merged**
