### PR TITLE
Fixed various areas problematic for users tracked as leads

### PR DESCRIPTION
**Pull request by alanhartless**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | y
| New feature? | 
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

2.9 stopped tracking a user as a contact. But it caused issues in various places that expected a Lead entity leading to Doctrine exceptions. This PR fixes those areas. 

#### Steps to test this PR:
1. Download an asset as a user
2. View dynamic web content as a user
3. Submit a form as a user in both kiosk and not kiosk mode
4. View a landing page as a user
5. Video hit tracking (#4480)

### CODE REVIEW

**Comment by dongilbert** [comment]
Hrm - hang on. Testing this still...

**Comment by dongilbert** [comment]
Yeah, we're still getting an error on this when requesting dynamic content.

**Comment by dongilbert** [comment]
👍

**Comment by mqueme** [comment]
it all worked for me.

**Pull request merged**
