### PR TITLE
Fix formula for bounced, bounced ratio, unsubscribed and unsubscribed ratio

### PR DESCRIPTION
**Pull request by Enc3phale**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Automated tests included? | N
| Related user documentation PR URL | N
| Related developer documentation PR URL | N
| Issues addressed (#s or URLs) | N
| BC breaks? | N
| Deprecations? | N

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
PR #7070 and #7128 fix 500 but insert wrong result for bounced, bounced ratio, unsubscribed and unsubscribed ratio stats.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create a report and choose email as data source
2. Add some columns.
3. Add unsubscribed, bounced, unsubscribed ratio and bounced ratio as a filter.
4. Save and close.
5. Click on your report to view it. Crazy result!

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com/7206)
2. Click on your report to view it. Good result!

### CODE REVIEW

**Comment by kuzmany** [comment]
But this PR step back of this issue https://github.com/mautic/mautic/pull/7070

Now bounced/unsubscribed where statement return error. This is reason why this PR https://github.com/mautic/mautic/pull/7070 added full SQL table query as where statement, because aggregated (SUM, COUNT) cannot be use in WHERE statement

https://mautibox.com/7206/s/reports/view/4

image

**Comment by kuzmany** [comment]
I think there is just error with missing where statement for channel and channel id  in DNC queries. This is reason why this stats make mess. I am working on it.

**Comment by Enc3phale** [comment]
@kuzmany I fixed that, could you retry?

**Comment by kuzmany** [comment]
Could we close this PR favor https://github.com/mautic/mautic/pull/7214 ?

**Comment by Enc3phale** [comment]
Yes you can.

**Pull request closed without merging**
