### PR TITLE
Contact field value campaign condition multiselect for including/excluding operators

### PR DESCRIPTION
**Pull request by patrykgruszka**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | "features"
| Bug fix?                               | bugfix/enhancement
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Issue(s) addressed                     | Fixes #... 

#### Description:
This PR adds possibility to define multiple contact field values for select type field with including and excluding operators. 
obraz

The including/excluding operator before this change allowed only to set one value, so basically it was the same as equals/not equals operator. 

I've also replaced the comparison method for in/notIn operator because it was using regex. This change should not break backwards compatibility of campaigns that uses this operators.

#### Steps to test this PR:
1. Apply this PR
2. Rebuild assets `php bin/console mautic:assets:generate`
2. Add campaign with condition based on contact field value
3. Set contact field to some type of list e.g Country
4. Set operator to including
5. Add multiple values

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/9658"></a>

### CODE REVIEW

**Comment by patrykgruszka** [comment]
I'm not sure that the failing tests are caused by this PR. I've got the `InputHelperTest::testUrlSanitization` test failure for features branch. Any ideas where is the issue?

**Comment by RCheesley** [comment]
Hmm, we have another PR that had this issue, looks like there may be a failing test in the Features branch. @mohit-rocks would you be able to take a look and see if we can find where the problem is?

**Comment by RCheesley** [comment]
@patrykgruszka it seems that the tests are failing due to some recent changes in a patch release from PHP - we are looking into a fix!

**Comment by patrykgruszka** [comment]
@RCheesley do you have any update on this failing tests issue? Please let me know if there is any action required.

**Comment by mohit-rocks** [comment]
@patrykgruszka Test cases seem good to me. There might be some issues with the upstream. I've rebased it with features branch.

**Comment by RCheesley** [comment]
Super - tests are passing now so we just need to get testers!

**Review by kuzmany — DISMISSED** [review]
Works as expected.
Include unit tests.
Code looks good, I don't see any BC issue.
I approve it.

But once be merged, this change make conflicts in Segment refactoring
https://github.com/mautic/mautic/pull/8649 

@escopecz or do we should focus merge Segments refactoring, and then this small improvements make it compatible with refatoring?

**Comment by escopecz** [comment]
I'd prefer merging the big old PR first otherwise we never get it in.

**Comment by RCheesley** [comment]
@patrykgruszka we would like to slate this PR for inclusion in the 4.1 release - can you please address the conflict so that it could be added to the milestone?  Thanks!

**Comment by patrykgruszka** [comment]
@RCheesley sure, conflicts are resolved.

**Comment by RCheesley** [comment]
@patrykgruszka awesome thanks for getting that done!  We may need to take a look at conflicts when https://github.com/mautic/mautic/pull/8649 is merged if that happens before this one as suggested above.

**Review by kuzmany — CHANGES_REQUESTED** [review]
I've tried it.
I created two contacts. 
Contact 1 with country Slovakia
Contact 2 without country.

Setup campaign

image

image

Both contact were passed to true.

Do I made something wrong?

**Comment by patrykgruszka** [comment]
@kuzmany your configuration looks fine. That's weird, I've reproduced the exact same test in my environment and everything works correctly. 
obraz

Do you have any idea what may cause this problem? Maybe it's some cache related issue.

**Comment by OxidoPL** [comment]
Thank you :)

This change would be appreciated!

Have a nice day,
Marek

**Review by kuzmany — DISMISSED** [review]
I did test again and works lie charm.
Nice addition.
Code looks good. 
Thanks 👍

**Comment by atowne07** [comment]
I'm still not able to select multiple values with a select-multiple field
image
Here's what I did:

- Create a select multiple field with Option 1, Option 2, Option 3
- Create 2 contacts, selecting option 1 for one of them and option 2 for the other
- Create a segment with the new field being not empty
**- Create a campaign with a contact field value condition, selected the new field, chose the Including operator**

Since I wasn't able to select multiple possibilities, this is where I stopped.

**Comment by kuzmany** [comment]
@atowne07 did you test it on test enviroment? If not you need call `php bin/console mautic:assets:generate`. Did you refresh browser (CTRL+F5 on Windows)

**Comment by atowne07** [comment]
@kuzmany I used the new Gitpod setup, so it's possible something went wrong there. I don't have my own Mautic installation, so I'm happy for Gitpod. Hopefully I'll be able to contribute more to testing with that. To be honest I wanted to try that more than test something that it looks like already worked, because based on your screenshot it looks like it at least displayed the way I'd expect!

**Comment by escopecz** [comment]
@patrykgruszka there seem to be another version of this fix: https://github.com/mautic/mautic/pull/10490

Can you please work with @shinde-rahul to decide which version is better? Or whether to mix them?

**Comment by RCheesley** [comment]
@patrykgruszka @shinde-rahul could you please decide between you how to proceed with these two PRs? It would be nice to try and get one or the other (or some combination of the two!) merged in the 4.1 release.

**Review by mabumusa1 — CHANGES_REQUESTED** [review]
image


Thanks @patrykgruszka for the PR, I tested it, worked as expected. May you please check the issues in the tests. I think this PR is ready to commit once you solve the issues

**Comment by shinde-rahul** [comment]
#10490 will be working as expected with
- custom fields
- the matches to get accurate results.  https://github.com/mautic/mautic/pull/10490/files#diff-4d518f9b162369b708836915e59155a97a415b36db3c85db0fe0ad3e67eb542eR238-R260

**Comment by patrykgruszka** [comment]
@mabumusa1 Thanks for your review. I couldn't reproduce this issue. Maybe some browser addon you using is causing this errors.

@RCheesley @escopecz @shinde-rahul I've reviewed #10490 it works fine for most cases, also code looks good. The main difference is that this PR replaces the comparison method for in/notIn operator because it was using regex which may cause unexpected behaviour when special characters like `|` are used in the select options. Therefore I prefer this PR to be merged.

Whether it will be this PR or #10490 let's get this improvement merged.

**Comment by patrykgruszka** [comment]
@RCheesley is there a chance that this PR will be merged in the near future? There were basically two positive reviews and I think it's ready to go live.

**Comment by OxidoPL** [comment]
Would it be possible to see this change in the official release in the nearest future?

**Comment by escopecz** [comment]
@patrykgruszka @OxidoPL Each PR needs 2 successful tests to be merged. Any chance you can lobby with the community to get those tests done? Anyone can do them (except the author). Check [the docs](https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#testing) for getting started and let's get this PR mergeable 🚀

**Comment by escopecz** [comment]
@mabumusa1 it looks like your test was successful and there are no test failures anymore. Can you re-review?

**Comment by patrykgruszka** [comment]
@shinde-rahul, @mohit-rocks, @kuzmany, @mabumusa1 I would be grateful if you could review this PR again

**Comment by patrykgruszka** [comment]
Rebased on 5.x, ready to test

**Comment by fedys** [comment]
@patrykgruszka please can you include also tests with a multiple-select field. My concern is that your implementation will not work with multiple selects as they are internally stored as pipe delimited list e.g. `one|two|three`.

**Comment by patrykgruszka** [comment]
@fedys could you please give an example of this test? IMO it's already covered by `LeadFieldRepositoryFunctionalTest::testCompareValueInOperator` and `LeadFieldRepositoryFunctionalTest::testCompareValueNotInOperator`.

Before applying this PR using multiple selects in contact field campaign condition was not possible at all.

**Comment by fedys** [comment]
@patrykgruszka your tests do not cover a scenario with multiple select **custom field**(column within a `leads` table) that can be created via UI as follows:
multiple-select-creational

You need to create such custom field in your test and test if your changes did not break the functionality. As multiple values are stored as `one|two|three` within the DB field, I am concerned that your PR did break the functionality.

**Comment by patrykgruszka** [comment]
@fedys good point, I will check it.

**Comment by patrykgruszka** [comment]
@fedys I've created multiple select field and verified how it's defined in the campaign condition - you can only select single value just like the single select. The current regex implementation with parsing `|` separated values is probably a dead code. `LeadFieldRepository::compareValue` method is used only in `CampaignSubscriber` in the context of a `lead.field_value` condition, so it should be safe to change.

My proposition is to replace it with proper `in/notIn` operators to avoid problem with using `|` symbol in select/multiselect values. Therefore i don't see need of testing this variant. 

image
image

**Comment by escopecz** [comment]
@patrykgruszka here is the test Fedy wrote we need:
```php
public function testCompareValueInOperatorWithMultiselectField(): void
    {
        $field = new LeadField();
        $field->setType('multiselect');
        $field->setObject('lead');
        $field->setAlias('colors');
        $field->setName('Colors');
        $field->setProperties(
            [
                'list' => [
                    [
                        'label' => 'Red',
                        'value' => 'red',
                    ], [
                        'label' => 'Green',
                        'value' => 'green',
                    ], [
                        'label' => 'Blue',
                        'value' => 'blue',
                    ],
                ],
            ]
        );

        $fieldModel = self::$container->get(FieldModel::class);
        \assert($fieldModel instanceof FieldModel);
        $fieldModel->saveEntity($field);

        $lead = new Lead();
        $lead->addUpdatedField('colors', 'green|blue');
        $contactModel = self::$container->get(LeadModel::class);
        \assert($contactModel instanceof LeadModel);

        $contactModel->saveEntity($lead);

        $repository = $fieldModel->getRepository();

        $this->assertTrue($repository->compareValue(1, 'country', ['green', 'blue'], 'in'));
        $this->assertFalse($repository->compareValue(1, 'country', ['red', 'green'], 'in'));
    }
```
You'll also need to set
```php
protected $useCleanupRollback = false;
```
As adding the new multiselect field modifies SQL schema. You'll see that it's failing when it shouldn't.

**Comment by patrykgruszka** [comment]
@escopecz I see it now, thanks for clarification. So we have to deal with the regex in query, and we want to assure that in case of multiselect field all values in condition are set. I've updated the code and tests, should be good now.

**Comment by patrykgruszka** [comment]
I've got this tests passing, but there is a problem with failing coverage and CLA verification. Probably some pipline failure. This PR should be ready to test now.

**Review by escopecz — APPROVED** [review]
I see no more issues in the code. Thank you!

**Comment by patrykgruszka** [comment]
@cla-bot check

**Comment by patrykgruszka** [comment]
@RCheesley do you think we can get this merged to 5.x? We need only one review confirmation here

**Review by mabumusa1 — APPROVED** [review]
I verified the code on gitpod, it looks good and works as expected

**Pull request merged**
