### PR TITLE
Fix overwrite custom field value with default value during redirection

### PR DESCRIPTION
**Pull request by kuzmany**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | 
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:
Noticed issue with contact field default value. 
If Mautic create contact and already have contact in url (ct), Mautic create new anonymouse contact first and then merge it with founded contact.
This make mess, because If our founded contact already exist and we modified custom field, then during the merge method, these two contact are merged and value is overwritten to default value.

[//]: # ( As applicable: )
#### Steps to reproduce the bug:
1. Create custom field with default value
2. Create contact (default values is filled)
3. Change default value
4. Create email with anchor link to http://mautic.org
5. Send email to contact
6. Copy redirect link from email
7. Open this link in incognito window
8. See value of custom field was set to default value (what we don't expect)

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2. Repeat all steps
3. See If value of custom field is not overwrite to default value

### CODE REVIEW

**Comment by florentpetitjean** [comment]
tested on Mautix box and it works (the value does not reset to default)

**Comment by kuzmany** [comment]
@florentpetitjean Can you retest with last changes? 
I hope new version should be much better to figure out this issue

**Comment by florentpetitjean** [comment]
Works fine with new patch

**Comment by RCheesley** [comment]
Ooh, nasty bug! Tested this on Mautibox with a PR that was only unit tests, so close as possible to vanilla 2.16 and could reproduce the bug.

Tested the PR on Mautibox and the field is not overwritten with the default content.

**Review by dennisameling — APPROVED** [review]
@kuzmany You're a hero! Was actually experiencing this myself on my Mautic instance (some contacts would mysteriously have some custom field values set back to their defaults sometimes), haven't tested it yet but based on the comments above I'm merging this PR 🎉

**Comment by dennisameling** [comment]
Possible duplicate of https://github.com/mautic/mautic/pull/7717

**Pull request merged**
