### PR TITLE
Add notifications for tracking pages

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | n
| New feature? | y
| Related user documentation PR URL | https://github.com/mautic/documentation/pull/157
| Related developer documentation PR URL | n
| Issues addressed (#s or URLs) | #3199
| BC breaks? | n
| Deprecations? | n

[//]: # ( Required: )
#### Description:
Added support notification for pages with tracking code.
This PR moved JS code to BuildJSSubscriber. 
Now we can use notification for both Mautic landing pages or pages with tracking code.
Also added support for non https sites.

Also this pr added CORS request and save osid to cookie.
https://github.com/mautic/mautic/pull/3274/files#diff-214219e233f348b2771cd41d503805a5R131

notifications

#### Steps to test this PR:
1.  Apply PR, clear cache and go to configuration  and enable both (landing pages, tracking pages)
2. For tracking pages:
Save these files and copy to root dir  of your tracking page 
https://yourmauticurl.tld/manifest.json
https://yourmauticurl.tld/OneSignalSDKWorker.js
https://yourmauticurl.tld/OneSignalSDKUpdaterWorker.js
3. Test notification

### CODE REVIEW

**Comment by escopecz** [comment]
It's the first time testing Notifications for me, so it may not be related to this PR, but I get this at the contact's timeline when he executes the notification action:
mautic-notification-event
I tested it in another browser, not an incognito mode. It prompted me to enable notifications, so I did. I got the welcome notification. But the notification from the campagin did not show up. This is from my log:
```
[2017-02-28 15:34:23] mautic.NOTICE: PHP Notice - Undefined index: status - in file app/bundles/NotificationBundle/Views/SubscribedEvents/Timeline/index.html.php - at line 17 [] []
[2017-02-28 15:34:23] mautic.NOTICE: PHP Notice - Undefined index: type - in file app/bundles/NotificationBundle/Views/SubscribedEvents/Timeline/index.html.php - at line 19 [] []
[2017-02-28 15:34:23] mautic.NOTICE: PHP Notice - Undefined index: heading - in file app/bundles/NotificationBundle/Views/SubscribedEvents/Timeline/index.html.php - at line 23 [] []
[2017-02-28 15:34:23] mautic.NOTICE: PHP Notice - Undefined index: content - in file app/bundles/NotificationBundle/Views/SubscribedEvents/Timeline/index.html.php - at line 25 [] []
[2017-02-28 15:34:40] mautic.NOTICE: PHP Notice - Undefined index: status - in file app/bundles/NotificationBundle/Views/SubscribedEvents/Timeline/index.html.php - at line 17 [] []
[2017-02-28 15:34:40] mautic.NOTICE: PHP Notice - Undefined index: type - in file app/bundles/NotificationBundle/Views/SubscribedEvents/Timeline/index.html.php - at line 19 [] []
[2017-02-28 15:34:40] mautic.NOTICE: PHP Notice - Undefined index: heading - in file app/bundles/NotificationBundle/Views/SubscribedEvents/Timeline/index.html.php - at line 23 [] []
[2017-02-28 15:34:40] mautic.NOTICE: PHP Notice - Undefined index: content - in file app/bundles/NotificationBundle/Views/SubscribedEvents/Timeline/index.html.php - at line 25 [] []
```

**Comment by kuzmany** [comment]
That error log is not related but i guees  no commit should fixed it. 
Added if action is failed.
Could you check your campaign lead events log db table if you see error  there?

**Comment by escopecz** [comment]
The reason in the `campaign_lead_event_log` table is `mautic.notification.campaign.failed.not_subscribed`. If I find the human translation of this error, it's 

> The contact has not subscribed to the Web Notification channel.

I'll try to test with another another contact. It'd be nice if the error reason was visible in the contac's event log.

**Comment by kuzmany** [comment]
Yes, but this is not reason for  send this info to timeline. 
The same situation like with send email when contact hasn't email address in profile https://github.com/mautic/mautic/blob/staging/app/bundles/EmailBundle/EventListener/CampaignSubscriber.php#L204
This is reason why I send another PR with lead notification condition https://github.com/mautic/mautic/pull/3473

**Comment by escopecz** [comment]
I don't understand what should I do in step 2. Where do I get the files?

**Comment by kuzmany** [comment]
@escopecz you should  open links  (on your mautic url)
https://yourmauticurl.tld/manifest.json
https://yourmauticurl.tld/OneSignalSDKWorker.js
https://yourmauticurl.tld/OneSignalSDKUpdaterWorker.js

Then save  these files and copy to root dir of your site with Mautic tracking code.
Mautic generate these file automatically for landing page, but we need copy them manually for tracking page .
This is easiest way how to do it, more info why we need it https://documentation.onesignal.com/docs/web-push-sdk-setup-https#section-2-upload-required-files

**Comment by escopecz** [comment]
@kuzmany could you resolve the conflicts, please?

**Comment by kuzmany** [comment]
@escopecz  tomorrow 👍

**Comment by kuzmany** [comment]
@escopecz  resolved

**Comment by escopecz** [comment]
It works as described. But do you think we could auto-load the js files [as you do the manifest.json](https://github.com/mautic/mautic/pull/3274/files#diff-214219e233f348b2771cd41d503805a5R132)?

**Comment by kuzmany** [comment]
@escopecz what do you mean "auto-load"?
Are you working today? Don't you have holiday in Czechia today? :)

**Comment by escopecz** [comment]
Haha, we do, but not in US where I work (in theory) ;)

I mean you do this with manivest.json:
```
var scrpt = document.createElement('link');
scrpt.rel ='manifest';
scrpt.href ='/manifest.json';
var head = document.getElementsByTagName('head')[0];
head.appendChild(scrpt);
```
Ah, I just noticed you load it from the root of the website, not the tracked website.

Do you think we can auto-load all of the required files like for example:
```
var baseUrl = '{UrlGeneratorInterface::ABSOLUTE_URL}';
var scripts = ['manifest.json', 'OneSignalSDKWorker.js', 'OneSignalSDKUpdaterWorker.js'];
var head = document.getElementsByTagName('head')[0];

scripts.forEach(function(script) {
    var scriptEl = document.createElement('link');
    scriptEl.href ='/'+script;
    head.appendChild(scriptEl);
});
```
_untested code_

Or maybe it can be optimized to load directly scripts from OneSignal instead of loading a script which loads a script. I'm not sure if it's needed to load the *Worker.js scripts from Mautic.

**Comment by kuzmany** [comment]
@escopecz thanks. Added minor lang improvement

**Comment by mqueme** [comment]
I was able to test this with the onesignal subdomain. and it worked

**Comment by hanselke** [comment]
Hi,
is this related to

A bad HTTP response code (404) was received when fetching the script.
ServiceWorkerHelper.ts:135 ServiceWorker registration TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
e.registerError @ ServiceWorkerHelper.ts:135

When using manual form insert (because the automatic javascript doesnt seem to deal with https properly), im getting this error when loading the form in mautic 2.7.2 and 2.8.

It seems like those files are expected to be in your website but it tries to load them from the mautic instance

**Comment by kuzmany** [comment]
@hanselke read https://github.com/mautic/documentation/pull/157/files 

Don't forget copy these files to root dir of your tracking page:

https://yourmauticurl.tld/manifest.json 
https://yourmauticurl.tld/OneSignalSDKWorker.js 
https://yourmauticurl.tld/OneSignalSDKUpdaterWorker.js

**Pull request merged**
