### PR TITLE
change wording of template email for a better understanding

### PR DESCRIPTION
**Pull request by npracht**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴
| New feature/enhancement? (use the a.x branch)      | 🟠 
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | N/A
| Issue(s) addressed                     | N/A

## Description

Following our discussion here: https://mautic.slack.com/archives/C024XBCQS3Z/p1724770095626019
we found out that Template Email is confusing and we better rename it to Trigger email to have something more adapted to what it does.

### CODE REVIEW

**Comment by andersonjeccel** [comment]
If you're feeling lucky today, there are some other translations needing alignment (list -> segment | template -> triggered):

```
mautic.notification.type.header="What type of notification do you want to create?"
mautic.notification.type.list="List Notifications"
mautic.notification.type.list.header="New List Notification"
mautic.notification.type.list.description="A list notification can be manually sent to selected contact lists. Once the notification has been sent, it cannot be edited. However, it can be sent to new contacts as they are added to the associated lists."
mautic.notification.type.template="Template Notifications"
mautic.notification.type.template.header="New Template Notification"
mautic.notification.type.template.description="A template notification is automatically sent by campaigns, forms, point triggers, etc. These can be edited but cannot be sent to a contact list."

mautic.sms.type.header="What type of sms do you want to create?"
mautic.sms.type.list="List Text Messages"
mautic.sms.type.list.header="Segment Text Message"
mautic.sms.icon_tooltip.list_sms="Is a segment (broadcast) SMS"
mautic.sms.type.list.description="A list sms can be manually sent to selected contact lists. Once the sms has been sent, it cannot be edited. However, it can be sent to new contacts as they are added to the associated lists."
mautic.sms.type.template="Template Text Messages"
mautic.sms.type.template.header="Template Text Message"
mautic.sms.type.template.description="A template sms is automatically sent by campaigns, forms, point triggers, etc. These can be edited but cannot be sent to a contact list."
```

**Review by andersonjeccel — CHANGES_REQUESTED** [review]
If you're feeling lucky today, there are some other translations needing alignment (list -> segment | template -> triggered):

```
mautic.notification.type.header="What type of notification do you want to create?"
mautic.notification.type.list="List Notifications"
mautic.notification.type.list.header="New List Notification"
mautic.notification.type.list.description="A list notification can be manually sent to selected contact lists. Once the notification has been sent, it cannot be edited. However, it can be sent to new contacts as they are added to the associated lists."
mautic.notification.type.template="Template Notifications"
mautic.notification.type.template.header="New Template Notification"
mautic.notification.type.template.description="A template notification is automatically sent by campaigns, forms, point triggers, etc. These can be edited but cannot be sent to a contact list."

mautic.sms.type.header="What type of sms do you want to create?"
mautic.sms.type.list="List Text Messages"
mautic.sms.type.list.header="Segment Text Message"
mautic.sms.icon_tooltip.list_sms="Is a segment (broadcast) SMS"
mautic.sms.type.list.description="A list sms can be manually sent to selected contact lists. Once the sms has been sent, it cannot be edited. However, it can be sent to new contacts as they are added to the associated lists."
mautic.sms.type.template="Template Text Messages"
mautic.sms.type.template.header="Template Text Message"
mautic.sms.type.template.description="A template sms is automatically sent by campaigns, forms, point triggers, etc. These can be edited but cannot be sent to a contact list."
```

**Comment by RCheesley** [comment]
@npracht could you please update the translations strings as mentioned above? It'd be great to make sure that we do actually change this in all places. We'll also need some documentation PRs as well (and maybe KB articles), cc @mautic/education-team to review.

**Comment by npracht** [comment]
All set ✅

**Review by andersonjeccel — APPROVED** [review]
Seems good to go!

**Comment by escopecz** [comment]
Is there a related PR for the docs?

**Comment by andersonjeccel** [comment]
@escopecz to be honest, it’s not worth it yet
I have another PR addressing translations across the UI that will need docs, I can include this change

**Comment by RCheesley** [comment]
@andersonjeccel can you make an issue in the docs repo to expect the PR for the translations, just so we don't lose sight of this for the 5.2 release? Thanks!

**Comment by andersonjeccel** [comment]
@RCheesley I can start working on the translation alignment based on the PR we were working on

then update the docs

**Comment by RCheesley** [comment]
Great, the issue just ensures that the Education Team know they need to check for that PR (and which mautic/mautic PRs it relates to) when the release is coming on the horizon.

**Pull request merged**
