### PR TITLE
Upload artifacts for failed E2E-tests

### PR DESCRIPTION
**Pull request by PatrickJenkner**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | 🔴 
| New feature/enhancement? (use the a.x branch)      | 🟢
| Deprecations?                          | 🔴
| BC breaks? (use the c.x branch)        | 🔴
| Automated tests included?              | 🔴🟢 
| Related user documentation PR URL      | mautic/user-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation-new#... 
| Issue(s) addressed                     | Fixes #... 

## Description

Codeception (the tool used for automated end-to-end tests) takes a screenshot as well as an html-snapshot when a test fails. This PR makes it so that these files are uploaded as an artifact during the CI workflow.
I have also bumped the version of the checkout-action to v4 during the e2e-step, to be in line with the other steps.

---
### 📋 Steps to test this PR:

This is tricky, since the changes are only to the CI workflow. However, there a 2 criteria:
1. If the Job "e2e-tests" succeeds, there should be **no** artifact called "e2e-test-screenshots"
2. If the Job "e2e-tests" fails, there should be an artifact called "e2e-test-screenshots" which contains a png- and an html-file (as well as a third file, which lists the failed tests)

I have successfully tested this on my fork, but I do not know how to properly test it in this repo.

### CODE REVIEW

**Comment by RCheesley** [comment]
Awesome, thanks for this @PatrickJenkner - I was only mentioning the other day to someone that it would be nice if we could expose the artifacts to the GitHub Action!

**Review by RCheesley — APPROVED** [review]
I can see and download the artifacts in the GitHub Action when the test is failing. Thanks for the PR!

**Review by escopecz — APPROVED** [review]
Lucky for us, there is the flaky test that is sometimes failing. Can see the artifact and in it is the screenshot:
Screenshot 2024-10-11 at 15 21 41
Screenshot 2024-10-11 at 15 20 52
I'll re-trigger the e2e job to see if it passes to also see the success behaviour. So far so good! 👍

**Comment by escopecz** [comment]
The e2e tests passed now and there is no artifact 👍

**Pull request merged**
