### PR TITLE
Add DDEV first-run experience 🚀

### PR DESCRIPTION
**Pull request by dennisameling**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | features
| Bug fix?                               | no
| New feature?                           | yes
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | N/A
| Related user documentation PR URL      | N/A
| Related developer documentation PR URL | ⚠️ TO DO!!!
| Issue(s) addressed                     | N/A

#### Description:

Adds a first-run experience for DDEV users.
When the user runs `ddev start` for the first time, they will be greeted with the following message:

```
$ ddev start
Do you want us to set up the Mautic instance for you with the recommended settings for DDEV?
If you answer "no", you will have to set up the Mautic instance yourself.
```

After installation, they will see some useful information to get started:

```
All done! Here's some useful information:
🔒 The default login is admin/mautic!
🌐 To open the Mautic instance, go to https://mautic.ddev.site in your browser.
🌐 To open PHPMyAdmin for managing the database, go to https://mautic.ddev.site:8037 in your browser.
🌐 To open MailHog for seeing all emails that Mautic sent, go to https://mautic.ddev.site:8026 in your browser.
🚀 Run "ddev exec composer test" to run PHPUnit tests.
🚀 Run "ddev exec bin/console COMMAND (like mautic:segments:update) to use the Mautic CLI. For an overview of all available CLI commands, go to https://mau.tc/cli
```

In the background, the following happens:
- Setup environment with PHP 7.4, Apache, Composer 1 (until Mautic 4 is released, which will add Composer 2 support)
- Install composer dependencies
- Install Mautic with user admin/mautic, API enabled, database set to db/db/db/db (DDEV default), MailHog for emails

#### Steps to test this PR:
1. Checkout this PR locally
2. Run `ddev start` (assuming you have DDEV installed)

### CODE REVIEW

**Review by RCheesley — DISMISSED** [review]
This is awesome! 1826 I started the command and by 1833 I had a fully configured Mautic instance up and running and ready for testing! 🎉 

The only thing that I noticed was:

>  - [0] The <strong>memory_limit</strong> setting in your PHP configuration is lower than the suggested minimum limit of %min_memory_limit%. Mautic can have performance issues with large datasets without sufficient memory.

^ The memory limit is seemingly not making it into the text there (and should it maybe be higher?)

Also should we inform in the output how to cleanly shut it down?

Otherwise super cool - will make testing so much easier for contributors!

Thank you!

**Comment by dennisameling** [comment]
**memory_limit**:

Fixed in https://github.com/mautic/mautic/pull/9669/commits/ab13dd6ec9dfe781df7c67d9b6250b4cfc52d7bb

The Apache memory limit is 1024M in DDEV by default:

image

The CLI has a memory limit of -1 (unlimited) though. The logic to check the PHP memory limit was, however:

```PHP
if ($memoryLimit < $suggestedLimit) {
  $messages[] = 'mautic.install.memory.limit';
}
```

-1 is "lower" than the suggested limit of 512M. Therefore I just changed the logic, so that the warning doesn't show up anymore when it's set to -1 (unlimited):

```PHP
if ($memoryLimit > -1 && $memoryLimit < $suggestedLimit) {
  $messages[] = 'mautic.install.memory.limit';
}
```

**Text issue for memory_limit warning**:
Regarding the text issue; some checks have additional arguments that are only accounted for in the HTML version of the installer:

image

If we want to fix this, it'd involve a slight restructuring of the installer logic. If you want to have this fixed, would you mind creating an issue for it @RCheesley? 😊 

**Issue with optional checks in the installer**:

When optional checks are failing in the CLI installer, it's supposed to ask `Continue with installation anyway?` if the `--force` option isn't set, but the logic was a bit flawed so that it didn't show this question. I also just fixed that in https://github.com/mautic/mautic/pull/9669/commits/ab13dd6ec9dfe781df7c67d9b6250b4cfc52d7bb.

**Shut down info**:

Just added some info about shutting down the instance in https://github.com/mautic/mautic/pull/9669/commits/4886c7c68ed7606d13e8ae8697d589c83c6ac731

**Comment by kuzmany** [comment]
I get this error. I am trying to build it as mautic3 project. I renamed project name in config.yaml

Do you see something weird? I am using ddev on wsl2 (windows subsystem 2 Ubuntu 18.04)

```
Starting mautic3...
Running   Command=ip address show dev docker0
Building db
Building web
Service 'web' failed to build : The command '/bin/sh -c apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests php7.4-imap' returned a non-zero code: 100
Failed to start mautic3: Failed to run docker-compose [-f /home/kuzmany/www/mautic3/.ddev/.ddev-docker-compose-full.yaml up --build -d], err='exit status 1', stdout='Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> 2f19a2bac03d
Step 3/6 : ARG username
 ---> Using cache
 ---> 93a4fba05515
Step 4/6 : ARG uid
 ---> Using cache
 ---> 1463e7e64712
Step 5/6 : ARG gid
 ---> Using cache
 ---> fff0274a9811
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Using cache
 ---> ebf6547e3e05

Successfully built ebf6547e3e05
Successfully tagged drud/ddev-dbserver-mariadb-10.3:v1.16.0-mautic3-built
Step 1/8 : ARG BASE_IMAGE
Step 2/8 : FROM $BASE_IMAGE
 ---> 9e6709a9d711
Step 3/8 : ARG username
 ---> Using cache
 ---> fa6e4ec6d325
Step 4/8 : ARG uid
 ---> Using cache
 ---> ef732f1336b9
Step 5/8 : ARG gid
 ---> Using cache
 ---> cdadc6571456
Step 6/8 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username")
 ---> Using cache
 ---> 821655019057
Step 7/8 : RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests php7.4-imap
 ---> Running in 00a04503d25a
Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Get:5 http://security.debian.org/debian-security buster/updates/main amd64 Packages [267 kB]
Get:6 https://deb.nodesource.com/node_14.x buster InRelease [4584 B]
Get:7 https://packages.sury.org/php buster InRelease [6771 B]
Get:8 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:9 http://nginx.org/packages/debian buster InRelease [3589 B]
Err:4 https://dl.yarnpkg.com/debian stable InRelease
  The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
Get:10 https://deb.nodesource.com/node_14.x buster/main amd64 Packages [764 B]
Get:11 https://packages.sury.org/php buster/main amd64 Packages [270 kB]
Get:12 http://nginx.org/packages/debian buster/nginx amd64 Packages [12.6 kB]
Get:13 http://packages.blackfire.io/debian any InRelease [23.3 kB]
Get:14 http://packages.blackfire.io/debian any/main amd64 Packages [3899 B]
Get:15 http://deb.debian.org/debian buster-updates/main amd64 Packages [9504 B]
Reading package lists...
W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
', stderr='Building db
Building web
Service 'web' failed to build : The command '/bin/sh -c apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests php7.4-imap' returned a non-zero code: 100'
```

**Comment by dennisameling** [comment]
@kuzmany this is a bug in DDEV that was fixed in the latest 1.16.6 release: https://github.com/drud/ddev/releases/tag/v1.16.6 😊

**Comment by kuzmany** [comment]
Works for me.

Just note:

I get error:

`bash: ./.ddev/mautic-setup.sh: /bin/bash^M: bad interpreter: No such file or directory`

I fixed it with (https://stackoverflow.com/a/29747593/12213656):

`sed -i -e 's/\r$//' ./.ddev/mautic-setup.sh`

**Review by kuzmany — DISMISSED** [review]
Works like charm 👍

**Comment by dennisameling** [comment]
> I get error:
> 
> bash: ./.ddev/mautic-setup.sh: /bin/bash^M: bad interpreter: No such file or directory

Looks like that has to do with line endings - are you on Windows @kuzmany? By default, Git for Windows converts Linux line endings (LF) to Windows line endings (CRLF) by default which seems to be causing the issue here.

Could you try it again now? Think i patched it with https://github.com/mautic/mautic/pull/9669/commits/2bf6afdd3fb9e9688abaa80ceeb50d01a2d44c24

**Pull request merged**
