### PR TITLE
Use the form results tables as report data sources

### PR DESCRIPTION
**Pull request by volha-pivavarchyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:

This PR adds an aditional types of report data sources:
image

This PR also adds a new setting to enable/disable this mode:
image

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Open the form settings and enable the `Use the form results as report data sources` setting
3. Create a new form and submit it a few times
4. Create a new report choosing a form result as the data source
5. Set the columns and filters 
6. Click the button `Save & close`
7. The report is displayed
8. Open the form settings again and disable the `Use the form results as data sources` setting
9. Try to create a new report
10. There are no form results data sources in the list
10. Open the list of reports
11. Open an existing report that uses the form results as a data source
12. The report is opened successfully, and there is only one form results data sources in the list

<a href="https://gitpod.io/#https://github.com/mautic/mautic/pull/11567"></a>

### CODE REVIEW

**Review by escopecz — COMMENTED** [review]
Nice feature! I have one objection about the code. There is a lot of form-related code in the report bundle. Can you please revisit it and either:
1. move it to the form bundle or
2. make it abstract so other bundles can use it too, not just forms?

The idea behind bundles is that it separates concerns to its own folder and they interact between each other by dispatching events. So if you remove a bundle, it will make other bundles still working and no dead code remains in the other bundles.

**Comment by RCheesley** [comment]
@volha-pivavarchyk could you take a look at the feedback above and refactor as appropriate? Thanks! 🚀

**Comment by volha-pivavarchyk** [comment]
@RCheesley @escopecz I'll try to do it soon

**Comment by TechBill** [comment]
Working as intended but debug message appears at the bottom of the form report 

Screenshot 2022-11-04 at 10 06 06 AM

**Comment by volha-pivavarchyk** [comment]
@TechBill The debug message is displayed for all reports in the dev mode. It doesn't relate to this PR.

I have changed a behavior when the `Use the form results as data sources setting` is disabled. Could you please test it again.

**Comment by volha-pivavarchyk** [comment]
@escopecz I have moved all code to the form bundle. The only thing is I have added a new property to ReportBuilderEvent to solve the problem with the display of created reports after disabling the `Use the form results as data sources` setting. What do you think about it?

**Review by escopecz — COMMENTED** [review]
Thanks! Please take a look at the failing tests. I re-triggered the failed tests in case it is a temporary failure but it failed the same way again.

**Comment by volha-pivavarchyk** [comment]
@escopecz The tests work well themself after merging.

**Review by escopecz — APPROVED** [review]
Thanks! 👍

**Pull request merged**
