### PR TITLE
Add support email and sms click segment filters and groups "behaviors" 

### PR DESCRIPTION
**Pull request by alanhartless**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | 
| New feature? | enhancement
| Automated tests included? |
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | 
| Deprecations? | 

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Description:

This adds support to segment filters for date based clicks from email or text messages. It also adds a filter for click on any link from any SMS (the feature already existed for email but updated the label). 

This PR also updates most if not all of the behavior based filters to make it clearer what the heck they do and places them in their own group in the filters dropdown.

[//]: # ( As applicable: )
#### Steps to test this PR:
1. Send an email with links
2. Click on the links from the email
3. Create a new segment with the "Clicked from an email (date)" filter and select the appropriate operator and timeframe (relative dates are supported like `-90 days`
4. Ensure your contacts are included in the segment
5. Change the filter to be outside the time you clicked and ensure the contact is removed.
6. Repeat with text messages.

Repeat with the `Clicked any link from any email` and `Clicked any link from any text message` filters.

Queries produced: 

For click period:
```
SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM (SELECT DISTINCT l.id as leadIdPrimary, tUCucvWG.lead_id AS tUCucvWG_lead_id FROM mautic_leads l LEFT JOIN mautic_lead_lists_leads tUCucvWG ON tUCucvWG.lead_id = l.id and (tUCucvWG.leadlist_id = 1) WHERE (l.id IN (SELECT UcMCVNtl.lead_id FROM mautic_page_hits UcMCVNtl WHERE (UcMCVNtl.redirect_id IS NOT NULL) AND (UcMCVNtl.lead_id IS NOT NULL) AND (UcMCVNtl.source = 'email'))) AND (tUCucvWG.lead_id IS NULL)) sss
```

For click based on date/time:
```
SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM (SELECT DISTINCT l.id as leadIdPrimary, hpflEAgJ.lead_id AS hpflEAgJ_lead_id FROM mautic_leads l LEFT JOIN mautic_lead_lists_leads hpflEAgJ ON hpflEAgJ.lead_id = l.id and (hpflEAgJ.leadlist_id = 1) WHERE (l.id IN (SELECT vImZJfoe.lead_id FROM mautic_page_hits vImZJfoe WHERE (vImZJfoe.redirect_id IS NOT NULL) AND (vImZJfoe.lead_id IS NOT NULL) AND (vImZJfoe.source = 'email') AND (vImZJfoe.date_hit >= '2018-11-24'))) AND (hpflEAgJ.lead_id IS NULL)) sss
```

### CODE REVIEW

**Comment by alanhartless** [comment]
This has been reviewed by our team in production for months so marking as pending test confirmation.

**Comment by kuzmany** [comment]
This filter doesn't work:

Set NO - Clicked any link in any email (expected contacts whose receive email but not click)
Tested here https://mautibox.com/7194/s/segments/edit/4 

image

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@alanhartless several conflicts to be resolved - unsure if this made its way into Mautic 3.0 or not!

**Comment by RCheesley** [comment]
Bumping to 3.2 due to unresolved conflicts

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by npracht** [comment]
@alanhartless any chance to have a look at that ?

**Comment by dennisameling** [comment]
Hi @alanhartless! Thanks for your PR 🚀 we just upgraded Mautic to Symfony 4 and this PR will need to be updated. Since this PR has conflicts now, could you please do a `git merge upstream/features` locally to resolve the conflicts? Thanks in advance!

**Comment by alanhartless** [comment]
Will need https://github.com/mautic/mautic/pull/8649 merged before dealing with this one to avoid further conflicts.

**Comment by alanhartless** [comment]
Part of this was absorbed into #8649 due to dependencies. The new filters originally added by this PR along with #7786 were removed in https://github.com/escopecz/mautic/commit/2cd018a59c214fe45d353e82c7dd22d249cc4b51. I'm going to close this and create a new PR based on #8649 adding back the new filters based on the new code.

**Comment by alanhartless** [comment]
https://github.com/mautic/mautic/pull/9852 re-introduces the click filters and fixes @kuzmany 's comment https://github.com/mautic/mautic/pull/7194#issuecomment-459259648

**Pull request closed without merging**
