### PR TITLE
Campaign tags

### PR DESCRIPTION
**Pull request by cykonetic**
**Please be sure you are submitting this against the _staging_ branch.**

[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | No
| New feature? | Yes 
| Automated tests included? | No
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | 
| BC breaks? | No
| Deprecations? | None

[//]: # ( Note that all new features should have a related user and/or developer documentation PR in their respective repositories. )

[//]: # ( Required: )
#### Steps to test this PR:
1. See/edit tags here https://mautibox.com/6792/s/campaigns/edit/1

### CODE REVIEW

**Comment by npracht** [comment]
Hi @cykonetic !
Thanks for contributing ! Could you please detail a bit more what this PRs offers ? How to test, screenshots, etc.

Thanks a lot.

**Comment by cykonetic** [comment]
Essentially this allows a way to arbitrarily group campaigns for reporting purposes. The only UI alteration is a new tags input on the campaign edit screen .
campaigntags

**Comment by heathdutton** [comment]
We are using this in production to help us distinguish between divisional lines (in addition to categories). It doesn't show up in the UI anywhere besides this screenshot for the time being, but in our cases it provides a way to query the data in ways we previously could not.

**Review by heathdutton — CHANGES_REQUESTED** [review]
Looks like you have unintentional css changes that aren't needed for this PR. Those are now causing conflicts. You will also want to resolve coflicts in CampaignApiController.php

**Comment by cykonetic** [comment]
Fixed

**Comment by Woeler** [comment]
I still see JS and CSS changes that don't belong to this pr.

**Comment by cykonetic** [comment]
I believe all unrelated code changes have been removed

**Comment by npracht** [comment]
Hi there!
It has been decided to not create any extra Mautic 2 minor versions (which means no more features in M2) knowing that Mautic 3 is coming very soon.

**We now want to integrate your contribution in the Mautic 3 roadmap as 3.1.0 candidate.**

## How to do?
1. Check if your feature or enhancement is still missing and relevant in Mautic 3
2. **If Yes**: rebase your PR against the 3.x branch
3. **If No**: please consider closing your PR if you are absolutely sure that the feature has made it into Mautic 3 already

**Please report results by commenting on your PR to make us administration easier.**
______
You can more information on how to do all of that on [this blog post "Getting you PR ready for Mautic 3"](https://www.mautic.org/blog/developer/getting-your-pr-ready-mautic-3).

**Comment by RCheesley** [comment]
@cykonetic I'd love to get this into 3.1 which ships at the end of August, however it looks like it needs a bit of work to get the conflicts resolved and have it work in Mautic 3.x - are you able to pick this up?

**Comment by RCheesley** [comment]
@cla-bot check

@cykonetic @heathdutton I think this would be a nice addition if we are able to address the conflicts and get this documented on github.com/mautic/mautic-documentation so that folk understand how to make use of it.

We would also need you to sign the [Contributors Agreement](https://www.mautic.org/contributor-agreement) and fix your Git config @cykonetic :) 

If we aim for 3.2 that would mean getting this resolved and ready to be tested by **Sunday, 15th November** - does that sound feasible? If not we can bump it back to 3.3 which would be looking at February 2021.

Could you let us know either way, so we can close the PR if it's not going to be actively brought forward? If we don't hear back we'll close the PR in 14 days.

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by npracht** [comment]
This is too old. i'll close it and if someone want to carry it again, then we'll re-open it with huge pleasure.

**Pull request closed without merging**
