### PR TITLE
Lead importation - multiselect fix

### PR DESCRIPTION
**Pull request by Dcoutelle**
| Q  | A
| --- | ---
| Bug fix? | Y
| New feature? | N
| Related user documentation PR URL | 
| Related developer documentation PR URL | 
| Issues addressed (#s or URLs) | https://github.com/mautic/mautic/issues/3553
| BC breaks? | N
| Deprecations? | N

[//]: # ( Required: )
#### Description:
Fix importation where there is multiselect

#### Steps to reproduce the bug:
1. create custom field named dropdown_test, with 3 option with value definied 1, 2 and 3
2. import enclosed file

#### Steps to test this PR:
1. apply PR
2. import file

[test_import.csv.txt](https://github.com/mautic/mautic/files/816695/test_import.csv.txt)

### CODE REVIEW

**Comment by npracht** [comment]
Works as expected !
Thanks !

**Comment by escopecz** [comment]
@Dcoutelle is #3547 really related to this PR? That issue seems to be related to report filters and this PR is about import.

**Review by escopecz — APPROVED** [review]
Works as described 👍

**Comment by virlatinus** [comment]
Works as described

**Pull request merged**
