### PR TITLE
TPROD-410: Remove dependency on stack/run

### PR DESCRIPTION
**Pull request by mollux**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [x]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
see https://mautic.atlassian.net/browse/TPROD-410

There is another stackPHP package: `stack/builder` that we currently still need.

That package is used for Middleware classes and still has symfony 5 support.
See https://github.com/stackphp/builder/pull/30 and The context from the Drupal community on that package: https://www.drupal.org/project/drupal/issues/3258902

#### Steps to test this PR:

1. Open this PR on Gitpod or pull down for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. code review and check if tests work

### CODE REVIEW

**Review by mabumusa1 — DISMISSED** [review]
Thanks @mollux for this, it works as expected Mautic boots, and tests are passing.

**Review by escopecz — DISMISSED** [review]
Much better. 👍  

@mollux can you resolve the conflict?

**Comment by mollux** [comment]
@escopecz conflict resolved (sha of `mautic/core-lib` in the `composer.lock` file)

**Review by escopecz — APPROVED** [review]
Thanks Mattias! 👍

**Pull request merged**
