### PR TITLE
Refactoring and Added test case for segment change event

### PR DESCRIPTION
**Pull request by dadarya0**
Thousands of anonymous contacts in segments

| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | Y
| New feature/enhancement? (use the a.x branch)      | N
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | Y 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Description:
Refactoring and Added test case for segment change event

#### Steps to test this PR:

Contact should be added/removed from segment same as earlier from form submission and point trigger

### CODE REVIEW

**Review by rohitpavaskar — APPROVED** [review]

**Comment by Galokh66** [comment]
Anonymous contact is being added to segment when a trigger action updates an anonymous contacts segment on visiting a landing page
Screenshot 2024-03-05 at 5 46 30 PM
Screenshot 2024-03-05 at 5 46 37 PM
@dadarya0

**Comment by Galokh66** [comment]
For second scenario it is working, anonymous contacts are not added to segment when a form is submitted

**Comment by npracht** [comment]
Hello @dadarya0,

I don't understand why this is a fix. If the contact, anonymous or not, meet conditions to be added to a segment (point trigger or form action), then it should go in. Why would we exclude anonymous contacts from it ?

**Review by npracht — CHANGES_REQUESTED** [review]
Hello @dadarya0,

I don't understand why this is a fix. If the contact, anonymous or not, meet conditions to be added to a segment (point trigger or form action), then it should go in. Why would we exclude anonymous contacts from it ?

**Comment by dadarya0** [comment]
> Hello @dadarya0,
> 
> I don't understand why this is a fix. If the contact, anonymous or not, meet conditions to be added to a segment (point trigger or form action), then it should go in. Why would we exclude anonymous contacts from it ?

I have updated PR description, it is just refactoring and added new test cases.

**Comment by npracht** [comment]
ah 😅
Then no issue from my side :)

**Review by Galokh66 — APPROVED** [review]

**Pull request merged**
