### PR TITLE
Focus Items: Add timeout before engage

### PR DESCRIPTION
**Pull request by kuzmany**
[//]: # ( Please answer the following questions: )

| Q  | A
| --- | ---
| Bug fix? | n
| New feature? | y
| Related user documentation PR URL | n
| Related developer documentation PR URL | n
| Issues addressed (#s or URLs) | n
| BC breaks? | n
| Deprecations? | n

[//]: # ( Required: )
#### Description:
This PR add to Focus Items new option  - Timeout before engage.
Best use case when you don't won't fire exit popup (whatever) immediately after page load.

timeout

#### Steps to test this PR:
1. Crete Focus Item with engage option and 5s timeout
2. Install Focus item to your page. 
3. Try fire you engage action before 5s. Works, If engage action fire after 5s timeout.

### CODE REVIEW

**Comment by alanhartless** [comment]
Hey @kuzmany. This is cool! Thanks for it. One thing, I think I would suggest a slightly different UI. In your screenshot, this is what I read. "Engage immediately, no never mind, let's wait 5 seconds." :-) Let's add an option back to the when to engage dropdown to be "After number of seconds." Hide the `Timeout before engage` by default and only show it when the `After number of seconds` option is chosen using the `data-show-on` feature.

**Comment by kuzmany** [comment]
@alanhartless 
Timeout options was inspirated by https://github.com/carlsednaoui/ouibounce (option Timer)
Pople want use timeout also for exit popup or scroll engagement.  This is reason why this option is still visible. Lot of vistiors open website, navigate curosr outside browser and exit popup is fired. But sometimes we want fire exit popup after timeout. 
I suggest only rename Immediatelly to Open after timeout (or Engage after timeout)
Please let me know If it's okay. 
Thank you for your time.

**Comment by alanhartless** [comment]
Ok. Gotcha. "Open after timeout" suggests that the timeout applies to that setting only and not the scroll events. How about we change the translation string for "Immediately" to "Upon arrival" or something like that?

**Comment by kuzmany** [comment]
@alanhartless commited

**Comment by alanhartless** [comment]
Works. Thanks!

**Comment by dongilbert** [comment]
+1 Thanks!

**Pull request merged**
