### PR TITLE
handle urls with unicode characters

### LINKED ISSUE #8627: Froala bug: URL with special char broke HTML
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
Create email and paste to editor/or code mode anchor with href with special chars, for example: 

`<a href="https://m3.mautibox.com/3.x/media/images/testá.png">fdsfs</a>`

image

After apply

image

image

### PR DESCRIPTION
**Pull request by mabumusa1**
| Q                                      | A
| -------------------------------------- | ---
| Branch?                                | staging
| Bug fix?                               | yes
| New feature?                           | no
| Deprecations?                          | no
| BC breaks?                             | no
| Automated tests included?              | yes
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #8627 

#### Steps to test this PR:
1. Load up [this PR](https://mautibox.com)
2.

### CODE REVIEW

**Comment by RCheesley** [comment]
Thanks for making the PR @mabumusa1 !

**Review by kuzmany — APPROVED** [review]
Tested and works properly. Thanks
Also this PR is required for this PR https://github.com/mautic/mautic/pull/8345

**Comment by mabumusa1** [comment]
@RCheesley is this ready to be merged or do we need more tests?

**Comment by RCheesley** [comment]
@mabumusa1 according to the [new code governance](https://www.mautic.org/blog/developer/update-mautic-community-code-governance-processes) a tier-1 PR requires:

- Code review from 1 core team member ✅ 
- Full testing and approval by at least one community member (could be the person doing the code review, but should not be from the same company/organisation as the person submitting the PR). (as @kuzmany is not the same company this can also be considered ✅ )

@cla-bot check also needed.

**Comment by RCheesley** [comment]
@mabumusa1 could you take a look at your git config settings per the message above? Thanks!

**Comment by RCheesley** [comment]
@cla-bot check

**Review by RCheesley — APPROVED** [review]
Confirmed the bug before applying the PR:

screenshot-local mautic3-2020 08 28-14_14_48

After applying the fix the link is correctly rendered!

screenshot-local mautic3-2020 08 28-14_16_09

**Comment by mabumusa1** [comment]
@cla-bot check

**Comment by benfavre** [comment]
This has now broken several emails by inserting white space or even line breaks in some emails.
Here is a screenshot of a space added in the middle of a html tag !
image

**Comment by kuzmany** [comment]
@benfavre After apply this patch? Can you upload theme to https://mautibox.com/staging/s/login to reproduce that issue?

**Comment by benfavre** [comment]
https://mautibox.com/staging/s/emails/view/7
Can't send emails from mauticbox, can't confirm the issue.
Good to know: Gmail is fine, outlook isn't

**Comment by benfavre** [comment]
Sorry ... No this is not related to my bug. It is related to using the adapter that is a WIP #9137

**Comment by benfavre** [comment]
Found it ! There is a maximum line length before outlook adds a \n or a whitespace ...
My email was minified and inlined to be only one single line and the aws api transport does not handle this at all

**Pull request merged**
